### PR TITLE
Change css selector from stripe elements in test environment.

### LINKED ISSUE #8951: [test ENV] Bad rendering of Stripe form
## Description

Blocks Stripe test automation for split checkout, on the card form (`/payment` step).
The credit card for is rendering incorrectly and prevents test implementation, on a staging environment.

## Expected Behavior

Rendering should be the same as in staging or production environments.

## Actual Behaviour

Currently broken, and does not allow testing.

## Steps to Reproduce

1. Visit the /payment step on a test environment; notice you can proceed to /summary despite having no or incorrect card info.
2. Visually compare with staging (below, left).

## Animated Gif/Screenshot

Peek 2022-02-23 19-46

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
In test env. we use a stripejs element mocked. Use the right selector to use it.

Closes #8951 

#### What should we test?
Green build 🟢 + review from @filipefurtad0  ;)

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
This one is pretty simple actually. 
Could be reviewed + merged by @filipefurtad0 I guess.

File: spec/support/request/stripe_helper.rb [hunk 1]
```diff
@@ -15,10 +15,9 @@ def checkout_with_stripe(guest_checkout: true, remember_card: false)
...
 
   def fill_out_card_details
-    expect(page).to have_css("input[name='cardnumber']")
-    fill_in 'Card number', with: '4242424242424242'
-    fill_in 'MM / YY', with: "01/#{DateTime.now.year + 1}"
-    fill_in 'CVC', with: '123'
+    fill_in "stripe-cardnumber", with: '4242424242424242'
+    fill_in "exp-date", with: "01/#{DateTime.now.year + 1}"
+    fill_in "cvc", with: "123"
   end
```
Comment (filipefurtad0) [inline spec/support/request/stripe_helper.rb:21]: Currently I only see this commit, which changes the helper only - necessary to make the spec pass I guess.

But in a previous version of this PR there was a change on the `app/views/shared/_stripe_js.html.haml`... With this previous change it does seem to work, tested it locally:

image

Yaay! :tada:  So, could it be this change got unintended overwritten by force-pushed or so?...

Comment (mkllnk) [reply spec/support/request/stripe_helper.rb:21]: Ideally, we don't load anything from the internet, including Stripe JS code. It's great when you can run specs while being offline and the specs don't depend on third party services. Then the specs are deterministic and a lot faster.

But as you found, the mocked version is very different to the real deal. It would be great if we could better fake the real script, record real interactions and play them back in specs. I had a go at adding [Puffing Billy](https://github.com/oesmith/puffing-billy/) to another project at some point but couldn't get it working. Maybe it's easier these days... there should be a solid solution for testing Stripe.

Comment (jibees) [reply spec/support/request/stripe_helper.rb:21]: First, I've pushed a version that actually use the online version. 
Then, I found that it triggers some others issues, and using external sources should be avoided. So, I rollbacked, and force-pushed another solution, that make the test pass. 
I don't think we want to test stripelement with this feature test: we can by default trust them. We should only test what we are responsible for. 
I agree with @mkllnk , it could be great to improve that mocked script somehow, but it could be very time consuming.

Comment (filipefurtad0) [reply spec/support/request/stripe_helper.rb:21]: > I don't think we want to test stripelement with this feature test: we can by default trust them

Ok, so in that case, we skip the test automation on this form for now - thanks for clarifying.

So the change here is to use the css selector :+1: 

Merging.

**Comment by filipefurtad0** [comment]
I've created [this spike](https://github.com/openfoodfoundation/openfoodnetwork/issues/8957) on [Puffing Billy](https://github.com/oesmith/puffing-billy/) (related to #7767), to assess it as a potential solution for testing stripe / paypal more effectively.
