### PR TITLE
Error 500 checking out with Stripe, after navigating back to the Summary page

### LINKED ISSUE #13556: Error 500 checking out with Stripe, after navigating back to the Summary page
## Description

Related to https://github.com/openfoodfoundation/openfoodnetwork/pull/13506.
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/13488.

If a customer checks out with a 3D card and - without completing authentication - then navigates back to the /summary page or leaves the cart but tries to checkout at a later stage, an error 500 is triggered; the customer needs to select another payment method to checkout or is blocked, if no other options are available.

## Expected Behavior

The customer should be able to checkout without an error 500.

## Actual Behaviour

The customer is unable to checkout and sees an error 500.

## Steps to Reproduce

1. As a customer, checkout and select Stripe with a x-3184 card.
2. Proceed to the /summary step and click Complete order -> this redirects the Stripe authentication step
3. Using your browser function, navigate back to the /summary step.
4. Click Complete order again
5. Notice the error 500 and the [redirect_auth_url](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/675c2c70e6226369c33c86b9?event_id=68d460ca014c8e96fff90000&i=sk&m=ra) error is triggered

## Animated Gif/Screenshot

User with several cards and payment methods
https://github.com/user-attachments/assets/8d57a722-d64b-4af7-8224-e38ae552df13

User with one card and payment method
https://github.com/user-attachments/assets/4d069a4b-5179-4cfa-8e89-34f3a9fb5c1c

## Workaround

Choosing another payment method.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: 5.2.5
* Browser name and version: all
* Operating System and version (desktop or mobile): all

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #13556 

This PR fixes a 500 error that occurred when handling Stripe payments requiring 3D Secure authorization. 
Previously, the `StripeScaPaymentAuthorize` service would return `nil` for any payment not in the `checkout` state. When a payment was already in the `requires_authorization` state (after initial authorization but pending 3D Secure verification), the service returned `nil`, causing a 500 error when the code attempted to extract the `redirect_auth_url` from a nil payment object.
Now, the service checks if the payment is already in the `requires_authorization` state and returns the payment object (which contains the `redirect_auth_url`) instead of `nil`, allowing the redirect to proceed correctly.

#### What should we test?

- As mentioned in the issue

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: engines/order_management/app/services/order_management/order/stripe_sca_payment_authorize.rb [hunk 1]
```diff
@@ -18,6 +18,8 @@ def initialize(order, payment: nil, off_session: false, notify_hub: false)
       end
 
       def call!(return_url = off_session_return_url)
+        # if the payment requires_authorization (3D Secure), can't be authorized again
+        return payment if payment&.requires_authorization?
```
Comment (mkllnk) [inline engines/order_management/app/services/order_management/order/stripe_sca_payment_authorize.rb:22]: I find the wording very confusing here. I would have thought that we want to call `authorize!` when it requires authorization. I'm not very familiar with this part of the code but I think that we call `authorize!` first. We can either get the authorization straight away or the gateway tells us that we require additional authorization. In that case we have to wait for the user and one of our endpoints will be called when the user gave additional authorization. Is that correct?

**Review by mkllnk — APPROVED** [review]

File: engines/order_management/app/services/order_management/order/stripe_sca_payment_authorize.rb (hunk 1 above)
Comment (chahmedejaz) [reply engines/order_management/app/services/order_management/order/stripe_sca_payment_authorize.rb:22]: > can either get the authorization straight away or the gateway tells us that we require additional authorization. In that case we have to wait for the user and one of our endpoints will be called when the user gave additional authorization. Is that correct?

Exactly @mkllnk.
This check is needed for an edge case where 3D authentication is required on the user’s end, they are redirected to the 3D auth page on Stripe, however, they navigate back to the OFN order summary page afterward.

Ideally, if the user clicks “Complete Order” again in OFN (after returning), they should be redirected back to the Stripe 3D authentication page. However, this flow fails because Stripe has already authorized the payment for that order, and a new authorization can’t be initiated until the current one is completed.

Therefore, this check ensures that if Stripe has already authorized the payment and additional user authentication is still required, we don’t start another authorization. Instead, we return the existing payment so the pending 3D authentication can be completed.

Please let me know if you have any questions. Thanks.

**Comment by filipefurtad0** [comment]
Hi @chahmedejaz ,

Awesome. This PR fixes the issue. I've tested the steps to reproduce it, namely:
- checking out with a 3DS card, till the authentication screen
- navigating back to the /summary page
- clicking place order -> redirects the customer to the 3DS authentication page

I've verified, that different payment intents are generated, when the same steps are followed and:
- the customer selects another card (both 3D and non 3D)
- the customer fails authentication, and retries checking out with the same card
- the customer fails authentication, and retries checking out with a different payment method

Looks good to go! :tada: 
Merging.
