### PR TITLE
Wraps expectation on within block

### LINKED ISSUE #9805: [Flaky] spec/system/admin/order_cycles/simple_spec.rb
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage simple order cycles
 modify the minute of a order cycle with the keyboard, check that the modifications are taken into account
     Failure/Error: expect(page).to have_content "You have unsaved changes"
       expected to find text "You have unsaved changes" in "Logged in as : margaretta@priceweber.info Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUP
S USERS Admin Order Cycles NEW SCHEDULE NEW ORDER CYCLE QUICK SEARCH INVOLVING Any Enterprise SCHEDULE Any Schedule COLUMNS NAME SCHEDULES OPEN CLOSE COORDINATOR PRODUCTS None Enterprise 1 0 variants"
     
     [Screenshot Image]: /home/maikel/code/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_simple_order_cycles_modify_the_minute_of_a_order_cycle_with
_the_keyboard__check_that_the_modifications_are_taken_into_account_378.png

     
     # ./spec/system/admin/order_cycles/simple_spec.rb:712:in `block (2 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'
     # -e:1:in `<main>'

Finished in 16.7 seconds (files took 1.59 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/system/admin/order_cycles/simple_spec.rb:704 # 
```

Locally, I got a pass rate of 97%. So difficult to reproduce but it's definitely happening on CI from time to time.

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3265236711/jobs/5367132845

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Closes #9805

The `#save-bar` or similar warnings appearing on the bottom of the page seem to account for some flaky specs. When running in headless mode, the bar is not really visible, but the assertion usually works.

One option would be to maximize the window before the assertion, with `page.windows[0].maximize`. This, however, still did not make the save bar visible.

The chosen approach was rather to "guide" capybara into the the `#save-bar` element, and look for the content within.

Got `100 of 100 passed (100%)` locally :green_circle: 

#### What should we test?

Green build.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Thanks @filipefurtad0, good catch!

**Comment by filipefurtad0** [comment]
Thank you, let's hope it holds :crossed_fingers:

File: spec/system/admin/order_cycles/simple_spec.rb [hunk 1]
```diff
@@ -714,7 +714,9 @@
     input = find(".flatpickr-calendar.open .flatpickr-minute")
     input.send_keys datetime.strftime("%M").to_s.strip
     input.send_keys :enter
-    expect(page).to have_content "You have unsaved changes"
+    within "#save-bar" do
+      expect(page).to have_content "You have unsaved changes"
+    end
```
Comment (mkllnk) [inline spec/system/admin/order_cycles/simple_spec.rb:719]: The additional `within` can add a bit of execution time, like a sleep, but it probably doesn't do much about the flakiness.

Comment (filipefurtad0) [reply spec/system/admin/order_cycles/simple_spec.rb:719]: Agree. It was not a ground-breaking change, but I thought we could solve it since the issue seems to be about the synchrony between the appearing of the #save-bar and the assertion.

I've tried `wait_until` in https://github.com/openfoodfoundation/openfoodnetwork/pull/9919 . Looks stable locally, but so did the other attempts...
