### PR TITLE
fix content moving when cart is open

### LINKED ISSUE #5916: [mobile ux] View cart makes the page content move to the right by a few pixels
## Expected Behavior
When the cart opens, no matter which page you're on, the body content stays exactly where it is.

## Actual Behaviour
When the cart opens, no matter which page you're on, the body content moves to the right by a few pixels and then moves back to the original place. 

## Animated Gif/Screenshot
https://www.loom.com/share/8228c59980f842729bfcd754caa7f1e4

## Workaround
n/a

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
**bug-s4: it's annoying, but you can use it**
bug-s5: we can live with it, only a few users impacted

## Your Environment
This occurs on Mac + Chrome/Safari and Windows 10 + Chrome

### PR DESCRIPTION
**Pull request by guidoDutra**
#### What? Why?

Closes #5916 

This is the simplest solution I found. The advantage is that it keeps the whole content from shifting (including static content like the header, footer and background), however the scrollbar stays visible, although inactive. Please let me know if this is ok!

#### What should we test?
Test whether there is any content shift when toggling the cart menu, both in mobile and desktop

#### Release notes
Prevented content from shifting when toggling cart menu

Changelog Category: User facing changes

### CODE REVIEW

File: app/assets/javascripts/darkswarm/directives/body_scroll.js.coffee [hunk 1]
```diff
@@ -4,6 +4,12 @@ Darkswarm.directive "bodyScroll", ($rootScope, BodyScroll) ->
...
+        document.body.style.top = "-#{window.scrollY}px"
+        document.body.style.position = 'fixed'
+        document.body.style.overflowY = 'scroll'
       else
-        elem.removeClass "disable-scroll"
+        scrollY = parseInt(document.body.style.top)
+        document.body.style.position = ''
+        document.body.style.top = ''
+        document.body.style.overflowY = ''
+        window.scrollTo(0, scrollY * -1) if scrollY
```
Comment (guidoDutra) [inline app/assets/javascripts/darkswarm/directives/body_scroll.js.coffee:15]: Is it appropriate to keep this code here? Or should I consider instead moving it to `cart_dropdown_controller` and remove the `body_scroll` directive? Also is it ok to use `document.body` straight up? Please let me know if there is any coffeescript styling related notes as well!

Comment (jibees) [reply app/assets/javascripts/darkswarm/directives/body_scroll.js.coffee:15]: - No strong opinion about keeping such a thing or move to `cart_dropdown_controller`, so why not keeping in here?
- I do not see any drawbacks about using `document.body` straight up, so perfect!

Anyway, thanks a lot ;)

**Review by jibees — APPROVED** [review]
Looks good to me: thanks! 🙏

File: app/assets/javascripts/darkswarm/directives/body_scroll.js.coffee [hunk 2]
```diff
@@ -4,6 +4,12 @@ Darkswarm.directive "bodyScroll", ($rootScope, BodyScroll) ->
   link: (scope, elem, attrs) ->
     $rootScope.$on "toggleBodyScroll", ->
       if BodyScroll.disabled
-        elem.addClass "disable-scroll"
+        document.body.style.top = "-#{window.scrollY}px"
+        document.body.style.position = 'fixed'
+        document.body.style.overflowY = 'scroll'
       else
-        elem.removeClass "disable-scroll"
+        scrollY = parseInt(document.body.style.top)
```
Comment (mkllnk) [inline app/assets/javascripts/darkswarm/directives/body_scroll.js.coffee:11]: The `* -1` should probably be in this line because there is no negative scroll.

**Review by mkllnk — COMMENTED** [review]
Nice! The solution looks great. Very simple. But my browsers don't seem to like it when the screen is a bit wider. I tested this in Firefox ESR and Chromium:
ofn-page-jump2

**Comment by guidoDutra** [comment]
> Nice! The solution looks great. Very simple. But my browsers don't seem to like it when the screen is a bit wider. I tested this in Firefox ESR and Chromium:
> ofn-page-jump2

Will check this out later today, thanks!

File: app/assets/javascripts/darkswarm/directives/body_scroll.js.coffee (hunk 2 above)
Comment (guidoDutra) [reply app/assets/javascripts/darkswarm/directives/body_scroll.js.coffee]: this has been addressed in last commit

**Comment by guidoDutra** [comment]
> Nice! The solution looks great. Very simple. But my browsers don't seem to like it when the screen is a bit wider. I tested this in Firefox ESR and Chromium:
> ofn-page-jump2

Just fixed. Its working on firefox and chome on my machine, please let me know if its working on your side now @mkllnk

**Review by mkllnk — APPROVED** [review]
Nice! That's much better. Thank you.

I did find a little regression but I think that it's better than before. Now, when you open the cart, it always displays a scroll bar even when it's not needed and wasn't there before:
ofn-page-jump-without-scroll

Since we have a big footer, this is quite rare. The only page really affected is the map. The map actually worked before (no scrollbar) and jumps now. All other pages (with scrollbar) don't jump any more. :+1: 

Do you have an idea how to solve the case without scrollbar?

**Comment by guidoDutra** [comment]
> Nice! That's much better. Thank you.
> 
> I did find a little regression but I think that it's better than before. Now, when you open the cart, it always displays a scroll bar even when it's not needed and wasn't there before:
> ofn-page-jump-without-scroll
> 
> Since we have a big footer, this is quite rare. The only page really affected is the map. The map actually worked before (no scrollbar) and jumps now. All other pages (with scrollbar) don't jump any more. 
> 
> Do you have an idea how to solve the case without scrollbar?

It might me possible to check whether the page itself is overflowing (if it has a scrollbar) and only apply the fix if so. I'll look into it today or tomorrow. Thanks!

**Review by mkllnk — APPROVED** [review]
This is excellent. Thank you! :tada:

**Comment by filipefurtad0** [comment]
Hello @guidoDutra - welcome!! :tada: 

Thank you for addressing this - and @mkllnk for all the testing :pray: 

I had another look at this and it looks great on desktop, both for Firefox and Chrome, (videos below are for FF):

Peek 2021-04-01 12-49

This works fine on mobile as well (vertical format, iPhone 12/Safari):

Peek 2021-04-01 13-02

and horizontal format:
Peek 2021-04-01 13-13

Ready to go!!
