### PR TITLE
limit users who can update shipping/payment method of an order cycle

### LINKED ISSUE #10462: Hub's suppliers can control shipping/payment methods for hub's order cycle
## Description
Suppliers/producers who are added to a hub's order cycle can check or uncheck the shipping and payment methods associated with that order cycle without any permissions given by the owner of the order cycle

## Expected Behavior

1. producer gives "add to order cycle" permissions to hub
2. hub adds producer to order cycle
3. producer can change which of their products do and don't show up in "incoming products" in hub order cycle and nothing else

## Actual Behaviour

1. producer gives "add to order cycle" permissions to hub
2. hub adds producer to order cycle
3. producer can change which of their products do and don't show up in "incoming products" (no problem)
4. producer can also change check ad uncheck shipping and payment methods for the whole order cycle

## Steps to Reproduce

1. As a producer,  give "add to order cycle" permissions to a hub account
2. With the hub account, add that producer to an order cycle
3. As the  producer go to /admin/order_cycles/ and change which shipping and payment methods are associated with order cycle and click "save".

## Animated Gif/Screenshot

image

## Workaround
None

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login or
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used:
* Browser name and version: Chrome Version 110.0.5481.104 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Chromebook and Windows laptops

## Possible Fix
wish I could help here sorry

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #10462

#### What should we test?

Some of the scenarios that I can think about:

- Access the edit order cycle => checkout options
- As an admin or coordinator, you should be able to edit the shipping methods/payment methods of any distributor
- As a distributor, 
    - you should be able to only update your shipping methods/payment methods.
    - you should not be able to edit other distributors' checkout options
- As a supplier, you should not be able to edit checkout options

Additional:
- As a coordinator and a distributor at the same time, you should be able to edit any distributor's checkout options.
- As a coordinator and a supplier at the same time, you should be able to edit any distributor's checkout options.
- As a supplier and a distributor at the same time, you should be able to edit any distributor's checkout options.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/services/order_cycle_form.rb [hunk 1]
```diff
@@ -160,4 +183,41 @@ def removed_schedule_ids
...
+  def can_update_selected_payment_methods?
+    @user.admin? || coordinator? || distributor?
+  end
+
+  def can_update_selected_shipping_methods?
+    @user.admin? || coordinator? || distributor?
+  end
+
+  def coordinator?
+    @user.enterprises.include?(@order_cycle.coordinator)
```
Comment (abdellani) [inline app/services/order_cycle_form.rb:196]: Is this Ok ? or Does the user have to be the owner of the enterprise?

File: app/services/order_cycle_form.rb [hunk 2]
```diff
@@ -160,4 +183,41 @@ def removed_schedule_ids
...
   end
+
+  def can_update_selected_payment_methods?
+    @user.admin? || coordinator? || distributor?
+  end
+
+  def can_update_selected_shipping_methods?
+    @user.admin? || coordinator? || distributor?
+  end
+
```
Comment (rioug) [inline app/services/order_cycle_form.rb:194]: As far as I can see these two methods are doing the same thing, maybe they can be combined : 
```ruby
def can_update_selected_payment_or_shipping_methods?
    @user.admin? || coordinator? || distributor?
end
```

File: spec/services/order_cycle_form_spec.rb [hunk 3]
```diff
@@ -260,7 +331,7 @@
           form = OrderCycleForm.new(
             order_cycle,
             { selected_distributor_payment_method_ids: [distributor_payment_method_ii.id] },
-            order_cycle.coordinator
+            order_cycle.coordinator.users.first
           )
```
Comment (rioug) [inline spec/services/order_cycle_form_spec.rb:335]: I am a bit confused by this, was the spec wrong before your fix ?

**Review by rioug — CHANGES_REQUESTED** [review]
My understanding of order cycle is a bit limited, but as far as I understand it looks good :+1: . I just left a comment for some minor changes.

**Comment by rioug** [comment]
Re reading the bug report, I am wondering if we should do some UX changes as well. Maybe we should hide/disable any payment/shipping methods you are not allowed to change. ie :

- As a distributor,
  - you should only be able to select your shipping methods/payment methods.
  - you should see other shipping methods/payment methods as disabled
  - you should be able to only update your shipping methods/payment methods.
  - you should not be able to edit other distributors' checkout options

- As a supplier, 
  - you should not be able to edit checkout options
  - you should see shipping methods/payment methods as disabled

**Comment by mkllnk** [comment]
@lauriewayne What do you think about those additional suggestions? Maybe they can be many little papercuts.

**Review by mkllnk — APPROVED** [review]
Wow, this is a bit complicated. I'm happy to get this through as soon as possible to fix the bug. But it also looks like we could improve a few things (tech debt). As Gaetan said, we probably want to change the UX as well and put this permissions logic into a separate service to be re-used.

File: spec/services/order_cycle_form_spec.rb (hunk 3 above)
Comment (mkllnk) [reply spec/services/order_cycle_form_spec.rb:335]: Good question. It looks like it was wrong. The form expects a user and, confusingly, the *coordinator* is an enterprise, not a person.

@abdellani It's best to change these things in a separate commit and explain why you are doing this. Then this question doesn't come up in the review.

**Comment by lauriewayne** [comment]
Thanks all, I appreciate your creativity, collaboration, and attention to this. I agree that the UX changes could be papercuts in the future and for now if an adventurous supplier is not able to innocently derail a hub's order cycle, that seems like a big win.  Heart emoji!

File: app/services/order_cycle_form.rb (hunk 1 above)
Comment (dacook) [reply app/services/order_cycle_form.rb:196]: I think this is right. Either the owner or any other users (aka "admins" or "managers") of the coordinator enterprise can be considered a "coordinator". 
FYI an owner is always a user thanks to `User#ensure_owner_is_manager`.

File: app/services/order_cycle_form.rb [hunk 4]
```diff
@@ -61,14 +61,29 @@ def apply_exchange_changes
...
 
   def attach_selected_distributor_shipping_methods
     return if @selected_distributor_shipping_method_ids.nil?
 
-    order_cycle.selected_distributor_shipping_method_ids = selected_distributor_shipping_method_ids
+    if distributor_only?
+      shipping_method_ids = order_cycle.selected_distributor_shipping_method_ids
+      shipping_method_ids -= user_distributor_shipping_method_ids
+      shipping_method_ids += user_only_selected_distributor_shipping_method_ids
+      order_cycle.selected_distributor_shipping_method_ids = shipping_method_ids
```
Comment (dacook) [inline app/services/order_cycle_form.rb:82]: To understand this requires a bit more context, so I suggest a comment such as:

```suggestion
      # A distributor can only update methods associated with their own
      # enterprise, so we load all previously selected methods, and replace
      # only the distributor's methods with their selection (not touching other
      # distributor's methods).
      shipping_method_ids = order_cycle.selected_distributor_shipping_method_ids
      shipping_method_ids -= user_distributor_shipping_method_ids
      shipping_method_ids += user_only_selected_distributor_shipping_method_ids
      order_cycle.selected_distributor_shipping_method_ids = shipping_method_ids
```

File: app/services/order_cycle_form.rb (hunk 2 above)
Comment (dacook) [reply app/services/order_cycle_form.rb:194]: Agreed with above ^

File: spec/services/order_cycle_form_spec.rb [hunk 5]
```diff
@@ -223,22 +223,93 @@
...
-          distributor_payment_method = create(
-            :payment_method,
-            distributors: [distributor]
-          ).distributor_payment_methods.first
-          order_cycle = create(:distributor_order_cycle, distributors: [distributor])
+        let!(:distributor){ create(:distributor_enterprise) }
+        let!(:payment_method){ create(:payment_method, distributors: [distributor]) }
+        let!(:payment_method2){ create(:payment_method, distributors: [distributor]) }
+        let!(:distributor_payment_method){ payment_method.distributor_payment_methods.first }
+        let!(:distributor_payment_method2){ payment_method2.distributor_payment_methods.first }
```
Comment (dacook) [inline spec/services/order_cycle_form_spec.rb:230]: It looks like these variables point to the same payment methods in the two lines above, and seem unnecessary. Can't the specs refer to `payment_method` and `payment_method2`?

File: spec/services/order_cycle_form_spec.rb [hunk 6]
```diff
@@ -223,22 +223,93 @@
...
+            form = OrderCycleForm.new(
+              order_cycle,
+              { selected_distributor_payment_method_ids: [distributor_payment_method.id] },
+              supplier.users.first
+            )
+
+            expect(form).not_to receive(:attach_selected_distributor_payment_methods)
+            expect(order_cycle.distributor_payment_methods).to match_array [
+              distributor_payment_method, distributor_payment_method2
+            ]
```
Comment (dacook) [inline spec/services/order_cycle_form_spec.rb:261]: This is testing that the value didn't change, but the spec doesn't define the initial value. I think a better way is simply:

```suggestion
            expect{ form.save }.not_to change{ order_cycle.distributor_payment_methods }
```

Comment (dacook) [reply spec/services/order_cycle_form_spec.rb:261]: By the way, it looks like you forgot to call `form.save`, so I think this test would never fail! 
It's a good idea to make the spec fail to confirm that it actually tests the code right. Sometimes I comment-out part of the program code to break it and check that the spec fails. It's important to remember the order: red > green > refactor (but i still forget sometimes too).

File: spec/services/order_cycle_form_spec.rb [hunk 7]
```diff
@@ -223,22 +223,93 @@
...
-          order_cycle = create(:distributor_order_cycle, distributors: [distributor])
+        let!(:distributor){ create(:distributor_enterprise) }
+        let!(:payment_method){ create(:payment_method, distributors: [distributor]) }
+        let!(:payment_method2){ create(:payment_method, distributors: [distributor]) }
+        let!(:distributor_payment_method){ payment_method.distributor_payment_methods.first }
+        let!(:distributor_payment_method2){ payment_method2.distributor_payment_methods.first }
+        let!(:supplier){ create(:supplier_enterprise) }
+        context "the submitter is a coordinator" do
+          it "saves the changes" do
+            order_cycle = create(:distributor_order_cycle, distributors: [distributor])
```
Comment (dacook) [inline spec/services/order_cycle_form_spec.rb:234]: Just a general comment: all the specs below are _assuming_ that this order cycle has started with the default selection including both payment methods.
This has potential to break if this default ever changed. So I would probably set up the payment method selection explicitly before the test, or simply just test the changes as in my suggestion below.

**Review by dacook — CHANGES_REQUESTED** [review]
This looks good and I think solves the bug, great! 💪 

While reviewing, I had to play with it a bit to understand, and noticed that we already disable checkboxes that the distributor doesn't have access to (pictured below). I wonder if it would have been simpler to do the same disable for producer users.
Screen Shot 2023-02-23 at 11 51 13 am

Anyway, this is robust and worth keeping, but with some modifications suggested.

_Edit_:  I just saw the above comments which have already mentioned this. I think most of the suggested changes are optional tech-debt improvements given the severity of this bug. But I double-checked and the specs that don't call `form.save` are faulty and I think **should be fixed as per the review comment**.

File: app/services/order_cycle_form.rb (hunk 4 above)
Comment (abdellani) [reply app/services/order_cycle_form.rb:84]: This is better

File: spec/services/order_cycle_form_spec.rb (hunk 5 above)
Comment (abdellani) [reply spec/services/order_cycle_form_spec.rb:230]: oh, yes that's correct they're pointing to the same payment method.

File: spec/services/order_cycle_form_spec.rb (hunk 6 above)
Comment (abdellani) [reply spec/services/order_cycle_form_spec.rb:261]: Good idea to use `change`.
I'll use it in all my test cases.

File: spec/services/order_cycle_form_spec.rb (hunk 7 above)
Comment (abdellani) [reply spec/services/order_cycle_form_spec.rb:234]: Yes, this is correct. If the Order Cycle creator doesn't select any payment/shipping methods, all the methods supported by the distributor will be [selected by default](https://github.com/openfoodfoundation/openfoodnetwork/issues/9873#issuecomment-1311537654).

Do you want me to set the payment methods explicitly?

File: spec/services/order_cycle_form_spec.rb (hunk 3 above)
Comment (abdellani) [reply spec/services/order_cycle_form_spec.rb:335]: done

File: spec/services/order_cycle_form_spec.rb (hunk 7 above)
Comment (dacook) [reply spec/services/order_cycle_form_spec.rb:235]: It's probably not necessary this time, just something to consider next time.

File: spec/services/order_cycle_form_spec.rb [hunk 8]
```diff
@@ -271,22 +342,90 @@
...
-            order_cycle,
-            { selected_distributor_shipping_method_ids: [distributor_shipping_method.id] },
-            order_cycle.coordinator
-          )
+            expect(form.save).to be true
+            expect(order_cycle.distributor_shipping_methods).to eq [distributor_shipping_method]
+          end
+        end
+        context "submitter is a supplier" do
+          it "doesn't save the changes" do
```
[the remark this answers is not in the document]
Comment (dacook) [reply spec/services/order_cycle_form_spec.rb:366]: I just tried to implement a `change` block, but can't get it to fail. `order_cycle.distributor_shipping_methods` seems to be changing after `OrderCycleForm.new`, which is weird, because it shouldn't change until `form.save`. 

I'm obviously not seeing things right so I'll hand back to you.

**Review by dacook — CHANGES_REQUESTED** [review]
Thanks for updating that, it looks good. But I just noticed a couple more that haven't been updated yet.

**Review by rioug — APPROVED** [review]

File: spec/services/order_cycle_form_spec.rb [hunk 9]
```diff
@@ -271,22 +342,90 @@
...
+                distributor.users.first
+              )
+
+              expect(form.save).to be true
+              expect(order_cycle.distributor_shipping_methods).to eq [distributor_shipping_method]
+            end
+          end
+          context "can't update other distributors' shipping methods" do
+            let(:distributor2){ create(:distributor_enterprise) }
+            it "doesn't save the changes" do
```
[the remark this answers is not in the document]
Comment (abdellani) [reply spec/services/order_cycle_form_spec.rb:423]: Sorry, I didn't notice that I only fix the part related to the payment method.

I fixed the remaining part now.

File: spec/services/order_cycle_form_spec.rb (hunk 8 above)
[the remark this answers is not in the document]
Comment (abdellani) [reply spec/services/order_cycle_form_spec.rb:369]: This is weird. There could be another problem that we overlooked. 
Can you please share the code?

[the remark this answers is not in the document]
Comment (dacook) [reply spec/services/order_cycle_form_spec.rb:369]: I can see it's updated with `form.save`.  I checked out the latest code and figured out how to make it fail: I made `can_update_selected_payment_or_shipping_methods?` return `true` and it fails, which seems right.

All good!

**Review by dacook — APPROVED** [review]
Approved with updated specs 👍

**Comment by drummer83** [comment]
# This is work in progress ...

Expected Behavior

    producer gives "add to order cycle" permissions to hub
    hub adds producer to order cycle
    producer can change which of their products do and don't show up in "incoming products" in hub order cycle and nothing else


    As an admin or coordinator, you should be able to edit the shipping methods/payment methods of any distributor
    As a distributor,
        you should be able to only update your shipping methods/payment methods.
        you should not be able to edit other distributors' checkout options
    As a supplier, you should not be able to edit checkout options


Some of the scenarios that I can think about:

    Access the edit order cycle => checkout options
    As an admin or coordinator, you should be able to edit the shipping methods/payment methods of any distributor
    As a distributor,
        you should be able to only update your shipping methods/payment methods.
        you should not be able to edit other distributors' checkout options
    As a supplier, you should not be able to edit checkout options

Additional:

    As a coordinator and a distributor at the same time, you should be able to edit any distributor's checkout options.
    As a coordinator and a supplier at the same time, you should be able to edit any distributor's checkout options.
    As a supplier and a distributor at the same time, you should be able to edit any distributor's checkout options.

### Test setup
- Coordinator: Konrad Producer Hub (Tax)
- Suppliers: Konrad Producer Hub (Tax) & The test producer shop
- Distributors: Konrad Producer Hub (Tax) & External Non-Producer Hub 1
- Permissions:
image
image

- Managers:
  - Konrad Producer Hub (Tax): enterprises@k... & producer@k...
  - The test producer shop: staging_uk@k...
  - External Non-Producer Hub 1: non-producer@k... & producer@k...

### Results BEFORE staging
| User | Supplier | Coordinator | Distributor | Manager of Distributor | Super Admin |
| - | - | - | - | - | - |
| Can edit general settings (step 1) | no ✔️ | yes ✔️ | no ✔️ | no ✔️ | yes ✔️ | 
| Can change incoming products (step 2) | own ✔️ | any ✔️ | no ✔️ | no ✔️ | any ✔️ |
| Can change outgoing products (step 3) | no ✔️ | any ✔️ | own distribution ✔️ | managed distribution ✔️ | any ✔️ | 
| Can edit checkout options (step 4) | any :x: | any ✔️ | any :x: | any :x: | any ✔️ |

# To be continued

**Comment by drummer83** [comment]
Hi @abdellani,
Thanks for fixing this s2! I got carried away while testing, but I can confirm, that 
- suppliers can't change any checkout options
- coordinators can change all checkout options
- distributors can change their own checkout options
- managers of distributors can change checkout options of their managed enterprise
- super admin can change all checkout options

Thanks again! This one has been merged now! 🚀
