### PR TITLE
Orders page inaccessible as superadmin (error 504)

### LINKED ISSUE #13416: Orders page inaccessible as superadmin (error 504)
## Description

The orders page is not accessible when logged in with a superadmin profile.

## Expected Behavior

The orders page should be accessible when logged in with a superadmin profile.

## Actual Behaviour

The orders page is not accessible when logged in with a superadmin profile.

## Steps to Reproduce

1. Log in as superadmin
2. Visit `/admin/orders`
3. See the slug - error 504 on the console -> staging-FR

## Animated Gif/Screenshot

Image

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v.5.1.3
* Browser name and version: Firefox 140.0.4
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

Likely related to https://github.com/openfoodfoundation/openfoodnetwork/pull/13338, only change on this weeks' release.

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #13416

This change introduces special handling for admin users when checking order and line item permissions. Previously, all users—including admins—relied on complex join queries to determine access to orders editable by producers. Those are needed for regular users. However, admin users should inherently have full access to all orders and line items, regardless of producer or distributor relationships.
To simplify and optimize this case, the logic has been updated so that admin users bypass these joins entirely and are granted full access directly. This improves both performance and correctness of permission handling for admins.

#### What should we test?

- As mentioned in the issue

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/controllers/admin/bulk_line_items_controller.rb [hunk 1]
```diff
@@ -88,5 +88,27 @@ def order_permissions
     def page
       params[:page] || 1
     end
+
+    def line_items_search_query
+      query = params.permit(q: {}).to_h[:q] || {}
+
+      search_fields_string = [
+        spree_current_user.admin? ? "order_distributor_name" : "order_distributor_name_alias",
```
Comment (chahmedejaz) [inline app/controllers/admin/bulk_line_items_controller.rb:96]: This change is necessary because admin users are allowed to view all orders without any filtering based on enterprise permissions. As a result, the query for admins is much simpler and the default order distributor ransacker works in this case.

On the other hand, non-admin users can only view orders from enterprises they manage or where their products are present. This filtering requires multiple joins across the enterprise table and related associations. To support filtering by distributor name in such cases, a custom ransacker is needed — and applied specifically for non-admin users.

To support this conditional ransacker usage, `search_query` key has been moved from frontend to backend.

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz,

I've restarted the server, and was able to stage the PR. A preliminary test shows the orders page now renders, this confirms the performance improvement :tada: 

image

File: app/services/permissions/order.rb
Comment (rioug) [inline app/services/permissions/order.rb:1]: The change looks good, but if I am not mistaken it's not really covered by our specs, or at least I doesn't look like the scenario with an admin user is cover. Could you double check that ?

**Review by rioug — CHANGES_REQUESTED** [review]

File: app/services/permissions/order.rb
Comment (chahmedejaz) [reply app/services/permissions/order.rb:1]: Thanks @rioug - I think the following file covers the admin features of the orders page:
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/system/admin/orders_spec.rb

The following folder covers the non-admin user features of the orders page:
https://github.com/openfoodfoundation/openfoodnetwork/tree/master/spec/system/admin/orders/having_producer_products.

The final result of the previous and current implementations won't differ, as admins have been seeing the same results with both current and previous implementations. The PR improves the overall performance of the admin orders page and doesn't impact any user-facing changes.  
Please let me know if anything is missing. Thanks

Comment (rioug) [reply app/services/permissions/order.rb:1]: Thanks for the clarification :pray:

**Review by rioug — APPROVED** [review]

**Comment by rioug** [comment]
Everyone else is on holidays, so we won't get another review any time soon, moving to test.

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz ,

I've compared a few page reloads from the orders page, as superadmin:

1) before this PR - with the previous release, before the regression (v5.1.2):

image

2) before this PR - with master / latest release (v5.1.3):

-> server timeout error 504 Gateway error

After this PR:

image

We can see that these values lower for this PR (from ~28 sec. to ~26 sec., two seconds less). A sanity test around the app spotted no other regressions.

Awesome work @chahmedejaz !
Merging.
