### PR TITLE
Admin, Edit customer details for an order: when changing to another customer, update `customer_id` as well

### LINKED ISSUE #10717: BO orders: changing customer does not update customer_id
## Description

Spotted [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/10624#issuecomment-1512453770).

When creating a BO order, selecting an existing customer associates a `customer_id` with the order being created.

If this is done a second time, then, the email and addresses will be updated (as seen in the UI) but the `customer_id` will not be updated.

This creates a mismatch between the email/addresses and the `customer_id`.

## Expected Behavior

Edit: When creating an order in the BO, a second customer selection should update the `customer_id` on the `order`.

## Actual Behaviour

Edit: When creating an order in the BO, a second customer selection does not updated the `customer_id` on the `order`.

## Steps to Reproduce

1 go to the admin dashboard -> order -> new order
2. select distributor and order cycle
3. click on next
4. select a customer, C1 for example
5. Notice that the email and the addresses will be loaded
6. completed the missing data
7. click on update
8. Select another customer: C2 for example
9. Notice that the email and the addresses will be updated
10. click on update
11. The email and the addresses will be updated, but the customer id will not be replaced! the order will always refer to C1 on the database.

## Animated Gif/Screenshot

For the order below:

image

```

openfoodnetwork=> select email, customer_id from spree_orders where number = 'R228047701';
             email             | customer_id 
-------------------------------+-------------
 filipefurtado+treec@gmail.com |        8180
(1 row)

openfoodnetwork=> select email,id from customers where id = 8180;
              email              |  id  
---------------------------------+------
 filipefurtado+almondc@gmail.com | 8180
```

## Severity

I'm not fully aware of all the impact this may have, but I can imagine inconsistencies in reporting.

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.3.3
* Browser name and version: Firefox 111
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10717 

Submitting the customer_id params in the request makes the customer_id to be updated by the controller. 

I'm not sure about the consequences of that change. 

#### What should we test?
From original issue:

1 go to the admin dashboard -> order -> new order
2. select distributor and order cycle
3. click on next
4. select a customer, C1 for example
5. Notice that the email and the addresses will be loaded
6. completed the missing data
7. click on update
8. Select another customer: C2 for example
9. Notice that the email and the addresses will be updated
10. click on update
11. The email and the addresses will be updated, but the customer id will not be replaced! the order will always refer to C1 on the database.

I'm not sure, but maybe it's fine to test https://github.com/openfoodfoundation/openfoodnetwork/pull/9710 also... (I've seen some code responsible to find associate customer to order modified in this PR ; it might be worth testing again...)

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by dacook — APPROVED** [review]
Makes sense to me, good fix.

File: spec/system/admin/order_spec.rb [hunk 1]
```diff
@@ -143,6 +143,37 @@ def new_order_with_distribution(distributor, order_cycle)
...
+    it "set the right customer attached to the order" do
+      expect(Spree::Order.last.reload.customer).to eq customer2
+    end
+
+    it "when changing the attached customer,"\
+       "it should update the order customer (not only its details)" do
+      tomselect_search_and_select customer3.email, from: 'customer_search_override'
+      expect do
+        click_button 'Update'
+        expect(page).to have_field 'order_email', with: customer3.email
```
Comment (rioug) [inline spec/system/admin/order_spec.rb:172]: It looks weird to me having an `expect` wrapped in an `expect`, but I am not sure how to the same without duplicating code.

**Review by rioug — APPROVED** [review]

**Review by rioug — APPROVED** [review]
I left a comment, but nothing blocking the PR. Nice one :+1:

**Comment by drummer83** [comment]
Hi @jibees,
Thanks for working on this one!

## Before staging
Here are three orders:
1. created in shopfront by customer kunde@...
2. created in shopfront by customer kunde2@...
3. created in back office selecting kunde@... first and then switching to kunde2@...

1 and 2 are clear and for reference only.

Regarding order no. 3 (first line):

BEFORE clicking update for the FIRST time, no customer is selected in the database:
image

AFTER clicking update for the FIRST time, the customer kunde@... is added in the database, email, user_id and customer_id are identical to the shopfront order:
image

AFTER selecting kunde2@... as customer and clicking update for the SECOND time, email and user_id are switched to kunde2@..., but customer_id is still the previous value:
image

I have also tried what happens if you simply change the email address of an existing order on the customer details page.
image
In this case, again email and user_id are updated, but all the address information and the customer_id remain the previous values:
image

## After staging
Before creating the order we can see the previous orders only:
image

BEFORE clicking update for the FIRST time, no customer is selected in the database:
image

AFTER clicking update for the FIRST time, the customer kunde@... is added in the database, email, user_id and customer_id are identical to the shopfront order (see before staging):
image

AFTER selecting kunde2@... as customer and clicking update for the SECOND time, email and user_id are switched to kunde2@..., **and customer_id is updated as well**:
image

I have also tried what happens if you simply change the email address of an existing order on the customer details page. 
In this case, again email and user_id are updated, but all **the address information and the customer_id remain the previous values**:
image

I have also tested #9710 again. Still looking good. :+1: 

## Results
- The issue #10717 seems to be solved. :heavy_check_mark: 
- #9710 still seems to be ok. :heavy_check_mark: 
- I wonder if changing the email address on the customer details page shouldn't update the customer_id as well, not just user_is and email? But this is clearly out of scope here. :question: 

I think this one is ready to get merged. :rocket: 
Thanks again! :partying_face:
