### PR TITLE
fix Snail when setting "0" in the unit value field 

### LINKED ISSUE #10100: [Product->Create] Snail when setting "0" in the unit value field
## Description
An error 500 occurs when creating a new product and putting "0" in the unit value field. 

## Expected Behavior
There should be an error message displayed to the user, such as:
"1 error prohibited this record from being saved:  Unit value must be greater than 0."

## Actual Behaviour
The user gets the 500 error page

The failing request is:
POST | https://coopcircuits.fr/admin/products
500 Internal Server Error

## Steps to Reproduce
1. Create a new product (admin/products/new)
2. Fill in the required fields, choose a unit, and set "0" in the "value" field
3. See that for "item" unit you get the error, for any other unit you get the snail

## Animated Gif/Screenshot
Dec-05-2022 16-51-09

## Workaround
Don't put 0. 

## Severity
bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #10100

#### What should we test?

- Try to create a product with unit value = 0

#### Release notes

Changelog Category:  Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by abdellani** [comment]
I don't know why some tests expect `Product.unit_value` to equal true.
I think that it doesn't make sense because `Variant.unit_value` is a float.
This also happens on the products cloner.

File: app/models/spree/product.rb [hunk 1]
```diff
@@ -53,7 +53,7 @@ class Product < ApplicationRecord
     validates :name, presence: true
 
     validates :variant_unit, presence: true
-    validates :unit_value, presence:
+    validates :unit_value, numericality: { greater_than: 0 }, allow_nil: true, presence:
       { if: ->(p) { %w(weight volume).include?(p.variant_unit) && new_record? } }
```
Comment (mkllnk) [inline app/models/spree/product.rb:57]: I find this quite confusing. We require it to be a number or nil but then it has to be present under certain conditions. What if we validate numericality under these conditions? I mean numericality instead of presence. Then we have fewer validators and we don't need to allow nil because it's automatically allowed when the condition isn't met.

We also got the same validation on the variant. We need to match the two, otherwise we'll have cases that are impossible to validate.

File: lib/spree/core/product_duplicator.rb [hunk 2]
```diff
@@ -24,7 +24,7 @@ def duplicate_product
           new_product.created_at = nil
           new_product.deleted_at = nil
           new_product.updated_at = nil
-          new_product.unit_value = true
+          new_product.unit_value = nil
```
Comment (mkllnk) [inline lib/spree/core/product_duplicator.rb:27]: This is weird indeed. It was probably just done to fulfil the validation. The value is forwarded to the variant and there it's converted to `1.0`. So we could just set it to `1.0` here to be more clear.

Comment (mkllnk) [reply lib/spree/core/product_duplicator.rb:27]: If the variant unit is weight or volume then we need to set this value. Otherwise the variant will be invalid and the cloning fails.

File: spec/models/spree/product_spec.rb [hunk 3]
```diff
@@ -168,7 +168,7 @@ module Spree
       end
 
       it "requires a unit value" do
-        expect(build(:simple_product, unit_value: nil)).not_to be_valid
+        expect(build(:simple_product, unit_value: nil)).to be_valid
```
Comment (mkllnk) [inline spec/models/spree/product_spec.rb:171]: The spec says: "requires a unit value" and then the content now does the opposite. I think that we need to spec both cases, the case where it's required and the case where it's not.

File: spec/system/admin/products_spec.rb [hunk 4]
```diff
@@ -64,6 +64,42 @@
       expect(page).to have_content "Name can't be blank"
     end
 
+    it "display all attributes when submitting with error: Unit Value must be grater than 0" do
+      login_to_admin_section
+
+      click_link 'Products'
+      click_link 'New Product'
```
Comment (mkllnk) [inline spec/system/admin/products_spec.rb:71]: This is slow. You can go to the page directly, at least to the products page.

File: spec/system/admin/products_spec.rb [hunk 5]
```diff
@@ -64,6 +64,42 @@
...
+
+      select @supplier.name, from: 'product_supplier_id'
```
Comment (mkllnk) [inline spec/system/admin/products_spec.rb:73]:
```suggestion
      select "New Supplier", from: 'product_supplier_id'
```

File: spec/system/admin/products_spec.rb [hunk 6]
```diff
@@ -64,6 +64,42 @@
...
+      fill_in 'product_name', with: "new product name"
```
Comment (mkllnk) [inline spec/system/admin/products_spec.rb:74]: It's better to use the labels (if they are connected to the inputs correctly).

**Review by mkllnk — CHANGES_REQUESTED** [review]
Good investigation. That new spec is great for this case. But I think that we have to consider a few more cases. See comments below.

File: spec/system/admin/products_spec.rb (hunk 6 above)
Comment (abdellani) [reply spec/system/admin/products_spec.rb:74]: Some labels are not connected correctly.
For example "display as"
image

Comment (mkllnk) [reply spec/system/admin/products_spec.rb:73]: That's a shame. We should fix that. Out of scope here though.

File: app/models/spree/product.rb [hunk 7]
```diff
@@ -207,6 +206,23 @@ def self.like_any(fields, values)
...
+      return if value.is_a?(Numeric) && value > 0
+
+      error = if value.nil?
+                I18n.t('errors.messages.not_a_number')
+              else
+                I18n.t('errors.messages.greater_than', count: 0)
+              end
+      errors.add(:unit_value, error)
+    end
+
```
Comment (mkllnk) [inline app/models/spree/product.rb:225]: Wow, I meant to simplify the logic, not make it more complex. :wink:

File: app/models/spree/product.rb [hunk 8]
```diff
@@ -53,8 +53,7 @@ class Product < ApplicationRecord
     validates :name, presence: true
 
     validates :variant_unit, presence: true
-    validates :unit_value, presence:
-      { if: ->(p) { %w(weight volume).include?(p.variant_unit) && new_record? } }
+    validate :validate_unit_value
```
Comment (mkllnk) [inline app/models/spree/product.rb:56]:
```suggestion
    validates :unit_value, numericality: {
      greater_than: 0,
      if: ->(p) { p.variant_unit.in?(%w(weight volume)) && new_record? }
    }
```

**Review by mkllnk — CHANGES_REQUESTED** [review]

**Review by mkllnk — APPROVED** [review]

**Review by dacook — APPROVED** [review]
Great fix!

**Comment by drummer83** [comment]
Hi @abdellani,
Thanks for working on this one!

I have compared some test cases before and after staging.

| Unit | Unit value | Result Before | Result After |
| - | - | - | - |
| Any (except 'items') | 0 | Error 500 ❌ | nice error message (see below) ✔️ |
| Items | 0 | Error 500 ❌ | Error 500 ❌ [Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/64a6c47c84ce33000848ef59?filters[error.status]=open&filters[event.since]=30d&filters[app.release_stage]=staging) |
| Any (except 'item') | empty | nice error message ✔️ | nice error message ✔️ |
| Items | empty | product created with Unit value = 1 ✔️ | product created with Unit value = 1 ✔️ |

image

### Conclusion
As you can see, one of the two errors is fixed. The second one (unit = items && unit value = 0) is still throwing an error 500.
This is an improvement, so I think we can merge and I will open an s3 for the remaining error.

Thanks! 🙏

**Comment by drummer83** [comment]
My user perspective (not the code perspective):
The unit value should be checked as well. If it is left empty it is already set to 1 automatically.
If you type unit value "1" and unit "bottle" and you later change it to unit value "2" ,it becomes "bottleS" automatically - magic! 😉

**Comment by dacook** [comment]
Sorry we missed this Konrad. I agree, given that it currently raises an error anyway, we should require the unit value to be greater than zero all the time.

I  noticed in the original issue, that it can be a decimal value. `0.1` for example would be valid for weight or volume, but a bit strange for items. Still, I think it's valid, and we can just have a simple rule: **Unit value must always be a number greater than 0**.
