### PR TITLE
Revoke transaction fee if payment is cancelled

### LINKED ISSUE #3584: Voiding payment does not remove transaction fee
Voiding either captured or uncaptured payment does not remove transaction fee.

## Description

I'm not sure if the payment method is relevant, but this was observed by @RachL for cash and myself for cheque. 

## Expected Behavior

When you void an existing payment and add another payment, you should only have the transaction fee for the payment that wasn't voided.

## Actual Behavior

When you void an existing payment and add another payment, you end up with two transaction fees.

## Steps to Reproduce

For below, create a cheque or cash payment method for the distributor. Take note of the expected calculation rate.

**As enterprise manager:**

Voiding payment that has been captured:

1. Create an order selecting the payment method earlier.
2. Complete the order without capturing payment. Check that the transaction fee is correct.
3. Capture payment. Check that the transaction fee is still correct.
4. Void the payment.
5. Add another payment. Notice in "Order Details" that there are now two transaction fees charged.

Voiding payment that was not captured:

1. Create another order.
2. Complete the order without capturing payment.
3. Mark the uncaptured payment void.
4. Add another payment to the order. Notice in "Order Details" that there are now two transaction fees charged.

## Context

Discovered by @RachL (and confirmed by myself) while testing #3563.

## Severity

bug-s3: a feature is broken but there is a workaround

You can set the transaction fee to $0.

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #3584

Revoke adjustment when cancelling a payment.

#### What should we test?
This is very well explained in the linked issue #3584 

As enterprise manager:

_Voiding payment that has been captured:_

1. Create an order selecting the payment method earlier.
2. Complete the order without capturing payment. Check that the transaction fee is correct.
3. Capture payment. Check that the transaction fee is still correct.
4. Void the payment.
5. Add another payment. Notice in "Order Details" that there are now two transaction fees charged.

_Voiding payment that was not captured:_

1. Create another order.
2. Complete the order without capturing payment.
3. Mark the uncaptured payment void.
4. Add another payment to the order. Notice in "Order Details" that there are now two transaction fees charged.

#### Release notes
Revoke transaction fee if payment is cancelled

Changelog Category: User facing changes

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]
We should probably add a test somewhere for this.

**Comment by jibees** [comment]
> We should probably add a test somewhere for this.

Yes, That's exactly what I'm trying to do today ;)

**Comment by jibees** [comment]
I'm stuck here... 
Impossible to get only one payment_fee. I guess I'm missing something but don't know what/why.

```diff
diff --git a/spec/models/spree/payment_spec.rb b/spec/models/spree/payment_spec.rb
index 27c6700cf..6636fbc83 100644
--- a/spec/models/spree/payment_spec.rb
+++ b/spec/models/spree/payment_spec.rb
@@ -356,6 +356,20 @@ describe Spree::Payment do
             payment.void_transaction!
           end
         end
+
+        context "if payment has any adjustment", :debug do
+          let!(:order) { create(:order) }
+          let(:payment_method) { create(:payment_method, calculator: ::Calculator::FlatRate.new(preferred_amount: 10)) }
+
+          it "should create another adjustment and revoke the previous one" do
+            payment = create(:payment, order: order, payment_method: payment_method, amount: order.total)
+            expect(order.all_adjustments.payment_fee.length).to eq(1)
+            payment.void_transaction!
+            payment = create(:payment, order: order, payment_method: payment_method, amount: order.total)
+            expect(order.all_adjustments.payment_fee.length).to eq(1)
+          end
+        end
       end
 
       context "#credit" do
```

**Comment by Matt-Yorkley** [comment]
I'm on my mobile right now and guessing, but does it work if you use `order.all_adjustments.payment_fee.eligible` instead?

**Comment by jibees** [comment]
> I'm on my mobile right now and guessing, but does it work if you use `order.all_adjustments.payment_fee.eligible` instead?

@Matt-Yorkley you're a wizard... 🧙 ❤️

File: spec/models/spree/payment_spec.rb [hunk 1]
```diff
@@ -356,6 +356,22 @@
...
+        context "if payment has any adjustment" do
+          let!(:order) { create(:order) }
+          let!(:payment_method) { create(:payment_method, calculator: ::Calculator::FlatRate.new(preferred_amount: 10)) }
+
+          it "should create another adjustment and revoke the previous one" do
+            payment = create(:payment, order: order, payment_method: payment_method)
+            expect(order.all_adjustments.payment_fee.eligible.length).to eq(1)
+
+            payment.void_transaction!
+            expect(order.all_adjustments.payment_fee.eligible.length).to eq(0)
```
Comment (mkllnk) [inline spec/models/spree/payment_spec.rb:369]: No need to change here but this is a good example for the `change` expectation:
```suggestion
            expect { payment.void_transaction! }.
              to change { order.all_adjustments.payment_fee.eligible.length }.by(-1)
```

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees ,

This looks really great.

I've gone through both scenarios, for payments with associated transaction fees:

- adding / voiding a payment **with** payment capture
- adding / voiding a payment **without** payment capture

In both cases, the transaction fee is removed from the adjustments table :tada: 

**Not** introduced by this issue: the payment total only gets updated after the user clicks `Update and recalculate fees`. So, at times, this can be rather misleading - I think this is a well known limitation of the UI but find it is worth mentioning:

Peek 2021-12-02 10-42


Ready to go!

**Comment by filipefurtad0** [comment]
I think this is a major improvement, pinging @openfoodfoundation/train-drivers-product-owners for awareness :+1:

**Comment by RachL** [comment]
This is amazing!
