### PR TITLE
Fix Admin Bulk Products screen performance issue

### LINKED ISSUE #13797: Admin Bulk Products screen is too slow for admins
## Description
This page loads veeery slowly, and is slow to operate, even when filtering to a small number of products.
Often the browser will notify "This page is unresponsive".

It's really not usable for a system admin when trying to provide support to users.

## Expected Behavior
It should respond within a reasonable timeframe, for example in less than 10 seconds

## Actual Behaviour
It takes well over one minute, sometimes more than 4 minutes!

## Steps to Reproduce
1. Log in as super admin on AU staging or prod (and any other large instance)
2. Visit Admin > Products
3. Go make a cup of tea ☕️

## Animated Gif/Screenshot
This was an extreme example with lots of variants on AU prod. It took 4.3mins before the entire page was initialised and ready to use:
Image

But once you try to open and close a dropdown, you still have to wait a long time, and the browser warns
Image

## Workaround
One trick I've learnt is to create a non-admin user, and assign it as a manager of the enterprise that you need to work on.

You can also save time by adding filters into the URL, for example filter by producer:
https://openfoodnetwork.org.au/admin/products?producer_id=250

## Severity
Chose s4 because it only affects admins. I would say "you can use it", but barely.

bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Possible Fix
It's probably related to the very long list of producers in the dropdowns: https://github.com/openfoodfoundation/openfoodnetwork/issues/12482

### PR DESCRIPTION
**Pull request by chahmedejaz**
## What? Why?

- Closes #13797, #12482

Replaced static dropdowns for producers, categories, and tax categories in the products admin page with Ajax-based searchable dropdowns.

The Products admin page becomes extremely slow and often unresponsive on large instances (e.g., AU prod) when logged in as super admin, primarily due to rendering very large dropdown option lists (producers, categories, tax categories). In some cases, the page takes several minutes to become interactive and triggers browser "page unresponsive" warnings.

This change introduces AJAX-based search endpoints and integrates them with `SearchableDropdownComponent` to load options on demand instead of rendering entire datasets upfront.

Key improvements:
- Eliminates large DOM payloads caused by thousands of dropdown options
- Significantly improves initial page load time
- Prevents browser unresponsiveness when interacting with dropdowns
- Scales better for enterprises with large numbers of producers

## What should we test?

- As super admin
- Visit Admin → Products page on a large producers dataset instance with pagination of 100 products per page.
- Verify page load time is significantly improved.
- Open producer, category, and tax category dropdowns and confirm:
  - They load options on demand
  - No browser "unresponsive" warning appears
- Search within dropdowns and verify results are fetched dynamically.
- Ensure pagination works when scrolling through results.
- Select values and confirm they persist after saving changes.
- Edit a product/variant and verify pre-selected values are correctly shown.
- Validate behavior for both filtering and inline editing.
- Confirm no regressions in product create, update, and bulk actions.

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: config/routes/admin.rb [hunk 1]
```diff
@@ -83,6 +83,9 @@
     delete 'products_v3/destroy_variant/:id', to: 'products_v3#destroy_variant', as: 'destroy_variant'
     post 'clone/:id', to: 'products_v3#clone', as: 'clone_product'
     post 'products/create_linked_variant', to: 'products_v3#create_linked_variant', as: 'create_linked_variant'
+    get 'products_v3/search_producers', to: 'products_v3#search_producers', as: 'products_search_producers'
+    get 'products_v3/search_categories', to: 'products_v3#search_categories', as: 'products_search_categories'
+    get 'products_v3/search_tax_categories', to: 'products_v3#search_tax_categories', as: 'products_search_tax_categories'
```
Comment (rioug) [inline config/routes/admin.rb]: The products URL are inconsistent, but I think we should use "products" over "products_v3". Could you update the URLs?

File: app/views/admin/products_v3/_variant_row.html.haml [hunk 2]
```diff
@@ -59,27 +59,27 @@
   = render(SearchableDropdownComponent.new(form: f,
       name: :supplier_id,
       aria_label: t('.producer_field_name'),
-      options: producer_options,
+      options: variant.supplier_id ? [[variant.supplier.name, variant.supplier_id]] : [],
```
Comment (rioug) [inline app/views/admin/products_v3/_variant_row.html.haml:62]: Just making sure I understand correctly, we only show the linked supplier as option in the select when loading the page ? and the supplier list will be populated when opening the dropdown . ie: on demand, is that correct ?

File: app/controllers/admin/ajax_search_controller.rb [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+      query = Spree::Taxon.all
+
+      render json: build_search_response(query)
+    end
+
+    def search_tax_categories
+      query = Spree::TaxCategory.all
+
+      render json: build_search_response(query)
+    end
```
Comment (dacook) [inline app/controllers/admin/ajax_search_controller.rb:22]: These are quite general queries, so I would suggest putting them in a separate controller that could be re-used on other pages too. For example controllers/admin/ajax_search_controller. 

Or maybe even as part of so that they can be used even more broadly. Hmm.. I see that we already have `api/v01/taxons` for example. It appears to support search and pagination, and we could add the required JSON format as a different `serializer`. But.. we don't want to rely on v0.

So I'm not really sure of the best overall solution. 
`±` For now I'd go with my first suggestion.

File: config/routes/admin.rb (hunk 1 above)
Comment (dacook) [reply config/routes/admin.rb]: (further to my suggestion of moving to a different controller)
I wonder if this can be expressed neater inside a `namespace` block? The routes could be grouped similar to a `resource` block.

File: app/controllers/admin/ajax_search_controller.rb [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+
+    def paginated_items(query, page, per_page)
+      query.order(:name).offset((page - 1) * per_page).limit(per_page).pluck(:name, :id)
+    end
+
+    def format_results(items)
+      items.map { |label, value| { value:, label: } }
+    end
+  end
+end
```
Comment (dacook) [inline app/controllers/admin/ajax_search_controller.rb:56]: I see some repetition between these private methods and those in `Reports::AjaxSearch`, so it might be good to DRY them up a bit. But it's not too much.

File: app/helpers/admin/products_helper.rb [hunk 5]
```diff
@@ -52,5 +52,15 @@ def allowed_source_producers
...
+
+    # Query only name of the model to avoid loading the whole record
+    def selected_option(id, model)
+      return [] unless id
+
+      name = model.where(id: id).pick(:name)
+      return [] unless name
+
+      [[name, id]]
+    end
```
Comment (dacook) [inline app/helpers/admin/products_helper.rb:64]: Part of me wondered if we should load the ActiveRecord object in the controller, and pass that through to the view. Then, if the resource needed to be used anywhere else in the page, it's already available without any further database query.

But.. we don't need it anywhere else in the page, so instead here we load it directly from the db without instantiating any unnecessary objects. Good solution 👍

Comment (dacook) [reply app/helpers/admin/products_helper.rb:64]: Hmm coming back to this, I think it would be advantageous passing in the ActiveRecord object.

It means we can pass in the selected object to `SearchableDropdownComponent` once, and automatically create the options array like so:

```
if options.nil? && remote_url.present? 
   options = [[selected_object.try(:name), selected_object.id]]
```

Most objects have a `name` attribute, but if not, you can still pass in `options` like before.

File: app/webpacker/controllers/tom_select_controller.js [hunk 6]
```diff
@@ -91,12 +94,9 @@ export default class extends Controller {
 
     options.load = this.#fetchOptions.bind(this);
 
-    options.onFocus = function () {
-      this.control.load("", () => {});
-    }.bind(this);
-
     options.onDropdownOpen = function () {
       this.openedByClick = true;
+      this.control.load("", () => {});
```
Comment (dacook) [inline app/webpacker/controllers/tom_select_controller.js:99]: ❓ What's the purpose of this change? I'm guessing it means that if the field was focussed by tabbing with the keyboard, it will open the dropdown. I'm not sure that's desirable, beacuse if you're trying to tab to another field the dropdown would get in the way.

So to me, it seems like a better idea to preload the options when focussed, but not open the dropdown.

**Review by dacook — CHANGES_REQUESTED** [review]
Great, thanks for fixing this. Can't wait to test it out! 

I have a few comments. Just one `±` suggestion to change and a ❓ question, plus some thoughts..

File: app/views/admin/products_v3/_variant_row.html.haml (hunk 2 above)
Comment (dacook) [reply app/views/admin/products_v3/_variant_row.html.haml:62]: That's right 👍

Comment (chahmedejaz) [reply app/views/admin/products_v3/_variant_row.html.haml:62]: Yes @rioug, that's right. It's just to show the already selected supplier on the UI by prepopulating it in the options.

File: config/routes/admin.rb (hunk 1 above)
Comment (chahmedejaz) [reply config/routes/admin.rb]: >The products URL are inconsistent, but I think we should use "products" over "products_v3". Could you update the URLs?

Yes, I wanted to do the same @rioug, and when I tried, I got some authorization weird errors. The controller was expecting the `search_producers, search_categories` as ActiveRecord resources, I think, because of some base controller logic. That's why, for the quick fix, I renamed it to v3.
As we have a suggestion to move these to a new controller, I think it shouldn't be the issue there. Thanks

File: app/controllers/admin/ajax_search_controller.rb (hunk 3 above)
Comment (chahmedejaz) [reply app/controllers/admin/ajax_search_controller.rb:22]: Sure @dacook - I'll move these to new controller

File: app/controllers/admin/ajax_search_controller.rb (hunk 4 above)
Comment (chahmedejaz) [reply app/controllers/admin/ajax_search_controller.rb:56]: Yeah, you are right. I'll try to move it to a utility module or something.

File: app/webpacker/controllers/tom_select_controller.js (hunk 6 above)
Comment (chahmedejaz) [reply app/webpacker/controllers/tom_select_controller.js:99]: @dacook - This behavior actually existed before: focusing the field would both open the dropdown and load the options.

This change aims to address that. Now, options are loaded **only when the dropdown is explicitly opened**, and opening the dropdown is triggered by a **click**, not just focus.

So in effect:
- **Focus (e.g., via tab):** does not open the dropdown or load options  
- **Click:** opens the dropdown and triggers loading

Please let me know if anything feels off with this approach. Thanks

Comment (dacook) [reply app/webpacker/controllers/tom_select_controller.js:99]: Oh, good that sounds best! 👍

File: app/controllers/admin/ajax_search_controller.rb (hunk 4 above)
Comment (dacook) [reply app/controllers/admin/ajax_search_controller.rb:56]: Thanks, don't worry if it is going to take too much time, I don't think it _needs_ updating.

**Comment by chahmedejaz** [comment]
Hey @dacook - I've addressed your suggestion here: https://github.com/openfoodfoundation/openfoodnetwork/pull/14040/commits/3ee338fa8d131aded18e7372dc96071237c1519d. It's ready for review.

P.S:
Sorry for getting back to this late, I got sick. Just got better! :)

File: bin/setup [hunk 7]
```diff
@@ -27,7 +27,7 @@ FileUtils.chdir APP_ROOT do
   system("bundle check 2> /dev/null") || system!(BUNDLE_ENV, "bundle install")
 
   # Install JavaScript dependencies
-  system!("script/nodenv-install.sh")
+  system("script/nodenv-install.sh")
```
Comment (rioug) [inline bin/setup]: This seems unrelated to the PR, could you revert this change ?

Comment (dacook) [inline bin/setup]: Was this an accident?

File: spec/requests/admin/ajax_search_spec.rb [hunk 8]
```diff
@@ -0,0 +1,285 @@
...
+          json_response = response.parsed_body
+          expect(json_response["results"].length).to eq(30)
+          expect(json_response["pagination"]["more"]).to be true
+        end
+
+        it "returns remaining results on second page with more flag as false" do
+          get admin_ajax_search_producers_path, params: { page: 2 }
+
+          json_response = response.parsed_body
+          expect(json_response["results"].length).to eq(8)
```
Comment (rioug) [inline spec/requests/admin/ajax_search_spec.rb:95]: Why is this 8 ? shouldn't that be 5 , as you created 35 enterprises ?

File: spec/requests/admin/ajax_search_spec.rb [hunk 9]
```diff
@@ -0,0 +1,285 @@
+# frozen_string_literal: true
```
Comment (dacook) [inline spec/requests/admin/ajax_search_spec.rb:1]: Regarding the filename, we actually [discussed this yesterday](https://github.com/openfoodfoundation/openfoodnetwork/pull/14092/commits/8d0aa303cd17fd122d80896e492883ada7f1db28#r2998416154) and concluded that request specs should generally be named for the path they are testing, not the controller class. That is, `ajax_search_spec.rb`. Could you please rename?

File: spec/requests/admin/ajax_search_spec.rb [hunk 10]
```diff
@@ -0,0 +1,285 @@
...
+          json_response = response.parsed_body
+          expect(json_response["results"].length).to eq(30)
+          expect(json_response["pagination"]["more"]).to be true
+        end
+
+        it "returns remaining results on second page with more flag as false" do
+          get admin_ajax_search_categories_path, params: { page: 2 }
+
+          json_response = response.parsed_body
+          expect(json_response["results"].length).to eq(8)
```
Comment (rioug) [inline spec/requests/admin/ajax_search_spec.rb:195]: Same as above

File: spec/requests/admin/ajax_search_spec.rb [hunk 11]
```diff
@@ -0,0 +1,285 @@
...
+          get admin_ajax_search_tax_categories_path, params: { page: 2 }
+
+          json_response = response.parsed_body
+          expect(json_response["results"].length).to eq(8)
+          expect(json_response["pagination"]["more"]).to be false
+        end
+      end
+    end
+  end
+end
```
Comment (dacook) [inline spec/requests/admin/ajax_search_spec.rb:285]: Great specs 🏅

File: bin/setup (hunk 7 above)
Comment (dacook) [reply bin/setup]: I see you've already fixed

File: spec/requests/admin/ajax_search_spec.rb (hunk 8 above)
Comment (chahmedejaz) [reply spec/requests/admin/ajax_search_spec.rb:95]: Yes, it seems right. However, in the outer context in [these lines](https://github.com/openfoodfoundation/openfoodnetwork/pull/14040/changes#diff-59b0b807be2166f94104dcc6dc27b3399ca831bd65c4893362b697a4e9201296R28-R33), we are creating 3 producers that are impacting the count here.
Sorry, it is not very clear. 😅

File: bin/setup (hunk 7 above)
Comment (chahmedejaz) [reply bin/setup]: Ah, nice catch. I mistakenly pushed it 😅
I usually comment this out because it gives me the error for nodenv and I don't use it as my node version manager. I added all my changes and pushed it mistakenly 😅

Comment (chahmedejaz) [reply bin/setup]: Yeah, I mistakenly pushed it 😅
I usually comment this out because it gives me the error for nodenv and I don't use it as my node version manager. I added all my changes and pushed it mistakenly 😅

**Comment by chahmedejaz** [comment]
Thanks, both 🙌 
It's ready now, @rioug.

**Review by rioug — APPROVED** [review]

**Comment by AMEA-LYON** [comment]
Waouw ! What an performance improvement (almost 5x faster !) Congratulations !

But I often had a "network error" dialog when using the "Next" pagination button...

https://github.com/user-attachments/assets/ba546303-d368-49bf-ae39-fb5ad12e285b



Another very minor remark : when using the "Clear search" button, the "Show" drop-down button selection is reset to "15 par page", is it possible to keep it unchanged ?

**Comment by chahmedejaz** [comment]
@AMEA-LYON - Great! And thanks for raising these issues. These are the existing ones that need to be handled separately. For the **network error**, we already have [this issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/13775). And for the **Clear search** button, please raise a separate good first issue for this one.
Please let me know if you have any questions. Thanks!

**Comment by AMEA-LYON** [comment]
Ok, thank you @chahmedejaz for the informations, 
=> Ready to go 🚀
