### PR TITLE
Page is redirected to root after login from shopfront page

### LINKED ISSUE #13019: Page is redirected to root after login from shopfront page
## Description
When a user is arriving to the ofn website via a link (e.g. a link to a shopfront), and the logs in via the login modal dialog, the page is redirected to the root url. This causes the user to loose the original shopfront, so she has to e.g. paste it again to the browser.

This is a obtrusive behivour in case the link to the shopfront is shared via email, etc. In our case we use a lot of hidden shopfronts for closed consumer groups.

  
## Expected Behavior
The user is not redirected to the root url, but stays the page she is when she started to login.

## Actual Behaviour
The user is redirected to the root url.

## Steps to Reproduce
0. Logout from OFN.
1. Copy a link of a shopfront from any enterprise.
2. Paste this url to the browser  - the shopfront shows up.
3. Login to OFN.
4. The page is redirected to the root.

## Workaround
User can paste the link again after login.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
irrelevant.

## Possible Fix
Send and re-use the actual url after login.

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #13019
- This PR fixes the issue by storing the location on the shop page such that when user login from the shop page, it's redirected back to the shop page rather than the home page

#### What should we test?

- As mentioned in the issue

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [X] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/controllers/enterprises_controller.rb [hunk 1]
```diff
@@ -24,6 +24,7 @@ def shop
     set_noindex_meta_tag
 
     @enterprise = current_distributor
+    store_location_for :spree_user, request.original_fullpath
```
Comment (dacook) [inline app/controllers/enterprises_controller.rb:27]: Interesting, I think this should have happened in `set_after_login_url`:
https://github.com/openfoodnetwork/openfoodnetwork/blob/main/app/controllers/application_controller.rb#L43

I wonder why it's necessary?

**Review by dacook — COMMENTED** [review]
Actually, I think the stored location doesn't work on any page, is there a way to solve it for all pages?

Maybe this action conflicts with it?
https://github.com/openfoodfoundation/openfoodnetwork/blob/main/app/controllers/spree/user_sessions_controller.rb#L17

File: app/controllers/enterprises_controller.rb (hunk 1 above)
Comment (chahmedejaz) [reply app/controllers/enterprises_controller.rb:27]: As far as I could understand, the purpose of `set_after_login_url` is that if the user tries to go to the auth protected page however, he isn't logged in, then after login he should redirect back to the protected page was wanted to go.

We cannot use it in our case because shop page is public (_not auth protected_), so `after_login_url` is not set.

Maybe we can tweak it to make it work for any user no matter which page he is on. Let me do a quick spike on it.

Comment (chahmedejaz) [reply app/controllers/enterprises_controller.rb]: @dacook - It's fixed for all the public pages as well. Here's the change: https://github.com/openfoodfoundation/openfoodnetwork/pull/13189/commits/edaffe1f1df0b956a071fe7fe384acada7952619

**Review by dacook — APPROVED** [review]
Yay, that looks like a good way to solve it!

**Review by dacook — CHANGES_REQUESTED** [review]
Ah, but it looks like a problem in a spec: 
```
rspec ./spec/system/admin/authentication_spec.rb:14 # Authentication as anonymous user logging into admin redirects home, then back to admin
```

File: app/views/layouts/_login_tab.html.haml [hunk 2]
```diff
@@ -1,5 +1,7 @@
 #login-content
   = form_with url: spree_user_session_path, scope: :spree_user, data: { remote: "true" } do |form|
+    = form.hidden_field :after_login, value: request.original_url, name: :after_login
```
Comment (mkllnk) [inline app/views/layouts/_login_tab.html.haml:3]: Have a look at the Stripe controller:

https://github.com/openfoodfoundation/openfoodnetwork/blob/de784209bbd4779607d104e8f69734519e75ac7b/app/controllers/payment_gateways/stripe_controller.rb#L49-L54

There we pass the path as parameter. The ApplicationController then stores that path:

https://github.com/openfoodfoundation/openfoodnetwork/blob/de784209bbd4779607d104e8f69734519e75ac7b/app/controllers/application_controller.rb#L104-L106

But your new form input then overrides that path. So in that case we end up on the homepage when we should be in the middle of the checkout. I haven't tested this but breaking the checkout at payment stage would be really bad. That said, I don't even know when the method above is used. There are other controllers using this mechanism though, for example when trying to view an order.

https://github.com/openfoodfoundation/openfoodnetwork/blob/de784209bbd4779607d104e8f69734519e75ac7b/app/controllers/spree/orders_controller.rb#L153-L160

Here we also see that the path is set twice. First the controller calls `store_location_for` directly but then it also sets the `after_login` path in addition. I guess that it was added to fix the redirection after implementing the login-modal. Just a guess. It was all a bit complicated when we were still depending on the spree gem and overriding its functionality with monkey-patching.

Anyway, this is a great opportunity to clean up and cover these cases with specs. There's also a security concern to think about. Look at these methods:

https://github.com/openfoodfoundation/openfoodnetwork/blob/de784209bbd4779607d104e8f69734519e75ac7b/lib/spree/core/controller_helpers/auth.rb#L37-L55

Spree was thinking about disallowed URLs because using user input to redirect is dangerous. Think, for example, of the `fire` method to change order state. Unfortunately, it's implemented as a GET route and somebody can trick you in following a link that will change the state of an order if you are an enterprise user. That's why it's better to avoid user input like form inputs or even the currently used URL parameter in redirects. It's best to call `store_location_for` as you did in your first commit. If we want a more general solution then we could always store the path, probably not the `fullpath` because that contains parameters which can indicate actions.

The tricky bit is though, to distinguish between the default path we set and a special path that is set in circumstances like accessing an order or during checkout. But maybe it will just align. :shrug: 

So I'm afraid it's not simple and we should do some robust work around this to solve it properly. If we need to rely on user input, we should parse it and only use the path without parameters. And we should delete all the unused code around this topic.

**Review by mkllnk — CHANGES_REQUESTED** [review]
Redirecting after log-in seems so simple but trips people up all the time. It's almost as difficult as caching. :wink: 

It's great that you found a solution that seems to work in every case. But I had a look around and found some code paths that could break. I'm not sure they do though. And it's a bit obscure.

**Comment by chahmedejaz** [comment]
Thanks @mkllnk for your insightful feedback. And you are right, it's not that simple to fix this for every page as there are a lot of factors to think about, as you mentioned.

@mkllnk, @dacook - I assume this may require more code-level time to cater to every use case and specs. Moreover, it would require a good deal of testing as well.
Considering that this specific issue for the shop page is causing much inconvenience to the user as reported, I suggest we fix this specifically for the shopfront page for now to ensure a smooth experience for the user and create a separate issue to fix this for other pages so that we can devote more time. Please let me know if you think otherwise so that I continue on it. Thanks.

**Review by mkllnk — APPROVED** [review]

**Review by dacook — APPROVED** [review]
Sounds good. Ahmed would you be able to create a new issue and document the remaining problem?

**Comment by chahmedejaz** [comment]
> Sounds good. Ahmed would you be able to create a new issue and document the remaining problem?

Sure, David. I'll create the issue to address the remaining problem.

**Comment by chahmedejaz** [comment]
@dacook, @mkllnk - The issue has been raised here:
https://github.com/openfoodfoundation/openfoodnetwork/issues/13198

Please review and make respective changes if I'm missing anything. Thanks.

**Comment by chahmedejaz** [comment]
Per [this slack](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1741377455220799), I did its quick testing on UK staging and here are the results:

Before staging the PR:

https://github.com/user-attachments/assets/a2c0642b-88b4-4ce4-a77b-982e50d3c110

It's observed that, from the shop page, we are redirected to the root upon login.

After staging the PR:

https://github.com/user-attachments/assets/529a0758-301c-4c34-a318-14879f69d680

It's observed that, from the shop page, we are redirected to the root upon login.

Looks good to go 🚀, Merging 🎉

**Comment by mkllnk** [comment]
We usually don't test our own pull requests because we tend to be blind to our own mistakes. But I'm happy for this one to be merged.
