### PR TITLE
Fix incorrect results for multiple tax rates in report

### LINKED ISSUE #12066: [Reports] Sales Tax Totals by Producer report shows all tax rates of a tax category and incorrect results
## Description

This was observed when testing [#11543](https://github.com/openfoodfoundation/openfoodnetwork/pull/11543).

If an order is placed involving a product which has a tax category that consists of multiple tax rates, then the Sales Tax Totals by Producer report will display one line for each and every tax rate of that category - even if that tax rate has never been applied in any orders. The additional lines also have Total excl. tax and Total incl. tax values listed but they should all be zero, because no orders used these tax rates.
The report gives the impression that the summary rows are incorrect - but in fact the summary rows are correct and the lines above are incorrect.

## Expected Behavior

Only tax rates which have been applied in any orders within the filter criteria should be shown and considered. If it is not possible to hide the unused tax rates, then at least the Total excl. tax and Total incl. tax values must be zero.

## Actual Behaviour

Tax rates which have not been applied to any orders are listed in the report and they even have Total excl. tax and Total incl. tax values entered.

## Steps to Reproduce

1. As super admin set up at least two tax rates for the same tax category.
2. Apply the tax category to a product.
3. Place an order including this product.
4. Run the Sales Tax Totals by Producer report.
5. See that the report lists both tax rates and values for Total excl. tax and Total incl. tax even for the tax rate which has never been used.

## Animated Gif/Screenshot

image

## Workaround

None.

## Severity
bug-s2 or bug-s5

## Your Environment

* Version used: staged #11543 
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by cyrillefr**
#### What? Why?

- Closes #12066 

The issue lied in the `total_excl_tax` method that did not take into account which `tax_rates` were really used.
The method would apply taxes if they were defined, even though they were not used.
An example would be a customer in a country which mandates a tax, but not in a state that requires one.
But as the 2 taxes are in the same category, they would both be applied in the report. 

One can also use the following use case(the one I have used): for a same tax category, 1 tax rate for Europe, one for Australia. It would be applied the 2 tax rates even though address can only be in one country.

#### What should we test?
Cf. § Steps to Reproduce in #12066
Repeat this procedure.
One can use the use case described above for the order.
Going to `localhost:3000/admin/reports`, clicking `Sales Tax Totals By Producer` should show an order with 2 lines.
There should be a line of 0 for non applicable tax rates

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb [hunk 1]
```diff
@@ -119,6 +120,66 @@
...
+      ship_address.update!({ state_id: another_state.id })
+      order.line_items.create({ variant:, quantity: 1, price: 100 })
+      order.update!({
+                      order_cycle_id: order_cycle.id,
+                      ship_address_id: ship_address.id
+                    })
+
+      while !order.completed?
+        break unless order.next!
+      end
```
Comment (rioug) [inline spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb:135]: We have a service for that, you can use `OrderWorkflow.new(order).complete!`

**Review by rioug — CHANGES_REQUESTED** [review]
Thanks for your work on this @cyrillefr ! Looks good. Just one little update in the spec , see my comment.

**Comment by rioug** [comment]
@abdellani Could you have a look at this ? I feel like you've looked at something similar not long ago .

File: spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb (hunk 1 above)
Comment (cyrillefr) [reply spec/system/admin/reports/sales_tax/sales_tax_totals_by_producer_spec.rb]: Did the replacement. While at it, I have also made the replacement for all other instances found in the spec.

**Review by abdellani — CHANGES_REQUESTED** [review]
@rioug  yes, you're right. Thank you for tagging me. : )

Hi @cyrillefr 
Thank you for your contribution :+1: .

I noticed a similar issue when I was working [on this](https://github.com/openfoodfoundation/openfoodnetwork/pull/12172/files#r1498223947).

If we return to the original [issue description](https://github.com/openfoodfoundation/openfoodnetwork/issues/12066),  you'll find that the problem is not with the calculated values but the report is listing a tax rate that was never used (@drummer83 please correct me if I'm wrong).

image

if you check the following code 
https://github.com/openfoodfoundation/openfoodnetwork/blob/a9d586952d43adf5868f7f9f72f1d33543dbf5d8/lib/reporting/reports/sales_tax/sales_tax_totals_by_producer.rb#L27-L32
you'll find that for every `line_item`, we're loading all the tax rates. This was my mistake because when I wrote that code, I thought that `Spree::LintItem#tax_rates` returns all the tax rates that are applied on the item.
This is a wrong assumption, the method returns all the tax rates that come under the tax category of the product's variant.
https://github.com/openfoodfoundation/openfoodnetwork/blob/a9d586952d43adf5868f7f9f72f1d33543dbf5d8/app/models/spree/line_item.rb#L196-L198 

To fix this, I would focus on the `query_result`. Instead of `line_item.tax_rates` you can `line_item.adjustments.eligible.tax.map(&:originator_id)`

**Comment by cyrillefr** [comment]
Hello @abdellani , @rioug ,

I did notice where the problem was, but did the selecting out of unapplied tax rates in the `total_excl_tax` method instead.
Now, (it was 2 weeks ago), I wonder why I did it there :smile: It is much simpler in the `query_result` method.
So I did the change, and reverted back `total_excl_tax` to its original state.

Also, the behaviour of the report is a bit different: with my solution, appeared one line with zeros.
Now, only lines with applied tax rates will appear.

**Review by mkllnk — APPROVED** [review]
This is looking good to me but I haven't worked with this code in a while.

**Review by rioug — APPROVED** [review]
Looks good now ! thanks !

**Comment by RachL** [comment]
Here is aan example of an order before / after the PR. This is looking good to me! Many thansk @cyrillefr ❤️ 


image


image
