### PR TITLE
Subscription emails for customer should not link to order page if customer has no user account

### LINKED ISSUE #2534: [Subs] Remove link to 'make changes' to order from confirmation email if customer is guest
## Description
#2508 described a problem of invalid link / unauthorised when subscription created for a guest i.e. Customer that is not confirmed OFN user

## Expected Behavior
This card replaces #2508 and #2511 - both of which outline more complex / effective improvements for consideration in next version of Subscriptions.

Expected behaviour for this 'quick fix' is that a guest Customer that does not have an OFN User does not have the 'make changes' link in their order confirmation email - so they cannot click on 'Make changes'. This Customer is not able to edit their order.

If they create a User later, they will be able to see orders created after that point, but not previous ones - they are lost forever.

NB. When this is done User Guide AND instance managers supporting Beta Subscriptions Users need to make sure they're aware that Customers who aren't OFN users will not be able to edit their orders. 

## Actual Behavior
An Enterprise can create a Customer without creating a User.
This means that they can then create a Subscription for a Customer that is not a User.
This means that when that subscription is turned into an order, the Customer receives an email telling them their order has been created and gives them a link to edit their order.
When they hit that link they get an 'unauthorised' page. If they then sign up (creating a User) and log in, they will be able to see new orders created but not old ones

To avoid this problem, a Hub would need to ensure that all their Customers have created User accounts before they can set up a Subscription for them. This is onerous and error-prone and will likely prevent people using Subscriptions at all. Way too many places to get interrupted / blocked and never complete the process.

## Steps to Reproduce
1. Create a new Customer from admin/customers - use a 'virgin' email that doesn't already have a User in OFN
2. Create a Subscription for that Customer
3. Click on the 'make changes' link in order confirmation
4. See 'unauthorised' screen

## Context
Testing Subscriptions as a person new to it, got completely tangled. Potentially very off-putting to Subscription beta testers

## Possible Fix
Change order confirmation text for a Customer that is not an authorised OFN user 

Current text "This order was automatically created for you. You can [make changes] until orders close on Fri Aug 31 @ 12:00AM. If you have any questions you can contact VT Organic Bulk Buy via kirsten@eaterprises.com.au."

For Guest orders "This order was automatically created for you. You can make changes until orders close on Fri Aug 31 @ 12:00AM by contacting **your Hub** via **hub@email**."

Hub can then explain to them that they can sign-up if they want to be able to make changes themselves for future orders

### PR DESCRIPTION
**Pull request by kristinalim**
#### What? Why?

Closes #2534

Updates subscription-related emails for customers, removing link to order page for customers who do not have a user account. Adds custom text for placement emails for this scenario.

#### What should we test?

For below, make sure that the OFN instance is already [configured for Stripe integration](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Setting-up-Stripe-on-an-OFN-instance).

The following should also be set up for the shop:

1. Subscriptions are enabled (Shop Preferences > Subscriptions)
2. Stripe payment method (Shop Preferences > Payment Methods)

There are three types of subscription emails affected by this PR:

1. Placement of order
2. Confirmation of order
3. Failure to automatically charge payment

And three scenarios that should be tested:

1. Customer has no associated user account
2. Customer has user account, and shop is configured to allow customer to edit placed orders
3. Customer has user account, but shop is configured to restrict customer from editing placed orders

**Scenario 1: Customer has no associated user account**

1. Create a new ongoing order cycle (OC).
2. Create the customer. Make sure there is no user account for this email yet.
3. Create a subscription that starts before current time. Select Cheque payment method.
4. Wait approximately 5 minutes. Find the order placement email, and check that it does not contain a link to the order. _"This order was automatically created for you. This order was automatically created for you. You can make changes until orders close on Fri Aug 31 @ 11:00PM by contacting Amazing Shop via shop@example.com."_
5. To simulate the OC closing, :warning: set its close time to a couple of minutes before current time.
6. Wait approximately 5 minutes. Find the order confirmation email, and check that it does not contain a link to the order. _"This order was automatically placed for you, and it has now been finalised. If you have any questions you can contact Amazing Shop via shop@example.com."_

(AFAIK, there is no way for a customer with no user account to receive the SO failed payment for the subscription. I will ask and will update this when I get info.)

**Scenario 2: Customer has user account, and shop is configured to allow customer to edit placed orders**

(Change enterprise setting: Shop Preferences > Change Orders > "Customers can change / cancel orders while OC is open")

1. :warning: Open the OC again by updating its close date.
2. Create the customer.
3. **As customer:** Sign up with the customer email.
4. **As customer:** Save [credit card details that would charge successfully](https://stripe.com/docs/testing#cards), and give the shop permission to charge you.
5. Create a subscription that starts before current time. Select Stripe payment method.
6. Wait approximately 5 minutes. Find the order placement email, and check that it contains a link to "make changes" to the order. _"This order was automatically created for you. You can make changes until orders close on Fri Aug 31 @ 11:00PM. If you have any questions you can contact Amazing Shop via shop@example.com."_
7. To simulate the OC closing, :warning: set its close time to a couple of minutes before current time.
8. Wait approximately 5 minutes. Find the order confirmation email, and check that it contains a link to "view details" of the order. _"This order was automatically placed for you, and it has now been finalised. You can view details of this order at any time. If you have any questions you can contact Amazing Shop via shop@example.com."_
9. :warning: Open the OC again by updating its close date.
10. **As customer:** Change the saved credit card details to a one that would fail when attempting to charge.
11. Create a subscription that starts before current time. Select Stripe payment method.
12. Wait approximately 5 minutes. Find the order placement email, and check that it contains a link to "view details" of the order. _"The payment for your subscription with Amazing Shop failed because of a problem with your credit card. Amazing Shop has been notified of this failed payment. You can view details of this order at any time. If you have any questions you can contact Amazing Shop via shop@example.com."_

**Scenario 3: Customer has user account, but shop is configured to restrict customer from editing placed orders**

(Change enterprise setting: Shop Preferences > Change Orders > "Placed orders cannot be changed / cancelled")

1. :warning: Open the OC again by updating its close date.
2. Create a subscription that starts before current time. Select Stripe payment method.
3. Wait approximately 5 minutes. Find the Order placement email, and check that it contains a link to "view details" of the order. _"This order was automatically created for you. You can view details of this order at any time. If you have any questions you can contact Amazing Shop via shop@example.com."_

#### Release notes

- Remove link to Order page from Subscription emails for Customers that do not have associated User.

Changelog Category: Fixed

### CODE REVIEW

File: app/helpers/shop_mail_helper.rb [hunk 1]
```diff
@@ -0,0 +1,5 @@
+module ShopMailHelper
+  def mail_long_datetime_format
```
Comment (sauloperez) [inline app/helpers/shop_mail_helper.rb]: an example of a date that follows the format below as method doc will come in handy

File: spec/mailers/subscription_mailer_spec.rb [hunk 2]
```diff
@@ -39,7 +40,36 @@
...
+      let(:shop) { create(:enterprise, allow_order_changes: true) }
+
+      let(:email) { SubscriptionMailer.deliveries.last }
+      let(:body) { email.body.encoded }
+
+      before do
+        SubscriptionMailer.placement_email(order, {}).deliver
+      end
+
+      let(:customer) { create(:customer, enterprise: shop) }
```
Comment (luisramos0) [inline spec/mailers/subscription_mailer_spec.rb]: is there a reason to have this let after the before and not together with the others lets above?

**Comment by luisramos0** [comment]
@kristinalim I think you can decide what to do with the two tiny details raised above and move to test ready afterwards.

File: app/helpers/shop_mail_helper.rb (hunk 1 above)
Comment (kristinalim) [reply app/helpers/shop_mail_helper.rb]: Thanks, @sauloperez. Done here: fc033822984cbd3ab183fe69874540f0f47ee9c9

**Comment by kristinalim** [comment]
I made the change, and also squashed a local change I hadn't pushed (oops! :worried:) which corrects `%distributor}` in the language file to `%{distributor}`. I also rebased this upon master.

Checks all good. Moving this to Test Ready now.

File: app/helpers/shop_mail_helper.rb (hunk 1 above)
Comment (kristinalim) [reply app/helpers/shop_mail_helper.rb]: Eep! :grin: After reading again, it's quite obvious that's what @sauloperez meant, and it makes a lot more sense. Sorry for the trouble, and thanks for checking! I pushed the change: ad8b120e4869c53a0ec04abff8bdd63de4191d7c PR checks remain green.

**Comment by kristinalim** [comment]
@luisramos0 Eep. :grin: I updated the method doc comment already. https://github.com/openfoodfoundation/openfoodnetwork/pull/2624#discussion_r214517145

**Comment by mkllnk** [comment]
Staged on https://staging1.openfood.com.au/.

**Comment by sstead** [comment]
**Testing notes**

All three scenarios were behaving correctly.

https://docs.google.com/document/d/13HFUszOoEyvNqdBlefMZ5K0haXj28iMiKJaLPkxXPF4/edit#
