### PR TITLE
Fixing Enterprise creation submit button behavior

### LINKED ISSUE #10009: [Enterprise->Create] A disabled button prevents from going forward in the process
## Description
When creating a new enterprise from the /register page, at step 3, if you don't choose "I'm a producer" or "No, I'm not a producer" and you click the red button to go to the next page, you have an error "Please choose one. Are you a producer?" and the button is disabled. But then, even after selecting one of the choices, the button remains disabled and you can't go forward. 

## Expected Behavior
The button must be reactivated after a selection has been done.

## Steps to Reproduce
1. Create a new enterprise from the /register page ("join" button on the homepage)
2. At step 3, don't choose either of the choices and click the "Create profile" red button
3. See that the button remains disabled whatever you do

## Animated Gif/Screenshot

stuckystcuck

## Workaround
Quit and do it again.

## Severity
bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by vviekk**
#### What? Why?

- Closes #10009

Fixes the Submit button behavior on enterprise creation form. 
1. Keeps the button from being disabled when submit button is hit without complete form. (Shows error)
2. Disables button once hit with valid form, to avoid multiple submissions.

#### What should we test?

1. log in
2. Visit /register page.
   1. If number of enterprises are already at max for the given account, please go the admin page and delete one of the test enterprises.
4. Fill out form till step 3.

##### Disabled button fix: 
1. On step 3 of the form, without selecting the type of the enterprise, hit submit.
2. Error is displayed to select the type of the enterprise.
  1. For control - the button gets disabled, and doesn't get re-enabled even after selecting the type.
  2. For treatment - Button does not get disabled and can submit after the type is selected.
     1. Error stays until the selection is made to complete the form and keeps from submitting without type selection.

##### Multiple submission fix:
1. Refresh the page and fill out the form till step 3 again.
1. Select a type and hit Submit multiple times.
  1. For control - the success page is loaded and error alerts are shown saying that the enterprise already exist. (For the number of times the submit button was pressed -1)
  2. For treatment - the success page is displayed. The button was disabled after the first submission, to avoid multiple clicks until the first request was processed.

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Comment by vviekk** [comment]
Apologies for such a long and dragged out wait for a simple fix. Had to focus on other things for a while.

**Comment by vviekk** [comment]
The check failing during set up : https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4183267123/jobs/7247411781
Could be a transient error.

**Comment by jibees** [comment]
> Could be a transient error.

Yes, it was ;)

**Review by mkllnk — APPROVED** [review]
Thanks!

**Review by filipefurtad0 — APPROVED** [review]
Thanks @vviekk !

I've added a spec change here:
https://github.com/openfoodfoundation/openfoodnetwork/pull/10470

This is good to go I think, feel to cherry-pick the commit https://github.com/openfoodfoundation/openfoodnetwork/pull/10470/commits/785527d4edb929442ce7723d57da24f88bf7786c of you don't find this PR tested and merged in the meantime :+1:

**Comment by vviekk** [comment]
Thank you!

@jibees @filipefurtad0!
Apologies I missed adding the spec. 

@filipefurtad0, i don't understand what you mean by cherry picking the commit. 
Do you mean to say we cherry pick the spec change commit to this PR?

**Comment by filipefurtad0** [comment]
Perfect! The build is green :tada:
Thanks @vviekk .

File: spec/system/consumer/registration_spec.rb [hunk 1]
```diff
@@ -70,6 +70,10 @@
       expect(page).to have_content 'Last step to add My Awesome Enterprise!'
 
       # Choosing a type
+      click_button "Create Profile"
+      expect(page).to have_content("Please choose one. Are you are producer?")
+      expect(page).to have_button "Create Profile", disabled: false
+
       click_link "producer-panel"
       expect(page).to have_selector '#producer-panel.selected'
```
Comment (filipefurtad0) [inline spec/system/consumer/registration_spec.rb:79]: We should still assure that the button now becomes active, after clicking the producer panel - right?

```suggestion
      expect(page).to have_button "Create Profile", disabled: false
```

**Review by filipefurtad0 — CHANGES_REQUESTED** [review]

File: spec/system/consumer/registration_spec.rb [hunk 2]
```diff
@@ -70,6 +70,10 @@
       expect(page).to have_content 'Last step to add My Awesome Enterprise!'
 
       # Choosing a type
+      click_button "Create Profile"
+      expect(page).to have_content("Please choose one. Are you are producer?")
+      expect(page).to have_button "Create Profile", disabled: false
```
Comment (filipefurtad0) [inline spec/system/consumer/registration_spec.rb:75]: If no profile has been chosen, then the button should be disabled I think - so disabled should be `true`here?
`expect(page).to have_button "Create Profile", disabled: true`

File: spec/system/consumer/registration_spec.rb (hunk 1 above)
Comment (vviekk) [reply spec/system/consumer/registration_spec.rb:79]: Correct.
But I assumed the next line `click_button "Create Profile"` would only work if its enabled.
Please let me know if my understanding is incorrect.

File: spec/system/consumer/registration_spec.rb (hunk 2 above)
Comment (vviekk) [reply spec/system/consumer/registration_spec.rb:75]: Ideally, yes.
But then we would have to listen for every update made in the form to check if its valid to re-enable the button which could be expensive.  (Or could be much simpler that I am unaware of. New to ruby and front-end)
So made the changes so we just show the show the error message without disabling or proceeding, If that makes sense. 

Please let me know if I'm missing something as a ruby noob.

**Comment by filipefurtad0** [comment]
Hey @vv

I've now staged the PR and confirmed that clicking the `Create Profile` button:

- does not disable the button
- displays an error message
- the message only disappears till the profile selection is made
- clicking several times does not display several errors (only one error) 
- after making the profile selection, the `Create Profile` takes the user to the next screen and creates the enterprise

Looks good! Merging :-)
Thanks for your work here.

I've attached a video to illustrate this:
https://www.loom.com/share/24a7fde555534044af6fa60b6f600f0c

**Comment by filipefurtad0** [comment]
Pinging you @audez for awareness, as the implemented solution is slightly different that the acceptance criteria indicated on the issue #10009.
