### PR TITLE
BUU Display error messages when file not valid

### LINKED ISSUE #12513: [BUU] Uploading corrupt product images fails silently
## Description

Uploading a corrupt image has no visible effect on the UI. This can give the impression that the change was sucessful, when in fact, nothing changes. An error can be seen in the console.

## Expected Behavior

An error message should be displayed to the user. Below, an image from legacy BO, as an example:

image

## Actual Behaviour

Nothing happens, no visible warning appears to the user (an error in the console can be seen)

## Steps to Reproduce

1. Edit a valid image (for example, on the text editor, delete some lines, and hit save)
2. With `admin_products_3` feature enabled, open the console and try uploading the corrupt file.
3. Notice no error appears to the user. An error is seen in the console.

## Animated Gif/Screenshot

image

## Workaround

None needed.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

See https://github.com/openfoodfoundation/openfoodnetwork/issues/12513#issuecomment-2132465419

### PR DESCRIPTION
**Pull request by cyrillefr**
#### What? Why?

- Closes #12513

I have chosen the first choice by @dacook and implemented a turbo stream response with the edit modal.
Either corrupted file/ non image file raise invalid attachment.
User can now upload a new file if wrong the 1st time instead of having to click to re open a modal.
There were 2 pending test lines in spec. I removed one and the other one tests the behaviour implemented here.

#### What should we test?
- as an admin / shop owner
- with `admin V3` feature toggled
- Visit `admin/products`
- scroll to bottom of page and click on one product image
- upload either a non image file (csv, pdf etc.) or a corrupted file (eg [this file](https://github.com/openfoodfoundation/openfoodnetwork/blob/e07cf6c628c9e50b0f3f902807caec2cf68df620/public/invalid_image.jpg))
- click upload
- the modal should only show error message(s) + back and upload buttons
- repeat the procedure to show again the modal with errors
- upload a valid file and see the product image being replaced, the modal closed. (does not jump back to the top of the page)

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [X] Feature toggled

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Looks good :+1:

File: app/controllers/spree/admin/images_controller.rb [hunk 1]
```diff
@@ -50,19 +50,20 @@ def update
         @url_filters = ::ProductFilters.new.extract(request.query_parameters)
         set_viewable
 
-        if @object.update(permitted_resource_params)
+        if @object.update!(permitted_resource_params)
```
Comment (dacook) [inline app/controllers/spree/admin/images_controller.rb:53]: I respect this approach, to consider invalid records as an exception. However it's not the usual approach so I would avoid it unless there was an added advantage in this case.

File: app/views/spree/admin/images/edit.turbo_stream.haml [hunk 2]
```diff
@@ -3,7 +3,13 @@
     %h2= t(".title")
 
     -# Display image in the same way it appears in the shopfront popup
-    %p= image_tag @image.persisted? ? @image.url(:large) : Spree::Image.default_image_url(:large), width: 433, height: 433
+    - if defined?(@errors) && !@errors.empty?
+      - @errors.each do |error|
+        %p
+          = error
```
Comment (dacook) [inline app/views/spree/admin/images/edit.turbo_stream.haml:9]: FYI usually `errors.full_message.to_sentence` is enough for cases like this.

File: app/controllers/spree/admin/images_controller.rb [hunk 3]
```diff
@@ -50,19 +50,20 @@ def update
...
           respond_with do |format|
             format.html { redirect_to location_after_save }
             format.turbo_stream
           end
-        else
-          respond_with(@object)
         end
-      rescue ActiveStorage::IntegrityError
-        @object.errors.add :attachment, :integrity_error
-        respond_with(@object)
```
Comment (dacook) [inline app/controllers/spree/admin/images_controller.rb:65]: Any reason to remove this error handler? I guess we didn't have specs for it.
`±` I'm sure it's there for a good reason so I think we should keep it. I don't know how to replicate it, but I imagine some corrupt files could trigger it.

I would suggest moving the `respond_with` block to a new method, so it can be shared for the two cases. (eg `respond_with_error`)

**Review by dacook — CHANGES_REQUESTED** [review]
Great, thanks for doing this!

`±` I have a query about removing the `IntegrityError` check, can you please have a look and restore if necessary?

Also, would you be willing to try adding a browser test for this, below here: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/system/admin/products_v3/products_spec.rb#L1042-L1066 ?

Otherwise, the other comments are just comments and don't require changes.

File: app/views/spree/admin/images/edit.turbo_stream.haml (hunk 2 above)
Comment (cyrillefr) [reply app/views/spree/admin/images/edit.turbo_stream.haml:9]: The @errors object actually contains only the full messages.

**Comment by cyrillefr** [comment]
Hello @dacook ,

Regarding the `ActiveStorage::IntegrityError`.
Yes I did that because there is no spec for it. I also noticed it was not used for checking file types.

Documentation for this error is scarce, and the few cases where people asked for help were not when checking file types.
It was always related to data already stored in Cloud or similar services.

Also, some times, it was simply a problem of missing key. I have looked a bit in the source gem, and this error is often raised when there is no key. Some key to identify some data in a particular service I would guess.
I would say that the word integrity refers to some functional integrity and not some binary integrity.

File: app/controllers/spree/admin/images_controller.rb (hunk 3 above)
Comment (cyrillefr) [reply app/controllers/spree/admin/images_controller.rb:65]: I have refactored to a new `respond_with_error` method.

File: app/controllers/spree/admin/images_controller.rb [hunk 4]
```diff
@@ -35,34 +35,24 @@ def create
...
         set_viewable
 
-        if @object.update(permitted_resource_params)
-          flash[:success] = flash_message_for(@object, :successfully_updated)
+        @object.update!(permitted_resource_params)
+        flash[:success] = flash_message_for(@object, :successfully_updated)
 
-          respond_with do |format|
-            format.html { redirect_to location_after_save }
-            format.turbo_stream
```
Comment (dacook) [inline app/controllers/spree/admin/images_controller.rb:58]: `±` It looks like we lose the `turbo_stream` format for `update` success. This was a shortcut which allows the image to be updated on the page without reloading the page (and losing scroll position). Can you please bring that back?

Comment (dacook) [reply app/controllers/spree/admin/images_controller.rb:58]: I can see that will make the turbo request spec fail. I can't think of a clean way to re-use the shared_examples, so you might need to just copy them, or add parameters to shared_examples.

File: app/controllers/spree/admin/images_controller.rb (hunk 3 above)
Comment (dacook) [reply app/controllers/spree/admin/images_controller.rb:65]: Thanks for looking into the error.  I remember now that I added this check on [this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/12048#issuecomment-1909206891). 
It has also been tracked here: https://github.com/openfoodfoundation/openfoodnetwork/issues/9302

So it seems that it only happens when trying to view existing images, not when uploading images.
But.. on the `update` action we _do_ also view images; in the `turbo_stream` success format.
So I think if the image integrity has broken, I think we still want to catch the error and let the user know. Because the only way to fix it is by uploading the image again.

However, this is only theory until we can replicate the error. 🤔 If we can't replicate it, then maybe we shouldn't try to catch it. Ok let's leave this out.

**Review by dacook — CHANGES_REQUESTED** [review]
Great work on the specs, thank you!

`±` Sorry but I noticed you removed a `turbo_stream` format which is required, can you please add that back?

File: app/controllers/spree/admin/images_controller.rb (hunk 4 above)
Comment (cyrillefr) [reply app/controllers/spree/admin/images_controller.rb:58]: Hello @dacook , I made a blunder by removing the classical html view. So, I quickly re-added them, in a new method to factor code between `create` and `edit` methods. I made 2 commits spaced by 45mn. The last one is green. So, I guess your comment came after the first commit of the two of them.

Comment (dacook) [reply app/controllers/spree/admin/images_controller.rb:58]: Yes, I see your last commit brings the `html` format back for **_error_** case 👍 
But, the `turbo_stream` format for the update **_success_** case is still missing. 

You can test this by scrolling to the product at the bottom of the page, and updating the image. It should update without jumping back to the top of the page.

(as a side note, turbo_stream format is also missing for `create` success, but it was already missing before this PR)

Comment (cyrillefr) [reply app/controllers/spree/admin/images_controller.rb:58]: Hello @dacook , you are right.
I set the turbo responses both for `update` & `create`.
It also had a small side effect on the request spec.

File: public/invalid_image.jpg
Comment (mkllnk) [inline public/invalid_image.jpg:1]: This is a big file for something that just needs to be invalid.

**Review by mkllnk — APPROVED** [review]
Okay, this should work. Thank you!

I still don't understand why you didn't follow the usual pattern of `if object.save ... else ...`.

File: public/invalid_image.jpg
Comment (cyrillefr) [reply public/invalid_image.jpg:1]: Hello @mkllnk ,
I do use Rescue so that it is straightforward. save! then rescue if it is not OK.
It is an habit, but a bad one. Because I use the rescue as a if , a control flow.
I just realized that after the week-end. I will update it in a few minutes.

**Comment by cyrillefr** [comment]
I would need someone to re launch the tests as there is some spec failing but that is green on my local ...

**Review by rioug — APPROVED** [review]

**Review by dacook — APPROVED** [review]
Great, thanks for the following up, this looks perfect to me. 
I've added a couple of notes to the testing notes and it's ready to test.

**Comment by RachL** [comment]
LGTM!

I'm not sure we need both error messages, but this can be improved later, at least we don't have an error 500 anymore 💪 thanks @cyrillefr !!

image

Something I need to check once the PR is merged: is "Attachment" added in translation correctly. Merging!

image

**Comment by dacook** [comment]
@RachL I have raised a new PR for translating this word. I'm wondering if there are other words like this which don't yet have a translation key?
