### PR TITLE
[Spree 2.1] Make backoffice stripe payments work in rails 4

### LINKED ISSUE #5525: [Spree 2.1] Stripe (Connect and SCA) payments not working in the backoffice
## Description

Payments with Stripe are not working if the order is placed in the backoffice, for both Stripe SCA and Stripe Connect, with the simplest test card 4242424242424242.

These payment methods have been tested in the shopfront and work fine, only known issue so far is #5447.

## Expected Behavior

Payments in the BO should work for both Stripe-Connect and Stripe-SCA, with cards which do not require authentication.

## Actual Behaviour

The "Error Saving Payment" message is shown (below).

## Steps to Reproduce

1. Create a new order for a given customer. Make sure this customer/user allows charges on a credit card or add one, under the user's account, /account -> Credit Cards. Place a Check under Authorised Shops, for the respective shop.
2. Fill the necessary details, and proceed to Payment Methods
3. Select a Stripe payment method and add the respective credit card data, allowed by the user.
4. Press Update -> The error messages (below) should be displayed.

## Animated Gif/Screenshot

Stripe Connect:

Stripe SCA:

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 3-0-stable
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Ubuntu 18.04, Desktop

## Possible Fix

Related issues:
Stripe SCA Payments fail in the backoffice #5212
[StripeSCA] Fix card payments in the Backoffice #5233

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5525

Backoffice Stripe payments were not working in rails 4 at all, the card attributes were not permitted and so the details were not being saved in the database.
Added a missing automated test to payments controller.

#### What should we test?
Verify backoffice stripe payments are now working for both StripeConnect and StripeSCA.

#### Release notes
Changelog Category: Fixed
Fixed stripe payments in the BackOffice in rails 4.

### CODE REVIEW

File: app/services/permitted_attributes/checkout.rb [hunk 1]
```diff
@@ -11,24 +13,13 @@ def call
           :existing_card_id, :shipping_method_id,
           payments_attributes: [
             :payment_method_id,
-            source_attributes: payment_source_attributes
+            source_attributes: PermittedAttributes::PaymentSource.attributes
```
Comment (sauloperez) [inline app/services/permitted_attributes/checkout.rb:16]: since this `PaymentSource` belongs to `PermittedAttributes` module Ruby's constant lookup should find it without having to specify `PermittedAttributes::`. Have you tried it?

Comment (luisramos0) [reply app/services/permitted_attributes/checkout.rb:16]: I havent. I think this is better than using the implicit namespace. Also because in this case the namespace is informative: it's not a payment source, it's the permitted attributes of a payment source.

Comment (sauloperez) [reply app/services/permitted_attributes/checkout.rb:16]: then the issue is with the actual class name IMO but fair enough :+1:

Comment (luisramos0) [reply app/services/permitted_attributes/checkout.rb:16]: thanks!
Can you review the PR? This PR is a release blocker I think.

**Comment by sauloperez** [comment]
I think this needs a rebase @luisramos0 . I see lots of old errors in the build

**Comment by luisramos0** [comment]
yes, rebased.

**Comment by luisramos0** [comment]
The caching spec is still failing, I think think means #5628 is not 100% fixed.

**Comment by filipefurtad0** [comment]
Hi @luisramos0 ,

Tested the outcome of different cards for both stripe methods, when placing orders in the backoffice, checking whether:

i) confirmation email
ii) order amounts and
iii) entries in Stripe dashboard

match. This was done for cards where success is expected:

a) Visa 4242424242424242
b) international card 4000002460000001

And when failure is expected:

c) 3D Secure 4000002760003184 (only for Stripe SCA)
d) card_declined code - 4000000000000002
e) incorrect_cvc code - 4000000000000127

Summarizing:
- when card types a) and b) are used in the backoffice i) ii) and iii) always match - all good.
- card type c) fails as expected (only for Stripe SCA)
- failing card types d) and e) lead to the expected result with Stripe SCA payment method; with Stripe-Connect it breaks the payment page (this is known - https://github.com/openfoodfoundation/openfoodnetwork/pull/5233#issuecomment-619935320)

Ready to go :tada:

**Comment by luisramos0** [comment]
great testing Filipe!
