### PR TITLE
4206 back from edit product removed filters products page

### LINKED ISSUE #4206: 'Back' from Edit Product removed filters on Products page
## Description

A small UX improvement such that a browsers Back buttons maintain filtering.

## Expected Behavior

1. A user filters the Products on the Products page to find a specific product.
2. They then click Edit Product to make some changes to it.
3. They save this then hit 'Back' or the button 'Back to Products List'.
4. I'm taken back to the Products page and all of my filters are still in place meaning that I'm still shown the same set of Products as before I navigated away.

## Actual Behaviour

1. .... As above
2. .....
3. ....
4. I'm taken back to the Products page but my filters have gone. I need to reload the filters, which takes time. If I'm editing dozens of products I quickly get annoyed!

## Steps to Reproduce

See above.

## Context

When I have a number of changes to make to multiple Products I get quite annoyed. For large hubs this becomes unweildy quite quickly as there are often sizeable changes to make and I can't make them on the Products page.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: 2.3.1
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Linux
* OFN Platform instance where you discovered the bug, and which version of the software they are using. UK

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

Closes #4206 

As explained in #4206, when setting some filters on the product list page, and then clicking on edit link to update a product, going back to the product list page isn't keeping the filters.

In the proposed solution, the product list page now set the filter parameters in the url when applying a filter, respectively the page will now apply the correct filter if there are any filter parameters present in the url. This ensure that the browser back button works as expected.
Filter parameters are then passed along to the product edit page, so that the "Back to product list" and "Cancel" links include  filter parameters in their url. 

#### What should we test?

On the product list page, test the filtering feature : 
- apply any filter/combination of filters and check that the page url includes the filter parameters, something like : "admin/products **#?categoryFilter=6**"
- apply any filter/combination of filters and check the products are filtered appropriately (regression test).

On the product edit page, test the "Cancel", "Back to product list" links and the browser back button :
First set a filter/combination of filters on the product list page, and load the product edit page by clicking on the "edit" link.

- Without updating the product :
  - use the browser "Back button" and check the previously applied filter are loaded correctly on the product list page.
  - use the "Back to product list" link and check the previously applied filter are loaded correctly on the product list page.
  - use the "Cancel" link and check the previously applied filter are loaded correctly on the product list page.
- Update the product by clicking on the "Update" button : 
  - use the "Back to product list" link and check the previously applied filter are loaded correctly on the product list page.
  - use the "Cancel" link and check the previously applied filter are loaded correctly on the product list page.

On the product edit page, test the various product related pages listed in the right hand side column :
- Images
- Variants
- Product Propertied
- Group Buy Options
- Search

First set a filter/combination of filters on the product list page, and load the product edit page by clicking on the "edit" link.
Then, you should be able to visit each pages, do any changes needed, and go back to the "Product details" page. From there, the "Cancel" and "Back to product list" links should load the product list page applying the previous selected filters.

#### Release notes

Back from the Edit product page keeps the previously set filters

Changelog Category: Added

### CODE REVIEW

File: app/controllers/spree/admin/products_controller.rb [hunk 1]
```diff
@@ -31,6 +31,19 @@ class ProductsController < ResourceController
...
       } }
 
+      respond_override update: { html: {
+        success: lambda {
+          redirect_to edit_admin_product_url(@product, @url_filter)
+        },
+        failure: lambda {
+          redirect_to edit_admin_product_url(@product, @url_filter)
+        }
+      } }
```
Comment (luisramos0) [inline app/controllers/spree/admin/products_controller.rb:41]: We need to stop using this respond_override style.
Can you please implement this in the update action? you can bring all the code from resource_controller, it would start with something like this and then you can add these overrides in there:
image


I wonder if the update action really needs to support html and js, maybe not and one can be removed.

Comment (rioug) [reply app/controllers/spree/admin/products_controller.rb:41]: Sure, I believe the js shouldn't be needed.

Comment (rioug) [reply app/controllers/spree/admin/products_controller.rb]: Done, I also refactored the create method to remove "respond_override".

File: app/controllers/spree/admin/products_controller.rb [hunk 2]
```diff
@@ -9,36 +9,34 @@ class ProductsController < ResourceController
...
-          end
-        },
-        failure: lambda {
-          render :new
-        }
-      } }
-
       def new
         @object.shipping_category = DefaultShippingCategory.find_or_create
         super
```
Comment (luisramos0) [inline app/controllers/spree/admin/products_controller.rb:21]: same as the edit action, instead of a call to super we can probably have a single line here using render.

File: app/controllers/spree/admin/variants_controller.rb [hunk 3]
```diff
@@ -4,14 +4,51 @@ module Spree
...
       new_action.before :new_before
 
+      def index
+        @url_filters = product_filters(request.query_parameters)
+      end
+
+      def edit
+        @url_filters = product_filters(request.query_parameters)
+
+        super
```
Comment (luisramos0) [inline app/controllers/spree/admin/variants_controller.rb:19]: same here, instead of super this is probably a one liner using render

File: app/controllers/spree/admin/variants_controller.rb [hunk 4]
```diff
@@ -4,14 +4,51 @@ module Spree
...
+          redirect_to admin_product_variants_url(params[:product_id], @url_filter)
+        else
+          redirect_to edit_admin_product_variant_url(params[:product_id], @object, @url_filter)
+        end
+      end
+
+      def new
+        @url_filters = product_filters(request.query_parameters)
+
+        super
```
Comment (luisramos0) [inline app/controllers/spree/admin/variants_controller.rb:36]: same here, instead of super, probably a one liner using render

File: spec/features/admin/bulk_product_update_spec.rb [hunk 5]
```diff
@@ -516,37 +516,61 @@
...
-          end
+        within "tr#v_#{v1.id}" do
+          find("a.edit-variant").click
         end
 
-        within_window new_window do
-          expect(URI.parse(current_url).path).to eq "/admin/products/#{v1.product.permalink}/variants/#{v1.id}/edit"
-          page.execute_script('window.close()')
+        uri = URI.parse(current_url)
+        expect(URI.parse(current_url).path).to eq "/admin/products/#{v1.product.permalink}/variants/#{v1.id}/edit"
```
Comment (luisramos0) [inline spec/features/admin/bulk_product_update_spec.rb:555]: you should use the url helpers here, I think this one is
edit_admin_product_variant_path(v1.product.permalink, v1.id})

File: spec/features/admin/bulk_product_update_spec.rb [hunk 6]
```diff
@@ -516,37 +516,61 @@
...
+        # Set a filter
+        select2_select p1.supplier.name, from: "producer_filter"
+        apply_filters
+
+        within "tr#v_#{v1.id}" do
+          find("a.edit-variant").click
         end
+
+        uri = URI.parse(current_url)
+        expect("#{uri.path}?#{uri.query}").to eq "/admin/products/#{v1.product.permalink}/variants/#{v1.id}/edit?producerFilter=#{p1.supplier.id}"
```
Comment (luisramos0) [inline spec/features/admin/bulk_product_update_spec.rb:573]: same here, I think this is
edit_admin_product_variant_path(v1.product.permalink, v1.id, producerFilter: p1.supplier.id)

File: spec/features/admin/products_spec.rb [hunk 7]
```diff
@@ -152,6 +152,32 @@
...
+      # Check the url still includes the filters
+      uri = URI.parse(current_url)
+      expect("#{uri.path}?#{uri.query}").to eq "#{spree.edit_admin_product_path(product)}?#{filter_query}"
+
+      # Link back to the bulk product update page should include the filters
+      expect(page).to have_link(I18n.t('admin.products.back_to_products_list'), href: %r{admin\/products#\?#{filter_query}})
+      expect(page).to have_link(I18n.t(:cancel), href: %r{admin\/products#\?#{filter_query}})
+
+      # Sidebar link should include the filters
+      expect(page).to have_link(I18n.t('admin.products.tabs.product_details'), href: %r{admin\/products\/#{product.permalink}\/edit\?#{filter_query}})
```
Comment (luisramos0) [inline spec/features/admin/products_spec.rb:173]: I think this would be easier to read with url helpers as well:
where the helper call would be done with producerFilter: "2" as the last argument as I show above.

File: spec/features/admin/variants_spec.rb [hunk 8]
```diff
@@ -1,30 +1,86 @@
 require 'spec_helper'
 
+# TODO check the filter are passed around as expected
```
Comment (luisramos0) [inline spec/features/admin/variants_spec.rb:3]: I dont think we should have TODO entries on the code. If this is something to be done in the future we should create a github issue to represent that task.

File: app/assets/javascripts/admin/bulk_product_update.js.coffee [hunk 9]
```diff
@@ -122,8 +127,9 @@ angular.module("ofn.admin").controller "AdminProductEditCtrl", ($scope, $timeout
 
   $scope.editWarn = (product, variant) ->
     if confirm_unsaved_changes()
-      window.open(editProductUrl(product, variant), "_blank")
-
+      filterUrl = $httpParamSerializer(generateFilter())
+      filterUrl = "?#{filterUrl}" if filterUrl isnt ""
+      $window.location.href = "#{editProductUrl(product, variant)}#{filterUrl}"
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee:132]: Yeah I had been thinking about that, hopefully I can come up with something more generic so can re use it for  #4207.

File: app/helpers/spree/admin/product_filter_helper.rb [hunk 10]
```diff
@@ -0,0 +1,15 @@
...
+
+module Spree
+  module Admin
+    module ProductFilterHelper
+      PRODUCT_FILTER = [
+        'query', 'producerFilter', 'categoryFilter', 'sorting', 'importDateFilter'
+      ].freeze
+
+      def product_filters(params)
+        params.select { |k, _v| PRODUCT_FILTER.include?(k) }
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/helpers/spree/admin/product_filter_helper.rb:11]: it didn't. As far as I can see [Naming/BlockParameterName](https://docs.rubocop.org/rubocop/0.86/cops_naming.html) isn't define in rubocop configuration. Is this something that has been added recently ?

File: app/controllers/spree/admin/products_controller.rb (hunk 2 above)
Comment (rioug) [reply app/controllers/spree/admin/products_controller.rb:21]: I was wondering, do we actually need to use `respond_with(@object)`  ? if not we can just get rid of the super.

Comment (luisramos0) [reply app/controllers/spree/admin/products_controller.rb:21]: no we dont need to use it. We can bypass it as long as things continue to work. I am not sure exactly what it does... it's from spree. Maybe it's just something that can be overrided with respond_override? I am not sure, I'd love to get rid of it:
https://github.com/openfoodfoundation/spree/blob/2-1-0-stable/core/lib/spree/core/controller_helpers/respond_with.rb

File: app/helpers/spree/admin/product_filter_helper.rb (hunk 10 above)
[the remark this answers is not in the document]
Comment (luisramos0) [reply app/helpers/spree/admin/product_filter_helper.rb:11]: no, it's not recent. I am not sure why it's not showing up. We should follow it here anyway :+1:

File: app/controllers/spree/admin/products_controller.rb [hunk 11]
```diff
@@ -38,7 +26,20 @@ def new
 
       def create
         delete_stock_params_and_set_after do
-          super
+          @prototype = Spree::Prototype.find(params[:product][:prototype_id]) if \
+            params[:product][:prototype_id].present?
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/controllers/spree/admin/products_controller.rb:27]: fixed

File: app/assets/javascripts/admin/directives/select2_min_search.js.coffee [hunk 12]
```diff
@@ -5,5 +5,10 @@ angular.module("ofn.admin").directive "ofnSelect2MinSearch", ->
       minimumResultsForSearch: attrs.ofnSelect2MinSearch
 
     ngModel.$formatters.push (value) ->
-      if (value)
-        element.select2('val', value);
\ No newline at end of file
+      # select2 populate options with a value like "number:3" or "string:category" but 
+      # select2('val', value) doesn't do the translation for us as one would expect 
+      if isNaN(value)
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/assets/javascripts/admin/directives/select2_min_search.js.coffee:10]: fixed

File: app/controllers/spree/admin/variants_controller.rb (hunk 4 above)
Comment (rioug) [reply app/controllers/spree/admin/variants_controller.rb:36]: fixed

File: app/controllers/spree/admin/variants_controller.rb [hunk 13]
```diff
@@ -4,14 +4,51 @@ module Spree
...
+      end
+
       def create
+        @url_filter = product_filters(request.query_parameters)
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/controllers/spree/admin/variants_controller.rb:40]: fixed

File: app/controllers/spree/admin/products_controller.rb [hunk 14]
```diff
@@ -56,14 +54,25 @@ def index
         @show_latest_import = params[:latest_import] || false
       end
 
+      def edit
+        @url_filters = product_filters(params)
+        super
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/controllers/spree/admin/products_controller.rb:59]: fixed

File: app/controllers/spree/admin/variants_controller.rb (hunk 3 above)
Comment (rioug) [reply app/controllers/spree/admin/variants_controller.rb:19]: fixed

File: spec/features/admin/bulk_product_update_spec.rb (hunk 5 above)
Comment (rioug) [reply spec/features/admin/bulk_product_update_spec.rb:555]: fixed

File: spec/features/admin/products_spec.rb (hunk 7 above)
Comment (rioug) [reply spec/features/admin/products_spec.rb:173]: fixed

File: spec/features/admin/variants_spec.rb (hunk 8 above)
Comment (rioug) [reply spec/features/admin/variants_spec.rb:3]: Removed, I did not mean to commit this.

File: spec/features/admin/bulk_product_update_spec.rb (hunk 6 above)
Comment (rioug) [reply spec/features/admin/bulk_product_update_spec.rb:573]: fixed

File: app/controllers/spree/admin/products_controller.rb (hunk 2 above)
Comment (rioug) [reply app/controllers/spree/admin/products_controller.rb:21]: I removed the respond_with where it wasn't needed.

File: app/assets/javascripts/admin/bulk_product_update.js.coffee (hunk 9 above)
[the remark this answers is not in the document]
Comment (rioug) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee]: Moved the filter functionality to ProductFilterService : https://github.com/rioug/openfoodnetwork/blob/4206-back-from-Edit-Product-removed-filters-products-page/app/assets/javascripts/admin/services/product_filters.js.coffee

File: app/helpers/spree/admin/product_filter_helper.rb [hunk 15]
```diff
@@ -0,0 +1,15 @@
+# frozen_string_literal: true
+
+module Spree
+  module Admin
+    module ProductFilterHelper
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/helpers/spree/admin/product_filter_helper.rb]: Moved ProductFilterHelper to a service : https://github.com/rioug/openfoodnetwork/blob/4206-back-from-Edit-Product-removed-filters-products-page/app/services/product_filters.rb

**Comment by rioug** [comment]
As far as I can tell the build errors have nothing to do with my changes.

**Comment by sigmundpetersen** [comment]
The branch has conflicts, maybe a rebase will fix them?

File: app/assets/javascripts/admin/bulk_product_update.js.coffee [hunk 16]
```diff
@@ -50,28 +43,37 @@ angular.module("ofn.admin").controller "AdminProductEditCtrl", ($scope, $timeout
     $scope.page = newPage
     $scope.fetchProducts()
 
+  generateFilter = ->
+    filters = {}
+    for filter in productFilters
+      filters[filter] = $scope[filter] if $scope[filter]
+
+    filters
```
Comment (luisramos0) [inline app/assets/javascripts/admin/bulk_product_update.js.coffee:51]: I think you have forgotten to remove this method, it's now in the service :+1:

File: app/assets/javascripts/admin/services/product_filters.js.coffee [hunk 17]
```diff
@@ -0,0 +1,23 @@
+angular.module("ofn.admin").factory "ProductFiltersService", ($httpParamSerializer) ->
```
Comment (luisramos0) [inline app/assets/javascripts/admin/services/product_filters.js.coffee:1]: here we should follow local dialect (do whatever the rest of the code is doing) and not name the service service. In this case I think the service could be called ProductFilters or ProductFiltersUrl

File: spec/features/admin/variants_spec.rb [hunk 18]
```diff
@@ -7,24 +7,98 @@
...
-    # Then the variant should have been created
-    expect(page).to have_content "Variant \"#{product.name}\" has been successfully created!"
+      expected_delete_url = Regexp.new(
+        Regexp.escape(spree.admin_product_variant_path(product, variant, filter))
+      )
+      expect(page).to have_link(I18n.t(:delete), href: expected_delete_url)
+    end
   end
 
   describe "editing unit value and description for a variant", js: true do
```
Comment (luisramos0) [inline spec/features/admin/variants_spec.rb:85]: there's already a js:true at the top of the spec so this one is not needed, right?

**Comment by rioug** [comment]
Thanks @luisramos0 , I'll try to have a look at this tomorrow.

> Thanks for the PR again @rioug are you on slack? would be good to know know more about you!

I am on slack under the name "Gaetan", you actually answered a few of my questions. Feel free to shoot me message. I really need to update my github profile.

**Comment by luisramos0** [comment]
ah, ok, I didnt match the GH profile with the slack profile :+1: 
awesome!

File: spec/features/admin/variants_spec.rb (hunk 18 above)
Comment (rioug) [reply spec/features/admin/variants_spec.rb:85]: If I am not mistaken this "describe" sits under (top of the file) : 
```
feature '
    As an admin
    I want to manage product variants
' do
```
and not under any other "describe", so I think we need the js:true here

File: app/assets/javascripts/admin/bulk_product_update.js.coffee (hunk 16 above)
Comment (rioug) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee]: Indeed, removed.

File: app/assets/javascripts/admin/services/product_filters.js.coffee (hunk 17 above)
Comment (rioug) [reply app/assets/javascripts/admin/services/product_filters.js.coffee]: Done

File: spec/features/admin/bulk_product_update_spec.rb [hunk 19]
```diff
@@ -514,37 +514,61 @@
...
+        # Set a filter
+        select2_select p1.supplier.name, from: "producer_filter"
+        apply_filters
+
+        within "tr#p_#{p1.id}" do
+          find("a.edit-product").click
         end
+
+        uri = URI.parse(current_url)
+        expect("#{uri.path}?#{uri.query}").to eq spree.edit_admin_product_path(v1.product.permalink, producerFilter: p1.supplier.id)
```
Comment (sauloperez) [inline spec/features/admin/bulk_product_update_spec.rb:539]: isn't this the same as `expect(page).to have_current_path(spree.edit_admin_product_path(v1.product.permalink, producerFilter: p1.supplier.id))`?

File: app/views/spree/admin/variants/index.html.haml [hunk 20]
```diff
@@ -27,9 +27,10 @@
         %td.align-center= variant.display_price.to_html
         %td.align-center= variant.sku
         %td.actions
-          = link_to_edit(variant, no_text: true) unless variant.deleted?
-          = link_to_delete(variant, no_text: true) unless variant.deleted?
+          = link_to_with_icon('icon-edit', Spree.t(:edit), edit_object_url(variant, @url_filters), no_text: true) unless variant.deleted?
+          = link_to_delete(variant, { url: object_url(variant, @url_filters), no_text: true }) unless variant.deleted?
 
+// TODO this
```
Comment (sauloperez) [inline app/views/spree/admin/variants/index.html.haml:33]: Leftover?

**Comment by sauloperez** [comment]
Amazing work @rioug ! Thanks a lot! I just added a couple of minor comments that don't block the PR.

File: app/views/spree/admin/variants/index.html.haml (hunk 20 above)
Comment (luisramos0) [reply app/views/spree/admin/variants/index.html.haml:33]: I think this needs to block the PR. Otherwise we will need to have commits after the test happens. We need to remove this before we test, ok?

**Review by luisramos0 — CHANGES_REQUESTED** [review]
Just changing my review so that the TODO entry is removed before we move to test ready.

**Comment by sauloperez** [comment]
According to https://github.com/openfoodfoundation/openfoodnetwork/issues/4207#issuecomment-678047832 @rioug won't be around anymore so we'll fix this things ourselves @luisramos0

**Review by luisramos0 — APPROVED** [review]

**Comment by luisramos0** [comment]
ok :+1:
I managed to remove the TODO and push my commit to @rioug s branch, this is good for testing imo.
@sauloperez do you want to add something else or move to test ready?

**Review by sauloperez — APPROVED** [review]

**Comment by gaetan-yg** [comment]
I was planning to look at this this week-end, I see it's already been taken care off. Thanks! 
As Pau mentioned, I am short on free time nowadays but I still hope to be able to contribute every now and then.

**Comment by rioug** [comment]
I was planning to look at this this week-end, I see it's already been taken care of, thanks ! 
As Pau mentioned, I have a lot less free time nowadays, but I still hope to be able to contribute every now and then.

**Comment by filipefurtad0** [comment]
Hi @sauloperez @luisramos0 ,
Somehow the check for Semaphore was not performed for this PR - the link for staging is missing.
Could you please run it now? Thanks.

**Comment by sigmundpetersen** [comment]
Hey @filipefurtad0 you can find the PR on the Semaphore overview page by identifying the PR number.
You can deploy from here https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-5722/builds/10

**Comment by filipefurtad0** [comment]
Thank you @sigmundpetersen!
It was there all along... And the checks were performed. All greens. Thanks again :raised_hands:

**Comment by filipefurtad0** [comment]
Hey @rioug ,

Thank you for the well documented PR and testing notes.

It was verified that this PR reverts #4342: After staging, clicking the edit button does not open a new tab.

I checked the following items both as admin and superadmin.

- verified filters work independently and in different combinations, as before (regression test)
- verified that the applied filters are reflected in the URL, for ex. the search show in the see pic below can be recreated with the link 

`https://staging.openfoodnetwork.org.uk/admin/products#?producerFilter=201389&categoryFilter=200054&query=blau&importDateFilter=2020-06-02
`

image

Having these set, on the product edit page, I checked that:

- "Cancel"
- "Back to product list" button
- and the browser back button

all bring you back to the products page, retaining all previously set filters. This works independently of having edited the product or not (tested both cases).  


Also, on the product edit page, tested various product related pages listed in the right hand side column :

- Images
- Variants
- Product Properties
- Group Buy Options
- Search

After navigating through these pages and making changes, returning to the "Product details" and clicking "Cancel" and "Back to product list" loads the product list page, with the previous selected filters.

This is good to go! 
Thanks again Gaitan :tada: 


PS: It was also verified the this PR does not introduce the new functionality when creating a new product. If filters are applied, clicking "+New Product" on the Products page initially retains the filters (in the URL), but after clicking "Create", "Create and add another" or "Cancel" removes them. I am wondering whether it would not make sense to extend this functionality to product creation. This is outside the scope of this PR and would require a new issue. Would this be a desired feature? Pinging @lin-d-hop @RachL  who were involved in  #4206 and #4338, respectively.
