### PR TITLE
Admin, Products list: fix variant creation when unit is not well formatted and on_demand is checked or on_hand is filled

### LINKED ISSUE #9068: When creating variants the error message on incorrectly input data is unreadable
## Description

On the admin/products page creating new variants is simple enough using the + button.
However if you type 120g instead of 120 you get an error that is hard to understand.
It would be great if the offending fields could be highlighted instead of a cryptic message at the bottom of the screen.
Failing that, can we make this error message easier to understand?

## Expected Behavior

When I get an error it's clear to me what the error is

## Actual Behaviour

Cryptic error message

## Steps to Reproduce

1. in /admin/products click + to add a new variant
2. Enter 120g instead of 120 in the unit field
3. See an error message that is hard to understand
4.

## Animated Gif/Screenshot

Screenshot from 2022-04-04 17-09-14

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Note that since we are about to rewrite this page its probably not worth investing too much into this, but a better error message would be nice.

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9068
Many errors that were intricate. 
But now, we display the original errors on why the variant saving failed. 

#### What should we test?

- As an admin, visit page `/admin/products`
- Create a new variant with `12g` in `unit` column (for example), and `on_hand` filled or `on_demand` checked
- This should display errors:

Capture d’écran 2022-07-05 à 16 44 35

Creating variants should be the same as before. 

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
@filipefurtad0 
i'd be happy if you could have look at this one, and specially around the case `when variant unit value is: '120g'` (line `#301`) on commit 9b51f85e9 : this should not pass, but actually is green. I cannot make it fails (ie. reproducing the original issue)

Actually, I manage to reproduce the bug on my setup, but not with specs. I think this situation could give me some advice.

File: spec/system/admin/bulk_product_update_spec.rb [hunk 1]
```diff
@@ -227,51 +227,85 @@
...
+        fill_in "variant_unit_value_with_description", with: "120g"
+        check "variant_on_demand"
 
-    # Then I should see edit buttons for the new variant
-    expect(page).to have_selector "a.edit-variant", visible: true
+        click_button 'Save Changes', match: :first
+        expect(page.find("#status-message")).to have_content "Changes saved."
+      end
+    end
   end
```
Comment (filipefurtad0) [inline spec/system/admin/bulk_product_update_spec.rb:309]: The error seems to be only triggered when creating a new variant, it's this bugsnag:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60e04e7202a6f500077688b2?filters[event.since]=30d&filters[error.status]=open&event_id=62c31b16009566bf54c20000

With the code below, I was able to reproduce it in my local system:

The error:
```
     Failure/Error: raise message if stock_items.empty?
     
     RuntimeError:
       You need to save the variant to create a stock item before you can set stock levels.

```

The code:



```
      it "creating a variant with unit value is: '120g'" do
        pending "#9068"
        within "tr#v_#{Spree::Variant.second.id}" do
          page.find(".add-variant").click
        end

        within "tr#v_-1" do
          fill_in "variant_unit_value_with_description", with: "120g"
          fill_in "variant_display_as", with: "120g"
          fill_in "variant_price", with: "6.66"
          fill_in "variant_on_hand", with: "222"
        end
        
        click_button 'Save Changes', match: :first
        expect(page.find("#status-message")).to have_content "Changes saved."
      end
```

File: spec/system/admin/bulk_product_update_spec.rb [hunk 2]
```diff
@@ -227,51 +227,85 @@
...
 
-    updated_variant = Spree::Variant.where(deleted_at: nil).last
-    expect(updated_variant.display_name).to eq "Case of 12 Bottles"
-    expect(updated_variant.unit_value).to eq 3000
-    expect(updated_variant.unit_description).to eq "(12x250 mL bottles)"
-    expect(updated_variant.display_as).to eq "Case"
-    expect(updated_variant.price).to eq 4.0
-    expect(updated_variant.on_hand).to eq 10
+      it "when variant unit value is: '120g'" do
+        fill_in "variant_unit_value_with_description", with: "120g"
```
Comment (filipefurtad0) [inline spec/system/admin/bulk_product_update_spec.rb:302]: On this test case, the variant is actually not being updated. For example, if we change the price as well, with something like this:

`        fill_in "variant_price", with: "6.66"`

And then after saving changes, assert that the price changed with:

`        expect(page).to have_content "6.66"`

Then the test will fail, probably because of the `g` in `120g`.

This looks closely related to #9068; do you think we need a separate issue?

File: spec/system/admin/bulk_product_update_spec.rb [hunk 3]
```diff
@@ -227,51 +227,85 @@
...
+        check "variant_on_demand"
 
-    # Then I should see edit buttons for the new variant
-    expect(page).to have_selector "a.edit-variant", visible: true
+        click_button 'Save Changes', match: :first
+        expect(page.find("#status-message")).to have_content "Changes saved."
+      end
+    end
```
Comment (filipefurtad0) [inline spec/system/admin/bulk_product_update_spec.rb:308]:
```suggestion
          it "creating a variant with unit value is: '120g'" do
        pending "#9068"
        within "tr#v_#{Spree::Variant.second.id}" do
          page.find(".add-variant").click
        end

        within "tr#v_-1" do
          fill_in "variant_unit_value_with_description", with: "120g"
          fill_in "variant_display_as", with: "120g"
          fill_in "variant_price", with: "6.66"
          fill_in "variant_on_hand", with: "222"
        end
        
        click_button 'Save Changes', match: :first
        expect(page.find("#status-message")).to have_content "Changes saved."
      end
    end
```

File: spec/system/admin/bulk_product_update_spec.rb (hunk 2 above)
Comment (jibees) [reply spec/system/admin/bulk_product_update_spec.rb:302]: I think this should all be handled by #9068 ;)

**Comment by jibees** [comment]
Ok thanks @filipefurtad0 !
I can now have a spec that reproduce the issue (and more because I realize that if `on_demand` is uncheck but `on_hand` is filled, the issue arise too)

File: app/services/sets/product_set.rb [hunk 4]
```diff
@@ -114,6 +114,8 @@ def create_variant(product, variant_attributes)
 
       variant = product.variants.create(variant_attributes)
 
+      return false unless variant.save
```
Comment (jibees) [inline app/services/sets/product_set.rb:117]: Actually this one make spec `spec/services/sets/product_set_spec.rb:175` fails... 
@mkllnk what do you think?

File: app/controllers/spree/admin/products_controller.rb [hunk 5]
```diff
@@ -76,10 +76,13 @@ def bulk_update
 
         product_set.collection.each { |p| authorize! :update, p }
 
-        if product_set.save
+        saved = product_set.save
+        errors = product_and_variants_errors(product_set)
+
+        if saved && errors.empty?
```
Comment (mkllnk) [inline app/controllers/spree/admin/products_controller.rb:82]: I think that you need to check only the errors. It doesn't matter if the product got saved but the variants had errors. And if the product wasn't saved, there should always be an error.
```suggestion
        product_set.save
        errors = product_and_variants_errors(product_set)

        if errors.empty?
```

File: app/controllers/spree/admin/products_controller.rb [hunk 6]
```diff
@@ -76,10 +76,13 @@ def bulk_update
...
           redirect_to main_app.bulk_products_api_v0_products_path(bulk_index_query)
-        elsif product_set.errors.present?
-          render json: { errors: product_set.errors }, status: :bad_request
+        elsif errors.any?
+          render json: { errors: errors }, status: :bad_request
```
Comment (mkllnk) [inline app/controllers/spree/admin/products_controller.rb:85]: Oh, I just realise that ProductSet has an `errors` method already. I guess that the only problem is that it includes only the product errors and not the variant errors. If we add the variant errors to the products then this code can stay the same. I show you what I mean in the next comment.

File: app/services/sets/product_set.rb (hunk 4 above)
Comment (mkllnk) [inline app/services/sets/product_set.rb:117]: After seeing the other code, I would now suggest this:
```suggestion
      if variant.errors.present?
        product.errors.merge!(variant.errors)
        return false
      end
```

Then the ProductSet provides these error messages via its own `#errors` method and the old code in the controller should work.

**Review by mkllnk — CHANGES_REQUESTED** [review]
Cool. I have a suggestion to go into a bit of a different direction. See my latest comments below (and ignore the previous ones, I just kept them to show you how I would have written it in that case). I didn't test this and I might be wrong but I think it's worth trying. It should be less code in the end.

File: app/services/sets/product_set.rb (hunk 4 above)
Comment (jibees) [reply app/services/sets/product_set.rb:117]: oh nice one! Will test it ;)

File: app/controllers/spree/admin/products_controller.rb (hunk 6 above)
Comment (jibees) [reply app/controllers/spree/admin/products_controller.rb]: Thanks!

**Comment by jibees** [comment]
Thanks @mkllnk ! I think it's better now. 🙏

File: app/controllers/spree/admin/products_controller.rb [hunk 7]
```diff
@@ -76,7 +76,7 @@ def bulk_update
 
         product_set.collection.each { |p| authorize! :update, p }
 
-        if product_set.save
+        if product_set.save && product_set.errors.empty?
```
Comment (mkllnk) [inline app/controllers/spree/admin/products_controller.rb:79]: I think it would be better if `#save` returned `false` in this case. We could add a line to the end of this method:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6f228781d47552eabf2de7a1a5c020504a9d28ca/app/services/sets/product_set.rb#L96-L100

```rb
product.errors.any?
```

But this works, too. It's just not quite the Rails convention of how `save` works.

File: spec/services/sets/product_set_spec.rb [hunk 8]
```diff
@@ -173,10 +173,8 @@
                 end
 
                 it 'does not create variant and notifies bugsnag still raising the exception' do
-                  expect(Bugsnag).to receive(:notify)
```
Comment (mkllnk) [inline spec/services/sets/product_set_spec.rb:176]: This part of the code is now untested but I'm okay with it.

**Review by mkllnk — APPROVED** [review]
Great! I have one more suggestion but I'll leave it up to you.

File: app/controllers/spree/admin/products_controller.rb (hunk 7 above)
Comment (jibees) [reply app/controllers/spree/admin/products_controller.rb:79]: `product_set.save` returns `true` event if it has errors (I added the line on `update_variants_attributes ` method)

Comment (jibees) [reply app/controllers/spree/admin/products_controller.rb]: Anyway, I think it's ok with `empty?`, here's the commit: 6f228781d

Comment (jibees) [reply app/controllers/spree/admin/products_controller.rb]: Moving to `Test Ready` then ;)

Comment (mkllnk) [reply app/controllers/spree/admin/products_controller.rb]: Ah, yes, perfect!
