### PR TITLE
redirect to shops list when an enterprise is not found

### LINKED ISSUE #4727: User should not see a snail, when accessing OFN via direct link to a shop that does not exist or is inactive
## Description
We have over 8k in AUS and 2.5 in UK events of this type:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5dd433e559edc60018caf959?filters[event.since][0]=30d&filters[error.status][0]=open

Screenshot 2020-01-28 at 15 22 59

Users type the correct shop URL but the shop name refers to a non existing shop or an inactive shop. The user sees a snail (and a bugsnag event is created).
This damages reputation and seo.

## Expected Behavior
The user can be redirected to the list of shops. Ideally an flash message is displayed "The shop you are looking for doesn't exist or is inactive on OFN. Please check other shops."

## Actual Behaviour
Snail.

## Steps to Reproduce
Inexistent enterprise:
https://openfoodnetwork.org.uk/theres-no-place-like-home/shop

Inactive/not visible shop:
https://openfoodnetwork.org.uk/pomeroys-rare-breeds-robyns-famhouse/shop
Create a shop and set it so that it's not visible in the frontoffice then visit it's shopfront using it's permalink.

## Workaround
None.

## Severity
We are talking about hundreds of (potential) customers seeing the OFN snail page.
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: UK and AU live
* Browser name and version: firefox
* Operating System and version (desktop or mobile): osx catalina

## Possible Fix
We just need a redirect to the shop list page and flash message. A few lines of code on the controller.

### PR DESCRIPTION
**Pull request by jeduardo824**
#### What? Why?

This PR closes #4727. I'm just rescuing the exception when the enterprise is not found and redirecting to the shops_path with a flash message.

#### What should we test?

If the user is redirected to the shops_path with a flash message when the enterprise not exists or is unavailable.

#### Release notes

Redirect to list of shops when an enterprise is not found or is unavailable.

Changelog Category: Changed

#### Discourse thread

#2247

### CODE REVIEW

**Comment by jeduardo824** [comment]
I tried to extract this logic to a method but, unfortunately, I got a type mismatch error
Screen Shot 2020-02-19 at 21 23 42

I also tried to call `and return` after the redirect_to, but I got an error of too many redirects.

**Comment by luisramos0** [comment]
ah, I see, it's a problem when the error occurs.
First idea I had was to move back to use the generic rescue at controller level, that way you wont get too many redirects problem I guess.
But maybe the best solution that will also work is to move the rescue to the end of the shop action "def shop"

**Comment by jeduardo824** [comment]
@luisramos0 What do you think about it?

File: spec/controllers/enterprises_controller_spec.rb [hunk 1]
```diff
@@ -139,4 +139,18 @@
...
+    before do
+      spree_get :shop, id: "some_nonexistent_enterprise"
+    end
+
+    it "redirects to shops_path" do
+      expect(response).to redirect_to shops_path
+    end
+
+    it "redirects to shops_path" do
+      expect(request.flash[:error]).to eq(I18n.t(:enterprise_shop_show_error))
```
Comment (luisramos0) [inline spec/controllers/enterprises_controller_spec.rb]: you can move this expect to the previous test or give this test a better name related to showing an error

Comment (jeduardo824) [reply spec/controllers/enterprises_controller_spec.rb]: Sorry. Cmd C + Cmd V problems hahaha.

Comment (jeduardo824) [reply spec/controllers/enterprises_controller_spec.rb]: All good now.

**Comment by RachL** [comment]
Cool!

image


This is ready to go :)

**Comment by sauloperez** [comment]
So happy to merge this one! thanks a lot @jeduardo824 ! I believe this should stop all those annoying 404 Bugsnag notifications.

**Comment by jeduardo824** [comment]
Awesome! I'm here to help!
