### PR TITLE
Include items from resumed orders when mailing producers

### LINKED ISSUE #8320: "Notify producers" is ineffective for orders which have been cancelled then resumed
## Description
This issue relates to orders which have been cancelled, then resumed, in a hub's backoffice. When the "notify producers" button is clicked in the order cycle, emails are not sent to producers of the resumed orders. 

We were alerted to the issue by a hub, who had an order for a customer which was mistakenly cancelled, then resumed. They expected all orders (including this resumed order) to be included in the producers' emails when they clicked the "notify producers" button. They later realised that the producers had not received details of this (resumed) order in their emails, and thus were unable to fulfil the order for the customer. 

## Expected Behavior
The "notify producers" button should send emails to producers included in all orders in that order cycle.

## Actual Behaviour
The "notify producers" button did not trigger emails to be sent to producers included in resumed orders.

## Steps to Reproduce
1. Place an order through a hub, for products from a producer who is not the hub. In the screenshot below, 3 orders were placed in Demo Hub:
- 1 for "Fruit Producer" products that was cancelled and resumed in the back office
- 1 for "Fruit Producer" products that was cancelled via the customer interface
- 1 for "Egg Producer" product that was completed

2. Find your order in the "orders" tab of the backoffice, and click "edit".
3. Click "cancel".
4. Click "resume".
5. Open the "order cycles" tab, find the order cycle in which your order was placed, and click "edit". In our example, the Order Cycle Supplier Totals by Distributer report confirms that a Notify Producers email should be sent to Egg Producer and to Fruit Producer.

6. Check the email account linked to the producer profile, to see if "notify producers" triggered an email to be sent to them. In our example, only the Egg Producer received an email notification.

## Workaround
No workaround available

## Severity
bug-s2

## Your Environment
* Browser name and version: Chrome 94.0.4606.61
* Operating System and version (desktop or mobile): MacOS Catalina, Desktop

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #8320 

Resumed orders were not included in the scope when emailing producers for an OC.

#### What should we test?

Resumed orders should be included when using the "notify producers" button.

#### Release notes

Fixed an issue where resumed orders were not included when emailing producers

Changelog Category: User facing changes

### CODE REVIEW

File: spec/mailers/producer_mailer_spec.rb [hunk 1]
```diff
@@ -103,6 +104,22 @@
...
   end
 
+  context "when a cancelled order has been resumed" do
+    let!(:order_resumed) do
+      order = create(:order, distributor: d1, order_cycle: order_cycle, state: 'complete')
+      order.line_items << create(:line_item, variant: p6.variants.first)
+      order.finalize!
+      order.cancel
+      order.resume
+      order.save
```
Comment (mkllnk) [inline spec/mailers/producer_mailer_spec.rb:114]: I like to use `save!` in specs to make sure that we detect failures here.

**Review by mkllnk — APPROVED** [review]

**Review by jibees — APPROVED** [review]
LGTM. Wondering about the @mkllnk comment and what's the next step then.

File: spec/mailers/producer_mailer_spec.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply spec/mailers/producer_mailer_spec.rb]: Updated :ok_hand:

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

Tested as follows (before staging):
- placed two orders, for a new OC
- cancelled and resumed one of the orders
- looked a the packing report for those orders -> the items for the resumed order appear correctly here
- clicked the "Notify Producers" button, under the respective OC -> verified that the items from the resumed orders are not included
- **staged the PR**
- clicked the "Notify Producers" button again and verified that the nr. of items now match (pic below, packing reports vs. one of the emails to one of the suppliers):

image

Good to go :tada:
