### PR TITLE
Index tax totals correctly for invoice display

### LINKED ISSUE #9605: Tax total shows only total of one tax rate if two have the same percentage
## Description

France has two separate tax rates at 20% but our code is assuming a unique percentage per tax rate. The alternative invoice (used in France) and packing slips use a method that chooses only one of the two 20% rates to display the total of. So if both tax rates are applied in the same order, the tax total is wrong.

## Expected Behavior

Each tax has a separate total on the invoice.

## Actual Behaviour

Each tax rate percentage has a separate total on the invoice and if there are two, only one of them is displayed.

## Steps to Reproduce

1. Create two 20% tax rates.
2. Apply one to products and one to shipping.
3. Create an order with affected items and shipping fee.
4. Display the alternative invoice.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
**bug-s2: a non-critical feature is broken, no workaround**
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

The problem is that we use a hash with the percentage as key:
https://github.com/openfoodfoundation/openfoodnetwork/blob/07018370e03394b636c2b252ba7d865b17c9a92c/app/helpers/checkout_helper.rb#L70-L77

So we can store only one total per percentage. We need to change the format. I would suggest to pass on the original hash (`total`) to the view and have helpers to render the tax rate and the amount.

## Other possibly related bugs

- https://github.com/openfoodfoundation/openfoodnetwork/issues/7983
- https://github.com/openfoodfoundation/openfoodnetwork/issues/5591
- https://github.com/openfoodfoundation/openfoodnetwork/issues/1500

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #9605 

The displayed tax totals were wrong on the alternative invoice template when there were two tax distinct tax rates with the same percentage. The total would display only one of the two.

#### What should we test?

- Have two tax rates in the same zone at 20%, for example one for shipping and one for products.
- Create an order with shipping and products which attract those taxes.
- Display the alternative invoice and check the total.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/helpers/checkout_helper.rb [hunk 1]
```diff
@@ -70,9 +70,11 @@ def display_checkout_tax_total(order)
...
 
-    totals.each_with_object({}) do |(tax_rate, tax_amount), hash|
-      hash[number_to_percentage(tax_rate.amount * 100, precision: 1)] =
-        Spree::Money.new tax_amount, currency: order.currency
+    totals.map do |tax_rate, tax_amount|
+      {
+        amount: Spree::Money.new(tax_amount, currency: order.currency),
+        percentage: number_to_percentage(tax_rate.amount * 100, precision: 1),
+      }
     end
```
Comment (filipefurtad0) [inline app/helpers/checkout_helper.rb:78]: Newb question: the idea with converting the array to a hash is to be able to call `amount` or `percentage` separately, from the same object, right?

File: app/views/spree/admin/orders/_invoice_table2.html.haml [hunk 2]
```diff
@@ -47,12 +47,12 @@
         %strong= @order.has_taxes_included ? t(:total_incl_tax) : t(:total_excl_tax)
       %td{:align => "right", :colspan => "2"}
         %strong= @order.has_taxes_included ? @order.display_total : display_checkout_total_less_tax(@order)
-    - display_checkout_taxes_hash(@order).each do |tax_rate, tax_value|
+    - display_checkout_taxes_hash(@order).each do |tax|
       %tr
         %td{:align => "right", :colspan => "3"}
-          = t(:tax_total, rate: tax_rate)
+          = t(:tax_total, rate: tax[:percentage])
```
Comment (filipefurtad0) [inline app/views/spree/admin/orders/_invoice_table2.html.haml:53]: It could be interesting to display these lines in a ordered fashion, like according to tax rate, or so. Currently, we have this (see pic below), but I think it could fall out of scope for this issue, I can open an issue for this.

image

**Review by filipefurtad0 — APPROVED** [review]
This looks good, thank you for requesting my review :+1:

File: app/helpers/checkout_helper.rb (hunk 1 above)
Comment (mkllnk) [reply app/helpers/checkout_helper.rb:78]: Yes. A hash has unique keys. So if we use the percentage as hash key we can store only one of them. But a list can just have as many items as we need. And the view turns it into a list of rows in the HTML. So the data structure is much closer to what's needed to render.

File: app/views/spree/admin/orders/_invoice_table2.html.haml (hunk 2 above)
Comment (mkllnk) [reply app/views/spree/admin/orders/_invoice_table2.html.haml:53]: Good idea. I added a commit for that.

File: app/helpers/checkout_helper.rb [hunk 3]
```diff
@@ -74,8 +74,9 @@ def display_checkout_taxes_hash(order)
       {
         amount: Spree::Money.new(tax_amount, currency: order.currency),
         percentage: number_to_percentage(tax_rate.amount * 100, precision: 1),
+        rate_amount: tax_rate.amount,
       }
-    end
+    end.sort_by { |tax| tax[:rate_amount] }
```
Comment (filipefurtad0) [inline app/helpers/checkout_helper.rb:79]: Great! Thanks.

I was expecting this change to [break this assertion](https://github.com/openfoodfoundation/openfoodnetwork/blob/8270a3f3868d031a0ed1eceef05659803c9d0db5/spec/system/admin/invoice_print_spec.rb#L259) - but it does not, which means this system spec can be improved to account for the sorting of tax rates. I've addressed it in a separate PR, in this commit 080b2ce9816471c8e2828b58117368a4c7731e01.

**Review by filipefurtad0 — APPROVED** [review]

**Comment by drummer83** [comment]
Thanks for this PR, @mkllnk!

I first tried to reproduce the issue. We can see that the numbers are not correct, because some products as well shipping have a tax rate of 10 %. The 10 % taxes for the products are not taken into account here.
Note: Ignore the 50 % and 25 % taxes, that's a different story.
image

After staging the PR things look much better. The numbers are now correct and we can also see that the order is sorted by percentage.
image

I also verified that the standard invoice hasn't changed. :+1: 

This is Ready to Go! :tada:
