### PR TITLE
Clears cache around examples

### LINKED ISSUE #11010: [Flaky] rspec ./spec/system/consumer/caching/shops_caching_spec.rb:17
### What we should change and why (this is tech debt)

`rspec ./spec/system/consumer/caching/shops_caching_spec.rb:17`

```
Failures:

  1) Shops caching caching enterprises AMS data caches data for all enterprises, with the provided options
     Failure/Error: expect(Rails.cache.exist?(key, options)).to be true
     
       expected true
            got false
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_shops_caching_caching_enterprises_ams_data_caches_data_for_all_enterprises__with_the_provided_options_155.png
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5263043188/jobs/9512817149
https://openfoodnetwork.slack.com/archives/C012LE8LLDS/p1686718490274599?thread_ts=1686601349.929099&cid=C012LE8LLDS

### PR DESCRIPTION
**Pull request by filipefurtad0**
for specs testing cache

#### What? Why?

- Closes #11010

I think cached values were leaking from `spec/system/consumer/caching/darkswarm_caching_spec.rb` to `spec/system/consumer/caching/shops_caching_spec.rb`;

This PR clears cache around these specs, making them independent of each other.

#### What should we test?

- Green build

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]
LGTM :ok_hand:

File: spec/system/consumer/caching/darkswarm_caching_spec.rb [hunk 1]
```diff
@@ -19,6 +19,11 @@
   }
   let(:exchange) { order_cycle.exchanges.outgoing.where(receiver_id: distributor.id).first }
 
+  around do |example|
+    Rails.cache.clear
+    example.run
+  end
```
Comment (mkllnk) [inline spec/system/consumer/caching/darkswarm_caching_spec.rb:25]: This clears the cache before these examples run but not after. So that specs protect themselves from a stale cache but they don't protect other specs from their own modifications.

These specs use the `caching: true` tag. It may be better to move this code into the spec helper and clear the cache there.

**Review by mkllnk — APPROVED** [review]
Great, good to know that this fixes some spec failures.
