### PR TITLE
[Flaky spec] Make sure clone link is present before clicking

### LINKED ISSUE #14182: [Flaky] ./spec/system/admin/products_v3/actions_spec.rb:
### What we should change and why (this is tech debt)

```
Failures:

  1) As an enterprise user, I can perform actions on the products screen actions menu clone Cloning product shows the cloned product on page when clicked on the cloned option
     Failure/Error: parent.public_send(controller_name).find(params[:id])
     
     NoMethodError:
       undefined method 'variants' for nil
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_enterprise_user_i_can_perform_actions_on_the_products_screen_actions_menu_clone_cloning_product_shows_the_cloned_product_on_page_when_clicked_on_the_cloned_option_2.png

     
     # ./app/controllers/admin/resource_controller.rb:155:in 'Kernel#public_send'
     # ./app/controllers/admin/resource_controller.rb:155:in 'Admin::ResourceController#find_resource'
     # ./app/controllers/admin/resource_controller.rb:137:in 'Admin::ResourceController#load_resource_instance'
     # ./app/controllers/admin/resource_controller.rb:108:in 'Admin::ResourceController#load_resource'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   ./spec/system/admin/products_v3/actions_spec.rb:184:in 'block (4 levels) in <top (required)>'

Finished in 4 minutes 8.6 seconds (files took 2.31 seconds to load)
83 examples, 1 failure

Failed examples:

rspec ./spec/system/admin/products_v3/actions_spec.rb:203 # As an enterprise user, I can perform actions on the products screen actions menu clone Cloning product shows the cloned product on page when clicked on the cloned option
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/24542585782/job/71751398658

### PR DESCRIPTION
**Pull request by rioug**
## What? Why?

- Closes #14182  

~~I am not sure if that's going to fix the issue but it looks like an obvious thing to fix.~~

Turbo prefetches links when you hover them, for this flaky test we are testing the presence of some menu which resulted in a prefetch request which would sometimes fail. I don't think it's really useful in the this context to prefetch the link, so I disabled it. It should also make specs a bit faster, as we won't be loading page we don't care about.

## What should we test?

Green spec :green_circle: 

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/support/products_helper.rb [hunk 1]
```diff
@@ -103,6 +103,7 @@ def all_input_values
   def click_product_clone(product_name)
     within row_containing_name(product_name) do
       page.find(".vertical-ellipsis-menu").click
+      expect(page).to have_link "Clone"
       click_link('Clone')
```
Comment (dacook) [inline spec/support/products_helper.rb:107]: I think `click_link` would already be waiting the default 20 seconds for the clone link to appear. So  unfortunately I don't think this will make a difference.

**Review by dacook — COMMENTED** [review]
Looking at the linked error message, it appears to be a data set up issue.
Also I don't think this change will have any functional difference (but could be wrong).

File: spec/support/products_helper.rb (hunk 1 above)
Comment (rioug) [reply spec/support/products_helper.rb:107]: You are right ! I still don't really know what's causing this error. I'll keep an eye on it for now

Comment (rioug) [reply spec/support/products_helper.rb:107]: The actual error seems to be 
```
./app/controllers/admin/resource_controller.rb:155:in 'Kernel#public_send'
```
which is weird because the products_v3 controller doesn't inherit from the ressource controller...

**Review by mkllnk — APPROVED** [review]
How did you check that this fixes it?

This change makes sense in any case though. So let's merge.

**Comment by rioug** [comment]
> How did you check that this fixes it?

My investigation revealed that the error in the specs were coming from this prefetch request. I don't really have a way to test it beside merging and seeing if the flaky spec goes away.

**Comment by dacook** [comment]
Thanks, and great work! 
I wondered if it was the prefetch, but couldn't imagine how a variant ID could be missing. Now I think perhaps it's because the database cleaner has already begun removing the variant, while the prefetch request continues to process in parallel.

🤔 I would think that capybara/chrome would have cancelled the ajax request at the browser level, but the web server continues to process it. Maybe we can configure rspec to end any unfinished requests once the spec is complete. 
Or maybe we'll never see the issue again and don't need to think about it anymore 🤞
