### PR TITLE
Fix error on summarising total_units in Order Cycle Supplier Totals report

### LINKED ISSUE #10847: ActionView::Template::Error in ReportJob@default
## Error in OpenFoodNetwork UK

**ActionView::Template::Error** in **ReportJob@default**
String can't be coerced into BigDecimal

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/643fc2072915e90008ca984e?event_id=6462c62a00bd2de465c90000&i=gh&m=ci)

## Stacktrace

    lib/reporting/reports/orders_and_fulfillment/order_cycle_supplier_totals.rb:30 - block in rules
    lib/reporting/report_row_builder.rb:49 - build_summary_row
    lib/reporting/report_rows_builder.rb:84 - block in group_and_sort
    lib/reporting/report_rows_builder.rb:79 - each
    lib/reporting/report_rows_builder.rb:79 - group_and_sort
    lib/reporting/report_rows_builder.rb:71 - build_tree
    lib/reporting/report_rows_builder.rb:15 - grouped_data
    lib/reporting/report_template.rb:12 - grouped_data
    app/views/admin/reports/_table.html.haml:9 - _app_views_admin_reports__table_html_haml___3187840633409250793_157820
    lib/reporting/report_renderer.rb:56 - to_html
    lib/reporting/report_renderer.rb:52 - public_send
    lib/reporting/report_renderer.rb:52 - render_as
    lib/reporting/report_template.rb:8 - render_as
    app/jobs/report_job.rb:11 - perform

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/643fc2072915e90008ca984e?event_id=6462c62a00bd2de465c90000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #10847 

#### What should we test?

- Deploy to UK staging or FR staging, both seem to have old, invalid data.
- Visit Order Cycle Supplier Totals report.
- Set the start date to the beginning of 2020 or earlier.
- Choose to display summary rows and don't download CSV (which doesn't have summaries).
- The report should display without error.
- The summary for Total Units should be empty if one of the rows has an empty value. Then you covered the previously failing scenario.
- The summary for Total Units should be the correct sum of the columns above if they all contain numbers (different date range).

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb [hunk 1]
```diff
@@ -29,6 +29,81 @@
...
+    let(:variant) { item.variant }
+
+    it "contains a sum of total items" do
+      variant.product.update!(variant_unit: "items", variant_unit_name: "bottle")
+      variant.update!(unit_value: 6) # six-pack
+      item.update!(final_weight_volume: nil) # reset unit information
+      item.update!(quantity: 3)
+
+      expect(table_headers[4]).to eq "Total Units"
+      expect(report_table[0][4]).to eq 18 # = 3 * 6, three six-packs
```
Comment (jibees) [inline spec/lib/reports/orders_and_fulfillment/orders_cycle_supplier_totals_report_spec.rb:43]: 🙏

**Review by jibees — APPROVED** [review]
Thanks! 
(The PR is also very pleasant to read)

**Review by abdellani — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @mkllnk,
I finally had a look at this one. 
Strangely I couldn't reproduce the original error message anymore. Instead I see a different one in bugsnag for all staging servers.

It seems like something has changed on master in the meantime, now covering the previous error?

## Before staging
Testing as super admin.

https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/647c8b82ded5750008fb49dd?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging

image

```
app/services/variant_units/variant_and_line_item_naming.rb:38 full_name
lib/reporting/reports/orders_and_fulfillment/base.rb:44 block in variant_name
lib/reporting/report_row_builder.rb:24 block in build_row
lib/reporting/report_row_builder.rb:20 transform_values
lib/reporting/report_row_builder.rb:20 build_row
lib/reporting/report_rows_builder.rb:42 block in computed_data
lib/reporting/report_rows_builder.rb:41 map
lib/reporting/report_rows_builder.rb:41 computed_data
lib/reporting/report_rows_builder.rb:15 grouped_data
lib/reporting/report_template.rb:12 grouped_data
app/views/admin/reports/_table.html.haml:9 _app_views_admin_reports__table_html_haml__26558476540845804_162960
lib/reporting/report_renderer.rb:56 to_html
lib/reporting/report_renderer.rb:52 public_send
lib/reporting/report_renderer.rb:52 render_as
lib/reporting/report_template.rb:8 render_as
app/jobs/report_job.rb:11 perform
Caused By: NoMethodError · undefined method `downcase' for nil:NilClass
app/services/variant_units/variant_and_line_item_naming.rb:38 full_name
lib/reporting/reports/orders_and_fulfillment/base.rb:44 block in variant_name
lib/reporting/report_row_builder.rb:24 block in build_row
lib/reporting/report_row_builder.rb:20 transform_values
lib/reporting/report_row_builder.rb:20 build_row
lib/reporting/report_rows_builder.rb:42 block in computed_data
lib/reporting/report_rows_builder.rb:41 map
lib/reporting/report_rows_builder.rb:41 computed_data
lib/reporting/report_rows_builder.rb:15 grouped_data
lib/reporting/report_template.rb:12 grouped_data
app/views/admin/reports/_table.html.haml:9 _app_views_admin_reports__table_html_haml__26558476540845804_162960
lib/reporting/report_renderer.rb:56 to_html
lib/reporting/report_renderer.rb:52 public_send
lib/reporting/report_renderer.rb:52 render_as
lib/reporting/report_template.rb:8 render_as
app/jobs/report_job.rb:11 perform
```

## After staging
Same as before staging. I couldn't see any difference.

## Result
I can't tell if this PR is an improvement covered by a new (independent?) issue. 
Adding the feedback needed label to hear what you think.

**Comment by mkllnk** [comment]
Let's get the other PR merged first then. I will rebase after and then maybe this issue will be visible again.

**Comment by mkllnk** [comment]
The other PR has been merged, this is rebased and ready for testing again.

**Comment by drummer83** [comment]
Thanks, @mkllnk!

### Before staging
I could now reproduce the previous error on staging UK: https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/643fc2072915e90008ca984e?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging

On staging AU the report renders correctly within a few seconds, so there seems to be no such invalid data causing the problem.

### After staging
- Setting the start date to 01.01.2020 thee report is rendering after 110 s, so just before the timeout. :heavy_check_mark: 
- I have checked that the summary values are calculated correctly. :heavy_check_mark: 
image
- If a Total Unit value is empty, then the summary row is also empty. :heavy_check_mark: 
image
- I checked the xlsx export as well. The calculation is correct and summary is empty when Total Units is empty. :heavy_check_mark: 
- If the report generation is taking longer, the download link is sent via email. :heavy_check_mark: 

### New Bugsnag issue
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/648314d716169200083dc080?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging

- It seems like the download link can only be opened in the browser session where it was created. I think this is new behaviour. I like it with respect to data privacy but if you are in a different session, you get an error 500. I think we should display the 'not authorized' flash message as we do in other use cases.
- Even after logout the report can be downloaded.
image

I created #10972 for this.

I think we can merge this and the found issue may be unrelated to this PR and be an edge case.
However I am leaving for you to merge.

Thanks!

**Comment by mkllnk** [comment]
I think that error is linked to https://github.com/openfoodfoundation/openfoodnetwork/pull/10812. That has been merged two weeks ago though, so I'm surprised that you are encountering it now. Might there be an old browser session still referring to old code?

**Comment by drummer83** [comment]
> Might there be an old browser session still referring to old code?

This could be true. I had to delete cookies to make the error disappear. Now the download can be started from any session again. :+1: 
No Bugsnag triggered anymore. :+1: 
Closing #10972 then. :+1: 

Thanks, @mkllnk!
