### PR TITLE
Fix decimal display for imperial weight on Cart, Order Confirmation page and Confirmation emails

### LINKED ISSUE #9720: Weird decimals when using 12.5 as weight in imperial metric system
## Description

Similar to #9493 and #9679
When adding 12.5 as product weight in an imperial (oz) system, it is displayed in cart and order confirmation with a huge number of unnecessary decimals.

## Expected Behavior

Just keep 12.5 - no additional decimals.

## Actual Behaviour

Cart:
image

Order confirmation:
image

## Steps to Reproduce

1. Create or edit a product with weight in oz
2. Enter 12.5 as weight
3. Save
4. As a customer put the product in your cart
5. Check the /cart page
6. :boom: 
7. Ckeck out
8. Check the order confirmation
9. :boom:

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: staged [d81037d](https://github.com/openfoodfoundation/openfoodnetwork/commit/d81037d6581f4ff88ad42b0d6571865388fec4f1)
* Browser name and version: Firefox 104.0
* Operating System and version (desktop or mobile): Desktop Windows 10 Enterprise

## Possible Fix

See #9497?

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #9720

When adding 12.5 as product weight in an imperial (oz) system, it is displayed in cart and order confirmation with a huge number of unnecessary decimals, it also happens in the order confirmation emails. 

#### What should we test?
- Create or edit a product with weight in oz
- Enter a weight with a decimal ie 11.3 
- Save
- As a customer put the product in your cart
- Check the /cart page

Mushroom_in_cart
- Check out
- Check the order confirmation

confirmed_mushroom_order
- Check email confirmations, if using a local environment you should see emails being generated in `tmp/letter_opener/` , check the two latest generated emails

mushroom_confirmation_email
 
#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

#### Dependencies
N/A

#### Documentation updates
N/A

### CODE REVIEW

File: app/services/variant_units/option_value_namer.rb [hunk 1]
```diff
@@ -56,7 +56,7 @@ def option_value_value_unit
     def option_value_value_unit_scaled
       unit_scale, unit_name = scale_for_unit_value
 
-      value = BigDecimal(@variant.unit_value / unit_scale, 6)
+      value = BigDecimal(@variant.unit_value / unit_scale, 6).truncate(2)
```
Comment (rioug) [inline app/services/variant_units/option_value_namer.rb:60]: Alternative solution would be to use `number_to_rounded` helper, but we would get 12.50 instead of 12.5

```ruby
::ActiveSupport::NumberHelper.number_to_rounded(value, precision: 2)
```

Comment (dacook) [reply app/services/variant_units/option_value_namer.rb:60]: Thanks Gaetan, it's great to point out the other options you considered.

From what I understand, truncating this number to maximum of two decimal places makes the most sense.

File: app/services/variant_units/option_value_namer.rb [hunk 2]
```diff
@@ -56,7 +56,7 @@ def option_value_value_unit
...
```
Comment (dacook) [inline app/services/variant_units/option_value_namer.rb:59]: But couldn't help but try to understand this further.
I'm unsure what the `6` is doing on this line. Apparently it's the number of [significant digits](https://ruby-doc.org/stdlib-2.5.1/libdoc/bigdecimal/rdoc/BigDecimal.html#:~:text=terminate%20the%20value.-,digits,the%20number%20of%20significant%20digits%20is%20determined%20from%20the%20initial%20value.,-The%20actual%20number) for the new BigDecimal, but it's obviously not limiting the number that we're seeing on the screen. So maybe it's no longer needed.

So I'm curious to see if this refactor works. Would you like to apply and see if tests still pass?
```suggestion
      value = (@variant.unit_value / unit_scale).to_d.truncate(2)
```

**Review by dacook — CHANGES_REQUESTED** [review]
Looks good to me, thanks Gaetan!

I've made a suggestion to refactor, can you please apply it and see if it works (or comment if you think I'm wrong)?

Otherwise all good, just add a comment to say that it is ready for testing.

File: app/services/variant_units/option_value_namer.rb (hunk 2 above)
Comment (rioug) [reply app/services/variant_units/option_value_namer.rb:59]: Same I am not sure what the `6` is doing here. It was added by @jibees here : https://github.com/openfoodfoundation/openfoodnetwork/pull/9497/commits/4452ad2c519a59f790985c460a2b79346a3e43f1 maybe he could provide more context.

Your suggested change works fine.

**Comment by rioug** [comment]
@dacook I applied your suggested change, ready to review.

File: app/services/variant_units/option_value_namer.rb (hunk 2 above)
Comment (dacook) [reply app/services/variant_units/option_value_namer.rb]: Great, thanks for looking into that! I guess it was intended to do the same thing as `.truncate(6)`.. but it obviously didn't work.

**Review by dacook — APPROVED** [review]
Great, I can see all specs pass so I think we're good!

**Comment by filipefurtad0** [comment]
Hi @rioug ,

Thanks for addressing this one.

I've observed the issue in:
 - cart
 - order summary step (split checkout)
 - order confirmation page
 - order confirmation email
 - order invoice

After staging the PR, we can verify the issue is solved:

 - cart 

image

 - order summary step (split checkout)

image

- order confirmation page

image

- order confirmation email

image

- order invoice

image


Awesome :tada: 
Merging.
