### PR TITLE
[Enterprise->Create] Show correct error message when user inputs url in instagram field

### LINKED ISSUE #10216: [Enterprise->Create] Wrong input in Instagram field leads to wrong error and being stuck in the process
## Description
When creating a new enterprise from the register page, if you put an url in the Instagram field, the displayed error message is misleading: "Failed to update your enterprise. Please ensure all fields are completely filled out". 

If you click the "back" button to check if previous fields are filled out, you're stuck in the process at step 4.

## Expected Behavior
The error should be "Instagram must be user name only" (same error than the one displayed when you edit social networks from Enterprises > Settings > Social).

## Steps to Reproduce
1. Create a new enterprise from the /register page 
3. At the end of the process, input "www.instagram.com/coopcircuits/ " in the Instagram field
4. See the error, go back on previous page, see that you're stucked

### Error when creating a new enterprise 👎
https://user-images.githubusercontent.com/28386648/210061911-d0a307a1-943e-41a1-acf6-ba41494e2a4e.mov

### Error when editing Instagram from admin dashboard (admin/enterprises/xxxx/edit#!#social_panel) 👍
Screen Shot 2022-12-30 at 11 32 14

## Workaround
Quit and go to admin dashboard.

## Severity
bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by binarygit**
#### What? Why?

- Closes #10216

#### What should we test?

- Visit page `/register`
- Register an enterprise
- At the last page `Social`, input a url like `www.github.com` in the `Instagram:` field
- Ascertain that the relevant error shows up below the field.

Screenshot 2023-01-04 at 20-49-01 Register - OFN Demo Site

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee [hunk 1]
```diff
@@ -55,6 +55,10 @@ angular.module('Darkswarm').factory "EnterpriseRegistrationService", ($http, Reg
       ).catch((response) ->
         Loading.clear()
         alert(t('failed_to_update_enterprise_unknown'))
```
Comment (jibees) [inline app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee:57]: Suprisly, we don't have any form errors displaying on that case. Only a popup alert.

File: app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee [hunk 2]
```diff
@@ -55,6 +55,10 @@ angular.module('Darkswarm').factory "EnterpriseRegistrationService", ($http, Reg
...
+        if response.data.errors.instagram
+          igErr = document.querySelector("#instagram-error")
```
Comment (jibees) [inline app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee:59]: Not generic, but should do the job. I'm wondering if we wanted to make a generic solution, or make a quick but a bit dirty solution as we don't want to spend to much time on it.

**Review by jibees — COMMENTED** [review]
This seems a great quick solution. 
But I've one concern: I'm wondering if this one solves the original issue, which is that user is block if they get back and then want to step forward. I don't think so, but I could be wrong. 
@binarygit any thoughts?

**Comment by binarygit** [comment]
@jibees you are correct. My commit didnot fix the bug where if the user went backwards they would be stuck. I just pushed a new commit that solves that bug.

The implementation has changed a bit though. Before we updated the `enterprise` after the `about` section. Now, the enterprise only gets updated after the `social` section.
The user got stuck if they entered a url in the ig field and then navigated back to the `about` section, then tried to move forward because we were `updating` the enterprise when they clicked the `continue` btn in the `about` section.

File: app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee (hunk 2 above)
Comment (binarygit) [reply app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee:59]: yes, it is a bit dirty. But not sure how to make it more clean :sweat_smile: 
If you could point me to a commit or an article that would help me, I will try to make it more clean. Just don't know angular well enough

**Review by jibees — COMMENTED** [review]
Seems like this part of code is a bit creepy, but let's make a quick solution.

I'd be happy if you could provide a spec as well, on the particular point we're trying to solve (original issue). What do you think?

**Comment by jibees** [comment]
I've added a spec, I hope this one is ready now.

**Review by mkllnk — CHANGES_REQUESTED** [review]
Spec fails. :disappointed:

**Comment by filipefurtad0** [comment]
I've tried to commit to this branch to fix the spec but - don't know why - GH created a new branch. It's [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10518/).

I'll need to open an issue, as it seems that the info on the error message does not correspond to the validation over the Instagram address.

**Review by mkllnk — APPROVED** [review]

File: app/views/registration/steps/_about.html.haml [hunk 3]
```diff
@@ -10,7 +10,7 @@
             %span{ ng: { class: "{brick: !enterprise.is_primary_producer, turquoise: enterprise.is_primary_producer}" } }
               {{ enterprise.name }}
 
-    %form{ name: 'about', novalidate: true, ng: { controller: "RegistrationFormCtrl", submit: "update('images',about)" } }
+    %form{ name: 'about', novalidate: true, ng: { controller: "RegistrationFormCtrl", submit: "selectIfValid('images', about)" } }
```
Comment (dacook) [inline app/views/registration/steps/_about.html.haml:13]: I checked in case we need to do this on any other steps, but it seems not.

File: app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee (hunk 2 above)
Comment (dacook) [reply app/assets/javascripts/darkswarm/services/enterprise_registration_service.js.coffee:59]: I was also wondering if we should support other fields here, but it seems this is the only one with special validation.

**Review by dacook — COMMENTED** [review]
The code updates look fine 👍 

But I checked it out locally to make sure we're covering the back/forth well enough. I wasn't able to trigger an error at all! Am I testing wrong?

Mar-08-2023 11-13-22

https://user-images.githubusercontent.com/4188088/223586386-2f7749ac-3cad-4220-8dcb-8a6fa00da10d.mp4

**Comment by jibees** [comment]
Thanks for your attention @dacook

I read the code around instagram validation, in order to be more precise in my anwser.

 1. `instagram` is an attribute of the `Entreprise` model, validating with a regexp:
https://github.com/openfoodfoundation/openfoodnetwork/blob/eb7d20d74d3fa35446fc93b73389ae83df369030/app/models/enterprise.rb#L103
 2. the regexp is the following: `\A[a-zA-Z0-9._]{1,30}([^\/-]*)\z` and can be tested [here](https://rubular.com/r/Gl0ak5OZh7IizH).
 3. Field instagram is _corrected_ before being assignated, via `correct_instagram_url` method:
https://github.com/openfoodfoundation/openfoodnetwork/blob/eb7d20d74d3fa35446fc93b73389ae83df369030/app/models/enterprise.rb#L460-L463

Which basically transform:
 - `www.instagram.com/InStAgRaM` to `instagram`, which is valid via the regexp ✅ 
 - `www.instagram.com/InStAgRaM/` to `instagram/`, which is not valid via the regexp ❌

▶️ That's why, when you test with `www.instagram.com/InStAgRaM` it's valid... You should test with `www.instagram.com/InStAgRaM/` (as done in the automatic spec): it's invalid (yes, it's subtile ...)


But I agree, this method `correct_instagram_url` could be improved a lot ;)

**Comment by dacook** [comment]
🤦 Oh, I didn't see the slash for some silly reason!

When I view somebody's page on instagram, I notice the slash is always included in the URL (this is standard web behaviour). So copy/pasting the URL would never work.
So if we already strip the start of the URL (`https://www.instagram.com/`), we might as well also strip the trailing slash (`/`).

I think that would be a really helpful improvement (it will save many users from ever getting an error), so while I'm here I decided to see if it was a simple fix. I think it is!

**Review by jibees — APPROVED** [review]
Thanks a lot @dacook ! 
I think this one is ready to test (great team work ;))

**Comment by drummer83** [comment]
Hi @binarygit, @dacook, @jibees,

Thanks for teaming up on this one! :muscle: 

I have tested the register process before and after this PR. Before I could reproduce the situation of being stuck. After the PR I did not get stuck anymore. The code accepts some sort of URL and - if it's not an instagram URL - provides a proper error message asking for the user name only.

Left: BEFORE THIS PR; Right: AFTER THIS PR;

https://user-images.githubusercontent.com/1790176/226208238-9ae2f611-e301-4903-a905-321d51ea0d4b.mp4

_
Using a non-instagram URL:

https://user-images.githubusercontent.com/1790176/226208256-cf284416-ceb8-4a60-802d-20ff79d01c91.mp4

### Result
I think this one is ready to go! Thank you all! :partying_face:
