### PR TITLE
On user confirmation, retrieve and link all orders to the new user that were already placed with the same email

### LINKED ISSUE #7905: Orders placed as guest customer cannot be viewed after sign-up
## Description

After a first (and following) successful orders placed as a `guest`, a customer which signs-up (and logs in) cannot view these orders on `/account#/orders`. It also cannot check the balance on that shop, under `/account#/transactions#`.

These are visible for the admin as usual.

## Expected Behavior

After signing up, a customer should be able to view orders placed before sign up (as a guest customer). Also, the customer should be able to see its balance, for that shop.

## Actual Behaviour

After signing up, a customer is not able to view orders placed before sign up (as a guest customer). Customer balance is not visible either.

## Steps to Reproduce

0. As a Hub/Shop, set it your shop to allow guest checkout. (admin/enterprises/<shop_permaling>/edit#/shop_preferences)
1. As a guest customer, place one or more orders (using the same email address) in a Hub
2. Sign up and log in to the account
3. Go to `/account#/orders` -> no orders appear
4. Notice that `/account#/transactions#` the hub from which the orders were placed appears, but no transactions are visible

## Animated Gif/Screenshot

Peek 2021-07-09 10-43

## Workaround

None for the customer. An idea would be to use the order number to view the order, but it leads to an authorization error (see video).

## Severity

I'm not sure. From process an S2, but maybe not occurring that often, so maybe S3.

## Your Environment

* Version used: ~~v3.8.3~~ at least since v3.8.4.
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #7905

#### What should we test?
Pretty well explained in the linked issue:
 - As a Hub/Shop, set it your shop to allow guest checkout. (`/admin/enterprises/<shop_permaling>/edit#/shop_preferences`)
 - As a guest customer, place one or more orders (using the same email address) in a Hub
 - Sign up and log in to the account still with the same email address
 - Go to `/account#/orders` -> see that all already placed orders are here
 - Notice that `/account#/transactions` transactions are visible

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/controllers/user_confirmations_controller.rb [hunk 1]
```diff
@@ -36,6 +36,10 @@ def create
   def show
     self.resource = resource_class.confirm_by_token(params[:confirmation_token])
 
+    Spree::Order.placed_by_customer_email(resource.email).each do |order|
```
Comment (jibees) [inline app/controllers/user_confirmations_controller.rb:39]: Are you sure that, at this point, user is pretty well confirmed?

File: app/models/spree/order.rb [hunk 2]
```diff
@@ -141,6 +141,11 @@ def states
         joins('LEFT OUTER JOIN spree_products ON (spree_products.id = spree_variants.product_id)')
     }
 
+    scope :placed_by_customer_email, lambda { |email|
+      joins('LEFT OUTER JOIN customers ON (customers.id = spree_orders.customer_id)').
```
Comment (jibees) [inline app/models/spree/order.rb:145]: I decided to join on `customers.email` and not on `order.email`, but maybe I'm wrong.
@mkllnk any tips?

**Comment by jibees** [comment]
I'd be happy if @mkllnk could review it, since I'm not sure this is the way to go here and this part of code is a bit sensitive. Thanks! 🙏

File: app/controllers/user_confirmations_controller.rb (hunk 1 above)
Comment (mkllnk) [reply app/controllers/user_confirmations_controller.rb:39]: Uh, this is getting a bit complicated. Don't we do this already? No, I found two similar actions:

* When a user is created, we associate all customer records by email.
* When an order is validated, we associate a customer record.

Now, I think, we want to find guest orders when a customer record is created. That should happen in the model, possibly when building the customer record (before saving).

A view is not the right place to modify records. It leaves the database in an inconsistent state if nobody looks at that page and it does it too often if you look at the page several times.

We could do it in a background job but it's not an expensive operation. I think that saving this with a new customer record would be best. Once the customer record is there, you can't check out as guest with the same email.

File: app/models/spree/order.rb [hunk 3]
```diff
@@ -141,6 +141,11 @@ def states
...
+        where('customers.email = ?', email)
```
Comment (mkllnk) [inline app/models/spree/order.rb:146]: Why do you do an outer join? Wouldn't it be better to just join the customers?

**Review by mkllnk — CHANGES_REQUESTED** [review]

File: app/controllers/user_confirmations_controller.rb (hunk 1 above)
Comment (jibees) [reply app/controllers/user_confirmations_controller.rb:39]: > Now, I think, we want to find guest orders when a customer record is created.

Not sure to understand your point here.

Shouldn't we do this after a user is created?

**Comment by jibees** [comment]
I think it's better now, closer to the model. 
Waiting for you review @mkllnk ;) 🙏

File: app/models/spree/order.rb [hunk 4]
```diff
@@ -141,6 +141,11 @@ def states
         joins('LEFT OUTER JOIN spree_products ON (spree_products.id = spree_variants.product_id)')
     }
 
+    scope :placed_by_customer_email, lambda { |email|
+      joins('JOIN customers ON (customers.id = spree_orders.customer_id)').
```
Comment (mkllnk) [inline app/models/spree/order.rb:145]: Even easier:
```suggestion
      joins(:customer).
```

I compared the two:

```rb
Spree::Order.placed_by_customer_email(nil).to_sql
=> "SELECT \"spree_orders\".* FROM \"spree_orders\" JOIN customers ON (customers.id = spree_orders.customer_id) WHERE (customers.email = NULL)"

Spree::Order.joins(:customer).where(customer: {email: nil}).to_sql
=> "SELECT \"spree_orders\".* FROM \"spree_orders\" INNER JOIN \"customers\" \"customer\" ON \"customer\".\"id\" = \"spree_orders\".\"customer_id\" WHERE \"customer\".\"email\" IS NULL"
```

But I have another idea I'll lay out further down.

File: app/models/spree/user.rb [hunk 5]
```diff
@@ -113,6 +113,12 @@ def associate_customers
       self.customers = Customer.where(email: email)
     end
 
+    def associate_orders
+      Spree::Order.placed_by_customer_email(email).each do |order|
+        order.associate_user!(self)
+      end
```
Comment (mkllnk) [inline app/models/spree/user.rb:119]: I just noticed that the `where` clause is the same as in `associate_customers`. So this could be a lot simpler and faster:
```suggestion
      Spree::Order.where(customer: customers).find_each do |order|
        order.associate_user!(self)
      end
```

We don't need the scope and we don't need to join. Sorry for being a bit picky here but the less code the less maintenance for our future selves.

**Review by mkllnk — CHANGES_REQUESTED** [review]
This is great! Much better place in the user model. Now I have only one suggestion to use less code. :smile:

**Comment by jibees** [comment]
> Now I have only one suggestion to use less code.

Thanks for those kind of suggestion. I must admit that I'm not confident with this kind of code, and it's a bit frustrating, but anyway, thanks it's cleaner now!

**Review by mkllnk — APPROVED** [review]
Great!

I know that this is not really your field of expertise but you are doing really well! I'm always impressed.

**Comment by filipefurtad0** [comment]
Hey @jibees,

Awesome.
This just works :sparkles: 

After:
- an order is created for the guest customer
- the customer registers
- and logs-in
- the "guest-order" can be found under the `/account#/orders`
- the customer balance is correct, and appears on `/account#/transactions`


On the video below, the first moment shows the guest order; after that, there is a tab switch (I'm not sure this is entirely clear) and the user proceeds to visit  `/account#/orders` and `/account#/transactions`, after logging in:

Peek 2022-06-21 17-56

Transactions page:
image

This looks great. Good to go!

(I was surprised the payments are there... But I guess the reason why this works is because payments are associated with the order, and not the user, right?)

**Comment by jibees** [comment]
> But I guess the reason why this works is because payments are associated with the order, and not the user, right?

Yes, I think so!
