### PR TITLE
Display only per_item fees for oc incoming exchange #11326

### LINKED ISSUE #11326: [Order Cycles] Incoming exchange accepts supplier fees with order-based calculators
## Description

In the scope of #11013, we've discussed the case of OC coordinators adding supplier fees, which are applied over the order.
While we've mentioned this might be an edge case, it would be good to:
- query production DBs to assess how often this is the case (incoming exchanges with supplier fees which are order based-calculators)
- prevent OC incoming exchanges from adding supplier fees with order-based calculators
- maybe finally, migrate existing fees, or contact users? Unsure about how to deal with the existing cases.

A PR to close this issue would focus on filtering the options on the incoming exchange, to display only line-item based calculators.

## Expected Behavior

Incoming exchanges only display supplier fees with line-item-based calculators

## Actual Behaviour

Incoming exchanges accepts supplier fees, with all calculator types (line item and order based)

## Steps to Reproduce

Create a coordinator and a supplier enterprise; having granted the required permissions:

0. As the supplier, create an enterprise fee, with a calculator which operates at the order level, for example, `flat-rate per order`.
1. As a coordinator, create an order cycle
2. In the incoming exchange, add the previously mentioned supplier
3. Notice you can add the supplier order-based calculator fee

## Animated Gif/Screenshot

-

## Workaround

Incoming exchange: Add line-items calculators instead; leave your order based calculators for the outgoing exchage

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.4.5
* Browser name and version: Firefox 115
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by abdulazizali77**
Add per_item param to EnterpriseFee angular service and rails controller

#### What? Why?

- Closes #11326

image

The order cycle incoming exchange should only show per_item fees. 
Solution was to pass additional parameter to the EnterpriseFee service/controller and get the appropriate fee scope

#### Uncertain
- Add new scopes in EnterpriseFee?
- Make scopes additive?
- Dont modify EnterpriseFee service call in EditController ? Call directly in IncomingController
- Should Weight calculators be explicitly filtered?
#### What should we test?
- Add a new per item EnterpriseFee for Fred's Farm
- Add a new per order EnterpriseFee2 for Fred's Farm
- Go to the Order Cycles Incoming Products page. Select Fred's Farm and click 'Add Fee' . Select Fred's Farm in the first dropdown
- Click on fee dropdown underneath, only the per item EnterpriseFee should display. Previously it would display both per item and per order EnterpriseFee 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [X] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Tests
- [] Unit tests - EnterpriseFee service
- [X] Unit tests - EnterpriseFee controller
- [X] Unit tests - Order cycle Incoming view

### CODE REVIEW

**Comment by abdulazizali77** [comment]
@sigmundpetersen PTAL and review. Apologies for the delay!

**Comment by abdulazizali77** [comment]
> Great work, thank you!
> 
> I note that the per_order flag is unused, and would generally avoid adding unused features, even when they are simple. But it seems harmless here.
> 
> `±` It's a pretty specific requirement, so could you please also cover it in a system (browser) spec too? I'm not sure exactly the best place to test this, but perhaps you can add a simple change to one of the specs under here?https://github.com/openfoodfoundation/openfoodnetwork/tree/master/spec/system/admin/order_cycles/

Have modified one simple order cycle spec to include fees. Concern/Unsure about: hardcoded `<select>` selector id

File: spec/system/admin/order_cycles/simple_spec.rb [hunk 1]
```diff
@@ -258,6 +274,18 @@
         click_button 'Add supplier'
         expect(page).to have_content "Permitted supplier"
 
+        within("tr.supplier-#{supplier_permitted.id}") { click_button 'Add fee' }
+        expect(page).to have_select(
+          "order_cycle_incoming_exchange_1_enterprise_fees_0_enterprise_id", minimum: 1
+        )
+        page.find("select#order_cycle_incoming_exchange_1_enterprise_fees_0_enterprise_id")
+          .all('option[label]').first.select_option
```
Comment (dacook) [inline spec/system/admin/order_cycles/simple_spec.rb:282]: I think the `select` helper will work here:
```suggestion
        select "Permitted supplier", from: "order_cycle_incoming_exchange_1_enterprise_fees_0_enterprise_id"
```

File: spec/system/admin/order_cycles/simple_spec.rb [hunk 2]
```diff
@@ -258,6 +274,18 @@
...
+        sleep 1
```
Comment (dacook) [inline spec/system/admin/order_cycles/simple_spec.rb:283]: Is this to wait for the next select to load? Usually have_* matchers will wait for the condition to pass, so I thought a sleep wouldn't be necessary.
But.. strangely this spec doesn't work on my computer. Do you  have any ideas why?

`expected to find visible select box "order_cycle_incoming_exchange_1_enterprise_fees_0_enterprise_fee_id" that is not disabled with options ["", "Supplier distributor fee1", "Supplier distributor fee3"] but there were no matches.`

`Also found "Supplier distributor fee1\nSupplier distributor fee3\nSupplier distributor fee4\nSupplier distributor fee2", which matched the selector but not all filters.`

`Expected options ["", "Supplier distributor fee1", "Supplier distributor fee3"]
found ["", "Supplier distributor fee1", "Supplier distributor fee3", "Supplier distributor fee4", "Supplier distributor fee2"]`
Screenshot 2024-07-10 at 9 42 26 am

**Review by dacook — COMMENTED** [review]
Thanks for updating this, but I'm confused why the spec doesn't work locally. Are you able to replicate that at all?

File: spec/system/admin/order_cycles/simple_spec.rb (hunk 2 above)
Comment (abdulazizali77) [reply spec/system/admin/order_cycles/simple_spec.rb:283]: Weird. From your screenshot it means the implementation isnt working. It works on my other two machines (my current windows has an older wsl which doesnt have X/wayland)

File: spec/system/admin/order_cycles/simple_spec.rb (hunk 1 above)
Comment (abdulazizali77) [reply spec/system/admin/order_cycles/simple_spec.rb]: Thanks. changed

File: spec/controllers/admin/enterprise_fees_controller_spec.rb [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+      let!(:enterprise){ create(:distributor_enterprise_with_tax, name: 'Enterprise') }
+      let!(:fee1) { create(:enterprise_fee, :flat_rate, enterprise:) }
+      let!(:fee2) { create(:enterprise_fee, :per_item, enterprise:) }
+      let!(:fee3) { create(:enterprise_fee, :flat_rate, enterprise:) }
+      let!(:fee4) { create(:enterprise_fee, :per_item, enterprise:) }
+      let!(:order_cycle){
+        create(:simple_order_cycle, name: "oc1", suppliers: [enterprise],
+                                    distributors: [enterprise])
+      }
+
```
Comment (rioug) [inline spec/controllers/admin/enterprise_fees_controller_spec.rb:25]: We should cover the scenario when there is no `per_item` or `per_order` parameters.

**Review by rioug — CHANGES_REQUESTED** [review]
It looks goods ,thanks @abdulazizali77. I believe we are missing a scenario in the specs, see my comment. Could you have a look at that ?

File: spec/controllers/admin/enterprise_fees_controller_spec.rb (hunk 3 above)
Comment (abdulazizali77) [reply spec/controllers/admin/enterprise_fees_controller_spec.rb:25]: added

File: spec/controllers/admin/enterprise_fees_controller_spec.rb [hunk 4]
```diff
@@ -0,0 +1,45 @@
+# frozen_string_literal: false
+
+require 'spec_helper'
+require 'open_food_network/order_cycle_permissions'
+
+RSpec.describe Admin::EnterpriseFeesController do
+  before { @request.env['HTTP_REFERER'] = 'http://test.com/' }
```
Comment (dacook) [inline spec/controllers/admin/enterprise_fees_controller_spec.rb:7]: I'm wondering if this is necessary? It may have been copy/pasted from other specs that are testing redirect behaviour, but not relevant here.

File: spec/controllers/admin/enterprise_fees_controller_spec.rb [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+
+  before do
+    allow(controller).to receive_messages spree_current_user: super_admin
```
Comment (dacook) [inline spec/controllers/admin/enterprise_fees_controller_spec.rb:10]: I think in general it's better to test with a non-admin user (eg a user that is a manager of the enterprise) to ensure they have the correct permission. But I wouldn't bother changing it now.

I can see that the below feature spec uses an enterprise user, so all good 👍

**Review by dacook — APPROVED** [review]
Great work!

**Comment by drummer83** [comment]
@rioug If I understand correctly there's a review open for you here. I moved it back to code review.
Thanks!

**Review by rioug — APPROVED** [review]
Thanks for that @abdulazizali77 !

File: spec/controllers/admin/enterprise_fees_controller_spec.rb (hunk 4 above)
Comment (rioug) [reply spec/controllers/admin/enterprise_fees_controller_spec.rb]: It's not needed, nor is  `open_food_network/order_cycle_permissions` above. I just remove them

**Comment by abdulazizali77** [comment]
Thanks @rioug @dacook !

**Review by dacook — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @abdulazizali77,
Thank you so much for working on this. I have staged your PR to our staging server and tested it. Here are the results.

### Before staging
- All types of fees can be applied to Incoming Products.
- All types of fees can be applied to Outgoing Products.

### After staging
- Existing carts remains unchanged and checkout works well. ✔️ 
- Fees of existing order cycles remain unchanged and checkout works well. ✔️ 

- The Incoming Products page sets the forbidden fees to blank. ✔️ 
grafik

- Fees on Outgoing Products are filtered too. ❌
On page Outgoing Products all types of fees should be available. Only fees on the Incoming Products page must be filtered.
grafik

### To be checked on next testing
- Are the blank fees still applied after saving the Incoming Products page? ❓ 

## Conclusion
We should fix the Outgoing Products page. Here all types of fees must be available.
I will move this back to In Progress.

@abdulazizali77 Are you available to fix this last bit? Great work so far!
Thank you again! 🙏 

@openfoodfoundation/train-drivers-product-owners Is it still intended to check our production servers for how many cases of 'per order' fees on Incoming Products we have? See [opening post in the original](https://github.com/openfoodfoundation/openfoodnetwork/issues/11326#issue-1834736852) issue.
According to my testing so far I'm not expecting issues for the transition, but users might be confused about why they can't select all fees anymore on the Incoming section.

**Comment by drummer83** [comment]
We should add a spec please to check that all fees are available for Outgoing Products, while it's filtered for the Incoming Products.

**Comment by abdulazizali77** [comment]
> We should add a spec please to check that all fees are available for Outgoing Products, while it's filtered for the Incoming Products.

i have to fix the implementation first given the new outgoing exchange requirements

**Comment by abdulazizali77** [comment]
> We should add a spec please to check that all fees are available for Outgoing Products, while it's filtered for the Incoming Products.

@drummer83 Have changed the implementation to only use per_item on incoming exchange and added the corresponding spec. PTAL thanks

File: app/assets/javascripts/admin/order_cycles/controllers/incoming_controller.js.coffee [hunk 6]
```diff
@@ -2,7 +2,7 @@ angular.module('admin.orderCycles').controller 'AdminOrderCycleIncomingCtrl', ($
   $controller('AdminOrderCycleExchangesCtrl', {$scope: $scope, ocInstance: ocInstance, $location: $location})
 
   $scope.view = 'incoming'
-
+  # NB: weirdly at this next line $scope.order_cycle.id comes out undefined so we use $scope.order_cycle_id instead
```
Comment (rioug) [inline app/assets/javascripts/admin/order_cycles/controllers/incoming_controller.js.coffee:5]: It looks like a race condition, `$scope.order_cycle` is loaded in `AdminEditOrderCycleCtrl` which this controller depend on via `AdminOrderCycleExchangesCtrl`. So if you try to access `$scope.order_cycle` before it's loaded, you'll get `undefined`. From memory, you could get around that by watching for changes on `$scope.order_cycle` via `$watch` before using it.

**Review by rioug — APPROVED** [review]
Looks good :+1: , thanks @abdulazizali77

File: app/assets/javascripts/admin/order_cycles/controllers/incoming_controller.js.coffee (hunk 6 above)
Comment (abdulazizali77) [reply app/assets/javascripts/admin/order_cycles/controllers/incoming_controller.js.coffee:5]: i guessed as much. would a watch be preferable here, what do you think?

Comment (rioug) [reply app/assets/javascripts/admin/order_cycles/controllers/incoming_controller.js.coffee:5]: I wouldn't bother given that you can access the `order_cycle_id` directly and we don't need any other order cycle data

File: spec/system/admin/order_cycles/simple_spec.rb [hunk 7]
```diff
@@ -301,6 +317,18 @@
         click_button 'Add distributor'
         expect(page).to have_content "Permitted distributor"
 
+        within("tr.distributor-#{distributor_permitted.id}") { click_button 'Add fee' }
+        expect(page).to have_select(
+          "order_cycle_outgoing_exchange_1_enterprise_fees_0_enterprise_id", minimum: 1
+        )
```
Comment (dacook) [inline spec/system/admin/order_cycles/simple_spec.rb:323]: Is the `minimum` parameter necessary here? I would hope that we can predict exactly how many appear, and where. 
Actually, is this `expect` necessary at all? I think it would be covered by the next `select ... from:...` anyway.

**Review by dacook — APPROVED** [review]
Thanks for working through this. I have a comment about the spec, but it's not worth making further changes. Let's test!

**Comment by drummer83** [comment]
Hi @abdulazizali77,
Thanks for continuing your work on this. I have tested again.

## Before staging
Whole order fees and per item fees are applied on incoming and outgoing exchanges - that's how I set it up:
image

## After staging
### Without any changes
Checking out without changing order cycle settings everything remains the same - that's good for existing order cycles:
image

The filtered fees on incoming exchanges are still applied, but displayed as 'blank'. This could be improved, because it's an undefined state for users (fees being applied without having them properly listed):
image

Fees on outgoing exchanges remain unchanged:
image

### After editing the order cycle and saving it still with 'blank' fees
The fees are still applied as before - which is ok, but again somewhat undefined for users:
image

### Cloning an order cycle with 'blank' fees
After cloning an order cycle with those filtered 'blank' fees, the fees are suddenly back on first loading of the page - that's probably an edge case we can live with:
image

### Removing those 'blank' fees
After removing those blank fees on incoming exchanges, only per item fees are added to incoming and outgoing exchanges. Per order fees are applied to outgoing exchanges only - as expected:
image

## Conclusion
In the transition phase there might be some confusion due to the blank fees which are still applied. However, cloning is the only way to keep them. New order cycles can't be set up with those fees filtered out. 
This PR clearly is an improvement and I couldn't find any regressions. We could merge.

I'm asking @openfoodfoundation/train-drivers-product-owners for their opinion on how to handle those blank fees because cloning of order cycles is used a lot. We could also evaluate the production servers and check how often we have fees per order assigned to incoming exchanges (as originally requested [in the opening post here](https://github.com/openfoodfoundation/openfoodnetwork/issues/11326#issue-1834736852)). Then we could decide if we need to improve the behavior, contact those enterprises or can simply ignore it.

Thanks again, @abdulazizali77! 
Adding the feedback-needed label for now.

**Comment by RachL** [comment]
Given this was spotted in testing and not reported by a user, I'm tempted to merge and if it's a problem perhaps we could even consider creating a migration? But that can come in a second PR for sure, let's move this one forward lot of great work happening here already! 🎉

**Comment by abdulazizali77** [comment]
thank you all!
