### PR TITLE
OC notifications

### LINKED ISSUE #8707: Notify Producers Email not sending on first button click
## Description

This morning a hub reported that when they clicked the Notify Producers email the emails didn't send.It appears the button had been pressed because it now was labelled 'Re-notify Producers'

After reading through the PR and testing on this it appears that with the automation of this button a first click was not tested but a second click was tested. I pressed 'Resend Notification Emails' and the emails sent correctly.

Obviously users should not have to press this button a second time for it to work. 

## Expected Behavior

Notify Producers button works every time it is pressed.

## Actual Behaviour

Notify Producers button appears to not work on the first press.

## Steps to Reproduce

1. After an order cycle closes, and when the Notify Producers button has not been automated, press the Notify Producers button
2. Emails dont send
3. Press again
4. Emails send

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

Marking as S1 as this is how producers are sent their orders and the UX suggests that everything has worked. If a hub manager doesnt notice then the whole order cycles produce will not be delivered to the hub.

## Your Environment

* Version used: 4.1.12
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Probably introduced in the last release in 4.1.12 with #8598

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #8707, #8713

Separates two flags (`processed_at` and `mails_sent`) for these two different processes; handling automatic processing when an OC closes and sending of email notifications. They were previously sharing one flag (just the `processed_at` column) and it's wasn't really sufficient. This lead to some OCs being marked as having their emails sent when actually they hadn't.

Also; cloning an OC was not resetting the state, so a cloned OC that had ended was still marked as having been processed when actually it was a new OC.

Does that make sense? I slept badly and need more coffee...

Also improves test coverage in a couple of key places.

#### What should we test?

Lets go for this: 

1. An OC that has automatic notifications **disabled**. Place an order and close the OC. Wait for the `OrderCycleClosingJob` to run (it runs every ~5 minutes) or just trigger the `OrderCycleClosingJob` from the console. Expected outcome: emails are not sent, and when you go to the OC edit page the button does not say "re-send" notifications and doesn't have the green check mark. Bonus test: click the send emails button and then go back to the edit page for that OC. The UI should now show the emails have been sent.
2. An OC that has automatic notifications **enabled**. Basically same as above, but the emails should get sent and the OC edit page should reflect that.
3. Cloning an OC that has had it's emails sent should "reset" it so it doesn't show as having emails sent.

#### Release notes

Fixed some UI issues with new automatic notifications feature

Changelog Category: User facing changes

### CODE REVIEW

File: app/jobs/order_cycle_notification_job.rb [hunk 1]
```diff
@@ -7,5 +7,6 @@ def perform(order_cycle_id)
     order_cycle.suppliers.each do |supplier|
       ProducerMailer.order_cycle_report(supplier, order_cycle).deliver_now
     end
+    order_cycle.update_columns mails_sent: true
```
Comment (mkllnk) [inline app/jobs/order_cycle_notification_job.rb:10]: Double sending could be a problem if this process takes longer and we run into a race condition. We could load the OC with a pessimistic lock above but a lengthy process like sending mail shouldn't block anything else...

Let's leave it for now but maybe we need another mechanism that prevents several jobs of the same type to run at the same time. Is there a Sidekiq option for that?

File: app/models/order_cycle.rb [hunk 2]
```diff
@@ -281,7 +281,9 @@ def orders_close_at_after_orders_open_at?
 
   def reset_processed_at
     return unless orders_close_at.present? && orders_close_at_was.present?
+    return unless orders_close_at > orders_close_at_was
 
-    self.processed_at = nil if orders_close_at > orders_close_at_was
+    self.processed_at = nil
+    self.mails_sent = false
```
Comment (mkllnk) [inline app/models/order_cycle.rb:287]: If we discover more things like this then "cloning" is probably not the right approach. We could just copy the data we need to a new OC. Out of scope here.

**Review by mkllnk — APPROVED** [review]
This looks good. I'm slightly worried about setting the new flag to false on already processed OCs but the mailing job shouldn't run for them again. So it should be okay for now.

File: app/jobs/order_cycle_notification_job.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply app/jobs/order_cycle_notification_job.rb:10]: In this case it's the `OrderCycleClosingJob` which actually controls whether or not to send the notifications. The `mails_sent` flag is only really used in the UI and not in the email sending logic.

`OrderCycleClosingJob` figures out which recently closed OCs need to have notifications sent and enqueues the `OrderCycleNotificationJob` for each of them using `perform_later` (which is non-blocking) and then immediately marks all the relevant OCs with a `processed_at` timestamp. 

Given that flow, I don't think we'll get any double-sending as `OrderCycleClosingJob` runs once every 5 minutes and I don't think it can take more than a second to complete. :thinking:

**Review by jibees — APPROVED** [review]
LGTM. As there are some open discussions, I leave it in `Code Review` state.

**Comment by Matt-Yorkley** [comment]
I'll have a think about a data migration but we can test this as it is :ok_hand:

File: db/migrate/20220112102539_add_mails_sent_to_order_cycles.rb [hunk 3]
```diff
@@ -0,0 +1,5 @@
+class AddMailsSentToOrderCycles < ActiveRecord::Migration[6.1]
+  def change
+    add_column :order_cycles, :mails_sent, :boolean, default: false
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply db/migrate/20220112102539_add_mails_sent_to_order_cycles.rb:3]: Done.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

Thanks for the detailed testing notes and that tip on running `OrderCycleClosingJob`! This goes straight to the wiki ;-)

So, I actually started off here:
- Cloning an OC that has had it's emails sent should "reset" it so it doesn't show as having emails sent
  - this works fine now: the cloned OC does not have the green tick nor the wording "Re-send" :+1: 

Peek 2022-01-17 16-53

- on an OC that has **automatic notifications disabled**:
  -  placing an order and closing the OC and trigger the OrderCycleClosingJob from the console
  -> Emails were not sent; the OC edit page the button does not say "re-send" notifications and doesn't have the green check mark
  -> Bonus test: clicking the send emails button changes the UI: it now shows the emails have been sent.

- on an OC that has **automatic notifications enabled**:
    An OC that has automatic notifications enabled. Basically same as above, but the emails should get sent and the OC edit page should reflect that - OK

Peek 2022-01-17 18-22

- Cloning an OC that has had it's emails sent should "reset" it so it doesn't show as having emails sent - OK

- also, verified that we now have the new column `mails_sent`, on the `order_cycles` table:
```
 mails_sent           | boolean                   |                |               | false                                      | plain       |                    | 
```

A relevant scenario might be when a user re-opens the OC (instead of cloning):
- in this case, the `mails_sent` get's reset as well :+1: 

I think this is enough improvement to merge...

However I did find a situation in which the created OC had the **mails_sent  = NULL**:

```
  id  | name |   orders_open_at    |   orders_close_at   | coordinator_id |         created_at         |         updated_at         | processed_at | automatic_notifications | mails_sent 
------+------+---------------------+---------------------+----------------+----------------------------+----------------------------+--------------+-------------------------+------------
 3512 | OC13 | 2022-01-01 17:00:00 | 2022-01-16 17:00:00 |           1785 | 2022-01-17 17:27:26.187484 | 2022-01-17 17:28:20.741297 |              | t                       | 
 3517 | OC2  | 2022-01-01 17:00:00 | 2022-01-16 17:00:00 |           1799 | 2022-01-17 18:27:38.458134 | 2022-01-17 18:30:03.606457 |              | t                       | 
(2 rows)

```

I'm not exactly sure how to reproduce this. But I think it relates on how the OC is created... In these cases, the auto-notification never gets sent; sending it manually populates the `mails_sent = t`.

I'll stop now on this PR, but I think this needs further investigation and an issue, but happy on your thoughts on this one.

File: db/migrate/20220114110920_update_order_cycle_mails.rb [hunk 4]
```diff
@@ -0,0 +1,12 @@
+class UpdateOrderCycleMails < ActiveRecord::Migration[6.1]
+  class MigrationOrderCycle < ActiveRecord::Base
+    self.table_name = "order_cycles"
+  end
```
Comment (mkllnk) [inline db/migrate/20220114110920_update_order_cycle_mails.rb:4]: Why not just `OrderCycle` and omit the table name?

I found that there's usually no conflict because the full class name here is actually `UpdateOrderCycleMails::OrderCycle`. That just doesn't work with polymorphic types.

**Comment by filipefurtad0** [comment]
Ok, I'm sure we're good:

- if a clone OC is coming from a previous OC in which `automatic_notifications = f` and `mails_sent = f`

Then, the `mails_sent` field will be empty (on the cloned OC).

However, toggling Automatic notifications will change `automatic_notifications` to `t ` and` mails_sent` to `f`, i.e., non-empty.

So, I think we're good. An issue would be if:

`automatic_notifications = t` and
`mails_sent = NULL`

Which I have not found to be occurring :+1: 
Thanks again!!
