### PR TITLE
5785 Notify Bugsnag when sending card to Stripe fails during checkout

### LINKED ISSUE #5785: Stripe not accepting multiple credit cards, can not process order
## Description
Customer attempting to check out - completes credit card details for stripe payment - details are not accepted. Customer attempts this with three different credit cards, from two different issuing banks, all return errors. See below errors:

ING debit card - your card has been declined.
ING debit card - your card does not support this type of purchase.
ANZ credit card - your card has been declined.

Customer was unable to process order and contacted hub.

NB. Notes from Customer

image

## Expected Behavior
Customer credit card details should have been accepted and transaction processed without error. 

## Actual Behaviour
Customer could not check out, order was unable to be made.

## Steps to Reproduce
Not able to reproduce

## Workaround
Hub manually processed the transaction for the customer.

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used:
* Browser name and version: Safari
* Operating System and version (desktop or mobile): Desktop

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #5785 and part of #5858.

Issue #5785 describes a checkout problem that we couldn't investigate properly because of missing logging. This pull request adds more logging to paying by card via Stripe.

#### What should we test?

* Test on a staging server with BugsnagJS set up.
* Test the checkout via Stripe using a non-saved card:
  - Success with valid card.
  - Fail with invalid card.
* A failed payment should show up in Bugsnag.
* Repeat the above with StripeSCA.

#### Release notes

The checkout with Stripe is more resilient and currently unknown errors can be reported to the user and our logging.

Changelog Category: Changed

### CODE REVIEW

File: app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee [hunk 1]
```diff
@@ -19,6 +19,11 @@ Darkswarm.factory 'StripeElements', ($rootScope, Messages) ->
           secrets.cc_type = @mapTokenApiCardBrand(response.token.card.brand)
           secrets.card = response.token.card
           submit()
+      .catch (response) =>
+        # Stripe handles errors in the response above. This code may never be
+        # reached. But if we get here, we want to know.
+        @reportError(response, t("js.stripe_elements.unknown_error_from_stripe"))
+        throw response
```
Comment (mkllnk) [inline app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee:26]: In my tests, a `throw` didn't trigger any Bugsnag events. And Bugsnag's documentation mentions notifying explicitly:
https://docs.bugsnag.com/platforms/javascript/reporting-handled-errors/#handled-promise-rejections

File: app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee [hunk 2]
```diff
@@ -35,11 +40,17 @@ Darkswarm.factory 'StripeElements', ($rootScope, Messages) ->
           secrets.cc_type = @mapPaymentMethodsApiCardBrand(response.paymentMethod.card.brand)
           secrets.card = response.paymentMethod.card
           submit()
+      .catch (response) =>
+        # Stripe handles errors in the response above. This code may never be
+        # reached. But if we get here, we want to know.
+        @reportError(response, t("js.stripe_elements.unknown_error_from_stripe"))
+        throw response
```
Comment (mkllnk) [inline app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee:47]: I know this is duplication but eventually this Stripe SCA part will replace the old Stripe code and we will have only one version.

Comment (luisramos0) [reply app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee:47]: yes, I kept it duplicated also because stripeconnect will go and it will be easier to remove if separated.

File: app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee [hunk 3]
```diff
@@ -35,11 +40,17 @@ Darkswarm.factory 'StripeElements', ($rootScope, Messages) ->
...
 
     reportError: (error, messageForUser) ->
       Messages.error(messageForUser)
       @triggerAngularDigest()
-      console.error(JSON.stringify(error))
+      console.error(error)
+      Bugsnag.notify(new Error(JSON.stringify(error)))
```
Comment (luisramos0) [inline app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee:53]: I think this "new Error" is important. I see "notify received a non error" in bugsnag:
image

but I am not sure where in the checkout.js code this one is coming from.
anyway, new Error here will avoid this problem.

File: config/locales/en.yml [hunk 4]
```diff
@@ -2767,6 +2767,11 @@ See the %{link} to find out more about %{sitename}'s features and to start using
       signup_or_login: "Start By Signing Up (or logging in)"
       have_an_account: "Already have an account?"
       action_login: "Log in now."
+    stripe_elements:
+      unknown_error_from_stripe: |
+        Uh oh, the Stripe integration failed. You can try again but there is
+        a very small chance that the payment came through already. It's best to
+        check your bank account first.
```
Comment (luisramos0) [inline config/locales/en.yml:2774]: The user is checking out with their card and may have no knowledge of what is Stripe.
This message is in the catch, submit was not executed.
This createToken is only creating the card in stripe, not making the payment (that's done on server side checkout, no call to submit means no server side checkout).
So, I'd make this error message a bit different:
"There was a problem setting up your card in our payments gateway. Please refresh the page and try again, if it fails a second time, please contact us for support."

**Review by luisramos0 — CHANGES_REQUESTED** [review]
Nice one Maikel.

I think the error message needs to be adapted.

File: app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee (hunk 3 above)
Comment (mkllnk) [reply app/assets/javascripts/darkswarm/services/stripe_elements.js.coffee:53]: Yes, I observed the same. The InvalidError is reported without `new Error` and it looks much better with `new Error`. So I'm doing it right, right?

File: config/locales/en.yml (hunk 4 above)
Comment (mkllnk) [reply config/locales/en.yml]: Ah, yes, right. I updated that with your text.

**Review by luisramos0 — APPROVED** [review]

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Moved on to staging-AU.

Before staging this PR, I verified that the following errors get triggered on Bugsnag:

Stripe Connect
card: 4000000000009995 - insufficient funds

https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5f28d21bd8769b0017d7b61a?filters%5Bapp.release_stage%5D%5B%5D%5Bvalue%5D=staging&filters%5Bapp.release_stage%5D%5B%5D%5Btype%5D=eq&event_id=5f5a753e005deff0c6ae0000

Stripe SCA
card: 4000000000009995 - insufficient funds

https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5f28d21bd8769b0017d7b61a?filters%5Bapp.release_stage%5D%5B%5D%5Bvalue%5D=staging&filters%5Bapp.release_stage%5D%5B%5D%5Btype%5D=eq&event_id=5f5a75b1005dedada9960000

Stripe SCA
3D-card 4000008260003178 - insufficient funds

https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5f28d21bd8769b0017d7b61a?filters%5Bapp.release_stage%5D%5B%5D%5Bvalue%5D=staging&filters%5Bapp.release_stage%5D%5B%5D%5Btype%5D=eq&event_id=5f5a7610005df366da4b0000

No errors found on BugsnagJS. After staging this PR, still nothing on BugsnagJS.

Tried several other cards as well, like

4000000000000002 | Charge is declined with a card_declined code.
4000000000000069 | Charge is declined with an expired_card code.
4000008400001629 | 3D Secure authentication is required, but payments will be declined with a card_declined

They all appear on Bugsnag/Slack, but not on BugsnagJS.

Is there something I'm missing here?

**Comment by filipefurtad0** [comment]
This is working apparently as well for BugsnagJS. On checkout:
- Selecting Stripe SCA / Stripe-Connect
- Leaving the card details empty or incomplete
- Clicking checkout generates error:

Stripe-SCA
https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/5f5a929c1fad0b00178c2a01?event_id=5f5a929c005df91d3f7b0000&i=sk&m=nw

Stripe-Connect:
https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/5f5a929c1fad0b00178c2a01?&event_id=5f5a94f8005e094a524b0000

image
