### PR TITLE
3.0 Initial fixes

### LINKED ISSUE #3706: [Spree 2.1] OFN Admin routes not available in specs (~100 specs)
For some reason the specs are not seeing the ofn route helpers, for example, admin_enterprise_relationships_path.

I have tried preceeding it with main_app. but it doesnt solve the problem.

```
As an Administrator
  I want to manage relationships between enterprises
 as a site administrator creating a relationship
      Failure/Error: visit admin_enterprise_relationships_path
      
      NameError:
        **undefined local variable or method `admin_enterprise_relationships_path'** for #<RSpec::ExampleGroups::AsAnAdministratorIWantToManageRelationshipsBetweenEnterprises::AsASiteAdministrator:0x00559f18db79e8>
      # ./spec/features/admin/enterprise_relationships_spec.rb:40:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
Closes #3706 (routes are now working correctly)

This PR is targetting the `3-0-stable` branch.

Introduces a number of fixes to get the app booting and the build working better with Spree 2.1 / Rails 4.

### CODE REVIEW

File: app/controllers/spree/admin/base_controller_decorator.rb [hunk 1]
```diff
@@ -86,13 +86,17 @@ def json_request?
...
       render options.merge(json: data, each_serializer: serializer(ams_prefix))
     else
       render options.merge(json: data, serializer: serializer(ams_prefix))
     end
   end
 
+  def each_serializer_required?(data)
+    ['Array', 'ActiveRecord::Relation'].include?(data.class.name)
+  end
+
```
Comment (luisramos0) [inline app/controllers/spree/admin/base_controller_decorator.rb]: this can go to master.

File: app/models/enterprise.rb [hunk 2]
```diff
@@ -25,7 +25,8 @@ class Enterprise < ActiveRecord::Base
   has_many :relationships_as_child, class_name: 'EnterpriseRelationship',
                                     foreign_key: 'child_id',
                                     dependent: :destroy
-  has_and_belongs_to_many :groups, class_name: 'EnterpriseGroup'
+  has_and_belongs_to_many :groups, join_table: 'enterprise_groups_enterprises',
+                          class_name: 'EnterpriseGroup'
```
Comment (luisramos0) [inline app/models/enterprise.rb]: this can be done in master

File: app/models/enterprise.rb [hunk 3]
```diff
@@ -117,9 +118,9 @@ class Enterprise < ActiveRecord::Base
     # checkout.
     ready_enterprises = Enterprise.ready_for_checkout.select('enterprises.id')
     if ready_enterprises.present?
-      where("enterprises.id NOT IN (?)", ready_enterprises)
+      where.not(id: ready_enterprises.map(&:id))
```
Comment (luisramos0) [inline app/models/enterprise.rb]: this can be done in master

File: app/models/enterprise_group.rb [hunk 4]
```diff
@@ -5,7 +5,7 @@ class EnterpriseGroup < ActiveRecord::Base
   include PermalinkGenerator
   acts_as_list
 
-  has_and_belongs_to_many :enterprises
+  has_and_belongs_to_many :enterprises, join_table: 'enterprise_groups_enterprises'
```
Comment (luisramos0) [inline app/models/enterprise_group.rb]: this can be done in master

File: app/models/order_cycle.rb [hunk 5]
```diff
@@ -10,11 +10,11 @@ class OrderCycle < ActiveRecord::Base
...
   # :incoming_exchanges and :outgoing_exchanges.
-  has_many :cached_incoming_exchanges, conditions: { incoming: true }, class_name: "Exchange"
-  has_many :cached_outgoing_exchanges, conditions: { incoming: false }, class_name: "Exchange"
+  has_many :cached_incoming_exchanges, -> { where incoming: true }, class_name: "Exchange"
+  has_many :cached_outgoing_exchanges, -> { where incoming: false }, class_name: "Exchange"
 
-  has_many :suppliers, source: :sender, through: :cached_incoming_exchanges, uniq: true
-  has_many :distributors, source: :receiver, through: :cached_outgoing_exchanges, uniq: true
+  has_many :suppliers, -> { uniq }, source: :sender, through: :cached_incoming_exchanges
+  has_many :distributors, -> { uniq }, source: :receiver, through: :cached_outgoing_exchanges
```
Comment (luisramos0) [inline app/models/order_cycle.rb]: this can be done in master, right?

File: config/routes/spree.rb [hunk 6]
```diff
@@ -122,6 +115,13 @@
     resources :tax_categories
   end
 
+  match '/admin', to: 'admin/overview#index', as: :admin_dashboard, via: :get
```
Comment (luisramos0) [inline config/routes/spree.rb]: this admin_dashboard and related changes can be done in master, right?

File: app/models/order_cycle.rb (hunk 5 above)
Comment (Matt-Yorkley) [reply app/models/order_cycle.rb]: We can try it :+1:

**Comment by mkllnk** [comment]
What do you think about moving this back to in-dev until some of the commits have been moved to their own master-prs? 40 commits is a lot to review.

File: app/models/enterprise.rb (hunk 3 above)
Comment (Matt-Yorkley) [reply app/models/enterprise.rb]: The #not method is Rails 4.

File: app/models/order_cycle.rb (hunk 5 above)
Comment (Matt-Yorkley) [reply app/models/order_cycle.rb]: Nope, turn out this one can't be done before Rails 4.

**Comment by Matt-Yorkley** [comment]
@luisramos0  I moved several commits to here: #4667, and one large commit to here: #4668 and discovered one of the suggested commits for moving to `master` couldn't be merged in Rails 3.2.

**Comment by Matt-Yorkley** [comment]
> Let's merge it!

What's the plan with managing `3-0-stable`? Should we merge this, then just merge master back into the stable branch after the spree backend PRs are in?

**Comment by luisramos0** [comment]
When spree_backend is removed in master, I'd like to rebase 3-0-stable.
At that pont we also need to create issues for every temp fix in the code of this branch.
After that I think we can start to merge regularly from master as rebasing is a lot more painful.
what do you think?

**Comment by luisramos0** [comment]
Unless this is blocking you to do something else, I think it would be good to get another review on this one before merging.

**Comment by luisramos0** [comment]
I think spree_backend will take a few weeks to get merged completely. So I'd merge this before.

File: spec/support/request/authentication_workflow.rb [hunk 7]
```diff
@@ -26,8 +26,8 @@ def login_to_admin_section
 
   # TODO: Should probably just rename this to create_user
   def create_enterprise_user( attrs = {} )
-    new_user = create(:user, attrs)
-    new_user.spree_roles = [] # for some reason unbeknown to me, this new user gets admin permissions by default.
+    new_user = build(:user, attrs)
+    new_user.spree_roles = [Spree::Role.find_or_create_by!(name: 'user')]
```
Comment (mkllnk) [inline spec/support/request/authentication_workflow.rb]: This should work in master, shouldn't it?

File: config/initializers/paper_trail.rb [hunk 8]
```diff
@@ -0,0 +1 @@
+PaperTrail.config.track_associations = false
```
Comment (mkllnk) [inline config/initializers/paper_trail.rb]: Does this work in master?

File: app/controllers/api/products_controller.rb [hunk 9]
```diff
@@ -121,7 +121,7 @@ def product_query_includes
     end
 
     def paged_products_for_producers(producers)
-      Spree::Product.scoped.
+      Spree::Product.where(nil).
```
Comment (mkllnk) [inline app/controllers/api/products_controller.rb]: I think that this works in Rails 3 as well.

File: app/models/spree/order_decorator.rb [hunk 10]
```diff
@@ -304,6 +304,14 @@ def tax_adjustment_totals
     end
   end
 
+  def price_adjustments
```
Comment (mkllnk) [inline app/models/spree/order_decorator.rb]: What is this method doing in this commit?

File: app/views/spree/admin/orders/_filters.html.haml [hunk 11]
```diff
@@ -1,5 +1,5 @@
 %div{"data-hook" => "admin_orders_index_search"}
-  = form_tag false, {name: "orders_form", "ng-submit" => "fetchResults()"} do
+  = form_tag nil, {name: "orders_form", "ng-submit" => "fetchResults()"} do
```
Comment (mkllnk) [inline app/views/spree/admin/orders/_filters.html.haml]: I don't know but I was wondering if this could work in Rails 3 as well?

File: .rubocop_styleguide.yml [hunk 12]
```diff
@@ -5,8 +5,8 @@
 # rubocop locally, the default configuration file `.rubocop.yml` loads
 # our "todo lists" to ignore all current violations.
 AllCops:
-  TargetRubyVersion: 2.2
```
Comment (mkllnk) [inline .rubocop_styleguide.yml]: There is probably a conflict here now since we updated Rubocop in master.

File: app/helpers/spree/admin/navigation_helper_decorator.rb [hunk 13]
```diff
@@ -1,3 +1,5 @@
+require 'spree/admin/navigation_helper'
```
Comment (mkllnk) [inline app/helpers/spree/admin/navigation_helper_decorator.rb]: Can we do this in master?

File: lib/open_food_network/orders_and_fulfillments_report.rb [hunk 14]
```diff
@@ -29,6 +29,22 @@ def table_items
       report_line_items.list(report.line_item_includes)
     end
 
+    def line_item_name
```
Comment (mkllnk) [inline lib/open_food_network/orders_and_fulfillments_report.rb]: master?

File: spec/controllers/spree/credit_cards_controller_spec.rb [hunk 15]
```diff
@@ -33,7 +33,7 @@
       let(:response_mock) { { status: 200, body: JSON.generate(id: "cus_AZNMJ", default_source: "card_1AEEb") } }
 
       it "saves the card locally" do
-        expect{ post :new_from_token, params }.to change(Spree::CreditCard, :count).by(1)
+        expect{ spree_post :new_from_token, params }.to change(Spree::CreditCard, :count).by(1)
```
Comment (mkllnk) [inline spec/controllers/spree/credit_cards_controller_spec.rb]: Does it work in master?

File: app/models/product_import/product_importer.rb [hunk 16]
```diff
@@ -214,7 +214,9 @@ def open_spreadsheet
     end
 
     def accepted_mimetype
-      File.extname(@file.path).in?('.csv', '.xls', '.xlsx', '.ods') ? @file.path.split('.').last.to_sym : false
+      return false unless ['.csv', '.xls', '.xlsx', '.ods'].include? File.extname(@file.path)
```
Comment (mkllnk) [inline app/models/product_import/product_importer.rb]: This is a great change which should go to master. There is actually a conflict already because we removed the options to `.csv` only.

File: app/models/product_import/spreadsheet_data.rb [hunk 17]
```diff
@@ -45,7 +45,7 @@ def create_enterprises_index
 
         next if @enterprises_index.key? enterprise_name
 
-        enterprise = Enterprise.find_by(name: enterprise_name, select: 'id, is_primary_producer')
+        enterprise = Enterprise.where(name: enterprise_name).select(:id, :is_primary_producer)
```
Comment (mkllnk) [inline app/models/product_import/spreadsheet_data.rb]: We can do this in master, right?

File: config/application.rb [hunk 18]
```diff
@@ -105,7 +105,7 @@ class Application < Rails::Application
       #{config.root}/app/jobs
     )
 
-    config.paths["config/routes"] = %w(
+    config.paths["config/routes.rb"] = %w(
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply config/application.rb]: I'm pretty sure this is only Rails 4.

File: app/models/spree/order_decorator.rb (hunk 10 above)
Comment (Matt-Yorkley) [reply app/models/spree/order_decorator.rb]: Ah, that looks like it shouldn't be in that commit. I think it was a method that we depend on in the decorator, but got removed from the model in `Spree 2.1`.

Comment (Matt-Yorkley) [reply app/models/spree/order_decorator.rb]: I've moved it to a new commit with a message.

File: .rubocop_styleguide.yml (hunk 12 above)
Comment (Matt-Yorkley) [reply .rubocop_styleguide.yml]: I think the Rails 3 and Rails 4 rubocop configs are not compatible at all...

File: app/models/spree/adjustment_decorator.rb [hunk 19]
```diff
@@ -9,8 +9,9 @@ module Spree
     # So we don't need the option `dependent: :destroy` as long as
     # AdjustmentMetadata has no destroy logic itself.
     has_one :metadata, class_name: 'AdjustmentMetadata'
-    belongs_to :tax_rate, foreign_key: 'originator_id',
-                          conditions: "spree_adjustments.originator_type = 'Spree::TaxRate'"
+    belongs_to :tax_rate, -> { where spree_adjustments: { originator_type: 'Spree::TaxRate' } },
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply app/models/spree/adjustment_decorator.rb]: Semaphore says no.

File: app/models/spree/order_decorator.rb [hunk 20]
```diff
@@ -21,10 +21,9 @@
   # This removes "inverse_of: source" which breaks shipment adjustment calculations
   #   This change is done in Spree 2.1 (see https://github.com/spree/spree/commit/3fa44165c7825f79a2fa4eb79b99dc29944c5d55)
   #   When OFN gets to Spree 2.1, this can be removed
-  has_many :adjustments,
+  has_many :adjustments, -> { order "#{Spree::Adjustment.table_name}.created_at ASC" },
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply app/models/spree/order_decorator.rb]: Nope.

File: spec/support/request/authentication_workflow.rb (hunk 7 above)
Comment (Matt-Yorkley) [reply spec/support/request/authentication_workflow.rb]: There are some other issues around enterprise roles in the 3-0 branch. Maybe it's best to wait until they're fully resolved?

Comment (mkllnk) [reply spec/support/request/authentication_workflow.rb]: I personally would still move it to master but I don't know the other role issues. Once this is merged into the 3-0 branch, we are unlikely to remove it, I guess. Unless we rebase on master regularly and copy it to master one day. :woman_shrugging: Not a big deal either way.

File: config/routes/spree.rb [hunk 21]
```diff
@@ -32,35 +32,35 @@
...
-  match '/admin/reports/users_and_enterprises' => 'admin/reports#users_and_enterprises', :as => "users_and_enterprises_admin_reports",  :via => [:get, :post]
-  match '/admin/reports/sales_tax' => 'admin/reports#sales_tax', :as => "sales_tax_admin_reports",  :via  => [:get, :post]
-  match '/admin/orders/bulk_management' => 'admin/orders#bulk_management', :as => "admin_bulk_order_management", via: :get
-  match '/admin/reports/products_and_inventory' => 'admin/reports#products_and_inventory', :as => "products_and_inventory_admin_reports",  :via  => [:get, :post]
-  match '/admin/reports/customers' => 'admin/reports#customers', :as => "customers_admin_reports",  :via  => [:get, :post]
-  match '/admin/reports/xero_invoices' => 'admin/reports#xero_invoices', :as => "xero_invoices_admin_reports",  :via  => [:get, :post]
-  match '/admin', :to => 'admin/overview#index', :as => :admin, via: :get
+  #match '/admin/reports/orders_and_distributors' => 'admin/reports#orders_and_distributors', :as => "orders_and_distributors_admin_reports",  :via  => [:get, :post]
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply config/routes/spree.rb]: I'll take a look at tidying these up and moving them to master...

[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply config/routes/spree.rb]: I've tidied up and moved these routes changes to `master` here: https://github.com/openfoodfoundation/openfoodnetwork/pull/4694

File: app/controllers/api/products_controller.rb (hunk 9 above)
Comment (mkllnk) [reply app/controllers/api/products_controller.rb]: What about porting this one to master?

File: app/views/spree/admin/orders/_filters.html.haml (hunk 11 above)
Comment (mkllnk) [reply app/views/spree/admin/orders/_filters.html.haml]: Did you try this one?

File: app/controllers/api/products_controller.rb (hunk 9 above)
Comment (luisramos0) [reply app/controllers/api/products_controller.rb]: Hi Maikel, I have asked this question on another PR or thread, Matt confirmed it is not compatible.

Comment (mkllnk) [reply app/controllers/api/products_controller.rb]: Ah, okay. It seems to work in a simple case but there must be some edge cases that don't work. :+1:

File: app/models/spree/order_decorator.rb [hunk 22]
```diff
@@ -21,16 +21,25 @@
...
   validate :disallow_guest_order
   attr_accessible :order_cycle_id, :distributor_id, :customer_id
 
+  # Removes Spree 2.1 additional email validation (currently failing every time)
+  # See: spree/core/validators/email.rb
+  _validate_callbacks.each do |callback|
+    if callback.raw_filter.respond_to? :attributes
+      callback.raw_filter.attributes.delete :email
+    end
+  end
```
Comment (kristinalim) [inline app/models/spree/order_decorator.rb]: Is there an issue or a pending spec somewhere that helps makes sure the team don't forget to investigate this?

File: app/views/spree/admin/orders/_filters.html.haml (hunk 11 above)
Comment (mkllnk) [reply app/views/spree/admin/orders/_filters.html.haml]: I checked this one and it makes no difference in Rails 3.

Comment (mkllnk) [reply app/views/spree/admin/orders/_filters.html.haml]: I opened a new pull request with this: #4763
Once that one is in master, we can rebase this pull request.

**Comment by luisramos0** [comment]
@mkllnk the plan was to merge this to 3-0-stable and only rebase 3-0-stable after spree_backend is gone from master.
the process to move changes from here to master is simply to remove the change from this PR and create a PR in master as you did. So, if this change (the form tag change) is removed from this PR I think we can merge this PR into 3-0-stable straight way.

File: app/models/spree/order_decorator.rb [hunk 23]
```diff
@@ -79,6 +88,10 @@
     where("state != ?", state)
   }
 
+  def validate_email_structure?
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply app/models/spree/order_decorator.rb]: Removed :+1:

**Comment by Matt-Yorkley** [comment]
I've dropped the commit that touches the form in `app/views/spree/admin/orders/_filters.html.haml` and force-pushed.

File: app/models/spree/order_decorator.rb [hunk 24]
```diff
@@ -21,16 +21,25 @@
...
 
+  # Removes Spree 2.1 additional email validation (currently failing every time)
+  # See: spree/core/validators/email.rb
+  _validate_callbacks.each do |callback|
+    if callback.raw_filter.respond_to? :attributes
+      callback.raw_filter.attributes.delete :email
+    end
+  end
+
+  # attr_accessible :order_cycle_id, :distributor_id, :customer_id
```
Comment (luisramos0) [inline app/models/spree/order_decorator.rb]: this line needs to be removed right? it's already above.

Comment (Matt-Yorkley) [reply app/models/spree/order_decorator.rb]: Removed.

**Comment by mkllnk** [comment]
Okay, I'm happy with that as well. It's faster than my idea. Result is the same. :+1:
