### PR TITLE
Check taxon's attribute instead of object identity

### LINKED ISSUE #5900: [Flaky Spec] spec/features/admin/bulk_product_update_spec.rb:245
### What we should change and why (this is tech debt)

```
Failures:

  1) 
  As an Administrator
  I want to be able to manage products in bulk
 updating product attributes
     Failure/Error: expect(p.primary_taxon).to eq t1
     
       expected: #<Spree::Taxon id: 56, parent_id: nil, position: 0, name: "Ruby on Rails", permalink: "ruby-on-rails"... icon_updated_at: nil, description: nil, meta_title: nil, meta_description: nil, meta_keywords: nil>
            got: #<Spree::Taxon id: 58, parent_id: nil, position: 0, name: "Ruby on Rails", permalink: "ruby-on-rails"... icon_updated_at: nil, description: nil, meta_title: nil, meta_description: nil, meta_keywords: nil>
     
       (compared using ==)
     
       Diff:
       @@ -1,2 +1,2 @@
       -#<Spree::Taxon id: 56, parent_id: nil, position: 0, name: "Ruby on Rails", permalink: "ruby-on-rails", taxonomy_id: 28, created_at: "2020-08-12 16:54:49", updated_at: "2020-08-12 16:54:49", lft: 3, rgt: 4, icon_file_name: nil, icon_content_type: nil, icon_file_size: nil, icon_updated_at: nil, description: nil, meta_title: nil, meta_description: nil, meta_keywords: nil>
       +#<Spree::Taxon id: 58, parent_id: nil, position: 0, name: "Ruby on Rails", permalink: "ruby-on-rails", taxonomy_id: 29, created_at: "2020-08-12 16:54:49", updated_at: "2020-08-12 16:54:53", lft: 7, rgt: 8, icon_file_name: nil, icon_content_type: nil, icon_file_size: nil, icon_updated_at: nil, description: nil, meta_title: nil, meta_description: nil, meta_keywords: nil>
       
     # ./spec/features/admin/bulk_product_update_spec.rb:284:in `block (2 levels) in <top (required)>'
```

### Context

This spec file has been flaky in the past:
- #3455
- #4239

### Impact and timeline

?

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Closes #5900

We don't care about the Ruby object instance but the actual DB record it represents.

#### What should we test?

A green build is enough.

#### Release notes

Fix unreliable bulk product update spec

Changelog Category: Fixed

### CODE REVIEW

File: spec/features/admin/bulk_product_update_spec.rb [hunk 1]
```diff
@@ -281,7 +281,7 @@
     expect(p.variant_unit).to eq "weight"
     expect(p.variant_unit_scale).to eq 1000 # Kg
     expect(p.available_on).to eq 3.days.ago.beginning_of_day
-    expect(p.primary_taxon).to eq t1
+    expect(p.primary_taxon.permalink).to eq "ruby-on-rails"
```
Comment (luisramos0) [inline spec/features/admin/bulk_product_update_spec.rb:284]: does category/primary taxon influence permalink? or are you changing the test and not validating the taxon has changed as expected? I think in that case line 270 above should be deleted.
It would be better to keep the taxon validation in some way...

**Review by luisramos0 — APPROVED** [review]
I got a bit confused with the permalink (I didnt see it was the taxon permalink). Anyway, I understand now :+1: 

nice one :+1:

File: spec/features/admin/bulk_product_update_spec.rb (hunk 1 above)
Comment (luisramos0) [inline spec/features/admin/bulk_product_update_spec.rb:284]: would this work?
`expect(p.primary_taxon.permalink).to eq t1.permalink`

Comment (sauloperez) [reply spec/features/admin/bulk_product_update_spec.rb:284]: Yes, that should too.

**Review by luisramos0 — APPROVED** [review]
:ok_hand:

**Comment by luisramos0** [comment]
will merge with one approval.
