### PR TITLE
Fix Spree::CreditCard#brand= deprecation for Rails 7.2 compatibility

### LINKED ISSUE #13727: ActiveSupport::DeprecationException in checkout#update
## Error in Open Food Network (Rails)

**ActiveSupport::DeprecationException** in **checkout#update**
DEPRECATION WARNING: Spree::CreditCard model aliases `cc_type` and has a method called `cc_type=` defined. Starting in Rails 7.2 `brand=` will not be calling `cc_type=` anymore. You may want to additionally define `brand=` to preserve the current behavior. (called from build_source at /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2025-11-17-021413/app/models/spree/payment.rb:123)

[View on Bugsnag](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/69088259cc7f080b9e7b5d07?event_id=691b5dac0153e84d6bad0000&i=gh&m=ci)

## Stacktrace

    app/models/spree/payment.rb:123 - build_source
    app/controllers/checkout_controller.rb:124 - update_order
    app/controllers/checkout_controller.rb:43 - update
    app/services/order_locker.rb:18 - block in lock_order_and_variants
    app/services/order_locker.rb:16 - lock_order_and_variants
    app/services/current_order_locker.rb:13 - around
    app/controllers/concerns/checkout_callbacks.rb:38 - sync_stock

[View full stacktrace](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/69088259cc7f080b9e7b5d07?event_id=691b5dac0153e84d6bad0000&i=gh&m=ci)

*Created by Gaetan via Bugsnag*

### PR DESCRIPTION
**Pull request by zilton7**
## What? Why?

- Closes #13727

This PR addresses a deprecation warning in Spree::CreditCard where  brand=  (aliased from  cc_type ) was not explicitly defined while  cc_type=  had a custom implementation.  
Starting in Rails 7.2, aliased attributes will no longer automatically call custom setter methods defined on the underlying attribute. 
To preserve the current behavior where setting the  brand  triggers the reformatting logic in  cc_type= , an explicit  brand=  method has been added.

## What should we test?

`bundle exec rspec spec/models/spree/credit_card_spec.rb`

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Looks good ! thanks for you help 🙏

**Comment by zilton7** [comment]
> Thank you for working on this!
> 
> I find the test results after your first commit interesting. The `brand=` method was never called. Searching through our code base, I can see that we assign `cc_type=` when using Stripe. And when using Paypal, we don't actually handle a credit card as we redirect to Paypal for that. These are the only two credit card payment methods we support at the moment. So I'm wondering if we can just remove then brand attribute altogether? There are a few places that need updating:
> 
>     * app/helpers/checkout_helper.rb
> 
>     * app/models/spree/gateway.rb
> 
>     * app/serializers/api/credit_card_serializer.rb
> 
> 
> But that looks pretty feasible. What do you think?
> 
> I will still approve this pull request for merging. It's an improvement getting rid of the deprecation warning.

  yeah what you're saying makes sense, keeping dynamic attribute for only one type of object seems kinda useless...

File: app/serializers/api/credit_card_serializer.rb [hunk 1]
```diff
@@ -2,9 +2,9 @@
 
 module Api
   class CreditCardSerializer < ActiveModel::Serializer
-    attributes :id, :brand, :number, :expiry, :formatted, :delete_link, :is_default
+    attributes :id, :cc_type, :number, :expiry, :formatted, :delete_link, :is_default
```
Comment (mkllnk) [inline app/serializers/api/credit_card_serializer.rb]: Please don't change the API though. We want to keep this backwards compatible. It's confusing but probably easier to keep the name `brand` but return `cc_type`.
