### PR TITLE
Synchronise processing of subscriptions and avoid duplicate order creation

### LINKED ISSUE #8606: Single subscriptions are creating duplicate orders in a single order cycle
## Description
A hub (ID 3359) noticed that 2 orders in a current order cycle (ID 10778) were placed for a single subscription (ID 368) for a customer (ID 21,471).

Metabase shows there is only 1 subscription related to this customer. And the subscription is attached to Schedule ID 81 (name = Fortnightly 1).

Both orders R608544751 and R525211337 were placed at 8.06pm 2 Dec (Melbourne time), 6 minutes after the order cycle opened. They have the same product and total in them which is why I think the platform has placed the subscription order twice.

The hub has to manually check for these duplicate orders, and delete the duplicates before the order cycle closes (to avoid double charging the customers).

## Expected Behavior
One subscription should create one order in each order cycle with the corresponding schedule. For example, for a customer with a subscription on the "weekly" schedule, one order should be placed in each order cycle on the "weekly" schedule.

## Actual Behaviour
In some cases, a single subscription creates two orders for a single customer, in the same order cycle. These orders have identical products included, but different order (invoice) numbers. For example, for a customer with a subscription on the "weekly" schedule, two orders are placed in each order cycle on the "weekly" schedule.

## Steps to Reproduce
Wasn't able to replicate before Maikel made a quick fix (see below), but this has occurred a number of times for this hub.

## Animated Gif/Screenshot
FND-doubles

## Workaround
No workaround to prevent these duplicates from being placed.

## Severity
bug-s1 (as suggested by Maikel)

## Possible Fix
Maikel has suggested that this may be caused by the subscription processing time... "We process subscriptions every 5 minutes and I'm wondering if we have so many subscriptions now that it takes longer than 5 minutes to place the orders which could mean that we start processing the same again while the old process is still in progress." Maikel and Kirsten have suggested extending this wait time to 15 minutes, and Maikel is testing this with a quick and temporary change on the server.

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #8606

We place subscription orders every five minutes. We've got so many subscriptions now though that the process can take longer than five minutes. When two processes are running at the same time they can process one subscription twice and place two orders.

I added database locking to avoid processing the same subscription twice at the same time.

#### What should we test?

Subscription orders are still placed.

I don't think that it's feasible to test the original issue. I added a spec though and we need to check production once deployed.

#### Release notes

Changelog Category: User facing changes

Avoid duplicate placing of subscription orders.

### CODE REVIEW

File: app/jobs/subscription_placement_job.rb [hunk 1]
```diff
@@ -4,9 +4,10 @@
 
 class SubscriptionPlacementJob < ActiveJob::Base
   def perform
-    ids = proxy_orders.pluck(:id)
-    ProxyOrder.where(id: ids).each do |proxy_order|
-      place_order_for(proxy_order)
+    ProxyOrder.transaction do
+      while proxy_order = proxy_orders.lock.first do
```
Comment (Matt-Yorkley) [inline app/jobs/subscription_placement_job.rb:8]: What was the motivation behind using `while` here? Wouldn't `proxy_orders.lock.each` be more idiomatic Ruby?

File: app/jobs/subscription_placement_job.rb [hunk 2]
```diff
@@ -19,10 +20,15 @@ def summarizer
...
 
   def proxy_orders
+    # Order cycles become active at certain times. We need to cache the
+    # collection here to keep the result deterministic and avoid dead locks.
+    @active_order_cycle_ids ||= OrderCycle.active.pluck(:id)
+
     # Loads proxy orders for open order cycles that have not been placed yet
     ProxyOrder.not_canceled.where(placed_at: nil)
-      .joins(:order_cycle).merge(OrderCycle.active)
+      .where(order_cycle_id: @active_order_cycle_ids)
```
Comment (Matt-Yorkley) [inline app/jobs/subscription_placement_job.rb:29]: > We need to cache the collection here to keep the result deterministic

This `proxy_orders` method is only called once in the entire lifecycle of the job though, right? And `@active_order_cycle_ids` is only called once. I don't understand in what way it's actually being cached or how it's practically different from what was here before...? :thinking:

Again; just curious. :smile:

Comment (Matt-Yorkley) [reply app/jobs/subscription_placement_job.rb:29]: Partly I'm asking because this will trigger an extra query that plucks the ID of every active OrderCycle and assign it to the `@active_order_cycle_ids` ivar, but the previous version would avoid doing that...

File: app/jobs/subscription_placement_job.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply app/jobs/subscription_placement_job.rb:8]: Hmmm... my local Rspec process seems to consistently hang when it reaches this while loop.

File: app/jobs/subscription_placement_job.rb [hunk 3]
```diff
@@ -19,10 +20,15 @@ def summarizer
...
       .joins(:subscription).merge(Subscription.not_canceled.not_paused)
+      .order(:id)
```
Comment (Matt-Yorkley) [inline app/jobs/subscription_placement_job.rb:31]: :+1:

File: app/jobs/subscription_placement_job.rb (hunk 1 above)
Comment (Matt-Yorkley) [inline app/jobs/subscription_placement_job.rb:8]: If we're wrapping the entire process in a transaction and any kind of error is encountered here, the entire thing will get rolled back, right? Every proxy order that had been (theoretically) processed will be reset to the state it was in when the transaction started. But within that we're also creating orders, line_items, payments, all kinds of stuff. It also means we'll be keeping a huge meta-transaction (which contains all the other transactions) open for the entire length of the processing (up to 5-6 minutes?).

But... we're also writing log entries and updating the details held in the `summarizer` object at various points in that process, and those changes _won't_ be rolled back, right? (they're effectively outside of the transaction)

I'm a bit nervous of the potential consequences here if we hit some unhappy paths...

Comment (mkllnk) [reply app/jobs/subscription_placement_job.rb:8]: I read that `lock.each` doesn't guarantee in which order the records are locked which can lead to a deadlock. So I thought if I have a deterministic order and lock them one by one then it would be safer in avoiding deadlocks. But I'm reconsidering that now. `while` is almost never a good idea. I have seen tutorials where the `order by` clause in Postgresql is supposed to determine the order of locking but I'm not sure that it's true. Considering that we run this job only every five minutes, we probably don't have to worry about deadlocks at this stage. If it's a problem, the spec will become flaky.

File: app/jobs/subscription_placement_job.rb (hunk 2 above)
Comment (mkllnk) [reply app/jobs/subscription_placement_job.rb:29]: > This proxy_orders method is only called once in the entire lifecycle of the job though, right?

Nope. The way I wrote it, the method gets called in the while loop once per proxy order to process. I added it so that repeated queries would not change with time and when calling `first` we would always get the next unprocessed proxy order.

But I'm thinking about querying them all in one batch again. The issue is the transaction though. I'll comment below.

File: app/jobs/subscription_placement_job.rb (hunk 1 above)
Comment (mkllnk) [reply app/jobs/subscription_placement_job.rb:8]: > If we're wrapping the entire process in a transaction and any kind of error is encountered here, the entire thing will get rolled back, right?

Yeah, that's a really good point. I'm now not sure how to resolve that though because we need the transaction for locking. 

If we want to lock all proxy orders in one batch then we need the big transaction around everything. Not great.

If we want smaller transactions, we need to do it per proxy order. So we either query each proxy order individually, as I'm doing at the moment or we query them all at once, without lock, and then lock them individually which is an additional query per proxy order.

We can also use the old approach of querying all the ids first and then loading them with a lock one-by-one within a smaller transaction. But since we then the proxy order selection is not synchronised and within once we acquired the lock on each we need to double check that it hasn't been processed yet. That's my best idea so far.

Comment (mkllnk) [reply app/jobs/subscription_placement_job.rb]: Since transactions should be as short as possible, I moved the locking into the service class which is actually doing the order placement. I think it's much better there. Please have another look.

**Review by Matt-Yorkley — APPROVED** [review]
Nice :+1:

File: app/jobs/subscription_placement_job.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply app/jobs/subscription_placement_job.rb]: That looks much nicer :100:

**Review by achauve — APPROVED** [review]
The fix seems really great 👍 ! Not sure about the test though, but it might help detect race conditions sometimes.

**Comment by mkllnk** [comment]
> Not sure about the test though, but it might help detect race conditions sometimes.

Yes, the problem is with the `sleep`. If the code is running on a slow machine, it may not be long enough. The breakpoint should make sure that the two threads run into a race condition if possible. But it's impossible to know if the second thread is still on its way to the race condition or is synchronising correctly.

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,

Went through some scenarios when placing subscription orders, before and after this PR.

- placing a subscription order for an item with stock - OK
- placing a subscription order for an item in which stock is reduced during the time the OC is open
- placing a subscription order for an item which the price changes during the time the OC is open

All as before, all good :+1: 
Merging.

PS: two things I've noticed and are not introduced by this PR
- this warning is seen in the console:
`RAILS_ENV=staging environment is not defined in config/webpacker.yml, falling back to production environment` -> maybe related to the work in #7784?
- the finding in [this comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/8635#issuecomment-998715716)
