### PR TITLE
Validate the presence of first/last name if there is no company

### LINKED ISSUE #8691: "First Name" and "Last Name" fields not displaying "can't be blank" error
## Description

On split-checkout the fields "First Name" and "Last Name" are not displaying the "can't be blank" error, when left blank and attempting to proceed to the next step.

## Expected Behavior

All mandatory and empty fields should display the respective error if left blank.

## Actual Behaviour

"First Name" and "Last Name" fields not displaying "can't be blank" error

## Steps to Reproduce

1. Try to proceed to Payment details with the two name fields left empty.

## Animated Gif/Screenshot

Previous checkout (left) vs. new checkout:

### PR DESCRIPTION
**Pull request by jibees**
No company = company is blank or company is "unused"

#### What? Why?
What I've found: https://github.com/openfoodfoundation/openfoodnetwork/issues/8691#issuecomment-1008884971
Closes #8691 

Note sure of this one, needs a review from @Matt-Yorkley and @apricot12 at least:
 - Maybe we should add some testing notes
 - Does any _company_ field is used for an order form?

Automatic testing will be done thanks to #8683 

#### What should we test?
Test that in the split checkout, the first name and the last name are well validated: they cannot be empty.

Capture d’écran 2022-01-10 à 14 59 00

#### Release notes
Split checkout: validate first name and last name of the order

Changelog Category: User facing changes

### CODE REVIEW

**Comment by apricot12** [comment]
@jibees As far as I know, and from my discussions with Matt while working on [6243](https://github.com/openfoodfoundation/openfoodnetwork/issues/6243), the Company field is totally unused anywhere except for the new business address form introduced in [PR#7973](https://github.com/openfoodfoundation/openfoodnetwork/pull/7973).

**Review by apricot12 — APPROVED** [review]
This should account for everything. LGTM 👍

File: app/models/spree/address.rb [hunk 1]
```diff
@@ -15,7 +15,9 @@ class Address < ApplicationRecord
 
     validates :address1, :city, :country, :phone, presence: true
     validates :company, presence: true, unless: -> { first_name.blank? || last_name.blank? }
-    validates :firstname, :lastname, presence: true, unless: -> { company.present? }
+    validates :firstname, :lastname, presence: true, if: -> do
+      company.blank? || company == I18n.t(:unused)
```
Comment (Matt-Yorkley) [inline app/models/spree/address.rb:19]: Hmm... I don't really like this hack where we set various fields to be `unused` in general... I'd really like it if we completely removed that at some point. But maybe that's an issue for another day.

Assuming we're sticking with that for now; we should be comparing `company` to `'unused'` here instead of `I18n.t(:unused)`, because the relevant lines are here:

https://github.com/openfoodfoundation/openfoodnetwork/blob/1b79fdd333f738de2d76bd215f4c0c3efd205897/app/models/concerns/set_unused_address_fields.rb#L13-L14

Comment (Matt-Yorkley) [reply app/models/spree/address.rb:19]:
```suggestion
      company.blank? || company == 'unused'
```

Comment (jibees) [reply app/models/spree/address.rb]: You're right, I've created an issue: #8697

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Looks good now:

Peek 2022-01-12 19-46

I'll update the tests in #8683, after merging :+1

PS: the error message at the top is also displayed correctly, it just got clipped out.
