### PR TITLE
Disallow changes of canceled order

### LINKED ISSUE #7166: Changing line item quantities on cancelled orders leads to stock management discrepancies
## Description

When an order is cancelled, the quantity from a given line item is returned to the `on_hand` amount, for that variant.
After this it is possible to edit the order, and reduce the line item amount or remove the line item, which _also_ returns them to the `on_hand` amount. Doing so ends up with an `on_hand` increased amount, up to 2x the initial one.

## Expected Behavior

It should not be possible to change the amount of a line item or to remove a line item, in cancelled orders; to do so, the order should be resumed.

## Actual Behaviour

It is possible to change the amount of a line item or to remove a line item, in cancelled orders, without resuming the order.

## Steps to Reproduce

1. Set a `on_hand` amount for a variant to = 3
2. Place an order with a line `item`, `quantity`: 3
3. Check your stock: Expect it to be out of stock.
4. Cancel the order. 
5. Check your stock again: Expect it to = 3. (cancelling an order automatically returns the item)
6. Edit the order.
7. Set the `quantity` for that `item` to = 0; or click the trash bin and remove the line item.
8. Check your stock again: It is now = 6.... (twice as much as in the beginning...)

## Animated Gif/Screenshot

Steps 6 - 8:

Peek 2021-03-19 10-29

## Severity

A customer can place orders when the displayed stock does not display the original settings - s2 i think

## Your Environment

* Version used: v3.6.8
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #7166.
Complements #7228 and #7265.

Updating cancelled orders messes with stock and payment amounts. So we decided to not allow that. Previous PRs removed the UI but here I'm also putting guards in the controllers so that this doesn't happen accidentally or via the API.

#### What should we test?

* Checkout for a completed order.
* Add, remove and adjust line items of the order as shop owner. Everything should work as normal.
* Open a new tab to change adjustments, as normal.
* Open a third tab to cancel the order.
* Going back to the previous two tabs, try to change adjustments or line items. It should not change anything.
* Reload the pages and observe that the edit buttons are gone.

#### Release notes

Changelog Category: User facing changes

It's not possible to change the contents of cancelled orders any more to avoid inconsistencies.

### CODE REVIEW

File: spec/controllers/api/v0/shipments_controller_spec.rb [hunk 1]
```diff
@@ -110,28 +110,69 @@
...
-                         order_id: order.to_param,
-                         id: order.shipments.first.to_param
+      context "for canceled orders" do
+        before do
+          expect(order.cancel).to eq true
+        end
 
-        expect(response.status).to eq(200)
-        expect(inventory_units_for(variant).size).to eq(1)
+        it "doesn't adjusts stock when adding a variant" do
```
Comment (sauloperez) [inline spec/controllers/api/v0/shipments_controller_spec.rb:163]: :warning: typo on `adjusts`

File: spec/controllers/api/v0/shipments_controller_spec.rb [hunk 2]
```diff
@@ -110,28 +110,69 @@
...
+          expect {
+            api_put :add, params.merge(variant_id: existing_variant.to_param)
+            expect(response.status).to eq(422)
+          }.to_not change { existing_variant.reload.on_hand }
+        end
+
+        it "doesn't adjusts stock when removing a variant" do
```
Comment (sauloperez) [inline spec/controllers/api/v0/shipments_controller_spec.rb:170]: here as well

File: spec/controllers/api/v0/shipments_controller_spec.rb [hunk 3]
```diff
@@ -110,28 +110,69 @@
...
 
-      it 'removes a variant from a shipment' do
-        order.contents.add(variant, 2)
-        api_put :remove, variant_id: variant.to_param,
-                         quantity: 1,
-                         order_id: order.to_param,
-                         id: order.shipments.first.to_param
+      context "for canceled orders" do
+        before do
+          expect(order.cancel).to eq true
```
Comment (sauloperez) [inline spec/controllers/api/v0/shipments_controller_spec.rb:160]: I'm not a big fan of asserting things in the test setup phase. It feels a bit like defensive and unconfident programming and it adds up to the build time. If `cancel` didn't work we would notice because the test would fail, right?

**Review by sauloperez — COMMENTED** [review]
You nailed it with those tests :clap:

File: app/controllers/api/v0/shipments_controller.rb [hunk 4]
```diff
@@ -8,6 +8,7 @@ class ShipmentsController < Api::V0::BaseController
       respond_to :json
 
       before_action :find_order
+      before_action :refuse_changing_cancelled_orders, only: [:add, :remove]
```
Comment (andrewpbrett) [inline app/controllers/api/v0/shipments_controller.rb:11]: Documentation by method name 👍

**Review by andrewpbrett — APPROVED** [review]
Thanks @mkllnk!

File: app/controllers/spree/admin/adjustments_controller.rb [hunk 5]
```diff
@@ -28,6 +29,10 @@ def set_order_id
         @adjustment.order_id = parent.id
       end
 
+      def skip_changing_canceled_orders
+        redirect_to admin_order_adjustments_path(@order) if @order.canceled?
```
Comment (Matt-Yorkley) [inline app/controllers/spree/admin/adjustments_controller.rb:33]: It feels like a flash message would be helpful here to give some user feedback.

**Review by Matt-Yorkley — APPROVED** [review]

File: spec/controllers/api/v0/shipments_controller_spec.rb (hunk 3 above)
Comment (mkllnk) [reply spec/controllers/api/v0/shipments_controller_spec.rb:160]: I'm not a big fan of asserting in the setup either. But I do want to know if something goes wrong here and I don't think that this assertion slows the tests down much.

If `cancel` doesn't work then the order might be in an unknown state with unknown behaviour and we don't know if that would pass or fail the test. I wish I could rely on it to work. My experience is though that it can be tricky to get the test setup right and then things don't behave as expected.

The best solution would probably be to add a new factory: `create(:cancelled_order)`. Another time...

File: app/controllers/spree/admin/adjustments_controller.rb (hunk 5 above)
Comment (mkllnk) [reply app/controllers/spree/admin/adjustments_controller.rb]: I added a commit for this.

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,

Thanks for the work and the detailed steps on how to test this. Going though them stepwise:

- Checked out for a completed order.
- Added, removed and adjusted line items of the order as shop owner.
At this point, I met this bug again, when deleting adjustments (not related to this issue) - #7341

- Opened a new tab to change adjustments, as normal.
- Opened a third tab to cancel the order.

After this, going back to the previous two tabs:
i)  tried to change line items, changing shipping method: all good here. Changes don't take effect at all - OK

ii) Editing or creating new adjustments displays the warning below, and takes no effect - OK
image
iii) deleting adjustments :
   - if the adjustment is a transaction fee -> one sees bug - #7341 
   - if the adjustment is something else (tax, or an enterprise fee) -> deleting appears to work (the adjustment is removed):
Peek 2021-04-07 22-08

So maybe on point iii) there would be room for improvement. I'll create  an issue to prevent deleting of adjustments, if an order was cancelled on a different tab - which is in a way an edge case.

But I think this brings plenty of value, so we should merge it :+1: Moving to ready to go.
