### PR TITLE
fix rubocop Rails/ResponseParseBody

### LINKED ISSUE #12620: Rubocop Rails/ResponseParsedBody
Fix [Rails/ResponseParsedBody](https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/ResponseParsedBody)

### PR DESCRIPTION
**Pull request by Yassir4**
#### What? Why?

- Closes #12620 
- Fixes the RuboCop Rails/ResponseParsedBody
##### Note
I disabled the RuboCop check on the `spec/controllers/user_registrations_controller_spec.rb` because the response is returned using [format.js](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/user_registrations_controller.rb#L54) not format.json which doesn't work well with the parsed_body method.

#### What should we test?
- Manual test for successful user registration/signup. Check JS console in case of any errors/warnings.
- Test should pass for the spec file changed

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

**Review by rioug — COMMENTED** [review]
Thanks @Yassir4 :pray: !

> I disabled the RuboCop check on the spec/controllers/user_registrations_controller_spec.rb because the response is returned using [format.js](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/user_registrations_controller.rb#L54) not format.json which doesn't work well with the parsed_body method.

It looks like something that should be using `format.json` and that we should fix, Would you want to give this a go ?

File: spec/controllers/user_registrations_controller_spec.rb [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 require 'spec_helper'
 
+# rubocop:disable Rails/ResponseParsedBody
 RSpec.describe UserRegistrationsController, type: :controller do
```
Comment (dacook) [inline spec/controllers/user_registrations_controller_spec.rb:6]: > It looks like something that should be using `format.json` and that we should fix

Agreed, this should be fixed if possible.

Alternatively, we shouldn't disable the rubocop rule here. It's a violation that is still "to do"

**Review by dacook — CHANGES_REQUESTED** [review]

File: spec/controllers/user_registrations_controller_spec.rb (hunk 1 above)
Comment (Yassir4) [reply spec/controllers/user_registrations_controller_spec.rb:6]: @rioug @dacook 

I will tackle it.

The UserRegistrationsController#create is not yet used for signup, I saw an [open issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/4019) for `merging Spree::UserRegistrationsController into UserRegistrationsController`, so changing the format won't break anything

**Review by rioug — APPROVED** [review]
Awesome ! thank you @Yassir4 :pray:  
FYI for next time, we tend to prefer rebasing the branch on master, rather than merging master.

**Comment by filipefurtad0** [comment]
Hey @Yassir4,


Thanks for this PR as well. (Thank you @dacook for the notes on what to test).
I have not spotted any new errors on the console, when registering a new user - those on the picture are pre-existent (those appearing on Stripe are intermittent and I don't think relate to this PR):


Before this PR

image

After this PR

image

All working as before. Merging.
