### PR TITLE
Admin, Reports: Inverting logic from "Columns to hide" to "Columns to show"

### LINKED ISSUE #9168: [Split Checkout] Should a shipment be created on the `/summary` step?
## Description

This issue is meant as a placeholder to double-check if the current behavior is correct. So not bug per se, rather a code/feature logic/design question:

Do we need to create shipments on the /summary step?

On legacy checkout: a shipment is created once the used clicks "Place order now".
On Split Checkout: a shipment is created once the user visits the `/summary` step, and before clicking "Complete order".

Why is this important?

If a shipment is created on `/summary` but the user goes back to `/details` shipping info may be changed. This means that the `shipment` entity needs to be updated or destroyed accordingly. This can influence the calculation of taxes, for example.

I've found no controller specs documenting this behavior.

## Actual Behaviour

On legacy checkout: a shipment is created once the used clicks "Place order now".
On Split Checkout: a shipment is created once the user visits the `/summary` step, and before clicking "Complete order".

## Steps to Reproduce

On legacy checkout:
1. Visit the /checkout page
2. Check the DB looking for shipments associated with that order -> see there is **none**.

On split-checkout:
1. Visit the `/payment` page
2. Check the DB looking for shipments associated with that order -> see there is **none**.
3. Proceed to `/summary`
4. Check the DB looking for shipments associated with that order -> see there is **one**.

## Animated Gif/Screenshot

Legacy Checkout (using the order id for that cart order):
image

Split-Checkout (using the order id for that cart order):
image

## Related

Clicking the empty cart destroys shipments associated with the order. If the shipment is missing the `/summary` page will not render, see #9131.

### LINKED ISSUE #9186: [UX] [Reports] Improve UX of Show/Hide Columns in Reports

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9186 
This one prepares the changes of inverting logic around columns for all the reports. Basically, we move from "columns to hide" concept to "columns to show" concept.
Each changes is behind a feature toggle: `report_inverse_columns_logic`

###### With feature toggle activated
- As an admin, visit reports index page under `/admin/reports`
- You should see all report + their subreport:
Capture d’écran 2022-05-31 à 16 01 31

- Click on a subreport, in the rendering option, you should:
  - Not see the `Report Type` option
  - See a `Columns` selector (instead of a `Columns to hide` selector), which can be used to hide/show columns:
Capture d’écran 2022-05-31 à 16 03 34
Capture d’écran 2022-05-31 à 16 03 50

###### Without feature toggle activated
Nothing should change around reports, worth checking it.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: lib/reporting/report_row_builder.rb [hunk 1]
```diff
@@ -27,7 +27,7 @@ def build_row(item)
     end
 
     def slice_and_format_row(row)
-      result = row.to_h.reject { |k, _v| k.in?(report.fields_to_hide) }
+      result = row.to_h.select { |k, _v| k.in?(report.fields_to_show) }
```
Comment (jibees) [inline lib/reporting/report_row_builder.rb:30]: Not sure on how to handle this one with the `group_by` option.
Currently, the spec `spec/lib/reports/report_spec.rb:153` fails, because of grouping option.

```diff
@@ -1,10 +1,10 @@
        [{:header=>"Hub 1"},
         {:header=>"Abby"},
       - {:product=>"Orange", :quantity=>6},
       + {:customer=>"Abby", :hub=>"Hub 1", :product=>"Orange", :quantity=>6},
         {:header=>"John"},
       - {:product=>"Apple", :quantity=>4},
       + {:customer=>"John", :hub=>"Hub 1", :product=>"Apple", :quantity=>4},
         {:header=>"Hub 2"},
         {:header=>"John"},
       - {:product=>"Pear", :quantity=>3},
       - {:product=>"Apple", :quantity=>5}]
       + {:customer=>"John", :hub=>"Hub 2", :product=>"Pear", :quantity=>3},
       + {:customer=>"John", :hub=>"Hub 2", :product=>"Apple", :quantity=>5}]
```

We should _remove_ or _unselect_ columns that are grouped (such as `hub` and `customer`) in the spec. 

If @seballot you could point me something... Thanks a lot! 🙏

File: lib/reporting/report_headers_builder.rb [hunk 2]
```diff
@@ -18,12 +18,12 @@ def available_headers
       report.columns.keys.map { |key| [translate_header(key), key] }
     end
 
-    def fields_to_hide
+    def fields_to_show
```
Comment (seballot) [inline lib/reporting/report_headers_builder.rb:21]: Hi @jibees, I think what you are missing is this method. It should be changed to something like

```
fields_in_headers = if report.display_header_row?
                      report.formatted_rules.map { |rule| rule[:fields_used_in_header] }.flatten.reject(&:blank?)
                    else
                      []
                    end
params_fields_to_show - fields_in_headers
```

Comment (seballot) [inline lib/reporting/report_headers_builder.rb:21]: Hi @jibees, I think what you are missing is this method. It should be changed to something like

```
fields_in_headers = if report.display_header_row?
                      report.formatted_rules.map { |rule| rule[:fields_used_in_header] }.flatten.reject(&:blank?)
                    else
                      []
                    end
params_fields_to_show - fields_in_headers
```

**Comment by seballot** [comment]
Hi !

I'm not sure about reloading the page, cause people will lose what they have done in filter section right?

Maybe we can just remove the subreport select and adjust the report index so only subreports links are available? @lin-d-hop WDYT?

**Comment by jibees** [comment]
> I'm not sure about reloading the page, cause people will lose what they have done in filter section right?

You're right. I didn't think about it. 

> Maybe we can just remove the subreport select and adjust the report index so only subreports links are available?

That one sounds brillant.

File: lib/reporting/report_headers_builder.rb (hunk 2 above)
Comment (jibees) [reply lib/reporting/report_headers_builder.rb:21]: Thanks!

**Comment by jibees** [comment]
pinging @openfoodfoundation/train-drivers-product-owners and adding label ;)

**Comment by jibees** [comment]
So, so proposed solution is: 
 - to include for `Bulk Co-Op`, `Payment Reports` and `Xero Invoices` theirs sub-report into the index page and it's done for `Orders & Fulfillment Reports` report for example
 - remove for all those reports the `Report type` section in the `RENDERING OPTIONS` section in the form

I think we will gain in term of clarity and it's then easier to implement this PR

What do you think?

**Comment by jibees** [comment]
Updates: Put all of the changes behind a feature toggle: `report_inverse_columns_logic`

File: lib/reporting/report_headers_builder.rb [hunk 3]
```diff
@@ -18,12 +18,15 @@ def available_headers
...
-      end.concat(params_fields_to_hide)
+    def fields_to_show
+      fields_in_headers = if report.display_header_row?
+                            report.formatted_rules.map { |rule|
+                              rule[:fields_used_in_header]
+                            }.flatten.reject(&:blank?)
+                          else
+                            []
+                          end
+      params_fields_to_show - fields_in_headers
```
Comment (mkllnk) [inline lib/reporting/report_headers_builder.rb:44]: Without reading all the code, I don't understand this statement. Why do subtract the header fields from the fields to show? Or why do we *not* show header fields?

File: lib/reporting/report_row_builder.rb (hunk 1 above)
Comment (mkllnk) [inline lib/reporting/report_row_builder.rb]: This is probably easier for the feature toggle but otherwise I would have thought that we can simplify it:
```rb
result = row.to_h.slice(report.fields_to_show)
```

File: app/controllers/admin/reports_controller.rb [hunk 4]
```diff
@@ -46,6 +46,7 @@ def assign_view_data
 
       # Initialize data
       params[:display_summary_row] = true if request.get?
+      params[:fields_to_show] = @report.columns.keys if request.get?
```
Comment (mkllnk) [inline app/controllers/admin/reports_controller.rb]: It would be much cleaner to use `params_fields_to_show` and leave the params unaltered. Never a good idea to change the `params` object.

**Review by mkllnk — APPROVED** [review]
Looking good to me.

File: lib/reporting/report_row_builder.rb (hunk 1 above)
Comment (jibees) [reply lib/reporting/report_row_builder.rb]: Yeap. I maybe find out more readable in the case of feature toggle (`select`/`reject`):

```ruby
if OpenFoodNetwork::FeatureToggle.enabled?(:report_inverse_columns_logic, @current_user)
 row.to_h.select { |k, _v| k.in?(report.fields_to_show) }
else
 row.to_h.reject { |k, _v| k.in?(report.fields_to_hide) }
end
```

File: app/controllers/admin/reports_controller.rb (hunk 4 above)
Comment (jibees) [reply app/controllers/admin/reports_controller.rb]: Ok, see commit: #560c1e2e0:

```ruby
@params_fields_to_show = if request.get?
                           @report.columns.keys
                         else
                           params[:fields_to_show]
                         end
```

File: lib/reporting/report_headers_builder.rb (hunk 3 above)
Comment (jibees) [reply lib/reporting/report_headers_builder.rb:44]: I'll talk under the control of @seballot but as I can see, `fields_used_in_header` are fields that:
> will be hidden when the header_row is activated

So we need to remove them in order to be shown (don't know if I'm clear)

Comment (seballot) [reply lib/reporting/report_headers_builder.rb:44]: Yes that's it. If the table have given_name / family_name / product / price, and we activate the header_row and the header_row display given_name && family_name, then we only want to display product and price column
```
GivenName | FamilyName | Product1 | XX €
GivenName | FamilyName | Product2 | XX €

Turns into

Header: Given_name Family Name
Product1 | XX €
Product2 | XX €
```

Comment (mkllnk) [reply lib/reporting/report_headers_builder.rb:44]: Ah, thank you for that example. I wasn't aware of that transformation. Interesting. We can probably find a better way to represent that but that's out of scope here.

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Thanks for the detailed notes on what to test.

The feature toggle works as expected:

- with `report_inverse_columns_logic` **deactivated**

The current behavior (i.e. before this PR) is observed:

- we don't see all report + their subreport types (on `/admin/reports`):

image

- we still see the Report Type option

image

- the Columns selector still works with a `hide` logic 

image


- with `report_inverse_columns_logic` **activated**

The code is correctly activated and:

- we see all report + their subreport types (on `/admin/reports`):

image

- the Report Type option is not displayed

image

- the Columns selector now works with a `display` logic 

image

- despite the new display logic, if no columns are selected, than all columns are displayed:

image


However, it seems that it's not possible to access certain report subtypes, when
- clicking the specific link 
- clicking the `/admin/reports/customers`

For example, I could not find a way to render the `/admin/reports/customers` for Addresses. Below, left - before this PR; right - after this PR:

Peek 2022-06-10 09-56


In any case, I think this would be safe to merge though as:
i) not on the next release
ii) behind a feature toggle

What do you think @jibees ?

**Comment by jibees** [comment]
>  I think this would be safe to merge

I agree with you. But you catch a bug closely related to this PR, so I'd say should go back to `In Dev`...

**Comment by filipefurtad0** [comment]
Hey @jibees ,

The points mentioned before are fixed, we can now render the all reports. This now allowed to uncover a minor formatting regression on tax reports:

`sales_tax`

After **activating** the feature:
image

After **deactivating** the feature:
image

Please let me know how you prefer:
- merging + opening issue
- back to in dev

In any case, there is plenty going on here, I wonder if we should not role this one out progressively: its quite challenging to assure we have no regressions with these manual tests.

Thanks :pray:

**Comment by jibees** [comment]
I do prefer _back to in dev_

🙏

**Comment by jibees** [comment]
One commit added, back in `Code Review`

**Review by mkllnk — APPROVED** [review]
Great!

File: spec/system/admin/reports_spec.rb [hunk 5]
```diff
@@ -31,37 +31,54 @@
...
   end
 
-  describe "Customers report" do
+  shared_examples "Can access Customers reports and generate report" do |inverse_columns_logic|
     before do
-      login_as_admin_and_visit admin_reports_path
+      allow(OpenFoodNetwork::FeatureToggle).to receive(:enabled?).with(
+        :report_inverse_columns_logic, anything
+      ).and_return(inverse_columns_logic)
     end
```
Comment (filipefurtad0) [inline spec/system/admin/reports_spec.rb:39]: Would it make sense to toggle this feature and let the build run to check for regressions?

If I understand correctly, currently only "Customers report" is tested with the feature toggled.

Comment (jibees) [reply spec/system/admin/reports_spec.rb:39]: Also `sales tax report`, but yes it's probably incomplete ...
