### PR TITLE
Soft-delete price objects

### LINKED ISSUE #3907: Delete product will break the shopfront (during the current OC) of all users who have bought that item in the current OC
## Description
When I log in with my producer account in Katuma's production I get a weird error and cannot do anything else.

## Steps to Reproduce
Just log in with my account rachel.arnould+carrots@gmail.com

Yesterday I was testing stuff and when I was done I turned my enterprise as "not visible" anymore as I didn't want any real customer to see it. Maybe this is having an impact?

## Animated Gif/Screenshot
image

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v.2.0.2
* Browser name and version: Firefox and Chromium
* Operating System and version (desktop or mobile): Desktop and mobile

### LINKED ISSUE #4053: Delete a product that is sold in an OC and all buyers with this item in their cart will see an error 500
## Description
As a manager, if I delete a product that is sold in an OC, all buyers with this item in their cart will see an error 500 when trying to reach the website.

## Steps to Reproduce
1. As buyer, add a variant in your cart
2. In a private windows, connect as a manager and delete that product while leaving the OC open
3. Try to reach the website as a buyer again (ANY page) and you will see an error 500, 

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop Ubuntu 19.10

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #4053
Closes #3907 
Possibly #4203 as well..?

Missing Spree::Price records were causing fatal errors in various scenarios where a product had been deleted.

Prices are now soft-deleted and can be accessed by associated variants.

Variants that have previously been soft-deleted and have had their associated price objects _hard_-deleted are removed from open carts via a migration.

#### What should we test?

- Add a product to the cart
- Go to backoffice and delete the product
- Go back to the cart
- The site is ok, and there's no error 500 

#### Release notes

Added soft-delete to price records to fix issues with soft-deleted products

Changelog Category: Fixed

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
I'm not sure about this migration...

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+    # Removes line_items from open carts where the variant has a hard-deleted price
+
+    variants_with_prices = Spree::Variant.
+      joins('INNER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id)').
+      select('spree_variants.id')
+
+    Spree::LineItem.
+      joins(:variant).where('spree_variants.id NOT IN (?)', variants_with_prices).
+      joins(:order).merge(Spree::Order.where(state: 'cart')).
+      delete_all
```
Comment (luisramos0) [inline db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: 1. is this the only migration we need here? I cant remember but maybe there is more data that needs to be cleaned up?

2. I think you should invert the first query because variants_with_prices can be too big
- I think you need to use arel for this (I never used it)
variants_without_price = select * from spree_variants v where not exists (select 1 from spree_prices where variant_id = v.id)
and then same second query with IN instead of NOT IN

Comment (Matt-Yorkley) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: I've updated the queries and tested them more thoroughly in the Rails console. :+1:

I'm not sure how much more we can clear up in terms of data. We can't restore hard-deleted prices, and I don't think we can reasonably remove line_items from completed orders.

File: db/migrate/20190830134723_add_deleted_at_to_spree_prices.rb [hunk 2]
```diff
@@ -0,0 +1,6 @@
+class AddDeletedAtToSpreePrices < ActiveRecord::Migration
+  def change
+    add_column :spree_prices, :deleted_at, :datetime
+    add_index :spree_prices, :deleted_at
```
Comment (sauloperez) [inline db/migrate/20190830134723_add_deleted_at_to_spree_prices.rb]: I think we've discussed this before but indexes on boolean columns are little to no value and make writes slower. I wouldn't add it.

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb [hunk 3]
```diff
@@ -0,0 +1,17 @@
...
+    # Removes line_items from open carts where the variant has a hard-deleted price
+
+    variants_without_prices = execute(
+      'SELECT spree_variants.id FROM spree_variants
+      LEFT OUTER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id)
+      WHERE NOT EXISTS (SELECT 1 FROM spree_prices WHERE spree_prices.variant_id = spree_variants.id)'
+    ).to_a.map{ |v| v['id'].to_i }
+
+    broken_line_items = Spree::LineItem.
+      joins(:variant).where('spree_variants.id IN (?)', variants_without_prices).
```
Comment (sauloperez) [inline db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: I know it might not make much difference given the numbers of affected variants but this is a pattern I see over and over again that has performance and complexity implications. We do a lot of pointless back and forth to the DB in cases that the DB can handself itself without having to resort to Ruby.

There's no need to collect the variant ids in line 9 to pass them back again if we perform a subquery. That can be achieved passing an ActiveRecord::Relation to the where method like:

```ruby
variants_without_prices = 'SELECT spree_variants.id FROM spree_variants
LEFT OUTER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id)
WHERE NOT EXISTS (SELECT 1 FROM spree_prices WHERE spree_prices.variant_id = spree_variants.id)'

broken_line_items = Spree::LineItem.
      joins(:variant).
      joins(:order).
      where(variant: { id: variants_without_prices }).
      merge(Spree::Order.where(state: 'cart')).

broken_line_items.each(&:destroy)
```

File: db/migrate/20190830134723_add_deleted_at_to_spree_prices.rb (hunk 2 above)
Comment (Matt-Yorkley) [reply db/migrate/20190830134723_add_deleted_at_to_spree_prices.rb]: It was recommended in the paranoia gem's documentation, but I can remove it :+1:

Comment (Matt-Yorkley) [reply db/migrate/20190830134723_add_deleted_at_to_spree_prices.rb]: Removed :+1:

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb (hunk 3 above)
Comment (Matt-Yorkley) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: Updated :+1:

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb [hunk 4]
```diff
@@ -0,0 +1,15 @@
+class RemoveBrokenVariantsFromCarts < ActiveRecord::Migration
+  def up
+    # Removes line_items from open carts where the variant has a hard-deleted price
+
+    variants_without_prices = 'SELECT spree_variants.id FROM spree_variants
+      LEFT OUTER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id)
+      WHERE NOT EXISTS (SELECT 1 FROM spree_prices WHERE spree_prices.variant_id = spree_variants.id)'
```
Comment (mkllnk) [inline db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: Wow, I've never seen this clause. I would have written this:
```sql
WHERE spree_prices.id IS NULL
```

In the joined table, all variants that don't have a price will have NULL in all spree_prices columns. @sauloperez What's your opinion on this?

Another way would be to use a subquery:
```sql
SELECT spree_variants.id FROM spree_variants
WHERE spree_variants.id NOT IN (SELECT spree_prices.id FROM spree_prices)
```
But I'm not sure what's more efficient. I believe that a subquery would be really slow in Mysql because it doesn't index that sub-query result. Not sure about Postgres.

Comment (sauloperez) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: Yep, good catch @mkllnk . We need to filter out variants that have price with that `WHERE spree_prices.id IS NULL`. @Matt-Yorkley https://blog.codinghorror.com/a-visual-explanation-of-sql-joins/ is your friend.

File: db/migrate/20190830134723_add_deleted_at_to_spree_prices.rb (hunk 2 above)
Comment (kristinalim) [reply db/migrate/20190830134723_add_deleted_at_to_spree_prices.rb]: > I think we've discussed this before but indexes on boolean columns add little to no value and make writes slower. I wouldn't add it.

I didn't know. This is useful information, thanks. @sauloperez

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb (hunk 4 above)
Comment (luisramos0) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: I think this is the better SQL:
```
variants_without_prices = 'SELECT spree_variants.id FROM spree_variants
      LEFT OUTER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id)
      WHERE spree_prices.id IS NULL
```

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb [hunk 5]
```diff
@@ -0,0 +1,15 @@
...
+
+    broken_line_items = Spree::LineItem.
+      joins(:variant).where(variant: { id: variants_without_prices }).
```
Comment (kristinalim) [inline db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: This migration is failing - It currently compares `variant.id` against the SQL subquery string above. I don't actually know how to use subqueries with the `where` method yet.

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb (hunk 4 above)
Comment (kristinalim) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: I like the suggestion of @luisramos0. :+1:

**Comment by luisramos0** [comment]
Hey, looking at this one again, why dont we "add deleted prices to deleted variants without prices"?

I think this is harmless:
```sql
insert into spree_prices (variant_id, amount, currency, deleted_at)
SELECT spree_variants.id, '0.00', (select value from spree_preferences where key = 'spree/app_configuration/currency'), now()
FROM spree_variants
LEFT OUTER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id)
WHERE spree_prices.id IS NULL;
```

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb (hunk 4 above)
Comment (sauloperez) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: credits to you @mkllnk :trollface:

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb (hunk 5 above)
Comment (sauloperez) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: Might be a Rails specific version :thinking: . But I tested in a Rails console and it correctly performed a single query using the subquery above.

**Comment by sauloperez** [comment]
That would keep the line items which is always better

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb (hunk 4 above)
Comment (Matt-Yorkley) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: These queries seem to give exactly the same results:
```ruby
SELECT spree_variants.id FROM spree_variants LEFT OUTER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id) 
WHERE NOT EXISTS (SELECT 1 FROM spree_prices WHERE spree_prices.variant_id = spree_variants.id)
```

```ruby
SELECT spree_variants.id FROM spree_variants LEFT OUTER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id) 
WHERE spree_prices.id IS NULL
```

**Comment by Matt-Yorkley** [comment]
>  why dont we "add deleted prices to deleted variants without prices"?

What happens when someone orders that product for `0.00`?

**Comment by luisramos0** [comment]
>>>  why dont we "add deleted prices to deleted variants without prices"?

> What happens when someone orders that product for `0.00`?

The variant is deleted so no one will buy it. Right?

File: db/migrate/20190906165501_remove_broken_variants_from_carts.rb [hunk 6]
```diff
@@ -0,0 +1,17 @@
+class RemoveBrokenVariantsFromCarts < ActiveRecord::Migration
+  def up
+    # Removes line_items from open carts where the variant has a hard-deleted price
+
+    variants_without_prices = execute(
+      'SELECT spree_variants.id FROM spree_variants
+      LEFT OUTER JOIN spree_prices ON (spree_variants.id = spree_prices.variant_id)
+      WHERE spree_prices.id IS NULL'
+    ).to_a.map{ |v| v['id'] }
```
[the remark this answers is not in the document]
Comment (sauloperez) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: let me know next time because there must be a way

[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: If you can provide an example that works, that would be awesome. :+1:

[the remark this answers is not in the document]
Comment (sauloperez) [reply db/migrate/20190906165501_remove_broken_variants_from_carts.rb]: I did a quick check on a Rails console with some dummy AR but I'll keep it in mind next time

**Comment by RachL** [comment]
Here is the test I've carried out on French staging:

1. I've added Fuji Apple on Mary's shop to my cart with my protonmail email address
2. I've deleted Fuji Apple as super admin
3. Then tried to checkout my cart with my personal account and got this:

image


I still could navigated within the site with no problem :+1: 🎉

**Comment by luisramos0** [comment]
there was a missing db:migrate in this PR to update db/schema.rb, I run it now in master and pushed it directly to master:
https://github.com/openfoodfoundation/openfoodnetwork/commit/2683efdd3c8124cc5607ba6e5653a312c0bcb36d
