### PR TITLE
Fix #6543

### LINKED ISSUE #6543: 3D-Secure cards not charged when placing subscriptions with Stripe SCA payment method
## Description

PR #6469 introduces changes on the setup and offline charging for subscriptions.

Before this PR, orders placed through subscriptions with Stripe SCA in combination with an authenticated 3D-Secure card (such as 4000002760003184) are not charged, and return the error - seen on the emails to the customer/hub:

`Invalid payment state`

After this PR, the customer can proceed to the authentication in  in the customer section `/account#/cards` of that card. However, placing the order results in an uncharged card, returning the error, via Email:

`Your card was declined. This transaction requires authentication. `

This introduces a regression, see discussion:
https://openfoodnetwork.slack.com/archives/CSCPHGVSS/p1608203766100600

## Expected Behavior

Stripe-SCA charges from 3D-auth cards should allow the placement of subscriptions.

## Actual Behaviour

Stripe-SCA charges from 3D-auth cards currently do not allow the placement of subscriptions.

## Steps to Reproduce

Customer
1. Add the 3D-secure card `4000002760003184` to the /account#/cards section.
2. Allow charges to a given hub
3. The authentication window should pop-up. Confirm authentication for that card.

Admin
1. Set up an OC, with a schedule - take note of the OC id number
2. Create a subscription for the customer above, setting the Stripe SCA as a payment method (optional: take note of the subscription id number)

Test the placement of the set subscription, following the procedure described:
- here https://github.com/openfoodfoundation/openfoodnetwork/wiki/Testing-Subscriptions (you'll need both OC and Subscription id nr.)
- or following #6291 - (you'll need the OC id nr.) a fix is underway for this, which reduces the waiting time, after the confirmation of the subscription (#6541)

## Your Environment

* Version used: this would be introduced in upcoming v3.4.5
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes https://github.com/openfoodfoundation/openfoodnetwork/issues/6543

In refactoring to a CreditCardCloneFinder, I combined two conditionals in order to appease Rubocop's desire for <=10 lines per method: https://github.com/openfoodfoundation/openfoodnetwork/pull/6469/commits/4c25edd91c395a22d592ad6ae7e0506e2879ca13

Combining the two conditionals meant that `fingerprint` was getting set to the result of `email = @card.user&.email` instead of the result of `fingerprint_for_card(@card)`.

This separates the two conditionals to fix it. 

#### What should we test?
The x-3155 credit card should now be able to be set up and charged offline for subscriptions. 

#### Release notes
n/a

### CODE REVIEW

**Review by lin-d-hop — APPROVED** [review]

**Comment by lin-d-hop** [comment]
This is a simple enough review that I feel confident reviewing ;-)

File: lib/stripe/credit_card_clone_finder.rb [hunk 1]
```diff
@@ -8,7 +8,8 @@ def initialize(card, stripe_account)
     end
 
     def find_cloned_card
-      return nil unless fingerprint = fingerprint_for_card(@card) && email = @card.user&.email
```
Comment (mkllnk) [inline lib/stripe/credit_card_clone_finder.rb:11]: Yeah, assignments are usually discouraged in conditionals. Combining that with boolean logic without brackets isn't very clear.
