### PR TITLE
13221 - Don't allow shipped orders to be editable

### LINKED ISSUE #13221: [Order edit] Shipped orders are editable
## Description

When orders are shipped it should in principle not be possible to edit them; currently, when editing a shipped order, the pencil and trashbin next to the line item are not visible, to prevent customers from changing quantities on shipped orders. However, the product dropdown remains active and it is possible to add new products to the order, despite having been shipped already.

## Expected Behavior

It should not be possible to add new line items or payments to shipped orders.

## Actual Behaviour

It's possible to add new line items or payments to shipped orders.

## Steps to Reproduce

1. As a hub, ship an order.
2. Visit the edit page for that order.
3. Notice the missing pencil/trashbin next to the existing line items; notice the product dropdown is active and allows adding new line items to the order:
4. Click on the dropdown and search for an existing product on that order cycle
5. Click the plus sign to add it to the order
6. Notice it gets added to the order as if the order was not shipped and how the order total changes
7. Visit the payments tab; add a new payment.

## Animated Gif/Screenshot

Image

## Workaround

None needed, but better not change shipped orders.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v5.0.18
* Browser name and version: Firefox 136
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by ashishp91**
#### What? Why?

- Closes #13221

#### What should we test?

- Create an order
- Go to http://localhost:3000/admin
- Click on Orders link
- Find the newly created order in the Listing orders
- Notice the shipment state to be pending for the newly created order
- At the right side of the order list item click on capture button to confirm that payment is received
- Then again press the button to ship the order
- When the order is in shipped state click on the order number 
- Confirm that Add Product doesn't have Add product drop down and instead have "Cannot add item to shipped order

"

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by ashishp91** [comment]
Hello @sigmundpetersen, This is ready for review.

**Comment by sigmundpetersen** [comment]
Thank you @ashishp91 
I guess you want to edit the description though, it looks like it's copied from #13256 🙂

**Comment by ashishp91** [comment]
Haha @sigmundpetersen my bad. Updated the description 😆

**Review by chahmedejaz — APPROVED** [review]
Looks good, thanks 🎉

File: spec/system/admin/order_spec.rb [hunk 1]
```diff
@@ -1023,6 +1023,7 @@ def new_order_with_distribution(distributor, order_cycle)
         it "ships the order and shipment email is sent" do
           expect(page).to have_content "ready"
           expect(page).not_to have_content "shipped"
+          expect(page).to have_css("#s2id_add_variant_id")
```
Comment (rioug) [inline spec/system/admin/order_spec.rb:1026]: This is a bit unclear as to what you are trying to do. We have some custom "[select2" matcher](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/support/matchers/select2_matchers.rb)

So you can do something like bellow which is a lot easier to understand : 
```suggestion
          expect(page).to have_select2 "add_variant_id"
```

**Review by rioug — CHANGES_REQUESTED** [review]
Thanks :pray:  for looking into this. So far it looks good, but we are only preventing users from adding product from the frontend, we should also enforce this rule in the back end as well. 
Something like this : https://github.com/openfoodfoundation/openfoodnetwork/blob/915dccc92d5743099e250d5d226c40ab6a04524f/app/controllers/api/v0/shipments_controller.rb#L11

Could you have a look implementing a similar solution for shipped orders ?

**Comment by ashishp91** [comment]
@rioug Please review.

File: db/schema.rb
Comment (rioug) [inline db/schema.rb:1]: This PR shouldn't touch the schema, could you clean this up ?

**Review by rioug — CHANGES_REQUESTED** [review]
Thanks @ashishp91 , it's looking pretty good now, we just need a little bit of clean up.

**Comment by ashishp91** [comment]
@rioug I've removed schema changes.

**Review by rioug — APPROVED** [review]
Thanks @ashishp91 :pray: 
FYI for next time we prefer to rebase the branch on master instead of merging master into the branch, see https://github.com/openfoodfoundation/openfoodnetwork/blob/master/CONTRIBUTING.md#submitting-a-pull-request

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @ashishp91,

Thanks for addressing this issue!

I've compared the behavior introduced by this PR, with the behavior in master:

image

The variant drop-down is hidden, so shipped orders cannot be edited.

The page renders correctly, when using another locale:

image

This looks good! Merging :tada:
