### PR TITLE
Clear opened_at when cloning order cycle 

### LINKED ISSUE #13396: Cloned order cycles aren't processed at open time
## Description
If an order cycle has been opened, then was cloned, the new cloned order cycle will not get processed as open.

This is not (yet) a condition for appearing in the shopfront, but it does affect two features that occur at order cycle opening time:
* Sync remote products (DFC-imported products)
* Send webhook notifications

These features won't work for order cycles that have been cloned.

## Expected Behavior
After cloning an opened order cycle and setting a new future open time, the affected features should work when open time is reached (sync remote products and send webhook notifications)

## Actual Behaviour
I haven't tested, but it doesn't look like it could work.

## Steps to Reproduce
1. Set up test, either or:
   - Set up webhook notifications 
   - Import products from DFC. Change a detail on a product so that it is out of sync.
3.  Find an order cycle that has been previously opened before. It should have a date set in `opened_at`
4. Clone it and choose an open time in the near future. - If testing DFC sync, ensure it contains at least one DFC-imported product
5. Wait until open time.
6. After open time, the webhook notification should be sent, or the products should be synchronised.

## Workaround
Create new order cycle instead of cloning.

## Severity
I think it's only an s5?

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Possible Fix
I think we just need to add `opened_at` to this line: 
https://github.com/openfoodfoundation/openfoodnetwork/blob/75b2119dd17194def7f025d68ffc824e16e7aefb/app/services/order_cycles/clone_service.rb#L12
And check it in the corresponding spec.

### PR DESCRIPTION
**Pull request by rahsheen**
#### What? Why?

- Closes #13396 

If an order cycle has been opened, then was cloned, the new cloned order cycle will not get processed as open because `opened_at` is not cleared during cloning. 

#### What should we test?

1. Find an order cycle that has been previously opened before. It should have a date set in opened_at
2. Clone it and choose an open time in the near future. - If testing DFC sync, ensure it contains at least one DFC-imported product
3. Wait until open time.
4. After open time, the webhook notification should be sent, or the products should be synchronised.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [X] Technical changes only

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/services/order_cycles/clone_service.rb [hunk 1]
```diff
@@ -9,7 +9,7 @@ def initialize(order_cycle)
     def create
       oc = @original_order_cycle.dup
       oc.name = I18n.t("models.order_cycle.cloned_order_cycle_name", order_cycle: oc.name)
-      oc.orders_open_at = oc.orders_close_at = oc.mails_sent = oc.processed_at = nil
+      oc.orders_open_at = oc.orders_close_at = oc.mails_sent = oc.processed_at = oc.opened_at = nil
```
Comment (rioug) [inline app/services/order_cycles/clone_service.rb:12]: Could you update the related spec ?

File: spec/jobs/open_order_cycle_job_spec.rb [hunk 2]
```diff
@@ -75,6 +75,30 @@
...
+    it "marks as open" do
+      expect {
+        subject
+        cloned_order_cycle.reload
+      }
+        .to change { cloned_order_cycle.opened_at }
+
+      expect(cloned_order_cycle.opened_at).to be_within(1).of(now)
+    end
+  end
```
Comment (rioug) [inline spec/jobs/open_order_cycle_job_spec.rb:107]: I think we should also check that `OrderCycles::WebhookService` is actually called , see the "enqueues webhook job" example at line 24 for inspiration.

**Review by rioug — CHANGES_REQUESTED** [review]
Thanks for your help @rahsheen :pray: 
It's a good start, but I think we can improve the testing, see my comments.

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @rahsheen ,

I verified the issue: indeed I could not sync DFC variants with a cloned order cycle. I've looked at stock changes.

After staging this PR, and having placed a few orders the stock dropped down to:

image

After setting the cloned OC to a future time, it was possible to observe the stock indeed was reset to the original values:

image

Awesome, thanks for fixing this! :tada: 
Merging.

**Comment by rahsheen** [comment]
> Hey @rahsheen ,
> 
> I verified the issue: indeed I could not sync DFC variants with a cloned order cycle. I've looked at stock changes.
> 
> After staging this PR, and having placed a few orders the stock dropped down to:
> 
> image
> 
> After setting the cloned OC to a future time, it was possible to observe the stock indeed was reset to the original values:
> 
> image
> 
> Awesome, thanks for fixing this! :tada: 
> Merging. 

My pleasure! I'm happy to make myself useful. Thank you!
