### PR TITLE
Fix Order Cycle search on BOM page is not working for more than 5 OCs

### LINKED ISSUE #13180: Order Cycle search on BOM page is not working for more than 5 OCs
## Description
On the BOM page,  it is often necessary to limit the search to a particular order cycle.  The drop down list of OCs on the BOM page is limited to 5 OCs.  If you select 'all' and search by order cycle name,   no orders in that OC are found.  So users with more than 5 OCs cannot find orders using BOM easily.

Further -  if you just search by date range to find orders -  the orders from all order cycles are found,   but there is a blank in the 'order cycle' field in the returned data,  so the user cannot identify which OC the order is from.

## Expected Behavior
User should be able to enter an order cycle name and find orders in this OC on the BOM page.

## Actual Behaviour
It is only possible to search for 5 order cycles.  The orders can be found - just by using a date range search.  But then the OC name is not appearing in the search results.   It is not possible to search and find all the orders in a given OC,  if the user has more than 5 active OCs.  

Users can easily have more than 5 OCs with active orders,   especially if the set up an OC per pickup location,   or use OC tagging for different customer groups....

## Steps to Reproduce
Create more than 5 order cycles,  with orders
Go to BOM and see that only 5 OCs show in the drop down
Search for your 6th OC name -  and see the search does not return results
Search for 'all' OCs (or search by date range)  and see that all the orders are listed,  
See that the order from the 6th order cycle has a blank where the OC name should be in the search results.
1.
2.
3.
4.

## Animated Gif/Screenshot
Here are my hub's order cycles for the past 90 days:

Image

Here is the BOM page  - showing only 5 of these OCs in the drop down

Image

If I search using a date range,  I capture the orders from the non-listed order cycles.  But note that the oc name is missing (for those order cycles not in the drop down search list)

Image

## Workaround
Searching by date range returns the orders -  but then the user needs to go to the order to see which OC it is from.    

## Severity
S3

bug-s1: a critical feature is broken: checkout, payments, signup, login
bug-s2: a non-critical feature is broken, no workaround
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix
There may not be 'room'  to add all the OCs in the dropdown,   but can it be possible to search by OC name?

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #13180
- Previously, we were displaying only those orders which are closed within 90 days.
- Due to this, OCs that have an active order but have been closed 90 or more days ago to be missing in the filter dropdown.
- This PR made respective changes to display all the available order cycles regardless of the closed date in the dropdown.

#### What should we test?

- As mentioned in the issue

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

**Review by rioug — CHANGES_REQUESTED** [review]
Thanks @chahmedejaz 

Your solution work if you have a limited amounts of order cycle, But now we are loading all the existing order cycles for the logged in user, so potentially quite a lot.
I think a better solution would be to investigate if select2 could do a search with an ajax request. That way we could present a limited amount of Order cycle when the user opens the dropdown, and then if they want to search for something specific, we fire an Ajax request. This way we don't have to load a potentially big amount of data.
Could you have a look at this ? 

FYI the dropdown is set up via this AngularJs directive : https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/utils/directives/ofn-select2.js.coffee
It's also worth checking if we don't already have a directive that does what I described above.

**Comment by chahmedejaz** [comment]
Sure, @rioug, that's a valid concern. I'll look into it. Thanks.

**Comment by chahmedejaz** [comment]
> I think a better solution would be to investigate if select2 could do a search with an ajax request. That way we could present a limited amount of Order cycle when the user opens the dropdown, and then if they want to search for something specific, we fire an Ajax request. This way we don't have to load a potentially big amount of data.
Could you have a look at this ?

Hi @rioug - I did a spike on this, as per the current architecture of the BOM page, it displays the order cycle for the line item by mapping the order_cycles from the dropdown.

For example:
If the dropdown initially contains some OCs (not all):
- OC_A
- OC_B

However, the BOM page shows a line_item which belongs to OC_C, then their order cycle will be blank on the UI as OC_C was not present in the dropdown. That's the root cause of the problem described in the issue:
Image

To implement the suggested solution, this whole thing needs to be refactored in a tech debt :sweat_smile:.

So, for now, I've added the same scope we use in the [reports to display OCs in the Order Cycle Filters dropdown](https://github.com/openfoodfoundation/openfoodnetwork/blob/ef6e37e7cabda8400d6d8427ce1d3f72942f2f90/lib/reporting/frontend_data.rb#L41-L46) here to narrow down the results: https://github.com/openfoodfoundation/openfoodnetwork/pull/13263/commits/6bcaec14c5c86b53f48a5223fef3fccdf3979858

This was also discussed in the comments here: https://github.com/openfoodfoundation/openfoodnetwork/issues/13180#issuecomment-2734988464

Please let me know what you think about it. Thanks

**Review by rioug — APPROVED** [review]
Thanks for looking into it @chahmedejaz.
I am still a bit nervous even with the `active_or_complete` filter. It might be OK for most user but it might blow up for a super admin. I'd rather increase the time limit to maybe 1 to 2 years. But let's see what other reviewers think.

**Comment by dacook** [comment]
I just deployed this on au_staging to have a look and found:
* Number of OCs loaded went form 49 to over 500
* Load time increased from about 1s (wow that's fast) to 3s (still very reasonable)
* The dropdown still seems to perform perfectly fine

Screenshot 2025-05-05 at 10 37 24 am
Screenshot 2025-05-05 at 10 37 33 am

Still, I share Gaetan's concern of loading too much. In other instances this could be more of a problem. 1 year seems like a reasonable filter to me. The down sides I can think of would be:
1. If you're looking for an order cycle more than a year ago, you won't find it, and there's no hints or explanation why.
2. If you're looking at old orders and enable the Order Cycle column, it will be blank. 

I think with a limit of 1 or more years, those wouldn't be big problems. So @chahmedejaz would you mind adding a time filter?

**Review by dacook — CHANGES_REQUESTED** [review]
(requesting change as per above comment)

**Comment by chahmedejaz** [comment]
Sure, @dacook and @rioug . 1 year filter sounds reasonable to me. However, let's confirm the duration from the product.

ping @RachL .

**Comment by RachL** [comment]
@chahmedejaz yes let's start with this and see if we have user feedback, but it sounds reasonable to me!

**Comment by chahmedejaz** [comment]
Hi @dacook - I've addressed your comment here: https://github.com/openfoodfoundation/openfoodnetwork/commit/db0922a7cf95536915a474b2803c8bf6af6a4add

**Review by rioug — APPROVED** [review]
Looks good :+1:

File: spec/system/admin/bulk_order_management_spec.rb [hunk 1]
```diff
@@ -701,6 +709,11 @@
                                           completed_at: 2.weeks.from_now,
                                           order_cycle: oc3 )
         }
+        let!(:o5) {
+          create(:order_with_distributor, state: 'complete', shipment_state: 'ready',
+                                          completed_at: 100.days.ago,
+                                          order_cycle: oc4 )
+        }
```
Comment (dacook) [inline spec/system/admin/bulk_order_management_spec.rb:716]: Can we have an expectation for this new record?

**Review by dacook — CHANGES_REQUESTED** [review]
Thanks, but I think we need to update the test

File: spec/system/admin/bulk_order_management_spec.rb (hunk 1 above)
Comment (dacook) [reply spec/system/admin/bulk_order_management_spec.rb:716]: I checked out the code and I think that it's worth checking for the line items too. 
I couldn't help but try to add it, and sorry then I did some refactoring along the way.... (that was kinda fun 😄 )

**Review by rioug — APPROVED** [review]

**Review by dacook — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz ,
I've verified the bug before staging this PR.
After staging it, I've found it to address two issues, on the bulk order management page:
1) it displays all available order cycles on the dropdown menu
2) it displays the order cycle name, on each order entry, for order cycles older than 90 days but newer than one year

image

We can see in the DB that there are other order cycles available, but that these are not displayed as they are older than one year (`created_at`):

```
 3774 | pin_pay                | 2020-06-30 14:00:00        | 2020-09-29 14:00:00        |           2483 | 2020-07-15 07:31:29.587769 | 2020-09-08 09:51:38.768214 |                            | f                       | f          | 
 3765 | OCApril                | 2020-03-31 13:00:00        | 2020-04-29 14:00:00        |           2483 | 2020-04-17 10:59:29.426951 | 2020-04-26 09:33:06.585683 |                            | f                       | f          | 
 3778 | OC1                    | 2020-11-16 13:00:00        | 2020-12-30 13:00:00        |           2483 | 2020-11-25 10:19:54.422372 | 2020-12-03 19:56:17.038957 |                            | f                       | f          | 
 3787 | tax_free_OC            | 2021-04-01 01:00:00        | 2021-04-30 02:00:00        |           2483 | 2021-04-15 10:27:22.549899 | 2021-04-15 10:27:22.549899 |                            | f                       | f          | 
 3780 | oc_sca_test            | 2021-02-01 01:00:00        | 2021-05-01 02:00:00        |           2483 | 2021-02-22 10:34:55.335896 | 2021-05-19 13:30:45.081881 |                            | f                       | f          | 
 3785 | supplier_OC            | 2021-04-01 01:00:00        | 2021-06-08 02:00:00        |           2483 | 2021-04-12 09:08:03.59919  | 2021-06-10 15:08:23.166836 |                            | f                       | f          | 
 3782 | oc_sca_test_2          | 2021-06-09 02:00:00        | 2021-06-09 05:35:00        |           2483 | 2021-03-10 21:28:34.490886 | 2021-06-11 09:05:22.997258 |                            | f                       | f          | 
 3793 | testing flatpicker     | 2021-06-09 02:04:00        | 2021-08-31 10:37:00        |           2483 | 2021-06-08 15:03:39.747863 | 2021-07-09 09:21:58.554599 |                            | f                       | f          | 
 3795 | OC_sanity_AWS          | 2021-12-01 01:00:00        | 2021-12-31 01:00:00        |           2483 | 2021-10-26 11:08:49.891438 | 2021-12-31 01:00:04.978888 | 2021-12-31 01:00:04.978868 | f                       | f          | 
 3796 | webpacker              | 2022-01-01 01:00:00        | 2022-08-17 02:00:00        |           2483 | 2022-01-03 11:04:00.481752 | 2022-08-19 10:14:36.246055 |                            | f                       | f          | 
 3805 | tax                    | 2022-07-28 02:00:00        | 2022-11-30 01:00:00        |           2483 | 2022-07-29 10:01:09.557842 | 2022-11-30 01:02:50.935009 | 2022-11-30 01:02:50.934999 | f                       | f          | 
 3811 | OC_2023                | 2023-01-01 01:00:00        | 2023-04-30 02:00:00        |           2483 | 2023-01-03 17:28:27.195968 | 2023-04-30 02:02:53.63738  | 2023-04-30 02:02:53.637368 | f                       | f          | 
 3825 | tax_report             | 2023-08-24 09:08:45.923979 | 2023-08-24 09:38:45.924066 |           2483 | 2023-05-29 16:30:27.632961 | 2023-08-24 09:42:59.999774 | 2023-08-24 09:42:59.999765 | f                       | f          | 2023-08-24 09:28:00.257537
 3837 | another_oc             | 2023-08-26 02:00:00        | 2023-08-31 02:00:00        |           2483 | 2023-08-24 08:09:56.309893 | 2023-08-31 02:02:48.718717 | 2023-08-31 02:02:48.718706 | f                       |            | 2023-08-26 02:02:48.914537
 3876 | oc_1                   | 2024-12-01 01:00:00        | 2024-12-31 01:00:00        |           2483 | 2024-12-15 15:32:47.341922 | 2024-12-31 01:00:25.489789 | 2024-12-31 01:00:25.48978  | f                       | t          | 
 3882 | pay_suppliers_test_    | 2025-01-01 01:00:00        | 2025-02-09 01:00:00        |           2483 | 2025-02-07 15:11:41.207819 | 2025-02-11 02:51:06.997522 |                            | f                       |            | 
 3840 | product import         | 2025-01-01 01:00:00        | 2025-01-31 01:00:00        |           2483 | 2023-09-20 19:35:37.385852 | 2025-01-31 01:00:26.080143 | 2025-01-31 01:00:26.080134 | f                       | f          | 
 3881 | pay_suppliers_test     | 2025-01-01 01:00:00        | 2025-02-02 01:00:00        |           2483 | 2025-02-07 00:58:43.48347  | 2025-02-11 02:50:24.609567 |                            | f                       |            | 
 3884 | pay_suppliers_test_OUT | 2025-03-25 16:04:26.665517 | 2025-03-25 16:19:26.665592 |           2483 | 2025-02-11 02:51:25.902883 | 2025-03-25 16:34:27.532363 | 2025-03-25 16:36:30.780862 | f                       | f          | 2025-03-25 16:36:30.80561
 3883 | pay_suppliers_test_INC | 2025-05-08 11:57:00        | 2025-07-31 11:58:00        |           2483 | 2025-02-11 02:50:27.276742 | 2025-05-08 20:12:47.854179 |                            | t                       | f          | 2025-05-08 11:58:03.570701


```

I've noticed a small increase in the load time as superadmin, from 1s to 3sec, but I think this is perfectly acceptable.

Looks great!
Merging.
