### PR TITLE
Tax display

### LINKED ISSUE #5986: Wrong tax amount per rate on invoices
## Description

Invoices present currently a line with total tax amount, however this line does not show a correct number. Amount excluding tax and including tax are correct however.

## Steps to Reproduce

1. Go check an order, example in FR prod R028838087
2. Print the invoice and check the total tax amount here it is :

3. Go see `/admin/reports/sales_tax` for that particular order
4. See that the invoice is showing only the amount at 20% VAT and not the total amount like it says it is.

Another super weird example is order R214658240

But total tax should be 7.73

## Workaround
None I'm afraid. But I wonder if the fix might not solve my breakdown need explained here: https://github.com/openfoodfoundation/openfoodnetwork/issues/5881

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: 3.2.5
* Browser name and version: All
* Operating System and version (desktop or mobile): Both

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #5986

The `OrderTaxAdjustmentsFetcher` service was not correctly summing tax on all line items in the order, but only returning the tax on one line item.

#### What should we test?

With multiple line items in an order that have different tax rates; displayed tax totals in invoice template and sales tax report should be correct for the order (screenshots in issue).

#### Release notes

Fixed display of tax totals in invoices and tax reports.

### CODE REVIEW

**Review by luisramos0 — APPROVED** [review]

File: app/services/order_tax_adjustments_fetcher.rb [hunk 1]
```diff
@@ -32,7 +32,7 @@ def order_adjustments
   end
 
   def line_item_adjustments
-    table[:adjustable_id].eq(order.line_item_ids.join(','))
+    table[:adjustable_id].eq_any(order.line_item_ids)
```
Comment (sauloperez) [inline app/services/order_tax_adjustments_fetcher.rb:35]: FYI I found out in https://rollout.io/blog/creating-advanced-active-record-db-queries-arel/ that `eq_any` changed in Rails 4.2. Apparently it didn't accept an empty collection anymore. However, in this case, there should always be at least a line item.

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

I created several products with three different tax-rates:
- Full (20%)
- Reduced (10%)
- No tax

Placed orders with several items each, before and after the PR.

Before the PR we can see the bug, as Rachel reported on the issue - only the 20% tax is being considered, and for only one line item:

- Invoice (alternative model):
image

Tax report (tax rates):
image



After staging this PR and placing an identical order (R782683134), we can see that both 10% and 20% are being considered. Below a comparison, before (left side) and after the PR (right side):
image

Also, it can be seen on the reports, that the previous order (R588022720) has been corrected - this is great news :tada: 

image

So, all is good with the PR - ready to go!

One question about the tax values, though - pinging  @RachL as well on this one:

- for the 20% taxed items: (12 + 9) x 0,2 = 4,2 -> and not 3,50 as shown in the invoice/report
- for the 10% taxed items: (15 + 15) x 0,1 = 3 -> and not 2,72 as shown in the invoice/report

Based on this reasoning, I'd expect the total included to tax to be 7,2 and not 6,22. The enterprise does have enterprise fees set, but not for this OC:

image

Am I missing something in the calculations ?

**Comment by RachL** [comment]
@filipefurtad0 prices are introduced as prices _**including**_ taxes. This makes my brains twist as well :D

So if you have a price with tax at (12+9) = 21, the tax value at 20% is 21*20/120 = 3.5.

For the items at 10%: (15+15) = 30, the tax value at 10% is 30*10/110 =2.72

All good 🎉

**Comment by filipefurtad0** [comment]
Ahh sure, should've seen that one :-D 
Thanks Rachel :+1:

**Comment by luisramos0** [comment]
It's useful arithmeticians for that "included in price".
PRICE_EXCLUDING_TAX = PRICE_INCLUDING_TAX * TAX / ( 100 + TAX)

**Comment by Matt-Yorkley** [comment]
Yay! :smile: 

This was a very tiny PR but it took a while to figure out what the hell was going on and how to fix it.

**Comment by RachL** [comment]
Tiny PR but HUGE impact!

**Comment by luisramos0** [comment]
:clap: :clap: :clap:

**Comment by filipefurtad0** [comment]
Couldn't help but thinking about [this](https://www.youtube.com/watch?v=aEZGW5Tlfm0) for the rest of the day :smile:
