### PR TITLE
[BUU] Fix non-admin saving

### LINKED ISSUE #12403: [BUU] Can't save changes on staging-AU
## Description

Since recently I can't save changes on the /admin/products page with admin_v3 toggle enabled. I get redirected to /unauthorized. Here is the error message from the browser console:

```
GET
https://staging.openfoodnetwork.org.au/unauthorized
[HTTP/2 401  196ms]

	
GET
	
scheme
	https
host
	staging.openfoodnetwork.org.au
filename
	/unauthorized
Address
	65.99.217.140:443
Status
	401
Version
	HTTP/2
Transferred
	18.71 kB (17.08 kB size)
Referrer Policy
	strict-origin-when-cross-origin
Request Priority
	Highest
DNS Resolution
	System

    	
    cache-control
    	no-store
    content-security-policy
    	default-src 'self' https:; font-src 'self' https: data: fonts.gstatic.com; img-src 'self' https: data: *.s3.amazonaws.com; object-src 'none'; frame-ancestors 'none'; script-src 'self' https: 'unsafe-inline' 'unsafe-eval' *.stripe.com openfoodnetwork.innocraft.cloud maps.googleapis.com maps.gstatic.com d2wy8f7a9ursnm.cloudfront.net; style-src 'self' https: 'unsafe-inline' fonts.googleapis.com cdnjs.cloudflare.com; connect-src 'self' https: https://staging.openfoodnetwork.org.au wss://staging.openfoodnetwork.org.au
    content-type
    	text/html; charset=utf-8
    date
    	Fri, 19 Apr 2024 12:25:21 GMT
    expires
    	Fri, 01 Jan 1990 00:00:00 GMT
    link
    	</packs/css/darkswarm-9775c18d.css>; rel=preload; as=style; nopush,</packs/js/application-c989ee9fb1b3acd181cd.js>; rel=preload; as=script; nopush,</assets/darkswarm/all-53e644a1fb5beee24c7d006b08b70d84afa4619ec5d6b05bd2adb983bb019afa.js>; rel=preload; as=script; nopush,</assets/web/all-1da1cc6fe6a50c600a4552a2cc1a45297623e3d517b0e95219ed51cd7f798342.js>; rel=preload; as=script; nopush
    pragma
    	no-cache
    referrer-policy
    	strict-origin-when-cross-origin
    server
    	nginx
    set-cookie
    	XSRF-TOKEN=vgKo2i_98Mic1crBmVtqx7aa99oUqJ6rvHdwlSVNYxy9A_F1-OcfHiD7ibkWEcg6mmWXHlvi7jwrDHi8KBlZ_g; path=/; SameSite=Lax; secure
    strict-transport-security
    	max-age=63072000; includeSubDomains
    x-content-type-options
    	nosniff
    x-content-type-options
    	nosniff
    x-download-options
    	noopen
    X-Firefox-Spdy
    	h2
    x-permitted-cross-domain-policies
    	none
    x-request-id
    	1919917d-eac1-45df-828c-176b95eea085
    x-runtime
    	0.053590
    x-xss-protection
    	1; mode=block
    x-xss-protection
    	1; mode=block
    	
    Accept
    	text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-GB,en;q=0.5
    Connection
    	keep-alive
    Cookie
    	_pk_id.3.32b3=3a6411dd196058de.1712920606.; __stripe_mid=e0acd1c5-aef0-4723-9363-d3a3c531883abc99f5; cookies_consent=cookies_consent; XSRF-TOKEN=j7XVOvq5-gr3oPuQlGEY_q1vv21F5m11iB8vw3ipQP-MtIyVLaMV3EuOuOgbK7oDgZDfqQqsHeIfZCfqdf16HQ; _ofn_session_id=bac583c1a8000f393f0caef219f197c4; _pk_ses.3.32b3=1; __stripe_sid=77833aa9-3752-4989-8303-273b4634a6822a82a7
    Host
    	staging.openfoodnetwork.org.au
    Referer
    	https://staging.openfoodnetwork.org.au/admin/products?_page=1&_per_page=15
    Sec-Fetch-Dest
    	document
    Sec-Fetch-Mode
    	navigate
    Sec-Fetch-Site
    	same-origin
    Sec-Fetch-User
    	?1
    TE
    	trailers
    Upgrade-Insecure-Requests
    	1
    User-Agent
    	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0
```

## Expected Behavior

Changes should be saved.

## Actual Behaviour

Changes are not changed and I get redirected to /unauthorized.

## Steps to Reproduce

1. Activate the Admin_v3 toggle.
2. Go to /admin/products page.
3. Make some changes.
4. Click 'Save changes'.

## Animated Gif/Screenshot

image

## Workaround

Make changes on the product details page.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: current master
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by dacook**
Project code: #7198 Back Office Uplift (Product): Build

#### What? Why?

- Closes #12403

The `Spree::Admin::BaseController` requires a permission defined for each controller action, so I've now added this.
It wasn't covered by the system spec because it only tested as an admin (which automatically has access to everything). I've updated the spec to always use an enterprise user, which is a better test.

But the error message was pretty disruptive and unhelpful (see issue). So in case it happens again, I've added a general error handler to show a  message, based on the HTTP code (401 - Unauthorized). 
Screenshot 2024-04-23 at 12 58 16 pm

#### What should we test?
Just a quick validation ideally by Konrad:
* Log in as an enterprise user that doesn't have the 'admin' role. Save a product change on the new products screen.

This also touches the general Turbo code which I think is used in the checkout process. But I believe this change is sufficiently covered by specs.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/products_v3/products_spec.rb [hunk 1]
```diff
@@ -173,7 +178,7 @@
         search_by_category "Category 1"
 
         # expect(page).to have_content "1 product found for your search criteria."
-        expect(page).to have_select "category_id", selected: "Category 1"
+        expect(page).to have_select "category_id", selected: "Category 1" # succeeds in CI but not dev.
```
Comment (dacook) [inline spec/system/admin/products_v3/products_spec.rb:181]: Hmm I forgot to go back and investigate why, but maybe next time..

File: spec/system/admin/products_v3/products_spec.rb [hunk 2]
```diff
@@ -2,13 +2,16 @@
 
 require "system_helper"
 
-describe 'As an admin, I can manage products', feature: :admin_style_v3 do
+describe 'As an enterprise user, I can manage my products', feature: :admin_style_v3 do
   include WebHelper
   include AuthenticationHelper
   include FileHelper
 
+  let(:producer) { create(:supplier_enterprise) }
```
Comment (dacook) [inline spec/system/admin/products_v3/products_spec.rb:10]: In many places the codebase says "supplier". We now prefer the term "producer", which is used in general communication, so I've named the variables as such. 
Maybe one day we'll update the codebase to avoid confusion..

File: app/webpacker/js/turbo.js [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+  event.preventDefault();
+
+  // show error message instead
+  status = event.detail.response.status;
+  if(status == 401) {
+    alert(I18n.t("errors.unauthorized.message"));
+  } else {
+    alert(I18n.t("errors.general_error.message"));
+  }
+});
```
Comment (dacook) [inline app/webpacker/js/turbo.js:14]: Hmm, in Rails we arrange code like this in a folder called `initializers`. Maybe we could do the same with JS next time.

**Comment by dacook** [comment]
todo: rerun failed flaky specs

File: spec/system/admin/products_v3/products_spec.rb (hunk 2 above)
Comment (mkllnk) [reply spec/system/admin/products_v3/products_spec.rb:10]: Oh, I didn't actually know this. "Supplier" is a bit more general. The enterprise may not be producing the product. :shrug:

**Review by mkllnk — APPROVED** [review]
Great fix, and testing.

File: spec/system/admin/products_v3/products_spec.rb (hunk 2 above)
Comment (dacook) [reply spec/system/admin/products_v3/products_spec.rb:10]: I recall having a conversation in Slack I think, and that "producer" was the winner.
I agree that "supplier" makes more sense, although arguably the distributor also "supplies" the product, so it could be ambiguous...

I can't find that conversation though, so now I'm not sure! I will seek clarification in #product-circle.

Comment (sigmundpetersen) [reply spec/system/admin/products_v3/products_spec.rb:10]: I think this is the conversation https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1679368367236359
Seems we ended up with "supplier" back then 🙂

**Comment by RachL** [comment]
FYI I did test with a non admin role on staging FR and fields like updating images or stock are working ok. Now I see however that updating product unit name for example raises the error "Content is missing". Sorry for that! I've used an admin role for testing those as it required to have several pages of product :(

**Comment by filipefurtad0** [comment]
> I've updated the spec to always use an enterprise user, which is a better test

Fully agree, thanks @dacook . Unfortunately, this is a common practice in our tests, we should consider improving this and making sessions more user specific (instead of always being logged as superadmin).

**Comment by filipefurtad0** [comment]
Hey @dacook ,

I've staged master and found that indeed, for some attributes (like SKU or as @RachL menitons, product unit name) we get a 401 error, as described in the issue, while the UI throws this error - this reproduces the issue:

image

After staging the PR, I could not observer the error anymore, nor the 401 error on the console:

image

I've tested updating all fields, including images.

Also, since you mention this touches checkout, I felt it was a good idea to have a smoke test on checking out: looking good!

As I understood from @RachL comment, this was before staging the PR, right? If so, then I think we're good to merge, but I'll await your confirmation.

**Comment by RachL** [comment]
yes before staging the PR - I was referring to the PR that introduced this.

**Comment by filipefurtad0** [comment]
Ok! Merging :-)

File: spec/system/admin/products_v3/products_spec.rb (hunk 2 above)
Comment (dacook) [reply spec/system/admin/products_v3/products_spec.rb:10]: Thanks Sigmund, I forgot my own comments! 😅

I'm going to write it on a post-it note on my computer screen..
