### PR TITLE
Disabled_at logic: redirect to login path if user is disabled

### LINKED ISSUE #9336: Error 500 (snail/slug) when deactivated user tries to access his/her account
## Description

In #9154 the functionality of deactivating/disabling users was introduced. However if a user is still logged in while he/she is being deactivated and then tries to access his/her account there is an error 500.

## Expected Behavior

If the deactivated user tries to access the account, he/she should be redirected to the main page with the flash error shown here:
grafik

## Actual Behaviour

There is a snail.

## Steps to Reproduce

1. As a customer log in.
2. As a super admin deactivate that user (in a separate session e.g. private mode of the browser).
3. As a customer try to access your account (/account page).
4. See the snail.

## Animated Gif/Screenshot

Peek 2022-06-21 18-22

## Workaround

No workaround.

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used: staged [606a56a64de9fd3f6145e45a3d1865e817fcb4de](https://github.com/openfoodfoundation/openfoodnetwork/pull/9154/commits/606a56a64de9fd3f6145e45a3d1865e817fcb4de)
* Browser name and version: 101.0.1 (64-Bit)
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9336

#### What should we test?
 - As a customer, log in.
 - As a super admin, deactivate that user (in a separate session e.g. private mode of the browser).
 - As a customer, try to access your account (/account page).
 - See that you're redirected to `/#/login`

#### Release notes

Changelog Category: User facing changes 

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/consumer/account_spec.rb [hunk 1]
```diff
@@ -111,5 +111,16 @@
         expect(page).to have_content I18n.t(:you_have_no_orders_yet)
       end
     end
+
+    context "as a disabled user" do
+      before do
+        user.disabled = '1'
```
Comment (mkllnk) [inline spec/system/consumer/account_spec.rb:117]: Wow, I just learned that we don't have to persist the user. `Warden::Test::Helpers#login_as` sets the user object in memory and unless we are doing other queries that need the database, we can use an in-memory user for authentication in specs!

That line here doesn't save to the database but we don't need to in this spec.

**Review by mkllnk — APPROVED** [review]
This is looking good. I don't know if the other PR is solving the same thing? I'll leave that up to you.

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Before staging the current behavior I could observe is as follows:

[Screencast from 17-08-2022 20:13:28.webm](https://user-images.githubusercontent.com/49817236/185223774-0bbc4680-301c-472a-8152-7fb85edae8bc.webm)

So, no snail, just a redirection to the homepage with the flash warning.

After staging this PR, the login appears:

[Screencast from 17-08-2022 20:24:21.webm](https://user-images.githubusercontent.com/49817236/185225739-24060b6d-6036-446d-b7ab-af8eded1e65e.webm)

It kind of overlaps the with the flash warning, but I think this is ok. The user can either close the window and still see the flash warning; also, if a new login attempt is made with the same (disabled) credentials then the modal is clearly displayed.

Good to go :+1:
