### PR TITLE
Fix inline error style in Add Manager dialog

### LINKED ISSUE #13993: Admin enterprise users - show inline error style consistent with product list
## Description
Currently the style for the inline error shown in the Add manager dialog is inconsistent with the latest one we have introduced in the product list.

## Expected Behavior
Should look like product list, color, size and icon

Image

## Actual Behaviour
has different style

Image
Image

## Steps to Reproduce

1. Go to /admin/enterprises/ and select one
2. Go to users
3. Add an existing user or add an invalid email address

## Severity
bug-s5: we can live with it, only a few users impacted

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

Fixes #13993

The "Add Manager" dialog in enterprise users shows inline validation errors with a different style than the product list. The product list wraps fields in a `.field` class, which activates the `.formError` styles in `forms.scss` (icon, color, font-size). The user invitation modal was missing this class.

This adds the `.field` class to the email field row in the user invitation modal so the error styling matches the product list:
- Error text color uses `$color-error`
- Font size uses 85%
- Error icon (icon-remove-sign) is shown before the message
- Label turns red and input border turns red on validation error

## Test plan

- [ ] Go to `/admin/enterprises/` and select an enterprise
- [ ] Go to Users tab
- [ ] Click "Invite manager" and submit with an invalid email
- [ ] Verify error message style matches the product list inline error style (red color, smaller font, icon)
- [ ] Try adding an already-existing user and verify error style is consistent

Developed with AI assistance (Claude Code)

### CODE REVIEW

File: app/services/payments/webhook_payload.rb [hunk 1]
```diff
@@ -13,7 +13,7 @@ def to_hash
         payment: @payment.slice(:updated_at, :amount, :state),
         enterprise: @enterprise.slice(:abn, :acn, :name)
           .merge(address: @enterprise.address.slice(:address1, :address2, :city, :zipcode)),
-        order: @order.slice(:total, :currency).merge(line_items: line_items)
+        order: @order.slice(:number, :total, :currency).merge(line_items: line_items)
```
Comment (mkllnk) [inline app/services/payments/webhook_payload.rb]: This change seems unrelated to the mentioned issue in the pull request.

**Comment by mvanhorn** [comment]
Rebased to remove the unrelated webhook commit - the branch now contains only the inline error style fix. Sorry about the mix-up.

**Comment by AMEA-LYON** [comment]
Tested successfully 🚀 => Ready to Go !

**Comment by mvanhorn** [comment]
Thanks for the testing and review, @AMEA-LYON and @rioug! Will use the PR template next time.
