### PR TITLE
[vouchers] fix tax calculation when moving back in the checkout process

### LINKED ISSUE #11359: [Vouchers] Excl. tax is calculated incorrectly when moving back in checkout process
## Description

Follow up of #11117.
There are different tax calculations depending on the way the checkout process is finished. This requires a product with taxes excluded from price and a payment method with transaction fee.

EDIT: This also seems to happen for tax incl. in price.

- Finishing **all three checkout steps in a row** while adding a voucher in step 2:
  - **CORRECT:** Tax on voucher is calculated **_including_** the transaction fee.
image
- Leaving step 2 without adding the voucher and then **going back from step 3 to step 2** to add the voucher yields this:
  - **NOT CORRECT:** Tax on voucher is calculated **_excluding_** the transaction fee.
image

## Expected Behavior

Both ways should provide identical results.
Both ways should provide the result shown as 'correct' above.

## Actual Behaviour

Both ways provide different results.
The second way provides the result shown as 'not correct' above..

## Steps to Reproduce

1. As enterprise user set up a shop with a voucher, a product with tax excluded from price and a payment method with transaction fee.

Way one:
1. As customer put that product in your cart (make sure your order total is higher than the voucher amount) and proceed to checkout.
2. Finish step 1 of the checkout.
3. In step 2 add the voucher code and select the payment method with transaction fees.
4. Proceed to step 3 and check the order summary.

Way two:
1. As customer put that product in your cart (make sure your order total is higher than the voucher amount) and proceed to checkout.
2. Finish step 1 of the checkout.
3. In step 2 DO NOT add the voucher code but select the payment method with transaction fees.
4. Proceed to step 3.
5. Bo back to step 2.
6. Add the voucher code and select the payment method with transaction fees.
7. Proceed to step 3 and check the order summary.

## Animated Gif/Screenshot

See images above.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### LINKED ISSUE #11361: [Vouchers] Negative order total (credit owed) after changing to a shipping method without fee
## Description

Follow up of #11117.
When starting a checkout process with a voucher and with a shipping method with shipping fee and later switching to a shipping method without shipping fee the result can be a negative order total amount in the order confirmation and a credit owed in the back office.

## Expected Behavior

Changes in shipping fees must be reflected correctly and must not lead to a negative order total.

## Actual Behaviour

It is possible to have a negative order total.

## Steps to Reproduce

1. As enterprise user set up a shop with a voucher and two shipping methods (one with a shipping fee and one without).
2. As customer put items in your cart with an order total less than the voucher amount.
3. Proceed to checkout and select the shipping method with shipping fee in step 1. 
4. Continue to step 2 and finish it.
5. In step 3 select 'Edit' next to Delivery details.
6. Select the shipping method without shipping fee.
7. Continue to step 2 and select a payment method (if required).
8. Continue to step 3.
9. Look at the order summary with the negative order total.
10. Complete the order.
11. As enterprise user look at the order in the back office and see that there is a 'credit owed'.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/c5fc9ebc-f7f7-40ac-b2bc-5d20bd73c7ea

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #11359 
- Closes #11361

In certain scenario when a voucher is applied to an order, moving back to a previous checkout step from the confirmation one, the voucher tax calculation can be wrong. ~~This is due to the order state not being updated when moving back to a previous step. It's particularly important for the payment step, as vouchers are recalculated after the order transition from the payment step. This is to take into account any payment fees applied to the order.~~ 

This is due to the voucher adjustment not being recalculated when it needs to. This fix the issue as well as negative order total one by recalculating the voucher adjustment when : 
* moving away from the details step, to account for any potential change in shipping fees
* moving away from the payment step, to take into account payment fees

Additionally, the solution also updates the order state if needed, based on the step we are loading. This is not necessary to fix the issue, as now voucher recalculation isn't dependent on order state transition, but I think it makes sense to keep the order state in sync with the checkout step.

##### tax calculation 
* As enterprise user set up a shop with a voucher, a product with tax excluded from price and a payment method with transaction fee.

Correct calculation :
1. As customer put that product in your cart (make sure your order total is higher than the voucher amount) and proceed to checkout.
2. Finish step 1 of the checkout.
3. In step 2 add the voucher code and select the payment method with transaction fees.
4. Proceed to step 3 and check the order summary. 

Go through checkout an move back during the checkout process :
1. As customer put that product in your cart (make sure your order total is higher than the voucher amount) and proceed to checkout.
2. Finish step 1 of the checkout.
3. In step 2 DO NOT add the voucher code but select the payment method with transaction fees.
4. Proceed to step 3.
5. Go back to step 2.
6. Add the voucher code and select the payment method with transaction fees.
7. Proceed to step 3 and check the order summary.
=> this should be the same as the "correct calculation" scenario above

8. Repeat this scenario but go back to step 1 this time 
=> the order summary should be the same as the "correct calculation" scenario above

##### Negative order total 

1. As enterprise user set up a shop with a voucher and two shipping methods (one with a shipping fee and one without).
2. As customer put items in your cart with an order total less than the voucher amount.
3. Proceed to checkout and select the shipping method with shipping fee in step 1.
4. Continue to step 2 and finish it.
5. In step 3 select 'Edit' next to Delivery details.
6. Select the shipping method without shipping fee.
7. Continue to step 2 and select a payment method (if required).
8. Continue to step 3.
9. Look at the order summary with the negative order total.
10. Complete the order.
11. As enterprise user look at the order in the back office and see that there is a 'credit owed'.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by rioug** [comment]
I found a bug while looking at #11361, I'll move it back to dev

File: app/controllers/concerns/checkout_steps.rb [hunk 1]
```diff
@@ -39,9 +43,19 @@ def redirect_to_step
...
+
+  def update_order_state
+    if @order.state == "confirmation" && payment_step?
+      @order.back_to_payment
+    end
+
+    return unless @order.state.in?(["payment", "confirmation"]) && details_step?
+
+    @order.back_to_address
+  end
```
Comment (mkllnk) [inline app/controllers/concerns/checkout_steps.rb:60]: Looking good. A bit confusing though. I think that Rubocop's suggestion can make things worse.

The code path allows to first go back to payment and then also back to address. This path is impossible though because payment_step and details_step can't both be true. So we could return after back to payment which means that we don't have to think about the other conditions within the same request.

To make things worse, the edit action also redirects to the right step based on the order.

1. So first we check the order state and update the page (step).
2. And then depending on the page (step) we update the order state again. :confused:
3. And then we check the step again to redirect if we are not there. :upside_down_face: 

That looks like we could be doing at least one unnecessary redirect. So maybe instead of redirecting in `redirect_to_step_based_on_order` we should just find where we should go, update the order if necessary, and then redirect accordingly.

Actually, I now realise that I don't quite understand how it works. If the order state is confirmation and the step is payment then we trigger a redirect to summary before this method is called. There's no return though. So this code is then executed as well, setting the order back to payment. Now the order and the step are both in payment which means that the next check of the step doesn't detect any mismatch and doesn't redirect. So I guess that the redirect to summary is still executed. The summary page would then detect a mismatch and redirect back to payment. Okay, so this path works but we have a couple of useless redirects to where we were already. The controller spec doesn't assert on the response to the request. That would be better in a request spec.

**Review by mkllnk — APPROVED** [review]
I'm happy for this to go ahead to solve the problem but I really want the split checkout logic to be simplified as well. This could happen in a separate PR but then the testing has to happen twice. So since this is not released yet, I would vote to do it in the same PR.

File: app/controllers/concerns/checkout_steps.rb (hunk 1 above)
Comment (rioug) [reply app/controllers/concerns/checkout_steps.rb]: I cleaned up the code to make things clearer, see : https://github.com/openfoodfoundation/openfoodnetwork/pull/11677/commits/25af178011dbf084d0d264d583921d20e2a58655

> To make things worse, the edit action also redirects to the right step based on the order.
> 
>  1. So first we check the order state and update the page (step).
>  2. And then depending on the page (step) we update the order state again. 😕
>  3. And then we check the step again to redirect if we are not there. 🙃

Think you misread the code here, 1. and 3. are mutually exclusive. 1. happens if `params[:step]` isn't set and 3. happens if `params[:step]` is set.

File: app/controllers/split_checkout_controller.rb [hunk 2]
```diff
@@ -96,11 +100,23 @@ def update_order
...
+    recalculate_voucher if details_step? || payment_step?
     @order.update_totals_and_states
 
     validate_current_step
   end
 
+  def recalculate_voucher
+    return if @order.voucher_adjustments.empty?
+
+    return if @order.shipping_method&.id == params[:shipping_method_id].to_i
```
Comment (abdellani) [inline app/controllers/split_checkout_controller.rb:115]: I'm still not familiar with vouchers yet.
I have a few questions:

1. why don't we use the same guard closure with payment_method?
2. what will happen if the `VoucherAdjustmentsService` is called and the `shipping_method` isn't changed?

File: app/controllers/split_checkout_controller.rb [hunk 3]
```diff
@@ -114,4 +130,15 @@ def advance_order_state
   def order_params
     @order_params ||= Checkout::Params.new(@order, params, spree_current_user).call
   end
+
+  # Update order state based on the step we are loading to avoid discrepancy between step and order
+  # state. We need to do this when moving back to a previous checkout step, the update action takes
+  # care of moving the order state forward.
+  def update_order_state
```
Comment (abdellani) [inline app/controllers/split_checkout_controller.rb:137]: I'm wondering why we're not comparing the `summary_step?` vs `order's state` in this method. 

This is just a question, I didn't spot any issues.

File: app/controllers/split_checkout_controller.rb (hunk 2 above)
Comment (rioug) [reply app/controllers/split_checkout_controller.rb:115]: > * why don't we use the same guard closure with payment_method?

You are right we should, I'll have a look at that. As explained below, the guard check is there to avoid doing unnecessary processing.

> * what will happen if the `VoucherAdjustmentsService` is called and the `shipping_method` isn't changed?

It would just recalculated the voucher adjustment and end up with the same result, I added this mostly to avoid doing processing that is not necessary.

File: app/controllers/split_checkout_controller.rb (hunk 3 above)
Comment (rioug) [reply app/controllers/split_checkout_controller.rb:137]: You can't "go back" to the summary step, ie you can't go from details step to the summary one directly. You have to use the "Next" button, which will trigger an order update and move the order to the correct state.

**Review by mkllnk — APPROVED** [review]

File: app/controllers/split_checkout_controller.rb (hunk 2 above)
Comment (rioug) [reply app/controllers/split_checkout_controller.rb:115]: I looked at adding a guard clause for payment_method, but it adds a lots complexity with the current code, which could probably be alleviated by refactoring split checkout controller but I don't think it's worth the effort. In most cases we want to recalculate the voucher when leaving the payment step, but not when leaving the details step. So I think it's fine here to not have guard clause. 

I really want to refactor the split checkout so it's clearer what's happening on each step, but I don't want to invest the time now. There is further work to be done on vouchers so maybe an opportunity will arise.

**Comment by dacook** [comment]
@abdellani I see that you've reviewed this PR, so am wondering if you're happy to approve, or suggest another action?

**Comment by abdellani** [comment]
> @abdellani I see that you've reviewed this PR, so am wondering if you're happy to approve, or suggest another action?

@dacook  it looks good. I'm happy to approve :)

**Review by abdellani — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @rioug ,

There's a bit to unpack, so I'll split this into separate comments. Below the tests related to tax calculation, and whether it closes #11359.

As @drummer83 observed, the bug is observed in both included and added tax. So, on the pics below, we'll see pics from staging-UK (**added tax, left side**) and staging-FR (**included tax, right side**).

For each of them, two scenarios are need to be considered:
1) the "correct" tax calculation - in which the user proceeds straight to order confirmation
2) the "incorrect" tax calculation - in which the user moves back to the payment step to add the voucher, after visiting the summary step 

For a:
- tax rate of 13% (added)
- voucher of 10 $
- order total of 50 $
- Transaction fee of 5 $

**Before staging** this PR, we get:

Scenario 1)
image

Scenario 2)
image

We can see the tax calculation changes, in scenario 2) -> the transaction fee is not included in the tax calculation


**After staging** this PR, we now get:

Scenario 1)
image

Scenario 2)
image

So, now, there is agreement in the obtained values, in both scenarios, and these correspond to the correct values. Below, the calculations, according to [this implementation](https://github.com/openfoodfoundation/openfoodnetwork/issues/10432#issuecomment-1439402476):

**Added tax**
tax amount (items) =  50 + 50 * 13 / 100 = 6.5 $
tax amount (voucher) =  10 * 6.5 / (50 + 5 + 6.5) = 1.06 $ :heavy_check_mark: 
voucher amount (brutto) = 10 - 1.06 = 8.94 $ :heavy_check_mark: 

**Included tax**
tax amount (items) =  50 - (50 * (100 / (100 + 10))) = 4.55 €
tax amount (voucher) =  4.55 * (1 - 45 / (55 - 10)) = 0.83 €
total included tax = 4.55 - 0.83 = 3.72 € :heavy_check_mark: 

**Summary**

This confirms #11359 is closed by the PR :tada: 

1 down, 2 to go: more comments up next ;-)

**Comment by filipefurtad0** [comment]
Test results around the **Negative order total** scenario. As before, staging-UK left, staging-FR, right side of the pics.

Before staging the PR, we can reproduce the issue and verify the negative order total on the `Summary` page:

image

Unfortunately, after staging the PR, it is still possible to attain negative order totals... However, we cannot observe these at the `Summary` step anymore; this is because, after the customer changes the shipping method on the Details step (as per steps to reproduce) clicking the `Next` button, has the following effects:
- the customer is redirected to the homepage
- emails with order confirmations arrive, which means...
- ...the orders were completed without final confirmation on the Summary step

With pics:

We can see the shipping fees, on the Summary step:

image

Visiting the Details step, and making the proposed changes on the shipping method:

image

The user attempts to move to the Payment or Summary step, by clicking "Next", but instead is redirected to the homepage, and the order is completed (emails arrive, order confirmation can be visited in the respective `/account#` section):

image

Order confirmation pages, for the placed orders:

image

**Summary**

According to these tests, this the PR does not close #11361. But what is perhaps a bit more concerning is the automatic order placement, once the user tries to proceed from the details step to the following ones.

Although there is a clear improvement (#11359 is closed by this PR) I'm not sure we're good to ship this as is. There might be other scenarios leading to unintended order placements...

It's nice to have it all in one PR for the sakes of testing (thanks for that :heart: ), but in this case, I'm wondering if we could rather split it and merge the bit which deals with tax calculation...

What do you reckon @rioug ?

**Comment by rioug** [comment]
> According to these tests, this the PR does not close #11361. But what is perhaps a bit more concerning is the automatic order placement, once the user tries to proceed from the details step to the following ones.

I though I had fixed that, I 'll have another look

**Comment by rioug** [comment]
@filipefurtad0 turned out one of my test wasn't quite right so it was "hiding the bug" !
It should be good to go now.

**Review by mkllnk — APPROVED** [review]

**Review by abdellani — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Alright :tada: 
This looks good now.

Total price including shipping method fees:
image

After changing to a shipping method with no cost:
image

So, the order total is not negative anymore - it is re-calculated and displayed correctly - this closes https://github.com/openfoodfoundation/openfoodnetwork/issues/11361.

Still one thing left to test, which is the introduced order states change (separate/following comment):

> Additionally, the solution also updates the order state if needed, based on the step we are loading. This is not necessary to fix the issue, as now voucher recalculation isn't dependent on order state transition, but I think it makes sense to keep the order state in sync with the checkout step.

**Comment by filipefurtad0** [comment]
Ok, indeed the state of the order changes upon the URL changes; This is not the case before this PR :+1: 

The pic below tries to summarize this, and follows the state of the order in the console, for each server:
- pic up, master staged
- pic down, this PR

- In both cases the order state progresses to `confirmation`, but before this PR it can only be brought back to address after visiting the `/cart` page, and clicking any of the buttons.
- after this PR: clicking the Continue shop brings the user back to the `/shop` page; I did not observe this in master, but seems like a correct behavior to me.

image

I could not observe the scenario in which orders were placed "spontaneously". So I'd say this is all good to go.
Awesome, thanks for this :clap: :clap: :clap:
