### PR TITLE
Fix Variant Unit Scale field initialization in Edit Product form

### LINKED ISSUE #7180: Metric weight and several volume units not displayed on Variant Unit Scale
## Description

First reported here: https://github.com/openfoodfoundation/openfoodnetwork/issues/6304#issuecomment-744696263

The UI is not displaying the most of the selected options on Variant Unit Scale, under product edit page `/admin/products/<product_name>/edit`. For example, for weight  and volume products. It works for items, imperial units and mL.

## Expected Behavior

The selection on the dropdown should be displayed in the UI, for all units supported by the instance.

## Actual Behaviour

The selection is only appearing on the Variant Unit Scale dropdown for:
- oz
- lb
- mL

The dropdown selection appears blank for all other units.

## Steps to Reproduce

As super admin:
1. Make sure you have all unit types selected in `admin/general_settings/edit` -> Available Units

As admin:
2. Visit `/admin/products/<product_name>/edit`
3. Select an option on Variant Unit Scale on the dropdown, and click Update.
4. See the blank dropdown.
5. Repeat for other units.

## Workaround

One can check the variant unit scale for a given product on /products.

## Severity

This is more extensive than initially thought - at least s3?

## Your Environment

* Version used: v3.6.0
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

Added this spec as pass criteria #7183 (approval pending).

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
VariantUnitManager.variantUnitOptions() returns array formatted like this:
```
["Weight (g)", "weight_1"]
```
and `product.variant_unit_scale` is formatted like this `weight_1.0` there is no possible match for the `<select />` element
So, remove the trailing `.0` from `product.variant_unit_scale` to match the options

**NB** : not sure of this one, still in `Draft`

Closes #7180 

##### Before, as super admin:
Make sure you have all unit types selected in admin/general_settings/edit -> Available Units
##### Then, as admin:
 1. Visit /admin/products/<product_name>/edit
 2. Select an option on Variant Unit Scale on the dropdown, and click Update.
 3. See that the option is well initialized with your previous saved option
 4. Repeat for other units.

#### Release notes
Initialize Variant Unit Scale field in the Edit Product form with its value

Changelog Category: User facing changes

### CODE REVIEW

**Review by andrewpbrett — COMMENTED** [review]
I think it's okay as it is - did you consider converting it to a number instead of removing the `.0`? That might make the intention more clear.

**Review by mkllnk — APPROVED** [review]

**Comment by jibees** [comment]
> did you consider converting it to a number instead of removing the .0? That might make the intention more clear.

That might be a good idea, but actually, in the case of `oz`, the `variant_unit_scale` is equal to `28.35`. So I can't convert it to `28`. 
So, that's mean converting it to a number **only if** only if it ends with `.0` which is more or less what i've done. No? But if it's clearer to you, I can certainly do it!

File: spec/features/admin/products_spec.rb [hunk 1]
```diff
@@ -488,7 +488,7 @@
           expect(flash_message).to eq('Product "a product" has been successfully updated!')
           product.reload
           expect(product.variant_unit).to eq(var_unit)
-          # TODO -> expect(page).to have_select('product_variant_unit_with_scale', :selected => dropdown_option)
+          expect(page).to have_select('product_variant_unit_with_scale', :selected => dropdown_option)
```
Comment (sauloperez) [inline spec/features/admin/products_spec.rb:491]: I know we mix them but IMO we should favor the hash symbol syntax over =>. See https://stackoverflow.com/questions/8675206/is-there-any-difference-between-the-key-value-and-key-value-hash-no

Comment (jibees) [reply spec/features/admin/products_spec.rb:491]: I just uncomment the code written by @filipefurtad0 but yes, I guess I could change it.
You mean:
```ruby
expect(page).to have_select('product_variant_unit_with_scale', selected: dropdown_option)
```
right?

Comment (jibees) [reply spec/features/admin/products_spec.rb]: Actually, I had a notification from Rubocop (i guess) inside my favorite ide
Capture d’écran 2021-04-14 à 16 13 55
Anyway, this is now corrected.

**Comment by andrewpbrett** [comment]
> That might be a good idea, but actually, in the case of oz, the variant_unit_scale is equal to 28.35. So I can't convert it to 28.

I was suggesting converting it to a decimal, not an integer. But in any case, I think this is fine.

**Review by andrewpbrett — APPROVED** [review]

File: spec/features/admin/products_spec.rb (hunk 1 above)
Comment (mkllnk) [reply spec/features/admin/products_spec.rb]: Which IDE is that?

Comment (sauloperez) [reply spec/features/admin/products_spec.rb]: the "new" Ruby 1.9 hash syntax is exactly `key: value` rather than `key => value`.

Comment (jibees) [reply spec/features/admin/products_spec.rb]: > Which IDE is that?

Visual Studio Code.

**Comment by filipefurtad0** [comment]
Hey @jibees ,
Thanks for this fix. 

Repeated the spec test-cases here:

Peek 2021-04-15 17-16

Ready to go.
