### PR TITLE
Fix: show success toast when saving column preferences

### LINKED ISSUE #13966: [Admin - products] When saving columns default in product list, an error toast is shown instead of success message
Currently when selecting a new default set of columns and clicking save, I'm presented with an error-looking toast, evn though it seems like the change has been saved successfully.

Image

**Steps to reproduce**

Go to /products
Click on Columns
Select a different set of columns
Click Save as default

**Expected behaviour**

Should show a black toast saying "Changes saved" as per when updating the product list itself.

Image

### PR DESCRIPTION
**Pull request by gbathree**
## What's the problem this PR addresses?

Closes #13966

When saving column preferences ("Save as default" in the Columns dropdown on `/admin/products`), a red/error-styled toast was shown instead of the black success toast, even though the save succeeded.

## What is your solution?

The flash was rendered inside the `turbo_stream.replace` targeting `bulk_admin_column_preferences_form`, which placed it inside the dropdown element with inconsistent styling context.

The fix moves the flash to its own `turbo_stream.append "flashes"` targeting the top-level `#flashes` container — the same pattern used by `destroy_product_variant.turbo_stream.haml` and `clone.turbo_stream.haml`.

**Before:**
```haml
= turbo_stream.replace "bulk_admin_column_preferences_form" do
  = render partial: "admin/shared/flashes", locals: { flashes: flash } if defined? flash
  = render partial: 'form', locals: { action: }
```

**After:**
```haml
= turbo_stream.replace "bulk_admin_column_preferences_form" do
  = render partial: 'form', locals: { action: }
= turbo_stream.append "flashes" do
  = render partial: "admin/shared/flashes", locals: { flashes: flash }
```

## How to test

1. Go to `/admin/products`
2. Click **Columns**
3. Check or uncheck any column
4. Click **Save as default**
5. ✅ A black success toast "Column preferences saved" should appear at the top of the page

The existing system spec `spec/system/admin/products_v3/actions_spec.rb` has been tightened to assert the flash appears inside `#flashes` with `.flash.success` class (not just that the text is present).

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Nice! Thank you. 🌟 

It would be helpful if you used our pull request template next time. Your description is very good as well but doesn't include the manual testing steps needed to verify this fix. Well done on the automated test though. 💪

**Comment by AMEA-LYON** [comment]
Sorry, I didn't succeed in reproducing this bug when deploying master on staging UK : "Column preferences saved" displayed in black. (But version deployed is labelled "V5.4.7-modified", shouldn't it be 5.4.6xxx ? )

After deploying this PR, same correct behaviour

**Comment by mariocarabotta** [comment]
@AMEA-LYON for me this is happening in staging australia

**Comment by AMEA-LYON** [comment]
Ok, thanks for the tip, 
indeed, the staging-AU version deployed is 5.4.6-xxx, I will use it as soon as it is freed

**Comment by RachL** [comment]
@AMEA-LYON :scream: sorry it looks like i forgot to remove the label! Don't hesitate to ping me when it's the case! And if I don't answer you can simply stage something new and restage the previous PR when you are done :)

**Comment by AMEA-LYON** [comment]
Thx Rachel,

Tested on AU staging server, but the bug is still occuring... 😞

**Comment by gbathree** [comment]
Hi @AMEA-LYON — thanks for testing! Could you clarify what you observed? There are two possible scenarios:

1. **You tested on master (without this PR)** and the bug still occurs there — that's expected, since this PR hasn't been merged yet.
2. **You tested this PR branch specifically** on AU staging, and the bug still shows even with this PR's changes applied.

If it's scenario 2, could you share more detail on what you saw? The fix moves the flash from inside the `turbo_stream.replace` of the form element to a separate `turbo_stream.append` targeting the top-level `#flashes` container — so the success message should appear at the top of the page with black styling rather than inside the column dropdown.

In case it helps: the fix is in `app/views/admin/column_preferences/bulk_update.turbo_stream.haml`.

**Comment by mariocarabotta** [comment]
after deploying to stagin australia this is still happening. here's what I see @gbathree 

[02.04.2026 10_30.webm](https://github.com/user-attachments/assets/02d5f0b9-52e4-4a3a-801f-0b7cebade8d1)

**Comment by gbathree** [comment]
Thanks @mariocarabotta for the video — that made the root cause clear.

**What was happening**

The error "Column name is not included in the list" came from `ColumnPreference`'s `column_name` validation. The validator called `valid_columns_for(action_name)` which internally called `get_default_preferences(action_name, Spree::User.new)` — a **blank user** with no enterprises and no feature toggles.

The `tags` column in `products_v3_index_columns` is only included in the valid column list when the `:variant_tag` feature toggle is enabled for the user. A blank user never has that toggle, so `tags` was never considered valid, causing validation to fail whenever someone with the toggle tried to save their column preferences.

**Fix**

Pass the actual user from the preference record to the validator:

```ruby
# Before
validates :column_name, ..., inclusion: { in: proc { |p| valid_columns_for(p.action_name) } }
def self.valid_columns_for(action_name)
  get_default_preferences(action_name, Spree::User.new).keys.map(&:to_s)
end

# After
validates :column_name, ..., inclusion: { in: proc { |p| valid_columns_for(p.action_name, p.user) } }
def self.valid_columns_for(action_name, user = nil)
  get_default_preferences(action_name, user || Spree::User.new).keys.map(&:to_s)
end
```

Added two specs covering both the valid and invalid cases for feature-toggled columns.

File: spec/models/column_preference_spec.rb [hunk 1]
```diff
@@ -73,6 +73,34 @@
...
+  describe "validating column_name" do
+    context "when the column is only valid for users with a feature toggle" do
+      let(:user) { create(:user) }
+      let(:enterprise) { create(:distributor_enterprise, owner: user) }
+
+      it "is valid when the feature toggle is enabled for the user's enterprise" do
+        allow(OpenFoodNetwork::FeatureToggle).to receive(:enabled?).and_return(false)
+        allow(OpenFoodNetwork::FeatureToggle).to receive(:enabled?).with(:variant_tag,
+                                                                         enterprise).
+          and_return(true)
```
Comment (rioug) [inline spec/models/column_preference_spec.rb]: You can enable a feature toggle for a specific spec with a flag, instead of using mocking `OpenFoodNetwork::FeatureToggle`:
```suggestion
      it "is valid when the feature toggle is enabled for the user's enterprise", feature: :variant_tag do
```
Could you fix the spec ?

**Review by rioug — CHANGES_REQUESTED** [review]
There is a linter error, could you have a look ? and the spec can be improved, see my comment.
