### PR TITLE
Fix “Import multiple products” button route on empty products page

### LINKED ISSUE #13818: On empty product list, button to import multiple products triggers an error
## Description
After creating a new admin user account, when trying to import multiple products, the button throws an unclear error.

## Expected Behavior
I assume to go to the [Import page](https://staging.openfoodnetwork.org.au/admin/product_import), but maybe there are more clues in the code?

## Actual Behaviour
Shows an error with no explanation.

## Steps to Reproduce

1. Log into admin account with no products
2. Go to product list page
3. Click on Import multiple products

## Animated Gif/Screenshot

Image

## Workaround
Go to Import page from the menu

## Severity
bug-s4: it's annoying, but you can use it

* Version used:
Brave browser 1.83.118 (Official Build) (x86_64)
Chromium: 141.0.7390.108

### PR DESCRIPTION
**Pull request by piyyu**
#### What? Why?

- Closes #13818

The "Import multiple products" button was linking to a non-existent route
(`/admin/products/import`), which resulted in a "Not Found" error when clicked,
especially visible when there were no products.

This change updates the button to use the correct
`admin_product_import_path`, ensuring it correctly navigates to the product
import page.

#### What should we test?

- Login as an admin user
- Go to **Admin → Products** with no products present
- Click **Import multiple products**
- Confirm the product import page loads correctly
- Verify the button still works when products already exist

#### Release notes

Changelog Category:

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

#### Dependencies

None

#### Documentation updates

None

### CODE REVIEW

**Comment by spreadFact** [comment]
Gracias — esto arregla el enlace roto y se ve bien. Probé el flujo localmente: en Admin → Products con la lista vacía, el botón "Import multiple products" ahora abre correctamente la página de importación, y también funciona cuando ya hay productos.  
> Pequeña sugerencia: ¿podrías añadir una spec de sistema/feature que verifique el caso sin productos (visitar Admin → Products, hacer click en el botón y comprobar que se navega a admin_product_import_path)? Aparte de eso, LGTM — apruebo.

**Review by chahmedejaz — APPROVED** [review]

**Comment by piyyu** [comment]
@spreadFact  thanks for the suggestion! Happy to add a system spec in a follow-up if needed 👍

File: spec/system/admin/products_v3/actions_spec.rb [hunk 1]
```diff
@@ -27,7 +27,7 @@
       # displays buttons to add products with the correct links
       expect(page).to have_link(class: "button", text: "New Product", href: "/admin/products/new")
       expect(page).to have_link(class: "button", text: "Import multiple products",
-                                href: "/admin/products/import")
+                                href: admin_product_import_path)
```
Comment (mkllnk) [inline spec/system/admin/products_v3/actions_spec.rb:30]: Here it would be okay to use the explicit string. Otherwise we are not testing much here and just mirroring the code.

**Comment by spreadFact** [comment]
Yes, do as you handle it better is not for me an problem,
Wish you be well

File: spec/system/admin/products_v3/actions_spec.rb (hunk 1 above)
Comment (spreadFact) [reply spec/system/admin/products_v3/actions_spec.rb:30]: Yes, do as you wish,if you need some thing more ,

**Comment by ValVerCH** [comment]
please @filipefurtad0 assign me to this issue

**Comment by ValVerCH** [comment]
@filipefurtad0 could you check my test please : 

I have created an account in staging.openfoodnetwork.org.uk (uk_staging2test) and tested the import button in Products Tab, and It was still not working 
but I have noticed in the Import Tab that the correct route to import button is admin/product_import and not admin_product_import_path nor /admin/products/import (the 2 routes that the developers tried before). 

So the developer should change it to : **admin/product_import** 

Also I did Verify the button still works when products already exist.

**Comment by filipefurtad0** [comment]
Hey @ValVerCH,
Welcome! :bouquet: 

Nice that you were able to add the label. You've triggered staging, but I think the issue might have been with the timing of your test: we need to wait a few minutes (usually 5-10 minutes) for the staging process to be completed. Only after this we should perform tests.

We can check this under Actions tab, on top of this page. We can see that it worked, but probably after you've performed the test:
image

I had a quick look and the issue looked fixed for me :green_circle: 

Maybe you can double check? Let's catch-up on this tomorrow!
Thanks again.

**Comment by ValVerCH** [comment]
Hi @piyyu , I have tested before and after staging your pull request, and it works well, here is the screenshot "after staging", I can confirm that the redirection goes correctly to the Import page. Thanks a lot.

Capture d&#39;écran 2026-01-15 113312-uk staging after
