### PR TITLE
Fix: Admin visiting non-existent enterprise raises error

### LINKED ISSUE #13193: Admin visiting non-existent enterprise raises error
## Error in Open Food Network (Rails)

**NoMethodError** in **admin/enterprises#edit**
undefined method `payment_methods' for nil:NilClass

      enterprise_payment_methods = @enterprise.payment_methods.to_a
                                              ^^^^^^^^^^^^^^^^

[View on Bugsnag](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/675fa77ded6bad5bb36ebf8c?event_id=67c7e70201130e9ac3ef0000&i=gh&m=ci)

## Stacktrace

    app/controllers/admin/enterprises_controller.rb:220 - load_methods_and_fees

[View full stacktrace](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/675fa77ded6bad5bb36ebf8c?event_id=67c7e70201130e9ac3ef0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by Tresor11**
#### What? Why?

Currently, when an admin tries to edit a no-existing enterprise, a `NoMethodError` is raised.

This commit adds a require_enterprise  method that raises a `ActiveRecord::RecordNotFound` error when the enterprise is not found and redirects the user to the enterprise index page with an error message.

- Closes #13193

#### What should we test?

- Login then  visit `/admin/enterprises/no-extisting/edit` you should be redirected to the enterprises path with an error message

Screenshot 2025-04-01 at 02 05 56

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes

### CODE REVIEW

**Review by rioug — COMMENTED** [review]
Thanks @Tresor11 :pray: 
Your solution does fix the problem, but looking at the code I can't tell where this `@enterprise` is coming from. I wonder if the better fix would be to replace the `@enterprise` by `@object`, which represent the model we are looking at. It should be loaded properly via `Admin::ResourceController`  Let's see what other reviewers think.

File: app/controllers/admin/enterprises_controller.rb [hunk 1]
```diff
@@ -216,6 +217,14 @@ def collection_actions
       [:index, :for_order_cycle, :visible, :bulk_update]
     end
 
+    def set_enterprise
+      @enterprise = @object
```
Comment (dacook) [inline app/controllers/admin/enterprises_controller.rb:221]: This instance variable is already set by `ResourceController#load_resource`:
https://github.com/dacook/openfoodnetwork/blob/main/app/controllers/admin/resource_controller.rb#L106-L115

So I would suggest removing that line and then this method perhaps should be named something else like this:

```suggestion
    def require_enterprise
```

**Review by dacook — CHANGES_REQUESTED** [review]
Thanks for looking into this. It appears that it solves the issue, but it would be good to add a request spec to clarify exactly what it solves. 

From what I can see, this change shouldn't be necessary. The `EnterprisesController#load_methods_and_fees` method is expected to run _after_ `ResourceController#load_resource`. `load_resource` calls the ActiveRecord `find` method, which should raise an exception if the resource (enterprise) is not found (see https://github.com/dacook/openfoodnetwork/blob/master/app/controllers/admin/resource_controller.rb#L153-L159).

The ResourceController is intended to handle that and redirect you to the index page, just as your fix does (see `resource_not_found`).

So it would be good to investigate why that functionality wasn't working in this case. The best way would be to write a request spec as mentioned, then you can poke and prod (eg with `binding.pry`) to see what's happening.

Would you be able to have a go at that?

**Comment by Tresor11** [comment]
Thanks for the review. @dacook @rioug 

I agree that reassigning the enterprise instance doesn't feel quite right, since we are already handling the `ActiveRecord::RecordNotFound` error in `ResourceController`, `require_enterprise` should only be responsible for raising an error when the enterprise is not found.
I've added a spec to test this behavior; i'm still not sure why this is not being raised by the resource controller

**Review by dacook — APPROVED** [review]
Great, thanks for adding the spec! I checked out the spec on master and could see the spec failure, then can see your change fixes it.
I've just added a commit to fix the linter errors and I think it's good 👍

**Comment by filipefurtad0** [comment]
Hey @Tresor11, welcome :bouquet: 

Many thanks for fixing this one.

I've reproduced the issue, by logging in as an admin and visiting the enterprise admin path, with a non-existing enterprise name, which triggered the error 500 you described.

After staging the PR, repeating the same scenario displayed the error message:

image

The translation is being picked up correctly - repeating the steps before, with FR as a locale:

image

Looks great! Merging :tada:
