### PR TITLE
[BUU] Fix No explanation why cloning failed

### LINKED ISSUE #12626: [BUU] No explanation why cloning failed
## Description

If cloning of a product fails there is an error message. However it does not indicate what's causing the problem, so the user may not be able to fix it.

## Expected Behavior

The error message should include information about what went wrong and what could be done. 

## Actual Behaviour

There is no additional information on the root cause.

## Steps to Reproduce

1. Activate the feature toggle 'admin_style_v3'.
2. Go to the page `/admin/products`.
3. Make cloning of a product fail. It's unclear how it can be done - it happened accidentally. Maybe it had to do with an invalid format of the product image?

## Animated Gif/Screenshot

image

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12626
- This issue is very hard to reproduce however,
- This PR adds the explanation for those invalid field errors which can be corrected by the user. Otherwise, the default error message will be displayed.

#### What should we test?

- Follow these steps to [reproduce the issue](https://github.com/openfoodfoundation/openfoodnetwork/issues/12626#issuecomment-2288782948)

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/controllers/admin/products_v3_controller.rb [hunk 1]
```diff
@@ -209,6 +219,18 @@ def products_bulk_params
...
         .to_h.with_indifferent_access
     end
+
+    def clone_error_message(error)
+      case error
+      when ActiveRecord::RecordInvalid
+        field_names = error.record.errors.attribute_names
+          .map{ |field_name| VIEW_FIELD_NAME_MAPPER[field_name] }.join(', ')
+
+        field_names.present? ? t('.invalid_fields_error', field_names:) : t('.error')
```
Comment (chahmedejaz) [inline app/controllers/admin/products_v3_controller.rb:229]: I could only think of these fields that may fail product cloning and the user may be able to fix these. If the `field_names` are empty, we display the default error message.
I believe product cloning would fail only on very rare occasions and I'm not sure if it's worth spending more on time investigating all the cases that may fail it and showing the error message to fix it.

**Review by dacook — COMMENTED** [review]
Thanks for solving this one. However it adds quite a lot of logic, to cover a pretty obscure case. 
I would have preferred to lean on Rails' built-in features for this. There's a very handy feature that provides a summary of a  model's errors, you can see an example here: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/voucher_adjustments_controller.rb#L70

The attribute names are translated using the activerecord translations, ie: `en.activerecord.attributes.spree/product`: 
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/en.yml#L68-L75

Do you agree that would be sufficient for this case?

**Comment by chahmedejaz** [comment]
Hi @dacook - Thanks for the feedback. I also thought of this but I had two concerns:
- First was for the translation 
- Second was that there are some attributes which have different names on the view vs the model. Like Variant Unit is displayed as the Unit Scale on the UI.

Thanks for sharing this. It resolved my concerns however, the translations still have the same model vs view names.
I'll look into it if we could change it for our use case here. Thanks

File: config/locales/en.yml [hunk 2]
```diff
@@ -70,7 +70,7 @@ en:
         price: "Price"
         primary_taxon_id: "Product Category"
         shipping_category_id: "Shipping Category"
-        variant_unit: "Variant Unit"
+        variant_unit: "Unit Scale"
```
Comment (chahmedejaz) [inline config/locales/en.yml:73]: `variant_unit` is displayed as Unit Scale on the UI

**Comment by chahmedejaz** [comment]
> The attribute names are translated using the activerecord translations, ie: `en.activerecord.attributes.spree/product`: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/en.yml#L68-L75
> 
> Do you agree that would be sufficient for this case?

@dacook - It's fixed here: https://github.com/openfoodfoundation/openfoodnetwork/pull/12857/commits/2a4d275f4b2113975739f1a75565977b188f2e2d

**Review by dacook — APPROVED** [review]
Excellent, and good idea to update the translation for unit scale 👍

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz ,

I've manually set variant_unit to NULL on the DB to reproduce the issue, and could verify that now a reason is shown, when attempting to clone a product:

image

Looks good! Merging.

**Comment by drummer83** [comment]
Removing the staged-AU label. I assume you're done here, @filipefurtad0?
