### PR TITLE
fix: v1/customers endpoint should load customers of managed enterprises only

### LINKED ISSUE #10585: [API] Customer endpoint returning results for enterprises I can edit
## Description

API endpoints should mimic app behaviour in terms of authentication.

The customer endpoint is returning data for customers of enterprises that:
- I own
- I have permission to manage
- I have permission to edit the profile of.

The UI allows me to view/edit data for customers of enterprises that:
- I own
- I have  permission to manage

Let's update the auth on the API to match the app.

## Expected Behavior

The customer endpoint is returning data for customers of enterprises that:
- I own
- I have permission to manage

## Actual Behaviour

The customer endpoint is returning data for customers of enterprises that:
- I own
- I have permission to manage
- I have permission to edit the profile of.

## Steps to Reproduce

1. With a browser session active for a user that has profile-edit permission only on an enterprise hit https://staging.openfoodnetwork.org.uk/api/v1/customers
2. Compare with an active session for an owner/manager
3. Compare the same sessions within the UI

## Workaround

None

## Severity

S2. A pretty serious one from a data perspective, though low risk as only users who have been granted additional auth by enterprises are impacted.

## Your Environment

* Version used: Live on prod

## Possible Fix

This bug was discovered through excellent testing [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10330). Amazing work @drummer83 :tada:

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #10585

#### What should we test?

- described on: #10585

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by dacook — COMMENTED** [review]
I can see this solves the problem, thanks to the spec 👍 . Is this the same method used in the admin UI? 

I'm worried that it happened in the first place, and was thinking that we shouldn't be defining who has access to what in a controller. 
In fact, we have a gem for that! I've not had to learn about it until now...

https://github.com/CanCanCommunity/cancancan . I see that all our permissions are defined in this file: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/spree/ability.rb

So I'd suggest that we should be managing permissions there instead, and perhaps the admin UI needs updating to do that also. 
It seems like this fix doesn't need to be urgently deployed, so I'll seek another opinion to see if can we improve this further.

File: app/controllers/api/v1/customers_controller.rb [hunk 1]
```diff
@@ -80,9 +80,12 @@ def search_customers
...
       def visible_customers
-        current_api_user.customers.or(
-          Customer.where(enterprise_id: editable_enterprises)
-        )
+        Customer.of(managed_enterprise_ids)
+      end
+
+      def managed_enterprise_ids
+        @managed_enterprise_ids ||= Enterprise.managed_by(current_api_user).
+          select('enterprises.id')
```
Comment (mkllnk) [inline app/controllers/api/v1/customers_controller.rb:88]: You are missing the `current_api_user.customers` part. That is the customer records of the user shopping at other enterprises. It's not mentioned in the issue, except that the issue says:

> API endpoints should mimic app behaviour in terms of authentication.

I think that the app allows to change `allow_charges` as user. `terms_and_conditions_accepted_at` is also done by the user during checkout. But I think that it's okay to leave this out and keep your version. Let's just be sure that we make a transparent decision about this because the API shouldn't change in the future.

@lin-d-hop What do you think?

Comment (mkllnk) [inline app/controllers/api/v1/customers_controller.rb:88]: I can see that this part is copied from the Admin::CustomersController. I agree with David that we should centralise this. It's not about asking for permission of a certain action and therefore I wouldn't use cancancan for this. Instead, it's a collection of records which could go into a scope. What do you think about creating `Customer.managed_by(user)` as a new scope which is then used in both controllers?

Comment (abdellani) [reply app/controllers/api/v1/customers_controller.rb:88]: Sorry, you're right.
When I read `current_api_user.customers`, I thought that `customers` are defined through the `enterprises` that belong to the `user`. 

Now, I can see that there's a direct link between `customers` and `users`.

Comment (abdellani) [reply app/controllers/api/v1/customers_controller.rb:88]: Just to confirm:
Is it possible for a user U1 to have a customer, and that customer doesn't belong to an enterprise managed by the U1?

From the `Admin::CustomersController`, it looks like this is possible only when the user is an admin.
```ruby
    def user_can_create_customer?
      spree_current_user.admin? ||
        spree_current_user.enterprises.include?(@customer.enterprise)
    end
```

Comment (abdellani) [reply app/controllers/api/v1/customers_controller.rb:88]: If the answer to my question is yes.
I don't this that the code will miss `current_api_user.customers`.

if the user is an `Admin`, `Enterprise.managed_by(current_api_user)` will return all the existing enterprises.
```ruby
  scope :managed_by, lambda { |user|
    if user.has_spree_role?('admin')
      where(nil)
    else
      joins(:enterprise_roles).where('enterprise_roles.user_id = ?', user.id)
    end
  }
```
From the customer model, every customer must belong to an enterprise.
```ruby
  belongs_to :enterprise, optional: false
```
So if the current user is an admin, he'll get all the customers.
Otherwise, he'll get the customer of the enterprises managed by him.

Comment (abdellani) [reply app/controllers/api/v1/customers_controller.rb]: I agree. 
I implemented the new scope.

Comment (lin-d-hop) [reply app/controllers/api/v1/customers_controller.rb]: @abdellani I think you are right though I'm not exactly sure I follow.

So a user can be a customer and a user can manage an enterprise that has customers. We want to focus on the relationships of the latter. 

> We want to mimic the behaviour of admin/customers in the API.

So an API user should be able to access and edit the customers of the enterprises that they own and manage (ie set via Enterrprise Settings/Users). They should not be able to access and edit customers for enterprises for which their enterprises have permissions to manange (ie set via enterprise permissions).

SuperAdmin can see everyone and crash the system, as always :sweat_smile: 

> I think that the app allows to change allow_charges as user. terms_and_conditions_accepted_at is also done by the user during checkout. But I think that it's okay to leave this out and keep your version. 

Yes we should not be able to edit allow_charges or terms_and_conditions_accepted_at via the API. An enterprise should not easily be able to edit these.

**Comment by lin-d-hop** [comment]
> I can see this solves the problem, thanks to the spec +1 . Is this the same method used in the admin UI?
> 
> I'm worried that it happened in the first place, and was thinking that we shouldn't be defining who has access to what in a controller. In fact, we have a gem for that! I've not had to learn about it until now...
> 
> https://github.com/CanCanCommunity/cancancan . I see that all our permissions are defined in this file: https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/spree/ability.rb
> 
> So I'd suggest that we should be managing permissions there instead, and perhaps the admin UI needs updating to do that also. It seems like this fix doesn't need to be urgently deployed, so I'll seek another opinion to see if can we improve this further.

@dacook this sounds 100% sensible. In fact I'm surprised this isn't the case. I was also surprised by this bug, but we've had a few contributors work on this issue.
Sounds like a good one to get the whole team across so that we can be sure we're following this practice in code reviews. 
It also makes me wonder if there are any other OFN skill shares we want to explore. We've got a team of great devs but there's so much OFN knowledge to get all the heads around :)

File: app/controllers/api/v1/customers_controller.rb [hunk 2]
```diff
@@ -106,10 +104,6 @@ def customer_params
         attributes
       end
 
-      def editable_enterprises
-        OpenFoodNetwork::Permissions.new(current_api_user).editable_enterprises.select(:id)
-      end
-
```
Comment (dacook) [inline app/controllers/api/v1/customers_controller.rb:112]: It looks like a choice has been made for one method over the other. I'm not sure I'm fully understanding this, so I dove in to check:

* `User#enterprises` is a scope for enterprised managed by the user, based on any enterprise **roles** the user has
* `OpenFoodNetwork::Permissions#editable_enterprises` is more complex, based upon more specific permission `:edit_profile` which is assigned by an enterprise **relationship**

Ah ha, I see now :)
So for roles (managed by), I guess it's ok to use the scope directly, but for permissions around relationships, we need the more complicated helper method.

**Review by dacook — CHANGES_REQUESTED** [review]
Good update. Just to confirm, I agree with Maikel's comment about using a scope in this situation. (I think I mostly understand permissions and roles now..)

But I'd like to see tests for this scope to ensure it's rock solid.

File: app/controllers/api/v1/customers_controller.rb (hunk 1 above)
Comment (mkllnk) [reply app/controllers/api/v1/customers_controller.rb]: I think I added some confusion to this. The association `user.customers` is the customer records of a shopper with the enterprises they bought from. It's not connected to admin at all and I think it's okay to leave it out here. I just raised it because an earlier version allowed to edit those records as well. But I don't think that we want shoppers to be able to update their customer records via the API. The use cases here are for enterprise managers, not customers/shoppers themselves.

File: app/models/customer.rb [hunk 3]
```diff
@@ -35,6 +35,7 @@ class Customer < ApplicationRecord
                     uniqueness: { scope: :enterprise_id, message: I18n.t('validation_msg_is_associated_with_an_exising_customer') }
 
   scope :of, ->(enterprise) { where(enterprise_id: enterprise) }
+  scope :managed_by, ->(user) { user&.persisted? ? where(user: user).or(of(user.enterprises)) : none }
```
[the remark this answers is not in the document]
Comment (abdellani) [reply app/models/customer.rb:38]: > It seems unlikely that user is nil or not persisted, and it would probably return an empty result anyway I think.

I also thought the same, but after running the tests I discovered that when a user calls the API v1 without being authenticated, a `NullObject` will be used as the current_user. 
`Customer.manager_by(currect_user)` will return all the customer with `user_id = nil`

[the remark this answers is not in the document]
Comment (abdellani) [reply app/models/customer.rb:38]: >if the user is a customer of their own enterprise, they should be able to access their customer. But if not, I don't think they should need to.

When can we say that a user is a customer? Is it when customer.user = user?
 
I did some research and from what I understand a user can create multiple customers. Does this mean that every customer represents the user?

**Comment by abdellani** [comment]
@dacook thanks for suggesting the tests. I discovered a mistake in the scope I defined.

**Comment by abdellani** [comment]
The test is failing due to the controller size.
What will be the next step?

**Comment by dacook** [comment]
I can see 
```
app/controllers/admin/customers_controller.rb:6:3: C: Metrics/ClassLength: Class has too many lines. [102/100]
```

I'm a bit confused because that class is over 120 lines long. It must not count some parts. 🤷 My first suggestion is to try to reduce it, but don't see any obvious updates we can do (I tried consolidating the new `customers` method but don't have any great ideas).

Secondly, 100 seems not that long to me. I had to dig a little to discover that [this is Rubocop's default](https://github.com/rubocop/rubocop/blob/master/config/default.yml#L2542-L2549). I think I'll suggest we increase it, it doesn't seem worth spending more time on!

I'll open a separate PR for that. So for now, let's just ignore it.

**Comment by dacook** [comment]
I was really confused: this file was in the rubocop_todo list, but was not being ignored. I noticed that it has been removed from the list on master, so I wondered if some kind of caching in CI was causing this 🤷 .
Oh well, I rebased on master and re-added this to the rubocop_todo list, and it's now passing!

PS I discussed with Maikel and Gaetan and it seems worth keeping the ClassLength rule at 100 lines: it's an ideal length where possible, and a useful prompt to restructure a class which is better to have sooner rather than later. We will always have exceptions, so for now we'll add it to the todo list..
Maikel pointed out that this class may shrink again one day if we implement StimulusReflex here (the json formats would be removed).

File: spec/models/customer_spec.rb [hunk 4]
```diff
@@ -69,4 +69,45 @@
...
+      let!(:user1) { create(:user) }
+      let!(:enterprise1) { create(:enterprise, owner: user1) }
+      let!(:customer2) { create(:customer, enterprise: enterprise1, user: user1) }
+
+      # manager of enterprise1
+      let!(:user2) { create(:user) }
+
+      # user who has edit profile permission on enterprise1
+      let!(:user3) { create(:user) }
+      let!(:enterprise2) { create(:enterprise, owner: user3) }
```
Comment (dacook) [inline spec/models/customer_spec.rb:90]: I could be wrong, but I don't think these need to be `let!`. If changed to just `let`, they will only execute when needed and save time.

Comment (dacook) [reply spec/models/customer_spec.rb:90]: Also is the comment about edit permission right? It is `user2` that has edit_profile permission, not `user3`.

File: spec/models/customer_spec.rb [hunk 5]
```diff
@@ -69,4 +69,45 @@
...
+
+      before do
+        EnterpriseRole.create!(user: user2, enterprise: enterprise)
+        EnterpriseRelationship.create!(parent: enterprise2, child: enterprise,
+                                       permissions_list: [:edit_profile])
+      end
```
Comment (dacook) [inline spec/models/customer_spec.rb:96]: I think this is only relevant to the second example below (`user2`), so it  can be moved inside that one, rather than running unnecessarily for each example.

**Review by dacook — CHANGES_REQUESTED** [review]
Great, thanks for adding the spec. I think we can make it more efficient though.

Also, I take it that the conditions in the scope were all necessary? I've lost my comment, but earlier I suggested that perhaps some could be removed. Did you try removing and see if the specs still pass?

File: spec/models/customer_spec.rb (hunk 5 above)
Comment (abdellani) [reply spec/models/customer_spec.rb]: `user2` is a manager of `enterprise`.
`user3` has `edit_profile` permission on `enterprise` (I want to make sure that he doesn't have access to `enterprise`'s customers

File: spec/models/customer_spec.rb (hunk 4 above)
Comment (dacook) [reply spec/models/customer_spec.rb]: Thanks for clarifying, but I think some of the variables aren't used in all tests, so I've added a commit to explain what I mean.

**Review by dacook — APPROVED** [review]
Otherwise it looks good to me, so I'll approve (including my own tweak ;) )

File: app/models/customer.rb [hunk 6]
```diff
@@ -35,6 +35,7 @@ class Customer < ApplicationRecord
                     uniqueness: { scope: :enterprise_id, message: I18n.t('validation_msg_is_associated_with_an_exising_customer') }
 
   scope :of, ->(enterprise) { where(enterprise_id: enterprise) }
+  scope :managed_by, ->(user) { user&.persisted? ? where(user: user).or(of(Enterprise.managed_by(user))) : none }
```
Comment (mkllnk) [inline app/models/customer.rb:38]: I'm still not sure about `where(user: user)`. This would allow a normal shopper (with API access) to edit their customer entry, right? That includes the enterprise id.

This is a pre-existing issue, so maybe out of scope here but pretty important. Two issues:

1. Do we let buyers change their customer records via the API or only enterprise managers?
2. We shouldn't allow updating the enterprise id. Updating the email can be dangerous as well but that risk is up to the enterprise manager, I think.

File: spec/models/customer_spec.rb [hunk 7]
```diff
@@ -69,4 +69,41 @@
       expect(c.user).to eq user2
     end
   end
+
+  describe 'scopes' do
+    context 'managed_by' do
```
Comment (mkllnk) [inline spec/models/customer_spec.rb:74]: We are missing the test case of the unpersisted user.

**Review by mkllnk — APPROVED** [review]

File: app/models/customer.rb (hunk 6 above)
Comment (abdellani) [reply app/models/customer.rb:38]: maybe @lin-d-hop can help?

File: spec/models/customer_spec.rb (hunk 7 above)
Comment (abdellani) [reply spec/models/customer_spec.rb:74]: done

File: app/models/customer.rb (hunk 6 above)
Comment (lin-d-hop) [reply app/models/customer.rb:38]: This endpoint is intended to mimic admin/customers. Not /account.

A user should not be able to edit their personal customer details unless they are a manager of the hub they are editing themself as a customer of.

Agree enterprise-id should not be editable.
S2 bug.

**Comment by drummer83** [comment]
Hi @abdellani,
Thanks for working on a fix for this! Here are my test results.

# Test setup
2 enterprise users have been set up:
- enterprises@kon...
  - owns Konrad Producer Shop 2 and Konrad Producer Hub (Tax), Konrad Producer Shop (No Tax), Konrad Non-Producer Hub)
  - manages External Producer Shop 0
- producer@kon...
  - owns External Producer Shop 0 and External Producer Shop 1
  - can edit profile of Konrad Producer Shop 2

In total 6 enterprises are in play:
- ID 1821: External Producer Shop 0
- ID 1836: External Producer Shop 1
- ID 1843: Konrad Producer Shop 2
- ID 1829: Konrad Producer Hub (Tax)
- ID 1830: Konrad Producer Shop (No Tax)
- ID 1832: Konrad Non-Producer Hub

# Before staging
## With edit profile permissions activated:
**User enterprises@kon**
- expected customers: from all managed and owned enterprises (see list above)
- **API result:** 19 customers (enterprises@1821 :heavy_check_mark:, kunde@1821 :heavy_check_mark:, enterprises@1829 :heavy_check_mark:, gast@1829 :heavy_check_mark:, kunde@1829 :heavy_check_mark:, kunde2@1829 :heavy_check_mark:, kunde3@1829 :heavy_check_mark:, kunde6@1829 :heavy_check_mark:, producer@1829 :heavy_check_mark:, kunde@1830 :heavy_check_mark:, kunde3@1830 :heavy_check_mark:, producer@1830 :heavy_check_mark:, enterprises@1832 :heavy_check_mark:, kunde@1832 :heavy_check_mark:, kunde3@1832 :heavy_check_mark:, profile@1832 :heavy_check_mark:, enterprise@1836 :x:, kunde@1843 :heavy_check_mark:, producer2@1843 :heavy_check_mark:)
- **UI result:** 18 customers (same as API but without enterprise@1836) :heavy_check_mark: 

**User producer@kon**
- expected customers: from External Producer Shop 0 and External Producer Shop 1 only
- **API result:** 7 customers (enterprises@1821 :heavy_check_mark:, kunde@1821 :heavy_check_mark:, producer@1829 :x:, producer@1830 :x:, enterprises@1836 :heavy_check_mark:, kunde@1843 :x:, producer2@1843 :x:)
- **UI result:** 3 customers :heavy_check_mark: 

## With edit profile permissions removed:
**User enterprises@kon**
- **API result:** 19 customers (unchanged) :x:
- **UI result:** 18 customers (unchanged) :heavy_check_mark:

**User producer@kon**
- **API result:** 5 customers (enterprises@1821 :heavy_check_mark:, kunde@1821 :heavy_check_mark:, producer@1829 :x:, producer@1830 :x:, enterprises@1836 :heavy_check_mark:)
- **UI result:** 3 customers :heavy_check_mark: 

# After staging
## With edit profile permissions activated:
**User enterprises@kon**
- expected customers: from all managed and owned enterprises (see list above)
- **API result: SAME AS BEFORE STAGING** 19 customers (enterprises@1821 :heavy_check_mark:, kunde@1821 :heavy_check_mark:, enterprises@1829 :heavy_check_mark:, gast@1829 :heavy_check_mark:, kunde@1829 :heavy_check_mark:, kunde2@1829 :heavy_check_mark:, kunde3@1829 :heavy_check_mark:, kunde6@1829 :heavy_check_mark:, producer@1829 :heavy_check_mark:, kunde@1830 :heavy_check_mark:, kunde3@1830 :heavy_check_mark:, producer@1830 :heavy_check_mark:, enterprises@1832 :heavy_check_mark:, kunde@1832 :heavy_check_mark:, kunde3@1832 :heavy_check_mark:, profile@1832 :heavy_check_mark:, enterprise@1836 :x:, kunde@1843 :heavy_check_mark:, producer2@1843 :heavy_check_mark:)
- **UI result: SAME AS BEFORE STAGING** 18 customers (same as API but without enterprise@1836) :heavy_check_mark: 

**User producer@kon**
- expected customers: from External Producer Shop 0 and External Producer Shop 1 only
- :exclamation: **API result: CHANGED AFTER STAGING** 5 customers (enterprises@1821 :heavy_check_mark:, kunde@1821 :heavy_check_mark:, producer@1829 :x:, producer@1830 :x:, enterprises@1836 :heavy_check_mark:, ~~kunde@1843~~ :heavy_check_mark:, ~~producer2@1843~~ :heavy_check_mark:)
- **UI result: SAME AS BEFORE STAGING** 3 customers :heavy_check_mark: 

## With edit profile permissions removed:
**User enterprises@kon**
- **API result: SAME AS BEFORE STAGING** 19 customers (unchanged) :x:
- **UI result: SAME AS BEFORE STAGING** 18 customers (unchanged) :heavy_check_mark:

**User producer@kon**
- **API result: SAME AS BEFORE STAGING** 5 customers (enterprises@1821 :heavy_check_mark:, kunde@1821 :heavy_check_mark:, producer@1829 :x:, producer@1830 :x:, enterprises@1836 :heavy_check_mark:)
- **UI result: SAME AS BEFORE STAGING** 3 customers :heavy_check_mark: 

## General checks to avoid regressions
- Running `https://staging.openfoodnetwork.org.uk/api/v1/customers?extra_fields[customer]=balance` as an enterprise admin I get the list of customers for my managed and owned enterprises including the balances. :heavy_check_mark: 
- Running `https://staging.openfoodnetwork.org.uk/api/v1/customers` I get the same list without balances. :heavy_check_mark: 
- The balances match the values I can see in the admin area as well. :heavy_check_mark: 
- I can create a customer for an enterprise I manage. :heavy_check_mark: 
- I can't create a customer for an enterprise I don't manage. :heavy_check_mark: 
- I can update a customer for an enterprise I manage. :heavy_check_mark: 
- I can't update a customer for an enterprise I don't manage. :heavy_check_mark: 
- I can delete a customer for an enterprise I manage. :heavy_check_mark: 
- I can't delete a customer for an enterprise I don't manage. :heavy_check_mark: 

# Results
- After staging the PR customers of enterprises who gave permission to edit their profile are no longer included in the API results. This is exactly what the original issue was about and this is solved now. See kunde@1843 and producer2@1843 not shown anymore after staging the PR. :heavy_check_mark: 
- If the user who is using the API is a customer at any other shops (which he is not managing or owning) he will be listed in the API results. See customer enterprise@ being listed for enterprise ID 1836 and customer producer@ being listed for enterprise IDs 1829, 1830 when doing the API requests themselves (marked with :x: above). I think this is a bug, but it is unrelated to this PR. :arrow_right: I will open an issue for this.
- No regressions could be found! :heavy_check_mark: 

# Open issues from previous conversations
- Create issue for editing enterprise ID (https://github.com/openfoodfoundation/openfoodnetwork/pull/10601#discussion_r1167387642) :arrow_right: @lin-d-hop Are you up for opening this issue?
- Update API documentation, see answer regarding Q2 in the linked comment (https://github.com/openfoodfoundation/openfoodnetwork/pull/10330#issuecomment-1458107385) :arrow_right: @lin-d-hop Who can do this update?

# Final Conclusion
Merging. Thanks again! :muscle: :partying_face:
