### PR TITLE
Hide product from shopfront when out of stock

### LINKED ISSUE #3830: RuntimeError in app/jobs/products_cache_integrity_checker_job.rb:6
## Error in Katuma

**RuntimeError** in **app/jobs/products_cache_integrity_checker_job.rb:6**
Products JSON differs from cached version for distributor: 93, order cycle: 469

[View on Bugsnag](https://app.bugsnag.com/katuma/katuma/errors/5c864dfee822db0019f45a62?event_id=5cd3d0a00039c766cb880000&i=gh&m=ci)

## Stacktrace

    app/jobs/products_cache_integrity_checker_job.rb:6 - perform
    script/delayed_job:5 - <main>

[View full stacktrace](https://app.bugsnag.com/katuma/katuma/errors/5c864dfee822db0019f45a62?event_id=5cd3d0a00039c766cb880000&i=gh&m=ci)

*Created by Katuma via Bugsnag*

## Description

Since v2.0.0 this error that used to happen sporadically now happens more often. This results in surpassing the 250 events/day free quota we have in Katuma. I did see an exceptional increase of these errors while we used v2.0.0 in staging but it wasn't clear whether the issue was limited to staging or not.

This background job checks whether for a given (distributor, order_cycle) pair the cache is stale or not, meaning that the JSON response stored in the cache is not equal to the actual and latest JSON response. This means that we're missing at least a scenario where the cache should be refreshed.

Also, because we enqueue as many of these jobs as cacheable exchanges (exchanges whose order cycle has at least opening or closing date and is not closed yet) and every hour, the flood of recurrent bugsnag notifications is considerable.

## Expected Behavior

The products cache should always be kept up to date by refreshing it when any of the entities involved in a shopfront is updated.

## Actual Behaviour

The products cache is not kept in sync with the actual data updates.

## Steps to Reproduce

TBD

## Context

This has been introduced by v2.0.0.

## Severity

Still not clear. We need to find out if changing the order cycle or any other attribute refreshes the cache. In the meantime, the shopfront won't reflect its actual state.

## Your Environment

* Version used: v2.0.0
* OFN Platform instance where you discovered the bug, and which version of the software they are using: Katuma

## Possible Fix

There must be some new model or attribute added in v2 and involved in a shopfront that doesn't trigger a cache refresh while it should.

A way to know the difference would be to fix the Bugsnag notification so that it could display it. This now fails. We pass `diff: checker.diff.to_s(:text)` as a second argument of the `Bugsnag.notify` call but it should be included in the exception message instead.

Additionally, as explained in https://github.com/openfoodfoundation/openfoodnetwork/wiki/Products-cache#development, there is a settings page to debug cache's staleness but it currently crashes in Katuma. The `log/production.log` shows how the app simply dies:

```
Started GET "/admin/cache_settings/edit" for 109.69.11.78 at 2019-05-09 21:14:48 +0000
Processing by Admin::CacheSettingsController#edit as HTML
Creating scope :accessible_by. Overwriting existing method OrderCycle.accessible_by.
Connecting to database specified by database.yml
[SKYLIGHT] [1.7.2] Skylight agent enabled
Creating scope :deleted. Overwriting existing method Spree::Variant.deleted.
Creating scope :available. Overwriting existing method Spree::PaymentMethod.available.
Creating scope :accessible_by. Overwriting existing method OrderCycle.accessible_by.
```

The root cause of this, as usual, is because we fetch all `Exchange.cacheable` and compute the diff between the cache and the actual shopfront for each of them.

### LINKED ISSUE #3862: Product stays in the product lists even when out of stock
## Description

Whenever a new order is placed and stock is updated the cache is not updated resulting on wrong stock displayed in the shopfront. Since the products cache is only used in the shopfront, all other parts of the app are not affected; they'll display correct stock level.

## Expected Behavior

The shopfront does not display products that are out of stock.

## Actual Behaviour

When you add an out of stock product into the cart, a modal pop ups telling it ran out of stock and then the product greys out forbidding you to purchase it.

## Steps to Reproduce

1. Disable on demand and add some stock to a variant
2. Place an order consuming all the stock available
3. Then, check the updated stock in the variant from the backoffice
4. Try placing a new order adding that same product

## Context

https://github.com/openfoodfoundation/openfoodnetwork/issues/3830#issuecomment-492970792

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v2.0.1
* OFN Platform instance where you discovered the bug: Katuma

## Possible Fix

Add the necessary cache refreshing logic for the new stock item model.

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Closes #3862 and closes #3830

This ensures the cache is up-to-date when a user accesses the shopfront and we use the appropriate stock levels.

Besides, this makes the (very annoying) ProductsCacheIntegrityCheckerJob succeed and thus Bugsnag won't be flooded with failures anymore.

As for the implementation of this. I'm not happy at all. It's disgusting to use `class_eval` for this but it's a good trade-off to deliver this fix ASAP. Katuma's been experiencing this error far too long see_no_evil. I was working on a better implementation that required a bit of refactoring but it was taking too much time. I'll open another PR with it soon.

#### What should we test?

Follow the steps listed by @luisramos0 in https://github.com/openfoodfoundation/openfoodnetwork/issues/3862.

We also need to check that no errors like https://github.com/openfoodfoundation/openfoodnetwork/issues/3830 show up in Bugsnag while testing in staging

#### Release notes

Out of stock variants do not appear in the shopfront anymore and any stock change is properly reflected in the products cache.

### CODE REVIEW

File: spec/models/spree/variant_spec.rb [hunk 1]
```diff
@@ -166,7 +166,8 @@ module Spree
       let(:variant) { create(:variant) }
 
       it "refreshes the products cache on save" do
-        expect(OpenFoodNetwork::ProductsCache).to receive(:variant_changed).with(variant)
+        # When creating the variant both the Variant and StockItem callbacks get executed
```
Comment (sauloperez) [inline spec/models/spree/variant_spec.rb]: I prefer to optimize these things in a separate PR. From my experience, you can end up in a black hole very easily when dealing with them and we need this fix ASAP.

What I have in mind is using something like

```
def refresh_products_cache
  unless variant.id_was == nil # at this point we know we're creating a new variant
    # refresh logic
  end
end
```

Or perhaps simply an `after_update` and an `after_destroy` instead of this broad `after_save`.

**Comment by lin-d-hop** [comment]
Ok I'm testing this now... though it still needs another code review, right?

**Comment by lin-d-hop** [comment]
Testing notes here:
https://docs.google.com/document/d/1Zn9kE9FpaZPvPppPFo_LLRa77R8aPtmtCZnhcU2IP4w/edit#

@sauloperez Back to you as either @Matt-Yorkley or @kristinalim still need to review before merging.
