### PR TITLE
Fix Inconsistent Behavior When Editing Products to mg Units in Hungarian Locale

### LINKED ISSUE #12815: Editing products with mL as units leads to inconsistent behavior with Hungarian locale
## Description
I encountered an issue when changing the unit scale in the admin/products section. This action causes inconsistent behavior when using the Hungarian (hun) locale. The bug is problematic because it affects the accuracy of product information displayed to users in this locale, leading to potential confusion or errors in interpreting product data. I was trying to ensure that product units are correctly scaled and displayed according to local preferences, but the inconsistency prevents achieving this objective effectively.

## Expected Behavior
Changing unit scales with ease.

## Actual Behaviour
When changing unit scales, the modified product banner gets stuck and displays inconsistent results. Additionally, the units change in an inconsistent manner.

## Steps to Reproduce
1. admin_style_v3 feature is enabled at /admin/feature-toggle/features
2. locale is set to hungarian (Magyar)
3. navigate to /admin/products
4. try to change any products Unit scale, e.g. from ml to mg

## Animated Gif/Screenshot
image
)

## Workaround
Switching admin_style_v3 off

## Severity
bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12815
- Please review the comment in the code, I think it'd better explain the change. 

#### What should we test?

- This needs to be validated with the Hungarian language (Magyar)
- Visit the products page
- Update product unit scale to different values
- It's better to validate it with all the available unit scales in the application.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/services/weights_and_measures.rb [hunk 1]
```diff
@@ -26,9 +26,15 @@ def system
   def self.variant_unit_options
     available_units_sorted.flat_map do |measurement, measurement_info|
       measurement_info.filter_map do |scale, unit_info|
+        # Our code is based upon English based number formatting
```
Comment (chahmedejaz) [inline app/services/weights_and_measures.rb:29]: **Ref:**
https://github.com/openfoodfoundation/openfoodnetwork/blob/b2e15f52cfe7239f8edafdc2b15baa1a31223fa2/spec/services/weights_and_measures_spec.rb#L102-L128

File: app/services/weights_and_measures.rb [hunk 2]
```diff
@@ -26,9 +26,15 @@ def system
...
+        # Some language locales like +hu+ uses a comma(,) for decimal separator
+        # While in English, decimal separator is represented by a period.
+        # e.g. en: 0.001, hu: 0,001
+        # Hence the results become "weight_0,001" for hu while or code recognizes "weight_0.001"
         scale_clean =
           ActiveSupport::NumberHelper.number_to_rounded(scale, precision: nil, significant: false,
```
Comment (chahmedejaz) [inline app/services/weights_and_measures.rb:35]: I believe this helper should only be used to round numbers when we want to display the output to the end user as it is highly influenced by the locale being used.

Upon further investigation (_from old UI_), I think it's being an alternative to Javascript's `parseFloat` method which behaves just like this helper. And here Rails being Rails, it just does so much under the hood that it feels like magic and these odd behaviors can be missed easily  😓

**Comment by chahmedejaz** [comment]
**FYI:** The failing specs are unrelated.

File: app/services/weights_and_measures.rb [hunk 3]
```diff
@@ -26,9 +26,15 @@ def system
...
-                                                               strip_insignificant_zeros: true)
+                                                               strip_insignificant_zeros: true,
+                                                               locale: :en)
         [
           "#{I18n.t(measurement)} (#{unit_info['name']})", # Label (eg "Weight (g)")
           "#{measurement}_#{scale_clean}", # Scale ID (eg "weight_1")
```
Comment (chahmedejaz) [inline app/services/weights_and_measures.rb:40]: I'm not sure exactly, we can tweak the keys of the `UNITS` hash such that we don't need to use the helper to round off-scale values here. i.e. already round off keys here. But I'm reluctant to do so because it's being used in other places and not sure if it's a good idea to do it this quickly.
https://github.com/chahmedejaz/openfoodnetwork/blob/a50be52cded204db8ba67e6dee4bdb4888d2d4a1/app/services/weights_and_measures.rb#L65-L86

The current solution works just like we would have expected in the old UI. So, maybe we can go with it for now. 🤷

File: app/models/spree/product.rb [hunk 4]
```diff
@@ -266,7 +266,8 @@ def variant_unit_with_scale
       scale_clean = ActiveSupport::NumberHelper.number_to_rounded(variant_unit_scale,
```
Comment (dacook) [inline app/models/spree/product.rb:266]:
```suggestion
      # Our code is based upon English based number formatting with a period `.`
      scale_clean = ActiveSupport::NumberHelper.number_to_rounded(variant_unit_scale,
```

**Review by dacook — APPROVED** [review]
Thanks so much for looking into this Ahmed. This looks like the perfect quick fix. 
As it is dealing with backend codes that are not visible to the user, it's appropriate to force the locale here. I like that the comment explains why in weights_and_measures, so suggest we also have that in products.rb

**Comment by dacook** [comment]
I think the weights and measures code in the system is pretty complicated and would like to see it simplified somehow.. 
But I don't have a suggestion for that right now!

**Comment by chahmedejaz** [comment]
> I like that the comment explains why in weights_and_measures, so suggest we also have that in products.rb

Thanks, David 👍 

> I think the weights and measures code in the system is pretty complicated and would like to see it simplified somehow..

Yeah, agreed 😅

**Review by mkllnk — APPROVED** [review]
Interesting. I wonder why this didn't fail in Germany and France before. They use a comma, too, right?

I think that the  underlying problem is that we compute identifiers for the units. We should have a fixed set for identifiers. Then we don't need to convert anything which could be affected by a locale.

@chahmedejaz, would you like to work on a follow-up contribution? Now that you fixed the problem, it's just tech debt.

**Comment by chahmedejaz** [comment]
> I think that the underlying problem is that we compute identifiers for the units. We should have a fixed set for identifiers. Then we don't need to convert anything which could be affected by a locale.

Exactly, @mkllnk agreed. Sure would love to work on this tech debt. Thanks. :)

**Comment by chahmedejaz** [comment]
> Interesting. I wonder why this didn't fail in Germany and France before. They use a comma, too, right?

I'll look into these and get back to you whether the locales for these actually use commas in Rails app. Thanks

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz ,

Thanks so much for this blazing fast fix.

First I've followed the steps described here, to enable the HU locale on staging-UK. Then I've reproduced the steps leading to the bug, and could now observe that the units are changed consistently:

From mL:
image

To mg:
image

Edited the name:
image

I've also made some smoke tests around the EN locale, with other units like Kg, and changing these to L, or items. Looks all good.
Since it looks like the bug relates to how commas and dots are used as separators, I've changed this setting in the server and repeated the tests above.

image


All good!
Merging.

**Comment by chahmedejaz** [comment]
> > Interesting. I wonder why this didn't fail in Germany and France before. They use a comma, too, right?
> 
> I'll look into these and get back to you whether the locales for these actually use commas in Rails app. Thanks

I just investigated this, and the issue is reproducible using the French locale however, on the German one it's working fine.
I believe the gem that provides these locales-related formatting data in the app (_rails-i18n_) has a comma as a decimal separator for the French locale and a period for the German.
