### PR TITLE
Fix multi lingual issue in cart and checkout: the user language selection was not being used

### LINKED ISSUE #2491: Selected LOCALE is not maintained with navigation
## Description
If you add a product to the cart on the Portuguese site, it switches to Spanish as you visit the cart.

- go to shop in Portuguese https://alpha.katuma.org/quinta-de-silvares-vizela/shop?locale=pt
- select an order cycle
- add a quantity
- click Edit Cart "Editar carrinho"
- the destination page is a page in spanish

## Expected Behavior
Should keep user language: portuguese in this example.

## Actual Behavior
Switches to Spanish.

## Steps to Reproduce
See description above.

## Context
Portugese version of Katuma not usable like this.

## Severity
S4

## Your Environment
* Version used: katuma live
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): OSX

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #2491 

The function set_locale in the controllers gets the locale variable into the locale cookie, this was only done in:
 - Spree::Admin::BaseController (all OFN backoffice controllers extend this one directly or through ResourceController)
- BaseController (most our frontend controllers extend this one) 

But in the frontoffice, we were missing this set_locale in all controllers that do not extend BaseController, basically, controllers still relying on Spree code:
- controllers/CheckoutController (extends Spree::CheckoutController)
- controllers/spree/Spree::OrdersController.class_eval
- controllers/spree/Spree::UsersController

UsersController already had the set_locale call itself and the other two CheckoutController and OrdersController both extend StoreController, so, that was the destination of the new call to set_locale. See the code.

I have checked backoffice code and some pages and I couldnt find any similar problem there.

#### What should we test?
Cart and checkout process with a non-default language.

#### Release notes
Changelog Category: Fixed
Bug in non-default language: user language selection is no longer jumping to default selection on the cart/checkout process. It keeps the user language through the process.

#### How is this related to the Spree upgrade?
not related.

### CODE REVIEW

File: app/controllers/spree/store_controller_decorator.rb [hunk 1]
```diff
@@ -1,6 +1,9 @@
 class Spree::StoreController
   layout 'darkswarm'
 
+  include I18nHelper
+  before_filter :set_locale
```
Comment (sauloperez) [inline app/controllers/spree/store_controller_decorator.rb]: Would you mind adding test for this in `spec/controllers/spree/store_controller_spec.rb`?

Comment (luisramos0) [reply app/controllers/spree/store_controller_decorator.rb]: When I think that the it will more expensive to add the test than the value it provides I skip it.
My initial intuition about this test was right.
But well, if you ask. I just spent an hour trying to write this test without success.
Maybe you can help, this is my best try:

```
require 'spec_helper'

describe Spree::StoreController, type: :controller do

  include I18nHelper
  def params
    {locale: 'xp'}
  end

  def spree_current_user
  end

  controller(Spree::StoreController) do
    before_filter :unauthorized
    def index
      render text: ""
    end
  end

  it "redirects to home when unauthorized" do
    get :index
    response.should render_template("shared/unauthorized", layout: 'darkswarm')
  end

  it "calls set_locale before index" do
    expect(controller).to receive(set_locale)

    get :index
  end
end
```

**Comment by luisramos0** [comment]
I have fixed the certificate on staging.katuma and the broken menu. It's all working now.

I've also tested the PR and it's looking good.

@RachL @myriamboure could you guys give this one a look so it gets included in todays release?
Thanks!

**Comment by RachL** [comment]
@luisramos0 sorry I've missed this comment! I'm on it. Don't hesitate to ping me on slack next time ;)

**Comment by RachL** [comment]
I think we are good to go! However I've did 2 orders one in Portuguese, one in Spanish and I've didn't received an email confirmation for the one in Portuguese. Maybe just email configuration missing on staging @sauloperez ?

Portugues:
image

Castellano:
image

**Comment by sauloperez** [comment]
>  Maybe just Portuguese email configuration missing on staging @sauloperez ?

There shouldn't be any difference so might be something else. Can you create an issue to investigate it after reproducing it again?
