### PR TITLE
Searching variants should order results by variant display name

### LINKED ISSUE #8507: Placing order from backoffice: product search gives results in random order and hub managers lose time
## Description
When a hub manager make an order for a customer from backoffice, they have to search for a product before adding it to the order. For that they type the first letters of the product. The problem is that for products with many variants starting with the same letters, the products are rendered in different order each time, without any reason. So the hub manager spends time for each new order to search again where is the product, there is no logical order in the way products are shown.

## Expected Behavior
When I start typing in the search box, products are shown in alphabetical order

## Actual Behavior
When I start typing in the search box, products are shown in random order

## Steps to Reproduce
1 Go to orders / new order / select a distributor and OC. Make sure you have some products with multiple variants whose names start the same way, like "Bread - wheat 1kg", "Bread - wheat 2kg", "Bread - spelt 1kg", etc.
2. Start typing "Brea" and see the result.
3. Redo the process again and see the result. Order has changed without reason.

## Animated Gif/Screenshot
capture d ecran de 2018-07-12 23-30-45
capture d ecran de 2018-07-12 23-31-54

## Context
A hub reported that bug, it is a bug that works with some people who are very bad with internet so still do some orders for them. They get very annoyed to have to go through the list of products without having any logical way to search.

## Severity
S4

## Your Environment
* Version used: V1.15
* Browser name and version: Mozilla
* Operating System and version (desktop or mobile): Ubuntu 18.

## Possible Fix
When start typing display resultats in alphabetical order?

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #8507

Order variant search by `display_name` of a variant.

#### What should we test?
 1. Go to orders / new order / select a distributor and OC. Make sure you have some products with multiple variants whose names start the same way, like "Bread - wheat 1kg", "Bread - wheat 2kg", "Bread - spelt 1kg", etc.
 2. Start typing "Brea" and see the results are ordered by display_name.
 3. Redo the process again and see the results is the same

#### Release note
Searching variants should order results by variant display name
Changelog Category: User facing changes

### CODE REVIEW

File: lib/open_food_network/scope_variants_for_search.rb [hunk 1]
```diff
@@ -34,7 +34,9 @@ def search_params
     def query_scope
       Spree::Variant.where(is_master: false).
         includes(option_values: :option_type).
-        ransack(search_params.merge(m: 'or')).result
+        ransack(search_params.merge(m: 'or')).
+        result.
+        order("display_name")
```
Comment (jibees) [inline lib/open_food_network/scope_variants_for_search.rb:39]: Is the `display_name` always filled? Should we use this field or the `display_as` field?

Comment (mkllnk) [reply lib/open_food_network/scope_variants_for_search.rb:39]: It depends on what is used. Did you test this? Maybe add a spec!

I'm just guessing, but I found this form referenced the the add-product form:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6e905bd2fc21767017fc8c56792ed43d2e812810/app/views/spree/admin/variants/_autocomplete.js.erb#L12

And the serializer defines the name like this:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6e905bd2fc21767017fc8c56792ed43d2e812810/app/serializers/api/admin/variant_serializer.rb#L11-L17

But neither `name` nor `full_name` is not a column in the variants table. `name` comes from the product:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6e905bd2fc21767017fc8c56792ed43d2e812810/app/models/spree/variant.rb#L22

And `full_name` is obscurely defined here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6e905bd2fc21767017fc8c56792ed43d2e812810/app/services/variant_units/variant_and_line_item_naming.rb#L49-L61

So the search order would be name, display_name, unit_to_display. This last attribute is computed as well:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6e905bd2fc21767017fc8c56792ed43d2e812810/app/services/variant_units/variant_and_line_item_naming.rb#L69-L77

We can expand that to display_as, variant_unit_name, options_text. And now we reach a point that is probably not worth implementing the order for:
https://github.com/openfoodfoundation/openfoodnetwork/blob/6e905bd2fc21767017fc8c56792ed43d2e812810/app/services/variant_units/variant_and_line_item_naming.rb#L12-L26

I haven't tested this but kind of pseudo code could look like this:

```suggestion
        includes(:product).
        order("name, display_name, display_as, variant_unit_name")
```

Still not perfect but maybe it was never implemented because the perfect solution is too hard.

Comment (jibees) [reply lib/open_food_network/scope_variants_for_search.rb]: Thanks a lot for you deep search, very appreciate... 🙏 

> Did you test this? Maybe add a spec!

Yep sure, and works fine for me, in my specific case, not sure this is the "normal" case ;)

I follow your advice: a5292d179

File: spec/lib/open_food_network/scope_variants_to_search_spec.rb [hunk 2]
```diff
@@ -73,7 +73,7 @@
         v2.save!
         v3.save!
         v4.save!
-        expect(result.map(&:display_name)).to eq ["Product 1", "Product 1 - a", "Product 1 - b", "Product 1 - c"]
+        expect(result.map(&:display_name)).to eq ["Product 1 - a", "Product 1 - b", "Product 1 - c", "Product 1"]
```
Comment (mkllnk) [inline spec/lib/open_food_network/scope_variants_to_search_spec.rb:76]: Oh, do we want this change in order? It doesn't seem intuitive to me. Is it due to [NULL values](https://www.postgresql.org/docs/8.3/queries-order.html) or depending on the product name?

Comment (jibees) [reply spec/lib/open_food_network/scope_variants_to_search_spec.rb:76]: Yes, it depends on the product.name:
```
(byebug) result[3].name
"Product 4"
```
(as we set `v4.display_name = "Product 1"`)

Don't know if sorting by name is a good idea then.

Comment (jibees) [reply spec/lib/open_food_network/scope_variants_to_search_spec.rb]: Then, I've updated the PR by commit d4af03dc5

Comment (mkllnk) [reply spec/lib/open_food_network/scope_variants_to_search_spec.rb]: Hang on, we are going in circles here. So your spec is looking at `display_name` and that didn't seem intuitive with the new order including the product. But I thought that the view (or the serializer) actually prints `"#{object.name} - #{object.full_name}"` which refers to the product's name. So if you want to test the order as displayed when adding a product then you have to test for this, not just display_name.

Maybe we should add a spec for the admin variant serializer? That should be much closer to what we see on the page.

I'm sorry for pointing in the wrong direction before. I just asked a question because I didn't actually know the answer. I hadn't thought that through.

Comment (jibees) [reply spec/lib/open_food_network/scope_variants_to_search_spec.rb]: I did a last (?) _force push_ commit. I didn't add a spec for the admin variant serializer (mainly because out of scope, but actually it could be interesting/going crazy to implement such a thing)
Hope it pass the review now ;)

File: lib/open_food_network/scope_variants_for_search.rb [hunk 3]
```diff
@@ -34,7 +34,10 @@ def search_params
     def query_scope
       Spree::Variant.where(is_master: false).
         includes(option_values: :option_type).
-        ransack(search_params.merge(m: 'or')).result
+        ransack(search_params.merge(m: 'or')).
+        result.
+        includes(:product).
+        order("products_spree_variants.name, display_name, display_as, products_spree_variants.variant_unit_name")
```
Comment (mkllnk) [inline lib/open_food_network/scope_variants_for_search.rb:40]: Where does that table name come from? Isn't it `spree_products`?

There are failing specs related to this.

Comment (jibees) [reply lib/open_food_network/scope_variants_for_search.rb:40]: @mkllnk 
I don't see any solution here, I'm a bit stuck actually. 
`products_spree_variants ` seems to be a generated table name from ``.
See the generated SQL here: 
```sql
SELECT DISTINCT spree_variants.*,
                "spree_variants"."id" AS t0_r0,
                "spree_option_values"."id" AS t1_r0,
                "spree_option_values"."position" AS t1_r1,
                "spree_option_values"."name" AS t1_r2,
                "spree_option_values"."presentation" AS t1_r3,
                "spree_option_values"."option_type_id" AS t1_r4,
                "spree_option_values"."created_at" AS t1_r5,
                "spree_option_values"."updated_at" AS t1_r6,
                "spree_option_types"."id" AS t2_r0,
                "spree_option_types"."name" AS t2_r1,
                "spree_option_types"."presentation" AS t2_r2,
                "spree_option_types"."created_at" AS t2_r3,
                "spree_option_types"."updated_at" AS t2_r4,
                "spree_option_types"."position" AS t2_r5,
                "products_spree_variants"."id" AS t3_r0,
                "products_spree_variants"."name" AS t3_r1,
                "products_spree_variants"."description" AS t3_r2,
                "products_spree_variants"."available_on" AS t3_r3,
                "products_spree_variants"."deleted_at" AS t3_r4,
                "products_spree_variants"."permalink" AS t3_r5,
                "products_spree_variants"."meta_description" AS t3_r6,
                "products_spree_variants"."meta_keywords" AS t3_r7,
                "products_spree_variants"."tax_category_id" AS t3_r8,
                "products_spree_variants"."shipping_category_id" AS t3_r9,
                "products_spree_variants"."created_at" AS t3_r10,
                "products_spree_variants"."updated_at" AS t3_r11,
                "products_spree_variants"."supplier_id" AS t3_r12,
                "products_spree_variants"."group_buy" AS t3_r13,
                "products_spree_variants"."group_buy_unit_size" AS t3_r14,
                "products_spree_variants"."variant_unit" AS t3_r15,
                "products_spree_variants"."variant_unit_scale" AS t3_r16,
                "products_spree_variants"."variant_unit_name" AS t3_r17,
                "products_spree_variants"."notes" AS t3_r18,
                "products_spree_variants"."primary_taxon_id" AS t3_r19,
                "products_spree_variants"."inherits_properties" AS t3_r20
FROM "spree_variants"
INNER JOIN "exchange_variants" ON "exchange_variants"."variant_id" = "spree_variants"."id"
INNER JOIN "exchanges" ON "exchanges"."id" = "exchange_variants"."exchange_id"
INNER JOIN "order_cycles" ON "order_cycles"."id" = "exchanges"."order_cycle_id"
LEFT OUTER JOIN "spree_products" ON "spree_products"."id" = "spree_variants"."product_id"
LEFT OUTER JOIN "spree_option_values_variants" ON "spree_option_values_variants"."variant_id" = "spree_variants"."id"
LEFT OUTER JOIN "spree_option_values" ON "spree_option_values"."id" = "spree_option_values_variants"."option_value_id"
LEFT OUTER JOIN "spree_option_types" ON "spree_option_types"."id" = "spree_option_values"."option_type_id"
LEFT OUTER JOIN "spree_products" "products_spree_variants" ON "products_spree_variants"."id" = "spree_variants"."product_id"
WHERE "spree_variants"."deleted_at" IS NULL
  AND "spree_variants"."is_master" = $1
  AND ("spree_products"."name" ILIKE '%brea%'
       OR "spree_variants"."sku" ILIKE '%brea%')
  AND "exchanges"."incoming" = $2
  AND (order_cycles.id = '1')
  AND "spree_variants"."id" IN
    (SELECT "exchange_variants"."variant_id"
     FROM "exchange_variants"
     INNER JOIN "exchanges" ON "exchanges"."id" = "exchange_variants"."exchange_id"
     WHERE (exchanges.incoming = FALSE
            AND exchanges.receiver_id = 3))
ORDER BY products_spree_variants.name,
         display_name,
         display_as,
         products_spree_variants.variant_unit_name
```



If I used `spree_products` instead (which seems to be logical) I get a SQL error: 
`ORDER BY expressions must appear in select list`
The generated SQL is here: 
```sql
SELECT DISTINCT spree_variants.*
FROM "spree_variants"
INNER JOIN "exchange_variants" ON "exchange_variants"."variant_id" = "spree_variants"."id"
INNER JOIN "exchanges" ON "exchanges"."id" = "exchange_variants"."exchange_id"
INNER JOIN "order_cycles" ON "order_cycles"."id" = "exchanges"."order_cycle_id"
LEFT OUTER JOIN "spree_products" ON "spree_products"."id" = "spree_variants"."product_id"
WHERE "spree_variants"."deleted_at" IS NULL
  AND "spree_variants"."is_master" = $1
  AND ("spree_products"."name" ILIKE '%bread%'
       OR "spree_variants"."sku" ILIKE '%bread%')
  AND "exchanges"."incoming" = $2
  AND (order_cycles.id = '1')
  AND "spree_variants"."id" IN
    (SELECT "exchange_variants"."variant_id"
     FROM "exchange_variants"
     INNER JOIN "exchanges" ON "exchanges"."id" = "exchange_variants"."exchange_id"
     WHERE (exchanges.incoming = FALSE
            AND exchanges.receiver_id = 3))
ORDER BY spree_products.name,
         display_name,
         display_as,
         spree_products.variant_unit_name
```

I'd invoke some help here ;) Thanks a lot.

Comment (mkllnk) [reply lib/open_food_network/scope_variants_for_search.rb:40]: Ouch, that's complicated. So in this case Rails generates the table name `products_spree_variants` selects attributes on that one. I don't know the solution. I need to play with it myself.

Comment (mkllnk) [reply lib/open_food_network/scope_variants_for_search.rb]: Okay, I found two solutions. First, it occurred to me that Rails has a way of telling that you want to reference the joined table and it looked like this:
```diff
--- a/lib/open_food_network/scope_variants_for_search.rb
+++ b/lib/open_food_network/scope_variants_for_search.rb
@@@ -37,7 -37,7 +37,8 @@@ module OpenFoodNetwor
          ransack(search_params.merge(m: 'or')).
          result.
          includes(:product).
--        order("products_spree_variants.name, display_name, display_as, products_spree_variants.variant_unit_name")
++        references(:product).
++        order("spree_products.name, display_name, display_as, spree_products.variant_unit_name")
      end
  
      def distributor
```

That's great but the generated query is ugly and I found a better way of telling Rails how to sort and it can optimise under the hood however it likes. I added a commit for that. :crossed_fingers: I hope that all specs pass now.

Comment (mkllnk) [reply lib/open_food_network/scope_variants_for_search.rb]: Okay, this didn't work. We have more failing specs now. The problem is that some code parts are changing the select statement, I think. Maybe we have to include the order statement somewhere else.

Comment (jibees) [reply lib/open_food_network/scope_variants_for_search.rb]: Based on what I've done in https://github.com/openfoodfoundation/openfoodnetwork/pull/8615, I made another try with commit: a33ebbdc8
```ruby
[...]
        result.
        order("spree_products.name, display_name, display_as, spree_products.variant_unit_name").
        includes(:product).
        joins(:product)
```
The key here is to `include` and `joins` _after_ the `order` in order to `select` `spree_products.*` and therefore be able to `order by`  `spree_products.name` and `spree_products.variant_unit_name`

Comment (achauve) [reply lib/open_food_network/scope_variants_for_search.rb]: @jibees Could you paste the new SQL request?

Comment (jibees) [reply lib/open_food_network/scope_variants_for_search.rb]: @achauve 

```sql
SELECT DISTINCT spree_variants.*,
                "spree_variants"."id" AS t0_r0,
                "spree_option_values"."id" AS t1_r0,
                "spree_option_values"."position" AS t1_r1,
                "spree_option_values"."name" AS t1_r2,
                "spree_option_values"."presentation" AS t1_r3,
                "spree_option_values"."option_type_id" AS t1_r4,
                "spree_option_values"."created_at" AS t1_r5,
                "spree_option_values"."updated_at" AS t1_r6,
                "spree_option_types"."id" AS t2_r0,
                "spree_option_types"."name" AS t2_r1,
                "spree_option_types"."presentation" AS t2_r2,
                "spree_option_types"."created_at" AS t2_r3,
                "spree_option_types"."updated_at" AS t2_r4,
                "spree_option_types"."position" AS t2_r5,
                "spree_products"."id" AS t3_r0,
                "spree_products"."name" AS t3_r1,
                "spree_products"."description" AS t3_r2,
                "spree_products"."available_on" AS t3_r3,
                "spree_products"."deleted_at" AS t3_r4,
                "spree_products"."permalink" AS t3_r5,
                "spree_products"."meta_description" AS t3_r6,
                "spree_products"."meta_keywords" AS t3_r7,
                "spree_products"."tax_category_id" AS t3_r8,
                "spree_products"."shipping_category_id" AS t3_r9,
                "spree_products"."created_at" AS t3_r10,
                "spree_products"."updated_at" AS t3_r11,
                "spree_products"."supplier_id" AS t3_r12,
                "spree_products"."group_buy" AS t3_r13,
                "spree_products"."group_buy_unit_size" AS t3_r14,
                "spree_products"."variant_unit" AS t3_r15,
                "spree_products"."variant_unit_scale" AS t3_r16,
                "spree_products"."variant_unit_name" AS t3_r17,
                "spree_products"."notes" AS t3_r18,
                "spree_products"."primary_taxon_id" AS t3_r19,
                "spree_products"."inherits_properties" AS t3_r20
FROM "spree_variants"
INNER JOIN "spree_products" ON "spree_products"."id" = "spree_variants"."product_id"
INNER JOIN "exchange_variants" ON "exchange_variants"."variant_id" = "spree_variants"."id"
INNER JOIN "exchanges" ON "exchanges"."id" = "exchange_variants"."exchange_id"
INNER JOIN "order_cycles" ON "order_cycles"."id" = "exchanges"."order_cycle_id"
LEFT OUTER JOIN "spree_option_values_variants" ON "spree_option_values_variants"."variant_id" = "spree_variants"."id"
LEFT OUTER JOIN "spree_option_values" ON "spree_option_values"."id" = "spree_option_values_variants"."option_value_id"
LEFT OUTER JOIN "spree_option_types" ON "spree_option_types"."id" = "spree_option_values"."option_type_id"
WHERE "spree_variants"."deleted_at" IS NULL
  AND "spree_variants"."is_master" = $1
  AND ("spree_products"."name" ILIKE '%bread%'
       OR "spree_variants"."sku" ILIKE '%bread%')
  AND "exchanges"."incoming" = $2
  AND (order_cycles.id = '1')
  AND "spree_variants"."id" IN
    (SELECT "exchange_variants"."variant_id"
     FROM "exchange_variants"
     INNER JOIN "exchanges" ON "exchanges"."id" = "exchange_variants"."exchange_id"
     WHERE (exchanges.incoming = FALSE
            AND exchanges.receiver_id = 3))
ORDER BY spree_products.name,
         display_name,
         display_as,
         spree_products.variant_unit_name
```

Comment (jibees) [reply lib/open_food_network/scope_variants_for_search.rb]: I guess the order by `display_name` and `display_as` is useless...

Comment (achauve) [reply lib/open_food_network/scope_variants_for_search.rb]: Thanks! your query seems a lot cleaner than before! However I'm still not sure why. There are lots of nested rails scopes. Is it usefull only to override previous scopes? And in your case don't "joins" and "includes" do the same thing (= inner join to products table to include products in result set)?

**Comment by mkllnk** [comment]
> The key here is to include and joins after the order

Really? I don't think that it makes a difference. But adding the `joins` should have done the trick.

> don't "joins" and "includes" do the same thing

Almost, but no. Joins is just affecting the query. You join because you want to do stuff like ordering here. The `includes` statement tells Rails to load the association at the same time but Rails decides how to do that (e.g. naming tables differently) and then Rails includes the association on the resulting Ruby objects. If you just do `joins` and then call the association on a model, it issues a new query to load the association.

**Review by mkllnk — APPROVED** [review]

**Comment by achauve** [comment]
Thanks Maikel for the details! So for ordering only, `joins` should be used but not `includes`? And mixing `includes` with fragments of hand-written SQL is not super good if rails renames things behind the scene?

**Review by achauve — APPROVED** [review]

**Comment by achauve** [comment]
Also not sure about code conventions: do we prefer using `.merge(Spree::Product.order(:name)` or `.order("spree_products.name")`? @mkllnk @Matt-Yorkley @jibees 
The first one has the advantage of not referencing manually table names?

**Comment by mkllnk** [comment]
> mixing includes with fragments of hand-written SQL is not super good

Correct. `includes` is only to tell Rails to preload data and can't be relied upon in writing SQL.

> for ordering only, joins should be used but not includes

The Rails documentation would say that if you use `includes` already and want to reference the table than you need to add `references` as well. That's the best solution when you preload data and add SQL. But in this example it failed because the `SELECT` clause was changed as well in some cases and `joins` seems to be our only option. To be hones, I'm not sure why `references` didn't work. It must be some limitation of Rails.

> do we prefer using .merge(Spree::Product.order(:name) or .order("spree_products.name")?

We don't have a rule for that (yet). The simple order clause is easier to understand and has been used in the past. In this example I used the `merge` approach hoping that Rails would recognise better what's happening and make it work with `references`. 

I think that avoiding writing SQL is better in general but there may be cases when it's a lot simpler to write SQL. It depends on the circumstances. In this specific case I don't mind either way.

**Comment by filipefurtad0** [comment]
Hey @jibees,

Sorry - I've lost your help request out of radar :pray: 

Before your PR - we can see that `Apples_2` comes before `Apples_13` on the result bar:
image

After your PR we can see that the ordering is:
- `Apples_1`*
- `Apples_2`
- `Apples_2`*

Which is the goal - awesome! :tada: 
Merging.
