### PR TITLE
Include the 'Ready for' time for the order cycle in the Notify Producers email

### LINKED ISSUE #6371: Notify Producers Email includes "ready for" of Order Cycle
## Description
As a Producer I use the Notify Producers Email to facilitate packing and administration of orders. I receive this email for every Order Cycle, and there is no distinguishing information for me to know which Order Cycle the email is referring to.

To simplify administering and organising Order Cycle Management, it would be helpful if the email contained the Order Cycle's 'Ready For' information so that I can easily refer to the orders from the correct order cycle when processing orders.

## Expected Behavior

As an Enterprise, I want my Producers to be able to see the following information in the Notify Producers Email:

**1. ORDER CYCLE INFORMATION**
The email should include the 'Ready For' information for the Order Cycle that appears in the Shopfront. In the example below, this would be:

Sunday 8th November

Screen Shot 2020-11-04 at 5 04 35 PM

The Order Cycle information should be included in the first line of the email text. It would replace the current text:

_We now have all the consumer orders for the next food drop._

The new first line of text should be. 

_Please find below an update about Order Cycle Ready For_ **READY FOR INFORMATION HERE**

See example:

Please find
 

## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by cillian**
This is so people can distinguish which order cycle the email is referring to. 

Closes #6371

#### What should we test?

1. Find a open Order Cycle in the admin area.
2. Click the _Notify producers_ button.
3. Check the email sent to the producer contains the _Ready for_ value.

#### Release notes

Include the 'Ready for' time for the order cycle in the Notify Producers email.

Changelog Category: User facing changes

### CODE REVIEW

**Review by sauloperez — APPROVED** [review]
welcome back @cillian ! that'll be very useful :muscle:

**Comment by sauloperez** [comment]
@filipefurtad0 this is a great example of a thing that's properly tested automatically. After you double-check so I wouldn't test it manually anymore.

File: app/mailers/producer_mailer.rb [hunk 1]
```diff
@@ -36,6 +36,7 @@ def load_data
     line_items = line_items_from(@order_cycle, @producer)
 
     @grouped_line_items = line_items.group_by(&:product_and_full_name)
+    @ready_for = @order_cycle.pickup_time_for(@coordinator)
```
Comment (Matt-Yorkley) [inline app/mailers/producer_mailer.rb:39]: Ahh... we might need to be a bit careful here. Pickup times are on outgoing exchanges, and I think it's possible that the OC's **coordinator** enterprise might not always be the enterprise handling the outgoing exchange...?

Comment (Matt-Yorkley) [reply app/mailers/producer_mailer.rb:39]: This is a tricky one. Maybe @filipefurtad0 has some insight?

Comment (sauloperez) [reply app/mailers/producer_mailer.rb:39]: oh yes, that's right :see_no_evil:

Comment (filipefurtad0) [reply app/mailers/producer_mailer.rb:39]: That's a great catch @Matt-Yorkley - I think the key role here would be the `distributor`, instead of the coordinator. As I understand this, a coordinator can have different distributors, each with different `pickup_time`s. So, each "Notify Producers" email will may have different `pickup_time` or `ready for` info.

**Comment by filipefurtad0** [comment]
Hey @cillian ,
Thank you so much for addressing this.

I tested the "Notify producers" Email before and after this PR, on this OC:

image

- the first `distributor` is also a producer (Baguette Factory)
- the second `distributor` is also the `coordinator` of the OC (Baguette Hub).

Somehow, I can't get the new line to appear on the emails. I can see the `receival instructions` - set in the Incoming Products - but neither "pickup time" nor "pickup instructions" - which are set in the Outgoing Products section - appear on the body of the email.

The notification emails look like this - I see no change introduced:

image

and 

image

I'm not sure this relates to @Matt-Yorkley comment above; I tend to agree and find that the key actors are the `supplier/producer` (incoming) and the `distributor` (outgoing exchange). This is set up by the order-cycle `coordinator`.

I was a bit surprised to see this PR passes the introduced test-cases on the specs. I'm moving this back to In Dev but please let me know if there is something you think I should test.

File: app/mailers/producer_mailer.rb (hunk 1 above)
Comment (cillian) [reply app/mailers/producer_mailer.rb]: Thanks, good to know. I have updated this [here ](https://github.com/openfoodfoundation/openfoodnetwork/pull/6674/commits/70a557cea37eea43b836c1f9d3d57730150c1961) so it displays the pickup times for each distributor now but not sure if it's correct yet because I'm not very familiar with incoming/outgoing exchanges.

**Comment by cillian** [comment]
Hi @filipefurtad0
I think that updated translation might not be appearing yet because of a different locale because I only updated [config/locale/en.yml](https://github.com/openfoodfoundation/openfoodnetwork/pull/6674/files#diff-44438ce218f5287c58d0017f965d888715635d94280669896f75841fbd7b4cd7L1656)

**Comment by sigmundpetersen** [comment]
What's the state of this one? Is it ready for another round of reviews?
@cillian @filipefurtad0

**Comment by filipefurtad0** [comment]
Thanks for pointing this out @sigmundpetersen.
I see there are some changes, so maybe ready for reviews?

I'll move it forward to code-review - please let us know if you feel otherwise @cillian :+1:

**Comment by cillian** [comment]
@filipefurtad0 @sigmundpetersen Yes this one is ready for review, thank you.

**Review by andrewpbrett — APPROVED** [review]
This looks good to me! I'm curious if the missing translation was actually the reason it didn't show up, however. I think it's ready to test again.

**Comment by filipefurtad0** [comment]
Hey @cillian ,

Awesome :tada: 

The ready for field is now visible on the email to the respective distributors:

image

This is really useful, thank you for this improvement!
Ready to go.
