### PR TITLE
Spree 2 Upgrade - MailMethod - Fix "undefined mail method" error in specs

### LINKED ISSUE #2020: [Spree 2 Upgrade] Fix references to MailMethod in specs
## What

We need to get rid of the creation of `Spree::MailMethod` in all specs and use `Spree::Config[:mails_from]` instead. 

So in https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/controllers/spree/orders_controller_spec.rb#L401 we would turn:

```ruby
Spree::MailMethod.create!(
  environment: Rails.env,
  preferred_mails_from: 'spree@example.com'
)
```

into:

```ruby
Spree::Config[:mails_from] = "spree@example.com"
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #2020 

Doing exactly what's described in #2020.

#### What should we test?
All these specs should now have progressed to green or other errors as described below.

Tests not verifiable right now as tests fail with other errors:
- spec/controllers/admin/subscriptions_controller_spec.rb:627 (2 tests)
- spec/jobs/subscription_confirm_job_spec.rb:104 (3 tests)

Tests with new errors:
- spec/controllers/spree/admin/orders_controller_spec.rb:180
       - other error related to email expectations
- spec/features/consumer/shopping/orders_spec.rb:38
       - other unrelated error
- spec/mailers/producer_mailer_spec.rb:4 (10 tests)
       - other error related to email expectations
- spec/mailers/enterprise_mailer_spec.rb:3
      - other error related to email expectations

Green tests:
- spec/controllers/spree/orders_controller_spec.rb:397
        - green after PR #2587 and PR #2574
- spec/models/order_cycle_spec.rb:517
        - green - I had to add a array sort in this spec expectation
- spec/models/spree/order_spec.rb:495
        - green
- spec/controllers/user_passwords_controller_spec.rb:34
       - green, just removed MailMethod call (this call is no longer needed)
- spec/mailers/user_mailer_spec.rb:4 (5 tests)
       - green, just removed MailMethod call

#### How is this related to the Spree upgrade?
This is part of getting the spree2 branch build to green.

#### Dependencies
This is related to PR #2587 and PR #2574 but can go first.

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
@luisramos0 please connect your PR's to issues :)

File: spec/models/order_cycle_spec.rb [hunk 1]
```diff
@@ -525,15 +525,13 @@
...
-        environment: Rails.env,
-        preferred_mails_from: 'spree@example.com'
-      )
+      Spree::Config[:mails_from] = "spree@example.com"
     end
     before { order5.cancel }
 
     it "only returns items from non-cancelled orders in the OC, placed by the user at the shop" do
       items = oc.items_bought_by_user(user, shop)
+      items.sort_by!(&:id)
```
Comment (mkllnk) [inline spec/models/order_cycle_spec.rb]: This seems completely unrelated to the task. A separate commit could have been good. And did you know about `match_array`?

Comment (luisramos0) [reply spec/models/order_cycle_spec.rb]: ok, moved this into a separate commit.
also used match_array instead, thanks, I didnt know it.
