### PR TITLE
Backoffice: Unit price not displaying when comma is the decimal separator

### LINKED ISSUE #7602: Unit price: when decimal separator is a comma, could not compute unit price
## Description
As an admin, if I want to edit variant (eg. `http://localhost:3000/admin/products/produit-1/variants/52/edit`), and if I use the comma as the decimal separator, unit price could not be computed (field is empty): 
Capture d’écran 2021-05-10 à 17 28 27

This is due to the magic of js:
```js
!isNaN("1.0")
true
!isNaN("1,0")
false
```

See line: https://github.com/openfoodfoundation/openfoodnetwork/blob/17a0063b40f2fb2ecd60cfaaec790cd9e209d6d1/app/assets/javascripts/admin/products/services/unit_prices.js.coffee#L4

## Expected Behavior
As a shop manager using comma as decimal separator, I want to see unit price when I edit a variant.

## Actual Behaviour
As a shop manager using comma as decimal separator, I could not see unit price when I edit a variant.

## Steps to Reproduce
1. Create a product with price `1` (url: `http://localhost:3000/admin/products/new`)
2. Display the list of products and click on the button to edit the associated variant of this new product
3. See that the price is `1,00` and therefor no unit price is displayed

## Severity

bug-s2: a non-critical feature is broken, no workaround

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Closes #7602

Unit price information is not displaying in the backoffice if the price contains comma (`,`) as the decimal separator. This seems to happen if the locale is set to `fr`

#### What should we test?
1. As an admin, change OFN language to `fr` (or others language that use comma as the decimal separator
2. Create a product with price with comma as decimal separator, eg: `1,5` (url: `http://localhost:3000/admin/products/new`)
3. See that the unit price field is well filled
Capture d’écran 2021-05-11 à 15 25 26
4. Display the list of products and click on the button to edit the associated variant of this new product
5. See that the price is `1,50` unit price is well filled.
Capture d’écran 2021-05-11 à 15 24 20

#### Release notes
Backoffice: display unit price if price is a number with decimal as comma separator
Changelog Category: User facing changes

### CODE REVIEW

File: app/assets/javascripts/admin/products/services/unit_prices.js.coffee [hunk 1]
```diff
@@ -1,6 +1,9 @@
 angular.module("admin.products").factory "UnitPrices", (VariantUnitManager, localizeCurrencyFilter) ->
   class UnitPrices
     @displayableUnitPrice: (price, scale, unit_type, unit_value, variant_unit_name) ->
+      decimal_separator = I18n.toCurrency(.1).substring(1,2)
+      if (decimal_separator == ",")
+        price = price.replace(",", ".")
```
Comment (sauloperez) [inline app/assets/javascripts/admin/products/services/unit_prices.js.coffee:6]: IMO this shouldn't be a responsibility of this module and should instead be handled by perhaps `localize_currency.js.coffee` if it's not handled somewhere else already. Duplicating this logic the next time we need to localize a money amount is not an option.

Comment (jibees) [reply app/assets/javascripts/admin/products/services/unit_prices.js.coffee]: Done with `app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee`

File: app/assets/javascripts/admin/products/services/unit_prices.js.coffee [hunk 2]
```diff
@@ -1,6 +1,7 @@
-angular.module("admin.products").factory "UnitPrices", (VariantUnitManager, localizeCurrencyFilter) ->
+angular.module("admin.products").factory "UnitPrices", (VariantUnitManager, localizeCurrencyFilter, unlocalizeCurrencyFilter) ->
   class UnitPrices
     @displayableUnitPrice: (price, scale, unit_type, unit_value, variant_unit_name) ->
+      price = unlocalizeCurrencyFilter(price)
```
[the remark this answers is not in the document]
Comment (jibees) [reply app/assets/javascripts/admin/products/services/unit_prices.js.coffee:4]: It's localized since it has a comma or a point as a decimal separator. So, I think you're right, its more a `unlocalizeFloatFilter` ?

[the remark this answers is not in the document]
Comment (sauloperez) [reply app/assets/javascripts/admin/products/services/unit_prices.js.coffee:4]: But what I don't understand is why we need to unlocalize the price that comes already localized at this point, and why we localize it again on line 6 :exploding_head:

File: app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee [hunk 3]
```diff
@@ -0,0 +1,8 @@
+angular.module("admin.utils").filter "unlocalizeCurrency", ()->
+  # Convert string to number using injected currency configuration.
+  (price) ->
+    # used decimal separator from currency configuration
+    decimal_separator = I18n.toCurrency(.1, {precision: 1, unit: ''}).substring(1,2)
+    if (decimal_separator == ",")
+      price = price.replace(",", ".")
+    return parseFloat(price, 10)
```
Comment (andrewpbrett) [inline app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee:8]: Is this rounding to 10 decimal places? Why not just omit the second parameter?

**Review by andrewpbrett — APPROVED** [review]
This makes sense to me... the naming of that function could potentially be more clear, since it does make it seem like we shouldn't unlocalize the price only to localize it again. We're essentially taking a localized price (which may or may not use `,` as its decimal separator) and converting it to a float that definitely does **not** use `,` as a decimal separator. I don't have a great suggestion for a different method name.

**Comment by jibees** [comment]
@andrewpbrett 
> the naming of that function could potentially be more clear

I agree, but couldn't find better name. I'm open to new suggestion for sure!

File: app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee (hunk 3 above)
Comment (jibees) [reply app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee:8]: I was sure that `parseFloat` accept second parameters but this is only for `parseInt` (and this is a radix parameter)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat

File: app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee [hunk 4]
```diff
@@ -0,0 +1,8 @@
+angular.module("admin.utils").filter "unlocalizeCurrency", ()->
+  # Convert string to number using injected currency configuration.
+  (price) ->
+    # used decimal separator from currency configuration
+    decimal_separator = I18n.toCurrency(.1, {precision: 1, unit: ''}).substring(1,2)
+    if (decimal_separator == ",")
+      price = price.replace(",", ".")
```
Comment (mkllnk) [inline app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee:7]: What if the price is `$1.000.000,00`?

Dr. Evil

Seriously, `parseFloat("1.000.000.00") == 1`.

File: spec/javascripts/unit/admin/products/services/unit_prices_spec.js.coffee [hunk 5]
```diff
@@ -138,3 +138,19 @@ describe "UnitPrices service", ->
       unit_value = 453.6
       expect(UnitPrices.price(price, scale, unit_type, unit_value)).toEqual 1
       expect(UnitPrices.unit(scale, unit_type)).toEqual "lb"
+
+  describe "get unit price when price is a decimal string", ->
+    unit_type = "weight"
+
+    it "with price: '1,0'", ->
+      price = '1,0'
```
Comment (mkllnk) [inline spec/javascripts/unit/admin/products/services/unit_prices_spec.js.coffee:146]: Here's the place to test out the limits of your logic.

File: spec/javascripts/unit/admin/filters/unlocalize_currency_spec.js.coffee [hunk 6]
```diff
@@ -0,0 +1,29 @@
+describe 'convert string to number with configurated currency', ->
+  filter = null
+
+  beforeEach ->
+    module 'ofn.admin'
+    inject ($filter) ->
+      filter = $filter('unlocalizeCurrency')
+
+  describe "with point as decimal separator for I18n service", ->
```
Comment (mkllnk) [inline spec/javascripts/unit/admin/filters/unlocalize_currency_spec.js.coffee:9]: This is a great unit test. :+1:

**Review by mkllnk — CHANGES_REQUESTED** [review]
Nice work. I wish there was a better way to get the number value of the price...

File: app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee (hunk 4 above)
Comment (jibees) [reply app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee:7]: Is this case really possible? I mean, can a point (`.`) be a separator of thousands?
Both cases that I can test:
Capture d’écran 2021-05-25 à 09 12 01
Capture d’écran 2021-05-25 à 09 12 28

Comment (jibees) [reply app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee:13]: Anyway, I've handled many cases in my last commit: dd47430f1910530575a1fb8b5566777dee75755f
I think we now cover a large set of cases.

Comment (mkllnk) [reply app/assets/javascripts/admin/utils/filters/unlocalize_currency.js.coffee:13]: > can a point (.) be a separator of thousands?

Yes. Germans use the dot for thousands: https://de.wikipedia.org/wiki/Million

**Review by mkllnk — APPROVED** [review]
Nice tests. :-)

**Comment by filipefurtad0** [comment]
Hey @jibees ,

This bug is a nice catch :muscle: 

I'm having some trouble to get commas to work as a decimal separator in staging environments... But the bug seems to be observable nevertheless:

in staging-AU, before staging this PR:

Peek 2021-05-27 11-09


**After staging your PR** (configurations, left - new product creation, right):

**Using EN locale**

- using `,` -> decimal, and `.` -> thousand separators, respectively

Peek 2021-05-27 11-11

- using `.` -> decimal, and `,` -> thousand separators, respectively

Peek 2021-05-27 11-12

I'm wondering if the configuration changes should not have an effect (?).

Anyway, we can see in the videos that the **commas are ignored, and unit prices render** anyway, despite adding several of them.

**Using FR locale**

- using `,` -> decimal, and `.` -> thousand separators, respectively

Peek 2021-05-27 11-26

This is reflected correctly when editing the product:

image


- using `.` -> decimal, and `,` -> thousand separators, respectively

Peek 2021-05-27 11-25

This is reflected correctly when editing the product (despite having set `.` as a decimal separator)

image


We can see that after this PR commas are accepted as decimal separator, and unit prices render correctly, both when creating and editing a product. Ready to go.

PS: we have a similar issue with the `Quantity` field on `/admin/products/new`. It seems that with locale FR values after the `,` are ignored:

Peek 2021-05-27 12-00

**Comment by jibees** [comment]
> I'm wondering if the configuration changes should not have an effect (?).

I didn't not see any changes, since the lib we use doesn't import these configuration.

**Comment by jibees** [comment]
> This deserves an issue I guess.

Yes, you're right



_(noooo I don't want to deal with decimal separator anymooooore 😱 )_

**Review by sauloperez — APPROVED** [review]
