### PR TITLE
Fix Products search timing out when creating a new subscription

### LINKED ISSUE #14015: Fix Products search timing out when creating a new subscription
## Description

A power user reported that they were unable to create a new subscription, as searching for a product led to the request timing out. I've tested and been able to reproduce for them as the hub, but testing with other hubs does not show the same behaviour.

## Expected Behavior

Searching for a product should return all products the hub has access to 

## Actual Behaviour

The loading spinner sticks, no products are returned, and eventually there's a 504 error in the console. As a result, the subscription cannot be created

## Steps to Reproduce

1. On UK, for enterprise id 160/Tamar Valley Food Hubs (renamed TV Food Hub), create a new subscription by entering customer details/shipping method etc
2. From the products screen, search for an available product (e.g. carrots)
3. Observe loading spinner in search box and overlay at top of screen
4. Wait two minutes until request times out and 504 error observed in console

Problem is the request: `https://openfoodnetwork.org.uk/admin/variants/search.json?q=carrots&distributor_id=160&eligible_for_subscriptions=true&include_out_of_stock=&_=1773139190911`

## Animated Gif/Screenshot

Image

## Workaround

No workaround - subscriptions cannot be created at all

## Severity

bug-s2: a non-critical feature is broken, no workaround
The hub is a longterm power user so is understanding, but right now they can't create subscriptions whatsoever

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Can't get into bugsnag using the login details in Vaultwarden any more (code being sent to an inbox I don't have access to) so I can't investigate further unfortunately. Previously we've had issues with this hub around lots of enterprise permissions slowing everything down, and I'm wondering if it might be something to do with that. I've asked them to remove any outdated permissions and update me if that helps

### PR DESCRIPTION
**Pull request by chahmedejaz**
## What? Why?

- Closes #14015

This PR fixes a performance issue caused by large `IN (...)` queries generated from `.pluck`-based implementations.

Previously, methods in `VariantsList` used `.pluck` to load IDs into Ruby arrays, which were then passed back into queries. For distributors with many permitted producers or variants, this resulted in very large `IN` clauses, leading to slow queries and increased memory usage.

### Key Changes:
- Replaced `.pluck` with `.select` to keep queries as ActiveRecord relations instead of materializing large arrays in memory.
- Refactored `permitted_producer_ids` to return a relation and leverage SQL composition (`OR`) instead of building large Ruby arrays.
- Updated `outgoing_exchange_variant_ids` to return a relation, avoiding large `IN` lists.

### Result:
- Avoids generating massive `IN` queries
- Reduces memory usage in Ruby
- Improves database performance by delegating work to SQL instead of Ruby
- Makes queries more scalable for large datasets

---

## What should we test?

- As mentioned in the issue and its comments
- Ideally, we should test it on the instance that has a huge number of variants in its outgoing exchange of all order cycles combined

---

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

---

### CODE REVIEW

File: engines/order_management/app/services/order_management/subscriptions/variants_list.rb [hunk 1]
```diff
@@ -30,17 +30,19 @@ def self.permitted_producer_ids(distributor)
...
         # Append to the potentially gigantic array instead of using union, which creates a new array
         # The db IN statement won't care if there's a duplicate.
-        other_permitted_producer_ids << distributor.id
+        Enterprise.where(id: distributor.id)
+          .select(:id)
+          .or(Enterprise.where(id: other_permitted_producer_ids))
       end
 
       def self.outgoing_exchange_variant_ids(distributor)
-        ExchangeVariant.select("DISTINCT exchange_variants.variant_id").joins(:exchange)
```
Comment (chahmedejaz) [inline engines/order_management/app/services/order_management/subscriptions/variants_list.rb:41]: We can safely omit `DISTINCT` here since this is used as a subquery within an `IN` clause, where duplicate values do not affect the result. Plus, this would also optimize query performance.

File: engines/order_management/app/services/order_management/subscriptions/variants_list.rb [hunk 2]
```diff
@@ -30,17 +30,19 @@ def self.permitted_producer_ids(distributor)
         other_permitted_producer_ids = EnterpriseRelationship.joins(:parent)
           .permitting(distributor.id).with_permission(:add_to_order_cycle)
           .merge(Enterprise.is_primary_producer)
-          .pluck(:parent_id)
+          .select(:parent_id)
 
         # Append to the potentially gigantic array instead of using union, which creates a new array
         # The db IN statement won't care if there's a duplicate.
```
Comment (rioug) [inline engines/order_management/app/services/order_management/subscriptions/variants_list.rb]: Can you remove the comment ? It's not describing the new code :)

File: engines/order_management/app/services/order_management/subscriptions/variants_list.rb (hunk 1 above)
Comment (rioug) [reply engines/order_management/app/services/order_management/subscriptions/variants_list.rb:41]: I think it's worth adding this comment in the code to prevent someone potentially adding "DISTINCT" in the future.

**Review by rioug — CHANGES_REQUESTED** [review]
Looks good ! but I think we should improve the comments.

File: engines/order_management/app/services/order_management/subscriptions/variants_list.rb (hunk 2 above)
Comment (chahmedejaz) [reply engines/order_management/app/services/order_management/subscriptions/variants_list.rb]: I thought I removed this, but I ignored it in the final push 😅

**Comment by chahmedejaz** [comment]
Thanks @rioug for the feedback, I've addressed it here: https://github.com/openfoodfoundation/openfoodnetwork/pull/14091/changes/fc123b38b450b885725a20b0b1ea8c4f9f581fb3

**Comment by chahmedejaz** [comment]
Hi @mkllnk — Yes, I verified this on prod UK with an affected enterprise, and the performance has improved significantly.

The main issue was the large `IN` clause generated when an enterprise had thousands of variants in its outgoing exchange. For example in the case of affected enterprise, this resulted in very long SQL queries (~41k characters), which increased parsing/planning time and degraded execution performance.

With this change, we avoid building such large `IN` clauses, reducing the query size to under ~1k characters and improving overall query efficiency.

**Comment by chahmedejaz** [comment]
Just did the benchmarks analysis out of curiosity:

**Time taken in minutes (_with current implementation_):**
image

**Time taken in seconds (_with the proposed fix_):**
image

**Comment by mkllnk** [comment]
Nice! That's great.

**Comment by AMEA-LYON** [comment]
Hi everyone, 
tested OK, perfs are really good on TV Food Hub
🚀 Ready to Go !

FYI : they were also good when testing on the master branch...

**Comment by chahmedejaz** [comment]
Thanks @AMEA-LYON - I think on staging we don't have enough data yet to reproduce the timeout issue. As it's working as expected as well, it's good then 👍🏻
Merging 🙏🏻
