### PR TITLE
[BUU] Fix Messy flash notifications on new products page

### LINKED ISSUE #12596: [BUU] Messy flash notifications on new products page
## Description

Discovered when working on #12567.

The error message about missing payment and shipping methods is displayed twice on top of itself. This requires to click 'Dismiss' twice. If an additional message is displayed (e.g. the 'changes saved' confirmation) only one of those two identical messages is shifted to the side which messes up the screen.

## Expected Behavior

- The message should be displayed only once.
- Any additional messages should be displayed in a tidy manner.

## Actual Behaviour

- The message is displayed twice.
- Any additional messages mess up the screen.

## Steps to Reproduce

1. Set up an active order cycle with just one payment or shipping method.
2. Delete this last payment or shipping method on page `/admin/shipping_methods` or `/admin/payment_methods`.
3. Go to `/admin/products` (with admin v3 feature toggle active)
4. Make changes to a product.
5. Click 'Save changes'.

## Animated Gif/Screenshot

image

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12596
- If the distributors have active order cycles but haven't set up shipping or payment methods, then a warning is displayed on the new screen.
- This warning is displayed each time the user visits any screen or switches tabs/pages.
- This PR fixes this such that the warning is displayed only once per user session.

#### What should we test?

- Have distributors that don't have payment or shipping methods setup
- Have order cycles opened for them
- Once you login, on the new admin screen, you should be able to see the order cycle warning
- Refresh the page, switch the tab, or navigate to another page, the order cycle warning should not be displayed anymore

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/controllers/spree/admin/base_controller.rb [hunk 1]
```diff
@@ -81,6 +84,12 @@ def check_json_authenticity
 
       private
 
+      def page_load_request?
+        return false if request.format.include?('turbo')
+
+        html_request?
+      end
+
       def html_request?
```
Comment (chahmedejaz) [inline app/controllers/spree/admin/base_controller.rb:93]: Keeping this helper because there might be some cases where we would want to check for requests that display data (HTML, turbo, etc) rather than serve data (JSON, XML, etc).
Moreover, it's being used here:

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/controllers/admin/customers_controller.rb#L8

File: app/controllers/spree/admin/base_controller.rb [hunk 2]
```diff
@@ -19,15 +19,18 @@ class BaseController < ApplicationController
...
       def warn_invalid_order_cycles
-        return if flash[:notice].present?
+        return if session[:displayed_order_cycle_warning]
 
         warning = OrderCycles::WarningService.new(spree_current_user).call
-        flash[:notice] = warning if warning.present?
+        return if warning.blank?
+
+        flash.now[:notice] = warning
+        session[:displayed_order_cycle_warning] = true
```
Comment (mkllnk) [inline app/controllers/spree/admin/base_controller.rb:33]: Does this mean that we display the message only once?

Comment (chahmedejaz) [reply app/controllers/spree/admin/base_controller.rb:33]: Yes, only once during the user's login session. If he re-logins then the warning will again pop up.

Comment (chahmedejaz) [reply app/controllers/spree/admin/base_controller.rb:33]: Ref: https://openfoodnetwork.slack.com/archives/C01CXQNJ1J6/p1723641747029789?thread_ts=1723641747.029789&cid=C01CXQNJ1J6

File: app/controllers/spree/admin/base_controller.rb [hunk 3]
```diff
@@ -19,15 +19,18 @@ class BaseController < ApplicationController
 
       before_action :authorize_admin
       before_action :set_locale
-      before_action :warn_invalid_order_cycles, if: :html_request?
+      before_action :warn_invalid_order_cycles, if: :page_load_request?
 
       # Warn the user when they have an active order cycle with hubs that are not ready
       # for checkout (ie. does not have valid shipping and payment methods).
       def warn_invalid_order_cycles
-        return if flash[:notice].present?
```
Comment (dacook) [inline app/controllers/spree/admin/base_controller.rb:27]: I think we should still keep this condition. It ensure we don't overwrite a more specific notice.

File: app/controllers/spree/admin/base_controller.rb [hunk 4]
```diff
@@ -81,6 +84,12 @@ def check_json_authenticity
 
       private
 
+      def page_load_request?
+        return false if request.format.include?('turbo')
+
+        html_request?
+      end
```
Comment (dacook) [inline app/controllers/spree/admin/base_controller.rb:91]: I vaguely remember talking about this before.. I guess we didn't merge it last time?

**Review by dacook — APPROVED** [review]
Great!
There's two changes here:

1. Don't check for the warning when making a partial page load (turbo).

This is a good safeguard to avoid doubling it up unnecessarily. But the next change means it wouldn't double anyway...

2. The session remembers if you've viewed the warning since last login. 

Hmm, how long do sessions last? Apparently we have no limit set, as long as the browser session remains open (which I suspect could be a long time if people leave their computer on).
Screenshot 2024-08-15 at 12 19 25 pm

So it's possible the reminder won't be persistent enough. It might be safer to wait until the user manually dismisses it. But this wasn't specified in the issue, and besides, I think people will be so glad not to see the message!


👍 Ok, thumbs up!

File: app/controllers/spree/admin/base_controller.rb (hunk 3 above)
Comment (dacook) [reply app/controllers/spree/admin/base_controller.rb:27]: change requested.

**Review by dacook — CHANGES_REQUESTED** [review]

File: app/controllers/spree/admin/base_controller.rb (hunk 3 above)
Comment (chahmedejaz) [reply app/controllers/spree/admin/base_controller.rb:27]: I've addressed this change, however, I tested the scenario where there's a specific flash notice in controller action (which is the case in our app right now), then rails automatically display that and doesn't get overridden by this method because its being called before calling any action (_in before_action callback_). And every other notices are set in controller actions. So, that controller message would get the priority over this.

In future we may have a case where we would want the same scenario (setting message in before_action), then I think our base controller message would get the priority.

This check was present here because before `flash[:notice]` was being used, not it's `flash.now[:notice]`. This notice was not discarded after being displayed before and we still had that notice for the very next request. We saw that if we still had it, then no need to recalculate the notice.

Just in case I'm missing something here, pushing the requested change.
https://github.com/openfoodfoundation/openfoodnetwork/pull/12778/commits/46e54f48c91dd8863dec1bacfb0f9664f94ce32d
Thanks

File: app/controllers/spree/admin/base_controller.rb (hunk 4 above)
Comment (chahmedejaz) [reply app/controllers/spree/admin/base_controller.rb:91]: Yes, I took it from here: https://github.com/openfoodfoundation/openfoodnetwork/pull/12672#pullrequestreview-2208870777 😅

**Comment by chahmedejaz** [comment]
> The session remembers if you've viewed the warning since last login.
Hmm, how long do sessions last? Apparently we have no limit set, as long as the browser session remains open (which I suspect could be a long time if people leave their computer on).

Thanks @dacook - Yes, that's concerning. I'm not sure if we should put a limit on session, but looking at from security standpoint, it seems like we should. But in case of UX, I don't think it would be a good idea to have user login much often 😅 

>  It might be safer to wait until the user manually dismisses it. 
Yes, I thought the same. But then I looked into the code, I don't think we have any behavior like this as of now. I doesn't look hard enough, by using user's local storage, cookies and some checks. It seems like a doable task. We should have this behavior for important notices, maybe some feature for the future? Thanks.

**Review by mkllnk — APPROVED** [review]
Nice!

I didn't know about the Slack conversation. That's all good then. We may implement something more clever where the user can dismiss the modal and that's stored. But for now this is a good improvement.

**Review by dacook — APPROVED** [review]
Great, ready to test.

File: app/controllers/spree/admin/base_controller.rb (hunk 3 above)
Comment (dacook) [reply app/controllers/spree/admin/base_controller.rb:27]: Ah ha, thanks for explaining. So this case should never occur.
Oh well, it doesn't hurt to be defensive here.

**Comment by dacook** [comment]
I think this is pretty important for the BUU rollout, so I'm testing it now for inclusion.

Staged on uk_staging. I can see the notice on first load:
Screenshot 2024-08-16 at 10 18 48 am

✅ On subsequent load, in any tab, it no longer appears.
✅ After logout > login > Admin: it appears again.

**Comment by chahmedejaz** [comment]
Thank you so much @dacook ♥️🎉
