### PR TITLE
Remove duplicative tax line on invoices

### LINKED ISSUE #7890: Line taxes listed on order confirmation and invoices
## Description

Since the adjustments work and latest release,  taxes are being listed individually on order confirmations and on invoices.  It is happening on both invoice templates.  It is happening for instances where tax is included and where tax is excluded from prices. 

## Expected Behavior

The order confirmation and the invoice should show totals of taxes (by tax category?)  and not each individual tax amount associated with an item.

## Actual Behaviour

Each individual tax amount  -  for each tax category -  is showing on the invoice and the order confirmation,   making for lengthy invoices.   For example:  a customer buys 50 taxable items -  the invoice shows 50 lines of tax amoungs.    In instances where two different tax categories are applicable (this would be in BC, Canada for example,  and I think many of the US states) the invoice would show two lines of tax for every item ordered. 

Example below.

## Steps to Reproduce

1.Place an order for more than one taxable item
2.See the invoice and the order confirmation
3. Swtich invoice templates -  and see its the same.
4.

## Workaround

No woraround

## Your Environment

We've tested in Chrome,  and in Firefox
[invoice-R150736087.pdf july 7.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/6777535/invoice-R150736087.pdf.july.7.pdf)

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### LINKED ISSUE #7894: Incorrect display of shopping tax on invoices and in order confirmations
## Description
On invoices (first screenshot) the shipping tax (0,13 €) is listed above the line, but it is already included in the shipping fee (2,00 €). So the total amount doesn't match all the numbers above the line. This is really confusing for customers and financial controlling. 
Same applies to the order confirmation in emails and the browser (second screenshot) as well as to order cancellation emails. 

## Expected Behavior
The shipping tax line should not be displayed seperately above the line, because the tax is already included in the shipping fee. 

## Actual Behaviour
There is a separate shipping tax line displayed above the line.

## Steps to Reproduce
1. Place an order which includes a shipping fee and a shipping tax
2. Look at the order confirmation screen and order confirmation email
3. Look at the invoice
4. Cancel the order
5. Look at the order cancelllation email

## Animated Gif/Screenshot
grafik
grafik(1)

## Workaround
not available

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v3.8.3
* Browser name and version: Firefox 89.0.2
* Operating System and version (desktop or mobile): Desktop Windows 8

## Possible Fix
The easiest solution would be to remove the separate shipping tax line.

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #7890 
Closes #7894 

<s>This groups tax adjustments with the same originator (a Spree::TaxRate) together at checkout and on the invoice. 

I just realized that this will create a new adjustment any time the invoice is generated or the page is viewed? We're doing something similar with the admin and handling adjustments, and they're not saved to the database (or, at least not immediately), but I'm not sure that this is the right approach.</s>

This now omits the tax adjustments line item if `:tax_rate` is passed in to the `checkout_adjustments_for` method in the `exclude` array, and updates all places where we call that method and passes `:tax_rate`, which is to say that it always omits them. If we confirm that this is the desired behavior we can simplify the PR quite a bit and just always omit them.

#### What should we test?

See issue

#### Release notes

Fixed a bug where taxes on taxes on enterprise fees were showing up separately on invoices, making the totals appear incorrect.

Changelog Category: User facing changes

### CODE REVIEW

**Comment by andrewpbrett** [comment]
I still need to check several things, but putting this out there as a first draft of a fix.

File: app/helpers/checkout_helper.rb [hunk 1]
```diff
@@ -40,6 +40,24 @@ def checkout_adjustments_for(order, opts = {})
       )
     end
 
+    tax_rate_adjustments = adjustments.select { |a|
+      a.originator_type == "Spree::TaxRate" && a.adjustable_type == "Spree::Adjustment"
+    }
+    adjustments.reject! { |a|
+      a.originator_type == "Spree::TaxRate" && a.adjustable_type == "Spree::Adjustment"
+    }
```
Comment (mkllnk) [inline app/helpers/checkout_helper.rb:48]: Would this be easier?
```suggestion
    tax_rate_adjustments, adjustments = adjustments.partition { |a|
      a.originator_type == "Spree::TaxRate" && a.adjustable_type == "Spree::Adjustment"
    }
```


And if we defined a new method on adjustments:

```rb
    tax_rate_adjustments, adjustments = adjustments.partition(&:adjustment_tax?)
```

**Review by mkllnk — APPROVED** [review]
I think that this is all happening in memory and not changing anything in the database, which is great. It's just a bit confusing that we are changing adjustments here instead of converting adjustments into display items for the invoice. Our of scope here.

File: app/helpers/checkout_helper.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/helpers/checkout_helper.rb]: I do like that suggestion and committed it. I'm slightly wary of having a new method on adjustments since... well, I guess because I don't feel familiar with this part of the code to know for certain that the conditional we use here is what you'd want in all cases where you might ask "is this a tax adjustment". Which is sort of like saying I don't have a sense of what the right name for it would be, so for now I'm more inclined to leave it as the explicit conditional until I do :)

**Review by mkllnk — APPROVED** [review]
I agree. Matt will be the right person to confirm that approach. There are also many other places in this method that don't use custom methods. At least we got rid of the code duplication here.

File: app/helpers/checkout_helper.rb [hunk 2]
```diff
@@ -40,6 +40,21 @@ def checkout_adjustments_for(order, opts = {})
       )
     end
 
+    tax_rate_adjustments, adjustments = adjustments.partition { |a|
+      a.originator_type == "Spree::TaxRate" && a.adjustable_type == "Spree::Adjustment"
```
Comment (Matt-Yorkley) [inline app/helpers/checkout_helper.rb:44]: This will only match taxes on fees and not taxes on line items or shipments. Is that intended?

If you want it on all tax adjustments you can do
```diff
-- a.originator_type == "Spree::TaxRate" && a.adjustable_type == "Spree::Adjustment"
++ a.originator_type == "Spree::TaxRate"
```

File: spec/helpers/checkout_helper_spec.rb [hunk 3]
```diff
@@ -60,6 +60,37 @@
...
+        create(:adjustment,
+          originator: tax_rate,
+          adjustable: fee_adjustment,
+          order: order
+        )
+      }
+      let!(:line_item_tax_adjustment) {
+        create(:adjustment,
+          originator: tax_rate,
+          adjustable: line_item_fee_adjustment,
```
Comment (Matt-Yorkley) [inline spec/helpers/checkout_helper_spec.rb:79]: On a line item tax adjustment the adjustable would be the line item itself.

**Comment by Matt-Yorkley** [comment]
Looking through the related issues again I'm wondering if what we want to do is not display any of those adjustments at all (instead of grouping them)..?

File: app/helpers/checkout_helper.rb (hunk 2 above)
Comment (andrewpbrett) [reply app/helpers/checkout_helper.rb]: Yep, I think that's right - based on the issue, it seemed like the problem was specifically with taxes on fees showing up individually. But it makes more sense that we would want to group all adjustments related to a particular tax together. b5881c2ec88ed4523fc42673ef8a289afd27cab3

File: spec/helpers/checkout_helper_spec.rb (hunk 3 above)
Comment (andrewpbrett) [reply spec/helpers/checkout_helper_spec.rb:79]: I think that's just a bad choice of variable name on my part; what I was trying to create was a tax adjustment on the enterprise fee... I think this setup mimics what I was seeing on the invoice from the issue. It had an adjustment with a taxrate originator and an adjustable of the enterprise fee adjustment.

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by andrewpbrett** [comment]
I took a second look at this based on @Matt-Yorkley's comment https://github.com/openfoodfoundation/openfoodnetwork/issues/7894#issuecomment-877391160 and I agree that it makes sense to just completely omit the line item for taxes in that invoice (as opposed to grouping them). In @filipefurtad0's test invoice for Red Berries Hub, for example, the items above the line sum to $175.29, which is the total **including** tax, but then the first number below the line is "Total excluding tax: $173.30" and then we itemize the total tax **again** and present the grand total below that. 

This will also fix https://github.com/openfoodfoundation/openfoodnetwork/issues/7894 if I'm not mistaken. 

To omit the tax line item, I added logic to the `checkout_adjustments_for` method to exclude tax_rate adjustments, if the caller passes in `:tax_rate` to the array of excluded adjustments. The `checkout_adjustments_for` method is used in seven different places in the code. I took a look at each and it seems like in each one, we actually don't want to display the tax at all since we display it separately nearby.

Those seven places are:
- Checkout
- Invoices (counts for 2)
- app/views/spree/admin/orders/ticket.html.haml - I think this is print tickets?
- Order mailer
- Viewing a completed order (counts for 2)

So if we confirm that all of these cases shouldn't in fact be showing the tax rate adjustments, we can essentially revert the changes in 743def9a768ac75fb234c9fdd70382d34c5f1046 and just keep:

https://github.com/openfoodfoundation/openfoodnetwork/blob/571661c8d4512760c269166615ae47d6137434f8/app/helpers/checkout_helper.rb#L31-L33

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

I see you've changed the notes on this PR, but I can only verify that it groups tax amounts and does not omit them. Maybe I'm missing something... I've staged `build #10 of pull-request-7892` to staging-UK and -FR.

I've setup different items, enterprise fees and a shipping method, associating them with the same tax rate in both staging-UK (added tax) and -FR (inclusive tax).

I've checked the places you mentioned - thanks for mentioning those:

- Checkout, Invoices, order confirmation (email) and order confirmation; also had a look at the `/cart` and `/checkout `pages.

I felt the best way to track down changes would be replicate the order and calculations on a calculus sheet. I've attached it to this comment (*odt and *pdf):

**[testing_tax_changes_7892.pdf](https://github.com/openfoodfoundation/openfoodnetwork/files/6797136/testing_tax_changes_7892.pdf)
[testing_tax_changes_S2_7892.ods](https://github.com/openfoodfoundation/openfoodnetwork/files/6797137/testing_tax_changes_S2_7892.ods)
**

**Summary**
- this PR groups tax amounts (both included and added taxes) resulting from enterprise and shipping method fees in one entry only; it thus closes #7890

**Invoices with Added tax (staging-UK):**

image

- this PR does not remove the tax amount mentioned in #7894; in the test results it can be seen, that not only the shipping method tax amount is still displayed as the values resulting from taxes on enterprise fees appear as well

**Invoices with Inclusive tax (staging-FR):**
image

Should we merge? And tackle #7894 in a separate issue?


PS: Out of scope of this PR, perhaps for another issue:

I think the Adjustments section should probably display the inclusive tax amount (when taxes are set in that way, as in staging-FR). So, if a shipment of 2 Eur has 13% inclusive tax, I think 0.23 € should appear here, right?

image

**Review by mkllnk — APPROVED** [review]
The code looks good to me. But I'm not completely following the requirements, where to display what. I hope that Matt or Filipe can confirm that. :+1:

**Comment by RachL** [comment]
I agree we can merge this and tackle #7894 in a separate issue :thumbsup:

File: app/helpers/checkout_helper.rb [hunk 4]
```diff
@@ -10,8 +10,8 @@ def checkout_adjustments_for(order, opts = {})
 
     adjustments = order.all_adjustments.eligible.to_a
 
-    # Remove empty tax adjustments and (optionally) shipping fees
-    adjustments.reject! { |a| a.originator_type == 'Spree::TaxRate' && a.amount == 0 }
+    # Remove tax adjustments and (optionally) shipping fees
+    adjustments.reject! { |a| a.originator_type == 'Spree::TaxRate' }
```
Comment (andrewpbrett) [inline app/helpers/checkout_helper.rb:14]: I believe this is in fact covered by the test :)

**Comment by andrewpbrett** [comment]
I did a check on UK and FR staging and confirmed that the invoices now add up correctly and do not have the separate line item for the tax that was throwing off the calculations, so this should now definitely fix #7894 as well. I did a checkout on UK and I believe it's also correct.

I'm reasonably confident that we want to exclude this line item in all cases so I squashed the commits down to simplify the PR.

**Comment by filipefurtad0** [comment]
Alright @andrewpbrett 

We're good here now:
https://docs.google.com/document/d/1ObTCXW1ZV0E2pPZRXCmk7YqLL8S1gwxLb1QGYymjkgc/edit

Order confirmations (email, and customer) and Invoices (both types) now add-up correctly the tax values, for the respective tax rates, appearing only in the Totals section; This closes both #7890 and #7894 .   

Two points which maybe could be improved, and out of scope of this PR:
i) as mentioned earlier, on "included-tax instances" the tax on Shipment is not displayed under Adjustments (Includes Tax column)
ii) for instances with "added-tax instances", on the Alternative Invoice, I think the ordering of the totals could be changed to improve readability:

image

Since for these instances there is an added parcel to the item `Total (Excl. Tax)`, maybe `Total` should be the last line, as it already is the case with the "regular" invoice? 

I think this PR is good to go, but more than happy to hear any additional thoughts on this @openfoodfoundation/train-drivers-product-owners @tschumilas and @drummer83

**Comment by RachL** [comment]
If the PR answer the requirements of the original issue let's merge it. I'm guessing any discussion o invoices templates needs to be move to the wishlist? To be honest I don't understand why we have 2 templates for example :D

**Comment by filipefurtad0** [comment]
Good point @RachL , thanks.

I think i) could be considered a bug (not introduced by this PR) while ii) is a nice to have, and could be discussed elsewhere.

**Comment by RachL** [comment]
I think i) was designed this way in the template. But I could be wrong. This is why I don't see it as a bug :shrug:

**Comment by andrewpbrett** [comment]
I noticed ii) as well, good catch @filipefurtad0. I'd be in favor of getting it into an issue as a potential papercut. 

I also don't know the story of why there are two invoice templates 🙈

**Comment by drummer83** [comment]
Uff, this one can really give you a headache!

Regarding i) and ii) I would love to see those listed as issues. In ii) my proposed order would be
- Total (excl. tax)
- Total tax (x %)
- Total

Solving #7890 and #7894 I assume that the Google Doc from @filipefurtad0 is the source of truth. 

Remarks for "Staging UK - added tax": 
- Order edit (Admin): The numbers under "Line item adjustments" don't make sense to me. This might be just an example, so just to doublecheck ...
- Alternative invoice makes no sense for "added tax" due to the headline saying "incl. tax" --> this is propably well known and not a problem

Remarks for "Staging FR - included tax":
- Alternative invoice: The tax rate should be displayed as well but might be out of scope --> create an issue no. iii)?
- **Regular invoice: The numbers in column GST are not correct (they do not correspond to 13 % tax)**
- Regular invoice: GST should be displayed for shipping as well --> could be combined with issue no. iii)
- Order edit (Admin): The numbers under "Line item adjustments" don't make sense to me. Same as in "Staging UK - addad tax"

**Comment by filipefurtad0** [comment]
I realize I was not clear on point i), where actually the `Included Tax` column in the Adjustments tab (order edit, BO) was referred to:

image

Clarified through DM with @RachL , thanks again - also for your feedback @andrewpbrett . Issues up next :+1:

**Comment by filipefurtad0** [comment]
Hey @drummer83,

Thanks for taking the time for reviewing the testing notes and pinging me! I completely missed your commend. Replying:

**Remarks for "Staging UK - added tax":**

1)

> The numbers under "Line item adjustments" 

Order edit (Admin):
  - `packing fee by distributor Mackerel and Co.:` - these are enterprise fees, which in this case were set as
      5 Eur per item (2x items) = 10 Eur
  - `Ontario - HST 13.0%:` - these lines display the tax value of each line item. For example, first line item:
       2 x 6 (price per item) * 0.13 = 1.56 

2)
>  Alternative invoice makes no sense for "added tax" due to the headline saying "incl. tax" --> this is probably well known and not a problem

I agree this is not clear.. Solution would be simply to remove the `Incl. Tax` header, right?

**Remarks for "Staging FR - included tax"**

3)
> Alternative invoice: The tax rate should be displayed as well but might be out of scope --> create an issue no. iii)?

 - Agreed that shipping lacks tax rate :+1: 

4)
> Regular invoice: The numbers in column GST are not correct (they do not correspond to 13 % tax)

Great catch Konrad - this is issue #5591 - the values on the GST column are relating only to the line item price _without the respective enterprise fees_. The sum below already includes enterprise fees, and for that reason, the sum of that column does not match the GST total below - agreed, this is not correct. 

5)
> Regular invoice: GST should be displayed for shipping as well --> could be combined with issue no. iii)

GST is missing on the alternative invoice for shipping, but not on the regular one... right? But I would argue that we would not need `Qty` = 1 on shipping...

6)
 > Order edit (Admin): The numbers under "Line item adjustments" don't make sense to me. Same as in "Staging UK - added tax"

Same as 1).


**Summary**

5) I think #5591 is indeed not closed, reopening. 

On the remaining issues: there seems to be consensus around issues i) and ii) mentioned in the previous comment. A third issue (wish-list item, not a bug) would be point 3) / iii) displaying the shipping tax on alternative invoicing (which actually relates to issue i). 

Does that sum it up?

**Comment by drummer83** [comment]
Thanks for checking my comment, @filipefurtad0! Very good summary!

1. Thanks for explaining! So the numbers are correct, but the order of the line item adjustments seems to be upside down. That's why I couldn't replicate the numbers. --> I might open a separate issue for this.
2. This is a Transifex issue. --> No action required.
3. --> Create issue no. iii)
4. --> Issue #5591
5. No! The alternative invoice doesn't have a GST (tax amount) column and it hasn't been requested so far. The regular invoice has column GST but the value for shipping is missing, see screenshot below. --> Inlude in issue no. iii)
6. See 1.

grafik

**Comment by filipefurtad0** [comment]
Thanks again for feedback and clarifying point 5 @drummer83! :raised_hands: 

@openfoodfoundation/train-drivers-product-owners 
I've created an epic to group these issues as I feel these might need to be considered together for prioritization/addressing. Please feel free to change severity accordingly :+1:
