### PR TITLE
Embedded response headers

### LINKED ISSUE #2382: Embedded shops aren't working when you go to checkout
## Description
I'm able to embed my shop into my own website. However, when i try to place an order in the embedded shop I can't get to the 'edit my cart' or 'checkout' pages. 

## Expected Behavior
I should be able to checkout in the embedded shop

## Actual Behavior
I see a blank screen when i try to checkout in an embedded shop. 

## Steps to Reproduce
1. Go to an embedded shop. here's an example - https://openfoodnetwork.org/user-guide/advanced-features/demo-embedded-shop/
2. Put an item in your cart
3. Click edit your cart or checkout
4. You'll see a blank screen- unable to checkout.

## Animated Gif/Screenshot
https://www.useloom.com/share/77734df7480e41f19708df787942bfcc

## Context
I'm trying to have a functional embedded shop. 

## Severity
S2

## Your Environment
* Version used: 1.16
* Browser name and version: Chrome, PC.

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #2382.

Issues with checking out whilst using embedded shopfronts. The initial page shows correctly but then the response headers cause the page to be blocked when moving to cart of checkout. Possibly due to not including the entire whitelist in the response headers since #2026.

#### What should we test?

Embedded  shopfronts work and can go to checkout.

#### Release notes

Issues with moving to the checkout page when using embedded shopfronts should be fixed. #2382

### CODE REVIEW

**Comment by myriamboure** [comment]
Ok this one then needs to be merged before we release or we'll have issues with all existing embedded shops, right? Ping @sauloperez if you review quickly and stage today we can test and that's the last thing I think we need to include before we can release...

File: app/services/embedded_page_service.rb [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+
+  def set_embedded_layout
+    return unless @session[:embedded_shopfront]
+    @use_embedded_layout = true
+  end
+
+  def embedding_enabled?
+    Spree::Config[:enable_embedded_shopfronts]
+  end
+end
```
Comment (sauloperez) [inline app/services/embedded_page_service.rb]: I'm missing unit tests for this whole class 🙈

File: app/services/embedded_page_service.rb [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+
+    process_embedded_request
+    set_response_headers
+    set_embedded_layout
+  end
+
+  private
+
+  def embeddable?
+    return true if current_referer == @request.host
```
Comment (sauloperez) [inline app/services/embedded_page_service.rb]: things are more maintainable and easier to change in the future if we use `attr_reader` for the ivars.

Comment (Matt-Yorkley) [reply app/services/embedded_page_service.rb]: I'm not sure what you want in `attr_reader`? 

The request object is passed in to the class and altered in various places, but doesn't need to be explicitly read from outside of the class. It needs to be available to the various methods internally but it doesn't need to be readable...

File: app/services/embedded_page_service.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply app/services/embedded_page_service.rb]: Ah, in my haste to fix the urgent s2 I forgot to spec the new service object and incurred the wrath of the monkey-face emoji... 

I've added specs now. :+1:

**Comment by myriamboure** [comment]
Cool that you staged and tested @Matt-Yorkley ! Do you have some testing notes just to know which cases you tested? We have some processes around testing to have some peer review on them if needed (see wiki) :-) Is it still staged on UK? If yes @RachL can have a look as well if needed (you will need access to global wordpress to test with the demo shop Rachel we talk in PM). If you think you tested all the cases and it works and we don't need to stage again then tell us :)

File: app/services/embedded_page_service.rb (hunk 2 above)
Comment (sauloperez) [reply app/services/embedded_page_service.rb]: My point is to use private reader methods instead of the raw ivars. That brings the usual benefits of encapsulation.

**Comment by Matt-Yorkley** [comment]
It should still be up on https://staging.openfodnetwork.org.uk. I just thought thought it would be good to test it myself as it's not always straightforward to do, and I wanted to assess the request and response headers in different cases, which isn't a normal part of testing.

File: app/services/embedded_page_service.rb (hunk 2 above)
Comment (Matt-Yorkley) [reply app/services/embedded_page_service.rb]: I'm not sure I understand what you mean? Adding `attr_reader` and `attr_accessor` lines under `private` will just create private methods for accessing those instance variables, right? But they can't be accessed outside of the instance anyway, and all but one of the methods are private to begin with. 

The class needs to be able to modify the objects referenced by `@resonse` and `@session`. Actually, that's basically it's primary job. It looks like it only needs to read the other two objects, so I guess we could use:

```
private
attr_reader :request, :params
attr_accessor :session, :response
```
But I don't really understand what would be gained from this? There's already no getters or setters for those variables, so this doesn't limits access in any way. Is the intention to make it more explicit that those variables are only accessible from within an instance of this class?

Comment (mkllnk) [reply app/services/embedded_page_service.rb]: I think the intention here is to standardise access to always use methods instead of direct access to the ivars. The advantage is that it's easier to change behaviour later or move parts into other classes without changing the code accessing these variables. The disadvantage is that you can't see immediately if a call to `request` has side effects or if it is private. You need to look up the accessor/reader first. That's why I'm not clear on this recommendation.

File: app/services/embedded_page_service.rb [hunk 3]
```diff
@@ -0,0 +1,90 @@
+# Processes requests for pages embedded in iframes
+
+class EmbeddedPageService
+  attr_reader :use_embedded_layout
```
Comment (mkllnk) [inline app/services/embedded_page_service.rb]: Now here is a disadvantage of the attr_reader. This method should be called `use_embedded_layout?`, right?

Comment (sauloperez) [reply app/services/embedded_page_service.rb]: let's make that a regular method if we want the question mark then. It's the only way if we want it.

File: app/services/embedded_page_service.rb (hunk 2 above)
Comment (sauloperez) [reply app/services/embedded_page_service.rb]: Yes, that's my point. 

Regarding

> The disadvantage is that you can't see immediately if a call to request has side effects or if it is private. You need to look up the accessor/reader first. 

I haven't experienced problems with this unless the class is huge. Once you open the class, from the constructor you see what vars compose its internal state and what is all about. However, this encapsulation brings much bigger benefits to changeability. 

It's relatively easier to move private methods to the public API without having to change much, or create a new subclass and rely on those reader methods or even to turn simple `attr_reader`s to regular methods when their logic grows, while keeping the consumers untouched. Not to mention the fact that a typo on a method call raises an error, while a typo on an ivar's name does not; that's really useful!

Having said that, I don't want to be picky. You guys decide.

Comment (Matt-Yorkley) [reply app/services/embedded_page_service.rb]: It looks like I would also have to convert lines like this:
`@embedding_domain = current_referer`

to use this syntax:
`instance_variable_set '@embedding_domain', current_referer`

because this won't work for assigning to the private ivars via methods:
`embedding_domain = current_referer`

Comment (mkllnk) [reply app/services/embedded_page_service.rb]: I'm not sure I know what you mean. You last line doesn't work even if you have a private `attr_writer`? Anyway, I'm moving this to test ready and keep all the comments in mind. I will probably make more use of accessor in the future.

Comment (sauloperez) [reply app/services/embedded_page_service.rb]: I don't follow it either. Look at https://github.com/codetriage/codetriage/blob/master/app/services/git_hub_authenticator.rb. This is a clear example of what I mean.

**Comment by myriamboure** [comment]
@Matt-Yorkley it seems all reviews are green, wouldn't you mind staging on UK staging? And maybe testing if you have an easy way to test? Else let @RachL and me know when it is staged and we can organize with the global wordpress and ask a user who we know pretty well for websites with www. (we had some issues with testing only in wordpress earier...) We are waiting this to be merge for releasing!!! Let's do it!!!

File: app/services/embedded_page_service.rb (hunk 2 above)
Comment (Matt-Yorkley) [reply app/services/embedded_page_service.rb]: It works nicely when reading from ivars via private attr_reader methods, but writing to those attributes needs some odd-looking rewrites using `#instance_variable_set`:
```ruby
private
attr_reader :private_ivar_one
attr_accessor :private_ivar_two

def example
example_local_variable = private_ivar_one # reading works fine and is clear/concise

private_ivar_two = 'new_value' # doesn't write to ivar, creates new local variable
instance_variable_set @private_ivar_two, 'new_value' # writes to the ivar, but isn't pretty
end
```

Comment (sauloperez) [reply app/services/embedded_page_service.rb]: Now I understand what you mean. That's what `self` is for. Check out [this](http://rubyfiddle.com/riddles/34ec5) example.

Comment (Matt-Yorkley) [reply app/services/embedded_page_service.rb]: Ah that's really obvious now, I don't know why I was only thinking of more complicated solutions like `send(private_ivar='new_value')` and everything except the simple answer... :see_no_evil:

**Comment by Matt-Yorkley** [comment]
@myriamboure Sorry for intervening in the usual testing process. This fix was a bit more urgent for the UK, so we were planning on pushing it to production before the next release. I tested it on UK staging using another site to embed a shopfront, and I wanted to be completely confident that pushing it to production early wouldn't cause any problems (and would fix the issue).

I checked to see if things were working generally, but mostly I was looking at the how the response headers behaved when moving to the checkout and cart, as that was the cause of the issue (and what was changed in the PR). Addition of the `'self'` keyword in the `Content-Security-Policy` header, and persistence of the embedding site's domain name on subsequent requests was my primary criteria:

screenshot from 2018-06-22 14-12-44

And here's a screenshot of the checkout page successfully showing in the embedded shop (basic pass criteria for the issue): 

screenshot from 2018-06-22 14-13-08

We've pushed this to UK production now, so you can see it working at: https://blackmountainfoodhub.co.uk/en/shop/ (which is live).

**Comment by myriamboure** [comment]
Yes @Matt-Yorkley no issue with me, you changed things after @sauloperez feedback so we thought we needed to test again. But if you pushed to production and it's all working good live I guess it's the best test we can have so @sauloperez I think we can merge!

**Comment by Matt-Yorkley** [comment]
@sauloperez do you want me to refactor to the private ivars first? And retest?
