### PR TITLE
Handle lang management on user passwords controller

### LINKED ISSUE #7842: Error 500 when changing locales, during password reset
## Description

While on the password reset screen, changing locales triggers an error 500, i.e., the page only works in the default language of the instance/server.

## Expected Behavior

Switching to other locales should be possible when resetting the password.

## Actual Behaviour

Switching locales triggers an error 500 and displays the snail to the user.

## Steps to Reproduce

1. Visit the home page 
2. Click `Login` and select the `Forgot Password?`
3. Type the email address of an existing account
4. Follow the link received per Email -> It should open a page to type the new password
5. While on the password reset page, select another language -> :boom: 

## Animated Gif/Screenshot

Peek 2021-06-25 18-44

## Workaround

No workaround to use a language different than the instances default language, when resetting the password.

## Severity

This seems to happen quite often (from looking at Bugsnag notifications)...
Proposing S2.

## Your Environment

* Version used: v3.8.3 (verified in production as well)
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Desktop, Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

This PR adds a controller and a path: `set_lang` to actually set the lang of the application. Therefore, links into the dropdown are updated (to `/user/set_lang/[LANG]`)
It replace the old way to day: ie. having a link to `?locale=#{l.to_s}` which cannot be handled in some URLs (specially with `/user/spree_user/password/edit?reset_password_token=[TOKEN]` because it already had a params). 
Once the lang is set, it then redirect to the `HTTP_REFERER` url (ie. the current page where the user is).

At the same time, this PR remove the already selected langage from the dropdown (no need to change the current langage to the same):
Capture d’écran 2021-06-28 à 11 38 34

Closes #7842

#### What should we test?
1. Visit the home page
2. Select another langage
3. Click `Login` and select the `Forgot Password?`
4. Type the email address of an existing account
5. Follow the link received per Email -> It should open a page to type the new password
6. This page should have the same language than the previous you selected
6. While on the password reset page, select another language. It's obviously should work

#### Release notes
Handle the change of the language on the user password change page.

Changelog Category: User facing changes

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -20,6 +20,7 @@
   get "/register", to: "registration#index", as: :registration
   get "/register/auth", to: "registration#authenticate", as: :registration_auth
   post "/user/registered_email", to: "spree/users#registered_email"
+  get "/user/set_lang/:lang", to: "application#set_lang", :as => :set_lang
```
Comment (andrewpbrett) [inline config/routes.rb:23]: Should this maybe be a `post`? It is changing something, but not on the server, since it just changes the cookie. I think it's okay to test/merge as it is though.

**Review by andrewpbrett — APPROVED** [review]
Looks great. If you agree about the route being a `post` feel free to update it, but not required IMO.

File: config/routes.rb (hunk 1 above)
Comment (jibees) [reply config/routes.rb:23]: If I set to a post here, then I can't handle it by a simple link in the langage selection dropdown. I must do a post request which is not as simple as a get (with a link). That's why, I prefer the `get` method. 
Let me know if it's a blocker for you, I'd happy to change my opinion.

Comment (andrewpbrett) [reply config/routes.rb:23]: Yep, not a blocker, I think a `get` request makes sense.

Comment (mkllnk) [inline config/routes.rb:23]: The ApplicationController tends to become too complex. Adding this method here means that every controller inherits this method even though no other controller needs it. I would suggest to create a new controller for this, the `LocalesController`. The locale can be stored in the database (user record) but it's also stored in a cookie which is important for guest users. So I would say that putting it under `/user/..` is misleading.

```suggestion
  resources :locales, only: [:show]
```

It's still not 100% in line with Rails conventions because `get` usually doesn't change anything but it's the easiest way of doing it. Rails does support POST in links but it relies on Javascript: https://stackoverflow.com/a/4752019/3377535
I would still go with the normal get request and therefore I used `show` in the example above.
It's like, "show me [all pages in] Spanish".

File: app/views/shared/menu/_language_selector.html.haml [hunk 2]
```diff
@@ -3,6 +3,6 @@
     %i.ofn-i_071-globe
     %span= t 'language_name'
   %ul.dropdown
-    - OpenFoodNetwork::I18nConfig.selectable_locales.each do |l|
+    - OpenFoodNetwork::I18nConfig.selectable_locales.select{|l| l.to_s != I18n.locale.to_s}.each do |l|
```
Comment (mkllnk) [inline app/views/shared/menu/_language_selector.html.haml:6]: This is a lot of logic in the view. Let's move it to `I18nConfig`. And did you know `reject` which is the opposite of `select`? It's a bit clearer to use `reject` with `==`. But since you are removing an element by value, it can be even simpler:

```suggestion
    - OpenFoodNetwork::I18nConfig.locale_options.each do |l|
```

```diff
diff --git a/lib/open_food_network/i18n_config.rb b/lib/open_food_network/i18n_config.rb
index 8830f9337..83d624f88 100644
--- a/lib/open_food_network/i18n_config.rb
+++ b/lib/open_food_network/i18n_config.rb
@@ -5,6 +5,11 @@ module OpenFoodNetwork
   # Currently, language settings are read from the environment.
   # See: config/application.yml
   class I18nConfig
+    # Users don't need to select the already selected locale.
+    def self.locale_options
+      selectable_locales.delete(I18n.locale.to_s)
+    end
+
     # Locales that can be selected by users.
     def self.selectable_locales
       ENV["AVAILABLE_LOCALES"].andand.split(/[\s,]+/) || []
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
This is great!

I just added a few suggestions about the structure to keep the code clean and in line with Rails conventions.

File: app/views/shared/menu/_language_selector.html.haml (hunk 2 above)
Comment (jibees) [reply app/views/shared/menu/_language_selector.html.haml]: Thanks a lot for pointing me out all this things. 
I've committed dd4ca3eac and made some modifications since the `delete` method returns the deleted item in the array and not the array itself.

File: config/routes.rb (hunk 1 above)
Comment (jibees) [reply config/routes.rb]: Makes a lot of sense. Committed: aa982fe8d

**Comment by jibees** [comment]
> This is great!
> 
> I just added a few suggestions about the structure to keep the code clean and in line with Rails conventions.

Thanks a lot @mkllnk for your deep and kind review. 🙏

**Comment by andrewpbrett** [comment]
Indeed, great suggestions @mkllnk!

File: lib/open_food_network/i18n_config.rb [hunk 3]
```diff
@@ -5,6 +5,13 @@ module OpenFoodNetwork
   # Currently, language settings are read from the environment.
   # See: config/application.yml
   class I18nConfig
+    # Users don't need to select the already selected locale.
+    def self.locale_options
+      locales = selectable_locales
+      locales.delete(I18n.locale.to_s)
+      locales
```
Comment (mkllnk) [inline lib/open_food_network/i18n_config.rb:12]: Cool, that's great, too. Sorry I didn't realise about the return value of `delete`. Another way to write this:
```suggestion
      selectable_locales - [I18n.locale.to_s]
```

**Review by mkllnk — APPROVED** [review]
:smile: 

Feel free to move it to test-ready if you don't want to work on it any more.

File: lib/open_food_network/i18n_config.rb (hunk 3 above)
Comment (jibees) [reply lib/open_food_network/i18n_config.rb]: Way much better: thanks a lot!

**Comment by jibees** [comment]
Thanks for you last review @mkllnk . I did the changes, and then moved to `Test Ready`

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Awesome, switching locales when re-setting the password works nicely now:

Peek 2021-07-09 14-14

Changing the password works, on the different languages. Also verified that the entry on the menu from the selected language is now removed.

I checked some senarios related to the locale settings, like:
- logging in
- selecting a language
- logging out
- Opening a new session
- Logging into the previous account should display the previously selected language -> OK

I noticed we sill have this on the side bar but this was not the purpose of this PR:

image

Good to go! :tada:
