### PR TITLE
Addresses flakyness in shopping_spec.rb

### LINKED ISSUE #9435: [Flaky] /consumer/shopping/shopping_spec.rb:529
### What we should change and why (this is tech debt)

```

Failures:
  1) As a consumer I want to shop with a distributor Viewing a distributor adding and removing products from cart when a variant is soft-deleted when the soft-deleted variant has an associated override adding the soft-deleted variant to the cart handles it as if the variant has gone out of stock
Failure/Error: expect(page).to have_selector selector
  expected to find css "#variant-709" but there were no matches

Failed examples:
rspec ./spec/system/consumer/shopping/shopping_spec.rb:529# As a consumer I want to shop with a distributor Viewing a distributor adding and removing products from cart when a variant is soft-deleted when the soft-deleted variant has an associated override adding the soft-deleted variant to the cart handles it as if the variant has gone out of stock
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/runs/7444089845?check_suite_focus=true

Previous issues:

- #7677
- #7669
- #8830

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Closes #9435

Several tests in this spec are flaky:

`spec/system/consumer/shopping/shopping_spec.rb:184` -> this block is split into two contexts, for each order cycle; one of them should require/test paginantion (20 products, 10 per page); the other one now as only 5 products (no pagination).

`spec/system/consumer/shopping/shopping_spec.rb:233` -> some minor changes were made, but seemed to have no effect whatsoever on flakyness.

`spec/system/consumer/shopping/shopping_spec.rb:529` -> nothing changed here.

The changes above were not really making a difference... So, I looked a bit for other causes and came to the conclusion we might be experiencing this known issue https://github.com/rubycdp/cuprite/issues/122.

So, in the end, the approach chosen was to change the default settings for `ferrum` (working under the hood within `cuprite`), these seem to overlap capybara's configuration. Some commits are a bit of a trial, but should then squashed/dropped, I think. (like the back and forth on the `Capybara.default_max_wait_time = 10` - it's interesting to note the effect on the build though :eyes: )

#### What should we test?

Consistently green build :crossed_fingers: 

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Other than minor changes and improvements, the way to go would be to increase `Capybara.default_max_wait_time`; however, we already set this to 10 on `cuprite_setup.rb`. I think we're looking at this issue https://github.com/rubycdp/cuprite/issues/122.

**Review by mkllnk — COMMENTED** [review]
Still failing specs. :disappointed:

**Comment by mkllnk** [comment]
Thank you for trying all that. I'm not sure where to go from here. :shrug:

**Comment by filipefurtad0** [comment]
Thanks @mkllnk.
I might go "back to the basics" and continue the approach of splitting each `it` block into the distinct `context`s. Maybe it will help... I'll try that and go from there.

I still find very interesting to "watch" which specs fail, when we change the capybara/ferrum settings. It shows pain points, perhaps not only in flakyness but also in the time these are consuming. Seems like a lot to unpack here...

**Comment by filipefurtad0** [comment]
image
:sob: 

I've tried pretty much everything I could think of, nuked everything and then started over. My conclusion is that the app is very inconsistent on these pages. Searching:
- _sometimes_ displays the spinner; shown text is "Loading products..."
- _sometimes_ displays all products even when the search clearly matches none, like on the example below...

image

It's not a good idea to comment out the spec/flaky test cases, but I really see no other option... Maybe these queries could be improved for consistency, somehow?

**Comment by mkllnk** [comment]
> sometimes displays the spinner; shown text is "Loading products..."

We can't rely on that because it's time based. If the testing code is executed slowly, the products are loaded and the spinner disappears before we tested for it. We need to remove that part.

> sometimes displays all products even when the search clearly matches none, like on the example below...

What? How frustrating! There must be some race condition in the JS code. I guess that it's a bug which is very hard to reproduce as a human. I would like to have a look at some point, even though I'm expecting to get really frustrated...

File: spec/system/consumer/shopping/shopping_spec.rb [hunk 1]
```diff
@@ -211,34 +219,50 @@
...
+          sleep(0.2)
+          expect(page).to have_content "Sorry, no results found"
+          expect(page).not_to have_content product2.name
+          click_on "Clear search" # clears search by clicking text
+          sleep(0.2)
+          expect(page).to have_content("Add", count: 4)
+        end
+        it "returns results and clears searches by clicking the clear-button" do
+          fill_in "search", with: "Meer" # For product named "Meercats"
+          find("#seach").native.send_keys(:tab)
```
Comment (mkllnk) [inline spec/system/consumer/shopping/shopping_spec.rb:258]:
```suggestion
          find("#search").native.send_keys(:tab)
```

**Comment by mkllnk** [comment]
I tested that search spec locally and found that two out of thirty runs fail on my machine. Then I looked at the code and saw that we search straight after the page load. JS may not have been initialised completely when a `visit` call ends. It's always good to assert some important content on the page first.

I added a `sleep 2` first and didn't see any fails in 60 runs. Then I replaced that with a content check which hopefully only succeeds once JS is finished. That event is sometimes difficult to detect. But it seems to work:

```
diff --git a/spec/system/consumer/shopping/shopping_spec.rb b/spec/system/consumer/shopping/shopping_spec.rb
index 823018143..ec1d924fe 100644
--- a/spec/system/consumer/shopping/shopping_spec.rb
+++ b/spec/system/consumer/shopping/shopping_spec.rb
@@ -232,6 +232,8 @@ describe "As a consumer I want to shop with a distributor", js: true do
 
       it "filters search results properly" do
         visit shop_path
+        expect(page).to have_content product2.name
+
         fill_in "search", with: "74576345634XXXXXX"
         expect(page).to have_content "Sorry, no results found"
         expect(page).not_to have_content product2.name
```

**Comment by jibees** [comment]
> ```expect(page).to have_content product2.name```


Yes, good idea: adding those kind of assertion to ensure that the page is loaded is a great idea.

**Comment by filipefurtad0** [comment]
Thanks for that suggestion @mkllnk I've committed it [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9721/commits/7b592fd80b814dd7cbfe79eaa8acd7343fbeb1cc). The build is indeed green but I've got a local failure:

```
Failures:

  1) As a consumer I want to shop with a distributor Viewing a distributor after selecting an order cycle with products visible filtering search results returns no results and clears searches by clicking the clear-link
     Failure/Error: expect(page).to have_content product2.name
       expected to find text "Meercats" in "SHOPS MAP PRODUCERS GROUPS ABOUT Inglés Login Shopping @ Enterprise 1 Cart 0 Close Your cart is empty Enterprise 1 Herndon Shop About Producers Contact Next order closing in 2 days Ready for frogs Loading products... Filter by Brand Ruby on Rails Interested in getting on the Open Food Network? Register here Secure and trusted. Open Food Network uses SSL encryption (2048 bit RSA) everywhere to keep your shopping and payment information private. Our servers do not store your credit card details and payments are processed by PCI-compliant services. Keep in touch Email us Newsletter sign-up News Calendar Navigate Shops Map Producers Groups About Join us Create a listing, shop or group directory on the Open Food Network. Tell me more! Read our Terms of service | Find us on GitHub Open Food Network is a free and open source software platform. Our content is licensed with CC BY-SA 3.0 and our code with AGPL 3. We take good care of your data. See our cookies policy"
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_a_consumer_i_want_to_shop_with_a_distributor_viewing_a_distributor_after_selecting_an_order_cycle_with_products_visible_filtering_search_results_returns_no_results_and_clears__31.png

     
     # ./spec/system/consumer/shopping/shopping_spec.rb:247:in `block (5 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

Finished in 42.5 seconds (files took 7.42 seconds to load)
1 example, 1 failure

```

Which relates to that first flakyness scenario - the spinner:

image

I've tried similar approaches like sending browser commends (like scrolling, sending key strokes, assertions on content) to make sure the page loads or that the change we make to the page (filling in the search field) has enough time. I've always found inconsistency on page behavior (I'm running these changes 50 times in parallel sessions, locally.)

I'll make some more tests on your suggestion of using the `sleep(2)`... I see no other choice to be honest. There are other test cases on this page which will fail for similar reasons, let's see.

**Comment by filipefurtad0** [comment]
Again, and on the last flaky spec here I could only fix spec flakiness by adding `sleep(2)` approach not to fail, at least locally - done in commit 977916cb111cf431131f818f1e88fd8f29b0efb4.

File: spec/system/consumer/shopping/shopping_spec.rb [hunk 2]
```diff
@@ -244,7 +244,7 @@
       context "filtering search results" do
         it "returns no results and clears searches by clicking the clear-link" do
           visit shop_path
-          expect(page).to have_content product2.name
+          sleep(2)
```
Comment (mkllnk) [inline spec/system/consumer/shopping/shopping_spec.rb:247]: I think that the content check is still good here because we are later testing that this content is *not* there.

**Review by mkllnk — APPROVED** [review]
Sleep is a last resort but better than commenting out the spec. Let's go with this for now.

File: spec/system/consumer/shopping/shopping_spec.rb (hunk 2 above)
Comment (filipefurtad0) [reply spec/system/consumer/shopping/shopping_spec.rb:247]: I've removed that line because it was causing a similar failure as mentioned [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9721#issuecomment-1266894646) (since the page was not fully loaded):

`# ./spec/system/consumer/shopping/shopping_spec.rb:247:in - block (5 levels) in <top (required)>`

But I guess we could add it after the `sleep(2)` line.
