### PR TITLE
Fix guest order cancellation redirecting to home page

### LINKED ISSUE #13817: Glitch with order cancellation when using guest checkout
## Description
If a hub/shop allows guest checkout AND orders to be changed/cancelled, then when a customer checkouts out and hits 'cancel order' button on the order confirmation page, the cancellation doesn't go through and they get redirected to the openfoodnetwork home page.  This can lead to customers incorrectly thinking that they have cancelled an order, but the hub/shop has no indication that the order has been cancelled.  This indeed happened with a large $$ order with an CAN hub and led to some upset.  

## Expected Behavior
If the customer places and order and wants to cancel right away by using the 'cancel order' button on the order confirmation page, then the order cancellation button should redirect to a page that confirms the order cancellation, send an cancellation confirmation email to the customer and hub/shop, and cancel the order in the hub/shop orders list (add items back to stock).  

## Actual Behaviour
When the order cancellation button is hit, the customer is asked to confirm that they want to cancel the order, and when choosing 'Yes' gets redirected to the openfoodnetwork home page in a glitchy way.  The customer is left wondering if their request went through.  Hub receives no indication that the customer has cancelled the order.  

## Steps to Reproduce

1. Make sure hub/shop is set up for guest checkout and orders can be changed or cancelled in shop preferences.
2. Place a demo order as a guest (signed out) for the hub/shop
3. After order is placed, choose 'cancel order' from order confirmation page. 
4. Will get asked to confirm that you want to cancel order, select 'yes'.  
5. Should get redirected to openfoodnetwork home page with no confirmation that order was cancelled.

## Animated Gif/Screenshot

https://github.com/user-attachments/assets/1d3d507f-bb53-4473-821e-6ecf3f850529

## Workaround
To not use guest checkout setting with order can be changed or cancelled.

## Severity

bug-s3: a feature is broken but there is a workaround

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used: OFN Canada
* Browser name and version: firefox 146.0
* Operating System and version (desktop or mobile): desktop mac Sequoia 15.7.3

### PR DESCRIPTION
**Pull request by gbathree**
## What? Why?

- Closes #13817

When a guest user places an order and clicks "Cancel order" on the confirmation page, the cancellation silently fails and they are redirected to the OFN home page with no feedback. The guest is left unsure whether the order was cancelled, and the hub receives no cancellation notification.

**Root cause — two missing pieces for guest (token-based) authorization:**

1. `Ability#add_shopping_abilities` granted `:cancel` only when `order.user == user`. For a guest, `order.user` is `nil` and the CanCan user is an unsaved `Spree::User.new`, so the check always fails. The `:read` and `:update` abilities already have a token fallback (`order.token && token == order.token`) — `:cancel` now uses the same pattern.

2. The `cancel` action called `authorize! :cancel, @order` without passing `session[:access_token]`, so even with the fixed ability definition the token was never evaluated.

Together these caused `CanCan::AccessDenied` to be raised for every guest cancel attempt, which `Spree::Core::ControllerHelpers::Auth#unauthorized` handles by redirecting unauthenticated users to the home page.

## What should we test?

- Set up a hub/shop with guest checkout enabled and orders allowed to be changed/cancelled.
- Place an order as a guest (signed out).
- On the order confirmation page, click "Cancel order" and confirm.
- Expected: order is cancelled, success flash shown, redirected to order page.
- Also verify a logged-in user can still cancel their own order (existing behaviour unchanged).

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes

(added by Greg)
step1-order-confirmed
step2-after-cancel

### CODE REVIEW

**Comment by gbathree** [comment]
## Manual verification — guest cancellation end-to-end

Tested locally against this branch using a headless browser (Playwright):

1. Logged out (guest session)
2. Navigated to Freddy's Farm Shop (guest checkout enabled, order changes allowed)
3. Added item to cart → checked out as guest
4. On the order confirmation page, clicked **Cancel Order** → confirmed dialog

**Before fix:** clicking Cancel as a guest silently failed and redirected to the OFN home page with no feedback. The guest had no way to know if the order was cancelled.

**After fix:** the guest stays on the order page and the status updates in-place to **Cancelled**.

### Step 1 — Order confirmed, Cancel Order button visible

Order confirmed

### Step 2 — After clicking Cancel Order (still on same page, same guest session)

Order cancelled

The screenshots are committed to `doc/demo/` on this branch and can be removed before merge if preferred.

File: spec/controllers/spree/orders_controller_spec.rb [hunk 1]
```diff
@@ -461,6 +461,26 @@
...
+      before do
+        allow(controller).to receive(:spree_current_user) { nil }
+        session[:access_token] = order.token
+      end
+
+      it "cancels the order and redirects to the order page" do
+        spree_put :cancel, params
+
+        expect(response).to have_http_status(:found)
+        expect(response.body).to match(order_path(order)).and match("redirect")
```
Comment (rioug) [inline spec/controllers/spree/orders_controller_spec.rb]: You can just use `redirect_to` matcher for this :
```suggestion
        expect(response).to redirect_to(order_path(order))
```

File: doc/demo/step1-order-confirmed.png
Comment (rioug) [inline doc/demo/step1-order-confirmed.png:1]: These screenshot should be added to the PR description. Could you remove them ?

File: doc/demo/step2-after-cancel.png
Comment (rioug) [inline doc/demo/step2-after-cancel.png:1]: Same as above comment

**Review by rioug — CHANGES_REQUESTED** [review]
Looks good, We just need a small change, see comment.
And screenshot describing the PR changes belong in the PR description, they shouldn't be added to the repository.

File: spec/controllers/spree/orders_controller_spec.rb (hunk 1 above)
Comment (gbathree) [reply spec/controllers/spree/orders_controller_spec.rb]: Good catch — I've now set `request.env['HTTP_REFERER']` in each cancel spec so the test reflects the real scenario (user is on the order page when they cancel). 

Note: I kept the `response.body` match pattern rather than `redirect_to` because the cancel action uses `cable_car.redirect_to` (a CableReady response), not a standard Rails redirect — so the `redirect_to` matcher won't work here. This is consistent with how `checkout_controller_spec.rb` tests CableReady redirects (line 714).

File: doc/demo/step1-order-confirmed.png
Comment (gbathree) [reply doc/demo/step1-order-confirmed.png:1]: Done — screenshots removed from the branch. For the PR description: I can't upload images programmatically via the API (GitHub image uploads require the web UI). Greg (the human collaborator) will paste the screenshots into the PR description directly.

File: doc/demo/step2-after-cancel.png
Comment (gbathree) [reply doc/demo/step2-after-cancel.png:1]: Same as above — removed.

**Review by rioug — APPROVED** [review]
Thanks ! I don't think the `HTTP_REFERER` is strictly necessary but it's good as it is.

**Review by mkllnk — APPROVED** [review]

**Comment by AMEA-LYON** [comment]
All is working accordingly to the manual verification procedure described in the comments,
I also tested that cancellation still works for a logged-in user

Congratulations 🎊 

=> Ready to Go 🚀
