### PR TITLE
Handle `items` in bulk order management

### LINKED ISSUE #8540: BOM addition calculator at the top doesn’t currently read from / add up quantities of ‘items’
## What is the need / problem?

Currently if a product has item as unit, the calculator at the top of the page is not working. Example on staging FR:

image

## Which type of users does this problem affect (and how many, if known)?

_- Hub Managers (MCFEs)_
_- Producers_
_- Instance Managers_

## Connected wishlist and discovery discussions* [list precedent discussions]

https://community.openfoodnetwork.org/t/bulk-order-management-wishlist/305/2?u=rachel

## Is Papercut or feature candidate?

Good questions

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #8540

#### What should we test?

- Create product that is set to `items` quantity (_sachets_ means bags, pouch in french) and is available for bulk mode
Capture d’écran 2022-04-25 à 16 11 44

- Set a Group By value
Capture d’écran 2022-04-26 à 15 32 06

- Checkout that product, and see the Bulk Order Management interface
Capture d’écran 2022-04-26 à 15 33 13

It should not affect the interface in metric and imperial system, but I'd think it worth a check (before and after the PR) ; see previous PR maybe for help (https://github.com/openfoodfoundation/openfoodnetwork/pull/8565)

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee [hunk 1]
```diff
@@ -286,15 +291,24 @@ describe "LineItemsCtrl", ->
           expect(scope.sumUnitValues()).toEqual 8
 
       describe "sumMaxUnitValues()", ->
-        it "returns the sum of the product of unit_value and maxOf(max_quantity, pristine quantity) for specified line_items", ->
+        fit "returns the sum of the product of unit_value and maxOf(max_quantity, pristine quantity) for specified line_items", ->
```
Comment (mkllnk) [inline spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee:294]:
```suggestion
        it "returns the sum of the product of unit_value and maxOf(max_quantity, pristine quantity) for specified line_items", ->
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
Looks good to me, except one line. :wink:

**Comment by jibees** [comment]
> Looks good to me, except one line. 😉

Thanks for your attention @mkllnk ... (maybe I should configure a pre-commit hook ;))

**Review by mkllnk — APPROVED** [review]

**Review by mkllnk — COMMENTED** [review]
Moving to test ready.

**Comment by drummer83** [comment]
@RachL: You are still assigned to this issue. Would you like to test it or can someone else pick it up?

**Comment by RachL** [comment]
@drummer83 go ahead :)

**Comment by drummer83** [comment]
Thanks @jibees for this PR. Finally I was able to test it.

I set up products with items as unit and also metric and imperial units and activated Group Buy for them.
Then I went shopping with three different customers and checked the BOM page.
Here are my results:

**Before this PR:**
The BOM page didn't show the ordered quantities for 'items':
grafik

**After this PR:**
Items are now nicely displayed on BOM page. The calculations are correct. Cool! :sunglasses: 
grafik

As requested I have also tested imperial units, which is also looking good:
grafik

I think this one is ready to go! :champagne:

**Comment by RachL** [comment]
@jibees I'm noticing "items" is not translated. Can we use a key or better display the unit name (like "botte" "panier") ?

image

**Comment by jibees** [comment]
@RachL 
It's not that easy unfortunately. I noticed that and I forgot to open an issue.
