### PR TITLE
Require variant category and supplier when creating new product variants [OFN-12666]

### LINKED ISSUE #12666: Creating a new variant is selecting the first producer and first category of the dropdown
Use #12476 Flower Farms code in clokify

## Description

Since we move the producer and the category to the variant, when creating a new variant in` admin/products`, the first producer of the user and the first category are selected by default. If the users act fast, they might create the variant with the wrong producer.

We need to leave the dropdown empty by default (which is the case on `/admin/products/XXXX/variants/new`)

## Steps to Reproduce

1. Go to `admin/products` with a user who has access to several producers
2. Create a new variant and notice a producer is already selected, same for the product category

## Animated Gif/Screenshot

image

## Workaround

Select a different one.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.5
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): desktop

### PR DESCRIPTION
**Pull request by wandji20**
**Use https://github.com/openfoodfoundation/openfoodnetwork/issues/12476 Flower Farms code in clokify**

#### What? Why?

- Closes #12666

- Remove callback to set variant category id on create
- Add logic to assign a new variant category to the same as the last variant for thesame product from the old products table
- Update specs to select variant producer and category 

#### What should we test?
- Updating products (variants) from old admin products table should work as before
- Updating products (variants) from v3 admin products table should show errors if producer or category is not selected

- Visit ... page.
[- ](http://localhost:3000/admin/products)

#### Release notes

Require variant category and supplier when creating new product variants

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] Technical changes only

Require variant category and supplier when creating new product variant

#### Dependencies
N/A

#### Documentation updates
N/A

### CODE REVIEW

**Comment by RachL** [comment]
@wandji20 hello! can you have a look at rebasing here? Many thanks for one more 🙏  You're on 🔥

File: spec/system/admin/products_v3/create_spec.rb [hunk 1]
```diff
@@ -81,6 +82,10 @@
           find('input[id$="_display_as"]').fill_in with: "2 grams"
           find('button[aria-label="On Hand"]').click
           find('input[id$="_price"]').fill_in with: "11.1"
+
+          select supplier.name, from: 'Producer'
+          select taxon.name, from: 'Category'
```
Comment (dacook) [inline spec/system/admin/products_v3/create_spec.rb:87]: This doesn't actually test the newly added requirements, that the producer and category dropdowns were blank at the beginning. 
That would have been nice, but I think this is still ok.

File: app/views/admin/products_v3/_variant_row.html.haml [hunk 2]
```diff
@@ -37,20 +37,24 @@
...
+%td.col-producer.field.naked_inputs
   = render(SearchableDropdownComponent.new(form: f,
       name: :supplier_id,
       aria_label: t('.producer_field_name'),
       options: producer_options,
       selected_option: variant.supplier_id,
-      placeholder_value: t('admin.products_v3.filters.search_for_producers')))
+      include_blank: t('admin.products_v3.filters.select_producer'),
+      placeholder_value: t('admin.products_v3.filters.select_producer')))
+  = error_message_on variant, :supplier
```
Comment (dacook) [inline app/views/admin/products_v3/_variant_row.html.haml:48]: Great, thanks for adding `error_message_on`. It probably should have been added in the beginning.

**Review by dacook — APPROVED** [review]
Thanks for updating this Wandji.

I note that it might have been just as much effort to implement the new requirement in the old admin screen, instead of re-implementing the old behaviour. But I think it's ok 👍

File: app/assets/javascripts/admin/bulk_product_update.js.coffee [hunk 3]
```diff
@@ -126,8 +126,11 @@ angular.module("ofn.admin").controller "AdminProductEditCtrl", ($scope, $timeout
     DisplayProperties.setShowVariants 0, showVariants
 
   $scope.addVariant = (product) ->
+    # Set new variant category to same as last product variant category to keep compactibility with deleted variant callback to set new variant category
+    newVariantId = $scope.nextVariantId();
+    newVariantCategoryId = product.variants[product.variants.length - 1]?.category_id
```
Comment (rioug) [inline app/assets/javascripts/admin/bulk_product_update.js.coffee:131]: I don't understand why we are doing this, It would make more sense to set the category to blank same as the new screen. I am not sure what you are referring to when you say "to keep compactibility with deleted variant callback to set new variant category"

Comment (dacook) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee:131]: > I am not sure what you are referring to when you say "to keep compactibility with deleted variant callback to set new variant category"

I think he means to maintain the existing behaviour on the old screen. So there would be no apparent change when using the old screen. But as you say,

> It would make more sense to set the category to blank same as the new screen

Comment (rioug) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee:131]: In the old screen the supplier is set to blank, I think it would be better to have a consistent behaviour.

Comment (dacook) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee:131]: 😮 Oh, so this change makes it worse than before? In that case we need to do better. 
Wandji would it be hard to make the old screen behave like the new one?

Comment (wandji20) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee:131]: Thanks a lot, @dacook and @rioug for identifying this one.
I noticed that the columns preference default for the category column in old screens have `visible: false`
Not so sure why we have this by default but I will gladly appreciate your input on this again.

File: spec/system/admin/products_v3/create_spec.rb (hunk 1 above)
Comment (wandji20) [reply spec/system/admin/products_v3/create_spec.rb:87]: Changes here were to fix failing specs
I agree it will be nice to check when the variant category and producer values are blank

File: app/assets/javascripts/admin/bulk_product_update.js.coffee (hunk 3 above)
Comment (dacook) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee:131]: Ok, that's a good point Wandji. If the Category column is hidden by default, it's not intuitive for the user to choose it.
I just tried it out and can see what you mean. 

If your PR ensures the old screen maintains the existing behaviour, I think it's ok to proceed as it is.  It adds a bit of technical debt, but that's ok because we're planning to remove the old screen later, once the transition to the new screen is complete.

Is that ok with you Gaetan?

Comment (rioug) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee:131]: > Is that ok with you Gaetan?

Yeah that's fine, if we get complaint we can always tell them to use the new screen :wink:

**Review by rioug — APPROVED** [review]
Looks good ! thanks @wandji20 :pray:

**Comment by filipefurtad0** [comment]
Hey @wandji20 ,

Thanks for another PR :pray: 

Before this change, we can see that:
1) a producer is pre-selected
2) The first product category s pre-selected on the list.

image

After staging the PR:

1) We can see that no produced is pre-selected
2) We can see that no product category is pre-selected

image

Attempting to save a variant without this information correctly triggers the warning, for these fields:

image

Looking great! Merging.
