### PR TITLE
Split Checkout: add error message when no shipping methods are available to the customer

### LINKED ISSUE #9145: [Split-checkout] Add a clean error message to customer when checkout fails due to absence of shipping methods
## Description

A similar issue to openfoodfoundation/openfoodnetwork#5950 (legacy checkout) is partially verified as well for split checkout: we can access the checkout flow although no shipping method is available, but can't complete it. The good think here is that this fails defensively: it does not allow to complete the order, so I don't think this is a rollout blocker.

## Expected Behavior

Show a message to the customer : "Checkout is not possible due to absence of shipping options. Please contact the shop owner."

## Actual Behaviour

A notice is displayed stating prompting the user to `Select a shipping method` when none is available.

## Steps to Reproduce

1. Hide all shipping methods either by:
2. Setting appropriate tags
3. Setting them as backoffice only
4. Checkout as customer (should not see any shipping methods)

## Animated Gif/Screenshot

**Legacy checkout** (for reference only):

image

**Split checkout**:

image

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9145
This adds a flash error message when no available shippings methods:
Capture d’écran 2022-08-08 à 16 25 49
Capture d’écran 2022-08-08 à 16 42 56

#### What should we test?

No shipping methods can occurs either:
  - hub didn't configure any shipping methods
  - no shipping methods are available due to tag rules

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

File: app/controllers/split_checkout_controller.rb [hunk 1]
```diff
@@ -21,6 +21,10 @@ class SplitCheckoutController < ::BaseController
 
   def edit
     redirect_to_step_based_on_order unless params[:step]
+
+    return if available_shipping_methods.any?
+
+    flash[:error] = I18n.t('split_checkout.errors.no_shipping_methods_available')
```
Comment (mkllnk) [inline app/controllers/split_checkout_controller.rb:27]: This is a bit confusing because it looks like the error case is the normal flow and the success case is terminating early. Would this be better?
```suggestion
    if available_shipping_methods.none?
      flash[:error] = I18n.t('split_checkout.errors.no_shipping_methods_available')
      return
    end
```

I could imagine rubocop complaining about it. We could also move the action to a method. I'm not sure without trying it out.

**Review by mkllnk — APPROVED** [review]
This is good but needs a conflict resolution. Moving to dev.

File: app/controllers/split_checkout_controller.rb (hunk 1 above)
Comment (jibees) [reply app/controllers/split_checkout_controller.rb]: Yes, rubocop complains, twice: 
 - Use a guard clause (`return unless available_shipping_methods.none?`) instead of wrapping the code inside a conditional expression. (convention:Style/GuardClause)
 - Redundant `return` detected

I'm wondering if this will do to the trick :
```ruby
    return unless available_shipping_methods.none?
    
    flash[:error] = I18n.t('split_checkout.errors.no_shipping_methods_available')
```

I personally dislike the `return unless` statement, which I find confusing, I do prefer use the `return if` statement.

So, what about
```ruby
flash_error_when_no_shipping_method_available if available_shipping_methods.none?

...

  def flash_error_when_no_shipping_method_available
    flash[:error] = I18n.t('split_checkout.errors.no_shipping_methods_available')
  end
```

See commit f0f287259

Comment (mkllnk) [reply app/controllers/split_checkout_controller.rb]: Yes. that's a good solution.

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @jibees,
Thanks for this one! :muscle: 

## Before this PR
I have first tested before staging your PR to reproduce the issue. You can see the useless error message in the screen capture below. 
### All shipping methods are set to backoffice only
Split checkout:
Peek 2022-09-08 00-39
Legacy checkout:
image

### Shipping method is hidden through tag rules:
Split checkout:
Peek 2022-09-08 00-44
Legacy checkout:
image

### Shipping method is shown through tag rules:
Split checkout:
Peek 2022-09-08 00-47
Legacy checkout:
image

## After this PR
### All shipping methods are set to backoffice only
Split checkout:
Peek 2022-09-08 01-11

Legacy checkout:
unchanged

### Shipping method is hidden through tag rules:
Split checkout:
Peek 2022-09-08 01-10

Legacy checkout:
unchanged

### Shipping method is shown through tag rules:
Split checkout:
unchanged

Legacy checkout:
unchanged

I have nothing else to ask for. This one is ready to go! :fireworks:

**Comment by mkllnk** [comment]
I resolved a conflict and will merge once specs pass.

**Review by mkllnk — COMMENTED** [review]
It looks like we have a related spec failure now. Back to In Dev.

**Comment by jibees** [comment]
> It looks like we have a related spec failure now. Back to In Dev.

Seems to be unrelated to this branch, as it also occurs in master: https://github.com/openfoodfoundation/openfoodnetwork/runs/8240457288?check_suite_focus=true

Since, merging https://github.com/openfoodfoundation/openfoodnetwork/pull/9631

I'll open an issue, and try to resolve it.

**Comment by sigmundpetersen** [comment]
This is probably good to go then?
