### PR TITLE
Disentangle on_demand and backordered

### LINKED ISSUE #4158: Cannot ship orders with variants on_demand
## Description
Manager cannot ship an order if the order contains variants that are on_demand. Variants on_demand will appear in the order as "quantity x backordered" (instead of "quantity x on_hand"), the shipment state will show pending instead of ready and the ship button (both in the order list and in the order page) will not appear. See images [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/4112#issuecomment-521584878).

## Expected Behavior
You can ship an order with on_demand variants.

## Actual Behaviour
You cannot ship orders with on_demand variants.

## Steps to Reproduce
1. place an order with a variant that is on_demand
2. try to ship the order

## Context
Detected in #4112 

## Severity
bug-s3
I dont think this is a critical feature.
The (not so good) workaround is to temporarily change the variant in the order to on_hand, ship the order and then move the variant back to on_demand.

## Your Environment
* Version used: staging katuma 2.2.2
* Browser name and version: chrome latest
* Operating System and version (desktop or mobile): mac desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using. 2.2.2

## Possible Fixes

- Remove backordered logic from the shipment state method [here](https://github.com/openfoodfoundation/spree/blob/8a8585a43cd04d1a50dc65227f337a91b18d66d5/core/app/models/spree/shipment.rb#L207).

- The items are marked as "backordered" when their stock is negative, and that sets the order to "backordered" state, which blocks is from being shipped. If we don't reduce stock of on_demand items below zero, it should be fixed.

### LINKED ISSUE #4217: on_demand and backorderd
## Description

Purchasing `on_demand` products lowers the variant's stock, and can lower it below zero. Spree 2.0 then marks this variant as `backordered`, and also marks any shipments that contain this item as `backordered`. This then triggers some confusing feedback and some unwanted logic; the items and shipments are clearly marked as `backordered` in the UI which doesn't make sense in this context, and shipments in the `backordered` state can't be shipped and can't transition correctly. This can apply to any order with an `on_demand` item in it.

## Expected Behavior

`on_demand` items and related shipments are not labelled as `backordered`, orders containing `on_demand` items can be shipped.

## Steps to Reproduce

1. Create a product with stock: 1.
2. Set it to `on_demand`.
3. Order more than 1 of the product.
4. Look at the order and it's line_items as an enterprise user. (Confusing UI)
5. Try to ship the order. (Fails)

## Context

Investigating a fix for issue #4158, this sums up the root cause of the issue.
Also related to discussions in #4125, such as: https://github.com/openfoodfoundation/openfoodnetwork/pull/4125#issuecomment-519593092

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Possible Fix

- Ensure `on_demand` items don't reduce the stock below zero. 
- Possibly add a migration to move all on_demand variants with negative stock levels back up to zero.

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #4217 (original bug report: #4157)

Adjusts `on_demand` logic so that shipments no longer decrement an `on_demand` variant's stock levels. This means that `on_demand` items will no longer go into negative stock levels, and `on_demand` variants and their associated shipments will no longer be marked by Spree as `backordered`, which triggers a lot of unwanted logic.

#### What should we test?

Buying an `on_demand` variant does not reduce it's stock level.
Buying  large quantity of an `on_demand` variant does not cause the order to be unshippable.
Orders with `on_demand` variants do not get their shipment state marked as `backordered`.

#### Release notes

Variants marked `on_demand` no longer reduce stock levels when sold, and are not marked as `backordered`

Changelog Category: Changed

### CODE REVIEW

File: app/models/concerns/variant_stock.rb [hunk 1]
```diff
@@ -100,7 +100,7 @@ def can_supply?(quantity)
   # Here we depend only on variant.total_on_hand and variant.on_demand.
   #   This way, variant_overrides only need to override variant.total_on_hand and variant.on_demand.
   def fill_status(quantity)
-    if on_hand >= quantity
+    if on_hand >= quantity || on_demand
```
Comment (luisramos0) [inline app/models/concerns/variant_stock.rb]: do you know if we could we just get rid of backordered here and always return on_hand = quantity and backordered = 0?
now that I consider this, maybe we never get to backordered if variant is on_hand, that would mean we are fullfilling an order with outofstock variant.

so, this change may make, the else part of this if, dead code... what do you think?

**Comment by Matt-Yorkley** [comment]
Ok, I've added a migration to change existing inventory_units from `backordered` to `on_hand`. 

Shall we move the second part of the cleanup to another issue/PR?

> bring StockItem#adjust_count_on_hand to ofn and remove process_backorders from it, this will make things faster and cleaner, maybe we can even bring the full stock item class (bye bye spree) as half of the class methods are related to this process_backorders

**Comment by Matt-Yorkley** [comment]
> tbh I am a bit nervous with this PR but we have to do it!

Agreed on both counts!

**Comment by luisramos0** [comment]
build is broken with a related error.

File: app/models/concerns/variant_stock.rb [hunk 2]
```diff
@@ -117,6 +117,9 @@ def fill_status(quantity)
   def move(quantity, originator = nil)
     raise_error_if_no_stock_item_available
 
+    # Don't change variant stock if variant is on_demand
+    return if on_demand
```
Comment (mkllnk) [inline app/models/concerns/variant_stock.rb]: This is an alternative fix to one of the products cache issues we had. :-)

File: db/migrate/20190908183511_set_backordered_inventory_to_on_hand.rb [hunk 3]
```diff
@@ -0,0 +1,5 @@
+class SetBackorderedInventoryToOnHand < ActiveRecord::Migration
+  def up
+    Spree::InventoryUnit.backordered.update_all(state: 'on_hand')
```
Comment (mkllnk) [inline db/migrate/20190908183511_set_backordered_inventory_to_on_hand.rb]: It's better to avoid existing models. Either use plain SQL or define your own model here. Otherwise this will fail when we delete the `backordered` scope from InventoryUnit. I think you can just include this in the migration:

```rb
class SpreeInventoryUnit < ActiveRecord::Base
  scope :backordered, -> { where state: 'backordered' }
end
```
But plain SQL might be easier here.

Comment (sauloperez) [reply db/migrate/20190908183511_set_backordered_inventory_to_on_hand.rb]: Yes, please. It's very painful when later on the model changed what the migration was relying on 🙈

Might be time to introduce https://github.com/testdouble/good-migrations

File: spec/models/spree/line_item_spec.rb [hunk 4]
```diff
@@ -132,6 +132,59 @@ module Spree
...
+        it "allows the order to be shipped" do
+          expect(order.ready_to_ship?).to be true
+        end
+
+        it "does not change stock levels when cancelled" do
+          order.cancel!
+          expect(variant_on_demand.reload.on_hand).to eq 1
+        end
+      end
+    end
```
Comment (sauloperez) [inline spec/models/spree/line_item_spec.rb]: IMO this belongs to a layer above, controller tests. This file contains line items unit tests but the examples that we added not even reference a line item.

**Comment by sauloperez** [comment]
> I have the feeling there's an impact on other areas, Ill check a few things on Sunday/Monday.

Any findings @luisramos0 ? I think we all have that fear. It happened before.

As for the migration, as far as I understand we don't change behavior but fix broken data. So I don't see the need to make it reversible.

**Comment by luisramos0** [comment]
I did check the code around... I didnt find anything, looks good. I am still a bit nervous.
Anyway, I think this is awesome, specially because it opens up the possibility of bringing the spree code to our side and delete quite a lot of it :tada

File: db/migrate/20190908183511_set_backordered_inventory_to_on_hand.rb (hunk 3 above)
Comment (luisramos0) [reply db/migrate/20190908183511_set_backordered_inventory_to_on_hand.rb]: yes, I think that's correct Kristina.

**Comment by luisramos0** [comment]
good point Kristina! I checked these scenarios and it's a valid alternative to process orders and update shipment etc through the orderUpdater for example, but I'd not go that way...
I think we will be ok if we leave shipment.states and order.shipment_states as they are. Also I don't think we will have a problem if we leave  order state as is.
What do you think is the problem of leaving these workflows as they are?

**Comment by kristinalim** [comment]
> I think we will be ok if we leave shipment.states and order.shipment_states as they are. Also I don't think we will have a problem if we leave order state as is.
> What do you think is the problem of leaving these workflows as they are?

I need to test this a bit more in a few hours to verify (maybe my local dev data is not valid anymore), but as far as I saw, updating `StockItem` and `InventoryUnit` are not enough to recover an existing order with backordered items.

If we have no goal to recover existing orders and won't be eliminating the "backorder" shipment state of orders yet, then I think we should not touch existing backordered `InventoryUnit` records in the DB migration too, just leave them there for now.

**Comment by luisramos0** [comment]
ok :+1:

Updating inventory_units state will fix the problem for all orders because the order edit page displays the inventory_units state [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/1d177a164bc71f7f6e8e6169f25cf8fad138c1aa/app/views/spree/admin/orders/_shipment_manifest.html.haml#L12).

I think you are worried the system stays in an incoherent state. By "recovering the orders" you mean moving the workflow to the correct place, right?

**Comment by Matt-Yorkley** [comment]
I don't think the shipment state `backordered` actually exists in the database, it just gets shown as tht in the UI if the shipment contains any `backordered` items.

File: db/migrate/20190908183511_set_backordered_inventory_to_on_hand.rb (hunk 3 above)
Comment (Matt-Yorkley) [reply db/migrate/20190908183511_set_backordered_inventory_to_on_hand.rb]: @mkllnk I've updated the migration to plain SQL.

**Comment by luisramos0** [comment]
@kristinalim "I need to test this a bit more in a few hours"
Did you manage to test this? Any interesting findings?

**Comment by kristinalim** [comment]
:v: So, I was able to confirm `Spree::Order#shipment_state` is indeed set to "backorder" for these orders. Please see the screen recording below:

20190914010200-backorder_shipment_state

After running the migrations in this branch, when the shipment state is "backorder" and I load the admin edit order page, the Ship option is not yet available but order advancement that happens behind the scenes changes the shipment state from "backorder" to "ready". After this first page load, it is possible to ship the order.

**Comment by kristinalim** [comment]
I think this is okay to leave as is for now, but we should note this so we don't forget that there could be "backorder" shipment state in production data when eliminating backorder logic from OFN.

I'm seeing two relevant places for this backorder state:

* `Spree::OrderUpdater#update_shipment_state`
* `Spree::Shipment#determine_state`

**Comment by kristinalim** [comment]
@Matt-Yorkley @luisramos0 Even with my concern above, what do you think of moving this PR forward and creating the tech debt issue for removing backorders and then noting possible "backorder" shipment state in existing data?

**Comment by Matt-Yorkley** [comment]
Ah! I didn't realise the `spree_orders` table had it's own `shipment_state` column, I thought it was just getting it from the shipments. Confusingly, `Spree::Shipment` doesn't have a `backordered` state, but `Spree::Order` does. 

I'll add another migration. :+1:

**Comment by Matt-Yorkley** [comment]
Ah, but we don't know whether to change it to `pending` or `ready` without checking all the other parts of the order...

**Comment by sauloperez** [comment]
Awesome investigation @kristinalim . Let's approve the PR and do what you suggest :+1:

**Comment by kristinalim** [comment]
I created #4267 for above concern. :zap:

**Comment by luisramos0** [comment]
great stuff, thanks @kristinalim
test ready 🎉

**Comment by RachL** [comment]
**Test case number 1** : Buying an on_demand variant does not reduce it's stock level.

I bought 3 carrots and 3 garlics from Freddo's farm hub. Carrots where at hidden stock 1 and garlic at 0.

The stock didn't move:

image

**Test case number 2** : Buying large quantity of an on_demand variant does not cause the order to be unshippable.

I bought 9999 Garlics at fred's farm hub (we will talk about bad breath another time...). And I could ship the order :tada:

**Test case number 3** : Orders with on_demand variants do not get their shipment state marked as backordered.

So this is true... however it is written "on_hand"... Anything to be concerned about @Matt-Yorkley ?

image

**Comment by luisramos0** [comment]
in terms of test case 3, we have changed the tag from backordered to on_hand, that's why they show on_hand :+1:
I dont know why shipment state is "none" but I pretty sure it's not related to this PR. I have seen it before... the tech debt PR created could fix it: #4267 
I think this is good to go.

**Comment by Matt-Yorkley** [comment]
> I think this is good to go.

With `shipment` and `payment` both displaying "none"?

**Comment by luisramos0** [comment]
it's just a missing translation:
`= t(@order.shipment_state, scope: :shipment_states, default: [:missing, "none"])`

**Comment by kristinalim** [comment]
By the way, I included this in the changelog as a "Fixed" item.

**Comment by RachL** [comment]
@luisramos0 @ Matt-Yorkley About the missing translation. Do we need an issue? I see from Theresa's screenshot that the "none" is still appearing in production.

Moreover, the text in the quantity column is always showing the class "translation missing". Is this the new process to spot missing translation keys?

**Comment by luisramos0** [comment]
They are two different issues actually:
- "the "none" is still appearing in production" - this was already the case before the release, yes, we need an issue to fix it
- "the class "translation missing"" - I am not sure I understand if it's showing missing translation for the user, or just the CSS class. I am not sure we can fix it with transifex or if we need an issue, can you share details here please so we can clarify? thanks!

**Comment by luisramos0** [comment]
ok, I see the second point is now in https://github.com/openfoodfoundation/openfoodnetwork/issues/4302

**Comment by RachL** [comment]
Yes, I will open a new issue for the "none"
