### PR TITLE
Avoid conflicting login sessions between staging and production

### LINKED ISSUE #13974: Fix shared login sessions between staging and production
## Description

Currently, **staging and production share the same login session scope** due to how the session cookie domain is configured.

In `config/initializers/session_store.rb`, we are stripping subdomains (including `staging.`, `stg.` and `app.`) from `SITE_URL`:

``` ruby
domain = if Rails.env.staging? || Rails.env.production?
           ".#{ENV['SITE_URL'].gsub(/^(www\.)|^(app\.)|^(staging\.)|^(stg\.)/, '')}"
         else
           :all
         end

Openfoodnetwork::Application.config.session_store(
  :active_record_store,
  key: "_ofn_session_id",
  domain: domain
)
```

Because `staging.` is stripped, both environments resolve to the same root domain (e.g. `.openfoodnetwork.org`), which causes:
- Logging into **staging** to invalidate the **production** session
- Logging into **production** to invalidate the **staging** session

This appears to be an unintended side effect of a previous change meant to fix staging session behavior.

This issue aims to **isolate sessions between environments** while keeping login functionality intact.

------------------------------------------------------------------------

## Expected Behavior

-   Logging into staging should **not** log the user out of production.
-   Logging into production should **not** log the user out of staging.
-   Each environment should maintain its own session cookie.

------------------------------------------------------------------------

## Actual Behaviour

-   Staging and production share the same cookie scope.
-   Logging into one environment replaces the session in the other.

------------------------------------------------------------------------

## Steps to Reproduce

You can simulate this locally using two subdomains:

### 1. Update your `/etc/hosts` file:

    127.0.0.1 localhost
    127.0.0.1 staging.localhost

### 3. Open two browser tabs:

-   http://localhost:3000
-   http://staging.localhost:3000

### 5. Log into the other tab.

You will observe that logging into one invalidates the other session because they share the same cookie domain.

You can confirm this by inspecting:

**DevTools → Application → Cookies → `_ofn_session_id`**

------------------------------------------------------------------------

## Workaround

Use separate browsers or incognito mode for staging vs production.

------------------------------------------------------------------------

## Severity

**bug-s3**

A feature (session isolation) is broken but there is a workaround.

------------------------------------------------------------------------

## Your Environment

-   Version used: current master
-   Browser name and version: Chrome (latest)
-   Operating System and version (desktop): macOS / Linux

------------------------------------------------------------------------

## Possible Fix

We should **stop stripping `staging.`, `stg.`, `app.`  and `www.` from `SITE_URL`.**

### Required Code Change

Update this line:

``` ruby
".#{ENV['SITE_URL'].gsub(/^(www\.)|^(app\.)|^(staging\.)|^(stg\.)/, '')}"
```

To:

``` ruby
ENV['SITE_URL']
```

### Why This Works

-   Ensures staging and production generate **different cookie domains**
-   We don't use `www.` and `app.` subdomains as well
-   We just want the session cookie to be used only by the given domain for the environment and not for its subdomains. Hence we should not prepend `.` with the domain
-   Can be fully verified locally

### PR DESCRIPTION
**Pull request by dacook**
## What? Why?

- hopelly this one closes #13974

## What should we test?
* Try logging into both prod and staging on the same domain. 
* Try it in a different order.
* Try it in a browser where you've previously been logged in (the likely case for all existing users)

We need to make sure it doesn't mess up existing sessions. We can't expect all users to clear their browser cookies and try again.

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by chahmedejaz — APPROVED** [review]
Thanks for the doc references, @dacook. It looks good to me. Apparently, it was tricky to test locally because localhost doesn't get a leading period even if we set the domain as localhost. So we need to add another test domain for that in the hosts.

However, I've tested this locally, and it looks good to me. 

Image

Image

Looks great now 👍

**Comment by dacook** [comment]
Thanks for testing that Ahmed, I ran out of time last week.
I've also verified that the cookie was set without the `domain` attribute:
```
set-cookie _ofn_session_id=faa4651257a3a1f5ceb9a2f614ae7f95; path=/; HttpOnly
```

So I will just request one more review ~~before merging~~. I think we will need to merge and deploy to production before we can observe the fix.

_Edit:_ I almost forgot, I still want to test that existing login sessions aren't messed up, and that you can log out and in again without issues.

**Review by rioug — COMMENTED** [review]
Looks good 👍

**Review by rioug — APPROVED** [review]

**Comment by AMEA-LYON** [comment]
It seems impossible to check because this PR is yet not deployed on the production server,
can you suggest me a way to test ?

**Comment by chahmedejaz** [comment]
@AMEA-LYON - Are you still able to reproduce the issue after deploying to the staging server? If you do, then I believe we might have to validate this when the fix is deployed on production.

What do you think, @dacook?

**Comment by AMEA-LYON** [comment]
Yes, I reproduced it on the staging server

**Comment by chahmedejaz** [comment]
I had a quick, on staging, and it seems like the issue still persists. Let me double check by redeploying. @AMEA-LYON

**Comment by chahmedejaz** [comment]
@AMEA-LYON - I redeployed and tested, it's working for me, apparently, however, I can see why it still gets reproduced on your end. It's because the prod cookie session is still accessible to staging, and in some cases might be overriding the staging session. However, I'm sure if it gets deployed to prod, it should get fixed for both environments.

**Comment by chahmedejaz** [comment]
Just for a last check, could you please do a quick test again?

**Comment by AMEA-LYON** [comment]
I made the following actions : 
- cleaned the cookies on both sites (staging and prod)
- logged on prod : needed to perform twice so that the menu update itself
- then no way to log on staging... the menu does not update itself

See the captured screen : 

https://github.com/user-attachments/assets/18634970-fea2-4689-a56a-0d98f5ba1940

**Comment by chahmedejaz** [comment]
@AMEA-LYON - Sorry, I lost it.
Are you able to login to staging before logging in to the prod?

**Comment by AMEA-LYON** [comment]
Tests done successfully ! Congratulations !!
- tested staging then production server login after cleaning cookies : OK (with same and/or different user logins)
- tested production then staging server login after cleaning cookies : OK (with same and/or different user logins)
I found out that I had to refresh the page after cleaning the cookies so that the first login attempt succeeds immediately.

=> Ready To Go !

**Comment by dacook** [comment]
I just did a whole lot of testing and wrote some really good technical notes here, but forgot to save before quitting my browser and lost them all 😢 .

I learnt that this PR has a problem: the existing cookie with the domain will persist and override the new cookie. (That is, the old 'dot' cookie will override the new 'dotless' cookie):
Screenshot 2026-04-01 at 12 48 32 pm
This means, after logging out, you can't log back in again, until your browser session is cleared (or you delete cookies).

I suspect that most people don't log themselves out, and from what I can see, our system isn't configured to log them out after a certain time. 

When is the browser session cleared? I just tested with Chrome on macOS and found that closing the tab or the window doesn't clear it, but quitting the whole app does. 

I also suspect that a lot of people rarely quit or restart their computer. But they're the kind of people who also don't manually log out of websites.

So.. I think this will probably affect some people, but probably not the majority. If it does, it can be resolved by quitting their browser and trying again. This is still not very good, and will likely result in a few customer service calls. 


I think it could be avoided by adding a hook to clear the old cookie, so I suggest we hold until we can do that. It might be as simple as something like:
```ruby
  class UserSessionsController < Devise::SessionsController
    def create
      # Delete old domain-based cookie, if any. This may be removed once all browser sessions as of 2026-04-01 have ended (2 weeks?)
      cookies.delete :_ofn_session_id, domain: ENV['SITE_URL']
      ...
```

**Comment by mkllnk** [comment]
> I suspect that most people don't log themselves out

I suspect that there will be a significant portion of users who do though. Last time we changed cookies, Matt wrote a Rack middleware to handle the transition.

- #8090
- #8127

We could resurrect the SessionCookieUpgrader to change the domain here. Then the old cookies get transferred to the new host-only version and we can delete the old cookie there, too.

**Comment by dacook** [comment]
## Update: rename cookie
I found we needed to rename the cookie for this to work. My testing results below, but after code review it would be worth having an extra test on a different server.

### au-staging: master
1. clear cookies
2. visit homepage
3. (test A) log in

A 'dot' cookie is present, whether logged in **(A)**: 
Screenshot 2026-04-28 at 3 53 13 pm
or not **(B)**:
Screenshot 2026-04-28 at 3 52 53 pm


### (test A) au-staging: this branch
1. visit homepage. Still logged in ✅
   Cookie is updated
Screenshot 2026-04-28 at 4 06 15 pm
2. log out
3. can log in again? ✅ yep

### (test B) au-staging: this branch
Tried logging in without reloading home page.
Cookie was updated immediately, 
Screenshot 2026-04-28 at 4 09 36 pm
But it failed ❌❌ two times, then succeeded ✅
Good enough?

File: config/application.rb [hunk 1]
```diff
@@ -47,6 +50,17 @@ class Application < Rails::Application
...
+    config.middleware.insert_before(
+      ActionDispatch::Cookies,
+      SessionCookieUpgrader, {
+        old_key: "_ofn_session_id",
+        new_key: "_h-ofn_session_id",
+        domain: ENV.fetch("SITE_URL", nil),
+        attrs: { http_only: true, secure: true },
+      }
+    ) if Rails.env.staging? || Rails.env.production?
+
```
Comment (dacook) [inline config/application.rb:63]: This code was taken from an old cookie migration: https://github.com/openfoodfoundation/openfoodnetwork/pull/8090/files?w=1

And yes, that's an odd name for the new cookie. I intended to use the new more secure cookie name prefix `__Host-Http-` described here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Cookies#security
But I didn't want to add another point of failure in my testing at first, because it takes a long time to manually test on a staging server. So I didn't use the new name prefix.. at least not yet. We can try adding it to this PR if others agree.

**Review by rioug — APPROVED** [review]
Code looks good, Thanks for taking care of this tricky problem !

**Review by mkllnk — APPROVED** [review]
That login failure is odd. I repeated your tests because I wanted to know what's going on and came to the same results. The cookie rotation is working on the first request but somehow the login fails silently. Maybe there's some security thing going on. This would only affect people who are not logged in and visit the site just before the deployment and then try to log in without loading another page first. I think that we can ignore that, especially because there's a workaround and solving this issue may take a lot more time.

I think that we are good to merge.
