### PR TITLE
Orders list : save filters params 

### LINKED ISSUE #4207: 'Back' from Edit Order removes filters on Orders page
## Description

A small UX improvement such that a browsers Back buttons maintain filtering.

## Expected Behavior

1. A user filters the orders on the Orders page to find a specific set of orders.
2. They then click Edit Order to make some changes to it.
3. They save this then hit 'Back' or the button 'Back to Orders List'.
4. They're taken back to the Orders page and all of their filters are still in place meaning that I'm still shown the same set of Products as before I navigated away.

## Actual Behaviour

1. .... As above
2. .....
3. ....
4. They're taken back to the Products page but their filters have gone. They need to reload the filters, which takes time. If I'm editing dozens of orders (and I can't do it in  the BOM) I quickly get annoyed!

## Steps to Reproduce

See above.

## Context

When I have a number of changes to make to multiple orders I get quite annoyed. For large hubs this becomes unwieldy quite quickly as there are often sizeable changes to make and I can't make them on the Orders or BOM pages.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: 2.3.1
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Linux
* OFN Platform instance where you discovered the bug, and which version of the software they are using. UK

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Closes #4207
This PR save filters params in session. This is used to retrieve previously used params when clicking on "Back to orders list" or refreshing the page. 

#### What should we test?
1. Go to `/admin/orders`
2. Modify some of the filters ("Date Range", "Status", ...)
3. Click on a specific order, to view it. 
4. Then click on "Back to order list" button
5. You should go back on your Order list, with already filtered order displayed and all filters rightly prefilled.

_NB_ :
 - You could also reload the page to test that filters are well prefilled and then applied to the fetched result
 - Having another tab open on the same page means that you can have two different filters "saved": each opened tab has its own lifecycle.

https://www.loom.com/share/0dc095e5561d44c9ac25412ade49e944

#### Release notes
Save filters params in Orders list to improve navigation through orders and search.

Changelog Category: User facing changes

### CODE REVIEW

**Review by sauloperez — COMMENTED** [review]
I haven't read the code yet but isn't saving the params in the URL enough for the browser history to work? Isn't that how browsers work anyway?

**Comment by jibees** [comment]
@sauloperez Yes, it's enough for the browser back button, not for the "Back to orders list". I I could also have done `history.back()`.

File: app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee [hunk 1]
```diff
@@ -16,11 +16,41 @@ angular.module("admin.orders").controller "ordersCtrl", ($scope, $timeout, Reque
...
+    $scope.q = {}
+    ["completed_at_gteq",
+     "completed_at_lteq",
+     "state_eq",
+     "number_cont",
+     "email_cont"
+     "bill_address_firstname_start",
+     "bill_address_lastname_start"
+     ]
+    .map((paramKey) ->
```
Comment (mkllnk) [inline app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:38]: `map` is used to map all items of a list to different items of a new list. You are not using the new list though. You are iterating over the items of the list. Coffeescript provides a syntax for that: https://coffeescript.org/#loops

This is not prescriptive but maybe I would write it like this (untested):
```coffee
searchKeys = [
     "completed_at_gteq",
     "completed_at_lteq",
     "state_eq",
     "number_cont",
     "email_cont"
     "bill_address_firstname_start",
     "bill_address_lastname_start"
]
for paramKey in searchKeys when params["q["+paramKey+"]"]
  $scope.q[paramKey] = params["q["+paramKey+"]"]
```

**Review by mkllnk — COMMENTED** [review]
Nice work. :muscle: 

I'm not sure about the local storage solution. It could be a bit confusing when people work with multiple tabs because they would share the stored parameters. Can you pass the URL into the edit order pages?

**Comment by jibees** [comment]
> I'm not sure about the local storage solution. It could be a bit confusing when people work with multiple tabs because they would share the stored parameters. Can you pass the URL into the edit order pages?

I didn't think about multiple tab, you're right. I could pass a parameter to edit order pages like: `backUrl`, and then use it. I think it's much better.

File: app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee (hunk 1 above)
Comment (jibees) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:38]: I've the habit (like many others ;)) to use map as an iterator over list (and use it to run a callback/lambda over each item).

Comment (jibees) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee]: Modified!

**Comment by jibees** [comment]
@mkllnk It's now passed with a param `backURL`: 9bcb855

**Comment by jibees** [comment]
@mkllnk : 
> Without using any `backURL` param, but with a simply `window.history.back();` makes the job.

Actually no, because this page could be reached by many others page, so it should be insuffisant.


> I'm not sure about the local storage solution. It could be a bit confusing when people work with multiple tabs because they would share the stored parameters. Can you pass the URL into the edit order pages?

I wonder if localStorage might not be a better solution: if you navigate through the order, you immediately loose the information of the filters params stored in the URL.
See the first video, we only navigate 1 step deep, and everything is ok:
https://www.loom.com/share/b24d61f470ed4fce8ee54c918524e2c0

But, if we navigate through the order, then we loose the information:
https://www.loom.com/share/7786d9d8c6844683a34dbb399852c6d0

I am rather for the localStorage solution...

**Comment by mkllnk** [comment]
> if we navigate through the order, then we loose the information:

I see. So we have two options:

- Include the search params in all links of the order page OR
- use local storage.

Including the params in every link is more work with lots of clutter but it would solve the problem. Local storage can be implemented more easily but breaks with multiple tabs.

This might be a really wild idea, but I was just wondering if we can look in the browser history for the params. So whenever we link to the orders page, we go through the history to find the last visit of the orders page and use the same URL. I've never heard of that approach before. Do you think that it's difficult or would have any problems?

One caveat I can think of: If you open an order in a new tab then the new tab won't have the history. Then navigating back would lose the options. But if the user opens a new tab, they probably do that because they want to keep the old one open and go back there if they want to see the same. I think that this case is okay.

**Comment by jibees** [comment]
@mkllnk 
> Include the the search params in all links of the order page

I agree with you, it can be very annoying/difficult and error prone. I'm not in favor on this solution.

> local storage

I'm wondering if we could ask for Product team on this one? Maybe they could have an really opinion on it, and how it can be either useful or annoying. 

> looking for browser's history

As I know/I can see: 
> `window.history` allows navigation, but not access to URLs in the session for security and privacy reasons.

So, afaik, it is impossible.

BUT

Maybe I found a third (fourth ?) way for resolving this one : session storage.
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

> the difference is that while data in localStorage doesn't expire, data in sessionStorage is cleared when the page session ends.
> **Opening a page in a new tab or window creates a new session** with the value of the top-level browsing context, which differs from how session cookies work.

Seems to be the behavior we need.

I can try this one! What do you think?

**Comment by mkllnk** [comment]
> session storage.

Yes! That sounds great! :smile:

File: spec/features/admin/orders_spec.rb [hunk 2]
```diff
@@ -110,4 +110,54 @@
...
+      user = create(:user, email: 'an@email.com')
+      shipping_method = create(:shipping_method, name: "UPS Ground")
+      order = create( :order,
+                      distributor: distributor,
+                      order_cycle: order_cycle,
+                      user: user,
+                      number: "R123456",
+                      state: 'complete',
+                      payment_state: 'balance_due',
+                      completed_at: 1.day.ago)
```
Comment (mkllnk) [inline spec/features/admin/orders_spec.rb:126]: This way of formatting is brittle to change. If you rename `order` then you have to change the indent of all parameters. And if you add a parameter at the end, you need to change the current last parameter as well. This formatting is more open to change:
```suggestion
      order = create(
        :order,
        distributor: distributor,
        order_cycle: order_cycle,
        user: user,
        number: "R123456",
        state: 'complete',
        payment_state: 'balance_due',
        completed_at: 1.day.ago,
      )
```

File: spec/features/admin/orders_spec.rb [hunk 3]
```diff
@@ -110,4 +110,54 @@
...
+
+      page.find('a.icon-search').click
+
+      page.driver.refresh
+
+      # Check every filters to be equal
+      expect(find_field("Only show complete orders")).not_to be_checked
+      expect(find_field("Invoice number").value).to eq "R123456"
+      # expect(find("#s2id_q_order_cycle_id_in").text).to eq order_cycle.name
+      # expect(find("#s2id_q_distributor_id_in").text).to eq distributor.name
```
Comment (mkllnk) [inline spec/features/admin/orders_spec.rb:153]: What are these comments?

File: spec/features/admin/orders_spec.rb (hunk 2 above)
Comment (jibees) [reply spec/features/admin/orders_spec.rb:126]: Yes, you're right, will squash it ;)

File: spec/features/admin/orders_spec.rb (hunk 3 above)
Comment (jibees) [reply spec/features/admin/orders_spec.rb:153]: This was an old comment: I was unable to verify that these two fields were filled in correctly.
Will delete the comments anyway.

**Review by andrewpbrett — APPROVED** [review]
This isn't really my area of expertise, but it seems pretty sensible, so if it's solving the problem it looks good to me! Are we just waiting on a second review?

**Comment by jibees** [comment]
@andrewpbrett 
> Are we just waiting on a second review?

Yes, I'll appreciate.

File: app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee [hunk 4]
```diff
@@ -15,12 +15,51 @@ angular.module("admin.orders").controller "ordersCtrl", ($scope, $timeout, Reque
...
+     "email_cont"
+     "bill_address_firstname_start",
+     "bill_address_lastname_start"
+     ]
+    for key in searchKeys when params["q["+key+"]"]
+      $scope.q[key] = params["q["+key+"]"]
+
+    # Special for arrays 'distributor_id_in' and 'order_cycle_id_in'. Arrays of arrays: q[params][]
+    for key in ["distributor_id_in", "order_cycle_id_in"] when params["q["+key+"][]"]
+      $scope.q[key] = params["q["+key+"][]"]
```
Comment (Matt-Yorkley) [inline app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: These "special cases" look pretty wild. I imagine if we touch anything related to these filters it will be quite likely this could break.

Is there no simpler way to store and retrieve this data without having to go through every key-value pair and re-write it explicitly?

Comment (Matt-Yorkley) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: The issues is: we have 4 different sources of truth now for the filters (the url params, the form elements, the angular variables, the localstorage) and the complexity in transferring that truth (state) between each place is getting really high.

Comment (jibees) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: Yes, I understand your point. It's always painful when we are facing multiple source of truth.

I inherit from this "special cases" which were here before I try to add this feature.

Comment (Matt-Yorkley) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: If we ignored the URL params and just focused on the variables in Angular and the data that's being stored in localStorage, could we simplify this? Like...

What happens if when we submit the form, we take the value of `$scope.q` and persist that in localStorage, then when we load the page we fetch it from localStorage and replace it in `$scope.q`?

Comment (jibees) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: Why I've done both URL and localStorage:

 - Removing URL params stuff, could be great for developer experience and for futur debug/code comprehension, but I wanted also to make it clear for a user point of view. As a user, I always prefer having params in URL when I load a page to understand that filters are already filled and therefore that results are already filtered. But maybe I'm not a "basic" user. 

 - Furthermore, the aim of localStorage here is _only_ to rebuild the URL used in the "Back to order list" button:
```haml
%a.button.icon-arrow-left{icon:  'icon-arrow-left', ng: { href: admin_orders_path + "{{ '#' + getStoredFilters() || '' }}"}}
```
If we decide to trust the localStorage (and only the localStorage), we also have to invalidate it.
When we arrive to this page from another way (ie. bu clicking on the "Orders" menu that leads you to `http://localhost:3000/admin/orders`), we have to ignore localStorage (and delete it). Dealing with URL building thanks to localStorage and order_controller in the "Back to order list" is way way simpler to me

Comment (Matt-Yorkley) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: For example, we could do something like this: https://github.com/jibees/openfoodnetwork/compare/4207-add-query-params-in-url...Matt-Yorkley:order-filters?expand=1

...then there's no need to manually mangle the data, and all the logic is simple and 100% re-usable in other contexts.

Comment (Matt-Yorkley) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: > If we decide to trust the localStorage (and only the localStorage), we also have to invalidate it.

It gets cleared when the browser is closed, right? That's probably enough.

Comment (jibees) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: > It gets cleared when the browser is closed, right? That's probably enough.

Yes it is, but I'm almost sure it's not enough. The only way to get the filter reinitialized once you go to /orders is to do it _by hand_, one by one. I don't think it's this is satisfactory

Comment (jibees) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: > For example, we could do something like this:...

I will check, thanks! 🙏

Comment (Matt-Yorkley) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: > The only way to get the filter reinitialized once you go to /orders is to do it by hand, one by one.

Yeah it really feels like it needs a button to clear all filters...

Comment (jibees) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: I think it's more a question about UX / product decision no?

Comment (jibees) [reply app/assets/javascripts/admin/orders/controllers/orders_controller.js.coffee:46]: > > For example, we could do something like this:...
> 
> I will check, thanks! 🙏

yes, much cleaner. I wonder if there is an opportunity to mix your solution with mine and having such a `QueryInURLPersistence` service.

**Comment by jaycmb** [comment]
Session storage sounds like a good solution to me to save the filters when going back and forth within the session.

**Comment by jibees** [comment]
@jaycmb 
> But as far as I understand that solution had at the same time the effect that the filters always stay, and the user needs to clear them one by one?

Yes.

**Comment by andrewpbrett** [comment]
Should this move back to In Dev @jibees? Or do we want to proceed with it as it is?

**Review by sauloperez — COMMENTED** [review]
is there any obvious reason that made us rule out moving the filters to server-side thus making a full page reload every time filters are changed? AFAIK that would mean we have a URL with a different query string for each and the browser would keep that in the history without having to end up with complex solutions.

**Comment by jibees** [comment]
> thus making a full page reload every time filters are changed?

Maybe because of this, and also because it is already managed in the frontend.

**Comment by sauloperez** [comment]
> it is already managed in the frontend.

well, it may mean more work but it's not rocket science, it's the plain old web. What we're seeing here is quite a lot of effort plus considerable complexity and duplication. I just wanted to raise a flag. Have we explored that anyway?

**Comment by mkllnk** [comment]
Filtering server-side doesn't solve the problem of remembering the parameters though.

**Comment by sauloperez** [comment]
Even if they are part of the URL's query string? 🤔

**Comment by Matt-Yorkley** [comment]
> Even if they are part of the URL's query string?

That would work with the "back" button, but here we essentially want to store those selections in the user's session and restore them after they return to the page _without_ using the back button.

**Comment by jibees** [comment]
@sauloperez @mkllnk @Matt-Yorkley
Should we go with the @Matt-Yorkley solution? ie. saving filters into sessionStorage and adding a button to clear all filters?

**Comment by Matt-Yorkley** [comment]
I submitted that [PR](https://github.com/jibees/openfoodnetwork/pull/3) with the suggested alternative. The main bit I'm concerned with is deleting these ~40 lines (and replacing them with 4):

https://github.com/jibees/openfoodnetwork/compare/4207-add-query-params-in-url...Matt-Yorkley:order-filters?expand=1#diff-de9b31ca4e2c4ac2a72322f888c1eb446c095d469d846669eec94fab32288e3fL24-R25

**Comment by mkllnk** [comment]
That's great work, @Matt-Yorkley. The more generic solution is so much more maintainable. What do you think about using session storage instead of local storage? That would limit the storage to the current tab and you can have different filters in different tabs without interference.

**Comment by jibees** [comment]
> What do you think about using session storage instead of local storage?

Yes, I guess it's a good idea.

**Comment by jibees** [comment]
@Matt-Yorkley Should I merge your PR (https://github.com/jibees/openfoodnetwork/pull/3) into my branch, and then squash/modify git history on this one? 
I can manage the session storage (instead of locale storage) and I will add a clear filters button.

**Comment by jibees** [comment]
@mkllnk 
> What do you think about using session storage instead of local storage? 

Actually, It's already done ;) 

https://github.com/jibees/openfoodnetwork/pull/3/files#diff-574585bf4ebad7045363bf0d72e2a478640197a202225c1c99e0f740c81c7162R7
```ruby
localStorageService.setStorageType("sessionStorage")
```

**Comment by mkllnk** [comment]
Yay, Matt, go! :rocket:

**Comment by mkllnk** [comment]
> Actually, It's already done ;)
> 
> https://github.com/jibees/openfoodnetwork/pull/3/files#diff-574585bf4ebad7045363bf0d72e2a478640197a202225c1c99e0f740c81c7162R7
> 
> localStorageService.setStorageType("sessionStorage")

Do we have only one global entity of `localStorageService` in Angular and we can only use session storage or local storage? That would be a bad limitation.

File: app/assets/javascripts/admin/services/query_persistence.js.coffee [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+      unless _.isEmpty(storedFilters)
+        for k,v of storedFilters
+          scope[k] = v
+
+        return true
+
+      false
+
+    clearFilters: () ->
+      localStorageService.remove(@storageKey)
```
Comment (luisramos0) [inline app/assets/javascripts/admin/services/query_persistence.js.coffee:30]: I dont think this class should be specific to filters. I'd rename most of the variables and methods to make it a generic LocalStorage KeyValueMapStore, the code is exacly the same (I just used a guard clause on restoreValues method to make it simpler):

```js
angular.module("admin.indexUtils").factory 'KeyValueMapStore', (localStorageService)->
  new class KeyValueMapStore
    localStorageKey: ''
    storableKeys: []

    constructor: ->
      localStorageService.setStorageType("sessionStorage")

    getStoredKeyValueMap: ->
      localStorageService.get(@localStorageKey) || {}

    setStoredValues: (source) ->
      keyValueMap = {}
      for key in @storableKeys
        keyValueMap[key] = source[key]
      localStorageService.set(@localStorageKey, keyValueMap)

    restoreValues: (target) ->
      storedKeyValueMap = @getStoredKeyValueMap()

      return false unless _.isEmpty(storedKeyValueMap)  
      
      for k,v of storedKeyValueMap
       target[k] = v

      return true

    clearKeyValueMap: () ->
      localStorageService.remove(@localStorageKey)


```

Comment (luisramos0) [reply app/assets/javascripts/admin/services/query_persistence.js.coffee:30]: One way or another this is a nice and easy class to add some js unit tests.

Comment (jibees) [reply app/assets/javascripts/admin/services/query_persistence.js.coffee]: I think it's a very relevant idea, and commit 7008b5ec7 should take into account your comments ;) Thanks! 🙏

Comment (luisramos0) [reply app/assets/javascripts/admin/services/query_persistence.js.coffee]: awesome :ok_hand:

**Comment by jibees** [comment]
@luisramos0 I've addressed your comments. Feel free to move into `Test Ready` column, if you think so ;)

**Comment by jibees** [comment]
As it has two approvals, moving to `Test Ready` ;)

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Very interesting functionality!

i) I've went through the testing steps you proposed, and it works - after setting some filters:
- viewing an order
- visiting other pages within `/admin` (ex. `/order_cycles`)

And then re-visiting the /orders page displays the previously set filter :tada: 

ii) checked the multi-tab setting of filters: it works as you pointed out. The "life-cycles" are independent

iii) removing the filters:
- clicking "Clear filters" works - also introduced in this PR
- logging out and back in
- visiting a non `/admin` page (like `/account`)

iv) sanity check - Setting up different filters and options should work as before
I've noticed a small regression:
- if the option "Only show completed orders" is ticked, then orders in state "Complete" will not be displayed. Below: left, before this PR; right, this PR:




So, not sure how to proceed. Maybe not great to introduce regressions? Should  I move back to In Dev? It does introduce improvements! What do you think @openfoodfoundation/train-drivers-product-owners ?

**Comment by kirstenalarsen** [comment]
This is cool :)

Can’t see image, but if understanding text correctly this would be unacceptable regression and would need to be fixed immediately - default is that that box ‘only show completed’ is ticked and it is the orders with state Complete that we need to see. If we introduced this and they disappeared there would be MASS confusion and angst

**Comment by filipefurtad0** [comment]
Thanks for pointing that out @kirstenalarsen , my bad: it is when the box is **un-ticked** that the "complete" orders disappear. The pic should be visible now. With this box unticked we currently display both complete and orders in all other states.

Edited the previous message.

**Comment by kirstenalarsen** [comment]
ok, that's less disastrous ;) I would prefer to see it fixed as part of this PR if possible

**Comment by jibees** [comment]
Thanks for that @filipefurtad0 : this is clearly a regression, and needs to be fixed as @kirstenalarsen said. Will do.
Back to `In Dev`

**Comment by jibees** [comment]
I've only added one commit with its feature test. Green is build, @filipefurtad0 will test. I guess there's no need to go through `Code Review` step.
Moving to `Test Ready` then.

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Thanks for the quick fix and adding the feature spec :tada: 
This looks good now:

Peek 2021-06-18 08-32

Let's get it in into the release :+1

**Comment by kirstenalarsen** [comment]
Awesome :)
