### PR TITLE
Admin updates can trigger new backorders until the order cycle is closed

### LINKED ISSUE #13056: NoMethodError in AmendBackorderJob@default
## Error in Open Food Network (Rails)

**NoMethodError** in **AmendBackorderJob@default**
undefined method `lines' for nil:NilClass

    order.lines.find do |line|
         ^^^^^^

[View on Bugsnag](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/6762e3218ff8640a044ecfb6?event_id=6769ae62010df00650850000&i=gh&m=ci)

## Stacktrace

    app/services/fdc_backorderer.rb:111 - find_order_line
    app/services/fdc_backorderer.rb:90 - find_or_build_order_line
    app/services/backorder_updater.rb:60 - block in update_order_lines
    app/services/backorder_updater.rb:57 - map
    app/services/backorder_updater.rb:57 - update_order_lines
    app/services/backorder_updater.rb:45 - update
    app/services/backorder_updater.rb:31 - amend_backorder
    app/jobs/amend_backorder_job.rb:24 - amend_backorder
    app/jobs/amend_backorder_job.rb:19 - block in perform
    app/services/order_locker.rb:18 - block in lock_order_and_variants
    app/services/order_locker.rb:16 - lock_order_and_variants
    app/jobs/amend_backorder_job.rb:18 - perform

[View full stacktrace](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/6762e3218ff8640a044ecfb6?event_id=6769ae62010df00650850000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #13056 

We had a case when an order was updated after the order cycle closed. The backorder amendment failed because the backorder was completed already. We now handle this gracefully by skipping the amendment. But if the order cycle is still open or will open then we can actually create a new backorder. We can assume that the order cycle hasn't had a backorder yet.

#### What should we test?

- Have an upcoming or open order cycle with FDC products.
- Place an order as admin for that order cycle with FDC products.
- A backorder in Shopify should be created.
- After the order cycle closed, update one of the orders in OFN.
- No new backorder should be created.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by RaggedStaff** [comment]
I'm away at orfc,  so won't ba able to test this till next week. 

I'm also a bit confused @mkllnk - I thought you said (in the issue) we couldn't create a new back order when the order cycle is closed. 😕 did you figure out a way to track the order number?

**Comment by mkllnk** [comment]
> I'm away at orfc, so won't ba able to test this till next week.

Okay, maybe we can test it then.


> I'm also a bit confused @mkllnk - I thought you said (in the issue) we couldn't create a new back order when the order cycle is closed. 😕 did you figure out a way to track the order number?

There's no technical limitation in creating backorders. And this pull request only creates backorders for order cycles before they close. After they close, we can assume that a backorder was placed and completed and then we shouldn't create a second one. But before the close time, it's okay.

**Comment by mkllnk** [comment]
> I'm away at orfc, so won't ba able to test this till next week.

Actually, next week is fine. We won't have complete code review until next week either.

File: app/services/backorder_updater.rb [hunk 1]
```diff
@@ -28,7 +28,7 @@ def amend_backorder(order)
 
     backorder = orderer.find_open_order(order)
 
-    update(backorder, user, distributor, order_cycle)
+    update(backorder, user, distributor, order_cycle) if backorder
```
Comment (dacook) [inline app/services/backorder_updater.rb:31]: I guess it amounts to the same thing, but I thought that we usually avoid implied booleans and use the more explicit `present?`

But i'm sure it amounts to the same thing, and this looks cleaner so I like it :)

File: spec/jobs/amend_backorder_job_spec.rb [hunk 2]
```diff
@@ -130,5 +130,32 @@
...
+
+      # We ordered a case of 12 cans: -3 + 12 = 9
+      expect(beans.on_hand).to eq 9
+
+      # Stock controlled items don't change stock in backorder:
+      expect(chia_seed.on_hand).to eq 7
+
+      expect(backorder.lines[0].quantity).to eq 1 # beans
+      expect(backorder.lines[1].quantity).to eq 5 # chia
+    end
```
Comment (dacook) [inline spec/jobs/amend_backorder_job_spec.rb:159]: Nice work, that's a tricky one to test. I guess the only other way would be to use VCR.

**Review by dacook — APPROVED** [review]
👍  Great fix

**Review by rioug — APPROVED** [review]
Nice one !

**Comment by RaggedStaff** [comment]
So I tested this & got an error email (Back Order failed) when I submitted an [Order](https://staging.openfoodnetwork.org.uk/admin/orders/R271443873/edit) (via the admin interface) after OC close.

I thought that wasn't supposed to happen now? 😕

**Comment by rioug** [comment]
Probably related : https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/67866e61bd74ea48476c29a8?event_id=67866e6101101a23afe10000&i=sk&m=nw

**Comment by mkllnk** [comment]
> I tested this & got an error email (Back Order failed) when I submitted an [Order](https://staging.openfoodnetwork.org.uk/admin/orders/R271443873/edit) (via the admin interface) after OC close.

Argh! I was so focused on the amending part that I forgot that the old initial backorder method is called whenever an order is finalised. I can add a check there or maybe make sure that it's only called during customer-facing checkout.

**Comment by RaggedStaff** [comment]
@mkllnk - I started testing this... got a [NoMethodError on the BackOrder job](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/678929cf5c25065c140018aa?filters[error.status]=open&filters[event.since]=30d) (which I started manually through sidekiq). 

I think it's related to removing a Product (Dulse flakes) from the Shopify DFC app before OC completion (long story, wasn't intentional on my part 🙄 ). It would be good if we could handle that more gracefully (users being what they are 🤨 ). Could we include in the error handling issue? Also happy to put it in a separate issue & prioritise (medium/low) 

Anyway, The admin interface still shows Test OC 24 as Open, so not sure I can validly test this. 😕

**Comment by mkllnk** [comment]
Hm, I fixed that Bugsnag issue but now I just get a server error 500 from the Shopify API. Going through the OFN orders I think that the Shopify order would be adjusted to just one case of Balsamic which should be a valid order. I don't know why it fails.

**Comment by mkllnk** [comment]
Digging into the stack trace it looks like I get the error when trying to retrieve the catalog. Maybe the token is expired? Oh, David was testing yesterday...

I tried reconnecting but I wonder if the Shopify app is missing a valid token. Is that something I can check myself? A 500 error is really not great there either.

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Review by dacook — APPROVED** [review]
Very nice 👍  
Sorry I think I forgot to submit this yesterday.

**Review by mkllnk — COMMENTED** [review]
I consider this tested now. Merging.
