### PR TITLE
Fixed inconsistency with display of unit name for products sold by item

### LINKED ISSUE #8495: Editing unit names is not correctly applied on shopfront
## Description

If you edit a unit name on a product sold by item, the shopfront does not display the unit name correctly everywhere. 

## Expected Behavior

Unit name is coherent

## Actual Behaviour

Only unit names on unit price is correctly edited.

## Steps to Reproduce

1. Change the unit name of a product already sold by item
2. See how the change is applied on the shopfront

## Animated Gif/Screenshot

An example in staging: 

In production (the user first save the product and made a mistake, now impossible to change it): 

## Workaround

I can't see one, hence s2.

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v.4.1.7
* Browser name and version: Firefox and chrome
* Operating System and version (desktop or mobile): Both

### PR DESCRIPTION
**Pull request by apricot12**
#### What? Why?

Closes #8495 

This PR fixes the bug where an update to the "Unit name" for products with the "Variant unit" set as "Items" does not reflect in shop front.

**Before :** 

Screenshot 2021-11-18 at 12 43 01 PM

**After :**

Screenshot 2021-11-18 at 12 43 58 PM

#### What should we test?

- Pricer per unit and Variant unit should be the same in shopfront after an update to unit name in back office.

#### Release notes
- Fixed inconsistency with update of unit name for product sold per item in shopfront.

Changelog Category: User facing changes

### CODE REVIEW

File: app/services/variant_units/variant_and_line_item_naming.rb [hunk 1]
```diff
@@ -71,6 +71,8 @@ def unit_to_display
 
       return variant.display_as if variant_display_as?
 
+      return product.variant_unit_name if product.variant_unit_scale == nil
```
Comment (mkllnk) [inline app/services/variant_units/variant_and_line_item_naming.rb:74]:
```suggestion
      return product.variant_unit_name if product.variant_unit_scale.nil?
```

**Review by mkllnk — COMMENTED** [review]
This is connected to an urgent issue. So I'm tempted to approve it straight away but it's missing a spec.

**Comment by apricot12** [comment]
@mkllnk That should do it? I;ve updated the spec for unit_to_display method.

File: spec/models/spree/variant_spec.rb [hunk 2]
```diff
@@ -589,10 +589,14 @@ module Spree
...
           v = build_stubbed(:variant)
           v1 = build_stubbed(:variant, display_as: "")
+          p = create(:simple_product, variant_unit_name: "items")
+          v2 = build_stubbed(:variant, product: p)
           allow(v).to receive(:options_text).and_return "ponies"
           allow(v1).to receive(:options_text).and_return "ponies"
+          allow(v2).to receive(:options_text).and_return "ponies"
           expect(v.unit_to_display).to eq("ponies")
           expect(v1.unit_to_display).to eq("ponies")
+          expect(v2.unit_to_display).to eq("ponies")
```
Comment (mkllnk) [inline spec/models/spree/variant_spec.rb:599]: This example seems unrelated to your code change. Your added code above handles `variant_unit_name` and `variant_unit_scale` which is not tested by this spec.

When you address a bug, it's best to write a spec that failing with the buggy code and then passes with your fixed code. A nice introduction to Test Driven Development is an old RailsCast episode: http://railscasts.com/episodes/275-how-i-test

I think that you chose the right spec file and roughly the right location but it would be nice to see a new example `it "displays the variant unit name if there is no unit scale" do`.

**Review by jibees — APPROVED** [review]
LGTM

**Comment by filipefurtad0** [comment]
Hey @apricot12 ,

Went through the following scenarios:

Tests regarding the bug fix:
- Created **an Items product**, with unit name = "box"
- Checked how it looks like in the shop-front - both product description and unit price display the same unit -> OK
- Changed the unit name to "bag" [note]
- Verified the change is consistent in the shop-front -> OK

[note] There are two places in the app in which we can change unit name:
- `/admin/products`
- `/admin/products/<product_name>/variants/<variant_id>/edit`

I've checked these for consistency with the above steps.

Regression tests
- Created **a kg product**
- repeated the above procedure (i.e. changing to items and back)

- Created **a liter product**
- repeated the above procedure (i.e. changing to items and back)

All good, thanks for this fix!
