### PR TITLE
Datetimepicker for order cycles: add keyup event listener on hour/minute inputs

### LINKED ISSUE #7689: Changes made to Order Cycle not captured by 'Save' if Date Picker is open
## Description

Final edits made to a cloned order cycle on the order cycle admin page ( https://openfoodnetwork.org.uk/admin/order_cycles ) are not captured by 'Save' if the date picker is open.

This results in order cycles opening and closing at non-desirable times.

## Expected Behavior

Clone an order cycle.
Edit the name, open and close date and time as shown in video below.
Click 'Save' while the date picker is still open.
All edits made are captured.

## Actual Behaviour

Clone an order cycle.
Edit the name, open and close date and time as shown in video below.
Click 'Save' while the date picker is still open.
The final edit made to the order cycle (in the case of the video it is the minutes in the closing time) is not captured.

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

https://user-images.githubusercontent.com/45104035/119632573-d6effd00-be08-11eb-9a09-84408580289f.mp4

## Workaround

Close the date picker before clicking 'Save'

## Severity

S4

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #7689 

The idea here is simply to watch for `keyup` event into the two input fields (for hour and minute) and then set the flatpickr  date (and triggering the `onChange` event). Therefore, once a user use the keyboard to change the hour/minute of the date, the original-linked input is synchronized, and the global form could be saved without closing the datetimepicker (which was the original issue)

#### What should we test?
1. Go to `admin/order_cycles`
2. Open a datetimepicker (for `open` or `close` field)
3. Change the minute (or hour, or both) by typing the value with your keyboard (not by clicking the arrow which should be always functional)
4. You should see that the original-linked input is synchronized and the red `Save` button appear to save it
5. Click on save, reload. You should that the date is _effectively_ saved.

#### Release notes
Save the datetimepicker hour/minute values when user enter value with keyboard.

Changelog Category: User facing changes

### CODE REVIEW

File: spec/features/admin/order_cycles/simple_spec.rb [hunk 1]
```diff
@@ -604,6 +604,17 @@
...
+  scenario "modify the minute of a order cycle with the keyboard, check that the modifications are taken into account" do
+    order_cycle = create(:simple_order_cycle, name: "Translusent Berries")
+    login_as_admin_and_visit admin_order_cycles_path
+    expect(page).to have_selector "tr.order-cycle-#{order_cycle.id}"
+    find("#oc#{order_cycle.id}_orders_close_at").click
+    datetime = Time.at(Time.zone.local(2040, 10, 17, 0o6, 0o0, 0o0))
+    input = find(".flatpickr-calendar.open .flatpickr-minute")
+    input.send_keys datetime.strftime("%M").to_s.strip
+    expect(page).to have_content "You have unsaved changes"
+  end
```
Comment (sauloperez) [inline spec/features/admin/order_cycles/simple_spec.rb:616]: this might be my personal preference but I prefer to split this big block. I tend to keep the various `expect` calls separate together with their own setup.

**Review by sauloperez — APPROVED** [review]

File: spec/features/admin/order_cycles/simple_spec.rb (hunk 1 above)
Comment (jibees) [reply spec/features/admin/order_cycles/simple_spec.rb:616]: Actually, this line:
```ruby
expect(page).to have_selector "tr.order-cycle-#{order_cycle.id}"
```
is a bit superfluous (as it is already tested elsewhere). 
Thus, this block as only one `expect()`. What do you think then?

Comment (sauloperez) [reply spec/features/admin/order_cycles/simple_spec.rb:616]: that's even better.

**Review by sauloperez — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]
Nice!

**Comment by filipefurtad0** [comment]
Hey @jibees ,

I could not exactly reproduce the bug. The video on the issue shows quite an extreme lag between actions and response on the browser - I'm really hoping that's rather due to bad internet connection :crossed_fingers: (instead of performance issues). But in any case, the changes are saved, after the datetimepicker is closed... 

That said, below we can check a server without this PR staged (left) and another window with this PR (right). We are inspecting both input fields on the console:

Peek 2021-06-08 16-09

We can see, that before this PR, we need to close the Date-time-picker in order for the changes to take effect, and then hit "Save"; after staging this PR, the changes on the Date-time-picker are displayed simultaneously on the Open/Close fields, so this PR is having the expected behavior.

It should be noticed though that it is possible to trigger NaN errors, if one introduces invalid values on the date-time-picker:

https://app.bugsnag.com/yaycode/open-food-network-js-uk/errors/60bf7e863b3231000833fcd0?event_id=60bf7e86007d12d59d4a0000&i=sk&m=nw

I don't think this is a big issue (not sure this is an issue at all) just pointing out that it's there, as this was not the case before this PR (comparison below):

Peek 2021-06-08 16-11

This does not break the calendar or dates, so I think we're good? I'd say this is good to go :+1:

**Comment by jibees** [comment]
Thans a lot @filipefurtad0 !

I think it's worth it to open an issue to be more strict on it. But I'd say this is good to go too!

**Comment by filipefurtad0** [comment]
Thanks for feedback @jibees , opened #7763 :+1:
