### PR TITLE
Include voucher tax adjustment in revenues by hub report

### LINKED ISSUE #11774: [Vouchers] [Reports] Include vouchers in report: Revenues by Hub
## Description

When vouchers are applied in orders, then reports must display the discounted values of products, enterprise fees, and their corresponding taxes. 
Until now, many reports still show the numbers without taking vouchers into account.
The numbers have to be updated foll all tax scenarios:
- no taxes apply,
- taxes are included in price,
- taxes are added on top of price.

## Expected Behavior

These are the correct values for orders with tax incl. in price (including the voucher discount):
image

## Actual Behaviour

Incorrect values (10 % voucher not considered)
image

## Steps to Reproduce

1. Set up an enterprise with vouchers and taxes.
2. Place three orders (without tax, with tax incl. in price and with added tax).
3. Run the report.
4. Check the numbers (compare to order details and adjustments in back office).

## Animated Gif/Screenshot

See above.

## Workaround

None.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by bmd08a1**
#### What? Why?

- Closes #11774

- Include voucher tax adjustments on Revenues by hub report
- Solution proposed:
  - Build tax data of grouped orders (by distributor id):
  - orders.total_included_tax: orders.sum(&:total)
  - orders.total_tax: orders.sum(&:total_tax) + orders.voucher_tax_adjustments
  - orders.total_excluded_tax: orders.total_included_tax - orders.total_tax

#### What should we test?

- Set up an enterprise with vouchers and taxes.
- Place three orders (without tax, with tax incl. in price and with added tax)
- Run the report.
- Check the numbers (compare to order details and adjustments in back office).

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/reports/revenues_by_hub_spec.rb [hunk 1]
```diff
@@ -10,22 +10,67 @@
...
+
+    allow(VoucherAdjustmentsService).to receive(:new) do |order_arg|
+      if order_arg.id == order.id
+        next double(voucher_included_tax: 0.0, voucher_excluded_tax: 0.0)
+      elsif order_arg.id == order_with_voucher_tax_included.id
+        next double(voucher_included_tax: 0.5, voucher_excluded_tax: 0.0)
+      elsif order_arg.id == order_with_voucher_tax_excluded.id
+        next double(voucher_included_tax: 0.0, voucher_excluded_tax: -0.5)
+      end
+    end
```
Comment (mkllnk) [inline spec/system/admin/reports/revenues_by_hub_spec.rb:67]: This is too much mocking. We should set up real data.

File: spec/system/admin/reports/revenues_by_hub_spec.rb [hunk 2]
```diff
@@ -10,22 +10,67 @@
...
+
     login_as_admin
     visit main_app.admin_report_path(report_type: 'revenues_by_hub')
   end
 
-  context "testing report" do
+  context "testing report", aggregate_failures: true do
```
Comment (mkllnk) [inline spec/system/admin/reports/revenues_by_hub_spec.rb:73]: Nice, I didn't know that option.

**Review by mkllnk — CHANGES_REQUESTED** [review]
Thank you for working on this. Can you improve the spec setup?

File: spec/system/admin/reports/revenues_by_hub_spec.rb (hunk 1 above)
Comment (rioug) [reply spec/system/admin/reports/revenues_by_hub_spec.rb:67]: Especially in system spec, we want to test scenarios as close as possible to what a user would experience.

You can have a look here to see how to set up data and apply a voucher to an order : https://github.com/openfoodfoundation/openfoodnetwork/blob/f6ba2dc70c0063d93f907ce4948de20af4b120a2/spec/system/consumer/checkout/summary_spec.rb#L410 
It's a bit tricky to put everything in place, let us know if you need some help.

File: spec/system/admin/reports/revenues_by_hub_spec.rb [hunk 3]
```diff
@@ -10,22 +10,67 @@
...
+  end
+  let(:order_with_voucher_tax_excluded) do
+    create(
+      :order_with_taxes,
+      completed_at: 2.days.ago,
+      order_cycle:,
+      distributor: distributor3,
+      product_price: 110.0,
+      tax_rate_amount: 0.1,
+      included_in_price: true,
```
Comment (rioug) [inline spec/system/admin/reports/revenues_by_hub_spec.rb:36]: It should be `included_in_price: false` to get tax excluded from price. In this case it's not affecting the result as you are mocking `VoucherAdjustmentsService`

**Review by rioug — COMMENTED** [review]
Thanks for looking at this ! Vouchers can be a bit tricky to understand let us know if you need some help.

File: spec/system/admin/reports/revenues_by_hub_spec.rb (hunk 1 above)
Comment (bmd08a1) [reply spec/system/admin/reports/revenues_by_hub_spec.rb:67]: ye okay, let me take a look. I'm a bit busy in weekdays so I'm gonna update it in weekends

File: spec/system/admin/reports/revenues_by_hub_spec.rb [hunk 4]
```diff
@@ -153,13 +137,21 @@
...
+
+  def apply_voucher(order, voucher)
+    voucher.create_adjustment(voucher.code, order)
+
+    # Update taxes
+    order.create_tax_charge!
+    order.update_shipping_fees!
+    order.update_order!
+
+    VoucherAdjustmentsService.new(order).update
```
Comment (rioug) [inline spec/system/admin/reports/revenues_by_hub_spec.rb:155]: You need to add `order.update_totals_and_states` after `VoucherAdjustmentsService.new(order).update` otherwise the various order total won't take into account the voucher adjustment you just updated.

**Review by rioug — CHANGES_REQUESTED** [review]
Just one last thing, see my comment.
Also. we prefer to rebase the branch on master instead of merging.

Thanks !

File: spec/system/admin/reports/revenues_by_hub_spec.rb (hunk 4 above)
Comment (bmd08a1) [reply spec/system/admin/reports/revenues_by_hub_spec.rb:158]: thanks, I updated the specs as you suggested

**Review by rioug — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @bmd08a1,
Thank you for this important fix! :muscle: 

I did some testing and here are the results.

Each order had a value of 10 $, tax (if applied) was 10 %, fees (if applied) were 10 %, voucher (always applied) was 10 %.

I placed three orders before staging your PR:
- without tax,
- with added tax,
- with included tax.

After staging the PR I placed some orders again:
- same three orders as before,
- additional orders to check shipping fees and enterprise fees.

## Results
### No tax
Before:
image
After:
image

### Tax excluded
Before:
image
After:
image

### Tax included
Before:
image
After:
image

### Total of all three orders
Before:
image
After:
image

### With 1 $ shipping fee (no tax)
After - No tax:
image
After - Tax excl.:
image
After - Tax incl.:
image

### Additional enterprise fee of 10 % (tax applies)
After - Tax excl.:
image

# Summary

Excellent work! :muscle: I couldn't find any issues with this. There are more complex scenarios for sure, but I tried to cover it systematically.

This one is ready for merging! :tada: :rocket: 
Thanks again!!!
