### PR TITLE
Fix unit description UI issue on updating a Product having imperial weight (oz)

### LINKED ISSUE #9679: Weird decimals when using 1234.5 or 1234.6 as weight in imperial metric system
## Description

Similar to #9493
When adding 1234.5 or 1234.6 as product weight in an imperial (oz) system, ends up with a huge number of unnecessary decimals on page /admin/products.

## Expected Behavior

Just keep 1234.5 or 1234.6 - no additional decimals.

## Actual Behaviour

image

## Steps to Reproduce

1. Create or edit a product with weight in oz
2. Enter 1234.5 or 1234.6
3. Save
4. :boom: 

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: staged [498d003](https://github.com/openfoodfoundation/openfoodnetwork/commit/498d0036841b726b380eb1483218299725383231)
* Browser name and version: Firefox 104.0
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

## Possible Fix

See #9497?

### PR DESCRIPTION
**Pull request by saunmanoj888**
#### What? Why?

Closes #9679

##### Screen Recording
[unit_value_issue.webm](https://user-images.githubusercontent.com/62114687/196766985-0dece014-1795-48bd-8517-e3cc6950a685.webm)

##### Solution Proposed
When we create a Product with imperial weight as (oz), column `unit_with_scale` under Product is saved with value `28.35`
It simultaneously creates a Variant  associated with the Product. The variant has a column `unit_value` which is also set to `28.35`

Now in the UI of products page  we see the `unit_description` as `1`. Please refer the ss below
unit_description

Now when user updates this `unit_description` to `1234.5`, following calculation occur

The `unit_value` of Variant is calculated as `unit_description * unit_with_scale ` i.e  `1234.5 * 28.35` that is equal to `34998.075000000004`, this gets saved in the DB

Now again via JS the updated `unit_description` is calculated using below formaula
```
 divideAsInteger: (a, b) ->
      (a * 1000000000) / (b * 1000000000)
```
this code is present in `app/assets/javascripts/admin/services/bulk_products.js.coffee`
which returns
 
```
(34998.075000000004 * 1000000000) / (28.35 * 1000000000) = 
1234.5000000000002
```

Hence to resolve the above issue, the multiplication and division we do, result is being rounded off upto 8 deciaml places and then trailing zeroes are being removed i.e `parseFloat(number.toFixed(8))`
Now the calculation looks like
The `unit_value` of Variant is calculated as `unit_description * unit_with_scale ` i.e  `1234.5 * 28.35` = `34998.075`

`unit_description` is calculated as
```
(34998.075 * 1000000000) / (28.35 * 1000000000) =
1234.5
```

#### What should we test?
 - Create or edit a product with weight in oz
 - Enter 1234.5 or 1234.6
 - Save

#### Release notes
Changelog Category: User facing changes

#### Dependencies
No dependencies

### CODE REVIEW

**Comment by saunmanoj888** [comment]
hii @jibees @mkllnk 
I have added the proposed solution reason in detail in the description of the PR. Can you please go through it and let me know if this solution looks good or if I need to make some other changes.
Thanks

File: app/assets/javascripts/admin/bulk_product_update.js.coffee [hunk 1]
```diff
@@ -261,7 +261,9 @@ angular.module("ofn.admin").controller "AdminProductEditCtrl", ($scope, $timeout
         product = BulkProducts.find product.id
         variant.unit_value  = parseFloat(match[1].replace(",", "."))
         variant.unit_value  = null if isNaN(variant.unit_value)
-        variant.unit_value *= product.variant_unit_scale if variant.unit_value && product.variant_unit_scale
+        if variant.unit_value && product.variant_unit_scale
+          variant_unit_value = variant.unit_value * product.variant_unit_scale
+          variant.unit_value = parseFloat(variant_unit_value.toFixed(8))
```
Comment (jibees) [inline app/assets/javascripts/admin/bulk_product_update.js.coffee:266]: I think I'd prefer use `js-big-decimal` (https://www.npmjs.com/package/js-big-decimal)
something like:
```
bigDecimal.multiply(variant.unit_value, product.variant_unit_scale, 2)
```

**Review by jibees — COMMENTED** [review]
I have another solution, which is think is better. What do you think?

I'd squash those two commits too.

File: app/assets/javascripts/admin/bulk_product_update.js.coffee (hunk 1 above)
Comment (saunmanoj888) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee]: hii @jibees 
I have used the package `js-big-decimal` but the specs have started to fail because specs are unable to find the method `bigDecimal.multiply`. Is it because we have included `js-big-decimal` as Dependenciesand not devDependencies?

Comment (jibees) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee]: I guess that `bigDecimal.multiply` should be imported or mocked for the specs environment ...

Comment (jibees) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee]: (not that easy actually)

Comment (saunmanoj888) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee]: hii @jibees 
Thanks for the above suggestions. I have made the changes in the specs. Can you please re review it.
Thanks

File: app/assets/javascripts/admin/bulk_product_update.js.coffee [hunk 2]
```diff
@@ -262,7 +262,7 @@ angular.module("ofn.admin").controller "AdminProductEditCtrl", ($scope, $timeout
         variant.unit_value  = parseFloat(match[1].replace(",", "."))
         variant.unit_value  = null if isNaN(variant.unit_value)
         if variant.unit_value && product.variant_unit_scale
-          variant.unit_value = parseFloat(bigDecimal.multiply(variant.unit_value, product.variant_unit_scale, 2))
+          variant.unit_value = parseFloat(window.bigDecimal.multiply(variant.unit_value, product.variant_unit_scale, 2))
```
[the remark this answers is not in the document]
Comment (jibees) [reply app/assets/javascripts/admin/bulk_product_update.js.coffee:265]: I've tested, without any success. I guess that adding this `window.` on bigDecimal + adding a mock (ie. not testing external librairies) is a good compromise.

**Review by jibees — APPROVED** [review]
Thanks for this one, and for listening to our comments! 🙏

**Comment by mkllnk** [comment]
@jibees Did you mean to move this PR back to In Dev or should it go to Test Ready?

**Comment by jibees** [comment]
> @jibees Did you mean to move this PR back to In Dev or should it go to Test Ready?

My mistake. To me it's `Test Ready`.

**Comment by drummer83** [comment]
Hi @saunmanoj888 and thank you for another PR!

I have tested this before and after staging your PR on our servers.
**Before:**
Peek 2022-10-28 13-12

**After:**
Peek 2022-10-28 13-31

You can see that the number is kept correctly without additional decimals. :+1: 

Continuing the checkout process we do see long decimals, but this is covered here: #9720.

This one is ready to merge! :tada:
Thanks!
