### PR TITLE
Password change logout

### LINKED ISSUE #2848: User logged out when changing password.
## Description

Follow-on from bug report #2840. When setting a new password under the account page, the user is logged out unexpectedly.

## Expected Behavior

User should stay logged in when setting a new password.

## Actual Behavior

User is unexpectedly logged out and bounced to the home page / login modal.

## Steps to Reproduce

1. Log in as a user
2. Go to /account, then Account Settings tab
3. Set a new password

## Context

Changing password.

## Severity

S4: annoying, but not critical.

## Possible Fix

Interestingly, the Spree::UsersController in the spree gem already has an apparent fix for this in the #update action, with the comment: `# this logic needed b/c devise wants to log us out after password changes`. Maybe it needs adjusting, or maybe we overrode it somewhere.

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #2848

Adjusts a config setting so that users are not logged out when updating their password.

#### What should we test?

Users can change password via /account page without being logged out.

#### Release notes

Users will not be logged out whilst changing their password.

Changelog Category: Changed

### CODE REVIEW

File: spec/features/consumer/account/settings_spec.rb [hunk 1]
```diff
@@ -27,5 +31,16 @@
       click_link I18n.t('spree.users.show.tabs.settings')
       expect(page).to have_content I18n.t('spree.users.show.unconfirmed_email', unconfirmed_email: 'new@email.com')
     end
+
+    it "allows the user to change their password" do
+      fill_in 'user_password', with: 'NewPassword'
+      fill_in 'user_password_confirmation', with: 'NewPassword'
+
+      click_button I18n.t(:update)
+      expect(find(".alert-box.success").text.strip).to eq "#{I18n.t(:account_updated)} ×"
```
Comment (mkllnk) [inline spec/features/consumer/account/settings_spec.rb]: `find(".alert-box.success")` fails. It looks like the user is logged out after hitting Update.

File: spec/features/consumer/account/settings_spec.rb [hunk 2]
```diff
@@ -27,5 +31,18 @@
       click_link I18n.t('spree.users.show.tabs.settings')
       expect(page).to have_content I18n.t('spree.users.show.unconfirmed_email', unconfirmed_email: 'new@email.com')
     end
+
+    it "allows the user to change their password" do
+      allow(Spree::Auth::Config).to receive(:[]).with(:signout_after_password_change).and_return(false)
```
Comment (Matt-Yorkley) [inline spec/features/consumer/account/settings_spec.rb]: @mkllnk I've added this to make the spec work, as the test environment doesn't pick up the value set in the spree initializer. Do you think this is ok, or should I try to set that config variable globally in the test environment instead? I'm wondering if it might interfere with other specs or changes to factories if it's set globally...

Comment (sauloperez) [reply spec/features/consumer/account/settings_spec.rb]: That's the way IMO. Changes to global state in tests => :boom:

Comment (mkllnk) [reply spec/features/consumer/account/settings_spec.rb]: I agree that changes to the global state are not good in tests in general. And I find this solution okay, but I see a problem in the fact that the logic is different for production and testing here. We have to add this line to the test case to make it behave the same way. That's basically code duplication in a very hidden place. Imagine we had to define the checkout state machine in the same spec that verifies that it's correct. It's not really testing the code used in production then.

**Comment by Matt-Yorkley** [comment]
I agree @mkllnk that changing the settings for the production environment but not for tests doesn't seem like a great idea. I've switched to setting it in the global test config, and all the specs are green, so I guess it's ok. 

@sauloperez are you happy with that? https://github.com/openfoodfoundation/openfoodnetwork/pull/2850/commits/4760ebb80c908b70a9fd5a0d184a57a49d2b36b3

**Comment by sauloperez** [comment]
Staged on https://staging.katuma.org/

**Comment by myriamboure** [comment]
testing notes: https://docs.google.com/document/d/1gtzQWewyiLawJEyyH85xUSNQHNHcAitVvLPL4lu63qQ/edit?usp=sharing

@Matt-Yorkley i randomly did another test as change password was affected I tested the "forgot password" process and it seems that PR is breaking it, the email recovery email is not sent. See notes. I tested on current French production (on v1.21) and it is working so it feels like it can be connected to that PR... back to in dev then for now.

**Comment by Matt-Yorkley** [comment]
@myriamboure I've just put this up on UK staging, and reset password emails are working fine with this PR. It'll leave it up if you want to re-test it.
