### PR TITLE
Fix product import on existing, empty unit_type and variant_unit

### LINKED ISSUE #8773: Uploading a product import file with empty unit type fails without any clue on the UI
## Description

Uploading a file and forgetting to fill unit_type and variant_unit_name leads to a fail after just 2 sec but the user does not know it.

## Expected Behavior

Show an error on the UI (same model than other product import error)

## Actual Behaviour

User see this:

image

console (no network errors)

image

## Steps to Reproduce

1. Create a file in order to **update** an existing product and leave both unit_type and variant unit_name empty
2. :boom:

## Workaround

Fill on of the 2 fields

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.1.13
* Browser name and version: All
* Operating System and version (desktop or mobile): desktop

### PR DESCRIPTION
**Pull request by SarvarKh**
#### What? Why?

Closes #8773 

Importing product file with empty `unit_type` and`variant_unit_name` columns on already existing products was failing without any error notice to the user.

#### What should we test?

- Visit `/admin/product_import` page.
- Fill out product list template (.csv) leaving `unit_type` and`variant_unit_name` columns empty and product `name` column to already existing product name.
- Select your .csv file, upload and import.
> Corresponding error notification appears.

PR_import

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

File: app/models/product_import/entry_validator.rb [hunk 1]
```diff
@@ -73,11 +73,13 @@ def mark_as_new_variant(entry, product_id)
...
-      end
-      if entry.attributes['on_hand'].present?
-        new_variant.on_hand = entry.attributes['on_hand']
+      if entry.attributes['unit_type'].present? || entry.attributes['variant_unit_name'].present?
+        if entry.attributes['on_demand'].present?
+          new_variant.on_demand = entry.attributes['on_demand']
+        end
+        if entry.attributes['on_hand'].present?
+          new_variant.on_hand = entry.attributes['on_hand']
+        end
```
Comment (mkllnk) [inline app/models/product_import/entry_validator.rb:82]: Thanks for finding a solution. As you said yourself, it's not ideal. It's not obvious what the connection between the missing values and the stock information is.

The error message said that the variant needs to be saved. So maybe this is a better way?

```suggestion
      if new_variant.persisted?
        if entry.attributes['on_demand'].present?
          new_variant.on_demand = entry.attributes['on_demand']
        end
        if entry.attributes['on_hand'].present?
          new_variant.on_hand = entry.attributes['on_hand']
        end
```

It would also be great to write a spec to cover this case. I would have run that to test this code.

Comment (SarvarKh) [reply app/models/product_import/entry_validator.rb]: Yes, it also works. I didn't pay due attention to the response of validate_date. So, it looks like a better way to solve the issue and works in other scenarios as well.

Screen Shot 2022-01-29 at 11 39 10 (2)

**Review by mkllnk — APPROVED** [review]
Great!

Would you like to write a spec, too? You could improve spec/models/product_import/entry_validator_spec.rb.

**Comment by mkllnk** [comment]
It's not a great spec. It uses a lot of mocked data. But I created an example to show how you can reach the code you fixed:
```
+  describe "variant validation" do
+    let(:potatoes) {
+      create(
+        :simple_product,
+        supplier: enterprise,
+        on_hand: '100',
+        name: 'Potatoes',
+        unit_value: 1000,
+        variant_unit_scale: 1000,
+        variant_unit: 'weight'
+      )
+    }
+    let(:potato_variant) do
+      ProductImport::SpreadsheetEntry.new(
+        unscaled_units: "1",
+        units: "1",
+        unit_type: "kg",
+        name: potatoes.name,
+        display_name: 'Pink Potatoes',
+        enterprise: enterprise,
+        enterprise_id: enterprise.id,
+        producer: enterprise,
+        producer_id: enterprise.id,
+      )
+    end
+
+    before do
+      allow(import_settings).to receive(:dig)
+      allow(spreadsheet_data).to receive(:tax_index)
+      allow(spreadsheet_data).to receive(:shipping_index)
+      allow(entry_validator).to receive(:enterprise_validation)
+      allow(entry_validator).to receive(:tax_and_shipping_validation)
+      allow(entry_validator).to receive(:variant_of_product_validation)
+    end
+
+    it "validates a product" do
+
+      entries = [potato_variant]
+      entry_validator.validate_all(entries)
+
+      expect(potato_variant.errors.count).to eq 0
+    end
+  end
```

There are still errors on the entry. This is not a complete test case but maybe a start for you?

**Comment by SarvarKh** [comment]
The given example was a great help, thanks.

**Review by mkllnk — APPROVED** [review]

**Review by jibees — APPROVED** [review]
👌 🙏

**Comment by filipefurtad0** [comment]
Hey @SarvarKh ,

I could reproduce the error on the freezing progress bar, it seems the same as the one reported here:
https://github.com/openfoodfoundation/openfoodnetwork/issues/5363#issuecomment-627846544

image


After your PR this is fixed:

The user sees why the file is not uploaded, and the error is not seen on the `Response` tab:

image

Updating other fields like stock, but having `unit_type = g` (in this case) works as before :+1: 


So, this closes both #5363 and #8773 - awesome!!! :muscle: :rocket:
