### PR TITLE
Reports improvement

### LINKED ISSUE #7176: Payment & Shipping Method Filters for Order Cycle Management Reports not working
## Description

View https://openfoodnetwork.org.uk/admin/reports/order_cycle_management

Entering a filter into either the Payment Method or Shipping Method fields and try to down load a report results in the Slug error message.

Both the Payment Method and Delivery reports can be accessed if no filters are applied for Payment/Shipping Method.

## Expected Behavior

Data for Delivery and Payment Method reports can be filtered by customer Payment & Shipping Method.

## Actual Behaviour

Data for Delivery and Payment Method reports can not be filtered by customer Payment and Shipping Method.

## Steps to Reproduce

1. Visit https://openfoodnetwork.org.uk/admin/reports/order_cycle_management
2. Select a hub
3. Enter a filter into the 'payment method' field
4. Select 'Payment Method report'
5. Click 'Search'
6. Observe the Slug Screen
7. Repeat with a filter in the 'Shipping Method' field.
8. Observe the slug screen
9. repeat both steps choosing the 'Delivery Report'
10. Observe the slug screen

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by seballot**
### What? Why?

Improve the reports

### 1. UI Uplift

Fixed some alignment, and created "filters" and "rendering" sections

image

### 2. Download as PDF, CSV, JSON, SpreadSheets for any report

image

### 3. Printable

I have done very small work so that now when you print a page in OFN it looks better. 
There is also a print button when the report is rendered on the screen

### 4. Ability to hide any columns

image

### 4. Header & Summary Row

Easily add header and summary_row for reports
Display them on demand through rendering option
image

image

### 5. Better Formatting

Price and numbers are now displayed in a human readable way, depending on locale

### Refactor

In order to implement the new functionalities, some refactor have been involved
Now, appart from packing report which work a bit differently, all reports are working consistently, inheriting from same class
Also the declaration of a report is easier (in my opninion at least!) and take less line of code
All reports (including packing) use same code for rendering, and are all available through API

Still to improve :
- The report filters could be DRY, as lot of reports use same filter inputs
- most of the reports load data with ActiveRecord Relation, and then iterate through the hydrated objects to make filters, grouping, and display the result (which often involve loading associated objects). This is quite unefficient, some data could be loaded directly with smart SQL queries. But in another hand, this type of object query and filtering is quite easy to follow from a dev perspective. The code made for packing report (which use SQL query with Arel lib) seems really efficient, but is very hard to understand and use IMHO. So as the reports are used only once in a time, and are not involving so much data (I guess big report only process thousand of data, not million right?), I'm not sure we should put energy in improving those queries. At least, after this refactor, it would be easier to do

Closes #7176

### CODE REVIEW

**Comment by lin-d-hop** [comment]
This is a great addition @seballot, thanks so much!

Regarding the show/hide columns.... 
I wonder if we can instead do the UX as a set of checkboxes. This is how we implement this in the Products area of the platform.
Screenshot from 2022-03-23 09-41-11

It is also the recommendation [here](https://ux.stackexchange.com/questions/110077/best-practices-to-allow-user-to-hide-show-columns-in-a-data-table).

What do you think @seballot?

**Comment by drummer83** [comment]
@seballot Wow, this is great I think!
Just a little typo: Optional columns (not Optio**nn**al columns)

**Comment by seballot** [comment]
Hi ! here's an update : I have worked on all reports so they now use same rendering code than the packing report

From now, any new feature added will be available for all reports at once. I would like to work next week on
- make columns configurable (for all reports)
- ability to have group headers : i.e do not display the grouped data at each line, but in a "header row" :

**Instead of :**
Sebastian | Castro | Apple | 5 |
Sebastian | Castro | Bread | 1 |
Mickael | Billman | sugar | 5 |
Mickael | Billman | Bread | 1 |

**Display:**
Sebastian Castro
Apple | 5 |
Bread | 1 |
Mickael Billman
sugar | 5 |
Bread | 1 |

WDYT?

**Comment by RachL** [comment]
@seballot Here are my notes from our meeting:

- as this is already a big piece of work, we can stop here scope wise and add improvements in future PRs, once this is merged.

**Some changes we agreed for this PR** (please comment / edit if I forgot something!):

- CSV export are considered "machine" exports : they reflect the same data format as JSON. Excel and Open Office export, are the human-readable version of the spreadsheet. So any formatting on data (ex: turn numbers in currency, "true" in "Yes" etc) should be applied on Excel / Open Office / PDF / onscreen version only

- some columns have no real data (ex "incoming transport"...which is just a string) and can be removed (we can add real data in future versions)

- we should keep the repeat of content on TOTAL lines for now

**Postponed for future PRs**:

- The excel / CSV / PDF etc dropdown can be replaced by radio buttons

- Add a print button on the onscreen version

- Handle total lines in a cleaner way (don't repeat content, add them on top for total reports => to be better defined)

- Adding tooltips on column names

- Merging of reports types which are very close in terms of columns (ex tax reports or delivery reports)

- Ability for the admin to save its rendering options per reports


Thank you so much for all this!!! Users will be over the moon once we release this :D

**Comment by seballot** [comment]
Ok I think this one is ready for review @Matt-Yorkley @jibees @mkllnk

File: lib/reporting/report_grouper.rb [hunk 1]
```diff
@@ -0,0 +1,158 @@
...
+      result = row.clone
+      report.fields_to_hide.each { |field| result.delete_field!(field) }
+      result
+    end
+
+    # Compute the query result item into a result row
+    # We use OpenStruct to it's easier to access the properties
+    # i.e. row.my_field, rows.sum(&:quantity)
+    def build_row(item)
+      OpenStruct.new(report.columns.transform_values do |column_constructor|
```
Comment (mkllnk) [inline lib/reporting/report_grouper.rb]: I'm not sure if it matters on this scale but there are some doubts about the performance of OpenStruct:
https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceopenstruct

Nowadays, you can also do `rows.pluck(:quantity).sum` to achieve the same.

File: app/controllers/api/v0/reports_controller.rb [hunk 2]
```diff
@@ -10,7 +10,8 @@ class ReportsController < Api::V0::BaseController
       before_action :validate_report, :authorize_report, :validate_query
 
       def show
-        @report = report_class.new(current_api_user, ransack_params, report_options)
+        params[:report_format] = 'json'
```
Comment (mkllnk) [inline app/controllers/api/v0/reports_controller.rb:13]: Why do we restrict to JSON? For some applications it can be very handy to get a CSV.
```suggestion
        params[:report_format] ||= 'json'
```

?

File: lib/reporting/report_loader.rb [hunk 3]
```diff
@@ -2,21 +2,22 @@
...
-    delegate :report_subtypes, to: :base_class
-
     def initialize(report_type, report_subtype = nil)
       @report_type = report_type
       @report_subtype = report_subtype
     end
 
+    # We currently use two types of report : old report inheriting from ReportObjectReport
+    # And new ones inheriting gtom ReportQueryReport
+    # They use different namespace and we try to load them both
```
Comment (mkllnk) [inline lib/reporting/report_loader.rb:12]: Is this comment outdated?

**Review by mkllnk — CHANGES_REQUESTED** [review]
Wow, what a huge chunk of work! And really well done. Thank you! :bouquet: 

I just have a few minor edits. Otherwise great!

File: .gitignore [hunk 4]
```diff
@@ -50,6 +50,7 @@ coverage
 /reports/
 !/reports/README.md
 /spec/components/stories/**/*.stories.json
+TODO
```
[the remark this answers is not in the document]
Comment (seballot) [reply .gitignore:53]: Nice I didn't knew about global gitignore, it's done thanks !

File: app/controllers/admin/reports_controller.rb [hunk 5]
```diff
@@ -22,14 +22,12 @@ def show
     private
 
     def export_report
-      render report_format.to_sym => @report.public_send("to_#{report_format}"),
-             :filename => report_filename
+      send_data @report.public_send("to_#{report_format}"), filename: report_filename
```
[the remark this answers is not in the document]
Comment (seballot) [reply app/controllers/admin/reports_controller.rb]: but if you try a non existing format, the method to_XXX will not exists, so it's already whitelisted no?
image

File: lib/reporting/report_grouper.rb (hunk 1 above)
Comment (seballot) [reply lib/reporting/report_grouper.rb]: Oh yes good point ! good idea re using `pluck`. I was a bit hesitating introducing this `OpenStruct`. Let wait for other input maybe? cause it will take a bit of time to refactor this :)

File: app/controllers/api/v0/reports_controller.rb (hunk 2 above)
Comment (seballot) [reply app/controllers/api/v0/reports_controller.rb:13]: you mean some applications will automate the download of the file and then process it? if we want to handle CSV, we shall also replace th way `Api::ReportController` render the report, cause for now it's `render json: { data: @report.to_csv }`

maybe we can first having this JSON api works, and let see if there is one day a use case for CSV? or does the use case already exists?

File: app/controllers/admin/reports_controller.rb (hunk 5 above)
[the remark this answers is not in the document]
Comment (mkllnk) [reply app/controllers/admin/reports_controller.rb]: If we are 100% sure about all methods starting with `to_` then this would be okay but there may be other methods (in the future) that we don't want to call. For example, there are `to_param`, `to_query`, `to_yaml`, `to_enum` and `to_s`. Most of them would probably just lead to a server error (even though we don't want that either) but some of them may expose sensitive data. If you look at `to_yaml` it exposes internal variables which could contain unfiltered data.

With `to_yaml` I get raw data of the current user including the password hash. That shouldn't be harmful for the current user to know their own hash but many vulnerabilities work by exploiting many little things that are not dangerous on their own.

File: app/controllers/api/v0/reports_controller.rb (hunk 2 above)
Comment (mkllnk) [reply app/controllers/api/v0/reports_controller.rb:13]: Good point about the rendering format. I'm not 100% sure but I guessed that there's already a use case for CSV. But you are right, lets wait for someone to ask and then we can do it properly.

File: app/controllers/admin/reports_controller.rb (hunk 5 above)
[the remark this answers is not in the document]
Comment (seballot) [reply app/controllers/admin/reports_controller.rb]: Good point ! I made a commit to whitelist format as you suggested

**Review by mkllnk — APPROVED** [review]
Thanks!

**Comment by RachL** [comment]
@seballot I get an error 500 when trying to reach `/admin/reports/sales_tax/tax_rates` (I'm not even able to reach the filters) the other reports load correctly. Do you have time to have a look?

We are running diffs to see if everything is working fine and will get back to you if we spot anything. Some UI improvements will be open as separate issues as well. thank you again for all this!!

**Comment by RachL** [comment]
@seballot just FYI there are some conflicts now on the branch

**Comment by lin-d-hop** [comment]
Testing Notes:
@RachL and I have looked at some big hubs in France and diffed the downloaded CSVs to try spot any differences.

Results of diffs:
- Xero report has no data in the 'new' version... @RachL might this be a problem with the download?
- Sales Tax Report - Differed in the way the date is displayed. Old=2021-06-06 12:30:07 New=2021-06-06 12:30:07 +0200
- Product & Inventory - Files are identical :heavy_check_mark: 
- Payments Report - Order of the data has changed. I don't think this is a problem
- Packing Reports - Headings are now capitalised. First name and last name swapped, price added, phone added. 'No' changed to 'False'. Default option is without totals. Anyone with scripts on this report will need to update them when this is released. Users will need warning about these changes :warning: There appear to be many rows in the 'new' file that are not in the 'old' file. @RachL That might benefit from your eyes on the files in case you can spot an obvious mistake somewhere.
- Orders and Distributors - Reports are identical :heavy_check_mark: 
- Orders and Fulfillments - Download filenames have changed. Unused cols removed. 'No' changed to 'False'. Order of columns changed. Default option is without totals. Users will need warning about these changes. :warning: 
- Order Cycle Management - 'Code' heading renamed to 'Customer Code'. Tis a good change but we'll need to let users know about this :warning: 
- Enterprise Fee Report - Files are identical :heavy_check_mark: 
- Customer Reports - Ordering of results has changed. I think this is okay.
- Bulk Coop Reports - Ordering of results has changed. Download filenames have changed so should let users know about that :warning: 

Summary:
As a lot of small things changed it was hard to track in a diff. So I don't have full confidence that these changes don't break things. However on my investigations things look good for the most part with lots of exciting things for users. You are a hero @seballot :superhero_man: 

Having said that I think we need to prepare users for this release. I think we need to give a few weeks notice to instances as any scripts on these reports might need updated to accommodate the changes. Similarly I think users need a week or two of notice for any bespoke scripts they run on their reports. I know that the reports can be configured to accommodate the column name changes etc, however some fair warning to users will help to make sure they aren't being surprised on packing day.

Perhaps the best way to do this is a discourse post? I'm happy to build this but will wait on some responses to specifics above :)

**Comment by RachL** [comment]
thanks @lin-d-hop how awesome it is to have this diff!!

And thanks @seballot for the fix, no more error 500 on tax sales report.

I will have a dive into packing reports. For the rest of the feedback, I would like to propose: 

- We change everywhere the default option to include totals for now (in order to keep minimum changes)

- Empty all pre-filled fields in Xero report

image

- Maybe put old filed names back for the moment, I guess we can change them later on?

@seballot is this easy to change at this stage? do you remember the reason for the date display change in sales report?

@lin-d-hop then from there and assuming no bugs on packing - there are especially breaking changes on Packing reports and Orders and fulfillment reports. Judging by the type of changes (mostly columns orders), I would say it looks like our current process (warn on Thursday for next Tuesday) is enough for core instances script makers (apart from UK and AU, do you know if there are any?). We could leave 2 weeks, but then I'm afraid this PR starts to get more conflicts. If we need 2 weeks notice for instance manager, we need a feature toggle on this I guess.

**Comment by RachL** [comment]
> Xero report has no data in the 'new' version... @RachL might this be a problem with the download?

Yep. Dunno what I've done. I've re-added the correct files to the drive and also added the ones for the second sales tax. Can you run the diffs @lin-d-hop ?

**Comment by RachL** [comment]
@seballot We discussed with the team how we are going to release this PR. Here are the main conclusions and I'm available for a call if it's not clear. Don't hesitate to propose something different if you feel this is wrong :) 

We don't know how many people exactly have macros / script working on the csv file. So ideally we would like to warn them before releasing

We've studied the option to put the PR behind a feature toggl and thus release to bits of users at a time. But this seems technically tough and might bring more problems than it would solve.

The proposed strategy would be to try and do a first release that does not change anything on the csv. After this is merge we can releasechanges in columns names and columns orders.

That means the updated list of suggested changes would be : 

- We change everywhere the default option to include totals

- Empty all pre-filled fields in Xero report

- Revert these changes in packing report: Headings are now capitalized. First name and last name swapped, price added, phone added. 'No' changed to 'False'.

- Revert these changes in orders and fulfillment reports: Unused cols removed. 'No' changed to 'False'. Order of columns changed.

What do you think?

You can forget my comment about not changing the files names, let's keep that work in. I'm editing my previous comment.

**Comment by seballot** [comment]
Hi ! great work, users will appreciate all this care :)

**We change everywhere the default option to include totals**
-> actually in CSV there is no Totals cause we decided to make in a "raw data format" like JSON.  that's why also "No" are replaced by "false". So for now we keep csv as "human readable" format is that right? but another consequence will be that for "human readable format" dates are formated in a better way (localized). that's why also the date format changed, it's because now it's raw ISO format. I can make an exception about formatting the date for CSV, but maybe it's not necessary, at least not for packing !

**Empty all pre-filled fields in Xero report**
those pre-filled were already there, but not displayed in the UI. so when you clicked submit with blank dates, it was actually using those default dates in the backend, which is wuite confusing, that's why I displayed them. If you want I can remove those default params from xero reports (not only in UI). Default values are
```invoice_date: Time.zone.today,
due_date: Time.zone.today + 1.month,
account_code: 'food sales'```

**Revert these changes in packing report: Headings are now capitalized. First name and last name swapped, price added, phone added. 'No' changed to 'False'.**
Ok will do. Just I think there is no need to remove price and phone as it's very clear from the UI to remove them, but I let you decide. If remved, I hope we will not wait too much for adding them ! :D

**Revert these changes in orders and fulfillment reports: Unused cols removed. 'No' changed to 'False'. Order of columns changed.**
Ok will do ! do you know column order have been modified? (there is so much if you already have an idea would be nice :) otherwise I will make a diff myself)

**Comment by lin-d-hop** [comment]
> Ok will do ! do you know column order have been modified? (there is so much if you already have an idea would be nice :) otherwise I will make a diff myself)
From memory I think it is first name and last name swapped.

> Ok will do. Just I think there is no need to remove price and phone as it's very clear from the UI to remove them, but I let you decide. If remved, I hope we will not wait too much for adding them ! :D
Yes you can remove them again, which is great. We're just trying to ease the pain on users and for anyone with scripts on these reports they just wont know why they are breaking so will stress out, probably while already rushing on packing day, having not read our emails, and not actually see the solution is easy. I know it seems pedantic but if we introduce ANY breaking change we need a whole rollout process around it. So if you are happy it would be great to focus on getting this out quickly and then moving on get the 'breaking changes' released together as fast as possible.

Once [this one](https://github.com/openfoodfoundation/openfoodnetwork/issues/9133) is in place we can much more freely add and remove columns from the reports. So perhaps if we focus on this next we can then look at the 'breaking changes' (standardising column names etc) afterward?

**Comment by lin-d-hop** [comment]
> Empty all pre-filled fields in Xero report
those pre-filled were already there, but not displayed in the UI. so when you clicked submit with blank dates, it was actually using those default dates in the backend, which is wuite confusing, that's why I displayed them.

Good catch. If this is what is happening then I think keep the behaviour you've implemented. What do you think @RachL?

**Comment by RachL** [comment]
@lin-d-hop yeah I was editing my post to add this proposal :D I will download everything again.

**Comment by RachL** [comment]
Notes on current (old) behavior for total lines, I've added checks if this is changed with this PR:

- Orders and distributors : NO ✔️ 
- Bulk coop supplier report : YES ✔️ 
- Bulk coop allocation  : YES ✔️ 
- Bulk coop packing sheets : NO 🔴 
- Bulk coop customer payments : NO 🔴 
- Order cycle supplier total : NO 🔴 
- Order cycle supplier total by distributors : YES ✔️ 
- Order cycle totals by supplier : YES ✔️ 
- Order cycle customers totals : YES ✔️ 
- Mailing list : NO ✔️ 
- Addresses : NO ✔️ 
- All products : NO ✔️ 
- Inventory : NO ✔️ 
- LettuceShare : NO ✔️ 
- Enterprise fee summary : NO ✔️ 
- Payment method report : NO ✔️ 
- Delivery report : NO ✔️ 
- Both sales tax : NO ✔️ 
- Xero invoices : NO ✔️ 
- Pack by customer : YES ✔️ 
- Pack by supplier : YES ✔️ 

So the current behavior would introduce breaking changes for people downloading xslx and trying their scripts / macros for the 3 reports in red as these reports would now have total lines (which makes sense). I feel the risk is pretty low and would roll with it. Do you agree @lin-d-hop ?

**Comment by seballot** [comment]
Sorry I'm not quite following :) there are a lot of "NO" with a green checkbox ah ah are they really green? :)

Even with xlsx I still need to reorder columns as before, and downcase packing report labels right?

re packing report, one other idea is to default the hidden columns to "price" and "phone", so if they just click "GO" without reading anything they will have same behaviour than before. But of course I'm also okay to remove those columns for now if you think it's best

**Comment by lin-d-hop** [comment]
Defaulting to hidden cols is a fair compromise to me.
I think given this huge contribution it makes sense to allow you to have this specific fields you need.

**Comment by lin-d-hop** [comment]
> Sorry I'm not quite following :) there are a lot of "NO" with a green checkbox ah ah are they really green? :)

Just look at the green tick meaning 'behaviour hasn't changed' ;)

**Comment by seballot** [comment]
Hi ! I just made following changes

**All CSV export**
the columns key is now the raw field instead of translated value. i.e. `last_name` instead of `Last Name` or `Nom de Famille`

**Packing report**
Order of columns reverted to it's original (first_name then last_name)
price and phone hidden by default
Spreadsheets report will also use the raw field name as columns headers instead fo translated value
-> so I think now the default packing spreadsheet export is perfectly identical to the old CSV export

**order & fulfilments**
At the end there is nothing to do right? please tell me if I misunderstood your lasts comments

**Comment by RachL** [comment]
@seballot thank you! We are downloading the xslx to run a final diff.

a first feedback: when downloading the xslx version for sale tax reports, the order number includes html. E.g.  `             <a href=/admin/orders/R352618212/edit class="edit-order" target="_blank">R352618212</a>` I guess we want to remove and leave number only?

**Comment by seballot** [comment]
good find ! I will wait for all your tests to complete so I can fix them all at once, let me know you are done ! thanks !

**Comment by RachL** [comment]
@lin-d-hop I've uploaded the .xlsx in the same folder. I don't have the same numbers of line for the csv in: 

- bulk coop reports
- orders & fulfilment reports
- customer reports
- xero reports

Yet I checked twice that I was selecting the same dates... but maybe I'm still doing something different?

**Comment by lin-d-hop** [comment]
Alright, testing round two:

General: Headings and translatable fields in the old were in English, in the new they are in French. Not sure if this was because you were using a different language @RachL?
Also, because I had to convert the files to compare them there are many little quirks making a diff impossible :(

Sales tax report: Order Number is the new report is a URL. This is nice for the human readable version, however fails the parity test. It means that this report can't be used as the CSV replacement. 

Products and Inventory: diffs fails because the conversion seemed to leave some odd characters in

Packing reports: In the old is says 'no' in the new is is French, 'non'. Again, I wonder if this is related to the language you used to download @RachL?

Payments reports: Does the 'new' file include currency symbols? They aren't rendering properly after the csv conversion but they seem to be on every price in the file, which is different to the 'old' which doesn't include currency symbols.

Orders and Distributors: In the new file 'order id' = "1,964,493". In the old file 'order id' = 1964493

Orders and Fulfilments: 
- Order Cycle Supplier totals gains a totals row :warning:. 
- In old the TOTAL in the totals row is capitalised, not in the new.  
- Fields are in FR not EN again. 
- Results are in a different order, which might mess up peoples packing processes :warning: 
- Currency symbols are included on prices in the new ones, which might mess up machine readability

Order cycles Mnagement: Files number 1 (old and new) were both empty @RachL ..?? FR vs EN.

Enterprise Fee: Didn't notice anything awry

Customers: Didn't notice anything awry

Bulk Coops Reporrts: Results are in a different order, which might mess up peoples packing processes :warning: 

Xero Report:  Didn't notice anything awry


### However...
There is a big issue here that any files in xslx format will need to be converted into CSV, so depending on the tools someone is using, the xslx might be unworkable. For example, in UK we do a lot with google sheets. However the import will not work in the way we use it now. Google demand you import xslx into a new spreadsheet - meaning our current systems will all fail. Thus it will be easier for me to update everything to the new CSV formats than it will be use xslx.

I don't know if this applies to other users as I don't know what supporting tools they use.

Because of this ... I'm not sure what the correct approach is here.

**Comment by RachL** [comment]
Oh so sorry!!! I checked the first time that I was in English and after was so focus on the lines I didn't pay attention to headers :(  you must have wasted a lot of time... 1000 apologies...

I will look more closely to the other errors.

But anyway you are right about xslx and google sheet... It looks like there is no easy solution for the release. I will think about it a bit more and come back to it tomorrow.

**Comment by seballot** [comment]
Hi !

what about createing a temporary new format, somehting like `old_csv` which will be perfectly similar to the one before? 
I think it's doable, we will need to
- include summary row
- format boolean with translated value (Yes/No instead of true/false)
- do not format currencies (1030.30 instead of 1 030,30)
- use translated headers, except for packing report
- format dates as before

and also, no matter the format
- Orders and Fulfilments : fix columns order
- Order Cycle Supplier : remove the extra total row that have been added
- Orders and Distributors : fix `order id = "1,964,493"` this is not a currency is should no be formatted like currency
- Sales Tax : remove the html part inside xlsx (order number)
- Orders and Fulfilments && Bulk Coops Reports : fix sorting so it's like before

**Comment by sigmundpetersen** [comment]
Closes #7176

**Comment by lin-d-hop** [comment]
Hi @seballot 

Rachel and I are just chatting and I think we can simplify this. Lets leav with just the new CSV and not bother making an 'old_csv' as well.

We've whittled down to just the necessary changes:
- ~include summary row~ So long we are display by default let's ignore this.
- ~format boolean with translated value (Yes/No instead of true/false)~ Let's ignore this and we'll make sure integrations are updated.
- do not format currencies (1030.30 instead of 1 030,30) :heavy_check_mark: in CSV no formatting.
- ~use translated headers, except for packing report~ All CSVs and xslx should have translated headers
- ~format dates as before~ ignore this. New date format will be okay.

- Orders and Fulfilments : fix columns order :heavy_check_mark: 
- ~Order Cycle Supplier : remove the extra total row that have been added~ Ignore this. We've keep it standardised across reports and manage integration and notifying users.
- Orders and Distributors : fix order id = "1,964,493" this is not a currency is should no be formatted like currency :heavy_check_mark: Correct, for both csv and xlss
- Sales Tax : remove the html part inside xlsx (order number) :heavy_check_mark: yes please
- Orders and Fulfilments && Bulk Coops Reports : fix sorting so it's like before :heavy_check_mark: yes please, this will reduce some headaches for hub managers on packing day.

**Comment by seballot** [comment]
Hi !

Sorry for the delay, I have finally made requested adjustements

For last item re results order, I think I have fixed it but my local data do not allow me to have very good test, and I have been lazy to spend time to create a complex database. I hope it will be fine !

**Comment by RachL** [comment]
@lin-d-hop I've re-downloaded all csv (old and new). ready to diff 💪 I hope I didn't screw something up this time.

@seballot thank you soooo much!!

**Comment by lin-d-hop** [comment]
Okay, next round of diffs:

Xero report - files are identical :heavy_check_mark: 

Sales tax - only difference is date field :heavy_check_mark: 

Product and inventory - identical :heavy_check_mark: 

Payments report - this looks very different between old and new. Differing amounts and even hubs. Perhaps a small mistake with the filters @RachL?

Packing reports - change between non/false. Total rows gone. All agree changes :heavy_check_mark: 

Orders and fulfilments - 
- order cycles customer totals - change between non/false. Total rows gone. All agree changes :heavy_check_mark: 
- order cycle distributor by supplier - change between non/false. Total rows gone. Shipping method field fixed. All agree changes :heavy_check_mark: 
- supplier totals by distributor - Did we agree that we would remove 'to hub' and include 'total qty'? @RachL :warning: 
- supplier totals - Again did we agree to remove hub? I think this is important for multi-hub models. :warning: 

Orders and distributors - identical :heavy_check_mark: 

Order cycle management - only change is that Code column is renamed to Cust Code :heavy_check_mark: 

Enterprise Fee report - identical :heavy_check_mark: 
@RachL I thought there were two types of enterprise fee reports? Or maybe I'm mistaken (I havent double checked)

Customer report - order of results has changed but we dont care :heavy_check_mark: 

Bulk coop - the ordering has changed so I can't be 100% certain but it all looks fine to me :heavy_check_mark: 

So we are REALLY close now. Really really really close. But I do think perhaps the little things on Orders and Fulfilment might be important. What do you think @RachL

**Comment by RachL** [comment]
Alright sooo

- Payment report : I completely messed up on this one (selected one hub in one case only...sorry). I did compare them manually, I think we are good.

- Enterprise fee : yeah there is only one :+1:

- Suppliers total : @lin-d-hop I've checked production and I can't see hub either there? Two columns where removed: incoming transport and status. But both are useless, so I think we are good on this one? Or am I missing something?

- supplier totals by distributor : I think I messed up the files. I've just checked production vs staging and the two reports look equivalent?

So pending a double check on "hub" for suppliers total, I think we are good to merge :scream:

the failing spec on Mayhem is ok right @filipefurtad0 @mkllnk ?

**Comment by mkllnk** [comment]
> the failing spec on Mayhem is ok right @filipefurtad0 @mkllnk ?

Yes, that's fine. It should be fixed in master now.

**Comment by jibees** [comment]
> > the failing spec on Mayhem is ok right @filipefurtad0 @mkllnk ?
> 
> Yes, that's fine. It should be fixed in master now.

Maybe it should be rebased then?

**Comment by jibees** [comment]
Rebased!

**Comment by RachL** [comment]
@lin-d-hop I have doubled checked: no hub on Order suppliers total in current master. Hub is present in both version of OC suppliers totals by distributors. However in prod it's called "to hub" and on the PR "hub".
But that can be fixed in translation.

I'm merging it! :scream:

**Comment by seballot** [comment]
Hi Rachel !

Oups, I didn't had any tax rate on my DB so it was working for me :)

I made a fix, should be fine but please double check the expected output of this tax_rate report, I don't know all this part of OFN !

Thanks for testing :)

------- Original Message -------
