### PR TITLE
Repair ProxyOrder to support order cycle without closing time

### LINKED ISSUE #13660: The subscriptions section hangs and never opens
## Description

When I click on subscriptions, it just hangs here for ages and never opens.

Workaround: make sure that all order cycles with subscriptions have an end date set.

## Error in Open Food Network (Rails)

**NoMethodError** in **admin/subscriptions#index**
undefined method `>' for nil:NilClass

      order_cycle.orders_close_at > Time.zone.now
                                  ^

[View on Bugsnag](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/6901f26825e7c232fff6c049?event_id=6901f46d015655ecaca00000&i=gh&m=ci)

## Stacktrace

    app/models/proxy_order.rb:79 - cart?
    app/models/proxy_order.rb:29 - block in state
    app/models/proxy_order.rb:28 - each
    app/models/proxy_order.rb:28 - state
    app/controllers/spree/admin/base_controller.rb:104 - render_as_json
    app/controllers/admin/subscriptions_controller.rb:31 - block (2 levels) in index
    app/controllers/admin/subscriptions_controller.rb:16 - index

[View full stacktrace](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/6901f26825e7c232fff6c049?event_id=6901f46d015655ecaca00000&i=gh&m=ci)

*Created by Maikel Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by pacodelaluna**
#### What? Why?

- Closes #13660.

The `ProxyOrder#cart?` method was missing a control to secure a value presence.

#### What should we test?

- Check a case on BugSnag where the issue was not fixed yet
- Control that the action is not throwing an error

#### Release notes

- Repair ProxyOrder to support order cycle without closing time

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [X] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/models/proxy_order.rb [hunk 1]
```diff
@@ -76,7 +76,8 @@ def pending?
 
   def cart?
     order&.state == 'complete' &&
-      order_cycle.orders_close_at > Time.zone.now
+      (order_cycle.orders_close_at.nil? ||
```
Comment (pacodelaluna) [inline app/models/proxy_order.rb]: I am assuming that the `nil` value is possible here. We can adjust differently in case it is not a supported case.

File: app/models/proxy_order.rb [hunk 2]
```diff
@@ -76,7 +76,8 @@ def pending?
 
   def cart?
     order&.state == 'complete' &&
-      order_cycle.orders_close_at > Time.zone.now
+      (order_cycle.orders_close_at.present? &&
```
Comment (pacodelaluna) [inline app/models/proxy_order.rb]: As mentioned in the issue comments, we chose to restrict this filter if the `orders_close_at` is not present.

File: spec/models/proxy_order_spec.rb [hunk 3]
```diff
@@ -206,6 +206,75 @@
...
+        proxy_order.canceled_at = Time.zone.now
+        expect(proxy_order.state).to eq('canceled')
+      end
+    end
+
+    context "when the order is not present" do
+      let(:order) { nil }
+
+      it "returns 'canceled'" do
+        expect(proxy_order.state).to eq('pending')
```
Comment (rioug) [inline spec/models/proxy_order_spec.rb:227]: It should be `cancelled` here :
```suggestion
        expect(proxy_order.state).to eq('canelled')
```
Or the spec description is wrong.

File: spec/models/proxy_order_spec.rb [hunk 4]
```diff
@@ -206,6 +206,75 @@
...
+          expect(proxy_order.state).to eq('paused')
+        end
+      end
+    end
+
+    context "when the order cycle is not yet open" do
+      let(:order_cycle) { build(:order_cycle, orders_open_at: 2.days.from_now) }
+
+      it "returns 'cart'" do
+        expect(proxy_order.state).to eq('pending')
```
Comment (rioug) [inline spec/models/proxy_order_spec.rb:242]: it should be "cart" here

File: spec/models/proxy_order_spec.rb [hunk 5]
```diff
@@ -206,6 +206,75 @@
...
+        it "returns 'cart'" do
+          order_cycle.orders_close_at = 2.days.from_now
+          expect(proxy_order.state).to eq('cart')
+        end
+      end
+
+      context "when the order cycle does not have a closing date" do
+        it "returns 'cart'" do
+          order_cycle.orders_close_at = nil
+          expect(proxy_order.state).to eq('complete')
```
Comment (rioug) [inline spec/models/proxy_order_spec.rb:266]: it should be "cart"

**Review by rioug — CHANGES_REQUESTED** [review]
Thanks @pacodelaluna ,The fix is good, but the specs need fixing, looks like some copy-paste error.

File: spec/models/proxy_order_spec.rb (hunk 3 above)
Comment (pacodelaluna) [reply spec/models/proxy_order_spec.rb:227]: @rioug Right, sorry about that, something is wrong with the tests, I will sort this out.

**Review by pacodelaluna — COMMENTED** [review]
@rioug I have cleaned up the tests, I should be fine now.

File: spec/models/proxy_order_spec.rb [hunk 6]
```diff
@@ -206,6 +206,75 @@
...
+  describe "#state" do
+    subject(:proxy_order) { build(:proxy_order, subscription:, order:, order_cycle:) }
+
+    let(:order) { build(:order) }
+    let(:subscription) { build(:subscription) }
+    let(:order_cycle) { build(:simple_order_cycle) }
+
+    context "when the proxy order is canceled" do
+      it "returns 'canceled'" do
+        proxy_order.canceled_at = Time.zone.now
```
Comment (dacook) [inline spec/models/proxy_order_spec.rb:218]: It may be more reliable to use the `cancel` method to mark it as cancelled, instead of changing the data.
But it's probably simple enough not to worry here.

File: spec/models/proxy_order_spec.rb [hunk 7]
```diff
@@ -206,6 +206,75 @@
...
+
+      it "returns 'pending'" do
+        expect(proxy_order.state).to eq('pending')
+      end
+
+      context "when the subscription is not paused" do
+        it "returns 'pending'" do
+          expect(proxy_order.state).to eq('pending')
+        end
+      end
```
Comment (dacook) [inline spec/models/proxy_order_spec.rb]: This test is exactly the same as the above test. is it needed?

File: app/models/proxy_order.rb [hunk 8]
```diff
@@ -76,6 +76,7 @@ def pending?
 
   def cart?
     order&.state == 'complete' &&
+      order_cycle.orders_close_at.present? &&
       order_cycle.orders_close_at > Time.zone.now
```
Comment (dacook) [inline app/models/proxy_order.rb:80]: Whenever I see duplication my brain tries to find a way to remove it ;). Just as an FYI, this would also work:

```suggestion
      order_cycle.orders_close_at&.> Time.zone.now
```

This uses the safe navigation operator to choose whether or not to call the `>` method. But it's a little ugly and unusual so I think your solution is quite fine 👍

**Review by dacook — COMMENTED** [review]
Great, I just have a question about if one of the specs is needed or not?
(plus a couple of inconsequential comments)

File: spec/models/proxy_order_spec.rb (hunk 6 above)
Comment (pacodelaluna) [reply spec/models/proxy_order_spec.rb:218]: Right, but I am not saving the proxy_order object in the database, in order to speed up a bit the test. But I can adjust it if you think it is worth to test deeper.

**Review by pacodelaluna — COMMENTED** [review]
@dacook I have removed the duplicated test.

File: spec/models/proxy_order_spec.rb (hunk 6 above)
Comment (dacook) [reply spec/models/proxy_order_spec.rb:218]: Good point, I didn't think about it that way 👍

**Comment by dacook** [comment]
I'm guessing to cause this issue, you'd need to do something like:
* Set up an order cycle with subscriptions to close soon.
* When the order cycle closes, the proxy orders would be created.
* then update the order cycle: remove the end date
* Then view the subscriptions screen.

Given that it's such a small code change I'm not sure it's worth manual testing actually. @rioug would you agree to skip it for this one?

**Review by mkllnk — APPROVED** [review]
Happy to merge this straight away.
