### PR TITLE
notify the user if any order cannot be invoiced on bulk invoice sending

### LINKED ISSUE #12373: [Invoices] Bulk printing invoices must show error if ABN is required but not set
## Description
**This should only be fixed under invoice feature toggle**

Similar to #12374.

When an instance has the setting "Require an ABN to generate an invoice" ACTIVE, then an error is shown in case an enterprise without ABN tries to generate an invoice. Currently this is only working on the Edit Order page (`/admin/orders/Rxxx/edit`).
The exact same error has to be shown as well, if invoices are to be generated on the orders page via bulk action (`/admin/orders`). Currently there is no such error on this page.

In case of selected orders of multiple enterprises, no invoice should be printed at all after the error message was shown, even in case some of the enterprises have the ABN set correctly. The error message must be shown for each enterprise with missing ABN or all of the enterprises with missing ABN must be listed in the error message.

The error shall be shown independently from:
- New admin v3 feature toggle activated/deactivated
- Enterprise setting "Charges GST" activated/deactivated

## Expected Behavior

The error "Enterprise XY must have a valid ABN before invoices can be used." must be shown on the orders page when generating an invoice in case the instance has the setting "Require an ABN to generate an invoice" ACTIVE, and the enterprise has no ABN set.

## Actual Behaviour

There is no error when generating an invoice on the orders page while the setting "Require an ABN to generate an invoice" is ACTIVE and the enterprise has no ABN set.

## Steps to Reproduce

Make sure this is only done when feature toggle "invoices" is turned ON

1. As super admin activate the setting "Require an ABN to generate an invoice" (`/admin/invoice_settings/edit`).
2. As admin user (or super admin user) create an enterprise and leave the ABN field empty (`/admin/enterprises/<Enterprise xy>/edit#/business_details_panel`). You can also use an existing enterprise and delete the input of the ABN setting.
3. Make sure there is a completed order available for that enterprise.
4. On page /admin/orders select the checkbox of the order and choose 'Print invoices' from the 'Actions' dropdown menu.
5. Check if the error is shown or not.

## Animated Gif/Screenshot

Instance setting:
image

Enterprise ABN setting:
image

Create invoice on Orders page:
image

Expected error message. It is currently only shown when generating the invoice on the Edit Order page:
image

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### LINKED ISSUE #12374: [Invoices] Bulk sending invoices must show error if ABN is required but not set
## Description

**This should only be fixed under invoice feature toggle**

Similar to #12373.

When an instance has the setting "Require an ABN to generate an invoice" ACTIVE, then an error is shown in case an enterprise without ABN tries to send an invoice. Currently this is only working on the Edit Order page (`/admin/orders/Rxxx/edit`).
The exact same error has to be shown as well, if invoices are to be sent on the orders page via bulk action (`/admin/orders`). Currently there is no such error on this page but the email is NOT sent.

In case of selected orders of multiple enterprises, no invoice should be sent at all after the error message was shown, even in case some of the enterprises have the ABN set correctly. The error message must be shown for each enterprise with missing ABN or all of the enterprises with missing ABN must be listed in the error message.

The error shall be shown independently from:
- New admin v3 feature toggle activated/deactivated
- Enterprise setting "Charges GST" activated/deactivated

## Expected Behavior

The error "Enterprise XY must have a valid ABN before invoices can be used." must be shown on the orders page when sending an invoice in case the instance has the setting "Require an ABN to generate an invoice" ACTIVE, and the enterprise has no ABN set. The email must not be sent (this part is working already).

## Actual Behaviour

There is no error when sending an invoice on the orders page while the setting "Require an ABN to generate an invoice" is ACTIVE and the enterprise has no ABN set.

## Steps to Reproduce

Make sure this is only done when feature toggle "invoices" is turned ON

1. As super admin activate the setting "Require an ABN to generate an invoice" (`/admin/invoice_settings/edit`).
2. As admin user (or super admin user) create an enterprise and leave the ABN field empty (`/admin/enterprises/<Enterprise xy>/edit#/business_details_panel`). You can also use an existing enterprise and delete the input of the ABN setting.
3. Make sure there is a completed order available for that enterprise.
4. On page /admin/orders select the checkbox of the order and choose 'Send invoices' from the 'Actions' dropdown menu.
5. Check if the error is shown or not.
6. Check if the email is sent or not.

## Animated Gif/Screenshot

Instance setting:
image

Enterprise ABN setting:
image

Send invoice on Orders page:
image

Expected error message. It is currently only shown when sending the invoice on the Edit Order page:
image

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #12374 
- Closes #12373

#### What should we test?

- describe on #12373 && #12374 
- 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/reflexes/admin/orders_reflex.rb [hunk 1]
```diff
@@ -133,5 +123,30 @@ def render_business_number_required_error(distributors)
...
+    end
+
+    def abn_required?
+      Spree::Config.enterprise_number_required_on_invoices?
+    end
+
+    def distributors_without_abn(orders)
+      Enterprise.where(
+        id: orders.select(:distributor_id),
+        abn: [nil,""],
```
Comment (rioug) [inline app/reflexes/admin/orders_reflex.rb]: The empty string `abn`isn't cover by specs, could you update that ?

**Review by rioug — CHANGES_REQUESTED** [review]

**Review by rioug — APPROVED** [review]
All Good now, Thanks @abdellani !

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

Tried both described scenarios, after making ABN mandatory for the instance, and deleting the ABN for the enterprise. On the orders page:

- attempting to print the invoice

image


- attempting to send the invoice per email

image 

Looks great! Merging :-)
