### PR TITLE
fix Bulk invoice printing/sending

### LINKED ISSUE #11046: [Invoices] Bulk invoice printing is showing endless spinner (Bugsnag)
## Description

Follow up of #10532.

When printing invoices in bulk there is an endless spinner and the invoices are not printed.
Here is the related bugsnag: https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/648834087e655d000884c36e?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open&filters%5Bapp.release_stage%5D=staging

## Expected Behavior

Print invoices.
No Bugsnag.

## Actual Behaviour

No invoices.
Bugsnag.

## Steps to Reproduce

1. Select one or more orders in the orders list.
2. Select 'Print invoices' from the actions dropdown menu.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### LINKED ISSUE #11047: [Invoices] Bulk sending invoices is not working (Bugsnag)
## Description

Follow up of #10532.

When trying to send bulk invoices there is a confirmation on screen but to emails are sent and there is a Bugsnag triggered.
This is the Bugsnag (same as in #11046): https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/648834087e655d000884c36e?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open&filters%5Bapp.release_stage%5D=staging

## Expected Behavior

Sending bulk invoices should work.
There should be no Bugsnag.

## Actual Behaviour

Sending bulk invoices doesn't work.
There is a Bugsnag.

## Steps to Reproduce

1. Select one or more orders in the orders list.
2. Select 'Send invoices' from the action dropdown menu.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### LINKED ISSUE #11149: New, alternative invoice fails on rendering logo
## Error in OpenFoodNetwork UK

**ActionView::Template::Error** in **BulkInvoiceJob@default**
wrong number of arguments (given 0, expected 1)

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/649da007fc68d5000829f088?event_id=649da03800becd23cc5e0000&i=gh&m=ci)

## Stacktrace

    app/models/enterprise.rb:299 - logo_url
    app/views/spree/admin/orders/invoice4.html.haml:9 - _app_views_spree_admin_orders_invoice__html_haml__1057873861057224477_152240
    app/services/invoice_renderer.rb:10 - render_to_string
    app/jobs/bulk_invoice_job.rb:11 - block in perform
    app/jobs/bulk_invoice_job.rb:10 - each
    app/jobs/bulk_invoice_job.rb:10 - perform

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/649da007fc68d5000829f088?event_id=649da03800becd23cc5e0000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### Steps to reproduce

* You need a distributor with logo.
* The distributor needs to activate displaying the logo on invoices.
* You need to activate the new invoices.
* The instance needs to have the alternative invoice template activated.
* Create a new invoice.

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #11046 
- Closes #11047
- Closes #11149

#### What should we test?

- Try to run bulk invoice printing/sending with default invoice and alternative invoice

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
Still a draft, moving into 'In dev'

File: spec/jobs/bulk_invoice_job_spec.rb [hunk 1]
```diff
@@ -3,19 +3,73 @@
...
+        [order1, order3].each do |order|
+          expect(subject).to receive(:generate_invoice).with(order)
+        end
+        expect(subject).not_to receive(:generate_invoice).with(order2)
+
+        subject.perform(order_ids, "/tmp/file/path")
+      end
+    end
+
+    describe "#generate_invoice" do
```
Comment (dacook) [inline spec/jobs/bulk_invoice_job_spec.rb:47]: Generally it's better to test the result from the public method, rather than directly testing internal methods. Perhaps it's a bit less efficient, and requires a bit more setup, but it would be less dependent on the inner workings.

**Review by dacook — CHANGES_REQUESTED** [review]
This PR overlaps with #11204. In this case, they're closely related and could have simply been included in the one PR, closing both issues.

I've reviewed the unique commits on this one and I think it's good, with a small suggestion to improve.

I do notice that there's a lot of mocking in these tests, with a lot of `expect.to receive`. I think this should used minimally, because it's better to test with the real object data. Certainly there can be a balance, but I would suggest for future development, to mock less and set up more real data.
Also as noted, it's better to test the results from the public method.

File: spec/jobs/bulk_invoice_job_spec.rb (hunk 1 above)
Comment (abdellani) [reply spec/jobs/bulk_invoice_job_spec.rb:47]: Hi @dacook 
are you suggesting removing that test?

btw the previous test `#sorted_orders` is also checking a private method.

Comment (dacook) [reply spec/jobs/bulk_invoice_job_spec.rb:47]: I suggest that everything should be tested from the public methods (`perform`) if possible.

The  "#generate_invoice" test is checking that a string from the renderer is being saved to a PDF.  I guess it's also checking that the _right_ renderer is used, but it's not using a 'real' renderer, so it doesn't seem like a thorough test.

Can we test that from `perform`? Yes I think we can check the contents of the PDF, and we could check for some orders details (like customer name and product name). To test for the _right_ renderer, is there a unique string that could be searched? If not, then yes perhaps it's worth doing the mocking here, but I'd try mocking a 'real' renderer.

Honestly I'm not sure the best way to balance between smaller/independent "unit" tests, and larger/real-life "integration" tests. But I would normally draw the line at private methods, and only use mocks sparingly.

How about we wait and see what a second reviewer says before making any change.

**Review by dacook — APPROVED** [review]
Hooray, closing three issues!

I think this is fine, although as discussed it would be great to have another perspective on the testing.

File: spec/jobs/bulk_invoice_job_spec.rb (hunk 1 above)
Comment (rioug) [reply spec/jobs/bulk_invoice_job_spec.rb:47]: I am with David here, we shouldn't be testing private method directly. As far as I understand, we are creating pdf for each invoice, so you should be able to look at the pdf to see if they have been generated with the correct data. 

We are probably in the realm of integration testing here, but I think that's fine. I am not sure if any of this would be tested somewhere else.

Comment (abdellani) [reply spec/jobs/bulk_invoice_job_spec.rb]: Ok, so I remove the private method tests + the mocks
I added new instructions to validate the content of the generated PDF.

File: spec/mailers/order_mailer_spec.rb [hunk 2]
```diff
@@ -216,4 +216,41 @@
...
+    subject(:email) { described_class.invoice_email(order) }
+    let(:order) { create(:completed_order_with_totals) }
+    let!(:invoice_data_generator){ InvoiceDataGenerator.new(order) }
+    let!(:invoice){
+      create(:invoice, order:,
+                       data: invoice_data_generator.serialize_for_invoice)
+    }
+
+    let(:generator){ double(:generator) }
+    let(:renderer){ double(:renderer) }
```
Comment (rioug) [inline spec/mailers/order_mailer_spec.rb:230]: I would use `instance_double` here, from the [doc](https://github.com/rspec/rspec-mocks/tree/main/features/verifying_doubles) : "Verifying doubles are a stricter alternative to [normal doubles](https://github.com/rspec/rspec-mocks/blob/main/features/verifying_doubles/basics/test-doubles) that provide guarantees about what is being verified."

**Review by rioug — APPROVED** [review]
Nice one ! I think there is a small change you could do, see my comment, but nothing blocking the PR

File: config/locales/en.yml [hunk 3]
```diff
@@ -4080,6 +4080,11 @@ See the %{link} to find out more about %{sitename}'s features and to start using
           from: "From"
           to: "Bill to"
           shipping: "Shipping"
+          payments_list:
+            date_time: "Date/time"
+            payment_method: "Payment method"
+            payment_state: "Payment state"
+            amount: "Amount"
```
Comment (dacook) [inline config/locales/en.yml:4087]: That's strange that this would be required only now, is it because the spec is now covering the template generation? 
It probably would have been picked up in manual testing, but I guess this shows how it's valuable to test without mocks where possible ;)

**Review by mkllnk — APPROVED** [review]

**Comment by mkllnk** [comment]
There's a conflict that needs resolving. Moving back to In Dev for that.

File: spec/mailers/order_mailer_spec.rb (hunk 2 above)
Comment (abdellani) [reply spec/mailers/order_mailer_spec.rb]: that's new for me
thank you for sharing :+1:

**Review by rioug — APPROVED** [review]
:+1:

**Review by dacook — APPROVED** [review]
Nice work!

**Comment by drummer83** [comment]
Hi @abdellani,
Thanks for continuing your work on this. We can see a lot of improvement, but I think we aren't there yet. 

## Test scenarios
### New invoices active (feature toggle on)
| Task  | Standard invoice | Alternative invoice |
| - | - | - |
| Print bulk invoices | :x: No enterprise name & address on invoice | :x: Endless spinner ([Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64883d4eb464420008d0d1ab?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging)) |
| Send bulk invoices | :x: See 'print' above | :x: No logo, no enterprise name & address if invoice exists already; :x: No email sent if invoice does not yet exist ([Same Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64883d4eb464420008d0d1ab?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging)) |
| Display individual invoices | :x: See 'print' above | :x: Error 500 (no Bugsnag) |

### Previous (old) invoice implementation (feature toggle off)
| Task  | Standard invoice | Alternative invoice |
| - | - | - |
| Print bulk invoices | invoices of incomplete orders sent as well, no logo | :x: Endless spinner if no invoice had been created earlier for this order ([Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64ca63c1abf0a70008dd8bb2?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging)) |
| Send bulk invoices | no logo | :heavy_check_mark: |
| Display individual invoices | no logo | :heavy_check_mark: |

1. The order doesn't have any invoice yet. In this case, we can list the following sub-cases: 
a. the order completed/resumed :arrow_right: **create invoice and send it** :heavy_check_mark: 
b. the order is not completed yet :arrow_right: **do nothing** :heavy_check_mark: 
c. the order is canceled :arrow_right: **do nothing** (because current invoices are not displaying that the order was cancelled) :heavy_check_mark: 

2. The order has at least one invoice. In this case, we have:
a. the order is not updated since the last invoice. :arrow_right: **send invoice** :heavy_check_mark: 
b. the order is updated since the last invoice, and the changes will require regenerating the latest invoice. :arrow_right: **update invoice and send it** :heavy_check_mark: Works in principle but not all changes are mapped correctly (e.g. when payment state changes the invoice should update, but a new one is generated instead).
c. the order is updated since the last invoice, and the changes will require generating a new invoice. :arrow_right: **create invoice and send it** :x: New invoices are created, but the first (oldest) one is sent.

### Open tasks for final detailed testing
- Invoice update and new creation according to specification in separate document.

### Other improvements
- The listed invoices should always be in order (ascending or descending). When mixing automatic creation due to invoice sending/printing with manual creation the order can be messed up:
image

## Conclusion
The :x: should be fixed before we go on. Also we should be careful about merging this one because it seems that the bulk printing of invoices is broken in some cases even if the feature toggle is switched off.
I will move this back to In Dev. Let me know if you think differently.
Thanks gain! :pray:

**Comment by abdellani** [comment]
Hi @drummer83 

Thank you for the detailed report, that was really helpful :pray: 

I solved most of the issues and tested them manually on my local environment. I just need more clarifications on some cases (I used :exclamation: next to them)
>### New invoices active (feature toggle on)

Task | Standard invoice | Alternative invoice
-- | -- | --
Print bulk invoices | No enterprise name & address on invoice (:heavy_check_mark: Solved & tested locally) | Endless spinner (Bugsnag) (:heavy_check_mark:Solved & tested locally)
Send bulk invoices | See 'print' above (:exclamation: I need more details) |<ul><li> No logo (:heavy_check_mark: Solved & tested locally)</li><li>no enterprise name & address if invoice exists already; (:heavy_check_mark: Solved & tested locally)</li><li> No email sent if invoice does not yet exist (Same Bugsnag)(:heavy_check_mark: Solved & tested locally)</li></ul>
Display individual invoices | See 'print' above (:exclamation: I need more details) |  Error 500 (no Bugsnag) (:heavy_check_mark: Solved & tested locally)

-------------------
>c. the order is updated since the last invoice, and the changes will require generating a new invoice. arrow_right create invoice and send it x New invoices are created, but the first (oldest) one is sent.

This problem is solved on #11116

--------------------
> Other improvements
The listed invoices should always be in order (ascending or descending). When mixing automatic creation due to invoice sending/printing with manual creation the order can be messed up:
image

This is already solved on  https://github.com/openfoodfoundation/openfoodnetwork/pull/11116

**Comment by abdellani** [comment]
> Hi @abdellani, Sorry for being lazy. 😉 By
> 
> > See 'print' above (exclamation I need more details)
> 
> I mean 'No enterprise name & address on invoice'. Just the same as for 'Print Bulk Invoices'.
> 
> I hope this makes it clear?

No worries. 
I thought you were referring to the UI, haha :)
In that case, I think that the problem is solved.

**Review by mkllnk — APPROVED** [review]
Looking good!

@abdellani, it looks like you amended previous commits and rewrote the Git history. Once the code has been reviewed it's better to add only new commits so that the reviewers see exactly what changed.

Sometimes that can make the history a bit bulky or contain detours but if your original development missed something then it's usually a good idea to point out the new learning in a new commit. It was probably something that was not obvious and anyone looking into the history later then knows that it's something to watch out for.

**Comment by RachL** [comment]
I'm merging this PR to ease testing. I will create issues for each update / create workflow that is not working. Endless spinner when toggle is off is fixed 🎉

**Comment by drummer83** [comment]
> I will create issues for each update / create workflow that is not working.

@RachL Have these issues been created? It seems to me that at least bulk invoice printing is still broken with the toggle activated. And I can't find an issue for this.

**Comment by RachL** [comment]
@drummer83 I can use bulk invoice printing with the toggle but let's dive again into this once we have the new template. Otherwise we will look at it twice :+1:
