### PR TITLE
2113 Display only selected languages in switcher

### LINKED ISSUE #2113: Multilingual language listing
With multilingual, the displayed languages can't be controlled, and the default language gets appended to the available languages listed in the `AVAILABLE_LANGUAGES` list. 

screenshot from 2018-03-05 16-20-13

## Description
`en` is being added to the languages list when it shouldn't be.

## Expected Behavior
A list of available languages can be defined in `application.yml`, and the languages shown should not be different from that list.

## Actual Behavior
Extra languages get added in, possibly just the default/fallback language.

## Steps to Reproduce
screenshot from 2018-03-05 17-22-48

## Context
Instances using multilingual.

## Severity
S2

## Possible Fixes
1. Add another env variable, which lists the languages to be shown?
2. Using the order in exisitng `available_locales` e.g. `[en, en_GB]` means that `en` is the fallback

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #2113.

#### What should we test?

The display and behaviour of the language switcher with different locale configurations.

#### Release notes

Fixed bug that always displayed an additional "English" in the language switcher if the server didn't have `en` configured as language.

#### How is this related to the Spree upgrade?

Not at all.

### CODE REVIEW

**Comment by lin-d-hop** [comment]
Sweeeet! @myriamboure @kirstenalarsen (product managers this round) and @daniellemoorhead 
Note this is a bug that affects all non-default-en instances so it would be good to patch this on the last release.

**Comment by myriamboure** [comment]
@sauloperez if you can quickly review we can hopefully stage that maybe today or tomorrow somewhere?

File: lib/open_food_network/i18n_config.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    end
+
+    def self.default_locale
+      ENV["LOCALE"] || ENV["I18N_LOCALE"] || source_locale
+    end
+
+    def self.source_locale
+      "en"
+    end
+  end
```
Comment (sauloperez) [inline lib/open_food_network/i18n_config.rb]: can we doc what's the purpose of each these methods? It takes some time to guess.

File: spec/features/consumer/multilingual_spec.rb [hunk 2]
```diff
@@ -71,11 +71,10 @@
 
   describe "using the language switcher UI" do
     context "when there is only one language available" do
-      around do |example|
-        available_locales = I18n.available_locales
-        I18n.available_locales = ['en']
-        example.run
-        I18n.available_locales = available_locales
+      before do
+        allow(ENV).to receive(:[]).and_call_original
```
Comment (sauloperez) [inline spec/features/consumer/multilingual_spec.rb]: why this stub?

File: config/application.rb [hunk 3]
```diff
@@ -1,6 +1,7 @@
 require_relative 'boot'
 
 require 'rails/all'
+require_relative "../lib/open_food_network/i18n_config"
```
Comment (enricostano) [inline config/application.rb]: this shouldn't be necessary, Rails should load code in `lib/`

Comment (sauloperez) [reply config/application.rb]: AFAIK `lib/` is not loaded by deafult only code within `app/`

Comment (mkllnk) [reply config/application.rb]: I found that this was necessary.

Comment (mkllnk) [reply config/application.rb]: We could auto-load lib, but is that the cleanest way to do it? It would mean that we load e.g. rake tasks into our main application. I would like a second opinion before doing this.

Comment (sauloperez) [reply config/application.rb]: AFAIK auto-loading `lib/` is not a good practice. I don't see it a big deal to add a require when we need a lib.

Comment (enricostano) [reply config/application.rb]: `require_relative` is a bit of an anti-pattern in Rails, but we can live with it

Comment (mkllnk) [reply config/application.rb]: A tried to use `Rails.root`, but that was empty when loading a rake task.

File: spec/features/consumer/multilingual_spec.rb [hunk 4]
```diff
@@ -84,21 +83,29 @@
       end
     end
 
-    it "allows switching language via the main navigation" do
-      visit root_path
+    context "when there are multiple languages available" do
+      before do
+        allow(ENV).to receive(:[]).and_call_original
```
Comment (sauloperez) [inline spec/features/consumer/multilingual_spec.rb]: I'm wondering why we need this line. AFAIK we are just stubbing a particular env var in the line below and not affecting the rest of ENV.

Comment (sauloperez) [reply spec/features/consumer/multilingual_spec.rb]: I don't see this done in other specs.

File: config/application.rb (hunk 3 above)
Comment (enricostano) [reply config/application.rb]: we should always try to use `require` but don't worry, let's move on. we'll see if it cause any problem in the future

:+1:

File: spec/features/consumer/multilingual_spec.rb (hunk 4 above)
Comment (mkllnk) [reply spec/features/consumer/multilingual_spec.rb]: We stub the call of `[]` on ENV. But in a feature spec, a lot more variables are accessed than the ones we stub here. I got an error that call of something like `ENV['TMP_DIR']` was not expected. The test doesn't want to care about all the other environment variables and therefore I put this catch all in. Is there a better way?

**Comment by pacodelaluna** [comment]
Just deployed it on https://staging.openfoodfrance.fr. @myriamboure Seems good, can't see locale select anymore.

**Comment by myriamboure** [comment]
Cool :-) So yes in use case "nothing is done, only default language is there" this work, no language witcher.
screenshot from 2018-03-22 23-50-18
I guess @pacodelaluna  to fully test we want maybe to enable multi-language and add two locals that are not english (like spanish and french) and check that English is not added. But this needs to be done on server side so can't do it myself. @mkllnk if you see that before we have time to do that on French server (it's late already here) please go ahead to try with this other case... before merging :-)

**Comment by pacodelaluna** [comment]
@myriamboure I have enabled ES and FR locales, the logic is working fine but there is still a translation issue.

**Comment by myriamboure** [comment]
Ok so quick image yes we see language switcher BUT we see only English - English
screenshot from 2018-03-23 13-54-07
Why that ?
I checked in Transifex but the translation at least for French is there:
screenshot from 2018-03-23 13-53-19

Also I'm wondering: where should be the translation for "Spanish" if I want to enable French and Spanish on French instance? I only have one `language_name` key in Transifex. @mkllnk can you explain how we can do that? And why in this case one of the two English is not Français as language_name key is properly translated in Transifex?

**Comment by pacodelaluna** [comment]
@myriamboure Ok, my bad, translations are not pulled properly with ofn-install, had to pull them manually, but then it is working properly I guess.

**Comment by myriamboure** [comment]
Ok I deleted my precedent comment to avoid confusion. So now I see the language switcher working properly:
screenshot from 2018-03-23 14-18-51
I notice that language `es` here is translated as "Castellano" but I guess it's fine if every language appear in the corresponding language, will be easier for people speaking those languages to find them an switch languages.
So it seems all good for me, ready to go!
