### PR TITLE
Fix error when confirming order fails.

### LINKED ISSUE #14184: ActionView::Template::Error in checkout#update
## Error in Coopcircuits

**ActionView::Template::Error** in **checkout#update**
undefined method '>' for nil

[View on Bugsnag](https://app.bugsnag.com/open-food-france/coopcircuits/errors/69e08cb27aaa488f2c3f77a4?event_id=69e13f080174c4e02b190000&i=gh&m=ci)

## Stacktrace

    app/views/checkout/_summary.html.haml:82 - block in _app_views_checkout__summary_html_haml__2626251347382874836_275744
    app/views/checkout/_summary.html.haml:1 - _app_views_checkout__summary_html_haml__2626251347382874836_275744
    app/views/checkout/_form.html.haml:5 - _app_views_checkout__form_html_haml__2187513233101480647_275736
    app/views/checkout/_checkout.html.haml:4 - _app_views_checkout__checkout_html_haml__3318372642985210172_275720
    app/controllers/concerns/cablecar_responses.rb:13 - CablecarResponses#partial
    app/controllers/checkout_controller.rb:72 - CheckoutController#render_error
    app/controllers/checkout_controller.rb:56 - CheckoutController#update
    app/services/order_locker.rb:18 - block in OrderLocker.lock_order_and_variants
    app/services/order_locker.rb:16 - OrderLocker.lock_order_and_variants
    app/services/current_order_locker.rb:13 - CurrentOrderLocker.around
    app/controllers/concerns/checkout_callbacks.rb:38 - CheckoutCallbacks#sync_stock

[View full stacktrace](https://app.bugsnag.com/open-food-france/coopcircuits/errors/69e08cb27aaa488f2c3f77a4?event_id=69e13f080174c4e02b190000&i=gh&m=ci)

*Created by Coopcircuits Admin via Bugsnag*

### PR DESCRIPTION
**Pull request by rioug**
## What? Why?

- Closes #14184  

When an error happens when confirming an order, re rendering the summary step fails because `@paid_with_credit` is not calculated. This PR fix this 

## What should we test?

Set up an enterprise requiring term and condition to place an order. You can do that by uploading a terms and condition file in the enterprise configuration page, in the "Business Details" section.
As a customer :
- Start an order with the enterprise and proceed to checkout
- On the summary step, make sure the "I agree to the platform Terms of service." is unticked.
- Try completing the order :
  -> you see the summary page again with an error message.

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/controllers/checkout_controller.rb [hunk 1]
```diff
@@ -64,7 +64,8 @@ def update
   private
 
   def render_error
-    @paid_with_credit = calculate_credit(@order) if payment_step?
+    # TODO fix this , error on moving to summary ?
```
Comment (dacook) [inline app/controllers/checkout_controller.rb]: Do you mean that there shouldn't ever be an error when moving to summary? Maybe we should investigate that instead?

But as this instance variable is required by a view, I reckon a better way to solve this would be to move this to a helper, so that the view can request the value on-demand, instead of trying to guess if we will need it or not.

**Review by dacook — CHANGES_REQUESTED** [review]
I have an idea for a more resilient fix:

File: app/controllers/checkout_controller.rb (hunk 1 above)
Comment (rioug) [reply app/controllers/checkout_controller.rb]: That TODO should not have been committed ... It meant there is an error when loading the summary step in `render_error`, which is what this PR fixes.

 > But as this instance variable is required by a view, I reckon a better way to solve this would be to move this to a helper, so that the view can request the value on-demand, instead of trying to guess if we will need it or not.
 
It sort of make sense, but I don't like the approach. In my mind the controller should be providing the data the view needs, the view shouldn't be requesting data. And we know @paid_with_credit is needed on the payment and summary steps so we are not guessing here.

Comment (dacook) [reply app/controllers/checkout_controller.rb]: Fair enough, that's another way to look at it. The controller should have control over what's happening, which may help ensure we know what we're loading, and we could load things more efficiently.

**Review by dacook — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]
Great!

I agree that the controller should load the data in most cases. When helpers load data, it can be really convenient and also trigger far too many queries. Helpers are part of the view layer in my mind.

**Comment by mkllnk** [comment]
Testing on au-staging.

- I can reproduce the bug with Magic farm.
- I'm going back to the summary page and wait for the deployment to finish. Asset compilation is slow....
- Now I see error messages on the summary page:
  * _Saving failed, please update the highlighted fields._ at the top.
  * _Please accept Terms and Conditions_ by the checkbox.
- Repeating the same thing results in the same error messages.
- Ticking the box and submitting is successful. Order confirmation is shown. :heavy_check_mark: 

image
