### PR TITLE
Adapt line_items_spec to work in the rails 4 branch as well

### LINKED ISSUE #4892: [Spree 2.1] Fix models/line_items_spec (2 broken specs)
```
  10) Spree::LineItem scopes finding line items with and without tax finds line items with tax
      Failure/Error: expect(LineItem.with_tax).to eq([li1])
      
        expected: [#<Spree::LineItem id: 136, order_id: 129, variant_id: 1198, quantity: 1, price: #<BigDecimal:7fd21c6...c1a728,'0.1E1',9(36)>, cost_price: #<BigDecimal:7fd225221308,'0.17E2',9(36)>, tax_category_id: nil>]
             got: #<ActiveRecord::Relation []>
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,2 @@
        -[#<Spree::LineItem id: 136, order_id: 129, variant_id: 1198, quantity: 1, price: #<BigDecimal:7fd21c6a1968,'0.1E2',9(18)>, created_at: "2020-03-02 18:41:35", updated_at: "2020-03-02 18:41:35", max_quantity: nil, currency: "AUD", distribution_fee: nil, final_weight_volume: #<BigDecimal:7fd21cc1a728,'0.1E1',9(36)>, cost_price: #<BigDecimal:7fd225221308,'0.17E2',9(36)>, tax_category_id: nil>]
        +[]
        
      # ./spec/models/spree/line_item_spec.rb:49:in `block (4 levels) in <module:Spree>'

  11) Spree::LineItem scopes finding line items with and without tax finds line items without tax
      Failure/Error: expect(LineItem.without_tax).to eq([li2])
      
        expected: [#<Spree::LineItem id: 139, order_id: 132, variant_id: 1213, quantity: 1, price: #<BigDecimal:7fd1d13...81f720,'0.1E1',9(36)>, cost_price: #<BigDecimal:7fd1d47190f0,'0.17E2',9(36)>, tax_category_id: nil>]
             got: #<ActiveRecord::Relation [#<Spree::LineItem id: 138, order_id: 132, variant_id: 1208, quantity: 1, pr...70110,'0.1E1',9(18)>, cost_price: #<BigDecimal:7fd1de870048,'0.17E2',9(18)>, tax_category_id: nil>]>
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,3 @@
        -[#<Spree::LineItem id: 139, order_id: 132, variant_id: 1213, quantity: 1, price: #<BigDecimal:7fd1d13eda50,'0.1E2',9(18)>, created_at: "2020-03-02 18:41:36", updated_at: "2020-03-02 18:41:36", max_quantity: nil, currency: "AUD", distribution_fee: nil, final_weight_volume: #<BigDecimal:7fd1dd81f720,'0.1E1',9(36)>, cost_price: #<BigDecimal:7fd1d47190f0,'0.17E2',9(36)>, tax_category_id: nil>]
        +[#<Spree::LineItem id: 138, order_id: 132, variant_id: 1208, quantity: 1, price: #<BigDecimal:7fd1de871df8,'0.1E2',9(18)>, created_at: "2020-03-02 18:41:35", updated_at: "2020-03-02 18:41:35", max_quantity: nil, currency: "AUD", distribution_fee: nil, final_weight_volume: #<BigDecimal:7fd1de871218,'0.1E1',9(18)>, cost_price: #<BigDecimal:7fd1de871150,'0.17E2',9(18)>, tax_category_id: nil>,
        + #<Spree::LineItem id: 139, order_id: 132, variant_id: 1213, quantity: 1, price: #<BigDecimal:7fd1de870c50,'0.1E2',9(18)>, created_at: "2020-03-02 18:41:36", updated_at: "2020-03-02 18:41:36", max_quantity: nil, currency: "AUD", distribution_fee: nil, final_weight_volume: #<BigDecimal:7fd1de870110,'0.1E1',9(18)>, cost_price: #<BigDecimal:7fd1de870048,'0.17E2',9(18)>, tax_category_id: nil>]
        
      # ./spec/models/spree/line_item_spec.rb:53:in `block (4 levels) in <module:Spree>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #4892 

See commit message.

#### What should we test?
Green build.

#### Release notes
Changelog Category: Changed
Adapt test code to rails 4.

### CODE REVIEW

File: spec/models/spree/line_item_spec.rb [hunk 1]
```diff
@@ -40,10 +40,13 @@ module Spree
...
         let(:tax_rate) { create(:tax_rate, calculator: Spree::Calculator::DefaultTax.new) }
-        let!(:adjustment1) { create(:adjustment, adjustable: li1, originator: tax_rate, label: "TR", amount: 123, included_tax: 10.00) }
-        let!(:adjustment2) { create(:adjustment, adjustable: li1, originator: tax_rate, label: "TR", amount: 123, included_tax: 10.00) }
+        let!(:adjustment1) { create(:adjustment, originator: tax_rate, label: "TR", amount: 123, included_tax: 10.00) }
 
-        before { li1; li2 }
+        before do
+            li1
+            li2
+            li1.adjustments << adjustment1
```
Comment (Matt-Yorkley) [inline spec/models/spree/line_item_spec.rb]: I think something like this is causing #4898, it looks like there's a `Spree::Calculator` being created somewhere as part of creating an associated adjustment, but it isn't being saved or associated properly in some way.

I'm wondering if there's something that needs changing in the code instead of just the specs? Like here we're having to manually associate the adjustment to the line item to fix the spec, but does this indicate that adjustments will not be being associated correctly when the app is running?

Comment (luisramos0) [reply spec/models/spree/line_item_spec.rb]: yeah, I thought exactly the same.
I have found #4890 is also caused by some database cleaner issue that could be caused by something related to this, I agree.

ping @mkllnk @sauloperez thoughts?

Comment (Matt-Yorkley) [reply spec/models/spree/line_item_spec.rb]: The bits we manually fixed in relation to enterprise_roles were similar, no?

Comment (Matt-Yorkley) [reply spec/models/spree/line_item_spec.rb]: Interesting... I just tried bumping the `database_cleaner` version with `bundle update database_cleaner`. It moved from 1.7.8 to 1.8.3 and those failing specs have changed slightly; there's a warning output during those tests: `WARNING:  there is already a transaction in progress`, and the error messages are different...

Comment (Matt-Yorkley) [reply spec/models/spree/line_item_spec.rb]: I think after each test it closes all open transactions, and somehow there are some incomplete transactions left open due to associations not saving or some error being raised and then rescued in an odd way...

Comment (Matt-Yorkley) [reply spec/models/spree/line_item_spec.rb]: Possibly related: https://github.com/DatabaseCleaner/database_cleaner/issues/198

Comment (Matt-Yorkley) [reply spec/models/spree/line_item_spec.rb]: Also possibly related: https://github.com/rails/rails/pull/14488

Comment (Matt-Yorkley) [reply spec/models/spree/line_item_spec.rb]: Maybe @jonleighton has some advice, as he's all over the code review in the above mentioned Rails PR from 2014 :point_up: 

:pray:

Comment (jonleighton) [reply spec/models/spree/line_item_spec.rb]: Hi! I've had a little look but I'm afraid it's impossible for me to say anything useful without spending a lot more time digging. I don't have enough context at the moment to understand this issue, or whether it's even related to the Rails PR you linked (which was a long time ago and my memory is pretty hazy!) Sorry I can't be of more help.

Comment (Matt-Yorkley) [reply spec/models/spree/line_item_spec.rb]: Haha, no worries.

Comment (Matt-Yorkley) [reply spec/models/spree/line_item_spec.rb]: Notes/discussion moved to #4898. I think we've almost got it cracked...

Comment (luisramos0) [reply spec/models/spree/line_item_spec.rb]: So, this PR is still needed after the fix to #4890 and #4898.
I'd say we will be ok with this, it happens in factory code but in live code this is not how  adjustments are assigned to line items. Adjustments are created in  
Spree::Core::CalculatedAdjustments through target.create_adjustments which would break a lot of specs if it wasn't working.
I'd merge this and move forward.
