### PR TITLE
Suppress "Line items can't be blank" message on order creation process

### LINKED ISSUE #6205: Error message when creating an order in BO
## Description

When you create an order in back office, an error is displayed when you landing on the page to select products

## Expected Behavior
Error should be displayed only when getting to next steps without product, not landing on the page

## Actual Behaviour

Errors shows up when landing on the page

## Steps to Reproduce
1. Go on to `admin/orders?q[s]=completed_at+desc`
2. Click on "new order"
3. See the flash message when landing on the list of products

## Animated Gif/Screenshot

image

## Workaround
Just wait for the message to fade away

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v3.2.11
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Both

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
When creating a new order, it's not necessary to display the "Line items can't be blank" as the order has just been created and the user is rightly doing configuration.

The param `suppress_error_msg` was already passed through the request, but unused.
See commit 38c25c412f5e09015d2f5a3c35b28a5a5a5320bb that creates the `suppress_error_msg` param.

Closes #6205

#### What should we test?
1. Go on to `admin/orders`
2. Click on "new order"
3. Select DISTRIBUTOR and ORDER CYCLE
4. Click on "Next"
5. You shouldn't see the red banner message
6. Click on "Update And Recalculate Fees" button. You should see the red banner on top of screen

##### Update And Recalculate Fees on this new order: red banner on top
(this gif is done just after the previous one)

#### Release notes
Delete inappropriate error message on order creation

Changelog Category: User facing changes

### CODE REVIEW

File: app/controllers/spree/admin/orders_controller.rb [hunk 1]
```diff
@@ -38,6 +38,11 @@ def update
         @order.recreate_all_fees!
 
         unless order_params.present? && @order.update(order_params) && @order.line_items.present?
```
Comment (Matt-Yorkley) [inline app/controllers/spree/admin/orders_controller.rb:40]: We could reduce the 10 lines inside this block down to 6. What do you think?
```ruby
unless order_params.present? && @order.update(order_params) && @order.line_items.present?
  if @order.line_items.empty? && !params[:suppress_error_msg]
    @order.errors.add(:line_items, Spree.t('errors.messages.blank'))
  end

  flash[:error] = @order.errors.full_messages.join(', ') if @order.errors.present?
  return redirect_to spree.edit_admin_order_path(@order)
end
```

**Comment by Matt-Yorkley** [comment]
Cool :+1: 

We should probably add a test here to cover the code changes.

File: app/controllers/spree/admin/orders_controller.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/controllers/spree/admin/orders_controller.rb:40]: I like this better as well, it avoids comparing a param to the string `"true"`.

**Review by andrewpbrett — APPROVED** [review]
Looks good pending resolution of Matt's comment 👍

File: app/controllers/spree/admin/orders_controller.rb (hunk 1 above)
Comment (jibees) [reply app/controllers/spree/admin/orders_controller.rb:40]: I agree. I'm not familiar with `unless` and ruby syntax (like the `if` at the end of the statement) and I don't have the reflexes . Will do the changes, thanks a lot.

**Comment by jibees** [comment]
> We should probably add a test here to cover the code changes.

Sure: ca87325635068b49dc4272293ace5cb5d651bfb5

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by jibees** [comment]
2 approvals, moving to `Test Ready`

**Comment by filipefurtad0** [comment]
Uff, what a relief! :smile_cat: 
I have to be honest - I found #6205 and this bug #6459 quite annoying: your PR also closes both :muscle:

On the videos below - left, before this PR; right, after this PR.

- Relevant test case to close #6205
i) Creating a new order and selecting distributor and order cycle; (no red-banner is expected after this PR)
ii) Clicking "Update and Recalculate Fees" when no line items are added; (the red banner should be kept))

Peek 2021-04-22 16-31

- Relevant test case to close #6459:
When editing an order, pressing "Update and Recalculate fees" displays a banner with no message; fixed on the right screen.

Peek 2021-04-22 16-30

Good to go!

**Comment by RachL** [comment]
> Uff, what a relief! 😸

+100000 !!!
