### PR TITLE
14004 link correct customer to order

### LINKED ISSUE #14004: Wrong customer associated with order when switching shop
## Description

When a user is a customer in multiple shops, it is possible for customer associated with the order to not be the customer matching the order's distributor. This happen in when a customer start a new order with shop B after placing an order with Shop A, the new order will be associated with the Shop A's customer. It generally does not cause an issue, because customer have the ability to update details during the checkout process. 

This however will become an issue for Payment with credit: #13855 , because the solution relies on the order's customer to check available credit.  

## Expected Behavior

With a user being an existing customer for multiple shop. ie Shop A and Shop B. 
After placing an order with Shop A, when a user starts a new order with shop B, the customer associated with the order should be Shop B customer. 

## Actual Behaviour

With a user being an existing customer for multiple shop. ie Shop A and Shop B. 
After placing an order with Shop A, when a user starts a new order with shop B, the customer associated with the order is Shop A customer. 

## Steps to Reproduce

1. Have a user that is a customer in two different shop (Shop A and Shop B)
2. In the backoffice, update the two customers billing address with a distinct name. ie set first name to Shop A and ShopB  
3.Start an order with Shop A, on the checkout details step, you should see "Shop A" as first name for the billing address 
4. Finish placing the order
5. Navigate to Shop B
6. Start an order with **Shop B,** on the checkout details step, you should see **"Shop A"** as first name for the billing address.   

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
## What? Why?

- Closes #14004 

After placing an order shop A, and starting a new order on  shop B, the order stayed linked to customer from shop A. This PR update the `CartResetService` logic to properly update the customer when switching shop.

## What should we test?

- Have a user that is a customer in two different shop (Shop A and Shop B)
- In the backoffice, update the two customers billing address with a distinct name. ie set first name to Shop A and Shop B
- Start an order with Shop A, on the checkout details step, you should see "Shop A" as first name for the billing address
- Finish placing the order
- Navigate to Shop B
- Start an order with Shop B, on the checkout details step, 
 --> you should see "Shop B" as first name for the billing address.

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/services/orders/cart_reset_service.rb [hunk 1]
```diff
@@ -19,16 +19,17 @@ def reset_distributor
...
+      order.customer = current_customer if current_customer.present?
       order.save!
     end
 
     private
 
     attr_reader :order, :distributor, :current_user
 
-    def reset_user_and_customer(current_user)
+    def reset_user(current_user)
```
Comment (dacook) [inline app/services/orders/cart_reset_service.rb:32]: That was a badly named method! I guess something got changed but the method name stayed the same.

Comment (rioug) [reply app/services/orders/cart_reset_service.rb:32]: Indeed, once upon a time it called `associated_customer` on the order.

File: app/services/orders/cart_reset_service.rb [hunk 2]
```diff
@@ -19,16 +19,17 @@ def reset_distributor
     end
 
     def reset_other!(current_user, current_customer)
-      reset_user_and_customer(current_user)
+      reset_user(current_user)
       reset_order_cycle(current_customer)
+      order.customer = current_customer if current_customer.present?
```
Comment (mkllnk) [inline app/services/orders/cart_reset_service.rb]: What if it's not present? Maybe you don't have a customer record yet. Should we set it to nil?

Comment (mkllnk) [inline app/services/orders/cart_reset_service.rb]:
```suggestion
      order.customer = current_customer
```

Comment (rioug) [reply app/services/orders/cart_reset_service.rb]: True, for instance if you log out after placing an order and start a new order as a guest we end up the scenario where the order has a customer but system doesn't have a current customer. 

Fixed here : https://github.com/openfoodfoundation/openfoodnetwork/pull/14008/commits/d706b3a6c2073218535db1119ac63182cbcea8dc

**Review by mkllnk — APPROVED** [review]

**Comment by rioug** [comment]
Has discussed with @mkllnk and @dacook we'll merge without testing, it will be covered by payment with credit testing.
