### PR TITLE
[Payment with credit] Credit not deducted when paying with Paypal

### LINKED ISSUE #14090: Credit not deducted from orders with Paypal payment method
**⚠️ Please use clockify code # 80 UK digital inclusion**

## Description

The user was testing the applying credit functionality (via the new 'credit customer' button on the Payments screen) by refunding items and making negative adjustments on orders. They noticed that whilst the customer was seeing the credit as deducted from their order total, when they actually paid using a Paypal payment method, the credit was not deducted, and the full amount was charged.

## Expected Behavior

Customers paying with Paypal payment method, who have credit on their account, should be charged the order total minus available credit. The total sent to Paypal should be the order total, minus credit.

## Actual Behaviour

The customer's checkout screen shows the order total, minus credit, but progressing to Paypal checkout charges the original order total. The customer then loses the credit on their account (e.g. no credit shown in customer's account, nor Customers list) as if they have spent it, when they haven't

## Steps to Reproduce

1. Find/create a customer with credit
2. Start an order using a Paypal payment method
3. Go to checkout screen and observe credit value deducted from order total
4. Click checkout, and observe amount shown in Paypal is original order total without deducting credit
5. Place order
6. Observe credit now shown as 'spent' on customer's account

## Animated Gif/Screenshot

Checkout screen:
Image
Paypal checkout screen:

Image

Order payments screen for the original customer's order, showing the £0.21 credit as a payment line and the original order value at £29.38 as paid for with Paypal. But because the £0.21 was not deducted from the order value, the order is therefore showing as Credit Owed -£0.21 (the customer paid with their credit, **and** for their full order value with Paypal):

Image

## Workaround

Paying with another payment method, if available

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
**⚠️ Please use clockify code # 80 UK digital inclusion**

## What? Why?

- Closes #14090 

The Paypal related code used the `order.total` as payment amount when sending data to Paypal, which resulted in the wrong amount being paid. On top of this, once the payment confirmed, the code used to delete any pending payment and create a new one.
This PR fix the data sent to Paypal to use the Paypal pending payment amount, and also send the "discount data" ( the credit with payment part ). Confusingly, it modelled by  the `ShippingDiscount` field, but it's displayed as "Seller discount" on the Paylpal side.

Reviewers new commit starts here : https://github.com/openfoodfoundation/openfoodnetwork/pull/14146/changes/b11f5aee0d68dc588a97212ffcc1c7a017382cfe

## What should we test?

Set up  a shop with a Paypal payment method (my developer account credentials are in  Vaultwarden) 

#### Check Paypal payment are working
- Start a checkout
- Choose Paypal as payment method
- Finish checkout and complete order.
  --> Order is completed with no error, payment information are correct in the back office.
  
#### Check Paypa payment are working with customer credit  
- Add credit to a customer for the configured shop, we want to test credit that partially covers the order. ( see original PR https://github.com/openfoodfoundation/openfoodnetwork/pull/13963 for info about adding credit)
- Start an order and proceed to checkout
- On the payment step, check customer credit has been applied and covers part of the order.
- Choose Paypal payment method
- Finish checkout and complete order 
  --> Paypal ask you to pay only the amount not covered by credit
  --> Order is completed with no error, payment information are correct in the back office.

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [X] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

## Dependencies

~~This PR https://github.com/openfoodfoundation/openfoodnetwork/pull/14094 needs to be merged first.~~

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Thank you!

I stumbled across this weird behaviour a few times and wanted to fix it. It's a lot better now.

File: app/services/orders/find_payment_service.rb [hunk 1]
```diff
@@ -14,6 +14,14 @@ def last_pending_payment
       last(@order.pending_payments)
     end
 
+    def last_customer_credit
+      last(
+        @order.pending_payments.select do |payment|
+          payment.payment_method == Spree::PaymentMethod.customer_credit
+        end
+      )
+    end
```
Comment (dacook) [inline app/services/orders/find_payment_service.rb:23]: I'm guessing the pending_payments are already loaded, which is why we're looping instead of using a db query?

So if we're looping but looking for the last, can't we loop in reverse and choose the first? We could do `.reverse.find`, which doesn't need to evaluate any more items once it finds a match.
And it looks like ruby now has [`rfind`](https://docs.ruby-lang.org/en/4.0/Array.html#method-i-rfind) to do it in one step, yay!

File: app/services/paypal/payment_details_service.rb [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+          }
+        }
+        return payment_hash
+      end
+
+      payment_hash = {
+        OrderTotal: {
+          currencyID: order.currency,
+          value: last_payment.amount
+        },
```
Comment (dacook) [inline app/services/paypal/payment_details_service.rb:37]: This part is duplicated with the above branch, so we could DRY it up, which might help reduce the rubocop offences.

File: app/services/paypal/payment_details_service.rb [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+          currencyID: order.currency,
+          value: order.ship_total
+        },
+        TaxTotal: {
+          currencyID: order.currency,
+          value: tax_adjustments_total
+        },
+        ShipToAddress: address_options,
+        PaymentDetailsItem: items,
+        ShippingMethod: "Shipping Method Name Goes Here",
```
Comment (dacook) [inline app/services/paypal/payment_details_service.rb]: I see in the next commit that this was pre-existing, but I wonder if we need to put something more meaningful here?

File: app/services/paypal/payment_details_service.rb [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+      {
+        Name: order.bill_address.try(:full_name),
+        Street1: order.bill_address.address1,
+        Street2: order.bill_address.address2,
+        CityName: order.bill_address.city,
+        Phone: order.bill_address.phone,
+        StateOrProvince: order.bill_address.state_text,
+        Country: order.bill_address.country.iso,
+        PostalCode: order.bill_address.zipcode
+      }
```
Comment (dacook) [inline app/services/paypal/payment_details_service.rb:88]: I'm not sure if it's ever nil in practice, but bill_address is technically optional, so we might need to protect from that here.
```
belongs_to :bill_address, class_name: 'Spree::Address', optional: true
```

File: spec/controllers/payment_gateways/paypal_controller_spec.rb [hunk 5]
```diff
@@ -87,28 +87,56 @@
...
+    end
+
+    describe "request details" do
+      it "creates a paypal express checkout data including payment details" do
+        data = {
+          SetExpressCheckoutRequestDetails: {
+            InvoiceID: order.number,
+            BuyerEmail: order.email,
+            ReturnURL: String,
+            CancelURL: String,
```
Comment (dacook) [inline spec/controllers/payment_gateways/paypal_controller_spec.rb:197]: TIL you can match based on type, that's nice!

File: spec/controllers/payment_gateways/paypal_controller_spec.rb [hunk 6]
```diff
@@ -57,27 +81,71 @@
...
+        before do
+          expect(current_order).to receive(:process_payments!).and_raise(Spree::Core::GatewayError)
+        end
+
+        it "redirects to checkout details step" do
+          expect(post(:confirm, params: { payment_method_id: payment_method.id })).
+            to redirect_to checkout_step_path(step: :details)
+
+          expect(flash[:error]).to eq(
+            "There was a problem with your payment information: Spree::Core::GatewayError"
```
Comment (dacook) [inline spec/controllers/payment_gateways/paypal_controller_spec.rb]: Hmm I know this is an existing message, but I wonder if we can provide more specifics or guidance to the user here. It doesn't seem to be very helpful.

File: app/services/paypal/payment_details_service.rb [hunk 7]
```diff
@@ -13,7 +13,9 @@ def call # rubocop:disable Metrics/MethodLength
       item_sum = items.sum { |i| i[:Quantity] * i[:Amount][:value] }
       tax_adjustments_total = order.all_adjustments.tax.additional.sum(:amount)
 
-      last_payment = payment_finder.last_pending_payment
+      last_payment = payment_finder.last_pending_paypal_payment
+      return {} if last_payment.nil?
```
Comment (dacook) [inline app/services/paypal/payment_details_service.rb:17]: 👇 
> Paypal does not support no items or a zero dollar ItemTotal

Will that be a problem here?

**Review by dacook — APPROVED** [review]
Great, thanks for working through this.
A few notes/questions, but I think all fine

File: app/services/paypal/payment_details_service.rb (hunk 3 above)
Comment (rioug) [reply app/services/paypal/payment_details_service.rb]: It made me laugh, I guess we could just put "Shipping Method".

File: app/services/paypal/payment_details_service.rb (hunk 7 above)
Comment (rioug) [reply app/services/paypal/payment_details_service.rb:17]: I think the paypal call will fail as the "PaymentDetails" will be missing. It's unlikely that we get there with no paypal payment so I think that's acceptable. We have improved logging so we should be alerted if such scenario occurs.

File: spec/controllers/payment_gateways/paypal_controller_spec.rb (hunk 6 above)
Comment (rioug) [reply spec/controllers/payment_gateways/paypal_controller_spec.rb]: It would provide more information in a real scenario, the spec doesn't provide any message to the exception that's why we get "Spree::Core::GatewayError". I'll update the spec.

File: app/services/orders/find_payment_service.rb (hunk 1 above)
Comment (rioug) [reply app/services/orders/find_payment_service.rb:23]: > I'm guessing the pending_payments are already loaded, which is why we're looping instead of using a db query?

Correct 

We are looking for the last one by `created_at` , so to use `rfind` we would need to order the the array first. Anyway, we generally only have a couple of pending payment so I don't think the current solution is an issue.

Comment (dacook) [reply app/services/orders/find_payment_service.rb:23]: Oh ok, sorry I didn't look at the definition for `last`. 👍

**Review by dacook — APPROVED** [review]
👍

**Comment by AMEA-LYON** [comment]
Tested successfully ! Congratulations 🥳 

=> 🚀 Ready to go !

**Comment by sigmundpetersen** [comment]
@rioug there are conflicts
