### PR TITLE
authorize enterprise users to access invoices page

### LINKED ISSUE #11048: [Invoices] Invoice page not accessible for enterprise users (authorization failure)
## Description

If an enterprise user want to access the invoice page there is an authorization failure. Only super admins can visit the page currently.

## Expected Behavior

Enterprise users and super admins should be able to visit the invoices page.

## Actual Behaviour

Only super admins can visit the invoices page.

## Steps to Reproduce

1. Log in as an enterprise user.
2. Go to /orders.
3. Click the edit button of an order.
4. Click 'Invoices' in the menu on the right.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #11048

#### What should we test?

- described on: #11048
- relevant tests, try to access the invoices page for an order as: 
1. admin
2. enterprise user (the owner of the distributor of the order)
3. enterprise user (not the owner of distributor of the order) 
4. normal user

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/controllers/spree/admin/orders/invoices_spec.rb [hunk 1]
```diff
@@ -103,4 +103,43 @@
       end
     end
   end
+
+  describe "#index" do
+    let!(:user) { create(:user) }
+    let!(:enterprise_user) { create(:user) }
```
Comment (mkllnk) [inline spec/controllers/spree/admin/orders/invoices_spec.rb:109]: There's no difference between the two users. There are two identical test cases for each user. I think that you need to give the enterprise user an enterprise.

**Review by mkllnk — CHANGES_REQUESTED** [review]

**Review by mkllnk — APPROVED** [review]
Trying to address my own comments I found that the PR enabled every enterprise user to view all invoices. :scream_cat: I think that I fixed it now. It's not easy to understand the permissions but very important.

**Review by rioug — APPROVED** [review]
Looks good :+1: +1

**Comment by rioug** [comment]
@abdellani could you review maikel's changes as well ?

**Comment by abdellani** [comment]
I think we still need to update the permissions section. 

If a user (except administrators) tries to generate an invoice, he'll not be authorized.

I fixed that part and ask for a second review.

File: app/models/spree/ability.rb [hunk 2]
```diff
@@ -29,6 +29,7 @@ def initialize(user)
         can :update, Order do |order, token|
           order.user == user || order.token && token == order.token
         end
+        can [:index, :generate, :create], :invoice
```
[the remark this answers is not in the document]
Comment (dacook) [reply app/models/spree/ability.rb:32]: Oh! We've mixed up CanCan _actions_ and _subjects_. I had to read up on this: https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

In the controller, we check if we can perform action `:invoice` on subject `Order`. But there's no rule for `can :invoice, Order`. Either, we should be checking if we can 
* `:index`, `:generate` or `:create` an `Invoice` (which is hard because these are bulk actions and the invoice doesn't exist yet). OR
* `invoice` an `Order` and update the rules here.

And finally, I think we need to re-think how these rules are applied. This part of of the file is a list of generic rules for all customers and admins; the admin-only section is down below.

**Review by dacook — COMMENTED** [review]
Maikel's fixed some issues, but from what I can see it's still not quite right. Unless I'm misunderstanding, we need update specs further (they must be wrong if they are passing) and update the rules again.

I've run out of time today to pick this up but will start by confirming the requirements on the issue.
If this makes sense to you Mohamed, would you be willing to proceed?

File: app/models/spree/ability.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (abdellani) [reply app/models/spree/ability.rb:32]: Hi @dacook 

> In the controller, we check if we can perform action :invoice on subject Order. But there's no rule for can :invoice, Order. 

I think we're already doing that on `add_order_management_abilities`
https://github.com/openfoodfoundation/openfoodnetwork/blob/de34b9b1098a0872f077abdba2995685b8aa1f94/app/models/spree/ability.rb#L266-L274

but after reading your comment and checking the code again, I think that I updated the permissions from the wrong place.  I'll update the permissions `:index, :generate, :create` from `add_order_management_abilities` (instead of the initialize)


Now, when the user tries to generate an invoice, the `authorize!` will be called (at least) three times:

2 times from  `‎Spree::Admin::BaseController`:
1. to check if the user has `admin` permission on `:invoice`
2. to check if the user has `generate` permission on `:invoice`
https://github.com/openfoodfoundation/openfoodnetwork/blob/de34b9b1098a0872f077abdba2995685b8aa1f94/app/controllers/spree/admin/base_controller.rb#L45-L57

3. the last call (from the action method) is to check if the user has `invoice` permission on the `order`.

I don't know if we can make things simpler.

File: app/models/spree/ability.rb [hunk 3]
```diff
@@ -29,6 +29,7 @@ def initialize(user)
         can :update, Order do |order, token|
           order.user == user || order.token && token == order.token
         end
+        can [:index], :invoice
```
Comment (dacook) [inline app/models/spree/ability.rb:32]: The only invoices controller is `Spree::Admin::InvoicesController`, and I think this rule applies for all users, which doesn't seem right to me. Should it also be moved to `add_order_management_abilities`?

**Review by dacook — COMMENTED** [review]
Thanks for explaining this Mohamed. So if I'm getting this right:

* The `:invoice` _Subject_ refers to the controller `Spree::Admin::InvoicesController` (thanks to the code snippet in the base controller you showed me). 

I can see the actions listed here match the actions in the controller . 👍 
I guess we have invoice rules based on controller instead of objects, because the objects aren't always available (there's lots of processing done to find/generate them). 
But we still need to validate access according to the enterprise you manage, so:

* The `:invoice` _Action_ refers to the `Order`

And we already had a rule for this in `add_order_management_abilities`. 👍 

Ok I think I finally understand, thanks for your patience! I just have one final question.

File: app/models/spree/ability.rb (hunk 3 above)
Comment (abdellani) [reply app/models/spree/ability.rb]: This will not change anything on the final result, because we're checking the permission on the action's method level.
but you're right, it'll make more sense to grant this permission from `add_order_management_abilities`.

**Review by rioug — COMMENTED** [review]
Looks good , I got to refresh my knowledge on `cancancan` :)

**Review by rioug — APPROVED** [review]

**Review by dacook — APPROVED** [review]
Great, thank you!

**Comment by filipefurtad0** [comment]
Hey @abdellani,

Looking good now:

Tried the test cases you've proposed:

- admin -> sees the invoices page -> :heavy_check_mark: (working, before this PR)
- enterprise user (the owner of the distributor of the order) -> sees the invoices page -> :heavy_check_mark: (broken, before this PR)
- enterprise user (not the owner of distributor of the order) -> **Unauthorized** -> :heavy_check_mark: 
- normal user (customer) -> **Unauthorized** -> :heavy_check_mark: 

image

Merging!
