### PR TITLE
SplitCheckout: handle navigation between steps

### LINKED ISSUE #8889: [Split checkout] Incorrect redirect from /details to /summary (/payment expected)
## Description

After visiting /summary, and navigating back to /details, clicking "Next - Payment method" should redirect to /payment - but it redirects to /summary.

## Expected Behavior

After visiting /summary, and navigating back to /details, clicking "Next - Payment method" should redirect to /payment should redirect to /details.

## Actual Behaviour

After visiting /summary, and navigating back to /details, clicking "Next - Payment method" should redirect to /payment redirects to /summary.

## Steps to Reproduce

1. When checking out, go all the way to /summary
2. Click "Back to Payment"
3. Click "Back to Details"
4. Click "Next - Payment method" -> notice the redirect to /summary

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
Handle two types of redirection: one is based on the order step itself, the other is based on the current step passed through the params

Closes #8889

#### What should we test?
We should test navigation between steps for different order.state (ie. is the order in details, payment or summary/confirmation state):
 - the tab should redirect to the previous concerned step
 - the _next/submit_ button at the bottom should redirect to the next step
 - the _cancel/previous_ button at the bottom should redirect to the previous step
 - when not specifying any step (ie. going on `/checkout`), should redirect to the order.state

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

File: app/controllers/split_checkout_controller.rb [hunk 1]
```diff
@@ -128,4 +128,14 @@ def redirect_to_step
       redirect_to order_path(@order)
     end
   end
+
+  def redirect_to_step
```
Comment (mkllnk) [inline app/controllers/split_checkout_controller.rb:132]: The class is growing to big. This method is good in the controller though. Shall we pull some of the checkout logic out into a service?

**Review by mkllnk — COMMENTED** [review]
Nice!

**Comment by mkllnk** [comment]
Just picking up the Slack conversation here:

> I was wondering how we can improve the readability of this class (app/controllers/split_checkout_controller.rb ). I thought about creating a Service, a Concern or a Helper. I thought specifically about those 3 methods: validate_details , validate_payment and validate_summary . But they seems to be strongly related to the controller (as they put some error messages in the @orderobject).
> The question is then: which part of the code could be a good candidate to decrease the number of lines of this controller and then increase the readability (I assume ... :p)

Those methods check the params (input to the controller) and add errors (output of the controller) and therefore they are really not great examples to separate. I mean, if the controller is too big just because of this kind of logic, it's still valid to separate it but let's look at other examples first. Maybe some business logic.

https://github.com/openfoodfoundation/openfoodnetwork/blob/4a617a76e45e370f9589a37055a4a5d1a7938635/app/controllers/split_checkout_controller.rb#L27-L28

Maybe those to can be added to the `OrderWorkflow` service?

https://github.com/openfoodfoundation/openfoodnetwork/blob/4a617a76e45e370f9589a37055a4a5d1a7938635/app/controllers/split_checkout_controller.rb#L23-L25

I'm wondering if those three calls can be combined in one. The `return if performed?` is adding complexity here. It's confusing that `update_order`, apparently, can be successful and performed or success and still needs work. What?

But maybe the real problem here is that we still have *one* controller that combines update and confirm. Now that we have several steps in the checkout, should we have several controllers? Updating the cart and actually checking out (completing the order) are very different things.

We want to avoid some scope creep in this PR as well. So if the best solution doesn't fit in here, we can do that in a separate PR. But maybe update to rubocop_todo and open a tech-debt issue for that.

**Comment by jibees** [comment]
@mkllnk 

> Those methods check the params (input to the controller) and add errors (output of the controller) and therefore they are really not great examples to separate

Yeap, agree, that's what I've found.

> So if the best solution doesn't fit in here, we can do that in a separate PR.

I've open a Tech-debt issue to handle this particular point: https://github.com/openfoodfoundation/openfoodnetwork/issues/8942

File: app/controllers/split_checkout_controller.rb (hunk 1 above)
Comment (jibees) [reply app/controllers/split_checkout_controller.rb:132]: Tech-debt issue opened: https://github.com/openfoodfoundation/openfoodnetwork/issues/8942

**Review by mkllnk — APPROVED** [review]
Great, I made sure that rubocop doesn't complain.

**Comment by filipefurtad0** [comment]
Using back/next buttons on the bottom of the screen:
details -> payment -> summary -> :+1: 
summary -> payment -> details -> payment -> summary:+1: 

Clicking the tabs on top of the screen:
summary -> details -> payment -> cart :+1:

From cart, Clicking Checkout:
-> getting summary, expecting details


Long video demonstrating this:
Peek 2022-03-10 15-57

Major improvement!
I'll merge and close the underlying issue, but open a similar one (and I guess with less priority) concerning the `cart -> details` transition :+1:
