### PR TITLE
Fix Rubocop Locale Errors

### LINKED ISSUE #12332: Rubocop Rails/I18nLocaleAssignment and Rails/I18nLocaleTexts
Part of https://github.com/openfoodfoundation/openfoodnetwork/issues/11482

- [ ] [Rails/I18nLocaleAssignment](https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/I18nLocaleAssignment)
- [ ] [Rails/I18nLocaleTexts](https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/I18nLocaleTexts)

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Part of #11482
- Closes #12332
- This PR fixes the following Rubocop errors:
  - [Rails/I18nLocaleAssignment](https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/I18nLocaleAssignment)
  - [Rails/I18nLocaleTexts](https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/I18nLocaleTexts)
- It'd help to review the PR commit by commit. Thanks

#### What should we test?
- Build should be green

#### Release notes

Changelog Category:

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: spec/models/spree/variant_spec.rb [hunk 1]
```diff
@@ -60,14 +60,12 @@
...
-    end
-
-    after do
-      I18n.locale = I18n.default_locale
+      default_locale = I18n.default_locale
+      I18n.with_locale(default_locale) do
+        I18n.backend.store_translations(:de,
+                                        { number: { currency: { format: { delimiter: '.',
+                                                                          separator: ',' } } } })
+      end
```
Comment (rioug) [inline spec/models/spree/variant_spec.rb:68]: I think this would be better as an `around` , otherwise the examples below won't run with `default_locale` applied.  
```suggestion
  around(:each) do |spec|
     I18n.with_locale(default_local) do
       I18n.backend.store_translations(:de,
                                        { number: { currency: { format: { delimiter: '.',
                                                                          separator: ',' } } } })
        spec.run
      end
  do
```

**Review by rioug — CHANGES_REQUESTED** [review]
Thanks for your help @chahmedejaz ! Looks good, but I think you changed the behaviour of a spec slightly, see my comment.

File: spec/models/spree/variant_spec.rb (hunk 1 above)
Comment (chahmedejaz) [reply spec/models/spree/variant_spec.rb:68]: Oh...My bad! 😅
Thanks for pointing that out ⭐

**Comment by chahmedejaz** [comment]
Hi @rioug - I've incorporated your suggestion [here](https://github.com/openfoodfoundation/openfoodnetwork/commit/9a80792c0c0f7ab4613b7f6a674fb5c733bcbe2b). Thanks.

**Review by mkllnk — APPROVED** [review]
Great work!

I added another commit to further simplify the code. With a general reset in the spec helper, we can keep the specs cleaner and avoid leakage without needing to reset it in individual specs.

I also found some unused code.
