### PR TITLE
[BUU] Fixes Products Page ActionView::Template::Error

### LINKED ISSUE #12705: [BUU] ActionView::Template::Error in admin/products_v3#index
## Error in OpenFoodNetwork Aus

**ActionView::Template::Error** in **admin/products_v3#index**
undefined method `/' for nil:NilClass

      scaled_unit_value = variant.unit_value / (variant.product.variant_unit_scale || 1)
                                             ^

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/669f38efa03983296406328b?event_id=66a07ff900efd698a1b20000&i=gh&m=ci)

## Stacktrace

    app/helpers/admin/products_helper.rb:21 - unit_value_with_description
    app/views/admin/products_v3/_variant_row.html.haml:20 - _app_views_admin_products_v___variant_row_html_haml__1827959112950086768_9292720
    app/views/admin/products_v3/_product_variant_row.html.haml:12 - block (3 levels) in _app_views_admin_products_v___product_variant_row_html_haml___4491341818290561796_9292540
    app/views/admin/products_v3/_product_variant_row.html.haml:10 - block (2 levels) in _app_views_admin_products_v___product_variant_row_html_haml___4491341818290561796_9292540
    app/views/admin/products_v3/_product_variant_row.html.haml:9 - each_with_index
    app/views/admin/products_v3/_product_variant_row.html.haml:9 - block in _app_views_admin_products_v___product_variant_row_html_haml___4491341818290561796_9292540
    app/views/admin/products_v3/_product_variant_row.html.haml:1 - _app_views_admin_products_v___product_variant_row_html_haml___4491341818290561796_9292540
    app/views/admin/products_v3/_table.html.haml:66 - block (2 levels) in _app_views_admin_products_v___table_html_haml___4011096604980307158_9291660
    app/views/admin/products_v3/_table.html.haml:65 - each_with_index
    app/views/admin/products_v3/_table.html.haml:65 - block in _app_views_admin_products_v___table_html_haml___4011096604980307158_9291660
    app/views/admin/products_v3/_table.html.haml:1 - _app_views_admin_products_v___table_html_haml___4011096604980307158_9291660
    app/views/admin/products_v3/_content.html.haml:18 - _app_views_admin_products_v___content_html_haml__4235413950232638027_9291280
    app/views/admin/products_v3/index.html.haml:15 - _app_views_admin_products_v__index_html_haml__3030162839370015489_9291040
    app/controllers/admin/products_v3_controller.rb:13 - index

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/669f38efa03983296406328b?event_id=66a07ff900efd698a1b20000&i=gh&m=ci)

*Created by Admin OFF via Bugsnag*

This helper assumes `variant.unit_value` is not nil, but there is nothing enforcing this rule if the `variant_unit` is items. The BUU product screen will populate `unit_value` with 1, so it shouldn't be an issue for new product, but it breaks for older product.
https://github.com/openfoodfoundation/openfoodnetwork/blob/dfea0cd805c555b84dce163f9ed83842a5b5b992/app/helpers/admin/products_helper.rb#L20-L28

## Workaround
Disable "admin_style_v3"  for the affected user 

## Technical workaround
Update variant where `unit_value: nil` and set it to 1 for the affected user.

## Severity#

bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12705

- This PR fixes this Error by using the previously implemented logic as per https://github.com/openfoodfoundation/openfoodnetwork/blame/6d6f8735e3eff94f53a142538e158116331175cd/app/views/admin/products_v3/_variant_row.html.haml#L22

#### What should we test?

- Visit the Products page, and make sure that some product variants have `nil` as their `unit_value`. i.e. very old products, created at the time when we didn't have validation for `unit_value`
- You should be able to view the page without any errors.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Looks good :+1: 
However I am wondering if we should show a blank value when `unit_value` and `unit_description` are nil ? @openfoodfoundation/core-devs ?

**Comment by dacook** [comment]
That sounds logical to me, I forget if there's a reason we didn't before. 
I guess with this current method, any time you save the record, it will get updated to `1` without the user necessarily noticing. Essentially it defaults to 1, which might not be correct for that product.

So if we let it be blank instead, then when you save you should get an error message. Then the user can choose the appropriate number.  I think that would be better, if the interface can support it. @chahmedejaz would you be able to test it out and see what works best?

**Comment by chahmedejaz** [comment]
> That sounds logical to me, I forget if there's a reason we didn't before. I guess with this current method, any time you save the record, it will get updated to `1` without the user necessarily noticing. Essentially it defaults to 1, which might not be correct for that product.
> 
> So if we let it be blank instead, then when you save you should get an error message. Then the user can choose the appropriate number. I think that would be better, if the interface can support it.  would you be able to test it out and see what works best?

Sure, David. Let me do a spike on it and get back to you. Thanks

**Comment by dacook** [comment]
Hi @chahmedejaz , sorry I didn't have an answer before. 

I think it's helpful to remember this is a rare case and considered corrupt data. The error above ☝️ means the whole page fails to load which is very disruptive. But if _cloning_ a corrupt product fails, I think that's much less disruptive and easy to work around, so we don't need to worry about solving it now. (the user can just manually create a new product with the same details)

**Comment by chahmedejaz** [comment]
> Hi @chahmedejaz , sorry I didn't have an answer before.
> 
> I think it's helpful to remember this is a rare case and considered corrupt data. The error above ☝️ means the whole page fails to load which is very disruptive. But if _cloning_ a corrupt product fails, I think that's much less disruptive and easy to work around, so we don't need to worry about solving it now. (the user can just manually create a new product with the same details)

Thanks @dacook 👍

File: app/helpers/admin/products_helper.rb [hunk 1]
```diff
@@ -11,19 +11,20 @@ def product_image_form_path(product)
     end
 
     def prepare_new_variant(product)
-      product.variants.build do |variant|
-        variant.unit_value = 1.0 * (product.variant_unit_scale || 1)
```
Comment (chahmedejaz) [inline app/helpers/admin/products_helper.rb:15]: Mimicking old UI behavior, when creating a new variant, then both of these are empty

File: app/views/admin/products_v3/_variant_row.html.haml [hunk 2]
```diff
@@ -18,7 +18,7 @@
       = f.hidden_field :unit_value
       = f.hidden_field :unit_description
       = f.text_field :unit_value_with_description,
-          value: unit_value_with_description(variant), 'aria-label': t('admin.products_page.columns.unit_value'), required: true
+          value: unit_value_with_description(variant), 'aria-label': t('admin.products_page.columns.unit_value')
```
Comment (chahmedejaz) [inline app/views/admin/products_v3/_variant_row.html.haml:21]: Having `required` here is causing an error upon saving in the following scenario:
- **New varaint** button is clicked to create a new variant
- As per Old UI behavior, unit_value is empty for this product.
- However, in the new UI, if this variant is changed then the saving form doesn't work because this field is hidden on the UI until its pop-up is opened
- JS tries to find it to show the required validation error but gets broken because it's not able to find it on the UI
- Hence neither the required error gets displayed nor the form gets submitted.
- This PR removes the required validation which won't cause the failure of the above use-case however, the backend is [handling this blank field error](https://github.com/openfoodfoundation/openfoodnetwork/pull/12710/files#diff-d8fe63147fa63b4c9fb35f7c510dd1c1990c61855be8420f1ce7ebf78967e2ddR517), so it will return the erorr "_can't be blank"_ which will be displayed below it.

File: spec/system/admin/products_v3/update_spec.rb [hunk 3]
```diff
@@ -58,9 +58,6 @@
       end
 
       # Unit popout
-      fill_in "Unit value", with: ""
```
Comment (chahmedejaz) [inline spec/system/admin/products_v3/update_spec.rb:61]: As we don't have required validation as per [this](https://github.com/openfoodfoundation/openfoodnetwork/pull/12710/files#r1703198190), so we can remove its expectation

**Comment by chahmedejaz** [comment]
@dacook @rioug - I've addressed your comments above, please review.
Here are the changes:
https://github.com/openfoodfoundation/openfoodnetwork/pull/12710/commits/1014a50aff403cc83347bd12aa9b0ee7bda73590
https://github.com/openfoodfoundation/openfoodnetwork/pull/12710/commits/d4e0b2ab51d36bd71b5dce4800221efecb679468

Thanks

File: app/views/admin/products_v3/_variant_row.html.haml (hunk 2 above)
Comment (rioug) [reply app/views/admin/products_v3/_variant_row.html.haml:21]: > JS tries to find it to show the required validation error but gets broken because it's not able to find it on the UI

This validation is handled by the browser, probably in Javascript. I think that's a fair trade off, I am wondering if we could show the pop up with error on form submit so we can still benefit from the browser validation but it's probably not worth the effort.

File: app/helpers/admin/products_helper.rb [hunk 4]
```diff
@@ -11,19 +11,20 @@ def product_image_form_path(product)
     end
 
     def prepare_new_variant(product)
```
Comment (rioug) [inline app/helpers/admin/products_helper.rb:13]: We could remove the helper has it's not doing much now, but that's fine as it is.

**Review by rioug — APPROVED** [review]
Looks good :+1: Thanks @chahmedejaz

File: app/views/admin/products_v3/_variant_row.html.haml (hunk 2 above)
Comment (rioug) [reply app/views/admin/products_v3/_variant_row.html.haml:21]: FYI: I ran into the same issue while working on the Product Refactor and I managed to implement the solution I was talking about above. It ended up pretty simple in the end.

Comment (chahmedejaz) [reply app/views/admin/products_v3/_variant_row.html.haml:21]: Thanks for implementing this one. ♥️ 
I tried to implement the above, maybe I was looking at it from a different POV and was facing issues. Looking forward to your solution to this in the refactor 😄

Comment (dacook) [reply app/views/admin/products_v3/_variant_row.html.haml:21]: The `required` JS validation was added after discussing with Mario. It ensures that the popout can't be closed if it's empty, which helps avoid the problem being hidden.
But as you've found, we have a problem if the field is empty and the popout never gets opened.

This change seems like the most practical best solution 👍  
I'm not sure if the red border will show on the popout, until you open it. But if there error text is there, I think that's ok.

**Review by dacook — APPROVED** [review]

File: spec/system/admin/products_v3/update_spec.rb (hunk 3 above)
Comment (dacook) [reply spec/system/admin/products_v3/update_spec.rb:61]: Can the case of blank unit value now be added here?

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/system/admin/products_v3/update_spec.rb#L251

**Review by dacook — CHANGES_REQUESTED** [review]
Actually sorry I just remembered that we are losing test coverage here. I think the removed test can still be covered in a different way:

**Comment by chahmedejaz** [comment]
>Can the case of blank unit value now be added here?

> https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/system/admin/products_v3/update_spec.rb#L251

Sure, David. 
Sorry, I thought the blank error functionality is already tested in the above spec and the removed spec was just validating that if the pop-up remains open if the field is blank 😅 
No worries, I'll it now 😄

**Comment by dacook** [comment]
> Sure, David. Sorry, I thought the blank error functionality is already tested in the above spec and the removed spec was just validating that if the pop-up remains open if the field is blank 😅 No worries, I'll it now 😄

I think it is covered for `"adding variants"`, but it would be worth covering for `"updating"`>`"with invalid data"` also. That is, at `"shows errors for both product and variant fields"`. I hope that makes sense.

**Comment by chahmedejaz** [comment]
> > Sure, David. Sorry, I thought the blank error functionality is already tested in the above spec and the removed spec was just validating that if the pop-up remains open if the field is blank 😅 No worries, I'll it now 😄
> 
> I think it is covered for `"adding variants"`, but it would be worth covering for `"updating"`>`"with invalid data"` also. That is, at `"shows errors for both product and variant fields"`. I hope that makes sense.

Sure, David 👍🏻

**Comment by chahmedejaz** [comment]
> Can the case of blank unit value now be added here?
> https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/system/admin/products_v3/update_spec.rb#L251

Hi @dacook - It's fixed here: https://github.com/openfoodfoundation/openfoodnetwork/pull/12710/commits/647a384561138ce831ead2ac9ce62165d091322b. Thanks.

**Review by dacook — APPROVED** [review]
Great, thank you!

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz ,

I've edited the DB to trigger the error, and could observer the error 500 when rendering the /products page.

After staging the PR, I can confirm the page renders, and that `unit_value` remains empty:

image

image

image

We should keep in mind that this PR only affects the products page and that the shopfront breaks in this case:

image

But at least the user has the possibility to access the products page and fix it - provided they can find the variant which is responsible.

I believe this is the intended scenario - the `/products` page does not break - I'd say this is looking good. Merging! Thanks.
