### PR TITLE
Stabilise flaky enterprise fee spec

### LINKED ISSUE #11461: [Flaky] ./spec/system/admin/enterprise_fees_spec.rb
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to manage enterprise fees
 editing an enterprise fee editing two enterprise fees handles updating two enterprise fees
     Failure/Error: expect(page).to have_selector "input[value='World!']"
       expected to find css "input[value='World!']" but there were no matches
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_enterprise_fees_editing_an_enterprise_fee_editing_two_enterprise_fees_handles_updating_two_enterprise_fees_696.png

     
     # ./spec/system/admin/enterprise_fees_spec.rb:191:in `block (4 levels) in <top (required)>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'


Finished in 4 minutes 42.8 seconds
70 examples, 1 failure

Failed examples:

rspec ./spec/system/admin/enterprise_fees_spec.rb:181 # 
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5947037243/job/16128512211?pr=11427

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #11461

The spec was creating a second fee while the page was loading data via Javascript. This created a race condition and sometimes the second fee was missing from the page and the editing failed.

#### What should we test?

- Specs only.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/enterprise_fees_spec.rb [hunk 1]
```diff
@@ -161,6 +161,7 @@
       let!(:fee1) { create(:enterprise_fee, fee_type: "sales", enterprise_id: enterprise.id) }
 
       before do
+        visit admin_enterprise_fees_path
```
Comment (mkllnk) [inline spec/system/admin/enterprise_fees_spec.rb]: Loading the page after `fee1` has been created ensures that it's present on the page.

File: spec/system/admin/enterprise_fees_spec.rb [hunk 2]
```diff
@@ -167,42 +167,51 @@
...
-      fill_in "#{prefix}_name", with: 'Hello!'
-      select 'Inherit From Product', from: "#{prefix}_tax_category_id"
-      select 'Flat Percent', from: "#{prefix}_calculator_type"
+      within fee_row(fee.name) do
+        select 'Foo' # enterprise
+        select 'Fundraising' # fee type
+        find("input[id$='_name']").fill_in with: "Hello!"
+        select 'Inherit From Product' # tax category
+        select 'Flat Percent' # calculator type
+      end
```
Comment (mkllnk) [inline spec/system/admin/enterprise_fees_spec.rb:176]: I'm not 100% confident about this approach. I think it's better than the hard-coded `prefix` and `prefix1` but it would be good to have a better way to identify the select fields. We could add another helper to find the table header label and use the column index to find the right table cell. That would make the comments obsolete.

I didn't want to spend too much time on this though. I hope this version to be helpful as example though.

**Review by dacook — APPROVED** [review]
Nice one. In the first commit I started trying to see if it would be possible to avoid the extra page load.. then I was glad to see you already did :)

File: spec/system/admin/enterprise_fees_spec.rb (hunk 2 above)
Comment (dacook) [reply spec/system/admin/enterprise_fees_spec.rb]: Great minds think alike, I was working on this same type of issue this week.

I started the system spec from the user's point of view and asked myself "how are these fields labelled?". The answer is by the column header; but to ensure the semantic meaning is applied I made use of aria-label (I chose this over `aria-labelled-by` [because it was more practical](https://github.com/openfoodfoundation/openfoodnetwork/commit/ae3cd6f7e046bb1eac5d8e8800bee3dba1f0f7f6)).

Then I was able to create a simple helper based on that: https://github.com/dacook/openfoodnetwork/commit/aff33b79ae24b5bd7d564ea48e64455804eb14bd

Comment (mkllnk) [reply spec/system/admin/enterprise_fees_spec.rb]: That's awesome! I like the labeling. It should improve the UX for some people as well. I won't add it to this PR it's good to keep this pattern in mind for next time.

**Review by mkllnk — COMMENTED** [review]
I think that one review is enough to get this merged and reduce flakiness of the build.

@filipefurtad0 you may also be interested to look at this.
