### PR TITLE
Hopefully fix flaky OC spec

### LINKED ISSUE #11037: [Flaky] rspec ./spec/system/admin/order_cycles/simple_spec.rb:572
### What we should change and why (this is tech debt)

Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/9894

```
  1) 
    As an administrator
    I want to manage simple order cycles
 simplified interface for enterprise users selling only their own produce creates order cycles
     Failure/Error: click_button 'Add coordinator fee'
     
     Capybara::Cuprite::MouseEventFailed:
       Firing a click at coordinates [101.1875, 758.28125] failed. Cuprite detected another element with CSS selector "html.webkit.chrome.chrome114.linux.js.orientation_landscape.maxw_1280 body.admin.stimulus-reflex-disconnected div#wrapper div#content div.row div.container div.sixteen.columns form#new_order_cycle.ng.order_cycle.ng-scope.ng-valid-maxlength.ng-valid-max-tags.ng-valid-min-tags.ng-valid-leftover-text.ng-dirty.ng-valid-parse.ng-valid.ng-valid-required save-bar.ng-isolate-scope div#save-bar.animate-show div.container div.seven.columns.alpha" at this position. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger("click").
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_manage_simple_order_cycles_simplified_interface_for_enterprise_users_selling_only_their_own_produce_creates_order_cycles_921.png

```
### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5286207807/jobs/9565418679?pr=11035

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Maybe closes #11037 

I couldn't reproduce this reliably but I found the loading of AngularJS components a bit slow sometimes. So this is just a guess.

#### What should we test?

- Specs only

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by mkllnk** [comment]
4/4 CI runs passed.

**Review by rioug — APPROVED** [review]
Looks good !

**Comment by mkllnk** [comment]
100/100 CI runs passed when spec was run on its own.

File: spec/system/admin/order_cycles/simple_spec.rb [hunk 1]
```diff
@@ -488,6 +488,7 @@
           expect(page).to have_content v1.product.name
 
           expect(page).not_to have_content "No variant available for this product"
+          expect(page).to have_content "(Some variants might be hidden via inventory settings)"
```
Comment (dacook) [inline spec/system/admin/order_cycles/simple_spec.rb:491]: Good eyes!🕵️

**Review by dacook — APPROVED** [review]
