### PR TITLE
Decouple payments

### LINKED ISSUE #7510: Order states inconsistency between subscription- and backoffice-placed orders
## Description

Placing a orders with cards requiring 3D-auth from a) placing a subscription and b) backoffice order will lead to different order states.

It does not look right that orders should differ in state, when the exact same amount, items and payment methods are used; both are awaiting authentication from the shopper. See pic below.

## Expected Behavior

Order states should be consistent, regardless of the "path" taken to reach the point where authentication is required.

## Actual Behaviour

Order states differ, depending on the order "path": backoffice orders are in a "payment" state, whereas subscription orders are in a "complete" state.

## Steps to Reproduce

1. Place two identical orders: one via subscription and another through the backoffice; 
2. Check the order states on `/orders`

## Severity

?

## Your Environment

* Version used: v3.6.9
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

### LINKED ISSUE #7665: Error 422 (user facing) if stock is reduced before providing authorization
## Description

Follow-up from PR #7649.

After an order is created in the backoffice and a Stripe-SCA payment is added, an email is sent to the customer to provide payment authorization. If stock is reduced during this time, when the customer provides authentication:

- an error 422 will be displayed (customer)
- no changes on the payment (admin; this can easily be seen as "the customer still has not provided auth.)
- the payment is successful and captured (Stripe Dashboard)

## Expected Behavior

Proposal:
Stock limitations should restrict payment creation (as imposed by #7649), but not payment capture: stock should be "reserved" for the order once a Stripe-SCA payment is created - I believe this is the case with confirmed subscription orders, which await payment authorization.

Also related: We could consider to order state should be "complete" ([as subs orders are](https://camo.githubusercontent.com/547899ad6f1f9dab41ebae752f5ae9236824a1fd7e03ab54e77399857c6a8c4c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564373631623034396464653635303030316561663332662f39316433613362342d663962362d343866352d626131312d653731623461366335613933)) while a new payment is awaiting authorization. A new payment state may be necessary to introduce here:

See discussion on this issue and comment https://github.com/openfoodfoundation/openfoodnetwork/issues/7510#issuecomment-841873665.

Ping @Matt-Yorkley @lin-d-hop @jaycmb @RachL 

## Actual Behaviour

If stock limitations occur within the time window from the moment the admin creates the payment till the time the customer provides authentication, the payment will be captured (on stripe), but an error is displayed to the customer; the order is left "not paid".

## Steps to Reproduce

As an admin:
1. Create a backoffice order with some items in the cart
2. Add a Stripe SCA payment method, card x-3184.
3. Reduce the stock for that item to zero.

As a customer:
4. Use the link received per email to authorize the payment -> see the cat.

## Animated Gif/Screenshot

image

## Workaround

None.

## Severity

The time between payment creation and customer authorization can be long... which leaves plenty of time to stock reduction (I'm thinking what happens if an OC closes in the meantime?)
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v3.7.1
* Browser name and version: Firefox 88
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

Related to #5784.

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #7665 
Closes #7510 

This is still a first attempt, but I think it's ready for review. 

There's been quite a few bugs whose root cause is that we authorize/take payment before making sure that we can move the order to the `complete` state. 

This PR removes the callback in the Order state machine that was calling `process_payments` as part of the transition to `complete`. Instead, it moves that decision/responsibility (when and if to process payments) to the caller. 

#### What should we test?

We'll want to do a pretty thorough test of checkout, admin payments, and subscription payments to make sure the changes to the test suite don't break anything that we aren't expecting. 

#### Release notes

Updated the Order workflow to make completing an order and processing payments two separate steps. 

Changelog Category: Technical changes

#### Dependencies

The first 13 commits in this PR are in #7708, so once that's been merged, we can rebase and just use the additional two (or more) from this branch.

### CODE REVIEW

File: app/jobs/subscription_placement_job.rb [hunk 1]
```diff
@@ -50,6 +50,7 @@ def place_order(order)
     return handle_empty_order(order, changes) if order.line_items.where('quantity > 0').empty?
 
     move_to_completion(order)
+    order.process_payments! if order.payment_required?
```
Comment (sauloperez) [inline app/jobs/subscription_placement_job.rb:53]: :warning: this will likely conflict with https://github.com/openfoodfoundation/openfoodnetwork/pull/7281

Comment (andrewpbrett) [reply app/jobs/subscription_placement_job.rb:53]: Yeah, it definitely will :) I think we can just add the same line right after we call `move_to_completion` again and it should be fine.

File: app/controllers/checkout_controller.rb [hunk 2]
```diff
@@ -142,7 +142,7 @@ def valid_payment_intent_provided?
   end
 
   def handle_redirect_from_stripe
-    if OrderWorkflow.new(@order).next && order_complete?
+    if OrderWorkflow.new(@order).next && order_complete? && @order.process_payments!
```
Comment (luisramos0) [inline app/controllers/checkout_controller.rb:145]: So, we will move the order to complete and then process payments?
We need to move the order back fro complete if payment fails, right?

Comment (luisramos0) [reply app/controllers/checkout_controller.rb:145]: I thought the order payment state was when we take payments. Is this changing? Do we keep the payment state, what for?

Comment (luisramos0) [reply app/controllers/checkout_controller.rb:145]: Independently of the points above, I dont think this line can be here, I think this needs to be moved to a service. The relation between the order workflow and the taking of payment should be isolated in a service.

File: app/services/order_workflow.rb [hunk 3]
```diff
@@ -21,6 +21,14 @@ def next(options = {})
...
   end
 
+  def advance_to_payment
+    until order.state == "payment"
+      break unless order.next
+
+      after_transition_hook(advance_order_options)
+    end
+  end
+
```
Comment (luisramos0) [inline app/services/order_workflow.rb:31]: this is copy pasted from advance_order, right? can youcreate a method advance_to_state(target_state) and reuse here and in advance_order?

**Review by luisramos0 — COMMENTED** [review]
Interesting! I leave a question.

File: app/controllers/checkout_controller.rb (hunk 2 above)
Comment (andrewpbrett) [reply app/controllers/checkout_controller.rb:145]: We want to change when we take the payments, yes. Namely we want to be able to have payment processing be separate from the state of the order. We may be able to remove the payment state entirely in the future, but there's other callbacks (`before_transition to: :payment, do: :create_tax_charge!` and `after_transition to: :payment, do: :set_payment_amount!` that we'd have to consider as well, and I wanted to keep this PR as small as possible. 

> We need to move the order back fro complete if payment fails, right?

I don't think so, not unless we specifically want to cancel the order. If a first attempt at payment fails, we should keep the order in `complete` and allow the customer or a manager to add an additional payment.

File: app/services/order_workflow.rb (hunk 3 above)
Comment (andrewpbrett) [reply app/services/order_workflow.rb:27]: 👍 f27c58ac7b240bd4d204257568a619827a9c1ea0

File: app/controllers/checkout_controller.rb (hunk 2 above)
Comment (luisramos0) [reply app/controllers/checkout_controller.rb:145]: ok, that makes sense and sounds really good :+1: 

the only problem I see then is the fact that this logic should be in a service :+1:

Comment (sauloperez) [reply app/controllers/checkout_controller.rb:145]: I also think (it's one of things that pop up to mind all the time) that the entire `#process_payments!` logic should be extracted and not hang from the omnipresent order model. But I agree with @andrewpbrett to be extra cautious and do that separately.

File: app/controllers/spree/admin/payments_controller.rb [hunk 4]
```diff
@@ -35,15 +35,16 @@ def create
...
           if @order.completed?
-            @payment.process!
+            authorize_stripe_sca_payment
+            @payment.process_offline!
             flash[:success] = flash_message_for(@payment, :successfully_created)
 
             redirect_to spree.admin_order_payments_path(@order)
           else
             OrderWorkflow.new(@order).complete!
+            authorize_stripe_sca_payment
```
Comment (sauloperez) [inline app/controllers/spree/admin/payments_controller.rb:46]: This is also quite smelly to be in the controller. I see it has nothing to do with it and it'd be better off in a separate service. Again, stuff for upcoming iterations.

File: app/controllers/spree/admin/payments_controller.rb [hunk 5]
```diff
@@ -175,9 +176,11 @@ def authorize_stripe_sca_payment
 
         @payment.authorize!(full_order_path(@payment.order))
 
-        raise Spree::Core::GatewayError, I18n.t('authorization_failure') unless @payment.pending?
+        unless @payment.pending? || @payment.requires_authorization?
+          raise Spree::Core::GatewayError, I18n.t('authorization_failure')
```
Comment (sauloperez) [inline app/controllers/spree/admin/payments_controller.rb:180]: wouldn't it be worth raising a diferent message in each case? that would at least be helpful while debugging but it could also be useful for the user.

File: app/services/order_workflow.rb [hunk 6]
```diff
@@ -6,7 +6,7 @@ def initialize(order)
   end
 
   def complete
-    advance_order(advance_order_options)
+    advance_to_state("complete", advance_order_options)
```
Comment (sauloperez) [inline app/services/order_workflow.rb:9]: this is just a minor thing, but I think symbols are better suited for this.

File: app/models/spree/payment.rb [hunk 7]
```diff
@@ -77,6 +78,15 @@ class Payment < ApplicationRecord
       event :invalidate do
         transition from: [:checkout], to: :invalid
       end
+      event :require_authorization do
+        transition from: [:checkout, :processing], to: :requires_authorization
+      end
+      event :failed_authorization do
+        transition from: [:requires_authorization], to: :failed
+      end
+      event :completed_authorization do
```
Comment (sauloperez) [inline app/models/spree/payment.rb:87]: this doesn't feel consistent with `require_authorization`. While this one is a participle the other one is an imperative verb. I'd stick to one or the other. Perhaps an imperative makes more sense when reading like `payment.complete_authorization`?

File: app/models/spree/payment/processing.rb [hunk 8]
```diff
@@ -240,6 +236,9 @@ def handle_response(response, success_state, failure_state)
             if response.cvv_result
               self.cvv_response_code = response.cvv_result['code']
               self.cvv_response_message = response.cvv_result['message']
+              if self.cvv_response_message.present?
+                return self.require_authorization!
```
Comment (sauloperez) [inline app/models/spree/payment/processing.rb:240]: the self is useless here because there's no assignment

File: engines/order_management/app/services/order_management/order/stripe_sca_payment_authorize.rb [hunk 9]
```diff
@@ -15,7 +15,9 @@ def call!(redirect_url = full_order_path(@order))
 
         @payment.authorize!(redirect_url)
 
-        @order.errors.add(:base, I18n.t('authorization_failure')) unless @payment.pending?
+        unless @payment.pending? || @payment.requires_authorization?
```
Comment (sauloperez) [inline engines/order_management/app/services/order_management/order/stripe_sca_payment_authorize.rb:18]: now that I saw the data migration, are we eventually removing the `@payment.pending?` clause?

File: engines/order_management/spec/services/order_management/order/updater_spec.rb [hunk 10]
```diff
@@ -152,6 +152,26 @@ module Order
...
+          end
+        end
+
+        context "when the order has a payment that requires authorization and a completed payment" do
+          let!(:payment) { create(:payment, order: order, state: "requires_authorization") }
+          let!(:completed_payment) { create(:payment, order: order, state: "completed") }
+
+          it "returns paid" do
+            updater.update_payment_state
+            expect(order.payment_state).to_not eq("requires_authorization")
```
Comment (sauloperez) [inline engines/order_management/spec/services/order_management/order/updater_spec.rb:171]: I'd be slightly more confident if we explicitly checked for `"paid"`.

File: app/controllers/spree/admin/payments_controller.rb [hunk 11]
```diff
@@ -35,15 +35,16 @@ def create
             return
           end
 
-          authorize_stripe_sca_payment
-
           if @order.completed?
-            @payment.process!
+            authorize_stripe_sca_payment
+            @payment.process_offline!
```
Comment (sauloperez) [inline app/controllers/spree/admin/payments_controller.rb:40]: why does it need to be processed offline now? could you explain it a bit more? is it to defend against a failed authorization step?

**Review by sauloperez — COMMENTED** [review]
This is definitely looking good! Indeed, a step in the right direction :clap: 

Something I'm a bit concerned about, and that we'll have to watch closely, is that the logic we move out of the inner guts of models and their callbacks may end up spread out throughout the app without a specific place to live in, with the consequences it can have.

While bad abstractions are worse than the duplication they avoid, we should come up with new ones as soon as we see they clearly fit.

**Comment by sauloperez** [comment]
Heads-up @andrewpbrett Two checkout controller specs seem to be failing due to legit reasons :warning:

File: app/controllers/spree/admin/payments_controller.rb (hunk 11 above)
Comment (andrewpbrett) [reply app/controllers/spree/admin/payments_controller.rb:40]: This change wasn't really to defend against anything, but I think it is the correct thing to do here. We're taking a payment in the back office, so the customer isn't "online" to complete the payment. I suspect we didn't notice this before because we always went through the other branch of this conditional.

Comment (sauloperez) [reply app/controllers/spree/admin/payments_controller.rb:40]: good catch :clap:

File: app/controllers/spree/admin/payments_controller.rb [hunk 12]
```diff
@@ -35,15 +35,16 @@ def create
             return
           end
 
-          authorize_stripe_sca_payment
-
           if @order.completed?
-            @payment.process!
+            authorize_stripe_sca_payment
```
Comment (sauloperez) [inline app/controllers/spree/admin/payments_controller.rb:39]: I did a deep dive into this method yesterday and I fail to understand why we skip non-StripeSCA payments like `@payment.payment_method.class == Spree::Gateway::StripeSCA` Why is it that we don't want to authorize PayPal payments, for instance? does anyone know? @luisramos0 ?

**Comment by luisramos0** [comment]
I think paypal payments are single shot. Authorize is only for payment
gateways with two step process, auth and purchase.

File: app/controllers/spree/admin/payments_controller.rb (hunk 12 above)
Comment (andrewpbrett) [reply app/controllers/spree/admin/payments_controller.rb:39]: I'm going to mark this resolved; @sauloperez has started to refactor and address this in https://github.com/openfoodfoundation/openfoodnetwork/pull/7809

File: app/controllers/spree/admin/payments_controller.rb (hunk 4 above)
Comment (andrewpbrett) [reply app/controllers/spree/admin/payments_controller.rb:46]: Agreed. I'll mark this as resolved since I think this will be addressed in https://github.com/openfoodfoundation/openfoodnetwork/pull/7809

File: app/models/spree/payment.rb (hunk 7 above)
Comment (andrewpbrett) [reply app/models/spree/payment.rb]: Agreed. I addressed this and `failed_authorization` in 2d7676d87f852966446b0b172cbd222580ab9b6c. It would be nice to also change `started_processing` to `start_processing` to be totally consistent, but I want to keep this PR small :)

File: app/controllers/checkout_controller.rb [hunk 13]
```diff
@@ -142,7 +142,7 @@ def valid_payment_intent_provided?
   end
 
   def handle_redirect_from_stripe
-    if OrderWorkflow.new(@order).next && order_complete?
+    if OrderWorkflow.new(@order).handle_redirect_from_stripe
```
Comment (Matt-Yorkley) [inline app/controllers/checkout_controller.rb:145]: This might need looking at (and more specs)... the pre-extracted version is equivalent though (eg: `next && order_complete? && @order.process_payments!`).

What happens if/when payment processing fails after order completion here? Lets imagine:
- We do `OrderWorkflow.new(@order).next`
- The order is completed
- We then do `@order.process_payments!` but it fails (for whatever reason)

What happens next?

- We jump to the other side of this conditional and call `checkout_failed`...
- which calls `Checkout::PostCheckoutActions.new(@order).failure`...
- which calls `OrderCheckoutRestart.new(@order).call`...

and then we'll get to here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/a1317be19b76d1953e38f9e47cbc8e5304d275e6/app/services/order_checkout_restart.rb#L9-L17

and then line 12 will throw a `StateMachines::InvalidTransition` error, which won't be caught by the controller action?

File: app/controllers/checkout_controller.rb (hunk 2 above)
Comment (Matt-Yorkley) [reply app/controllers/checkout_controller.rb]: > If a first attempt at payment fails, we should keep the order in complete and allow the customer or a manager to add an additional payment.

We don't want to do that for the checkout though, right? Currently if payment fails at the checkout the order is not completed, and we don't want to change that behavior?

Comment (andrewpbrett) [reply app/controllers/checkout_controller.rb]: Yeah, that's a really good catch @Matt-Yorkley. I just pushed some changes to reflect that. It also means we no longer do this three part chained conditional so that might reduce the need to move things to a service in the immediate term... but there's still a lot of opportunity to refactor here. 

This highlights the difference between order processing in the shopfront and backoffice: in the shopfront flow, we check for stock availability at the beginning of each action, so we're confident that we can process the payment before moving the order to the complete state. In the backoffice, we complete the order first in order to reduce the stock, so that we don't take payment for an order that we don't have stock for. 

Now I'm wondering if instead of, or in addition to, this PR we could add the stock check to the backoffice flow instead of using the action of "completing the order" as a tool to accomplish the goal of checking stock...

File: app/controllers/checkout_controller.rb (hunk 13 above)
Comment (andrewpbrett) [reply app/controllers/checkout_controller.rb]: That's definitely what happened, I verified that I got a state machine transition error when I failed SCA auth on a payment. The latest commit should avoid this.

File: app/controllers/checkout_controller.rb [hunk 14]
```diff
@@ -152,8 +154,10 @@ def handle_redirect_from_stripe
 
   def checkout_workflow(shipping_method_id)
     while @order.state != "complete"
-      if @order.state == "payment" && redirect_to_payment_gateway
-        return
+      if @order.state == "payment"
+        return if redirect_to_payment_gateway
+
+        return action_failed unless @order.process_payments!
```
Comment (andrewpbrett) [inline app/controllers/checkout_controller.rb:160]: This line is taking the deleted `before_transition` callback in the checkout.rb and moving it here, since in the checkout flow we do want to ensure that we process the payment before moving the order to `complete`.

File: app/models/spree/order/checkout.rb [hunk 15]
```diff
@@ -67,12 +67,6 @@ def self.define_state_machine!
                 transition to: :cart, unless: :completed?
               end
 
-              if states[:payment]
-                before_transition to: :complete do |order|
-                  order.process_payments! if order.payment_required?
-                end
-              end
-
```
Comment (sauloperez) [inline app/models/spree/order/checkout.rb:75]: :clap: removing a conditional at this point is worth it all

**Review by sauloperez — APPROVED** [review]

File: app/jobs/subscription_placement_job.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/jobs/subscription_placement_job.rb]: Rebased to address this 👍

**Comment by sauloperez** [comment]
This has been sitting here for a while and considering the shortage of dev hours these days and how urgent it is, I think is best if we move it forward.

**Review by Matt-Yorkley — APPROVED** [review]
Great :muscle:

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett,

This is looking pretty good :clap: :clap: :clap: 

#7665 is not reproducible after this PR. On the pics below, we see why: stock is "reserved" when the payment is created on the order. The moment this is done, the order turns from state `payment` into `complete`. Left is before this PR, right is after:

Order states (right - `payment`; left - `complete`):
image

Stock - on both cases, initial on_hand = 10; line item quantity = 5. We can see that despite the created payment, before this PR, the stock level has not changed, it is still 10. After this PR, it gets reduced as expected:
image

This proves the "concept" and that it closes issue #7665. I think this still needs a careful sanity check to verify there are no regressions, but I thought it could be good to provide early feedback.

**Comment by filipefurtad0** [comment]
As a sanity check tested:

- shopfront orders:
  - Paypal - OK
  - Stripe SCA
    - valid and invalid cards - these behave as expected - Successful payment -> redirect to order confirmation; failed payment redirect to `/checkout` page.
    - scenarios evolving stock reduction during the authentication step - customer is redirected to the `/cart` page
  - cash - order goes to state `complete`; voiding the payment does not revert order state to `payment` or `cart` - OK
 
Observed no changes in shopfront orders.

- backoffice order:
  - Stripe SCA
    - stock reduction - test case pointed out in the previous comment - OK
    - completing payment (valid card)
    - failing payment (invalid card) -> payment state changes from `authentication_required` to `failed` - OK 
  - cash payments - OK

- subscriptions
  - cash - OK
  - stripe SCA
    - valid 3D-auth. card and non-auth. (4242..) - OK 
    - valid 3D-auth.: failing authentication - card is not charged; Stripe reflects this correctly :+1: 
  - no stock available error: no charging and no authentication requested, as expected. Emails arrive as expected.

**Additional thoughts**

i) This PR also closes #7510 :tada: 
Backoffice order flow is now a step closer to the subscription order flow :+1: 

ii) We should note that backoffice orders now resemble a _bit less_ shopfront orders:

- after this PR (and as mentioned above) even after a failed payment is introduced in the BO, the order remains in state `complete`
- in the shopfront though, if a Stripe SCA payment fails, the order remains in the state `payment`:

image

I can't think of anything else to check right now. I found no regressions, so I'd say this is good to go.
Congratulations for the great work :tada:

**Comment by andrewpbrett** [comment]
Thanks as always for the thorough testing @filipefurtad0!!
