### PR TITLE
OrderBalance missing methods

### LINKED ISSUE #7293: subscription orders: NoMethodError: undefined method `to_d' for #<OrderBalance:0x00000000074123f8>
## Description

Observed both with feature toggle on and off:

Orders placed via subs are returning errors. Placing/confirming the sub is successful, but payments seem not to go through. Verified for stripe SCA (card x-3184) and Cash payment methods.

Bugsnag:
(1) After manually forcing the confirmation job in the console:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/60644cbf579e980007f63e7e?event_id=60644cbf0075ef0a8c680000&i=sk&m=nw

(2) Attempting to manually capture StripeSCA payments (a consequence of the previous error)
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6059d808db1b8d0007c7528f?event_id=606450a80076106ce9ab0000&i=sk&m=nw

## Expected Behavior

Valid payments via subscription should be successful.

## Actual Behaviour

Valid payments via subscription are not successful. Order is in a pending state and can be captured manually. 

## Steps to Reproduce

1. Placing a subscription with SCA or Cash -> triggers error (1)
2. Attempt to manually capture the payment on /orders page -> triggers error (2)

## Animated Gif/Screenshot

-
## Workaround

-
## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: current master (after v3.6.2)
* Browser name and version: Firefox 86
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #7293

There were some missing method issues where the code was expecting the object returned by `Order#oustanding_balance` to behave like a number and respond to methods like `#to_d`, which are not implemented in `OrderBalance`. More details [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/7293#issuecomment-810998236)

#### What should we test?

Errors when processing subscriptions, detailed in #7293. Maybe a general check of order balances as well.

#### Release notes

Updated interface in OrderBalance to handle additional methods.

Changelog Category: Technical changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
I'm wondering if we might want to catch any other potential errors here by implementing `OrderBalance#method_missing` and passing the given method to `#amount` if it's not found?

File: app/models/order_balance.rb [hunk 1]
```diff
@@ -1,21 +1,21 @@
 # frozen_string_literal: true
 
 class OrderBalance
-  delegate :zero?, :abs, :to_s, to: :to_f
+  delegate :zero?, :abs, :to_s, to: :amount
```
Comment (sauloperez) [inline app/models/order_balance.rb]: I'm afraid this may break implicit conversions buy I haven't checked

File: app/models/order_balance.rb [hunk 2]
```diff
@@ -24,7 +24,7 @@ def to_f
   end
 
   def +(other)
-    to_f + other.to_f
+    amount + other.to_f
```
Comment (sauloperez) [inline app/models/order_balance.rb:27]: If we go with this renaming, we need to call `other.amount` too

File: spec/models/order_balance_spec.rb [hunk 3]
```diff
@@ -325,6 +325,40 @@
     end
   end
 
+  describe '#to_f and #to_d' do
```
Comment (sauloperez) [inline spec/models/order_balance_spec.rb:328]: Would youind duplicating them? I think is best to make them independent so both we don't tie them innecessarely. We could use an RSpec's shared examole if needed.

File: spec/models/order_balance_spec.rb [hunk 4]
```diff
@@ -358,4 +392,42 @@
       end
     end
   end
+
+  context "with comparison operators" do
```
Comment (sauloperez) [inline spec/models/order_balance_spec.rb:396]: Here as well. I fear that being a bit vague as opposed to clearly stating the method under test may cause these tests not to be thorough enough in the future.

**Comment by sauloperez** [comment]
> I'm wondering if we might want to catch any other potential issues here by implementing OrderBalance#method_missing and passing the given method to #amount if it's not found?

I'm always reluctant to use method_missing for non-framework code but I guess in this case it could make the roll-out of balances smoother. If we stick to `OrderBalance` though, we'll have to implement all the necessary methods and remove method_missing.

**Comment by sauloperez** [comment]
I think is best if we can ship this with the next release. My comments are just minor things and can be tackled separately. Also, using `method_missing` can be done in a new PR as this already solves an issue.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley,

All as before.

Placed Stripe-SCA and cash subscription orders:
- payment states behave as expected
- customer balances reflect these and the order totals
- payments are "capturable" (cash) and accept authorization from the customer (Stripe-SCA)

Ready to go :+1:

File: spec/models/order_balance_spec.rb (hunk 3 above)
Comment (Matt-Yorkley) [reply spec/models/order_balance_spec.rb:328]: I started off with them separated, but I merged them as the huge amount of duplication seemed like it wasn't worth it for these quick tests :see_no_evil:

**Comment by Matt-Yorkley** [comment]
Alright, so we'll merge this for now and we can iterate on the details later?

File: app/models/order_balance.rb (hunk 2 above)
Comment (Matt-Yorkley) [reply app/models/order_balance.rb:27]: But... what if we're adding something that's not an `OrderBalance` object? Like `order.outstanding_balance + shipping_fee` or something. It'll give unexpected results, right? If we're adding two objects that are both an `OrderBalance`, when we do `other.to_f` it'll already be delegated to `#amount` by default, right?

File: spec/models/order_balance_spec.rb (hunk 3 above)
Comment (sauloperez) [reply spec/models/order_balance_spec.rb:328]: shared examples could help removing the duplication.

File: app/models/order_balance.rb [hunk 5]
```diff
@@ -1,21 +1,21 @@
 # frozen_string_literal: true
 
 class OrderBalance
-  delegate :zero?, :abs, :to_s, to: :to_f
+  delegate :zero?, :abs, :to_s, :to_f, :to_d, :<, :>, to: :amount
```
Comment (sauloperez) [inline app/models/order_balance.rb:4]: I'd like to try if using Ruby's [Comparable](https://ruby-doc.org/core-3.0.0/Comparable.html) and implementing the `<=>` saves us from having to implement each method separately. Could you take a look @Matt-Yorkley ?

File: app/models/order_balance.rb (hunk 2 above)
Comment (sauloperez) [reply app/models/order_balance.rb:27]: you are right. I wasn't thinking `other` can be of any type, not just `OrderBalance` :see_no_evil:
