### PR TITLE
Fixes button staying disabled after report fail

### LINKED ISSUE #12801: [Reports] Go button remains disabled after a failed report
## Description

In case the generation of a report fails due to the error message `This report failed. It may be too big to process. We will look into it but please let us know if the problem persists.`, then the 'Go' button remains disabled after the error message is shown. The user can make changes to the report setting (to reduce its size), but it's impossible to run the report again afterwards.

## Expected Behavior

The 'Go' button should become active again after the error message was shown.

## Actual Behaviour

The 'Go' button remains disabled after the error message was shown.

## Steps to Reproduce

1. Log in as user 7990 on staging AU (happy to provide the login details).
2. Go to the 'All products' report.
3. Run the report without filling in any fields in the report filters.
4. You should see the error message.
5. The 'Go' button remains disabled.

## Animated Gif/Screenshot

image

## Workaround

Reload the page.

## Severity
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by cyrillefr**
#### What? Why?

Closes #12801 

After a failed report, "Go" button used to remain disabled.
It was not implemented.
Button is disabled during loading time and is now enabled again in case of report failure.

#### What should we test?
Replaying the steps provided by @drummer83 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [X] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/support/reports_helper.rb [hunk 1]
```diff
@@ -13,6 +13,19 @@ def run_report
     expect(page).to have_button "Go", disabled: false
   end
 
+  def run_failed_report(report)
```
Comment (dacook) [inline spec/support/reports_helper.rb:16]: I think  a single test (as you have done) is enough, therefore there's no need for this to be in a method. The code could be directly inside the test, so I'd suggest moving it there.

**Review by dacook — CHANGES_REQUESTED** [review]
Great, thanks for fixing this.

I have a suggestion: could you extend the test so that it runs the report a second time?

Perhaps you can set up the and_raise to only raise an error the first time, then let it succeed the second time. If you can't get it to work then don't worry, we can keep the current test.

It would also be good to move all the test code inside `reports_spec.rb`, because I don't think it needs to be in a helper method.

File: spec/support/reports_helper.rb (hunk 1 above)
Comment (cyrillefr) [reply spec/support/reports_helper.rb]: I have removed the failed test from the helper to the main test. 
I have added a 2nd run (not failing) on my test.
For that, I have used the `and_call_original` to "unmock" the call, a feature I did not know, I find it very handy.

File: spec/system/admin/reports_spec.rb [hunk 2]
```diff
@@ -352,7 +352,24 @@
...
+      expect(page).to have_button "Go", disabled: false
+      expect(page).to have_content 'This report failed. It may be too big to process. ' \
+                                   'We will look into it but please let us know ' \
+                                   'if the problem persists.'
+
+      # Admin shoulb be able to make some changes and retry
+      sleep(1)
+      allow(report).to receive(:new).and_call_original
+
+      run_report
```
Comment (rioug) [inline spec/system/admin/reports_spec.rb:372]: I think we should check the report is actually displayed on the page. Something like `expect(page).to have_content "Supplier" ` should be enough.

File: spec/system/admin/reports_spec.rb [hunk 3]
```diff
@@ -352,7 +352,24 @@
...
+      perform_enqueued_jobs(only: ReportJob)
+
+      expect(page).not_to have_selector ".loading"
+      expect(page).to have_button "Go", disabled: false
+      expect(page).to have_content 'This report failed. It may be too big to process. ' \
+                                   'We will look into it but please let us know ' \
+                                   'if the problem persists.'
+
+      # Admin shoulb be able to make some changes and retry
+      sleep(1)
```
Comment (rioug) [inline spec/system/admin/reports_spec.rb:369]: Is the `sleep` necessary here ? It's better to not use `sleep` as it can result in flacky test.

**Review by rioug — DISMISSED** [review]

File: spec/system/admin/reports_spec.rb (hunk 2 above)
Comment (cyrillefr) [reply spec/system/admin/reports_spec.rb:371]: I just added that line.

File: spec/system/admin/reports_spec.rb (hunk 3 above)
Comment (cyrillefr) [reply spec/system/admin/reports_spec.rb]: I have removed the sleep.

**Review by dacook — APPROVED** [review]
Great 👍

**Review by rioug — APPROVED** [review]
Great ! Thanks :pray:

**Comment by dacook** [comment]
I think you're right about the 404s: from memory it will poll for the finished report, waiting until it is complete. So I believe that's a normal behaviour.

Regarding the bugsnag error, yes it's most likely due to the product refactor. Primary taxon (product category used to be on the product record. I think it should have been migrated with a DB migration, but perhaps the migration wasn't successful on that server, or the data was out of sync due to the order of PRs being deployed on the staging server. 🤷 I wouldn't worry unles it also occurs in production.
