### PR TITLE
Don't allow multi-line voucher codes

### LINKED ISSUE #10868: [Vouchers] Multi-line voucher code can be created but can't be applied
## Description

When creating a voucher code, there is a text field provided and you can enter several lines of text there. However it is not possible to use that voucher during checkout because it can't be found.

## Expected Behavior

Every voucher code that can be created should be usable.

## Actual Behaviour

Voucher codes with several lines can be created but they can't be used.

## Steps to Reproduce

1. Go to 'new voucher' page (admin/enterprises/enterprise_name/vouchers/new).
2. Create a voucher with several lines.
3. Try to use the voucher during checkout.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/18ef66fe-7d42-4969-9c83-8191f598f767

## Workaround

Use one line only.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

Use a simple input field with one line only instead of a text field with multiple lines.

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

- Closes #10868 and...
- Automatically removes whitespace at the start or end of codes
- Validates code doesn't exceed the database column width i.e. 255
- Validates code doesn't contain new line characters

#### What should we test?

See steps to reproduce in #10868

#### Release notes

Changelog Category: User facing changes 

### Before

voucher-code-before

### After

voucher-code-after

### CODE REVIEW

File: app/models/voucher.rb [hunk 1]
```diff
@@ -10,7 +12,11 @@ class Voucher < ApplicationRecord
            class_name: 'Spree::Adjustment',
            dependent: :nullify
 
-  validates :code, presence: true, uniqueness: { scope: :enterprise_id }
+  before_validation :strip_code
+
+  validates :code, format: { without: INVALID_CODE_REGEX },
+                   length: { maximum: STRING_COLUMN_LIMIT },
```
Comment (mkllnk) [inline app/models/voucher.rb:18]: What do you think about using the limit of the database itself instead of repeating it in our own constant?
```suggestion
                   length: { maximum: columns_hash["code"].limit },
```

Apparently, there's a gem for it but it looks out of date:

* https://github.com/rubiety/validates_lengths_from_database

File: app/models/voucher.rb [hunk 2]
```diff
@@ -12,7 +14,8 @@ class Voucher < ApplicationRecord
 
   before_validation :strip_code
 
-  validates :code, length: { maximum: STRING_COLUMN_LIMIT },
+  validates :code, format: { without: INVALID_CODE_REGEX },
```
Comment (mkllnk) [inline app/models/voucher.rb:17]: I think that this is too much validation. The browser doesn't allow this, right? Is there another way this could happen by accident? I don't think that there's a case of some trying this intentionally and then it's their own fault. Going down this rabbit hole we could start to enforce only certain characters that are easy to print and read etc but I would leave this up to the person creating the voucher. It's always a balance between all the cool features and simple code.

**Review by mkllnk — APPROVED** [review]
Great contribution, thank you!

There are a couple of things that I would like to be changed. Would you be happy to work on those?

Otherwise the current code is good and solves the problem. I'm approving it.

File: app/models/voucher.rb (hunk 2 above)
Comment (dacook) [reply app/models/voucher.rb:17]: I agree; I appreciate the extra validation done here but in general validation is to help avoid mistakes or malicious behaviour. The browser input solves the problem for us, so we don't need to add additional code to the codebase. 
Especially as Maikel explained, we may need to handle newlines differently soon anyway.

File: app/models/voucher.rb (hunk 1 above)
Comment (dacook) [reply app/models/voucher.rb:18]: That seems cool, but whether it's an activerecord validation error, or a database error, I guess the impact would be similar.

Even better if we can validate lengths on the frontend input. I once looked for a gem to add this automatically to the form builder but didn't find an answer.. 

But in any case, I think it would be better to worry about this once we deal with batch-creation.

File: app/models/voucher.rb [hunk 3]
```diff
@@ -43,4 +49,10 @@ def create_adjustment(label, order)
   def compute_amount(order)
     -amount.clamp(0, order.pre_discount_total)
   end
+
+  private
+
+  def strip_code
+    code.strip! if code.present?
+  end
```
[the remark this answers is not in the document]
Comment (cillian) [reply app/models/voucher.rb]: That's better, fixed by https://github.com/openfoodfoundation/openfoodnetwork/pull/11259/commits/9eba266efc92a52e13734b719c46238cff4d24fd and good to know about `normalizes`.

File: app/models/voucher.rb (hunk 2 above)
Comment (cillian) [reply app/models/voucher.rb]: No problem, removed in https://github.com/openfoodfoundation/openfoodnetwork/pull/11259/commits/ab0d899a17c2198ee4d6de9e886816f3e75abd0e. This was in case vouchers could be created via an API endpoint in future.

File: app/models/voucher.rb (hunk 1 above)
Comment (cillian) [reply app/models/voucher.rb]: I have removed this https://github.com/openfoodfoundation/openfoodnetwork/pull/11259/commits/d026438edcd7f0211f1528dcef0318176b414fa1 for now seen as though it might be changing soon. Thanks for the review, let me know if you want me to rebase things.

File: app/models/voucher.rb [hunk 4]
```diff
@@ -10,12 +10,14 @@ class Voucher < ApplicationRecord
...
 
-  before_validation :strip_code
-
   validates :code, length: { maximum: STRING_COLUMN_LIMIT },
                    presence: true, uniqueness: { scope: :enterprise_id }
   validates :amount, presence: true, numericality: { greater_than: 0 }
 
+  def code=(value)
+    super(value.to_s.strip)
+  end
```
Comment (mkllnk) [inline app/models/voucher.rb:18]: My version contained the `&.` operator in case we are assigning `nil`. That is unlikely, but we may do that in specs for example to test validations. It's always good to have robust code that doesn't raise errors on nil values.

Comment (mkllnk) [reply app/models/voucher.rb:18]: Oh, I just realised that `to_s` is converting `nil` to a string already and there since the empty string is as invalid as nil, this works fine. :heavy_check_mark:

**Review by mkllnk — APPROVED** [review]

**Review by rioug — APPROVED** [review]
Looks good ! thanks for that.

**Comment by drummer83** [comment]
Hi @cillian,
Thank you for another contribution!

### Before staging
- It was possible to enter multiple lines of text as a voucher code. This was intended to provide the functionality to create multiple voucher codes at once. However this hasn't been implemented yet.
image
- Multiple lines were combined in one voucher code:
image
- This code couldn't be used by customers because it couldn't be found in the list of voucher codes. :x:

### After staging
- It is only possible to use one line for voucher codes. :heavy_check_mark: 
image
- The voucher is correctly created. :heavy_check_mark: 
image
- The voucher can be used for checkout. :heavy_check_mark: 
image
- I also confirmed that previously generated vouchers can still be used. :heavy_check_mark: 
- I also confirmed that leading and trailing blank spaces are being removed and the created voucher can be used. :heavy_check_mark: 

## Conclusion
Excellent work once again! :tada: 
Everything seems to work as expected. Merging! :partying_face: 

Thanks again! :pray:
