### PR TITLE
Fix payment capture handling in Api::OrdersController

### LINKED ISSUE #7109: Errors in payment processing message
This error has popped up in [Bugsnag](https://app.bugsnag.com/open-food-france/coopcircuits/errors/604f323d3820370007ab0010?event_id=604f323d0073be9c59010000&i=sk&m=nw) several time:

```
NoMethodError: undefined method `t' for #<Api::OrdersController:0x0000000013834290>
Location
app/controllers/api/orders_controller.rb:50 - payment_capture_failed
```

There's a bug in the orders controller stopping it from rendering error messages.

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #7109 

Fixes:
```
NoMethodError: undefined method `t' for #<Api::OrdersController:0x0000000013834290>
Location
app/controllers/api/orders_controller.rb:50 - payment_capture_failed
```

#### What should we test?

Green build should be enough, a regression test is added.

#### Release notes

Fixed displaying of errors when payment capture fails.

Changelog Category: Technical changes

### CODE REVIEW

File: spec/controllers/api/orders_controller_spec.rb [hunk 1]
```diff
@@ -285,6 +285,18 @@ module Api
           expect(order.reload.pending_payments.empty?).to be true
           expect_order
         end
+
+        context "when payment is not required" do
+          before do
+            allow_any_instance_of(Spree::Order).to receive(:payment_required?) { false }
```
Comment (sauloperez) [inline spec/controllers/api/orders_controller_spec.rb:291]: I'm not very fond of this and would very much prefer to stub the finder method to return the `order` we care about but it's not a big deal I guess

**Review by sauloperez — APPROVED** [review]

**Review by andrewpbrett — APPROVED** [review]
