### PR TITLE
3283 [Enterprise Fee Summary] Fix values when calculator is order-based

### LINKED ISSUE #2616: Build Enterprise Fee Summary Report
https://docs.google.com/spreadsheets/u/1/d/1pnJwHgBo2sokdcwNoLquYlVh8ICUcx6X4J2ZAMnRyio/edit?usp=sharing
Sheet "THIS By Customer"

Fee Type | Enterprise Owner | Fee Name | Customer | Fee Placement | Fee calc on trans through | Tax Category | $$ SUM
-- | -- | -- | -- | -- | -- | -- | --
Admin | Coord 1 |   | Customer A | Coordinator | All |   | 2.3
Admin | Coord 1 |   | Customer B | Coordinator | All |   | 4.7
Admin | Hub 2 |   | Customer A | Outgoing | Hub 2 |   |  
Admin | Hub 2 |   | Customer B | Outgoing | Hub 2 |   |  
Mgmt | Coord 1 |   | Customer A | Incoming | Supplier 2 |   |  
Mgmt | Coord 1 |   | Customer B | Incoming | Supplier 2 |   |  
Packing | Supplier 1 |   | Customer A | Incoming | Supplier 1 |   |  
Packing | Supplier 1 |   | Customer B | Incoming | Supplier 1 |   |  
Transport | Coord 1 |   | Customer A | Incoming | Supplier 2 |   |  
Transport | Coord 1 |   | Customer B | Incoming | Supplier 2 |   |  
Transport | Hub 3 |   | Customer A | Outgoing | Hub 3 |   |  
Transport | Hub 3 |   | Customer B | Outgoing | Hub 3 |   |  
Transport | Supplier 1 |   | Customer A | Incoming | Supplier 1 |   | etc
Transport | Supplier 1 |   | Customer B | Incoming | Supplier 1 |   | etc

### PR DESCRIPTION
**Pull request by kristinalim**
#### What? Why?

Relates to #3283 
Closes #2616

Because of constraints in the way we compute and store calculations for order-based calculators, there is no way currently to track the exchange to which an order-based exchange fee is associated, and to break down this fee per line item/variant/supplier.

So, we do not have an existing way to get "Fee Calc on Transfer Through" and "Tax Category" (when the Enterprise Fee itself does not have an associated tax category) for these exchange fees.

As proposed in #3283, we could use "Entire Orders through DISTRIBUTOR_NAME" for these order-absed exchange fees. For "Tax Category", we could use "Various" when there is no associated tax category to the enterprise fee.

#### What should we test?

1. Set up an OC with different enterprises for producer, coordinator, and distributor.
2. Set up an incoming and outgoing exchange for a variant with stock.
3. **Fees for exchanges**: For the incoming exchange and also for the outgoing exchange, add one enterprise fee with order-based calculator (such as "Flat Rate (per order)") for each of the producer, coordinator, and distributor. For testing purposes, one of these enterprise fees should assign a tax category, one should inherit the product's tax category, and one should have no tax category.
4. **Coordinator fees**: Add two "coordinator fees" with order-based calculator to the OC, not to an exchange. For testing purposes, one of these enterprise fees should assign a tax category, one should inherit the product's tax category, and one should have no tax category.
4. Create and complete an order for the variant.
5. Check the Enterprise Fee Summary.
6. For the 6 rows marked "Incoming" / "Outgoing":
    - "Fee Calc on Transfer Through" for the exchange fees should show "Entire Orders through DISTRIBUTOR_NAME".
    - For tax category:
        a. If the enterprise fee itself has a tax category, this should be used.
        b. If the enterprise fee inherits the product's tax category, this should be "Various".
        c. If the enterprise fee has no tax category, this should be blank.
7. For the rows marked "Coordinator":
    - "Fee Calc on Transfer Through" should be "All". For tax category.
    - For tax category: Same as in Step 6.

#### Release notes

No release notes needed as this would be packaged with the rest of the initial changes for the Enterprise Fee Summary.

Changelog Category: -

#### Dependencies

This requires #3319 to be merged to the transitional branch first.

### CODE REVIEW

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/scope.rb [hunk 1]
```diff
@@ -169,14 +170,38 @@ def include_enterprise_fee_details
...
         end
 
-        # If for line item - Use data only if spree_line_items.id is present
+        # If for order source
+        #
+        # Includes:
+        # * Source order
+        # * Distributor
+        def include_order_source_details
+          join_scope(
```
Comment (mkllnk) [inline engines/order_management/app/services/order_management/reports/enterprise_fee_summary/scope.rb]: This method name is a bit ambiguous: https://www.rubydoc.info/github/rails/rails/ActiveRecord%2FReflection%2FAbstractReflection:join_scope

Did you forget to chain the two scopes together?

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/enterprise_fee_type_total_summarizer.rb [hunk 2]
```diff
@@ -2,66 +2,92 @@ module OrderManagement
...
 
         def fee_type
-          if for_payment_method?
-            i18n_translate("fee_type.payment_method")
-          elsif for_shipping_method?
-            i18n_translate("fee_type.shipping_method")
-          else
-            data["fee_type"].try(:capitalize)
-          end
+          case adjustment_source_type
```
[the remark this answers is not in the document]
Comment (kristinalim) [reply engines/order_management/app/services/order_management/reports/enterprise_fee_summary/enterprise_fee_type_total_summarizer.rb]: Thanks @mkllnk! I've addressed this here: https://github.com/openfoodfoundation/openfoodnetwork/pull/3337/commits/5a9178a9df6ab9ac529107b986b682251c5b3688

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/incoming_exchange_line_item_fee.rb [hunk 3]
```diff
@@ -0,0 +1,17 @@
+module OrderManagement
+  module Reports
+    module EnterpriseFeeSummary
+      module DataRepresentations
```
Comment (sauloperez) [inline engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/incoming_exchange_line_item_fee.rb]: What does this namespace provide other than making the nesting level pretty wide? These model classes won't clash with any other within the `EnterpriseFeeSummary` namespace, so I'd just remove `DataRepresentations`.

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/associated_enterprise_fee.rb [hunk 4]
```diff
@@ -0,0 +1,31 @@
+module OrderManagement
+  module Reports
+    module EnterpriseFeeSummary
+      module DataRepresentations
+        class AssociatedEnterpriseFee
```
Comment (sauloperez) [inline engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/associated_enterprise_fee.rb]: I'd be great to provide an explanation of what this is in a comment.

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/summarizer.rb [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+        end
+
+        def i18n_translate(translation_key, options = {})
+          I18n.t("order_management.reports.enterprise_fee_summary.#{translation_key}", options)
+        end
+
+        private
+
+        def representation
+          @representation ||= representation_klass.new(self)
```
Comment (sauloperez) [inline engines/order_management/app/services/order_management/reports/enterprise_fee_summary/summarizer.rb]: If we passed `data` instead of `self` we could avoid lots of references to `context` in all `DataRepresentations` classes.

File: spec/factories/orders.rb [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+      after(:create) do |order, evaluator|
+        order.create_shipment!
+        create(:payment, state: "checkout", order: order, amount: order.total,
+                         payment_method: evaluator.payment_method)
+        order.update_distribution_charge!
+        while !order.completed? do break unless order.next! end
+      end
+    end
+  end
+end
```
Comment (sauloperez) [inline spec/factories/orders.rb]: Thanks for creating a new file! :clap:

File: spec/factories/orders.rb [hunk 7]
```diff
@@ -0,0 +1,27 @@
...
+  factory :order do
+    trait :with_line_item do
+      transient do
+        variant { FactoryGirl.create(:variant) }
+      end
+
+      after(:create) do |order, evaluator|
+        create(:line_item, order: order, variant: evaluator.variant)
+      end
+    end
```
Comment (sauloperez) [inline spec/factories/orders.rb]: do we really need this new trait? Spree itself has the `order_with_line_items` factory already. Other than that, this could be done by simply creating two of the three entities and letting FactoryBot create the third one. I'm just concerned about having too many purpose-specific factories that need to be maintained over time. I believe that is already the case in OFN.

File: spec/factories/orders.rb [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+
+    trait :completed do
```
Comment (sauloperez) [inline spec/factories/orders.rb]: Spree has the `completed_order_with_totals` factory, which we reused to build more complex ones in OFN. Can't we use just that one?

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/summarizer.rb [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+        end
+
+        def representation_klass
+          return DataRepresentations::PaymentMethodFee if for_payment_method?
+          return DataRepresentations::ShippingMethodFee if for_shipping_method?
+          enterprise_fee_adjustment_presentation_klass if for_enterprise_fee?
+        end
+
+        def enterprise_fee_adjustment_presentation_klass
+          return DataRepresentations::CoordinatorFee if for_coordinator_fee?
```
Comment (mkllnk) [inline engines/order_management/app/services/order_management/reports/enterprise_fee_summary/summarizer.rb]: I used to write code this way, but the Ruby community seems to prefer another style:
```rb
if for_payment_method?
  DataRepresentations::PaymentMethodFee
elsif for_shipping_method?
  DataRepresentations::ShippingMethodFee
#...
end
```

Now, after the refactoring, there is a bit of duplication in the naming here. Everything is mentioned twice. If I wrote it from scratch, I would remove one level here:

```rb
if data["payment_method_name"].present?
  DataRepresentations::PaymentMethodFee
#...
```

But I don't think you need to touch this now. Just something to keep in mind when changing code in the future.

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/incoming_exchange_line_item_fee.rb (hunk 3 above)
Comment (kristinalim) [reply engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/incoming_exchange_line_item_fee.rb]: I disagree about removing `DataRepresentations`, @sauloperez.

The class ends up more deeply nested, but `DataRepresentations` I think makes it easier to find/ignore these classes and gives you an idea about their purpose.

If we reduce the nesting, I would want to rename the individual classes to reflect that they map DB query row attributes to report row attributes. For example, append "Representation" or "Presenter" (both terms actually from review of @mkllnk). Compared to this, I prefer nesting.

Let me know if you are okay with keeping this.

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/associated_enterprise_fee.rb (hunk 4 above)
Comment (kristinalim) [reply engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/associated_enterprise_fee.rb]: I added class descriptions for these new classes: https://github.com/openfoodfoundation/openfoodnetwork/pull/3337/commits/37b8a36f66cd88c7f4f5c7cf4fee65e94b490f3c Thank you!

**Comment by kristinalim** [comment]
I updated the issue description to also close issue #2616. This is the last PR addressing known issues in the report values.

File: engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/incoming_exchange_line_item_fee.rb (hunk 3 above)
Comment (luisramos0) [reply engines/order_management/app/services/order_management/reports/enterprise_fee_summary/data_representations/incoming_exchange_line_item_fee.rb]: I like this way of using namespaces to organize your code! #java

**Comment by kristinalim** [comment]
Thanks, @luisramos0! Moving this to "Test Ready".

**Comment by kirstenalarsen** [comment]
YIHIYIPPEEEEIO!!! YES!!! Passed the tests and good to go! Fantastic test notes @kristinalim I was overwhelmed but when I looked closely and just worked through the steps it made perfect sense and was thorough and I am confident that it works. YAY! So excited! MERGEROONIE!

**Comment by sauloperez** [comment]
Sorry to ruin the party but I think it's better if you rebase it @kristinalim

**Comment by kristinalim** [comment]
I've rebased, @sauloperez. Conflict now gone, and build is green. Thank you!

**Comment by kristinalim** [comment]
As discussed here https://github.com/openfoodfoundation/openfoodnetwork/pull/3415#issuecomment-462705477, @sauloperez I recommend merging #3415 first. And then I will change the base of this PR to master and rebase, to comply with the process. :+1:

**Comment by sauloperez** [comment]
done. #3415 merged

**Comment by kristinalim** [comment]
Aha! :slightly_smiling_face: Finally, a green build.

I've rebased this already, and changed the base branch to "master". This is ready to go.
