### PR TITLE
Fix Rubocop Rails issue: Rails/FindEach

### LINKED ISSUE #11482: Fix Rubocop Rails issues

### LINKED ISSUE #12290: Rubocop Rails/FindEach
Part of #11482 

https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Rails/FindEach

### PR DESCRIPTION
**Pull request by anthonyms**
#### What? Why?

Closes #12290 

Fix all violations of the Rails/FindEach cop.

- Part of #11482 

[Rubocop](https://www.rubydoc.info/gems/rubocop/0.41.2/RuboCop/Cop/Rails/FindEach) recommends using `find_each` in place of `each` whenever the call is chained to a `where`, `all` or `not`.

This PR is one of many PR's addressing issue #11482.

#### What should we test?
N/A

#### Release notes
Fix all violations of the Rails/FindEach cop.

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

#### Dependencies
N/A

#### Documentation updates
N/A

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Nice one ! Thanks for your help :pray:

File: app/services/orders/bulk_cancel_service.rb [hunk 1]
```diff
@@ -10,11 +10,14 @@ def initialize(params, current_user)
...
     def call
-      editable_orders.where(id: @order_ids).each do |order|
+      cancelled_orders = []
+      editable_orders.where(id: @order_ids).find_each do |order|
         order.send_cancellation_email = @send_cancellation_email
         order.restock_items = @restock_items
         order.cancel
+        cancelled_orders << order
       end
+      cancelled_orders
```
Comment (dacook) [inline app/services/orders/bulk_cancel_service.rb:20]: It took me a few minutes to work out why this was needed: because `each` returns the array of records, but `find_each` doesn't retain an array, to avoid taking up too much memory.

Hmm, so then if we need to store the records in an array, there's no reason to use `find_each` here!

`±` Could you please change this one back to `each` with a `rubocop:disable`?

File: app/services/products_renderer.rb [hunk 2]
```diff
@@ -89,10 +89,14 @@ def variants_for_shop
...
 
+      scoped_variants = []
+
       distributed_products.variants_relation.
         includes(:default_price, :stock_locations, :product).
         where(product_id: products).
-        each { |v| scoper.scope(v) } # Scope results with variant_overrides
+        find_each { |v| scoped_variants << scoper.scope(v) } # Scope results with variant_overrides
+
+      scoped_variants
```
Comment (dacook) [inline app/services/products_renderer.rb:99]: `±` same as for other comment.

**Review by dacook — CHANGES_REQUESTED** [review]
Thank you!

I have a comment about a couple of the changes, which I think need changing.

File: app/services/orders/bulk_cancel_service.rb (hunk 1 above)
Comment (anthonyms) [reply app/services/orders/bulk_cancel_service.rb:20]: Theres some (little) benefit in retaining the `find_each` since the processing will be done in batches.  The `cancelled_orders` array will expand gradually rather than suddenly.

The little benefit is negated by the lack of readability.

Will use a `rubocop:disable` for this one.

**Review by mkllnk — APPROVED** [review]
Nice, thank you.

**Review by dacook — APPROVED** [review]
Thank you, and bonus points for comments explaining why! 💯
