### PR TITLE
Splits assertions to allow JS table populate

### LINKED ISSUE #10799: [Flaky] rspec ./spec/system/admin/order_spec.rb:146
### What we should change and why (this is tech debt)

```
Failures:

  1) 
    As an administrator
    I want to create and edit orders
 can add a product to an existing order
     Failure/Error: expect(page).to have_selector 'td', text: product.name
       expected to find visible css "td" with text "Product #4 - 3935" but there were no matches. Also found "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", "<<ERROR>>", which matched the selector but not all filters. 
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_as_an_administrator_i_want_to_create_and_edit_orders_can_add_a_product_to_an_existing_order_285.png

     
     # ./spec/system/admin/order_spec.rb:155:in `block (2 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <top (required)>'

Finished in 4 minutes 42.8 seconds
52 examples, 1 failure

Failed examples:

rspec ./spec/system/admin/order_spec.rb:146 # 
    As an administrator
    I want to create and edit orders
 can add a product to an existing order
I, [2023-05-03T14:18:49.146894 #2963]  INFO -- : [knapsack_pro] To retry all the tests assigned to this CI node, please run the following command on your machine:
I, [2023-05-03T14:18:49.146956 #2963]  INFO -- : [knapsack_pro] bundle exec rspec --format progress --default-path spec "spec/system/admin/order_spec.rb"
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
Coverage report generated for RSpec to /home/runner/work/openfoodnetwork/openfoodnetwork/coverage. 6888 / 24146 LOC (28.53%) covered.
Error: Process completed with exit code 1.
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4872903815/jobs/8691745034

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

- Closes #10799 

The assertion was looking for content within the table: the table was found, very often it was not yet populated with the line item names - instead a cryptic `<<ERROR>>` was "seen" by Capybara.

This PR splits the assertions into three bits, preceded by a `sleep(1)`:
1) the table
2) the content
3) the content within the table
4) check the order now has a new line item appended

The `sleep(1)` is not ideal, but seems to work... I've explored different variations, but I could not prevent this spec from timeout this way. It now passes `100 of 100 passed (100%)`; before it took longer (~20 secs) and failed several times already within the first 10 runs...

#### What should we test?

- :green_circle: build

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/order_spec.rb [hunk 1]
```diff
@@ -179,9 +179,9 @@ def new_order_with_distribution(distributor, order_cycle)
     visit spree.edit_admin_order_path(order)
 
     select2_select product.name, from: 'add_variant_id', search: true
-
     find('button.add_variant').click
     # Wait for JS
+    sleep(1)
     page.has_selector?("table.index tbody tr td")
```
Comment (Matt-Yorkley) [inline spec/system/admin/order_spec.rb:185]: I think if we change this line to an `expect` then the `sleep` might not be required...? :thinking:

```diff
-- page.has_selector?("table.index tbody tr td")
++ expect(page).to have_selector("table.index tbody tr td")
```

Comment (filipefurtad0) [reply spec/system/admin/order_spec.rb:185]: Hey @Matt-Yorkley , thanks - I'd think the same...

I've tried this locally but get 5 pass out of 10, with:
`expected to find visible css "td" with text "Product #1 - 7326" but there were no matches`

Comment (mkllnk) [reply spec/system/admin/order_spec.rb:185]: `has_selector?` waits as well. There's no difference in flakiness. I'm more wondering if we need that statement if it doesn't actually work.

This kind of expectation has caused flakiness in the past. I suspect a bug in Capybara. From memory, it's the combination of a selector with text. It doesn't recognise the text change on an existing element. Or do we replace the element? I don't know. Hopefully these edge-cases will disappear with removing AngularJS.

**Review by mkllnk — APPROVED** [review]
