### PR TITLE
Admin, create new order: distributor and order cycle are now mandatory on step 1 (aka the set_distribution step)

### LINKED ISSUE #6133: Backoffice orders: Endless spinner and error 500 after skipping OC selector
## Description

Observed while testing #6039

Selecting a distributor and an order cycle from that distributor are the first steps to take, when placing backoffice orders. 

If the selection of the order cycle is skipped and the user clicks "Next" then the "Add Product" field is broken: attempting to search and choose from a product list from, by inserting characters in the, shows an endless spinner, error 500 on the console and  bugsnag is triggered.

See video below.

## Expected Behavior

Selecting an OC should be mandatory

## Actual Behaviour

The user is "allowed" to skip the choosing-OC step, which breaks the product search function: adding the first letters results in an endless spinner in the search field, error 500 in console and bugsnag error report:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5f33a1494da42b00178f81c4?event_id=5f5fa0c5005dfe3cef320000&i=sk&m=nw

## Steps to Reproduce

Log in as admin
1. Click "New Order"
2. Select a distributor; don't select an OC
3. Click "Next"
4. Try to select a product, by inserting the relevant first three letters/characters
5. See endless spinner/error 500/bugnsnag error

## Animated Gif/Screenshot

error_not_selecting-OC

## Workaround

Selecting the OC, just below the "Add a product" section solves this.

## Severity

Proposing bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v3.2.8
* Browser name and version: Firefox 81
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #6133 

_Context_: Admin section, creating a new order

This PR make the _distribution step_ (ie. the one that set both distributor and order_cycle for an order) mandatory when creating a new order in the admin backoffice. 

 - creates a new step, via a new URL: `/distribution`
 - validates order_cycle and distributor presence for an order in a `set_distribution_step` context
 - remove links to others steps on `/distribution` when no distributor or order_cycle are set

#### Can't access next step-s (via `Next` button, or links on the side) until distributor and order cycle are set
Capture d’écran 2023-04-18 à 14 47 20

#### Can access next steps when distributor and order cycle are set
Capture d’écran 2023-04-18 à 14 50 11

#### What should we test?
As an admin, check that when creating a new order, we can't go to next steps until distributor and order_cycle are set for this new order

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/controllers/spree/admin/orders_controller.rb [hunk 1]
```diff
@@ -9,20 +9,31 @@ class OrdersController < Spree::Admin::BaseController
...
+
+      def set_distribution
+        return if order_params.blank?
+
+        on_update
+
+        @order.update(order_params)
+        return unless @order.valid?(:set_distribution_step)
+
+        @order.save
```
Comment (mkllnk) [inline app/controllers/spree/admin/orders_controller.rb:35]: Now I see the additional validations. I think that you want to use `assign_attributes` to prevent saving before running those validations. You can also pass the context to `save`.
```suggestion
        @order.assign_attributes(order_params)
        return unless @order.save(context: :set_distribution_step)
```

This runs the validations only once.

**Review by mkllnk — CHANGES_REQUESTED** [review]
Great work. There's just one suggestion below.

**Review by mkllnk — APPROVED** [review]

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Comment by drummer83** [comment]
Hi @jibees,
Thanks for this one!

I have reproduced the issue before staging first. The situation is a bit different now, because when the issue was created, we still had the product selection first and then the customer selection afterwards. This is the other way round now. Additionally the customer selection doesn't return any results if no distributor is selected on the very first step. 
The good thing is: Both issues are solved by your PR because there is no way to access the next pages without selecting distributor AND order cycle.

If information is missing, one of the following errors will be shown:
image

image

I didn't manage to see any endless spinners of error 500. Excellent!
Merging! :partying_face: 
Thanks!
