### PR TITLE
Fix When user deletes a shipping method existing orders are updated with a random shipping method

### LINKED ISSUE #6029: When user deletes a shipping method existing orders are updated with a random shipping method
## Description

When an enterprise removes shipping method from their Shipping Method list existing orders with this shipping method are changed. It seems the first shipping method available to the enterprise is selected.

This results in:
1) the enterprise manager dispatching products incorrectly (eg. expects customer to collect when the customer asked for delivery) 
2) If there is a difference in cost of the two shipping methods the order total is changed.

Example:
Orders: R852656180 (paid by PayPal) and R282147658 (paid by Stripe) placed with enterprise Sail Cargo SE (ID 201099).
Customer opted for 'UK delivery outside Brighton and Hove B1, B2, B3 postcodes' and paid 10% fee associated with this method at check out.
Hub removed this shipping method
Order and reports display 'Collection from Fiveways office...' which has £0.00 fee.  Orders display as 'credit owing'.

## Expected Behavior

1. Customer places order with a shipping method
democheckout
order confirmation email shows this is what they have paid for
demoemail
which is reflected on the Orders page
demoorderbefore

2. Hub removes the shipping method from their shipping method list.
List at the time order was placed
demobefore
List some time after order placed when hub has removed this shipping option
demoshipnew

3. Order (via 'Orders' -> Edit order and via Reports) should the shipping method as originally selected by the shopper.

## Actual Behaviour

Steps 1 and 2 as Expected Behaviour

3. View Order (Orders - > Edit) or in Reports, order now displaying a different shipping method. As the fee is different the order total is also different.
demoorderafter

Further, thange is not reflected under order adjustments
demoadjustments

## Steps to Reproduce

1. Set up an enterprise with 2 shipping methods.  One has a fee associated with it. 
2. Open an OC. Place an order as a customer and chose shipping method A.
3. Confirm shipping method in order, reports and in customer confirmation email.
4. Remove shipping method A from Enterprise Shipping methods list
5. See that the shipping method has changed in the original order and reports.

## Workaround

Workaround is to recreate the shipping method.

## Severity

s3 - Damaging if not noticed.

## Your Environment

* Version used: 3.2.7
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #6029

## Summary

The original issue:
1. a customer creates an order and selects the shipping method `sm1`
2. the distributor decides to no longer support `sm1`
3. if the distributor accesses the edit order page, the order's selected shipping method will be replaced automatically with the next available shipping method.

source of the problem: `Spree::Shipment#refresh_rates`
Fix:
we'll keep the selected shipping method when `refresh_rates` is called.

Potential issues (not sure if we have to solve it on this PR):
If the distributor hits `Update & Recalculate Fees`
1. Will the selected shipping method be replaced? 
When I tested it, it was not replaced.
2. Suppose that the shipping rate is updated, will the shipping cost be recalculated? 
When I tested it, it was not recalculated. 
3. I notice that the order sorting has changed.
#### What should we test?

- Described on #6029 

#### Release notes

Changelog Category: Technical changes

### CODE REVIEW

**Comment by abdellani** [comment]
The idea is to store a copy of the original `select_shipping_rate` before overwriting the `shipping_rates`  of a `shipment` with the results of  `OrderManagement::Stock::Estimator.new(order).shipping_rates(to_package)`

**Comment by abdellani** [comment]
The two tests fail because the selected shipment method is expected to be removed.
If the solution is validated, I'll fix those tests.
```
./spec/models/spree/shipment_spec.rb:111
./spec/models/spree/shipment_spec.rb:122
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
Hello @abdellani and a Happy New Year! :bouquet: 

I have a question about the existing code: What is the purpose of `#refresh_rates`? From a quick glance, it checks if the existing shipping method is still available and assigns a new one if not. But now we want to preserve the existing method even if it has been deleted. So is there any other functionality we have to preserve? Otherwise I'm wondering if we can get rid of the whole thing.

I probably didn't consider the case of multiple rates per shipping method and that the quantity of items could change. Then we need to refresh the rate, guess. I'm not familiar with this code at the moment.

In those cases, when a better rate is available, would your addition prevent the update? Or do we have only one rate per method?


> If the solution is validated, I'll fix those tests.

Ideally, we would change specs before fixing the code. I know that sometimes we don't know which specs are affected and can change them only afterwards but it would be good to verify your solution with specs before review.

**Comment by abdellani** [comment]
Happy New Year @mkllnk  :)
> I have a question about the existing code: What is the purpose of `#refresh_rates`? From a quick glance, it checks if the existing shipping method is still available and assigns a new one if not. But now we want to preserve the existing method even if it has been deleted. So is there any other functionality we have to preserve? Otherwise I'm wondering if we can get rid of the whole thing.
> 

In my understanding:
1. `refresh_rates` fetches the list of the available shipping methods on the distributor.
2. For every shipping method, it creates one shipping rate in the order

Suppose that the distributor offers two shipping methods "sm1" and "sm2", The problem comes when
1. The user creates an order and selects the shipping method "sm 1"
2. The distributor decides to no longer support "sm 1" 
3. `refresh_rates` will remove `sm 1`  and mark `sm 2` as the selected one.

So, we want to preserve the existing shipping method in the order **only if this method is selected**. If it's not selected, it's ok to lose it.

> I probably didn't consider the case of multiple rates per shipping method and that the quantity of items could change. Then we need to refresh the rate, guess. I'm not familiar with this code at the moment.
> In those cases, when a better rate is available, would your addition prevent the update? Or do we have only one rate per method?
> 

Now that I think of it,  maybe under some conditions, my solution will create a problem.
For example: if the distributor offers one shipping method and the user decided to update his order. The shipment cost will not be updated.
I'll need to recalculate the cost using the shipping method estimator 
https://github.com/openfoodfoundation/openfoodnetwork/blob/f122f4bf50e83e744e6527531a4688393498e4b3/engines/order_management/app/services/order_management/stock/estimator.rb#L60-L62

File: spec/controllers/api/v0/shipments_controller_spec.rb [hunk 1]
```diff
@@ -246,6 +246,7 @@
 
       before do
         order.shipments.first.shipping_methods = [shipping_method1, shipping_method2]
+        order.shipments.each(&:refresh_rates)
```
[the remark this answers is not in the document]
Comment (abdellani) [reply spec/controllers/api/v0/shipments_controller_spec.rb:249]: I think now, we don't need to use
```ruby
        order.shipments.first.shipping_methods = [shipping_method1, shipping_method2]
```
because this will create shipping rates with cost = 0.

Instead, we can use 
```ruby
        order.shipments.each(&:refresh_rates)
``` 
`refresh_rates` will automatically load the shipping methods from the distributor and calculate the cost before creating the `shipping_rates`.

https://github.com/openfoodfoundation/openfoodnetwork/blob/f122f4bf50e83e744e6527531a4688393498e4b3/app/models/spree/shipment.rb#L117-L121
https://github.com/openfoodfoundation/openfoodnetwork/blob/f122f4bf50e83e744e6527531a4688393498e4b3/engines/order_management/app/services/order_management/stock/estimator.rb#L18-L21

File: app/models/spree/shipment.rb [hunk 2]
```diff
@@ -116,7 +116,14 @@ def refresh_rates
...
       # The call to Stock::Estimator below will replace the current shipping_method
       original_shipping_method_id = shipping_method.try(:id)
-      self.shipping_rates = OrderManagement::Stock::Estimator.new(order).shipping_rates(to_package)
+      new_shapping_rates = OrderManagement::Stock::Estimator.new(order).shipping_rates(to_package)
+
+      if selected_shipping_rate.present? && new_shapping_rates.none?{ |shipping_rate|
+        shipping_rate.shipping_method_id == selected_shipping_rate.shipping_method_id
+      }
+        new_shapping_rates << selected_shipping_rate
+      end
```
[the remark this answers is not in the document]
Comment (abdellani) [reply app/models/spree/shipment.rb:125]: I like the suggested syntax, but `new_shapping_rates` will always contain new objects.

how about?
```ruby
new_shapping_rates.map(&:shipping_method_id).exclude?(selected_shipping_rate.shipping_method_id)
```

**Comment by mkllnk** [comment]
Ah, thank you. I read a bit more and the existing code is really hard to read. One complicating design fault is the `selected` field on the shipping rates. A direct association would be easier.

Anyway, I think that your idea is really good. When the selected shipping rate is not available any more, we want to keep it. But that needs to apply only for a selected rate. And the user still needs to be able to select another one. Maybe check if there are test cases for this already or set some up. Then it's easier to check if the code is doing what we think it does.

**Comment by abdellani** [comment]
@mkllnk 
I implemented a system test that reproduces the same context described in the issue.

**Review by mkllnk — COMMENTED** [review]
> I implemented a system test that reproduces the same context described in the issue.

Yes very good. I was wondering though if we need to also cover other cases which are not covered yet.

For example, if we change the amount of a shipping method then the new amount will be applied, correct? Do we want that? Shouldn't the original rate be kept in all cases?

I'm wondering if it would be useful to override the `eql?` method here.

**Comment by abdellani** [comment]
If we want to recalculate the shipment price, we can reuse the estimator.
```ruby
estimator = OrderManagement::Stock::Estimator.new(order)
selected_shipping_rate.update(cost: estimator.calculate_cost(selected_shipping_rate, to_package)
```

**Comment by abdellani** [comment]
* `Shippment#refresh_rates` fetches the available shipping methods from the order's distributor and calculates the shipping rates.
* if the shipment instance is in the state `shipped`,  the method returns without updating the order's amount.
* The order state doesn't matter, the `refresh_rates` method only cares about the shipment instance.

So, we have three parameters to take into account:
a. order shipping status
b. whether the shipping method is supported or not
c. the shipping rate 

Based on those, I suggest testing the following cases:
|order shipping status?|shipping method removed from distributor?|shipping method rate update?|Result (order amount will be updated?)|
|-|-|-|-|
|Not shipped|Yes|Yes|Yes|
|Not shipped|Yes|No|No|
|Not shipped|No|Yes|Yes|
|Not shipped|No|No|No|

**Comment by abdellani** [comment]
@filipefurtad0 
Can you please tell me what you think about the new system tests that I implemented?

At this level, I'm stuck with the `refresh_rate` method.
After the PR, It's returning the expected `shipping_rates`, but the shipment rate amount is always 0.

File: spec/system/admin/order_spec.rb [hunk 3]
```diff
@@ -420,7 +420,7 @@ def new_order_with_distribution(distributor, order_cycle)
 
     describe "viewing the edit page" do
       let!(:shipping_method_for_distributor1) do
-        create(:shipping_method, name: "Normal", distributors: [distributor1])
+        create(:shipping_method_with, :flat_rate, name: "Normal", amount: 12, distributors: [distributor1])
       end
       let!(:order) do
         create(:order_with_taxes, distributor: distributor1, ship_address: create(:address),
```
Comment (filipefurtad0) [inline spec/system/admin/order_spec.rb:426]: I think the issue is that, creating an `order_with_taxes` (which has `completed_order_with_totals` as parent) will create a shipment for it too. So, later on, when... (continuing below)

File: spec/system/admin/order_spec.rb [hunk 4]
```diff
@@ -571,6 +571,51 @@ def new_order_with_distribution(distributor, order_cycle)
...
+        context "when the distributor unsupport a shipping method that's selected in an existing order " do
+          before do
+            distributor1.shipping_methods = [shipping_method_for_distributor1, different_shipping_method_for_distributor1]
+            order.shipments.each(&:refresh_rates)
+            order.select_shipping_method(different_shipping_method_for_distributor1)
+            distributor1.shipping_methods = [shipping_method_for_distributor1]
+          end
+          context "shipment is shipped" do
+            before do
+              order.shipments.first.update_attribute(:state, 'shipped')
```
Comment (filipefurtad0) [inline spec/system/admin/order_spec.rb:584]: ...when the shipment is updated as shipped it is actually that pre-determined shipment which is being considered:
```

=> #<Spree::Shipment:0x00007f5d87308680
 id: 1586,
 tracking: "U10000",
 number: "100",
 cost: 0.0,
 shipped_at: nil,
 order_id: 1920,
 address_id: 10846,
 created_at: Tue, 24 Jan 2023 03:39:18.117486000 AEDT +11:00,
 updated_at: Tue, 24 Jan 2023 03:52:09.860837000 AEDT +11:00,
 state: "shipped",
 stock_location_id: 672,
 included_tax_total: 0.0,
 additional_tax_total: 0.0,
 adjustment_total: 0.0>
```

And this one has indeed  `cost: 0.0`.

I'm not sure what the best way to go around this could be, but perhaps:
- creating a separate shipment and associating it with the intended shipping method, something like:
`let!(:shipment) { create(:shipment_with, :shipping_method, shipping_method: different_shipping_method_for_distributor1) }`

- And then associate this with `order`
- And only after that 'ship' the order

Or:
- create an incomplete order for this purpose (instead of recycling `order`), and then "process" the order like `./spec/system/admin/reports_spec.rb:208`

I did not manage to bring this to work right now, but I hope this comment already helps.

**Comment by abdellani** [comment]
@filipefurtad0 

I debugged the test:
All starts from `select_shipping_method`
https://github.com/openfoodfoundation/openfoodnetwork/blob/1ea730454924a05d414f45dc07747cdad91a2c33/app/models/concerns/order_shipment.rb#L39-L49

`Order#select_shipping_method` works as follow:

-   retrieves `shipment`
-   retrieves the `shipping_rate` among the available `shipping_rates` using the `selected_shipping_method_id` 
-   set the `shipping_rate` as the selected one using `shipment.selected_shipping_rate_id`
https://github.com/openfoodfoundation/openfoodnetwork/blob/1ea730454924a05d414f45dc07747cdad91a2c33/app/models/spree/shipment.rb#L104-L108
-   `save!`  will trigger the `ensure_correct_adjustment`
https://github.com/openfoodfoundation/openfoodnetwork/blob/1ea730454924a05d414f45dc07747cdad91a2c33/app/models/spree/shipment.rb#L261-L267

Now, the shipping method will be updated, as expected, but there's one thing that I don't understand. The cost will not be updated!

```ruby
     fee_adjustment.amount = selected_shipping_rate.cost if fee_adjustment.open? 
```
Why do we authorize updating the shipping methods, and check if the `fee_adjustment.open?` only when it comes to updating the cost?

**Comment by abdellani** [comment]
I fixed the new test by calling 'open' and 'close' on the shipment adjustment.
The only test that's not passing is when the shipping rate of an *unsupported* shipping method is *updated*. 
it's supposed to update the order's shipment cost, but this is not happening for the same reason: `fee_adjustment` is closed.

**Comment by abdellani** [comment]
> Just to be sure, when you mean unsupported, you mean a shipping method which was deleted by the distributor?

Yes

> Please note that this functionality was removed - notice the radio button associated adjustment open/closed:

Do you mean I can remove this condition `if fee_adjustment.open? `? 
and can we remove  `fee_adjustment.state` field from the database?  

> What is the state of shipment, in this case? 

The shipment state is pending, but the problem is related to the state of the adjustment.

**Comment by mkllnk** [comment]
> Do you mean I can remove this condition if fee_adjustment.open?
> and can we remove fee_adjustment.state field from the database?

Maybe. I'm not sure either. It's legacy functionality from Spree and we never used it intentionally but there may be functionality which relies on it without us realizing. As Filipe said, let's try that in a separate PR. It will need thorough testing.

**Comment by mkllnk** [comment]
Just another thought from our discussion in the delivery circle: We don't want to change finalised orders, only incomplete orders. So if we check the order state then we can ignore the adjustment state.

**Comment by abdellani** [comment]
@mkllnk  @filipefurtad0 
1. I worked on the order state machine, and found that all the adjustments are closed when the order is completed.
2. if an adjustment is not in the `open` state, its amount should not be recalculated when `update_adjustment!` is called.
3. there is a flag named `force`, if it's set to `true`, this will force recalculating the amount. 
image
image

In summary, I don't think that this field can be removed from the database without causing a lot of issues.

**Comment by mkllnk** [comment]
Good investigation. So we keep it for now. Do you know how to proceed with this pull request?

**Comment by abdellani** [comment]
when `refresh_rates` is called:

* if the order is completed, it's Ok to replace/update the selected shipping method but the price must remain the same.
* if the selected shipping method is no longer supported by the distributor, the first shipping method will be selected by default.  

https://github.com/openfoodfoundation/openfoodnetwork/blob/889b132069591e0059dac4cdcb222a2770299648/app/models/spree/shipment.rb#L260-L267


https://github.com/openfoodfoundation/openfoodnetwork/blob/889b132069591e0059dac4cdcb222a2770299648/app/models/spree/shipment.rb#L126-L138

https://github.com/openfoodfoundation/openfoodnetwork/blob/889b132069591e0059dac4cdcb222a2770299648/app/models/spree/shipment.rb#L268-L274

This doesn't mean that the price will never be updated after the completion of the order. For example, the `OrderFeesHandler` forces updating the prices on the adjustments 

https://github.com/openfoodfoundation/openfoodnetwork/blob/9ca25df93473e5c9e23d3d58c2005decba50f00f/app/services/order_fees_handler.rb#L46-L56


In other places, we check if the adjustment is finalized first
https://github.com/openfoodfoundation/openfoodnetwork/blob/9ca25df93473e5c9e23d3d58c2005decba50f00f/app/models/spree/order.rb#L711-L716



`refresh_rates` is called from three controllers:

* ShipmentsController#create
* OrdersController#edit
* Orders::CustomerDetailsController#update

**Comment by abdellani** [comment]
There're other places where the `update_adjustments` is called with `force: true`. 

For example on `OrderContents`.  
https://github.com/openfoodfoundation/openfoodnetwork/blob/9ca25df93473e5c9e23d3d58c2005decba50f00f/app/models/spree/order_contents.rb#L76-L82

This means that if any of its methods `update_item`, `update_cart`, `remove`, and `add` is called, the shipping price will be calculated again.

I think that it's better to 
* change the behavior on 'refresh_rates' to keep the selected shipping method, 
* At the same time, I'll avoid touching the part responsible for recalculating the shipping cost.

**Comment by abdellani** [comment]
@filipefurtad0 
Some tests are failing because the sorting of the orders has changed. Is it ok?

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

> Some tests are failing because the sorting of the orders has changed. Is it ok?

The failure seems consistent, but it does not seem related to this PR. If I pull this branch and run the spec locally, it passes.

The test should look like this:

image

But for some reason, in the CI, we're getting:

image

I'll try to debug this. It might be an order related failure. But it's a blocker for merging I guess...

**Comment by abdellani** [comment]
@filipefurtad0 
Sorry, I meant the tests are failing because the returned orders are sorted differently from what's expected.

```ruby
     Failure/Error: expect(page).to have_content(/#{order5.number}.*#{order4.number}.*#{order3.number}.*#{order2.number}/m)
expected to find text matching /R445887202.*R518028774.*R884221646.*R424560362/m in "Logged in as : evonne@hane.name Account Logout Store DASHBOARD PRODUCTS ORDER CYCLES ORDERS REPORTS CONFIGURATION ENTERPRISES CUSTOMERS GROUPS USERS ORDERS BULK ORDER MANAGEMENT SUBSCRIPTIONS Listing Orders NEW ORDER SEARCH DATE RANGE STATUS cart address delivery payment confirmation complete cancelled awaiting return returned resumed INVOICE NUMBER: EMAIL FIRST NAME BEGINS WITH LAST NAME BEGINS WITH ONLY SHOW COMPLETE ORDERS SHIPPING METHOD UPS Ground UPS Ground Pick-up at the farm UPS Ground Signed, sealed, delivered UPS Ground UPS Ground UPS Ground UPS Ground DISTRIBUTORS Enterprise 99 Enterprise 100 Enterprise 101 Enterprise 98 Enterprise 102 ORDER CYCLES Four Three Two Five FILTER RESULTS CLEAR FILTERS No order selected ACTIONS 15 per page 4 Results found. Viewing 1 to 4. DISTRIBUTOR COMPLETED AT NUMBER STATE PAYMENT STATE SHIPMENT STATE EMAIL NAME TOTAL ▲ Enterprise 100 February 15, 2023 R884221646 COMPLETE CREDIT OWED ($-10,000.00) READY joel.gutmann@leannon.biz Winston Mayer $50.00 Enterprise 102 February 15, 2023 R445887202 COMPLETE PAID READY brant_larkin@schroeder.info Ashlee Rolfson $50.00 Enterprise 101 February 15, 2023 R518028774 COMPLETE CREDIT OWED ($-9,980.00) READY christi@braun.info Meaghan Wilkinson $70.00 Enterprise 99 February 13, 2023 R424560362 COMPLETE BALANCE DUE ($40.00) PENDING caryn.wilderman@ledner.name Fermin Morar $90.00 « FIRST PREVIOUS 1 NEXT LAST »"
```
order2.number,order3.number,order4.number,order5.number are on the page content but in a different order.
I was wondering if it's ok to reorder the orders in the expectation.

**Comment by filipefurtad0** [comment]
> I was wondering if it's ok to reorder the orders in the expectation.

Sure, I think it is ok to change the spec according to the new sorting.

I'm just wondering whether it is a consistent behavior as I cannot make the spec fail in my local env. It seems to only fail on the CI, so I was tipping on order-dependent failure. But I'm not sure, bisecting the specs did not help, as they always pass (for me).

So I don't have a clear answer, I don't know what's causing this failure.

**Comment by abdellani** [comment]
Everything is green Yay !! :tada: 
 
I think that the problem is fixed now.
I'm just not sure 100% if this will not create another problem with the recalculation of the order's amount.

File: spec/system/admin/order_spec.rb [hunk 5]
```diff
@@ -571,6 +571,60 @@ def new_order_with_distribution(distributor, order_cycle)
...
+            end
+          end
+          context "shipment is pending" do
+            before do
+              order.shipments.first.update_attribute(:state, 'pending')
+            end
+
+            it "should not replace the selected shipment method" do
+              visit spree.edit_admin_order_path(order)
+              expect(page).to have_content "Shipping: #{different_shipping_method_for_distributor1.name} $15.00"
```
Comment (filipefurtad0) [inline spec/system/admin/order_spec.rb:612]: We're checking the UI, which is great - but maybe we could assert that the order total is not modified?

(we could do `order.reload` first and then assert on the `order.total`, but maybe there is a better way)

In fact, I think this is relevant even for each of the cases introduced in this PR.

Bonus, a tiny bit out of scope: we could add such an assertion for the case in which changing shipping methods is expected to change the order total, namely, under the block `it "can edit shipping method" do`. What do you think?

File: spec/system/admin/order_spec.rb [hunk 6]
```diff
@@ -571,6 +571,60 @@ def new_order_with_distribution(distributor, order_cycle)
 
           expect(page).to have_content "Shipping: #{different_shipping_method_for_distributor1.name}"
         end
```
Comment (filipefurtad0) [inline spec/system/admin/order_spec.rb:573]:
```suggestion

          within "#order-total" do 
            expect(page).to have_content "$175.00"
          end
        end
```

**Comment by mkllnk** [comment]
Moved back to In Dev because changes were requested by Filipe. I will review after those have been addressed. :smile:

File: app/models/spree/shipment.rb [hunk 7]
```diff
@@ -116,7 +116,22 @@ def refresh_rates
 
       # The call to Stock::Estimator below will replace the current shipping_method
       original_shipping_method_id = shipping_method.try(:id)
-      self.shipping_rates = OrderManagement::Stock::Estimator.new(order).shipping_rates(to_package)
+
+      estimator = OrderManagement::Stock::Estimator.new(order)
+      new_shapping_rates = estimator.shipping_rates(to_package)
```
[the remark this answers is not in the document]
Comment (abdellani) [reply app/models/spree/shipment.rb:121]: I used this name when I was reproducing the original issue.
This variable will contain the shipping rates of the shipping methods currently supported by the distributor.
I agree that this name doesn't reflect the content. I'll use `distributor_shipping_rates` instead.

File: spec/system/admin/order_spec.rb [hunk 8]
```diff
@@ -571,6 +571,60 @@ def new_order_with_distribution(distributor, order_cycle)
...
+
+              it "should not update the shipping cost" do
+                visit spree.edit_admin_order_path(order)
+                expect(page).to have_content "Shipping: #{different_shipping_method_for_distributor1.name} $15.00"
+              end
+            end
+          end
+          context "shipment is pending" do
+            before do
+              order.shipments.first.update_attribute(:state, 'pending')
```
[the remark this answers is not in the document]
Comment (abdellani) [reply spec/system/admin/order_spec.rb:607]: When I replaced 
```ruby
              order.shipments.first.update_attribute(:state, 'pending')
```
with 
```
              expect(order.shipments.first.state).to eq 'pending'
```
the test failed, I needed to add the callback `ensure_correct_adjustment` to make sure that costs will be recalculated.

File: spec/system/admin/order_spec.rb (hunk 5 above)
Comment (abdellani) [reply spec/system/admin/order_spec.rb:625]: done : )

File: spec/system/admin/order_spec.rb [hunk 9]
```diff
@@ -571,6 +571,60 @@ def new_order_with_distribution(distributor, order_cycle)
...
+                different_shipping_method_for_distributor1.shipping_rates.first.update!(cost: 16)              
+              end
+
+              it "should not update the shipping cost" do
+                visit spree.edit_admin_order_path(order)
+                expect(page).to have_content "Shipping: #{different_shipping_method_for_distributor1.name} $15.00"
+              end
+            end
+          end
+          context "shipment is pending" do
```
[the remark this answers is not in the document]
Comment (abdellani) [reply spec/system/admin/order_spec.rb:617]: Are you saying that the shipment is created with `state` = `ready`?
I tried to replace the `update` but the test failed.
```ruby
> expect(order.shipments.first.state).to eq('shipped')

     Failure/Error: expect(order.shipments.first.state).to eq('shipped')
     
       expected: "shipped"
            got: "pending"
     
       (compared using ==)
```

File: spec/system/admin/order_spec.rb (hunk 8 above)
[the remark this answers is not in the document]
Comment (filipefurtad0) [reply spec/system/admin/order_spec.rb]: You're correct, thanks for sharing :pray:
I was wrongly checking `order.shipment_state` and not `order.shipments.first.state`
Resolving conversation :+1:

File: spec/system/admin/order_spec.rb (hunk 9 above)
[the remark this answers is not in the document]
Comment (filipefurtad0) [reply spec/system/admin/order_spec.rb:617]: Same as my previous comment, I thought that order.shipment_state would equal the `shipment.state`, but I guess this is not (always?) true...

> Are you saying that the shipment is created with state = ready?

If a payment is captured upon order creation (Stripe SCA / Paypal) then the `order.shipment_state = ready`; but I'm not sure if this is reflected in `shipment.state`.

File: spec/system/admin/order_spec.rb (hunk 5 above)
Comment (filipefurtad0) [reply spec/system/admin/order_spec.rb:625]: Thanks :-)

**Review by filipefurtad0 — APPROVED** [review]
This looks good from the specs, as far as I could gather. I think in the manual testing phase we need a good look at states, and to verify if we keep a consistent behavior when the admin wishes to change the shipping method of a placed (complete, but not shipped) order.

Thanks for all you work here @abdellani!

**Review by mkllnk — APPROVED** [review]
Great. This is looking good. :+1:

File: app/models/spree/shipment.rb [hunk 10]
```diff
@@ -116,7 +116,22 @@ def refresh_rates
...
+             .exclude?(original_shipping_method_id)
+        cost = estimator.__send__(:calculate_cost, shipping_method, to_package)
+        unless cost.nil?
+          original_shipping_rate = shipping_method.shipping_rates.new(cost: cost)
+          self.shipping_rates = distributor_shipping_rates + [original_shipping_rate]
+          self.selected_shipping_rate_id = original_shipping_rate.id
+        end
+      else
+        self.shipping_rates = distributor_shipping_rates
+      end
```
Comment (dacook) [inline app/models/spree/shipment.rb:134]: I noticed a call to a private method with `__send__`. This was a hint for me: I think the purpose of this code is to re-implement `OrderManagement::Stock::Estimator` in a specific way. 

I'm wondering if the Estimator class should be updated. Would this implementation be safe to apply directly in Estimator? I see that it is called from perhaps one other place: `Order#create_proposed_shipments` (though I didn't search extensively). 

Otherwise, perhaps this should be an alternate method next to `Estimator#shipping_rates`. Or at the very least, `calculate_cost` could be promoted to a public method.

**Review by dacook — CHANGES_REQUESTED** [review]
I have to admit I'm not familiar with this part of the system so it's hard to comment.

At a high level, I would have hoped to simply relax a condition somewhere to allow a shipping method to be used, despite being removed from `distributors_shipping_methods`. Maybe that's what you're doing here.

So looking at this implementation, it's calling a private method which I think is a bad idea. Can you re-arrange it?

File: app/models/spree/shipment.rb (hunk 10 above)
Comment (abdellani) [reply app/models/spree/shipment.rb:134]: I didn't want to copy-and-paste the code from the estimator to avoid potential issues in case the logic is updated.
I'll promote `calculate_cost` to a public method.

Comment (dacook) [reply app/models/spree/shipment.rb]: Okay, I'm still concerned that this code belongs in `Estimator`, but let's go ahead like this for now.

**Review by dacook — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @abdellani 

Starting from an order with a given shipping method with a fee:

image

Then, deactivating the shipping method:

image

Is displayed on the reports:

image

So in summary, deactivating a shipping method:

- removes it from the shipping methods list
- removes it from the OC
- keeps it in the orders where it was chosen - clicking update and recalculate fees keeps the fee and the shipping method
- the used shipping method is kept on Orders and Distributors report

This looks great to me.

We should still find out though if we can still edit orders, change shipping methods and update fees (regression testing). I found this to be very robust -> because we now keep it after deleting, let's say we wish to remove that shipping method from an order:

image

After selecting and updating fees, we can see that the amounts are correct:

image

And that the correct shipping fee appears on the invoice - 10 EUR instead of 20 EUR:

image

I can't think of anything else to test, so...
I'd say this is good to go!! :tada: Congrats for your work and patience on this one :clap: :muscle:

File: app/models/spree/shipment.rb (hunk 10 above)
Comment (dacook) [reply app/models/spree/shipment.rb]: I guess we should have moved back to 'In Dev' while under discussion ;)

I think this is still a good idea. Would you be confident to try it in a new PR?

Comment (abdellani) [reply app/models/spree/shipment.rb]: I'll do that in a different PR :)

Comment (filipefurtad0) [reply app/models/spree/shipment.rb]: Sorry, I've missed these new messages - went ahead, tested and merged :grimacing:
