### PR TITLE
[BUU] Optimisation

### LINKED ISSUE #12331: [BUU] [Infinite loader] - Remove Stimulus Reflex from Products Page
In some circumstances, the new bulk edit products screen will fail to load products, leaving an infinite loader, and a poor user wondering if anything was still happening.
- Split from #11752 because these issues have different impacts and will be solved separately

**Action Items:**
Remove SR From:
- [x] Product screen loading, filtering and saving (https://github.com/openfoodfoundation/openfoodnetwork/pull/12328)
- [x] Product delete action (https://github.com/openfoodfoundation/openfoodnetwork/issues/12398)
- [ ] #12551

## Steps to reproduce
This was last replicated on fr_prod, at approx 9:30am AEST: https://github.com/openfoodfoundation/openfoodnetwork/issues/11752#issuecomment-2024144334
Sometimes it works fine, but maybe if the server is busier, it doesn't.

Image

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?

Optimise by pre-loading required columns, with thanks to the Bullet gem which helped identify them.

Who knows, this might have fixed #12331 on its own, but it wouldn't have solved the root cause.

#### What should we test?

Test before and after deployment:

- Open browser devtools
- Visit BUU admin products page twice
- observe load times

#### Dependencies

- It will be a bit easier to measure performance improvements after #12328 is merged

### CODE REVIEW

**Comment by dacook** [comment]
I had previous observed lots of ActiveStorage requests to S3, during bulk products load on servers. I thought it affected both the old and new screens, but now I can only replicate on the old screen. So I guess the new one is already more efficient, yey!
(the new one only loads the :mini image url, while the ImageSerializer loads all of them).

For my own reference, here's an example from the logs:
```
I, [2024-04-10 05:28:00 #20849]  INFO -- :   S3 Storage (962.7ms) Downloaded file from key: public/images/spree/products/18378/original/8rEHJ39Q.jpeg
I, [2024-04-10 05:28:00 #20849]  INFO -- :   S3 Storage (450.0ms) Uploaded file to key: dvydwjrzeu8nou2scf9g9u1r65zo (checksum: o61YqplTjGIXmcSKXKUkFQ==)
I, [2024-04-10 05:28:00 #20849]  INFO -- : [ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 76e5b9b2-1737-4a7a-a30e-2e59b9d49be7) to Sidekiq(default) with arguments: #<GlobalID:0x00007f50062a8868 @uri=#<URI::GID gid://openfoodnetwork/ActiveStorage::Blob/84915>>
I, [2024-04-10 05:28:00 #32528]  INFO -- : [ActiveJob] [ActiveStorage::AnalyzeJob] [76e5b9b2-1737-4a7a-a30e-2e59b9d49be7] Performing ActiveStorage::AnalyzeJob (Job ID: 76e5b9b2-1737-4a7a-a30e-2e59b9d49be7) from Sidekiq(default) enqueued at 2024-04-10T05:28:00Z with arguments: #<GlobalID:0x00007f7c6284ba58 @uri=#<URI::GID gid://openfoodnetwork/ActiveStorage::Blob/84915>>
I, [2024-04-10 05:28:00 #20849]  INFO -- : source=rack-timeout id=0b560759-130e-4c43-8b24-8045ea152434 wait=2ms timeout=359998ms service=6565ms state=completed
```

**Comment by dacook** [comment]
✅ Specs pass, that last one was a flaky spec (`rspec ./spec/system/admin/order_spec.rb:961 `)

**Comment by dacook** [comment]
@rioug if you have time before the end of the day, it would be handy to review so we can proceed this week. (it's a really small one!)

File: app/controllers/admin/products_v3_controller.rb [hunk 1]
```diff
@@ -87,14 +87,16 @@ def ransack_query
...
-        #   :stock_locations,
-        #   :stock_items,
-        #   :variant_overrides
-        # ]
+        :image,
+        :supplier,
+        { variants: [
+          :default_price,
+          :primary_taxon,
+          :product,
```
Comment (rioug) [inline app/controllers/admin/products_v3_controller.rb:96]: Do you need the product here ? isn't the request to load product ?

**Review by rioug — APPROVED** [review]
I had a quick look, I just have a small question, see comment.

I appreciate that you included the temporary spec, but I am wondering if that should be squashed ? 
Anyway it's fine to go ahead like this.

File: app/controllers/admin/products_v3_controller.rb (hunk 1 above)
Comment (dacook) [reply app/controllers/admin/products_v3_controller.rb:96]: Good question. I think I added it because it was suggested by the Bullet gem. But surely Rails is smart enough to avoid needing this, let me see...

Comment (dacook) [reply app/controllers/admin/products_v3_controller.rb:96]: I don't know why, but removing this generates 14 additional queries in my test. (Lucky I didn't squash it so it was easy to test again 😉 )
Rails should be [finding inverse associations automatically](https://github.com/rails/rails/pull/9522#top), and even if I explicitly define `inverse_of`, it still doesn't help:

```
    belongs_to :product, -> { with_deleted }, touch: true, class_name: 'Spree::Product', inverse_of: :variants
```

Part of me wants to dig further to find out the answer, but I'm sure it's not worth it!

**Review by mkllnk — APPROVED** [review]
Nice one!

**Comment by mkllnk** [comment]
> I had previous observed lots of ActiveStorage requests to S3

That's strange. Images variants should be processed right after an image is uploaded and after that it should be stored and not needing to download the images again. Are you observing something different?

**Comment by dacook** [comment]
> That's strange. Images variants should be processed right after an image is uploaded and after that it should be stored and not needing to download the images again. Are you observing something different?

I only observed what I wrote in my comment: when loading the bulk products list, sometimes it spends a lot of time processing images as per those log messages. But not always. Maybe some older products hadn't been processed yet? 🤷

**Comment by mkllnk** [comment]
> Maybe some older products hadn't been processed yet?

Yes, that's one explanation. That problem should disappear automatically in this case.

File: app/controllers/admin/products_v3_controller.rb (hunk 1 above)
Comment (rioug) [reply app/controllers/admin/products_v3_controller.rb:96]: Thanks for looking into it, I am wondering if that could come from calling `variant.product` somewhere in the code. You'd think we shouldn't need that as we are dealing with products but who knows ? :man_shrugging:

**Comment by drummer83** [comment]
Hi @dacook,
Thanks for this improvement!

Here are some loading times I took from the browser dev tools:

| Stage | 1 | 2 | 3 | 4 | 5 | Avg. |
| - | - | - | - | - | - | - |
| Before | 6.24 s | 5.96 s | 5.69 s | 6.14 s | 6.25 s | Average: 6.056 s |
| After | 6.29 s | 5.49 s | 5.08 s | 5.34 s | 5.28 s | Average: 5.496 s |

This calculates to a reduction of loading time of ~ 9 %. Great! :tada:

I noticed authorization failures when editing products (clicking 'Save changes'). But it's in master as well when testing on staging AU. It's working on staging UK, but there I don't know what's currently staged due to https://github.com/openfoodfoundation/openfoodnetwork/issues/12375.

I'll let this one for you to merge or comment what should be done.

Thanks again!

**Comment by dacook** [comment]
Hi Konrad, thanks for testing this out, it's great to have some concrete figures. 
I hoped it would make more of a difference, but every little bit helps!

**Comment by dacook** [comment]
I'll merge this now, it sounds like the staging issue is unrelated.
