### PR TITLE
fix Viewing an invoice with the instance's invoice setting set to alternative model leads to an error 500

### LINKED ISSUE #11050: [Invoices] Viewing an invoice with the instance's invoice setting set to alternative model leads to an error 500 (Bugsnag)
## Description

Follow up of #10532.

Trying to view/download an invoice on an instance with the invoice setting set to alternative model leads to an error 500.
Here is the Bugsnag: https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64883d4eb464420008d0d1ab?filters%5Bevent.since%5D=30d&filters%5Berror.status%5D=open&filters%5Bapp.release_stage%5D=staging
Even if the new invoices are supposed to work for regular invoices only, there should be no error 500.

## Expected Behavior

Existing invoices should be viewable/downloadable independent of the invoice setting.
If the new invoices are available for standard invoices only, then instances with the alternative invoice model still need access to the legacy invoice functionality.

## Actual Behaviour

There is an error 500 if an invoice is downloaded/viewed on an instance with instance setting set to alternative model.

## Steps to Reproduce

1. As super admin set the invoice setting to alternative model.
2. Create an invoice on the invoice page.
3. Try to download/view it.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by abdellani**
…resenter

#### What? Why?

- Closes #11050

#### What should we test?

- described on: #11050

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/models/invoice/data_presenter.rb [hunk 1]
```diff
@@ -68,19 +68,30 @@ def checkout_adjustments(exclude: [], reject_zero_amount: true)
...
       end.sort_by { |tax| tax[:rate_amount] }
     end
 
     def all_tax_adjustments
-      all_eligible_adjustments.select { |a| a.originator_type == 'Spree::TaxRate' }
+      all_eligible_adjustments.select { |a| a.originator.type == 'Spree::TaxRate' }
+    end
+
+    def tax_adjustment_totals
+      all_tax_adjustments.each_with_object(Hash.new(0)) do |adjustment, totals|
```
Comment (rioug) [inline app/models/invoice/data_presenter.rb:86]: Could you use `{}` instead of `Hash.new(0)` like below ? or vice versa, it would be better if they were consistent.

**Review by rioug — COMMENTED** [review]
Nice!. I left a few comments to tidy up the code.

**Review by mkllnk — APPROVED** [review]
Looks good to me.

File: app/models/invoice/data_presenter.rb [hunk 2]
```diff
@@ -49,9 +50,9 @@ def order_completed_at
     end
 
     def checkout_adjustments(exclude: [], reject_zero_amount: true)
-      adjustments = all_eligible_adjustments
+      adjustments = all_eligible_adjustments.map(&:clone)
 
-      adjustments.reject! { |a| a.originator_type == 'Spree::TaxRate' }
+      adjustments.reject! { |a| a.originator.type == 'Spree::TaxRate' }
```
Comment (Matt-Yorkley) [inline app/models/invoice/data_presenter.rb:55]: I think this was right before, it should be `a.originator_type`...

File: app/models/invoice/data_presenter.rb [hunk 3]
```diff
@@ -49,9 +50,9 @@ def order_completed_at
     end
 
     def checkout_adjustments(exclude: [], reject_zero_amount: true)
-      adjustments = all_eligible_adjustments
+      adjustments = all_eligible_adjustments.map(&:clone)
```
Comment (Matt-Yorkley) [inline app/models/invoice/data_presenter.rb:53]: Why was this needed?

File: app/models/invoice/data_presenter.rb [hunk 4]
```diff
@@ -67,19 +68,30 @@ def checkout_adjustments(exclude: [], reject_zero_amount: true)
...
+          amount: Spree::Money.new(tax_amount, currency: currency),
           percentage: number_to_percentage(tax_rate.amount * 100, precision: 1),
           rate_amount: tax_rate.amount,
         }
       end.sort_by { |tax| tax[:rate_amount] }
     end
 
     def all_tax_adjustments
-      all_eligible_adjustments.select { |a| a.originator_type == 'Spree::TaxRate' }
+      all_eligible_adjustments.select { |a| a.originator.type == 'Spree::TaxRate' }
```
Comment (Matt-Yorkley) [inline app/models/invoice/data_presenter.rb:82]: Same here, I'm pretty sure this should be `a.originator_type`...

Comment (Matt-Yorkley) [reply app/models/invoice/data_presenter.rb:82]: Ah wait I see. So it's changing here to serializing copies of all the TaxRate objects along with the data and using those instead of referencing the TaxRate object directly?

**Comment by mkllnk** [comment]
Moving back to In Dev for conflict resolution.

File: app/models/invoice/data_presenter.rb (hunk 3 above)
Comment (abdellani) [reply app/models/invoice/data_presenter.rb:53]:
```ruby
      adjustments = all_eligible_adjustments.map(&:clone)

      adjustments.reject! { |a| a.originator.type == 'Spree::TaxRate' }
```
without `.map(&:clone)`, calling `reject!` on `adjustments` will affect `all_eligible_adjustments` too

File: app/models/invoice/data_presenter.rb (hunk 2 above)
Comment (abdellani) [reply app/models/invoice/data_presenter.rb:55]: the `originators` connected to the `adjustments` are serialized now.
because in some cases, I need to access the originator's amount (when the originator is a tax rate).

File: app/models/invoice/data_presenter.rb (hunk 4 above)
Comment (abdellani) [reply app/models/invoice/data_presenter.rb:82]: instead of including `originator_type` && `originator_id` into the adjustment. I extracted the originators into a separate object that contains: `id`, `type`, and `amount`.

I need the `amount` in the helper `display_checkout_taxes_hash`

File: spec/system/admin/invoice_print_spec.rb
Comment (rioug) [inline spec/system/admin/invoice_print_spec.rb:1]: It would have been better to split the actual code changes, and the cosmetic changes in different commit. It makes it easier to understand what's going on.

**Review by rioug — APPROVED** [review]
Nice one !

**Review by mkllnk — APPROVED** [review]

**Comment by RachL** [comment]
hmmm I'm still facing the error 500 :thinking:

**Comment by abdellani** [comment]
> hmmm I'm still facing the error 500 🤔 I will try another staging server

Thank you @RachL for the feedback.
Can you please share the server name, which I guess is FR staging, and the order number?

**Comment by RachL** [comment]
@abdellani yes, here are some orders example:

https://staging.coopcircuits.fr/admin/orders/R278132225/invoices
https://staging.coopcircuits.fr/admin/orders/R665566751/invoices
https://staging.coopcircuits.fr/admin/orders/R612706835/invoices

**Comment by filipefurtad0** [comment]
Hey,
I've just bumped in this one as well, trying to reproduce another issue. I think the bugsnag is:
https://app.bugsnag.com/open-food-france/coopcircuits/errors/64e0f7532a544a0008c3285b?filters[error.status]=open&filters[event.since]=30d&event_id=64e7ade500bee4e3a3ec0000

Can you access Bugsnag @abdellani ? If not please let me know and I can share the credentials with you, and/or help debug it.

**Comment by abdellani** [comment]
Hi @filipefurtad0 

I made a local copy of the database, I'll use it to debug the issue on my env.

thank you :)

**Comment by filipefurtad0** [comment]
> I made a local copy of the database, I'll use it to debug the issue on my env.

Ok thanks @abdellani - I'll move this one into In Dev, and remove the labels :+1:

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @abdellani,
Thanks for this fix!

Here are some scenarios and results:
- Invoice created AFTER your PR with ALTERNATIVE template: :heavy_check_mark: 
- Invoice created AFTER your PR with STANDARD template: :heavy_check_mark: 
- Invoice created BEFORE your PR --> error 500 when downloading :x: 
  - [Bugsnag for ALTERNATIVE template](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/65281032f806a9000831320e?filters[error.status]=open&filters[event.since]=30d&filters[app.release_stage]=staging)
  - [Bugsnag for STANDARD template](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/65281162ec9ed800081c61ab?filters[error.status]=open&filters[event.since]=30d&filters[app.release_stage]=staging)
  - Editing the order and then creating a new invoice works well. :+1: 

I think the problem I found is not a real one because we don't have invoices created in production yet. Just a few invoices on our staging servers could be broken. We can probably live with that.

Since this is still behind a feature toggle anyway, I will merge.
Pinging @RachL in case you see it differently.

Thanks Mohamed! :pray:
