### PR TITLE
Order cycle creation, fix needless warning and add warning to prevent data loss

### LINKED ISSUE #9874: Order cycle creation: Needless warning and lost data when leaving and saving
## Description

During complex order cycle creation there are warnings when leaving the page without saving the data. However this isn't applied on all steps and sometimes the warning is shown even when no data was changed. Also the 'save' buttons should only be active when data was changed and needs to be saved.

- Leaving step 3 of complex order cycle asks to confirm to leave the page even when no data was changed.
- Leaving step 4 of complex order cycle DOESN’T ask to confirm to leave the page even when data was changed (the change is lost without notice).
- The buttons ‘save’ and ‘save and back to list’ should only be active when data was changed.

## Expected Behavior

- Leaving any step of order cycle creation should NOT warn the user if NO data has been changed.
- Leaving any step of order cycle creation SHOULD warn the user IF data has been changed.
- The buttons ‘save’ and ‘save and back to list’ should only be active if data was changed.

## Actual Behaviour

- Leaving step 3 of complex order cycle asks to confirm to leave the page even when no data was changed.
- Leaving step 4 of complex order cycle DOESN’T ask to confirm to leave the page even when data was changed (the change is lost without notice).
- The buttons ‘save’ and ‘save and back to list’ are always active on step 3 and 4.

## Steps to Reproduce

1. Create an order cycle for a hub (sells = any)
2. Proceed through all steps and save
3. Edit the order cycle
4. Proceed to step 3, don't change anything and the click on step 1, 2 or 4 --> the warning will be shown
5. Proceed to step 4, change data and then click on step 1, 2 or 3 or any other page --> there will be no warning, data will be lost
6. Observe the buttons 'save' and 'save and back to list' while editing an order cycle

## Animated Gif/Screenshot

Peek 2022-10-25 15-45

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

Closes #9874
When editing a complex order cycle, there are warning when leaving a step with unsaved data. However the behaviour is inconsistent on step 3 and 4. This PR add the expected behaviour:
* Leaving step 3 without changing any data doesn't ask to confirm to leave the page
* Leaving step 4 after changing data ask to confirm to leave the page
* On step 3, 'save' and 'save and next' buttons are not active if data hasn't been changed
~~* On step 4, 'save' and 'save and back to list' buttons are only active if data has been changed~~
This is a bit confusing when creating a new order cycle, as you would end up on the last page with no way of saving. I kept the existing behaviour of having 'save' and 'save and back to list' enable

Tech note:
* step 3 bug is an unintended side effect of this PR https://github.com/openfoodfoundation/openfoodnetwork/pull/4452

#### What should we test?

- Visit admin -> Order cycles, and 
-  create an order cycle for a hub, and proceed through all the steps
- Edit the order cycle just created
- Proceed to step 3 and don't change anything :
  - 'save' and 'save and next' buttons are disabled
  
  step_3
  
  - click on step 1,2 or 4 --> no warning shown
- Come back to step 3 and update something :
  - 'save' and 'save and next' buttons are enabled
  - click on step 1,2 or 4 --> Confirmation to leave site will be shown

  step_3_updated

- Proceed to step 4 and don't change anything :
  - 'save' and 'save and back to list' buttons are enable ( current behaviour )

  step_4_no_update

  - click on step 1,2 or 3 --> no warning shown
- Proceed to step 4 and change anything :
  - click on step 1,2 or 3 --> Confirmation to leave site will be shown

  step_4_warning

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — CHANGES_REQUESTED** [review]
You'll need to adjust a couple of specs. Moving to In Dev till then.

**Comment by rioug** [comment]
I am on it, I actually broke something so fix it now

File: app/webpacker/controllers/unsaved_changes_controller.js [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+// - with turbolinks :
+//    <form data-controller="unsaved-changes" data-action="turbolinks:before-visit@window->unsaved-changes#leavingPage" data-unsaved-changes-changed="true">
+//      <input data-action="change->unsaved-changes#formIsChanged">
+//    </form>
+//
+// You can also combine the two actions
+//
+export default class extends Controller {
+  formIsChanged(event) {
+    this.setChanged("true");
```
Comment (mkllnk) [inline app/webpacker/controllers/unsaved_changes_controller.js]: I'm still dreaming of a way of comparing the initial state to the current state to determine this value. It means that changing something back marks the form as clean. I think that there have been some attempts but nobody got it quite right. Or did I forget? My best approach would be take the parameters of the initial form and compare them to what would be submitted now. You don't have to do this now though. Probably best to finish the migration away from AngularJS first.

**Review by mkllnk — APPROVED** [review]
This is looking good to me.

**Comment by dacook** [comment]
> * ~~On step 4, 'save' and 'save and back to list' buttons are only active if data has been changed~~
> This is a bit confusing when creating a new order cycle, as you would end up on the last page with no way of saving. I kept the existing behaviour of having 'save' and 'save and back to list' enable

Hmm, this one is a bit funny, so I jumped into the system to learn more about it. The order cycle record is already saved in step **1**, so technically steps 2, 3, and 4 are optional and don't have to be saved. That's why steps 2 and 3 have all those button options. So technically I would say step 4 should be the same.

But I guess it wouldn't make sense to leave step 4 unsaved (why have an order cycle if you don't have any options to check out?), so maybe we have these buttons to help guide the user through the process. In fact, you could argue that step three is not optional either..

OK I don't think this PR is about changing those buttons though, so I'll ignore that.

File: app/webpacker/controllers/unsaved_changes_controller.js (hunk 1 above)
Comment (dacook) [reply app/webpacker/controllers/unsaved_changes_controller.js]: I was thinking the same thing; surely this can be solved (and solved well) by a plugin. But I think this method is sufficient.

And great documentation!

File: app/views/admin/order_cycles/checkout_options.html.haml [hunk 2]
```diff
@@ -3,7 +3,7 @@
 - content_for :page_title do
   = t :edit_order_cycle
 
-= form_for [main_app, :admin, @order_cycle], html: { class: "order_cycle" } do |f|
+= form_for [main_app, :admin, @order_cycle], html: { class: "order_cycle" , data: { controller: 'unsaved-changes', action: 'beforeunload@window->unsaved-changes#leavingPage', 'unsaved-changes-changed': "false" } } do |f|
```
Comment (dacook) [inline app/views/admin/order_cycles/checkout_options.html.haml:6]: > `, 'unsaved-changes-changed': "false"`

Is it necessary to specify this in the view, or can we just let the controller initialisation set up the default value?

File: spec/javascripts/stimulus/unsaved_changes_controller_test.js [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+        data-unsaved-changes-changed="false"
+      >
+        <input id="test-checkbox" type="checkbox" data-action="change->unsaved-changes#formIsChanged"/>
+        <input id="test-submit" type="submit"/>
+      </form>
+    `
+  })
+
+  describe("#connect", () => {
+    describe("when disable-submit-button is true", () => {
```
Comment (dacook) [inline spec/javascripts/stimulus/unsaved_changes_controller_test.js:28]: I don't see this condition used in the view. It's good to know it works, but perhaps it was unnecessary to specify this initial value if it's never used.

**Review by dacook — CHANGES_REQUESTED** [review]
The code looks good, but while clicking around to understand it, I think I found a bug (see below)

I also have a question about Stimulus controllers. I notice that you're using the `data` method of the form to store controller state. I'm wondering if this is normal practise, or if it can store private instance variables instead? Or are controller classes not instantiated in the way I'm expecting?

**Comment by dacook** [comment]
I think I found a bug:

1. Visit step 4. submit active ✅ . Make a change, and submit is still active ✅ 
   Screen Shot 2023-02-08 at 11 44 52 am
2. Click cancel. Warning appears ✅ 
    Screen Shot 2023-02-08 at 11 45 19 am
3. Click 'cancel' on the dialog to keep the changes. The submit buttons are disabled and I cannot save my changes  ❌ 
    Screen Shot 2023-02-08 at 11 45 28 am
4. Making further changes, I still cannot save:
    Screen Shot 2023-02-08 at 11 45 37 am

File: app/views/admin/order_cycles/checkout_options.html.haml (hunk 2 above)
Comment (rioug) [reply app/views/admin/order_cycles/checkout_options.html.haml:6]: We could let the controller initialise the default value, but having the ability to set it in the view gives you the option to force the warning. 
Now that I think about it :thinking: , maybe it would create a confusing user experience. You could have the situation where a user land on form, doesn't change anything and then get the warning when trying to leave the page. Happy to change that if you think that's an issue.

File: spec/javascripts/stimulus/unsaved_changes_controller_test.js (hunk 3 above)
Comment (rioug) [reply spec/javascripts/stimulus/unsaved_changes_controller_test.js:28]: > On step 4, 'save' and 'save and back to list' buttons are only active if data has been changed

This was the solution I used for the point above, before I decided against it after further testing. I kept it because I thought it might be useful if we were to use the controller in another context.

**Comment by rioug** [comment]
@dacook I didn't manage to reproduce the bug the way you described it. But in step 2:
> Click cancel. Warning appears :white_check_mark:

If I click 'save' or 'save and back to list' instead then I can reproduce it. Looking at it now.

File: app/views/admin/order_cycles/checkout_options.html.haml (hunk 2 above)
Comment (dacook) [reply app/views/admin/order_cycles/checkout_options.html.haml]: I was actually wondering if this snippet could simply be removed in this case, and let the default apply. But I don't think it's necessary to change.

**Comment by dacook** [comment]
Oops sorry I think didn't write the steps exactly right. Glad you figured it out still.

File: app/webpacker/controllers/unsaved_changes_controller.js (hunk 1 above)
Comment (jibees) [reply app/webpacker/controllers/unsaved_changes_controller.js]: I was thinking: 

could it be something that is automatic like (in `connect()` method):
```js
this.element
      .querySelectorAll("input, select, textarea")
      .forEach((input) => {
        input.addEventListener("change", this.formIsChanged.bind(this));
      });
```
This avoid to use `data-action="change->unsaved-changes#formIsChanged"` for each form element. 
If we don't want to enabled that for each form elements, why not using `target` then?

It's not really important, but to me it's more easy to understand and much simpler. 

What do you think?

**Review by jibees — APPROVED** [review]
Nice one, and very clear explanation, thanks a lot!

I just have one small comment, but definitely can go in `Test Ready` like this ;)

File: app/webpacker/controllers/unsaved_changes_controller.js (hunk 1 above)
Comment (rioug) [reply app/webpacker/controllers/unsaved_changes_controller.js]: Yeah I like the idea and it would make it easier to use. I did think about doing something similar over the week-end (you know shower thought ) :smile:  
So if I understand correctly we could do something like this in controller : 

```javascript
static targets = [ "formIsChanged ]

...

this.formIsChangedTargets
  .forEach((input) => {
    input.addEventListener("change", this.formIsChanged.bind(this));
  });
```
and in the html we would have :
```html
<input data-unsaved-changes-target="formIsChanged"  />
```
Maybe it would make it easier to understand, as you'd see in controller directly what triggers the update to `changed`.
I would be in favour of doing what I just described, it would probably set a better precedent that my current solution. 

What do people think ? @mkllnk @dacook @jibees  ?

Comment (mkllnk) [reply app/webpacker/controllers/unsaved_changes_controller.js]: What's the advantage of using targets instead of the simple `connect` method?

I now found where it came up before:

- https://github.com/openfoodfoundation/openfoodnetwork/pull/9807

That PR proposes a custom controller but we can probably make our life easier with this library which was discussed at the time:

- https://github.com/kirillplatonov/dirty-form

Unfortunately, we were not clear in which direction to go and the contributors lost interest. But if we introduce this as the core team then future contributors can use that, too.

Comment (jibees) [reply app/webpacker/controllers/unsaved_changes_controller.js]: @mkllnk 
> What's the advantage of using targets instead of the simple connect method?

What do you mean exactly by _simple connect method_? I'm not sure to understand: you were referencing my code?

@rioug @mkllnk 
Regarding https://github.com/kirillplatonov/dirty-form they use all elements of the form, without any target (nor action):
```
this.fields = [
      ...this.form.elements,
      ...this.form.querySelectorAll('trix-editor')
    ]
```
([source](https://github.com/kirillplatonov/dirty-form/blob/master/src/dirty-form.js#L6))

Comment (rioug) [reply app/webpacker/controllers/unsaved_changes_controller.js]: > What's the advantage of using targets instead of the simple connect method?

Using the targets method (or the current action method) it would allow you to have some form element that would not make the form dirty. But then I am not sure if there is a use case for this really. It's probably something we can deal with if the need arises.

I'll give the library a go, to see if fits our needs.

Comment (mkllnk) [reply app/webpacker/controllers/unsaved_changes_controller.js]: @jibees 
> What do you mean exactly by simple connect method? I'm not sure to understand: you were referencing my code?

Yes, I was referencing your code.

@rioug 

> But then I am not sure if there is a use case for this really.

There may be. But let's start with the simple case and add if needed.

Comment (rioug) [reply app/webpacker/controllers/unsaved_changes_controller.js]: I gave the library a go but  it needs some fixing, for instance it doesn't handle checkbox properly... I got it to work but at this stage It would probably be easier to fix my solution.

Comment (mkllnk) [reply app/webpacker/controllers/unsaved_changes_controller.js]: Cool. Go ahead with your solution. This was just an idea. If we want to use that library, we should probably do that in a separate pull request anyway. Can we fix the library and submit a PR there, too?

Comment (rioug) [reply app/webpacker/controllers/unsaved_changes_controller.js]: We could, although the library hasn't got any test, so I would want to add some before fixing everything. At this point I am not sure it's worth the effort, and we don't know how responsive the maintainer is.
The main advantage I can see is that we could use the library outside stimulus controller.

**Review by dacook — APPROVED** [review]

**Comment by dacook** [comment]
The updates look good, I think this is ready for test!

**Comment by rioug** [comment]
I refactored my solution a bit based on JB's suggestion and the dirty-form library. It should be much easier to use, you just need to drop `data-controller="unsaved-changes" data-action="beforeunload@window->unsaved-changes#leavingPage` on the form tag and it will take care of the rest.
