### PR TITLE
Replaced the default alert and confirm modals in the order page by custom modals

### LINKED ISSUE #8098: Replace default alert by a custom modal when removing last item from an order
## Description

Follow-up from issue #8040.
The default modal has some design and usability issues - it can, for example, be muted, see discussion and testing notes on the issue.

## Expected Behavior

When removing last item from an order a custom modal should be displayed, instead of the default warning. 

## Actual Behaviour

When removing last item from an order the default warning is displayed.

## Steps to Reproduce

As an admin:
1. Edit an order
2. Attempt to remove the last item
3. See the default alert
4. Mute the default alert
5. Click around and notice how the UI appears to be broken - clicking the trash bin does not remove the last item

## Workaround

It is usable, but not very visible and able to be muted.

## Severity

bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.0.2
* Browser name and version: Firefox 90
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by meronokbay**
#### What? Why?

Closes #8098 

This will replace the default alert and confirm modals in the order page by custom modals. In some browsers like firefox, the default modal can be silenced which results in usability issues. Using custom modals fixes that.

### Demo
Peek 2021-09-09 06-40

#### What should we test?

Create an order with multiple items, then go to `/admin/orders` as an admin and click on the order you created. Play around with the items and check how the new modals behave.

#### Release notes

Replaced the default alert and confirm modals in the order page by custom modals

Changelog Category: User facing changes

### CODE REVIEW

File: spec/features/admin/order_spec.rb [hunk 1]
```diff
@@ -144,7 +144,7 @@ def new_order_with_distribution(distributor, order_cycle)
       fill_in(:quantity, with: max_quantity + 1)
       find("a.save-item").click
     end
-    accept_js_alert
+    find("button.confirm").click
```
Comment (mkllnk) [inline spec/features/admin/order_spec.rb:147]: Shouldn't we test for what the user sees? What do you think about this?
```suggestion
    click_button("OK")
```

File: app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb [hunk 2]
```diff
@@ -154,3 +157,20 @@ addVariantFromStockLocation = function() {
   }
   return 1
 }
+
+showAlert = function(message) {
```
Comment (mkllnk) [inline app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb:161]: This is defining the method globally, right?

I'm okay with this for now but we may want to share it with other parts of the application at some point in the future and then it could be good to use a clearer name. Maybe `ofnAlert`? No need to change it now, I think.

File: app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb [hunk 3]
```diff
@@ -154,3 +157,20 @@ addVariantFromStockLocation = function() {
...
+  $('#custom-alert .message').text(message)
+  $('#custom-alert .confirm').click(function(e) {
+    $('#custom-alert').hide()
+  })
```
Comment (mkllnk) [inline app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb:165]: Whenever `showAlert` is called, a new hide-callback is added to this element. That could become a bit inefficient after a while. This callback should probably be added only once, in some initialising code.

File: app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb [hunk 4]
```diff
@@ -154,3 +157,20 @@ addVariantFromStockLocation = function() {
...
+  $('#custom-alert').show()
+}
+
+showConfirm = function(callback) {
+  $('#custom-confirm').data($(event.target).data());
+  $('#custom-confirm').show();
+  $('#custom-confirm button.confirm').click(callback);
+  $('#custom-confirm button.cancel').click((event) => {
+    $('#custom-confirm').hide()
+  });
```
Comment (mkllnk) [inline app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb:175]: Same here. This callback could be added several times.

**Review by mkllnk — APPROVED** [review]
Nice work! And well presented in the pull request. :star: 

I left a few minor comments.

@Matt-Yorkley I'm wondering how this work fits in with our transition away from AngularJS towards Reactive Rails. It's avoiding AngularJS but still using jQuery. And there are new tools coming that could be leveraged for this kind of work.

**Comment by Matt-Yorkley** [comment]
> @Matt-Yorkley I'm wondering how this work fits in with our transition away from AngularJS towards Reactive Rails. It's avoiding AngularJS but still using jQuery. And there are new tools coming that could be leveraged for this kind of work.

As this is a fairly simple bit of show/hide functionality when the user clicks something I would generally recommend doing this kind of thing with StimulusJS (which is already in the stack) going forward. We're in a bit of a grey area in regards to the transition though and haven't started using it in admin pages yet. I think it's okay to go ahead with this PR as is for now :ok_hand:

File: app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb [hunk 5]
```diff
@@ -54,18 +54,21 @@ $(document).ready(function() {
     }
     $('a.save-item').click(handle_save_click);
 
-    handle_delete_click = function(e, confirmed){
-      if (confirmed) {
-        var del = $(this);
-        var shipment_number = del.data('shipment-number');
-        var variant_id = del.data('variant-id');
+    handle_delete_click = function(e){
+      var del = $(this).parent().parent().parent();
```
Comment (andrewpbrett) [inline app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb:58]: Could we find this element in a different way? With this code, if the structure of the HTML changes, this function could break.

**Review by andrewpbrett — COMMENTED** [review]
Thanks @meronokbay! This looks pretty good - it would be nice to address some of the small feedback here, so I'll mark this as In Dev for now and move it to Test Ready when you've had a chance to update it.

File: app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb (hunk 2 above)
Comment (meronokbay) [reply app/assets/javascripts/admin/spree/orders/variant_autocomplete.js.erb]: I kept these methods in the same file because I was getting some errors in the CI when I tried to move them elsewhere even though the code worked fine in the browser.

**Comment by meronokbay** [comment]
I made the requested changes. Let me know what you think.

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @meronokbay,

Thanks for this PR and the detailed notes and demo.

I've checked this scenario again on:

- Ubuntu 20.04 - Chrome 93:

Peek 2021-09-15 15-09

- Ubuntu 20.04 - Firefox 91:

Peek 2021-09-15 15-08

- MacOS Catalina - Safari 13.1

Peek 2021-09-15 15-13

- Windows 10 - Edge 93 -> All good.

Thanks for this improvement - moving to ready to go.
