### PR TITLE
[Spree Upgrade] Fixed updates of order.shipping_method_id and improved order, stock_location and shipment factories

### LINKED ISSUE #2693: [Spree Upgrade] Handle references to order.shipping_method_id
I am not sure yet, but I believe this column should be dropped.

We need to handle all references to it:
- app/services/order_factory.rb
- lib/open_food_network/order_cycle_management_report.rb
- spec/features/consumer/shopping/orders_spec.rb
- spec/models/spree/order_spec.rb
- spec/services/order_factory_spec.rb
- db/migrate/20121005015852_populate_order_default_shipping_method.rb

There are 2 more references in separate issues: #2681 and #2682

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #2693

Moving uses of order.shipping_method_id to order.shipments in models/spree/order_spec and features/consumer/shopping/orders_spec.

Also improved factory order_completed_with_fees. It now completes the checkout workflow without errors which moves a few specs to a new state.

#### What should we test?
Only changing specs. Errors on these specs are now mostly related to the calculations not being the values expected.

#### Dependencies
This PR depends on #2680 and will have to be rebase and merged _after_ it.

### CODE REVIEW

File: spec/factories.rb [hunk 1]
```diff
@@ -384,6 +385,9 @@
       payment_calculator = build(:calculator_per_item, preferred_amount: evaluator.payment_fee)
       payment_method = create(:payment_method, calculator: payment_calculator)
       create(:payment, order: order, amount: order.total, payment_method: payment_method, state: 'checkout')
+
+      # skip the rebuilding of order.shipments from line_items and stock locations (this is enforced in checkout step :address to :delivery)
+      order.stub(:create_proposed_shipments)
```
Comment (sauloperez) [inline spec/factories.rb]: but won't this leave the order in an unexpected state? why do we need to skip it?

**Comment by luisramos0** [comment]
I dont think this issue is blocked. Ill unblock it, let me know if you have blocked it for some particular reason.

File: spec/factories.rb (hunk 1 above)
Comment (luisramos0) [reply spec/factories.rb]: actually, the following method (that we are not skipping) is ensure_available_shipping_rates, and it passes.

**Comment by sigmundpetersen** [comment]
No, just your comment

> Dependencies
>
> This PR depends on #2680 and will have to be rebase and merged after it.

But I guess you have control over the merge order 🙂

**Comment by luisramos0** [comment]
oh, sorry.. I missed my own comment about the dependency :-(

File: spec/factories.rb [hunk 2]
```diff
@@ -616,3 +616,15 @@
...
+  factory :stock_location, class: Spree::StockLocation do
+    # keeps the test stock_location unique
+    initialize_with { Spree::StockLocation.find_or_create_by_name(name)}
+  end
+
+  factory :shipment, class: Spree::Shipment do
+    # keeps test shipments unique per order
+    initialize_with { Spree::Shipment.find_or_create_by_order_id(order.id)}
+  end
+end
```
Comment (sauloperez) [inline spec/factories.rb]: nice!

**Comment by sauloperez** [comment]
Is this ready then? feel free to merge it yourself @luisramos0

**Comment by luisramos0** [comment]
I was waiting for a green check next to your name. I dont think you have "approved" the PR. Anyway, it's merged. Thanks!

**Comment by sauloperez** [comment]
Lol
