### PR TITLE
SplitCheckout: preselect the shipping/payment method if the only one available

### LINKED ISSUE #8827: SplitCheckout: Preselect shipping/payment method if only one is available on the current shop
## Description
When the hub only have one shipping or payment method, preselect it.

## Expected Behavior
Shipping/Payment should be pre-checked if only one is available for the current shop.

## Actual Behaviour
Shipping/Payment method is not pre-checked, even if there is only one.
Capture d’écran 2022-02-02 à 14 11 45

## Steps to Reproduce

1. Add product to card, proceed to checkout
2. With a hub with only one shipping method and one payment method, those two options should be pre-checked in the interface

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #8827

#### What should we test?
 - Add product to card, proceed to checkout
 - With a hub with only one shipping method and/or one payment method, those two options should be pre-checked in the interface
 - Check if more than one, for a guest user none are preselected, and for a connected user, the previous is selected

#### Release notes

SplitCheckout: preselect the shipping/payment method if it's the only one is available

Changelog Category: User facing changes

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]

File: spec/system/consumer/split_checkout_spec.rb [hunk 1]
```diff
@@ -242,6 +261,31 @@
...
+
+        expect(page).to have_checked_field "payment_method_#{payment_method.id}"
+      end
+
+      context "with more than one payment method" do
+        let!(:payment_method2) { create(:payment_method, distributors: [distributor]) }
+
+        before do
+          order.distributor.update! payment_methods: [payment_method, payment_method2]
+        end
```
Comment (mkllnk) [inline spec/system/consumer/split_checkout_spec.rb:278]: You don't need to update the distributor because you assigned the payment method already at creation.

```suggestion
        let!(:payment_method2) { create(:payment_method, distributors: [distributor]) }
```

**Review by mkllnk — APPROVED** [review]
Great specs!

I'll leave it to you to asses my comment below and move to test ready.

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Thanks for this additional improvement. Since the specs you've added cover the existence of methods so nicely :heart:  I thought I'd have a go on testing the hiding/displaying methods instead :+1: 

On shipping methods:

Backoffice only are still displayed in the shopfront
image

But the PR does what's intended if only one method is active:
image

image

On payment methods:

image

image


Found issues:

1) Setting shipping methods as `backoffice only` does not hide them from the checkout. This seems to work for payment methods.

Issue coming up :+1: 

2) having single payment method as "Checkout only" closes the shop

Issue to remove the "Checkout only" possibility - [as discussed here](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1645093482606989) - coming up :+1: 


Merging :rocket:

**Comment by jibees** [comment]
Thanks for pointing me that out, and opening issues. I've never heard about it .. !
