### PR TITLE
Report errors during checkout with Taler to user

### LINKED ISSUE #13906: Error 422 if items goes out of stock before confirming Taler payment
⚠️ **Please use clockify code # 79 Taler when working on this**

## Description

If an item goes out of stock before confirming a payment with Taler, an error 422 is shown to the user.

When using Paypal, a redirection happens, but not

## Expected Behavior

If only one item in the order, take the user back to shop with an error message "The item selected has run out of stock"

If the order contains several products, redirect to the cart, which can highlight the lines that don't have enough stock anymore

## Actual Behaviour
An error 422 shows up when confirming the payment

## Steps to Reproduce

1. Add an item to your cart
2. Checkout with Taler
3. Before confirming Taler payment, change available stock to 0
4. See an error 422

## Animated Gif/Screenshot

Image

## Severity
bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by mkllnk**
⚠️ **Please use clockify code # 79 Taler when working on this**

## What? Why?

- Closes #13906 

Our Taler payment method was not checking stock before finalising a paid order. This lead to ugly error pages. This should now be handled properly.

These code changes adapt the current payment logic slightly. There's a risk of breaking something accidentally. Most payment methods get a payment authorisation first and then take the payment only after the order has been validated again. But with Taler, the final payment confirmation is done by the user asynchronously. When we become aware of the payment completion, we can still validate the order but we have an existing complete payment. We now take that into account when checking out. This path of complete payments before order completion didn't exist before.

## What should we test?

- Check out with Taler.
- Make products out of stock before completing the payment, while the Taler payment page is displayed
- Try to check out again with different products.
- Let an order cycle end before completing the payment.

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/consumer/multilingual_spec.rb
Comment (rioug) [inline spec/system/consumer/multilingual_spec.rb:1]: Did you mean to remove the Multilingual spec as well ? They are not marked as pending as far as I can tell.

Comment (mkllnk) [reply spec/system/consumer/multilingual_spec.rb:1]: Yes, I meant to delete that. I should have done it in a separate commit to explain. The spec was active but it was mainly testing internal JS variables. It wasn't using the proper language selector and I rated it as mostly useless. Sorry to be rough here. I can't remember what triggered me looking at that file. Maybe some flakiness?

Comment (rioug) [reply spec/system/consumer/multilingual_spec.rb:1]: Thanks for clarifying ! happy to remove  unnecessary test, it just didn't match the commit description.

File: spec/system/consumer/multilingual_spec.rb [hunk 1]
```diff
@@ -1,197 +0,0 @@
...
-      it "on the summary step" do
-        visit checkout_step_path(:summary, locale: 'es')
-
-        expect_menu_and_cookie_in_es
-        expect(page).to have_content "Detalles de entrega"
-      end
-    end
-  end
-
-  describe "using the language switcher UI" do
```
Comment (dacook) [inline spec/system/consumer/multilingual_spec.rb:154]: I agree to clear most of this out, and that we generally don't need to test internals. But I think..

- This section "using the language switcher UI" should be tested because it's  part of the UI
- The testing of cookies is intended to ensure that when you continue browsing you continue to get the right language. That's worth having at least one test for. I can see that it's checked in this section so maybe that's enough.

I would also consider the test "can switch language by params" has importance because _URLs are UI_, but I wouldn't bother here.

File: spec/system/consumer/shopping/checkout_stripe_spec.rb [hunk 2]
```diff
@@ -1,224 +0,0 @@
...
-  end
-
-  before do
-    stripe_enable
-    pick_order order
-    add_product_to_cart order, product
-    distributor.shipping_methods << [shipping_with_fee, free_shipping]
-  end
-
-  pending "using Stripe SCA" do
```
Comment (dacook) [inline spec/system/consumer/shopping/checkout_stripe_spec.rb:44]: I just checked what other specs we have, and all I could find was one test for a successful Stripe SCA payment in `spec/system/consumer/checkout/payment_spec.rb`. Given that it's about payments, it worries me that we aren't testing all these other cases.

Of course, we're already not testing those, and wasting time on it. So I agree to discard the content of the tests, but think we should at least keep stubs to document what tests we're missing.

File: spec/system/consumer/multilingual_spec.rb (hunk 1 above)
Comment (mkllnk) [reply spec/system/consumer/multilingual_spec.rb:154]: You are right. There are some useful specs here. I had a closer look and added more detailed commits updating this spec. All that should have gone into a separate PR, I think. But now that I touched it here, I just added it.

File: spec/system/consumer/shopping/checkout_stripe_spec.rb
Comment (rioug) [inline spec/system/consumer/shopping/checkout_stripe_spec.rb:1]: I would have put it under `spec/system/consumer/checkout`, but I see the `paypal` one is under shopping as well so 🤷‍♂️

**Comment by AMEA-LYON** [comment]
Hello, everybody,

The test is running Ok now 🥳 🎉 

But, I have a remark in the payment method page : no error message displayed if backend URL is empty in the provider settings, it should be mandatory as there is an error 500 at checkout if the parameter are missing.

**Comment by mkllnk** [comment]
> no error message displayed if backend URL is empty in the provider settings, it should be mandatory as there is an error 500 at checkout if the parameter are missing.

Ah, thanks. I will see if there's an easy fix for that. I'll do that in a different pull request though. Merging this.
