### PR TITLE
Disable header row bulk_coop report

### LINKED ISSUE #9291: CSV reports: Grey out the option to add summary lines when csv is selected
## Description

No matter if you choose the add summary lines in CSV reports or not - the summary line will not be in the file.

## Expected Behavior

- Add an explanation text that csv files will never have summary rows
- Grey out the option to add summary lines when csv is selected

## Actual Behaviour

The option is there, but the summary lines are never.

## Steps to Reproduce

1. Go to a report which has the option to add a summary line (e.g. Bulk Coop Reports)
2. Activate the checkbox for summary row
3. Create the report in CSV format
4. Look at the created file

## Animated Gif/Screenshot

Peek 2022-06-10 11-47

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by aintluks**
#### What? Why?
CSV reports: Grey out the option to add summary lines when csv is selected
Closes #9291

#### What should we test?

- Visit page `/admin/reports/bulk_coop`
- Select the Generate Report with 'csv'
- You should not be able to select 'summary row' in display field
Captura de tela de 2022-08-16 16-33-32

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by binarygit** [comment]
Hello @aintluks Welcome to OFN :tada: 

I'm not sure why you disabled the `header row` after `CSV` is selected because the goal is to disable the `summary row`. It's mentioned here:  https://github.com/openfoodfoundation/openfoodnetwork/issues/9291#issuecomment-1180449734 I think, maybe you got confused :slightly_smiling_face:

File: app/webpacker/controllers/csv_header_report_controller.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+import { Controller } from "stimulus";
+
+export default class extends Controller {
+  static targets = ["reportType"]
+
+  handleSelectChange() {
+    let displayHeaderRow = document.querySelector("#display_header_row");
```
Comment (binarygit) [inline app/webpacker/controllers/csv_header_report_controller.js:7]: Using `querySelector` to get the element is not recommended with StimulusJs, why don't you use `targets` ?
https://stimulus.hotwired.dev/reference/targets

**Review by binarygit — CHANGES_REQUESTED** [review]

**Comment by aintluks** [comment]
> Hello @aintluks Welcome to OFN tada
> 
> I'm not sure why you disabled the `header row` after `CSV` is selected because the goal is to disable the `summary row`. It's mentioned here: [#9291 (comment)](https://github.com/openfoodfoundation/openfoodnetwork/issues/9291#issuecomment-1180449734) I think, maybe you got confused slightly_smiling_face

Yep, I got confused there.. my bad :p

File: app/webpacker/controllers/csv_select_controller.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
+import { Controller } from "stimulus";
+
+export default class extends Controller {
+  static targets = ["reportType", "checkbox", "label"]
+
+  handleSelectChange() {
+    this.reportTypeTarget.value == "csv" ? this.disableField() : this.enableField()
```
Comment (mkllnk) [inline app/webpacker/controllers/csv_select_controller.js:7]: What do you think about making this more generic? If you supplied the value `"csv"` to the controller then it could work with any input field and disable any other form elements.

A generic controller would need to iterate through all targets and apply an action depending on their type. Checkboxes get checked, labels get a class, all inputs and buttons get disabled. This can be extended if needed.

You don't need to do this here now. It's just an idea to build more generic functionality which can be re-used instead of creating new controllers all the time.

**Review by mkllnk — APPROVED** [review]
Thank you!

**Comment by filipefurtad0** [comment]
Hey @aintluks, 

Thanks for picking this one up :+1: 

After staging the PR it is possible to confirm that the option to select the **summary row** is opted out:

image

This indeed generates CSV files without the summary row:

image

So, this PR changes the behavior for the checkbox for the **summary row**, for all the reports which display this option:

- Bulk Co-Op and sub-reports
- Orders & Fulfillment and sub-reports
- Packing and sub-reports

The behavior for the header row is left untouched.

Looks good to me :+1:
