### PR TITLE
Poll to check when invoice file finished

### LINKED ISSUE #12215: Can not compile invoices pdf
## Description
On French Instance compilation of invoices pdf doesn't work in some cases. The problem doesn't appear when printing from order page.

## Expected Behavior
When required pdf should be generated.

## Actual Behaviour
Only waiting screen is displayed

## Steps to Reproduce
Using Firefox 123.0 (Ubuntu), I ask printing of 2 orders on shop with ID 4523. The screen below stalls for more than 10 minutes without ending.
image

This was tried with at least another shop as super-admin.

The same reports were edited correctly using chromium on the same computer (and with Firefox by another user with another computer).

## Severity
bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?
A fix to ensure we dont' get stuck with an infinite loader when generating invoices.

- Closes #12215

We could continue and remove the reflex, I just didn't get to that yet. If we do, the notification time could be reduced (say 3 seconds) for a more accurate response time.

#### What should we test?
As per issue.

### CODE REVIEW

**Review by mkllnk — COMMENTED** [review]
Nice backup solution.

I tested it locally and it works well. I'll try to write a spec for it as well.

File: spec/system/admin/orders/bulk_actions_spec.rb [hunk 1]
```diff
@@ -287,6 +287,27 @@
...
+            end
+
+            # Don't send anything via web sockets.
+            before do
+              expect_any_instance_of(BulkInvoiceJob)
+                .to receive(:broadcast)
+                .and_return(nil) # do nothing
+            end
+
+            it_behaves_like "can bulk print invoices from 2 orders"
```
Comment (mkllnk) [inline spec/system/admin/orders/bulk_actions_spec.rb:308]: I checked that this fails when commenting out some of the new Javascript code. :heavy_check_mark:

**Review by mkllnk — APPROVED** [review]

**Comment by mkllnk** [comment]
Failing specs are pre-existing. There were unsynchronised pull requests.

**Comment by mkllnk** [comment]
Ideally we would have two reviews and proper testing for this one but I would like to include it in the next release due to it's urgency as S2 bug. The changes seem to be low risk. So I will stage it and merge if everything works.

**Comment by mkllnk** [comment]
Testing on au-staging worked.
