### PR TITLE
Fix variant data inconsistencies

### LINKED ISSUE #4216: Cannot clone order cycle - grumpy cat
## Description

A user in Australia is trying to clone an order cycle. They are getting a grumpy cat (see below). This is the 'old' error message screen that should have been replaced with the snail. So it suggests that we are touching some weird part of the code?

They have now sent a follow up email saying that "After the message with the cat picture. It does show a copy of the order cycle but it only has 73 variants and not the 521 variants  that the Master order cycle contains."

I have asked whether they can think of any other clues, and also for the name of the order cycle.

I have just tried cloning 3719 Master, and replicated. This is what dev tools look like - fails really fast!

## Expected Behavior
OC should be cloned

## Actual Behaviour
Grumpy cat and incomplete OC created

## Steps to Reproduce

1. Go to Aus prod
2. Clone 3719 Master OC, or it seems any OC as Food Connect manager

I have tried in another hub and it seems ok 

## Context
User clones their order cycles to get shops open for the week. This needs to be done in next hour. Working on a workaround but pretty stressful 

## Severity
S1 - cloning order cycles is a critical feature for many users, especially with this many products

### LINKED ISSUE #5234: Problem when changing product unit from item to weight
## Description

I have a user who sees the error "Unit name cannot be blank" when trying to save a product which she has just changed from item to weight.

When I try at super admin, I cannot always reproduce the problem...

HUB ID: 922 

Producers name: GAEC du Serpolet and also on La Ferme le Mont Charvet

## Steps to Reproduce
1. I don't know
2.
3.
4.

## Animated Gif/Screenshot

image

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.9.2
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile): Desktop

### LINKED ISSUE #6368: Switching between Weight and Item unit measures creates corrupt products
## Description

When a user edits a product switching between weight and item unit measures, the change does not correctly save.
This results in corrupted products that cause cloning order cycles to fail. This has been seen intermittently but repeatedly in [#4216](https://github.com/openfoodfoundation/openfoodnetwork/issues/4216)

## Expected Behavior

Users should be able to update their products from items to weights units and back again and not suffer issues across the system due to corrupt product data.

## Actual Behaviour

If a user updates products from items to weights and/or vice versa order cycles containing that product cannot be cloned. The product becomes corrupted.

This is a screen shot of a DB query. All of these products should have been stored as items. Some (though I'm not sure exactly which) were shifted between items and weights.

## Steps to Reproduce

1. Create a product as 'items' unit type
2. Edit to save as 'weight'
3. Switch back to 'item'
4. Now try to clone an OC with this product in. CAT IN YOUR FACE!

## Workaround

I managed to fix this through the UI after I identified the products though it took a few attempts. I changed all products to Items on by one.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #4216
Closes #6368
Closes #5234 

Fixes recurring data inconsistency issue #4216 where a product's variant_unit value is changed from "weight" to "items" and some of the product's variants can be left in an invalid state, which in turn breaks cloning of order cycles (with fatal errors). 

The fix in these cases is to find variants in the OC that have a product with `variant_unit: "weight"` and where the variant's `unit_value` is `nil`, and manually change them in the DB or the console from `nil` to `1`. :see_no_evil: 

#### What should we test?

1. Create a product that has "weight" as it's unit type, and add some variants.
2. Add those variants to an order cycle. 
3. Change the product from "weight" to "items". 
4. Try cloning the order cycle.
5. It should be cloned without exploding, no snails :no_entry_sign: :snail: 

#### Release notes

Fixed a variant weight/items issue leading to OCs that cannot be cloned

Changelog Category: Technical changes

### CODE REVIEW

**Comment by andrewpbrett** [comment]
I updated the specs and the build is now green; it would be really nice to fix this! It might fix the root cause of https://github.com/openfoodfoundation/openfoodnetwork/issues/6527 as well. 

We'll want to have a good think about it to make sure that we're okay changing those tests and that we're not just playing whackamole and going to see another bug pop up because of these changes. I think @sauloperez would be a good person to review since it looks like he wrote some of the original specs.

Sorry about all the force pushing/squashing @Matt-Yorkley

File: app/models/spree/variant.rb [hunk 1]
```diff
@@ -297,5 +298,11 @@ def destruction
       exchange_variants(:reload).destroy_all
       yield
     end
+
+    def ensure_unit_value
+      return unless product&.variant_unit == "items" && unit_value.nil?
+
+      self.unit_value = 1.0
+    end
```
Comment (sauloperez) [inline app/models/spree/variant.rb:306]: I agree this is a quick patch that may solve the issue but it feels like we're pilling up callbacks onto callbacks which make our models slow and hard to reason about. IMO it'd a much maintainable approach to create a `ChangeProductUnit` and explicitly call it from the controller in charge. This way the variant doesn't pay the toll of yet another callback in every single INSERT/UPDATE to DB.

File: app/models/spree/variant.rb [hunk 2]
```diff
@@ -297,5 +298,11 @@ def destruction
       exchange_variants(:reload).destroy_all
       yield
     end
+
+    def ensure_unit_value
+      return unless product&.variant_unit == "items" && unit_value.nil?
+
+      self.unit_value = 1.0
```
Comment (sauloperez) [inline app/models/spree/variant.rb:305]: If the issue is that we rely on `unit_value` even when `product.variant_unit == "items"` we should extend the validation at line 58, right?

File: app/models/spree/variant.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/models/spree/variant.rb:306]: I think the root cause of this is that the `Product` and `Variant` models are not separated very well, and that the UI reinforces this commingling. So if we create a separate service and put the responsibility on the controller in charge, then the messiness spreads out to that controller as well. Then if another controller, say an API controller, is created, we have to ask "does this new controller need to use this service?" rather than just keeping the weirdness limited to these two classes. 

I definitely agree that it looks like a hack upon a hack, but in this specific instance I'd lean toward the callback approach instead of a service.

File: app/models/spree/variant.rb (hunk 2 above)
Comment (andrewpbrett) [reply app/models/spree/variant.rb:305]: I think it's slightly different what we need to do; in the case of that validation, we're saying if you try to save a variant with `weight` or `volume`, **you** must provide the `unit_value` or it'll be invalid. 

Here, we're more saying that if you try to save a variant with `items` and don't provide a `unit_value`, because the UI doesn't really make it clear that you need to, or allow you to, then we're going to set it to be 1.0 for you.

File: app/models/spree/variant.rb (hunk 1 above)
Comment (sauloperez) [reply app/models/spree/variant.rb:306]: I'm not 100% sold on that but it's fair enough :+1:

**Review by sauloperez — APPROVED** [review]

File: app/models/spree/variant.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply app/models/spree/variant.rb:306]: Agreed it's not great, but these problems are piling up all the time. 

We're setting a value on the object during the `before_validation` step, so it's not really an extra strain on the DB in terms of transactions. Eg: we're not triggering additional database updates inside of an `after_save` callback for example, which would be a lot worse...

**Comment by Matt-Yorkley** [comment]
Github won't let me approve this PR as I authored the first bit, but I think we should move this along, we're getting too many errors coming up due to these data inconsistencies and it keeps eating dev time.

**Comment by Matt-Yorkley** [comment]
I'm guessing @andrewpbrett approves, so I'll move this to `test-ready`.

File: app/models/spree/variant.rb (hunk 2 above)
Comment (Matt-Yorkley) [reply app/models/spree/variant.rb:305]: Yeah, and I think in the actual cases that are causing these issues, the user doesn't have a chance to update that field. Like if the product is changed to `items` in the bulk products page, it's not possible to adjust this other field on the variants at the same time.

**Review by andrewpbrett — APPROVED** [review]

**Comment by andrewpbrett** [comment]
@Matt-Yorkley Your guess was correct, I think I hadn't explicitly approved since it felt like I was partially the author... or maybe I just forgot. In any case, Test Ready! 👍

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

This is quite tricky, this one.

I had a look at the related bugs namely the steps to reproduce on #6368 and your advice on what should we test. I tried this:
- Create a product that has "weight" as it's unit type, and add some variants.
- Add those variants to an order cycle.
- Change the product from "weight" to "items"

But somehow managed to clone the OC with no issues. I was only able to reproduce it by following that procedure but starting off as an "Items" product, following these steps.

- First, create an "Items" product: It plays a role, whether one insert a string or a number on the `Value *` field:

i) inserting a string, will now allow to change the product from Item to Weight -> which is issue #5234; This prevents the fail cascade. So we need a integer, to continue break the OC cloning, so

ii) inserting a number on the `Value *` field and
- adding a variant. To observe the bug, this **needs** to be done under `/admin/products/<product>/variants/new`. Now, fill in all the fields with strings - no numbers, except on price and on_hand.

- Changing the product to "Weight" -> At this point, attempting to change from "Items" to "Weight" on the `/products` page leads to error 400 -> which is again #5234; To observe the OC bug, this **needs** to be done under `/admin/products/<product>/variants`. 

- After this, we should have a integer on the "Items" variant and a string on the "weight" variant... Adding these variants to the OC, trying to clone the OC -> Error 422 -> which is issue #4216

I could not observe error 500 around this scenario. I also could not reproduce issue #6527.

All this is the current behaviour. I'll stage your PR and see how it is addressed :+1:

**Comment by filipefurtad0** [comment]
Ok, **after staging this PR** I noticed, that:

- the Value * field is not mandatory any more for "Item" products. This corresponds to the testcase v) above.

If one chooses "Weight", fills everything but `Value *` one gets the expected warning:

image

This would be expected for items as well, right? Or are we making it not mandatory on purpose? In that case, should we remove the `*` symbol?

- I observed issue #6527 or, to be more precise, issue #6608 - I'm not 100% sure they are the same. It triggered this error, and occurs from changing the units from items to weight, and weight to items. However, this only happens, if the edit occurs in the `/products` page - this message is show:

`Saving failed. Save failed due to invalid data:422`

and bugsnag is triggered:
- https://app.bugsnag.com/open-food-france/coopcircuits/errors/5fff08a04cdb1a001788a61f?event_id=5fff0c8f00659893e7760000&i=sk&m=fq

This means, the app behaves differently in the pages `/products` and `/products/<product_name>/edit`
This makes it quite challenging to test, as the possibilities are quite many... We've experienced differences in the past, in related pages, hence this proposal #6650.

This is the culprit variant:

image

As to the PR, it seems to bring improvement, as I was not able to create corrupt variants, and reproduce the three underlying issues above.

But it looks like we might be dealing with this, for all previously created variants, in which this change is attempted. So, I I'm not sure it definitively closes #6527...

This and related issues might need further dev/testing but I feel this probably needs to move on. I'd prefer to have some feedback before merging. What do you think about all this @Matt-Yorkley ?

**Comment by Matt-Yorkley** [comment]
> I was not able to create corrupt variants, and reproduce the three underlying issues above

YAY! :tada: :man_dancing: :partying_face: 

> we might be dealing with this, for all previously created variants

We've been manually fixing them as we go, which has been crazy. If we spot any others we can fix them manually as well (it's not always a simple case that can be blindly handled by a migration), but the big win here is that we won't be creating new ones.

**Comment by filipefurtad0** [comment]
Thanks for feedback!
Its quite an improvement @Matt-Yorkley - I have to say this one was quite challenging to test, as there are so many different paths to product creation x product edition x product deletion... really lot's of possibilities.
But yeah, let's move it to ready to go :+1:
