### PR TITLE
Pi/updating variants bug

### LINKED ISSUE #2602: Product Import: strange validation results
## Description

(Reported in Slack)

Strange results when import products with product import. The validation shows multiple entries for inventories and products at the same time in some cases, and items are listed under the errors section, but have no errors.

## Expected Behavior

Validation should happen without error.

## Actual Behavior

In some cases the results are not as expected.

## Animated Gif/Screenshot

screenshot_from_2018-08-27_14-20-49

## Your Environment

* Version used: Found when testing on UK staging.
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #2602

Fixes some old logic on finding/matching products when updating existing variants that was leading to strange user feedback in the validation step, and improved some related specs.

#### What should we test?

Issue outlined in Slack channel with example large CSV file. Validation should now be working correctly during import.

#### Release notes

Fixed validation issue when updating existing products during product import.

Changelog Category: Fixed

### CODE REVIEW

File: app/models/product_import/entry_validator.rb [hunk 1]
```diff
@@ -124,16 +124,15 @@ def producer_validation(entry)
...
 
-      if match.nil?
+      if products.empty?
         mark_as_invalid(entry, attribute: 'name', error: I18n.t('admin.product_import.model.no_product'))
         return
       end
 
-      match.variants.each do |existing_variant|
-        unit_scale = match.variant_unit_scale
+      products.map(&:variants).flatten.each do |existing_variant|
```
Comment (sauloperez) [inline app/models/product_import/entry_validator.rb]: I feel this can be simpler with [#flat_map](https://apidock.com/ruby/Enumerable/flat_map)

File: app/models/product_import/entry_validator.rb [hunk 2]
```diff
@@ -176,24 +175,20 @@ def tax_and_shipping_validation(entry, type, category, index)
...
-      # If no matching product was found, create a new product
-      if match.nil?
+      if products.empty?
         mark_as_new_product(entry)
         return
       end
 
-      # Otherwise, if a variant exists with matching display_name and unit_value, update it
-      match.variants.each do |existing_variant|
+      products.map(&:variants).flatten.each do |existing_variant|
```
Comment (sauloperez) [inline app/models/product_import/entry_validator.rb]: here as well

File: spec/features/admin/product_import_spec.rb [hunk 3]
```diff
@@ -201,6 +201,44 @@
...
+      attach_file 'file', '/tmp/test.csv'
+      click_button 'Upload'
+
+      import_data
+
+      expect(page).to have_selector '.item-count', text: "2"
+      expect(page).to_not have_selector '.invalid-count'
+      expect(page).to have_selector '.create-count', text: "2"
+      expect(page).to_not have_selector '.update-count'
+      expect(page).to_not have_selector '.update-count'
```
Comment (sauloperez) [inline spec/features/admin/product_import_spec.rb]: duplicate?

File: app/models/product_import/entry_validator.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply app/models/product_import/entry_validator.rb]: Thanks, I didn't know about #flat_map

**Comment by Matt-Yorkley** [comment]
@sauloperez It'd be great for the UK if we could get these little bug fixes into the next release as we will need this on production... :pray:

**Comment by sauloperez** [comment]
Sorry, I forgot about this one.

**Comment by myriamboure** [comment]
Please folks let us know with a comment when you stage something so we receive a notification ;-) I'm not sure how we should test this one as it was for a specific case bugging in the UK. @Matt-Yorkley @lin-d-hop do we know what caused the bug more specifically so we can do a proper testing? I'm happy to test but I don't know what to test exactly... in the issue I don't know what was in the file that was imported...

**Comment by sauloperez** [comment]
Sorry @myriamboure, I thought you go check the test ready column in ZenHub

**Comment by RachL** [comment]
@sauloperez @myriamboure Actually I do go through the zenhub column and I think @sstead is doing that too. So I really just need the label and the assigned tester if there s already one. As we said Myriam that I would ask you when you need to test, I think there is no need for comments. Do you agree ?

**Comment by myriamboure** [comment]
Hum... @RachL I think we discussed and agreed to do both to avoid confusion, that's what we wrote in the process. So I would suggest we try the process we decided and if it doesn't work then we adapt? Cause some devs only put message and no label, some do the other side and some do both so let's try to let people do the same thing and see how it works?

**Comment by RachL** [comment]
@myriamboure as you wish. But so far I've never had an issue with the label. So that's why if it's easier I'm proposing this.

**Comment by luisramos0** [comment]
from slack:
matt-yorkley [1:07 PM]
we've actually tested #2604 in the UK and are happy with it's changes, not sure if that's enough or we want extra testing. what do you think @lin-d-hop ? (edited)

@lin-d-hop ;-)

**Comment by daniellemoorhead** [comment]
>Sorry @myriamboure, I thought you go check the test ready column in ZenHub

One thing that makes finding staged things easier @sauloperez @luisramos0 @Matt-Yorkley @mkllnk is to make sure they're at the top of the test ready column. Yesterday I moved the pr-staged-es up because it was lost further down the list.

Just spoke to @sstead and she doesn't mind with/without a comment. She comes in on her day and looks for staged things on AU and then throughout the day she and Maikel communicate on slack when things are staged/tested.

**Comment by daniellemoorhead** [comment]
>from slack:
>matt-yorkley [1:07 PM]
>we've actually tested #2604 in the UK and are happy with it's changes, not sure if that's enough or we want extra testing. what do you think @lin-d-hop ?

Given this ☝️  I'm moving PR to the Ready to Go column. @lin-d-hop move it back if this isn't the case.

**Comment by mkllnk** [comment]
screenshot from 2018-09-07 15-07-56

**Comment by RachL** [comment]
actually I didn't test it...I was waiting for a confirmation in the slack product import channel to know what to test :( @daniellemoorhead

**Comment by daniellemoorhead** [comment]
Uh oh... looks like I read the comment stream incorrectly 😱 

Not sure what to do now that it's merged... @RachL @Matt-Yorkley suggestions?

**Comment by Matt-Yorkley** [comment]
We were testing this on staging with large and complex inputs to get it right, and we quietly pushed thus branch to UK production about a week ago so we could use it live. It's been used since and is working correctly without any problems.
