### PR TITLE
Fix removing customer tag when using search bar for said tag

### LINKED ISSUE #9553: Removing customer tag fails to save when using search bar for said tag
## Description

We created an integration for an enterprise that allowed new customers to create an account with a specific tag entitling them to a discount. The discount was only intended for first orders, so the tag needed to be removed from customers who had since placed an order. The enterprise had a large customer list so in order to find the required customers, we searched the relevant tag 'CGJUNE22'. This returned the required customers.
However, when clicking the 'x' next to the tag, the customer disappears from the list. The user assumes the tag has been removed successfully and no 'save changes' button is shown. When returning to the customer list though (i.e. by refreshing via loading another enterprise's customer list), the tags persist. This is confusing and frustrating for users.

## Expected Behavior

Searching a customer tag, then deleting that tag via the filtered customer list, should not remove the customer from the list and should allow the user to 'save changes'.

## Actual Behaviour

Searching a customer tag, then deleting that tag removes the customer from the list and does not save the tag change. The customer is still tagged with the tag the user tried to delete.

## Steps to Reproduce

1. Go to customer list of an enterprise with tags (e.g. Deeside Food Hub)
2. Search for the tag (e.g. 'cgjune22')
3. From filtered list of customers, remove the tag from a customer
4. Observe customer disappear from filtered list
5. Change enterprise to a different one/leave page and return to force refresh of customer list
6.  Search the tag again (e.g. 'cgjune22')
7.  Observe that the customer you removed the tag from is still there with the tag present.

## Animated Gif/Screenshot

Kapture 2022-08-10 at 12 26 49

## Workaround

Not searching the tag, instead searching the customer name, or using the browser 'find in page' tool (e.g. CTRL + F/ Command + F) allows tags to be removed and saved. 

## Severity
bug-s4

## Your Environment

* Version used: UK Prod
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #9553 

This fix makes sure removal of tags are added to pending changes, when the customer list is filtered by a specific tag and the use remove said tag from a customer. It results in the customer disappearing from the screen as it doesn't match the current filter any more.

This is where the magic happens on the template : 
https://github.com/openfoodfoundation/openfoodnetwork/blob/6f83d5b3163409fd7e59e9452f541c6655c39537/app/views/admin/customers/index.html.haml#L93-L94

The [objForUpdate](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/assets/javascripts/admin/index_utils/directives/obj_for_update.js.coffee) directive is in charge monitoring change, and queue any changes. The issue here is when you remove the filtered by tag from a customer, the customer is removed from the filtered list, thus removing the `objForUpdate` directive. It result on the changes not being queued. 
To fix this, we listen on the `$destroy` event and queue up change if a tag has been removed.

#### What should we test?

Make sure you have an enterprise with an existing tag, and a the tag to a few customers

- Go to customer list of an enterprise with tags
- Search for the tag 
- From filtered list of customers, remove the tag from a customer
  -> Customer disappear from the filtered list
  -> Save bar with "You have unsaved changes" is displayed
- Click on "Save changes"
   -> it should save changes successfully 
 - Change enterprise to a different one/leave page and return to force refresh of customer list
 - Search the tag again 
  -> the customer you removed the tag from is not in the filtered list

Check the above scenario with removing the tag from multiple customers.
When removing the last customer :
- "No customers found" will be displayed
- The save bar with "You have unsaved changes" is displayed
- Make sure to click on "Save changes" otherwise the customers won't be updated

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/assets/javascripts/admin/index_utils/directives/obj_for_update.js.coffee [hunk 1]
```diff
@@ -11,14 +11,9 @@ angular.module("admin.indexUtils").directive "objForUpdate", (switchClass, pendi
...
-        change =
-          object: scope.object()
-          type: scope.type
-          attr: scope.attr
-          value: if value? then value else ""
-          scope: scope
         scope.pending()
-        pendingChanges.add(scope.object().id, scope.attr, change)
+        value = if value? then value else ""
+        addPendingChange(scope.attr, value)
```
Comment (dacook) [inline app/assets/javascripts/admin/index_utils/directives/obj_for_update.js.coffee:16]: This refactor looks good, though perhaps it could have been a separate commit first.

The only thing is I notice we're updating an argument variable, which is probably not a good idea. We can probably just condense to one line.
I'm not familiar with the coffeescript `?` modifier, but assume it means "truthy", so would this be equivalent?

```suggestion
        addPendingChange(scope.attr, value || "")
```

**Review by dacook — COMMENTED** [review]
Nice work! 

I'm wondering if this can occur for any other cases where a view is filtered by an editable field?
And so I'm thinking it would be helpful to spec it with at least the known case (whether a JS test or full system spec). Would that be possible?

**Review by jibees — APPROVED** [review]
Nice, and congrats, I didn't think about that 👏 

I think it is worth having a system spec as well. What do you think?

**Comment by rioug** [comment]
> I'm wondering if this can occur for any other cases where a view is filtered by an editable field? be possible?

I just tried that and indeed there is the same problem, I'll fix it

File: spec/system/admin/customers_spec.rb [hunk 2]
```diff
@@ -185,6 +186,77 @@
...
       end
 
+      describe "filtering" do
+        before do
+          customer4.update enterprise: managed_distributor1
+        end
+
+        context "when filtering by code" do
+          before do
+            customer4.update code: 12_345
```
Comment (mkllnk) [inline spec/system/admin/customers_spec.rb:196]: I guess that this should have been a string.

**Review by mkllnk — APPROVED** [review]

**Review by jibees — APPROVED** [review]
Thanks! 🙏 ☺️

**Comment by drummer83** [comment]
Hi @rioug,
Thanks for this one! It's a great improvement around tags!

I tested as admin and as super admin user. :heavy_check_mark: 
I have also checked that other pages with search functionality are not affected. :heavy_check_mark: 
I can confirm that the behaviour is as described in your test instructions: :heavy_check_mark: 

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/38034e83-37d8-411c-aba6-4e1fde06aab1

We still have some strange behaviour when editing other fields which had been searched for. 
Example: If you search for a last name and you want to change that exact last name the entry is hidden as soon as you start typing, because it doesn't match the search string anymore. This has been strange before this PR already, so no regression here, just mentioning it.

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/24724826-6337-468f-9448-44651d6a1f4d

I think the best user experience would be if the list was only updated if the search string has changed or if the changes were saved. The list should not be updated if the content of the results is changed.

But again, this is a great improvement and it's ready to merge! :muscle: 
Thanks!
