### PR TITLE
SplitCheckout, Specs: fix errors count when submitting form with errors

### LINKED ISSUE #10327: [Flaky?] `spec/system/consumer/split_checkout_spec.rb:486`
## Description
````
Failure/Error: expect(page).to have_content("can't be blank", count: 3)
       expected to find text "can't be blank" 3 times but found 6 times in ...
spec/system/consumer/split_checkout_spec.rb:492
```

```
Failure/Error: expect(page).to have_content("can't be blank", count: 7)
       expected to find text "can't be blank" 7 times but found 20 times in
spec/system/consumer/split_checkout_spec.rb:544
```

```
rspec ./spec/system/consumer/split_checkout_spec.rb:486
rspec ./spec/system/consumer/split_checkout_spec.rb:533
```

_Context: https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4013706632/jobs/6893763092_

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Since https://github.com/openfoodfoundation/openfoodnetwork/pull/10317 we are displaying the error message also in the flash message. For unknown reason, build didn't fail for that PR, but, as the PR adds some error message, we need to change the spec to reflect that change.

This PR separates error in checkout page itself, and errors in flash message banner.

- Closes #10327 

#### What should we test?
🟢 Green build. 

#### Release notes

Changelog Category: Technical changes
failures_r_spec_example_groups_as_a_consumer_i_want_to_checkout_my_order_as_a_logged_in_user_details_step_not_filling_out_delivery_details_should_display_error_when_fields_are_empty_561

### CODE REVIEW

File: spec/system/consumer/split_checkout_spec.rb [hunk 1]
```diff
@@ -489,7 +489,12 @@
               expect(page).to have_field("Address", with: "")
               expect(page).to have_field("City", with: "")
               expect(page).to have_field("Postcode", with: "")
-              expect(page).to have_content("can't be blank", count: 3)
+              within "checkout" do
+                expect(page).to have_content("can't be blank", count: 3)
+              end
+              within ".flash[type='error']" do
```
Comment (filipefurtad0) [inline spec/system/consumer/split_checkout_spec.rb:495]: As above:

```suggestion
              within ".flash[type='error']" do
                expect(page).to have_content "Saving failed, please update the highlighted fields."
                expect(page).to have_content("can't be blank", count: 3)
              end
```

File: spec/system/consumer/split_checkout_spec.rb [hunk 2]
```diff
@@ -541,7 +546,13 @@
           expect(page).to have_field("Address", with: "")
           expect(page).to have_field("City", with: "")
           expect(page).to have_field("Postcode", with: "")
-          expect(page).to have_content("can't be blank", count: 7)
+          within "checkout" do
```
Comment (filipefurtad0) [inline spec/system/consumer/split_checkout_spec.rb:549]:
```suggestion
          within "checkout" do
            expect(page).to have_field("First Name", with: "")
            expect(page).to have_field("Last Name", with: "")
            expect(page).to have_field("Email", with: "")
            expect(page).to have_content("is invalid")
            expect(page).to have_field("Phone number", with: "")
            expect(page).to have_field("Address", with: "")
            expect(page).to have_field("City", with: "")
            expect(page).to have_field("Postcode", with: "")
            expect(page).to have_content("can't be blank", count: 7)
            expect(page).to have_content("Select a shipping method")
          end
```

File: spec/system/consumer/split_checkout_spec.rb [hunk 3]
```diff
@@ -541,7 +546,13 @@
...
+            expect(page).to have_content("can't be blank", count: 7)
+          end
+          within ".flash[type='error']" do
```
Comment (filipefurtad0) [inline spec/system/consumer/split_checkout_spec.rb:552]:
```suggestion
          within ".flash[type='error']" do
            expect(page).to have_content("Saving failed, please update the highlighted fields")
            expect(page).to have_content("can't be blank", count: 13)
            expect(page).to have_content("is invalid", count: 1)
          end
```

**Review by filipefurtad0 — APPROVED** [review]
Thanks so much for addressing this :pray:
I've left a minor suggestion, for readability.

**Comment by filipefurtad0** [comment]
Looks good! Build green - taking the liberty to merge this one.
Thanks JB.
