### PR TITLE
[inventory] Fix product sorting

### LINKED ISSUE #12670: [Inventory] Products duplicated and not sorted alphabetically
## Description

Users who use the inventory have contacted us because the inventory tool no longer displays Products in alphabetical order. For users with large inventories, this makes using the tool frustrating. This lack of sorting is evident on both the old UI and the new UI. Some products are also duplicated, despite only one product existing (see below). This is especially confusing and makes the inventory unusable, in the words of the user, as the inventory is therefore flooded with duplicates.

## Expected Behavior

When accessing the inventory, products should be sorted alphabetically to make managing the inventory simpler. Each single product should appear in the inventory once.

## Actual Behaviour

There is no sorting applied. Some products are duplicated.

## Steps to Reproduce

1. Go to Inventory
2. Observe that products are not shown in alphabetical order (all enterprises)
3. Observe that some products are duplicated (e.g. product 'Lettuce, Batavia - UK (org)' id=213045, under Cambridge Food Hub id=201177)
Duplicate inventory

4. Any changes made to either duplicate product are replicated on the other duplicate. 
5. Observe in the Products list that only one product exists for 'Lettuce, Batavia - UK (org)'

## Animated Gif/Screenshot

Example of other duplicated products:
Screenshot 2024-07-15 at 11 10 24

## Workaround

Searching for product

## Severity

bug-s3 - Users are finding this frustrating and are confused why the products are now shown in a random order. I have checked other user's inventories and confirmed that the issue is not unique to Cambridge Food Hub for product duplication.

## Your Environment

* Version used: UK prod - lack of sorting and duplication evident in both new and old UI
* Browser name and version: Firefox and Chrome, both up to date.
* Operating System and version (desktop or mobile):

## Possible Fix

Revert to alphabetical sorting of products

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #12670 

The product sorting in the inventory got broken after the product refactor, where the supplier got moved to the variant, this PR re add the sorting. Product are now sorted by producer alphabetically and product alphabetically.

#### What should we test?

* Go to Inventory
* Observe that products are displayed in alphabetical order by producer
* Observe that products are displayed in alphabetical order by product within the same producer

This may help with https://github.com/openfoodfoundation/openfoodnetwork/issues/12679, but it might be easiest to wait and test the replication case given in production.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/queries/product_scope_query_spec.rb [hunk 1]
```diff
@@ -101,11 +101,24 @@
...
+      producer_b = create(:supplier_enterprise, name: "b_name")
+      product_b1 = create(:product, name: "g_name", supplier_id: producer_b.id)
+      product_b2 = create(:product, name: "z_name", supplier_id: producer_b.id)
+      product_b3 = create(:product, name: "a_name", supplier_id: producer_b.id)
+
+      create(:enterprise_relationship, parent: producer_b, child: hub,
+                                       permissions_list: [:create_variant_overrides])
+
+      result = query.products_for_producers
+      expect(result).to eq([product_b3, product_b1, product_b2, product3, product4])
```
Comment (dacook) [inline spec/queries/product_scope_query_spec.rb:120]: At first glance, it's not easy to see if this is correct or not. We could name the variables the same as the record names to make it clearer.

Not that I'm complaining, at least we have a spec now!!

**Review by dacook — APPROVED** [review]
Great, thanks for adding the spec to help protect us in the future 💯

**Comment by filipefurtad0** [comment]
Hey @rioug,

This looks good. Before staging the PR, one can see that both products and variants are not sorted alphabetically; this changes after staging the PR:

image

Merging!
