### PR TITLE
Compile JS before testing caching

### LINKED ISSUE #11010: [Flaky] rspec ./spec/system/consumer/caching/shops_caching_spec.rb:17
### What we should change and why (this is tech debt)

`rspec ./spec/system/consumer/caching/shops_caching_spec.rb:17`

```
Failures:

  1) Shops caching caching enterprises AMS data caches data for all enterprises, with the provided options
     Failure/Error: expect(Rails.cache.exist?(key, options)).to be true
     
       expected true
            got false
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_shops_caching_caching_enterprises_ams_data_caches_data_for_all_enterprises__with_the_provided_options_155.png
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5263043188/jobs/9512817149
https://openfoodnetwork.slack.com/archives/C012LE8LLDS/p1686718490274599?thread_ts=1686601349.929099&cid=C012LE8LLDS

### PR DESCRIPTION
**Pull request by mkllnk**
That avoids flakiness.

#### What? Why?

- Closes #11010 

#### What should we test?

- CI only, let's repeat that a few times.

Tick a box when you re-run the specs on CI so that we see when we had enough:

- [x] One CI run
- [x] Two CI runs
- [x] Three CI runs
- [x] Four CI runs
- [x] Five CI runs
- [x] Six CI runs: some flaky, but not related: /spec/system/consumer/split_checkout_tax_incl_spec.rb:115 [Results](https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5674785840/attempts/6?pr=11284)
- [x] Seven CI runs

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/consumer/caching/shops_caching_spec.rb [hunk 1]
```diff
@@ -14,9 +14,12 @@
   }
 
   describe "caching enterprises AMS data" do
-    xit "caches data for all enterprises, with the provided options" do
-      pending "#11010"
+    it "caches data for all enterprises, with the provided options" do
+      # Trigger lengthy tasks like JS compilation before testing caching:
+      visit shops_path
```
Comment (dacook) [inline spec/system/consumer/caching/shops_caching_spec.rb:19]: Just wondering what this first visit is for?

Comment (mkllnk) [reply spec/system/consumer/caching/shops_caching_spec.rb:19]: Oh, I was hoping that the comment would explain that. During the first visit the JS assets are compiled. So when we get to the second visit, it doesn't take ages to render the page and we can assert on the cache key before it expires.

Comment (dacook) [reply spec/system/consumer/caching/shops_caching_spec.rb:19]: Ohhh, sorry yes that's clearer now. I misunderstood and thought the `Rails.cache.clear` was to clear the JS compilation to make the second call intentionally slower. But I guess that cache clear is relating to the caching test.

**Review by dacook — APPROVED** [review]

**Review by jibees — APPROVED** [review]
Thanks @mkllnk for this deep investigation!

**Comment by jibees** [comment]
Seven CI runs is enough i guess, merging!

**Review by filipefurtad0 — COMMENTED** [review]
Nice idea - thanks @mkllnk!
(ahh - seems I can't approve after merging, which makes sense -> approved! :heavy_check_mark: )
