### PR TITLE
Fix Stripe payment flash rendering issue

### LINKED ISSUE #9048: [Admin][Order] StripeSCA - No user feedback after making Stripe payments in the backoffice
## Description
When a manager makes a Stripe payment in the backoffice with the customer card, there's no feedback about how the payment went except in column "Payment Status" of the payment list. If there are multiple payments, it's not clear what happened to the payment that was just made. The user should see a green banner on top of the page with a success or error message.

(there is some code that is doing this, setting flash[], but the flash is not showing. I think this is due to the fact a redirect is being made.

I think this can be seen anywhere with Stripe configured.

## Expected Behavior
User can see flash message "Payment was successfully made" or "Payment was not successfully made".

## Actual Behaviour
No flash message, the new payment will appear in the list of payments with a payment status.

## Steps to Reproduce
Edit an order and add a stripe payment to it.

## Workaround
Memorize what payments already exist in the order and check what is the new payment in the list after you made the payment, check the payment status of that payment to see what happened to your new payment.

NOTE: most payments will have status COMPLETED or FAILED. Some other status are INVALID and CHECKOUT.
With StripeSCA there's a new case where stripe demands extra auth for the payment (which is not supported in the backoffice). If this happens, the manager is taken to the payments list and the payment status will be PROCESSING... this case will be improved as part of https://github.com/openfoodfoundation/openfoodnetwork/issues/4178

## Possible Fix
We need to make sure the flash message in the code is sent to the browser even with the redirect.

### PR DESCRIPTION
**Pull request by murjax**
#### What? Why?
- Closes #9048 

When creating a Stripe payment from the backoffice, the user should receive feedback in the form of a flash message whether or not the payment was successful. Currently, this does not occur because the frontend forces a redirect to the payments list, completely ignoring the result of the saved payment.

This is what the flash looks like after saving a payment from the backoffice:
Screenshot from 2023-10-27 09-26-04

#### What should we test?
1. Sign in as a customer.
2. Find a shop with Stripe configured to accept payments.
3. Start a new order and complete it.
4. Sign in as an enterprise owner.
5. Visit your enterprise's orders.
6. Click edit on the recent order.
7. This order will probably be marked paid. To add a balance, add another product.
8. Click the payments tab.
9. Click New Payment.
10. Select Stripe for the payment method.
11. Fill in the payment details and click Update.
12. Ensure the payments list/index is rendered with the new payment.
13. Ensure the flash message "Payment has been successfully created!" is rendered.
14. Ensure the current path is `admin/orders/:order_id/payments`.

Other payment methods should also be checked, along with any known payment failure conditions.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by murjax** [comment]
I posed a question a couple weeks ago on the issue regarding the HTML response of the payment create endpoint. Given that we're posting and redirecting from JS, it typically makes sense to have a JSON response and then call the correct endpoint based on the response.

The code in this PR simply renders the HTML response though. The logic is this is the least invasive change and gets us in a more working state. Perhaps architectural cleanup could be a followup to this. I'm also not very familiar with Angular, so it's possible I'm missing something with the current architecture. That said I'm very much open to more feedback and discussion on this.

File: app/controllers/spree/admin/payments_controller.rb [hunk 1]
```diff
@@ -33,20 +33,12 @@ def create
...
+          OrderWorkflow.new(@order).complete! unless @order.completed?
 
-            redirect_to spree.admin_order_payments_path(@order)
-          else
-            OrderWorkflow.new(@order).complete!
-            authorize_stripe_sca_payment
-            @payment.process_offline!
-
-            flash[:success] = Spree.t(:new_order_completed)
-            redirect_to spree.edit_admin_order_url(@order)
```
Comment (murjax) [inline app/controllers/spree/admin/payments_controller.rb:48]: The frontend was redirecting to the index. This change ensures the backend always returns the index in a successful scenario.

File: spec/system/admin/payments_stripe_spec.rb [hunk 2]
```diff
@@ -64,7 +64,6 @@
             fill_in_card_details_in_backoffice
             click_button "Update"
 
-            expect(page).to have_link "StripeSCA"
```
Comment (rioug) [inline spec/system/admin/payments_stripe_spec.rb:67]: Why removing this ?

File: spec/system/admin/payments_stripe_spec.rb [hunk 3]
```diff
@@ -85,7 +84,6 @@
           fill_in_card_details_in_backoffice
           click_button "Update"
 
-          expect(page).to have_link "StripeSCA"
```
Comment (rioug) [inline spec/system/admin/payments_stripe_spec.rb:88]: Again, why removing this ?

**Review by rioug — COMMENTED** [review]
Looks good, but I am a bit confused why some of the test have been changed for no apparent reason. See my comments.

File: app/controllers/spree/admin/payments_controller.rb (hunk 1 above)
Comment (dacook) [reply app/controllers/spree/admin/payments_controller.rb:48]: Hmm, so this "new order completed" code path was essentially dead code? Assuming this was the only form that submits here, I guess it hasn't been used in at least a few years. 
In any case, we certainly don't seem to have specs covering it. 


Therefore can you please also remove the now-unused [translation key](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/config/locales/en.yml#L3784)?

File: app/assets/javascripts/admin/payments/services/payment.js.coffee [hunk 4]
```diff
@@ -42,8 +42,9 @@ angular.module('admin.payments').factory 'Payment', (AdminStripeElements, curren
 
     submit: =>
       munged = @preprocess()
-      PaymentResource.create({order_id: munged.order_id}, munged, (response, headers, status)=>
-        $window.location.pathname = "/admin/orders/" + munged.order_id + "/payments"
+      PaymentResource.create({order_id: munged.order_id}, munged, (response, headers, status) ->
+        document.body.innerHTML = Object.values(response).join('')
+        $window.history.pushState({}, '', "/admin/orders/" + munged.order_id + "/payments")
```
Comment (dacook) [inline app/assets/javascripts/admin/payments/services/payment.js.coffee:47]: I wish I knew enough about angular to suggest how we could update it to use a standard form submission, instead of having to try and simulate it here.

But oh well, I can see how this would work, thanks for fixing this!

**Review by dacook — CHANGES_REQUESTED** [review]
Thanks for looking into this Ryan, and for your patience with an unanswered question! 

I'm also unsure about how this all works, so appreciate your contribution. I just have a suggestion to cleanup further, and will comment on the issue about removing this message.

File: spec/system/admin/payments_stripe_spec.rb (hunk 2 above)
Comment (murjax) [reply spec/system/admin/payments_stripe_spec.rb:67]: I thought this was redirecting to the edit page without JS. I misread this. When I changed the JS code it started rendering the new payment page on error, where before it redirected to the payment list. I'll change the controller to always render the payment list.

File: app/assets/javascripts/admin/payments/services/payment.js.coffee (hunk 4 above)
Comment (murjax) [reply app/assets/javascripts/admin/payments/services/payment.js.coffee:47]: Might be worth rewriting this area at some point to simplify this. Standard form submission would be better, but this doesn't hurt for now.

File: app/controllers/spree/admin/payments_controller.rb [hunk 5]
```diff
@@ -33,23 +33,15 @@ def create
...
-          end
+          authorize_stripe_sca_payment
+          @payment.process_offline!
+          flash[:success] = flash_message_for(@payment, :successfully_created)
+          redirect_to spree.admin_order_payments_path(@order)
         rescue Spree::Core::GatewayError => e
           flash[:error] = e.message.to_s
-          redirect_to spree.new_admin_order_payment_path(@order)
+          redirect_to spree.admin_order_payments_path(@order)
```
[the remark this answers is not in the document]
Comment (dacook) [reply app/controllers/spree/admin/payments_controller.rb:44]: Great, that makes sense to me. I note that payment failures are mentioned in the manual testing notes too 👍

File: config/locales/ar.yml [hunk 6]
```diff
@@ -3590,7 +3590,6 @@ ar:
     gateway_error: "عملية الدفع فشلت"
     more: "أكثر"
     new_adjustment: "تعديل جديد"
-    new_order_completed: "طلب جديد مكتمل"
```
Comment (dacook) [inline config/locales/ar.yml:3593]: Thanks for cleaning this up. FYI all locale files except default `en.yml` are managed with an external tool ([Transifex](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-(i18n))), so you only need to update `en.yml`. But I think it's fine to remove keys in this case 👍

**Review by dacook — APPROVED** [review]
Great, thanks for following up!

As an aside, we generally prefer not to update commits with new changes after a PR has been reviewed, so that we can more easily see what's changed since. Rather, you can add a new commit(s) to the branch. But it's fine this time!

**Review by rioug — APPROVED** [review]
Looks good now ! thanks for your help :pray:

**Comment by filipefurtad0** [comment]
Hey @murjax ,

Nice - thanks for this improvement. I've tried some scenarios around Stripe / Cash (Paypal is not implemented in backoffice payments):

1) Stripe - not requiring customer authorization (card x-4242):

We get a green banner here - this is great, as the payment is immediately created and captured.

image

The string is translatable:
image


2) Stripe - requiring customer authorization (card x-3184):

We get a red banner here, indicating an action is required - this is great, as the payment and its capture occur asynchronously.

image

This string is also translatable:
image


3) Cash / Check

image

Awesome :rocket: 
Merging!

____ 
Noting an improvement suggestion, not related to this PR:

If a card requiring authorization but with insufficient funds is used in the BO, then, after authorizing the user will not see any message indicating the reason of payment failure. We just see the not paid notice (customer) and the failed payment state (hub):

image

This is hardly a papercut so, maybe leaving this one for now.

**Comment by filipefurtad0** [comment]
I think this issue introduced a minor regression:

with the flash message we get the `boolClass = '[object Boolean]',` and its value from `vendor/assets/javascripts/lodash.underscore.js` displayed as well:

image

This can actually be seen in the [pics above](https://github.com/openfoodfoundation/openfoodnetwork/pull/11730#issuecomment-1816252292) but I recall testing in a small screen and did not notice this before.

Pinging you @murjax - in case this is an easy fix and you feel you have room for this improvement :pray:
