### PR TITLE
Fix #6964: don't try to complete a failed payment

### LINKED ISSUE #6964: Snail when failing Stripe SCA-Payments
## Description

In staging, paying with a 3D-auth card requires an authentication step and clicking "Fail Authentication" shows us the snail, triggering bugsnag:

https://app.bugsnag.com/open-food-france/coopcircuits/errors/6038dea811072c0018798902?event_id=6038dea80072dd55a5d70000&i=sk&m=nw

Is this only visible on a staging environment or to customers as well in production, each time a payment is not authorized by a bank?

## Expected Behavior

Payment should fail with no snail.

## Actual Behaviour

Payment fails, but snail is visible.

## Steps to Reproduce

1. Create any payment which requires 3D-auth.
2. When prompted, click "Fail Payment"
3. See the snail.
4. Refreshing the page should allow you to proceed as usual.

## Animated Gif/Screenshot

Peek 2021-02-26 16-04

## Workaround

Refresh the page.

## Severity

Assuming it is only visible in staging:
bug-s5?

## Your Environment

* Version used: v.3.5.10
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #6964 

Here we only complete a payment if it's in a state where it can be completed, and list those states explicitly

#### What should we test?

Choosing not to authorize an SCA payment should not result in a snail. 

This might be pretty difficult to write an automated test for since we're testing what happens when the customer interacts with the Stripe website. 

#### Release notes

I don't think this is happening in production

Changelog Category: Technical changes

### CODE REVIEW

**Comment by sauloperez** [comment]
> This might be pretty difficult to write an automated test for since we're testing what happens when the customer interacts with the Stripe website.

but we do know the exact Stripe request we receive when that happens, don't we? We would need to stub that out and we'd be reproducing the same scenario.

File: app/services/process_payment_intent.rb [hunk 1]
```diff
@@ -20,7 +20,7 @@ def call!
 
     last_payment.update_attribute(:cvv_response_message, nil)
     OrderWorkflow.new(@order).next
-    last_payment.complete! if !last_payment.completed?
+    last_payment.complete! if %w('pending processing').include?(last_payment.state)
```
Comment (sauloperez) [inline app/services/process_payment_intent.rb:23]: I would personally make the effort to find an abstract name for this logic so that 1) we don't mix levels of abstraction 2) we make it easier for the next dev to understand why `pending` and `processing` states and not others.

**Review by sauloperez — CHANGES_REQUESTED** [review]
We should test this new behavior.

EDIT nice, the test is failing

File: app/services/process_payment_intent.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/services/process_payment_intent.rb]: Good catch, I'm not sure I didn't just use the `can_complete?` method in the first place.

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

thanks for addressing this.

**Before this PR** we had the following scenario:

i) placing an order in the BO (admin)
ii) using the email received per email to proceed with authentication (customer)
iii) clicking "Fail Authentication" leads to the bug as below (**left**, admin; **right**, customer):

image

**After this PR**:
iii) does not trigger a snail anymore, and looks like this:

image

Also, please not that I was **not able to reproduce** bug #6683 after this PR :tada: 
Neither by refusing authentication nor by using an invalid card like `4000008260003178`.

image

We can see, that the (3 eur) transaction fee do not pile up, despite the failed payment attempts:

image

The fact that the order is still in the balance due state relates to bug #5574.

It would be good to have a spec covering us from the re-occurrence of #6683. Should I open a tech-debt for this?

Awesome, let's get this merged :tada:

**Comment by sauloperez** [comment]
> It would be good to have a spec covering us from the re-occurrence of #6683. Should I open a tech-debt for this?

Yes, I think it's worth exploring why no test failed after we introduced this regression.
