### PR TITLE
[Spree Upgrade] Fix redirection on admin products specs

### LINKED ISSUE #3031: [Spree Upgrade][BackOffice] Fix redirection issue in admin products controller (2 broken tests)
Fix spec/controllers/spree/admin/products_controller_spec.rb

```
 18) Spree::Admin::ProductsController creating a new product redirects to products when the user hits 'create'
      Failure/Error: response.should redirect_to spree.admin_products_path
        Expected response to be a <:redirect>, but was <200>
      # ./spec/controllers/spree/admin/products_controller_spec.rb:96:in `block (3 levels) in <top (required)>'

  19) Spree::Admin::ProductsController creating a new product redirects to new when the user hits 'add_another'
      Failure/Error: response.should redirect_to "/admin/products/new"
        Expected response to be a <:redirect>, but was <200>
      # ./spec/controllers/spree/admin/products_controller_spec.rb:116:in `block (3 levels) in <top (required)>'
```

This should be a simple fix after #2982 is fixed.

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Closes #3031 

In Spree v2.0 the product attributes being sent were no longer valid. Providing a shipping category and setting a stock location on the DB so that a stock item can be created fixes them.

Remember `Variant#create_stock_item`, which is defined as an `after_create` callback, relies on `StockLocation` to create the item.

#### What should we test?

This two tests should get green.

### CODE REVIEW

File: spec/controllers/spree/admin/products_controller_spec.rb [hunk 1]
```diff
@@ -74,45 +74,30 @@
   end
 
   context "creating a new product" do
-    before { login_as_admin }
+    let(:supplier) { create(:supplier_enterprise) }
+    let(:taxon) { create(:taxon) }
+    let(:shipping_category) { create(:shipping_category) }
+
+    let(:product_attrs) {
+      attributes_for(:product).merge(
```
Comment (sauloperez) [inline spec/controllers/spree/admin/products_controller_spec.rb]: `attributes_for` is one of FactoryBot's creation methods.

File: app/models/spree/product_decorator.rb [hunk 2]
```diff
@@ -275,19 +275,23 @@ def ensure_standard_variant
...
-    rescue ActiveRecord::RecordInvalid
-      master.errors.each do |att, error|
-        self.errors.add(att, error)
-      end
-      raise
+  rescue ActiveRecord::RecordInvalid
+    master.errors.each do |att, error|
+      self.errors.add(att, error)
     end
+    raise
```
Comment (luisramos0) [inline app/models/spree/product_decorator.rb]: welcome to spree v3 where this is done: https://github.com/spree/spree/commit/fe6369f9d289d7d69b0970b576d77f41a1eb7061

File: spec/controllers/spree/admin/products_controller_spec.rb (hunk 1 above)
Comment (luisramos0) [reply spec/controllers/spree/admin/products_controller_spec.rb]: nice!!! you can use a factory to generate a hash!

Comment (sauloperez) [reply spec/controllers/spree/admin/products_controller_spec.rb]: Yep, perfect fit for creation controller specs IMO.
