### PR TITLE
2696,2788 [Spree Upgrade] Fix use of shipping method ID for subscriptions

### LINKED ISSUE #2696: [Spree Upgrade] Fix subscriptions.shipping_method_id (13 broken specs)
Subscriptions and spree 2 shipping_methods will need to work together.
There's a column subscriptions.shipping_method_id that, I believe, is used to create orders in a subscription. We need to verify how this process works with the new spree 2 way of creating shipments from shipping methods.

Files referencing shipping_method_id:
          - app/serializers/api/admin/subscription_serializer.rb (this used to be a separate issue #2732 that can be reopened if appropriate)
          - app/models/proxy_order.rb
          - app/services/order_syncer.rb
          - app/assets/javascripts/admin/subscriptions/services/subscription_functions.js.coffee
          - app/views/admin/subscriptions/_details.html.haml
          - app/views/admin/subscriptions/_table.html.haml
          - spec/controllers/admin/subscriptions_controller_spec.rb
          - spec/services/subscription_form_spec.rb
          - spec/services/order_syncer_spec.rb
          - spec/features/admin/subscriptions_spec.rb
          - spec/controllers/admin/proxy_orders_controller_spec.rb
          - spec/javascripts/unit/admin/subscriptions/services/subscription_functions_spec.js.coffee

### PR DESCRIPTION
**Pull request by kristinalim**
Fix use of shipping method ID for subscriptions.

#### What? Why?

- Closes #2696
- Relates to #2788 (does not close issue)

The shipping method in Spree 2.0 is not associated directly to orders, but through shipment shipping rates.

Before Spree 2, `OrderFactory` keeps subscription orders in cart state but already sets associations and creates associated records (like payments). But in Spree 2, transitioning an order to "delivery" state removes and regenerates shipments. Considering above, this means that the selected shipping method could be forgotten.

To work around this, the code that regenerates shipping rates for a shipment has been updated to remember the previously selected shipping method first and select it again after creating the new shipping rates.

#### What should we test?

Not worth testing as there are still some broken functionalities. But some unit and feature tests have been uncommented and now pass.

### CODE REVIEW

File: app/services/order_syncer.rb [hunk 1]
```diff
@@ -66,12 +66,16 @@ def update_payment_for(order)
...
+      shipment = Spree::Shipment.find(shipment.id)
+
+      select_shipping_method_for_shipment(shipment, shipping_method)
       order.update_attribute(:shipping_method_id, shipping_method_id)
     else
-      unless order.shipments.with_state('pending').where(shipping_method_id: shipping_method_id).any?
+      unless pending_shipment_using_shipping_method(order, shipping_method_id).present?
         order_update_issues.add(order, I18n.t('admin.shipping_method'))
       end
     end
```
Comment (luisramos0) [inline app/services/order_syncer.rb]: see order_shipment.rb, in ofn v2 we have one very useful rule (it makes everything much easier): one order can only have one shipment, there will never be 2 shipments in an order. So you can use order.shipment.

also, spree::shipment.selected_shipping_rate is kept to single selection in spree::shipment.selected_shipping_rate_id=
so you can always use order.shipment.selected_shipping_rate

also, you can simply use **order_shipment.shipping_method** that redirects to spree::shipment.shipping_method that redirects to spree::shipment.selected_shipping_rate :-)

I think these facts will help simplify this code, right?

File: app/services/order_syncer.rb [hunk 2]
```diff
@@ -106,4 +110,22 @@ def force_ship_address_required?(order)
       order.ship_address[attr] == distributor_address[attr]
     end
   end
+
+  def select_shipping_method_for_shipment(shipment, shipping_method)
+    shipping_rate = find_or_create_shipping_rate_for_shipping_method(shipment, shipping_method)
+    shipment.update_attributes(selected_shipping_rate_id: shipping_rate.id)
```
Comment (luisramos0) [inline app/services/order_syncer.rb]: should be shipment.selected_shipping_rate_id=(shipping_rate.id)

File: app/services/order_syncer.rb [hunk 3]
```diff
@@ -106,4 +110,22 @@ def force_ship_address_required?(order)
...
+  end
+
+  def find_or_create_shipping_rate_for_shipping_method(shipment, shipping_method)
+    shipping_rate = shipment.shipping_rates.where(shipping_method_id: shipping_method.id).last
```
Comment (luisramos0) [inline app/services/order_syncer.rb]: as in order_shipment.select_shipping_method you can do:
shipping_rate = shipment.shipping_rates.find_by_shipping_method_id(shipping_method_id)

File: app/services/order_syncer.rb [hunk 4]
```diff
@@ -66,12 +66,16 @@ def update_payment_for(order)
   end
 
   def update_shipment_for(order)
-    shipment = order.shipments.with_state('pending').where(shipping_method_id: shipping_method_id_was).last
+    shipment = pending_shipment_using_shipping_method(order, shipping_method_id_was)
+
     if shipment
```
Comment (luisramos0) [inline app/services/order_syncer.rb]: maybe this can simply be
`if order.shipment.shipping_method == shipping_method_id_was?`

File: spec/services/order_syncer_spec.rb [hunk 5]
```diff
@@ -34,27 +34,31 @@
...
 
         before do
           # Updating the shipping method on a shipment updates the shipping method on the order,
           # and vice-versa via logic in Spree's shipments controller. So updating both here mimics that
           # behaviour.
-          order.shipments.first.update_attributes(shipping_method_id: changed_shipping_method.id)
-          order.update_attributes(shipping_method_id: changed_shipping_method.id)
+          shipment = order.shipments.first
+          shipping_rate = shipment.shipping_rates.where(shipping_method_id: changed_shipping_method.id).first
+          shipment.update_attributes(selected_shipping_rate_id: shipping_rate.id)
```
Comment (luisramos0) [inline spec/services/order_syncer_spec.rb]: this is probably order.shipment.select_shipping_method(changed_shipping_method.id)

File: spec/services/order_syncer_spec.rb [hunk 6]
```diff
@@ -34,27 +34,31 @@
...
+          order.update_attributes!(shipping_method_id: changed_shipping_method.id)
```
Comment (luisramos0) [inline spec/services/order_syncer_spec.rb]: see above regarding the column order.shipping_method_id

File: app/services/order_factory.rb [hunk 7]
```diff
@@ -14,8 +14,22 @@ def create
...
     set_addresses
+
+    # Transition to :delivery state.
+    @order.next!
+
+    set_shipping_method
+
+    # Transition to :payment state.
+    @order.next!
+
```
Comment (luisramos0) [inline app/services/order_factory.rb]: you are assuming a specific order workflow here...

also, do you know what happens if one of these steps fails for some reason?
you could run @order.next! only if order.state is the expected state and you could do something if @order.next! fails

I am sorry I dont have a specific suggestion for this one...

File: app/services/order_factory.rb [hunk 8]
```diff
@@ -65,6 +79,10 @@ def set_addresses
     @order.update_attributes(attrs.slice(:bill_address_attributes, :ship_address_attributes))
   end
 
+  def set_shipping_method
+    @order.update_attributes!(shipping_method_id: attrs[:shipping_method_id])
```
Comment (luisramos0) [inline app/services/order_factory.rb]: the column order.shipping_method_id is deprecated and will be deleted after v2 is live. we cannot rely on it.
this is how you do it in v2:
@order.shipment.select_shipping_method(attrs[:shipping_method_id])

File: app/services/order_syncer.rb (hunk 2 above)
Comment (kristinalim) [reply app/services/order_syncer.rb]: @luisramos0 Using `update_attributes` also works because `selected_shipping_rate_id` is `attr_accessible`: https://github.com/openfoodfoundation/spree/blob/2-0-4-stable/core/app/models/spree/shipment.rb#L19 And specs would fail if in the future it won't allow mass assignment anymore.

**Comment by kristinalim** [comment]
Thanks for the info, @luisramos0 - that's very helpful info and indeed makes this simpler.

File: app/services/order_factory.rb (hunk 7 above)
Comment (kristinalim) [reply app/services/order_factory.rb]: @luisramos0 What do you think about this approach: https://github.com/openfoodfoundation/openfoodnetwork/pull/3560/commits/7206cd88995ba52b77763a22d377c8564505a164 https://github.com/openfoodfoundation/openfoodnetwork/pull/3560/commits/dd2f7ecac65e3222afddd20748243fcfd8691c66

With these changes, shipment records are now created without changing the order status (similar to what is done for payments), and we now remember the previously selected shipping method and select it again after the new shipping rates have been created.

**Comment by kristinalim** [comment]
@luisramos0 Thanks for that feedback.

I have already been working on this, but then noticed this code in Spree `admin/orders#edit` which [transitions orders as far as it can](https://github.com/openfoodfoundation/spree/blob/v2.0.4/backend/app/controllers/spree/admin/orders_controller.rb#L57). :face_with_head_bandage:

```ruby
while @order.next; end
```

So that was why I kept seeing in the UI that subscription orders were completed... I suppose we're keeping this behaviour to keep the workflow similar to Spree? This behaviour wasn't in the previous version.

And then I checked Spree 2.4, and it looks like it remembers the shipping method when regenerating the shipping rates:

- [`admin/orders#edit`](https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/shipment.rb)
- [`Spree::Order#refresh_shipment_rates`](https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/order.rb#L556)
- [`Spree::Shipment#refresh_rates`](https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/shipment.rb#L221)

```ruby
      # StockEstimator.new assigment below will replace the current shipping_method
      original_shipping_method_id = shipping_method.try(:id)

      self.shipping_rates = Stock::Estimator.new(order).shipping_rates(to_package)

      if shipping_method
        selected_rate = shipping_rates.detect { |rate|
          rate.shipping_method_id == original_shipping_method_id
        }
        self.selected_shipping_rate_id = selected_rate.id if selected_rate
      end
```

Considering above, I think that overriding the `Spree::Order` method would be the best approach for now.

Let me know what you think. Moving this back to Code Review for further critique.

**Comment by luisramos0** [comment]
yes, that while order.next is so painful!

I see you prefer this version. I still prefer the previous version or some form of service that handles this logic outside of spree models. The main reason is that this overriding is not necessary and by creating a service with a clear API we would be able to improve the messy spree checkout workflow code.

Let's see what other reviewers say.

**Comment by luisramos0** [comment]
yes, the order workflow will fail (it will be stuck in delivery) if no shipping methods are available. another case is that the selection gets lost if the selected shipping method becomes unavailable. But that will be a problem in both implementations: in or out of the spree model.

**Comment by kristinalim** [comment]
I was wrong in my previous statement, where I said future versions of Spree remember the shipping method. This remembering only happens in `Spree::Shopment#refresh_rates`, which happens separately from transitioning an order (I got confused). This is called in [`admin/orders#edit`](https://github.com/openfoodfoundation/spree/blob/2-0-4-stable/backend/app/controllers/spree/admin/orders_controller.rb#L55) and [`admin/orders/customer_details#update`](https://github.com/openfoodfoundation/spree/blob/2-0-4-stable/backend/app/controllers/spree/admin/orders/customer_details_controller.rb#L25), separate from `while @order.next; end`. I think the goal mostly is to make sure that `Spree::ShippingRate` records exist and are calculated where needed.

When transitioning, it still calls `Spree::Order#create_proposed_shipments` which continues to remove shipments, until [2-4-stable](https://github.com/spree/spree/blob/2-4-stable/core/app/models/spree/order/checkout.rb#L96).

> What if the method got changed before the end of the order cycle? Would that change get lost in the old implementation?

@mkllnk When the shipping method in the subscription is changed before the OC closes, `OrderSyncer` updates the shipping method in future orders IF the shipping method in the order is still the same as that in the subscription (meaning it wasn't customized in the order). This behaviour is described in specs [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/23cf0729984b4827c8b83146231e3c83f46732b7/spec/services/order_syncer_spec.rb#L11).

**Comment by luisramos0** [comment]
@kristinalim fyi as it is related to this PR, as I was playing with live data in v2, I realized that refresh rates should only be called if order is not complete: https://github.com/spree/spree/blob/3c46d141c5cb2bedced63596178a0a79df3f0c9e/backend/app/controllers/spree/admin/orders_controller.rb#L54-L60

I think we'll need to bring this change to our spree 2-0-4 branch otherwise, editing an old order may just break it as shipping methods may not be setup appropriately for older orders.

**Comment by kristinalim** [comment]
> I think we'll need to bring this change to our spree 2-0-4 branch otherwise, editing an old order may just break it as shipping methods may not be setup appropriately for older orders.

@luisramos0 I'll do it if you're not working on it yet. :slightly_smiling_face:

**Comment by luisramos0** [comment]
no, I am not working on it. please go ahead :-)

I think we need to keep the workflow .next loop in these methods, because otherwise the page flow (moving automatically to customer details) will not work.

**Comment by mkllnk** [comment]
@kristinalim 
> When the shipping method in the subscription is changed before the OC closes, OrderSyncer updates the shipping method in future orders

That's not what I meant. I was thinking of the scenario that a single order is changed without touching the subscription. From the description of your previous implementation it sounded like that change would get lost because you would use the proxy order as reference for the shipping method. If the change is done in the proxy order as well (I don't know) then it's no problem and your previous implementation was correct.

I'll wait for your next version and review again. :-)

**Comment by kristinalim** [comment]
Thanks, @mkllnk!

> That's not what I meant. I was thinking of the scenario that a single order is changed without touching the subscription. From the description of your previous implementation it sounded like that change would get lost because you would use the proxy order as reference for the shipping method.

The implementation was using the previous shipping method of the _order_ before the transition, whether or not this was created for a subscription, so it wasn't losing the data. Does this answer your concern?

Anyway, I've already moved the order advancement code to a service (pretty okay with the idea now). :slightly_smiling_face: I'm just making a last change of having other places advancing the order state to use this service as well, if the initial order state is not specific.

**Comment by kristinalim** [comment]
This is now back in Code Review. Thanks for your feedback, @luisramos0 and @mkllnk!

File: app/controllers/spree/admin/orders_controller_decorator.rb [hunk 9]
```diff
@@ -27,6 +27,17 @@ def index
     # within the page then fetches the data it needs from Api::OrdersController
   end
 
+  def edit
+    @order.shipments.map &:refresh_rates
```
Comment (luisramos0) [inline app/controllers/spree/admin/orders_controller_decorator.rb]: there are two points about this method:
- there's a unless statement that we will need before the refresh shipping rates (out of scope for this PR)
https://github.com/spree/spree/blob/3c46d141c5cb2bedced63596178a0a79df3f0c9e/backend/app/controllers/spree/admin/orders_controller.rb#L54

- and also, the order advancement logic was removed in later versions of spree 2-0:
https://github.com/spree/spree/commit/8208b4bd0871b73be97bb2a7c7c1e0e4c04b3073#diff-1e2ba31309f1f1abd2a4b626036d316f

these are both out of scope of this PR.

File: app/controllers/spree/admin/payments_controller_decorator.rb [hunk 10]
```diff
@@ -1,6 +1,35 @@
...
+
+        flash[:success] = Spree.t(:new_order_completed)
+        redirect_to edit_admin_order_url(@order)
+      end
+
+    rescue Spree::Core::GatewayError => e
+      flash[:error] = "#{e.message}"
+      redirect_to new_admin_order_payment_path(@order)
+    end
+  end
```
Comment (luisramos0) [inline app/controllers/spree/admin/payments_controller_decorator.rb]: It's not good that we need to copy spree code to our code base but I am actually very happy that we are reclaiming this payments code to OFN, because the spree code is not good in v2 and it's a big mess in v3.7 [here](https://github.com/spree/spree/blob/e2d6599715932215635baf5a709693d9e9daad20/backend/app/controllers/spree/admin/payments_controller.rb#L25).

this kind of logic must go to a service, it's not the responsibility of the controller.
So I see this as the first step to improve it on our side.

It's out of scope for this PR.

File: app/services/advance_order_service.rb [hunk 11]
```diff
@@ -0,0 +1,35 @@
...
+  attr_reader :order
+
+  def initialize(order)
+    @order = order
+  end
+
+  def call(raise_on_error = false)
+    shipping_method_id = order.shipping_method.id if order.shipping_method.present?
+    options = { shipping_method_id: shipping_method_id }
+    raise_on_error ? advance_order!(options) : advance_order(options)
```
Comment (luisramos0) [inline app/services/advance_order_service.rb]: I see this raise_on_error and advance_order! as YAGNI 🔥

File: app/services/order_syncer.rb [hunk 12]
```diff
@@ -66,14 +66,13 @@ def update_payment_for(order)
...
-      unless order.shipments.with_state('pending').where(shipping_method_id: shipping_method_id).any?
-        order_update_issues.add(order, I18n.t('admin.shipping_method'))
-      end
+    shipment = order.shipment
+    return track_shipping_method_issue(order) if shipment.blank?
+
+    if shipment.state == "pending" && shipment.shipping_method.id == shipping_method_id_was
+      order.select_shipping_method(shipping_method_id)
+    elsif !(shipment.state == "pending" && shipment.shipping_method.id == shipping_method_id)
+      track_shipping_method_issue(order)
```
Comment (luisramos0) [inline app/services/order_syncer.rb]: this is too difficult to read,
we should simplify this, even if only extracted to methods with good names.

or maybe just remove the elsif,
if we just have two ifs one after the other, it's more readable and more correct, in case the first assignment fails, right?

```ruby
    if shipment.state == "pending" && shipment.shipping_method.id == shipping_method_id_was
      order.select_shipping_method(shipping_method_id)
    end
    unless shipment.state == "pending" && shipment.shipping_method.id == shipping_method_id
      track_shipping_method_issue(order)
     end
```
and then, is this correct?
```ruby
    track_shipping_method_issue(order) unless shipment.state == "pending"
    if shipment.shipping_method.id == shipping_method_id_was
      order.select_shipping_method(shipping_method_id)
    end
    track_shipping_method_issue(order) unless shipment.shipping_method.id == shipping_method_id
```

File: app/services/advance_order_service.rb [hunk 13]
```diff
@@ -0,0 +1,35 @@
+class AdvanceOrderService
```
Comment (luisramos0) [inline app/services/advance_order_service.rb]: we went for option 4 here
https://community.openfoodnetwork.org/t/how-to-name-a-new-service-in-ofn/1530

File: app/services/advance_order_service.rb (hunk 11 above)
Comment (kristinalim) [reply app/services/advance_order_service.rb]: @luisramos0 This has implications in the handling in the places where this is used. For example, when creating a payment and the order cannot be transitioned all the way to completion, this would rollback. But in the edit order page, this would just stop where the state cannot be transitioned anymore.

I actually considered merging the two. But aside from raising an error where needed, I was being cautious about how `order.state == "complete"` is not the same as `order.completed?`. (An order that is completed and then cancelled would return `false` for the first condition but `true` for the next.)

I prefer not touch this for now, and think we should look into that later. What do you think? Spree 2.4-stable does not use the bang version in `admin/payments#create` anymore, and it can be :fire: without much audit then.

**Spree 2.4-stable:**

```
$ grep -r order.next | egrep -v 'spec|testing_support'
src/frontend/app/controllers/spree/orders_controller.rb:              @order.next if @order.cart?
src/frontend/app/controllers/spree/checkout_controller.rb:        unless @order.next
src/backend/app/controllers/spree/admin/orders/customer_details_controller.rb:            @order.next
src/backend/app/controllers/spree/admin/payments_controller.rb:            while @order.next; end
src/backend/app/controllers/spree/admin/payments_controller.rb:            # If "@order.next" didn't trigger payment processing already (e.g. if the order was
src/api/app/controllers/spree/api/checkouts_controller.rb:        @order.next!
src/api/app/controllers/spree/api/checkouts_controller.rb:        while @order.next; end
src/api/app/controllers/spree/api/checkouts_controller.rb:          if @order.completed? || @order.next
src/core/lib/tasks/exchanges.rake:        while order.state != order.checkout_steps[-2] && order.next; end
```

**Current Spree version:**

```
$ grep -r order.next | egrep -v 'spec|testing_support'
frontend/app/controllers/spree/orders_controller.rb:              @order.next_transition.run_callbacks if @order.cart?
frontend/app/controllers/spree/checkout_controller.rb:        unless @order.next
backend/app/controllers/spree/admin/orders/customer_details_controller.rb:            while @order.next; end
backend/app/controllers/spree/admin/orders_controller.rb:        while @order.next; end
backend/app/controllers/spree/admin/payments_controller.rb:              @order.next!
backend/app/controllers/spree/admin/payments_controller.rb:      # where order.next is called which leaves the order in payment step
api/app/controllers/spree/api/orders_controller.rb:        if @order.valid? && @order.next
api/app/controllers/spree/api/checkouts_controller.rb:          state_callback(:after) if @order.next
api/app/controllers/spree/api/checkouts_controller.rb:        @order.next!
api/app/controllers/spree/api/checkouts_controller.rb:          if @order.valid? && @order.next
```

File: app/services/order_syncer.rb (hunk 12 above)
Comment (kristinalim) [reply app/services/order_syncer.rb]: The first snippet works is equivalent with a `return` in the first block. :+1: 

But the next version is not equivalent. The current version does not always call `track_shipping_method_issue(order)` if shipment state is not pending, but this would.

Thinking about this...

Comment (kristinalim) [reply app/services/order_syncer.rb]: I added a commit. It's a lot more readable now: https://github.com/openfoodfoundation/openfoodnetwork/pull/3560/commits/7505dd0410043d51065122c7db65c2032ce32226

Thanks, @luisramos0! :slightly_smiling_face:

Comment (luisramos0) [reply app/services/order_syncer.rb]: ah, yes, awesome, much better!

File: app/services/advance_order_service.rb (hunk 11 above)
Comment (luisramos0) [reply app/services/advance_order_service.rb]: yeah, I see now, I think we need to keep it until 2.2

it was in v2.2 they removed this here: https://github.com/spree/spree/commit/4eade0fa78f426f5a3a8db15789dee48c2f87fa9?diff=unified
and then added the one without the bang here: https://github.com/spree/spree/commit/59198f74cf156e3b09dbf16f8eca523e28ebec79

Comment (luisramos0) [reply app/services/advance_order_service.rb]: thanks for the explanation!

Comment (mkllnk) [reply app/services/advance_order_service.rb]: The syntax is not clear though. You don't know what the boolean means from reading this:
```rb
AdvanceOrderService.new(@order).call(true)
```

You could go with a named parameter:
```rb
AdvanceOrderService.new(@order).call(raise_on_error: true)
```

But in this case I would go with the bang convention:
```rb
AdvanceOrderService.new(@order).call!
```

If you put `options` into its own method it becomes really easy.

File: app/controllers/spree/admin/orders/customer_details_controller_decorator.rb [hunk 14]
```diff
@@ -1,6 +1,22 @@
 Spree::Admin::Orders::CustomerDetailsController.class_eval do
   before_filter :set_guest_checkout_status, only: :update
 
+  def update
+    if @order.update_attributes(params[:order])
+      if params[:guest_checkout] == "false"
```
Comment (sauloperez) [inline app/controllers/spree/admin/orders/customer_details_controller_decorator.rb]: I'm a bit surprised to compare a boolean value to a string. Rails does parse JSON to Ruby primitives. How is it possible that we end up with a String and not with a FalseClass instance 🤔 ? I would have expected to read this as `if !params[:guest_checkout]`

File: app/services/advance_order_service.rb [hunk 15]
```diff
@@ -0,0 +1,35 @@
...
+  def call(raise_on_error = false)
+    shipping_method_id = order.shipping_method.id if order.shipping_method.present?
+    options = { shipping_method_id: shipping_method_id }
+    raise_on_error ? advance_order!(options) : advance_order(options)
+  end
+
+  private
+
+  def advance_order(options)
+    until order.state == "complete"
```
Comment (sauloperez) [inline app/services/advance_order_service.rb]: It'd be great to stick to the approach in line 24 for consistency IMO

File: app/controllers/spree/admin/orders/customer_details_controller_decorator.rb (hunk 14 above)
Comment (kristinalim) [reply app/controllers/spree/admin/orders/customer_details_controller_decorator.rb]: @sauloperez This isn't the case when the string is sent to the server as HTTP form data. However, this string would still be converted to a boolean as we expect when assigned to an `ActiveRecord` boolean attribute. :slightly_smiling_face:

File: app/services/advance_order_service.rb (hunk 15 above)
Comment (kristinalim) [reply app/services/advance_order_service.rb]: I gave this a try just now, @sauloperez, and confirmed that a completed but later cancelled order would attach an error here (`ActiveRecord::Base#errors`) whereas using `order.completed?` would not. `Spree::Order#completed?` looks at `completed_at`, not the order state.

We can actually remove `advance_order!` in Spree 2.2. (Discussion here: [heere](https://github.com/openfoodfoundation/openfoodnetwork/pull/3560#discussion_r265746751)) Are you okay with waiting until then so we avoid doing a more comprehensive check?

File: app/services/advance_order_service.rb (hunk 11 above)
Comment (kristinalim) [reply app/services/advance_order_service.rb]: Thanks, @mkllnk! I changed this here: https://github.com/openfoodfoundation/openfoodnetwork/pull/3560/commits/94606025c9c881c61fe52c07dc9adf4f86f35962 I also added a couple of specs to cover `call!`.

**Comment by sauloperez** [comment]
Merging as suggested by @kristinalim . It seems to be passing those 13 specs.
