### PR TITLE
Delete linked coordinators fees when deleting an order cycle

### LINKED ISSUE #5903: Can't delete Cloned Order Cycle
## Description
Enterprise Willunga Farmers Market (2545) created a clone of an existing order cycle. They were then unable to delete that cloned order cycle. These cloned O/Cs were of the existing O/C called **2020 Week 21**

ERROR:
**An order cycle has been selected by a customer and cannot be deleted. To prevent customers from accessing it please close it instead.**

When logged in as a Manager of the Enterprise we were also unable to delete the cloned order cycle. We created an additional test clone and were unable to delete that either.

To remove the cloned order cycles from the Enterprise's view, we changed their end dates to January 2019. These two order cycles are now no longer visible in the Order Cycle list, and cannot be browsed for as they are more than 90 days ago (is this a bug in itself?). When using the search tool for the names of these order cycles (**COPY of 2020 Week 21**) there are no results. It's not clear if these order cycles still exist.

## Expected Behavior
The Order Cycle can be deleted

## Steps to Reproduce

1. Access Enterprise Willunga Farmers Market as Superadmin
2. Go to Order Cycles
3. Select clone for an existing order cycle
4. Attempt to delete the cloned order cycle

To remove the Order Cycle from view, change the end date to a date well in the past. This Order Cycle disappears and cannot be searched (but does it still exist??) 

## Severity
S3
 
The workaround is to change the end date of the order cycle, which makes it disappear (to somewhere???)

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
There was a `InvalidForeignKey` when deleting a cloned OrderCycle, due to existing `coordinators_fees`. This PR adds a `dependent: :destroy` on `coordinator_fees` for an `order_cycle`

Closes #5903

#### What should we test?

 - Clone an order cycle (with coordinator fees)
 - Delete the new created order cycle
 - This should be possible without any error

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Spec?

**Comment by jibees** [comment]
> Spec?

Done: [5fc7d72](https://github.com/openfoodfoundation/openfoodnetwork/pull/8950/commits/5fc7d72b09b9bc508bf31e9b587b5029b8f1fe49)

I'm a bit afraid with this one: actually I thought that some tests will failed, but none failed. Deleting associated coordinator_fees when deleting OC seems to be ok (at least in term of spec). I'm still wondering if it's ok in term of user/product point of view...

File: spec/controllers/admin/order_cycles_controller_spec.rb [hunk 1]
```diff
@@ -401,6 +401,20 @@ def build_resource
           expect(flash[:error]).to eq I18n.t('admin.order_cycles.destroy_errors.schedule_present')
         end
       end
+
+      describe "when an order cycle has any coordinator_fees", :debug do
```
Comment (mkllnk) [inline spec/controllers/admin/order_cycles_controller_spec.rb:405]:
```suggestion
      describe "when an order cycle has any coordinator_fees" do
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
Thank you for your reflection on this! It made me look into the data model and an enterprise fee `has_many :order_cycles`. So we can't just delete it. I think that we need to do something like an around_destroy action that:

- checks for coordinator fees
- disassociates those fees
- [destroy oc]
- check if the fees are associated to anything else or now orphans
- destroy orphaned fees

**Comment by mkllnk** [comment]
With your testing steps and your current implementation, is the fee deleted from the original OC or is it duplicated for the cloned OC?

If it's deleted (which would be a bug) then it could be good to write that down as a spec for cloning OCs as well.

File: spec/controllers/admin/order_cycles_controller_spec.rb (hunk 1 above)
Comment (jibees) [reply spec/controllers/admin/order_cycles_controller_spec.rb:405]: 🤦

**Comment by jibees** [comment]
Ok, this post is here to try to understand, and 

###### Dataset
`OC_2`, the original
`OC_9`, the cloned from `OC_2`

Retrieving `coordinator_fees` for `OC_2`: 
```
select * from coordinator_fees where coordinator_fees.order_cycle_id = 2;

id | order_cycle_id | enterprise_fee_id
-- | -- | --
2 | 2 | 4
```

Retrieving `coordinator_fees` for `OC_9`: 
```
select * from coordinator_fees where coordinator_fees.order_cycle_id = 9;


id | order_cycle_id | enterprise_fee_id
-- | -- | --
9 | 9 | 4
```

###### Conclusions I've made
The `coordinator_fees` data is copied when an OC is cloned. A `coordinator_fees` is only linked with one order_cycle. It reference then an `enterprise_fee` which is the same (in the previous sql query, you could see that `enterprise_fee_id` is `4` for both `coordinator_fee`).

For all those reasons, I thought could be a good idea to delete the associated `coordinator_fees` when deleting an order cycle.

###### To answer your questions
> With your testing steps and your current implementation, is the fee deleted from the original OC or is it duplicated for the cloned OC?

I didn't test with a cloned OC (which I probably should), but when deleting an OC, it deletes the `coordinator_fees` that is associated to its OC (in our exemple, if we delete the `OC_9`, the `coordinator_fees` with id `9` will by deleted)

**Comment by jibees** [comment]
I've pushed one commit that #[7ca6434](https://github.com/openfoodfoundation/openfoodnetwork/pull/8950/commits/7ca6434b1410b9b2eb831a4592dd96131b996f59) should actually improve the test coverage. 
Will be happy if you can check it out.

**Review by mkllnk — APPROVED** [review]
Great, thank you!

That was thorough investigating. :slightly_smiling_face: 

I didn't realise the difference between coordinator fees and exchange fees. Both associate an enterprise fee with an order cycle but exchange fees are associated via the participating enterprises while the coordinator fee can be associated directly because the coordinator doesn't need to be one of the trading enterprises.

Your new spec is excellent!

**Comment by jibees** [comment]
This one is more than 1 month old, has been reviewed by @mkllnk --> moving to `Test Ready` column.
If you feel that this should not happened, feel free to move it back to `Code Review` column.

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Many thanks for the detailed investigation and discussion! 

> I didn't realise the difference between coordinator fees and exchange fees. 

I also had forgotten all about them @mkllnk :-) There's really plenty of granularity as of where to place the fee in the OC :sweat_smile: 

So, after reproducing the error (cloned OC + coordinator fee), the PR was staged and it was verified that:

- the cloned OC can now be deleted - no error message :+1: 
- the coordinator fee is not deleted from the OC from it was cloned - it can be seen below:

Peek 2022-04-18 11-46

Before deleting:

```
openfoodnetwork=> select * from coordinator_fees where coordinator_fees.order_cycle_id = 3585;
 order_cycle_id | enterprise_fee_id | id  
----------------+-------------------+-----
           3585 |               299 | 468
(1 row)

openfoodnetwork=> select * from coordinator_fees where coordinator_fees.order_cycle_id = 3586;
 order_cycle_id | enterprise_fee_id | id  
----------------+-------------------+-----
           3586 |               299 | 469
(1 row)
```

After deleting:

```

openfoodnetwork=> select * from coordinator_fees where coordinator_fees.order_cycle_id = 3586;
 order_cycle_id | enterprise_fee_id | id 
----------------+-------------------+----
(0 rows)

openfoodnetwork=> select * from coordinator_fees where coordinator_fees.order_cycle_id = 3585;
 order_cycle_id | enterprise_fee_id | id  
----------------+-------------------+-----
           3585 |               299 | 468
```

Good to go, merging - thanks :tada:
