### PR TITLE
Get the whole list of products on order cycle changes

### LINKED ISSUE #7458: incorrect product displayed in multi OC shop
## Description
Enterprise ID : 998 

A shop with 3 OC opened simultaneously, with 3 identicals product's content 
Capture d’écran 2021-04-22 à 16 12 18

## Expected Behavior
Products diplaying identical in the [shop](https://www.coopcircuits.fr/le-potager-de-saint-inn/shop) for the 3 OC

## Actual Behaviour
The shop displaying 20 products for the 1st OC "Commande des plants pour le 30 avril" 
Capture d’écran 2021-04-22 à 16 12 18

When swicth from the top right button or the 2nd OC "Commande pour le 14 mai" the shop displaying 20 products 
Capture d’écran 2021-04-22 à 16 19 25

But, when you switch for the third OC "Commande pour le 28 mai" the shop displaying 10 products.
So, It missed 10 products, the displaying stopped to the tenth product " poivron Corno Di Toro Roux " 

Capture d’écran 2021-04-22 à 16 22 24

## Steps to Reproduce

1. To the shop https://www.coopcircuits.fr/le-potager-de-saint-inn/shop
2. Consult products 
3. Change OC from the first to the third
4. Compare products

## Workaround
Ask client to reload the web page

## Severity

bug-s3: a feature is broken but there is a workaround

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment

* Browser name and version: Firefox 87.0 (64 bits) and Chrome Version 89.0.4389.128

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?
 - `ProductsCtrl` loaded twice: so we asked twice for the list of products for each store.
 - Values that were watched by Angular was not initialized: therefore they triggered a change (from `undefined` to `[]`) which was unnecessary
 - We now reinit the `page` params to `1` as we change the order cycle
 - Do not call `loadMore` immediately: this led to calling the next 10 products although this was not necessary. 

Therefore, I reduce the number of requests to `api/v0/order_cycles/6/products.json` by 2 ? (depending on user behavior of course)

Closes #7458

#### What should we test?
1. Create a shop with more than 1 open order cycle
2. Assign more than 30 products to each order cycle
3. Go to this shop, load the first order cycle, then scroll the page to display all the 30 (or more) products
4. Change order cycle, products list should refresh, and load more items (30 or more) when scrolling the product list

#### Release notes

Changelog Category: User facing changes | Technical changes

### CODE REVIEW

**Review by andrewpbrett — COMMENTED** [review]
This is looking great! Nice catch JB. I'm going to put it In Dev for now but feel free to move it back to Code Review once it's ready.

**Comment by jibees** [comment]
@andrewpbrett 

Yes, as it needs some automated tests, you're right, this is actually `In Dev`

**Comment by jibees** [comment]
I wanted to create automated tests to check this behavior : a shop with at least 2 open OC and with 30 products each.

```diff
diff --git a/spec/features/consumer/shopping/shopping_spec.rb b/spec/features/consumer/shopping/shopping_spec.rb
index 3be9aa346..7a61f3f60 100644
--- a/spec/features/consumer/shopping/shopping_spec.rb
+++ b/spec/features/consumer/shopping/shopping_spec.rb
@@ -159,6 +159,23 @@ feature "As a consumer I want to shop with a distributor", js: true do
             end
           end
         end
+
+        describe "multiple order cycle and more than 10 products for each", :debug do 
+          before do
+            30.times do
+              puts "create product"
+              product = create(:simple_product, supplier: supplier)
+              add_variant_to_order_cycle(exchange1, product.variants.first)
+              add_variant_to_order_cycle(exchange2, product.variants.first)
+            end
+          end
+
+          it "show the first page" do
+            visit shop_path
+            select "turtles", from: "order_cycle_id"
+            expect(page).to have_selector("product", count: 20)
+          end
+        end
       end
     end
``` 

I can't figure out, but it doesn't work as expected ; randomly (but very often) the request that get the list of products is empty.

**Comment by jibees** [comment]
> I can't figure out, but it doesn't work as expected ; randomly (but very often) the request that get the list of products is empty.

Finally, I found a workaround.

File: spec/features/consumer/shopping/shopping_spec.rb [hunk 1]
```diff
@@ -159,6 +159,31 @@
...
           end
         end
+
+        describe "two order cycles and more than 20 products for each" do
+          before do
+            20.times do
+              product = create(:simple_product, supplier: supplier)
+              add_variant_to_order_cycle(exchange1, product.variants.first)
+              add_variant_to_order_cycle(exchange2, product.variants.first)
+            end
```
Comment (sauloperez) [inline spec/features/consumer/shopping/shopping_spec.rb:169]: this is going to be quite expensive. We could find a way to stub the number of items per page so we test the same but with 2 products.

**Review by sauloperez — COMMENTED** [review]
Great job @jibees !

**Comment by Matt-Yorkley** [comment]
Alright... so as discussed Slack, there's a weird error that comes up when running the test here, which looks like this:
```
Failure/Error: @app.call(env)
     LoadError:
       Unable to autoload constant Api::V0::OrderCyclesController, expected /Users/jibees/dev/openfoodnetwork/app/controllers/api/v0/order_cycles_controller.rb to define it
     # ./lib/open_food_network/rack_request_blocker.rb:36:in `call'
     # ------------------
     # --- Caused by: ---
     # Capybara::ExpectationNotMet:
     #   expected not to find visible css "img.spinner", found 1 match: ""
     #   ./spec/features/consumer/shopping/shopping_spec.rb:177:in `block (6 levels) in <top (required)>'
```
When I run it I also get these warnings:
```
... activesupport-5.0.7.2/lib/active_support/dependencies.rb:458: warning: already initialized constant Api::V0
... activesupport-5.0.7.2/lib/active_support/dependencies.rb:458: warning: previous definition of V0 was here
```

I'm pretty sure this is a weird class loading issue caused by the XHR requests not being handled nicely by Capybara. So what I think is happening is: the page is being loaded in the main thread, then an XHR request is being made, but it's actually being handled by the same thread, which then loads that API controller class a second time, which fails. It only seems to occur about 25% of the time. Super weird.

We could possibly use this in your spec:
```ruby
around do |example|
  Capybara.raise_server_errors = false
  example.run
  Capybara.raise_server_errors = true
end
```
...but it feels pretty hacky.

**Comment by jibees** [comment]
@Matt-Yorkley 

Thanks a lot for you investigation. I also found the workaround with `config.raise_server_errors = false` in `spec_helper` file.

As it has nothing to do with this PR, maybe we should open a new issue on your investigation (and as I know, about your solution?)

**Comment by Matt-Yorkley** [comment]
> config.raise_server_errors = false in spec_helper

Yeah I think we can go with that for now, but I'd rather use the previous example and add it just within the context of this one test (and not in `spec_helper.rb`):
```ruby
around do |example|
  Capybara.raise_server_errors = false
  example.run
  Capybara.raise_server_errors = true
end

it "show the whole products list for each OC" do
...
```
this way we're not disabling that setting for the entire test suite (which could mean we end up missing errors elsewhere in the build).

> maybe we should open a new issue on your investigation

Yeah I think we'll have to re-assess this setup soon anyway. If we start using Websockets I think we might have to move away from using Webrick in the test suite, and make a few other improvements :+1:

File: spec/features/consumer/shopping/shopping_spec.rb (hunk 1 above)
Comment (jibees) [reply spec/features/consumer/shopping/shopping_spec.rb:169]: I can easily change the value of the `DEFAULT_PER_PAGE` constant inside `ProductsRenderer` which is in charge of doing the jsonification of products with this line:
```ruby
stub_const("#{ProductsRenderer}::DEFAULT_PER_PAGE", 1)
```

But, inside the angularjs controller, to test if it should load more products, the conditional testing is: 
```js
if ($scope.page * $scope.per_page) <= Products.products.length
      $scope.loadMoreProducts()
```

and `$scope.per_page` in initialized with a simple: `$scope.per_page = 10`

Which also means that `ProductsRenderer::DEFAULT_PER_PAGE` and `ProductsCtrl.$scop.per_page` must be the same to work well.

Comment (jibees) [reply spec/features/consumer/shopping/shopping_spec.rb:175]: So I'm looking for a way to change the value of an Angularjs controller constant in a Capybara feature test...

**Review by Matt-Yorkley — APPROVED** [review]
Great :muscle:

File: spec/features/consumer/shopping/shopping_spec.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply spec/features/consumer/shopping/shopping_spec.rb:175]: In this case the cost is ~10 seconds on the build, but the reward is confidence that products are loading correctly in the shopfront. 

Maybe we can look at improving the efficiency in a separate tech-debt issue? It would be good to get this in the release...

Comment (jibees) [reply spec/features/consumer/shopping/shopping_spec.rb:175]: Yes, I think you're right : it probably needs some none-negligible time to create such a test, but we should merge this PR because it solves a lot of performing issues (at least unnecessary requests loads) in the app.
So: 
 - Happy to create a tech debt issue 
 - Let's merge it (if everyone is ok with the solution/code review of course)

Comment (jibees) [reply spec/features/consumer/shopping/shopping_spec.rb:175]: Issue created: #7508

**Review by sauloperez — APPROVED** [review]

**Comment by jibees** [comment]
Moving to `Test Ready`! 🎉

**Comment by sauloperez** [comment]
Thanks, I'm on my phone and I can't move it from GH.

**Comment by filipefurtad0** [comment]
Hey @jibees !

Thank you for your detailed testing notes. Somehow it did not work for me with two OCs only, so I added a third, and could indeed observe, that the third OC (labelled "OC2") only loaded 10 products (after setting them simultaneously with over 40 products):

before_PR7478

For "OC2" the last product loaded is "Orange Tree 17", but there are 40 of these. After staging this PR the issue is fixed! All OC load the products correctly:

after_PR7478

Also - maybe my impression - but the page loads much faster! It would be great to assess this improvement. This probably will be seen in Datadog, for shops with plenty of products.

Moving to ready to go! Congratulations on your first S2 :tada: :raised_hands:

**Comment by sauloperez** [comment]
Awesome stufff @jibees :heart_eyes: !
