### PR TITLE
Keep stock selection when error on saving

### LINKED ISSUE #12569: [BUU] Stock settings selection is lost, if there are errors on saving
## Description

Follow-up from #12553.

On the products page, when creating a new variant, the stock options are lost, if there are errors on the form, and the user hits Save changes.

## Expected Behavior

If some stock options were already selected, these should be kept, even when there are errors on the form, when saving.

## Actual Behaviour

The selected stock options are not kept, when there are errors on the form, when saving.

## Steps to Reproduce

1. Click the + sign, to add a Variant
2. Fill in all fields and select a stock option (wither by ticking the On Demand option, or by typing in a numerical value on the On Hand field). Make sure you leave a mandatory field empty (like price or Unit)
3. Click Save changes
4. Notice the changes inserted on the On Hand field were reset

## Animated Gif/Screenshot

image

After hitting Save changes:

image

## Workaround

Fill in the stock options again

## Severity

More of a usability issue?
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.4.50
* Browser name and version: Firefox 126
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by cyrillefr**
#### What? Why?

- Closes #12569 

#### What should we test?
- Feature Admin V3 toggled on
- Visit `/admin/products`
- Add a variant ( + sign) to a product
- Do not fill anything, except the On Hand part
  -  click on checkbox `On demand`
  - or choose a number
- Click `Save changes`
- Page should return in error mode with a `cannot be blank` in the `Unit` column
- But  the status for the `On Hand` part should keep what was entered at first.

#### How I did it
I added 2 not to be persisted attributes aimed at dealing with the UI. Their purpose is to be passed and passed by in case of validation errors from and to the UI.
Therefore, there is no interference with the current fields and logic.

In the view: I added some kind of "mode": when variant exists on DB or not.
So instead of on_hand/on_demand methods passed in form helpers, it will be now either:
- `on_hand` when variant exists (current only case)
- `on_hand_desired` for a new variant

So that, in `variant`, one can get values from the ui whether or not the variant exists or not.
In case validation fails, the value for on_hand/on_demand are stored and are passed by to the ui in the variant object.
If everything fine, then variant is persisted in DB.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [X] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/services/sets/product_set.rb [hunk 1]
```diff
@@ -153,5 +153,12 @@ def notify_bugsnag(error, product, variant, variant_attributes)
         report.add_metadata(:variant_error, variant.errors.first) unless variant.valid?
       end
     end
+
+    def create_stock_for_variant(variant, on_demand, on_hand)
+      variant.on_demand = on_demand if on_demand.present?
+      variant.on_demand = variant.on_demand_desired if variant.on_demand_desired.present?
+      variant.on_hand = on_hand.to_i if on_hand.present?
+      variant.on_hand = variant.on_hand_desired.to_i if variant.on_hand_desired.present?
```
Comment (mkllnk) [inline app/services/sets/product_set.rb:161]: It's not clear to me which value is used in which case here. Looking only at this logic, the stock could even be set twice when updated. So first it would set the old on_hand value when it's present and then set the new desired value. This is a bit inefficient but also confusing to follow.

I think that it would be clearer to have one branch of logic:

* Form always sets the desired value.
* We always use the desired value to update stock.

File: app/views/admin/products_v3/_variant_row.html.haml [hunk 2]
```diff
@@ -30,14 +31,14 @@
   = error_message_on variant, :price
 %td.col-on_hand.field.popout{'data-controller': "popout"}
   %button.popout__button{'data-popout-target': "button", 'aria-label': t('admin.products_page.columns.on_hand')}
-    = variant.on_demand ? t(:on_demand) : variant.on_hand
+    = variant.send(method_on_demand) ? t(:on_demand) : variant.send(method_on_hand)
```
Comment (mkllnk) [inline app/views/admin/products_v3/_variant_row.html.haml:34]: Using `send` is a sign that there's an issue with the code design. I think that it would be better to implement the reader on the model to read the value from the database if the desired value isn't set.

File: spec/system/admin/products_v3/products_spec.rb [hunk 3]
```diff
@@ -926,6 +926,45 @@ def expect_other_columns_visible
...
+          check "On demand"
+        end
+
+        click_button "Save changes"
+
+        expect(page).to have_content "Please review the errors and try again"
+        within row_containing_name("Large box") do
+          expect(page).to have_content "On demand"
+        end
+      end
```
Comment (mkllnk) [inline spec/system/admin/products_v3/products_spec.rb:965]: Great to have this tested! :100: 

Since system specs are slow, I would combine these two examples. You can fill both values, hit save once and then assert on both values.

**Review by mkllnk — CHANGES_REQUESTED** [review]

File: spec/system/admin/products_v3/products_spec.rb (hunk 3 above)
Comment (cyrillefr) [reply spec/system/admin/products_v3/products_spec.rb]: I have refactored the spec in this way :)

File: app/views/admin/products_v3/_variant_row.html.haml (hunk 2 above)
Comment (cyrillefr) [reply app/views/admin/products_v3/_variant_row.html.haml]: I have added 2 methods in `variant_stock` to choose from which field to read. I have applied the same logic as in the view.

File: app/services/sets/product_set.rb (hunk 1 above)
Comment (cyrillefr) [reply app/services/sets/product_set.rb]: Yes, it was a bit cluttered. After a few trials (and errors), I think this is better now.
The conditional I added is because in legacy mode, you enter the create variant with on Hand/on demand whereas in v3 you do not.

**Comment by sigmundpetersen** [comment]
Hi all.
Why was this one closed? I can't find a mention of that in the issue or pr.
Seems the changes were ready for another round of review, but that the pr was left hanging in the 'In progress' column.

@openfoodfoundation/reviewers should we reopen and have another look at it?
Or do you think it should stay closed?

**Review by mkllnk — COMMENTED** [review]
Much better!

It's still a little bit cumbersome but that's worth fixing the bug. Thank you!

I'm sorry that I missed your updates. Can you please re-open? I would approve this as is.

File: app/views/admin/products_v3/_variant_row.html.haml [hunk 4]
```diff
@@ -30,14 +31,14 @@
...
     .field
-      = f.number_field :on_hand, min: 0, 'aria-label': t('admin.products_page.columns.on_hand'), 'data-toggle-control-target': 'control', disabled: f.object.on_demand
-      = error_message_on variant, :on_hand
+      = f.number_field method_on_hand, min: 0, 'aria-label': t('admin.products_page.columns.on_hand'), 'data-toggle-control-target': 'control', disabled: f.object.on_demand_desired_or_current
+      = error_message_on variant, method_on_hand
     .field.checkbox
-      = f.label :on_demand do
-        = f.check_box :on_demand, 'data-action': 'change->toggle-control#disableIfPresent change->popout#closeIfChecked'
+      = f.label method_on_demand do
+        = f.check_box method_on_demand, 'data-action': 'change->toggle-control#disableIfPresent change->popout#closeIfChecked'
```
Comment (dacook) [inline app/views/admin/products_v3/_variant_row.html.haml:41]: I wish there was a better way to manage these two cases. If we need to add this complexity, the on_hand/on_demand field might deserve to have its own partial.

File: app/models/concerns/variant_stock.rb [hunk 5]
```diff
@@ -77,6 +77,18 @@ def on_demand=(new_value)
...
+
+    on_demand
+  end
+
+  def on_hand_desired_or_current
+    return on_hand_desired if new_record?
+
+    on_hand
+  end
+
```
Comment (dacook) [inline app/models/concerns/variant_stock.rb:91]: These are arguably view-specific logic, so perhaps these could be moved to view helpers. Also `method_on_demand`.

**Review by dacook — COMMENTED** [review]
I'm guessing the new, separate "desired" attributes are to reduce risk. It's a shame it makes it pretty complicated, but it protects against creating new stock issues. I probably would have chosen a different name for these temporary variables, but don't have any better ideas.

I have a few other thoughts on how this could be organised, because as Maikel says it's pretty cumbersome.

But it would be great to fix the bug 👍

**Comment by cyrillefr** [comment]
Hello @mkllnk , @dacook , @sigmundpetersen 

Sorry for the PR closing. I did some local project cleaning a fee weeks ago and I guess by deleting a local branch, it automatically closed this PR. It was not my intention. I must have made some bad filtering and did not see the corresponding issue was still open ....

Do you want me to re open this PR ? (I guess i can do it by restoring the deleted branch).

**Comment by sigmundpetersen** [comment]
> Do you want me to re open this PR ? (I guess i can do it by restoring the deleted branch).

Yes, thank you @cyrillefr . Maybe we could get the fix merged, that would be nice 👍

**Comment by rioug** [comment]
@cyrillefr If you are not on it already, could you address the conflict ?

**Comment by cyrillefr** [comment]
Conflict is solved, but I need to fix the specs since behaviour seemed to have a bit changed since last time.

**Review by mkllnk — APPROVED** [review]
Thank you!
