### PR TITLE
Fix for new subscription dialog

### LINKED ISSUE #9648: [Subscriptions] Searching a shop doesn't work when creating a new subscription
## Description

When setting up a new subscription the list of shop open and shows a search input but you can't type anything in there. You have to scroll through the list of shops to find the one you need.

## Expected Behavior

Typing letters in the search input field should show the relevant results only.

## Actual Behaviour

Typing into the search input field is not possible.

## Steps to Reproduce

1. Go to /admin/subscriptions
2. Click 'New Subscription'
3. A modal opens
4. Try to search for a shop in the list

## Animated Gif/Screenshot

Peek 2022-09-08 15-08

## Workaround

Find and select the shop without using the search.

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: staged [abbb61b](https://github.com/openfoodfoundation/openfoodnetwork/commit/abbb61b943abb0c22012bdcb147f898d1b0b5bf2)
* Browser name and version: Firefox 104
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by ashwini-seshadri**
#### What? Why?

Closes #9648

When setting up a new subscription the list of shop open and shows a search input but was not able to type anything in there. This PR fixes that and there is no need for the user to scroll through the list of shops to find the one they need.

#### What should we test?
Other parts of the app will not be affected from this change.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

#### Dependencies

No

#### Documentation updates

No

### CODE REVIEW

**Comment by ashwini-seshadri** [comment]
https://user-images.githubusercontent.com/88281470/192154016-029939f8-93b5-47c0-adad-44da5e3656ec.mov

**Comment by ashwini-seshadri** [comment]
Screenshot 2022-09-25 at 6 19 52 PM

I see a "triangle" in green color from the nav bar showing up on the modal. Shall I increase the z-index of the modal?

File: spec/support/request/web_helper.rb [hunk 1]
```diff
@@ -128,9 +128,11 @@ def close_select2
   end
 
   def tomselect_search_and_select(value, options)
-    page.find("[name='#{options[:from]}']").sibling(".ts-wrapper").click
-    page.find(:css, '.ts-dropdown input.dropdown-input').set(value)
-    page.find(:css, '.ts-dropdown .ts-dropdown-content .option', text: value).click
+    tomselect_wrapper = page.find("[name='#{options[:from]}']").sibling(".ts-wrapper")
+    tomselect_wrapper.find(".ts-control").click
```
Comment (ashwini-seshadri) [inline spec/support/request/web_helper.rb:132]: tom select along with capybara was behaving weird, and I was seeing this failure. So I did multiple clicks. I hope it is ok.:
```
Capybara::ElementNotFound:
       Unable to find visible css ".ts-dropdown input.dropdown-input" within #<Capybara::Node::Element tag="div" path="//HTML[1]/BODY[1]/DIV[1]/DIV[1]/DIV[4]/DIV[1]/DIV[1]/DIV[1]/DIV[2]/DIV[2]/DIV[1]/FORM[1]/DIV[1]/DIV[1]">
```

File: spec/support/request/web_helper.rb [hunk 2]
```diff
@@ -128,9 +128,11 @@ def close_select2
   end
 
   def tomselect_search_and_select(value, options)
-    page.find("[name='#{options[:from]}']").sibling(".ts-wrapper").click
-    page.find(:css, '.ts-dropdown input.dropdown-input').set(value)
-    page.find(:css, '.ts-dropdown .ts-dropdown-content .option', text: value).click
+    tomselect_wrapper = page.find("[name='#{options[:from]}']").sibling(".ts-wrapper")
```
Comment (ashwini-seshadri) [inline spec/support/request/web_helper.rb:131]: I think we have to do this instead of full page, since a page could contain multiple tom select elements and we might end up targeting wrong element.

**Review by mkllnk — APPROVED** [review]
Thank you! The code looks good to me. Let's see what @jibees says.

File: app/views/admin/subscriptions/index.html.haml [hunk 3]
```diff
@@ -6,7 +6,7 @@
 
 - content_for :page_actions do
   %li{ "data-controller": "help-modal-link", "data-action": "click->help-modal-link#open", "data-help-modal-link-target-value": "new_subscription_help_modal" }
-    %a.button.icon-plus#new-subscription
+    %a.button.icon-plus#new-subscription{ href: "javascript:void(0)" }
```
Comment (jibees) [inline app/views/admin/subscriptions/index.html.haml:9]: Not sure to understand this change?

File: spec/support/request/web_helper.rb (hunk 2 above)
Comment (jibees) [reply spec/support/request/web_helper.rb:131]: Yep. I think you're right.

**Review by jibees — CHANGES_REQUESTED** [review]
Quick comments below on commits, and general comments:

 - I think you should at least delete the second commit which is a bad merge commit, and probably squash the two commits into one because the last is only "fix specs".
 - Outside purely code review, I see : 
   - you mention a green arrow. Where does it comes? Sounds like they should not appear here right?
   - I think that text is center aligned in the dropdown. I don't think it's the way to go, as in other place, the text is left aligned.

File: app/views/admin/subscriptions/index.html.haml (hunk 3 above)
Comment (ashwini-seshadri) [reply app/views/admin/subscriptions/index.html.haml:9]: The capybara spec was unable to target the link.

Comment (mkllnk) [reply app/views/admin/subscriptions/index.html.haml:9]: We shouldn't change the code for no other benefit than making a spec work. I could imagine that Capybara expects an `href` to use `click_link`. But could you use `find(...).click`?

**Comment by ashwini-seshadri** [comment]
> Quick comments below on commits, and general comments:
> 
> * I think you should at least delete the second commit which is a bad merge commit, and probably squash the two commits into one because the last is only "fix specs".
> * Outside purely code review, I see :
>   
>   * you mention a green arrow. Where does it comes? Sounds like they should not appear here right?
>   * I think that text is center aligned in the dropdown. I don't think it's the way to go, as in other place, the text is left aligned.

Hi, @jibees I have squashed all the commits into a single commit.
I have changed the text alignment to left in the dropdown.
I have also fixed the green arrow by changing it's z-index to 0 which was coming from [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/9702/files#diff-80b53678d55024c2f3c7aeb1b19f22f04b281182b214545137be31f6a152ee8cR161)

**Review by jibees — APPROVED** [review]
Nice 💪 
Thanks a lot @ashwini-seshadri !
Moving to `test ready`

**Comment by filipefurtad0** [comment]
Hey @ashwini-seshadri ,
Welcome :wave: 

Thanks for picking this up, I've verified the issue prior to staging and checked that your PR fixes it after staging it:

[Screencast from 30-09-2022 13:29:30.webm](https://user-images.githubusercontent.com/49817236/193270291-803d3943-3fbc-4f5b-aa33-5e803b05b934.webm)

Many thanks! Merging.

**Comment by drummer83** [comment]
@ashwini-seshadri I have just used this new functionality for the first time! It's amazing!
Thank you again! :tada:
