### PR TITLE
[Spree Upgrade] Fix Product model spec and small refactoring in VariantStock

### LINKED ISSUE #3036: [Spree Upgrade][FrontOffice] Fix orders_controller spec, insuficient stock spec (1 broken test)
Fix spec/controllers/spree/orders_controller_spec.rb:135

```
58) Spree::OrdersController viewing cart when an item has insufficient stock displays a flash message when we view the cart
      Failure/Error: expect(flash[:error]).to eq("An item in your cart has become unavailable.")
      
        expected: "An item in your cart has become unavailable."
             got: nil
      
        (compared using ==)
      # ./spec/controllers/spree/orders_controller_spec.rb:135:in `block (4 levels) in <top (required)>'

```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Part of #2804 (fixes 2 of the 10 tests)
See commit messages.
Also, closes #3036 by fixing a typo in #3100

#### What should we test?
spec/controllers/spree/orders_controller_spec.rb:135 and product_spec.rb:120, product_spec:126  should be green now.

### CODE REVIEW

**Comment by luisramos0** [comment]
I've added a new commit to fix a typo in #3100 that will close #3036

File: app/models/concerns/variant_stock.rb [hunk 1]
```diff
@@ -130,9 +130,13 @@ def raise_error_if_no_stock_item_available
...
   def overwrite_stock_levels(new_level)
-    # There shouldn't be any other stock items, because we should
-    # have only one stock location.
-    stock_items.first.__send__(:count_on_hand=, new_level)
+    stock_item.__send__(:count_on_hand=, new_level)
+  end
+
+  # There shouldn't be any other stock items, because we should
+  # have only one stock location.
+  def stock_item
```
Comment (sauloperez) [inline app/models/concerns/variant_stock.rb]: :ok_hand:
