### PR TITLE
Faster page loads for previously unusable Enterprise Fee reports

### LINKED ISSUE #13625: Some Enterprise Fee reports are unusable when managing big shops
## Description
The reports "Enterprise Fee Summary" / "Enterprise Fees With Tax Report By Order" and "Enterprise Fees With Tax Report By Producer" are unusable, 
System error 500 page is displayed after a 2 minutes timeout

## Expected Behavior
A form is displayed to configure the report parameters

## Actual Behaviour
System error 500 page is displayed after a 2 minutes timeout

## Steps to Reproduce
1. You must be manager of the "Au local" shop (ID OFN 922, FR instance), contact me (laurent.measson@coopcircuits.fr or Slack @Laurent Measson ) in order to be added.
2. Select "Enterprise Fee Summary" / "Enterprise Fees With Tax Report By Order"
3. System error 500 page is displayed after a 2 minutes timeout

## Animated Gif/Screenshot
Image

## Workaround
No workaround found

## Severity
bug-s2

## Your Environment
Reproduced on :
Firefox 143.0.3 Ubuntu 24.93.3 LTS
Firefox 144.0 arm64 and Safari 26.0.1 - MacOS 15.7.1 (Apple M1)

## Possible Fix
Seems to be a long request running on database, because this problem appears on huge shops only

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #13625

This PR introduces **AJAX-powered search for report filters** on Enterprise Fee–related reports, replacing large preloaded datasets with paginated, server-side queries.

Previously, report filters (enterprise fees, fee owners, distributors, suppliers, order cycles, and customers) were populated eagerly in the view using helper methods and in-memory collections. This caused:
- Slow page loads on instances with large datasets, such that timeout errors occurred
- Heavy memory usage
- Poor UX when selecting from long dropdowns

To solve this, this PR:
- Adds a reusable `Reports::AjaxSearch` concern to handle paginated, filtered JSON responses for Select2
- Uses the Stimulus `tom-select` controller with in-memory caching and Rails-compatible multi-select submission
- Updates report filter views to use AJAX-backed TomSelect fields
- Removes now-unused helper methods that eagerly loaded options
- Updates permissions and routes to safely expose the new search endpoints
- Adds comprehensive controller and JavaScript tests to ensure correctness

This results in faster report pages, scalable filtering, and a cleaner separation of concerns between backend querying and frontend UI behavior.

---

#### What should we test?

- Visit **Enterprise Fees With Tax (by Order)** report
  - Verify distributor, order cycle, fee name, fee owner, and customer filters load results via AJAX
  - Ensure typing filters results correctly
  - Confirm multiple selections work and submit correctly
- Visit **Enterprise Fees With Tax (by Producer)** report
  - Verify distributor, supplier, order cycle, fee name, fee owner, and customer filters behave correctly
- Confirm previously selected filter values remain selected after form submission
- Validate pagination works when scrolling through Select2 results

---

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/webpacker/controllers/select2_ajax_controller.js [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+export default class extends Controller {
+  static values = {
+    url: String,
+  };
+
+  connect() {
+    if (typeof $ === "undefined" || typeof $.fn.select2 === "undefined") {
+      console.error("Select2 AJAX Controller: jQuery or Select2 not loaded");
+      return;
+    }
```
Comment (rioug) [inline app/webpacker/controllers/select2_ajax_controller.js]: I really don't like the idea of mixing Stimulus and JQuery. I think we should move away from JQuery when possible. And also, we now use TomSelect as a replacement for Select2. Is there anyway you could do the same thing in with TomSelect ? It also supports using remote data : https://tom-select.js.org/examples/remote/

Comment (dacook) [reply app/webpacker/controllers/select2_ajax_controller.js]: I agree that we are wanting to move from Select2 to TomSelect (although we haven't reviewed this decision for a long time).

I took a look at that link and TomSelect also supports remote searching, so you would be able to use the same backend implementation, and it should simplify the JS implementation a lot, so I agree with Gaetan.

File: app/controllers/concerns/reports/ajax_search.rb [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+
+    def enterprise_fee_owner_ids(orders)
+      EnterpriseFee.where(id: enterprise_fee_ids(orders)).select(:enterprise_id)
+    end
+
+    def enterprise_fee_ids(orders)
+      Spree::Adjustment.enterprise_fee.where(order_id: orders.select(:id)).select(:originator_id)
+    end
+  end
+end
```
Comment (dacook) [inline app/controllers/concerns/reports/ajax_search.rb:108]: If it doesn't depend on the ReportsController, I think this could have been neater as a separate controller (for example Reports::SearchController). But I don't think it's necessary to change now.

**Comment by chahmedejaz** [comment]
Sure @rioug and @dacook . Thanks for the feedback. I'll replace the select2 with TomSelect. 👍🏻

**Comment by chahmedejaz** [comment]
@dacook @rioug - Sorry for getting back to this late... TomSelect doesn't support pagination on remote data fetching, so it took a bit of time researching and implementing the select2-like solution with tom-select. Now it's ready for review here in these commits:

- https://github.com/openfoodfoundation/openfoodnetwork/pull/13823/changes/77fe1fa6f9306d38466bb97a3db47df612fa424e
- https://github.com/openfoodfoundation/openfoodnetwork/pull/13823/commits/d4811648f17a2de29d6ee4da47fc9f491a21cdf1
- https://github.com/openfoodfoundation/openfoodnetwork/pull/13823/changes/b58834b11f3d15e8cf2f3abe7a23402a9378a887

File: spec/javascripts/stimulus/tom_select_controller_test.js [hunk 3]
```diff
@@ -0,0 +1,318 @@
+/**
+ * @jest-environment jsdom
+ */
+
+import { Application } from "stimulus";
+import tom_select_controller from "../../../app/webpacker/controllers/tom_select_controller.js";
```
Comment (rioug) [inline spec/javascripts/stimulus/tom_select_controller_test.js]: No need for the relative folder , `Jest` is configured to search for files in `app/webpacker' 
```suggestion
import tom_select_controller from "controllers/tom_select_controller.js";
```

File: spec/javascripts/stimulus/tom_select_controller_test.js [hunk 4]
```diff
@@ -0,0 +1,318 @@
...
+      expect(controller.page).toBe(2);
+
+      // Can update hasMore flag
+      controller.hasMore = false;
+      expect(controller.hasMore).toBe(false);
+
+      // Can track loading
+      controller.loading = true;
+      expect(controller.loading).toBe(true);
+    });
```
Comment (rioug) [inline spec/javascripts/stimulus/tom_select_controller_test.js]: I don't understand the point of these test, it just looks like you are testing variable allocation ? like:
```javascript
let x = 0;

x = 1;
expect(x).toBe(1);
```

File: spec/javascripts/stimulus/tom_select_controller_test.js [hunk 5]
```diff
@@ -0,0 +1,318 @@
...
+          id="test-select"
+          data-controller="tom-select"
+          data-tom-select-placeholder-value="Choose an option">
+          <option value="">-- Select --</option>
+          <option value="1">Option 1</option>
+          <option value="2">Option 2</option>
+        </select>
+      `;
+
+      await new Promise((resolve) => setTimeout(resolve, 0));
```
Comment (rioug) [inline spec/javascripts/stimulus/tom_select_controller_test.js]: Why do we need this ? as far as I can tell, it doesn't do anything ?

File: app/webpacker/controllers/tom_select_controller.js [hunk 6]
```diff
@@ -29,4 +39,144 @@ export default class extends Controller {
     const optionsArray = [...this.element.options];
     return optionsArray.find((option) => [null, ""].includes(option.value))?.text;
   }
+
+  #addRemoteOptions(options) {
```
Comment (rioug) [inline app/webpacker/controllers/tom_select_controller.js:85]: There is a lot going on in here, would it be possible to extract at least `buildUrl` and `fetchOptions` and move them to their own method ? I think it would make `#addRemoteOptions` easier to read ?

File: spec/javascripts/stimulus/tom_select_controller_test.js [hunk 7]
```diff
@@ -0,0 +1,318 @@
...
+      expect(controller.scrollAttached).toBe(true);
+      expect(addEventListenerSpy).toHaveBeenCalledWith("scroll", expect.any(Function));
+
+      // Does not attach multiple times
+      controller.control.settings.onDropdownOpen();
+      expect(addEventListenerSpy).toHaveBeenCalledTimes(1);
+    });
+  });
+
+  describe("infinite scroll (#fetchNextPage)", () => {
```
Comment (rioug) [inline spec/javascripts/stimulus/tom_select_controller_test.js]: I don't think we are testing the infinite scrolling with interactions like a user would do. I recently introduced the dom testing library : https://testing-library.com/docs/dom-testing-library/intro that should help with testing such things. Could you give this a go ? You can have a look at this for inspiration : https://github.com/openfoodfoundation/openfoodnetwork/blob/7bfe51d067b470a0bff32bc8fe780c7e447dd693/spec/javascripts/stimulus/tag_list_input_controller_test.js#L460

File: spec/javascripts/stimulus/tom_select_controller_test.js [hunk 8]
```diff
@@ -0,0 +1,252 @@
...
+  Object.defineProperty(dropdown, "clientHeight", {
+    configurable: true,
+    value: clientHeight,
+  });
+
+  Object.defineProperty(dropdown, "scrollTop", {
+    configurable: true,
+    writable: true,
+    value: scrollTop,
+  });
```
Comment (chahmedejaz) [inline spec/javascripts/stimulus/tom_select_controller_test.js:61]: `jsdom` doesn’t implement layout-related properties (_like scrollHeight, clientHeight, or offsetHeight_). However, Tom Select’s remote data fetching on scroll relies heavily on these values to determine when the user has reached the bottom.

Because of this, simply dispatching a scroll event in tests wasn’t enough—scrolling to the bottom never triggered the next fetch call.

After digging into the Tom Select source code, I found the exact layout properties it checks internally. Mocking those properties manually in jsdom was necessary to reproduce the real scroll behavior and correctly trigger the remote fetch.

**Comment by chahmedejaz** [comment]
Thanks for pointing that out, @rioug.

I had already reviewed `virtual_scroll`. Initially, it appeared to be purely a rendering optimization—only displaying the visible options—so I didn’t think it explicitly supported pagination. After reviewing it again, I realized it can replace the manual scroll event handling, so I’ve now incorporated it.

I’ve also addressed the other comments related to specs and refactoring of the controller. Could you please review the changes here:

- https://github.com/openfoodfoundation/openfoodnetwork/pull/13823/changes/5f31baa022703fa5052438094ee012e319a1f28f
- https://github.com/openfoodfoundation/openfoodnetwork/pull/13823/changes/8eb9709a04866448d1bde820d6ede71428709149

Thanks again for the feedback!

**Review by rioug — APPROVED** [review]
Thanks @chahmedejaz ! It looks good now, it's much easier to follow what's going on.

File: app/components/searchable_dropdown_component/searchable_dropdown_component.html.haml [hunk 9]
```diff
@@ -1 +1,4 @@
-= f.select name, options_for_select(options, selected_option), { include_blank: }, class: classes, data:, 'aria-label': aria_label, **other_attrs
+- if uses_form_builder?
+  = f.select name, options, { selected: selected_option, include_blank:, multiple: }, class: classes, data:, 'aria-label': aria_label, **other_attrs
+- else
+  = select_tag name, options_for_select(options, selected_option), include_blank: include_blank, multiple: multiple, class: classes, data: data, 'aria-label': aria_label, **other_attrs
```
Comment (dacook) [inline app/components/searchable_dropdown_component/searchable_dropdown_component.html.haml]: I notice that most of these options are the same. It may not be worth DRYing them in this case, but at least we could remove a couple of duplicated words:

```suggestion
  = select_tag name, options_for_select(options, selected_option), include_blank:, multiple:, class: classes, data:, 'aria-label': aria_label, **other_attrs
```

(For bonus points, consider renaming `classes` to `class` ;)

File: app/webpacker/controllers/tom_select_controller.js [hunk 10]
```diff
@@ -29,4 +39,54 @@ export default class extends Controller {
...
+          const currentPage = parseInt(currentUrl.searchParams.get("page") || "1");
+          const nextUrl = this.#buildUrl(query, currentPage + 1);
+          this.control.setNextUrl(query, nextUrl);
+        }
+
+        callback(json.results || []);
+      })
+      .catch(() => {
+        callback();
+      });
```
Comment (dacook) [inline app/webpacker/controllers/tom_select_controller.js]: It looks like any errors (eg server error or network error) will be treated the same as 0 results. This could be confusing and make it hard to work out what's going on.

Generally for AJAX calls, I consider it worth notifying the user that there's something wrong, and would use a general handler like `showHttpError` (search codebase). It shows a crude browser popup, but I think it's ok for these exceptions. What do you think?

File: config/routes/admin.rb [hunk 11]
```diff
@@ -137,6 +137,12 @@
     end
 
     get '/reports', to: 'reports#index', as: :reports
+    get '/reports/search_enterprise_fees', to: 'reports#search_enterprise_fees', as: :search_enterprise_fees_reports
+    get '/reports/search_enterprise_fee_owners', to: 'reports#search_enterprise_fee_owners', as: :search_enterprise_fee_owners_reports
+    get '/reports/search_distributors', to: 'reports#search_distributors', as: :search_distributors_reports
+    get '/reports/search_suppliers', to: 'reports#search_suppliers', as: :search_suppliers_reports
+    get '/reports/search_order_cycles', to: 'reports#search_order_cycles', as: :search_order_cycles_reports
+    get '/reports/search_order_customers', to: 'reports#search_order_customers', as: :search_order_customers_reports
```
Comment (dacook) [inline config/routes/admin.rb]: These all follow the same pattern, so I'm wondering if they can be grouped together better. If nothing else, they could be nested under `namespace :reports`. IE:


```suggestion
    namespace :reports
      get '/search_enterprise_fees', to: 'reports#search_enterprise_fees', as: :search_enterprise_fees_reports
      get '/search_enterprise_fee_owners', to: 'reports#search_enterprise_fee_owners', as: :search_enterprise_fee_owners_reports
      get '/search_distributors', to: 'reports#search_distributors', as: :search_distributors_reports
      get '/search_suppliers', to: 'reports#search_suppliers', as: :search_suppliers_reports
      get '/search_order_cycles', to: 'reports#search_order_cycles', as: :search_order_cycles_reports
      get '/search_order_customers', to: 'reports#search_order_customers', as: :search_order_customers_reports
   end
```

File: spec/controllers/admin/reports_controller_spec.rb [hunk 12]
```diff
@@ -368,4 +368,117 @@
       end
     end
   end
+
```
Comment (dacook) [inline spec/controllers/admin/reports_controller_spec.rb]: I think we are generally preferring to write request specs instead of new controller specs. But I can't find any documentation saying that, so I will discuss in Slack for future reference!

File: spec/controllers/admin/reports_controller_spec.rb [hunk 13]
```diff
@@ -368,4 +368,117 @@
...
+          :search_enterprise_fees,
+          report_type: :enterprise_fee_summary,
+          report_subtype: :enterprise_fees_with_tax_report_by_order
+        )
+
+        expect(response).to have_http_status(:ok)
+        json_response = response.parsed_body
+
+        names = json_response["results"].pluck("label")
+        expect(names).to eq(['Admin Fee', 'Delivery Fee'])
```
Comment (dacook) [inline spec/controllers/admin/reports_controller_spec.rb]: Perhaps we should test that a non-linked fee doesn't display here too?

File: spec/javascripts/stimulus/tom_select_controller_test.js [hunk 14]
```diff
@@ -0,0 +1,252 @@
...
+      fetch.mockRejectedValueOnce(new Error("Network error"));
+
+      openDropdown();
+
+      await waitFor(() => {
+        expectEmptyDropdown();
+      });
+    });
+  });
+});
```
Comment (dacook) [inline spec/javascripts/stimulus/tom_select_controller_test.js:296]: 💯 Well done, that was tricky to test. It's great to have specs around this!

File: app/models/spree/ability.rb [hunk 15]
```diff
@@ -260,7 +260,9 @@ def add_product_management_abilities(user)
       can [:admin, :index, :import], ::Admin::DfcProductImportsController
 
       # Reports page
-      can [:admin, :index, :show, :create], ::Admin::ReportsController
+      can [:admin, :index, :show, :create, :search_enterprise_fees, :search_enterprise_fee_owners,
+           :search_distributors, :search_suppliers, :search_order_cycles, :search_order_customers],
+          ::Admin::ReportsController
```
[the remark this answers is not in the document]
Comment (dacook) [reply app/models/spree/ability.rb]: Nice pickup. Search for `ReportsController` below.

File: app/controllers/concerns/reports/ajax_search.rb [hunk 16]
```diff
@@ -0,0 +1,105 @@
...
+    end
+
+    private
+
+    def build_search_response(query)
+      page = (params[:page] || 1).to_i
+      per_page = 30
+
+      filtered_query = apply_search_filter(query)
+      total_count = filtered_query.size
```
[the remark this answers is not in the document]
Comment (chahmedejaz) [reply app/controllers/concerns/reports/ajax_search.rb:54]: @dacook — As per my understanding, using `.size` is preferable to `.count` because it’s smarter about how it calculates the result.

`.size` will issue a `COUNT(*)` (_which returns the total number of rows_) query only when the records are not already loaded. If the association is already in memory, it simply counts the in-memory collection and avoids an extra DB query altogether.  
Ref: https://apidock.com/rails/ActiveRecord/Associations/AssociationCollection/size

Additionally, `filtered_query` has some queries where we explicitly select specific columns like `id` or `name` (_I think it's for customer query_). Calling `.count` in this case attempts to generate `COUNT(id, name)`, which results in an invalid SQL query. In contrast, `.size` falls back to `COUNT(*)`, which correctly returns the total number of rows — exactly what we need for this use case.

File: app/views/admin/reports/filters/_enterprise_fees_with_tax_report_by_producer.html.haml [hunk 17]
```diff
@@ -1,27 +1,57 @@
...
+      selected_option: params.dig(:q, :distributor_id_in),
+      multiple: true,
+      remote_url: admin_search_distributors_reports_url))
 .row
   .alpha.two.columns= label_tag nil, t(:report_producers)
-  .omega.fourteen.columns= select_tag(:supplier_id_in, options_from_collection_for_select(@data.orders_suppliers, :id, :name, params[:supplier_id_in]), {class: "select2 fullwidth", multiple: true})
+  .omega.fourteen.columns
+    = render(SearchableDropdownComponent.new(name: :supplier_id_in,
+      options: [],
+      selected_option: params.dig(:supplier_id_in),
```
[the remark this answers is not in the document]
Comment (chahmedejaz) [reply app/views/admin/reports/filters/_enterprise_fees_with_tax_report_by_producer.html.haml:16]: @dacook - It's already handled here: https://github.com/openfoodfoundation/openfoodnetwork/pull/13823/changes#diff-15b59cc0d1592241bb558db7b9a7aad77370ae7abb6ffdde9064cb8203bea2bcR4
using multiple in the select element automatically appends `[]` in the name.

Plus we can't use form here because the existing backend filtering doesn't take `supplier_id_in` from `q` param key. It directly uses `supplier_id_in` from the `params`.

File: app/controllers/concerns/reports/ajax_search.rb (hunk 16 above)
[the remark this answers is not in the document]
Comment (dacook) [reply app/controllers/concerns/reports/ajax_search.rb:54]: Oh you're right. Bad AI! It was completely wrong:

> Using `.size` on an ActiveRecord relation can load all records into memory to count them

File: app/components/searchable_dropdown_component/searchable_dropdown_component.html.haml (hunk 9 above)
Comment (chahmedejaz) [reply app/components/searchable_dropdown_component/searchable_dropdown_component.html.haml]: @dacook - `classes` cannot be renamed to `class` as it's a reserved ruby word for defining class I belive 😅 
Rest are addressed 👍

**Comment by chahmedejaz** [comment]
Hi @dacook - Thanks for the feedback.
I've addressed them here:
https://github.com/openfoodfoundation/openfoodnetwork/pull/13823/changes/8eb9709a04866448d1bde820d6ede71428709149..7c0586db7b9b53de1cd5396669ef1bb043dc834b

It's ready for review. Thanks

File: app/components/searchable_dropdown_component/searchable_dropdown_component.html.haml (hunk 9 above)
Comment (dacook) [reply app/components/searchable_dropdown_component/searchable_dropdown_component.html.haml]: 😅 Oh yeah, I forgot sorry!

File: app/webpacker/controllers/tom_select_controller.js [hunk 18]
```diff
@@ -85,6 +95,19 @@ export default class extends Controller {
...
+    }.bind(this);
+
+    options.onType = function () {
+      this.openedByClick = false;
+    }.bind(this);
+
+    // As per TomSelect source code, no result feedback after API call is shown when this callback returns true.
+    options.shouldLoad = function (query) {
+      return this.openedByClick || query.length > 0;
+    }.bind(this);
```
Comment (dacook) [inline app/webpacker/controllers/tom_select_controller.js:109]: I don't quite understand the purpose of this. I guess it means that after typing a query, then deleting it, TomSelect will avoid re-loading. Is this because the unfiltered data has already been loaded?

File: spec/controllers/admin/reports_controller_spec.rb (hunk 12 above)
Comment (dacook) [reply spec/controllers/admin/reports_controller_spec.rb]: Sorry, I wasn't very clear. I didn't mean that you have to change it. 
But it's great that you have taken the opportunity to, and I see you also added tests for pagination 💯

File: app/webpacker/controllers/tom_select_controller.js (hunk 18 above)
Comment (dacook) [reply app/webpacker/controllers/tom_select_controller.js:109]: thanks for adding the comment! It would have helped me if it was included with the other commit (you can use git interactive rebase to update previous commits)

**Comment by chahmedejaz** [comment]
Thanks, David. I'll keep these in mind for the future commits. 👍🏻

**Review by rioug — APPROVED** [review]

**Comment by AMEA-LYON** [comment]
Hey @chahmedejaz ,

Thank you so much for the great job, 
the timeout error is now gone and the usability of these reports is improved a lot,

It is good to go ! Thank you ! 🎉 👍 

Before :
capture_erreur

After : 
capture_resultat

A few remarks : 
- Customers results have duplicates (as you can see in the screenshot), I will issue a new PR for this, as it is not a regression
- Other reports could greatly benefit of this improvment, is it a big amount of work to implement these changes ?
- when I select a hub, other popup fields (order cycle, customer, for example) still have all the results, not just the one related to the selected hub(s), i would like to issue a PR, but it seems to be a significant evolution, as I have noticed this behavior in many parts of the application, can you confirm that for me ?

**Comment by chahmedejaz** [comment]
Thanks for the detailed feedback @AMEA-LYON. 

> Customers results have duplicates (as you can see in the screenshot), I will issue a new PR for this, as it is not a regression

I'll look into these on the server, but my hunch is that these are different customers with the same email address. But I'll still confirm it.

>Other reports could greatly benefit of this improvment, is it a big amount of work to implement these changes?

Yes, now we can easily use these on other reports as well. It's not a big effort now, as most of the work is generic and can easily be utilized there.  

> when I select a hub, other popup fields (order cycle, customer, for example) still have all the results, not just the one related to the selected hub(s), i would like to issue a PR, but it seems to be a significant evolution, as I have noticed this behavior in many parts of the application, can you confirm that for me?

As far as I know, these filter fields are independent of the hub selection and show all the options as per the permissions of the logged in user. However, @RachL can still confirm the expected behavior for this better. Thanks

**Comment by RachL** [comment]
> can still confirm the expected behavior for this better. 

Yes I'm afraid that this is the current behavior for our dropdowns. If we can slowly change this, it could help users. 

is this something we can open as good first issue @chahmedejaz or is this tricky? we could then open one issue per page

pinging @mariocarabotta for info.

On another note this looks ready to go!! Merging :rocket:

**Comment by chahmedejaz** [comment]
>is this something we can open as good first issue @chahmedejaz or is this tricky? we could then open one issue per page

Yes, @RachL - For the same dropdown filters we have on the affected reports of this issue, they could be easily replaced on other report pages as well. We can open good first issues for them.
