### PR TITLE
[White Label] Remove ofn navigation for small width screens as well when option is activated

### LINKED ISSUE #10900: White Label: Remove OFN navigation for small width screens
## Description

OFN navigation on large screens is hidden when the White Label feature is activated. However on small screens the navigation is still shown in the side menu.

## Expected Behavior

OFN navigation should be hidden on small screens as well. This includes (on staging AU, names depend on the instance settings):
- Shops
- Map
- Producers
- About
- Learn

## Actual Behaviour

All menu items are shown on small screens in the side menu.

## Steps to Reproduce

1. Activate 'Hide OFN navigation' in the White Label settings of an enterprise.
2. Visit the white labelled shopfront.
3. Reduce screen size until the side menu (burger menu) appears.
4. Open the menu.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/296452/413ef328-e214-460b-a196-dd76ac28d1ff

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10900 
##### Before
Capture d’écran 2023-06-05 à 14 49 01

##### After
Capture d’écran 2023-06-05 à 14 46 27

#### What should we test?

- As a shop manager, hide OFN navigation for you enterprise under white label settings
- As a consumer, with a small width screen, check that you cannot see the OFN navigation on the right pages (shop, cart, checkout, order confirmation for the shop)

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/support/request/ui_component_helper.rb [hunk 1]
```diff
@@ -1,11 +1,21 @@
 # frozen_string_literal: true
 
 module UIComponentHelper
+  def browser_as_small
```
Comment (mkllnk) [inline spec/support/request/ui_component_helper.rb:4]:
```suggestion
  def browse_as_small
```

File: spec/system/consumer/white_label_spec.rb [hunk 2]
```diff
@@ -29,20 +30,87 @@
...
+          expect(page).not_to have_selector "a[href='#{main_app.map_path}']"
+          expect(page).not_to have_selector "a[href='#{main_app.producers_path}']"
+          expect(page).not_to have_selector "a[href='#{main_app.groups_path}']"
+          expect(page).not_to have_selector "a[href='#{I18n.t('.menu_5_url')}']"
+        end
+      end
+    end
+  end
+
+  shared_examples "does not hides the OFN navigation for mobile view as well" do
```
Comment (mkllnk) [inline spec/system/consumer/white_label_spec.rb:56]:
```suggestion
  shared_examples "does not hide the OFN navigation for mobile view as well" do
```

**Review by mkllnk — APPROVED** [review]
Great work. Excellent test coverage. I wonder though if we need all those tests. System specs are quite expensive as they add to the runtime. And I found a couple of typos. :wink: That doesn't need to block the rollout though.

**Comment by mkllnk** [comment]
I couldn't resist to fix the typos and simplify the screen size switching.

**Review by jibees — COMMENTED** [review]
Thanks a lot ! 👌 
(and sorry for the typo...)

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Comment by drummer83** [comment]
Hi @jibees,
Thanks for this one!

### Before staging

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/5ad082bb-73c8-4fc7-9070-5dfdb47c2adc

### After staging

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/ccf639e0-d366-41c9-8a06-e783a2bbad0e

- The navigation is hidden on large screens. :heavy_check_mark: 
- The navigation is hidden on small screens. :heavy_check_mark: 
- The navigation is only hidden when 'Hide OFN navigation' is activated. :heavy_check_mark: 
- The navigation is hidden on the relevant pages (shopfront, cart, checkout, confirmation). :heavy_check_mark: 

Great! I think this one can be merged! :muscle: 
Thanks again!
