### PR TITLE
Return if variant is deleted

### LINKED ISSUE #9054: Cannot update subscription after product deleted
## Description
When editing a subscription, if you want to remove a product where that product has been discontinued or deleted, you cannot delete it from the subscription. When you delete the product, and then click save, you get an error message 'There are no open or upcoming order cycles for this product'.
If you try adding new products and click save, it appears to work, but when you refresh and go back to the subscription, the new products are not there, and the deleted product/s is still there

Cannot delete and save or add in a replacement product, which leads to having to delete the whole subscription and create a new one.

## Expected Behavior
Should be able to delete products that have been deleted, and add new products

## Actual Behaviour
When you try to delete a product, you get an error message
If you try to add a new or updated product, it will not stay in the subscription after clicking save and refreshing page

## Steps to Reproduce
1. Created a subscription with a live product (almond milk) in a fake shop
2.Deleted product (almond milk) that was in the subscription
3.Tried to delete the deleted product (almond milk) from the subscription and add a new product (beetroot)
4.Refresh page, go back into subscription, deleted product (almond milk) is still there with error, added product (beetroot) is no longer in the subscription

## Animated Gif/Screenshot
Screen Shot 2022-03-31 at 3 49 04 pm

Screen Shot 2022-03-31 at 3 49 21 pm

## Workaround
Recreate a whole new subscription

## Severity
s3

## Your Environment
Multiple computers and browsers

### PR DESCRIPTION
**Pull request by georgethoppil**
#### What? Why?

Closes #9054 
Cannot update subscription after product deleted

#### What should we test?
1. Created a subscription with a live product (almond milk) in a fake shop
2.Deleted product (almond milk) that was in the subscription
3.Tried to delete the deleted product (almond milk) from the subscription and add a new product (beetroot)
4.Refresh page, go back into subscription, deleted product (almond milk) is still there with error, added product (beetroot) is no longer in the subscription

### CODE REVIEW

File: engines/order_management/app/services/order_management/subscriptions/validator.rb [hunk 1]
```diff
@@ -107,7 +107,7 @@ def requested_variants_available?
       end
 
       def verify_availability_of(variant)
-        return if available_variant_ids.include? variant.id
+        return if (available_variant_ids.include? variant.id) || variant.deleted_at.present?
```
Comment (mkllnk) [inline engines/order_management/app/services/order_management/subscriptions/validator.rb:110]: This now reads as: "Deleted variants are available." I would imagine that you can now add deleted variants to a subscription as well, right?

While this seems to be the simplest fix, I wonder if it would make more sense to modify `requested_variants_available?`. That method checks all items:
https://github.com/openfoodfoundation/openfoodnetwork/blob/67d3bd7414fc8def66996b800444de0a02b1b378/engines/order_management/app/services/order_management/subscriptions/validator.rb#L105-L107

Instead of checking all items, it could ignore items that are marked for destruction.

We have similar logic already:
https://github.com/openfoodfoundation/openfoodnetwork/blob/67d3bd7414fc8def66996b800444de0a02b1b378/engines/order_management/app/services/order_management/subscriptions/validator.rb#L99-L103

It may be worth introducing a new method, for example:
```rb
      def persisting_line_items
        subscription_line_items.except(&:marked_for_destruction?)
      end
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
Great to see how you navigate complicated code. I got an idea for a better solution below though.

And I think that you could improve the commit message:

> Return if variant is deleted

That is describing exactly what the code is telling us already. I find it more helpful to explain *why* a change happened and what the benefit is. Especially if you use the same message in the pull request title because we copy those to our release notes which are eventually read by end users.

I would suggest something like this:

> Allow update of subscriptions containing deleted products

This wording is much closer to the issue description which was written by our customer support. As you can imagine, customer support talks to customers every day and uses the same *language*.

File: engines/order_management/app/services/order_management/subscriptions/validator.rb (hunk 1 above)
Comment (georgethoppil) [reply engines/order_management/app/services/order_management/subscriptions/validator.rb]: Thanks for the help on this 👍

**Comment by georgethoppil** [comment]
Will make sure that commits are more clearer in the future

**Comment by georgethoppil** [comment]
@mkllnk added the system test

**Review by mkllnk — APPROVED** [review]
Great!

**Comment by filipefurtad0** [comment]
Hey @georgethoppil ,

Thanks for this PR - this looks good:

Before this PR:

Peek 2022-04-28 10-52

After this PR:

Peek 2022-04-28 11-08

I've noticed though, that the new product still can't be edited, although at first it does look successful:

Peek 2022-04-28 11-18

So, I'd say we can merge this PR, but one an issue to address this - before that I'll investigate a bit further on under which conditions are admins able to add new items to orders - I thought always. To be investigated.

Thanks, moving to ready to go and merging after I've clarified the point above.

**Comment by filipefurtad0** [comment]
Ok, it seems that after the PR, we can't add new line items to the subscription, **during the time** in which the order cycle is open. This works as before, **before** the OC opens, and **after** it closes. So, would not consider this a regression, and actually the correct behavior.

When the OC opens orders are created with the items in the subscription. During this time orders can be edited, but as I understand it - please correct me if wrong @openfoodfoundation/train-drivers-product-owners - it does not make much sense to add items to the subscription, because the orders have been created already (during the time OC is open). It only makes sense to edit a subscription in the time window before or after the timeframe the OC is actually open.

I'll leave this PR on ready to go and await your feedback before merging.

**Comment by sigmundpetersen** [comment]
It says here https://guide.openfoodnetwork.org/basic-features/subscriptions/subscriptions-creating-and-managing-orders#edit-one-specific-order in the Note that one cannot add items to a specific order, I guess one that is ongoing. 

So I guess it is as it should be?

**Comment by filipefurtad0** [comment]
> So I guess it is as it should be?

I think so too. Thanks for digging that up from the user guide Sigmund. Merging.
