### PR TITLE
[Shopfront] Hide hub with "hide all references" setup in producers profiles

### LINKED ISSUE #9468: [Shopfront] Link to hub with "hide all references" setup is still displayed in producers profiles
## Description
Even if a hub selects the "hide all references" settings to make its shopfront completely invisible, the reference is still displayed in its producers profiles.

This impacts hubs that want their shops to remain private, for example hubs that have a pro and public shop, because they don't want customers to see that they apply different prices to their products. 

## Expected Behavior
Reference to the shop must be hidden everywhere (see issue #8896).

## Actual Behaviour
Reference is invisible in Producers tab but remains displayed in the producers profiles (popup of producers details), that can be accessed through:
- the [supplier shop page > Producers tab ](https://coopcircuits.fr/nouvelle/shop#/producers)> click on the supplier shop link > a popup will open, displaying the reference below "SHOP FOR XXX PRODUCTS AT:"
- another hub provided by the supplier > Producers tab > click on the supplier shop link > a popup will open, displaying the reference below "SHOP FOR XXX PRODUCTS AT:"

## Steps to Reproduce
1. Connect as admin or superadmin to a hub 
2. In admin dashboard > Enterprises settings, set "Visible in search?" to "Hide all references"
3. Go to one of the hub producer's shopfront (alternatively, go to another hub provided by the supplier)
4. Click on the "Producers" tab to display the producers list. 
5. Click on the supplier's link, this opens a popup with producers' details
6. You can see a link to the hub (below the label "SHOP FOR XXX PRODUCTS AT:")

## Animated Gif/Screenshot
This is a hub set up to "Hide all references" :
Screen Shot 2022-07-27 at 14 50 06

Connecting to another hub that shares the same supplier, the reference can be found in the "Producers" tab, by clicking on the supplier's link:
Screen Shot 2022-07-27 at 14 50 46

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Possible Fix
In the [shop page](https://coopcircuits.fr/testaude/shop#/producers), in Producers list, in the view that opens when clicking on a producer, hide references to shops that chose the "Hide all references" setting.

### PR DESCRIPTION
**Pull request by vsmay98**
#### What? Why?

Closes #9468 

#### What should we test?

- Connect as admin or superadmin to a hub
- In admin dashboard > Enterprises settings, set "Visible in search?" to "Hide all references"
- Go to one of the hub producer's shopfront (alternatively, go to another hub provided by the supplier)
- Click on the "Producers" tab to display the producers list.
- Click on the supplier's link, this opens a popup with producers' details
- You can see a link to the hub (below the label "SHOP FOR XXX PRODUCTS AT:")
- The hub with "Hide all references" should not be shown on the popup

#### Release notes

[Shopfront] Hide hub with "hide all references" setup in producers profiles

### CODE REVIEW

**Comment by mkllnk** [comment]
Let us know when this is ready for review.

**Comment by vsmay98** [comment]
Hello @mkllnk Please review this PR

File: app/serializers/api/enterprise_shopfront_serializer.rb [hunk 1]
```diff
@@ -63,7 +63,7 @@ def producers
 
     def hubs
       ActiveModel::ArraySerializer.new(
-        enterprise.distributors, each_serializer: Api::EnterpriseThinSerializer
+        enterprise.distributors.not_hidden, each_serializer: Api::EnterpriseThinSerializer
```
Comment (mkllnk) [inline app/serializers/api/enterprise_shopfront_serializer.rb:66]: This looks like it would work. Can you add a spec for it? You can add to `spec/serializers/api/enterprise_shopfront_serializer_spec.rb`. You would need to write a spec that fails without this change but then passes with this change. It needs to verify the absence of a hidden distributor.

Comment (vsmay98) [reply app/serializers/api/enterprise_shopfront_serializer.rb:66]: Sure @mkllnk

Comment (vsmay98) [reply app/serializers/api/enterprise_shopfront_serializer.rb:66]: Done @mkllnk Please re review

**Review by mkllnk — APPROVED** [review]
Great!
