### PR TITLE
Paypal stock clashes

### LINKED ISSUE #5953: Payment taken from customer by PayPal but no order created on platform
## Description

Customer placed an order with Tamar Valley Food Hub (UK) at 9:30 26/08/20 (end of their OC). She paid by Paypal and used Chrome browser.
1. First attempt at payment Paypal redirected customer back to basket as butternut squash was out of stock.  Customer amended order.
2. Customer submits order 2nd time. Time is now after 9:30 am.  Order does not go through. No order number generated. No customer order notification sent. No order generated in the admin section of OFN for Tamar.  (Order created later by Tamar in backoffice)
3. Customer receives receipt from Paypal for their order. Payment to Tamar went through- confirmed by Tamar.

Bugsnag report here:
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/5f2954c78473a50018ef45a9?filters%5Bevent.since%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.since%5D%5B%5D%5Bvalue%5D=30d&filters%5Berror.status%5D%5B%5D%5Btype%5D=eq&filters%5Berror.status%5D%5B%5D%5Bvalue%5D=open&filters%5Bevent.unhandled%5D%5B%5D%5Btype%5D=eq&filters%5Bevent.unhandled%5D%5B%5D%5Bvalue%5D=true&event_id=5f44cbb4005e08c5dcde0000

## Expected Behavior

Customer submits an order to a hub/shop after OC has closed.  Order fails and no payment is taken.

## Actual Behaviour

Customer submits and order to hub/shop shortly after OC has closed.  Order fails but PayPal (payment gateway) OKs the order and takes payment.

## Steps to Reproduce

1.
2.
3.
4.

## Severity

S3
## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

Chrome

## Possible Fix

slack thread: https://openfoodnetwork.slack.com/archives/CDLKH9MM0/p1598513843029000

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #5953

Fixes an issue where stock could be reduced to zero between the point a paypal payment was started and when it was finished. The result was that the order was no longer valid, so it would not be saved (and would disappear from the system) but the payment would come out of the user's account :grimacing: 

#### What should we test?

This will be an interesting one. Requires a Paypal test account. I'd say:

- Open up the edit page for a variant with low stock in one tab
- Add that variant to a cart in another tab
- Check out and use Paypal
- After submitting and going to the paypal form, but before submitting, switch to the other tab and set the stock to zero on the item
- Submit the Paypal form
- You should be redirected to the cart with the usual "out of stock" message
- The payment should not have been finalised

#### Release notes

Fixed an issue with paypal payments where items had gone out of stock at the point of payment processing

Changelog Category: Technical changes

### CODE REVIEW

**Comment by luisramos0** [comment]
At some point we have discussed bringing all that's needed from better_spree_paypal_express to OFN, there's not much left in there anyway. Maybe this is a good opportunity?

**Comment by Matt-Yorkley** [comment]
Yeah, I was thinking that as well. Adding more specs and trying to fix the bug are currently higher up my list though :sweat_smile:

**Comment by Matt-Yorkley** [comment]
I had to pull in another chunk of code from the spree paypal gem here to make these changes. We should probably pull it all in as with Bye Bye Spree, but I think it's worth doing in a separate issue/PR. All these Rubocop failures are from the imported Spree code... :point_up:

File: app/controllers/spree/paypal_controller_decorator.rb [hunk 1]
```diff
@@ -51,6 +56,32 @@ def express
...
+        token: params[:token],
+        payer_id: params[:PayerID]
+      }),
+      amount: @order.total,
+      payment_method: payment_method
+    })
+    @order.next
+    if @order.complete?
+      flash.notice = Spree.t(:order_processed_successfully)
+      flash[:commerce_tracking] = "nothing special"
```
Comment (andrewpbrett) [inline app/controllers/spree/paypal_controller_decorator.rb:77]: Is this flash not user-visible?

File: app/controllers/spree/paypal_controller_decorator.rb [hunk 2]
```diff
@@ -51,6 +56,32 @@ def express
     end
   end
 
+  def confirm
+    @order = current_order || raise(ActiveRecord::RecordNotFound)
+
+    # At this point the user has come back from the Paypal form, and we get one
+    # last chance to interact with the payment process before the money moves...
+    return handle_insufficient_stock unless sufficient_stock?
```
Comment (andrewpbrett) [inline app/controllers/spree/paypal_controller_decorator.rb:64]: Nice! Helpful comment :)

**Review by andrewpbrett — APPROVED** [review]
I don't have a very in-depth understanding of our PayPal flow (or the code that we're pulling in for it), but just looking at the diffs makes sense to me. I think it'd be not too tricky to test as long as there's a good PayPal test account we can use (similar to Stripe's test cards) - again, not very familiar with how we do that (yet).

**Review by luisramos0 — COMMENTED** [review]
I dont see anything suspicious so let's give it s good testing round :+1: 

This code is so poor! We should just move all of better_spree_paypal_express to OFN and improve it gradually :+1:

**Review by luisramos0 — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

Thanks for the detailed scenario - it was easy to reproduce in staging-FR:

1) Customer: Adding some items to the cart and proceeding to checkout
2) Customer: Checking out with Paypal. Logging in and filling in payment info.
3) Admin: reduce stock to zero
4) Customer: clicking "Pay now" leads to:

image

Bugsnag
https://app.bugsnag.com/open-food-france/coopcircuits/errors/5fac018dd077d20018bb74a8?event_id=5fbff2ed00659c7ea53f0000&i=sk&m=nw

This matches nicely with the Bugsnag error reported on the issue :+1: 

After staging the PR, step 4) above now leads directly to this:

image


However, the "Update" button seems to be missing, in the pic above. Running a similar stock conflict situation (with cash or other payment methods) leads to this:

image

But perhaps could still be improved, to allow the customer to correct the cart, which would be the usual behavior, as verified for other payment methods. But it prevents payments to occur with no orders, so I'd say the benefit is much bigger than the regression here.

Moving to ready to go - if you agree to merge this as is, I'll open an issue on this missing bit. What do you think?

File: app/controllers/spree/paypal_controller_decorator.rb (hunk 1 above)
Comment (sauloperez) [reply app/controllers/spree/paypal_controller_decorator.rb:77]: yes, and what's even that `:commerce_tracking`?

**Comment by sauloperez** [comment]
@Matt-Yorkley better_spree_paypal_express is not liking it when booting DJ. it's causing the <details>
<summary>stacktrace</summary>
bundler/gems/better_spree_paypal_express-1a477e9f7763/app/controllers/spree/admin/paypal_payments_controller.rb:2:in `<module:Spree>': uninitialized constant Spree::Admin::BaseController (NameError)
    from bundler/gems/better_spree_paypal_express-1a477e9f7763/app/controllers/spree/admin/paypal_payments_controller.rb:1:in `<top (required)>'
    from gems/railties-4.0.13/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
    from gems/railties-4.0.13/lib/rails/engine.rb:464:in `each'
    from gems/railties-4.0.13/lib/rails/engine.rb:464:in `block in eager_load!'
    from gems/railties-4.0.13/lib/rails/engine.rb:462:in `each'
    from gems/railties-4.0.13/lib/rails/engine.rb:462:in `eager_load!'
    from gems/railties-4.0.13/lib/rails/engine.rb:347:in `eager_load!'
    from gems/railties-4.0.13/lib/rails/application/finisher.rb:56:in `each'
    from gems/railties-4.0.13/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
    from gems/railties-4.0.13/lib/rails/initializable.rb:30:in `instance_exec'
    from gems/railties-4.0.13/lib/rails/initializable.rb:30:in `run'
    from gems/railties-4.0.13/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `each'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `call'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
    from /home/openfoodnetwork/.rbenv/versions/2.3.7/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
    from gems/railties-4.0.13/lib/rails/initializable.rb:54:in `run_initializers'
    from gems/railties-4.0.13/lib/rails/application.rb:215:in `initialize!'
    from gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from config/environment.rb:5:in `<top (required)>'
    from script/delayed_job:3:in `require_relative'
    from script/delayed_job:3:in `<main>'
</details>
There might be a require needed somewhere so things load in the right order.

source: https://app.bugsnag.com/katuma/katuma/errors/5fc0c0f62510c6001818b4f7?filters[event.since][0]=30d&filters[error.status][0]=open
failed deployment: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/katuma-staging/deploys/485

**Comment by sauloperez** [comment]
Most of the CodeClimate issues can be solved

File: app/controllers/spree/paypal_controller_decorator.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply app/controllers/spree/paypal_controller_decorator.rb:77]: This is the code directly imported from the gem :see_no_evil:  I've made this issue to pull it all in and clean it up: #6421

Comment (sauloperez) [reply app/controllers/spree/paypal_controller_decorator.rb:77]: I thought so but I looked it up in better_spree_paypal_express and couldn't find any result: https://github.com/openfoodfoundation/better_spree_paypal_express/search?q=commerce_tracking. Am I missing something?

Comment (sigmundpetersen) [reply app/controllers/spree/paypal_controller_decorator.rb:77]: Couldn't find it searching either but found it browsing the code here https://github.com/openfoodfoundation/better_spree_paypal_express/blob/2-1-0-stable/app/controllers/spree/paypal_controller.rb#L62

**Comment by Matt-Yorkley** [comment]
@filipefurtad0 I've just added a slight adjustment that should mean the update button is correctly shown when redirecting back to the cart. Could you re-stage and re-check it? :pray:

**Comment by filipefurtad0** [comment]
Just had a second look at this, it looks great now :muscle: 

image

This ready to go, thanks Matt!

**Comment by sauloperez** [comment]
I'm merging this so it gets to the release but I'd appreciate if you could address CodeClimate's failures separately.
