### PR TITLE
Missing translation: table headers in product import validation table #8458

### LINKED ISSUE #8458: Missing translation: table headers in product import validation table
## Description
During product import one of the last steps is to display two tables with all the products which were found in the csv-file and all the products which will be created. The headers of those tables are not translated.

## Expected Behavior
The table headers should be translated.

## Actual Behaviour
The table headers are not translated.

## Steps to Reproduce
0. Prepare a csv-file for product import
1. Select a language other than English
2. Log in
3. Go to /admin/product_import (products - import)
4. Choose the csv-file you have prepared and klick 'upload'
5. Follow the instructions until you end up at the validation screen

## Animated Gif/Screenshot
image

## Workaround
None.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.1.6
* Browser name and version: Chrome 95.0.4638.69 (Offizieller Build) (64-Bit)
* Operating System and version (desktop or mobile): Windows 10, Desktop

### PR DESCRIPTION
**Pull request by tsara27**
#### What? Why?

Closes  #8458 

I added translation for product heading that will match the translation. The translation for other languages should be added after merging this pull request. 

#### What should we test?

Test the import products while using other language than English.

1. Select a language other than English
2. Log in
3. Go to /admin/product_import (products - import)
4. Choose the csv-file you have prepared and klick 'upload'
5. Follow the instructions until you end up at the validation screen

#### Release notes

Use translation when displaying the products list on the product import validation page. 

Changelog Category: User facing changes

### CODE REVIEW

File: spec/system/admin/product_import_spec.rb [hunk 1]
```diff
@@ -565,6 +565,47 @@
...
+        find('a.button.proceed').click
+
+        within('.panel-header .header-caret') { find('i').click }
+
+        within('.panel-content .table-wrap') do
+          product_headings = ['producer', 'category', 'units', 'unit_type',
+                              'price', 'on_hand', 'shipping_category', 'name']
+
+          product_headings.each do |heading|
+            expect(page).to have_content I18n.t("admin.product_import.product_headings.#{heading}").upcase
```
Comment (mkllnk) [inline spec/system/admin/product_import_spec.rb:604]: Since we haven't translated this yet, the headings are still in English. But that should change once we do have translations.

**Review by mkllnk — APPROVED** [review]
Great! And thank you for yet another contribution. I like your thoroughness and test coverage.

File: spec/system/admin/product_import_spec.rb (hunk 1 above)
Comment (tsara27) [reply spec/system/admin/product_import_spec.rb:604]: Got that.

**Review by Matt-Yorkley — APPROVED** [review]
Thanks @tsara27 :heart:

**Comment by filipefurtad0** [comment]
Hey @tsara27 ,

Good to see you back here :+1: 

I've staged the PR, and all seems good here:
image

Once the keys are updated the translations should appear on the table.

Thanks for this!
Merging.
