### PR TITLE
[Spree Upgrade] shipping_category now required for products

### LINKED ISSUE #3663: [Spree upgrade] Better translate that shipping category is now mandatory for Product Import
## Description
Shipping category is now mandatory but the error is not showing correctly, it's "cant be blank", should be "shipping category cant be blank".

## Steps to Reproduce

1. Use file product_listv2_test1 uploaded here https://drive.google.com/drive/u/0/folders/1fI0r3CuHEs0e2y3N46QHIUPJkMs4mfrf on AU staging
2. An error message will be displayed saying "can't be blank"

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2
* Browser name and version: Firefox 65
* Operating System and version (desktop or mobile): Ubuntu 18.10

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #3663

Updates Product Import with a validation to reflect the fact that `shipping_category` is now mandatory.

#### What should we test?

Shipping category is now required in Product Import. Validation messages are clearer when the field is missing.

#### Documentation updates

Product import user guide will need updating.

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
Should this target `2-0-stable` rather than `master`?

**Comment by Matt-Yorkley** [comment]
Ready for re-review

File: spec/models/product_importer_spec.rb [hunk 1]
```diff
@@ -175,6 +175,27 @@
...
+  describe "when shipping category is missing" do
+    before do
+      csv_data = CSV.generate do |csv|
+        csv << ["name", "producer", "category", "on_hand", "price", "units", "unit_type", "variant_unit_name", "on_demand", "shipping_category"]
+        csv << ["Shipping Test", "User Enterprise", "Vegetables", "5", "3.20", "500", "g", "", nil, nil]
+      end
+      File.write('/tmp/test-m.csv', csv_data)
+      file = File.new('/tmp/test-m.csv')
+      settings = {'import_into' => 'product_list'}
+      @importer = ProductImport::ProductImporter.new(file, admin, start: 1, end: 100, settings: settings)
```
[the remark this answers is not in the document]
Comment (sauloperez) [reply spec/models/product_importer_spec.rb]: I not fan of moving the subject of the test, `@importer`, far away from the actual test and I would also make use of RSpec features for consistency. So it can easily be DRYed up by as follows:

```
let(:file) { File.new('/tmp/test-m.csv') }
let(:settings) { {'import_into' => 'product_list'} }
let(:importer) { ProductImport::ProductImporter.new(file, admin, start: 1, end: 100, settings: settings) }

around(:each) do |example|
  File.write('/tmp/test-m.csv', csv_data)
  example.run
  File.delete('/tmp/test-m.csv')
end

describe do
  let(:csv_data) do
    CSV.generate {}
  end

  it 'whatever' do
  end
end
```

**Comment by Matt-Yorkley** [comment]
@luisramos0 when i rebased this the test changed in relation to `on_demand`. I had to change this to get it green: https://github.com/openfoodfoundation/openfoodnetwork/pull/3672/commits/41c0b3320efbb11faed7056fe375f903427b8043

**Comment by luisramos0** [comment]
Nice @Matt-Yorkley 
From the tests I see users will need to input shipping category name now and not shipping category id. will shipping category id also work?

**Comment by Matt-Yorkley** [comment]
> From the tests I see users will need to input shipping category name now and not shipping category id. will shipping category id also work?

Shipping id works unofficially, but it's always used the human-readable shipping category name.

**Comment by RachL** [comment]
@Matt-Yorkley it seems that the "can't be blank" mention is still appearing alongside the clear error message, see below for a screenshot of an import with a product with all columns and a product without shipping category.

Can you remove the lonely "can't be blank" easily?

image

**Comment by RachL** [comment]
@Matt-Yorkley the file is here https://drive.google.com/drive/u/0/folders/1_xBrJefhSRbdRbzO2SpxcmL_nPUA2qvw

**Comment by Matt-Yorkley** [comment]
@RachL ready for re-test :+1:

**Comment by RachL** [comment]
Awesome! This is ready to go

image

**Comment by luisramos0** [comment]
⚠️ this needs to be merged into master, not 2-0-stable

File: app/views/admin/product_import/_errors_list.html.haml [hunk 2]
```diff
@@ -7,5 +7,3 @@
       ( {{entry.attributes.display_name}} )
   %p.error{ng: {repeat: "(attribute, error) in entry.errors", show: "ignore_fields.indexOf(attribute) < 0" }}
     &nbsp;-&nbsp; {{error}}
-  %p.error{ng: {repeat: "(attribute, error) in entry.product_validations"}}
-    &nbsp;-&nbsp; {{error}}
```
Comment (luisramos0) [inline app/views/admin/product_import/_errors_list.html.haml]: I dont understand this change @Matt-Yorkley 
product_validations is still being populated in some cases, why would you remove it from the page?

**Comment by sauloperez** [comment]
I don't think it's a critical bug so not worth including it into v2.0. Merge to master :+1:

File: app/views/admin/product_import/_errors_list.html.haml (hunk 2 above)
Comment (Matt-Yorkley) [reply app/views/admin/product_import/_errors_list.html.haml]: There was some duplication here, as the `product_validations` are actually being added elsewhere. Also the formatting was not right:

Comment (luisramos0) [reply app/views/admin/product_import/_errors_list.html.haml]: ok, I dont understand the code... why do we need to keep both entry.errors and entry.product_validations?

    def mark_as_invalid(entry, options = {})
      entry.errors.add(options[:attribute], options[:error]) if options[:attribute] && options[:error]
      entry.product_validations = options[:product_validations] if options[:product_validations]
    end
