### PR TITLE
Use capture! if payment is already authorized

### LINKED ISSUE #7495: [Spike] StripeSCA Subs - Payments taken twice for some banks
Proposing a timeboxed spike to investigate this.... 

## Description

Stripe users with specific banks (Monzo, Lloyds) are reporting that Stripe payments for their subscriptions are taken twice.
The second payment is refunded within a month, but we've had a number of users payments fail as the second payment takes them into negative balance or other complications. A lot of subs users are getting very stressed by this.

## Expected Behavior

Subs just take one payment - the payment hold and the actual payment are not separate transactions taken twice.

## Actual Behaviour

Some banks are taking two payments.

## Steps to Reproduce

1.
2.
3.
4.

## Workaround

- Tell the user to wait a month to have their money returned (with weekly orders this is crazy)
- Manually refund the second payment

## Severity

S2

## Your Environment

* Version used: Related to Stripes SCA implementation
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

I don't know if this is fixable at all. It might be a bank issue or a Stripe issue. Hence, can we timebox a spike to 2 hrs to see what we can learn about our responsibility here and what a potential fix would be, if one exists.

## More Info

More sites seem to suggest using idempotent requests.... are we?
https://stripe.com/docs/api/idempotent_requests

Some interesting discussions on this thread - this one seems potentially relevant:
https://forums.wpsharks.com/t/stripe-causing-double-payments/7002/41

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #7495 

We were previously calling `authorize` on a payment, and if there was no SCA auth required, making a separate call to run the charge. According to the Stripe docs, the authorization does not result in an actual charge and expires within 7 days; however, for some types of cards, it appears that the amount is in fact debited from the card and then refunded after 7 days (or maybe longer).

This PR uses the `capture` method for the second call and so only one transaction should appear on the card statement. On the Stripe side, the difference is shown here:
Screen Shot 2021-04-27 at 6 04 39 PM
Before this change, we make the call to authorize (4:26PM) and then the call to run the charge (4:27PM). After this change, the second call is to capture the original payment intent (4:33PM). 

#### What should we test?

I tested this with the subscription rake tasks to manually verify the difference in the Stripe logs, and added a couple unit tests. We should verify that after this change, the Stripe logs show a call to `capture`. 

#### Release notes

Fixed a bug where subscription payments would appear twice on customer's card statements (once as an authorization and again for the actual charge)

Changelog Category: User facing changes

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]
LGTM :+1:

File: app/models/spree/payment/processing.rb [hunk 1]
```diff
@@ -6,14 +6,22 @@ module Processing
       def process!
         return unless validate!
 
-        purchase!
+        if response_code
```
Comment (sauloperez) [inline app/models/spree/payment/processing.rb:9]: I think wrapping this in a more abstract query method such as `authorized?` would help a great deal in showing what's the actual "algorithm". As is, when I read this, I need to find out what does having a response_code at this point means, and I feel a bit lost. Didn't we discuss and implement this before?

File: spec/models/spree/payment_spec.rb [hunk 2]
```diff
@@ -97,6 +97,30 @@
...
+      context "#process_offline when payment is already authorized" do
+        before do
+          allow(payment).to receive(:response_code) { "pi_123" }
+        end
+
+        it "should call capture if the payment is already authorized" do
+          expect(payment).to receive(:capture!)
+          expect(payment).to_not receive(:purchase!)
+          payment.process!
+        end
```
Comment (sauloperez) [inline spec/models/spree/payment_spec.rb:123]: I'm missing also an integration-level test that should ideally cover the exact case reported in #7495 , or as close as we can get.

File: app/models/spree/payment/processing.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/models/spree/payment/processing.rb:9]: That's a good point. It sounds familiar because we did it for cvv_response_message:

```
def authorization_action_required?
   cvv_response_message.present?
end
```

I'll add it here too

Comment (sauloperez) [reply app/models/spree/payment/processing.rb:9]: I'm not sure I'm following. We always call `authorize!` first and we call capture if required user authorization?

Comment (andrewpbrett) [reply app/models/spree/payment/processing.rb:9]: We call authorize first, but the user authorization step is often not necessary. In either case (whether the user authorization step is required or not), we've already created a Payment Intent in Stripe by calling authorize, so this PR calls capture on that Payment Intent instead of creating a new one.

Comment (sauloperez) [reply app/models/spree/payment/processing.rb:9]: I fail to see when would `#purchase!` create a new payment intent :thinking: In `#purchase` we `#fetch_payment_intent` first but both call `provider.capture` at the end. What am I missing?

Comment (andrewpbrett) [reply app/models/spree/payment/processing.rb:9]: Hm yeah I think you're right actually. `#purchase` already guards against this, so it's just `#charge_offline` that we need to modify.

Comment (sauloperez) [reply app/models/spree/payment/processing.rb]: again, having a regression test that we can rely on would make it easier for you to move code around while not breaking the behavior.

File: app/models/spree/payment/processing.rb [hunk 3]
```diff
@@ -190,6 +186,10 @@ def authorization_action_required?
         cvv_response_message.present?
       end
 
+      def preauthorized?
+        response_code.presence&.match("pi_")
+      end
```
Comment (sauloperez) [inline app/models/spree/payment/processing.rb:191]: this should be private right? sorry to be picky :sweat_smile:

Comment (andrewpbrett) [reply app/models/spree/payment/processing.rb:193]: 😁 👍

File: spec/models/spree/payment_spec.rb (hunk 2 above)
Comment (andrewpbrett) [reply spec/models/spree/payment_spec.rb:122]: Okay, I added a spec to ..... the SubscriptionConfirmJob spec..... 😁 

It isn't perfect, but gets at the idea of what we want. Add it to the reasons to prioritize https://github.com/openfoodfoundation/openfoodnetwork/pull/7281 - and just to rework subscriptions in general.

File: spec/jobs/subscription_confirm_job_spec.rb [hunk 4]
```diff
@@ -158,12 +158,19 @@
...
+          allow(stripe_sca_payment_method.provider).to receive(:capture) { true }
         end
 
         it "runs the charges in offline mode" do
           job.send(:confirm_order!, order)
           expect(stripe_sca_payment_method.provider).to have_received(:purchase)
         end
+
+        it "uses #capture if the payment is already authorized" do
+          allow(stripe_sca_payment).to receive(:preauthorized?) { true }
```
Comment (sauloperez) [inline spec/jobs/subscription_confirm_job_spec.rb:170]: the abstraction is already paying off :heart_eyes:

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

I'm not entirely sure I spot the difference (maybe I'm just looking in the wrong direction). Which card was used in the tests and logs posted in your notes on what to test?

After staging the PR, payments which require authentication require manual capturing on Stripe (as before), see this example for x-3814:

Sub is placed, and payment authorized:
image

Payment remains in an un-captured state; changes to `captured` after manually capturing, and appears respectively in the logs:

image

This is not introduced by this PR. Is this the behavior we're after?

PS: I did spot something while testing - not introduced by this PR - regarding the scenario in which a payment attempt fails:

It seems that despite failing the payment, the orders appear as paid, for both the customer and admin:

Peek 2021-04-29 12-51

**Comment by andrewpbrett** [comment]
Thanks for testing @filipefurtad0. I should have specified that despite the name, this actually has nothing to do with SCA authorization, at least not directly. The card I used in testing was the standard x-4242 card. 

I believe that the behavior you observed is expected in the scenario where we use the x-3184 card and the customer is required to perform an additional authorization step - the payment should remain "uncaptured" in Stripe in that case. 

The other bug does sound like a very good find - I can create an issue for it, unless you have already or you have everything ready to go.

**Comment by filipefurtad0** [comment]
Thanks for feedback @andrewpbrett ,

I noticed you mentioned cards which do not require authentication, so I tried this one as well - thought I'd pick a 3D compatible card, but one which does not require auth., the `x-3055`:

image

Here are the logs, for that payment:
image

Indeed, the logs do look similar to your tests. So maybe we're good? I'm not sure.

PS: on the issue, no worries I can open it :+1:

**Comment by andrewpbrett** [comment]
Thanks @filipefurtad0 - yes, this is good to go IMO.
