### PR TITLE
render date without time on invoices list

### LINKED ISSUE #11051: [Invoices] Time in the invoices list not set correctly
## Description

Follow up of #10532.

The displayed time of the invoices in the invoice list always seems to be 12 a.m.

## Expected Behavior

The displayed time should be the time of invoice creation.

## Actual Behaviour

The displayed time is always 12 a.m.

## Steps to Reproduce

1. Create one or more invoices.
2. Look at the invoice list.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #11051

#### What should we test?

- described on #11051

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by drummer83** [comment]
See comment on the issue: https://github.com/openfoodfoundation/openfoodnetwork/issues/11051#issuecomment-1606121014

**Review by mkllnk — APPROVED** [review]
Cool. A spec addition would have been nice.

File: app/models/invoice.rb [hunk 1]
```diff
@@ -4,6 +4,7 @@ class Invoice < ApplicationRecord
   belongs_to :order, class_name: 'Spree::Order'
   serialize :data, Hash
   before_validation :serialize_order
+  default_scope { order(created_at: :desc) }
```
Comment (jibees) [inline app/models/invoice.rb:7]: ah, ok, now I see ;)

File: app/views/spree/admin/invoices/_invoices_table.html.haml [hunk 2]
```diff
@@ -7,12 +7,12 @@
...
       %th= t(:file)
   %tbody
-    - @order.invoices.each do |invoice|
+    - @order.invoices.order('number desc').each do |invoice|
       - tr_class = cycle('odd', 'even')
       - tr_id = spree_dom_id(invoice)
       %tr{:class => tr_class, "data-hook" => "invoice_row", :id => tr_id}
         %td.align-center.created_at
-          = pretty_time(invoice.date)
+          = invoice.presenter.invoice_date
```
Comment (jibees) [inline app/views/spree/admin/invoices/_invoices_table.html.haml:15]: Sorry, I try to retrieve some information, but couldn't find if this handle i18n?

**Review by jibees — COMMENTED** [review]
Got a few comments! Thanks! 🙏

File: app/views/spree/admin/invoices/_invoices_table.html.haml (hunk 2 above)
Comment (rioug) [reply app/views/spree/admin/invoices/_invoices_table.html.haml:15]: As far as I can see we are going in circle here, `Invoice::DataPresenter` delegates `date` to `Invoice` so I think we should revert this change. Plus the change doesn't handle i18n

File: app/views/spree/admin/invoices/_invoices_table.html.haml [hunk 3]
```diff
@@ -7,12 +7,12 @@
       %th= t(:status)
       %th= t(:file)
   %tbody
-    - @order.invoices.each do |invoice|
+    - @order.invoices.order('number desc').each do |invoice|
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/views/spree/admin/invoices/_invoices_table.html.haml]: For other reviewer, this is fixed in the next commit.

**Review by rioug — CHANGES_REQUESTED** [review]
One of the change is I think unnecessary

File: app/views/spree/admin/invoices/_invoices_table.html.haml (hunk 2 above)
Comment (abdellani) [reply app/views/spree/admin/invoices/_invoices_table.html.haml]: @jibees  you're right. I fixed that by  adding a new helper.

@rioug 
I don't see a circle
```ruby
class Invoice
  class DataPresenter
     delegate :data, :date, to: :invoice
....
    def invoice_date
      date
    end
  end
end
```
Instead, we can replace that code with 
```ruby
    delegate :date, to: :invoice, prefix: true
```

Comment (rioug) [reply app/views/spree/admin/invoices/_invoices_table.html.haml]: The presenter delegate `date` to `invoice`, right ? so calling `invoice.presenter.invoice_date` should return the same thing as `invoice.date` . So I don't see the point of calling the presenter here.

File: app/views/spree/admin/invoices/_invoices_table.html.haml [hunk 4]
```diff
@@ -12,7 +12,7 @@
       - tr_id = spree_dom_id(invoice)
       %tr{:class => tr_class, "data-hook" => "invoice_row", :id => tr_id}
         %td.align-center.created_at
-          = invoice.presenter.invoice_date
+          = pretty_date(invoice.date)
```
Comment (rioug) [inline app/views/spree/admin/invoices/_invoices_table.html.haml:15]: Now I would argue that `pretty_date` should be called from the presenter, isn't it it's role to format the data ? Then it would make sense to call `invoice.presenter.invoice_date` or maybe something more descriptive like `invoice.presenter.display_date` ? What do you think ?

File: spec/system/admin/orders/invoices_spec.rb [hunk 5]
```diff
@@ -36,7 +36,7 @@
 
   let(:row1){
     [
-      Time.current.to_date.to_s,
+      I18n.l(Time.current.to_date, format: :long),
```
Comment (mkllnk) [inline spec/system/admin/orders/invoices_spec.rb:39]: This can fail when you run the spec at midnight. We had this kind of flakiness before and it was very hard to track down.

I would pass the dates to the factories and then test against the resulting string.

**Review by mkllnk — CHANGES_REQUESTED** [review]
Mostly good. Just one adjustment of the spec to avoid flakiness.

File: app/views/spree/admin/invoices/_invoices_table.html.haml (hunk 4 above)
Comment (abdellani) [reply app/views/spree/admin/invoices/_invoices_table.html.haml:15]: Yes, you're right.

**Review by mkllnk — APPROVED** [review]

**Review by rioug — APPROVED** [review]
:+1:

**Comment by RachL** [comment]
- Date and ordering are correct
- Sending an invoice sends correctly the last one.
- deactivating the feature toggle works correctly

However, I noticed we can't sen and print invoices individually anymore with the toggle/

without toggle : 
image


toggle activated : 

image

will open a new issue for this and merge in the meantime
