### PR TITLE
Order lines are deleted when one tries to capture a payment after order cycle is closed

### LINKED ISSUE #13519: Order lines are deleted when one tries to capture a payment after order cycle is closed
## Description
It can happen that an order is not completed (Confirmation state) while the payment has been proceeded by the customer. I know it happens when the customer doesn’t come back to the browser after he confirmed payment in the bank app.
In that case the shop manager could try to capture the payment in the Stripe dashboard. I have not tested what happens when the Order Cycle is not closed (I assume it should work fine) but I have tested when OC is already closed --> the payment is captured as expected BUT the order disappear in OFN !

## Expected Behavior
The order should be marked as completed and paid, so the shop can process it.
We can discuss the fact that a payment can be captured after the OC is closed because it can raise problems if producers have already prepare orders for instance. Hubs should be aware of that.

## Actual Behaviour
In OFN the order can not be seen anymore.
Anyway by analyzing database with Metabase ! could assess that order is still there but order lines have been wiped out. I could also find the error in bugsnag : 

Image

## Steps to Reproduce
- identify an order stalled at confirmation state
- check that this is due to a stripe payment uncomplete, not captured
- wait for the end of order cycle 
- capture the payment in Stripe dashboard
- see that order has disappeared

## Workaround
print the order before capturing the payment  (but expect wrong reports)

## Severity

bug-s2: a non-critical feature is broken, no workaround
but only a few users impacted

## Your Environment
CoopCircuits PR

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #13519

The existing `check_order_cycle_expiry` logic unconditionally emptied the order and redirected to the shop page when an order cycle closed during checkout. This caused issues in payment gateway flows (PayPal and Stripe), where the order should **not** be emptied immediately—users need to be informed and guided to contact support to finalize the payment without losing the order context.

This PR:
1. Refactors `check_order_cycle_expiry` to accept a `should_empty_order:` parameter (default: `true`).
2. Updates PayPal and Stripe controllers to call it with `should_empty_order: false`.
3. Introduces improved messaging:
   - When order is emptied → "The order cycle you've selected has just closed. Please try again!"
   - When order is preserved → "The order cycle you've selected has just closed. Please contact us to complete your order #ORDER_NUMBER!"
4. Redirects to `/shops` (instead of `/shop`) when preserving the order, since the shop page auto-empties carts.

#### What should we test?
- Validate Stripe/Paypal flows where 3D auth is required from the user.
  - Order Cycle gets closed when user does 3D authentication
  - User should be able to navigate to the shops where the following prompt should display while keeping the cart intact:
    - `The order cycle you've selected has just closed. Please contact us to complete your order #ORDER_NUMBER!`
- Validate Stripe/Paypal flows (_non-closed cycle_) are unaffected.
- Validate **regular checkout flow** (_closed/non-closed cycle_) is unaffected.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: spec/controllers/checkout_controller_spec.rb [hunk 1]
```diff
@@ -39,6 +39,47 @@
...
+          expect(flash[:info]).to eq(message)
+          expect(response).to redirect_to shop_url
+        end
+
+        context "when CableReady request" do
+          before do
+            request.headers["Accept"] = "text/vnd.cable-ready.json"
+          end
+
+          let(:cable_car) { instance_spy(CableReady::CableCar) }
```
Comment (rioug) [inline spec/controllers/checkout_controller_spec.rb:66]: Is this needed ? It's not used anywhere .

File: app/controllers/concerns/order_stock_check.rb [hunk 2]
```diff
@@ -24,23 +24,41 @@ def check_order_cycle_expiry(should_empty_order: true)
     return unless current_order_cycle&.closed?
 
     Alert.raise_with_record("Notice: order cycle closed during checkout completion", current_order)
-    if should_empty_order
-      current_order.empty!
-      current_order.assign_order_cycle! nil
-    end
 
-    flash[:info] = I18n.t('order_cycle_closed')
+    handle_closed_order_cycle(should_empty_order)
```
Comment (rioug) [inline app/controllers/concerns/order_stock_check.rb]: I think the code would read better like this :
```suggestion
    handle_closed_order_cycle if should_empty_order
```

Then you can remove the parameter from `handle_closed_order_cycle`

**Review by rioug — COMMENTED** [review]
Looks good, I just have a couple of questions. I see we test the new functionality for Stripe, shouldn't we be doing the same for Paypal ?

File: app/controllers/concerns/order_stock_check.rb (hunk 2 above)
Comment (mkllnk) [reply app/controllers/concerns/order_stock_check.rb]: I agree.

File: app/controllers/concerns/order_stock_check.rb [hunk 3]
```diff
@@ -24,23 +24,41 @@ def check_order_cycle_expiry(should_empty_order: true)
...
+
+  def build_order_cycle_message(should_empty_order)
+    # If order is not emptied, we assume user will contact support for next steps
+    key = should_empty_order ? 'order_cycle_closed' : 'order_cycle_closed_next_steps'
+    I18n.t(key, order_number: current_order.number)
+  end
+
+  def redirect_to_shop_page(should_empty_order)
+    # If order is not emptied, redirect to shops page because shop page empties the order by default
+    redirect_url = should_empty_order ? main_app.shop_path : main_app.shops_path
```
Comment (mkllnk) [inline app/controllers/concerns/order_stock_check.rb:49]: This seems to be a band aid fix. If the user then navigates to the shop again, the order still empties and all the information is lost?

Maybe we need to re-think the UX here. When you switch shops, there's a warning that you will lose your cart. I'm wondering if we need that here as well. But instead of checking before we navigate to a shop, we could modify the shop page to show another template where you can choose to empty cart and continue or keep cart and go back. Then we avoid the pop-up, have less JS and simpler code that works for any navigation to a shop and not for the transition from the shops page.

**Review by mkllnk — APPROVED** [review]
I'm approving this because it fixes an S2. But I think that we should follow up to clean up the code and maybe introduce better UX after discussing this. Delivery circle?

File: spec/controllers/checkout_controller_spec.rb (hunk 1 above)
Comment (chahmedejaz) [reply spec/controllers/checkout_controller_spec.rb:66]: Thanks @rioug - SimpleCov raised the error to have specs for this. That's why I added spec for those.
Plus I also did a bit of spike on it and found that it wasn't being used. However, I didn't take a chance to remove it, thought I might be missing something.

File: app/controllers/concerns/order_stock_check.rb (hunk 3 above)
Comment (chahmedejaz) [reply app/controllers/concerns/order_stock_check.rb:49]: >This seems to be a band aid fix. If the user then navigates to the shop again, the order still empties and all the information is lost?
 
I agree. We discussed this in the last meeting and we came up with this warning for the user in this case:
`The order cycle you've selected has just closed. Please contact us to complete your order!`

However, if the user still goes to the different shop, then I assume he doesn't want to contact us about the current order, in that case, it should be emptied.

>Maybe we need to re-think the UX here. When you switch shops, there's a warning that you will lose your cart. I'm wondering if we need that here as well. But instead of checking before we navigate to a shop, we could modify the shop page to show another template where you can choose to empty cart and continue or keep cart and go back. Then we avoid the pop-up, have less JS and simpler code that works for any navigation to a shop and not for the transition from the shops page.

This UX update in a follow-up issue sounds good to me. We may raise it in the Delivery Circle to get everyone's view on it. 👍 
**Edit:** I'm not sure keeping the cart on the same shop would help because the order cylce through which they ordered items is now closed 😅

**Comment by chahmedejaz** [comment]
Thanks @rioug for catching the Paypal specs, I've addressed your comments here: https://github.com/openfoodfoundation/openfoodnetwork/pull/13666/commits/913dded766442f6f3942fc4ec71716732b6a0a19

**Comment by rioug** [comment]
We agreed to move forward with this during delivery-circle, moving to test ready.

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz,

Thanks so much for the great documentation.

I've managed to reproduce #13666 in two ways:
The Order Cycle gets closed during the 3D authentication step (Stripe) / payment completion (Paypal). Then:
i) the user clicks Authenticate. In this case, we get the new behavior, as introduced by this PR :tada: 

image

Now the user is redirected to the `/shops` page, and the order is not emptied. It should be noted though, if the user selects _another_ shop, then the cart is emptied and the order edit path becomes inaccessible, by the hub:

image

This seems to be the behavior also in master, for both Stripe and Paypal incomplete orders - I've never really noticed it before. I guess the reason is, this happens when users first abandon the cart, the order cycle closes, and they return at a later point to the homepage.

Since now we redirect the customer directly to the shops page, we might be getting more of these events: I think a customer with an incomplete order might have the urge to go to another shop...

ii) the user abandons checkout, and/or hits the back-navigation button. In this case, issue #13666 is still reproducible:

image

I've stumbled upon an issue on the staging servers, so I'll have to restart testing. But I'll leave these notes here for now, to be completed later.

**Summary**

I think this PR reduces the occurrence from #13666 and covers the agreed solution from all our discussions. So I'd say it is good to go.

However, two takeaways:
- we might get more inaccessible carts (unauthorized edit order path) from users being redirected to the /shops page (scenario i)
- this PR does not affect the case in which carts are abandoned then returning to the /shop page or when users hit the navigate back button, during the authorization step (scenario ii) and order cycle closure

I agree we might need follow-up issues here; but we might need to have some thought on this. 

Merging for now!
Thanks @chahmedejaz .
