### PR TITLE
Split orders across several shops of same order cycle instead of aggregating in several Orders and Fulfilment reports

### LINKED ISSUE #9267: Wrong report when selecting multiple shops
## Description

In FR our big users are doing 1 shop = 1 pick up place. 

When then downloading Orders and fulfillment reports for 1 shop, they get different results then when doing shops by shops.

## Steps to Reproduce

1. Ask Rachel to add you as manager of hub 28
2. Try order and fulfillment reports especially all but OC total by customers (to be confirmed)

## Animated Gif/Screenshot

When multiple shops : 

With only filtering this shop - I can't even screenshot everything: 

## Severity
bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment

* Version used: last
* Browser name and version: all
* Operating System and version (desktop or mobile): both

## Possible Fix

It's possible we are grouping variants per shop

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9267

#### What should we test?

- Visit ... page.
- 
Capture d’écran 2022-06-07 à 16 22 18
Capture d’écran 2022-06-07 à 16 23 26

#### Release notes

Changelog Category: User facing changes | Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by filipefurtad0** [comment]
Hey @RachL,
Thanks again for the testing + detailed notes! I think I've finally nailed it as well.

Permission scheme:

Kimchi Hub is **both** Coordinator and Supplier
Red Berries Hub is Distributor
Wasabi Farm is Distributor

**Before staging**

- Orders and Fulfillement report aggregate results for **one of the Distributors** if the report is called for the two **distributors**
image


- Calling the same report for the respective distributors correctly displays the ordered products/amounts

Distributor 1
image

Distributor 2
image

Staging and re-testing....

**Comment by filipefurtad0** [comment]
Hey @jibees,
After staging the PR, I can't seem to see a difference in behavior:

Peek 2022-06-07 12-41

@RachL could you the expected behavior in your tests?

**Comment by RachL** [comment]
@filipefurtad0 the expected behavior is the following : when you filter on both hubs you should have the data per hub and not one hub with all the data.

So basically the same result that you have when filtering individually, but one after the other. If not clear I will try to do a mockup.

**Comment by jibees** [comment]
@filipefurtad0 
i've made some modifications on the PR (this was only available for `Order Cycle Customer Totals` report). Now this is available for `Orders & Fulfillment` reports. @RachL should confirm me or not if this should be applied to `Order Cycle Customer Totals` so.

**Comment by RachL** [comment]
@filipefurtad0 @jibees OC customer totals looks ok. I thinkit's logical because it orders by customers, so the problem of grouping cannot occur?

Writing this, I'm wondering about the case of the same customer ordering the same product on two different shops / same OC. I haven't have time to test it. It's pretty rare in real life though. I don't see a real use case on this.

File: lib/reporting/reports/orders_and_fulfillment/order_cycle_customer_totals.rb [hunk 1]
```diff
@@ -97,7 +97,7 @@ def line_item_includes
 
         def query_result
           report_line_items.list(line_item_includes).group_by { |e|
-            [e.variant_id, e.price, e.order_id]
+            [e.variant_id, e.price, e.order_id, e.order.distributor_id]
```
Comment (mkllnk) [inline lib/reporting/reports/orders_and_fulfillment/order_cycle_customer_totals.rb:100]: I think that we don't need this because we are grouping by order_id already. One order has only one distributor.

**Comment by mkllnk** [comment]
> Writing this, I'm wondering about the case of the same customer ordering the same product on two different shops / same OC.

The customer totals report was already grouping by order-id. So if the same user ordered several times, it would not be bunched up in the same line. It's already separate. Maybe that's not intended? But that's how it works at the moment.

**Review by mkllnk — APPROVED** [review]
I'm approving this because it's solving an S1 while my comment below is just about performance and code style and shouldn't affect the result of the reports.

File: lib/reporting/reports/orders_and_fulfillment/order_cycle_customer_totals.rb (hunk 1 above)
Comment (jibees) [reply lib/reporting/reports/orders_and_fulfillment/order_cycle_customer_totals.rb:100]: Yep, I think you're right... Good point. 
Will update the PR by removing this.

**Comment by jibees** [comment]
Ready to test!

**Comment by filipefurtad0** [comment]
> @filipefurtad0
> i've made some modifications on the PR (this was only available for Order Cycle Customer Totals report). Now this is available for Orders & Fulfillment

Thanks @jibees , I'll consider both those reports when testing (see comment to follow) :+1: 

>@filipefurtad0 the expected behavior is the following : when you filter on both hubs you should have the data per hub and not one hub with all the data.

Thanks @RachL. I was looking at the totals by supplier; the most recent changes on the PR introduced the changes here too :+1: 

(testing notes on the following comment)

**Comment by filipefurtad0** [comment]
**Orders and fulfillment report**

- Totals by Distributor

Filtering by OC only:

image

Filtering by OC + each individual supplier:

Supplier 1

image

Supplier 1

image

**Comment by filipefurtad0** [comment]
**Orders and fulfillment report**

Customer Totals

Filtering by OC only:

image

Filtering by OC + each individual supplier:

Supplier 1

image

Supplier 2

image

**Comment by filipefurtad0** [comment]
**Orders and fulfillment report**

Supplier Totals

Filtering by OC only:

image

Filtering by OC + each individual supplier:

Supplier 1

image

Supplier 2

image

**Comment by filipefurtad0** [comment]
**Summary**
This is checked now for the 4 report sub-types, on the **orders and fulfillment** reports.

The PR prevents aggregation of quantities/totals on a single distributor only, in the case where two distributors have the same item in the shopfront (i.e., two OCs, same item).

This looks good to go, I'll move to ready to go.
Would you like to test as well @RachL ? We might need some regression testing on these report changes...

**Comment by sigmundpetersen** [comment]
What if you actively filter on both hubs in the 'Hubs' input box?
I guess this should give the exact same result as no Hub filter, but worth a check?

Like this:
image

**Comment by RachL** [comment]
Yes :) I'm merging then!

**Comment by RachL** [comment]
F*** I was so obsessed with having an impact on Total OC by customers that I neglected Order cycle supplier totals and order cycle distributors total by suppliers : these two should group by suppliers (producers) and not distributors... I'm opening a new issue :sob:
