### PR TITLE
[Spree Upgrade] Add VariantStock.on_demand as attribute_accessible

### LINKED ISSUE #3017: [Spree Upgrade][FrontOffice] Fix cart_controller_specs errors related to on_hand numbers (3 broken tests)
Fix the 3 broken tests in cart_controller_spec.

Probably some detail related to the new variant.on_hand adapter introduced in #2615.

```
  24) CartController returning stock levels in JSON on success generating stock levels returns a hash with variant id, quantity, max_quantity and stock on hand
      Failure/Error:
        expect(controller.stock_levels(order, [v.id])).to eq(
          {v.id => {quantity: 2, max_quantity: 3, on_hand: 4}}
        )
      
        expected: {1523=>{:quantity=>2, :max_quantity=>3, :on_hand=>4}}
             got: {1523=>{:quantity=>2, :max_quantity=>3, :on_hand=>5}}
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,2 @@
        -1523 => {:quantity=>2, :max_quantity=>3, :on_hand=>4},
        +1523 => {:quantity=>2, :max_quantity=>3, :on_hand=>5},
        
      # ./spec/controllers/cart_controller_spec.rb:36:in `block (4 levels) in <top (required)>'

  25) CartController returning stock levels in JSON on success generating stock levels includes all line items, even when the variant_id is not specified
      Failure/Error:
        expect(controller.stock_levels(order, [])).to eq(
          {v.id => {quantity: 2, max_quantity: 3, on_hand: 4}}
        )
      
        expected: {1529=>{:quantity=>2, :max_quantity=>3, :on_hand=>4}}
             got: {1529=>{:quantity=>2, :max_quantity=>3, :on_hand=>5}}
      
        (compared using ==)
      
        Diff:
        @@ -1,2 +1,2 @@
        -1529 => {:quantity=>2, :max_quantity=>3, :on_hand=>4},
        +1529 => {:quantity=>2, :max_quantity=>3, :on_hand=>5},
        
      # ./spec/controllers/cart_controller_spec.rb:42:in `block (4 levels) in <top (required)>'

  26) CartController returning stock levels in JSON on success generating stock levels includes an empty quantity entry for variants that aren't in the order
      Failure/Error:
        expect(controller.stock_levels(order, [v.id, v2.id])).to eq(
          {v.id  => {quantity: 2, max_quantity: 3, on_hand: 4},
           v2.id => {quantity: 0, max_quantity: 0, on_hand: 2}}
        )
      
        expected: {1535=>{:quantity=>2, :max_quantity=>3, :on_hand=>4}, 1538=>{:quantity=>0, :max_quantity=>0, :on_hand=>2}}
             got: {1535=>{:quantity=>2, :max_quantity=>3, :on_hand=>5}, 1538=>{:quantity=>0, :max_quantity=>0, :on_hand=>5}}
      
        (compared using ==)
      
        Diff:
        @@ -1,3 +1,3 @@
        -1535 => {:quantity=>2, :max_quantity=>3, :on_hand=>4},
        -1538 => {:quantity=>0, :max_quantity=>0, :on_hand=>2},
        +1535 => {:quantity=>2, :max_quantity=>3, :on_hand=>5},
        +1538 => {:quantity=>0, :max_quantity=>0, :on_hand=>5},
        
      # ./spec/controllers/cart_controller_spec.rb:48:in `block (4 levels) in <top (required)>'

```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

This is required so that it is mass-assigned from product_controller_decorator.bulk_update.
That makes the admin product list on_demand checkboxes work.
That helps the changes in PR #3139 close issue #2804 by fixing two extra tests. 

Also, this closes #3017 by fixing the 3 tests and this also fixes one of the 12 tests in #2943 

#### What should we test?
This PR fixes 6 tests.

Hey, let's stage this one for proper testing!!!!
Product List on_demand checkboxes are now working.

### CODE REVIEW

**Comment by sauloperez** [comment]
> Hey, let's stage this one for proper testing!!!!
Product List on_demand checkboxes are now working.

Is this possible?????

**Comment by sauloperez** [comment]
You'll need a rebase :recycle: here

**Comment by luisramos0** [comment]
These fields are now working!
screenshot 2018-11-23 at 12 08 26

**Comment by luisramos0** [comment]
re staging: we need to try it at some point!

**Comment by luisramos0** [comment]
This code is breaking 21 tests...

giphy 1

File: app/models/concerns/variant_stock.rb [hunk 1]
```diff
@@ -105,6 +105,7 @@ def on_demand=(new_value)
     # unknown reasons, it does not pass the test.
     stock_items.each do |item|
       item.backorderable = new_value
+      item.save
```
Comment (sauloperez) [inline app/models/concerns/variant_stock.rb]: I would really think twice to do this. These are the kind of things that cause the myriad of UPDATE and INSERT statements we see in development, resulting in multiple and pointless writes sometimes. 

This is just like another db column baked by AR and in that case, AR won't persist on assignments. I would not do it in our case either. To me, this is the responsibility of the consumer of this setter method.

Comment (luisramos0) [reply app/models/concerns/variant_stock.rb]: ok, thinking twice... I write up my thoughts so you can comment:

1. first I wanted to see **if this works**. answer: yes! this fixes not just the 21 one broken tests but a couple more.

2. then, I wanted to **understand** why: I think I now understand what's going on, if we dont save on_demand, the call to on_hand is saving the stock_item and ignoring the on_demand value (stock_item.backorderable) set just before by the consumer. By saving when we call on_demand, the consumers request to set on_demand is not lost when on_hand is called.

3. **explaining** this change: I got into this because the initial version was not working correctly. With  stock_item.send count_on_hand= the stock item data was not saved correctly on mass assignments. I believe it's acceptable to say that these stock management methods on_hand and on_demand require a lock on update and thus a save (this is what spree does on stock_item.count_on_hand). one advantage of this approach is that it makes both on_hand and on_demand behave similarly. So, because it's stock management, I actually think it's a nice exception to the rule of letting the consumers control persistence.

4. **improvements** to this: I believe that if we keep these saves in on_hand and on_demand we make it better by removing attribute_accessible, i.e., these methods need to be called explicitly by the consumers.

3. I believe this the best of the **alternatives** we have so far. what other alternatives do we have? any ideas? maybe some kind of after_save hook on variant to persist the stock_item? I am not sure...

**Comment by luisramos0** [comment]
This PR fixes 4 tests:
spec/controllers/cart_controller_spec.rb:35
spec/controllers/cart_controller_spec.rb:41
spec/controllers/cart_controller_spec.rb:47
spec/models/spree/line_item_spec.rb:92

File: app/models/concerns/variant_stock.rb (hunk 1 above)
Comment (mkllnk) [reply app/models/concerns/variant_stock.rb]: Good thoughts. Saving the stock items after saving the variant seems reasonable to me. Worth a try?

There is a difference between on_hand and on_demand in the way they have to be synchronised. on_demand is set by a manager and not modified during checkout. It has only two values. Locking is not essential.

The on_hand value is very critical though. And offering an admin interface to set stock levels is ambiguous. What if the manager counts the product on the shelf and finds that there are `5` while the database still shows `6` (someone was hungry last night). Now the manager enters `5` while a customer buys one at the same time. Should we save `5` or `4`? I think the new Spree 2 approach is wise in allowing only stock increase and decrease, no direct setting. It would end up with `4`.

As long as we keep this consistent (`new_level - stock_item.count_on_hand` uses the two values from the same point in time) it doesn't matter when we save it to the database.

Comment (luisramos0) [reply app/models/concerns/variant_stock.rb]: >> Saving the stock items after saving the variant seems reasonable to me. 

Rethinking about it. I think the solution in this PR is better. It's more explicit than having callbacks.

Another approach could be to remove on_hand from mass assigments and keep on_demand as mass assignable. That would make the API a bit weird as users would have to save after on_demand but not after calling on_hand.
I think in this case, this would be the normal usage:
variant.on_demand = false
variant.on_hand = 4
variant.save
But I am not sure how to make this sequence work correctly:
variant.on_demand = false
variant.save
variant.on_hand = 4

Do you guys think that would be better than the current PR?

Comment (sauloperez) [reply app/models/concerns/variant_stock.rb]: I just read both of your comments and let's go with this PR. After the upgrade there will be for sure a cleanup phase where we'll realize about the long term implications of all these small trade-offs #iterate

Thanks for making thoughtfull and objective discussions. We rock :muscle:!

Comment (luisramos0) [reply app/models/concerns/variant_stock.rb]: ok, cool! This moves us to 90 broken tests in the 2-0-stable build.

**Comment by luisramos0** [comment]
just to finish the gif story on this one:
giphy 2

**Comment by sauloperez** [comment]
He was my hero @luisramos0 !
