### PR TITLE
Vouchers part 2

### LINKED ISSUE #10857: [Vouchers] Errors when/from iterating between /summary and /cart page
## Description

_This is treated as one issue, as it seems to me (I might be wrong) that this is all coming from the same root cause. Also related to #10855_

After adding a voucher and while on the confirmation page, the user may opt for returning to either the /cart page (editing quantities, for ex.):

- If there are no taxes on the order/voucher -> voucher is removed from the order
- If there are taxes on the order/voucher, and `voucher amount` > `order.total` -> snail
- If there are taxes on the order/voucher, `voucher amount` <= `order.total` -> additional parcels will be created for the voucher, on each /summary page visit, till a snail is triggered

**Bugsnag**
https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6464d03f630d0f000895ebe9?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging&event_id=6464d90700bd31520e150000

## Expected Behavior

The user should be able to iterate between `/summary` and the `/cart` pages.

## Actual Behaviour

Iterating between the `/cart` and `/summary` pages triggers a snail.

## Steps to Reproduce

For all voucher issues: per-requisites are:
- As super admin - enable the vouchers feature toggle
- Having a hub with at least one voucher created
- The hub should have an open shop

An order/line item/customer with no taxes:

1. As a customer, on the shopfront, add items to the cart and proceed to the `/summary` step

image

2. Open the side menu and visit the /cart page. 

image

**no taxes on the order/voucher** 

3. Click Checkout button, to return to the /summary page -> notice the voucher was removed from the order.

image

**taxes on the order/voucher, and `voucher amount` > `order.total` -> snail**

3. Open the side menu and visit the /cart page. Click Checkout button -> :snail: 

image

## Animated Gif/Screenshot

image

## Workaround

- returning to the /payment step, and re-adding the voucher
- If error 500 is triggered, then the user is "stuck" -> only way out is emptying the cart on the `/cart` page

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #10857, #10865, #10869, #10855 and #10787

Brings in a few changes to the way vouchers are applied at the checkout.

- Splits the voucher form fields in the checkout payment step out into a separate `<form>` so it can submit to a separate controller as mentioned here https://github.com/openfoodfoundation/openfoodnetwork/pull/10587#issuecomment-1529844054
- Extracts all the voucher-applying logic out of the checkout controller and into a `create` action in the voucher controller (alongside the existing `delete` action which is already there)
- Improves visual feedback in the UI when a voucher isn't found
- Introduces the concept of a "zero priced order" explicitly into the code, which is needed in various places. This is an order which is valid and has line items but also has an order total of zero. This can be either because a shop has products with zero price (see https://github.com/openfoodfoundation/openfoodnetwork/issues/10787) or now (more commonly) because applying a voucher can bring the order's total to zero. There are a number of places the codebase needs to know about this "zero priced order" case and treat it as a valid scenario and a valid order, and previously it was not doing that.
- Adds some slightly new behaviour for handling these "zero priced order" cases during the checkout; namely that if the order total is zero, the payment method options are hidden and the user sees feedback that payment is not required. This is also shown in the order confirmation. A payment object with an amount of `0.0` gets added to the order in this case and the order can be completed successfully.

#### What should we test?

If an order is valid but doesn't require payment then... it doesn't require payment. Adding a voucher that brings the order total to zero hides the payment method options and lets the user know that no payment is required. The order can be completed successfully.

voucher

#10857, #10865, #10869, #10855 and #10787 should all be fixed/closed.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### Follow up required
* There's probably various changes that need to be made around tax adjustments on vouchers
* Also update email template to match checkout summary (https://github.com/openfoodfoundation/openfoodnetwork/pull/11135#issuecomment-1619485712)

### CODE REVIEW

**Comment by drummer83** [comment]
This shouldn't be in column 'closed', should it?

**Comment by rioug** [comment]
When a voucher is applied to an order with tax excluded from the price, two voucher adjustment are created, one for the voucher and one for the tax component. I fixed the `VoucherAdjustmentsController#destroy` to take that into account.

File: app/helpers/spree/payment_methods_helper.rb [hunk 1]
```diff
@@ -4,12 +4,13 @@ module Spree
   module PaymentMethodsHelper
     def payment_method(payment)
       # hack to allow us to retrieve the name of a "deleted" payment method
-      id = payment.payment_method_id
+      return unless (id = payment.payment_method_id)
```
Comment (rioug) [inline app/helpers/spree/payment_methods_helper.rb:7]: I find this hard to read and it's easy to miss you are not doing a comparison here (my rails console also gives me a nice warning : warning: found '= literal' in conditional, should be ==) .
I'd prefer something like this for clarity:
```suggestion
      id = payment.payment_method_id
      return if id.nil?
```

File: spec/requests/voucher_adjustments_spec.rb [hunk 2]
```diff
@@ -4,55 +4,120 @@
...
+  let(:shipping_method) { distributor.shipping_methods.first }
   let(:voucher) { create(:voucher, code: 'some_code', enterprise: distributor) }
-  let!(:adjustment) { voucher.create_adjustment(voucher.code, order) }
 
   before do
     # Make sure the order is created by the order user, the factory doesn't set ip properly
     order.created_by = user
     order.save!
 
+    exchange.variants << order.line_items.first.variant
```
Comment (rioug) [inline spec/requests/voucher_adjustments_spec.rb:29]: I am lacking context around exchange I think. If I understand correctly, this add the first line item in the order to the exchange (which is an Enterprise from the order cycle point of view ) , is that correct ? If so why is it needed ? and shouldn't the factory `:order_with_line_items` set that up for us ?

**Review by rioug — CHANGES_REQUESTED** [review]
Re added my review from the old PR.

File: spec/requests/voucher_adjustments_spec.rb (hunk 2 above)
Comment (Matt-Yorkley) [reply spec/requests/voucher_adjustments_spec.rb:29]: Yeah it looks like this line can be dropped :+1:

File: app/controllers/voucher_adjustments_controller.rb [hunk 3]
```diff
@@ -5,6 +5,8 @@ class VoucherAdjustmentsController < BaseController
 
   def create
     if add_voucher
+      VoucherAdjustmentsService.calculate(@order)
```
Comment (dacook) [inline app/controllers/voucher_adjustments_controller.rb:8]: This seems to be a fixup for the previous commit.

File: spec/controllers/voucher_adjustments_controller_spec.rb [hunk 4]
```diff
@@ -0,0 +1,78 @@
+# frozen_string_literal: true
+
+require 'spec_helper'
+
+describe VoucherAdjustmentsController, type: :controller do
```
Comment (dacook) [inline spec/controllers/voucher_adjustments_controller_spec.rb]: I was going to say we should move this to a request spec, but I see Gaetan already has 👍

File: app/controllers/split_checkout_controller.rb [hunk 5]
```diff
@@ -203,6 +203,7 @@ def validate_details!
 
   def validate_payment!
     return true if params.dig(:order, :payments_attributes, 0, :payment_method_id).present?
+    return true if @order.zero_priced_order?
```
Comment (dacook) [inline app/controllers/split_checkout_controller.rb:206]: Can we spec for this?

File: app/models/spree/order.rb [hunk 6]
```diff
@@ -621,6 +621,10 @@ def process_each_payment
       raise Core::GatewayError, Spree.t(:no_pending_payments) if pending_payments.empty?
 
       pending_payments.each do |payment|
+        if payment.amount.zero? && zero_priced_order?
+          payment.update_columns(state: "completed", captured_at: Time.zone.now)
+        end
```
Comment (dacook) [inline app/models/spree/order.rb:626]: Can we spec for this?

File: app/helpers/spree/payment_methods_helper.rb (hunk 1 above)
Comment (dacook) [reply app/helpers/spree/payment_methods_helper.rb:7]: +1

I'm surprised we don't have a linter rule for that.

File: app/controllers/voucher_adjustments_controller.rb [hunk 7]
```diff
@@ -6,8 +6,9 @@ class VoucherAdjustmentsController < BaseController
   def create
     if add_voucher
       VoucherAdjustmentsService.calculate(@order)
+      @order.update_totals_and_states
 
-      render_voucher_section
+      update_payment_section
```
Comment (dacook) [inline app/controllers/voucher_adjustments_controller.rb]: We're updating the payment section 👍. But no longer updating the voucher section?

Comment (dacook) [reply app/controllers/voucher_adjustments_controller.rb]: Oh, I that's brought back later in another commit.

**Review by dacook — APPROVED** [review]
Fantastic, looks like a big re-arrange that solves some problems and helps us move forward with vouchers.

I noticed a couple of additions without associated specs that I thought seemed important. If we don't add them now, can they be included in the next round?

Also I have several questions/comments soz :trollface: 

But overall I think this is good to proceed as-is (if the specs are included in the next round).

**Comment by rioug** [comment]
@Matt-Yorkley 
> I think there's probably various changes that need to be made around tax adjustments on vouchers

Is that being addressed anywhere ? are you looking at it ?

**Comment by dacook** [comment]
PS sorry one more question, do we need to update the email confirmation template too?

**Comment by rioug** [comment]
> PS sorry one more question, do we need to update the email confirmation template too?

As the vouchers use adjustment, we get that for free,  adjustments will show on the email confirmation.

**Comment by dacook** [comment]
Actually i was thinking, since we're [updating the confirmation screen](https://github.com/openfoodfoundation/openfoodnetwork/pull/11135/files#diff-720ad36bfcb0c3908a6bb59164606fb24927bafed8af2ec4723db3fceeb5832e) to show "No payment required", this might also be relevant for the confirmation email.

Upon looking, I think it is relevant. The `confirm_email_for_customer` (and several others) use [app/views/spree/shared/_payment.html.haml](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/spree/shared/_payment.html.haml) which I guess would say something like "Not paid". As far as I understand, if we don't update this we'll have an inconsistency within the app.

So.. can we add this in a follow-up PR? (I don't want to stall this one any longer!)

File: app/controllers/admin/vouchers_controller.rb [hunk 8]
```diff
@@ -9,14 +9,11 @@ def new
...
 
     def create
-      voucher_params = permitted_resource_params.merge(enterprise: @enterprise)
-      @voucher = Voucher.create(voucher_params)
+      @voucher = Voucher.create(permitted_resource_params.merge(enterprise: @enterprise))
 
       if @voucher.save
-        redirect_to(
-          "#{edit_admin_enterprise_path(@enterprise)}#vouchers_panel",
-          flash: { success: flash_message_for(@voucher, :successfully_created) }
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply app/controllers/admin/vouchers_controller.rb:18]: I was just trimming it down from 4 lines to 2, and making it consistent style-wise with the flash error declaration below it (with the flash message on it's own line before the response). It looked a bit cleaner to me, but it's not important :shrug:

```ruby
flash[:error] = @voucher.errors.full_messages.to_sentence
render :new
```

File: app/controllers/voucher_adjustments_controller.rb [hunk 9]
```diff
@@ -1,32 +1,66 @@
...
-      status: :ok,
-      cable_ready: cable_car.replace(
-        "#voucher-section",
-        partial(
-          "split_checkout/voucher_section",
-          locals: { order: @order, voucher_adjustment: @order.voucher_adjustments.first }
-        )
+    render cable_ready: cable_car.replace(
+      selector: "#voucher-section",
+      html: render_to_string(
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply app/controllers/voucher_adjustments_controller.rb]: To avoid a double render error. We're just writing a little bit of HTML to a variable here, but in controllers Rails will blow up if you call the `render` method twice.

File: app/controllers/voucher_adjustments_controller.rb (hunk 3 above)
Comment (Matt-Yorkley) [reply app/controllers/voucher_adjustments_controller.rb:8]: I think this commit changed a bit after a rebase. I'll squash it :ok_hand:

File: app/controllers/admin/vouchers_controller.rb (hunk 8 above)
[the remark this answers is not in the document]
Comment (dacook) [reply app/controllers/admin/vouchers_controller.rb:18]: I agree it's not important 👍

**Review by dacook — COMMENTED** [review]
I'm not sure about the usage of `dup`, so am wondering if we can avoid that?

Also I've applied Gaetan's suggestion.

I collated some follow up notes and added to the description of this PR too.

File: app/models/spree/order.rb [hunk 10]
```diff
@@ -222,7 +222,7 @@ def payment_required?
     # There are items present in the order, but either the items have zero price,
     # or the order's total has been modified (maybe discounted) to zero.
     def zero_priced_order?
-      valid? && line_items.count.positive? && total.zero?
+      dup.valid? && line_items.count.positive? && total.zero?
```
[the remark this answers is not in the document]
Comment (Matt-Yorkley) [reply app/models/spree/order.rb]: There are multiple places where this method will be called from (not just one controller), and calling `valid?` flushes all errors on the current order object and re-checks them, which is not desirable in some situations (custom non-ActiveRecord errors added during checkout  being a prime example).

I'll just drop the `valid?` check, maybe it's not necessary.

[the remark this answers is not in the document]
Comment (dacook) [reply app/models/spree/order.rb]: Specs pass... so I guess it's not 🤞

**Review by dacook — APPROVED** [review]
👍 LGTM!

**Review by rioug — APPROVED** [review]
Looks good !

**Comment by filipefurtad0** [comment]
Hey team,

There's quite a lot to unpack here, I think it's best to split this across different tests (evtl. testers). I'll start by:

**1) Testing the new functionality of not having to add a payment method**

i) For a simple order (no taxes or fees):
- adding a voucher in which the total of the voucher equals the order total
  - **hides the payment method selector**, on the `/payment`  step

image

  - allows completing an order (confirmation emails arrive) -> the payment method section is empty in this case

image

  - the same goes for the payment section in the backoffice, when editing the order:
image

  - no taxes are calculated here, as the order total is zero


ii) For an order with at least one enterprise fee with a per-order calculator:
- adding a voucher in which the total of the voucher equals the order total
  - **does not hide the payment method section**. This feels like the correct behavior, as indeed, more expenses will be displayed on the final `/summary` step:

image

  - completing checkout displays the order confimation per email, as usual

image

  - and displays the payment as usual as well, on the backoffice:

image

It's relevant to note, how these orders are displayed in the **Payments report - by Type** - and that this does not make the report blow up :tada: 

image

but that we have a missing translation for the none string:

image

**Comment by filipefurtad0** [comment]
Ok, continuing:

- scenario for #10857

Fixed: a snail is not triggered after visiting the cart page and resuming checkout. However, when resuming checkout, the user always seems to be redirected to the `/details` step (regardless of the previous step), making it start checkout over again -> issue .... (to be edited)

- scenario for #10865

Fixed: I could not reproduce the issue, it seems to have been related orders with `total = 0`.

- scenario for #10869

Fixed:

image

- scenario for #10855

Fixed: Visiting the `/cart` from the `/payment` step (and after adding a voucher) now updates the cart:

image
 
- scenario for #10787

Fixed: it's possible to checkout now for orders with total = 0 (**without adding a voucher**):

image

Order confirmation:

image


**Summary**
Whoa 5 / 5 :star2: 
Minor issue with the redirection to the `/details` page (after visiting the `/cart`).

Merging :muscle:
