### PR TITLE
Cartastrophe

### LINKED ISSUE #4053: Delete a product that is sold in an OC and all buyers with this item in their cart will see an error 500
## Description
As a manager, if I delete a product that is sold in an OC, all buyers with this item in their cart will see an error 500 when trying to reach the website.

## Steps to Reproduce
1. As buyer, add a variant in your cart
2. In a private windows, connect as a manager and delete that product while leaving the OC open
3. Try to reach the website as a buyer again (ANY page) and you will see an error 500, 

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v2.2
* Browser name and version: Firefox 66
* Operating System and version (desktop or mobile): Desktop Ubuntu 19.10

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #4053

Could affect #3907, #4203, others?

Missing Spree::Price records were causing fatal errors in various scenarios where a product had been deleted.

Prices are now soft-deleted and can be accessed by associated variants.

#### What should we test?

- Add a product to the cart
- Go to backoffice and delete the product
- Go back to the cart
- The site is ok, and there's no error 500 

#### Release notes

Added soft-delete to price records to fix issues with soft-deleted products

Changelog Category: Fixed

### CODE REVIEW

**Comment by lin-d-hop** [comment]
:point_up: #checkastrophe @Matt-Yorkley (your pun was better)

**Comment by Matt-Yorkley** [comment]
Okay... there's some weird custom delegation for price via a Spree method called `delegate_belongs_to`, which seems a bit flaky. Also, there's some callback somewhere that's removing the price object and replacing it with a blank one before it can be soft-deleted, so the object still isn't available... :disappointed:

File: app/models/spree/price_decorator.rb [hunk 1]
```diff
@@ -1,7 +1,14 @@
 module Spree
   Price.class_eval do
+    acts_as_paranoid without_default_scope: true
+
     after_save :refresh_products_cache
 
+    # Allow prices to access associated soft-deleted variants.
+    def variant
+      Spree::Variant.unscoped { super }
+    end
```
Comment (luisramos0) [inline app/models/spree/price_decorator.rb]: I think this deserves a unit test.

File: app/models/spree/variant_decorator.rb [hunk 2]
```diff
@@ -91,6 +91,11 @@ def in_stock?(quantity = 1)
     can_supply?(quantity)
   end
 
+  # Allow variant to access associated soft-deleted prices.
+  def default_price
+    Spree::Price.unscoped { super }
+  end
```
Comment (luisramos0) [inline app/models/spree/variant_decorator.rb]: I think this deserves a unit test.

**Comment by Matt-Yorkley** [comment]
> Have you checked whether this patch was introduced in Spree later on in their Git history?

They've done basically the same thing in 2.1:
https://github.com/spree/spree/blob/2bbf2a5a517e5ea62389cd90e58e3e91e14bf117/core/app/models/spree/price.rb#L26-L29
https://github.com/spree/spree/blob/2bbf2a5a517e5ea62389cd90e58e3e91e14bf117/core/app/models/spree/variant.rb#L88-L90

**Comment by sauloperez** [comment]
That's a great validation :+1:

**Comment by RachL** [comment]
Both the scenario in the PR and the linked issue are now fixed :muscle:

image


This is ready to go!

**Comment by luisramos0** [comment]
We should retest #3907 and  #4203 right? this PR is maybe fixing them.

**Comment by RachL** [comment]
@luisramos0 yes that's the plan, but not sure I will managed today, will keep people posted
