### PR TITLE
Changing a variant unit scale from items to weight/volume does not remove variant unit name

### LINKED ISSUE #13026: Changing a variant unit scale from items to weight/volume does not remove variant unit name
## Description

Whilst working on the product export flow in n8n and testing with Product Import, I noticed that changing the variant_unit from items to weight/volume did not remove the custom variant_unit_name as expected. This is not visible in the UI, but is visible in the Products API and the spree_variants database table. This meant that when running a product export via the API or directly querying the database, the old items variant_unit_name appeared which caused problems with importing the same products.

## Expected Behavior

Changing a variant_unit from items to volume/weight should clear the variant_unit_name field, as this field should only be filled when the variant_unit=items, i.e. if variant_unit<>items, variant_unit_name="" 

## Actual Behaviour

Changing variant_unit from items to volume/weight does not clear variant_unit_name. This causes problems when trying to import - clearing the field manually results in 'variant unit name cannot be updated via product import' error, but leaving the field in means that new products are created. This means that any variants formerly created as items cannot be managed via the product import tool

## Steps to Reproduce

1. Create a product variant with variant_unit=items and enter a custom variant_unit_name 
2. Save the variant and observe variant_unit_name in spree_variants and API
3. Change the variant_unit to a weight or a volume, see that the variant_unit_name field disappears from the UI, click save
4. Observe the variant_unit_name field in spree_variants and API. See that variant_unit_name is still the custom value you entered in step 1

## Animated Gif/Screenshot

Former 'item' changed to volume scale
Screenshot 2024-12-10 at 11 43 15
Former 'item' showing in spree_variants with correct scale and measurement, but with variant_unit_name incorrectly persisting
Screenshot 2024-12-10 at 11 46 32
Product import failing when variant_unit_name manually cleared for former items:
Screenshot 2024-12-10 at 12 02 04
Product import failing to match variants and therefore creating new variants, when variant_unit_name matches the (incorrect) old variant_unit_name:
Screenshot 2024-12-10 at 12 01 45

## Workaround

No workaround - only option is to delete and recreate the product. Cloning the product also clones the old variant_unit_name, so the product has to be manually created.

## Severity

bug-s3

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #13026
- This PR resets the variant unit name if the variant unit is changed to any unit other than `items`

#### What should we test?

- As mentioned in the issue

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: spec/models/spree/variant_spec.rb [hunk 1]
```diff
@@ -987,11 +987,11 @@
 
       variant.variant_unit = 'weight'
       variant.variant_unit_scale = 1
-      variant.variant_unit_name = 'g'
```
Comment (chahmedejaz) [inline spec/models/spree/variant_spec.rb:990]: I think we need to remove this step as per the logic described in the issue that only variants with unit equal `items` have the value for `variant_unit_name`, otherwise it should be empty.

File: app/services/variant_units/variant_and_line_item_naming.rb [hunk 2]
```diff
@@ -65,6 +65,7 @@ def update_units
     def unit_value_attributes
       units = { unit_presentation: option_value_name }
       units.merge!(variant_unit:) if has_attribute?(:variant_unit)
+      units.merge!(variant_unit_name: '') if reset_variant_unit_name?
```
Comment (chahmedejaz) [inline app/services/variant_units/variant_and_line_item_naming.rb:68]: Updating with the emtpy string as per Line#123 of the spec:

https://github.com/openfoodfoundation/openfoodnetwork/blob/7302c2d1618118995a73f9f9b467a00eff3fd92f/spec/system/admin/products_spec.rb#L95-L131

**Review by dacook — APPROVED** [review]
Great solution 👍

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz ,

Thanks for fixing this.

Before testing we can indeed verify in the DB, that editing the units from Items to Volume (or Weight) does not remove `variant_unit_name`:

image

After this PR, this clears this attribute:

image

Creating an items variant works as before.

I think its a good idea to test product import before merging, I'll continue at a later stage.

**Comment by RachL** [comment]
@filipefurtad0 I'm stilling staging FR this afternoon, but I should be done when you are back online

**Comment by filipefurtad0** [comment]
Ok @chahmedejaz,

Now tested product import of an variant which was changed from unit_type = item to weight.

After clearing the `variant_unit_name` attribute on the CSV file, it is possible to update the variant, without creating undesired new variants, as reported on #13026.

Merging, thanks!
