### PR TITLE
Bulk product import stalling at 66% when missing info

### LINKED ISSUE #12973: Bulk product import stalling at 66% when missing info
## Description
Bulk product upload function stalls with no error message when unit field is missing info in any row.

## Expected Behavior
The upload should complete and then display error messages about what is wrong with the upload

## Actual Behaviour
The upload does not complete and no error message is shown when there is a field left blank in the upload template. The upload stalls at 66% and does not progress or show an error message

## Steps to Reproduce
Complete a bulk product upload template. 

Leave the 'unit' field blank in one row. 

Upload the csv - see that the upload stalls at 66%. Fixing this blank field allows the upload to complete and other errors are catalogued in the usual error message screen.

## Severity
bug-s2: a non-critical feature is broken, no workaround

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity
-->

## Your Environment
Happens across multiple environments

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12973

- **Root cause and Fix:** https://github.com/openfoodfoundation/openfoodnetwork/pull/13001#discussion_r1862705554
- Along with the above, this PR also fixes error response rendering from the products import controller.

#### What should we test?

- As mentioned in the issue
- Please make sure that the sheet doesn't have the `units` and `on_hand` value present

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/models/product_import/entry_validator.rb [hunk 1]
```diff
@@ -79,10 +79,9 @@ def mark_as_new_variant(entry, product_id)
         if entry.attributes['on_hand'].present?
           new_variant.on_hand = entry.attributes['on_hand']
         end
+        check_on_hand_nil(entry, new_variant)
       end
 
-      check_on_hand_nil(entry, new_variant)
```
Comment (chahmedejaz) [inline app/models/product_import/entry_validator.rb:84]: - If the sheet doesn't have the `units` present, then the variant is not saved due to model validation
- After that, while assigning `on_hand` value in this method, the error is raised that the variant is not created first
- So we need to make sure that the variant is created before calling this method

File: app/controllers/admin/product_import_controller.rb [hunk 2]
```diff
@@ -76,7 +76,7 @@ def process_data(method)
       begin
         @importer.public_send("#{method}_entries")
       rescue StandardError => e
-        render json: e.message, response: 500
+        render plain: e.message, status: :internal_server_error
```
Comment (chahmedejaz) [inline app/controllers/admin/product_import_controller.rb:79]: The UI does not render any error on the import loading screen and stalls because of the existing implementation of the `render` method. The string error message is being passed to the `json` option, which is not valid (_maybe it was valid at the time of implementation_), so the `data` was not present in the error response [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/40531d769c10bba455f6300c8e6b36316516c6c6/app/assets/javascripts/admin/product_import/controllers/import_form_controller.js.coffee#L92-L95), causing the UI to not show any errors.
This is now fixed such that the string message is being returned as plain text, and its `status` option is also set respectively, so the errors on the UI sshowcorrectly now

File: app/controllers/admin/product_import_controller.rb [hunk 3]
```diff
@@ -30,13 +30,13 @@ def import
     def validate_data
       return unless process_data('validate')
 
-      render json: @importer.import_results, response: 200
+      render json: @importer.import_results
```
Comment (chahmedejaz) [inline app/controllers/admin/product_import_controller.rb:33]: Apparently, it's not a valid option anymore. It implicitly returns 200 status.

**Comment by chahmedejaz** [comment]
The same spec is failing in master as well: https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/12076014528/job/33676757352#step:10:72

**Review by mkllnk — APPROVED** [review]
Great work.

**Comment by mkllnk** [comment]
The failing spec was introduced by another PR.

**Review by dacook — APPROVED** [review]
Great 👍

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz,

I could not reproduce the 66% upload bar, but I did notice that the bar does not progress and that there is a console error, **if the Units field is left empty,** on the CSV file:

image

After this PR, the file is uploaded successfully, and an informative error message is displayed to the customer:

image

If **both On hand and On_demand fields are left empty**, then this error message is displayed:

image

If all mandatory fields are filled in, then products are updated:

image

Looks great :tada: 
Merging.
