### PR TITLE
Prevent error on inventory page when logged out

### LINKED ISSUE #13315: NoMethodError in admin/variant_overrides#index
## Error in Open Food Network (Rails)

**NoMethodError** in **admin/variant_overrides#index**
undefined method `admin?' for nil:NilClass

    if user.admin?
           ^^^^^^^

[View on Bugsnag](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/680ee525e434b227eaaf64f3?event_id=681f80e4012548b4fd2d0000&i=gh&m=ci)

## Stacktrace

    app/models/enterprise.rb:230 - block in <class:Enterprise>
    lib/open_food_network/permissions.rb:116 - managed_enterprises
    lib/open_food_network/permissions.rb:31 - variant_override_hubs
    app/controllers/admin/variant_overrides_controller.rb:46 - load_data

[View full stacktrace](https://app.bugsnag.com/yaycode/open-food-network-rails/errors/680ee525e434b227eaaf64f3?event_id=681f80e4012548b4fd2d0000&i=gh&m=ci)

*Created by David Cook via Bugsnag*

### PR DESCRIPTION
**Pull request by dacook**
#### What? Why?

- Closes #13315

#### What should we test?
- Log out of OFN
- Visit the inventory page (/admin/inventory)
- [ ] You should be redirected to login
- Log in to OFN
- Visit the inventory page (/admin/inventory)
- [ ] It works!

### CODE REVIEW

File: spec/controllers/admin/variant_overrides_controller_spec.rb [hunk 1]
```diff
@@ -3,6 +3,29 @@
 require 'spec_helper'
 
 RSpec.describe Admin::VariantOverridesController, type: :controller do
+  describe "index" do
+    context "not logged in" do
+      it "redirects to login" do
+        pending
```
Comment (mkllnk) [inline spec/controllers/admin/variant_overrides_controller_spec.rb:9]:
```suggestion
```

File: spec/controllers/admin/variant_overrides_controller_spec.rb [hunk 2]
```diff
@@ -3,6 +3,29 @@
...
+        get :index
+        expect(response).to have_http_status :found
```
Comment (mkllnk) [inline spec/controllers/admin/variant_overrides_controller_spec.rb:11]:
```suggestion
        expect(response).to redirect_to xxx_path
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
Nice TDD.

File: spec/controllers/admin/variant_overrides_controller_spec.rb (hunk 1 above)
Comment (dacook) [reply spec/controllers/admin/variant_overrides_controller_spec.rb]: 🤦 
Fixed in amended commit.

File: spec/controllers/admin/variant_overrides_controller_spec.rb (hunk 2 above)
Comment (dacook) [reply spec/controllers/admin/variant_overrides_controller_spec.rb]: I skipped this before because it's not a simple path and it didn't seem too important. But seeing as you've mentioned it, I've updated it now 🙂

**Review by mkllnk — APPROVED** [review]
Perfect.

**Review by rioug — APPROVED** [review]
Nice :+1:

**Comment by drummer83** [comment]
Hi @dacook,
Thanks for looking into this! :muscle: 

### Before
- Log out
- Visit inventory page 
- Error 500 :boom: 

### After
- Log out
- Visit inventory page
- Redirected to Log in
- Log in
- Redirected to inventory page :heavy_check_mark: 

## Conclusion
I can confirm that this is working fine now. No error 500 is shown.
Merging. :rocket: :tada:
