### PR TITLE
Reset order state to cart in case the stripe SCA authorization step fails

### LINKED ISSUE #5816: Stripe-SCA payment do not include ship/transaction fees (on a second payment attempt)
## Description

PR #5798 introduced changes to address the bug described in issue #5774. This relates to incorrect payment amounts processed by Stripe payments, after a first failed attempt, due to an invalid card. These incorrect payment amounts relate to transaction and shipment fees, set by the shop.

It was verified that this PR solves the issue for Stripe-Connect but that the issue persists with Stripe-SCA, namely it what concerns enterprise fees - which is the scope of the present issue.

## Expected Behavior

After a failed payment attempt, a successful payment should cover the total value of the order, including fees.

## Actual Behaviour

After a failed payment attempt, a successful payment does not cover the total value of the order: transaction fees remain marked as "Balance Due (€xx)".

## Steps to Reproduce

Admin
1. Set a transaction for Stripe-SCA and a shipment fee. Open an OC with these payment and shipment methods.

Customer
2. Insert items in the cart, from the above mentioned OC, proceeding to checkout.
3. Choose Stripe-SCA as payment method and Insert the invalid card 4000000000000069 (Charge is declined with an expired_card code)
4. Insert a valid test card (with or without 3D-authentication)
5. Check the total value of your order on the order confirmation

Admin
6. Compare the order total with:
i) Stripe Dashboard
ii) /orders page

Verify the values don't match with the order total. In i) and ii) it should be visible that:

Total order amount = charged amount + transaction fee

Depending on the card used, a failed payment may appear as well under:
iii) /admin/orders/Rxxxxxxxxxxx/payments

## Animated Gif/Screenshot

- Stripe Dashboard:

image

- /orders page (Admin):

image

## Workaround

No workaround

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: Observed while testing PR #5798, which should integrate v3.2.0
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

Perhaps related to #5818 .

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #5816 and #5818
I am putting these two fixes together in one PR because they are not too big but mostly so we can test these things together, they are different but closely related.

Regarding #5816
The handler of any gateway exceptions is used for the StripeSCA authorization step. Whenever there's an error on checkout we need to reset the order to cart state.
We were not doing that before and that was causing the order to stay in the payment state after an authorization error. Because the order was in the payment state, the callback to update order totals was not executed on the second attempt and that caused not all fees to be collected #5816

This is a generic improvement so it will make the checkout code more resilient for some other cases as well.

Regarding #5818
Here we are adding an alternative to [the infamous after_rollback callback called persist_invalid for the payment model](https://github.com/openfoodfoundation/spree/blob/0b0c422369c82b6dd7e7cb627a24e3a9fca19a6c/core/app/models/spree/payment.rb#L35).
On checkout, in the situation where we are [handling a redirect from stripe](https://github.com/openfoodfoundation/openfoodnetwork/blob/add7bb489f52e73b6763ad32c033cf401c57fac7/app/controllers/checkout_controller.rb#L159) and capturing the payment, the payment is correctly set to **failed state** but the order workflow state machine rolls it back to **pending state** causing #5818. Here we are adding some logic to the OrderWorkflow service to persist the payments after a failure so we get the data for debugging.
Related to this there's a good refactoring with code moved from checkout controller to the OrderWorkflow service.

Additionally, while investigating I thought I'd have to patch the checkout workflow code, in the end I didnt but I ended up bringing the checkout.rb file from spree_core to OFN. No changes to it, just rubocop and transpec.
 
#### What should we test?
We need to verify the issue is solved.
The code changed is related to any errors that happen on the stripe side so we can test any other error scenario on stripe and verify that fixing it will process the payment in stripe with the correct amount. For example, we can check if this will also work if we use a card that needs external authorization and we fail the validation.

I just verified that #5816 is also present when we use a card like 4000 0027 6000 3184 and press "fail authentication". So:
- on first attempt use 4000 0027 6000 3184 and press "FAIL authentication"
- on second attempt use 4000 0027 6000 3184 and press "COMPLETE authentication"
This test case should fail before this PR and pass after this PR :+1:

#### Release notes
Changelog Category: Fixed
Fixes StripeSCA problem where the second attempt to make a payment would fail even the card and details were valid.

### CODE REVIEW

File: app/controllers/checkout_controller.rb [hunk 1]
```diff
@@ -261,6 +253,13 @@ def update_failed_response
     end
   end
 
+  def rescue_from_spree_gateway_error(error)
+    flash[:error] = t(:spree_gateway_error_flash_for_checkout, error: error.message)
+    # This can also happen during the edit action
+    #   but the actions and response needed are exactly the same as when the update action fails
+    update_failed(error)
+  end
```
Comment (luisramos0) [inline app/controllers/checkout_controller.rb:261]: the key difference here is the call to checkout_failed in update_failed that executes PostCheckoutActions that will reset the order state to cart :+1:

**Comment by sauloperez** [comment]
looks like we had an infinite loop in the build.

**Comment by luisramos0** [comment]
ah, yeah, I missed that. I'll have a look now,. Thanks!

**Comment by luisramos0** [comment]
I tried to fix the build but this after_rollback callback breaks the specs because the specs always rollback the transactions...

I saw that Spree also removes this callback in v2.3.

So I tried to create a better solution. It was hard but I think I do have a slightly better workaround for this.

**Comment by mkllnk** [comment]
The specs need more work, moving back to in-dev.

**Comment by mkllnk** [comment]
I fixed all the obvious specs but there are still some failing:
```
rspec ./spec/features/consumer/shopping/checkout_spec.rb[1:1:4:2:2:5:1:1]
rspec ./spec/features/consumer/shopping/checkout_spec.rb[1:1:4:2:2:5:2:1]
rspec ./spec/features/consumer/shopping/shopping_spec.rb:414
```

The last one passed locally and may be flaky but the first two are definitely broken by this pull request. The credit card secrets are not passed onto the payment gateway and without valid credit card number it fails.

**Comment by mkllnk** [comment]
Reloading the payment is a problem:
https://github.com/openfoodfoundation/openfoodnetwork/blob/07005594ff09a688f8a1af0a5a6afe4c3d1325cc/app/services/order_workflow.rb#L67

While the records look exactly the same, I guess that reloading gets rid of in-memory data like the credit card secrets.

**Comment by mkllnk** [comment]
@luisramos0 I'm handing the keyboard back to you. Let me know what you think. I guess we can go ahead with this fix and create a tech debt issue. Or we investigate fixing the callback. You may have a better overview of that and it may make more sense to tackle that in bye-bye-spree.

File: app/controllers/checkout_controller.rb [hunk 2]
```diff
@@ -261,6 +242,13 @@ def update_failed_response
     end
   end
 
+  def rescue_from_spree_gateway_error(error)
+    flash[:error] = t(:spree_gateway_error_flash_for_checkout, error: error.message)
+    # This can also happen during the edit action
```
Comment (sauloperez) [inline app/controllers/checkout_controller.rb:247]: IMO we should stick to the `rescue_from` defined at line 35 for both `#edit` and `#update` or the rescue block but having separate approaches makes things harder. This PR is a good chance.

File: app/services/order_workflow.rb [hunk 3]
```diff
@@ -35,9 +43,31 @@ def advance_order!(options)
...
+
   def after_transition_hook(options)
     if order.state == "delivery"
       order.select_shipping_method(options[:shipping_method_id]) if options[:shipping_method_id]
     end
+
+    persist_all_payments if order.state == "payment"
   end
+
+  # When a payment fails, the order state machine rollbacks all transactions
```
Comment (sauloperez) [inline app/services/order_workflow.rb:62]: just thinking out loud. If that's not what we want we'll need to split up that single transaction at some point so that a rollback while persisting payment doesn't affect the order changes. Definitely not today. Removing that callback is a lot already.

Comment (luisramos0) [reply app/services/order_workflow.rb:62]: yeah, I'd love to do that, but I think it's state_machine that does the rollback by default if the workflow step returns false.
btw, that's why I brought Checkout.rb from spree, because I was trying to do exactly that. But I dont know enough about the state_machine gem... the other problem is that we may want the rollback to happen for other objects other than the payments...

File: app/controllers/checkout_controller.rb (hunk 2 above)
Comment (luisramos0) [reply app/controllers/checkout_controller.rb:247]: I removed this comment and renamed the update_failed method to action_failed. I think that makes it more clear. It's just a generic method, not specific to edit or update.

But this takes me to another detail of this method.
The specific rescue in the update action that calls this method was added by Maikel here:
https://github.com/openfoodfoundation/openfoodnetwork/commit/bd67d63b63cca3c889755d95fcf1dd94a16ae9e0
Maybe it's a mistake because this checkout controller already had and still has the generic:
 `rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error`
Maybe we can just remove this rescue from the update action? I think we can. I am just asking because this is such a critical part of the checkout process.

Comment (sauloperez) [reply app/controllers/checkout_controller.rb:247]: > Maybe we can just remove this rescue from the update action?

I believe we can, otherwise, Rails would be broken

File: app/services/order_workflow.rb (hunk 3 above)
Comment (sauloperez) [reply app/services/order_workflow.rb:62]: yes, it feels like heart surgery. Overall, I'm a bit concerned about our current status where things are partially implemented in the Spree order state machine, plus patched on our checkout controller and our services. I guess I just need to believe in us while we simplify our customizations up until the day we can question the state machine's implementation.

File: app/controllers/checkout_controller.rb (hunk 2 above)
Comment (luisramos0) [reply app/controllers/checkout_controller.rb:247]: ah, I think I see why we need this now! If I remove the first rescue the second more generic rescue will be triggered and the rescue_from rule will not be used as we want. This is why Maikel added it I am pretty sure, I think I'll add a comment to explain this :+1:

File: app/services/order_workflow.rb (hunk 3 above)
Comment (luisramos0) [reply app/services/order_workflow.rb:62]: yeah, I see what you mean, but we are improving!

File: app/controllers/checkout_controller.rb (hunk 2 above)
Comment (luisramos0) [reply app/controllers/checkout_controller.rb:247]: I ended up removing the rescue_from line and adding the rescue to the edit action. I think this makes it very simple:
- edit rescues GatewayError
- update rescues GatewayError and StandardError

**Comment by luisramos0** [comment]
hey @mkllnk nice async pair programming! Thank you!

I think your fix works! I am not sure the persisted failed payments will end up with all the info but it doesnt matter for now, first checkout will now work and second, we will have spree_log_entries which is the most important.

I added a few more simple commits.
I think this is ready to move forward.

File: app/services/order_workflow.rb [hunk 4]
```diff
@@ -64,8 +64,8 @@ def after_transition_hook(options)
   def persist_all_payments
     order.payments.each do |payment|
       original_payment_state = payment.state
-      if original_payment_state != payment.reload.state
-        payment.update(state: original_payment_state)
+      if original_payment_state != Spree::Payment.find(payment.id).state
+        payment.reload.update(state: original_payment_state)
```
Comment (mkllnk) [inline app/services/order_workflow.rb:68]: I'm still a bit confused what's happening here. Do we need a comment explaining that? My theory is:

- During checkout the order is going to state `payment` and a payment object is created.
- The order should go from state `payment` to `complete` but on error the state machine stays in `payment`.
- The payment object's normal states are: `checkout`, `pending`, `processing`, `completed`
- Error states are: `void` and `invalid`.
- A failed checkout causes a database rollback which reverts the payment state from `void` or `invalid` to `checkout` or `pending` (I don't know which).
- Despite the rollback, our in-memory payment object still has the failed state.
- Checking for a state change in the database is a sign of a rollback and we override the database with our payment state.
- In theory, if something else updated the payment record at the same time, like a webhook, we could accidentally override that. There is a potential race condition here but we are most likely fine because of the checkout sequence and synchronisation.

Do you agree with this?

What else could happen? I guess a payment could complete but something else fails and we override the payment state to mark it as completed. That's a good thing.

I reckon that the payment should happen outside of the state machine transition to not be affected by the rollback. The state machine transition just verifies that there is enough money for the order. Out of scope here.

Comment (luisramos0) [reply app/services/order_workflow.rb]: I dont agree about you being confused :-)
I think what's happening is exactly what you have described :ok_hand: and that was what I thought was happening :+1: 
I used some of your description to add code comments. I think it's now better explained, thanks!

**Comment by filipefurtad0** [comment]
Hey @luisramos0 and reviewers,


- About #5816 

Reproduced issue and re-ran the procedure, after staging - for both Stripe-SCA and Connect (which was already working before). This looks good, transaction fee is now correctly charged, after failing the payment once, with card ...0069. Amounts match in stripe-dashboard and on Payments (while editing the order):

image

image

Also verified we now get a warning on [Bugsnag/Slack](https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1596213668446700) on this type of failed payments - which is really awesome, surely helpful as well for issues such as #5785 ! This works for both stripe methods.

- About #5818

Reproduced the issue before staging. True, it seems to break as well by manually failing the 3D authentication process. So, after this PR the process goes as expected, after the first failed attempt:

image

No additional transaction fees are added, for each failed attempt - I tried several other invalid cards, such as 4000008260003178 (insufficient funds) or 4000008400001629 (card_declined), verifying that these errors appear in Bugsnag and in stripe's Dashboard, correctly:

image


Both issues are solved - and we've got data on errors now. Awesome work :muscle: 
Good to go.

**Comment by luisramos0** [comment]
This is great news. I will include this in this release 3.2.1 making it fully ready for the stripeSCA rollout :tada:

**Comment by lin-d-hop** [comment]
@filipefurtad0 
Did you test this when taking payments in the backend?
On release testing I tried placing an order with an SCA card in the backend and it failed.
I think this needs a new issue.
