### PR TITLE
Use :user factory instead of build_stubbed to create the current_api_…

### LINKED ISSUE #3034: [Spree Upgrade] Fix spree api products_controller spec (10 broken tests)
Fix broken specs in spec/controllers/spree/api/products_controller_spec.rb

```
29) Spree::Api::ProductsController as a normal user should deny me access to managed products
      Failure/Error: assert_unauthorized!
      
        expected: {"error"=>"You are not authorized to perform that action."}
             got: {"exception"=>"stubbed models are not allowed to access the database - Spree::User#save!()"} (using ==)
        Diff:
        @@ -1,2 +1,2 @@
        -"error" => "You are not authorized to perform that action.",
        +"exception" => "stubbed models are not allowed to access the database - Spree::User#save!()",
        
      # ./spec/controllers/spree/api/products_controller_spec.rb:27:in `block (3 levels) in <module:Spree>'

  30) Spree::Api::ProductsController as an administrator retrieves a list of managed products
      Failure/Error: keys = json_response.first.keys.map{ |key| key.to_sym }
      
      NoMethodError:
        undefined method `keys' for #<Array:0x007fd3cf1de750>
      # ./spec/controllers/spree/api/products_controller_spec.rb:67:in `block (3 levels) in <module:Spree>'

  31) Spree::Api::ProductsController as an administrator retrieves a list of products with appropriate attributes
      Failure/Error: keys = json_response.first.keys.map{ |key| key.to_sym }
      
      NoMethodError:
        undefined method `keys' for #<Array:0x007fd3ce716750>
      # ./spec/controllers/spree/api/products_controller_spec.rb:73:in `block (3 levels) in <module:Spree>'

  32) Spree::Api::ProductsController as an administrator sorts products in ascending id order
      Failure/Error: ids = json_response.map{ |product| product['id'] }
      
      TypeError:
        no implicit conversion of String into Integer
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `[]'
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `block (4 levels) in <module:Spree>'
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `each'
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `map'
      # ./spec/controllers/spree/api/products_controller_spec.rb:83:in `block (3 levels) in <module:Spree>'

  33) Spree::Api::ProductsController as an administrator formats available_on to 'yyyy-mm-dd hh:mm'
      Failure/Error: json_response.map{ |product| product['available_on'] }.all?{ |a| a.match("^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$") }.should == true
      
      TypeError:
        no implicit conversion of String into Integer
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `[]'
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `block (4 levels) in <module:Spree>'
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `each'
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `map'
      # ./spec/controllers/spree/api/products_controller_spec.rb:90:in `block (3 levels) in <module:Spree>'

  34) Spree::Api::ProductsController as an administrator returns permalink as permalink_live
      Failure/Error: json_response.detect{ |product| product['id'] == product1.id }['permalink_live'].should == product1.permalink
      
      TypeError:
        no implicit conversion of String into Integer
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `[]'
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `block (4 levels) in <module:Spree>'
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `each'
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `detect'
      # ./spec/controllers/spree/api/products_controller_spec.rb:95:in `block (3 levels) in <module:Spree>'

  35) Spree::Api::ProductsController as an administrator soft deletes a product
      Failure/Error: response.status.should == 204
      
        expected: 204
             got: 422 (using ==)
      # ./spec/controllers/spree/api/products_controller_spec.rb:112:in `block (3 levels) in <module:Spree>'

  36) Spree::Api::ProductsController#clone as a normal user denies access
      Failure/Error: assert_unauthorized!
      
        expected: {"error"=>"You are not authorized to perform that action."}
             got: {"exception"=>"stubbed models are not allowed to access the database - Spree::User#save!()"} (using ==)
        Diff:
        @@ -1,2 +1,2 @@
        -"error" => "You are not authorized to perform that action.",
        +"exception" => "stubbed models are not allowed to access the database - Spree::User#save!()",
        
      # ./spec/controllers/spree/api/products_controller_spec.rb:127:in `block (4 levels) in <module:Spree>'

  37) Spree::Api::ProductsController#clone as an administrator responds with a successful response
      Failure/Error: expect(response.status).to eq(201)
      
        expected: 201
             got: 422
      
        (compared using ==)
      # ./spec/controllers/spree/api/products_controller_spec.rb:158:in `block (4 levels) in <module:Spree>'

  38) Spree::Api::ProductsController#clone as an administrator clones the product
      Failure/Error: expect(json_response['name']).to eq("COPY OF #{product1.name}")
      
        expected: "COPY OF Product #447 - 856"
             got: nil
      
        (compared using ==)
      # ./spec/controllers/spree/api/products_controller_spec.rb:163:in `block (4 levels) in <module:Spree>'

```

### PR DESCRIPTION
**Pull request by HugsDaniel**
#### What? Why?

Closes #3034

Surprisingly enough, changing `build_stubbed(:user)` to `create(:user)` for the `current_api_user` fixed all the failing specs from #3034.
It was returning an exception with message `stubbed models are not allowed to access the database - Spree::User#save!()\`, which was making all accesses fail, so all specs accessing the database fail as well.

#### What should we test?

Specs in `spec/controllers/spree/api/products_controller_spec.rb` pass.

### CODE REVIEW

File: spec/controllers/spree/api/products_controller_spec.rb [hunk 1]
```diff
@@ -10,7 +10,7 @@ module Spree
     let(:product_other_supplier) { create(:product, supplier: supplier2) }
     let(:attributes) { [:id, :name, :supplier, :price, :on_hand, :available_on, :permalink_live] }
 
-    let(:current_api_user) { build_stubbed(:user) }
+    let(:current_api_user) { create(:user) }
```
Comment (luisramos0) [inline spec/controllers/spree/api/products_controller_spec.rb]: ahaha, nice. I tried build and it also works. build is faster than create. the spec runs in 9secs with build and 12s with create.

**Comment by sauloperez** [comment]
It's sad that we have to depend even more on the DB but :+1:

**Comment by luisramos0** [comment]
Amazing!
