### PR TITLE
Prevent saving the enterprise fee when a per order calculator is selected along with 'Inherit from product'

### LINKED ISSUE #10348: Tax not charged on Enterprise Fee, when tax category set to "Inherit from product"
## Description

If an enterprise fee is set to Inherit From Product, then tax is not charged over the value of the fee.

## Expected Behavior

~~The `inherit from product` option should work: tax should be charged over the value of the enterprise fee.~~

EDIT: to be defined.

## Actual Behaviour

The `inherit from product` option is not working: tax is not charged over the value of the enterprise fee.

## Steps to Reproduce

(tricky... here we go:)

As superadmin:
1. Create a zone
2. Create a tax category
3. Create a tax rate linking the zone and the tax category

As admin:
4. Create an enterprise fee with the `Flat rate (per order)` calculator and set the tax category to `<tax_category_name>` (created in 2.), with a non-zero amount.
5. Create a product with a tax category having a tax rate for the zone created in 1.
6. Create an order cycle: Add the product created in 2. (incoming and outgoing exchanges) and the enterprise fee created in 1. to outgoing exchange
7. Create an for a customer with billing address within the zone (shopfront or backoffice) and with the product created in 5. (the order should contain **only** this product)

=> if all is well, you should have an order with tax applied to both the product and the enterprise fee (this is the correct behavior, but it is necessary to make sure this works, to observe the bug)

8. Edit the enterprise fee: set it to `Inherit from Product`
9. Repeat step 7

=> Notice tax was only charged on the product, not the enterprise fee.

## Animated Gif/Screenshot

image

## Workaround

Selecting the desired tax category, instead of using the `Inherit from Product` option.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.2.32
* Browser name and version: Firefox
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

Not really a fix, but a "workaround" could be to remove this option from the UI, to prevent the bug. While doing so, we would need to make sure the blank option is selected by default.

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #10348

#### What should we test?

- Go to the Enterprise Fees page
- Selected an existing Enterprise Fee ( or you  can create a new one )
- select 'Inherit From Product' as the tax category
- select any 'Per Order' calculator.
- Fill in the remaining field if you're creating a new enterprise fee.

You should see an error message:
""You cannot select 'Inherit From Product' when a per order calculator is selected""
#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
Thanks for this one. I think it is worth creating a controller spec for this particular case, what do you think?

**Review by mkllnk — APPROVED** [review]
Good work. I added another commit to show how you can simplify the translation of the error message.

Before, the error message included the attribute name which looked odd:
Screenshot from 2023-03-06 14-22-48

But now it's just the new message which I tested in the spec and manually with the dev server.

Another improvement would be to move this code to a validation method instead of a `before_save` action. It would then show this error message along with other validation errors. The existing code would need to be called before validation then as well. Feel free to open a pull request for that if you like to play around with it.

I'm moving this to test ready for now so that we get the bug fix in the next release.

**Comment by abdellani** [comment]
@mkllnk 
This is new to me.
Thank you :)

**Comment by filipefurtad0** [comment]
Hey @abdellani,

I think we need a second thought on this one.

If we have a previously existing enterprise fee - even if set as per item:
- updating the page, i.e., creating or editing always triggers the error

image


Also, I've tested from a situation where we have no **previous enterprise fees**: the error seems to always get triggered, also when creating a fee with a calculator operating over items:

image

In fact, clicking update with an empty form triggers the warning as well.

For this reason, I think we should move this one back to In dev for now.

-------------------------

In any case, for the next iteration, I think we need to consider the case of pre-existing fees applied at the order level + the "Inherit from product": 

image

In this situation, the user will not be able to update this page, unless, previously created fees are changed; I'm not sure how to deal with these. I'll add some more comments to the issue. Moving back to In Dev for now.

File: spec/models/enterprise_fee_spec.rb [hunk 1]
```diff
@@ -9,6 +9,19 @@
...
+        :enterprise_fee,
+        inherits_tax_category: true,
+        calculator: Calculator::FlatRate.new
+      )
+
+      expect(subject.save).to eq false
+      expect(subject.errors.full_messages.first).to eq(
+        "Inheriting the tax categeory requires a per-item calculator."
+      )
+    end
```
Comment (filipefurtad0) [inline spec/models/enterprise_fee_spec.rb:24]: In addition to this one, I'd suggest to add an it block, in which the validation is not triggered and saving into the DB is successful.

**Review by filipefurtad0 — COMMENTED** [review]
Also, maybe this one would be suitable to add a request spec in which:
- submitting a order fee + inherit option -> error message + HTTP status code 304 (Not Modified)
- submitting a item fee + inherit option -> no error message + HTTP status code 200

Would this make sense?

**Comment by abdellani** [comment]
Hi @filipefurtad0 

I tested the two first scenarios and I was not able to reproduce the issue locally.

Screenshots:

>If we have a previously existing enterprise fee - even if set as per item:
>
>* updating the page, i.e., creating or editing always triggers the error


image


>Also, I've tested from a situation where we have no previous enterprise fees: the error seems to always get triggered, also when creating a fee with a calculator operating over items:


image

Did I miss anything?

--------------

>In any case, for the next iteration, I think we need to consider the case of pre-existing fees applied at the order level + the "Inherit from product":


Since it's not a valid configuration, maybe we can reconfigure the existing enterprise fees to the closest valid configuration? or maybe remove them?

**Comment by filipefurtad0** [comment]
Thanks for checking @abdellani .

> I tested the two first scenarios and I was not able to reproduce the issue locally.

I'll test again, at staging environment, and locally as well, on a test environment.

**Comment by filipefurtad0** [comment]
Hey @abdellani,
 
In a test environment, indeed this is possible: I've created some test cases [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/10539).

In staging however, I can't seem to create any fees, also in new enterprises. I've logged into the server and checked the logs, I think this might be happening because the validation occurs also over other previously created fees, for other enterprises:

image

Any ideas?

**Comment by abdellani** [comment]
Hi @filipefurtad0 
I check the controller's code.

https://github.com/openfoodfoundation/openfoodnetwork/blob/62d0ce290a53ba616e9894a14c30e32de0f616a7/app/controllers/admin/enterprise_fees_controller.rb#L38-L47

It looks like `Sets::EnterpriseFeeSet` loads all the existing enterprise fees.

https://github.com/openfoodfoundation/openfoodnetwork/blob/62d0ce290a53ba616e9894a14c30e32de0f616a7/app/services/sets/enterprise_fee_set.rb#L3-L11

One solution is to update the existing enterprise fees that have an invalid configuration. What do you think?

**Comment by filipefurtad0** [comment]
Hey @abdellani 

> It looks like Sets::EnterpriseFeeSet loads all the existing enterprise fees.

:muscle: Thanks for verifying this!

> One solution is to update the existing enterprise fees that have an invalid configuration. What do you think?

Yes, indeed. We were discussing this yesterday with @RachL and @jibees, some thoughts:
- for the invalid cases we'd ideally replace the selected option "Inherit from product" with a tax category which needs to be associated to a zero tax rate
- in these cases, the `enterprise_fee` has `inherits_tax_category` = `true` -> it should be set to false
- this should concern only calculators with `calculable_type` = `"EnterpriseFee"` and with `type` like ` flat rate per order`, `flexible rate per order`, `price sack`

File: db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb [hunk 2]
```diff
@@ -0,0 +1,16 @@
+# frozen_string_literal: true
+
+class DisableInheritsTaxCategoryFromPerOrderEnterpriseFees < ActiveRecord::Migration[6.1]
+  def change
+    EnterpriseFee.where(id: enterpise_fee_ids)
+      .where(inherits_tax_category: true)
+      .update_all(inherits_tax_category: false)
```
Comment (filipefurtad0) [inline db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb:7]: We set these into `false`, but it is not clear to me (from the code) which tax category will be selected for the fee, in this case. Ideally, it would be something like "None" or category associated to a zero tax rate. Do you know what happens with this migration @abdellani ?

Otherwise, let's move to test ready and test it there. But I feel this is an acceptance criteria which we should not overlook on testing: we need to assure that the migration sets:

- inherits_tax_category: true
- the selected tax category has a zero tax rate associated

The risk here is, that a random or first option is selected, which can lead to incorrect tax rate attribution to enterprise fees. 

I can't tell much more from the code, s

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

Deployment failed, it seems there is something with the migration. I'm transcribing the error below:

` StandardError · An error has occurred, this and all later migrations canceled: Rails attempted to auto-load: /home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-03-21-151843/app/models/enterprise_fee.rb Which is in your project's `app/` directory. The good_migrations gem was designed to prevent this, because migrations are intended to be immutable and safe-to-run for the life of your project, but code in `app/` is liable to change at any time. The most common reason for this error is that you may be referencing an ActiveRecord model inside the migration in order to use the ActiveRecord API to implement a data migration by querying and updating objects. For instance, if you want to access a model "User" in your migration, it's safer to redefine the class inside the migration instead, like this: class MakeUsersOlder < ActiveRecord::Migration class User < ActiveRecord::Base # Define whatever you need on the User beyond what AR adds automatically end def up User.find_each do |user| user.update!(:age => user.age + 1) end end def down #... end end For more information, visit: https://github.com/testdouble/good-migrations`

More details on [bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/6419cb389b0ab60008bbe7c5?event_id=6419cb3700b9d3585fdc0000&i=sk&m=nw) and [semaphore](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/uk-staging/deploys/1607).

Moving back to in dev, for now.

**Comment by abdellani** [comment]
@filipefurtad0 

I guess the problem is that I referred to a constant, declared on the ActiveRecord Model, from the migration.
If someone edits the constant later, that migration will have a different behavior.
I'll replace that constant with its value. This should fix the problem.

**Comment by filipefurtad0** [comment]
I've tried staging (on a different server too) this new version @abdellani , but still get the [same error](https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/servers/fr-staging/deploys/973).

**Comment by dacook** [comment]
@abdellani, in the deployment I see the message below.
I guess we never run migrations in CI (the test environment loads directly from the latest db/schema.rb version).
But I would have expected this to occur when running the the migration in your development environment, did you execute it there?

```
Rails attempted to auto-load:

/home/openfoodnetwork/apps/openfoodnetwork/releases-old/2023-03-22-114538/app/models/enterprise_fee.rb

Which is in your project's `app/` directory. The good_migrations
gem was designed to prevent this, because migrations are intended
to be immutable and safe-to-run for the life of your project, but
code in `app/` is liable to change at any time.

The most common reason for this error is that you may be referencing an
ActiveRecord model inside the migration in order to use the ActiveRecord API
to implement a data migration by querying and updating objects.

For instance, if you want to access a model \"User\" in your migration, it's safer
to redefine the class inside the migration instead, like this:

class MakeUsersOlder < ActiveRecord::Migration
  class User < ActiveRecord::Base
    # Define whatever you need on the User beyond what AR adds automatically
  end

  def up
    User.find_each do |user|
      user.update!(:age => user.age + 1)
    end
  end

  def down
    #...
  end
end

For more information, visit:

https://github.com/testdouble/good-migrations
```

**Comment by abdellani** [comment]
Sorry @filipefurtad0 , @dacook 

I just tested the queries on `rails console`.
Now, I fixed the migration and tried `rails db:migrate`.

**Comment by filipefurtad0** [comment]
Ok @abdellani ! Just as an early feedback: The PR stages now :tada: 

It migrates the selected option in tax category: We go from this scenario (per order calculators with the `Inherit from product` option selected):

image

To this scenario:

No tax category selected:

image

So the migration works correctly :raised_hands: 

The selection is not mandatory in this screen (this is the current behavior) so I'd say we're good here :ok_hand: 

Also, I've tested creating a valid, additional fee - this is now possible, no error is triggered:

image

So, this all looks good. I'd still wait for code review before any additional tests or merging.

File: db/schema.rb [hunk 3]
```diff
@@ -291,6 +291,17 @@
...
+    t.bigint "order_id"
+    t.string "status"
+    t.integer "number"
+    t.jsonb "data"
+    t.date "date", default: -> { "CURRENT_TIMESTAMP" }
+    t.datetime "created_at", precision: 6, null: false
+    t.datetime "updated_at", precision: 6, null: false
+    t.index ["order_id"], name: "index_invoices_on_order_id"
+  end
+
```
Comment (dacook) [inline db/schema.rb:304]: `±` Oops!
This happened because rails migrate always regenerates the schema.db file from your dev database.

File: spec/models/enterprise_fee_spec.rb (hunk 1 above)
Comment (dacook) [reply spec/models/enterprise_fee_spec.rb:24]: `±` Good suggestion 👍

File: db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+  end
+
+  def enterpise_fee_ids
+    Spree::Calculator.where(
+      calculable_type: 'EnterpriseFee',
+      type: per_order_calculators
+    ).pluck(:calculable_id)
+  end
```
Comment (dacook) [inline db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb:21]: Not that efficiency matters here, I thought it worth pointing out that we could probably use a `join` to avoid the extra query.

**Review by dacook — CHANGES_REQUESTED** [review]
Almost ready, just a couple of updates to make.

File: db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb (hunk 4 above)
Comment (mkllnk) [reply db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb:21]: Yes, or at least a `select` to have a subquery.

**Review by mkllnk — COMMENTED** [review]
There's a conflict on the db/schema.rb but it needs to be rewritten anyway. I agree with David's comments but otherwise all good.

File: db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb (hunk 4 above)
Comment (abdellani) [reply db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb]: I replaced the old code with a join

File: spec/models/enterprise_fee_spec.rb (hunk 1 above)
Comment (dacook) [reply spec/models/enterprise_fee_spec.rb:24]: I think we should still add a test for the successful cases. I think the most important one is:

* Per-item calculator, with inheritance ticked

**Review by dacook — CHANGES_REQUESTED** [review]

File: spec/models/enterprise_fee_spec.rb (hunk 1 above)
Comment (abdellani) [reply spec/models/enterprise_fee_spec.rb:53]: I updated the tests to check the per-order and per-item calculators.
Now, I'm thinking we only discussed the two types of calculators, how about the others?
image

Comment (dacook) [reply spec/models/enterprise_fee_spec.rb:53]: I can see in one of @filipefurtad0's [comments](https://github.com/openfoodfoundation/openfoodnetwork/issues/10348#issuecomment-1410664238) that these three can inherit tax category:

> Flat percent (per item), Flat rate (per item), Weight

So I assume all others cannot. Is that right Filipe?

Comment (abdellani) [reply spec/models/enterprise_fee_spec.rb:53]: if that's true, maybe we can extends the original issue to include all the categories (except per-item) ?

Comment (filipefurtad0) [reply spec/models/enterprise_fee_spec.rb:53]: We've clarified it over a huddle with @abdellani - I think we're good: weight is indeed applied over a line item, but should be included in the PR already :+1

Comment (dacook) [reply spec/models/enterprise_fee_spec.rb:53]: Ok, sounds like we're all good!

**Review by dacook — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
@filipefurtad0 Are you willing to continue/finish testing this one? I think it would take me quite some time to dive into this and get a test setup ready.

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

I've deleted the previously ran migration from the migrations table, on the server - so I could re-run it:

```
openfoodnetwork@staging:~/apps/openfoodnetwork/current$ bundle exec rails db:migrate:status | grep 'inherit'
   up     20230316034707  Disable inherits tax category from per order enterprise fees
openfoodnetwork@staging:~/apps/openfoodnetwork/current$ psql -h localhost openfoodnetwork ofn_user
psql (10.17 (Ubuntu 10.17-1.pgdg16.04+1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

openfoodnetwork=> delete from schema_migrations where version = '20230316034707';
DELETE 1
openfoodnetwork=> \q
openfoodnetwork@staging:~/apps/openfoodnetwork/current$ bundle exec rails db:migrate:status | grep 'inherit'
  down    20230316034707  Disable inherits tax category from per order enterprise fees

```

Then staged the PR, and got:
```

openfoodnetwork@staging:~/apps/openfoodnetwork/current$ bundle exec rails db:migrate:status | grep 'inherit'
   up     20230316034707  Disable inherits tax category from per order enterprise fees

```

But somehow, I did not observe any changes, as previously reported:

I still see the `inherit from product` option selected, on enterprise fees:

image

Any idea why?

**Comment by abdellani** [comment]
@filipefurtad0 

I found the issue.

In the migration, we have two class declarations: `EnterpriseFee` and  `Spree::Calculator`.

As the association is polymorphic, we use `calculable_id` and `calculable_type` on the calculator to find the associated EnterpriseFee.

When I tried  `EnterpriseFee.joins(:calculator)`, the SQL query ran with `calculable_type= DisableInheritsTaxCategoryFromPerOrderEnterpriseFees::EnterpriseFee ` instead of `EnterpriseFee`.

I solved the issues by adding a new condition on the `Spree::Calculator` query and avoiding declaring the relationship as if it's not polymorphic.

**Comment by sigmundpetersen** [comment]
Pushing this one through a short re-review

File: db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb [hunk 5]
```diff
@@ -0,0 +1,29 @@
+# frozen_string_literal: true
+
+class DisableInheritsTaxCategoryFromPerOrderEnterpriseFees < ActiveRecord::Migration[6.1]
+  class EnterpriseFee < ApplicationRecord
+    has_many :calculator, class_name: "Spree::Calculator", foreign_key: :calculable_id
```
Comment (dacook) [inline db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb:5]: From what I can understand in the last comment, you've updated this line. 
I think that using `as: :calculable` as [in the model](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/concerns/calculated_adjustments.rb#L9) would have achieved the same result (rails would guess "calculable_id" from "calculable").
But it sounds like this works too 👍 .

I think sometimes it's actually simpler and safer to just build the SQL directly for a migration, rather than try to re-create the model.

File: db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+  end
+
+  module Spree
+    class Calculator < ApplicationRecord
+      self.table_name = 'spree_calculators'
+    end
+  end
+
+  def change
```
Comment (dacook) [inline db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb:14]: Migrations have two actions: `rake db:migrate` (perform the migration) and `rake db:rollback (undo the migration if possible). 

This method migrates the data to the new state, so it should only run on `migrate`. 
In this case we're not losing any information, so we don't need a rollback (I think the `inherits_tax_category` did nothing before).

The `change` method runs for both `migrate` and `rollback`. To only run on `migrate`, we can just define `up`:

```diff
-  def change
+  def up
```

This is only for future reference. It doesn't really matter in this case if it runs on rollbacks so I don't suggest we bother updating the code.

**Review by dacook — APPROVED** [review]
The update looks ok to me.
I noticed another issue with the migration code, but I believe it's not essential and we should just move forward.

Let's re-test.

In order to re-try the migration, we'll need to rollback or delete the migrations log like Filipe did earlier.

File: db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb (hunk 5 above)
Comment (abdellani) [reply db/migrate/20230316034707_disable_inherits_tax_category_from_per_order_enterprise_fees.rb:5]: >I think that using as: :calculable as [in the model](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/concerns/calculated_adjustments.rb#L9) would have achieved the same result (rails would guess "calculable_id" from "calculable").

@dacook that's correct, but the problem is with calculable_type. The SQL query will have the two following parameters 
1. calculable_id: will have the correct id of the enterprise fee
2. calculable_type: will be set to `DisableInheritsTaxCategoryFromPerOrderEnterpriseFees::EnterpriseFee`, which is wrong ( it must be `EnterpriseFee`)

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

This looks good now. Setting up fees with per-order calculators, with the `Inherit from product` tax category, **before this PR**:

image

**After this PR**:
image

1) We can see that these have been successfully migrated, to have no selected tax category  :heavy_check_mark: 

2) Creating a new fee or editing existing ones is possible  :heavy_check_mark: 

3) Creating a new fee with per-order calculator and the `Inherit from product` tax category, triggers the error:
image

The fee is not created :heavy_check_mark: 

4) By editing a fee, it is still possible to save the undesired combination into the DB: the error is triggered, but the DB is updated. 

For example, by changing:
image
to
image

@abdellani , I did not think of this scenario before... the bug report only mentions fee creation. It would be great to merge this, to prevent further iterations. So in this case, I'd open an issue after merging.
On the other hand, I think that undesired combinations are possible, so we don't need to re-run a migration in production again, in this regard.

What do you think it is best?

**Comment by abdellani** [comment]
@filipefurtad0 

I tried to reproduce the issue but I failed.
Can you please check the screencast? did I miss something?
https://user-images.githubusercontent.com/16113997/235596633-733c3e83-0e19-44f4-8c61-fc61bea099a6.mp4

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

The steps I took to reproduce were:

1) Creating a fee with an allowed combination:
Tax Category: `Alberta GST`
Calculator: `Flat percent (per Item)`

image

2) Refresh the page to verify it is saved into the DB

3) Change the Tax category to be inherited from product - notice this combination is allowed, but the UI displays the warning:
Tax Category: `Inherit from product`
Calculator: `Flat percent (per Item)`

image

4) Change the calculator to an order based calculator - notice the warning here as well -> this is correct
Tax Category: `Inherit from product`
Calculator: `Flat percent (per Order)`

image

5) Refresh the page or check the DB to verify the not allowed combination was stored


I see two issues here:
- on point 3) ideally, we would not display the warning
- on point 4) the not allowed combination is stored on the DB, despite the warning

There is a lot going on on this PR. Do you think we should split this in two? For example:
- PR 1 -> addressing all UI issues
- PR 2 -> after merging PR 1, perform the DB migration

What do you think?

**Comment by abdellani** [comment]
Hi @filipefurtad0 

The order of the steps on my test is different that's why I didn't detect the problem.

Suppose we start from any valid state, for example:
1. inheritance from product: disabled
2. calculator: flat percent per order


On my test:
1. I changed enabled the inheritance and changed the calculator at the same time.

Results:
1. the calculator will be replaced
2. the inheritance flag will not change because the combination is invalid


On your test:
1. you enabled the inheritance first
2. you changed the calculator

results:
1. the calculator will be replaced
2. the inheritance flag will be set


The reason behind this behavior:

After the update button is clicked, the backend:
1. replace the calculator (remove the old calculator and create the selected one) 
2. update the enterprise fee
3. run the validations ( which's too late because the calculator is already replaced)

I'm not against splitting the PR, but I think that the problem is with the validations.

Now, I'm not sure about the best way to solve the issue.

I tried to prevent the creation of the selected calculator under invalid conditions but didn't solve the problem because the original calculator will be removed first.

The bulk update is done through `ModelSet`, I don't think that it supports adding validations before updating the enterprise fees collection.


I'm thinking about introducing parameter validation on `enterprise_fee_controller`, but is there a better solution?

**Comment by dacook** [comment]
It sounds like the problem is that the association is updated regardless of the validation. I think this is because associations in Rails are saved immediately. 
Hm...

It would be nice to solve it in the model, but the only way I can think to do that is move the validation to the "per order" calculator models, relying on the assoicated fee 'inherits' value. 

So perhaps we need to pre-validate in the controller or ModelSet. I'm not familiar with  ModelSet and I'm guessing it's not flexible enough to do that. Perhaps you could add a hook for that, otherwise go ahead and validate in the controller.

**Comment by abdellani** [comment]
> I agree. For example, on point 3. https://github.com/openfoodfoundation/openfoodnetwork/pull/10512#issuecomment-1531161376 the banner is displayed, although the combination is legitimate.

@filipefurtad0  I'm not able to reproduce it.
Can you please check the screenshot?

https://user-images.githubusercontent.com/16113997/237044125-a1329a3b-339d-4a88-9729-f71ba611a252.mp4


> So perhaps we need to pre-validate in the controller or ModelSet. I'm not familiar with ModelSet and I'm guessing it's not flexible enough to do that. Perhaps you could add a hook for that, otherwise go ahead and validate in the controller.

@dacook Ok,  I'll go with the second option.

**Comment by abdellani** [comment]
@dacook 

We already have a validation on the controller, it was introduced a few months ago https://github.com/abdellani/openfoodnetwork/commit/755107ec9f60034119cbabdf8c2b077aedd92fee

**Comment by abdellani** [comment]
@filipefurtad0 
I run the test again.
I think it's good now.

File: app/controllers/admin/enterprise_fees_controller.rb [hunk 7]
```diff
@@ -2,11 +2,13 @@
 
 require 'open_food_network/order_cycle_permissions'
 
+# rubocop:disable Metrics/ClassLength
```
Comment (mkllnk) [inline app/controllers/admin/enterprise_fees_controller.rb:5]: We should add the filename to the rubocop todo file instead of disabling the cop here.

**Review by mkllnk — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]

**Review by dacook — APPROVED** [review]
Good one!👍

**Comment by filipefurtad0** [comment]
Hey @abdellani ,

I think we're good now!! :tada: 

Before this PR:

image

After this PR:

image

We can see, that for the order level calculators, the Inherit from product option was removed :heavy_check_mark: 

Also, I was unable to create new fees with invalid combinations, either by creating or editing existing fees (the test cases previously mentioned).

This is ready to go!

Congratulations for the work and resilience :clap: :clap: :clap: 

PS: I'll update the tests on #10539.
