### PR TITLE
Setting payment state for subscription order

### LINKED ISSUE #8232: Payment State of Subscription Order canceled Before Stripe payment taken
## Description

System automatically generates a subscription order for a customer who will pay by Stripe.  Hub settings allow orders to be cancelled or changed while an order cycle is open.  Payment for subscription order is thus not taken from customer account straight away.
Order is cancelled by either customer or hub before order cycle closes.
Payment state of order remains as 'amber= balance due'.
No payment is required as no goods purchased.

## Expected Behavior

Customer or hub cancels a subscription order (paid for by Stripe) while an order cycle is open and before payment has been automatically taken from customer's account.
No payment is due for the order.
Payment state of order should read 'void' rather than balance due.

## Actual Behaviour

System automatically generates a subscription order for a customer who will pay by Stripe.  Hub settings allow orders to be cancelled or changed while an order cycle is open.  Payment for subscription order is thus not taken from customer account straight away.
Order is cancelled by either customer or hub before order cycle closes.
Payment state of order remains as 'amber= balance due'.

Similar to issue #8229 but in this case the capture payment icon is not visible.

## Steps to Reproduce

1.
2.
3.
4.

## Animated Gif/Screenshot

cancelled_suborder

## Severity

S5
Potential paper cut

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by georgethoppil**
#### What? Why?

Closes #8232 

For a subscription order that is cancelled before a payment is collected should result in a void payment state. Current work around is after cancelling the order, the admin has to click the 'Update and Recalculate Fees' to reflect the change. We want this action to take place right after the cancel is initiated. [Thread](https://openfoodnetwork.slack.com/archives/C022DJZJ1J9/p1644418446848719) on the discussion 

#### What should we test?
1) Create a subscription order
2) Ensure there is no payment that is completed for said order 
3) Cancel order
4) See that the payment state is now void
5) Resume order 
6) See that the payment state is now back to balance due

### CODE REVIEW

File: app/models/spree/order.rb [hunk 1]
```diff
@@ -661,11 +661,12 @@ def after_cancel
       shipments.each(&:cancel!)
 
       OrderMailer.cancel_email(id).deliver_later
-      self.payment_state = 'credit_owed' unless shipped?
```
Comment (georgethoppil) [inline app/models/spree/order.rb:664]: I was a bit confused as to why this was added in the first place. Seems like in order to reflect the payment_state on the order, we would need to update the order via 'Update and Recalculate Fees' which in turn calls `update_payment_state`

File: spec/models/spree/order/state_machine_spec.rb [hunk 2]
```diff
@@ -136,21 +136,16 @@
       end
 
       context "without shipped items" do
-        it "should set payment state to 'credit owed'" do
+        it "should set payment state to 'void'" do
           order.cancel!
-          expect(order.payment_state).to eq 'credit_owed'
+          expect(order.payment_state).to eq 'void'
```
Comment (mkllnk) [inline spec/models/spree/order/state_machine_spec.rb:141]: This spec doesn't actually test if the change is persisted. That's something you fixed with update_column. I think that we should write this spec to cover that:
```suggestion
          expect {
            order.cancel!
            order.reload
          }.to change { order.payment_state }.to("void")
```

File: spec/models/spree/order/state_machine_spec.rb [hunk 3]
```diff
@@ -136,21 +136,16 @@
...
         end
       end
 
       context "with shipped items" do
         before do
           allow(order).to receive_messages shipment_state: 'partial'
         end
```
Comment (mkllnk) [inline spec/models/spree/order/state_machine_spec.rb:148]: This context is not needed any more.

File: spec/models/spree/order/state_machine_spec.rb [hunk 4]
```diff
@@ -136,21 +136,16 @@
...
-
-        it "should not alter the payment state" do
```
[the remark this answers is not in the document]
Comment (mkllnk) [reply spec/models/spree/order/state_machine_spec.rb:150]: I'm not completely sure but you are probably right. This spec was copied from spree and I'm happy for you to remove it. If we notice a bug related to this one day, we probably want to write a better spec anyway.

File: app/models/spree/order.rb [hunk 5]
```diff
@@ -661,11 +661,12 @@ def after_cancel
...
+      update_column(:payment_state, updater.update_payment_state)
```
[the remark this answers is not in the document]
Comment (georgethoppil) [reply app/models/spree/order.rb]: Good catch, using `update` is a better approach. lets not skip the validations and callbacks

File: spec/models/spree/order/state_machine_spec.rb (hunk 2 above)
Comment (georgethoppil) [reply spec/models/spree/order/state_machine_spec.rb]: Nice! good idea

File: spec/models/spree/order/state_machine_spec.rb [hunk 6]
```diff
@@ -162,5 +153,12 @@
       allow(order).to receive_messages state: "canceled"
       allow(order).to receive_messages allow_resume?: true
     end
+
+    it "should set payment state to 'balance due'" do
+      expect {
+        order.resume!
```
Comment (georgethoppil) [inline spec/models/spree/order/state_machine_spec.rb:159]: @mkllnk been fighting with this spec tonight and I am not sure what I am doing wrong. I expect when I `order.resume!`, the checkout state should run the after_transition block [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/spree/order/checkout.rb#L45) and change the state to `resumed` and then calling order.after_resume. For some reason on the test, it only sets the state to `canceled` which causes the test to fail. Any ideas that I may have overlooked?

Comment (mkllnk) [reply spec/models/spree/order/state_machine_spec.rb:159]: You can go in with a debug statement like `binding.pry` to find out if the `save` is success in that method. And if not, you can call `errors` to find out why not. The test data may be incomplete.

Comment (georgethoppil) [reply spec/models/spree/order/state_machine_spec.rb]: After some digging, it seems like when you set the state in the `before do` column via
`allow(order).to receive_messages state: "canceled"`, this unfortunately is being set again in the after_transaction block. So the transition to "resume" is successful and in the after_transaction block, order.state is referenced as "canceled" and setting order.state = order.state, sets it back to canceled. 

Not sure why we introduced the after_transaction block here tho. The state is already set but looks like we are re-setting it again. Loved this bug hunt, got a good understanding about rails state machines 😄

**Review by mkllnk — APPROVED** [review]
Nice specs! Thank you.

I'm not sure about that after_transition hook either. It's most likely something we copied from Spree and maybe we won't need it any more. It's risky to remove though because some other code may rely on this weird behaviour. We would need to test it very carefully but I would love to see that removed.

**Comment by jibees** [comment]
Hi @georgethoppil !

> This branch has conflicts that must be resolved
`app/models/spree/order.rb`

Thanks! 🙏

**Review by jibees — APPROVED** [review]
👌

**Comment by filipefurtad0** [comment]
Hey @georgethoppil ,

Thanks for this improvement! This works fine now:

**Cash payment**

image

Cancelling - changes the payment state of the order to void:

image

Resuming - brings the payment state to its previous state: 

image



**Stripe payment**

For an order with a Stripe Payment awaiting authorization:
image

Cancelling - changes the payment state of the order to void:
image

Resuming - brings the payment state to its previous state: 

image


Paypal payments are captured by default as such fall out of scope for this PR.

This looks great!
Merging.
