### PR TITLE
Pi/french issue

### LINKED ISSUE #2951: Product import not working on French instance with simple file
## Description

A new user has some excel files to populate to create their catalog in OFN. I did try to do the first import for them, and it is not working, and no error displays.

## Expected Behavior

I can upload a list of product with product import feature.

## Actual Behavior

I can't.

## Steps to Reproduce

1. On french instance, go to https://www.openfoodfrance.org/admin/product_import
2. Try to import a simple file like https://drive.google.com/open?id=1JKDfEcb-VhSL_wqEhXZl2nFoWkFKhIcF of course make sure the producer already exists
3. See the error, the file can't be uploaded, and no error message is displayed

## Animated Gif/Screenshot

capture du 2018-10-25 22-17-13

## Context

A new promising user on OFFrance want to upload their producer catalog.

## Severity
S3 - S2, you can still create manually products, but for hundreds of products it becomes complicated. Here I put S3 for now, we start with only one list that if it doesn't work we can fill in manually, it's only around 30 products...

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #2951

An instance configuration on French production was causing unexpected product validation messages when creating a new product. This setting was forcing all products to require a tax_category to be set, and added an extra validation error into product objects at an unexpected point in the import process.

#### What should we test?

Importing products from CSV on an instance with this checkbox checked in the config:
screenshot from 2018-11-18 20-31-40
should show an error message if there is no tax_category set in the CSV file.

#### Release notes

Fixed tax category validations in product import for instances that enforce mandatory tax categories.

Changelog Category: Fixed

### CODE REVIEW

File: app/models/product_import/entry_validator.rb [hunk 1]
```diff
@@ -243,7 +243,7 @@ def mark_as_new_product(entry)
       new_product.assign_attributes(entry.attributes.except('id'))
       new_product.supplier_id = entry.producer_id
 
-      if new_product.valid?
+      if new_product.valid? && new_product.errors.empty?
```
Comment (sauloperez) [inline app/models/product_import/entry_validator.rb]: I don't understand this extra check. If the model is valid it won't have errors in the array (unless we add them ourselves outside of validations).

File: app/models/product_import/product_importer.rb [hunk 2]
```diff
@@ -100,7 +100,8 @@ def entries_json
         entries[entry.line_number] = {
           attributes: entry.displayable_attributes,
           validates_as: entry.validates_as,
-          errors: entry.invalid_attributes
+          errors: entry.invalid_attributes,
+          product_validations: entry.product_validations
```
Comment (sauloperez) [inline app/models/product_import/product_importer.rb]: I know it's not strictly related to this PR, but IMO the JSON serialization should rather be extracted into a serializer. We could create an issue for it, if we all agree.

Comment (Matt-Yorkley) [reply app/models/product_import/product_importer.rb]: Issue added: https://github.com/openfoodfoundation/openfoodnetwork/issues/3105

File: app/models/product_import/entry_validator.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply app/models/product_import/entry_validator.rb]: Ah, I think I added these whilst debugging because the outcome wasn't making sense. I've removed them now. :+1:

**Comment by luisramos0** [comment]
staged: https://staging.openfoodfrance.org

**Comment by luisramos0** [comment]
@Matt-Yorkley @sauloperez on staging this PR I noticed the commit messages of this PR: they are very specific and with no reference to the context. I wonder if this is ok or if we should always include context in every commit message. I ask this because I am not sure what's the best approach. You opinion?
Maybe an opportunity to improve this guide:
https://github.com/openfoodfoundation/openfoodnetwork/wiki/Making-a-great-commit

**Comment by sauloperez** [comment]
I think they are fine and they stick to the those guidelines, which I think are quite good.

In my experience a great way to see this is from the perspective of someone new to the app. Is it easy to trace back to the decisions behind the code changes? Aka. Our experience with the Spree upgrade investigations.

**Comment by luisramos0** [comment]
ok, thanks. I am glad I asked. Maybe I need to adapt some of my commit messages.

**Comment by RachL** [comment]
@Matt-Yorkley @luisramos0 PR is working fine but the error message was not translated:
image

Is it linked to the PR or to staging?
Thx :)
Testing notes:
https://docs.google.com/document/d/1yu4UVizLSR6TcPkDD_Jyp28km1GGuJ3ktoog9ucNDqA/edit#

**Comment by luisramos0** [comment]
@RachL it's how it works, first we get this tested and then merged and then validation_msg_tax will get to transifex from master, and after translated, back to master on a transifex merge.

**Comment by RachL** [comment]
@luisramos0 yup
