### PR TITLE
Verify line item when placing sub order (Fix #6680)

### LINKED ISSUE #6680: Order with wrong total amount
## Description

Hub ID in FR prod: 173 (one of FR oldest user 🧙 )

Ok so here is the full story of bread in this order. For non French people `Pain de méteil - c-Pain de méteil moulé 800 g (1 pain 800 g)` is the bread product in this order. Buckle up:

- This is a hub where bread bakers were supposed to be on holiday this week. So when preparing their OC, they removed all bread products from the OC.

- The hub manager is also a shopper at the hub and has 3 subscriptions for it (bread, cheese, veggies)

- On January the 10th, at the opening of the cycle, the hub manager receives an email telling them that the order has been placed but that "unfortunately some products requested were not available" (so far so good: the bread was not in the cycle products and they have bread as a subscription in addition to vegetables and cheese)

- On January the 12th, they learn that the bakers have come back earlier from their holidays and that they will have plenty of bread, So they add the bread in the shop. 

- Now, for some reason that I haven't been able to reproduce yet they are telling me that the subscription never was updated (If I find out why, I will open another issue). So they manually created orders with bread inside.

- they have managed to end up with an order (# R110771347 ) that does not count bread and therefor has a wrong total. updating and re-calculating does not change anything. Why?

I'm searching if there are other orders in that state.

## Steps to Reproduce
 No idea.

## Animated Gif/Screenshot
see above

## Workaround
they can re-do everything manually

## Severity
bug-s2: a non-critical feature is broken, no workaround

I'm putting s2 for quick investigation to understand if we have more logs to help me debug.

## Your Environment

* Version used: v3.5
* Browser name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Both

## Possible Fix
 -

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #6680 

It looks like when we place a subscription order and there isn't sufficient stock for one of the items, we leave the line item on the order with quantity 0, so that we can show the customer and shop owner what changed in their subscription order because of insufficient stock. 

However, since the `Shipment#manifest` method does not take the quantity of a line item into account, it determines (incorrectly) that there is still quantity 1 of those line items on the order. 

This removes the inventory unit from the shipment manifest, so that the item no longer appears on the order view in the admin view.

#### What should we test?

Placing a subscription order with unavailable stock. Previously the item remained on the order with quantity 0

#### Release notes

Fixed a bug where subscription items that were out of stock would show up on the back office view of the order.

Changelog Category: User facing changes

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Looking good :+1:

Do we need some more test coverage here?

**Comment by Matt-Yorkley** [comment]
I'm wondering if this bug could also be the cause of other weird subs issues, like #7063...

File: app/jobs/subscription_placement_job.rb [hunk 1]
```diff
@@ -62,6 +62,10 @@ def cap_quantity_and_store_changes(order)
     unavailable_stock_lines_for(order).each do |line_item|
       changes[line_item.id] = changes[line_item.id] || line_item.quantity
       line_item.update(quantity: 0)
+
+      Spree::OrderInventory.new(order).verify(line_item, order.shipment)
+      order.line_items.reload
+      order.recreate_all_fees!
```
Comment (Matt-Yorkley) [inline app/jobs/subscription_placement_job.rb:68]: This might be a bit expensive, especially if there are multiple out of stock items. I think we can get the same outcome with this (but with a lot less transactions):
```ruby
    unavailable_stock_lines_for(order).each do |line_item|
      changes[line_item.id] = changes[line_item.id] || line_item.quantity
      line_item.update(quantity: 0)

      Spree::OrderInventory.new(order).verify(line_item, order.shipment)
    end
    if changes.present?
      order.line_items.reload
      order.update_order_fees!
    end
```

Comment (andrewpbrett) [reply app/jobs/subscription_placement_job.rb]: 👍 done. Good catch.

**Review by mkllnk — COMMENTED** [review]
Looks reasonable but it needs tests.

**Comment by andrewpbrett** [comment]
@mkllnk 👍. That explains the feeling I had earlier today... it was either that I'd left the house and forgotten to turn the stove off, or left my desk and forgotten to write a test before moving something to code review 😁

File: app/jobs/subscription_placement_job.rb [hunk 2]
```diff
@@ -62,6 +62,12 @@ def cap_quantity_and_store_changes(order)
     unavailable_stock_lines_for(order).each do |line_item|
       changes[line_item.id] = changes[line_item.id] || line_item.quantity
       line_item.update(quantity: 0)
+
+      Spree::OrderInventory.new(order).verify(line_item, order.shipment)
+    end
+    if changes.present?
+      order.line_items.reload
+      order.update_order_fees!
```
Comment (sauloperez) [inline app/jobs/subscription_placement_job.rb:70]: My concern around this job class is growing every time we touch it. Just look at this method's complexity. It's a lot for my little brain to process :see_no_evil:

File: app/models/spree/order_inventory.rb [hunk 3]
```diff
@@ -98,8 +98,7 @@ def remove_from_shipment(shipment, variant, quantity)
         inventory_unit.destroy
         removed_quantity += 1
       end
-
-      shipment.destroy if shipment.inventory_units.count == 0
+      shipment.destroy if shipment.inventory_units.reload.count == 0
```
Comment (sauloperez) [inline app/models/spree/order_inventory.rb:101]: I know it's not related to this PR at all but... this method has nothing to do with the class it's in (no state or associations used; all method local vars) and it fits perfectly as a `RemoveFromShipment` service

**Review by sauloperez — CHANGES_REQUESTED** [review]
Agree with the others about adding a regression test to ensure we fixed the issue.

File: app/models/spree/order_inventory.rb (hunk 3 above)
Comment (andrewpbrett) [reply app/models/spree/order_inventory.rb:101]: Agree on both counts. I'd like to ship the S2 fix asap though... yet another tech debt issue?

File: spec/jobs/subscription_placement_job_spec.rb [hunk 4]
```diff
@@ -115,6 +115,18 @@
...
+
+        context "and the order has been placed" do
+          before do
+            allow(order).to receive(:ensure_available_shipping_rates) { true }
+            allow(order).to receive(:process_each_payment) { true }
+            job.send(:place_order, order.reload)
+          end
+
+          it "removes the unavailable items from the shipment" do
+            expect(order.shipment.manifest.size).to eq 1
```
Comment (mkllnk) [inline spec/jobs/subscription_placement_job_spec.rb:127]: A little pro-tip to spec this more precisely:

```suggestion
            expect {
              job.send(:place_order, order.reload)
            }.to change {
              order.shipment.manifest.size
            }.from(2).to(1)
```

But I don't want to delay this PR further.

**Review by mkllnk — APPROVED** [review]

File: spec/jobs/subscription_placement_job_spec.rb (hunk 4 above)
Comment (andrewpbrett) [reply spec/jobs/subscription_placement_job_spec.rb:127]: Oh nice, thanks for the tip @mkllnk! That's really nice and expressive. I tried it out and in this specific case the shipment doesn't actually exist before calling `place_order`, so I think it's best to leave it as is.

File: app/models/spree/order_inventory.rb (hunk 3 above)
Comment (sauloperez) [reply app/models/spree/order_inventory.rb:101]: Not sure it's worth it. I bet it'll stay there forever.

**Review by sauloperez — APPROVED** [review]

File: app/models/spree/order_inventory.rb (hunk 3 above)
Comment (sauloperez) [reply app/models/spree/order_inventory.rb:101]: Rubocop agrees and it's flagging the complexity. I'd just move on.

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

Thanks for this fix! And thank you @RachL for the steps to reproduce this one :muscle: 
Indeed, this is reproducible by:

- Creating the subscription with some variants
- Removing one of the variants from the OC
- Running the subscription

Before this PR, it leads to this scenario (below, admin view - left; customer view - right). In this example, we remove Peppermint from the OC:

image

We can see, that 1x peppermint still appears on the admin view, while on the customer's side it correctly shows 0 x peppermint. The order total matches :+1: so this is bug #6680. After staging, the same steps, lead to:

image

**£25.50** is the correct order total. In the first case, the £26.50 value comes from an enterprise fee (below) which considered the line item, despite stock zero.

image


This PR fixes this :+1: 

Awesome, ready to go.

**Comment by filipefurtad0** [comment]
Related to fees (and out of scope of this PR):

If we consider the case, in which an a variant remains in the OC, but becomes unavailable due to stock restrictions, when a subscription is placed:

- before this PR

image

- after this PR

image

So, the line item fee is removed, but this fee:

image

Is still appearing. After clicking "Update" the fee is removed, and order total decreases, which turns into "Credit Owed". This needs an issue as these orders are being overcharged (unless the admin manually clicks Update and issues refunds)...

**Comment by filipefurtad0** [comment]
Ouch! This one goes waaay back #1629

**Comment by andrewpbrett** [comment]
@filipefurtad0 thanks for the thorough testing (and encyclopedic knowledge of old bugs!) 

I actually noticed a version of this when I was testing this myself, that fees stuck around when they shouldn't have. I added [this line](https://github.com/andrewpbrett/openfoodnetwork/blob/577401fca030af161ad449d5ee292265cadba1f2/app/jobs/subscription_placement_job.rb#L70) to get rid of it, but I'm guessing that it only worked for a transaction fee. 

It actually [came up in code review](https://github.com/openfoodfoundation/openfoodnetwork/pull/7048#discussion_r596299876) that doing a `recreate_all_fees` (which was what I did at first) would be expensive, but I'm wondering if that might resolve #1629 for subs at least. @Matt-Yorkley what do you think?

**Comment by Matt-Yorkley** [comment]
> doing a `recreate_all_fees`

Yeah, we can give that a try :+1:

**Comment by Matt-Yorkley** [comment]
Actually @andrewpbrett I think that will be fixed when #6974 is merged.

**Comment by andrewpbrett** [comment]
@Matt-Yorkley ah excellent I'll stop trying to write this test for the already complicated method in the placement job 😁
