### PR TITLE
Remove direct dependency on MiniMagick

### LINKED ISSUE #12769: Products not loading on shopfront: S3 exception
## Description
On shopfront the loading of products freezes.
Example: https://openfood.hu/anyahajoegyesulet/shop#/shop_panel

## Expected Behavior
Load all products.

## Actual Behaviour
The first few chunk of product list loads, then the loader stays.

## Steps to Reproduce
Go to https://openfood.hu/anyahajoegyesulet/shop#/shop_panel
Scroll down a few times.
See loader do not disappear.

Error in dev toolbar, network response: 
https://openfood.hu/anyahajoegyesulet/shop#/shop_panel

## Animated Gif/Screenshot
Screenshot from 2024-08-14 09-02-52

## Workaround
None.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login

## Your Environment
Environment independent.

## Possible Fix
Catch and log S3 exception.

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #12769 
- Alternative fix for https://github.com/openfoodfoundation/openfoodnetwork/issues/12751
- Follow up from #12754

We still depend on it as long as we set it as image processor but now we can switch to another image processor without changing the code around error handling.

We now rescue from unknown errors during image processing which should make the app more robust.

#### What should we test?

- Visit a shopfront with images.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/models/enterprise.rb [hunk 1]
```diff
@@ -1,7 +1,5 @@
 # frozen_string_literal: false
 
-require "mini_magick"
-
```
Comment (dacook) [inline app/models/enterprise.rb:4]: Sorry I feel like I'm missing something. If the image has not yet been processed, would MiniMagic automatically process it? So why not keep this `require` and ensure the image processes successfully, instead of skipping over it?

Or is MiniMagick not providing any benefit here?

File: app/models/enterprise.rb [hunk 2]
```diff
@@ -479,7 +477,7 @@ def image_url_for(image, name)
     return unless image.variable?
 
     image_variant_url_for(image.variant(name))
-  rescue ActiveStorage::Error, MiniMagick::Error, ActionView::Template::Error => e
+  rescue StandardError => e
```
Comment (dacook) [inline app/models/enterprise.rb:480]: I think it's worth a comment explaining why, eg that it gracefully catches MiniMagic errors without the gem being loaded.

File: app/models/enterprise.rb (hunk 1 above)
Comment (mkllnk) [reply app/models/enterprise.rb:4]: We need the require statement if we reference MiniMagick in the code. But when we only reference StandardError then we don't need to know about MiniMagick. If the image needs processing then Minimagick gets loaded and if that fails we get an error and catch it correctly. That's the happy path. But if something else fails, for example AWS raises an error then the rescue statement goes through the different error classes and doesn't know what a MiniMagick error is unless we load that code first.

So the bad path is not loading Minimagick and some other error being raised.

File: app/models/enterprise.rb (hunk 2 above)
Comment (mkllnk) [reply app/models/enterprise.rb:480]: I don't think that we need to mention Minimagick here because it doesn't matter anymore. We don't care what error is raised. Maybe the commit message should have explained that better...

File: app/models/enterprise.rb (hunk 1 above)
Comment (dacook) [reply app/models/enterprise.rb:4]: Ah, thank you I see now 👍 
We only needed to `require` MiniMagic so that we could make reference to a `MiniMagic` error. 

If a `MiniMagic` error does get raised, then obviously MiniMagic has been loaded because the code raised the error.

**Review by dacook — APPROVED** [review]
All good!

**Comment by drummer83** [comment]
Hi @mkllnk,
Thanks for this fix. I have tested on staging AU and tried the following:
- Display shopfront with images. :heavy_check_mark: 
- Update product images in admin area. :heavy_check_mark: 
- Update enterprise logo and banner. :heavy_check_mark: 
- Display enterprise logo and banner in shopfront. :heavy_check_mark: 

I couldn't find any problems with this PR - merging! :tada: 
Thanks again! :muscle:
