### PR TITLE
SplitCheckout: add already opened cart message on summary step when distributor allow order changes

### LINKED ISSUE #9007: [Split Checkout] Previous order information missing for split checkout
## Description

The legacy checkout displays open orders on the /checkout page. This is missing from the split-checkout; I think the closest would be the `/summary` step, before order confirmation.

See also [this thread](https://openfoodnetwork.slack.com/archives/C01V3KW8RSM/p1647267494221469) for reference.

## Expected Behavior

Previous order information should appear for split checkout, on `/summary` step?

## Actual Behaviour

Previous order information is missing for split checkout (summary step?).

## Steps to Reproduce

1. As an enterprise, under `Shop preferences` toggle the option `Customers can change / cancel orders while order cycle is open`
2. As a customer: Place an order.
3. As a customer: Place another order.
4. Notice the missing info (see pic for reference)

See also PR #9007.

## Animated Gif/Screenshot

As an example, this is how it currently looks like on legacy checkout:
image

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9007
The title says it all ;)
Capture d’écran 2022-03-17 à 10 26 36
Capture d’écran 2022-03-17 à 10 26 48

#### What should we test?
Pretty well described in the linked issue:

1. As an enterprise, under `Shop preferences` toggle the option `Customers can change / cancel orders while order cycle is open`
2. As a customer: Place an order.
3. As a customer: Place another order.
4. Notice the missing info (see pic for reference)

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

File: app/controllers/concerns/checkout_callbacks.rb [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 module CheckoutCallbacks
   extend ActiveSupport::Concern
+  include EnterprisesHelper
```
Comment (mkllnk) [inline app/controllers/concerns/checkout_callbacks.rb:5]: You could just use this as a helper and then you don't need additional action and variable.
```suggestion
  helper EnterprisesHelper
```

File: app/views/split_checkout/_checkout.html.haml [hunk 2]
```diff
@@ -1,4 +1,5 @@
 %checkout.row#checkout
   .small-12.medium-12.columns
     = render partial: "split_checkout/tabs"
+    = render partial: "split_checkout/already_ordered" if @already_ordered && checkout_step?(:summary)
```
Comment (mkllnk) [inline app/views/split_checkout/_checkout.html.haml:4]: If you have the helper, you can simply write this:
```suggestion
    = render partial: "split_checkout/already_ordered" if show_bought_items? && checkout_step?(:summary)
```

**Review by mkllnk — COMMENTED** [review]
Nice solution!

I have one suggestion below. What do you think?

File: app/controllers/concerns/checkout_callbacks.rb (hunk 1 above)
Comment (jibees) [reply app/controllers/concerns/checkout_callbacks.rb]: It seems impossible to call helper inside this module. 
I then have this error: `undefined method `helper' for CheckoutCallbacks:Module`

Any thoughts?

Comment (mkllnk) [reply app/controllers/concerns/checkout_callbacks.rb]: Yes, I didn't see that the code was in a concern and not the controller. The `helper` method is only useful in controllers because they are connected to the view where we call the helper.

Comment (jibees) [reply app/controllers/concerns/checkout_callbacks.rb]: Thanks @mkllnk ! 🙏

**Comment by filipefurtad0** [comment]
Hey @jibees ,

After staging and checking out with a customer with previous orders on that OC we can see the info this PR introduces on the summary step:

image

Looks good to me :+1:
