### PR TITLE
[DFC] Add spree_product_uri to SuppliedProduct

### LINKED ISSUE #12253: DFC product import doesn't verify spree_product_id when creating variants
## Description

The DFC API allows to create new products with a variant or new variants for an existing product. To create new variants, you must supply the attribute `ofn:spree_product_id` to reference to existing product. Now this has two problems:

1. It doesn't check for permissions on the product. You can create variants for a product you don't own.
2. It doesn't know if the product id was really referencing the local database or if that field was imported from another OFN instance.

## Expected Behavior

You can only create variants for products you own.
The product id is ignored if it references a product on another platform.

## Actual Behaviour

See above.

## Steps to Reproduce

1.
3.
4.
5.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #12253 

#### What should we test?

- No test.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [x] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: engines/dfc_provider/app/services/supplied_product_builder.rb [hunk 1]
```diff
@@ -36,6 +44,23 @@ def self.import_variant(supplied_product)
...
+    if uri.present?
+      route = Rails.application.routes.recognize_path(uri)
+      params = Rack::Utils.parse_nested_query(URI.parse(uri).query)
+
+      # Check that the given URI points to us:
+      return unless uri == urls.enterprise_url(route.merge(params))
+
+      Spree::Product.find(params["spree_product_id"])
+    elsif id.present?
+      Spree::Product.find(id)
```
Comment (mkllnk) [inline engines/dfc_provider/app/services/supplied_product_builder.rb:60]: I think that the product search should be scoped to `current_enterprise.supplied_products.find_by(id: ...)`. And if we don't find it, we just ignore it. That will check the permission and also allow someone to clone the products of another enterprise when they have only read permissions. 

The controller needs to pass the enterprise for this. We can then also assign the enterprise here instead of in the controller.

File: engines/dfc_provider/spec/services/supplied_product_builder_spec.rb [hunk 2]
```diff
@@ -130,4 +143,179 @@
...
+
+        it "adds a new variant" do
+          expect(imported_variant.id).to be_nil
+          expect(imported_variant.product).to eq(spree_product)
+          expect(imported_variant.display_name).to eq("Tomato")
+          expect(imported_variant.unit_value).to eq(2000)
+        end
+      end
+
+      context "when doesn't spree_product_uri match the server host" do
```
Comment (rioug) [inline engines/dfc_provider/spec/services/supplied_product_builder_spec.rb:258]:
```suggestion
      context "when spree_product_uri doesn't match the server host" do
```

**Review by rioug — APPROVED** [review]
Good one ! I notice a funny named context but otherwise good to go !

**Review by dacook — APPROVED** [review]
Great team work!

**Comment by dacook** [comment]
I've added a "[DFC]" label to the title for easy reference in the release notes (so instance managers can see at a glance which API it relates to). 
As we don't seem to have a standard for that, i propose  this ☝️

File: engines/dfc_provider/spec/services/supplied_product_builder_spec.rb [hunk 3]
```diff
@@ -79,6 +84,14 @@
 
       expect(product.image).to eq variant.product.image.url(:product)
     end
+
+    it "assigns the product uri" do
+      product = builder.supplied_product(variant)
+
+      expect(product.spree_product_uri).to eq(
+        "http://test.host/api/dfc/enterprises/7?spree_product_id=6"
```
[the remark this answers is not in the document]
Comment (mkllnk) [reply engines/dfc_provider/spec/services/supplied_product_builder_spec.rb:92]: It's just the enterprise URL with the spree_product_id as parameter. This can be given as hash to the URL helper:
https://github.com/openfoodfoundation/openfoodnetwork/blob/29dad44f9fd181d4cdd7ff109b40f9c8d0985d77/engines/dfc_provider/app/services/supplied_product_builder.rb#L9-L12
