### PR TITLE
[Spree Upgrade] Adapt Product level stock management to Spree 2

### LINKED ISSUE #2982: [Spree Upgrade] Fix accessing new product
## Description

When clicking on `+ NEW PRODUCT`, a 500 error is returned with the following error:

```
Completed 500 Internal Server Error in 438.5ms (ActiveRecord: 1.8ms)
** [Bugsnag] No API key configured, couldn't notify

ActionView::Template::Error (undefined method `backorderable?' for nil:NilClass):
    1: <%# This chunk is just a copy of Spree's core/app/views/spree/admin/products/new.js.erb %>
    2: $("#new_product").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:erb]) %>');
    3: handle_date_picker_fields();
    4: <% unless Rails.env.test? %>
    5:   $('.select2').select2();
  app/models/concerns/variant_stock.rb:87:in `on_demand'
  app/models/concerns/variant_stock.rb:31:in `on_hand'
  app/models/spree/product_decorator.rb:138:in `on_hand'
  app/views/spree/admin/products/new.js.erb:2:in `_ac8cba3fd61d6e0362ef0d2ce3c49503'


  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.1ms)
  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.1ms)
  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (14.7ms)
  Rendered /home/pau/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-3.2.22.5/lib/action_dispatch/middleware/templates/rescues/layout.erb (15.8ms)
```

## Expected Behavior

Clicking this button should show the order creation page.

## Actual Behavior

The 500 error decribed above gets raised and nothing happens on the page.

## Possible Fix

According to the comment present on `app/views/spree/admin/products/new.js.erb`

```
 This chunk is just a copy of Spree's core/app/views/spree/admin/products/new.js.erb
```

but it turns out this view got moved in https://github.com/openfoodfoundation/spree/commit/e1e175c1c

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #2982, #3018 and #3030

For reviewers:
- see commits individually: commit messages should be self explanatory
- overall comment: it took me quite a lot of time to get to this solution, it's not a beautiful solution, but works...

#### What should we test?
New product page is now working.

Fixes the following specs:
- [X] spec/features/admin/products_spec.rb:23  (#3018)
- [X] spec/features/admin/products_spec.rb:62  (#3018)
- [x] spec/features/admin/products_spec.rb:108  (#3018)
- [X] spec/features/admin/bulk_product_update_spec.rb:174 (#3018)
- [x] spec/features/admin/bulk_product_update_spec.rb:686  (#3018)
- [X] spec/models/spree/product_set_spec.rb:26 (#3030)

Specs and respective issues that are closely related to this PR but will be fixed afterwards:
- spec/features/admin/bulk_product_update_spec.rb:531 (#3091)
- spec/features/admin/bulk_product_update_spec.rb:203 (#3114)
- spec/features/admin/products_spec.rb:201 (#3122)
- spec/features/admin/products_spec.rb:222 (#3122)
- spec/controllers/spree/admin/products_controller_spec.rb:79 (#3031)
- spec/controllers/spree/admin/products_controller_spec.rb:99 (#3031)

#### Dependencies
This PR needs #3190 to make the specs green.

### CODE REVIEW

File: app/controllers/spree/admin/products_controller_decorator.rb [hunk 1]
```diff
@@ -31,6 +31,18 @@ def index
     @show_latest_import = params[:latest_import] || false
   end
 
+  def create
```
Comment (mkllnk) [inline app/controllers/spree/admin/products_controller_decorator.rb]: I'm not a big fan of Rails' callbacks, but this seems the perfect use case for `around_action`:
```rb
around_action :delete_stock_params_and_set_after, only: :create, :update
```
https://guides.rubyonrails.org/action_controller_overview.html#after-filters-and-around-filters

Comment (luisramos0) [reply app/controllers/spree/admin/products_controller_decorator.rb]: ehehe, I didnt now that existed, thanks! but tbh I think these callbacks are terrible. It would reduce lines of code but the current solution is very explicit about what's doing. When I am doing things that are not standard (it's the case here) I like to be explicit. around_action would hide it on the top of the file. I prefer as is...

**Comment by luisramos0** [comment]
Rebased so that we see the build results of the freshly merged #3190 together with this one.

**Comment by luisramos0** [comment]
btw, first build I see below 50 broken tests (48).

File: app/controllers/spree/admin/products_controller_decorator.rb [hunk 2]
```diff
@@ -119,4 +131,22 @@ def strip_new_properties
...
     end
   end
+
+  def delete_stock_params_and_set_after
+    on_demand = params[:product].delete(:on_demand)
+    on_hand = params[:product].delete(:on_hand)
+
+    yield
+
+    set_stock_levels(@product, on_hand, on_demand) if @product.errors.empty?
```
Comment (sauloperez) [inline app/controllers/spree/admin/products_controller_decorator.rb]: You could use [valid?](https://apidock.com/rails/v3.2.13/ActiveResource/Validations/valid%3F) instead. It does this check for us.

File: app/models/concerns/product_stock.rb [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+        variants.first.on_demand
+      end
+    else
+      master.on_demand
+    end
+  end
+
+  def on_hand
+    if has_variants?
+      variants.map(&:on_hand).reduce(:+)
```
Comment (sauloperez) [inline app/models/concerns/product_stock.rb]: I think AR's [sum](https://apidock.com/rails/v3.2.13/ActiveRecord/Calculations/sum) would be more performant as we wouldn't load all the variant objects, iterate to get their on_hand value and then sum them all. Something like:

```suggestion
      variants.sum(:on_hand)
```

File: app/models/concerns/product_stock.rb [hunk 4]
```diff
@@ -0,0 +1,25 @@
+require 'active_support/concern'
+
+module ProductStock
+  extend ActiveSupport::Concern
+
+  def on_demand
+    if has_variants?
+      if variants.size > 1
+        raise 'Cannot determine product on_demand value of product with multiple variants'
```
Comment (sauloperez) [inline app/models/concerns/product_stock.rb]: what about implementing this as an early return? I think this better conveys the fact that it's an invalid case and it'd reduce a nesting level.

File: app/models/spree/product_set.rb [hunk 5]
```diff
@@ -63,27 +63,37 @@ def update_product_variants(product, attributes)
...
   end
 
+  def create_variant(product, variant_attributes)
+      on_hand = variant_attributes.delete(:on_hand)
+      on_demand = variant_attributes.delete(:on_demand)
+
+      variant = product.variants.create(variant_attributes)
+
+      variant.on_demand = on_demand if on_demand.present?
+      variant.on_hand = on_hand.to_i if on_hand.present?
```
Comment (sauloperez) [inline app/models/spree/product_set.rb]: I don't really understand why we assign them this way and can't be done through `#create`. Can you remind me why we need it?

File: spec/models/concerns/product_stock_spec.rb [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+describe ProductStock do
+  let(:product) { create(:simple_product) }
+
+  context 'when product has no variants' do
+    before do
+      product.variants.first.destroy
+      product.variants.reload
+    end
+
+    scenario 'product.on_demand is master.on_demand' do
```
Comment (sauloperez) [inline spec/models/concerns/product_stock_spec.rb]: why don't we use `it` like all other unit tests? I'd rather keep the consistency to avoid confusing new devs.

File: app/models/concerns/product_stock.rb (hunk 3 above)
Comment (luisramos0) [reply app/models/concerns/product_stock.rb]: I will do that.
this is your code btw ;-)
https://github.com/openfoodfoundation/openfoodnetwork/commit/75ad4254a6c50b28a2f3b36828d2e3428b20b774#diff-e6a3a7e1c82ac34e5e72899c9ceb109cR133

File: app/models/concerns/product_stock.rb (hunk 4 above)
Comment (luisramos0) [reply app/models/concerns/product_stock.rb]: do you mean:
```ruby
 if has_variants?
   raise 'Cannot determine product on_demand value of product with multiple variants' if variants.size > 1
   variants.first.on_demand
else
   master.on_demand
end
```

File: app/models/spree/product_set.rb (hunk 5 above)
Comment (luisramos0) [reply app/models/spree/product_set.rb]: it's because these assignments will save the variant themselves and that messes up the overall variant save process. I think this is ok, first you have to create the variant and then you can manage stock (there are stock items and stock movements involved in stock management).

File: app/models/concerns/product_stock.rb (hunk 3 above)
Comment (sauloperez) [reply app/models/concerns/product_stock.rb]: Yes, I saw. I was probably too lazy

File: app/models/spree/product_set.rb (hunk 5 above)
Comment (sauloperez) [reply app/models/spree/product_set.rb]: uf, this is getting messy... we'll need to fix these things once get the upgrade live.

Comment (luisramos0) [reply app/models/spree/product_set.rb]: I dont think it's too bad. you cant expect to create a variant and all it's parts in one mass_assignemnt. we should have a collection of services to do different things to models. I think it's totally fine to detach variant stock management from the variant model. the only thing we need to fix is to take these attributes out of the variant into a service. moving from variant_stock into some form of variant_stock_service.

so, in this case the actual change would be on the frontend where the "API" to create variants with stock settings disappears and the frontend needs to first create the variant and then set/manage stock levels (it would be a different API endpoint to manage stock levels).

Comment (sauloperez) [reply app/models/spree/product_set.rb]: definitely, we'll need to work on the frontend and that will simplify the backend.

File: app/models/concerns/product_stock.rb (hunk 3 above)
Comment (mkllnk) [reply app/models/concerns/product_stock.rb]: I don't think ActiveRecord's `sum` works here, because `on_hand` is not a column in the database, right? Each variant actually needs to find all stock locations first. And the variants may be augmented by variant overrides.

Comment (luisramos0) [reply app/models/concerns/product_stock.rb]: hey @mkllnk , thanks, that makes sense!

Comment (luisramos0) [reply app/models/concerns/product_stock.rb]: I'll skip this. ok?

**Comment by luisramos0** [comment]
ready for re-review @sauloperez @mkllnk 
thanks!

File: app/models/concerns/product_stock.rb (hunk 3 above)
Comment (sauloperez) [reply app/models/concerns/product_stock.rb]: @mkllnk my point here was to get the sum straight from DB; way faster than Ruby.

Comment (mkllnk) [reply app/models/concerns/product_stock.rb]: Sure. :-)
