### PR TITLE
Load MiniMagick before use

### LINKED ISSUE #12751: Some products not showing on Hungarian instance shopfront
## Description
This error can be reproduced on the following page:

https://openfood.hu/anyahajoegyesulet/shop#/shop_panel

The products stop loading and the loader image is showing endlessly.

Checking the network tab of the developer toolbar a HTTP 422 error is shown with the following message:
exception	"uninitialized constant Spree::Image::MiniMagick\n\n rescue ActiveStorage::Error, MiniMagick::Error, ActionView::Template::Error => e\n ^^^^^^^^^^\nDid you mean? MiniMime"

## Expected Behavior
All products are shown.

## Actual Behaviour
Some products not shown, but instead the loader image shows up endlessly.

## Steps to Reproduce
1. Go to https://openfood.hu/anyahajoegyesulet/shop#/shop_panel
2. Scroll down until the loder image wont disaappear and products do not load.
3. It usually happens at product "Savanyú uborka "

## Animated Gif/Screenshot
Screenshot from 2024-08-08 08-55-45

## Workaround
No workaround.

## Severity
bug-s1: a critical feature is broken: checkout, 

## Your Environment
Happens in all browsers, regardless of OS.

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #12751

We only reference MiniMagick when rescuing errors but when it's not loaded, that code fails to find the error class itself to apply the rescue block.

The rescue block is covered by a spec but the code passes there as MiniMagick is loaded.

We can see this error only in development, staging and production with a freshly restarted server before any image has been uploaded. An upload triggers the loading of MiniMagick and the error disappears.

So there are two conditions to trigger this bug:

* MiniMagick is not loaded.
* An image to display is not processed and the processing raises an error other than `ActiveStorage::Error`.

#### What should we test?

- This will be a production test on the Hungarian instance.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/models/spree/image.rb [hunk 1]
```diff
@@ -1,5 +1,7 @@
 # frozen_string_literal: true
 
+require "mini_magick"
```
Comment (mkllnk) [inline app/models/spree/image.rb:3]: The alternative is to rescue `StandardError` which may be more robust and agnostic of what kind of problem is arising when processing an image.

Usually it's good practice to rescue specific errors. But if an unknown error breaks the shop page instead of not displaying an image then that's a bad consequence in production as well.

I want to merge this pull request today to include it in the release. But let's discuss other options, @openfoodfoundation/developers.

Comment (chahmedejaz) [reply app/models/spree/image.rb:3]: I agree that using specific errors for rescuing should be the practice, however, I think it should be the case where we want to handle different errors differently.

If we need to handle each error similarly, then the `StandardError` rescue seems better with some logging or non-code-breaking alerts. In this case, we are rescuing from [3 different errors](https://github.com/mkllnk/openfoodnetwork/blob/93edf4e3adbc21580713a46fd0e65ebb37beb2e8/app/models/spree/image.rb#L34-L43) I guess, but each is handled in a same way. We could shorten this by just rescuing `StandardError`. In image processing, many cases may break the code and we may again face a similar issue in the future. That may have been handled by the `MiniMagick::Error` rescue. But yes, like you said `StandardError` may be more agnostic to handling these image processing cases.

Comment (dacook) [reply app/models/spree/image.rb:3]: I agree it's worth breaking our rule of "always rescue specific errors" for this case. We are still notifying to Bugsnag so it won't be hiding any new types of errors.

Do we need to differentiate between known errors (ActiveStorage::Error, MiniMagick::Error, ActionView::Template::Error) and new error types? 
I think not. Whatever the error type, if it happens infrequently  we can probably ignore it. If it is impacting on users and they report it, we can investigate. Or if we see a huge spike in bugsnag, we can investigate it.

So I'm happy to switch to just StandardError. But I would suggest we use at least one of these known error types in the spec (if not already).
