### PR TITLE
[Spree Upgrade] Add missing translations causing a test failure

### LINKED ISSUE #3015: [Spree Upgrade][FrontOffice] Fix confirmation email spec (1 broken test)
Fix error in spec/features/consumer/confirm_invitation_spec.rb:22

```
  3) Confirm invitation as manager confirm email and set password allows you to set a password
     Failure/Error: expect(page).to have_text "Change my password"
       expected to find text "Change my password" in "Powered by Open Food Network Shops Map
```

Something related to UserConfirmationsController? I couldn't figure this one out quickly.

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Closes #3015

These two translations were missing and one of them was causing a test to fail.

### CODE REVIEW

File: spec/features/consumer/confirm_invitation_spec.rb [hunk 1]
```diff
@@ -19,7 +19,7 @@
       visit spree.spree_user_confirmation_url(confirmation_token: user.confirmation_token)
 
       expect(user.reload.confirmed?).to be true
-      expect(page).to have_text "Change my password"
```
Comment (sauloperez) [inline spec/features/consumer/confirm_invitation_spec.rb]: The page was rendering `Change My Password` as the result of the missing translation thus, not matching this assertion.

**Comment by sauloperez** [comment]
I won this time @sigmundpetersen :trollface:

**Comment by sigmundpetersen** [comment]
You're getting better @sauloperez :trollface:
