### PR TITLE
[Vouchers] fix error when creating a percentage voucher

### LINKED ISSUE #11362: [Vouchers] Error 500 when trying to create a percentage voucher after trying a first time without entering a voucher code (Bugsnag)
## Description

There is an error 500 when trying to create a percentage voucher after trying a first time without entering a voucher code. [Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork-aus/errors/64c25864c4516800087f95dd?filters[event.since]=30d&filters[error.status]=open&filters[app.release_stage]=staging) Same happens if the voucher amount was not a number or zero or code taken or amount >100  on the first try. For flat amounts this is working ok.

## Expected Behavior

No error 500.

## Actual Behaviour

Error 500.

## Steps to Reproduce

1. See screen capture below.

## Animated Gif/Screenshot

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/c5a03107-23fc-4d89-bb8e-f0f5311e2e24

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #11362 

When getting an error while creating a percentage voucher, subsequent try to create a voucher result in 500 error.This fix the issue.

#### What should we test?

see screen capture here : #11362

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/controllers/admin/vouchers_controller.rb [hunk 1]
```diff
@@ -9,9 +9,13 @@ def new
     end
 
     def create
+      # In the scenario where you get an error when trying to create a percentage voucher, we'll
+      # now have percentage rate voucher instanciated. Hence why we check for both params type
+      voucher_type = params.dig(:vouchers_flat_rate, :voucher_type) ||
+                     params[:vouchers_percentage_rate][:voucher_type]
```
Comment (mkllnk) [inline app/controllers/admin/vouchers_controller.rb:15]: You do a similar thing in `permitted_resource_params` already. It could be good to re-use that. But I think I just found a better way of doing that. You can do `Voucher.new.becomes(Voucher)` and then we have only one name in the parameters.

And if we assign the type as attribute to `Voucher` then Rails verifies that it's a subclass and we don't have to do that. I'll have a play with it and maybe add a commit. Stay tuned...

**Review by mkllnk — APPROVED** [review]

File: app/views/admin/vouchers/new.html.haml [hunk 2]
```diff
@@ -1,4 +1,4 @@
-= form_with model: @voucher, url: admin_enterprise_vouchers_path(@enterprise), html: { name: "voucher_form" } do |f|
+= form_with model: @voucher.becomes(Voucher), url: admin_enterprise_vouchers_path(@enterprise), html: { name: "voucher_form" } do |f|
```
Comment (rioug) [inline app/views/admin/vouchers/new.html.haml:1]: TIL about `becomes`

**Comment by rioug** [comment]
It's much cleaner like this, it make sense that rails can handle generating the correct object using the type.

**Review by dacook — APPROVED** [review]
Good changes. 
I wouldn't have thought to simply let the exception get raised and handle it like that. It's great to remove lots of branching, and simply specify behaviour for a specific exception like that. 

I remember talking about it in the past, and your suggestion of doing this for all validation errors which made a lot of sense. (But I also remember disagreeing simply because it isn't the usual done thing in Rails..)

**Comment by mkllnk** [comment]
> I remember talking about it in the past, and your suggestion of doing this for all validation errors

I revised that idea since because exceptions are for *exceptional* cases while validations are pretty normal. In this case though, we have a form with only two pre-defined options for the type and both are correct. An error is only raised if something goes wrong in a deploy or someone tries to inject values manually. That is not a normal case and Rails handles it.

**Comment by drummer83** [comment]
Hi @rioug,
Thanks for this important fix. I reproduced the error on staging first and checked your PR afterwards. I also checked that for flat amount vouchers everything is working still.

### After staging the PR
| Error | Percentage voucher | Flat voucher |
| - | - | - |
| no code entered | ✔️ | ✔️ |
| code already taken | ✔️ | ✔️ |
| amount is zero | ✔️ | ✔️ |
| amount is not a number | ✔️ | ✔️ |
| amount is > 100 | ✔️ | n.a. | 

I also confirmed that there are no more errors in Bugsnag. ✔️ 

Everything is looking good! 💪 
Merging! Thanks! 🚀

**Comment by dacook** [comment]
> exceptions are for _exceptional_ cases

I think that's a great definition 😁
