### PR TITLE
Make the payment methods filter handle misconfigured stripe payment methods

### LINKED ISSUE #4044: ActionView::Template::Error in checkout#edit
## Description

It seems to be possible to setup Stripe with an invalid payment method. The check for validity fails due to a simple programming error. This looks like it's easy to fix. It also only happened to @emilyjeanrogers so far.

**ActionView::Template::Error** in **checkout#edit**
undefined method `zero?' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d277cae5ad6b0001b90a8ed?event_id=5d2c0354004a917e07e20000&i=gh&m=ci)

## Stacktrace

    lib/open_food_network/available_payment_method_filter.rb:18 - stripe_configuration_incomplete?
    lib/open_food_network/available_payment_method_filter.rb:5 - block in filter!
    lib/open_food_network/available_payment_method_filter.rb:5 - reject!
    lib/open_food_network/available_payment_method_filter.rb:5 - filter!
    app/helpers/enterprises_helper.rb:28 - available_payment_methods
    app/helpers/injection_helper.rb:35 - inject_available_payment_methods
    app/views/checkout/_form.html.haml:8 - block in _3f60c5c8bcc9959695a349c2b00a917c
    app/views/checkout/_form.html.haml:1 - _3f60c5c8bcc9959695a349c2b00a917c
    app/views/checkout/edit.html.haml:25 - _3692837941a48bc1e30f97cfc71f160a

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d277cae5ad6b0001b90a8ed?event_id=5d2c0354004a917e07e20000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

I bumped into this one while doing the Stripe SCA work.

Closes #4044
This also makes #4713 much better (maybe closes it?): there will be no 500 error on checkout, the mis-configured payment method will just not show up on the checkout page.

#### What should we test?
Configure a Check payment method and make sure it can be used on checkout.
Configure a Stripe payment method and do not add a enterprise or connect to stripe. Make sure it does not appear on checkout but checkout works.
Configure a Stripe payment method and define the enterprise but do not connect to stripe. Make sure it does not appear on checkout but checkout works.
Configure a Stripe payment method and define the enterprise and connect to stripe. Make sure it *does* appear on checkout and you can checkout using it.

No error 500 on checkout :-)

#### Release notes
Changelog Category: Fixed
Fixed bug on checkout when a stripe payment method was misconfigured.

### CODE REVIEW

File: lib/open_food_network/available_payment_method_filter.rb [hunk 1]
```diff
@@ -15,9 +15,9 @@ def stripe_enabled?
     end
 
     def stripe_configuration_incomplete?(payment_method)
-      return true if payment_method.preferred_enterprise_id.zero?
-
-      payment_method.stripe_account_id.blank?
+      payment_method.preferred_enterprise_id.nil? ||
+        payment_method.preferred_enterprise_id.zero? ||
+        payment_method.stripe_account_id.blank?
```
Comment (sauloperez) [inline lib/open_food_network/available_payment_method_filter.rb]: Isn't this equivalent to `payment_method.preferred_enterprise_id.zero? || payment_method.stripe_account_id.blank?` since

```ruby
irb(main):002:0> nil.blank?
=> true
```

Comment (luisramos0) [reply lib/open_food_network/available_payment_method_filter.rb]: no because
2.3.7 :001 > nil.zero?
NoMethodError: undefined method `zero?' for nil:NilClass
	from (irb):1
	from /Users/luisramos/.rvm/rubies/ruby-2.3.7/bin/irb:11:in `<main>'

it's 2 different properties: preferred_enterprise_id and stripe_account_id

**Comment by RachL** [comment]
hello @luisramos0 !

Can you provide additional details on how to do
> Configure a Stripe payment method and define the enterprise but do not connect to stripe. Make sure it does not appear on checkout but checkout works.

I don't see how to define an enterprise without connecting stripe.

**Comment by luisramos0** [comment]
like this:
image

**Comment by luisramos0** [comment]
ah, I see you cant update to an enterprise that is not connected if the payment method is already connected, but you can create a new one and save with an enterprise even if no connection to stripe is done :+1:

**Comment by RachL** [comment]
- Configure a Check payment method and make sure it can be used on checkout.

Yes.

- Configure a Stripe payment method and do not add a enterprise or connect to stripe. Make sure it does not appear on checkout but checkout works.

@luisramos0 if I do not add an enterprise I cannot configure a stripe payment method. What did you meant by that?

- Configure a Stripe payment method and define the enterprise but do not connect to stripe. Make sure it does not appear on checkout but checkout works.

Same here, if I don't connect, I cannot validate the form

image

- Configure a Stripe payment method and define the enterprise and connect to stripe. Make sure it does appear on checkout and you can checkout using it.

All good here

**Comment by RachL** [comment]
- Configure a Check payment method and make sure it can be used on checkout.

Yes.

- Configure a Stripe payment method and do not add a enterprise or connect to stripe. Make sure it does not appear on checkout but checkout works.

@luisramos0 if I do not add an enterprise I cannot configure a stripe payment method. What did you meant by that?

- Configure a Stripe payment method and define the enterprise but do not connect to stripe. Make sure it does not appear on checkout but checkout works.

Same here, if I don't connect, I cannot validate the form

image

- Configure a Stripe payment method and define the enterprise and connect to stripe. Make sure it does appear on checkout and you can checkout using it.

All good here

**Comment by RachL** [comment]
- Configure a Check payment method and make sure it can be used on checkout.

Yes.

- Configure a Stripe payment method and do not add a enterprise or connect to stripe. Make sure it does not appear on checkout but checkout works.

@luisramos0 if I do not add an enterprise I cannot configure a stripe payment method. What did you meant by that?

- Configure a Stripe payment method and define the enterprise but do not connect to stripe. Make sure it does not appear on checkout but checkout works.

Same here, if I don't connect, I cannot validate the form

image

- Configure a Stripe payment method and define the enterprise and connect to stripe. Make sure it does appear on checkout and you can checkout using it.

All good here

**Comment by RachL** [comment]
oooops I just noticed that I asked you about this a week ago... I'm getting old :facepalm:

**Comment by luisramos0** [comment]
see my comment above:
"you cannot update the owner of the payment method to an enterprise that is not connected if the owner is an enterprise that is already connected, but you can create a new payment method and save with an enterprise that is not connected +1"

SO,

this is not possible :+1:    "Configure a Stripe payment method and do not add a enterprise or connect to stripe. Make sure it does not appear on checkout but checkout works."

but this is possible if creating a new payment method:    "Configure a Stripe payment method and define the enterprise but do not connect to stripe. Make sure it does not appear on checkout but checkout works."

**you must use an enterprise that is not connected to stripe yet.**

**Comment by RachL** [comment]
I'm deeply sorry I was getting confused over nothing...



This is last test is working, moving to ready to go :tada: :

image

image

**Comment by luisramos0** [comment]
lol, panda

**Comment by luisramos0** [comment]
what do you think about #4713?
