### PR TITLE
Fix NoMethodError in Admin::ProductsV3#index - Only when using the hu.yml locale

### LINKED ISSUE #12739: NoMethodError in Admin::ProductsV3#index - Only when using the hu.yml locale
## Description
When using the hu.yml locale and the admin_style_v3 is fully enabled the Products page (admin/products) throws the following error:
`<pre style="font-size: 11px; white-space: pre-wrap; color: rgb(236, 236, 236); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(34, 34, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code>undefined method `&gt;' for nil:NilClass

          if options[:significant] &amp;&amp; options[:precision] &gt; 0
                                                          ^</code></pre><div class="source " id="frame-source-0-11" style="border: 1px solid rgb(85, 85, 85); background: rgb(51, 51, 51); max-width: 978px; color: rgb(236, 236, 236); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#22</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background: rgb(68, 68, 68);">
20 21 22 23 24 25 | def unit_value_with_description(variant)       scaled_unit_value = variant.unit_value / (variant.product.variant_unit_scale \|\| 1)       precised_unit_value = number_with_precision(         scaled_unit_value,         precision: nil,         strip_insignificant_zeros: true
-- | --

</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(236, 236, 236); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(34, 34, 34); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Trace of template inclusion: #&lt;ActionView::Template app/views/admin/products_v3/_product_variant_row.html.haml locals=["category_options", "form", "producer_options", "product", "product_index", "tax_category_options"]&gt;, #&lt;ActionView::Template app/views/admin/products_v3/_table.html.haml locals=["category_options", "producer_options", "products", "tax_category_options"]&gt;, #&lt;ActionView::Template app/views/admin/products_v3/_content.html.haml locals=["category_id", "category_options", "flashes", "pagy", "producer_id", "producer_options", "products", "search_term", "tax_category_options"]&gt;, #&lt;ActionView::Template app/views/admin/products_v3/index.html.haml locals=["categories", "flash", "producers", "tax_category_options"]&gt;</p><br class="Apple-interchange-newline">`

If I switch the language to es or en_AU the same page works flawlessly. The same behavior can be reproduced on locale and also the live site with the mentioned configuration. 

## Expected Behavior
The app should render the page as with other locales.

## Actual Behaviour
See description.

## Steps to Reproduce
1. Add the hu language to the AVAILABLE_LOCALES in .env
2. Make sure v3_admin_style is enabled (/admin/feature-toggle/features)
3. Login, go to administration/products
4. Use rake tmp:cache:clear when making changes to the translation files.

## Animated Gif/Screenshot
Screenshot 2024-08-06 at 22 33 14

## Workaround
The app works as intended if we switch off v3_admin_style for every user.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
Both locale and production.

* Version used: [v4.5.4 Orange roll](https://github.com/openfoodfoundation/openfoodnetwork/releases/tag/v4.5.4)

## Possible Fix
Probably a configuration issue.

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12739

- This PR looks for other areas where the following fix needs to be implemented:
- https://github.com/openfoodfoundation/openfoodnetwork/pull/12700
- The reported issue is caused by the same issue fixed above, but in a different place

#### What should we test?

- Change the language to Hungarian ( or should be tested on Hungarian instance)
- Go to the new products page
- It should not throw the error

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [x] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

**Comment by chahmedejaz** [comment]
**HEADS-UP:** In the future, whenever we are using Rails rounding off methods like `number_to_rounded` or `number_with_precision` with `precision: nil`, we would have to use `significant: false` as well. Otherwise, it would break for hu locale, and may break for any others we don't know yet. Thanks

File: app/helpers/admin/products_helper.rb [hunk 1]
```diff
@@ -22,7 +22,8 @@ def unit_value_with_description(variant)
       precised_unit_value = number_with_precision(
         scaled_unit_value,
         precision: nil,
-        strip_insignificant_zeros: true
+        strip_insignificant_zeros: true,
+        significant: false,
```
Comment (mkllnk) [inline app/helpers/admin/products_helper.rb:26]: According to the documentation, `significant` is false by default. So this wouldn't change anything. Do you have a test for this?

https://api.rubyonrails.org/classes/ActiveSupport/NumberHelper.html#method-i-number_to_rounded

Comment (dacook) [reply app/helpers/admin/products_helper.rb:26]: This [error](https://github.com/openfoodfoundation/openfoodnetwork/issues/12739) keeps popping up on the Hungary instance when we don't explicitly set significant false (despite what the documentation says). 
I don't think we've got to the bottom of the reason yet. 
@rioug spent a little time trying to get to the bottom of it, I think he wasn't able to conclusively call it a Rails bug. So it's possibly something related to the OFN codebase somehow.

It does seem likely that this could happen again (anybody could use number_with_precision in the future, and not realise about this obscure issue). But I'm not sure how best to proceed. We could try monkey-patching, but that's not a great solution.. 

It would be better to understand why it's happening first. A couple of thoughts:
* replicate with a spec 
* look further into the rails source code to understand what's happening

Note that there's a few HU-specific variables that could be related. I'm guessing it's the system locale:
https://github.com/openfoodfoundation/ofn-install/blob/master/inventory/group_vars/hu.yml

I started digging into the source code, but it seems that `significant` always defaults to `false`, so I don't know what's happening or where the locale comes into play.
https://github.com/rails/rails/blob/main/activesupport/lib/active_support/number_helper/number_converter.rb

**Review by dacook — APPROVED** [review]
In the interest of fixing the bug, I think we should go ahead with this fix, but it would be worth more investigation to see if we can find out the cause.

@chahmedejaz have you been able to replicate the issue in your development environment? Would you mind trying, in case you can find out the cause? (Maybe try a spike for one hour maximum?)

**Review by mkllnk — APPROVED** [review]

**Comment by chahmedejaz** [comment]
> In the interest of fixing the bug, I think we should go ahead with this fix, but it would be worth more investigation to see if we can find out the cause.
> 
> @chahmedejaz have you been able to replicate the issue in your development environment? Would you mind trying, in case you can find out the cause? (Maybe try a spike for one hour maximum?)

Yes, David, when I set the locale to hu, it gets reproduced in my dev environment. Let me do a spike on whether it's the locale or our locale-specific configurations. Thanks

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz,
merge appeared conflicts for this PR. Can you take a look? Thanks :pray:

**Comment by chahmedejaz** [comment]
> Hey @chahmedejaz, some merge conflicts appeared for this PR. Can you take a look? Thanks 🙏

Hi @filipefurtad0 - The conflict has been resolved. Thanks.

**Comment by chahmedejaz** [comment]
> In the interest of fixing the bug, I think we should go ahead with this fix, but it would be worth more investigation to see if we can find out the cause.
> 
> @chahmedejaz have you been able to replicate the issue in your development environment? Would you mind trying, in case you can find out the cause? (Maybe try a spike for one hour maximum?)

Hi @dacook - I was able to reproduce this in the dev environment of our app and another one as well:
image

Moreover, I did a spike on the root cause, and here are the findings:
https://www.loom.com/share/1a9092cfde2e451b8388f9ca1aabd5da

Please let me know whether you want to take this PR as an opportunity to remove this gem and remove our _fix_ from all the places or if we should do that in another issue. Thanks.

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz ,

Thanks for the heads up on this one. I've checked that:
- the PR deploys correctly
- the products page renders correctly with the locales in staging-FR - I can't really make test it for HU locale

So, on my end this would be good to go. But as just agreed via DM, I'll leave it up to you @chahmedejaz and reviewers to decide whether you wish to merge and go for this solution, or rather try something else. Added the feedback needed label.

Thanks!

**Review by mkllnk — APPROVED** [review]
Thanks for the investigation. That's really interesting.

I'll merge this pull request because it will fix a bug immediately.

I'm not sure about the way forward though. It's true that rails-i18n is not maintained by the Rails team, so it's not "official". But it does contain some localisation data that we may be missing otherwise. One example are error messages like "name can't be blank".

If we remove the rails-i18n gem, we may find more places were we need to add our own translations. That may be a good thing because then anyone can translate it with Transifex in the OFN context.

I'm worried that we may create more work for ourselves. The rails-i18n gem is actively maintained and contains a lot of knowledge. But then, looking at the reverse dependencies, I can't see any significant projects. So there are not many other (funded) organisations contributing to this.

So my vote would be for removing in a future PR. What do others think, @dacook, @rioug.

**Comment by chahmedejaz** [comment]
> I'm not sure about the way forward though. It's true that rails-i18n is not maintained by the Rails team, so it's not "official". But it does contain some localisation data that we may be missing otherwise. One example are error messages like "name can't be blank".

Yes, exactly I just realized this, and looking at Rails default behavior and the `hu.yml` locale data in `rails-i18n`, I think it's a bug in the gem because it's overriding the default behavior. I'm opening an issue, maybe we could get this resolved in the gem itself or may have some thoughts from the maintainers on it.
Moreover, For the time being in the next PR, we could add `number.format.significant` to `false` in our app's `hu.yml` to make it work.

>I'm worried that we may create more work for ourselves. The rails-i18n gem is actively maintained and contains a lot of knowledge. But then, looking at the reverse dependencies, I can't see any significant projects. So there are not many other (funded) organisations contributing to this.

Agreed

Sorry for the back and forth 😅

**Comment by rioug** [comment]
Thanks for getting to the bottom of this @chahmedejaz ! 
Like David said it's hard to know how useful the gem is, without knowing that I wouldn't want to remove the gem for now. I guess we could try to remove it and see which test fails and fixed them, but that's likely time consuming.

As much as it would be good to remove a dependency, I don't think we are in a position right now to do so. So I vote to keep it. Should we open at tech debt issue to track this ?

**Comment by chahmedejaz** [comment]
Thanks, David and Gaetan for the feedback.

And yes @rioug - I think we should open an issue for this one to track it. In that fix, we would be removing our existing fix from all the places and adding `number.format.significant` to `false` for `hu.yml`. Thanks
