### PR TITLE
Fix invalid unit value (rebase of #6250)

### LINKED ISSUE #3912: Unable to create new product (snail) with Value field empty
## Description
User cant create product.

Screenshot 2019-06-10 at 13 11 51

I am still talking to the user to confirm this is her problem but I did find a bug.

## Steps to Reproduce
When creating a product with unit type items, user fills in all required fields except the unit value field which is mandatory.

## Actual Behaviour
After submitting the form, the user should see the same page with a standard form error saying "unit value field cant be blank".

Screenshot 2019-06-10 at 13 11 58

## Expected Behavior
After submitting the form, user sees snail page.

## Context
First real bug coming from Portuguese users.

## Severity
bug-s3
the workaround is to call support that will call developers that will look at the logs and will tell support "unit value field is mandatory" that will tell the user "unit value field is mandatory" :-D

## Your Environment
* Version used: Katuma OFN v2.0.2
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): osx 10.14

## Possible Fix
the bug is in this line:
https://github.com/openfoodfoundation/openfoodnetwork/blob/568e3003ba43c713ac4fb5a57fddfbca086f7b98/app/controllers/spree/admin/products_controller_decorator.rb#L142

for some reason product.valid? is returning true but product.errors is not empty:
Screenshot 2019-06-10 at 13 05 24

Probably related to the fact that this field unit_description is a delegate in the product model:
`delegate_belongs_to :master, :unit_value, :unit_description`

The fix is to either use product.errors instead of product.valid? here or change something in the model to get product.errors and product.valid? consistent again.

### LINKED ISSUE #4959: Creating a Product: snail when Value* field left blank
## Description
When creating a new product in the backoffice, leaving the mandatory field Value* blank, generates an error 500 Snail, instead of triggering the warning usually displayed when other mandatory fields are left blank.

## Expected Behavior

A warning should appear, indicating that the field is mandatory (pic below). In the example below, only 5 errors are triggered. It would be expected that the Value* field appears on the mandatory field list, its input box underlined in red, with the red message below "can't be blank" , as for other mandatory fields:

image

## Actual Behavior
Error 500, instead of the error message and red markings described above.

## Steps to Reproduce

1. Go to /admin/products
2. Click on the [+ New Product] button
3. Fill out all the mandatory fields, except Value*
5. Click on [Create] -> the Snail should appear.

## Animated Gif/Screenshot
These settings originated error 500/Snail - the "1" in Value* is a placeholder (grayed out):
image

The settings below do not break the page - not because of the upload of the picture (as initially thought :-) but rather because the Value field is not empty:
image

## Workaround

Filling out the field is the only way to create the product.

## Severity
bug-s3: a feature is broken but there is a workaround - although it is happening quite a lot lately, and does show a Snail to the user...

## Your Environment

* Version used: v2.7.8 Striped Espargo
* Browser name and version: Chrome/Firefox
* Operating System and version (desktop or mobile): desktop

### LINKED ISSUE #6117: Invalid unit_value on product creation returns 500 instead of 422
## Description
Entering a non-number for `unit_value` (appears as the "Value" text field) during product creation returns a 500 error instead of a more informative error message. We do have placeholder text in the field but this can often be missed or misinterpreted.

## Expected Behavior
Error message stating "Value must be a number" and a 422 server response.

## Actual Behaviour
Entering a non-number for unit_value during product creation returns a 500 error.

## Steps to Reproduce

1. https://openfoodnetwork.net/admin/products
2. Click on New Product
3. Enter valid product information except for the Value text field
4. Click Create
5. Death by slug

## Animated Gif/Screenshot
Screen Shot 2020-10-01 at 1 53 41 PM

## Workaround
Reading the placeholder text, or just guessing at what went wrong. 

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment
Safari

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #6117
Closes #3912
Closes #4959 

See the original PR (#6250) for details; I tried to rebase it after the spree updates and couldn't untangle things... sorry @tsara27 !

There is still a lot left to be desired in this UI; as @Erioldoesdesign [noted](https://github.com/openfoodfoundation/openfoodnetwork/issues/4959#issuecomment-721177819), it isn't very clear what this field is for. Moreover the error now says "unit value can't be blank" but the label on the field itself is "value"; and even moreover, if you do fill in the field but with something that's not a number, because it's confusing what should go in there, you get the same "unit value can't be blank" error. 

So yes, lots of potential for further improvement here...but this gets rid of the 500 slug. And closes three issues for the price of one!

#### What should we test?
Login as an admin.
Go to products.
Create a new product.
Fill other required details, leave the unit value empty.
Should see an error and not a slug. 

#### Release notes
Fixed a bug where entering an empty or invalid value on the product creation page would show a slug instead of an error message. 
Changelog Category: User facing changes

### CODE REVIEW

**Comment by andrewpbrett** [comment]
@sauloperez I noticed that you'd written some of the specs related to this, so I thought you'd be a good person to review it :)

File: spec/features/admin/products_spec.rb [hunk 1]
```diff
@@ -112,6 +112,27 @@
...
+
+      fill_in 'product_name', with: 'Hot Cakes'
+      select 'New supplier', from: 'product_supplier_id'
+      select "Weight (kg)", from: 'product_variant_unit_with_scale'
+      select taxon.name, from: "product_primary_taxon_id"
+      fill_in 'product_price', with: '1.99'
+      fill_in 'product_on_hand', with: 0
+      check 'product_on_demand'
+      select 'Test Tax Category', from: 'product_tax_category_id'
+      page.find("div[id^='taTextElement']").native.send_keys('In demand, and on_demand! The hottest cakes in town.')
```
Comment (sauloperez) [inline spec/features/admin/products_spec.rb:129]: we don't actually need to specify `page`. `find` is globally available just like the other Capybara form in put methods

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

Great - this seems to work fine now. I tested the Units field with both numeric and non-numeric values, in both pages:

- /admin/products/new
- /admin/products/

In all cases, the error "Unit value can't be blank" is displayed now:

image

This is good to go.

Would it be a good idea to extend this test case in the specs:
spec/features/admin/products_spec.rb:134 `expect(page).to have_content "Unit value can't be blank"`

to all other mandatory fields? We recently had an S2 related to this #6393  and this issue #6159 - the latter can be closed now as well. Opened #6447 on this.

Something else noticed while testing: "Display as" and "on hand" don't seem to be mandatory fields - it's possible to create products without filling in anything.
