### PR TITLE
[Spree Upgrade] Sets StockLocation.backorderable_default to false in test factories

### LINKED ISSUE #3114: [Spree Upgrade][BackOffice] Fix admin/bulk_product_update spec (1 broken test)
admin/bulk_product_update has a few errors in #2804, #3018 and #3091.
Apart from these, there is this error in bulk_product_update related to creating a variant directly on the bulk product edit page:

```ruby
  16) 
  As an Administrator
  I want to be able to manage products in bulk
 creating new variants
      Failure/Error: raise message if stock_items.empty?
      
      RuntimeError:
        You need to save the variant to create a stock item before you can set stock levels.
      # ./app/models/concerns/variant_stock.rb:125:in `raise_error_if_no_stock_item_available'
      # ./app/models/concerns/variant_stock.rb:77:in `count_on_hand='
      # ./app/models/concerns/variant_stock.rb:58:in `on_hand='
      # ./app/models/spree/product_set.rb:83:in `update_variant'
      # ./app/models/spree/product_set.rb:71:in `block in update_variants_attributes'
      # ./app/models/spree/product_set.rb:70:in `each'
      # ./app/models/spree/product_set.rb:70:in `update_variants_attributes'
      # ./app/models/spree/product_set.rb:61:in `update_product_variants'
      # ./app/models/spree/product_set.rb:32:in `update_attributes'
      # ./app/models/spree/product_set.rb:95:in `block in save'
      # ./app/models/spree/product_set.rb:94:in `each_value'
      # ./app/models/spree/product_set.rb:94:in `each'
      # ./app/models/spree/product_set.rb:94:in `all?'
      # ./app/models/spree/product_set.rb:94:in `save'
      # ./app/controllers/spree/admin/products_controller_decorator.rb:46:in `bulk_update'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ExpectationNotMet:
      #   expected to find text "Changes saved." in "Saving failed.Save failed due to invalid data:500"
      #   ./spec/features/admin/bulk_product_update_spec.rb:225:in `block (2 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
This makes the default value of variant.on_demand be false

#### What? Why?
Closes #3114
Replaying #3246 but now making the necessary adaptations.

Notes:
I made most changes in one single commit on purpose, these changes are all closely related and are better looked at together.

I had to fix the :product factory modify part and set on_hand default value.
:simple_product is being used in many places and it's property on_demand as well. At some point we have to decide to use either :product or :simple_product. I think we should use :product and delete :simple_product. Something we should do at some point in the future.

#### What should we test?
see 3246 description https://github.com/openfoodfoundation/openfoodnetwork/pull/3246#issue-241033260

### CODE REVIEW

File: spec/models/spree/payment_method_spec.rb [hunk 1]
```diff
@@ -28,16 +28,20 @@ module Spree
...
     it "computes the amount of fees" do
-      pickup = create(:payment_method)
       order = create(:order)
-      expect(pickup.compute_amount(order)).to eq 0
-      transaction = create(:payment_method, calculator: Calculator::FlatRate.new(preferred_amount: 10))
-      expect(transaction.compute_amount(order)).to eq 10
-      transaction = create(:payment_method, calculator: Calculator::FlatPercentItemTotal.new(preferred_flat_percent: 10))
-      expect(transaction.compute_amount(order)).to eq 0
+
+      free_payment_method = create(:payment_method) # flat rate calculator with preferred_amount of 0
```
Comment (mkllnk) [inline spec/models/spree/payment_method_spec.rb]: This is much better. Next time I would be tempted to convert the comment into code as well. Passing on the calculator may not be necessary, but if we rely on the calculator, we shouldn't trust the factory default. It would make the comment obsolete and still work if the default changed.

Comment (luisramos0) [reply spec/models/spree/payment_method_spec.rb]: yes agree.
in this case this is not a default factory, it's [a default value in the object](https://github.com/openfoodfoundation/openfoodnetwork/blob/c178478a4f0210133e98e0fbcc25a4d96943a300/app/models/spree/payment_method_decorator.rb#L47).
maybe I should have called it default_free_payment_method...

**Comment by luisramos0** [comment]
ah, yeah. the product form is not picking up the default product.on_demand value! I ignored that problem when I did the product_stock work because I knew I'd put this PR at some point. So, there is a problem there, the form doesnt pick up the default value. I think we can ignore.

File: spec/models/spree/product_spec.rb [hunk 2]
```diff
@@ -711,26 +711,6 @@ module Spree
...
-        end
-      end
-
-      context 'when the product has no variants' do
-        before { product.variants.destroy_all }
-
-        it 'returns the on_hand of the master' do
-          expect(product.on_hand).to eq(product.master.on_hand)
-        end
-      end
```
Comment (sauloperez) [inline spec/models/spree/product_spec.rb]: Are these cases covered elsewhere?

Comment (luisramos0) [reply spec/models/spree/product_spec.rb]: yes, it's mentioned in the commit message: product_stock_spec is doing exactly the same
