### PR TITLE
Make 'Clear All' button work on order cycle page

### LINKED ISSUE #2362: In OC interface the 'Clear All' button (to clear OC search terms or filters) does nothing
## Description
There's a button the OC interface which does nothing- this isn't good for users- can confuse them.

## Expected Behavior
If I'm searching or filtering in the OC interface and i click 'clear all' then my search terms and filters should be removed. 

## Actual Behavior
Nothing happens when you click 'clear all' 

## Steps to Reproduce
1. Login with an enterprise which has OCs
2. Search or filter within the OC listing page.
3. Click 'clear all' - this should clear the filters but it does nothing

## Animated Gif/Screenshot
https://www.useloom.com/share/6e6d2d4512fc4a9799cebbef7b5b9fa3?focus_title=1&muted=1

## Severity
s4

## Your Environment
Aus production
Chrome 
PC

## Possible Fix
Either make the button work, or remove it.

### PR DESCRIPTION
**Pull request by nikobozi**
#### What? Why?

Closes #2362 
The expected functionality (clearing filters) didn't work because there was no corresponding function in the controller.

#### What should we test?  

- Navigate to `/admin/order_cycles`  
- Apply some filters
- Click on 'Clear all' 
The filters should be reset to initial state

#### Release notes

Make 'Clear All' button work on admin order cycles page

### CODE REVIEW

File: app/assets/javascripts/admin/order_cycles/controllers/order_cycles_controller.js.coffee [hunk 1]
```diff
@@ -3,8 +3,12 @@ angular.module("admin.orderCycles").controller "OrderCyclesCtrl", ($scope, $q, C
...
   $scope.saveAll = -> OrderCycles.saveChanges($scope.order_cycles_form)
   $scope.ordersCloseAtLimit = -31 # days
-  $scope.involvingFilter = 0
-  $scope.scheduleFilter = 0
+
+  $scope.resetSelectFilters = ->
+    $scope.scheduleFilter = 0
+    $scope.involvingFilter = 0
+    $scope.query = ''
+  $scope.resetSelectFilters()
```
Comment (sauloperez) [inline app/assets/javascripts/admin/order_cycles/controllers/order_cycles_controller.js.coffee]: sorry @nikobozi, I'm not very angular-savy. When does this get executed? can you explain a bit?

Comment (luisramos0) [reply app/assets/javascripts/admin/order_cycles/controllers/order_cycles_controller.js.coffee]: it's when the controller is loaded @sauloperez

Comment (sauloperez) [reply app/assets/javascripts/admin/order_cycles/controllers/order_cycles_controller.js.coffee]: Great! thanks both!

**Comment by RachL** [comment]
Everything looks good ! Good job and welcome @nikobozi !
Testing notes:

https://docs.google.com/document/d/1Gw7Zy3xJsMboJRnTZinQ5OBJBxp_HqvD1DCI7KQqOdY/edit#

**Comment by sauloperez** [comment]
Congrats @nikobozi !

**Comment by nikobozi** [comment]
thanks :)
