### PR TITLE
Bug/4592 - Hide Environment column on Payment Methods page when user is not admin

### LINKED ISSUE #4592: Payment Methods Table in Dashboard does not display in Plain Language
## Description
Table showing Payment Methods in Dashboard includes non-intuitive language that would not make sense to a customer. eg. Spree::PaymentMethod::Check, Environment: Production 

## Expected Behaviour
Table fields should display information in plain language

## Actual Behaviour
Log in as an Enterprise
Access Dashboard
Select Payment Methods 
Click on Manage Payment Methods button

## Animated Gif/Screenshot

Screen Shot 2019-12-12 at 4 50 01 PM

## Workaround
Table is still visible, but much of the information is meaningless to a customer

## Severity
S4

## Your Environment

Australian Instance

### PR DESCRIPTION
**Pull request by jeduardo824**
#### What? Why?

Closes #4592 

On the table in the Payment Methods page, we have a column "Environment" that is kind of "tech-oriented" information. This PR hides the column when the user is not an admin.

#### What should we test?
Check if the column "Environment" is displayed when the user is admin and hidden when it is not.

#### Release notes

Hide the column "Environment" from the Payment Methods page in the admin section when the user is not a super admin.

Changelog Category: Changed

### CODE REVIEW

File: spec/support/request/authentication_workflow.rb [hunk 1]
```diff
@@ -37,6 +37,18 @@ def create_enterprise_user( attrs = {} )
...
+    new_user = build(:user, attrs)
+    new_user.spree_roles = [Spree::Role.find_or_create_by!(name: 'admin')]
+    new_user.save
+    if attrs.key? :enterprises
+      attrs[:enterprises].each do |enterprise|
+        enterprise.users << new_user
+      end
+    end
+    new_user
+  end
```
Comment (luisramos0) [inline spec/support/request/authentication_workflow.rb:50]: This would work but it's not needed. I looked around to find how this should be done.
There's a :admin_user factory, you can simply do:

`allow(view).to receive_messages spree_current_user: create(:admin_user)`

I realized we should delete this create_enterprise_user method and so I created this PR that cleans up a few things related to this topic :+1: 

This test in this PR can still just use the user factory :+1:

File: spec/views/spree/admin/payment_methods/index.html.haml_spec.rb [hunk 2]
```diff
@@ -19,10 +21,52 @@ def object_url(object = nil, options = {}) "" end
...
+        allow(view).to receive_messages spree_current_user: create_enterprise_user
+      end
+
+      it "shows only the providers of the existing payment methods" do
+        render
+
+        expect(rendered).to have_content "Cash/EFT/etc. (payments for which automatic validation is not required)", count: 2
+      end
+
+      it "does not show Enviroment column when user is not admin" do
```
Comment (sauloperez) [inline spec/views/spree/admin/payment_methods/index.html.haml_spec.rb:35]: you can avoid `when user is not admin` because that's exactly what this test's context says

File: spec/views/spree/admin/payment_methods/index.html.haml_spec.rb [hunk 3]
```diff
@@ -19,10 +21,52 @@ def object_url(object = nil, options = {}) "" end
...
+        render
+
+        expect(rendered).not_to have_content "Environment"
+      end
+
+      it "does not show column content when user is not admin" do
```
Comment (sauloperez) [inline spec/views/spree/admin/payment_methods/index.html.haml_spec.rb:41]: ditto

File: spec/views/spree/admin/payment_methods/index.html.haml_spec.rb [hunk 4]
```diff
@@ -19,10 +21,52 @@ def object_url(object = nil, options = {}) "" end
...
+        allow(view).to receive_messages spree_current_user: create(:admin_user)
+      end
+
+      it "shows only the providers of the existing payment methods" do
+        render
+
+        expect(rendered).to have_content "Cash/EFT/etc. (payments for which automatic validation is not required)", count: 2
+      end
+
+      it "does not show Enviroment column when user is not admin" do
```
Comment (sauloperez) [inline spec/views/spree/admin/payment_methods/index.html.haml_spec.rb:59]: and here it seems a copy & paste leftover

File: spec/views/spree/admin/payment_methods/index.html.haml_spec.rb [hunk 5]
```diff
@@ -19,10 +21,52 @@ def object_url(object = nil, options = {}) "" end
...
+        render
+
+        expect(rendered).to have_content "Environment"
+      end
+
+      it "does not show column content when user is not admin" do
```
Comment (sauloperez) [inline spec/views/spree/admin/payment_methods/index.html.haml_spec.rb:65]: and here too

File: spec/views/spree/admin/payment_methods/index.html.haml_spec.rb (hunk 2 above)
Comment (jeduardo824) [reply spec/views/spree/admin/payment_methods/index.html.haml_spec.rb]: Done

File: spec/views/spree/admin/payment_methods/index.html.haml_spec.rb [hunk 6]
```diff
@@ -19,10 +21,52 @@ def object_url(object = nil, options = {}) "" end
   end
 
   describe "payment methods index page" do
-    it "shows only the providers of the existing payment methods" do
-      render
+    context "when user is not admin" do
+      before do
+        allow(view).to receive_messages spree_current_user: create_enterprise_user
```
Comment (luisramos0) [inline spec/views/spree/admin/payment_methods/index.html.haml_spec.rb:26]: this PR needs rebasing. the helper is now AuthenticationHelper and create_enterprise_user is gone. It should be simply
create(:user)

Comment (jeduardo824) [reply spec/views/spree/admin/payment_methods/index.html.haml_spec.rb]: Done

**Review by luisramos0 — APPROVED** [review]
awesome, thank you!

**Review by sauloperez — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hi @jeduardo824 ,

I checked that the Environment column was visible both as Admin (see pic below) and as Superadmin, in the Payment Methods page (/admin/payment_methods).

image

After staging the PR, it was observed that the Environment column was hidden from Payment Methods (pic below):

image



...but remained visible, when logged-in as Superadmin (pic below):
image

All good here! :tada: 
Thank you Eduardo.
