### PR TITLE
Admin, Enterprise creation : set visibility to "Hidden" by default

### LINKED ISSUE #9123: Inconsistent default visibility setting, for newly created enterprises
## Description

Follow-up from #9087.
See Slack [thread](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1650640081691859) .

After this PR and for newly created enterprises:
- The default value in the DB for the `Enterprises` table, column `visible` is `t`
- However, after #9087 valid values are `hidden`, `only_through_links` and `public`
- This leads to having newly created enterprises invisible till one of the radio buttons is selected (and a valid value is attributed to `visible`)
- EDIT, added from #10038: Enterprises are invisible both in the enterprise list AND on the map, after creation

## Expected Behavior

For newly created enterprises:
- The default value in the DB for the `Enterprises` table, column `visible` should be ~~`public`.~~ Edit: ~~`hidden`~~ `only_through_links`.
(Updated following [discussion on Slack](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1651255901800579?thread_ts=1650640081.691859&cid=C02TZ6X00)).
- The UI should have the "Not Visible" radio-button selected

## Actual Behaviour

For newly created enterprises:
- The default value in the DB for the `Enterprises` table, column `visible` is `t`.
- The UI has no radio-button selected
- After creation, enterprises are invisible both in the enterprise list AND on the map

## Steps to Reproduce

1. Create an enterprise; note the id
2. Check the entry on the DB for that enterprise
3. Notice the default value in the DB for the `Enterprises` table, column `visible` is `t`.
4. Notice no radio button is selected on the enterprise "Primary details" page

## Animated Gif/Screenshot

image

## Severity

This seems harmless, but it's worth investigating as discussed on the [slack thread](https://openfoodnetwork.slack.com/archives/C02TZ6X00/p1650645939262759?thread_ts=1650640081.691859&cid=C02TZ6X00) .

## Your Environment

* Version used: v4.1.27
* Browser name and version: Firefox 99
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #9123

Capture d’écran 2023-07-20 à 11 20 24

###### As an admin
- As a admin, create an enterprise
- Check that its visibility is set to `only_through_links` (ie. "Hidden" in the UI) by default
###### As a user
- As a user, create an enterprise
- Check that its visibility is set to `only_through_links` (ie. "Hidden" in the UI) by default

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
Excellent!

File: db/schema.rb [hunk 1]
```diff
@@ -233,7 +233,7 @@
     t.boolean "enable_subscriptions", default: false, null: false
     t.integer "business_address_id"
     t.boolean "show_customer_names_to_suppliers", default: false, null: false
-    t.string "visible", limit: 255, default: "public", null: false
+    t.string "visible", default: "only_through_links", null: false
```
Comment (dacook) [inline db/schema.rb:236]: I guess a later version of Rails doesn't specify a default limit anymore.
We could actually set a much smaller limit, but I don't know how much this helps optimise the db. Probably not worth it.

File: spec/factories/enterprise_factory.rb [hunk 2]
```diff
@@ -14,6 +14,7 @@
     description { 'enterprise' }
     long_description { '<p>Hello, world!</p><p>This is a paragraph.</p>' }
     address
+    visible { 'public' }
```
Comment (dacook) [inline spec/factories/enterprise_factory.rb:17]: I guess this is for backwards-compatibility with specs assuming this value? 
If so, I think it would have been better to specify it in the specs themselves (they are now using a context with a non-default value). Perhaps the specs might need updating to test the default value too.

**Review by dacook — APPROVED** [review]
We have a minor inconsistency with the spec factory now, but it probably isn't worth changing 👍

File: spec/factories/enterprise_factory.rb (hunk 2 above)
Comment (jibees) [reply spec/factories/enterprise_factory.rb:17]: > I guess this is for backwards-compatibility with specs assuming this value?

Yes. 

> If so, I think it would have been better to specify it in the specs themselves (they are now using a context with a non-default value).

I had hesitation yes ... I chose the easiest solution, but maybe not the best one... I will change that if you think it's better. Maybe will create a new trait for that.

**Comment by filipefurtad0** [comment]
Hey @jibees ,

A very quick test - I'll have to explore this result a bit better - but after:
- staging the PR
- creating an enterprise (from an existing customer)

I've noticed there still is no option pre-set:

image

Checking the DB:

```
openfoodnetwork=> select visible from enterprises where id = 2520;
 visible 
---------
 t
(1 row)
```

I'll test other scenarios but it seems not to be doing what we'd expect - or maybe

**Comment by jibees** [comment]
Whoo. Super strange.

> creating an enterprise (from an existing customer)

i've tested with the super-admin user I guess. What about you? Maybe this produce a difference?

**Comment by filipefurtad0** [comment]
> i've tested with the super-admin user I guess. What about you?

Indeed, creating an enterprise via superadmin (`/enterprises`, clicking the `+ New Enterprise` button), works:

image

I was not explicit about this when the issue was opened, apologies - I did not consider this possibility, still learning about the app :see_no_evil:

I considered only, the case in which a user wishes to create its own enterprise. This process starts by clicking this tab, on the homepage, after logging in:

image

So, I'd propose to merge this PR, and leave the issue open, to account for enterprises created from users, sounds good @jibees ?

**Comment by jibees** [comment]
> So, I'd propose to merge this PR, and leave the issue open, to account for enterprises created from users, sounds good @jibees ?

hummm ... I think I'd prefer manage this case in the same PR. Maybe there will be some interaction between them, and I rather treat within the same context. Back into `In Dev` then (if it's ok for you)

**Comment by filipefurtad0** [comment]
Sure - that's good too. I've indicated the relevant file and added a couple of lines to test the upcoming fix in [this PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/11267).

**Comment by jibees** [comment]
Back in `Code Review` since things have changed in the meantime. 3 more commits to do this.

**Review by dacook — APPROVED** [review]
Looks good! The defaults for creating an enterprise were different before, but now all the same:

* Admin
* Frontend ("register here")
* API v0

I can't find any documentation for enterprises on API v0 so there's nothing to update  ;)

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @jibees.
staging is failing on UK and AU (haven't tried FR). Could this be a problem with the migration, which may have run on those servers already?

Anyway, here are my notes BEFORE staging this PR for later reference.

## Test scenarios
Enterprises can be created
- as enterprise user
  - on /register page (link in the footer banner)
  - on /enterprises page (?)
- as super admin user
  - on /register page (link in the footer banner)
  - on /enterprises page (?)
- as new user (logged out)
  - on /register page (link in the footer banner)
- via API v0?

Enterprises should show/not show
- on the /map page
- on the /shops page
- on the /producers page
- as a reference in the profile of other enterprises

## Database BEFORE staging
Check DB before staging the PR

Staging AU
```
openfoodnetwork=> SELECT visible, count (visible) FROM enterprises GROUP BY visible;
      visible       | count 
--------------------+-------
 t                  |     4
 public             |  1089
 only_through_links |  1368
 f                  |     2
(4 rows)

openfoodnetwork=> SELECT visible, id, name, email_address FROM enterprises WHERE visible = 't';
 visible |  id  |     name      |             email_address             
---------+------+---------------+---------------------------------------
 t       | 2515 | Producer 3    | producer3@kon***
 t       | 2518 | Producer 5 AU | kunde7@kon***
 t       | 2520 | tapas shop    | fil***
 t       | 2519 | Mario's farm  | mar***
(4 rows)


openfoodnetwork=> SELECT visible, id, name, email_address FROM enterprises WHERE visible = 'f';
 visible |  id  |     name      |           email_address           
---------+------+---------------+-----------------------------------
 f       | 2511 | an enterprise | fil***
 f       | 2516 | Producer 4 AU | producer4@kon***
(2 rows)
```

Staging UK
```
openfoodnetwork=> SELECT visible, count (visible) FROM enterprises GROUP BY visible;
      visible       | count 
--------------------+-------
 t                  |    14
 public             |   857
 only_through_links |   933
 f                  |     7
(4 rows)

openfoodnetwork=> SELECT visible, id, name, email_address FROM enterprises WHERE visible = 't';
 visible |  id  |            name             |               email_address               
---------+------+-----------------------------+-------------------------------------------
 t       | 1847 | Mario's legacy farm         | ***@gmail.com
 t       |    4 | accounts and billing        | x
 t       | 1786 | Cranberry Farm              | ***@gmail.com
 t       | 1838 | External Non-Producer Hub 1 | non-producer@kon***
 t       | 1823 | 976rfk                      | 
 t       | 1824 | place                       | ***@gmail.com
 t       | 1827 | Melissa McNab               | ***@gmail.com
 t       | 1841 | Non-Producer Profile 1      | profile@kon***
 t       | 1795 | profile only                | ***@gmail.com
 t       | 1819 | Ghanoush's place            | ***@protonmail.com
 t       | 1853 | Sconeshop                   | ***@gmail.com
 t       | 1854 | TestDFC                     | ***@protonmail.com
 t       | 1782 | Tree Hub                    | ***@protonmail.com
 t       | 1822 | Kimchi Hub                  | ***@gmail.com
(14 rows)

openfoodnetwork=> SELECT visible, id, name, email_address FROM enterprises WHERE visible = 'f';
 visible |  id  |              name               |            email_address            
---------+------+---------------------------------+-------------------------------------
 f       | 1842 | External Producer Shop 2        | kunde5@kon***
 f       | 1845 | enterprise                      | ***@gmail.com
 f       | 1849 | name                            | ***@gmail.com
 f       | 1851 | Producer 3 UK                   | producer3@kon***
 f       | 1839 | External Non-Producer Hub 2     | non-producer@kon***
 f       | 1840 | External Non-Producer Profile 1 | non-producer@kon***
 f       | 1825 | erg                             | ***@gmail.com
(7 rows)

```

- After the PR the default in the DB should be 'only_through_links' (before it was 'public').

## User interface BEFORE staging
- The UI should have the "Not Visible" radio-button selected

I can confirm that for `visible =t` and `visible = f` in the DB no radio button is selected:
image
image

If you have any ideas regarding the failing staging process let me know please. Thanks!

**Comment by filipefurtad0** [comment]
> staging is failing on UK and AU (haven't tried FR). Could this be a problem with the migration, which may have run on those servers already?

Yes, it seems this was the case @drummer83 : [after deleting the migration](https://app.gitbook.com/o/-L9rgjXCVdbnhSow2XnR/s/-M7NnFH2urYVKG6zlEtN/testers-toolkit/re-running-migrations) and re-deploying, it's good to test :+1:

**Comment by filipefurtad0** [comment]
Hey @jibees ,

However, creating an enterprise as admin leads to the expected result

image

However, creating an enterprise from the homepage, still does not lead to the expected result:

image

Maybe there is something fishy with the PR / deployment?

I've just looked at the code at the staging server, and it seems that it does not have the most recent version - I've looked at the spec file:

This PR:
image

The staging server:
image

This is despite our message in devops channel:
https://openfoodnetwork.slack.com/archives/CEF14NU3V/p1690458870444589

And the success logs on GH actions:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/5680130353/job/15393633414?pr=11247

**Comment by filipefurtad0** [comment]
Wait... Maybe something else got staged in the meantime? ping @Matt-Yorkley :sweat_smile: 
image

Uff - that's a relief. This looked way too mysterious for this time of the day. I'll try again later :wink:

**Comment by filipefurtad0** [comment]
New enterprises, created via:

- superadmin

image

- logging in as user:

image

Have the default `hidden` option selected :tada: 


Previously created enterprises seem not to be changed by this PR / data migration:

image


I'd say this brings improvement and is good to ship.

We seem to have 4 options... while the UI only displays three:

```
openfoodnetwork=> SELECT visible, count (visible) FROM enterprises GROUP BY visible;
      visible       | count 
--------------------+-------
 only_through_links |   937
 t                  |    15
 public             |   856
 f                  |     7
(4 rows)

```
In staging-FR we have a 5th option:
```
openfoodnetwork=> SELECT visible, count (visible) FROM enterprises GROUP BY visible;
      visible       | count 
--------------------+-------
 only_through_links |  1177
 hidden             |     4
 t                  |    21
 public             |  1531
 f                  |    22
(5 rows)
```

The PR does not change this. I'd say we can do this DB cleanup elsewhere - please shout @jibees if you see this as a blocker for some reason. Merging!
