### PR TITLE
Revoke transaction fee if there is an amount to be credited in order

### LINKED ISSUE #3490: When crediting an order the transaction fee is applied when it shouldn't
## Expected Behavior
I have an order which was paid in full with Stripe. Then I removed an item from the order, putting the order in Credit. I tried to refund this credit using the Credit button. I found that when the credit was applied, the transaction fee that the shop has on Stripe payments was applied to the credit. 

I would not expect a payment method transaction fee to be applied to a credit event.

## Actual Behaviour
The credit event incurred the transaction fee.

## Steps to Reproduce
1. Place an order in a shop and pay with Stripe- where stripe has a payment method fee associated (e.g $5)
2. Go to Orders in the backend and take one item from the order, putting it into credit
3. Go to edit the order and go to payments. Click the credit button.
4. See that the credit was applied but the transaction fee was also applied.

## Animated Gif/Screenshot
image

## Workaround

The new workaround for this bug is to stop doing partial refunds through OFN or if the partial refund is done through OFN do a negative adjustments and refund through stripe :face_with_head_bandage: 

## Context
I'm trying to do a partial refund from the backend.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
Product, Aus, Chrome, PC, Desktop

## Possible Fix
Credit event should not carry fee.

### PR DESCRIPTION
**Pull request by apricot12**
#### What? Why?

Closes #3490 

It seems, the revoking of transaction fee for certain situations is handled by :

```Ruby
    def ensure_correct_adjustment
      revoke_adjustment_eligibility if ['failed', 'invalid', 'void'].include?(state) 
      return if adjustment.try(:finalized?)

      if adjustment
        adjustment.originator = payment_method
        adjustment.label = adjustment_label
        adjustment.save
      elsif payment_method.present?
        payment_method.create_adjustment(adjustment_label, self, true)
        adjustment.reload
      end
    end
```
<s>But I'm facing a a problem : 
**Once I add `|| can_credit?` to the ` revoke_adjustment_eligibility if ['failed', 'invalid', 'void'].include?(state) ` condition, only the first credit is succesful without a transaction fee applied and all subsequent credits have the fee applied.** 

And even though 'credit' seems to be a valid state, adding it to the state conditions seems to have no effect. </s>

We  can ensure that the payment method fee adjustment is not created by adding the condition  `return if order.payment_state == 'credit_owed` to the `ensure_correct_adjustment` method.

#### What should we test?
- There should be no transaction fee/payment method fee applied for crediting an amount.

#### Release notes
- Transaction fee is not applied when crediting an order.

Changelog Category: Technical changes

### CODE REVIEW

**Comment by apricot12** [comment]
@jibees Since you've worked on this block of code before, maybe you'll have some insight?

**Comment by jibees** [comment]
Hey @apricot12 !
I've worked on it, and yes, it's tricky. Take everything I said here _with a grain of salt_.

I don't think this code is good, because of all the failing tests here. What I would do:
 - Create an automatic test, that recreate the described scenario in the linked issue. I think the place to do this is `spec/models/spree/payment_spec.rb` on line `#383` and should look like this (this code isn't right, take it just as a canva) : 
```ruby
        context "if payment method has any adjustments", :debug do
          let!(:payment_method) { create(:payment_method, calculator: ::Calculator::FlatRate.new(preferred_amount: 10)) }

          before do
            payment.update!(payment_method: payment_method)
            payment.save!
          end

          it "should not applied any transaction fees" do
            payment.credit!
            expect(order.all_adjustments.payment_fee.eligible.length).to eq(0)
          end
        end
```
 - Then, correct the test. I don't think the test (`can_credit?`) is the right one since it only test that the payment allow some credit. I since it's more around the method `credit` on file `app/models/spree/payment/processing.rb#78`. 
 
 Sorry, I don't know if it's really helpful, but here's my 2 cents.

File: app/models/spree/payment.rb [hunk 1]
```diff
@@ -141,7 +141,7 @@ def payment_source
 
     def ensure_correct_adjustment
       revoke_adjustment_eligibility if ['failed', 'invalid', 'void'].include?(state)
-      return if adjustment.try(:finalized?)
+      return if adjustment.try(:finalized?) || order.payment_state == 'credit_owed'
```
Comment (mkllnk) [inline app/models/spree/payment.rb:144]: This should work in most cases, but checking the state could go wrong. In theory, we could trigger another payment while credit is owed. Then we would owe even more. It doesn't seem to make sense at first but maybe we want to check if a payment goes through before adding an item.

Anyway, I think that the underlying assumption is that we don't pay transaction fees on refunds, no matter what the state of the order is. I would guess that we can check `amount <= 0`.

It also looks to me as if `revoke_adjustment_eligibility` would make sense in this case. So maybe it could look like this:
```rb
    def ensure_correct_adjustment
      revoke_adjustment_eligibility if failed_or_refund?
      ...
    end

    def failed_or_refund?
      ['failed', 'invalid', 'void'].include?(state) || amount <= 0
    end
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
Good work on finding the right code part to do this. I had an idea for an improvement (comment below). And I think that this should be covered by a spec. It's always a good idea to write a spec to re-produce a bug and then fix it. In this case, a model spec should be enough.

File: app/models/spree/payment.rb (hunk 1 above)
Comment (apricot12) [reply app/models/spree/payment.rb:144]: @mkllnk `revoke_adjustment_eligibility` looked like the obvious choice here, but it doesnt get executed when we use conditions like `amount <=0`, `order.payment_state == 'credit_owed` or `order.payment_state == paid`. These only work with the return keyword. I'm not exactly sure why 🤔

Comment (mkllnk) [reply app/models/spree/payment.rb:144]: I don't understand. The `revoke_adjustment_eligibility` should finalise the adjustment and the next line returns if the adjustment if finalised:
https://github.com/openfoodfoundation/openfoodnetwork/blob/1cbb0d8bbd8ee5d18405cf15c2e0992e336436e8/app/models/spree/payment.rb#L170-L178
https://github.com/openfoodfoundation/openfoodnetwork/blob/1cbb0d8bbd8ee5d18405cf15c2e0992e336436e8/app/models/spree/payment.rb#L143-L144

Can you write a spec first? Then we have an example to experiment with and you can show me what you mean.

**Comment by apricot12** [comment]
@mkllnk After using debugger, It's this line:

**Comment by apricot12** [comment]
@mkllnk After using debugger, it's at line #175 that the execution of revoke_adjustment_eligibility stops when using argument `amount <= 0`:
https://github.com/openfoodfoundation/openfoodnetwork/blob/72193848a1d7d5350d3819d8fbbbe52756325d0e/app/models/spree/payment.rb#L175-L176

But as you can see from the specs, both of these conditions are supposed to be passing. I'm not sure what exactly is going on in this scenario? Is it because once the adjustment is made when you credit, it go's into the `closed` state?

**Review by mkllnk — COMMENTED** [review]
Thanks for the spec! That's very helpful. It looks like we don't have an adjustment yet when this code is called. The states `'failed', 'invalid', 'void'` refer to a changing payment while a refund payment is a new one. I didn't think of that. So my previous suggestion doesn't work.

I'm wondering if we prevent the adjustment creation instead. We code change `CalculatedAdjustments` but then it needs to know the difference between payments and other things with adjustments. Not good.

Maybe it's enough to modify this method here further down to avoid the creation of an adjustment:

https://github.com/openfoodfoundation/openfoodnetwork/blob/72193848a1d7d5350d3819d8fbbbe52756325d0e/app/models/spree/payment.rb#L150

```diff
-      elsif payment_method.present?
+      elsif amount.positive? &&  payment_method.present?
```

I saw in CalculatedAdjustments that some adjustments are mandatory and then we need to add a `0` amount adjustment but we can assume that no transaction fees are mandatory at this stage. Not adding an adjustment is much easier.

Would that work?

**Comment by apricot12** [comment]
@mkllnk Yes not creating the adjustment itself definitely works, and from what I've seen of the related code not adding payment adjustment when refunding shouldn't really affect anything else.

 OH so when we're credit some amount back, It's a whole new payment! I didn't think of it that way though it seems so obvious to me now. 

I'll update the commits and change up the specs a little bit 👍

File: app/models/spree/payment.rb [hunk 2]
```diff
@@ -140,19 +140,23 @@ def payment_source
...
         adjustment.label = adjustment_label
         adjustment.save
-      elsif payment_method.present?
+      elsif amount.positive? && payment_method.present?
         payment_method.create_adjustment(adjustment_label, self, true)
         adjustment.reload
       end
     end
 
+    def failed_or_refund?
```
Comment (mkllnk) [inline app/models/spree/payment.rb:156]: This method name is now outdated.

**Review by mkllnk — CHANGES_REQUESTED** [review]
Almost there.

**Review by mkllnk — APPROVED** [review]
Looks good to me.

**Comment by Matt-Yorkley** [comment]
Great! I rebased and added a couple of "review-commits" to tighten up the tests a bit and increase the clarity. I left some notes in the commit messages :ok_hand:

What do you think of this change: https://github.com/openfoodfoundation/openfoodnetwork/pull/8689/commits/8084ad00689e3eddb34bdc90b20a886d96d75e69? 

There's an old saying in Software Development: 
> "Today, only you and god understand your code. In six months, only god will understand your code."

I try to keep this in mind when I'm writing bits of code, and ask myself: "if I come back to this in 6 months when I've completely forgotten all the surrounding context, will it make sense or will I have to find the issue and read all the notes before I can figure out why it's there?" Trying to make my code self-explanatory and idiot-proof is a valuable strategy, especially because the idiot is usually _me_, in the future. :sweat_smile:

**Review by Matt-Yorkley — APPROVED** [review]
:+1:

**Comment by apricot12** [comment]
@Matt-Yorkley Haha that change is actually great. It provides all the context one would need from just from the name! 

I'll keep it in mind to make everything as idiot proof as possible in future.

**Comment by filipefurtad0** [comment]
Hey @apricot12 ,

Before this PR:

- removing an item
- issuing a partial refund
- charges a second transaction fee

image

After this PR:

Peek 2022-02-21 20-28

We can see that the second fee is not charged. Great work :muscle:
