### PR TITLE
Stabilise flaky spec with defined enterprise order

### LINKED ISSUE #10055: [Flaky] Order dependent failure rspec ./spec/system/admin/enterprises/index_spec.rb:83
### What we should change and why (this is tech debt)

Order dependent failure:

`bundle exec rspec --format progress --default-path spec "spec/system/admin/tag_rules_spec.rb" "spec/system/admin/enterprises/index_spec.rb"
`

```

Failures:

  1) Enterprises Index as an admin user editing enterprises in bulk with data that violates rules does not update the enterprises and displays errors
     Failure/Error: expect(second_distributor.owner).to_not eq d_manager
     
       expected: value != #<Spree::User id: 75, email: "michaela@mcglynn.info", persistence_token: nil, perishable_token: nil, ...terprise_limit: 1, locale: nil, disabled_at: nil, show_api_key_view: false, provider: nil, uid: nil>
            got: #<Spree::User id: 75, email: "michaela@mcglynn.info", persistence_token: nil, perishable_token: nil, ...terprise_limit: 1, locale: nil, disabled_at: nil, show_api_key_view: false, provider: nil, uid: nil>
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -#<Spree::User id: 75, email: "michaela@mcglynn.info", persistence_token: nil, perishable_token: nil, last_request_at: nil, login: "michaela@mcglynn.info", ship_address_id: nil, bill_address_id: nil, created_at: "2022-11-25 01:41:13.312166774 +0000", updated_at: "2022-11-25 01:41:13.312166774 +0000", authentication_token: "xxxx166934047389675xxxxxxxxxxxxx", spree_api_key: nil, api_key: nil, enterprise_limit: 1, locale: nil, disabled_at: nil, show_api_key_view: false, provider: nil, uid: nil>
       +#<Spree::User id: 75, email: "michaela@mcglynn.info", persistence_token: nil, perishable_token: nil, last_request_at: nil, login: "michaela@mcglynn.info", ship_address_id: nil, bill_address_id: nil, created_at: "2022-11-25 01:41:13.312166000 +0000", updated_at: "2022-11-25 01:41:13.312166000 +0000", authentication_token: "xxxx166934047389675xxxxxxxxxxxxx", spree_api_key: nil, api_key: nil, enterprise_limit: 1, locale: nil, disabled_at: nil, show_api_key_view: false, provider: nil, uid: nil>
```

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3544677610/jobs/5952175489

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #10055 

This spec would fail when a certain number of enterprises were created before this spec. Enterprise names are generated continuously from Enterprise 1, Enterprise 2 etc. The second enterprise in this spec could be displayed above the first one due to the alphabetical sorting. Examples: "10, 9" or "90, 89". But the spec assumes that it's always the second enterprise which can't be assigned an owner and that assumption wasn't true when the second enterprise was updated first.

#### What should we test?

- Specs only.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/enterprises/index_spec.rb [hunk 1]
```diff
@@ -39,8 +39,7 @@
       let!(:d_manager) { create(:user, enterprise_limit: 1) }
 
       before do
-        d_manager.enterprise_roles.build(enterprise: d).save
-        expect(d.owner).to_not eq d_manager
+        d.users << d_manager
```
Comment (dacook) [inline spec/system/admin/enterprises/index_spec.rb]: Enterprise owners are always users, so I guess this assignment would fail if somehow the manager was already the owner.

File: spec/system/admin/enterprises/index_spec.rb [hunk 2]
```diff
@@ -35,11 +35,11 @@
     end
 
     context "editing enterprises in bulk" do
-      let!(:d){ create(:distributor_enterprise, sells: 'none') }
-      let!(:d_manager) { create(:user, enterprise_limit: 1) }
+      let!(:distributor){ create(:distributor_enterprise, sells: 'none') }
+      let!(:mani) { create(:user, enterprise_limit: 1) }
```
Comment (dacook) [inline spec/system/admin/enterprises/index_spec.rb:41]: I don't understand the `mani` reference..

**Review by dacook — CHANGES_REQUESTED** [review]
Great, however one variable name confuses me..

File: spec/system/admin/enterprises/index_spec.rb (hunk 2 above)
Comment (mkllnk) [reply spec/system/admin/enterprises/index_spec.rb:41]: Hm, it's just a name. At some point I found it helpful to use real names for users as suggested by Myriam:

* https://community.openfoodnetwork.org/t/personas-lets-name-our-users/1135 <- that's from the first gathering a bit over five years ago Kirsten was referring to on Monday.

But that probably works better with more common names. Do you have any suggestions?

File: spec/system/admin/enterprises/index_spec.rb (hunk 1 above)
Comment (mkllnk) [reply spec/system/admin/enterprises/index_spec.rb]: Yes, it does fail: `Validation failed: That role is already present.`

File: spec/system/admin/enterprises/index_spec.rb (hunk 2 above)
Comment (dacook) [reply spec/system/admin/enterprises/index_spec.rb:41]: Oh wow, they're nice pictures. In this case I guess a distributor would be a Mary or Shannon? A common name would help, but only for those whom it is common to..

Hmm I appreciate a bit of creativity and fun in specs, but I would try to avoid indirection most of the time. I would find `distributor_user` or simply `user` much easier to follow. 

🤷  Naming things is hard.

Comment (filipefurtad0) [reply spec/system/admin/enterprises/index_spec.rb:41]: Agree with @dacook.

I usually add real names (more or less common) where these can actually be seen and found by Capybara in the app (for example a first- and last-name on the customers page or so).

Since these are variables I'd say `distributor_user` or  `user` are easier to follow and perhaps clearer on what type of entity we're aiming at, when we create it in the spec.

**Review by filipefurtad0 — APPROVED** [review]
Thanks for this fix, I found it very challenging myself.
I don't have any additional comments on the code except on the naming (as David mentioned).
Thanks :muscle:

File: spec/system/admin/enterprises/index_spec.rb (hunk 2 above)
Comment (mkllnk) [reply spec/system/admin/enterprises/index_spec.rb:41]: Okay, I think that I will rename it to `manager` because that's more specific than `user` in this context. It's where the spec begins. But what I find difficult with this is that roles can change over the course of the example. This manager is becoming an owner in one example. It's okay here because the owner can still manage as well. If someone adds a test for the removal of the user then we may have a problem with the naming. But we can worry about that then.

**Review by dacook — APPROVED** [review]
👍

**Comment by dacook** [comment]
Specs pass, so I think this is ready to go. Please correct me if not!
