### PR TITLE
Change date displayed on sales_tax reports

### LINKED ISSUE #5306: Tax report is showing order.created_at instead of completed_at
## Description

When looking at the report `/admin/reports/sales_tax` the date shown is `order.updated_at`, we need it to be set at `completed_at` which would then be the same date as shown in `/admin/orders?q[s]=completed_at+desc`. 

## Steps to Reproduce
1. Connected as a manager, check the dates of the report `/admin/reports/sales_tax`

2. See some of them are different from `/admin/orders?q[s]=completed_at+desc` for the same order number

## Animated Gif/Screenshot
Example in French production :

Order page:

image

Tax report:

image

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment
* Version used: v2.9.5
* Browser name and version: Firefox 76
* Operating System and version (desktop or mobile):Desktop

### PR DESCRIPTION
**Pull request by pacodelaluna**
#### What? Why?
Closes #5306 

I just change the date called on the report generation, from `created_at` value to `completed_at` value, on Sales Tax reports and Order And Distributor reports.
The format is more consistent with codebase, hiding the part related to time zone.

#### What should we test?
On Sales Tax reports (accessible on `/admin/reports/sales_tax`) and Order And Distributor reports (accessible on `/admin/reports/order_and_distributors`), you need to check that the `completed_at` value is displayed on the `Date` column. ANd with a readable format, like `2020-05-02 01:51:49`.

#### Release notes
- Put completed_at date on Sales Tax reports and on Order And Distributor reports

Changelog Category: Changed

### CODE REVIEW

**Comment by pacodelaluna** [comment]
I was also trying to format the date using `I18n.l` but this may change the output on the CSV export and I am scared of some side effects. Tell me if it is safe and I will update it.

File: lib/open_food_network/sales_tax_report.rb [hunk 1]
```diff
@@ -57,7 +57,7 @@ def table
           totals = totals_of order.line_items
           shipping_cost = shipping_cost_for order
 
-          [order.number, order.created_at, totals[:items], totals[:items_total],
+          [order.number, order.completed_at, totals[:items], totals[:items_total],
```
Comment (luisramos0) [inline lib/open_food_network/sales_tax_report.rb:60]: in this thread: https://github.com/openfoodfoundation/openfoodnetwork/pull/5325/files#r417325953
we agreed with can always use the date format like this:
order.completed_at.strftime("%F %T")
are you ok with this? can you add the formatting?

We also have this problem in lib/open_food_network/order_and_distributor_report.rb
do you mind fixing it there as well?

**Comment by pacodelaluna** [comment]
@luisramos0 Just updated with your format suggestion. Tell me if any issue.

**Comment by luisramos0** [comment]
Nice, thanks @pacodelaluna 
The order distributor report needs a line in the PR description in "What to test"
That report change is breaking the build, the spec needs to be adjusted.

**Comment by Ekow244** [comment]
Tests Notes here:https://docs.google.com/document/d/1d6HvIQNN32zN9K553VRNMzntAY0an9yU81cGD6fJcyk/edit# 
Tests have passed and PR can be merged @pacodelaluna
