### PR TITLE
[Rails 5.2] Fixed change in rails 5.2 in callbacks attribute_changed?

### LINKED ISSUE #7258: [Rails 5.2] acts_as_list
### What we should change and why (this is tech debt)

We have various classes that use the **acts_as_list** gem, and they currently have some kind of weird issue. This applies to various things like unit value names, product properties, etc. The objects representing those items are not being created or saved for some reason?

Bumping the gem requires Ruby 2.4.7+, but I tried this and bumped both Ruby and the gem, and it made no difference.

Example error:
```
36) Spree::Product variant units when the product already has a variant unit set (and all required option types exist) removes the old option type and assigns the new one
      Failure/Error: expect(p.option_types).to eq([ot_volume])
      
        expected: [#<Spree::OptionType id: 1046, name: "unit_volume", presentation: "Volume", created_at: "2021-03-27 19:13:51", updated_at: "2021-03-27 19:13:51", position: 670>]
             got: #<ActiveRecord::Associations::CollectionProxy []>
      
        (compared using ==)
      
        Diff:
        @@ -1 +1 @@
        -[#<Spree::OptionType id: 1046, name: "unit_volume", presentation: "Volume", created_at: "2021-03-27 19:13:51", updated_at: "2021-03-27 19:13:51", position: 670>]
        +[]
        
      # ./spec/models/spree/product_spec.rb:769:in `block (4 levels) in <module:Spree>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #7258

#### What should we test?
No errors like 7258

#### Release notes

Changelog Category:  | Technical changes
Adapt code to rails 5.2

### CODE REVIEW

**Review by andrewpbrett — APPROVED** [review]

File: app/models/spree/product.rb [hunk 1]
```diff
@@ -455,7 +455,7 @@ def add_primary_taxon_to_taxons
     end
 
     def remove_previous_primary_taxon_from_taxons
-      return unless primary_taxon_id_changed? && primary_taxon_id_was
+      return unless saved_change_to_primary_taxon_id? && primary_taxon_id_was
```
Comment (Matt-Yorkley) [inline app/models/spree/product.rb:458]: Is this `#primary_taxon_id_was` still okay..? :thinking:

Comment (Matt-Yorkley) [reply app/models/spree/product.rb:458]: I notice there's still a lot of failing model specs for Product related to the taxon....

**Review by Matt-Yorkley — APPROVED** [review]

File: app/models/spree/product.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/models/spree/product.rb:458]: Nice spot, 43a38cdaa4cb110995bc01ea2807a35d16263261
