### PR TITLE
Handle checkout as guest feature on split checkout

### LINKED ISSUE #8668: Checking out as a guest
## Description

On the new split-checkout feature,  guest users are not prompted to either login or checking out as guest (if allowed by the shop) and are always able to checkout.

## Expected Behavior

When visiting a shop as a guest:
- If a shop **does not** allow guest checkout, the customer is redirected to this screen

- If a shop **does** allow guest checkout, the customer is redirected to this screen

## Actual Behaviour

Guest users are not prompted to either login or checking out as guest (if allowed by the shop) and are always able to checkout.

## Steps to Reproduce

As a guest customer:
1. Visit a shop which allows guest-checkout
2. Add items to the cart and proceed to checkout (you should be on `/checkout` page)

3. On a different session, log in as the admin and change the setting to require customer log-in. This is set in `/admin/enterprises/<enterprise_name>/edit#!/shop_preferences`.

Go back to your customer session and:
4. Visit the same shop, now not allowing guest-checkout
5. Add items to the cart and proceed to checkout (`/checkout` page) 

6. Notice how in both cases the user is able to proceed to the first step of the split checkout `1 - Your details`

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #8668

This PR handles the _checkout as guest feature_ on the new split checkout.

No design specifications found, screenshots must be reviewed by @openfoodfoundation/train-drivers-product-owners :

Capture d’écran 2022-01-05 à 16 30 59

Capture d’écran 2022-01-05 à 16 30 54

Capture d’écran 2022-01-05 à 16 43 10

##### As anonymous user, when distributor authorize checkout as guest
1. Add product to cart
2. Go to checkout, then you must be redirected to `/checkout/guest`
3. Then you can either _Login_ or _Checkout as guest_
4. _Checkout as guest_ redirect to `/checkout/details`

##### As anonymous user, when distributor _doesn't_ authorize checkout as guest
1. Add product to cart
2. Go to checkout, then you must be redirected to `/checkout/guest`
3. Then you can only _Login_
4. Each URL under `/checkout` (such as  `/checkout/details`) redirects to `/checkout/guest`

##### As connected user
1. Add product to cart
2. Go to checkout, then you must be redirected to `/checkout/details`

#### Release notes
Handle checkout as guest feature on split checkout
Changelog Category: User facing changes

### CODE REVIEW

**Comment by RachL** [comment]
LGTM :+1:

File: app/controllers/split_checkout_controller.rb [hunk 1]
```diff
@@ -16,10 +16,14 @@ class SplitCheckoutController < ::BaseController
   helper OrderHelper
 
   def edit
-    redirect_to_step unless params[:step]
+    return redirect_to_step unless params[:step]
+
+    return redirect_to_guest if !@order.distributor.allow_guest_orders? && params[:step] != "guest"
```
Comment (achauve) [inline app/controllers/split_checkout_controller.rb:21]: The logic here seems not straightforward. Should `redirect_to_guest` rather be named `redirect_to_guest_or_login`?

**Review by achauve — APPROVED** [review]
LGTM!
As it's the first PR I review on checkout and split checkout I'm a bit lost in the controller logic and not sure about the names, but the tests look good so it should be good!

File: app/controllers/split_checkout_controller.rb (hunk 1 above)
Comment (jibees) [reply app/controllers/split_checkout_controller.rb:21]: Maybe.
The point here is that the step itself is named `guest` (and then the view is also named `guest`). And this method redirect to that URL/view, that's why.
You're right, it's more `not logged`, `disconnected`, `anonymous` but I guess it's not that beautiful in the url ... If you have any proposals?! 🙏

Comment (achauve) [reply app/controllers/split_checkout_controller.rb:21]: If I understand well, the "guest view" the user is redirected to won't display guest but only the login option in this case, as guest is disabled is this distributor. So I think it would be clearer if the step and view were named something like "authentication" (with two choices guest/anonymous and logged_in_user). But I suppose it's quite out of the scope of this PR... :D

Comment (jibees) [reply app/controllers/split_checkout_controller.rb:21]: `redirect_to_guest` is also used to redirect to `/checkout/guest` when distributor allow guest order, ie. a view when you can see login and checkout as user:
Capture d’écran 2022-01-05 à 16 34 27


I can rename it to `authentication` if it's much clear for everyone ;-)

**Review by Matt-Yorkley — COMMENTED** [review]
I'm wondering if we could make this a bit simpler by just handling it with an overlay instead of handling it in the controller?

Like: you visit the checkout page and the form is (conditionally) covered up by that "Ok, ready to checkout?" view with the two buttons. If you click the "Checkout as guest" the overlay gets removed (we can use StimulusJS for that) and you immediately see the form, otherwise you log in...  which I think will refresh the page anyway (which will automatically remove the overlay).

Know what I mean?

**Comment by jibees** [comment]
Yes, why not. I guess it's more a UX improvement since the code should be (more or less) the same in the backend ie defend with a redirect if the user enter directly the URL (or POST on the URL). 

I don't know if this is simpler (although I'm a big fan of frontend solution ;))

**Comment by jibees** [comment]
> If we handle it in the frontend I was thinking we could probably just drop the changes to the routes and the extra controller logic?

Yes, dropping the changes for the routes and the controller, but those logic should appear somewhere (ie. _Should I display the form or this anonymous overlay?_). I think it's done here right? `app/assets/javascripts/darkswarm/controllers/checkout/checkout_controller.js.coffee`

**Comment by Matt-Yorkley** [comment]
I was thinking we could just do it directly in the view, eg wrap the form [here](https://github.com/openfoodfoundation/openfoodnetwork/blob/6f47619c5a5a73986f271b9ed247ee23fa316438/app/views/split_checkout/_form.html.haml#L4-L6) and find out what should be shown using [guest_checkout_allowed?](https://github.com/openfoodfoundation/openfoodnetwork/blob/6f47619c5a5a73986f271b9ed247ee23fa316438/app/helpers/checkout_helper.rb#L8-L10) and add a StimulusJS controller to handle the show/hide behaviour?

**Review by mkllnk — APPROVED** [review]
Looks good.

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Thanks for addressing this and the detailed testing notes, going through them:

1.a) As anonymous user, when distributor authorize checkout as guest

    Add product to cart
    Go to checkout, then you must be redirected to /checkout/guest
`    Then you can either Login or Checkout as guest` -> **Customer checks out as guest**
    Checkout as guest redirect to /checkout/details

Peek 2022-01-12 20-06

This is OK, we're all good here :+1: 

1.b) As anonymous user, when distributor authorize checkout as guest

`Then you can either Login or Checkout as guest` -> **Customer logs-in**

Peek 2022-01-12 20-06_

We can see above, that after logging in the customer should be redirected to the `/checkout/details` section. Instead, the customer is redirected to the homepage, after logging in. While the items in the cart are kept, this is probably disruptive for the checkout process -> I'll open an issue for this :+1: 

2) As anonymous user, when distributor doesn't authorize checkout as guest

```
    Add product to cart
    Go to checkout, then you must be redirected to /checkout/guest
    Then you can only Login
    Each URL under /checkout (such as /checkout/details) redirects to /checkout/guest
```

This is OK, as well, however, logging in redirects to the home page (similarly as the video above).

3) As connected user

```
    Add product to cart
    Go to checkout, then you must be redirected to /checkout/details
```

All good for the logged in user :+1: 

I'll merge this, and open a separate issue for 1.b)
