### PR TITLE
Patch #6469: use `purchase` to charge offline for Stripe Connect

### LINKED ISSUE #6543: 3D-Secure cards not charged when placing subscriptions with Stripe SCA payment method
## Description

PR #6469 introduces changes on the setup and offline charging for subscriptions.

Before this PR, orders placed through subscriptions with Stripe SCA in combination with an authenticated 3D-Secure card (such as 4000002760003184) are not charged, and return the error - seen on the emails to the customer/hub:

`Invalid payment state`

After this PR, the customer can proceed to the authentication in  in the customer section `/account#/cards` of that card. However, placing the order results in an uncharged card, returning the error, via Email:

`Your card was declined. This transaction requires authentication. `

This introduces a regression, see discussion:
https://openfoodnetwork.slack.com/archives/CSCPHGVSS/p1608203766100600

## Expected Behavior

Stripe-SCA charges from 3D-auth cards should allow the placement of subscriptions.

## Actual Behaviour

Stripe-SCA charges from 3D-auth cards currently do not allow the placement of subscriptions.

## Steps to Reproduce

Customer
1. Add the 3D-secure card `4000002760003184` to the /account#/cards section.
2. Allow charges to a given hub
3. The authentication window should pop-up. Confirm authentication for that card.

Admin
1. Set up an OC, with a schedule - take note of the OC id number
2. Create a subscription for the customer above, setting the Stripe SCA as a payment method (optional: take note of the subscription id number)

Test the placement of the set subscription, following the procedure described:
- here https://github.com/openfoodfoundation/openfoodnetwork/wiki/Testing-Subscriptions (you'll need both OC and Subscription id nr.)
- or following #6291 - (you'll need the OC id nr.) a fix is underway for this, which reduces the waiting time, after the confirmation of the subscription (#6541)

## Your Environment

* Version used: this would be introduced in upcoming v3.4.5
* Browser name and version: Firefox 83
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Fixes a regression discovered in #6469 where subscriptions were not working for Stripe Connect

Closes #6543 

#### What should we test?
Charging a subscription that is set up with Stripe Connect.

#### Release notes
n/a

### CODE REVIEW

**Review by sauloperez — CHANGES_REQUESTED** [review]
IMO we should add unit test but also some sort of integration.

File: spec/jobs/subscription_confirm_job_spec.rb [hunk 1]
```diff
@@ -134,6 +134,48 @@
...
+        end
+      end
+
+      context "Stripe Connect" do
+        let(:stripe_connect_payment_method) { create(:stripe_connect_payment_method) }
+        let(:stripe_connect_payment) { create(:payment, amount: 10, payment_method: stripe_connect_payment_method) }
+
+        before do
+          allow(order).to receive(:pending_payments) { [stripe_connect_payment] }
+          expect(stripe_connect_payment_method).to receive(:charge_offline)
```
Comment (mkllnk) [inline spec/jobs/subscription_confirm_job_spec.rb:170]: This doesn't test if the method `charge_offline` actually exists. This test passes regardless of your fix. Your other unit test covers that though. I found that less mocking / more integration testing reveals more bugs and needs fewer changes when refactoring code.

**Review by mkllnk — APPROVED** [review]
Looking good!

File: spec/jobs/subscription_confirm_job_spec.rb (hunk 1 above)
Comment (andrewpbrett) [reply spec/jobs/subscription_confirm_job_spec.rb:170]: Ah, yeah. Good point!

File: spec/jobs/subscription_confirm_job_spec.rb [hunk 2]
```diff
@@ -134,6 +134,48 @@
...
+          .to_return(charge_response_mock)
+      end
+
+      context "Stripe SCA" do
+        let(:stripe_sca_payment_method) { create(:stripe_sca_payment_method) }
+        let(:stripe_sca_payment) { create(:payment, amount: 10, payment_method: stripe_sca_payment_method) }
+
+        before do
+          allow(order).to receive(:pending_payments) { [stripe_sca_payment] }
+          expect(stripe_sca_payment_method).to receive(:charge_offline)
```
Comment (sauloperez) [inline spec/jobs/subscription_confirm_job_spec.rb:156]: this is the actual assertion of the test so it should rather be within the `it` block IMO. https://thoughtbot.com/blog/four-phase-test is a good article on this topic.

File: spec/jobs/subscription_confirm_job_spec.rb (hunk 1 above)
Comment (sauloperez) [reply spec/jobs/subscription_confirm_job_spec.rb:170]: See my comment above

Comment (andrewpbrett) [reply spec/jobs/subscription_confirm_job_spec.rb]: Definitely agree. I updated the Connect spec 3f39d23dcba7c0b437e0dfdd1290987f826e5dcd and also the SCA spec f7a00dc0d97d4d8a0fb9c27c667051af9a0da9ca

File: spec/jobs/subscription_confirm_job_spec.rb (hunk 2 above)
Comment (andrewpbrett) [reply spec/jobs/subscription_confirm_job_spec.rb]: That was a lot of head scratching for what turned out to be a change in tense 😂 - e749f75b10cd79cfc13780eba8b2182a9d1021d0

File: spec/jobs/subscription_confirm_job_spec.rb [hunk 3]
```diff
@@ -134,6 +134,50 @@
...
+      end
+
+      context "Stripe SCA" do
+        let(:stripe_sca_payment_method) { create(:stripe_sca_payment_method) }
+        let(:stripe_sca_payment) { create(:payment, amount: 10, payment_method: stripe_sca_payment_method) }
+
+        before do
+          allow_any_instance_of(Stripe::CreditCardCloner).to receive(:find_or_clone) { ["cus_123", "pm_1234"] }
+          allow(order).to receive(:pending_payments) { [stripe_sca_payment] }
+          expect(stripe_sca_payment_method.provider).to receive(:purchase) { true }
```
Comment (sauloperez) [inline spec/jobs/subscription_confirm_job_spec.rb:157]: This needs to be a method stub with `allow` as you did at line 171

**Comment by andrewpbrett** [comment]
I am seeing that lone test failure pass locally, but it is consistent across builds on Semaphore.

**Review by sauloperez — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey Andy,

I've placed a few orders using subscriptions, with some different testing cards/settings:

**1)** Order R454757432
Payment Method: **Stripe Connect**
Card: Visa | x-4242 | 04/2044; **3D-Secure: No**

This worked now, the issue seems fixed!

**2)** Order R277107505
Payment Method: **Stripe SCA**
Card: Visa | x-4242 | 04/2044; **3D-Secure: No**

All good.


At this point, I switched the card to a 3D-Secure one, under the customer's `/account#/cards`, and repeated the subs placement:

**3)** Order R758411716
Payment Method: **Stripe SCA**
Card: Visa | x-3184 | 03/2033; **3D-Secure: Yes**

Payments are failing for 3D-Secure cards, as already pointed out while testing #6469 . The email indicates the following:
_Here are the details of the failure provided by the payment gateway: Your card was declined. This transaction requires authentication._ 

**4)** Order R585525364
Payment Method: **Stripe SCA**
Card: Visa | x-3178 | 12/2020; **3D-Secure: Yes - Card with insufficient funds**

Same as in test case 3) payment fails due to bad authentication - expected `insufficient funds` message.

I think test cases 3) and 4) are out of scope of this PR and something to be tackled seperately. 
This is good to go!

**Comment by lin-d-hop** [comment]
Thanks @filipefurtad0 

Re Test Case 3
For this roll out of SCA this failure indicates that we need to ask the user to reauth their card in /accounts

Re Test Case 4 
Do we expect an insufficient funds message here? I would have thought that the reauth error is correct

**Comment by filipefurtad0** [comment]
Test cases 3) and 4) were performed after the authentication step, under the customers `/account#/cards`. All looks good there, the window pops-up and one can confirm authentication for both cards (or click "Fail Authentication"). But so far, I could not observe a successful payment with a 3D-secure card, when placing subscriptions.

Regarding 4) I think authentication should work with the specific card used used in this test - it should trigger this specific error:

`4000008260003178 | This card requires authentication for one-time payments. All payments will be declined with an insufficient_funds failure code even after being successfully authenticated or previously set up.`

It just looks to me as if authentication is not working properly for subscriptions yet. Is this a requirement for PR #6469?

**Comment by lin-d-hop** [comment]
Ah thanks @filipefurtad0.
So this is a patch on top of #6469?
That is troubling then.

**Comment by andrewpbrett** [comment]
Hi @filipefurtad0 - thanks for the testing notes! I noticed that you used the card x-3184 for Case 3; in the Stripe docs it says: "This card requires authentication on all transactions, regardless of how the card is set up."

There is another card available for testing, which x-3155, which says "This card requires authentication for one-time payments. However, if you set up this card and use the saved card for subsequent off-session payments, no further authentication is needed. In live mode, Stripe dynamically determines when a particular transaction requires authentication due to regional regulations such as Strong Customer Authentication."

That second card is the one I tested with and the one I would expect to be able to be charged for a subscription. Is there any chance you could try step 3 again with that card?

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

Thanks for that advice! I'll retest again, considering card 4000002500003155 (a one off payment card) :crossed_fingers:
And place the results in this issue.

**Comment by filipefurtad0** [comment]
So, I checked this scenario with:

**a)** the card you pointed out `4000002500003155`

I'm still get the same error:
`Here are the details of the failure provided by the payment gateway: Your card was declined. This transaction requires authentication. `

**b)** I repeated the test for the one off payment card 4000008260003178. As on my testing notes above, this triggers the same authentication error.

**c)** I tried the card below as, which may be the appropriate one for this scenario:

`4000003800000446 | This card requires authentication for one-time and other on-session payments. However, all off-session payments will succeed as if the card has been previously set up.
`-- | --

This payment **works** with this card, using Stripe SCA. It is charged when placing subscriptions. This seems to me as the only off session testing card. So, it's great that it works under this scenario.


Are we sure this should work with card tested in a) , i.e. 4000002500003155?
