### PR TITLE
Cancel empty orders on BOM page

### LINKED ISSUE #8131: BOM: Deleting last item (trash-bin icon and selecting/deleting) leads to an empty order
## Description

Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/7627
Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/7637
Follow-up from https://github.com/openfoodfoundation/openfoodnetwork/pull/8040

Please note that this bug can be addressed together with #7637 or separately.

There were **two missing scenarios** which led to empty orders as well; while on the BOM it is possible to delete the last item of an order by:
-  clicking the trash-bin icon
-  selecting one or more items and deleting via the global action button "Delete Selected" (#7637)

## Expected Behavior

**Updated**

Clicking the trash icon or selecting on last item of an order and using the "Delete Selected" button:
- should **display a modal text** similar to the one implemented by #8040 but changing the text to "deleting this item will cancel the order as it is the last line item, do you wish to proceed: yes/no".
- selecting "yes" should **cancel the order** -> changing the order status to `cancelled` and shipment status to `none` 

## Actual Behaviour

While on the BOM it is possible to delete the last item of an order by clicking the trash-bin icon and by selecting one or more items and deleting via the global action button "Delete Selected"

## Steps to Reproduce

As admin:
1. Visit `/admin/orders/bulk_management`
2. Click the trash-bin icon to delete the last item of an order 

## Animated Gif/Screenshot

Peek 2021-09-03 09-16

## Workaround

- Edit the order and add items back to the order (reverses the deletion and makes the order accessible to the custumer)
- Manually cancel the order on the respective order edit page

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.0.1
* Browser name and version: Firefox 90
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Possible Fix

See Expected Behavior section.

### PR DESCRIPTION
**Pull request by guidoDutra**
#### What? Why?

Closes #8131 

Deleting all line items from an order on BOM (bulk order management) page will open a confirm modal. If accepted, the order will be canceled.
Obs:
* Applicable for deleting a single line item using the trash icon or for deleting multiple items at once with the "Actions" dropdown (see issue #8131)
* Multiple orders can be cancelled at once. In this scenario a single confirmation modal will be opened.
* A single generic message is being used in both scenarios: "This operation will result in one or more empty orders, which will be cancelled. Do you wish to proceed?" This can be changed if needed.
* Currently it's not possible to see what order(s) will be canceled when deleting line items. Further layout changes might be needed for this functionality

#### What should we test?
Deleting all items from an order should cause the confirm modal to open, and if accepted the order should be canceled.
* must be applicable for both scenarios described in #8131 (delete trash icon and "Actions" dropdown)
* must be able to delete multiple orders at once

#### Release notes
Removing all line items from an order in BOM page will cause order to be cancelled.

Changelog Category: User facing changes

### CODE REVIEW

File: app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee [hunk 1]
```diff
@@ -104,15 +104,38 @@ angular.module("admin.lineItems").controller 'LineItemsCtrl', ($scope, $timeout,
...
+    for item in lineItemsToDelete
+      { order } = item
+      deleteCount.set(
+        order,
+        (deleteCount.get(order) ? 0) + 1)
+      if (order.item_count == deleteCount.get(order))
+        ordersToCancel.push(order)
+    return ordersToCancel
+
+  $scope.cancelOrder = (order) ->
```
Comment (guidoDutra) [inline app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee:119]: This method for cancelling orders is used elsewhere in the codebase. However, it doesn't change cancelled order's shipment status (as described in issue #8131: selecting "yes" should cancel the order -> changing the order status to `cancelled` and shipment status to `none`. Is this ok? Or am I missing something?

**Comment by guidoDutra** [comment]
Just updated the PR to meet criteria discussed above. On another note: @Matt-Yorkley had suggested that I move the logic for `deleteLineItems` to the backend, in order to avoid unresolved operations due to lost connection. I think with the latest changes there should be no issue, since there is no asynchronous operation except for the page refresh, but Matt please advise if you still think that's applicable.
I did try to make that change, but I was a bit confused as to where that function should be placed in the backend (what controller it should be at), and how to access it (angularjs $http service?). Please let me know if you know the answer to that

File: app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee [hunk 2]
```diff
@@ -104,15 +104,50 @@ angular.module("admin.lineItems").controller 'LineItemsCtrl', ($scope, $timeout,
     else
       StatusMessage.display 'failure', t "unsaved_changes_error"
 
+  $scope.getOrdersToCancel = (lineItemsToDelete) ->
```
Comment (mkllnk) [inline app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee:107]: It looks like you replaced this logic and now you don't need this function any more. Is that correct?

Comment (guidoDutra) [reply app/assets/javascripts/admin/line_items/controllers/line_items_controller.js.coffee:107]: that's correct, sorry about that. Will remove later today

**Comment by filipefurtad0** [comment]
Thank you so much for keeping up on this one @guidoDutra :muscle: 
I think we're pretty close. I'll move to in Dev for this last change, feel free to push it to code review after the latest changes :+1:

**Comment by guidoDutra** [comment]
> Thank you so much for keeping up on this one @guidoDutra muscle I think we're pretty close. I'll move to in Dev for this last change, feel free to push it to code review after the latest changes +1

Hey @filipefurtad0, just fixed it. I'm not sure what you're refering to though, how can I move the PR status to "code review"? Is there a github project or someting like that?

**Comment by filipefurtad0** [comment]
> how can I move the PR status to "code review"

Ah right, maybe you can't see this option because the https://www.zenhub.io/ plugin is missing for your browser? But even if you do, you might not be able to do this because of access rights to the repo - this is fine, I've just moved it forward :+1: 

Thanks again.

**Review by mkllnk — APPROVED** [review]

**Comment by RachL** [comment]
Alright @guidoDutra thanks for all these updates. I think we are almost ready to go !

One question left : 

Have you added the text of the modal as a translation key? 

image


Also as mentioned before, we need to take care of the cancellation email before merging this improvement. Are you still up to work on it in a separate PR @guidoDutra ? I've updated the issue here : https://github.com/openfoodfoundation/openfoodnetwork/issues/8477

Let me know if there are any questions on the scope, we can discuss it within this new issue. 

Many thanks!

**Comment by Matt-Yorkley** [comment]
> Have you added the text of the modal as a translation key?

Yes, it's translated :ok_hand:

**Comment by guidoDutra** [comment]
Hey @RachL, sure, I can work on issue #8477. Will try to make a PR for that next week

**Comment by guidoDutra** [comment]
Hey @RachL, sorry for the delay, some things came up and I didn't have time to look into issue #8477 yet. I think I'd only be able to do it on January. Please feel free to assign it to someone else if its urgent

**Comment by RachL** [comment]
@jibees do we need to do something here now #8477 is merged or is this ready for testing?

**Comment by jibees** [comment]
> @jibees do we need to do something here now #8477 is merged or is this ready for testing?

giphy (1)

I'd say `Ready for testing`

**Comment by RachL** [comment]
Ok I'm not able to reproduce this: 

> cancelling orders from the BOM page does send the cancellation email.

Each time I delete the last item through BOM, the order gets cancelled but no email is sent to the customer.

If I go it on the order itself and delete the last item, the cancellation email is sent; so emails do work on staging FR (tested also confirmation emails etc).

I would go for merging this PR as is, it has been on hold for too long.

Then work on an issue harmonizing behavior between both pages (order page and BOM): 

1. Adding the modal @jibees did in https://github.com/openfoodfoundation/openfoodnetwork/issues/8477

2. Delete the last item in cancelled order too. Now if I delete the last item on the order the last item is removed and the order is cancelled. Through BOM the order is cancelled but the product remain. Both approach are valid, but having both behavior is a bit confusing?

Everyone ok with this plan?

**Comment by filipefurtad0** [comment]
> I'm not able to reproduce this

Could it be because the default behavior is not to send the email? I'm aware that the checkbox is not yet implemented in BOM, but maybe related to #8985.

In any case, agree with the plan you propose @RachL :+1:

**Comment by RachL** [comment]
@jibees here you go: https://github.com/openfoodfoundation/openfoodnetwork/issues/9028
