### PR TITLE
Cart dropdown now closes when clicking outside it.

### LINKED ISSUE #1255: Make cart more easily collapsible
Update by Myriam 21.05.2018

## Description
When a customer clicks on cart dropdown, but then want to do some other action, the cart dropdown doesn't collapse and disturb navigation, until the user undertands that she has to click again on the cart icon and do it.

## Expected Behavior
If I click outside the cart dropdown, the cart dropdown collapses.

## Actual Behavior
The cart can only be collapsed by clicking on the shopping cart icon, which is annoying.

## Steps to Reproduce
1. Add some items in your cart from any shopfront
2. Click on cart icon and see

## Animated Gif/Screenshot
image

On mobile, when a User has created a shopping cart with many items, they're forced to scroll back to the top of the page to close it and continue shopping
image

## Context
Cleaning up and specifying old issues.

## Severity
S4. It works as expected but is a pretty annoying UX bug so keeping it as a bug. I suspect it's good first issue but needs some dev to confirm that it's easy.

## Your Environment
Desktop + Mobile + Tablet
Aus/French production (retested by Myriam on French production)
Chrome

## Possible Fix
If the cart dropdown is expanded from header, it should close if user clicks outside of the dropdown.

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #1255

Warm-up PR for Mobile Ready work. The cart dropdown now closes when clicking outside of it! :tada:

#### What should we test?

The cart dropdown closes when clicking outside of it.

#### Release notes

Cart dropdown is now more easily collapsible

Changelog Category: Fixed

#### Animated GIF

omg-it-closes

### CODE REVIEW

File: app/assets/javascripts/darkswarm/directives/cart_toggle.js.coffee [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+      cart_button_clicked = (element_and_parents.indexOf(cart_button) != -1)
+
+      if cart_button_clicked
+        scope.$apply ->
+          scope.open = !scope.open
+      else
+        scope.$apply ->
+          scope.open = false
+
+      return
```
Comment (sauloperez) [inline app/assets/javascripts/darkswarm/directives/cart_toggle.js.coffee]: how difficult would it be to unit test this? I ask because I'm not used to stub $document and I don't know if it's tricky or not. I'd test it if possible.

Comment (Matt-Yorkley) [reply app/assets/javascripts/darkswarm/directives/cart_toggle.js.coffee]: I don't think we can test click events on nested DOM elements in `karma`?

Comment (sauloperez) [reply app/assets/javascripts/darkswarm/directives/cart_toggle.js.coffee]: No idea, tbh

**Comment by daniellemoorhead** [comment]
Yep, works good on a Mac in Chrome, FF, Safari.

Good to go!

**Comment by sigmundpetersen** [comment]
@daniellemoorhead you can use Browserstack to test on mobile as well. Credentials in Bitwarden, maybe @RachL can help with access there if you don't have it

**Comment by RachL** [comment]
@daniellemoorhead please let me know if I need the credentials again. As this touches the front office, we usually test mobile as well. Browserstack can help you also have a look at how it works on a windows machine. 
But this can also be checked during release testing if we want to merge anyway, ping @lin-d-hop

**Comment by Matt-Yorkley** [comment]
There's no cart dropdown on mobile yet :+1:

**Comment by daniellemoorhead** [comment]
And this why I only tested on desktop version 🤘🏻
