### PR TITLE
Sort orders by last name

### LINKED ISSUE #10116: [BOM] Orders sorted alphabetically by first name instead of last name
## Description
In Bulk Order Management (BOM) page, when sorting the orders by "Name", they are sorted alphabetically by first name instead of last name. 

## Steps to Reproduce
1. Pass 2 orders with names and first name beginning by different letters (for instance Aude Zoo and Bless You)
2. In BOM page (admin/orders/bulk_management), click on the table element "Name" to sort the orders alphabetically
3. See that they are sorted alphabetically by first name (Aude Zoo will appear before Bless You)

As a comparison, you can see in the "Orders" page and in the reports that they are sorted alphabetically by last name (Bless You will appear before Aude Zoo)

### BOM Page: alphabetically by first name
Screen Shot 2022-12-07 at 21 13 53

### Orders Page: alphabetically by last name
Screen Shot 2022-12-07 at 21 03 29

## Workaround
A producer who is using the packing report and the BOM page is doing this: "In order not to waste a lot of time looking for names in the list, I have to modify the 'packing' report on excel, select each different product and classify them each time by first name. I've been doing it for 3 years every week and I have to say that in the long run it's tedious."

## Severity
bug-s3: a feature is broken but there is a workaround

### PR DESCRIPTION
**Pull request by thejwuscript**
#### What? Why?

- Closes #10116 

Currently, orders can be sorted alphabetically by first name on the Bulk Order Management (BOM) page. However, this is causing inconvenience to producers who rely on the Packing report and Orders report, as they are spending additional time on file handling. Furthermore, the sorting method differs from the Orders page, where orders can be sorted alphabetically by last name.

This PR enables orders on the BOM page to be sorted alphabetically by last name. Also, names will be displayed in  "Last Name, First Name" format.

#### What should we test?

- Create at least 3 orders with names. Two orders must have the same last name. For example:
    - Williams, Bill
    - Williams, Bill Jr.
    - Smith, Kevin
- Visit the BOM page (http://localhost:3000/admin/orders/bulk_management) , and click on the table heading "Name"
- See that orders are sorted alphabetically by last name in ascending order
- Click on the table heading "Name" again
- See that orders are sorted alphabetically by last name in descending order

#### Screenshots
Ascending order:
sort asc

Descending order:

sort desc

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
This looks good to me! Thanks @thejwuscript !

Waiting for a second review now.

File: app/serializers/api/admin/order_serializer.rb [hunk 1]
```diff
@@ -17,6 +17,14 @@ def full_name
         object.billing_address.nil? ? "" : ( object.billing_address.full_name || "" )
       end
 
+      def first_name
+        object.billing_address.nil? ? "" : ( object.billing_address.first_name || "" )
```
Comment (abdellani) [inline app/serializers/api/admin/order_serializer.rb:21]: I think the following syntax is shorter (and will not make rubocup complain) 
```ruby
object.billing_address&.first_name || "" 
```

File: app/serializers/api/admin/order_serializer.rb [hunk 2]
```diff
@@ -17,6 +17,14 @@ def full_name
...
+      end
+
+      def last_name
+        object.billing_address.nil? ? "" : ( object.billing_address.last_name || "" )
```
Comment (abdellani) [inline app/serializers/api/admin/order_serializer.rb:25]: same here

File: app/views/spree/admin/orders/bulk_management.html.haml [hunk 3]
```diff
@@ -170,7 +170,7 @@
           %td.bulk
             %input{ :type => "checkbox", :name => 'bulk', 'ng-model' => 'line_item.checked', 'ignore-dirty' => true }
           %td.order_no{ 'ng-show' => 'columns.order_no.visible' } {{ line_item.order.number }}
-          %td.full_name{ 'ng-show' => 'columns.full_name.visible' } {{ line_item.order.full_name }}
+          %td.full_name{ 'ng-show' => 'columns.full_name.visible' } {{ line_item.order.last_name + ', ' + line_item.order.first_name }}
```
Comment (abdellani) [inline app/views/spree/admin/orders/bulk_management.html.haml:173]: I think we can continue to use `line_item.order.full_name` here.
`full_name` is slightly different.
```ruby
    def full_name
      "#{firstname} #{lastname}".strip
    end
```

Comment (dacook) [reply app/views/spree/admin/orders/bulk_management.html.haml:173]: Actually, this was discussed in the issue and the requirement is to display "last_name, first_name" because this better represents what is being sorted. (Don't worry, I had to read the entire comment history to find this out).

However, if the first or last name is blank, this could look funny. I have another suggestion..

**Review by dacook — CHANGES_REQUESTED** [review]
Thanks for picking this up!

This is a good improvement, but I'd like to suggest a slightly different approach.

Although we don't want to change behaviour elsewhere (yet), we can set up a way for the model to represent this value consistently that we can use in the future.

We actually already have a class dedicated to display formats here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/models/concerns/address_display.rb
In fact, it has a `full_name_reverse` method which is _almost_ what we want. It gracefully handles blank values. However it doesn't have a comma:

```ruby
[lastname, firstname].reject(&:blank?).join(" ")
```

Because this is already used in a report, we shouldn't change this format, but we can add a new one. Perhaps a name like `full_name_for_sorting` because we want to use this format whenever multiple names are listed together and sorted.

Then I think the javascript and serialiser can then just simply switch to this new method.

What do you think?

**Review by dacook — APPROVED** [review]
Great, looks good to me! 

I found one similar but unrelated spec was failing, which is really bizarre. So I went ahead and fixed it (eventually).

**Comment by drummer83** [comment]
Hi @thejwuscript,
Thanks for this PR! I have tested this before and after staging it on our servers.

### Before the PR
We can see that
- sorting by name sorts the entries by first name correctly.
- looking at the last names there is no specific order.

image

### After the PR
We can see that
- names are now displayed as Last name, First name :heavy_check_mark: 
- sorting by name sorts the entries by last name correctly :heavy_check_mark: 
image

I have also checked that
- sorting by name again sorts the entries descending instead of ascending :heavy_check_mark: 
- if the last name is identical, then the entries are sorted by first name :question: 
image
image

## Results
Seems to work perfectly! Thanks for this improvement! :tada: 
This one is ready to merge! :rocket: 

## Open issues
- Create issue to use the same ordering method on the /orders page.
- Create issue to include the order indicator on BOM page
