### PR TITLE
[Spree Upgrade] Create the default StockLocation in DB

### LINKED ISSUE #3253: [Spree Upgrade] Fix reference to backorderable_default from admin/products/new.html.haml
## Description

Our VariantStock module relies on the `Spree::StockLocation.first.backorderable_default` but in `2-0-stable` we don't create the default stock location yet.

This obviously causes a 500 error as follows:

```
...
Completed 500 Internal Server Error in 929.8ms (ActiveRecord: 34.8ms)
** [Bugsnag] No API key configured, couldn't notify

ActionView::Template::Error (undefined method `backorderable_default' for nil:NilClass):
    1: <%# This chunk is just a copy of Spree's backend/app/views/spree/admin/products/new.js.erb %>
    2: $("#new_product").html('<%= escape_javascript(render :template => "spree/admin/products/new", :formats => [:html], :handlers => [:haml]) %>');
    3: handle_date_picker_fields();
    4: <% unless Rails.env.test? %>
    5:   $('.select2').select2();
  app/models/concerns/variant_stock.rb:91:in `on_demand'
  app/models/concerns/variant_stock.rb:32:in `on_hand'
  app/models/concerns/product_stock.rb:19:in `on_hand'
  app/views/spree/admin/products/new.html.haml:57:in `block (2 levels) in _6397cc2bb50734c9d7283660ebd313d6'
  app/views/spree/admin/products/new.html.haml:53:in `block in _6397cc2bb50734c9d7283660ebd313d6'
  app/views/spree/admin/products/new.html.haml:3:in `_6397cc2bb50734c9d7283660ebd313d6'
  app/views/spree/admin/products/new.js.erb:2:in `_80cf50a20567230ea7daadc245fd7326'
  lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
  lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
...
```

## Expected Behavior
`products/new` page should render successfully without errors and allow users to specify a value for the stock level.

## Actual Behavior
The page fails to render raising the error showed above.

## Steps to Reproduce
1. Go to `/admin/products`
2. Click on `+ NEW PRODUCT`

## Possible Fix

We need to add a data migration that creates that default StockLocation. Once executed this should be fixed.

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Closes #3253

The data migration creates a StockLocation in the configured default country of the instance with the name "OFN default". Check https://github.com/openfoodfoundation/openfoodnetwork/wiki/Spree-Upgrade%3A-Stock-locations
for details.

After running it a rails console should output something like

```
pry(main)> Spree::StockLocation.all
=> [#<Spree::StockLocation id: 5, name: "OFN default", created_at: "2018-12-28 12:16:43", updated_at: "2018-12-28 12:16:43", address1: nil, address2: nil, city: nil, state_id: 58, state_name: nil, country_id: 109, zipcode: nil, phone: nil, active: true, backorderable_default: false, propagate_all_variants: true>]
```

Then, if you create a product you should be able to get that same location as follows

```
pry(main)> variant.stock_items.first.stock_location
=> #<Spree::StockLocation id: 5, name: "OFN default", created_at: "2018-12-28 12:16:43", updated_at: "2018-12-28 12:16:43", address1: nil, address2: nil, city: nil, state_id: 58, state_name: nil, country_id: 109, zipcode: nil, phone: nil, active: true, backorderable_default: false, propagate_all_variants: true>
```

#### What should we test?
It should be possible to create a product from /admin

### CODE REVIEW

**Comment by sauloperez** [comment]
Tested and working!

File: db/migrate/20181228115540_add_default_location.rb [hunk 1]
```diff
@@ -0,0 +1,11 @@
+class AddDefaultLocation < ActiveRecord::Migration
+  def up
+    country = Spree::Country.find_by_iso(ENV['DEFAULT_COUNTRY_CODE'])
+    state = country.states.first
+    Spree::StockLocation.create!(name: 'OFN default', country_id: country.id, state_id: state.id)
```
Comment (mkllnk) [inline db/migrate/20181228115540_add_default_location.rb]: Why did you go with `OFN default` instead of `default` as specified in the wiki? I don't really mind. I think we came up with `default`, because it's used by Spree sample data:
https://github.com/openfoodfoundation/spree/blob/f55722b38db7e706a8521c9091a0e00119bb4d20/sample/db/samples/stock.rb#L3

Comment (sauloperez) [reply db/migrate/20181228115540_add_default_location.rb]: I didn't know we stated its name in the wiki. I just wanted to differentiate from Spree's stuff.

How does that Spree code relate to OFN? AFAIK that's Spree's sample data and there is no default location as per its migrations.

**Comment by sauloperez** [comment]
Nice @mkllnk I had the same feeling while typing that code but with the default country but then I got lazy.

File: db/migrate/20181228115540_add_default_location.rb (hunk 1 above)
Comment (sauloperez) [reply db/migrate/20181228115540_add_default_location.rb]: for the record, openfoodfoundation/spree:sample/db/samples/stock.rb@f55722b#L3 is not executed with Spree's seed data (the one that we run when executing `bundle exec rake db:reset`) but from Spree's CLI, which I think is used to set up new Spree projects.

**Comment by sauloperez** [comment]
I also added a constraint at app level to restrict StockLocation to a single record. I couldn't find a way to do it at DB level as well though.

File: app/models/default_stock_location.rb [hunk 2]
```diff
@@ -0,0 +1,15 @@
+# Encapsulates the concept of default stock location that OFN has, as explained
+# in https://github.com/openfoodfoundation/openfoodnetwork/wiki/Spree-Upgrade%3A-Stock-locations
+class DefaultStockLocation
```
Comment (luisramos0) [inline app/models/default_stock_location.rb]: id prefer a service here, the more we avoid growing /models the better.

File: app/models/spree/stock_location_decorator.rb [hunk 3]
```diff
@@ -1,9 +1,19 @@
 Spree::StockLocation.class_eval do
+  validate :just_default_location
```
Comment (luisramos0) [inline app/models/spree/stock_location_decorator.rb]: i didnt get the "just" quickly. maybe ensure_single_stock_location is easier to understand?

File: spec/factories.rb [hunk 4]
```diff
@@ -645,9 +645,6 @@
 
 FactoryBot.modify do
   factory :stock_location, class: Spree::StockLocation do
-    # keeps the test stock_location unique
-    initialize_with { Spree::StockLocation.find_or_create_by_name(name)}
-
```
Comment (luisramos0) [inline spec/factories.rb]: are you sure this is not causing build errors?
I see "Validation failed: The default location already exists"

Comment (sauloperez) [reply spec/factories.rb]: Then we need to fix those because the violate a constraint.

**Comment by sauloperez** [comment]
The deeper I dig, the more complicated it gets... https://github.com/openfoodfoundation/spree/commit/2c48bfbaad

**Comment by luisramos0** [comment]
1.
I am not aware of how are we managing spree migrations... are we including all migrations that spree brings? has that been done for 2.0.4 already?

2.
The link you share shows that spree was already doing what you are doing in this PR.
So, does this PR become unnecessary?

**Comment by sauloperez** [comment]
> 1.

Yep, long ago. AFAIK there was an issue for it.

> 2.

We stepped onto each other. See my last comment.

**Comment by mkllnk** [comment]
@sauloperez Would you like to clean-up the commit history before we merge this? There are a couple of detours.

**Comment by luisramos0** [comment]
This is not ready to be merged.
we need to fix the 2 stock location specs and there is also a problem with spec/models/concerns/variant_stock_spec.rb:155
correct @sauloperez ?

**Comment by sauloperez** [comment]
Yep, and yes. I need to also cleanup the history.

**Comment by sauloperez** [comment]
This is ready now @luisramos0 @mkllnk

**Comment by luisramos0** [comment]
I think this is pending @mkllnk re-review, right?

File: spec/factories.rb [hunk 5]
```diff
@@ -656,8 +656,10 @@
 
 FactoryBot.modify do
   factory :stock_location, class: Spree::StockLocation do
+    name { 'default' }
```
Comment (mkllnk) [inline spec/factories.rb]: This name doesn't make sense when using "OFN default" via `DefaultStockLocation.find_or_create`.
