### PR TITLE
Display tax rate for shipping in alternative invoice model

### LINKED ISSUE #7934: Alternative invoice: Tax rate not displayed for shipping fee
## Description

Relates to #7892; closely related to #7932 and #7933.

The alternative invoice does not display the tax rate for a shipping fee, on the `Tax rate` column.

## Expected Behavior

The alternative invoice displays the tax rate an applied shipping fee, on the `Tax rate` column.

## Actual Behaviour

Currently, no information is displayed on this space (see pic below).
 
## Steps to Reproduce

Same 6 steps as in issue #7932.

7. As super admin, select the option "Use the alternative invoice model" under `/admin/invoice_settings/edit`
8. As admin, visit the order and click Print invoice -> notice the blank space on the `Shipping / Tax rate` table entry

## Animated Gif/Screenshot

image

## Workaround

Calculate these values manually.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.5.8
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Not sure of this one. Seems to correct the initial issue, but I'm wondering if I chose the right way to fix it. Adjustments are pretty complex, I'd be happy to have a review from @Matt-Yorkley on this one. 

Closes #7934

#### What should we test?
Well explained in issues #7932 and #7934:

1. Set a tax category for "Shipping"
2. Set a tax rate for "Shipping", with a given value. Select "included in the price"
3. Create a shipping method and associate it with the "Shipping" tax category
4. Create an order with the respective shipping method
5. Make sure the billing/shipping address fall into the respective Zone (for the Tax Rate)
6. Check the orders invoice and the order edit page, making sure the shipping tax has been included in the price -> this should show all your settings are correct
7. Click the Adjustments tab or visit /admin/orders/<order_number>/adjustments and notice that the Tax included in shipping fee is not displayed
8. As super admin, select the option "Use the alternative invoice model" under /admin/invoice_settings/edit
9. As admin, visit the order and click Print invoice
10. Shipping / Tax rate table entry should have the appropriate value.

Capture d’écran 2022-02-11 à 09 21 41

#### Release notes

Display tax rate for shipping in alternative invoice model

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by apricot12 — APPROVED** [review]
This is great! 💯

File: spec/services/tax_rate_finder_spec.rb [hunk 1]
```diff
@@ -22,6 +27,11 @@
       expect(rates).to eq [tax_rate]
     end
 
+    it "finds the tax rate of a shipping_method fee", :debug do
```
Comment (Matt-Yorkley) [inline spec/services/tax_rate_finder_spec.rb:30]:
```suggestion
    it "finds the tax rate of a shipping_method fee" do
```

**Review by Matt-Yorkley — APPROVED** [review]
LGTM :+1:

**Comment by jibees** [comment]
> Is it worth dropping the changes here that are already included in https://github.com/openfoodfoundation/openfoodnetwork/pull/8849 ?

Maybe once #8849 is merged?

**Comment by jibees** [comment]
> > Is it worth dropping the changes here that are already included in #8849 ?
> 
> Maybe once #8849 is merged?

as this is only relevant for the development mode (and works like a charm in a staging env.), i have dropped the commit and force-pushed. This is cleaner now. Thanks! 🙏

**Comment by filipefurtad0** [comment]
Ok, before:

- no associated tax rate showing
image

After:
- the associated tax rate is displayed
image

This was not the best example...

Ok this one is, the tax rate is displayed next to the shipping fee:

image

Merging!
