### PR TITLE
[WhiteLabel] Make update button active when changing custom tab content

### LINKED ISSUE #10946: [White Label, Trix editor] Changes on the custom tab content do not trigger the Update button
## Description

Relates to https://github.com/openfoodfoundation/openfoodnetwork/pull/10875 - point (2) on the testing notes.

An admin has a custom tab enabled for its shop; If changes are made to the contents of the custom tab, the Update is not activated, which makes it a not straightforward task to save these changes (see workaround).

## Expected Behavior

Changes on the custom tab content (Trix editor) should trigger the Update button, allowing the user to save changes.

## Actual Behaviour

Changes on the custom tab content (Trix editor) do not trigger the Update button, which makes saving changes a non-straight forward task (see workaround).

## Steps to Reproduce

As a hub

1. Create a custom tab
2. Add some text to it
3. Save your changes by using the (activated) Update button
4. Re-visit the White Label section and make some changes to your text
5. Notice the Update button was not activated

## Animated Gif/Screenshot

Peek 2023-06-06 15-41

## Workaround

Un-check and check the "Create custom tab in shopfront" checkbox. This _does_ trigger the Update button and allows the user to save changes.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.3.11
* Browser name and version: Firefox 113.2
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10946 

#### What should we test?

- As a shop manager, go to white label panel under your enterprise settings
- Edit the custom tab content (but no other field): the "update" button should not be disabled

#### Release notes

Changelog Category: User facing changes

### CODE REVIEW

File: spec/system/admin/enterprises_spec.rb [hunk 1]
```diff
@@ -774,6 +774,13 @@
               expect(page).to have_content("Custom tab content")
             end
 
+            it "enable the update button on custom tab content change" do
+              fill_in_trix_editor "custom_tab_content", with: "Custom tab content changed"
+              within "save-bar" do
+                expect(page).to have_button("Update", disabled: false)
+              end
```
Comment (dacook) [inline spec/system/admin/enterprises_spec.rb:781]: Can we go further and test that the content can be saved to the db?

Comment (jibees) [reply spec/system/admin/enterprises_spec.rb:781]: Yes! Done ;)

**Review by rioug — APPROVED** [review]
Looks good !

File: spec/system/admin/enterprises_spec.rb (hunk 1 above)
Comment (dacook) [reply spec/system/admin/enterprises_spec.rb:781]: 👏

**Review by dacook — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @jibees,
Perfect! The update button is now active as soon as anything changes in the description text field.

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/ec49cde3-ba77-45a3-9d5a-6eb6d9c97731

What else should I say? Merging! :muscle: :rocket:
