### PR TITLE
Hide shipped orders from BOM

### LINKED ISSUE #7457: Deleting line items from shipped orders is possible through Bulk Order Management page
## Description

Shipping an order removes the icons to edit the line item quantity (and shipping method details) from the UI, to prevent orders from being edited after shipping :+1: 

However, it is still possible to remove a line item through using bulk order management feature :-1: 

Attempting to change the stock for that line item triggers:
https://app.bugsnag.com/yaycode/openfoodnetwork/errors/60816e5b006e7d0007864736?event_id=60816e5b0077c2ac330c0000&i=sk&m=nw

Through the "Actions" menu one can remove the line item. Doing so introduces changes on the balance of the order. While this change is correctly reflected under admin/customers (admin view) and account#/transactions (customer view) one should notice that:

- if a (shipped) order is left with no line items, it will not appear on the `order_management/reports/bulk_coop` reports, which will lead to a misleading sum of customer balances.

## Expected Behavior

Line items from shipped orders should not be visible on the bulk order management page (right?)

## Actual Behaviour

Line items are appearing on the BOM page, which makes it quite tempting to edit:
- edit quantity -> bugsnag
- delete through the Actions menu -> customer balance discrepancies

## Steps to Reproduce

1. Create an order with **one line item**, add a payment and ship it. Take notice of the order number.
2. Notice that you can find this order on the on bulk order management reports (customer payments); check the balance for that customer (both on admin and customer side)
4. Now, look for the order on `admin/orders/bulk_management`
5. Try to edit the line item amount -> triggers bugsnag
5. Select (tick the checkbox) that line item and click the Actions menu -> Click "Delete Selected"
6. Notice that:
- customer balance changed (both on admin and customer side)
- the order does not appear on bulk order management reports
- you can visit the edit order page, but it displays a shipped order with no line items :-1: 

## Animated Gif/Screenshot

A shipped order. The UI does not allow to make changes here :+1

image

Trying to edit the line item amount:

image

The same order, after following the steps to reproduce:

image

## Workaround

Don't delete line items from shipped orders. However, nothing really tells you they are shipped, on the BOM page.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.5.7
* Browser name and version: Firefox 89
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

I think making line items from shipped orders not visible through Bulk Order Management list would solve this.

### PR DESCRIPTION
**Pull request by apricot12**
#### What? Why?

Closes #7457 

This change is needed so that there can't be any confusion caused be deleting already shipped orders through BOM.

#### GIF/Screenshot : 

BOM

#### What should we test?
- There should be no canceled or shipped orders visible in BOM.

#### Release notes
- Removed shipped orders from BOM page.

Changelog Category: User facing changes

### CODE REVIEW

File: app/services/permissions/order.rb [hunk 1]
```diff
@@ -44,7 +44,7 @@ def editable_line_items
     def filtered_orders(orders)
       return orders unless filter_orders?
 
-      orders.complete.not_state(:canceled).ransack(search_params).result
+      orders.complete.not_state(:canceled, :shipped).ransack(search_params).result
```
Comment (Matt-Yorkley) [inline app/services/permissions/order.rb:47]: I think we probably don't want to add this here. This class and it's methods are used in lots of other places in the codebase, where we want to show shipped orders. The changes to the search filters in `line_items_controller.js` should be enough?

Comment (apricot12) [reply app/services/permissions/order.rb]: You're right. The weird thing is, I added this in because it wasn't working the first time. I was probably mistaken though.

**Comment by Matt-Yorkley** [comment]
Alright, we'll have to update some of the specs to reflect these code changes :+1:

`spec/features/admin/bulk_order_management_spec.rb` will need updating a bit.

Our javascript specs are a bit weird. You should be able to run them locally with: `bundle exec rake karma:run`. You'll  need to make a little change around line 48 of `spec/javascripts/unit/admin/line_items/controllers/line_items_controller_spec.js.coffee` to fix this one:
```
Unexpected request: GET /api/v0/orders.json?q%5Bcompleted_at_gteq%5D=SomeDate&q%5Bcompleted_at_lt%5D=SomeDate&q%5Bcompleted_at_not_null%5D=true&q%5Bdistributor_id_eq%5D=&q%5Border_cycle_id_eq%5D=&q%5Bshipment_state_not_eq%5D=shipped&q%5Bstate_not_eq%5D=canceled
	   Expected GET /api/v0/orders.json?q%5Bcompleted_at_gteq%5D=SomeDate&q%5Bcompleted_at_lt%5D=SomeDate&q%5Bcompleted_at_not_null%5D=true&q%5Bdistributor_id_eq%5D=&q%5Border_cycle_id_eq%5D=&q%5Bstate_not_eq%5D=canceled
```

**Comment by apricot12** [comment]
@Matt-Yorkley I'm gonna get right on it then, boss. :ok_hand:

**Comment by Matt-Yorkley** [comment]
So most of our tests are written in **RSpec**. It takes a while to learn and lot longer to master, but it's pretty nice. Here's a nice intro: https://www.rubyguides.com/2018/07/rspec-tutorial/ and there's plenty of examples in the `spec/` folder :+1:

**Comment by apricot12** [comment]
@Matt-Yorkley Yeah I've written tests on Rspec before. So, when it comes to ``spec/features/admin/bulk_order_management_spec.rb``, I just have to add tests to check if shipped orders are visible or not, right?

**Comment by Matt-Yorkley** [comment]
> I just have to add tests to check if shipped orders are visible or not, right?

Well the first issue to look at is that there are 39 tests in that file that are currently **failing**. I'm guessing the test setup uses an order that's shipped, and maybe that just needs to be switched? (I haven't looked yet)

And then yes, a simple test which checks that line items from shipped orders don't show up on the page would be good :ok_hand:

**Comment by Matt-Yorkley** [comment]
> Also, should i be looking for relevant specs whenever I make changes to some code?

_Sometimes_ a change is fairly small and the relevant code already has good test coverage, and if the tests are passing then it's fine. Otherwise; any changes made in the code should usually have some accompanying changes in the tests :ok_hand:

File: config/initializers/sidekiq.rb [hunk 2]
```diff
@@ -1,4 +1,4 @@
-redis_jobs_url = ENV.fetch("OFN_REDIS_JOBS_URL", "redis://localhost:6381/0")
+redis_jobs_url = ENV.fetch("OFN_REDIS_JOBS_URL", "redis://localhost:6379/0")
```
Comment (Matt-Yorkley) [inline config/initializers/sidekiq.rb:1]: I know this is currently a bit annoying in dev, but we can't merge this change at the moment because it would break things in production and staging.

This is a good example of why we'll be adding Dotenv soon (which will help with these issues): https://github.com/openfoodfoundation/openfoodnetwork/issues/7745

Comment (apricot12) [reply config/initializers/sidekiq.rb:1]: @Matt-Yorkley I didnt actually mean to push it. I think it got in there when I merged remote with local. :sweat_smile:

Comment (apricot12) [reply config/initializers/sidekiq.rb:1]: I'll just change this, and do a squish. :ok_hand:

**Comment by Matt-Yorkley** [comment]
Great! There's a couple of things here that need looking at.

The first is a test that covers this change. So... we can add a new example like "does not show line items from shipped orders", and then set the test up with one order that's shipped and one that's not shipped, visit the page, and then verify the line item from the shipped order is not present and the line item from the unshipped order is present. Should be pretty simple :+1:

The second thing is that there's a failing test here relating to the datepickers. I pulled you PR and had a look, and it fails consistently. But then I switched to `master` and tried the same test, and it was also failing in `master` :disappointed: So it's probably not introduced by this PR, but it needs to be fixed. I might have a go at it separately...

**Comment by apricot12** [comment]
@Matt-Yorkley I think the latest push should add the test coverage for shipment state of line items. 

And with the failure related to date picker, are these the failing examples? 
```Ruby
      it "displays only line items whose orders meet the date restriction criteria, when changed" do
        find('#start_date_filter').click
        select_date_from_datepicker Time.zone.today - 8.days

        expect(page).to have_selector "tr#li_#{li1.id}"
        expect(page).to have_selector "tr#li_#{li2.id}"
        expect(page).to have_selector "tr#li_#{li3.id}"
        expect(page).to have_no_selector "tr#li_#{li4.id}"

        find('#end_date_filter').click
        select_date_from_datepicker Time.zone.today + 1.day

        expect(page).to have_selector "tr#li_#{li1.id}"
        expect(page).to have_selector "tr#li_#{li2.id}"
        expect(page).to have_selector "tr#li_#{li3.id}"
        expect(page).to have_selector "tr#li_#{li4.id}"
      end
```
Because all examples seem to pass on my end?
image

**Review by Matt-Yorkley — APPROVED** [review]
Awesome :muscle:

**Review by jibees — APPROVED** [review]
Nice one! 👌

**Comment by filipefurtad0** [comment]
Hey @apricot12 ,
In the meantime some conflicts with master came up... Could you have a look at that? Once they are solved we can test the PR. Thanks!

**Comment by apricot12** [comment]
@filipefurtad0 It seem's like there's been changes made to the BOM spec since i made this PR. I'll look into it :ok_hand:

**Comment by apricot12** [comment]
@filipefurtad0 Hey, I think you might have to restart the CI to check if the conflicts are resolved.

**Comment by RachL** [comment]
@filipefurtad0 I think https://github.com/openfoodfoundation/openfoodnetwork/issues/3807 will be solve by this PR. So I'm closing the issue, but we can reopen if there are cases missed :thumbsup:

File: spec/features/admin/bulk_order_management_spec.rb [hunk 3]
```diff
@@ -21,12 +21,16 @@
     end
 
     context "displaying the list of line items" do
-      let!(:o1) { create(:order_with_distributor, state: 'complete', completed_at: Time.zone.now ) }
-      let!(:o2) { create(:order_with_distributor, state: 'complete', completed_at: Time.zone.now ) }
+      let!(:o1) { create(:order_with_distributor, state: 'complete', shipment_state: 'ready', shipment_state: 'ready', completed_at: Time.zone.now ) }
+      let!(:o2) { create(:order_with_distributor, state: 'complete', shipment_state: 'ready', shipment_state: 'ready', completed_at: Time.zone.now ) }
```
Comment (filipefurtad0) [inline spec/features/admin/bulk_order_management_spec.rb:25]: I think we have a double here: ` shipment_state: 'ready',` is appearing twice in the lines above.

**Comment by filipefurtad0** [comment]
Hey @apricot12 

Awesome - this works as expected:

Before this PR this shipped order:

image


Appears in BOM:

image

Which can lead to #7457 and as you point out @RachL to #3807.

After staging the order cannot be found on the BOM page:

image

I think I encountered a minor typo in the variable declaration (see my comment above), but thank you for updating the specs! :muscle: 

Ready to go :tada:

File: spec/features/admin/bulk_order_management_spec.rb (hunk 3 above)
Comment (apricot12) [reply spec/features/admin/bulk_order_management_spec.rb]: Yeah, I probably appeared when I merged. I just fixed it :smile:
