### PR TITLE
SplitCheckout - Handle submit on step2 

### LINKED ISSUE #8625: [Split Checkout] Clicking the `Next - Order Summary` button has no effect
## Description

Follow-up from #8503; concerns checkout split (feature toggle on).

After selecting a payment method and adding the necessary data, clicking the `Next - Order Summary` button has no effect. This seems to work only when adding new credit card details on a stripe SCA payment, but is broken for all other payment methods.

## Expected Behavior

Clicking the `Next - Order Summary` button should redirect the user to the Order Summary page.

## Actual Behaviour

If cash, paypal, Stripe SCA (with a saved card) are selected as payment methods, then clicking the `Next - Order Summary` button takes no effect.

## Steps to Reproduce

1. On checkout, select any payment method (Exception is Stripe SCA while adding new card details)
2. Click `Next - Order Summary` button -> notice nothing happens.

## Animated Gif/Screenshot

Peek 2021-12-15 17-06

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

The aim of this PR is simply to handle form submit on step 2. Each commits resolve a case, and the `How to test?` section should be complete on each case. 

Closes #8625

###### Error message
Capture d’écran 2021-12-20 à 17 28 17

#### What should we test?
Check, for every payment method, the step 2.

Pay attention to the Stripe payment method, since it can be:
1. Without any register stripe card: should create a new one, with or without error
2. With existing registered card, and create a new one
3. With existing registered card, and select an existing
4. I don't know if this case is relevant, but it can co-exist in the same page many stripe payment methods

#### Release notes
Split checkout : Handle step-2 submit

Changelog Category: User facing changes

### CODE REVIEW

File: app/webpacker/controllers/paymentmethod_controller.js [hunk 1]
```diff
@@ -12,6 +12,14 @@ export default class extends Controller {
...
   selectPaymentMethod(event) {
     this.doSelectPaymentMethod(event.target.dataset.paymentmethodId);
+    const stripeCardsController =
+      this.application.getControllerForElementAndIdentifier(
+        document
+          .getElementById(event.target.dataset.paymentmethodId)
+          .querySelector('[data-controller="stripe-cards"]'),
+        "stripe-cards"
+      );
+    stripeCardsController.connect();
```
Comment (Matt-Yorkley) [inline app/webpacker/controllers/paymentmethod_controller.js:22]: What problem is this solving? :thinking:

Comment (jibees) [reply app/webpacker/controllers/paymentmethod_controller.js:22]: When selecting a payment method (such as Stripe), we want to re-initialize the stripe-cards controller in order select the card and then add the `disabled` attribute to each `input` of the `stripeelements` container.
Thus, we won't submit those input if we select an already registered card.

_(thanks for having a look here, it needs another review on my side, but I wanted to be sure to have your opinion here since you've made a lot here)_

**Comment by Matt-Yorkley** [comment]
I pushed a few review-commits :sweat_smile:

File: app/webpacker/controllers/paymentmethod_controller.js (hunk 1 above)
Comment (Matt-Yorkley) [reply app/webpacker/controllers/paymentmethod_controller.js]: Ah I see, it's because we disable all the fields in the preceding line...

**Review by mkllnk — APPROVED** [review]
I'm a bit out of my depth here but you've got my blessing. :wink:

**Comment by jibees** [comment]
> I pushed a few review-commits 😅

Thanks @Matt-Yorkley for this. I think this is (almost) ready to go. I've only one concern, here's the how to reproduce:

 - Select a payment method, with no error, (example stripe) then redirected to step 3
 - Back to step 2, but select another payment method (for exemple Credit Card) but introduce errors: ie. do not fill the form
 - Then you're redirecting to the step 2 (that's ok), with a flash error message `Please update the highlighted fields` (that's ok) but the payment method selected with the previous one that was ok (ie. here Stripe) not the one which failed (ie. here Credit Card). 
Capture d’écran 2021-12-21 à 10 32 55

**Comment by Matt-Yorkley** [comment]
@jibees I think that `Credit Card (fake)` payment method you're using is one of the "Bogus" payment methods (it shows a credit card details form but it's not Stripe, right?). I'm considering a proposal to remove them entirely as they are never used in production, only in testing and dev. So... this problem won't be a problem :wink:

**Comment by jibees** [comment]
> it shows a credit card details form but it's not Stripe, right?
Absolutely. 

So ... seems legit ;) 

Waiting to another review then ;)

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Great! It is now possible to checkout. Thank you for the test cases, checked:

- cash checkout - OK
- Paypal checkout - OK
- Stripe checkout, the cases

i) Without any register stripe card: should create a new one, with or without error - OK

Errors now appear correctly displayed:
image

Adding a card worked fine :+1: 

ii) With existing registered card, and create a new one - OK
iii) With existing registered card, and select an existing - OK
iv) I don't know if this case is relevant, but it can co-exist in the same page many stripe payment methods - OK


All good!
Merging.

**Comment by filipefurtad0** [comment]
Also, verified above that issues #8626 and #8624 could be closed.
Awesome! :muscle: 

image

The checkbox is still active, despite using a saved card, so keeping issue #8623 open for now.
