### PR TITLE
Remove product SKU from product pages and report

### LINKED ISSUE #11973: Fully remove SKU on product level
## Description

It is currently possible to set the SKU on product level (on page `/products`) as well as on variant level (on pages `/products` and `/products/<Product_ID>/variants/<Variant_ID>/edit`. However it is unclear which one is used where.

This could be related to #10939 where master variants have been removed - not sure.

**Assumption 1**: Since it is not possible to edit the product's SKU on page `/products/<Product_ID>/edit`, removing it from `/products` page could have been overlooked. In this case always the variant's SKU should be used everywhere - but in some reports the product's SKU is still being used.

~~**Assumption 2**: It was intentional to keep the SKU field on product level. Then it should be clear where it is used insead of the variant's SKU.~~

## Expected Behavior

☑️ **Option A:** Fully remove SKU on product level
- Remove the input field for SKU on page `/products`.
- Search the code for places where the product's SKU is being used and replace it with the variant's SKU (e.g. `Orders and Distributors` report).
- Disadvantage: It's unknown to me if and how much the product's SKU is being used by our users. A migration (maybe including communication to users could be required). But since in most customer facing cases the variant's SKU is already being used, the effect might be small.
- Disadvantage: Uncomfortable to add SKUs when it needs to be done for every single variant.
- Advantage: Clearly defined usage of SKU.

🆇 ~~**Option B:** Fully keep SKU on product level~~
- Add SKU input field on page `/products/<Product_ID>/edit`.
- Clearly indicate where which SKU is being used, e.g. by naming them Product SKU vs. Variant SKU or similar.

🆇 ~~**Option C:** Keep the input field on product level but always use variant's SKU~~
- Search the code for places where the product's SKU is being used and replace it with the variant's SKU (e.g. `Orders and Distributors` report).
- Proposal: Add logic to copy the product's SKU to all variants, when it's updated. Optional: Ask before overwriting existing variant's SKUs.
- Advantage: It's quick to add the same SKU or a SKU-prefix to all variants.
- Disadvantage: It's unknown to me if and how much the product's SKU is being used by our users. A migration (maybe including communication to users could be required). But since in most customer facing cases the variant's SKU is already being used, the effect might be small.

## Actual Behaviour

SKU **can** be set for product and variant:
image
image

**Product's** SKU **can't** be set on the `/products/<Product_ID>/edit` page:
image

**Variant's** SKU **can** be set on the `/products/<Product_ID>/variants/<Variant_ID>/edit` page:
image

**Variant's** SKU is used in order confirmation email:
image

**Variant's** SKU is used in order cycle report email:
image

**Product's** SKU is used in Orders and Distributors report:
image

**Variant's** SKU is used in Order Cycle Supplier Totals report:
image
image

**Other reports have not yet been checked.**

## Steps to Reproduce

1. Add different SKUs to the product and it's variant.
2. Check out with that variant.
3. Run the Orders and Distributors report.
4. Run the Order Cycle Supplier Totals report.
5. See that the different SKUs are being used.

## Animated Gif/Screenshot

See above.

## Severity
bug-s3: a feature is broken but there is a workaround
OR
bug-s5: we can live with it, only a few users impacted

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix (for option A)

Step 1:
* hide the field on the old products page (`/admin/products`) 
* hide the field on the new products page (`/admin/products` with feature toggle `admin_style_v3`; see `app/views/admin/products_v3`) and
* update Orders and Distributors report to use variant SKU
* Disable column with [`ignored_columns`](https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-ignored_columns-3D)

Step 2: Then once that change has been released and bedded down, we can perform a full cleanup and delete the database column in a separate PR.

### PR DESCRIPTION
**Pull request by murjax**
#### What? Why?

- Closes #11973 

This removes the product SKU from the UI to remove ambiguity with the variant SKU.

Pages impacted:
- Product List Page (`/admin/products/`)
- Product Edit Page (`/admin/products/:id/edit`)
- Orders and Distributors Report. (`/admin/reports/orders_and_distributors`)

#### What should we test?

1. Sign in as an admin.
2. Create a new product (Products -> New Product).
3. Editing a product to add variants with SKUs. (Products -> Edit -> Variants -> New Variant)
4. Viewing and editing a product from the list page, including the variant SKUs.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/reports/orders_and_distributors_spec.rb [hunk 1]
```diff
@@ -34,27 +35,27 @@
       }
       let(:line_item1) {
         [completed_at, order.id, "John Doe", order.email, "123-456-7890", "Herndon",
-         "ABC", Spree::Product.first.name.to_s, "1g", "1", "none", "10.0", "none", "Check",
+         variant.sku, Spree::Product.first.name.to_s, "1g", "1", "none", "10.0", "none", "Check",
```
Comment (mkllnk) [inline spec/system/admin/reports/orders_and_distributors_spec.rb:38]: It's better to use the actual value in specs. Otherwise we may miss a bug, for example if the sku is nil and the report fails to print the sku then this test would still pass.

**Review by mkllnk — APPROVED** [review]
Nice one. Thank you!

**Review by dacook — APPROVED** [review]
Looks good. I agree with Maikel's point but let's go.

**Comment by drummer83** [comment]
Hi @murjax,
Thank you so much for working on this. :pray: 

I've done some testing and here are my results.

## After staging

:heavy_check_mark: The field for SKU on master level is gone:
grafik

:heavy_check_mark:  The SKU of the variant is used in the Orders and Distributors report:
grafik

:heavy_check_mark: The variant SKU can still be edited on /products and on the /products/-ID-/variants/-ID-/edit pages.
:heavy_check_mark: The master SKU can't be found in the UI.
:heavy_check_mark: Order confirmation emails and order cycle summary emails are using the variant SKU.
:heavy_check_mark: All other reports (where SKU is used) are using the variant SKU.

## Results
I couldn't find any problems with this PR. It's working as expected. :partying_face: 
I think we can go ahead and merge this one! :rocket: 
Thanks again! :tada:
