### PR TITLE
Ensure directory exists before saving invoices pdf

### LINKED ISSUE #8080: Sidekiq error on bulk printing: Errno::ENOENTBulkInvoiceJob@default
## Description

~~Plenty of occurrences on the this error on the last day only, but so far only on UK-prod - checked bugsnag for FR, DE, US, AU:~~

Issue reported for FR-prod:

https://app.bugsnag.com/open-food-france/coopcircuits/errors/64802e66f3387700081f3ad9?event_id=64805b0700be10ebf2020000&i=sk&m=fq

One print attempt triggers several errors in Bugsnag.

## Expected Behavior

~~There have been user reports on this, so I guess the b~~
Bulk-pdf printing is not working for users.

## Actual Behaviour

Users should be able to bulk-print pdfs.

## Steps to Reproduce

~~Could not reproduce it in staging.~~

1. On the orders page, select a some orders
2. On the Actions dropdown, select Print invoices
3. Notice the print-job never finishes.
4. Notice the multiple Bugsnag errors.

## Workaround

Printing individual invoices, on the edit order pages, works as before.

Or as dev, after deploy run:
```
ansible all-prod -u openfoodnetwork -a 'mkdir -p ~/apps/openfoodnetwork/current/tmp/invoices'
```

## Severity

S2 at least for further investigations and to prevent it affects other instances.

## Your Environment

* Version used: ~~v4.0.1~~ v4.3.11
* Browser name and version: Firefox 113
* Operating System and version (desktop or mobile): Ubuntu 22.04

## Possible Fix

Possibly related to the latest rollback?

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
These directories can get wiped during deployments so before writing to them we should make sure they are created/recreated.

#### What? Why?

- Closes #8080

#### What should we test?

Printing bulk invoices after a fresh deployment

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
It appears that an important client of France having this issue, and needs to have invoices for tomorrow. Do you know if there is a workaround?

File: app/jobs/bulk_invoice_job.rb [hunk 1]
```diff
@@ -41,4 +43,10 @@ def broadcast(filepath, channel)
       ).
       broadcast
   end
+
+  def ensure_directory_exists(filepath)
+    return unless File.exist?(File.dirname(filepath))
+
+    FileUtils.mkdir_p(File.dirname(filepath))
```
Comment (mkllnk) [inline app/jobs/bulk_invoice_job.rb:50]: `mkdir_p` is okay with the directory existing:
```suggestion
    FileUtils.mkdir_p(File.dirname(filepath))
```

**Review by mkllnk — APPROVED** [review]

**Review by dacook — APPROVED** [review]
Perfect.

**Comment by jibees** [comment]
Commenting here (in addition to the [slack thread](https://openfoodnetwork.slack.com/archives/C01T75H6G0Z/p1686178760745059?thread_ts=1686170412.271089&cid=C01T75H6G0Z)) the workaround in case we need it:

```
ansible all-prod -u openfoodnetwork -a 'mkdir -p ~/apps/openfoodnetwork/current/tmp/invoices'
```

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley,

Ok, this fixes it in staging too. After deployment we can render bulk invoices as before :+1: 

image

Now, as a second double check, I guess it's interesting to check bulk invoicing after we stage something else, on top of this merged PR, to assure the directory does not get deleted.

I'll merge this now, stage the next PR and drop another comment on the outcome.

**Comment by filipefurtad0** [comment]
Ahh,
actually, after merging and deploying something else, the test fails:

image

Which makes sense, or at lease, I'd explain it by:
- assuming that staging with Ansible  does not stage a merged version of the branch with master; which means the staged branch does not contain the fix within this PR
- indeed, staging deletes that tmp directory (!)... I'm just wondering why did this not happen more often, in prod, staging... (shrug emoji)

I guess, on release testing, we need to make sure this works again. I'll updated the testing template as our test does not cover this scenario.

Also opened an issue to improve this test, https://github.com/openfoodfoundation/openfoodnetwork/issues/10967. We could at least check that a file was created, this would already be a step in the right direction (even if we don't assert on the contents).

**Comment by jibees** [comment]
>I guess, on release testing, we need to make sure this works again. I'll updated the testing template as our test does not cover this scenario.

👍

**Comment by Matt-Yorkley** [comment]
> assuming that staging with Ansible does not stage a merged version of the branch with master; which means the staged branch does not contain the fix within this PR

Yeah I think that's right. Any PRs that are rebased should be fine :+1:

**Comment by mkllnk** [comment]
@Matt-Yorkley What do you think about the lost invoices during deployment? It should be rare but if someone generates an invoice while we deploy then it will be lost after the deploy and can't be downloaded.

In the past, the pattern has been to use a shared directory. We could also use ActiveStorage and set it to local for invoices because they are not persisted ... until we have the numbered invoices which could benefit from persisted blobs...

Many possibilities, what's your take?
