### PR TITLE
prevent deleting only item in confirmed order

### LINKED ISSUE #5546: Deleting the last item from the confirmed order is allowed in /cart page (no warning) and easily leads to error 500
## Description

While in the /cart page and placing orders in shops which have the option to edit confirmed orders for the same OC, the customer can remove all items from previously confirmed orders. This leads to an empty order and generates error 500 when attempting to viewing these (bug #5505).

This issue was first reported here https://github.com/openfoodfoundation/openfoodnetwork/pull/5480#discussion_r433421881

## Expected Behavior

While editing the cart, removing the last item from a previously confirmed order should not be allowed, and warning should be shown to the customer stating so.

This already happens if the order is viewed/edited in the /account#/orders/ page:

## Actual Behaviour

In the /cart page the user can remove all items from a previously confirmed order. Attempting to view this empty order will generate error 500 (bug #5505).

## Steps to Reproduce

Admin:
1. Go to shop preferences an choose "Customers can change / cancel orders while order cycle is openallow shops to Go to a shop which allows" 

Customer:
2. Visit shop and place an order. Make sure you get the order confirmation.
3. Visit the shopfront again and, for the same OC, place an item in the cart, proceeding to /cart page
4. While in cart page, the previous order should be visible (pic below).
5. Now remove all items from the previously placed order.
6. Press Edit confirmed items.
7. Boom.

## Workaround

Cancelling the previously confirmed order.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 2.9.10 and 2.9.11
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Ubuntu 18.04 Desktop

## Possible Fix

Related with issue bug #5505.
Perhaps also related with issues #5253 and #5350.

### PR DESCRIPTION
**Pull request by guidoDutra**
#### What? Why?

Closes #5546 

when there are multiple confirmed orders, it is possible for the customer to delete all items in one of them, which causes an issue where there is a confirmed order with no items in it (see issue for more details). This PR aims to fix this bug.

#### What should we test?
whether its possible to delete the last remaining item in a confirmed order through the Edit Cart page

#### Release notes
prevented customer from deleting the last remaining item in a confirmed order when there are multiple confirmed orders.

Changelog Category: User facing changes

### CODE REVIEW

File: app/assets/javascripts/darkswarm/services/cart.js.coffee [hunk 1]
```diff
@@ -115,8 +115,9 @@ Darkswarm.factory 'Cart', (CurrentOrder, Variants, $timeout, $http, $modal, $roo
       @line_items = []
       localStorageService.clearAll() # One day this will have to be moar GRANULAR
 
-    has_one_line_item: =>
-      @line_items_finalised.length == 1
+    isOnlyItemInOrder: (id) =>
+      deletedItem = @line_items_finalised.find((item) -> item.id == id)
+      @line_items_finalised.filter((item) -> item.order_id == deletedItem.order_id).length == 1
```
Comment (guidoDutra) [inline app/assets/javascripts/darkswarm/services/cart.js.coffee:120]: please let me know if there is a more elegant way of doing this

Comment (sauloperez) [reply app/assets/javascripts/darkswarm/services/cart.js.coffee:120]: I'm not entirely sure a Cart can have line items from different orders. If that's the case the problem lays in the Cart abstraction itself. Lines 7 and 8 make me think so. We initialize the line item arrays from a single order :thinking:

Comment (Matt-Yorkley) [reply app/assets/javascripts/darkswarm/services/cart.js.coffee:120]: I think this relates to the option where there's a previous order in the same OC and the OC hasn't closed yet, and the distributor allows editing open orders?

**Review by Matt-Yorkley — APPROVED** [review]
LGTM. Thanks @guidoDutra !

File: app/assets/javascripts/darkswarm/services/cart.js.coffee (hunk 1 above)
Comment (guidoDutra) [reply app/assets/javascripts/darkswarm/services/cart.js.coffee:120]: that's right @Matt-Yorkley

**Review by andrewpbrett — APPROVED** [review]

**Comment by andrewpbrett** [comment]
Thanks @guidoDutra! I've moved this to Test Ready in zenhub.

**Comment by filipefurtad0** [comment]
Hey @guidoDutra ,

Thanks for this PR. After staging, the issue can't be reproduced anymore :tada: 
So, if an OC allows customer to change their orders while the OC is still open, the last item cannot be removed and leaving the order empty - even if there were several placed orders: this was the missing bit which PR  #6528 was not addressing:

Peek 2021-05-12 19-44

Also checked the case in which we only have one past order only - it works as before:

Peek 2021-05-12 19-52


Awesome! This closes #5546.
Ready to go.
