### PR TITLE
Split checkout: handle cards that throws any errors

### LINKED ISSUE #9038: [Split Checkout] insufficient_funds decline code breaks checkout
## Description

Looks related to #8952.

The `insufficient_funds` decline code - say from introducing the card 4000000000009995 on split ckeckout - breaks the checkout flow.

## Expected Behavior

I think the expected behavior would be to be redirected to `/payment` step.

## Actual Behaviour

Snail.

## Steps to Reproduce

1. Visit `/payment` and introduced the card * 9995
2. Proceed to `/summary`
3. Complete the order
4. See the snail

## Animated Gif/Screenshot

Peek 2022-03-25 11-23

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9038

Handle Stripe card errors in split checkout

###### Proceed to checkout with a card that throws error
 - Visit `/payment` and introduced the card that failed (ex. https://stripe.com/docs/testing?numbers-or-method-or-token=card-numbers#declined-payments)
 - Proceed to `/summary`
 - (try to) Complete the order
 - You should be redirected to step 2 (aka. payment) with a flash error
Capture d’écran 2022-04-27 à 15 51 19

###### Proceed to payment step to save a card that throws error
- Visit `/payment` and introduced the card that failed (ex. https://stripe.com/docs/testing?numbers-or-method-or-token=card-numbers#declined-payments)
- Check on "Save card for future user"
Capture d’écran 2022-04-27 à 15 51 10

- Click on "Next - Order summary"
- You should see error:
Capture d’écran 2022-04-27 à 15 51 19

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @jibees ,
Awesome :muscle:  This PR handles non-3D cards / general errors correctly, and prevents #9131.

I've tested the scenarios mentioned on your "What to test" section, with:

- cards not requiring authentication, like 4000000000000002 (general failure):

   - trying to save the card
   - trying to place the order (without saving the card)
 
both redirect the customer to the `/payment` step:
image

**Regression tests**
- cards requiring authentication, like 4000008260003178 (insufficient funds card):  

As before:

 - trying to place the order
 - failing authentication 

Display the expected error and redirect to `/details` step -> I guess ideally the customer would be redirected to the `/payment` step - a minor issue (coming up):

Peek 2022-05-02 12-17

This is good to go! :rocket: 

PS: I've noticed that transaction fees accumulate with payment attempts, this is issue #9112 - initially reported for legacy checkout but also seen on here on split-checkout:
image

File: spec/system/consumer/split_checkout_spec.rb [hunk 1]
```diff
@@ -627,6 +627,7 @@
             it "selects Stripe SCA and proceeds to the summary step" do
               choose pay_method.to_s
               fill_out_card_details
+              click_on "Next - Order summary"
```
Comment (filipefurtad0) [inline spec/system/consumer/split_checkout_spec.rb:630]: `yes, this is a hack, but can't make it work as a normal behavior. For testing purpose, we use `spec/support/fixtures/stripejs-mock.js` and it seems not working with our `app/webpacker/controllers/stripe_controller.js``

Yeah! I've had troubles with this too... I'm not fully understanding this yet, and the implications but at some point good it would be great to exchange thoughts on this.

**Comment by RachL** [comment]
@filipefurtad0 so #9131 can be closed? Or do you mean it prevents the issue but the issue is not fixed?

**Comment by filipefurtad0** [comment]
Yes, I _think_ it should not occur for new customers, but those which have experienced the bug will still not be able to checkout.

The second aspect of that issue is that emptying the cart is not really bringing the customer to create a new order.

**Comment by jibees** [comment]
> clicking empty cart or switching shops should allow the user to start a fresh new order, from state cart. This would allow the redirection to the /details page

Totally agree. 👍
