### PR TITLE
Display producer's name in products inspite of hide all refs option

### LINKED ISSUE #9698: When producer enterprises "hide all references" their name gets hidden on product shopfront as well
## Description

"hide all references" is made in order to hide link to enterprises which do not want to appear outside of their community. This should not include their products. Each products should always show the link to the producer profile.

## Expected Behavior

See producer 's name

image

## Actual Behaviour

We see a blank space

image

## Steps to Reproduce

1. Go to a producer profile settings `/admin/enterprises/XXX/edit`
2. Select "hide all preferences"
3. Observe a shopfront with this producer products
4. See producer name is blank

## Workaround

Unhide.

## Severity
bug-s3: a feature is broken but there is a workaround

## Your Environment
* Version used: v4.2.14
* Browser name and version: ALL
* Operating System and version (desktop or mobile): all

### PR DESCRIPTION
**Pull request by binarygit**
selected

#### What? Why?

- Closes #9698

#### What should we test?

- Login as admin and navigate to `enterprises/<name>/edit` of a `producer`
- Select `hide all references`
- Navigate to any open OC that display's the producer's products
- Ascertain that you can see the producer's name listed alongside its product 
Capture d’écran 2023-03-09 à 15 42 57
- Ascertain that you can see the producer's name listed in the producers name, but no modal should open
Capture d’écran 2023-03-09 à 16 08 26

When visibility is by default, nothing should change. 
#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by jibees — APPROVED** [review]
As this is close to my proposed solution (https://github.com/openfoodfoundation/openfoodnetwork/issues/9698#issuecomment-1257952998), I don't know if I'm legit to review/approve this one ;)

**Comment by binarygit** [comment]
it's your exact solution! I just popped it in there and it worked! :laughing:

**Review by abdellani — COMMENTED** [review]
Hi 
I'm not sure that I'm checking the right place.
Can you please confirm?
So, I started by selecting `HIDE ALL REFERENCES` on the producer `producer-1`
image
Then I refreshed the shop link `http://HOST/producer-1/shop` and it's still blank.
image

**Comment by RachL** [comment]
@abdellani you've looked at the right place yes

**Comment by binarygit** [comment]
@abdellani Sorry about earlier confusion. I did check after I had made the changes, but looks like I was wrong. Probably had the `visible in search` set to `public` and then looked at the OC page, obviously the producer's name was going to show up! :sweat_smile: 

It took me a little time to figure out what was causing it, but I have checked twice this time, and the producer's name does show up even when `hide all references` is selected.

Screenshot 2022-12-18 at 11-42-01 Enterprises - OFN Administration
Screenshot 2022-12-18 at 11-42-21 Mary #39 s Online Shop

**Review by jibees — COMMENTED** [review]
Finally not that close to my initial proposition.. 
💪

**Review by abdellani — APPROVED** [review]
Looks good

**Comment by RachL** [comment]
Hello @binarygit good news, this PR fixes the problem the in the shopfront / list of products: 

image

And if a hub is hidden, it does not show on a producer modal (here I can't see release farm as shop): 

image


Bad news - it reintroduces the hidden enterprises in the producer tab, which we tried to avoid with this "hide all reference" new button. 

image


This button was introduced here : https://github.com/openfoodfoundation/openfoodnetwork/pull/9087

And I guess we have the problem on the product list since then. But the current behavior of the producer tab is the good one and should be kept. Can you have another look?

**Comment by RachL** [comment]
Actually now that I think of it I understand why this bug was introduce: we want to hide some shops, because they can contain products with different prices than the shop we are currently visiting.

We have chosen to hide them completely from the shop, but it causes the problem of not seeing who is the producer behind the product when the shop is also a producer. I see two options: 

1. instead of trying to hide them we could display them with no link? Downside is shopper loose access to the presentation of the producer...

2. We keep the display proposed here, but we make sure we can't reach a hidden shopfront from the producer profile. Here, I should not be able to visit Release farm shop: 

image

**Comment by binarygit** [comment]
ah okay. Thanks for testing and pointing this out @RachL. 
I'll work on this and update you :smile:

**Comment by binarygit** [comment]
Okay, so what I did is that the producer's name is still displayed alongside their products but it's now highlighted in red, and clicking it doesn't open the modal which would have enabled the shopper to visit the producer's shop.
Screenshot 2022-12-23 at 12-51-47 Mary #39 s Online Shop

Same thing in the other places where the `producer` is displayed: name is displayed but the modal does not open when clicked, the ones I've found and checked are
here:
Screenshot 2022-12-23 at 12-53-15 Mary #39 s Online Shop

and here:
Screenshot 2022-12-23 at 12-54-05 Shops

Let me know what you think of this solution @RachL and if I missed something.

File: app/assets/javascripts/darkswarm/services/enterprise_modal.js.coffee [hunk 1]
```diff
@@ -2,6 +2,7 @@ angular.module('Darkswarm').factory "EnterpriseModal", ($modal, $rootScope, $htt
   # Build a modal popup for an enterprise.
   new class EnterpriseModal
     open: (enterprise)->
+      return if enterprise.visible == 'hidden'
```
Comment (dacook) [inline app/assets/javascripts/darkswarm/services/enterprise_modal.js.coffee:5]: I think it's rather unfortunate that this attribute value looks very similar to the css `visibility: hidden`.
It's even more confusing that "Hidden" is not the same as "hidden"!!
https://github.com/openfoodfoundation/openfoodnetwork/blob/7c69cc5aa9abf00f798dbb2809f7308450d37960/config/locales/en.yml#L1002-L1004
(this is not your fault of course!)

I would like to see this part of the system a bit more intuitive. It would be better if the `EnterpriseModel` didn't have to know about the internal values of `Enterprise` and could just call a public method. There's already an `Enterprise#public?` method, so a  new `hide_references?` method would be good.
But I can see this has been waiting three weeks so perhaps we don't need to change this now.

**Comment by dacook** [comment]
This looks ok to me, I will add my code review. 
But I'm not sure about the red colour of the producer name. Given that this is not an error state, and that there's nothing the user can do to interact with the name, I suggest it should just be the same grey colour as the text "_from_". Also ideally it would not have the mouse cursor show the pointer.

@RachL what do you think?

File: app/webpacker/css/darkswarm/typography.scss [hunk 2]
```diff
@@ -150,6 +150,8 @@ ul.check-list {
   padding-bottom: 100px;
 }
 
+.red { color: red }
```
Comment (dacook) [inline app/webpacker/css/darkswarm/typography.scss:153]: I'm not sure this is the best way to highlight this, but will await Rachel's feedback.

**Comment by RachL** [comment]
@binarygit :scream_cat: so sorry I'm just seeing your notification now :( don't hesitate to ping me on slack when this happens or add the "feedback-needed" label, as I'm always on the board I would spot these issues more quickly.

@dacook good point. We don't have this specified well in the current style guide. So I guess your proposal of doing it in grey is a good one as in other places (like the producer tab), our links are in red.

File: app/assets/javascripts/darkswarm/services/enterprise_modal.js.coffee (hunk 1 above)
Comment (binarygit) [reply app/assets/javascripts/darkswarm/services/enterprise_modal.js.coffee:5]: Yup why don't we change this later :smile:

File: app/views/shop/products/_summary.html.haml [hunk 3]
```diff
@@ -10,11 +10,16 @@
...
-    .product-producer
-      = t :products_from
-      %span
-        %enterprise-modal
-          %span{"ng-bind" => "::enterprise.name", "ng-class" => "{'red': enterprise.visible == 'hidden'}"}
+    %div{ "ng-switch" => "enterprise.visible" }
+      .product-producer{ "ng-switch-when": "hidden" }
+        = t :products_from
+        %span
+          %span.grey{"ng-bind" => "::enterprise.name"}
```
Comment (dacook) [inline app/views/shop/products/_summary.html.haml:17]: If the "products from" text is grey, maybe we don't need any `span` elements at all in this case?

File: app/views/shop/products/_summary.html.haml [hunk 4]
```diff
@@ -10,11 +10,16 @@
...
         %span{"ng-bind" => "::product.name"}
     %p.product-description{ng: {bind: "::product.description", click: "triggerProductModal()", show: "product.description.length"}}
-    .product-producer
-      = t :products_from
-      %span
-        %enterprise-modal
-          %span{"ng-bind" => "::enterprise.name", "ng-class" => "{'red': enterprise.visible == 'hidden'}"}
+    %div{ "ng-switch" => "enterprise.visible" }
+      .product-producer{ "ng-switch-when": "hidden" }
+        = t :products_from
```
Comment (dacook) [inline app/views/shop/products/_summary.html.haml:15]: This code is repeated in both switch cases, so I think it can be deduplicated and moved outside the `ng-switch`.

**Review by dacook — CHANGES_REQUESTED** [review]
Thanks for changing that. I just have a couple of suggestions to reduce the amount of code needed, can you please take a look?

**Comment by jibees** [comment]
I think this one is ready to be reviewed... Thanks!

**Review by dacook — APPROVED** [review]
Thanks for finishing this one off!

File: app/views/shopping_shared/tabs/_producers.html.haml [hunk 5]
```diff
@@ -6,6 +6,9 @@
           = t :shopping_producers_of_hub, hub: '{{ shopfront.name }}'
         %ul.small-block-grid-1.medium-block-grid-2.large-block-grid-3
           %li{"ng-repeat" => "enterprise in shopfront.producers"}
-            %enterprise-modal
+            %enterprise-modal{"ng-if": "enterprise.visible != 'hidden'"}
```
Comment (mkllnk) [inline app/views/shopping_shared/tabs/_producers.html.haml:9]: I just checked a production database:

```rb
Enterprise.distinct.pluck(:visible)
=> ["t", "public", "only_through_links", "hidden", "f"]
```

I think that `t == public` and `f == only_through_links`. So the check is right here. But then I wondered why we hide the modal?

**Review by mkllnk — COMMENTED** [review]
The code is good but I don't understand why we hide the modal. I didn't see that in the issue. 

> "hide all references" is made in order to hide link to enterprises which do not want to appear outside of their community.

I thought that the important part here is *outside of their community*. So when you have access to a shop, you can see everything including the modal. There's just no discovery feature (map, shops etc) for these enterprises.

**Comment by jibees** [comment]
Trying to be clear. 

`Freddy's Farm Shop` is a shop that sells `Fred's Farm` products. `Fred's Farm` has set `Hide all references` preference. 
Then, when visiting producers of `Freddy's Farm Shop`, we see that `Fred's Farm` is in the list of producer, but we don't open any modal, since it's _outside of their community._ (ie. it's Freddy's community, not Fred's community). Does it makes sense to you @mkllnk ?


But as I'm reading the help, I don't know if this is the right choice:
Capture d’écran 2023-03-20 à 10 01 14

Why not then, for the producers list of a shop:

1. _publicly visible, appearing on the OFN map and listings._ 
--> Name + link to modal 
2. _Hidden on maps and listings but referenced by other shops and linked in their profile._
--> Only name
3. _Completely hidden._
--> Nothing.

But that's maybe another issue/PR after all? Don't know...

I also will request confirmation/help/advice from @RachL

**Comment by RachL** [comment]
@jibees not showing the modal is the good way to go. If we _really_ want something clean, the ideal world is to show the modal, but not show the linked shops.

let me explain with the use case

"hide all references" has not been introduce to make a profile disappear completely (we always need to have traceability) it was made to hide links to some shops, so the shopper can't make their way to shop with different prices.

E.g. : 

I'm a shop that sell producer's product to end consumer and businesses. I sell the same product at a lower price to businesses. I could create a closed shops for businesses but I have 100 clients and it's a pain for me to handle the customer list. So I leave the shop "hidden" believing that only people with the link will find out. The problem with "hidden" is that shoppers can find the link to my business shop in the producer tab and in the modal where it is listed as "shop for XX products at".

Is it clearer?

i agree however that in case of a producer with no shops I wonder if we should even display "hide all references" as an option. I don't see a use case for that one. So "hide all references" or "hidden" would have the same result for a shopless profile currently.

**Comment by RachL** [comment]
@jibees are you good here?

**Comment by jibees** [comment]
I've rebased the PR, had a call with @RachL to clarify: I think this one is ready now.

**Review by dacook — APPROVED** [review]
I approved the code change.
I'm assuming Rachel approves the functionality.

**Review by mkllnk — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @binarygit  and @jibees,

Before this PR, after setting a given producer to "hide all references":

Shopfront:
image

Producers tab:
image


After this PR:

Shopfront:
image

Producers tab:
image


Regression test:

If we set the producer back to public, then the producer appears again on the map, and the references are clickable
image

Good to go, thanks!
