### PR TITLE
Fix users removing last item of confirmed order on /cart page

### LINKED ISSUE #5546: Deleting the last item from the confirmed order is allowed in /cart page (no warning) and easily leads to error 500
## Description

While in the /cart page and placing orders in shops which have the option to edit confirmed orders for the same OC, the customer can remove all items from previously confirmed orders. This leads to an empty order and generates error 500 when attempting to viewing these (bug #5505).

This issue was first reported here https://github.com/openfoodfoundation/openfoodnetwork/pull/5480#discussion_r433421881

## Expected Behavior

While editing the cart, removing the last item from a previously confirmed order should not be allowed, and warning should be shown to the customer stating so.

This already happens if the order is viewed/edited in the /account#/orders/ page:

## Actual Behaviour

In the /cart page the user can remove all items from a previously confirmed order. Attempting to view this empty order will generate error 500 (bug #5505).

## Steps to Reproduce

Admin:
1. Go to shop preferences an choose "Customers can change / cancel orders while order cycle is openallow shops to Go to a shop which allows" 

Customer:
2. Visit shop and place an order. Make sure you get the order confirmation.
3. Visit the shopfront again and, for the same OC, place an item in the cart, proceeding to /cart page
4. While in cart page, the previous order should be visible (pic below).
5. Now remove all items from the previously placed order.
6. Press Edit confirmed items.
7. Boom.

## Workaround

Cancelling the previously confirmed order.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 2.9.10 and 2.9.11
* Browser name and version: Firefox 75
* Operating System and version (desktop or mobile): Ubuntu 18.04 Desktop

## Possible Fix

Related with issue bug #5505.
Perhaps also related with issues #5253 and #5350.

### PR DESCRIPTION
**Pull request by mprieger**
#### What? Why?

Closes #5546

This change prevents users from removing the last item of a confirmed order on the /cart page. This was allowed when shops had the option to edit confirmed orders for the same OC. 

The functionality is similar to what happens when an order is edited from the /orders page. The main difference is that it displays the error without a page reload. The remove button is disabled when a user presses it for 10s (the time the flash error message is displayed for) to prevent multiple error messages appearing with each button press.

#### What should we test?
When a shop allows edits to confirmed orders, ensure that user cannot remove last item of a confirmed order in the /cart page.
Confirm that attempting to remove an item multiple times displays at most one error message.

#### Release notes
Customers can no longer remove the last item of a confirmed order on the /cart page.

Changelog Category: User facing changes

#### Dependencies
This fix is related to #5505 and should prevent one possible cause for this bug of getting a 500 error when viewing an order from which all items were removed.

### CODE REVIEW

File: app/assets/javascripts/darkswarm/services/cart.js.coffee [hunk 1]
```diff
@@ -115,6 +115,12 @@ Darkswarm.factory 'Cart', (CurrentOrder, Variants, $timeout, $http, $modal, $roo
       @line_items = []
       localStorageService.clearAll() # One day this will have to be moar GRANULAR
 
+    check_last_finalised_item: =>
+      if @line_items_finalised.length == 1
+        Messages.error(t 'orders_cannot_remove_the_final_item')
+
+      @line_items_finalised.length == 1
+
```
Comment (andrewpbrett) [inline app/assets/javascripts/darkswarm/services/cart.js.coffee:123]: This might be more clear with a different name, and if we leave it up to the controller to display the Message. Coupled with the other suggested change in the controller, this could be: 

```suggestion
    has_one_line_item: =>
        @line_items_finalised.length == 1
```

It might not be totally necessary to have it as a method on Cart, but if we do keep it as a separate method, we don't use the instance variable outside the Cart class.

File: app/assets/javascripts/darkswarm/controllers/edit_bought_order_controller.js.coffee [hunk 2]
```diff
@@ -1,12 +1,19 @@
...
 
   $scope.deleteLineItem = (id) ->
-    params = {id: id}
-    success = (response) ->
-      $(".line-item-" + id).remove()
-      Cart.removeFinalisedLineItem(id)
-    fail = (error) ->
-      console.log error
+    if Cart.check_last_finalised_item()
+      $scope.removeEnabled = false
```
Comment (andrewpbrett) [inline app/assets/javascripts/darkswarm/controllers/edit_bought_order_controller.js.coffee:7]:
```suggestion
    if Cart.has_one_line_item()
        Messages.error(t 'orders_cannot_remove_the_final_item')
        $scope.removeEnabled = false
```

**Review by andrewpbrett — APPROVED** [review]
This looks good! I think it can go to testing after a second review. 

One way to potentially go further: the error message suggests that the customer should cancel the order instead of removing the last line item. Is that easy for them to do? Could we make it easier?

**Comment by andrewpbrett** [comment]
@mprieger Do you mind if I commit these suggestions to your branch?

**Comment by sauloperez** [comment]
I would go ahead @andrewpbrett . It'd be cool to have this included in the next release.

**Comment by andrewpbrett** [comment]
@sauloperez done! Needs a second review and then I think it can be moved to Test Ready.

**Review by sauloperez — APPROVED** [review]

**Comment by sigmundpetersen** [comment]
Build is failing

**Comment by andrewpbrett** [comment]
Thanks @sigmundpetersen! Let's see if this fixes it.

**Comment by filipefurtad0** [comment]
Hey @mprieger ,

Thank you for this contribution!

I staged your PR, but somehow could not verify the underlying issue is fixed. Following the steps described on #5546, I was still able to remove the last item, while on the /cart page, thus breaking the order. See for example, this one:

image

Would you like to have a second look at it? I'm moving to In Dev, for now.

**Comment by RachL** [comment]
hello @mprieger Are you still available to make the required changes? Thank you for your contribution :-)

**Comment by mprieger** [comment]
Hello @RachL and @filipefurtad0

My apologies for the delayed response! Unfortunately, I will not be able to continue work on this at this time, but hopefully my changes (and the revisions from the reviewers) serve as a good starting point for anyone looking to pick this up.

**Comment by andrewpbrett** [comment]
Hi @filipefurtad0 - I rebased and made a small change and I'm now seeing the message show up on the cart page; I think this is ready for a re-test. One thing I did notice is that if there are multiple open orders, it still allows you to delete the last item from all the open orders except the last one. So this doesn't completely fix the problem, but I think it would be fairly uncommon for there to be multiple orders that someone is placing in an order cycle, so I think this would definitely be an improvement (if you do in fact verify it's working).

**Comment by filipefurtad0** [comment]
Hey @mprieger,

Thanks for this contribution!

After staging your changes it's possible to verify @andrewpbrett findings - your notes really made testing this much easier, thanks Andy :+1: 

- attempting to remove the last item from the cart, with one previous order only now displays a warning :tada: 

Peek 2021-03-04 11-31

- if more orders are placed, we can see below, that it is still possible to remove the last item (from the same order as above):

Peek 2021-03-04 11-33

So, agree this is an improvement, let's merge this :+1: 

Instead of closing, I'd propose to downgrade #5546. Surely this PR will make it easier to address the missing scenario.
