### PR TITLE
Wait for angular to load in BOM spec

### LINKED ISSUE #3383: [Flaky Spec] spec/features/admin/bulk_order_management_spec.rb:56
## Description

This spec is unreliable: https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-2833/builds/5

## Context

Our Semaphore builds fail regularly because of these unreliable tests. If you encounter this in your build, please comment on this issue or add :+1: 

Error:

```
  As an Administrator
  I want to be able to manage orders in bulk
 listing orders displaying individual columns displays a column for order date
     Failure/Error: expect(page).to have_selector "td.date", text: o1.completed_at.strftime('%B %d, %Y'), visible: true
       expected to find visible css "td.date" with text "January 24, 2019" but there were no matches. Also found "", "", which matched the selector but not all filters.
     # ./spec/features/admin/bulk_order_management_spec.rb:58:in `block (4 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #3383

Hopefully this will finally fix this flaky spec!

#### The issue:

There are a number of tests that fail occasionally in this file. Angular is making some asynchronous requests on the page, then updating the DOM when it's finished. The issue seems to be that Capybara is not waiting long enough, or is not waiting until Angular has finished loading. It's consistently green in people's dev environments, but fails sometimes on Semaphore, so I think the problem is partly due to the CI environment being slower?

#### My solution:

I've added a couple of helper methods for feature specs that enable us to interrogate angular directly from within a test, and find out if the `$http` module is still processing requests, or if the `RequestMonitor` class is still loading data. They should be re-usable in the future if we have similar issues.

#### What should we test?

Tests in `/spec/features/admin/bulk_order_management_spec.rb` should not be flaky.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
I've tried various things with this flaky spec. I thought I had it that last time, but the test is still failing... 

:sob:

**Comment by Matt-Yorkley** [comment]
Ok, I've had another go and I think I've nailed it this time.

File: spec/support/request/web_helper.rb [hunk 1]
```diff
@@ -152,6 +152,16 @@ def accept_js_alert
...
+  def angular_http_requests_finished(angular_controller=nil)
+    scope_element = angular_controller ? "[ng-controller=#{angular_controller}]" : '.ng-scope'
+    page.evaluate_script("angular.element(document.querySelector('#{scope_element}')).injector().get('$http').pendingRequests.length == 0")
+  end
+
+  def request_monitor_finished(angular_controller=nil)
+    scope_element = angular_controller ? "[ng-controller=#{angular_controller}]" : '.ng-scope'
+    page.evaluate_script("angular.element(document.querySelector('#{scope_element}')).scope().RequestMonitor.loading == false")
+  end
+
```
Comment (luisramos0) [inline spec/support/request/web_helper.rb]: I think this will make it more readable:
```suggestion
.
def angular_http_requests_finished(angular_controller=nil)
    scope_expr = scope_element_expression(angular_controller)
    pending_http_requests_script = "#{scope_expr}.injector().get('$http').pendingRequests.length == 0"
    page.evaluate_script(pending_http_requests_script)
end

 def request_monitor_finished(angular_controller=nil)
    scope_expr = scope_element_expression(angular_controller)
    request_monitor_script = "#{scope_expr}.scope().RequestMonitor.loading == false")"
    page.evaluate_script(request_monitor_script)
  end
  
  def scope_element_expression(angular_controller=nil)
      scope_element = angular_controller ? "[ng-controller=#{angular_controller}]" : '.ng-scope'
      scope_element_expression = "angular.element(document.querySelector('#{scope_element}')"
  end
```

Comment (Matt-Yorkley) [reply spec/support/request/web_helper.rb]: I've tidied it up and added a comment to explain how the format for the angular controller name  and how it finds the scope if `nil` :+1:

**Comment by sauloperez** [comment]
:clap:

**Comment by sauloperez** [comment]
It ran three times in a row so it seems stable enough, for now :trollface:

**Comment by sigmundpetersen** [comment]
... and it uncovered the next flaky BOM spec https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/508 🙀
