### PR TITLE
Process order cycle emails individually to avoid duplicates

### LINKED ISSUE #13278: Producers receiving multiple copies of Order Cycle Report notification emails
## Description

Two hubs in the UK have reported their producers receiving multiple copies of the same Order Cycle Report notification emails. Both hubs have automatic producer notifications turned on. I have confirmed that hubs aren't simply 're-notifying' their producers by mistake to trigger the multiple emails.

## Expected Behavior

Producers should receive one copy of the notification email when automatic notifications are turned on.

## Actual Behaviour

Producers receive multiple copies of the notification emails. Which producers receive multiple emails does not seem to be predictable - not all producers in an order cycle receive multiple emails, and those that do receive multiple copies don't necessarily receive multiple copies in the next order cycle.

## Steps to Reproduce

Difficult to reproduce!
The affected hubs are Tamar Valley Food Hubs (id: 160) and In My Back Yard C.I.C (id: 201505).
Below is the source information for three copies of the same email that was received three times by the producer, I've redacted email addresses.

<details> <summary>Email header 1</summary> 
X-Antivirus: avg (VPS 25041600)
X-Antivirus-Status: Clean
Return-Path: <bounces+38202728-762a-hello=openfoodnetwork.org.uk@em9402.openfoodnetwork.org.uk>
Delivered-To: hello@openfoodnetwork.org.uk
Received: from smtp-4-9000.mail.infomaniak.ch ([10.7.10.130])
	by mda-3-0341.mail.infomaniak.ch with LMTP
	id ODX5IM1x/2eEZDcADqYp3Q
	(envelope-from <bounces+38202728-762a-hello=openfoodnetwork.org.uk@em9402.openfoodnetwork.org.uk>)
	for <hello@openfoodnetwork.org.uk>; Wed, 16 Apr 2025 11:01:01 +0200
Authentication-Results: mx.infomaniak.com; dmarc=pass (p=none dis=none) header.from=openfoodnetwork.org.uk
Authentication-Results: mx.infomaniak.com;
	dkim=pass (2048-bit key; unprotected) header.d=openfoodnetwork.org.uk header.i=@openfoodnetwork.org.uk header.a=rsa-sha256 header.s=s1 header.b=YFrf3iFr;
	dkim-atps=neutral
Received: from o1.ptr7895.openfoodnetwork.org.uk (o1.ptr7895.openfoodnetwork.org.uk [149.72.220.188])
	by smtp-4-9000.mail.infomaniak.ch (Postfix) with ESMTPS id 4Zcw3w4qXFzZ4g
	for <hello@openfoodnetwork.org.uk>; Wed, 16 Apr 2025 11:01:00 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=openfoodnetwork.org.uk;
	h=from:subject:mime-version:reply-to:to:cc:content-type:
	content-transfer-encoding:cc:content-type:from:subject:to;
	s=s1; bh=QgBcWK8OPZ0PXbLw1/xys7ewyQ5n+hG6kwdT6uzqrI0=;
	b=YFrf3iFr8PdrIUfDxQ4WYDFOVqetB10U/tDL/iimZxmiCok36bDOF2Ku1jWiUFv3r7Bv
	Y/OX+bbamCLxm8oq9O20Nq1LCkx6CKjl206oOlH1/tZRR6Ad+Zijczm+MLVs5RuA5D871a
	3UKRbff3pCaO3iwoRpI3VHBH2sN53Iu5TpC2oGQjwVAlMXRr4RdP035NlTBQ3WsWuPZfsv
	C8uTvfLp0QclbTjIAiVOvfCuafukgFlaX2+q4JgX3+LH1nCxkFJ/ffMfOtWQOPxXOKQS0G
	MHlZiBhOs+Pca5tx5+ETIzgCgOo8LVyPmVOkEgE3w4TkXt1ZMV8wWtwdLC8pVLkA==
Received: by recvd-57d69887f8-d9srt with SMTP id recvd-57d69887f8-d9srt-1-67FF71CA-70
	2025-04-16 09:00:58.961952468 +0000 UTC m=+643966.782144264
Received: from smtp.sendgrid.net (unknown)
	by geopod-ismtpd-5 (SG)
	with ESMTP
	id GNsDz2cIQayH_82GGMm2xA
	Wed, 16 Apr 2025 09:00:58.829 +0000 (UTC)
Date: Wed, 16 Apr 2025 09:00:59 +0000 (UTC)
From: hello@openfoodnetwork.org.uk
Message-ID: <67ff71ca88d7a_1a85061b94075019@uk-prod.mail>
Subject: [Open Food Network UK] Order cycle report for Forest Fungi
Mime-Version: 1.0
Reply-To: [Hub Email]
X-SG-EID: 
 =?us-ascii?Q?u001=2E83eZEDHdXp6aJm=2FdI=2F9Fi1DmF8rNPdbiGbv43hrKsx9BqYQwWGfBKyzpx?=
 =?us-ascii?Q?dw98xLvuwf5=2FPGLSgLcbPG7Typ3kZ7S7H0Qz1Ai?=
 =?us-ascii?Q?IGQuOYMuGu8qVkLQ3hwvc0LbwsoVi=2F70KUjJRyw?=
 =?us-ascii?Q?6D3Ohxf+ebUcphzPeq9Ai87w8wTNBIbK=2FM7T3Wn?=
 =?us-ascii?Q?3xqsjMba7ZLDaaeCDFiy6FGDv=2FJHd1nWE+zqlD0?=
 =?us-ascii?Q?JkmGGI8wyDqH5DPc9ySsjs=3D?=
To: [Producer Email]
Cc: [Hub Email]
X-Entity-ID: u001.2UPdBk753qwjWvyTxqkZpw==
Content-Type: multipart/alternative;
 boundary="--==_mimepart_67ff71ca84bd0_1a85061b940749ec";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Authentication-Results: mx.infomaniak.com; spf=pass smtp.mailfrom=em9402.openfoodnetwork.org.uk
X-Spam-Score: 11
X-Spam-Detail: gggruggvucftvghtrhhoucdtuddrgeefvddrtddtgddvvdehleehucetufdoteggodetrfdotffvucfrrhhofhhilhgvmecukffphffqofetpffktefmnecuuegrihhlohhuthemucfpsdetnecutfgtvhguucffrghtvgcurghnohhmrghlhiculddvuddmnefjrghmjfgvrgguvghrhfhivghlugcujfgvrgguvghrucfutghorhhinhhgucdlqddutddmnecujfgurhepfffhkffugghrvfevtgfgsegrjeerredttdejnecuhfhrohhmpehhvghllhhosehophgvnhhfohhoughnvghtfihorhhkrdhorhhgrdhukhenucggtffrrghtthgvrhhnpeevkeefhfffheeuleegffegffekhfeiudefvdehhefhleeutdejiefhhfetueektdenucffohhmrghinhepohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhknecukfhppedugeelrdejvddrvddvtddrudekkeenucevlhhushhtvghrufhiiigvpedtnecurfgrrhgrmhepihhnvghtpedugeelrdejvddrvddvtddrudekkedphhgvlhhopehouddrphhtrhejkeelhedrohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhkpdhmrghilhhfrhhomhepsghouhhntggvshdivdeufeekvddtvdejvdekqdejiedvrgdqhhgvlhhlohdifeffohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhksegvmhelgedtvddrohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhkpdhnsggprhgtphhtthhopedupdhrtghpthhtohephhgvlhhlohesohhpvghnfhh
 oohgunhgvthifohhrkhdrohhrghdruhhkpdhsphhfpehprghsshgmpdgukhhimhepphgrshhs
X-Infomaniak-Type: ham
X-Infomaniak-Spam: ham
X-Infomaniak-Cause: gAAAAABn_3HNdtskmLsBuwgT2qB3CJG9CXcu8IFwRQc9hx-wOAZea2RWMXOGZn70HnjGdlbaVXR_GtGZkX5Am26cH4dl-EQM9BchAjsN0Wg98QyErGTN2aRsTd_-clHebh1Gl7cUoHHu6v2G_vh71DSZRTCJXDJOWhbC1cO5-q7o1OzXZAZmsp8_F0mI0H3dgZO5N46Y-8AkxN2JKvkVC6L063K3_kMNx8iTzytaG9zM7RmssViM2OqcOee3APPYXHajubmXzxOTSpTs_nR_1qAIkHI6NWxtkTkv3T-I59BjZsHF405fLpH3NnZNmn0RqL7HuTng4-P2-IrEYcWjYe3EED59Lyv3yKDGgk5rmgkQn4n8-V_YBTk=
</details>

<details> <summary>Email header 2</summary>
X-Antivirus: avg (VPS 25041600)
X-Antivirus-Status: Clean
Return-Path: <bounces+38202728-762a-hello=openfoodnetwork.org.uk@em9402.openfoodnetwork.org.uk>
Delivered-To: hello@openfoodnetwork.org.uk
Received: from smtp-3-9000.mail.infomaniak.ch ([10.4.36.130])
	by mda-3-0341.mail.infomaniak.ch with LMTP
	id uKrgNPBx/2dwmzcADqYp3Q
	(envelope-from <bounces+38202728-762a-hello=openfoodnetwork.org.uk@em9402.openfoodnetwork.org.uk>)
	for <hello@openfoodnetwork.org.uk>; Wed, 16 Apr 2025 11:01:36 +0200
Authentication-Results: mx.infomaniak.com; dmarc=pass (p=none dis=none) header.from=openfoodnetwork.org.uk
Authentication-Results: mx.infomaniak.com;
	dkim=pass (2048-bit key; unprotected) header.d=openfoodnetwork.org.uk header.i=@openfoodnetwork.org.uk header.a=rsa-sha256 header.s=s1 header.b=up8qfIJE;
	dkim-atps=neutral
Received: from o1.ptr7895.openfoodnetwork.org.uk (o1.ptr7895.openfoodnetwork.org.uk [149.72.220.188])
	by smtp-3-9000.mail.infomaniak.ch (Postfix) with ESMTPS id 4Zcw4c0MQTzqnJ
	for <hello@openfoodnetwork.org.uk>; Wed, 16 Apr 2025 11:01:35 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=openfoodnetwork.org.uk;
	h=from:subject:mime-version:reply-to:to:cc:content-type:
	content-transfer-encoding:cc:content-type:from:subject:to;
	s=s1; bh=vh/E9ym2/Hh4sEk5Y0ZQGOI2WjB5llv49I4a/z28jyk=;
	b=up8qfIJEkMv2JXNYpdss+eMKagDw2XaNS47Vo9/Mmea0vM9JgiwsGvwzC4MrMrcGmGNW
	NKdi34BUKmUrCigmyvdPORJ/9aDRWQpBmbXV3fIft/SfKMrVTvfkFs6dz7eTesX5mjBWvC
	nBsfWFftRX3nFTMUaWydIZO8nSVZaDXp3Vd6Mg2fni0K33sY6atjTxk+tPtz9ob2yH3TMQ
	Fg2iX2nDfDLJaFxsjywwEOoJuP2KyIhBmfFxok1J3zoK7uT3T35EtRPpj6VKB5uALUX0tx
	xc4FOq1UtWs+A7cfA1tyjcYpKHZsOJrt8qzMjBNUh4Akt36sccQBTEoUJy1ywvIQ==
Received: by recvd-65bb6cdcb5-p7669 with SMTP id recvd-65bb6cdcb5-p7669-1-67FF71EE-4E
	2025-04-16 09:01:34.460857919 +0000 UTC m=+644003.305339938
Received: from smtp.sendgrid.net (unknown)
	by geopod-ismtpd-1 (SG)
	with ESMTP
	id Kn7vKVISSFKNqYgp6G-96Q
	Wed, 16 Apr 2025 09:01:34.328 +0000 (UTC)
Date: Wed, 16 Apr 2025 09:01:34 +0000 (UTC)
From: hello@openfoodnetwork.org.uk
Message-ID: <67ff71eeea1c_1a85061ba4477434@uk-prod.mail>
Subject: [Open Food Network UK] Order cycle report for Forest Fungi
Mime-Version: 1.0
Reply-To: [Hub Email]
X-SG-EID: 
 =?us-ascii?Q?u001=2E83eZEDHdXp6aJm=2FdI=2F9Fi1DmF8rNPdbiGbv43hrKsx9BqYQwWGfBKyzpx?=
 =?us-ascii?Q?dw98xLvXX6VO2tIxYdwQ7ISlDqyjAqstsmypbYk?=
 =?us-ascii?Q?7xbPv95f0lxpOcBngfvwMLqfjjOaQnWimkNoszk?=
 =?us-ascii?Q?pwngQuPvkULoHOep5=2FgwLbePyc4ooMCzjiXx766?=
 =?us-ascii?Q?STtq=2FjJ6xjTJgQ7Ay7xW8HKHpCLhZZBST6fxCBF?=
 =?us-ascii?Q?vtwAVvl5pXuzHhW49tR8gI=3D?=
To: [Producer Email]
Cc: [Hub Email]
X-Entity-ID: u001.2UPdBk753qwjWvyTxqkZpw==
Content-Type: multipart/alternative;
 boundary="--==_mimepart_67ff71eeb00a_1a85061ba44773e7";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Authentication-Results: mx.infomaniak.com; spf=pass smtp.mailfrom=em9402.openfoodnetwork.org.uk
X-Spam-Score: 11
X-Spam-Detail: gggruggvucftvghtrhhoucdtuddrgeefvddrtddtgddvvdehleehucetufdoteggodetrfdotffvucfrrhhofhhilhgvmecukffphffqofetpffktefmnecuuegrihhlohhuthemucfpsdetnecutfgtvhguucffrghtvgcurghnohhmrghlhiculddvuddmnefjrghmjfgvrgguvghrhfhivghlugcujfgvrgguvghrucfutghorhhinhhgucdlqddutddmnecujfgurhepfffhkffugghrvfevtgfgsegrjeerredttdejnecuhfhrohhmpehhvghllhhosehophgvnhhfohhoughnvghtfihorhhkrdhorhhgrdhukhenucggtffrrghtthgvrhhnpeevkeefhfffheeuleegffegffekhfeiudefvdehhefhleeutdejiefhhfetueektdenucffohhmrghinhepohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhknecukfhppedugeelrdejvddrvddvtddrudekkeenucevlhhushhtvghrufhiiigvpedunecurfgrrhgrmhepihhnvghtpedugeelrdejvddrvddvtddrudekkedphhgvlhhopehouddrphhtrhejkeelhedrohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhkpdhmrghilhhfrhhomhepsghouhhntggvshdivdeufeekvddtvdejvdekqdejiedvrgdqhhgvlhhlohdifeffohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhksegvmhelgedtvddrohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhkpdhnsggprhgtphhtthhopedupdhrtghpthhtohephhgvlhhlohesohhpvghnfhh
 oohgunhgvthifohhrkhdrohhrghdruhhkpdhsphhfpehprghsshgmpdgukhhimhepphgrshhs
X-Infomaniak-Type: ham
X-Infomaniak-Spam: ham
X-Infomaniak-Cause: gAAAAABn_3Hw9c-iYCdRUBFweP3g2Oodp-qbOB-9SPoareE4Q9tKY9Vry8ClK88wVzfO7SgeKt3UAHuJ-sspatROVmxYplXMI5jWcpTFM67P51zSwYiW3opMssIc5qomdKXSlEumtJ9ZnL1sobIEo0_8ebI000m-rAQt-XeXh5Dq_nOOTsZNTacFAqi4NmO9iFsAYlQzPG7KeONRvjModknD3CzivkPD40AfQJcYEwY9v2v_0ZAVv-sTx75Inr8zgXhZYX-yoNWDBacnt2_elBbPmF-hBeU8_HxBP0EWW-b_CclR-GWajilABH_5mCxF_Q-wC8WG6VXoM3aDMV6Tyq7tNFeqX68O4xTuXtUl9d70h2OHxbd3d4U=
</details>

<details> <summary>Email header 3</summary>
X-Antivirus: avg (VPS 25041600)
X-Antivirus-Status: Clean
Return-Path: <bounces+38202728-762a-hello=openfoodnetwork.org.uk@em9402.openfoodnetwork.org.uk>
Delivered-To: hello@openfoodnetwork.org.uk
Received: from smtp-3-9002.mail.infomaniak.ch ([10.4.36.132])
	by mda-3-0341.mail.infomaniak.ch with LMTP
	id CNoSFR1y/2cupjcADqYp3Q
	(envelope-from <bounces+38202728-762a-hello=openfoodnetwork.org.uk@em9402.openfoodnetwork.org.uk>)
	for <hello@openfoodnetwork.org.uk>; Wed, 16 Apr 2025 11:02:21 +0200
Authentication-Results: mx.infomaniak.com; dmarc=pass (p=none dis=none) header.from=openfoodnetwork.org.uk
Authentication-Results: mx.infomaniak.com;
	dkim=pass (2048-bit key; unprotected) header.d=openfoodnetwork.org.uk header.i=@openfoodnetwork.org.uk header.a=rsa-sha256 header.s=s1 header.b=sbQo5WId;
	dkim-atps=neutral
Received: from o1.ptr7895.openfoodnetwork.org.uk (o1.ptr7895.openfoodnetwork.org.uk [149.72.220.188])
	by smtp-3-9002.mail.infomaniak.ch (Postfix) with ESMTPS id 4Zcw5S21sMzrvl
	for <hello@openfoodnetwork.org.uk>; Wed, 16 Apr 2025 11:02:20 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=openfoodnetwork.org.uk;
	h=from:subject:mime-version:reply-to:to:cc:content-type:
	content-transfer-encoding:cc:content-type:from:subject:to;
	s=s1; bh=n62KYJad+0/wQ4a0rh5/vCff+1qBYdwmkhN7QeG46i4=;
	b=sbQo5WId3THLjerq/t0RIX+MwDC1glS4/qrDNfOp0wdq5LL/UPAtJl7knYQyPaq++O65
	/XpIhTENVJsC0DcArkBBBHgipVFUtycj986PG3cse+Rt6PxrnEmxK7Po3d4ei9x8QXivCg
	FLDrTsOXBHCcseK4LMidF07BxsnvqJ/OvElPxrtTxap2D1wWwrdycJ/cz3/yIRQ0/sSwGf
	LwWduLIupvHX0cCr79AJWsNZp5M1lxDhtWv5vgugNyFGUANt04Vje++Q860uKDWDa4T0QC
	Sh9JSoZt8QLpaTdeyYGwfhi8xWOkhEwiY7MbFLdkHdE5GNCBe9uk0ro/0TQVyjTA==
Received: by recvd-6884bf9dd7-c8hg5 with SMTP id recvd-6884bf9dd7-c8hg5-1-67FF721A-3D
	2025-04-16 09:02:18.528168858 +0000 UTC m=+644044.930025981
Received: from smtp.sendgrid.net (unknown)
	by geopod-ismtpd-7 (SG)
	with ESMTP
	id EaZ1N64VT0OxDmYOljcFaQ
	Wed, 16 Apr 2025 09:02:18.420 +0000 (UTC)
Date: Wed, 16 Apr 2025 09:02:18 +0000 (UTC)
From: hello@openfoodnetwork.org.uk
Message-ID: <67ff721a4d0f5_1a85061ba1c7952f@uk-prod.mail>
Subject: [Open Food Network UK] Order cycle report for Forest Fungi
Mime-Version: 1.0
Reply-To: [Hub Email]
X-SG-EID: 
 =?us-ascii?Q?u001=2E83eZEDHdXp6aJm=2FdI=2F9Fi1DmF8rNPdbiGbv43hrKsx9BqYQwWGfBKyzpx?=
 =?us-ascii?Q?dw98xLv36B7Qu3b412HGe4T9TNq4UEUoNqGycRs?=
 =?us-ascii?Q?Yzn2zOK4qDQ8owKrySs+UNZ=2Frov7i4gkBhH4eTL?=
 =?us-ascii?Q?00+h+2Gza3rGAPXeSs3nNUR2a3db8OQClCUUdiB?=
 =?us-ascii?Q?XJhdYFx9rCyJLezkrUkkdelnp4MUQ6ssCteSm9c?=
 =?us-ascii?Q?BCHXB9PpNvLAuVY82wfvYk=3D?=
To: [Producer Email]
Cc: [Hub Email]
X-Entity-ID: u001.2UPdBk753qwjWvyTxqkZpw==
Content-Type: multipart/alternative;
 boundary="--==_mimepart_67ff721a49c17_1a85061ba1c79432";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
Authentication-Results: mx.infomaniak.com; spf=pass smtp.mailfrom=em9402.openfoodnetwork.org.uk
X-Spam-Score: 11
X-Spam-Detail: gggruggvucftvghtrhhoucdtuddrgeefvddrtddtgddvvdehleeiucetufdoteggodetrfdotffvucfrrhhofhhilhgvmecukffphffqofetpffktefmnecuuegrihhlohhuthemucfpsdetnecutfgtvhguucffrghtvgcurghnohhmrghlhiculddvuddmnefjrghmjfgvrgguvghrhfhivghlugcujfgvrgguvghrucfutghorhhinhhgucdlqddutddmnecujfgurhepfffhkffugghrvfevtgfgsegrjeerredttdejnecuhfhrohhmpehhvghllhhosehophgvnhhfohhoughnvghtfihorhhkrdhorhhgrdhukhenucggtffrrghtthgvrhhnpeevkeefhfffheeuleegffegffekhfeiudefvdehhefhleeutdejiefhhfetueektdenucffohhmrghinhepohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhknecukfhppedugeelrdejvddrvddvtddrudekkeenucevlhhushhtvghrufhiiigvpedtnecurfgrrhgrmhepihhnvghtpedugeelrdejvddrvddvtddrudekkedphhgvlhhopehouddrphhtrhejkeelhedrohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhkpdhmrghilhhfrhhomhepsghouhhntggvshdivdeufeekvddtvdejvdekqdejiedvrgdqhhgvlhhlohdifeffohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhksegvmhelgedtvddrohhpvghnfhhoohgunhgvthifohhrkhdrohhrghdruhhkpdhnsggprhgtphhtthhopedupdhrtghpthhtohephhgvlhhlohesohhpvghnfhh
 oohgunhgvthifohhrkhdrohhrghdruhhkpdhsphhfpehprghsshgmpdgukhhimhepphgrshhs
X-Infomaniak-Type: ham
X-Infomaniak-Spam: ham
X-Infomaniak-Cause: gAAAAABn_3IdgLfGgxYF5jfh0iYhAyWaiQoXMaYXm-QCGobe_8rZr4_MvVhhq1XVL8qHJp0fpSwmOzqQr8ALKcELOcwRBvP3uic_ucY763AhKcIMDpXcy6vr1E9Cd5SrMwXvZHQQeRgC9b_oS8WQuxtlcPrKPVFGSknQ8M-i05XztsLxictyA-6dh5jVVVccFoGCQoXBvOtKoZgg5Y9HOFC3cieITNBcRijw4Tf1TPsYgP8fkUzl5yPR2kKeRp-KZlCC2SardAm5NCsoA4aEfbe93LVm09IIwPT4DT-MJyFaaqsG33K7qfWlqA-r7n_HAMv91ecDXh0RjAG9cpN_CrynLSKOu4g9phcPuYl-iVAFm7FZ_KhOWmI=
 </details>

I can provide more headers if needed.

## Severity

bug-s2 

This is causing confusion for producers thinking they've received more orders than they actually have, and clogging up the inboxes of hubs who are CC'd on every producer notification.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

I am unsure if this is related to the recent changes to 'reply-to' email address a the users first noticed it on April 2nd, after [Add a 'reply to' email address to some more emails #13176](https://github.com/openfoodfoundation/openfoodnetwork/pull/13176) was released.

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Errors or delays can cause multiple duplicate emails to the same suppliers.

- Closes #13278 

#### What should we test?

- Producer notifications after order cycle close.
- Additional production test.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/jobs/order_cycle_notification_job_spec.rb [hunk 1]
```diff
@@ -4,20 +4,18 @@
...
+    }.to enqueue_mail(ProducerMailer, :order_cycle_report).twice
   end
 
   it "records that mails have been sent for the order cycle" do
-    expect do
+    expect {
       OrderCycleNotificationJob.perform_now(order_cycle.id)
-    end.to change{ order_cycle.reload.mails_sent? }.from(false).to(true)
+    }.to change {
+      order_cycle.reload.mails_sent?
```
Comment (dacook) [inline spec/jobs/order_cycle_notification_job_spec.rb:18]: Hmm, now `mails_sent` means "mails enqueued".

Before, it was run in serial so we could know at the end if mails were all sent successfully or not. Now we don't know. Does that matter?

It looks like `mails_sent` is used to d
1. display an email success icon on the order cycle edit page, and 
2. enable a "re-notify" button.

I think no. 1 would be best served by a "mails sent" , and no2 would be better as "mails enqueued". So.. I think it's all close enough that it doesn't matter. 👍

**Review by dacook — APPROVED** [review]
Great investigation and fix!

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Comment by filipefurtad0** [comment]
Hi @mkllnk,

I've tested this PR with the following steps:

- enabled the option to automatically notify producers, on the Advanced order cycle options
- set up an order cycle to open in a future time
- waited till the OC opens and closes

The assertions:
- the notify producers email arrives
- the `Notify producers` button changes to image, and displays a green check
image

- the button is re-enabled and works as expected (clicking it delivers an additional order cycle notification email)

This looks good. Let's hear back from production on this one? I've marked it as a production test. Merging!
