### PR TITLE
Avoid double processing payment

### LINKED ISSUE #7130: Payment status of 'Failed' but Stripe show a successful payment
## Description

Order R063002374
Enterprise Sole of Discretion (ID: )

Customer places order on 5th March and pays by Stripe.
Payment recorded for £121 on 5th March associated with the order is complete in Sole of Discretion's Stripe account
sodstripe

Email sent to sole of discretion and customer states the payment was complete
sodemailpayment

An adjustment was made to the order on 11th March
sodadjustments

Payment status of the order is currently showing as failed
sodpayments

## Expected Behavior

The payment status of an order on the OFN platform should reflect the status of the transaction in the hub's Stripe account.

## Actual Behaviour

The payment status of an order does not reflect the payment status of the transaction in the hub's Stripe account.

## Steps to Reproduce

1. Checkout paying via Stripe.
2. When Stripe redirects you back to OFN, quickly reload the page. The timing can be tricky here and it's difficult to tell if you got it right.
3. Check the order as admin and observe the state to be "payment" and the payment to be failed.

## Workaround

Never reload during payments. A developer can reset the state of the order.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
**bug-s2: a non-critical feature is broken, no workaround**
bug-s3: a feature is broken but there is a workaround
bug-s4: it's annoying, but you can use it
bug-s5: we can live with it, only a few users impacted

https://github.com/openfoodfoundation/openfoodnetwork/wiki/Bug-severity

These categories don't fit well but s2 seems apt.

## Your Environment

* Version used: v3.5.12
* Browser name and version: Chrome 89
* Operating System and version (desktop or mobile):

## Possible Fix

This method ignores the possibility that the payment may be complete already:
https://github.com/openfoodfoundation/openfoodnetwork/blob/06deab9605ca67a024911f576d113e415be63475/lib/stripe/payment_intent_validator.rb#L25-L29

We should log the status here. If the intent is complete, we should either ignore it here or further up the caller chain. We don't want to capture again but gracefully return in this method:
https://github.com/openfoodfoundation/openfoodnetwork/blob/06deab9605ca67a024911f576d113e415be63475/app/models/spree/gateway/stripe_sca.rb#L36-L48

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #7130

Well, this is based on my theory of how the issue could have happened. We will see over time if the Bugsnag error re-appears. This happened only once in production.

#### What should we test?

1. Checkout paying via Stripe.
2. When Stripe redirects you back to OFN, quickly reload the page. The timing can be tricky here and it's difficult to tell if you got it right.
3. Check the order as admin. If the order is in "payment" state and the payment is failed, the bug is still present. If the payment is still complete and the order is good as well then the bug has been fixed.

I saw that @filipefurtad0 triggered this 12 times in staging. So I hope you won't be able to reproduce it again. :smile: 
I think that the checkout redirects you to the cart page which may be confusing for users. But that's a different issue (not s2) and at least the order has been processed.

#### Release notes

Changelog Category: User facing changes

Fix a rare bug that showed a failed Stripe payment even though it was successful.

### CODE REVIEW

File: spec/controllers/checkout_controller_concurrency_spec.rb [hunk 1]
```diff
@@ -42,12 +42,15 @@
...
+
+    # Avoid setting headers as Rails 5 is not thread-safe here:
+    allow(controller).to receive(:restrict_iframes)
   end
 
   # This spec does not seem to be running in two threads in Rails 5. There are errors for the
   # same response headers being set twice, possibly indicating that there is only one response
   # as opposed to two separate requests in two threads?
-  xit "handles two concurrent orders successfully" do
+  it "handles two concurrent orders successfully" do
```
Comment (sauloperez) [inline spec/controllers/checkout_controller_concurrency_spec.rb:53]: we need to work on making this test more resilient if we want to enable it back. It's very very flaky.

**Review by sauloperez — CHANGES_REQUESTED** [review]

File: spec/controllers/checkout_controller_concurrency_spec.rb (hunk 1 above)
Comment (Matt-Yorkley) [reply spec/controllers/checkout_controller_concurrency_spec.rb:53]: I think I disabled this during the Rails 5 upgrade because it was failing ~90% of the time...

**Review by Matt-Yorkley — APPROVED** [review]
LGTM, lets run the specs a few times and see what happens.

File: spec/controllers/checkout_controller_concurrency_spec.rb (hunk 1 above)
Comment (luisramos0) [reply spec/controllers/checkout_controller_concurrency_spec.rb:53]: I think I commented this out. I spent some time on this test and my conclusion after some serious debugging is that this test was invalid, the breakpoint was not working so the threads were just running one after the other all the time.

**Review by andrewpbrett — APPROVED** [review]
Seems worth a shot, nice sleuthing @mkllnk

File: spec/controllers/checkout_controller_concurrency_spec.rb (hunk 1 above)
Comment (mkllnk) [reply spec/controllers/checkout_controller_concurrency_spec.rb:50]: Thank you all for raising your points. That made me double-check:

> It's very very flaky.

First, I tested if the the spec fails reliably. I commented out the pessimistic locking and ran the spec a dozen times. It always failed. :heavy_check_mark: 

Second, I ran the code that should pass 100 times. It passed 100 times. :heavy_check_mark: 

Third, I ran the specs 20 more times with my CPU maxed out with other processes. They all passed again. :heavy_check_mark: 

> my conclusion after some serious debugging is that this test was invalid, the breakpoint was not working so the threads were just running one after the other all the time.

I had to stub `#restrict_iframes` because the app ended up in an invalid state. It tried to add headers in the second thread when the first sent them already. That made me think that the requests are executed concurrently.

I read through the code and noticed that the mutex lock wasn't used though. I'm surprised that the spec failed so reliably without the lock. It's lucky but it could accidentally pass even if the code is not syncing properly.

Looking through the history I found commit b0fa1464f of PR #6119 which took the usage of the breakpoint out. @sauloperez and @luisramos0 approved that PR without realising that it would make the spec unreliable. And that's totally understandable because that code was using a random, unrelated but convenient method to synchronise the threads. I wonder how we can make the test easier to understand.

The purpose of the lock is to ensure that both threads load the order and complete all the before_action checks first. And only after both threads did all the checks and are waiting for the lock, we release the lock and they both try to process the checkout at the same time with stale objects. That is the flow when the test is failing.

If the controller uses pessimistic locking correctly, then the second thread is waiting before any of the before_action checks. Those checks run after the first thread finished and see the processed order correctly.

I re-added the synchronisation via the mutex lock to make the spec reliably fail (even though it was doing that on my machine already). I then re-ran 100 tests passing and 100 test failing. It worked as expected. The intentional failures were quite varied because the two threads race unpredictably. Here are some examples:

```
     StateMachines::InvalidTransition:
       Cannot transition state via :restart_checkout from :complete (Reason(s): State cannot transition via "restart checkout")

     AbstractController::DoubleRenderError:
       Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like "redirect_to(...) and return".

     ActiveRecord::StatementInvalid:
       PG::TRDeadlockDetected: ERROR:  deadlock detected
```

The DoubleRenderError is probably a bug in our code but out of scope here. Please have a look at the new commit and let me know if you understand it and if we can make it easier to understand. I was able to use a newer rspec syntax now that's hopefully clearer.

**Comment by andrewpbrett** [comment]
I'm going to move this to test ready; it would be good to discuss more about https://github.com/openfoodfoundation/openfoodnetwork/pull/7208#discussion_r601943813 but we could also just see if it's flaky again and revisit the discussion if necessary.

**Comment by filipefurtad0** [comment]
Hey @mkllnk ,

As on #7175 ([testing notes](https://github.com/openfoodfoundation/openfoodnetwork/pull/7175#issuecomment-808312168)), I've tried to reproduce the error, but was not really able to.

I refreshed the page, either several times, or in slightly different moments during re-direction back to OFN. This led to the same result:
- clicking "refresh" led to the OFN home page -> a regular checkout (without hitting "reload") redirects the customer to the order confirmation page (`/orders/<order_number>`) 

Even in such cases, the order was in a "complete" state, this was checked as admin.

In no moment I could observe this statement (redirects to `/cart`):
> I think that the checkout redirects you to the cart page which may be confusing for users. But that's a different issue (not s2) and  at least the order has been processed.

But as mentioned, it does not relate to this PR. Do we have an issue for this? If so, we need to clarify the circumstances this redirect occurs.

Anyway, it seems we are good to merge this PR (green build, manual testing - OK) - moving to ready to go.

File: spec/controllers/checkout_controller_concurrency_spec.rb (hunk 1 above)
Comment (sauloperez) [reply spec/controllers/checkout_controller_concurrency_spec.rb:50]: ups, yes, we totally missed that PR removing the syncing :see_no_evil:

**Review by sauloperez — APPROVED** [review]

**Comment by mkllnk** [comment]
>     I think that the checkout redirects you to the cart page which may be confusing for users. But that's a different issue (not s2) and at least the order has been processed.
> 
> ... Do we have an issue for this? If so, we need to clarify the circumstances this redirect occurs.

I don't think so. But it's also an error state we may never end up in. I don't think that we need to create an issue if we can't re-produce it.
