### PR TITLE
[vouchers] fix delete voucher when tax excluded from price

### LINKED ISSUE #11183: [Vouchers] With tax excluded from price, deleting a voucher doesn't work properly
## Description
When addding a voucher to an order with tax excluded from price, it will create two adjustment , one for the voucher amount and one for the tax component.
Currently when trying to remove a voucher on the checkout it will only remove one of the adjustment, so it appears like the delete didn't work.

## Expected Behavior
When deleting a voucher on the checkout payment step, the voucher is actually deleted. And we see the voucher input and "Apply" button

## Actual Behaviour
When deleting a voucher on the checkout payment step, only part of the voucher is deleted. Nothing seems to happen and the voucher is still displayed with the "Remove code" link

## Steps to Reproduce

Assuming you have voucher enabled, have an enterprise set up with a voucher and have set up a tax excluded from price 
1. Add something to the cart, and proceed to checkout
2. Proceed to payment step
3. Add a voucher 
4. Delete voucher by clicking on the "remove code"
5. Voucher should be deleted and "Enter voucher code" input shoud be visible

## Workaround

The workaround is to try to delete the voucher again, after the second time it would have removed both adjustment and should work as expected.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #11183 

Fix deleting a vouchers when used with a tax excluded from price

#### What should we test?

Assuming you have voucher enabled, have an enterprise set up with a voucher and have set up a tax excluded from price 
- Add something to the cart, and proceed to checkout
- Proceed to payment step
- Add a voucher
- Delete voucher by clicking on the "remove code"
- Voucher should be deleted and "Enter voucher code" input should be visible

#### Release notes

Changelog Category: User facing changes 

The title of the pull request will be included in the release notes.

#### Dependencies
This PR #11135 will need to merged first

### CODE REVIEW

**Review by mkllnk — APPROVED** [review]
:+1:

File: app/controllers/voucher_adjustments_controller.rb [hunk 1]
```diff
@@ -15,7 +15,11 @@ def create
   end
 
   def destroy
-    @order.voucher_adjustments.find_by(id: params[:id])&.destroy
+    # An order can have more than one adjustment linked to one voucher
+    adjustment = @order.voucher_adjustments.find_by(id: params[:id])
+    if adjustment.present?
+      @order.voucher_adjustments.where(originator_id: adjustment.originator_id)&.destroy_all
```
Comment (dacook) [inline app/controllers/voucher_adjustments_controller.rb:21]: Part of me wants to suggest that we move the knowledge about what the originator_id is used for, to the `VoucherAdjustmentsService` (which already has this knowledge). But.. I'm probably overthinking it.

**Review by dacook — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @rioug,

Thanks for the issue and the detailed steps on what to test. I've verified the issue, by going through these steps:

- Add something to the cart, and proceed to checkout
- Proceed to payment step
- Add a voucher
- Delete voucher by clicking on the "remove code"

Outcome:
- Voucher was not deleted, just a confirmation modal.
- Only when clicking a second time was the voucher actually removed

After staging the PR and repeating the steps above, changed the outcome:
- Voucher was deleted and "Enter voucher code" input became visible

Looks good! Merging.
