### PR TITLE
[Enterprise Fees] Keep fees on product when a product is removed from the order cycle

### LINKED ISSUE #13100: Fees wrongly removed when an order is modified after products have been removed from the order cycle
## Description
It happens that hubs or shops remove some products from the order cycle (OC) during the OC. It succeeds for instance if the producer needs to stop orders before the OC finish.
In that case, If the hub/shop admin change an order, for instance deleting a product that was not available, the commission and fees are calculated again. But if there are products previously removed from the OC in the order those products remain (expected behaviour), but their fees are deleted. The result is that the credit owed is not only the price of deleted product, but also includes the fees wrongly removed.
In practice, we have a Hub in France that has just realized it had made numerous excessive reimbursements.
(while writing this issue I have acknowledged that it happens also when customer modify its own order)

## Expected Behavior
When products are removed from an order cycle, modifying the order should not change the fees associated with the products included in order that were removed of the order cycle after they were bought.

## Actual Behaviour
The fees are deleted, which leads to wrong and too high credit owed information.

## Steps to Reproduce

1. As a shop owner I remove 2 products from an order cycle. Those products were previously ordered by a customer : 

Image

2. Edit an order. In this example, I will delete "Yourts Coulis de fruits... ". I expect the credit owe should be product price (2,20) + associated fee (0,24) = 2,44

Image

3. As you can see here not only product fee associated with the product removed from order are cancelled but also the product fee linked to Yaourts nature. Consequently the credit owed is 2.66 € instead of 2.44 €

Image
 
Please note that in this example the product modified in order was removed from order cycle, but it is not relevant.

Here is another example where this is the customer who modify its own order : 
1 - Order issued by customer : 

Image

2 - The hub admin removes "Yourts coulis de fruits par 4*125g - Yaourt coulis abricot par 4 " from order cycle

3 - The customer decides to delete 1 product from its order. The new price should be 13,32 €, but it is 13,08 €

Image

## Workaround
Re-introducing products in the order cycle before modifying orders is a workaround, but not possible if the customer modify its own order.

## Severity

bug-s1: a critical feature is broken: checkout, payments, signup, login
This bug causes errors in the order amounts. It is a function in which users should have complete trust.

## Your Environment
Examples on Coopcircuits.fr

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #13100 

Currently when an order gets updated all enterprise fees are deleted and recreated to ensure it's up to date. This is an issue when a product has been removed from an Order Cycle, any subsequent update to the order will remove fees associated with said product. To prevent this, we now create or update per item enterprise fees, per order fee are still deleted and recreated.

An easier way to fix the issue is to assume any product in the order are from the Order Cycle linked to the order, so we could keep the delete and recreate solution. However, currently Order Cycle are not mandatory on the Order, and there is no check to ensure a product is the Order Cycle when adding/updating an order.

#### What should we test?

In general we want to test that enterprise fee per item are working as before. In particular we want to make sure fees are applies to only product they are supposed to apply to. Previous attempt at fixing this bug resulted in a S1 #13217 

As an enterprise manager :

* Create an order cycle with per item fee on incoming variants and another fee on outgoing variant. Make sure to include multiple supplier each using their own fees.

As a customer

* place an order with a couple of different product.

##### 1. Removing variant

As an enterprise manager:

* Search for the just placed order and open the edit page
* ensure both fees were applied
* remove on outgoing variant
* on the order edit page, Click on "update and recalculate fees!"
    --> check the outgoing fee is still present
* remove the incoming variant
* on the order edit page, Click on "update and recalculate fees!"
    --> check the incoming fee is still present
* update the removed product quantity
    --> check the fess are re calculated as expected

As a customer
* place an order with an enterprise that allow updating order (see Enterprise configuration -> Shop Preference)
 
As an enterprise manager
* Remove a variant from the order cycle use for the order, make sure it's a variant that's part of the order

As a customer
* Edit your order
    --> Check the fees have not been removed to the variant removed from the Order Cycle

##### 2. Removing fee

* remove a fee from the Order Cycle,
* on the order edit page, Click on "update and recalculate fees!"
    --> Check the fee has been removed
* Go to Configuration -> Enterprise Fees
* Remove a fee associated to the Order Cycle
* on the order edit page, Click on "update and recalculate fees!"
    --> Check the fee has been removed
* Remove a variant from the order cycle
* Run the scenario above
    --> Check the fee has been removed for the removed variant

##### 3. Adding fee

* add a fee to the Order Cycle
* on the order edit page, Click on "update and recalculate fees!"
    --> Check the fee has been added
* Remove a variant from the order cycle
* Run the scenario above
    --> Check fee has been added to the removed variant

Try adding and removing fees when the same fee is applied to the incoming and outgoing exchange, the appropriate supplier or distributor fee should be added or removed. 

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/services/orders/handle_fees_service.rb [hunk 1]
```diff
@@ -58,6 +64,57 @@ def update_order_fees!
...
+
+    def delete_removed_fees!(line_item)
+      order_cycle_fees = order_cycle_per_item_enterprise_fee_for
+
+      removed_fees = line_item.enterprise_fee_adjustments.where.not(originator: order_cycle_fees)
+
+      removed_fees.each(&:destroy)
+    end
+
+    def order_cycle_per_item_enterprise_fee_for
```
Comment (dacook) [inline app/services/orders/handle_fees_service.rb]: "for..."?  This method returns an array of per_item enterprise_fees, so how about:
```suggestion
    def order_cycle_per_item_enterprise_fees
```

(Ah, I see this method was copied from `per_item_enterprise_fee_applicators_for(variant)`)

File: lib/open_food_network/enterprise_fee_applicator.rb [hunk 2]
```diff
@@ -20,6 +20,7 @@ def create_adjustment(label, adjustable)
       AdjustmentMetadata.create! adjustment:, enterprise: enterprise_fee.enterprise,
                                  fee_name: enterprise_fee.name, fee_type: enterprise_fee.fee_type,
                                  enterprise_role: role
+      adjustment
```
Comment (dacook) [inline lib/open_food_network/enterprise_fee_applicator.rb:23]: Good idea, it would be pretty confusing to call create_adjustment and receive an AdjustmentMetadata object instead!

File: app/services/orders/handle_fees_service.rb [hunk 3]
```diff
@@ -16,21 +18,30 @@ def recreate_all_fees!
...
+      order.line_items.includes(:variant).each do |line_item|
+        # No fee associated with the line item so we just create them
+        if line_item.enterprise_fee_adjustments.blank?
+          create_line_item_fees!(line_item)
+          next
         end
+        create_or_update_line_item_fee!(line_item)
+
+        # delete any fees removed from the Order Cycle
+        delete_removed_fees!(line_item)
```
Comment (dacook) [inline app/services/orders/handle_fees_service.rb:44]: We can only see what fees were removed if we still have a reference to the OC. 
If there's no reference to OC, can we skip it?
```suggestion
        delete_removed_fees!(line_item) if provided_by_order_cycle?
```

**Review by dacook — COMMENTED** [review]
Wow, it sure is complicated. I'm very thankful to have you working through this!
It looks pretty good but I can't take it all in, in one sitting so will finish reviewing tomorrow.

File: spec/services/orders/handle_fees_service_spec.rb [hunk 4]
```diff
@@ -4,24 +4,263 @@
...
+  let(:order) {
+    create(:order_with_line_items, line_items_count: 1, order_cycle:,
+                                   distributor: order_cycle.distributors.first)
+  }
   let(:line_item) { order.line_items.first }
 
   let(:service) { Orders::HandleFeesService.new(order) }
   let(:calculator) {
-    double(OpenFoodNetwork::EnterpriseFeeCalculator, create_order_adjustments_for: true)
+    instance_double(OpenFoodNetwork::EnterpriseFeeCalculator, create_order_adjustments_for: true)
```
Comment (dacook) [inline spec/services/orders/handle_fees_service_spec.rb:15]: Given that the specs already have a distributor and order cycle record, I wonder if it wouldn't hurt to just use a real EnterpriseFeeCalculator.

```suggestion
    OpenFoodNetwork::EnterpriseFeeCalculator.new(order_cycle.distributors.first, order_cycle)
```

It would then be easier to remove some of the mocks below and use data instead.

**Review by dacook — APPROVED** [review]
Great, epic job. I found it hard to follow, probably largely because I haven't worked with fees much and it's such a complex system.

The specs provide really clear guardrails around what should happen, well done 👍 
I noticed a lot of mocking of the EnterpriseFeeCalculator in the specs and though it might be worth using more real data. 

But I'm not sure if it's worth changing, so I approve as-is :)

File: app/services/orders/handle_fees_service.rb (hunk 3 above)
Comment (rioug) [reply app/services/orders/handle_fees_service.rb:44]: `HandleFeeService` knows the OC via the order, so we can actually remove fees even on variant that are not provided by the OC. This is consistent with the current behaviour, so we wouldn't want to change that.

File: spec/services/orders/handle_fees_service_spec.rb (hunk 4 above)
Comment (rioug) [reply spec/services/orders/handle_fees_service_spec.rb:15]: This was the original testing approach, so I kept it. I think it's fine to mock here given the `EnterpriseFeeCalculator` is something we wrote, and by using an instance double we have additional checks to make sure mocked method do exist on the real implementation.
Technically if you use a real `EnterpriseFeeCalculator` it becomes integration testing.

File: app/services/orders/handle_fees_service.rb (hunk 3 above)
Comment (dacook) [reply app/services/orders/handle_fees_service.rb:44]: Right, sorry for my misunderstanding

File: spec/services/orders/handle_fees_service_spec.rb (hunk 4 above)
Comment (dacook) [reply spec/services/orders/handle_fees_service_spec.rb:15]: Good points.

> Technically if you use a real `EnterpriseFeeCalculator` it becomes integration testing.

Would that be a bad thing? I'm not sure we have a rule that all `services` specs must be pure unit tests. I thought that integration tests would be more valuable.

**Review by chahmedejaz — APPROVED** [review]
Looks Good 🎉

**Comment by filipefurtad0** [comment]
Hey @rioug ,

I've set up an order cycle in the following way:

image

image

image

Set up the following permissions:
```

Baguette Producer 	permits 	Baguette Coordinator 	to add to order cycle
Baguette distributor 	permits 	Baguette Coordinator 	to add to order cycle
Baguette Producer 	permits 	baguette distributor 	to add to order cycle
Flour Producer 	        permits 	baguette distributor 	to add to order cycle
Flour Producer 		permits 	Baguette Coordinator 	to add to order cycle 
```

And placed orders with items from the two producers:

image

The fees are correctly attributed and:

**(tests on variants)**
- removing an outgoing variant and updating the order (order edit page) -> does not change the order total or how the fees were applied

image


- removing an incoming variant and updating the order (order edit page) -> does not change the order total or how the fees were applied

image


**(tests on fees - removing)**
- removing an outgoing fee and updating the order (order edit page) -> removes the fee and changes the order total

image

- removing an incoming fee and updating the order (order edit page) -> removes the fee and changes the order total

image

**(tests on fees - adding)**
- adding an outgoing fee and updating the order (order edit page) -> removes the fee and changes the order total

image

- adding an incoming fee and updating the order (order edit page) -> removes the fee and changes the order total

image

I'll need a break on this one for now, and to double check the values. Also, I think it's a good opportunity to review the respective system spec. More on this later!

**Comment by nicolasVr** [comment]
Hi! Will this PR be included in the prod release soon ?
We have a shop who uses refunds intensively and is very impacted by this bug. He now has also problems when refunding products with stock=0. I’m asking myself if it is worth making more investigations now, and maybe file an issue, or if it is clever to wait for the release of this PR.

**Comment by filipefurtad0** [comment]
Hi @nicolasVr ,

If all goes well, yes - it should be in the release next week.

**Comment by nicolasVr** [comment]
Ok, I will test and document the bug.

**Comment by filipefurtad0** [comment]
This looks good to go @rioug.

> I think it's a good opportunity to review the respective system spec.

I did not manage to finish this before release prep. The spec looks ok, but there are some details on the setup that could perhaps be improved (I'm thinking, adding the respective enterprise permissions). Maybe this won't change the assertions, but it might change some values. Anyway, I'm happy to make a proposal on a PR this week.

Merging! :rocket:
