### PR TITLE
[Spree Upgrade] Specify :mailer type in specs

### LINKED ISSUE #3039: [Spree Upgrade] Fix producer_mailer spec (9 broken tests)
Some basic email sending problem needs to be fixed here.

Example:
```
30) ProducerMailer includes receival instructions
      Failure/Error: mail.body.encoded.should include 'Outside shed.'
      
      NoMethodError:
        undefined method `body' for nil:NilClass
      # ./spec/mailers/producer_mailer_spec.rb:66:in `block (2 levels) in <top (required)>'

```

We probably need to fix #2882 first.

### PR DESCRIPTION
**Pull request by sauloperez**
#### What? Why?

Closes #3039

According to RSpec docs, we need to specify `type: :mailer` for mails to work. Check it out: https://relishapp.com/rspec/rspec-rails/v/3-8/docs/mailer-specs.
    
This fixes all specs in `producer_mailer_spec.rb`.

### CODE REVIEW

File: spec/mailers/producer_mailer_spec.rb [hunk 1]
```diff
@@ -47,12 +46,8 @@
     order.save
     order
   end
-  let(:mail) { ActionMailer::Base.deliveries.last }
 
-  before do
-    ActionMailer::Base.deliveries.clear
-    ProducerMailer.order_cycle_report(s1, order_cycle).deliver
-  end
+  let(:mail) { ProducerMailer.order_cycle_report(s1, order_cycle).deliver }
```
Comment (mkllnk) [inline spec/mailers/producer_mailer_spec.rb]: Do we need `deliver` here? I didn't see that in the documented example.

Comment (sauloperez) [reply spec/mailers/producer_mailer_spec.rb]: Good point. I'm not sure I tried removing it

Comment (sauloperez) [reply spec/mailers/producer_mailer_spec.rb]: Certainly not needed. Thanks @mkllnk !
