### PR TITLE
Patch Rails :deep_munge issue so empty array parameters don't get converted to nil

### LINKED ISSUE #6224: Unable to remove Coordinator Fee from Order Cycle
## Description

Once an enterprise fee has been selected for 'Add Coordinator Fee' (page 1 of hub OC: General Settings), it can not be removed (it can be changed to a different enterprise fee though)

## Expected Behavior

1. Create Order Cycle and add Coordinator Fee to page 1 (General Settings)
cfee1
2. Complete the rest of the Order cycle set up and return to Order Cycle List
3. Edit Order Cycle
4. Remove Coordinator Fee and press save 
cfee2
5. Return to Order Cycle List
6. Edit Order Cycle for 2nd time.
7. No Enterprise Fee is present on page 1 (General Settings) under the Coordinator Fee section.

## Actual Behaviour

1-5 as Expected Behaviour
6. Edit Order Cycle for 2nd time.
7. Enterprise Fee removed in step 4 is present.
cfee1

## Steps to Reproduce

1. Create Order Cycle with Coordinator Fee, return to Order Cycle list
2. Edit Order Cycle created in step 1
3. Remove Coordinator fee and press save. Return to Order Cycle list
4. Edit Order Cycle for a 2nd time and note that Coordinator fee removed in step 3 is reinstated.

## Workaround

Close the Order Cycle and open a new one without the associated fee.

## Severity

bug -s3
The work around is annoying as a lot of hubs will clone order cycles. If the OC which they clone has a coordinator fee but the one they wish to set up doesn't then they will have to spend extra time creating a new OC from scratch

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by cillian**
#### What? Why?

Before people were unable to remove coordinator fees from an order cycle because [Rails was converting the empty :coordinator_fee_ids array parameter into nil](https://github.com/rails/rails/issues/13420). This issue was introduced to Rails in v4.0.0.beta1 and isn't fixed [until v5.0.0.beta1](https://github.com/rails/rails/commit/8f8ccb9901cab457c6e1d52bdb25acf658fd5777)

We could avoid the monkey patch :see_no_evil: by do something like `params[:coordinator_fee_ids] ||= []` but it seems like this issue could cause problems in other parts of the app so perhaps a general fix might be better until Rails v5.

Closes #6224

#### What should we test?

See _Steps to reproduce_ in #6224 

#### Release notes

Fix removing of coordinator fees from order cycles.

Changelog Category: User facing changes

### CODE REVIEW

File: spec/lib/action_dispatch/request_spec.rb [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+  end
+
+  it "doesn't convert an empty array to nil" do
+    assert_parses({ "key" => [] }, 'key[]')
+  end
+
+  private
+
+  def assert_parses(expected, actual)
+    assert_equal expected, ActionDispatch::Request.new('QUERY_STRING' => actual).query_parameters
```
Comment (Matt-Yorkley) [inline spec/lib/action_dispatch/request_spec.rb:16]: We generally use `Rspec` syntax in specs instead of `Test::Unit`, so this would be:
```ruby
expect(expected).to eq(ActionDispatch::Request.new('QUERY_STRING' => actual).query_parameters)
```

**Review by Matt-Yorkley — APPROVED** [review]
I left a comment, and there's a couple of Rubocop issues, but LGTM :+1:

**Review by luisramos0 — APPROVED** [review]

**Comment by cillian** [comment]
Doh, forgot to run Rubocop again but I have fixed those issues up now. Let me know if it needs any more changes.

**Comment by luisramos0** [comment]
Looks good, thanks. Moving to test ready.

**Comment by filipefurtad0** [comment]
Hey @cillian ,

Thank you for addressing this!

I verified the issue before staging, following @lbwright22 detailed "steps to reproduce"  :+1: 
Adding to these steps, I checked whether adding/removing the coordinator fee was taking effect in the shopfront (seen for example, under Price Breakdown).

After staging the PR, it was verified that adding and removing the coordinator fee from that OC - Clicked "Remove", "Save" and "Back to List" was working and the issue was solved. Also, checked the shopfront for the expected fee removal.

All good, awesome - thanks for this Cillian!

I was thinking whether this Rails 4 issue could cause any unnoticed problems anywhere else in the app, so looked around a bit as well but found nothing. Anyway, moved to ready to go! :+1:
