### PR TITLE
Fix an issue which prevented filtering by properties and sorting by category on a shopfront.

### LINKED ISSUE #9046: Property filters on shopfronts not functioning
## Description

User clicks to apply any of the properties filters to items (e.g. certified organic, nut free, vegan etc) and no filtering occurs. Raised by customer of one specific hub and I've replicated across multiple hubs. 

## Expected Behaviour

Clicking a property filter on a shop should filter the items displayed to those tagged with the property (e.g. clicking certified organic should show only items with the certified organic property). 

## Actual Behaviour

Clicking a property filter does not trigger any filtering. Applying a category filter first functions as expected, but clicking a category filter _after_ clicking a property filter also fails to filter any products. 

## Steps to Reproduce

1. Go to any shopfront with properties e.g. Tamar Valley Food Hub
2. Click a property filter (e.g. certified organic, gluten free)
3. Observe lack of filtering of item lists
4. Now apply a category filter (e.g. herbs & spices)
5. Observe lack of category filtering

## Animated Gif/Screenshot

Kapture 2022-03-29 at 09 36 09

## Workaround

No workaround

## Your Environment

* Version used: UK prod
* Browser name and version: Version 99.0.4844.51 (Official Build) (arm64)
* Operating System and version (desktop or mobile): Mac OS Big Sur 11.6.2

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #9046

Removing the `distinct` keyword that cause SQL error when using `ORDER BY column_name=value`

#### What should we test?
- On a hub, enable sorting by category
Capture d’écran 2022-04-12 à 17 17 46

- Then, on the shopfront, filter by a property and a category. 
- You should see the concerned products:
Capture d’écran 2022-04-12 à 17 18 49

#### Release notes

Fix an issue which prevented filtering by properties and sorting by category on a shopfront.

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by jibees** [comment]
When sorting and filtering by property the error is: 
```
PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
       LINE 10: ...id" = $6) GROUP BY "spree_products"."id" ORDER BY spree_prod...
```
and the generated sql is:
```sql
SELECT DISTINCT "spree_products".*
FROM "spree_products"
LEFT OUTER JOIN "spree_product_properties" ON "spree_product_properties"."product_id" = "spree_products"."id"
LEFT OUTER JOIN "enterprises" ON "enterprises"."id" = "spree_products"."supplier_id"
LEFT OUTER JOIN "producer_properties" ON "producer_properties"."producer_id" = "enterprises"."id"
LEFT OUTER JOIN "spree_properties" ON "spree_properties"."id" = "producer_properties"."property_id"
WHERE "spree_products"."deleted_at" IS NULL
  AND "spree_products"."id" IN
    (SELECT DISTINCT spree_variants.product_id
     FROM "spree_variants"
     INNER JOIN "exchange_variants" ON "exchange_variants"."variant_id" = "spree_variants"."id"
     INNER JOIN "exchanges" ON "exchanges"."id" = "exchange_variants"."exchange_id"
     INNER JOIN "spree_stock_items" ON "spree_stock_items"."deleted_at" IS NULL
     AND "spree_stock_items"."variant_id" = "spree_variants"."id"
     LEFT OUTER JOIN
       (SELECT *
        FROM inventory_items
        WHERE enterprise_id = 6252) AS o_inventory_items ON o_inventory_items.variant_id = spree_variants.id
     LEFT OUTER JOIN variant_overrides ON variant_overrides.variant_id = spree_variants.id
     OR (variant_overrides.id IS NOT NULL
         AND (variant_overrides.on_demand IS TRUE
              OR variant_overrides.count_on_hand > 0))
     OR (variant_overrides.id IS NOT NULL
         AND (variant_overrides.on_demand IS NULL
              AND spree_stock_items.backorderable IS TRUE))
     OR (variant_overrides.id IS NOT NULL
         AND (variant_overrides.on_demand IS NULL
              AND spree_stock_items.backorderable IS FALSE
              AND spree_stock_items.count_on_hand > 0))))
  AND ("spree_products"."inherits_properties" = TRUE
       AND "producer_properties"."property_id" = 15
       OR "spree_product_properties"."property_id" = 15)
GROUP BY "spree_products"."id"
ORDER BY spree_products.primary_taxon_id=3026 DESC,
         spree_products.primary_taxon_id=3024 DESC,
         spree_products.name ASC,
         spree_products.id ASC
```

When sorting only, here is the sql:
```sql
SELECT "spree_products".*
FROM "spree_products"
WHERE "spree_products"."deleted_at" IS NULL
  AND "spree_products"."id" IN
    (SELECT DISTINCT spree_variants.product_id
     FROM "spree_variants"
     INNER JOIN "exchange_variants" ON "exchange_variants"."variant_id" = "spree_variants"."id"
     INNER JOIN "exchanges" ON "exchanges"."id" = "exchange_variants"."exchange_id"
     INNER JOIN "spree_stock_items" ON "spree_stock_items"."deleted_at" IS NULL
     AND "spree_stock_items"."variant_id" = "spree_variants"."id"
     LEFT OUTER JOIN
       (SELECT *
        FROM inventory_items
        WHERE enterprise_id = 6252) AS o_inventory_items ON o_inventory_items.variant_id = spree_variants.id
     LEFT OUTER JOIN variant_overrides ON variant_overrides.variant_id = spree_variants.id
     AND variant_overrides.hub_id = 6252
     WHERE (o_inventory_items.id IS NULL
            OR o_inventory_items.visible = (TRUE))
       AND "exchanges"."order_cycle_id" = 1703
       AND "exchanges"."incoming" = FALSE
       AND "exchanges"."receiver_id" = 6252
       AND "spree_variants"."deleted_at" IS NULL
       AND ((variant_overrides.id IS NULL
             AND (spree_stock_items.backorderable IS TRUE
                  OR spree_stock_items.count_on_hand > 0))
            OR (variant_overrides.id IS NOT NULL
                AND (variant_overrides.on_demand IS TRUE
                     OR variant_overrides.count_on_hand > 0))
            OR (variant_overrides.id IS NOT NULL
                AND (variant_overrides.on_demand IS NULL
                     AND spree_stock_items.backorderable IS TRUE))
            OR (variant_overrides.id IS NOT NULL
                AND (variant_overrides.on_demand IS NULL
                     AND spree_stock_items.backorderable IS FALSE
                     AND spree_stock_items.count_on_hand > 0))))
GROUP BY "spree_products"."id"
ORDER BY spree_products.primary_taxon_id=3026 DESC,
         spree_products.primary_taxon_id=3024 DESC,
         spree_products.name ASC,
         spree_products.id ASC
```

**Comment by jibees** [comment]
Ok, found it.
```sql
SELECT DISTINCT "spree_products".*
FROM "spree_products"

GROUP BY "spree_products"."id"
ORDER BY spree_products.primary_taxon_id=3026 DESC,
         spree_products.primary_taxon_id=3024 DESC,
         spree_products.name ASC,
         spree_products.id ASC
```
is not valid due to `spree_products.primary_taxon_id=3026`

_But_,
```sql
SELECT DISTINCT "spree_products".*, spree_products.primary_taxon_id=3026, spree_products.primary_taxon_id=3024
FROM "spree_products"

GROUP BY "spree_products"."id"
ORDER BY spree_products.primary_taxon_id=3026 DESC,
         spree_products.primary_taxon_id=3024 DESC,
         spree_products.name ASC,
         spree_products.id ASC
```
is valid.

So now, I should either:
 - remove the `distinct` keyword
 - add the `spree_products.primary_taxon_id=3026` in the select clause

**Comment by jibees** [comment]
Wait https://github.com/openfoodfoundation/openfoodnetwork/pull/9083 to be merged (or cherry-pick commits) before merging this one.

File: spec/services/products_renderer_spec.rb [hunk 1]
```diff
@@ -26,23 +26,62 @@
...
+        it "filters products with property when sorting is enabled" do
+          allow(distributor).to receive(:preferred_shopfront_taxon_order) { "#{t1.id},#{t2.id}" }
+          p1.product_properties.create!({ property_id: pa.id, value: '1', position: 1 })
+          p2.product_properties.create!({ property_id: pa.id, value: '1', position: 1 })
+          p3.product_properties.create!({ property_id: pa.id, value: '1', position: 1 })
+          p4.product_properties.create!({ property_id: pa.id, value: '1', position: 1 })
+          products_renderer = ProductsRenderer.new(distributor, order_cycle, customer, { q: { with_properties: [pa.id] } })
+          products = products_renderer.send(:products)
+          expect(products).to eq([p2, p4, p1, p3])
+        end
```
Comment (mkllnk) [inline spec/services/products_renderer_spec.rb:83]: This is difficult to understand. It looks like you are creating four of the same and then expect a different order. `p1` could be a "product" or a "property" and looking it up requires to go back to the top of the file.

Some ideas:

- We can give the products proper names. For example *apples*, *bananas* and so on. The alphabetical order is then clear.
- We can also name the other variables like `farmer_john` the supplier and `vegetables` the taxon and `organic` the property.
- Use a property value that gives a meaning. `A grade` would be before `organic`. Or we use `A grade` and `B grade`.

File: app/models/spree/product.rb [hunk 2]
```diff
@@ -78,8 +78,7 @@ class Product < ApplicationRecord
         where(producer_properties: { property_id: property_ids }).
         or(
           where(spree_product_properties: { property_id: property_ids })
-        ).
-        distinct
```
Comment (mkllnk) [inline app/models/spree/product.rb:82]: I'm a bit worried about the implications here. The `distinct` was added because the scope uses `left_outer_joins` and that can multiply the product rows if a product has multiple properties.

The sorting query doesn't seem to use the joins. It uses grouping instead. But the non-sorting query could now produce too many rows. Did you test that?

Comment (jibees) [reply app/models/spree/product.rb:82]: I've _tested_ by changing the implementation of `spec/controllers/api/v0/order_cycles_controller_spec.rb`:

```ruby
expect(product_ids).to eq [product1.id, product2.id]
```
instead of
```ruby
expect(product_ids).to include product1.id, product2.id
```

I thought it was enough, but maybe I'm wrong.

File: spec/services/products_renderer_spec.rb [hunk 3]
```diff
@@ -9,7 +9,7 @@
   let(:customer) { create(:customer) }
   let(:products_renderer) { ProductsRenderer.new(distributor, order_cycle, customer) }
 
-  describe "sorting" do
+  context "sorting and filtering" do
```
[the remark this answers is not in the document]
Comment (jibees) [reply spec/services/products_renderer_spec.rb:12]: > Just wondering why you preferred context here?

I've no answer to this... Will modify to `describe`

File: app/models/spree/product.rb (hunk 2 above)
Comment (mkllnk) [reply app/models/spree/product.rb:82]: I see. I had another look and when I call `with_properties` with multiple properties and a product has several of them then the product appears several times. But ransack seems to add the grouping which de-duplicates the records and everything is fine.

At the moment, this scope is only used with ransack and only in this one controller, I think. And it works here. We just have to be aware of this if we ever try to use this scope in a different context.

File: spec/controllers/api/v0/order_cycles_controller_spec.rb [hunk 4]
```diff
@@ -68,7 +68,7 @@ module Api
                              q: { with_properties: [property1.id, property2.id] }
 
           expect(response.status).to eq 200
-          expect(product_ids).to include product1.id, product2.id
+          expect(product_ids).to eq [product1.id, product2.id]
```
Comment (mkllnk) [inline spec/controllers/api/v0/order_cycles_controller_spec.rb:71]: Both products have only one property. If you assign property2 to product1 as well then you are testing for duplication. I did that locally and it works. It may be worth adding though, to avoid regressions in the future.

**Review by mkllnk — APPROVED** [review]
All good. Just one suggestion about improving the spec.

File: spec/services/products_renderer_spec.rb (hunk 1 above)
Comment (jibees) [reply spec/services/products_renderer_spec.rb]: Done !

File: spec/services/products_renderer_spec.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (jibees) [reply spec/services/products_renderer_spec.rb]: Done !

File: spec/controllers/api/v0/order_cycles_controller_spec.rb (hunk 4 above)
Comment (jibees) [reply spec/controllers/api/v0/order_cycles_controller_spec.rb:71]: Right. I'v added `property2` to `product1` !

**Review by georgethoppil — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]
I love your new naming! :star: Now I want to buy that stuff. :yum:

**Comment by filipefurtad0** [comment]
Hey @jibees ,

Thanks for this fix!

I made a quick check here:
- reproducing the scenario which triggered the bug renders all products :+1: 
- filters work as before :+1: 

Peek 2022-04-22 11-00


Good to go :tada:
