### PR TITLE
Admin, Orders list: when capturing an order, fix an issue that makes the tooltip invisible (+ errors in the console)

### LINKED ISSUE #10956: [Orders page] Uncaught Error: Missing target element "tooltip" for "tooltip" controller - missing Ship order Icon
## Description

Capturing a payment triggers the error:

```
          Ferrum::JavaScriptError:
            Error: Missing target element "tooltip" for "tooltip" controller
                at extended.get (http://127.0.0.1:43907/packs-test/js/admin-b37e4fa00b2104ec0263.js:49200:15)
                at _this.showTooltip (http://127.0.0.1:43907/packs-test/js/admin-b37e4fa00b2104ec0263.js:3946:13)

```

This makes specs fail and hides the ship order icon, which was previously visible

## Expected Behavior

Tooltip for the ~~edit~~ shipping orders icon should be visible for as before.

## Actual Behaviour

Tooltip for the ~~edit~~ orders icon is not visible.

## Steps to Reproduce

1. As a hub, visit the /orders page; open the console.
2. Mouse-hover on the pencil icon. Notice the missing tooltip.
3. Capture a payment -> this should trigger the error on the console

## Animated Gif/Screenshot

image

## Workaround

None, I guess.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: 4.3.11
* Browser name and version: Firefox 113
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

- Closes #10956

~~We should use `cable_ready.inner_html` instead of `morph` to be sure that every stimulus controllers attached to the DOM that is replaced is will connected. Actually, I don't know why, this is empirical. What I saw is that when using `morph`, the stimulus controller (specially `tooltip_controller`) were not attached to the DOM (and not disconnected as well) that triggered some errors in the console.~~

This explains nicely what is happening here: https://github.com/stimulusreflex/stimulus_reflex/issues/314#issuecomment-702479357
>In the context of SR (Stimulus Reflex), the expectation is that you would specify the UI you want to exist in the browser on the server. There's no need for a render stage because the markup is already perfect before it is sent down the wire. There is no build stage, no rehydration. We're not taking over the task of redrawing the UI from the browser.

The tooltip controller was adding some html element to the page on connect, which doesn't play well with StimulusReflex. So we refactored the controller and use a partial to populate tooltip content. 

#### What should we test?

- As a hub manager, go to `/admin/orders`
- Capture a payment with the small icon on the right
- Once the order has been captured, see that you can display the tooltips for this order (on each action icons)

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/reflexes/admin/orders_reflex.rb [hunk 1]
```diff
@@ -8,8 +8,13 @@ def capture
...
       if payment_capture.call
-        morph dom_id(@order), render(partial: "spree/admin/orders/table_row",
-                                     locals: { order: @order.reload, success: true })
+        cable_ready.inner_html(
+          selector: dom_id(@order),
+          html: render(partial: "spree/admin/orders/table_row",
+                       locals: { order: @order.reload, success: true })
+        ).broadcast
+
+        morph :nothing
```
Comment (mkllnk) [inline app/reflexes/admin/orders_reflex.rb:17]: That's an interesting observation. It sounds like a bug in StimulusReflex to me. I don't like this new pattern but if it works then it's good.

I tried to find any information about why this is happening. And I found an interesting section in the docs:

> `inner_html` completely wipes out any Stimulus controllers present in the replaced DOM hierarchy and doesn't respect the data-reflex-permanent attribute. How can we adapt this so that both morph operations are performed by the morphdom library?
> https://docs.stimulusreflex.com/guide/morph-modes.html#real-world-example-pagy-refactoring

So there's a difference between inner_html and morphdom and morphdom seems to keep as much as possible, therefore not disconnecting and reconnecting controllers. I think it tries to update the existing tooltip elements without replacing them.

Maybe a problem of the tooltip controller is that it renders the tooltip on connect and is not aware of data attribute changes after that.

Another thing I found is: 

> You cannot change the attributes of your morph target.
> https://docs.stimulusreflex.com/appendices/troubleshooting.html#you-cannot-change-the-attributes-of-your-morph-target

So either solution means that the `tr` attribute for order state never updates. This is probably a pre-existing bug. But looking at [morphdom](https://github.com/patrick-steele-idem/morphdom) it seems to be able to update attributes on the target. So, I'm not sure where that limitation comes from or if the warning is only there in case StimulusReflex decides to replace inner_html only (which it seems to do in some cases).

Maybe we should test if the state change is a problem and then we need to use outer_html. Otherwise we are good.

**Review by mkllnk — APPROVED** [review]

File: app/reflexes/admin/orders_reflex.rb (hunk 1 above)
Comment (rioug) [reply app/reflexes/admin/orders_reflex.rb:17]: I think this describe quite neatly the issue and the recommended solution here : 
https://github.com/stimulusreflex/stimulus_reflex/issues/314#issuecomment-702479357

I am wondering if we should rewrite the tooltip stimulus controller to use `stimulus-reflex:after` callback as described above, it seems to me to be the better approach. It would prevent the issue in any other page that uses the tooltip controller.As it stands, the onus is on the reflex to do the correct render, and I feel like it's not its job to have to worry about any stimulus controller it's not interacting directly with. 

That said the stimulus docs do describe the pattern used here : https://docs.stimulusreflex.com/guide/cableready.html#using-cableready-inside-a-reflex-action 

What do you guys think ?

Comment (mkllnk) [reply app/reflexes/admin/orders_reflex.rb:17]: Thank you for the links, Gaetan, very interesting. I didn't know that you could also queue cable_ready events without broadcasting them immediately and that they get then broadcasted after the StimulusReflex morph.

I guess the idealistic solution for the tooltip is to render the tooltip server-side and include it in the morphing partial. Hm, that's actually already done in other places. Do we just need to get rid of `insertToolTipMarkup` and replace it with a partial?

Comment (rioug) [reply app/reflexes/admin/orders_reflex.rb:17]: I believe original intend was to use a partial : https://github.com/openfoodfoundation/openfoodnetwork/commit/b76d9045ce733c61c32919cbf51eeae37c2c48fd but then Matt did some refactoring here : https://github.com/openfoodfoundation/openfoodnetwork/commit/d64a9afece84105e96e591bb935726ff489bff6c which led to the current behaviour.

I had a go at using `stimulus-reflex` callbacks, I can trigger a re render but for some reason it's not finding the data attributes linked to the element with the tooltip controller :confused:  

From the linked I shared above :  
> In the context of SR (Stimulus Reflex), the expectation is that you would specify the UI you want to exist in the browser on the server. There's  no need for a render stage because the markup is already perfect before it is sent down the wire. There is no build stage, no rehydration. We're not taking over the task of redrawing the UI from the browser.

I'll look at moving back to a partial.

**Review by mkllnk — APPROVED** [review]
Nice, this is great.

File: app/views/admin/shared/_tooltip_button.html.haml [hunk 2]
```diff
@@ -0,0 +1,7 @@
+%div{ "data-controller": "tooltip" }
+  %button{class: button_class, "data-reflex": button_reflex, "data-id": reflex_data_id, "data-tooltip-target": "element" }
+  .tooltip-container
+    .tooltip{"data-tooltip-target": "tooltip"}
+      = sanitize tooltip_text
```
Comment (dacook) [inline app/views/admin/shared/_tooltip_button.html.haml:5]: Would it not be sanitised automatically?

File: spec/system/admin/orders_spec.rb [hunk 3]
```diff
@@ -443,8 +443,9 @@
 
         it "displays a note with order instructions" do
           within "tr#order_#{order3.id}" do
-            expect(page).to have_content I18n.t('spree.admin.orders.index.note')
-            expect(page).to have_css "[data-tooltip-tip-value='#{order3.special_instructions}']"
+            expect(page).to have_content "Note"
+            find(".icon-warning-sign").hover
+            expect(page).to have_content /#{order3.special_instructions}/i
```
Comment (dacook) [inline spec/system/admin/orders_spec.rb:448]: 🏅

**Review by dacook — COMMENTED** [review]
Looks good! 👍  I just have a query about the need for `sanitize`.

File: app/views/admin/shared/_tooltip_button.html.haml (hunk 2 above)
Comment (rioug) [reply app/views/admin/shared/_tooltip_button.html.haml:5]: I believe rails escape html automatically but does not sanitize unless you do it manually.

**Review by dacook — APPROVED** [review]
Argh, looking back I'm sorry I stalled this while you were on leave. 

Thanks for responding. Looking at this again, I can see `tooltip_text` comes from the locale, so it shouldn't require any further sanitising.
But I can also see that it was copy/pasted from existing code, so all good 👍 

I don't want to stall it anymore, so will move to test ready when specs pass!

**Comment by drummer83** [comment]
Hi @rioug,
Thanks for finishing this PR! :muscle: 

## Before staging
- I could see the error message in the browser console.
ksnip_20231018-103343

- I could see the missing tooltip after capturing a payment. After reloading the page, the tooltip was back.
- I could see the missing 'Ship' icon after capturing a payment. However I think the icon is there but it has very little contrast compared to the background (the icon is not changing its color back to blue when removing the mouse hovering). After clicking anywhere else on the page to release the focus, the icon is back.

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/389609ab-8431-4f66-8bed-3bc729d5ae47

## After staging
- The error in the browser console is gone. :heavy_check_mark: 
- The tooltip remains visible at all times. :heavy_check_mark: 
- The 'Ship' icon is stll 'missing' (invisible) after capturing a payment. :x: 

https://github.com/openfoodfoundation/openfoodnetwork/assets/1790176/7f5941dc-09bb-422d-a586-503a051df17a

## Summary
I will merge this one because it's fixing two out of three issues. 
For the remaining invisible 'Ship' icon I will create a new issue.

Thanks again! :tada:
