### PR TITLE
Fix javascript logic that parses server errors in the bulk product edit page

### LINKED ISSUE #3120: Error when editing products from product list page
## Description

When editing and saving "unit" column on the products page, the following message appears when you choose "item" unit but don't fill the box: _not saved._ _There was an error saving unsupported data: 400_. Instead, by doing the same editing procedure from the product details page, the error message is: _variant unit name can't be blank_ which is much more understandable to users.

## Expected Behavior

The error message that appears when leaving unit box empty in "Unit" column from products list on "Poducts page" should be the same as the one that appears by editing products from "product details page".

## Actual Behavior

If you edit an existing product on product list and change any unit to "item" but leave empty unit box the error message is not clear to users: _not saved_There was an error saving unsupported data_.

## Steps to Reproduce

1. Sign as a producer. 
2. Go to products > products page.
3. Edit one product of the list expanding the details on product page.
4. Change Unit column from any unit to item.
5. Leave empty the box below (type of item).
6. Save the changes you edited.

## Context

Editing some product details from diferent products from the same producer (like "display as", "value", or "price").

## Severity

bug-s4

## Your Environment

* Version used: v1.24.0 
* Browser name and version: Firefox 63.0.3
* Operating System and version (desktop or mobile): Windows 7

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #3120 
This PR fixes the error message handling in bulk product update page, the errors structure coming from the server was not being parsed correctly by the javascript code.
The JS code and the server code were introduced in the [same commit](https://github.com/openfoodfoundation/openfoodnetwork/commit/5fea15e8a93e1ad29d6610b5fd14b6fc4497093a
) but the original server "errors" object could have been an array and now it's a structure with keys. I decided to leave the code that parses errors as an array in case that happens in some situations.

#### What should we test?
Verify the bulk product update page still works as normal (basic tests) and make sure you get appropriate error messages for the errors you manage to generate in the page (I am not sure what these could be, maybe we will find there's more we can do here). Most importantly if you leave variant unit name empty you should see this now:
image

#### Release notes
Changelog Category: Changed
Improved error messages on the bulk product edit page.

### CODE REVIEW

**Comment by Matt-Yorkley** [comment]
Needs a rebase...

File: app/assets/javascripts/admin/utils/services/errors_parser.js.coffee [hunk 1]
```diff
@@ -2,16 +2,25 @@
 angular.module("admin.utils").factory "ErrorsParser", ->
   new class ErrorsParser
     toString: (errors, defaultContent = "") =>
+      return defaultContent unless errors?
+
+      errorsString = ""
       if errors.length > 0
         # it is an array of errors
-        errorsString = error + "\n" for error in errors
+        errorsString = this.arrayToString(errors)
```
Comment (kristinalim) [inline app/assets/javascripts/admin/utils/services/errors_parser.js.coffee]: Maybe you can use `errors.join("\n")` here instead?

File: app/assets/javascripts/admin/utils/services/errors_parser.js.coffee [hunk 2]
```diff
@@ -2,16 +2,25 @@
...
       else
         # it is a hash of errors
         keys = Object.keys(errors)
-        errorsString = ""
         for key in keys
-          errorsString += error for error in errors[key]
+          errorsString += this.arrayToString(errors[key])
```
Comment (kristinalim) [inline app/assets/javascripts/admin/utils/services/errors_parser.js.coffee]: (But need to add the trailing newline after each key here if going to use `Array#join`.)

File: app/assets/javascripts/admin/utils/services/errors_parser.js.coffee (hunk 1 above)
Comment (luisramos0) [reply app/assets/javascripts/admin/utils/services/errors_parser.js.coffee]: ah, yes, thanks. done :+1:

File: app/assets/javascripts/admin/utils/services/errors_parser.js.coffee (hunk 2 above)
Comment (luisramos0) [reply app/assets/javascripts/admin/utils/services/errors_parser.js.coffee]: thanks for the heads up, could have forgotten this :+1:

**Comment by sauloperez** [comment]
Feel free to move it to Test Ready once you get the tests passing @luisramos0

**Comment by luisramos0** [comment]
:+1:
@kristinalim please shout if you see something wrong here.

**Comment by luisramos0** [comment]
I forgot to add the trailing break line to the case where errors come as an array. fixed now.

**Comment by RachL** [comment]
The original issue is fixed and bulk update sanity check went good.

This is ready to go!

image

**Comment by luisramos0** [comment]
nice :-)

**Comment by sauloperez** [comment]
Nice! this is a good one!
