### PR TITLE
[Orders Page] Fix Confirmation modals do not auto-close

### LINKED ISSUE #12982: Order cancel error
## Description
Screenshot 2024-11-18 at 19 05 51

On the Order List secreen selecting a list of orders and chosing action to cancel these orders freezes the app.
Also the attached error appears in the console.

## Expected Behavior
User is able to cancel orders from list.

## Actual Behaviour
Order cancel freezes the app.

## Steps to Reproduce
It maybe only an issue on the Hungarian instance.

Open Orders List.
Select some items.
Choose Cancel Orders action.

## Workaround
None

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by chahmedejaz**
#### What? Why?

- Closes #12982 ,  #12803

- **Context:** https://github.com/openfoodfoundation/openfoodnetwork/issues/12982#issuecomment-2499096920
- This PR fixes auto-close functionality for all the Orders Page confirmation modals after the confirmation.
- Moreover, it also fixes the `flatpickr invalid locale hu error` as mentioned in the issue

#### What should we test?

- Validate that you can cancel the order
- And after cancelation, the modal is closed automatically
- Along with the above, please validate the following modals such that when you click confirm, they get closed automatically after the intended operation (_operation's validity is out of the scope of this issue, we just need to validate whether the modal automatically closes or not_).
  - Resend Confirmation
  - Send Invoice Confirmation
- Lastly, please validate that in the Hungarian locale, when you use any date picker (e.g. on the Order Cycles Page), you can view the calender in the Hungarian locale, and no error should be displayed on the console related to flatpickr.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

### CODE REVIEW

File: app/webpacker/controllers/mixins/useOpenAndCloseAsAModal.js [hunk 1]
```diff
@@ -12,8 +12,8 @@ export const useOpenAndCloseAsAModal = (controller) => {
     }.bind(controller),
 
     close: function (_event, remove = false) {
-      // Only execute close if there is an open modal
-      if (!document.querySelector("body").classList.contains('modal-open')) return;
+      // Only execute close if the current modal is open
+      if (!this.modalTarget.classList.contains('in')) return;
```
Comment (chahmedejaz) [inline app/webpacker/controllers/mixins/useOpenAndCloseAsAModal.js:16]: This `close` function is executed whenever the `modal:close` event is triggered.
On the Orders page, we have 3 confirmation modals e.g. 
- Resend Confirmation
- Send Invoice Confirmation
- Cancel Order Confirmation
Consider the scenario where the _Cancel Order Confirmation_ Modal is confirmed, then the `modal:close` event triggers. This `close` function gets triggered 3 times for each confirmation modal in sequential order (_Resend Confirmation Modal -> Send Invoice Confirmation -> Cancel Order Confirmation_) as each is listening for this event.
On the first `close` execution (_for Resend Confirmation Modal_), the `modal-open` class is removed from the body as per [Line#20](https://github.com/openfoodfoundation/openfoodnetwork/pull/13004/files#diff-b40716814842983e1b31e36b0292b142d9b08612d2af5ca54b7087a5408aee38R20).
So, on further executions (_for Send Invoice Confirmation and Cancel Order Confirmation_), the [existing guard condition](https://github.com/openfoodfoundation/openfoodnetwork/pull/13004/files#diff-b40716814842983e1b31e36b0292b142d9b08612d2af5ca54b7087a5408aee38L16) would always be `true`, causing the method to return without any close operation. Further to this point, no other confirmation modal will be closed on the page. 
So, updating the guard condition such that the `close` function only triggers if the current modal is opened.
I hope this explanation makes sense, please let me know if I'm missing something.

File: app/webpacker/controllers/flatpickr_controller.js [hunk 2]
```diff
@@ -36,6 +37,7 @@ export default class extends Flatpickr {
     sv: sv,
     tr: tr,
     en: en,
+    hu: hu,
```
Comment (chahmedejaz) [inline app/webpacker/controllers/flatpickr_controller.js:40]: Fixes the `flatpickr invalid locale hu` error as mentioned in the issue

**Review by mkllnk — APPROVED** [review]
Thank you!

The missing locale will probably happen again with new instances. But we don't want to add too many locales to the JS either. It increases the size and other instances don't need it. It would be great to have a more flexible solution where we set the locale on demand and load it from a CDN.

**Review by dacook — APPROVED** [review]
Great work, and good support. When it's a simple fix it's great to act straight away 👍

**Comment by chahmedejaz** [comment]
> The missing locale will probably happen again with new instances. But we don't want to add too many locales to the JS either. It increases the size and other instances don't need it. It would be great to have a more flexible solution where we set the locale on demand and load it from a CDN.

Yes Maikel, I strongly agree with this. Maybe in the future, we could incorporate it.

**Comment by chahmedejaz** [comment]
> Good work.
I think this would be worth mentioning on this page: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29
It would be a helpful tip for someone when they're adding a new language.

Sure, David, let me add that. Thanks.

**Comment by chahmedejaz** [comment]
David, It's added in the documentation [here](https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-%28i18n%29#flatpickr-locale-configuration) now.

**Comment by filipefurtad0** [comment]
Hey @chahmedejaz ,

I've verified the issue for the following modals, taking notice that none of them closes after the action is confirmed:
- Resend Confirmation
- Send Invoices
- Cancel Orders

After your PR:
- Resend Confirmation -> confirming closes the modal and displays the information to the user that the confirmation has been sent

image

- Send Invoices -> confirming the action closes the modal and displays the corresponding information

image

- Cancel Orders -> confirming the action cancels the orders, and closes the modal. It does not display any additional information to the user. 

I was not able to verify the issue with the Hungarian locale, this setup is not available in staging. Pinging @pragai for this production test.

This addresses all other issues, merging!
