### PR TITLE
3477 Render only eligible adjustments on the order page

### LINKED ISSUE #3477: [Spree Upgrade] Adjustments with amount zero are being displayed in the orders edit page
## Description
Order edit page is showing adjustments that have amount zero. These adjustments should be removed by using the scope adjustment.eligible. See [this review comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/3445#discussion_r255901384).

Additionally, the id order-charges is being used several times making the html invalid. See [this comment](https://github.com/openfoodfoundation/openfoodnetwork/pull/3445#discussion_r255896692)

## Expected Behavior
Adjustments with amount zero should not be shown.
html div Id order-charges is NOT present multiple times in the html if order has more than one adjustment.

## Actual Behaviour
Adjustments with amount zero are listed.
html div Id order-charges is present multiple times in the html if order has more than one adjustment.

## Steps to Reproduce
Create an order with a adjustment with a zero amount (a specific example needs to be given here) and verify it is not showing on the orders edit page.

## Possible Fix
Use the eligible scope to fetch adjustments.

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #3477 

The admin orders edit form was displaying adjustments even if they were    "not eligible". For example, an additional fee with amount `0` is not    eligible. They were already hidden in the adjustments view and we are    hiding them in reports.

#### What should we test?

1. Place an order.
2. Log in as admin and go to the order.
3. Go to adjustments and create an adjustment with zero amount.
4. After Saving you will see a success message but you won't see the adjustment. That's confusing but correct, I think.
5. Go back to the order details. You shouldn't see the adjustment there either.

Bad:
Screenshot from 2019-03-29 18-45-48

Good:
Screenshot from 2019-03-29 18-47-06

### CODE REVIEW

**Comment by mkllnk** [comment]
Ah, I see. We need to filter the adjustments before passing them on to the partial.

**Comment by mkllnk** [comment]
@luisramos0 I added a few more commits that need a review.

- The duplicate HTML id issue is fixed (I didn't see that before).
- The spec is fixed.
- The empty adjustments table is hidden.

**Comment by mkllnk** [comment]
@luisramos0 I added another little commit for a missing translation on that page. I also backported it to master for translations: https://github.com/openfoodfoundation/openfoodnetwork/pull/3679

But now I'm wondering if we need to do that in the future. I guess we will merge to master at some point. And then we can tell everybody to go on Transifex and translate. If we don't backport, that could be a lot in one go but that could be as efficient as translating bits and pieces from time to time. What do you think?

**Comment by luisramos0** [comment]
re translations, I think we should put the translations in master now in some way. Previously I put the translations only in master and waited for the merge from master to 2-0, but I think backporting them is better now :+1:

Are we merging 2-0-stable to master? omg, when, how, is it that simple?

File: app/helpers/admin/orders_helper.rb [hunk 1]
```diff
@@ -0,0 +1,14 @@
+module Admin
+  module OrdersHelper
+    def order_adjustments(order)
+      order.adjustments.eligible.select do |adjustment|
+        type = adjustment.originator_type
+
+        is_shipping_method_fee = (type == 'Spree::ShippingMethod')
```
Comment (luisramos0) [inline app/helpers/admin/orders_helper.rb]: I think it's important we are strict with naming so for me there's a big difference between shipping_method_fee, shipping_method_adjustment and shipping_fee. Fee's (just like hubs) dont exist in ofn code, we only have adjustments not fees. So I'd call this variable is_shipping_method_adjustment.

File: app/helpers/admin/orders_helper.rb [hunk 2]
```diff
@@ -0,0 +1,14 @@
+module Admin
+  module OrdersHelper
+    def order_adjustments(order)
```
Comment (luisramos0) [inline app/helpers/admin/orders_helper.rb]: this is not really order_adjustments right?
this method is order_adjustments_displayed_in_the_adjustments_table_on_the_order_edit_page_which_excludes_shipping_method_adjustments_and_zero_tax_rate_adjustments 🤣 

because of this I'd call it order_adjustments_for_display and add a method comment with something like
"we exclude shipping method adjustments because they are displayed in a separate table together with the order line items"
and "we exclude tax rate adjustment with zero value because..." I actually dont know why tax rates need to be excluded here, they would be removed already as not eligible if amount is zero.

**Comment by mkllnk** [comment]
@luisramos0 
> Are we merging 2-0-stable to master? omg, when, how, is it that simple?

That's probably a discussion for the next meeting. But yes, at some point we should probably do this:

- Last v1 release.
- Merge 2-0-stable to master.
- Extensive testing and bug fixing.
- Publish 2.0.0-beta pre-release.
- Test that release on small instances (Germany, Canada, Katuma).
- Observe and fix bugs.
- Release 2.0.0.
- Carefully deploy to one instance at a time, maybe leaving a couple of days in between to observe errors.
- Fix bugs and release 2.0.1, 2.0.2,...2.0.42. ;-)
- Deploy to Australia (3rd most traffic, oldest data)
- Deploy to UK (2nd most traffic, 2nd oldest data)
- Deploy to France (most traffic)

File: app/helpers/admin/orders_helper.rb (hunk 1 above)
Comment (mkllnk) [reply app/helpers/admin/orders_helper.rb]: I agree, I added another commit (and then made it obsolete :wink:)

File: app/helpers/admin/orders_helper.rb (hunk 2 above)
Comment (mkllnk) [reply app/helpers/admin/orders_helper.rb]: Thank you for bringing it up. I guess you could argue that helpers are to be used in views. So all helper are "for display" and therefore the suffix is redundant. :stuck_out_tongue_closed_eyes: 
In this case it's probably better to point it out though. 

I had a similar thought about the zero value adjustments. So I first covered that part with a spec and then removed the redundant logic. Much simpler, isn't it?

Comment (luisramos0) [reply app/helpers/admin/orders_helper.rb]: you refactored code to delete it afterwards :-)
re removing tax rate filter, we can do that. I am just not 100% sure it is redundant...

**Comment by luisramos0** [comment]
nice summary! I created an issue for the "v2 release" here #3692

File: spec/features/admin/orders_spec.rb [hunk 3]
```diff
@@ -267,7 +267,7 @@ def new_order_with_distribution(distributor, order_cycle)
       end
 
       scenario "shows the order tax adjustments" do
-        within('tbody#order-charges') do
+        within('fieldset', text: 'LINE ITEM ADJUSTMENTS') do
```
Comment (sauloperez) [inline spec/features/admin/orders_spec.rb]: We should reference the translation key instead as per https://github.com/openfoodfoundation/openfoodnetwork/wiki/Code-Conventions#always-use-i18nt-in-spec-assertions, right?

File: spec/features/admin/orders_spec.rb [hunk 4]
```diff
@@ -283,6 +283,19 @@ def new_order_with_distribution(distributor, order_cycle)
...
+          :adjustment,
+          adjustable: @order,
+          label: "invalid adjustment",
+          amount: 0
+        )
+
+        visit spree.edit_admin_order_path(@order)
+
+        expect(page).to have_no_content adjustment.label
+      end
```
Comment (sauloperez) [inline spec/features/admin/orders_spec.rb]: Have you considered writing a controller test instead? the test does not involve any user interaction or more than a page so it should be possible AFAIK. You know the benefits already, improved reliability, execution speed, etc.

Comment (luisramos0) [reply spec/features/admin/orders_spec.rb]: @sauloperez the filtering is done in the view

File: app/views/spree/admin/orders/_form/_adjustments.html.haml [hunk 5]
```diff
@@ -3,12 +3,12 @@
...
       %thead
-        %th= Spree.t('name')
-        %th= Spree.t('amount')
-      %tbody#order-charges.with-border
+        %tr
+          %th= Spree.t('name')
+          %th= Spree.t('amount')
+      %tbody.with-border
         - adjustments.each do |adjustment|
-          - if (adjustment.originator_type != 'Spree::ShippingMethod') && !(adjustment.originator_type == 'Spree::TaxRate' && adjustment.amount == 0)
```
Comment (luisramos0) [inline app/views/spree/admin/orders/_form/_adjustments.html.haml]: I think we can delete admin/orders_spec line 258:
`next if (adjustment.originator_type == 'Spree::TaxRate') && (adjustment.amount == 0)`

File: spec/features/admin/orders_spec.rb (hunk 4 above)
Comment (sauloperez) [reply spec/features/admin/orders_spec.rb]: I see, and that is why I suggest a controller test. By using `render_views`, which we might use by default, we hit the view too.

Comment (luisramos0) [reply spec/features/admin/orders_spec.rb]: eheh, good that I commented, I learned something. I didnt know that render_views trick 👍

File: spec/features/admin/orders_spec.rb (hunk 3 above)
Comment (mkllnk) [reply spec/features/admin/orders_spec.rb]: I thought about that. But then this was much easier for several reasons:

- The translation key was missing. While rendering of the page has a fallback and uses the key name, that doesn't happen when calling `I18n.t` in the spec. I added the missing translation now and could use it.
- Some Spree logic (maybe the view) is printing it all in capitals. So I would need to use this: `I18n.t('spree.admin.orders.form.line_item_adjustments').upcase` which is long and hard to read.

But we have a convention, so I better obey. :wink:

File: spec/features/admin/orders_spec.rb (hunk 4 above)
Comment (mkllnk) [reply spec/features/admin/orders_spec.rb]: Good idea. Have a look at my last commit. We are saving 7 seconds here.

File: app/views/spree/admin/orders/_form/_adjustments.html.haml (hunk 5 above)
Comment (mkllnk) [reply app/views/spree/admin/orders/_form/_adjustments.html.haml]: Done.

File: spec/features/admin/orders_spec.rb (hunk 3 above)
Comment (luisramos0) [reply spec/features/admin/orders_spec.rb]: 🤣

File: spec/features/admin/orders_spec.rb (hunk 4 above)
Comment (sauloperez) [reply spec/features/admin/orders_spec.rb]: Wow! 7 seconds it's a whole lot!

**Comment by RachL** [comment]
This is ready to go ! https://docs.google.com/document/d/1ane0lt3y67wDM1sokJJ7dXNhIUorwTaNA9ZtED_8yvU/edit#
