### PR TITLE
[Spree Upgrade] Scope variants in line items availability validator

### LINKED ISSUE #3118: [Spree Upgrade][FrontOffice] Fix shopping/variant_overrides_spec (1 broken test)
Fix spec/features/consumer/shopping/variant_overrides_spec

these errors will have to fixed after or as part of #2559
```
 1) shopping with variant overrides defined creating orders subtracts stock from the override
     Failure/Error:
       expect do
         complete_checkout
       end.to change { v4.reload.count_on_hand }.by(0)
     
       expected `v4.reload.count_on_hand` to have changed by 0, but was changed by -2
     # ./spec/features/consumer/shopping/variant_overrides_spec.rb:126:in `block (4 levels) in <top (required)>'
     # ./spec/features/consumer/shopping/variant_overrides_spec.rb:125:in `block (3 levels) in <top (required)>'

  2) shopping with variant overrides defined creating orders subtracts stock from stock-overridden on_demand variants
     Failure/Error:
       expect do
         complete_checkout
       end.to change { v6.reload.count_on_hand }.by(0)
     
       expected `v6.reload.count_on_hand` to have changed by 0, but was changed by -2
     # ./spec/features/consumer/shopping/variant_overrides_spec.rb:137:in `block (4 levels) in <top (required)>'
     # ./spec/features/consumer/shopping/variant_overrides_spec.rb:136:in `block (3 levels) in <top (required)>'

  3) shopping with variant overrides defined creating orders does not show out of stock flags on order confirmation page
     Failure/Error: sleep(0.1) until value = yield
     
     Timeout::Error:
       execution expired
     # ./spec/support/request/web_helper.rb:151:in `sleep'
     # ./spec/support/request/web_helper.rb:151:in `block in wait_until'
     # ./spec/support/request/web_helper.rb:150:in `wait_until'
     # ./spec/support/request/web_helper.rb:157:in `wait_until_enabled'
     # ./spec/features/consumer/shopping/variant_overrides_spec.rb:201:in `click_checkout'
     # ./spec/features/consumer/shopping/variant_overrides_spec.rb:155:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
This PR includes all 5 commits from #3210, this PRs commits are the last 5.
#### What? Why?

Closes #3118 

When validating line_item.variant stock levels in stock/availability_validator we need to scope variants so that variant overrides stock levels are used instead. Here we re-use the the line_item.scoper so that the variant_overrides are not loaded several times in the handling fo line_items in the same request.

Additional problems solved:
- adapting line_item.sufficient_stock? to spree 2 by using the new variant.can_supply?
- fix variant.in_stock? by also using the new variant.can_supply?
- move stock_location.fill_status to VariantStock and fix it, it was totally dependent on stock_item methods and is not using already overridden variant methods (on_demand and total_on_hand)

#### What should we test?
This is one of the final steps in making cart and checkout handle stock levels correctly in v2!
the spec in 3118 (spec/features/consumer/shopping/variant_overrides_spec.rb:152) should be green.

#### Dependencies
This PR goes after #3210

### CODE REVIEW

File: app/models/spree/stock/availability_validator_decorator.rb [hunk 1]
```diff
@@ -24,18 +24,26 @@ def quantity_in_shipment(line_item)
...
-  # But using the calculated quantity instead of the line_item.quantity.
+  # Overrides Spree v2.0.4 validate method version to:
+  #   - scope variants to hub and thus acivate variant overrides
+  #   - use calculated quantity instead of the line_item.quantity
+  #   - rely on Variant.can_supply? instead of Stock::Quantified.can_supply?
+  #       so that it works correctly for variant overrides
   def validate_quantity(line_item, quantity)
-    quantifier = Spree::Stock::Quantifier.new(line_item.variant_id)
-    return if quantifier.can_supply? quantity
+    line_item.scoper.scope(line_item.variant)
```
Comment (mkllnk) [inline app/models/spree/stock/availability_validator_decorator.rb]: Instead of exposing the scoper, you could offer `line_item.scope_variant`.

I still have a concern about the performance of the scoper used in this way, but that can probably be solved later on.

File: app/models/concerns/variant_stock.rb [hunk 2]
```diff
@@ -130,6 +130,23 @@ def in_stock?(quantity = 1)
...
+  # We can have this responsibility here in the variant because there is only one stock item per variant
+  #
+  # Here we depend only on variant.total_on_hand and variant.on_demand.
+  #   This way, variant_overrides only need to override variant.total_on_hand and variant.on_demand.
+  def fill_status(quantity)
+    if count_on_hand >= quantity
+      on_hand = quantity
+      backordered = 0
+    else
+      on_hand = total_on_hand < 0 ? 0 : total_on_hand
```
Comment (mkllnk) [inline app/models/concerns/variant_stock.rb]: I find this one easier:
```suggestion
      on_hand = [0, total_on_hand].max
```

Comment (luisramos0) [reply app/models/concerns/variant_stock.rb]: spree code is actually:
```
          on_hand = item.count_on_hand
          on_hand = 0 if on_hand < 0
```

I'll keep your suggestion.
