### PR TITLE
Show any tax category errors when saving variants

### LINKED ISSUE #12480: [BUU] Variants with "none" tax category have an invisible error
## Description
When this option is ticked:
Screenshot 2024-05-15 at 4 52 04 pm

But variants still have "None" selected, they are in an invalid state. 
The BUU PRoducts screen shows a summary that they are "modified", yet shows no indication of what's wrong. When attempting save, they are counted as erorrs, but don't show any  messages explaining why.

image

Discovered in:
- https://github.com/openfoodfoundation/openfoodnetwork/issues/12473

## Expected Behavior

I don't think they should show "modified" at all.

When saving, an error is expected for each variant that has "None" selected. There should be a message appearing below the Tax Category dropdown.

## Steps to Reproduce

as above

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by dacook**
### What? Why?

- Closes #12480

If the tax category is required, but not chosen on a variant, the error is now clearer so you know what's wrong:
* on bulk products screen: an error message now appears below the dropdown
* on variant edit screen: the label is highlighted red.

I now realise this was due to bad setup (see below), and would like to update the interface to avoid the root cause. But until then at least we have better error messaging.

Screenshot 2024-05-16 at 3 19 29 pm

Screenshot 2024-05-16 at 11 18 49 am

It would have been nice to highlight the Tomselect and  Select2 dropdowns too, but there's a couple of problems with that..
.. And we'll have to fix unit value another day.

### What should we test?

**Setup**
I now realise that this is bad setup, but it's currently possible, and it's not intuitive:
1. Visit `/admin/tax_settings/edit`, select "products require tax category" and save
2. Visit `/admin/tax_categories` and ensure there is no "default"

**Test with `admin_style_v3` enabled**
4. Visit `/admin/products`
5. select "None" for tax category on a variant, and attempt save
6. Error message should explain why it did not save.

**Try both: with `admin_style_v3` enabled, also without.**
7. Visit `/admin/products/x/variants/x/edit` 
8. select "None" for tax category, and attempt save.

#### Release notes
It's only really noticeable on admin_style_v3

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

### Documentation updates
The config requirements may already be documented in the guide, I don't know. But we really need to make the app more intuitive anyway.

### CODE REVIEW

**Comment by dacook** [comment]
Need to fix this spec:
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/engines/dfc_provider/spec/requests/supplied_products_spec.rb#L89

File: app/models/spree/variant.rb [hunk 1]
```diff
@@ -64,7 +64,7 @@ class Variant < ApplicationRecord
     validates_lengths_from_database
     validate :check_currency
     validates :price, numericality: { greater_than_or_equal_to: 0 }, presence: true
-    validates :tax_category, presence: true,
+    validates :tax_category_id, presence: true,
```
Comment (mkllnk) [inline app/models/spree/variant.rb:67]: That's a shame. This format has a few downsides, for example a new tax category can't be associated to a variant before it's saved. So instead of letting Rails save the record, we have to save it first. That shouldn't be in issue in our model but may be for test data.

**Review by mkllnk — COMMENTED** [review]
> I think this spec is expecting the tax category to be chosen automatically, but I think my change here revealed that it's not.

No, the default tax category is not saved on the variant. But it's loaded when needed. Before, the validation was checking that it had a tax category. And it did "have" the default tax category without being associated to it. But it doesn't have a tax category id. I know it's confusing. I worked on it last and just kept the existing behaviour because I was worried about breaking anything.

File: app/views/admin/products_v3/_variant_row.html.haml [hunk 2]
```diff
@@ -48,6 +48,7 @@
       selected_option: variant.primary_taxon_id,
       aria_label: t('.category_field_name'),
       placeholder_value: t('admin.products_v3.filters.search_for_categories')))
+  = error_message_on variant, :primary_taxon_id
```
Comment (mkllnk) [inline app/views/admin/products_v3/_variant_row.html.haml:51]: We don't have a spec on this, do we?

File: app/views/admin/products_v3/_variant_row.html.haml [hunk 3]
```diff
@@ -56,6 +57,7 @@
       include_blank: t('.none_tax_category'),
       aria_label: t('.tax_category_field_name'),
       placeholder_value: t('.search_for_tax_categories')))
+  = error_message_on variant, :tax_category_id
```
Comment (mkllnk) [inline app/views/admin/products_v3/_variant_row.html.haml:60]: I just had a play with this and it seemed to work to go back to validating tax_category and just changing the error message here, without changing the input above:
```suggestion
  = error_message_on variant, :tax_category
```

If I require a tax category but don't have a default then this will display an error.

The grey zone is to require a tax category, set a default and then select "None". Then it will look like it doesn't have a tax category but the default will be applied during checkout. That's another problem though.

File: app/models/spree/variant.rb (hunk 1 above)
Comment (dacook) [reply app/models/spree/variant.rb:67]: Yes, I thought it was a shame too, but I thought it's also more compatible with rails forms which is a good thing.
The test data issue is the only downside I can think of, can you think of any others?

File: app/views/admin/products_v3/_variant_row.html.haml (hunk 2 above)
Comment (dacook) [reply app/views/admin/products_v3/_variant_row.html.haml:51]: 🙈  You're right, I need to add that.

Comment (dacook) [reply app/views/admin/products_v3/_variant_row.html.haml:51]: Wait, for `primary_taxon_id`, I don't think there is a way to trigger an error. 
I put this in for future-proofing, which I realise is generally a bad idea, but it seemed likely that if someone added a validation condition, they wouldn't think to add this.
It's important on this screen, because we don't have an error summary at the top of the screen.

File: app/views/admin/products_v3/_variant_row.html.haml (hunk 3 above)
Comment (dacook) [reply app/views/admin/products_v3/_variant_row.html.haml:60]: Nice work, I didn't think of that. 

It won't work for the above select (ie `<select name="...variant[tax_category_id]">`). That means we won't get the `field_with_errors` wrapper class to add a red border on the field.
But that's an acceptable tradeoff 👍

Comment (dacook) [reply app/views/admin/products_v3/_variant_row.html.haml:60]: Note to self: also add spec for this error.

**Review by dacook — COMMENTED** [review]
Thanks for your help, I'll try proceeding with `error_message_on variant, :tax_category`

File: app/views/admin/products_v3/_variant_row.html.haml (hunk 2 above)
Comment (dacook) [reply app/views/admin/products_v3/_variant_row.html.haml:51]: Given that it's untested, there's a very real possibility it doesn't work (eg, any validations would be on the association, not the id!).
So I will remove this.

**Review by mkllnk — APPROVED** [review]
Nice!

**Review by rioug — APPROVED** [review]
Nice !

**Comment by filipefurtad0** [comment]
Hey @dacook ,

Thank you for working on this one.

First, I've followed your suggested tests. After staging the PR, and with a Requires tax category option ticked:

image

And no default tax category (all set to `false`), and

with `admin_style_v3` enabled:
- Visit /admin/products
- Select "None" for tax category on a variant, and attempt save
- Error message should explain why it did not save

This works as expected: the changed variant is highlighted. In fact, there are several other variants with None as a tax category, and these are displayed as well:

image

Clicking on Discard changes reverts the change for the edited variant, and the error messages disappear. It should be noticed though, that the other 7 variants are left unchanged (they are still having a `None` tax category).

Then, repeated this for `admin_style_v3` disabled:

image

In this case, the only offending variant is the edited variant, although other variants also have `None` as a Tax Category.

**Summary**
With admin_style_v3 enabled -> 8 offending variants.
With admin_style_v3 disabled -> 1 offending variants.

I think this is because of variants on a previous state, which I'm not sure about.

So, after this test, I've tried to look for the related scenario, in which we had the warning about edited variants, but no possibility to remove the banner. This corresponds to bug #12473, i.e., with admin_style_v3 enabled.

1) With a default tax category -> **no change in behavior**

Going through pagination I spotted the `Discard changes` warning is still appears and the responsible variants are not highlighted (in this case, I could figure out which one was responsible for the error, although there are other variants with `None` ):

image

Clicking `Discard changes` reloads the page (after confirmation, as before) but does not remove the warning. . Is this not a legitimate setup in production? I can still find plenty of such variants on staging-AU, and am unclear on the root cause. To put it in another way, I'm not sure #12473 should be closed?

2) Without a default tax category -> **a change is observed** 

After setting all tax categories as non-default, indeed there is a bug fix: 
- we can see the highlighted fields, showing which tax category needs to be updated
- we can discard changes: the button works, at least in the sense that it removes the banner. However, all variants are left unchanged, i.e., there is no revert to a previous / allowed state.

**Summary**

i) I think this PR highlights variants which have a None tax category. So I'd say it's good to merge.
ii) I'm not sure we've totally understood/fixed/prevented #12473, so I'm a bit weary of having this issue closed. I have not checked production servers - I'm not sure this is visible on the data structure - but are we sure we don't have such variants "corrupt" in production and that enabling BUU won't surface the bug?

I'd vote for merging. Let me know what you think @dacook . Thanks! :pray:

**Comment by dacook** [comment]
Hi @filipefurtad0 , thanks for looking into this.

I agree, this change doesn't solve the root cause of https://github.com/openfoodfoundation/openfoodnetwork/issues/12473. 
However it does help discover variants with an invalid tax category, and so helps work around it, in some cases. Clearly not all cases though :(

You also revealed that the old bulk screen only validates changed records, while the new screen validates _all_ records on the screen. I've been wanting to optimise that since the beginning, will add a tech debt issue to track it.

So I think still need to solve that issue #12473. If it is due to corrupt data, then we should still try to handle it gracefully.

I will merge this one.
