### PR TITLE
fix #5829 (Voiding an initial payment (i.e. a full refund) after partially refunding the order is not possible with Stripe-SCA)

### LINKED ISSUE #5829: Voiding an initial payment (i.e. a full refund) after partially refunding the order is not possible with Stripe-SCA
## Description

Orders payed with both Stripe-Connect and Stripe-SCA allow to perform a partial refund of the order (after removing some items). However, after this partial refund, voiding the initial payment of the order is still possible in Stripe-Connect, but fails with Stripe-SCA.

## Expected Behavior

In both payment methods, voiding of the initial order payment should be possible, after a partial refund. This should be reflected on the Stripe-Dashboard:

Initial payment:

After partial refund:

After voiding the initial payment:

## Actual Behaviour

Only with Stripe-Connect it is possible to void of the initial payment of the order, after a partial refund. With Stripe-SCA this operation yields the error "Refund amount (€xxx) is greater than unrefunded amount on charge (€xxx)

## Steps to Reproduce

Customer (or Admin, in the BO)
1. Place an order with several items, using Stripe-SCA as a payment method.

Admin
2. Edit the respective order, remove some items.
3. Go to Payments - there should be a given amount in credit owed.
4. Press "Credit" on the initial payment of the order. A second entry should appear under Payments.
5. Now, on the first (initial) payment, press the X (void payment). See the error.

## Animated Gif/Screenshot

After partial refund, and attempting to void the original payment:

## Workaround

Cancelling the order is maybe an option, but it does not provide the refund through Stripe.

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v3.1.3
* Browser name and version: Firefox 78
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

## Possible Fix

Observed while testing #5780 but apparently not related to this PR. Also appears independent of applying transaction fees.

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #5829 

This adds a method to calculate the refundable amount by looking at the `charges` property of the returned `PaymentIntent` from Stripe. A charge is created when a partial refund is issued. If there are no partial refunds issued, the full amount will still be refunded. 

#### What should we test?
See issue's Steps to Reproduce

#### Release notes
Fixed a bug that prevented payments from being refunded if a partial refund had already been issued. 

Changelog Category: User facing changes

### CODE REVIEW

File: app/models/spree/gateway/stripe_sca.rb [hunk 1]
```diff
@@ -79,6 +79,11 @@ def create_profile(payment)
 
       private
 
+      def refundable_amount(payment_intent_response)
+        payment_intent_response.amount_received -
+          payment_intent_response.charges.data.map(&:amount_refunded).sum
```
Comment (sauloperez) [inline app/models/spree/gateway/stripe_sca.rb:84]: What if there are unsuccessful charges? Looking at the docs it seems that they might not even include them all?

> This list only contains the latest charge, even if there were previously multiple unsuccessful charges. To view all previous charges for a PaymentIntent, you can filter the charges list using the payment_intent parameter.

source: https://stripe.com/docs/api/payment_intents/object#payment_intent_object-charges.

Comment (andrewpbrett) [reply app/models/spree/gateway/stripe_sca.rb:84]: I believe this still works, because each time we try to make a payment for an order it creates a new PaymentIntent. I tried a couple things:

At first, I thought you meant "what if there are multiple partial refunds" so I tried that: I placed an order, then in the backend I made two adjustments to the order and issued a refund each time. The `amount_refunded` returns the sum across all refunds. 

Then I realized you might be asking "what if the customer or an admin creates unsuccessful charges?" For the admin side, I placed an order through the front end and chose Cash. Then on the backend, I created two unsuccessful charges and one successful one. I was still able to do the partial refunds on the successful charge. I found the same when the unsuccessful charges were created by the customer on the front end. 

The option to do the refund on the failed charge never appears in the first place, only on the successful one: 
Screen Shot 2020-12-10 at 2 37 57 PM

Comment (sauloperez) [reply app/models/spree/gateway/stripe_sca.rb:84]: But does that mean that the `payment_intent_response.charges` includes only successful charges then? Sorry, I'm still wrapping my head around this Stripe API.

**Review by sauloperez — APPROVED** [review]

**Review by Matt-Yorkley — APPROVED** [review]

File: app/models/spree/gateway/stripe_sca.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/models/spree/gateway/stripe_sca.rb:84]: What I'm saying is that for our case, the PaymentIntent that we're querying Stripe about will only have the single successful charge. It's definitely complex! Especially since our mapping is not as direct as it could be if we were only dealing with Stripe as a provider.

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

I took the initial issue and reproduced those steps, after staging the PR. Tried this for 3D-auth and non-3D-auth cards (not sure this would make any difference). I associated a transaction fee for StripeSCA.

So, after placing the order as a customer, the admin can remove some items from that order, and issue one, or several partial refunds - this is working now, awesome.

Below are the pics of an example, in which the admin succesivelly removes items from an order, one by one, issuing refunds for each change. The final one, is a total refund of the initial payment:

image

The dashboard from Stripe shows all these changes correctly:

image

The values above are not correct - this is because of issue #3584. This is shown below, on the repeated transaction fees:

image

So, we're all good here :+1: 
Ready to go!


PS: also bumped on a known issue related to the removal of the last item from an order - #5546
