### PR TITLE
Restarts checkout flow, when emptying the cart

### LINKED ISSUE #9299: [Split Chekcout] Clicking "Empty cart" breaks future checkout attempts
## Description

Related to https://github.com/openfoodfoundation/openfoodnetwork/issues/9131.

Emptying the cart on the `/cart` page after visiting the `/summary` page breaks the checkout: after this, the user cannot visit any of the checkout steps and always sees the snail.

## Expected Behavior

Clicking "Empty cart" should not break the checkout, on future checkout attempts.

## Actual Behaviour

Clicking "Empty cart" breaks the checkout, on future checkout attempts.

## Steps to Reproduce

1. Enable Split Checkout and visit a shop
2. Add items to your cart and proceed to `/details`
3. Fill out details and proceed to `/payment`
4. Select a payment method and proceed to `/summary`
5. Toggle the side cart and visit the `/cart` page
6. Click "Empty cart"
7. Restart on step 2 -> clicking "Checkout" will trigger a snail

## Animated Gif/Screenshot

Peek 2022-06-11 09-41

## Workaround

Only workaround currently is disabling split checkout for that user. The first order placed after this will go through but still display a snail

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Closes #9299.
Partially addresses  https://github.com/openfoodfoundation/openfoodnetwork/issues/9131: it does not prevent the bug but adds a workaround.

It follows a similar approach as #9190, but for the order `state = confirmation`;
By clicking "Empty cart" the state of the order should no longer be `confirmation`, and as such, redirection to `/summary` page should not occur.

The PR adds:
- a system spec, which expects the order state to change when the user clicks "Empty Cart", on the `/cart` page => spec fails
- adds the code change, which should allow "Empty Cart" to take effect when the state of the order is `confirmation` => should make the spec pass

#### What should we test?

- Follow the steps to reproduce on the issue: the bug should not be reproducible (step 7)
- After going through the steps above it should be possible to place an order, as usual

`Worth checking` before and after the PR
- visit shop, add items and proceed to the `/summary` step - don't complete the order
- go back to the `/shop` page and select another shop
- place an order on this second shop

#### Release notes

Changelog Category: User facing changes

Restarts checkout flow, when, when emptying the cart

### CODE REVIEW

**Comment by filipefurtad0** [comment]
[This comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/9131#issuecomment-1121726323) needs to be considered here. Marking as draft PR for now.

File: app/models/spree/order.rb [hunk 1]
```diff
@@ -434,6 +434,7 @@ def empty!
       payments.clear
       shipments.destroy_all
       restart_checkout_flow if state == "payment"
+      restart_checkout_flow if state == "confirmation"
```
Comment (georgethoppil) [inline app/models/spree/order.rb:437]: can probably combine this with line 436

`restart_checkout_flow if ["payment", "confirmation"].include?(state)`

File: spec/system/consumer/split_checkout_spec.rb [hunk 2]
```diff
@@ -877,6 +877,23 @@
...
+        it "is 'confirmation' on the summary step" do
+          expect(order.reload.state).to eq "confirmation"
+        end
+
+        it "emptying the cart changes the order state back to address" do
+          visit main_app.cart_path
+          find('#clear_cart_link').click
+          expect(page).to have_current_path enterprise_shop_path(distributor)
+          expect(order.reload.state).to eq "address"
+        end
```
Comment (mkllnk) [inline spec/system/consumer/split_checkout_spec.rb:895]: Separating the specs like this is excellent style. Unfortunately, system specs are quite expensive. They take a long time to run which means that we have to wait longer and CI servers are causing more greenhouse gases etc. So in this particular case I would combine the two specs into one:
```suggestion
        it "emptying the cart changes the order state back to address" do
          visit main_app.cart_path
          expect {
            find('#clear_cart_link').click
            expect(page).to have_current_path enterprise_shop_path(distributor)
          }.to change { order.reload.state }.from("confirmation").to("address")
        end
```

File: app/models/spree/order.rb (hunk 1 above)
Comment (mkllnk) [inline app/models/spree/order.rb:437]: Since we are talking about this already, I would probably do this:
```suggestion
      restart_checkout_flow if state.in?(["payment", "confirmation"])
```

**Review by mkllnk — APPROVED** [review]

File: app/models/spree/order.rb (hunk 1 above)
Comment (filipefurtad0) [reply app/models/spree/order.rb]: Thanks @georgethoppil, I've combined it following your suggestion. Wondering if other states should not be included here as well. I've left it like this for now though.

File: spec/system/consumer/split_checkout_spec.rb (hunk 2 above)
Comment (filipefurtad0) [reply spec/system/consumer/split_checkout_spec.rb]: Thanks @mkllnk ,

> `to change { order.reload.state }.from("confirmation").to("address")`

this formulation is really useful to test state changes :+1:

File: app/models/spree/order.rb (hunk 1 above)
Comment (georgethoppil) [reply app/models/spree/order.rb]: In terms of readability, id pick this over mine

**Review by georgethoppil — APPROVED** [review]

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @filipefurtad0,
Great to see another pull request from you! And thank you for the great instructions on how to reproduce and test this.

Exactly as you described, the following steps lead to a snail BEFORE the PR and checkout can successfully be completed AFTER the PR: 💪 

1. Enable Split Checkout and visit a shop
2. Add items to your cart and proceed to /details
3. Fill out details and proceed to /payment
4. Select a payment method and proceed to /summary
5. Toggle the side cart and visit the /cart page
6. Click "Empty cart"
7. Restart on step 2 -> clicking "Checkout" will trigger a snail

Also the second scenario creates a snail BEFORE your PR and checkout works perfectly fine AFTER your PR: 💪 

1. Visit shop, add items and proceed to the /summary step - don't complete the order
2. Go back to the /shop page and select another shop
3. Place an order on this second shop

**Left: before PR, right after PR:**
image

I have no other idea to make this fail! It is ready to go! 🥳

**Comment by filipefurtad0** [comment]
Thank you for testing and your notes @drummer83 :muscle: 

While the `confirmation` state of the order only exists for the split-checkout flow I guess it can't hurt to check if the same scenario (empty cart) still works as before on the legacy checkout. I guess we can double check this on master/release testing.

**Comment by drummer83** [comment]
Thanks for adding this, @filipefurtad0!
I have tested legacy checkout now as well:
- Empty cart scenario: Breaking before this PR, working well after this PR. :muscle:
- Change shop scenario: Working well before and after this PR. :+1:
