### PR TITLE
Data cleanup

### LINKED ISSUE #2247: Delete old sessions from the database
We are storing session data in the database, but never delete them. Our database fills up with useless session data.

## Description

We use https://github.com/rails/activerecord-session_store which is part of the Rails 3 core.

## Expected Behavior

Sessions older than a month should get deleted.

## Actual Behavior

Session data persists forever even if the user's browser doesn't have the session id any more.

## Steps to Reproduce

1. Log into a long running instance database.
2. Run: `select updated_at from sessions limit 5;`
3. Observe dates that are years old.

```
openfoodnetwork=> select updated_at from sessions limit 5;
         updated_at         
----------------------------
 2015-06-11 02:48:17.72724
 2015-06-11 02:48:18.089722
 2015-06-11 02:48:22.233834
 2015-06-11 02:48:22.443063
 2015-06-11 02:48:26.397765
(5 rows)
```

## Context

I was just about to implement the session store in another project and came across `rake db:sessions:trim`. That rake task is not included in our version of Rails and we never clean up sessions.

## Possible Fix

Check how https://github.com/rails/activerecord-session_store implements the session trimming. Maybe it's just including the gem and adding a task to our cron schedule.

### LINKED ISSUE #3608: Clean up useless data from live DBs to improve db backups speed and potentially app performance
### What we should change and why (this is tech debt)
We will soon have tasks to sanitize and truncate data from production  #3579 This is useful to fetch data from live environments into testing environments.

Now we should create a new task for a different purpose: to reduce the live DB size by deleting data that is not needed.
Maybe it can be called ofn:data:clean_up

There are at least 3 good candidates to be deleted or truncated (keep only latest entries):
- spree_state_changes
- spree_log_entries
- sessions

This requires further investigation about what exactly are these tables and if they can really be deleted.

**Deleting all the data in these 3 tables in the AUS live database reduces the ZIP database size from 485MB to 67MB!**

### Context
this was found as part of Spree 2 data migrations.
This issue can include #2247 but it's not specific to sessions.

### Impact and timeline
This will make backups run faster and take a lot less space.
And it can improve app performance: #3099

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #3608
Closes #2247

- Puts our databases on a much-needed diet by clearing out old data from the `spree_state_changes`, `spree_log_entries`, and `sessions` tables.
- Extracts `#remove_transient_data` from `TruncateData` and moves it to a separate rake task.
- Adds an entry in `config/schedule.rb` to run the task once per month.

#### What should we test?

Running `rake ofn:data:remove_transient_data` clears transient data as expected. Tailing the log shows an entry like this after running the task:

Screenshot from 2020-08-15 11-30-04

#### Release notes

Added scheduled task to clear old transient data from the database

### CODE REVIEW

File: lib/tasks/data/remove_transient_data.rb [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+    Spree::StateChange.delete_all("created_at < '#{retention_period}'")
+    Spree::LogEntry.delete_all("created_at < '#{retention_period}'")
+    Session.delete_all("updated_at < '#{retention_period}'")
+  end
+
+  private
+
+  def retention_period
+    2.months.ago.to_date
```
Comment (mkllnk) [inline lib/tasks/data/remove_transient_data.rb:21]: Can we start with six months, please? Sometimes it takes a while until a problem is recognised, documented and worked on.

File: lib/tasks/data/remove_transient_data.rb [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  # This model lets us operate on the sessions DB table using ActiveRecord's
+  # methods within the scope of this service. This relies on the AR's
+  # convention where a Session model maps to a sessions table.
+  class Session < ActiveRecord::Base
+  end
+
+  def call
+    Rails.logger.info("RemoveTransientData: processing")
+
+    Spree::StateChange.delete_all("created_at < '#{retention_period}'")
```
Comment (mkllnk) [inline lib/tasks/data/remove_transient_data.rb:13]:
```suggestion
    Spree::StateChange.where("created_at < ?", retention_period).delete_all
```

File: lib/tasks/data/remove_transient_data.rb [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+
+class RemoveTransientData
+  # This model lets us operate on the sessions DB table using ActiveRecord's
+  # methods within the scope of this service. This relies on the AR's
+  # convention where a Session model maps to a sessions table.
+  class Session < ActiveRecord::Base
+  end
+
+  def call
+    Rails.logger.info("RemoveTransientData: processing")
```
Comment (sauloperez) [inline lib/tasks/data/remove_transient_data.rb:11]:
```suggestion
    Rails.logger.info("#{self.class.name}: processing")
```
:ok_hand:

File: lib/tasks/data/remove_transient_data.rb (hunk 2 above)
Comment (sauloperez) [reply lib/tasks/data/remove_transient_data.rb:13]: Given `Spree::StateChange` has no callbacks, I would prefer getting the performance boost of `delete_all`. Instantiating a potentially large list of models will have its cost.

File: lib/tasks/data/remove_transient_data.rb (hunk 1 above)
Comment (sauloperez) [reply lib/tasks/data/remove_transient_data.rb:21]: we can start with 6 and see what's the impact on the system.

File: lib/tasks/data/remove_transient_data.rb (hunk 2 above)
Comment (mkllnk) [reply lib/tasks/data/remove_transient_data.rb:13]: I'm still suggesting to use `delete_all`. The `where` clause is just a bit neater.

Comment (sauloperez) [reply lib/tasks/data/remove_transient_data.rb:13]: right, I got confused with the `where` and thought it would instantiate the records. Yes, it won't.

**Comment by sauloperez** [comment]
I addressed all comments. Once green, we can give it a go in staging and hopefully have it ready soon so we stop dealing with AU's disk manually.

**Review by luisramos0 — APPROVED** [review]
Looks good, go!

**Review by mkllnk — APPROVED** [review]

**Comment by sauloperez** [comment]
I deployed and the `crontab` lists the new entry:

```
# Begin Whenever generated tasks for: ofn at: 2020-09-09 07:48:03 +0000
0 0 1 * * /bin/bash -l -c 'cd /home/openfoodnetwork/apps/openfoodnetwork/current && RAILS_ENV=staging bundle exec rake ofn:data:remove_transient_data --silent'
```

**Comment by sauloperez** [comment]
Alright, this definitely works although it doesn't log the SQL statements. I think it's totally fine as we already see a log line when it gets executed.

To be extra sure I wasn't getting confused with dates, I changed the code to `RETENTION_PERIOD = 1.day.ago.to_date` and it wiped out these three DB tables. Ready to go :tada: !
