### PR TITLE
Fixing incorrect payment and balance calculation

### LINKED ISSUE #4732: Reports Balance Calculation does not match User Balance Calculation
## Description

OFN has a very very basic ability to manage customer balances.

Shoppers can see their balance in Accounts -> Transactions.

Hub Managers can see customer balances in Reports -> Order Cycle Management -> Payment Methods reports.

The two places use different calculations to come to a customer balance. Shoppers see a sum or order balances while hub managers see a sum of order totals minus payments.

These two calculations should match. In the code the most common method used is the version the shoppers see. The Reports should use that method too.

## Expected Behavior

Shoppers and Hub Managers see a consistent balance. 

## Actual Behaviour

Shoppers and Hub Managers are seeing different balances

## Steps to Reproduce

1. Shop and make payments for a shopper.
2. Cancel a payment for the shopper in Edit Orders -> Payments
3. Go to Accounts -> Transactions and see one balance for the shopper
4. Go to Reports -> Order Cycle Management -> Payment Methods report and see a different balance for the shopper
5. Cringe at the difference.

## Workaround

Our current work around is to not use this feature!

## Severity

bug-s4: a feature is broken and there is no workaround. The feature is currently unused but in hot demand.

## Your Environment

* Version used: 2.7.1 UK
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Ubuntu

### PR DESCRIPTION
**Pull request by lin-d-hop**
#### What? Why?

Closes #4732

OFN has a very very basic ability to manage customer balances.

Shoppers can see their balance in Accounts -> Transactions.

Hub Managers can see customer balances in Reports -> Order Cycle Management -> Payment Methods reports.

The two places use different calculations to come to a customer balance. Shoppers see a sum or order balances while hub managers see a sum of order totals minus payments.

These two calculations should match. In the code the most common method used is the version the shoppers see. The Reports should use that method too.
#### What should we test?

To test:

1. With a shopper account create some orders and payments.
2. As Hub manager make adjustments to the orders and payments. Including voiding payments and orders. Add multiple payments to an order and include addition payments so that the orders also have more payments than the order amount.
3. As you make the changes in step 2 check the Shopper balance in Accounts -> Transactions. Compare this to the Balance and Payment Totals shown in Reports -> Order Cycle Management Reports -> Payment Methods Report.

The figures should match with all the changes you make.

#### Release notes

Hub Managers can accurately monitor Shopper balances using Payment Methods report

Changelog Category: Fixed

#### Discourse thread

First step in 
https://community.openfoodnetwork.org/t/2-enable-customers-to-pay-partially-or-fully-with-their-credits/1211/31

#### Documentation updates

We'll update the documentation after scoping the minimal acceptance criteria for Enabling Customers to pay with credits.

### CODE REVIEW

File: lib/open_food_network/order_cycle_management_report.rb [hunk 1]
```diff
@@ -130,6 +130,10 @@ def is_payment_methods?
       params[:report_type] == "payment_methods"
     end
 
+    def payments_total(payments)
+      payments_total = payments.sum(&:amount)
+    end
```
Comment (lin-d-hop) [inline lib/open_food_network/order_cycle_management_report.rb]: Assignment not needed. Thanks CodeClimate :-)

Comment (lin-d-hop) [reply lib/open_food_network/order_cycle_management_report.rb]: Ping devs - I have a question here.
This is broken as it is also showing Void payments and Incomplete payments.
I would be very grateful if someone could help me strip out Void and Incomplete payments such that the Payments total is accurate.
Thanks in advance!

Comment (luisramos0) [reply lib/open_food_network/order_cycle_management_report.rb]: you shouldnt do biz logic here, the models do that for you.
Maybe you just need order.payment_total ?

Comment (lin-d-hop) [reply lib/open_food_network/order_cycle_management_report.rb]: That is exactly the kind of wisdom I was looking for... Wisdom to help noobs :-)

File: lib/open_food_network/user_balance_calculator.rb [hunk 2]
```diff
@@ -6,25 +6,14 @@ def initialize(email, distributor)
     end
 
     def balance
-      payment_total - completed_order_total
+      completed_orders.sum(&:outstanding_balance)
```
Comment (luisramos0) [inline lib/open_food_network/user_balance_calculator.rb]: I think this is correct but youare inverting the sign of the balance.
order.outstanding_balance is the positive valuee that buyer must pay.
this balance method here was "user balance".
order is 30 you have paid 10. order.outstand_balance = 20 this method -20

Comment (luisramos0) [inline lib/open_food_network/user_balance_calculator.rb]:
```suggestion
      - completed_orders.sum(&:outstanding_balance)
```

**Comment by RachL** [comment]
Nice! This is working well :-)

I noticed that the buyer's profile does not list the payment as "paid" if you paid and capture more money than your order amount.

But this is already in production, so this PR can go. Moving to ready to go and creating an issue.
