### PR TITLE
On checkout of pickup orders, set ship_address to shipping_address_from_distributor instead of empty Spree::Address.default

### LINKED ISSUE #4005: StateMachine::InvalidTransition in checkout#update
## Error in OpenFoodNetwork

**StateMachine::InvalidTransition** in **checkout#update**
Cannot transition state via :restart_checkout from :payment (Reason(s): State cannot transition via "restart checkout")

[View on Bugsnag](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d1948bc850871001b662ad5?event_id=5d1948bc00469dfd87950000&i=gh&m=ci)

## Stacktrace

    app/services/restart_checkout.rb:22 - reset_state_to_cart
    app/services/restart_checkout.rb:10 - call
    app/controllers/checkout_controller.rb:142 - update_failed
    app/controllers/checkout_controller.rb:40 - update

[View full stacktrace](https://app.bugsnag.com/yaycode/openfoodnetwork/errors/5d1948bc850871001b662ad5?event_id=5d1948bc00469dfd87950000&i=gh&m=ci)

*Created by Maikel via Bugsnag*

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #4005 and probably #4003 

In CheckoutController#update, instead of clearing ship address by setting it to empty Spree::Address.default, we set shipping_address_from_distributor which is what's done already when order is finalized.

#4005 was happening because an **empty** ship address (set in clear_ship_address) makes restart_checkout fail. restart_checkout_spec was not detecting this because it was using a **nil** ship_address.
We now set the distributor ship address on ship_address and also test that scenario in both restart_checkout_spec and checkout_controller.

#### What should we test?
We need to test checkout manually. The scenario that changed was when checking out using a pick up ship method without ship address and using a broken bogus credit card, the user was getting a sail or just not seeing any errors, now the user should see an flash error: credit card payment failed.

Added by Maikel:
Verify every way the checkout can fail:
- Out of stock
- Payment method not set up correctly
- Invalid credit card
Test these with a shipping method that needs an address and without. Then try to checkout again and make sure that the right shipping address is either preserved or blank and needs filling in.

Extra scenario added by Luis:
On checkout:
- ship method is pickup, no ship address form
- checkout with failed payment and see payment error
- go back to ship methods and change to some delivery ship method
- make sure the ship address shown by default is not the distributor's address

#### Release notes
Changelog Category: Fixed
Fixed problem in user checkout when payment validation failed. User is now being informed of what is wrong in the checkout form.

### CODE REVIEW

File: app/controllers/checkout_controller.rb [hunk 1]
```diff
@@ -165,15 +165,6 @@ def update_failed
     end
   end
 
-  # When we have a pickup Shipping Method,
-  #   we clone the distributor address into ship_address before_save
-  # We don't want this data in the form, so we clear it out
```
Comment (sauloperez) [inline app/controllers/checkout_controller.rb]: so we'll miss this behavior, right? users will see the address of the distributor which on the other hand seems good.

**Comment by luisramos0** [comment]
thanks @mkllnk for the review and test scenarios!

--- I'm not clear on a case though: What happens when the shipping method requires an address? Do we set the distributor's address and the user won't see it during checkout because it's collapsed (done)?

When the shipping method requires an address, OrderUpdater#shipping_address_from_distributor does nothing so the user needs to input the address.
```
  def shipping_address_from_distributor
    return if order.shipping_method.blank? || order.shipping_method.require_ship_address
```

File: app/controllers/checkout_controller.rb (hunk 1 above)
Comment (luisramos0) [reply app/controllers/checkout_controller.rb]: the behaviour is the same but instead of an empty address we inject the distributor address (instead of this clear_ship_address, we are calling OrderUpdater#shipping_address_from_distributor).

When the ship method is pick up, the ship address form is not shown on checkout, so the user will not see it.

One test scenario I did here (will move it to the description so testers can try):
- ship method is pickup, no ship address form 
- checkout with failed payment and see payment error
- go back to ship methods and change to some delivery ship method
- make sure the ship address shown by default is not the distributor's address

**Comment by luisramos0** [comment]
I have updated the test scenarios in the description.

File: app/controllers/checkout_controller.rb (hunk 1 above)
Comment (mkllnk) [reply app/controllers/checkout_controller.rb]: I was wondering about this case:

- ship method requires address
- checkout with failed payment
- what is the ship address now?

Comment (luisramos0) [reply app/controllers/checkout_controller.rb]: yes, I tested that. the ship address is not overritten, it will be whatever the user wrote  because the shipping_address_from_distributor will not update ship address if order.shipping_method.require_ship_address

**Comment by RachL** [comment]
@luisramos0 my first tests results:

A. Checking out with an invalid Bogus credit card with Pick-up shipping method (no shipping address form) results in no errors for the user (error 400 in dev tools)
image


B. Trying to add stripe as a payment method on a shop and I get an error 500:

image

Could it be that the PR was incorrectly staged?
Notes to myself:
https://docs.google.com/document/d/1tcwWTCUaS_ZCzJp3bN4KB7AXOcFOCukcONGZ_q_VOpI/edit#

**Comment by luisramos0** [comment]
the PR is correctly staged.

case A - the problem is credit card date. For some reason, if the card is expired (a specific problem) the flash message is not set. I remember seeing this while in dev but could not fix it quickly. As this is an S2, I think we should open a separate issue for this one.
I tried to checkout with same invalid card number and code but with a date after current date, and the error is displayed.

case B - is stripe setup in uk staging?

**Comment by luisramos0** [comment]
case A - now I see you used Jan 2022, I will retest :-/

**Comment by luisramos0** [comment]
case A - I cant replicate, unless I put an expired date.... can you try to replicate and if it happens click on the Response tab in the 400 error?

**Comment by luisramos0** [comment]
case B - cant find the snail, can you add specific steps to get to the snail? Thanks!

**Comment by RachL** [comment]
@luisramos0

Case B: I forgot yes stripe is not working in UK staging... :facepalm:
Will stage on to FR.

About A. I have the following message:
image

Yet I do have "pick-up as the only shipping method".... will start again on FR and keep you posted

**Comment by sauloperez** [comment]
@RachL would you mind creating an issue to add/fix Stripe to UK staging?

**Comment by sigmundpetersen** [comment]
https://github.com/openfoodfoundation/ofn-install/issues/283

**Comment by RachL** [comment]
This is looking good on staging FR!

https://docs.google.com/document/d/1tcwWTCUaS_ZCzJp3bN4KB7AXOcFOCukcONGZ_q_VOpI/edit#

**Comment by luisramos0** [comment]
🎉
