### PR TITLE
[Release test automation] Adds assertions on bulk invoice creation

### LINKED ISSUE #10967: Improve bulk invoice printing spec
### What we should change and why (this is tech debt)

We currently have a test for this on `./spec/system/admin/orders_spec.rb`. But it does not quite help prevent regressions related to missing directories or sidekiq:

```
        it "can bulk print invoices from 2 orders" do
          page.find("#listing_orders tbody tr:nth-child(1) input[name='bulk_ids[]']").click
          page.find("#listing_orders tbody tr:nth-child(2) input[name='bulk_ids[]']").click

          page.find("span.icon-reorder", text: "ACTIONS").click
          within ".ofn-drop-down .menu" do
            page.find("span", text: "Print Invoices").click
          end

          expect(page).to have_content "Compiling Invoices"
          expect(page).to have_content "Please wait until the PDF is ready "\
                                       "before closing this modal."
          # an error 422 is generated in the console
        end
```

Not sure why we always get that 422...

### Context

Related to #10955.

### Impact and timeline

Not having to test this manually on each release testing :see_no_evil:

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

- Closes #10967 

The system spec only went as far as clicking on the menu. Because we don't have Sidekiq running in the test environment, we can explicitly trigger the BulkPrint job, and assert that the new modal appears, with the correct link to the pdf file.

We were checking this manually, during release testing.

#### What should we test?

- green build

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1 or DFC)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/orders_spec.rb [hunk 1]
```diff
@@ -583,7 +583,11 @@
           expect(page).to have_content "Compiling Invoices"
           expect(page).to have_content "Please wait until the PDF is ready " \
                                        "before closing this modal."
-          # an error 422 is generated in the console
+
+          # Invoices are never compiled in the test environment
+          # so, these assertions fail
+          expect(page).to have_content "Bulk Invoice created"
+          expect(page).to have_content "View File"
```
Comment (mkllnk) [inline spec/system/admin/orders_spec.rb:590]:
```suggestion
          perform_enqueued_jobs(only: BulkInvoiceJob)
          expect(page).to have_content "Bulk Invoice created"
          expect(page).to have_content "View File"
```

**Review by dacook — APPROVED** [review]
Yay, great to automate a manual test!

**Comment by dacook** [comment]
This implements Maikel's suggestions so I'll assume his approval and merge.
