### PR TITLE
Ensure product category error message is shown when creating new product [OFN-12591]

### LINKED ISSUE #12591: Error 500 when product category left blank
## Description

This seems to be a somewhat recent regression:
leaving the product category empty while creating a product returns an error 500.

## Expected Behavior

leaving the product category empty while creating should display a message to the user, no error 500 should be seen - See pic below, taken from staging-UK which has not been updated for quite a while now:

image

## Actual Behaviour

Leaving the product category empty while creating a product returns an error 500.

## Steps to Reproduce

1. Log in as an enterprise user
2. Visit the products page and click "New Product"
3. Fill in all the mandatory fields except Product Category
4. Click "Create"

## Animated Gif/Screenshot

[Screencast from 19-06-24 14_47_17.webm](https://github.com/openfoodfoundation/openfoodnetwork/assets/49817236/e05c7f6c-9c62-4333-af74-1946abc0e1cd)

## Workaround

Fill in product category before clicking "Create"

## Severity

bug-s3: a feature is broken but there is a workaround

## Your Environment

* Version used: v4.4.52
* Browser name and version: Firefox 126.0.2
* Operating System and version (desktop or mobile): Ubuntu 22.04

### PR DESCRIPTION
**Pull request by wandji20**
#### What? Why?

- Closes #12591
For validations to run on a product variant when creating a product, I changed the `ensure_standard_variant ` to run after validations have run and updated the error messages.

#### What should we test?
Creating a product without a category will display the proper error message
Creating a product without a producer will display the proper error message

- http://localhost:3000/admin/products/new

#### Release notes

Add an error message when creating a new product without a product category or without producer 

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] Technical changes only

The title of the pull request will be included in the release notes.

Add an error message when creating a new product without a product category

#### Dependencies
<!-- Does this PR depend on another one?
N/A

#### Documentation updates
N/A

### CODE REVIEW

File: app/models/product_import/entry_processor.rb [hunk 1]
```diff
@@ -149,6 +149,7 @@ def save_existing_inventory_item(entry)
       end
     end
 
+    # rubocop:disable Metrics/AbcSize
```
Comment (dacook) [inline app/models/product_import/entry_processor.rb:152]: Curious, I don't see how this change increased the [ABC size](https://www.rubydoc.info/gems/rubocop/0.27.0/RuboCop/Cop/Metrics/AbcSize), so I'm not sure if this `disable` comment is necessary.

If it is, it would be better to add it to the `.rubocop_todo.yml` file, to remind us to improve it next time we work on the file.

File: app/models/spree/product.rb [hunk 2]
```diff
@@ -288,6 +289,21 @@ def description=(html)
...
 
+    def validate_variant_attrs
+      # Avoid running validation when we can't set variant attrs
+      # eg clone product. Will raise error if clonning a product with no variant
+      return if variants.first&.valid?
+
+      unless Spree::Taxon.find_by(id: primary_taxon_id)
+        errors.add(:primary_taxon_id,
+                   I18n.t('activerecord.errors.models.spree/product.must_exist'))
+      end
```
Comment (dacook) [inline app/models/spree/product.rb:300]: I didn't follow why the category is included here, but I see you've been discussing with Gaetan so will let him confirm.

**Review by dacook — APPROVED** [review]
Looks good to me, apart from one query for Gaetan. Thank you!

File: app/models/product_import/entry_processor.rb (hunk 1 above)
Comment (rioug) [reply app/models/product_import/entry_processor.rb:152]: It does change the Abc size somehow, I just tested. I can't see a quick and easy solution to fix that, so better to add it to `.rubocop_todo.yml`. You can run the following command to do so : 
```
bundle exec rubocop --regenerate-todo --no-auto-gen-timestamp
```

**Review by rioug — CHANGES_REQUESTED** [review]
Good effort ! I think it needs a few tweaks to clean it up, see comments below. We are also missing a spec for creating a product without a producer (supplier), could you add that?

Thanks !

File: config/locales/en.yml [hunk 3]
```diff
@@ -68,7 +68,7 @@ en:
       spree/product:
         name: "Product Name"
         price: "Price"
-        primary_taxon: "Product Category"
+        primary_taxon_id: "Product Category"
```
[the remark this answers is not in the document]
Comment (wandji20) [reply config/locales/en.yml:71]: @rioug
It is correct that primary_taxon is now linked to the variant.

However, we still use it at least to collect form input and display the correct error message.
Removing this will result in a validation message **Primary taxon must exist** instead of **Product Category must exist**

Not so sure if users understand that the Primary taxon refers to the Product category in this case.

File: app/models/product_import/entry_processor.rb (hunk 1 above)
Comment (rioug) [reply app/models/product_import/entry_processor.rb:152]: @wandji20 you need to remove the rubocop comments before updating the todo files, otherwise it gets ignored.

File: config/locales/en.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (rioug) [reply config/locales/en.yml]: I see, didn't realised that. Sorry could you revert it back to how you did it the first time ? I don't expect user to understand what the Primary taxon refers to.

**Review by rioug — CHANGES_REQUESTED** [review]
Thanks for the quick turn around. There are still a couple things to iron out see my comments. Sorry about the translations, I somehow missed it was still used :pray:

**Review by rioug — APPROVED** [review]
Looks good now, Thanks :pray:

**Comment by filipefurtad0** [comment]
Hey @wandji20 ,
I see there are conflicts on the `.rubocop_todo.yml` file. Are you able to fix these?

Moving to In progress, for the time being.

**Comment by wandji20** [comment]
> Hey @wandji20 , I see there are conflicts on the `.rubocop_todo.yml` file. Are you able to fix these?
> 
> Moving to In progress, for the time being.

For this, I rebased and regenerated `.rubocop_todo.yml` with `bundle exec rubocop --regenerate-todo --no-auto-gen-timestamp`

**Review by rioug — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @wandji20,
Thank you for yet another PR! Before staging I also couldn't reproduce the error 500 but found that products could be created without variants - just like you mentioned.

I tested this in detail while I was working on it anyway, so you will thing below, which are out of scope for this PR, but I found it worth mentioning for completeness. 

## Comparison before and after staging the PR

| Field | Before | After |
| - | - | - |
| Supplier | No error when empty :x: | :exclamation: Error when empty :heavy_check_mark: :muscle: |
| | Product can be created when empty, but no variant created :x: | :exclamation: Product can't be created :heavy_check_mark: :muscle: |
| | No red highlighting at all on error :x: | No red color of field's label on error :x: |
|  Product name | Error when empty :heavy_check_mark: | Error when empty :heavy_check_mark: |
| Unit size | Error when empty :heavy_check_mark: | Error when empty :heavy_check_mark: |
| | No red border on error :x: | No red border on error :x: |
| Value (if variant unit == item) | No error when empty (set to '1') :heavy_check_mark: | No error when empty (set to '1') :heavy_check_mark: |
| Unit name (if variant unit == item) | Error when empty :heavy_check_mark: | Error when empty :heavy_check_mark: |
| | Unit name is not kept after error messages :x: | Unit name is not kept after error messages :x: |
| | No red highlighting at all on error :x: | No red highlighting at all on error :x: |
| Value (if variant unit != item) | Error when not a number :heavy_check_mark: | Error when not a number :heavy_check_mark: |
| | No red border on error :x: | No red border on error :x: |
| Display as (if variant unit != item) | No error when empty :heavy_check_mark: | No error when empty :heavy_check_mark: |
| Product category | No error when empty :x: | :exclamation: Error when empty :heavy_check_mark: :muscle: |
| | Product can be created when empty, but no variant created :x: | :exclamation: Product can't be created :heavy_check_mark: :muscle: |
| | No red highlighting at all on error :x: | No red border on error :x: |
| Price | Error when not a number :heavy_check_mark: | Error when not a number :heavy_check_mark: |
| Unit price | Auto-filled :heavy_check_mark: | Auto-filled :heavy_check_mark: |
| Tax category | Pre-selected :heavy_check_mark: | Pre-selected :heavy_check_mark: |
| Shipping category | Pre-selected :heavy_check_mark: | Pre-selected :heavy_check_mark: |
| | Shipping category is not kept after error message :x: | Shipping category is not kept after error message :x: |
| On hand | No error when empty (set to 0) :heavy_check_mark: | No error when empty (set to 0) :heavy_check_mark: |
| On demand | Checkbox only :heavy_check_mark: | Checkbox only :heavy_check_mark: |
| Image | No error when empty :heavy_check_mark: | No error when empty :heavy_check_mark: |

## Further ideas for improvement
  - Use same 'can't be blank' string for supplier and product category as for e.g. product name.
  - Unify the three different types of drop down menus:
    - Modern design wth pre-filled 'Select a supplier'
    - Modern design without pre-filled information (completely empty)
    - Legacy design (smaller line heights, no highlighting on hover)

### General remark
  - Unit value (if variant unit == item) can only be edited on /products, not on the /edit page.

## Conclusion
The issue in #12591 is resolved. :muscle: 
There was no regression found within this PR. :partying_face: 
Anything else I found was out of scope of this PR.
We can merge and address the other bits in separate PRs. :rock: 

Thanks again for your work!

**Comment by drummer83** [comment]
@wandji20 I've created #12744 just in case you would like to tackle some of those. No need to address them all at once.
Thanks again!

**Comment by wandji20** [comment]
Sure @drummer83 
That is fine by me
