### PR TITLE
3426 [Flaky Spec] Address timing issues in enterprise users feature specs

### LINKED ISSUE #3426: [Flaky Spec] /spec/features/admin/enterprise_roles_spec.rb:131,147
## Description

These specs are unreliable: 
rspec ./spec/features/admin/enterprise_roles_spec.rb:131
rspec ./spec/features/admin/enterprise_roles_spec.rb:147

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/pull-request-3209/builds/12

## Context

Our Semaphore builds fail regularly because of these unreliable tests. If you encounter this in your build, please comment on this issue or add :+1: 

Error:

```
  4) 
  As an Administrator
  I want to manage relationships between users and enterprises
 as a site administrator using the enterprise managers interface can invite unregistered users to be managers
     Failure/Error: expect(page).to have_selector "table.managers"
       expected to find visible css "table.managers" but there were no matches. Also found "", which matched the selector but not all filters.
     # ./spec/features/admin/enterprise_roles_spec.rb:102:in `block (4 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by kristinalim**
Address timing issues in enterprise users feature specs.

#### What? Why?

Closes #3426 

#### What should we test?

Semaphore build should be green.

In the long term, this test should also not fail.

#### Release notes

* Address intermittently failing feature tests

Changelog Category: Fixed

### CODE REVIEW

File: spec/features/admin/enterprise_roles_spec.rb [hunk 1]
```diff
@@ -170,9 +172,16 @@
...
 
-
   private
 
+  def navigate_to_enterprise_users
+    within ".side_menu" do
+      click_link "Users"
+    end
+
+    expect(page).to have_selector "table.managers"
```
Comment (sauloperez) [inline spec/features/admin/enterprise_roles_spec.rb]: I wouldn't add this here as we're coupling the actual navigation with an assertion. As a result, in line 133 above we're adding an extra step that we don't need. That being said, I don't think line 101 should need it.

Comment (sauloperez) [reply spec/features/admin/enterprise_roles_spec.rb]: what do you think @kristinalim ?

Comment (kristinalim) [reply spec/features/admin/enterprise_roles_spec.rb]: @sauloperez I moved check for table presence out of the helper method. Build is green, and I moved this back to Code Review.
