### PR TITLE
First stored credit card becomes default again

### LINKED ISSUE #3727: [Subs] Intermittent Failures on Payments
## Description

We are getting weekly reports of payments failing in subscriptions.
This is not happening on all customers - generally one or two customers per week. A number of enterprises have reported this issue but on UK Prod it seems to be affecting Farmham Community Farm the most.

## Expected Behavior

Subscription payments should complete as expected without error

## Actual Behaviour

Occasional payment failures with the error:
Errors: You cannot use a Stripe token more than once

## Steps to Reproduce

I don't yet know how to reproduce this error, but chat to me on Slack and I'll share details of specific customers to help with searching the logs.

## Animated Gif/Screenshot

Screenshot from 2019-04-11 10-45-04

## Context

This means that the hub needs to take payment for the subscription outside of OFN then manually update OFN to say that payment has in fact been received. This is a major headache for the hub.

## Severity

S2
## Your Environment

* Version used: v1.29
* Browser name and version: Chrome
* Operating System and version (desktop or mobile): Desktop
* OFN Platform instance where you discovered the bug, and which version of the software they are using. UK Production

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

Closes #3727 

A user can store their credit card when checking out. Due to a bug in https://github.com/openfoodfoundation/openfoodnetwork/pull/3840 it
didn't become the default card any more. This behaviour is now restored.
If there is no default card yet, a new card added during checkout
becomes the default card.

#### What should we test?

Not storing:

- Set up Stripe for a shop.
- Delete all credit cards of the current user.
- Check out using Stripe, not storing the credit card.
- The new card should not appear in the stored cards (account profile).

Storing:

- Check out using Stripe, storing the entered credit card.
- Check the stored cards. The new card should be there and should be the default.
- Repeat another checkout storing a new card.
- The new card should be stored but not become the default (the default stays the same).

Storing a card in the profile:

- Create a card in the profile.
- The previous default card should stay the same.
- Then delete the default card.
- Now there is no default card.
- Create a new card.
- The new card should be the default.

#### Release notes

Fixed: The first stored credit card is automatically the default card again.

Changelog Category: Fixed

### CODE REVIEW

File: app/models/spree/credit_card_decorator.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@
   belongs_to :user
 
   after_create :ensure_single_default_card
-  after_save :ensure_single_default_card, if: :is_default_changed?
+  after_save :ensure_single_default_card, if: :default_card_needs_updating?
```
Comment (luisramos0) [inline app/models/spree/credit_card_decorator.rb]:
```suggestion
  after_save :ensure_single_default_card
  
  def ensure_single_default_card
      return unless default_card_needs_updating?
```

I think these inline if statements are never a good idea and should be moved into the method itself.
actually, I think callbacks are never a good idea, in this case, that means that saving a credit card should be in a service.

Comment (mkllnk) [reply app/models/spree/credit_card_decorator.rb]: > I think these inline if statements are never a good idea and should be moved into the method itself.

I agree. The difficulty here is that we have two different events calling the same method (create and save events). They don't share the same conditions.

I also agree with avoiding callbacks. I opened a new tech debt issue: #3966. Please let me know what you think about the two modelling options.

Comment (luisramos0) [reply app/models/spree/credit_card_decorator.rb]: I see :+1:
I left my vote in the tech debt issue.

**Comment by RachL** [comment]
@mkllnk thank you so much for you detailed testing notes :)

Everything is looking good! Notes: https://docs.google.com/document/d/13Z3Iy15o3kZgMYp3ZUCv-ZGCZaBOT4TnIFYWAutsqvY/edit#
