### PR TITLE
Disable hiding of hamburger menu upon resize <= 1024px width

### LINKED ISSUE #2907: Can't login anymore on mobile (hamburger menu too long and closing when scroll)
## Description
I try to login on mobile, open the hamburger menu on the left, but the list is long now that we have more menus on the French production, so I try to scroll with my finger to reach the "se connecter" (=login) menu, but when I scroll the menu closes ! 

## Expected Behavior
I manage to access the login menu on mobile

## Actual Behavior
I don't

## Steps to Reproduce
1. With a mobile (I did with Iphone SE) go to www.openfoodfrance.org and click on the hamburger menu on the top left corner.
2. Try to scroll to reach "se connecter" which is the last menu entry not visible if you don't scroll
3. See the result

## Context
I was doing some testing.

## Severity
S2, I have no way if I want to do a quick intervention on my hub to login on mobile.

## Your Environment
* Version used: V1.21 on French production, iPhone SE
* Browser name and version: Safari
* Operating System and version (desktop or mobile): Iphone OS

## Possible Fix
- Enable scrolling on hamburger menu?

### PR DESCRIPTION
**Pull request by kristinalim**
#### What? Why?

Closes #2907 

Disable hiding the hamburger menu (off-canvas) upon window resize to less than 1024px width.
    
In some browsers for mobile devices, the address bar is automatically hidden when scrolling down the page. This is not workable if the height of the contents of the hamburger menu exceeds the height of the screen, because the latter portion of the contents stays hidden to the user.

Refer to code of directive: https://github.com/openfoodfoundation/angular-foundation/blob/0.9.020180826174721/src/offcanvas/offcanvas.js

Merely changing the hamburger menu to be scrollable is quite tangly and will need a lot of testing because of how the DOM elements are laid out, which I think this is counter-productive. The behaviour of automatically closing the hamburger menu is introduced by [angular-foundation](https://github.com/openfoodfoundation/angular-foundation/blob/0.9.0-20180826174721/src/offcanvas/offcanvas.js#L2) which has long been unsupported. We should move away from the library rather than work around its features.

#### What should we test?

Test closed and open hamburger menu for different screen sizes, and switching between landscape and portrait for mobile devices.

#### Release notes

- Disable hiding of hamburger menu in screen widths of not more than 1024px.

Changelog Category: Fixed

#### How is this related to the Spree upgrade?

The behaviour should be checked again if the version of Foundation is upgraded.

### CODE REVIEW

**Comment by sigmundpetersen** [comment]
@kristinalim that spec fails often in semaphore, just try a rebuild

File: app/assets/javascripts/darkswarm/directives/off_canvas_wrap.js.coffee [hunk 1]
```diff
@@ -19,4 +22,8 @@ angular.module('mm.foundation.offcanvas').directive 'offCanvasWrap', ($window) -
 
       # Unbind hiding of the off-canvas upon window resize.
       win.unbind('resize.body', isolatedScope.hide)
+
+      # Bind hiding of the off-canvas that only happens when screen width is over 1024px.
+      win.bind 'resize.body', ->
+        isolatedScope.hide() if $(window).width() > 1024
```
Comment (luisramos0) [inline app/assets/javascripts/darkswarm/directives/off_canvas_wrap.js.coffee]: I think you can use $window
https://docs.angularjs.org/api/ng/service/$window

**Comment by luisramos0** [comment]
staged staging.openfoodfrance.org

**Comment by myriamboure** [comment]
I'm testing it straight away, hopefully it can go into the release!!

**Comment by myriamboure** [comment]
I didn't open a file for this, it is working, I can browse the hamburger menu and access the login ! And I can login. Good to go !

**Comment by myriamboure** [comment]
img_9596
