### PR TITLE
3332 [Enterprise Fee Summary] Disable report for non-superadmin users

### LINKED ISSUE #3332: [Enterprise Fee Summary] Hide report link with feature flag
Hide report link with feature flag.

## Description

This was recommended by @sauloperez [in Slack](https://openfoodnetwork.slack.com/messages/C2GQ45KNU/convo/C2GQ45KNU-1547186925.158100/).

The link should be visible only to superadmins. However, any enterprise user can also access the report by going directly to the URL.

## Expected Behavior

A non-superadmin user should not see "Enterprise Fee Summary" in the list of reports.

## Actual Behavior

All enterprise users see "Enterprise Fee Summary" in the list of reports.

## Steps to Reproduce

In the admin section:

1. Log in as a non-superadmin user.
2. Go to the admin section.
3. Click on "Reports".
4. Notice the "Enterprise Fee Summary" link.

### PR DESCRIPTION
**Pull request by kristinalim**
#### What? Why?

Closes #3332

This exposes the "Enterprise Fee Summary" link and resource to only superadmins. This will allow us to merge existing changes for the report to master even if there are still bugs.

This doesn't enable the feature for non-production environments. Note that this limits permission testing that can be done, so a thorough round of permission testing needs to be done before the feature toggle is enabled for all enterprise users.

#### What should we test?

As superadmin:

1. Go to "Reports". There should be a link to "Enterprise Fee Summary".
2. Click on the link. There should be no permission issues.
3. Generate a report that is expected to provide data. Data should be provided.

As manager of an enterprise with orders:

1. Go to "Reports". There should be no link to "Enterprise Fee Summary".
2. Go directly to URL path `/admin/reports/enterprise_fee_summary/new`. There should be a permissions issue.

#### Release notes

- Expose "Enterprise Fee Summary" only to superadmin users.

Changelog Category: Changed

#### Dependencies

This would be merged into the transitional branch "feature/enterprise_fee_summary", not "master".

### CODE REVIEW

File: app/models/spree/ability_decorator.rb [hunk 1]
```diff
@@ -283,6 +283,16 @@ def add_relationship_management_abilities(user)
...
+
+  def add_enterprise_fee_summary_abilities(user)
+    feature_enabled = FeatureFlags.new(user).enterprise_fee_summary_enabled?
+    return unless feature_enabled
+
+    # Reveal the report link in spree/admin/reports#index
+    can [:enterprise_fee_summary], :report
+    # Allow direct access to the report resource
+    can [:admin, :new, :create], :enterprise_fee_summary
+  end
```
Comment (sauloperez) [inline app/models/spree/ability_decorator.rb]: This file is already quite unmanageable and although I love the path you take @kristinalim I'd go one step further and split abilities into multiple files. It is as easy as registering the individual classes as we do in line 298. If you agree, could you create a tech debt issue for it?

File: spec/support/feature_flags_helper.rb [hunk 2]
```diff
@@ -0,0 +1,10 @@
+module FeatureFlagsHelper
+  def set_feature_flag(user, feature, status)
+    feature_flags = instance_double(FeatureFlags, "#{feature}?" => status)
+    allow(FeatureFlags).to receive(:new).with(user) { feature_flags }
+  end
+
+  def unstub_feature_flags(user)
+    allow(FeatureFlags).to receive(:new).with(user).and_call_original
+  end
+end
```
Comment (sauloperez) [inline spec/support/feature_flags_helper.rb]: I'm not sure it's really worth introducing new methods for what `allow` already does and with which all devs are familiar with. If feature flags were more tedious it'd make more sense.

File: spec/models/feature_flags_spec.rb [hunk 3]
```diff
@@ -25,4 +25,22 @@
       end
     end
   end
+
+  describe ".enterprise_fee_summary_enabled?" do
```
Comment (sauloperez) [inline spec/models/feature_flags_spec.rb]: the convention of the `.` prefix is used to note this is a class method while `#` for instance ones. As this case is the latter, I would stick to it and use `#`. It will be confusing otherwise.

**Comment by sauloperez** [comment]
I'm really happy to see us adopting feature flags to ship more often :tada: !

File: spec/models/feature_flags_spec.rb (hunk 3 above)
Comment (kristinalim) [reply spec/models/feature_flags_spec.rb]: Agh, yes thanks! I copied that from the other example group - fixed both already.

File: spec/support/feature_flags_helper.rb (hunk 2 above)
Comment (kristinalim) [reply spec/support/feature_flags_helper.rb]: After thinking it over, I'm okay with removing these spec helpers. Done! Thanks, @sauloperez.

File: app/models/spree/ability_decorator.rb (hunk 1 above)
Comment (kristinalim) [reply app/models/spree/ability_decorator.rb]: Nice! I created the tech debt issue: #3345

**Comment by kristinalim** [comment]
I've made changes based on the review.

@sauloperez kindly approve if you're already okay with this. :slightly_smiling_face:

**Comment by kristinalim** [comment]
FYI, I rebased this PR's branch upon the recently rebased (upon master) `feature/enterprise_fee_summary`.

**Comment by kirstenalarsen** [comment]
ok flag works. Fee report can be seen / used as superadmin but not as enterprise

**Comment by kristinalim** [comment]
Okay, merging this to our transitional branch now. Thanks, @kirstenalarsen!
