### PR TITLE
Bring the spree_get spec helpers from spree and move them together with the api_get spec helpers

### LINKED ISSUE #5533: [Spree 2.1] Broken spec - EnterprisesController missing routes
Errors:

```
  1) EnterprisesController as an enterprise owner creating an enterprise creates as sells=any when it is not a producer
     Failure/Error: spree_post :create, { enterprise: new_enterprise_params }
     
     AbstractController::ActionNotFound:
       The action 'create' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:33:in `block (4 levels) in <module:Api>'

  2) EnterprisesController as an enterprise owner creating an enterprise saves all user ids submitted
     Failure/Error:
       spree_post :create, {
         enterprise: new_enterprise_params.
           merge({ user_ids: [enterprise_owner.id, manager1.id, manager2.id] })
       }
     
     AbstractController::ActionNotFound:
       The action 'create' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:43:in `block (4 levels) in <module:Api>'

  3) EnterprisesController as an enterprise manager submitting a valid image I can update enterprise image
     Failure/Error: spree_post :update_image, logo: 'a logo', id: enterprise.id
     
     AbstractController::ActionNotFound:
       The action 'update_image' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:71:in `block (4 levels) in <module:Api>'

  4) EnterprisesController as an non-managing user submitting a valid image I can't update enterprise image
     Failure/Error: spree_post :update_image, logo: 'a logo', id: enterprise.id
     
     AbstractController::ActionNotFound:
       The action 'update_image' could not be found for EnterprisesController
     # ./spec/controllers/api/enterprises_controller_spec.rb:90:in `block (4 levels) in <module:Api>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

I refactored this code as I was investigating #5533

The main change is that the spree_get actions are now setting use_route to :main_app and not :spree.

In rails 4.2 we will be able to replace this use_route with the `routes` entry as Spree did in v3:
https://github.com/spree/spree/commit/bd881d9d34e418eeb73a30440013bfeb31ebea45
This will mandatory for upgrading to rails 5.

Anyway, this did not fix #5533, I have created another PR to fix #5533 and #5504 

#### What should we test?
This only changes test code, needs a green build.

#### Release notes
Changelog Category: Changed
Improved test support code related to routing and controllers.

### CODE REVIEW

File: spec/controllers/api/shipments_controller_spec.rb [hunk 1]
```diff
@@ -14,12 +15,12 @@
 
   context "as a non-admin" do
     it "cannot make a shipment ready" do
-      api_put :ready
+      api_put :ready, order_id: shipment.order.to_param, id: shipment.to_param
```
Comment (sauloperez) [inline spec/controllers/api/shipments_controller_spec.rb:18]: thanks. This is the sort of change that will save ous valuable minutes while investigating a test failure :ok_hand:
