### PR TITLE
Cart variant scoping

### LINKED ISSUE #3222: Broken stock levels on product list page when product added and removed quickly from basket
## Description
I am pretty sure there is a bug in this commit/line:
https://github.com/openfoodfoundation/openfoodnetwork/commit/a26266159cefcdc55c2e1bff7d5498a9d88c069d#diff-0e4d2deb3b86720d428f95f51c0c19dfR65
This is calculating stock_levels (on_hand) for variants that are listed in the request but are not present in the order (prior to this code is executed, the method li_stock_levels fetches stock levels for variants present in the order). The problem is that variants coming from the order are scoped in the cart service (are transformed into overrides) but this Spree::Variant.find call does not scope variants, so the on_hand value sent is the variants one when it should be the override on_hand value if a override exists.

I am not too sure about this logic but looking at the commit this code was added to fix a problem with multiple requests where frontend code requests stocklevels for a specific list of variants but when the server executes, the variants are not in the order any more (probably due to another request removing them). We should keep the logic but fix the bug.

## Expected Behavior
In some cases on the product list when adding and removing quantities, stock levels reported will be the variants values even if buying from a hub with inventory.

## Actual Behavior
Inventory (variant overrides) stock levels are reported instead.

## Steps to Reproduce
I didn't replicate this and probably better just to get this covered in specs. I believe manual verification will be difficult.

## Context
Detected while fixing Spree Upgrade build.

## Severity
bug-s5: we can live with it, only a few users impacted

## Possible Fix
So, a few things need to be done here:
1. create spec to validate the bug exists
2. fix the bug by scoping the variant before calling on_hand
3. refactor code! the method names at least need to be improved (the current best way to understand what's going on is to read the tests [here](https://github.com/openfoodfoundation/openfoodnetwork/commit/a26266159cefcdc55c2e1bff7d5498a9d88c069d#diff-cc6b7d88d7ef9e9a51819e616293808fR98))

The fix to the bug will be something like this:
```
      variant = Spree::Variant.find(variant_id)
      cartService.scoper.scope(variant)
      stock_levels[variant_id] = { quantity: 0, max_quantity: 0, on_hand: variant.on_hand }
```

I found this issue because this is where #3118 is breaking in the v2 branch. This is only seen in v2 variant overrides specs because order.add_variant is not working for the spec in #3118. To be investigated as part of #3118

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #3222 
Possibly cause of S2: #5069

The code in the original issue has been moved around and refactored several times since it was opened, but the issue was still there.

Adds two tests for cases where `VariantsStockLevels` was used when populating the cart but no scoping was being done to the variants, and fixes both cases so the correct stock values are returned.

#### What should we test?

Adding/removing variants with variant overrides in the cart, should give correct feedback based on the override's stock, not the variant's stock.

#### Release notes

Updated cart stock logic to include variant overrides

Changelog Category: Fixed

### CODE REVIEW

File: app/services/variants_stock_levels.rb [hunk 1]
```diff
@@ -34,12 +34,21 @@ def notify_bugsnag(order, requested_variant_ids, order_variant_ids)
...
+           on_hand: variant.on_hand,
+           on_demand: variant.on_demand }]
       end
     ]
   end
+
+  def scoped_variant(distributor, variant)
+    return variant if distributor.blank?
+
+    OpenFoodNetwork::ScopeVariantToHub.new(distributor).scope(variant)
```
Comment (luisramos0) [inline app/services/variants_stock_levels.rb]: I think you need to memoize the scoper like this
```ruby
  def scoper(distributor)
    @scoper ||= OpenFoodNetwork::ScopeVariantToHub.new(distributor)
  end
```
this will avoid loading all the hubs overrides several times:
```ruby
  class ScopeVariantToHub
    def initialize(hub, variant_overrides = nil)
      @hub = hub
      @variant_overrides = variant_overrides || VariantOverride.indexed(@hub)
    end
```

**Comment by luisramos0** [comment]
I have moved this up in the test ready column as it is linked to an S2 #5069

**Comment by filipefurtad0** [comment]
Hi @Matt-Yorkley, 
I tried reproducing the bug, by trying out the basic functionality of product stock override, but no success - I didn't reproduce @RachL 's S2 bug #5069. Cash checkout works fine, as well as warnings for stock limitations imposed by inventory settings.

So I staged the PR, and:
- Backoffice ->limited the stock in inventory (override)
- Shopfront -> added several products to cart, testing stock override.
- Verified that the limitation set in the inventory works, for the respective variants 
- Checked out with cash.

I believe this is good to go.
