### PR TITLE
User account, Credit cards: Do not allow to check "Allow charges" if no credit cards marked as default

### LINKED ISSUE #8897: No error message to warn customer they don't have a default card set when they authorise payments for a subscription
## Description

Customer has a credit/debit card registered with their OFN account but none are set to 'default'.
They check the 'allow charges' box, log out and log back into find the box has become unchecked.
Hub can not set up a subscription for the customer.

## Expected Behavior

Customer ticks the 'allow charges?' box to set up their subscription.
The 'default' card toggle is not set.
A warning pops up that their request to save won't go through until they set their default card

=> don't allow the "allow charges" checkbox to be selected if no default card is set.

## Actual Behaviour

Customer ticks the 'allow charges?' box to set up their subscription.
The 'default' card toggle is not set.
The customer thinks they have completed their subscription set up, logs out.
Customer finds out later their subscription can't be processed.

## Steps to Reproduce

1. Log in as a customer with a subscription
2. Save your credit card and allow charges, but don't set the card to default
3. See the subscription is not going through

## Severity
bug-s4: it's annoying, but you can use it

papercut

### PR DESCRIPTION
**Pull request by jibees**
#### What? Why?

Closes #8897

This PR basically does two things:
 - It's impossible to check the "Allow Charges to Default Card?" checkbox if no default credit card
Capture d’écran 2022-07-21 à 14 57 34

 - When deleting the default card and if another saved card is present, then select the first as the default one

#### What should we test?

- As a user, visit page `/account#/cards`
- If no card, then add one
- If one card and
  - marked as default: you should be able to allow charges from Authorised Shops
  - not marked as default: you should not be able to check the checkboxes
- If more than one card, delete the default one, then, the next should be marked as default

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee [hunk 1]
```diff
@@ -20,3 +20,7 @@ angular.module('Darkswarm').controller "CreditCardsCtrl", ($scope, $http, Credit
     ).finally ->
       window.location.reload()
 
+
+  $scope.hasOneDefaultSavedCards = () ->
+    $scope.savedCreditCards.length > 0 && $scope.savedCreditCards.some((card) -> card.is_default)
```
Comment (mkllnk) [inline app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee:25]: Shouldn't it be disabled when there's no card?

From memory, that case is covered already but I don't know why this conditional is here.

File: app/views/spree/users/_authorised_shops.html.haml [hunk 2]
```diff
@@ -7,10 +7,11 @@
     %th= t(".allow_charges?")
   %tr.customer{ id: "customer{{ customer.id }}", ng: { repeat: "customer in customers" } }
     %td.shop{ ng: { bind: 'shopsByID[customer.enterprise_id].name' } }
-    %td.allow_charges
+    %td.allow_charges{tooltip: "{{ hasOneDefaultSavedCards() ? null : ('spree.users.authorised_shops.no_default_saved_cards_tooltip' | t) }}",}
```
Comment (mkllnk) [inline app/views/spree/users/_authorised_shops.html.haml:10]: Since this is a normal view, you could use the Ruby method:
```suggestion
    %td.allow_charges{tooltip: "{{ hasOneDefaultSavedCards() ? null : '#{t(\".no_default_saved_cards_tooltip\")' }}",}
```

Upside: lazy lookup (shorter key).
Downside: additional quotes.

:shrug:

File: config/locales/en.yml [hunk 3]
```diff
@@ -4232,6 +4232,7 @@ See the %{link} to find out more about %{sitename}'s features and to start using
       authorised_shops:
         shop_name: "Shop Name"
         allow_charges?: "Allow Charges to Default Card?"
+        no_default_saved_cards_tooltip: To allow charges, you should have one credit cards marked as default
```
Comment (mkllnk) [inline config/locales/en.yml:4235]:
```suggestion
        no_default_saved_cards_tooltip: You need to mark one credit card as default to allow charges.
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
This should work. Just some thoughts:

* The model of having a column to mark a card as default has been flawed from the beginning because the data structure doesn't guarantee integrity. We have to do this extra work of selecting and making sure that we are not selecting two cards as default. A better model would be an additional table for the relationship with a unique index. But this is always out of scope.
* If we use the first available card as default when no default is selected, why don't we do that in general when reading from the database? I mean, we can do something like `default_credit_card || stored_cards.first` when charges are allowed. It means that we don't need to change the database unless we store the user's choice.
* The card selection can also be done in the database with `credit_cards.order(:is_default).last`. The database sees `true` as greater than `false`.
* If the user has only one card, why would they select a default? Shouldn't that be the standard? That would be fulfilled by my points above.

File: app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee (hunk 1 above)
Comment (jibees) [reply app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee:25]: Not sure to understand actually.
 - If there's no card, then `hasOneDefaultSavedCards ` returns `false`. 
 - By the way, if there's no card, the "Allow charges" is hidden, via `hide: 'CreditCard.visible || savedCreditCards.length == 0'`

https://github.com/openfoodfoundation/openfoodnetwork/blob/825058472b5bd70a6f86ea872e3c5720f3d2489a/app/views/spree/users/_cards.html.haml#L21

**Comment by jibees** [comment]
@mkllnk I read, and re-read your comment and sorry, but I cannot understand. Would you mind commit something, or write some pseudo-code on what you thought? Thanks a lot, and sorry for that 🙏

File: app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee (hunk 1 above)
Comment (mkllnk) [reply app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee:25]: > If there's no card, then hasOneDefaultSavedCards returns false.

Yes, and would the result be the same if we did this?
```suggestion
    $scope.savedCreditCards.some((card) -> card.is_default)
```

Or even if the result was different, we wouldn't care. My point was that we don't need the length check, do we?

Comment (mkllnk) [reply app/assets/javascripts/darkswarm/controllers/credit_cards_controller.js.coffee]: I added this as commit and the specs are passing.

**Comment by mkllnk** [comment]
> I read, and re-read your comment and sorry, but I cannot understand. Would you mind commit something, or write some pseudo-code on what you thought?

I guess that you mean my comment about selected a default card when reading instead of always storing the default card flag in the database. It would be an alternative pull request, I think. I'll try something.

**Review by mkllnk — APPROVED** [review]
I looked into the logic and while I think that this is not the ideal solution it's best to keep this at papercut size and go with what you've already done.

**Comment by jibees** [comment]
> My point was that we don't need the length check, do we?

You're absolutely right!

> I guess that you mean my comment about selected a default card when reading instead of always storing the default card flag in the database. 

Yes, exactly. 

> It would be an alternative pull request, I think. I'll try something.

Thanks! 🙏 

> I looked into the logic and while I think that this is not the ideal solution it's best to keep this at papercut size and go with what you've already done. 

Perfect!

**Comment by filipefurtad0** [comment]
Hey  @jibees ,

Following your notes on what to test:
- As a user, visit page /account#/cards
  - If no card, then add one -> added one
  - If one card and
        marked as default: you should be able to allow charges from Authorised Shops -> OK
        not marked as default: you should not be able to check the checkboxes -> Only before this PR I was able to have a card added which is not default :+1: 
  - If more than one card, delete the default one, then, the next should be marked as default - OK, see:

Peek 2022-08-11 16-27

Looks great! :tada: 
Merging.
