### PR TITLE
Adjust expectations in flaky spec

### LINKED ISSUE #3473: [Flaky Spec] ./spec/features/admin/shipping_methods_spec.rb:82
## Description

This spec is unreliable:
./spec/features/admin/shipping_methods_spec.rb:82

https://semaphoreci.com/openfoodfoundation/openfoodnetwork-2/branches/master/builds/473

## Context

Our Semaphore builds fail regularly because of these unreliable tests. If you encounter this in your build, please comment on this issue or add 👍

Error:
```

  1) shipping methods as an enterprise user creating a shipping method
     Failure/Error: expect(page).to have_flash_message message
       expected to find flash message #Shipping method "Teleport" has been successfully created!
     # ./spec/features/admin/shipping_methods_spec.rb:108:in `block (3 levels) in <top (required)>'

```

### PR DESCRIPTION
**Pull request by Matt-Yorkley**
#### What? Why?

Closes #3473

Tweaking a flaky spec to try to get it a bit more stable.

#### What should we test?

`/spec/features/admin/shipping_methods_spec.rb` should be green. Line 82 / 108.

### CODE REVIEW

File: spec/features/admin/shipping_methods_spec.rb [hunk 1]
```diff
@@ -103,9 +103,8 @@
 
       click_button I18n.t("actions.create")
 
-      expect(page).to have_no_button I18n.t("actions.create")
-      message = "Shipping method \"Teleport\" has been successfully created!"
-      expect(page).to have_flash_message message
+      expect(page).to have_content "Editing Shipping Method"
```
Comment (Matt-Yorkley) [inline spec/features/admin/shipping_methods_spec.rb]: At this point in the test the page loads from the "new" shipping method page to "edit", showing the new shipping method that has been created. The sticking point seems to be that page load transition, which is a common problem with feature specs. I've changed the expectation here to check for the presence of the title of the next page instead of the absence of an element from the previous page.

File: spec/features/admin/shipping_methods_spec.rb [hunk 2]
```diff
@@ -103,9 +103,8 @@
...
+      expect(flash_message).to eq 'Shipping method "Teleport" has been successfully created!'
```
Comment (Matt-Yorkley) [inline spec/features/admin/shipping_methods_spec.rb]: I also changed this expectation to be in line with the syntax used throughout our other feature specs.

File: spec/features/admin/shipping_methods_spec.rb (hunk 1 above)
Comment (sauloperez) [reply spec/features/admin/shipping_methods_spec.rb]: Sounds good

File: spec/features/admin/shipping_methods_spec.rb (hunk 2 above)
Comment (sauloperez) [reply spec/features/admin/shipping_methods_spec.rb]: Let's not forget to use I18n in assertions as agreed on https://github.com/openfoodfoundation/openfoodnetwork/wiki/Code-Conventions#always-use-i18nt-in-spec-assertions.

**Comment by luisramos0** [comment]
the build is green, so ready to go.
