### PR TITLE
Include vouchers in report: Enterprise Fees With Tax Report By Order 

### LINKED ISSUE #11768: [Vouchers] [Reports] Include vouchers in report: Enterprise Fees With Tax Report By Order
**_ALL dev, code review, product and testing etc should use the Clockify code attached to this Epic https://github.com/openfoodfoundation/openfoodnetwork/issues/11922 - Citi OFN Vouchers Upgrade_**

## Description

When vouchers are applied in orders, then reports must display the discounted values of products, enterprise fees, and their corresponding taxes. 
Until now, many reports still show the numbers without taking vouchers into account.
The numbers have to be updated foll all tax scenarios:
- no taxes apply,
- taxes are included in price,
- taxes are added on top of price.

## Expected Behavior

These are the correct values for orders with tax incl. in price (including the voucher discount):
image

## Actual Behaviour

Incorrect values (10 % voucher not considered)
image

## Steps to Reproduce

1. Set up an enterprise with vouchers and taxes.
2. Place three orders (without tax, with tax incl. in price and with added tax).
3. Run the report.
4. Check the numbers (compare to order details and adjustments in back office).

## Animated Gif/Screenshot

See above.

## Workaround

None.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by chahmedejaz**
:warning: **ALL dev, code review, product and testing etc should use the Clockify code attached to this Epic https://github.com/openfoodfoundation/openfoodnetwork/issues/11922 - Citi OFN Vouchers Upgrade**
#### What? Why?

- Closes #11768

#### What should we test?

- Please validate the **Steps to Reproduce**
- Along with above, please make sure that the report in question is working as expected without vouchers as well

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/models/spree/order.rb [hunk 1]
```diff
@@ -621,6 +621,15 @@ def after_delivery_state?
       state.in?(["payment", "confirmation"])
     end
 
+    # @return [BigDecimal] The rate of the voucher if applied to the order
+    def applied_voucher_rate
+      # As an order can have only one voucher, hence using +take+ because each voucher adjustment will have the same voucher
+      return BigDecimal(0) unless (voucher_adjustment = voucher_adjustments.take)
+
+      voucher = voucher_adjustment.originator
```
Comment (mkllnk) [inline app/models/spree/order.rb:630]: I wonder if this can be better expressed as AR association. `has_many :vouchers, through: :voucher_adjustments` should work. Maybe even `has_one`?

File: app/models/spree/order.rb [hunk 2]
```diff
@@ -621,6 +621,15 @@ def after_delivery_state?
       state.in?(["payment", "confirmation"])
     end
 
+    # @return [BigDecimal] The rate of the voucher if applied to the order
+    def applied_voucher_rate
+      # As an order can have only one voucher, hence using +take+ because each voucher adjustment will have the same voucher
+      return BigDecimal(0) unless (voucher_adjustment = voucher_adjustments.take)
```
Comment (mkllnk) [inline app/models/spree/order.rb:628]: Assignment within a conditional is hard to read. I would split this.

File: lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb [hunk 3]
```diff
@@ -299,6 +305,11 @@ def enterprise_fee_id(query_result_row)
         def keys(query_result_row)
           query_result_row.first
         end
+
+        def apply_voucher_on_amount(order, amount)
+          rate = order.applied_voucher_rate
+          amount + (amount*rate)
```
Comment (mkllnk) [inline lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb]: Mathematically, this can be simplified to `amount * (1 + rate)`.

File: spec/models/spree/order_spec.rb [hunk 4]
```diff
@@ -1544,4 +1544,50 @@ def advance_to_delivery_state(order)
       expect(order.voucher_adjustments).to eq(expected_adjustments)
     end
   end
+
+  describe '#applied_voucher_rate' do
```
Comment (mkllnk) [inline spec/models/spree/order_spec.rb:1548]: For future reference: it's better to include the spec in the same commit as the code change needing the spec.

File: lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb [hunk 5]
```diff
@@ -299,6 +305,12 @@ def enterprise_fee_id(query_result_row)
         def keys(query_result_row)
           query_result_row.first
         end
+
+        def apply_voucher_on_amount(order, amount)
+          rate = order.applied_voucher_rate
+          result = amount + (amount * rate)
+          BigDecimal(result.to_s).round(2, BigDecimal::ROUND_HALF_UP)
```
Comment (mkllnk) [inline lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb:312]: It's a shame that we have to round. Unfortunately, there's no better way with the current data structure of vouchers. But I'm pretty sure that we will have rounding errors one day.

**Review by mkllnk — APPROVED** [review]
Good work!

File: app/models/spree/order.rb (hunk 1 above)
Comment (chahmedejaz) [reply app/models/spree/order.rb:630]: Yes, this is the best case scenario for the current situation at hand.
I believe when vouchers were introduced, we had it in mind that in the near future we might be needing more than 1 vouchers applied to an order.

Hey @RachL - It would be great if we have some kind of confirmation on whether we are planning to introduce multiple vouchers to apply to an order. 
If it's not planned in the near future, then I believe we should create a good-first-issue issue and incorporate this comment. This would help us clean up some logic in code. Thanks.

Comment (chahmedejaz) [reply app/models/spree/order.rb:630]: Yes it's the best scenario for the situation at hand.
I'd go for the has_many because this would help us incorporate multiple vouchers if in future we have this feature without making any schema level changes.

We can have an issue to incorporate this comment and use this relationship wherever required. What do you say?

File: lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb (hunk 5 above)
Comment (chahmedejaz) [reply lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb:312]: Yeah I was also thinking that we might face the data round off issues. I was wondering how we can avoid this thing. :sweat_smile:

Comment (mkllnk) [reply lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb:312]: The only solution I can think of is a complete re-modelling of the voucher adjustments. Instead of adjusting the whole order, we could adjust each line item. The total of all voucher adjustments could still be different to the rate applied to the whole order but that's easier to explain. It could also be easier to use those adjustments in reports like this one. But it's a big chunk of work that I wouldn't start right now. Gaetan and Lynne also expressed their concerns over starting this work while there's not big reason for it.

File: spec/models/spree/order_spec.rb [hunk 6]
```diff
@@ -1544,4 +1544,50 @@ def advance_to_delivery_state(order)
...
+        voucher.create_adjustment(voucher.code, order)
+        allow(order).to receive(:pre_discount_total).and_return(BigDecimal(20))
+      end
+
+      context "when order has voucher_flat_rate adjustment" do
+        let(:voucher) { create(:voucher_flat_rate, enterprise: order.distributor, amount: 10) }
+
+        it 'returns the BigDecimal 0 value' do
+          actual = order.applied_voucher_rate
+          expect(actual.class).to eq(BigDecimal)
```
Comment (rioug) [inline spec/models/spree/order_spec.rb:1573]: I would use `be_kind_of(BigDecimal)` matcher, but this works as well.

File: app/models/spree/order.rb [hunk 7]
```diff
@@ -623,7 +623,8 @@ def after_delivery_state?
 
     # @return [BigDecimal] The rate of the voucher if applied to the order
     def applied_voucher_rate
-      # As an order can have only one voucher, hence using +take+ because each voucher adjustment will have the same voucher
+      # As an order can have only one voucher,
+      # hence using +take+ as each voucher adjustment will have the same voucher
```
Comment (rioug) [inline app/models/spree/order.rb:627]: Note for next time, it's better to fix Rubocop issue in a separate commit.

File: app/models/spree/order.rb (hunk 1 above)
Comment (rioug) [reply app/models/spree/order.rb:630]: I think it's fine to do it in this issue. I don't think we had a need for it so far so that's probably why it hasn't been done, and yes we should use `has_many`.

File: spec/models/spree/order_spec.rb (hunk 6 above)
Comment (chahmedejaz) [reply spec/models/spree/order_spec.rb:1573]: TIL: `be_kind_of` matcher. Thanks :)

Comment (mkllnk) [reply spec/models/spree/order_spec.rb:1573]: There's also `be_a` doing the same.

File: lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb [hunk 8]
```diff
@@ -221,23 +223,27 @@ def tax_rate_amount(query_result_row)
...
         def tax(query_result_row, all: false, included: nil)
-          order_id = order(query_result_row).id
+          order = order(query_result_row)
+          order_id = order.id
           adjustment_ids = enterprise_fee_adjustment_ids(query_result_row)
           query = Spree::Adjustment.tax
           query = query.where(included: true) unless included.nil?
           query = query.where(originator_id: tax_rate_id(query_result_row)) unless all == true
-          query.where(order_id:)
+          tax_amount = query.where(order_id:)
```
Comment (dacook) [inline lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb:242]: We could actually remove the `order_id` variable and refer directly to `order`. AR automatically uses the ID anyway.

**Review by dacook — CHANGES_REQUESTED** [review]
It looks like consensus is to change to an AR association like `has_many :vouchers, through: :voucher_adjustments`

**Comment by chahmedejaz** [comment]
> It looks like consensus is to change to an AR association like `has_many :vouchers, through: :voucher_adjustments`

Just to re-iterate, this should be handled in a separate issue as we may need to replace code in many other places which might be out of the issue's scope. Thanks. :)
ref: https://github.com/openfoodfoundation/openfoodnetwork/pull/11985#discussion_r1440102614

File: lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb (hunk 8 above)
Comment (chahmedejaz) [reply lib/reporting/reports/enterprise_fee_summary/enterprise_fees_with_tax_report_by_order.rb]: That's great! :heart_eyes: 

It's updated here: https://github.com/openfoodfoundation/openfoodnetwork/pull/11985/commits/1d44a3ffe04de6faae91a4aeb546122dd57320b4

**Review by mkllnk — APPROVED** [review]

**Review by dacook — APPROVED** [review]
Ok, I didn't realise it was a big change.

**Comment by drummer83** [comment]
Hi @chahmedejaz,
I have tested this on staging AU today. It's looking good, but there is one thing I don't understand.
For orders with tax incl. in price there are somehow additional 0.08 $ displayed in the report. However, it doesn't show up in the summary row.
image

To calculate the numbers (maybe I'm wrong):
- the enterprise fee is 10 $ incl. tax
- the voucher is a 10 % voucher
- tax: 10 $ = 9.09 $ fee + 0.91 $ tax
- voucher: 10 % = 0.91 $ fee discount + 0.09 $ tax discount
- total: 9 $ = 8.18 $ fee + 0.82 $ tax

Can you find out where those additional 8 ct. in the report are coming from? I don't think it's correct. But maybe you can convince me that it is. :wink: 

I will move this back to In Dev so you can check this is more detail.

Here are the order details:
image

Report setting for reference:
image


Thanks!

**Comment by chahmedejaz** [comment]
> It's looking good, but there is one thing I don't understand.
For orders with tax incl. in price there are somehow additional 0.08 $ displayed in the report. However, it doesn't show up in the summary row.

Hey @drummer83 - Sorry for getting back on this late. Yeah, you are right. I've fixed this issue. It should be good now.
Thanks for raising this one ❤️ 

Hey @dacook, @mkllnk - Can you please review this small fix: https://github.com/openfoodfoundation/openfoodnetwork/pull/11985/commits/ff488252414ca4ba41c9808701cdce7d75de6226 Thanks ❤️

**Review by mkllnk — APPROVED** [review]

**Review by dacook — APPROVED** [review]
Great work on picking that up Konrad, and for fixing it Ahmed!

**Comment by drummer83** [comment]
Thanks, @chahmedejaz!

Yes, it's looking good now. Same orders, same report, correct numbers. :+1: 

image

Merging! :tada: 
:rocket:
