### PR TITLE
Sort zones by name again, in the admin panel

### LINKED ISSUE #10499: [Flaky] rspec ./spec/system/admin/configuration/zones_spec.rb:14
### What we should change and why (this is tech debt)

`rspec ./spec/system/admin/configuration/zones_spec.rb:14 # Zones list existing zones`

```

Failures:

  1) Zones list existing zones
     Failure/Error: within_row(1) { expect(page).to have_content("eastern") }
       expected to find text "eastern" in "western cool san fran false"
     
     [Screenshot Image]: /home/runner/work/openfoodnetwork/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_zones_list_existing_zones_357.png
```

image

### Context

https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/4304445434/jobs/7505492878

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #10499 

I just came across this flaky spec for sorting zones and it turned out that the production code wasn't sorting by default.

#### What should we test?

- Visit Admin -> Configuration -> Zones
- By default, the zones should be sorted alphabetically.
- You can sort them by description as well.

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by mkllnk** [comment]
Blocked by another flaky spec. :disappointed:

**Comment by abdellani** [comment]
> Blocked by another flaky spec. disappointed

is it about `rspec ./spec/services/order_cycle_form_spec.rb:425` ?

**Comment by mkllnk** [comment]
> is it about rspec ./spec/services/order_cycle_form_spec.rb:425 ?

Yes.

File: spec/system/admin/configuration/zones_spec.rb [hunk 1]
```diff
@@ -6,12 +6,8 @@
   include AuthenticationHelper
   include WebHelper
 
-  before do
-    login_as_admin
-  end
-
   it "list existing zones" do
-    visit spree.edit_admin_general_settings_path
+    login_as_admin_and_visit spree.edit_admin_general_settings_path
```
Comment (dacook) [inline spec/system/admin/configuration/zones_spec.rb:10]: Nice tip!
Hmm... but are you sure? It looks like they both do the same thing:

https://github.com/openfoodfoundation/openfoodnetwork/blob/master/spec/support/request/authentication_helper.rb#L13

I'm guessing `login_as` is a Warden helper which may or may not make a request.

**Review by dacook — APPROVED** [review]
So the flakiness was actually revealing a bug! Great to fix 👍

File: spec/system/admin/configuration/zones_spec.rb (hunk 1 above)
Comment (mkllnk) [reply spec/system/admin/configuration/zones_spec.rb:10]: You are right. I've been thinking of some really old code and that's not relevant any more:

* https://github.com/openfoodfoundation/openfoodnetwork/commit/8b04e45ea5d4c902ada59012f43c8abdd399e308

We can probably DRY all these helpers now.
