### PR TITLE
Clears Stripe settings after example run

### LINKED ISSUE #9938: Spec order failure
### What we should change and why (this is tech debt)

Documenting here as this is easily reproducible (at least in my) local system:

Running:

`bundle exec rspec --default-path spec "spec/system/admin/bulk_order_cancellation_spec.rb" "spec/system/admin/configuration/taxonomies_spec.rb" "spec/system/admin/enterprises/images_spec.rb" "spec/system/admin/payments_stripe_spec.rb" "spec/system/admin/schedules_spec.rb" "spec/system/consumer/account/developer_settings_spec.rb" "spec/system/consumer/multilingual_spec.rb" "spec/system/consumer/shopping/products_spec.rb" "spec/system/flatpickr_spec.rb" "spec/system/admin/order_cycles/complex_updating_specific_time_spec.rb"`

Fails with:

```
Failures:

  1) Developer Settings as a logged in user when show_api_key_view is true shows the developer settings tab
     Failure/Error: visit "/account"
     
     Ferrum::JavaScriptError:
       ReferenceError: Stripe is not defined
           at http://127.0.0.1:41851/account:962:30
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_developer_settings_as_a_logged_in_user_when_show_api_key_view_is_true_shows_the_developer_settings_tab_257.png

     
     # ./spec/system/consumer/account/developer_settings_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  2) Developer Settings as a logged in user when show_api_key_view is true when the user has an api key shows the api key
     Failure/Error: visit "/account"
     
     Ferrum::JavaScriptError:
       ReferenceError: Stripe is not defined
           at http://127.0.0.1:41851/account:962:30
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_developer_settings_as_a_logged_in_user_when_show_api_key_view_is_true_when_the_user_has_an_api_key_shows_the_api_key_629.png

     
     # ./spec/system/consumer/account/developer_settings_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  3) Developer Settings as a logged in user when show_api_key_view is true when the user has an api key lets the user regenerate the api key
     Failure/Error: visit "/account"
     
     Ferrum::JavaScriptError:
       ReferenceError: Stripe is not defined
           at http://127.0.0.1:41851/account:962:30
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_developer_settings_as_a_logged_in_user_when_show_api_key_view_is_true_when_the_user_has_an_api_key_lets_the_user_regenerate_the_api_key_568.png

     
     # ./spec/system/consumer/account/developer_settings_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  4) Developer Settings as a logged in user when show_api_key_view is false does not show the developer settings tab
     Failure/Error: visit "/account"
     
     Ferrum::JavaScriptError:
       ReferenceError: Stripe is not defined
           at http://127.0.0.1:41851/account:945:30
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_developer_settings_as_a_logged_in_user_when_show_api_key_view_is_false_does_not_show_the_developer_settings_tab_383.png

     
     # ./spec/system/consumer/account/developer_settings_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  5) Test Flatpickr orders opens the datepicker and closes it using the 'CLOSE' button
     Failure/Error: find(field).click
     
     Capybara::ElementNotFound:
       Unable to find visible css "#q_completed_at_gteq"
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_test_flatpickr_orders_opens_the_datepicker_and_closes_it_using_the__close__button_39.png

     
     # ./spec/system/flatpickr_spec.rb:42:in `open_datepicker'
     # ./spec/system/flatpickr_spec.rb:12:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  6) Test Flatpickr orders opens the datepicker and sets date to today
     Failure/Error: find(field).click
     
     Capybara::ElementNotFound:
       Unable to find visible css "#q_completed_at_gteq"
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_test_flatpickr_orders_opens_the_datepicker_and_sets_date_to_today_308.png

     
     # ./spec/system/flatpickr_spec.rb:42:in `open_datepicker'
     # ./spec/system/flatpickr_spec.rb:24:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

  7) Test Flatpickr orders opens the datepicker and closes it by clicking outside
     Failure/Error: find(field).click
     
     Capybara::ElementNotFound:
       Unable to find visible css "#q_completed_at_gteq"
     
     [Screenshot Image]: /home/ffurtado/openfoodnetwork/tmp/capybara/screenshots/failures_r_spec_example_groups_test_flatpickr_orders_opens_the_datepicker_and_closes_it_by_clicking_outside_232.png

     
     # ./spec/system/flatpickr_spec.rb:42:in `open_datepicker'
     # ./spec/system/flatpickr_spec.rb:31:in `block (3 levels) in <main>'
     # ./spec/system/support/cuprite_setup.rb:41:in `block (2 levels) in <main>'

Finished in 2 minutes 30.3 seconds (files took 8.42 seconds to load)
38 examples, 7 failures, 1 pending

Failed examples:

rspec ./spec/system/consumer/account/developer_settings_spec.rb:19 # Developer Settings as a logged in user when show_api_key_view is true shows the developer settings tab
rspec ./spec/system/consumer/account/developer_settings_spec.rb:29 # Developer Settings as a logged in user when show_api_key_view is true when the user has an api key shows the api key
rspec ./spec/system/consumer/account/developer_settings_spec.rb:33 # Developer Settings as a logged in user when show_api_key_view is true when the user has an api key lets the user regenerate the api key
rspec ./spec/system/consumer/account/developer_settings_spec.rb:44 # Developer Settings as a logged in user when show_api_key_view is false does not show the developer settings tab
rspec ./spec/system/flatpickr_spec.rb:10 # Test Flatpickr orders opens the datepicker and closes it using the 'CLOSE' button
rspec ./spec/system/flatpickr_spec.rb:22 # Test Flatpickr orders opens the datepicker and sets date to today
rspec ./spec/system/flatpickr_spec.rb:29 # Test Flatpickr orders opens the datepicker and closes it by clicking outside
```

### Context

This came up here:
https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3393780700/jobs/5641810234

### Impact and timeline

Build speed up; introducing Knapsack Pro

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

Closes #9938

Stripe settings were leaking to "neighboring" specs, causing some these to fail.

#### What should we test?

Running:
`bundle exec rspec ./spec/system/admin/payments_stripe_spec.rb[1:2:3:1] ./spec/system/consumer/account/developer_settings_spec.rb[1:1:1:1,1:1:1:2:1,1:1:1:2:2,1:1:2:1]
`
should be green, locally.

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: spec/system/admin/payments_stripe_spec.rb [hunk 1]
```diff
@@ -20,7 +20,13 @@
 
   before { setup_stripe }
 
-  context "making a new Stripe payment", js: true do
+  after do
+    allow(Spree::Config).to receive(:stripe_connect_enabled).and_return(false)
```
Comment (mkllnk) [inline spec/system/admin/payments_stripe_spec.rb:24]: I don't think that you need this line. It's only effective before test code, not after. Any `allow` and `expect` mocks should be forgotten after each test case.

Comment (mkllnk) [reply spec/system/admin/payments_stripe_spec.rb:24]: I noticed that we have the `setup_stripe` helper above. We should have a `teardown_stripe` method to call afterwards with this code.

Comment (mkllnk) [reply spec/system/admin/payments_stripe_spec.rb:24]: But I'm wondering if we can make this whole `after` callback obsolete by change `setup_stripe` to use `allow` in which case the cleanup is handled automatically. It was introduced in 04ff4fa47cde6799303d007c7aee23c7c1e40bcb but unfortunately the commit message only describes the "what" and not the "why". :disappointed: I think it's worth trying that.

**Review by mkllnk — CHANGES_REQUESTED** [review]

File: spec/system/admin/payments_stripe_spec.rb (hunk 1 above)
Comment (mkllnk) [reply spec/system/admin/payments_stripe_spec.rb:24]: No, I meant:

```rb
allow(Stripe).to receive(:api_key).and_return("sk_test_12345")
```

But there may be reason why this wasn't used in the past. Maybe Stripe internals access the values differently. :shrug: :question:

Comment (filipefurtad0) [reply spec/system/admin/payments_stripe_spec.rb]: > `allow(Stripe).to receive(:api_key).and_return("sk_test_12345"`)

Yeah, I've tried this way as well, but it seemed not to work either... I'm not sure why.

My best take on this is to create a helper method `clear_stripe`, and to call it on each spec in which `stripe_setup` is called. Also found other specs which were leaking the stripe configuration.

File: spec/system/admin/payments_stripe_spec.rb [hunk 2]
```diff
@@ -19,8 +19,9 @@
   end
 
   before { setup_stripe }
+  after { clear_stripe }
```
Comment (mkllnk) [inline spec/system/admin/payments_stripe_spec.rb:22]: I just had another idea which would prevent us from forgetting to clear Stripe:
```suggestion
  around do |example|
    with_stripe_setup { example.run }
  end
```

And the helper something like:
```rb
def with_stripe_setup(api_key = "sk_test_12345", publishable_key = "pk_test_12345")
  original_keys = [Stripe.api_key, Stripe.publishable_key]

  Stripe.api_key = api_key
  Stripe.publishable_key = publishable_key
  allow(Spree::Config).to receive(:stripe_connect_enabled).and_return(true)

  yield

  Stripe.api_key, Stripe.publishable_key = original_keys
end
```

This method makes sure that we always restore the original state, whatever it is. We could even nest calls.

**Review by mkllnk — APPROVED** [review]
Great! That's much better. I thought of one improvement below.

File: spec/system/admin/payments_stripe_spec.rb (hunk 2 above)
Comment (filipefurtad0) [reply spec/system/admin/payments_stripe_spec.rb:22]: Thanks for that suggestion @mkllnk  I totally agree it would be much better to have this within `around` block - I had tried it before with no success, but we're getting closer with your code now. It is throwing the error:
`       The use of doubles or partial doubles from rspec-mocks outside of the per-test lifecycle is not supported.`

So I did some digging and it seems we need to wrap
`allow(Spree::Config).to receive(:stripe_connect_enabled).and_return(true)`

around `RSpec::Mocks.with_temporary_scope`; for reference, taken from [this discussion](https://github.com/rspec/rspec-core/issues/1598#issuecomment-351794624).

After this change your suggestion works like a charm, and we need not remember to clear stripe settings. I'll commit and make the changes on the necessary files.

Thanks!

Comment (filipefurtad0) [reply spec/system/admin/payments_stripe_spec.rb]: Ok, so using `RSpec::Mocks.with_temporary_scope` seems not to really enable Stripe. It seems this is not always necessary and indeed, using `allow(Spree::Config).to receive(...` already prevents leaking. So perhaps it is a better idea to include only the api and private keys within the `around` block, since these are the settings leaking and causing issues.

Enabling/disabling Stripe is now included as helpers and can be called independently of the `around` block.

File: spec/system/admin/payments_stripe_spec.rb [hunk 3]
```diff
@@ -18,9 +18,11 @@
     create(:stripe_account, enterprise: order.distributor, stripe_user_id: "abc123")
   end
 
-  before { setup_stripe }
+  around do |example|
+    with_stripe_setup { example.run }
+  end
 
-  context "making a new Stripe payment", js: true do
+  context "making a new Stripe payment" do
```
Comment (dacook) [inline spec/system/admin/payments_stripe_spec.rb:25]: I'm not sure, but it looks like we have some Stripe-related Javascript about selecting a card, so it might be worth keeping JS mode to ensure that is covered.

Comment (dacook) [reply spec/system/admin/payments_stripe_spec.rb:25]: @jibees Do you have any thoughts to add to this?

**Review by dacook — COMMENTED** [review]
The latest update with the `around` block looks good! But I will get a second opinion about some of it.

File: spec/system/admin/payments_stripe_spec.rb (hunk 3 above)
Comment (jibees) [reply spec/system/admin/payments_stripe_spec.rb:25]: I re-read the documentation of capybara (https://github.com/teamcapybara/capybara): 

> Use js: true to switch to the Capybara.javascript_driver (:selenium by default), or provide a :driver option to switch to one specific driver.

But we use https://github.com/rubycdp/cuprite as our javascript driver: 

https://github.com/openfoodfoundation/openfoodnetwork/blob/911d816233bb5426610e497562ec6ab3c969e82a/spec/system/support/cuprite_setup.rb#L25


So my opinion: we should remove this `js: true` on all system spec since it's useless.

File: spec/support/request/stripe_helper.rb [hunk 4]
```diff
@@ -28,9 +28,22 @@ def fill_in_card_details_in_backoffice
...
-  def setup_stripe
-    Stripe.api_key = "sk_test_12345"
-    Stripe.publishable_key = "pk_test_12345"
+  def stripe_enable
     allow(Spree::Config).to receive(:stripe_connect_enabled).and_return(true)
   end
+
+  def stripe_disable
+    allow(Spree::Config).to receive(:stripe_connect_enabled).and_return(false)
+  end
```
[the remark this answers is not in the document]
Comment (filipefurtad0) [reply spec/support/request/stripe_helper.rb:37]: Right - we don't need it, fully agree.

[the remark this answers is not in the document]
Comment (filipefurtad0) [reply spec/support/request/stripe_helper.rb]: I've committed a fixup to the first commit to remove that method - thanks David!

File: spec/system/admin/payments_stripe_spec.rb (hunk 3 above)
Comment (filipefurtad0) [reply spec/system/admin/payments_stripe_spec.rb:25]: Yes, that's my understanding too - we should remove it from all specs, it's a tech debt for system specs.

Comment (dacook) [reply spec/system/admin/payments_stripe_spec.rb:25]: Oh, thanks for pointing this out! So the default is always use a browser test (Chrome via Cuprite) for _all_ system tests. Hence it's unnecessary to specify JS mode.

**Review by jibees — APPROVED** [review]
👍

**Comment by jibees** [comment]
I've run specs locally, build is green: I merge this one!
