### PR TITLE
Fix shared login sessions between staging and production

### LINKED ISSUE #13974: Fix shared login sessions between staging and production
## Description

Currently, **staging and production share the same login session scope** due to how the session cookie domain is configured.

In `config/initializers/session_store.rb`, we are stripping subdomains (including `staging.`, `stg.` and `app.`) from `SITE_URL`:

``` ruby
domain = if Rails.env.staging? || Rails.env.production?
           ".#{ENV['SITE_URL'].gsub(/^(www\.)|^(app\.)|^(staging\.)|^(stg\.)/, '')}"
         else
           :all
         end

Openfoodnetwork::Application.config.session_store(
  :active_record_store,
  key: "_ofn_session_id",
  domain: domain
)
```

Because `staging.` is stripped, both environments resolve to the same root domain (e.g. `.openfoodnetwork.org`), which causes:
- Logging into **staging** to invalidate the **production** session
- Logging into **production** to invalidate the **staging** session

This appears to be an unintended side effect of a previous change meant to fix staging session behavior.

This issue aims to **isolate sessions between environments** while keeping login functionality intact.

------------------------------------------------------------------------

## Expected Behavior

-   Logging into staging should **not** log the user out of production.
-   Logging into production should **not** log the user out of staging.
-   Each environment should maintain its own session cookie.

------------------------------------------------------------------------

## Actual Behaviour

-   Staging and production share the same cookie scope.
-   Logging into one environment replaces the session in the other.

------------------------------------------------------------------------

## Steps to Reproduce

You can simulate this locally using two subdomains:

### 1. Update your `/etc/hosts` file:

    127.0.0.1 localhost
    127.0.0.1 staging.localhost

### 3. Open two browser tabs:

-   http://localhost:3000
-   http://staging.localhost:3000

### 5. Log into the other tab.

You will observe that logging into one invalidates the other session because they share the same cookie domain.

You can confirm this by inspecting:

**DevTools → Application → Cookies → `_ofn_session_id`**

------------------------------------------------------------------------

## Workaround

Use separate browsers or incognito mode for staging vs production.

------------------------------------------------------------------------

## Severity

**bug-s3**

A feature (session isolation) is broken but there is a workaround.

------------------------------------------------------------------------

## Your Environment

-   Version used: current master
-   Browser name and version: Chrome (latest)
-   Operating System and version (desktop): macOS / Linux

------------------------------------------------------------------------

## Possible Fix

We should **stop stripping `staging.`, `stg.`, `app.`  and `www.` from `SITE_URL`.**

### Required Code Change

Update this line:

``` ruby
".#{ENV['SITE_URL'].gsub(/^(www\.)|^(app\.)|^(staging\.)|^(stg\.)/, '')}"
```

To:

``` ruby
ENV['SITE_URL']
```

### Why This Works

-   Ensures staging and production generate **different cookie domains**
-   We don't use `www.` and `app.` subdomains as well
-   We just want the session cookie to be used only by the given domain for the environment and not for its subdomains. Hence we should not prepend `.` with the domain
-   Can be fully verified locally

### PR DESCRIPTION
**Pull request by AwsAqh**
## What? Why?

- Closes #13974

## What should we test?

As in issue:

> -   Logging into staging should **not** log the user out of production.
> -   Logging into production should **not** log the user out of staging.
> -   Each environment should maintain its own session cookie.

## Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: config/initializers/session_store.rb [hunk 1]
```diff
@@ -5,7 +5,7 @@
 # (create the session table with "rails generate session_migration")
 
 domain = if Rails.env.staging? || Rails.env.production?
-           ".#{ENV['SITE_URL'].gsub(/^(www\.)|^(app\.)|^(staging\.)|^(stg\.)/, '')}"
+           ".#{ENV['SITE_URL'].gsub(/^(www\.)/, '')}"
```
Comment (rioug) [inline config/initializers/session_store.rb]: we don't need  to strip `www` any more, could you fix this ?

**Review by rioug — APPROVED** [review]
Looks good, thanks for your help 🙏 !

**Comment by AwsAqh** [comment]
> I note that this doesn't remove the leading `.` at the start of the domain, which was suggested in the issue description. Can you please review the issue and try testing locally with the provided instructions?
Leading . removed.

File: config/initializers/session_store.rb [hunk 2]
```diff
@@ -5,7 +5,7 @@
 # (create the session table with "rails generate session_migration")
 
 domain = if Rails.env.staging? || Rails.env.production?
-           ".#{ENV['SITE_URL'].gsub(/^(www\.)|^(app\.)|^(staging\.)|^(stg\.)/, '')}"
+           "#{ENV['SITE_URL']}"
```
Comment (dacook) [inline config/initializers/session_store.rb]: Thanks, now it doesn't need string interpolation either, so I will simplify:
```suggestion
           ENV['SITE_URL']
```

**Comment by ValVerCH** [comment]
Testing the switching of accounts on UK_staging and UK_production

On UK_staging, I am logged in as admin
image

I am switching to the UK_production, and it asks me to log in 
image

Now I go back to UK_staging, and it has logged me out , so I need to log in again indeed
image

So now I will deploy to see if it keeps me on both or not

**Comment by ValVerCH** [comment]
Hello David  @dacook 
I have an issue
After deploying the branch with PR_Staged_UK, I cannot log-in anymore in the UK_staging environment
clicking on sign in (in the menu bar), gives me the same panel to log in, but nothing happens after clicking on the button sign-in
image

Can you help me ? I need the uk_staging access to do other tests too.

**Comment by sigmundpetersen** [comment]
Hi @ValVerCH you can try deploying master and see if your login works again

**Comment by RachL** [comment]
argh i'm just seeing this comment now. FYI I'm staging another PR: it hsould stage master as well, so we can see if login still works!

**Comment by RachL** [comment]
I can login/logout in UK, but I haven't tested login out before staging as I didn't see this comment. I suggest we stage this PR on AU and see if this PR works?

**Comment by ValVerCH** [comment]
@sigmundpetersen @RachL thanks a lot for your follow-up
Well, I have retested and strange thing, I cannot login anymore, neither on staging nor on production.

**Comment by ValVerCH** [comment]
I have re-deployed it this morning and now everything is fine

We can have 2 logins in parallel, in staging and in production, and stay on both, either in the same navigator or in 2 different navigators. Thanks to all who helped me get through this PR 

image

**Comment by chahmedejaz** [comment]
I'm looking into the build failure of this PR before merging it for the release.

**Comment by chahmedejaz** [comment]
Apparently, the branch was quite outdated after recent merges in the master. So, rebased, pushed again, and the build is green now. 

Merging 🚀

**Review by chahmedejaz — APPROVED** [review]
