### PR TITLE
Void payments requiring auth upon marking order paid

### LINKED ISSUE #8059: Payments awaiting authorization from order payment state = 'Paid' are displayed on the customers "Transactions" tab
## Description

Related to https://github.com/openfoodfoundation/wishlist/issues/5, #7708 and #7653.

If a cash payment is added on top of a stripe SCA pending payment, the order `payment state` can transition into "paid", regardless of the previously added Stripe payment; this payment still appears on the `/account/transactions` page of the customer and the customer can still provide payment authorization. If so, then it displays an error to the user changing the payment into an `uncaptured` state.

As [previously discussed](https://github.com/openfoodfoundation/openfoodnetwork/issues/7692#issuecomment-880689258), Stripe captures "uncaptured" payments automatically, after a few days.

## Expected Behavior

- If the payment state of the Order in `Paid` the these payments should not show up on the `/account/transactions`, thus  preventing the customer from clicking the "Authorize Payment" button.
- Links received per email `/payments/<payment_nr>/authorize` on orders which are on state `Paid` should not take effect when used by the customer.

To put this in a different way: Stripe SCA payment authorization should only be possible for orders which either:
- have no payment added (order is not complete)
- order is in state `complete` but payment state is `balance due`

## Actual Behaviour

Customers can still authorize payments for complete/paid orders in two ways:
- on the `/account/transactions`
- by using the links received per email `/payments/<payment_nr>/authorize`

## Steps to Reproduce

As an Admin:
1. Create a BO order; add a stripe-SCA payment
2. Add a cash payment fully covering the order total; capture the cash payment (this should not trigger an error) -> order should be in state = `Paid` (payment state of the order)

As a customer:
3. Visit `/account/transactions` and authorize the payment on the respective order, or
4. Use the received link to authorize the payment
5. See the error on the order confirmation page

6. Log in to stripe and notice the SCA payment is in state `uncaptured`

## Animated Gif/Screenshot

Peek 2021-08-16 15-05

## Workaround

Login to Stripe and cancel these payments.

## Severity

bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.0.1
* Browser name and version: Firefox 90
* Operating System and version (desktop or mobile): Ubuntu 20.04

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #8059 

#### Release notes

Fixed a bug where paying for an order with another payment method would keep pending SCA payments open and available to authorize (thus paying twice).

Changelog Category: User facing changes

### CODE REVIEW

**Comment by RachL** [comment]
hey @andrewpbrett how are you doing on this one? I'm asking as it is marked as s2: should we consider lowering the severity or assign to someone else as you have a lot on your plate?

**Comment by andrewpbrett** [comment]
Thanks @RachL :) My plate is starting to clear a bit, I should have time in the next couple days to pick this up again and get it to code review.

File: spec/models/spree/order_spec.rb [hunk 1]
```diff
@@ -195,6 +195,21 @@
...
       order.finalize!
     end
+
+    context "extra payments exist that require authorization" do
+      let!(:cash_payment) { build(:payment, state: "completed", amount: order.new_outstanding_balance) }
+      let!(:stripe_payment) { build(:payment, state: "requires_authorization") }
+      before do
+        order.payments << cash_payment
+        order.payments << stripe_payment
+        allow_any_instance_of(Spree::Payment).to receive(:void_transaction!) {}
```
Comment (andrewpbrett) [inline spec/models/spree/order_spec.rb:205]: Using `any_instance_of` is not ideal; however, putting the allow/expect on the `stripe_payment` itself wasn't working, even though I verified that it is in fact receiving `void_transaction!` - I'm not sure why it wasn't passing.

Comment (mkllnk) [reply spec/models/spree/order_spec.rb:205]: First you allow it to be called and then you expect it to be called? I don't understand. Would it be better to expect it to be called twice or however often it's called?

The problem with any instance is that we don't know if it's voiding the cash payment or the stripe payment. You could create two test cases, one with cash and one with stripe. The first one is not voided the second one should be voided.

**Review by mkllnk — APPROVED** [review]
Good work. I'm approving because it seems quite urgent but I'm not sure about the spec. It doesn't seem to be very reliable. It would probably still pass if you forgot to scope to `requires_authorization`.

File: spec/models/spree/order_spec.rb (hunk 1 above)
Comment (andrewpbrett) [reply spec/models/spree/order_spec.rb:205]: > First you allow it to be called and then you expect it to be called?

My intention with the `allow` was to pass the empty block so that calling `void_transaction!` doesn't actually try to make any call to Stripe.

**Comment by andrewpbrett** [comment]
Thanks for reviewing @mkllnk. I agree it's not a great spec. 

> It would probably still pass if you forgot to scope to requires_authorization.

The way I get it to fail is by not having a `stripe_payment` - if you remove/comment out lines 201 and 204, it fails. So that's telling me that if there's no extra payment, we never call void_transaction, which is what I'm intending to test. 

But there's probably a better way to test it. I remember reading at some point that `allow` and `expect` in Rspec don't work for saved ActiveRecord objects, but I'm having trouble finding the source for that. That's the only reason I resorted to `allow_any_instance_of` in the first place. `void_transaction` is clearly being called, and called specifically on the stripe_payment, but the `expect` doesn't see it happening... 🤷 

> I'm approving because it seems quite urgent

It is technically an S2 since it deals with payments, but I'd say it's pretty rare that it's actually happening in production (this is a good example of a bug where just the S1-5 scale doesn't reflect its urgency and why we were talking about adding some other metric/label). 

If we think we can do better on the spec, let's not rush it through. I'd be happy to pair on it with you for a bit if your schedule allows.

File: app/models/spree/order.rb [hunk 2]
```diff
@@ -597,6 +598,12 @@ def address_from_distributor
 
     private
 
+    def cancel_payments_requiring_auth
+      return unless payment_state == "paid"
+
+      payments.requires_authorization.each(&:void_transaction!)
```
[the remark this answers is not in the document]
Comment (mkllnk) [reply app/models/spree/order.rb:604]: So option 2 here is:
```suggestion
      payments.to_a.select(&:requires_authorization?).each(&:void_transaction!)
```

File: spec/models/spree/order_spec.rb (hunk 1 above)
Comment (mkllnk) [inline spec/models/spree/order_spec.rb:205]: This line can be removed. The spec passes anyway. It's actually better removed because then the spec fails if both payments receive `void_transaction`.
```suggestion
```

File: spec/models/spree/order_spec.rb [hunk 3]
```diff
@@ -195,6 +195,21 @@
...
+      end
+
+      it "cancels payments requiring authorization" do
+        expect_any_instance_of(Spree::Payment).to receive(:void_transaction!)
```
Comment (mkllnk) [inline spec/models/spree/order_spec.rb:209]: The option 2 suggestion above still passes this spec. But we can now be more specific:
```suggestion
        expect(stripe_payment).to receive(:void_transaction!)
        expect(cash_payment).to_not receive(:void_transaction!)
```

Comment (mkllnk) [inline spec/models/spree/order_spec.rb:209]: Or, if you don't want to change the model code and keep the scope (I'm not sure what's better myself):
```suggestion
        expect_any_instance_of(Spree::Payment).to receive(:void_transaction!) do |payment|
          raise unless payment == stripe_payment
        end
```

**Review by mkllnk — CHANGES_REQUESTED** [review]
Okay! Sorry for the delay. I wanted to come up with good examples. I got two solutions and can't decide between them! Please help and choose one. :smile:

**Comment by andrewpbrett** [comment]
Thanks @mkllnk! The second one, using the payment object in memory, made more sense to me. 

> I found this by putting a lot of puts payment.object_id in the code. 😉

Thanks for explaining this! I was getting frustrated and not understanding how the expected messages weren't being received, but this makes sense now.

**Review by mkllnk — APPROVED** [review]

**Review by Matt-Yorkley — APPROVED** [review]

**Comment by filipefurtad0** [comment]
Hey @andrewpbrett ,

I've reproduced the scenario **before staging the PR**:
- customers could grant authorization to additional payments, on orders which were in payment state = paid

image


However, **after staging this PR** I could not spot any change in behavior:

Peek 2021-09-27 15-38

After the order changes to `paid`, the link is still found on `/account#/transactions` (customer) -> I would have expecte that the link is not to be found or working anymore, thus preventing the granting of authorization and the creation of a new payment on Stripe.

Thoughts?

**Comment by jaycmb** [comment]
> I would have expected that the link is not to be found or working anymore, thus preventing the granting of authorization and the creation of a new payment on Stripe.

Agree

**Comment by andrewpbrett** [comment]
Thanks for testing @filipefurtad0: 

> I would have expected that the link is not to be found or working anymore

That's also what was intended with the PR, and what I was seeing in development. I'm looking into why it wouldn't have worked on UK staging.

**Comment by Matt-Yorkley** [comment]
I've moved some bits around here so that we clear the unused payments whenever an order changes to "paid" state instead of when the order is finalized (as those two events can happen separately at different times, and for different reasons).

I've put it back in code review for now if someone wants to give it another look. Otherwise it should be ready for testing again :ok_hand:

File: engines/order_management/app/services/order_management/order/updater.rb [hunk 4]
```diff
@@ -162,6 +163,12 @@ def after_payment_update(payment)
 
       private
 
+      def cancel_payments_requiring_auth
+        return unless order.payment_state == "paid"
```
Comment (mkllnk) [inline engines/order_management/app/services/order_management/order/updater.rb:167]: This is checked above already.

**Review by mkllnk — APPROVED** [review]

File: engines/order_management/app/services/order_management/order/updater.rb (hunk 4 above)
Comment (Matt-Yorkley) [reply engines/order_management/app/services/order_management/order/updater.rb:167]: They're actually two different conditions. I could move them both down into this method, but I'd have to pass in the `last_payment_state` here, like:
```ruby
  def cancel_payments_requiring_auth(last_payment_state)
    return unless order.payment_state == "paid" && last_payment_state != "paid"
    ...
```
Would that be preferable?

Comment (mkllnk) [reply engines/order_management/app/services/order_management/order/updater.rb:167]: Ah, now I see. I overlooked `order.payment_state = infer_payment_state` in between. :see_no_evil: 

Good to go.

**Comment by filipefurtad0** [comment]
Hey @Matt-Yorkley ,

Before this PR, adding more than one Stripe payment to an order in the BO, and granting authorization to the latest one leads to this situation:

- one payment is completed / the order is paid
- a second payment requiring authorization is still visible to the customer and on Stripe dashboard 

image

**After this PR**

Two additional payments (50Eur) were created:
 
image

We can see these two payments and the previously created one (40 Eur). After authorizing the **last added payment**, the remaining payment on that order gets cancelled:

image

This is great :+1: 

However: If, on the other hand, the customer attempts to authorize the payment which was first created, then the payment fails for the customer:

image

But remains in an `uncaptured state` on stripe (see above, middle window). I think this is ok, as we've recently concluded that uncaptured payments are automatically cancelled within a few days. However, this is already the case **prior to this PR**, so I think we're good.

In any case, the payment authorization options disappear for the customer, on `account/transactions`, which is great. I'd say we're good to go. Awesome! :muscle: 


PS: It would certainly be great to be able to "clear out" payments created prior to the deployment of this PR, but this is out of scope here.

**Comment by Matt-Yorkley** [comment]
> PS: It would certainly be great to be able to "clear out" payments created prior to the deployment of this PR, but this is out of scope here.

Yeah, that might be nice. Also pretty easy. I could make a quick migration for that in a separate PR?
