### PR TITLE
Fix product with ml unit display dl

### LINKED ISSUE #11724: Products with 'mL' unit displaying as 'dL' on shopfront
## Description

Newly created products created with unit=mL are showing in backoffice as millilitre. On the shopfront, they are incorrectly showing as dL/decilitre. Older products previously created as mL are still showing mL correctly.

## Expected Behavior

Products on shopfront should display the unit selected in backoffice

## Actual Behaviour

New products with mL are converted to dL units

## Steps to Reproduce

1. Create a **new** product with millilitre unit size
2. Add product to open order cycle
3. See product converted to decilitre units on shopfront
4. See pre-existing products on shopfront correctly displaying mL

## Animated Gif/Screenshot

Backoffice:
Screenshot 2023-10-26 at 16 09 25

Shopfront:
Screenshot 2023-10-26 at 16 09 31

Unit dropdown also does not even list decilitre as an option:
Screenshot 2023-10-26 at 16 15 24

## Workaround

No workaround - decilitre does not appear in superadmin config to deselect:
Screenshot 2023-10-26 at 16 00 49

## Severity

Raising as an S2 because decilitre is an unknown unit size to majority of people and this is customer facing

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix

See message from @mkllnk in [slack](https://openfoodnetwork.slack.com/archives/CG7NJ966B/p1698099327301509?thread_ts=1698037613.112019&cid=CG7NJ966B)

### PR DESCRIPTION
**Pull request by abdellani**
#### What? Why?

- Closes #11724

#### What should we test?

In addition to the scenario described in the original issue. I highlighted some fields that require a special focus
image

image

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Comment by abdellani** [comment]
Do we want to list all the available Units on the product creation form?

image

File: spec/services/weights_and_measures_spec.rb [hunk 1]
```diff
@@ -90,4 +90,12 @@
       end
     end
   end
+
+  describe "UNITS" do
+    include Spree::Admin::GeneralSettingsHelper
+    it "should include all the available untis" do
+      units = WeightsAndMeasures::UNITS.values.flat_map(&:values).pluck("name").sort.uniq
+      expect(units).to eq(all_units.sort.uniq)
```
Comment (mkllnk) [inline spec/services/weights_and_measures_spec.rb:98]: If this is the same, shall we call `WeightsAndMeasures::UNITS.values.flat_map(&:values).pluck("name")` from `all_units`? Then we don't need to maintain two lists. We just need to make sure that the units are in the right order.

**Review by mkllnk — COMMENTED** [review]
Looking good!

> Do we want to list all the available Units on the product creation form?

I would display only the configured available units unless someone complains...

File: spec/javascripts/unit/admin/services/variant_unit_manager_spec.js.coffee [hunk 2]
```diff
@@ -23,16 +23,28 @@ describe "VariantUnitManager", ->
...
     it "returns a sorted set of scales for unit type volume", ->
-      expect(VariantUnitManager.unitScales('volume')).toEqual [0.001, 1.0, 1000.0]
+      expect(VariantUnitManager.unitScales('volume')).toEqual [0.001, 0.01, 0.1, 1.0, 4.54609, 1000.0]
 
   describe "compatibleUnitScales", ->
     it "returns a sorted set of compatible scales based on the scale and unit type provided", ->
       expect(VariantUnitManager.compatibleUnitScales(1, "weight")).toEqual [1.0, 1000.0, 1000000.0]
       expect(VariantUnitManager.compatibleUnitScales(453.6, "weight")).toEqual [28.35, 453.6]
 
+    pending "should load only available unit", ->
```
Comment (abdellani) [inline spec/javascripts/unit/admin/services/variant_unit_manager_spec.js.coffee:36]: this new test is failing.
I don't know how to update `availableUnits` before running the tests.
I tried directly assigning a new value to `VariantUnitManager.availableUnits`, but it didn't work.

File: app/assets/javascripts/admin/products/services/variant_unit_manager.js.coffee [hunk 3]
```diff
@@ -60,8 +72,13 @@ angular.module("admin.products").factory "VariantUnitManager", (availableUnits)
...
       scaleSystem = @units[unitType][scale]['system']
-      (parseFloat(scale) for scale, scaleInfo of @units[unitType] when scaleInfo['system'] == scaleSystem).sort (a, b) ->
-         a - b
+      if availableUnits
+        available = availableUnits.split(",")
+        (parseFloat(scale) for scale, scaleInfo of @units[unitType] when scaleInfo['system'] == scaleSystem and available.includes(scaleInfo['name'])).sort (a, b) ->
+          a - b
+      else
+        (parseFloat(scale) for scale, scaleInfo of @units[unitType] when scaleInfo['system'] == scaleSystem).sort (a, b) ->
+          a - b
```
Comment (dacook) [inline app/assets/javascripts/admin/products/services/variant_unit_manager.js.coffee:81]: It looks like the condition could have been included into the existing code, rather than copy to a separate branch. 
In fact, it looks like all functions in this class need to filter by available units.

I think there should be a filtered `units` list, which would probably be shared with the other functions.
But I have to admit I'm struggling with this kind of Javascript and am not sure how to refactor it!

So if you'd like to try, I'd be very thankful, but don't expect you to!

File: spec/system/admin/product_import_spec.rb [hunk 4]
```diff
@@ -53,6 +53,14 @@
 
   let(:shipping_category_id_str) { Spree::ShippingCategory.all.first.id.to_s }
 
+  let(:available_units) {
+    ["mg", "g", "kg", "T", "oz", "lb", "mL", "cL", "dL", "L", "kL", "gal"].join(",")
+  }
+
+  before do
+    Spree::Config.set_preference(:available_units, available_units)
+  end
```
Comment (dacook) [inline spec/system/admin/product_import_spec.rb]: We should actually mock the preference, so that it doesn't leak into other specs. In fact, there's and example below in this file!
It wasn't working because you used a different method for accessing the preference. I've added a commit to change this to use the more standard format (`Spree::Config.available_units`), and now `product_import_spec.rb` works without any further changes.

**Review by dacook — APPROVED** [review]
Great work! You identified an inconsistency in the app and changed it to respect the configured preferences, which is a great end result.

I noticed we can use a better way of accessing the preference, so have added a commit for this to demonstrate.
I also thought of a way to make the JS test pass and added another commit.

I think we could tidy up the JS a bit, but don't know how, so I approve of this ;)

**Review by mkllnk — APPROVED** [review]
Great improvements.

**Comment by drummer83** [comment]
Hi @abdellani,
Thanks for working on this important fix! :muscle: 

### Before staging
- previous (old) products & variants still showed ml
- edited and new variants converted volume to dl

### After staging
- New units in instance configuration settings:
  - mg (milligram) :heavy_check_mark: 
  - cl (centilitre) :heavy_check_mark: 
  - dl (decilitre) :heavy_check_mark: 
  - gal (gallon) :heavy_check_mark: 
image
- New units in instance configuration settings are inactive by default. :heavy_check_mark: 
- Previously active/inactive units are still active/inactive after staging. :heavy_check_mark: 
- Previous units in shopfront are unchanged (e.g. dl), even if the unit is inactive in configuration settings.
  - I wonder if a migration to convert dl and cl to ml would make sense? @openfoodfoundation/train-drivers-product-owners :question: 
- On order summary page and on order confirmation page only active units are being used (e.g. dl is converted to ml) :heavy_check_mark: 
image
- Edit order cycle pages needs to be checked again if the unit values of older products are converted to largest suitable unit scale and inactive units are used as well.:question: 
- On bulk edit products page only the active units are being used. :heavy_check_mark: 
- On edit product page only the active units are being used. :heavy_check_mark: 
- On product details page only active unit scales can be selected. :heavy_check_mark: 
- We again see rounding issues in the shopfront for 700 ml. :x: (out of scope here, reopened #7504)
- Error 500 in shopfront after deactivating certain unit scales (oz, ml in my case) [Bugsnag here](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/654bc14921d97100082d9fee?filters[error.status]=open&filters[event.since]=30d&filters[app.release_stage]=staging) :x:

I think we should look at the error 500 and think about a migration before merging.

Will move this back to In Dev but we're close.

Thanks again!

**Comment by abdellani** [comment]
> Error 500 in shopfront after deactivating certain unit scales (oz, ml in my case) [Bugsnag here](https://app.bugsnag.com/yaycode/openfoodnetwork-uk/errors/654bc14921d97100082d9fee?filters%5Berror.status%5D=open&filters%5Bevent.since%5D=30d&filters%5Bapp.release_stage%5D=staging) ❌


Nice catch @drummer83  :+1: 
I fixed that issue now.

Thank you

**Comment by drummer83** [comment]
@openfoodfoundation/train-drivers-product-owners

Can you please comment on the question about converting existing dl and cl to ml?

**Comment by lin-d-hop** [comment]
So only the new/edited products were updated to dl since the change?
In that case probably not so many are impacted. A migration would be good but more important to get this out fast to minimise products impacted.
Perhaps we get this out, then add a papercut for a migration and instances can choose it if it is bugging them?

File: app/services/weights_and_measures.rb [hunk 5]
```diff
@@ -45,8 +45,10 @@ def system
     }
   }.freeze
 
-  def scales_for_variant_unit
-    @scales_for_variant_unit ||= @units[@variant.product.variant_unit]&.reject { |_scale, unit_info|
+  def scales_for_variant_unit(ignore_available_units: false)
+    return @units[@variant.product.variant_unit] if ignore_available_units
+
+    @units[@variant.product.variant_unit]&.reject { |_scale, unit_info|
```
Comment (dacook) [inline app/services/weights_and_measures.rb:51]: This no longer caches the result, but I assume caching wasn't needed anyway. Even if it gets called twice, it seems like an inexpensive process.

**Review by dacook — APPROVED** [review]
A migration seems like a good idea, because we're confident that `dL` was not intended on any products. It is possible that someone might intentionally use `dL`, in which case a future migration could cause an undesired outcome. So I'd suggest it's better to choose now or never.

But it's easy to manually fix and hopefully doesn't affect too many people, so "never" is probably a reasonable option :)

**Review by mkllnk — APPROVED** [review]

**Comment by drummer83** [comment]
Hi @abdellani,

I have tested my scenarios from above again. Everything is still looking good and I couldn't reproduce the error 500 anymore. :muscle: 

One thing I need to mention: Staging failed on FR server. I assume this is because I had staged the first version of this PR on that server earlier already. It worked well on AU server.

So - I'm not merging this one because I'm not sure about the failed staging. But apart from that this PR is ready to go!

Thanks! :pray: 

Ping @filipefurtad0, since you will be drafting the release tomorrow.

**Comment by filipefurtad0** [comment]
Thanks for testing and the heads-up @drummer83.
On what the deployment concerns: We'll still go through release testing, so if there is something really nasty about it I think we would still catch it there.

I'd propose to still stage on UK-staging (doing so now), and all is well, then merge?

**Comment by filipefurtad0** [comment]
Ok, deployment was fine on staging-UK:
image

What do you recon @openfoodfoundation/developers ?

**Comment by dacook** [comment]
I just checked the logs for the fr-staging deployments and it appears to have failed due to this error during asset compilation:

```
Compiling...
Compilation failed:
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

(deprecation warnings follow..)
```

I think I've seen this before. This is certainly not related to this PR, so we're good to go 👍 

But we should pay attention to the warning. I'll give that a try..

**Comment by filipefurtad0** [comment]
Thanks @dacook ! :pray:
