### PR TITLE
Fix missed I18n translations for enterprises sells options

### LINKED ISSUE #13356: Untranslateable text for enterprise admin select field
## Description
Go to **Admin > Enterprises** (as an admin user)
The selection values in column "Sells" cannot be translated

- Raised in https://openfoodnetwork.slack.com/archives/C2GQ45KNU/p1748772593129549

## Animated Gif/Screenshot
Image

## Workaround
Admins must find out what the English text means.

## Possible Fix
Add a translation for the select field values here:
https://github.com/openfoodfoundation/openfoodnetwork/blob/master/app/views/admin/enterprises/_admin_index.html.haml#L31

Use lazy lookup so that the keys can be added under here: https://github.com/openfoodfoundation/openfoodnetwork/blob/94cb1f45a00e3e99c04d6945bfcc4917a847b7ce/config/locales/en.yml#L1514

More info about translations here: https://github.com/openfoodfoundation/openfoodnetwork/wiki/Internationalisation-(i18n)#development

### PR DESCRIPTION
**Pull request by AndreyUsyaev**
#### What? Why?

- Closes #13356 

Because of the sells options is an array inside Enterprises::SELLS, I thought it would be better to use the values as keys in our locales files. As I understood correctly other locales will be filled after Transifex find changes in en.yml file? So to test it locally you should temporarily add such translations in other locales files

#### What should we test?

- Go to Admin > Enterprises (as an admin user)
- The selectors under column "Sells" should show translated labels

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/helpers/admin/enterprises_helper.rb [hunk 1]
```diff
@@ -71,6 +71,12 @@ def enterprise_attachment_removal_panel_id
       "#{enterprise_attachment_removal_panel}_panel"
     end
 
+    def enterprise_sells_options
+      Enterprise::SELLS.map do |s|
+        [I18n.t("admin.enterprises.admin_index.sells_options.#{s}"), s]
+      end
```
Comment (mkllnk) [inline app/helpers/admin/enterprises_helper.rb]: You don't need to change it but just for future reference, you could write it like this:
```suggestion
      scope = "admin.enterprises.admin_index.sells_options"
      Enterprise::SELLS.map do |s|
        [I18n.t(s, scope:), s]
      end
```

**Review by mkllnk — APPROVED** [review]
Thank you!

**Comment by filipefurtad0** [comment]
Hey @AndreyUsyaev,

Congrats on your first PR! :bouquet: 

You're right, we could test this in staging servers by manually adding the keys and restarting the server. Mostly, we just make sure the page renders well, with other locales and then wait till it reaches production with the new keys in place.

In that sense, I've gave it a quick look:

image

Looks good for now, so let's ship this one into the next release!
