### PR TITLE
[split checkout] Fix bug preventing user from reaching payment step

### LINKED ISSUE #10479: [Split checkout] Users without shipping address are not able to reach step2 if there is only a pickup shipping method in step 1
## Description

See user info here: https://openfoodnetwork.slack.com/archives/C01V3KW8RSM/p1677251613703549?thread_ts=1677249745.577039&cid=C01V3KW8RSM

when this user tries to go to payment step, they see an error message saying they should add a shipping address. yet the only shipping method is a pickup one (no shipping address required).

couldn't reproduce on staging, couldn't reproduce with my US super admin account 🤔 

## Steps to Reproduce

1. Go to https://openfoodnetwork.net/open-food-network-usa/shop#/shop
2. Go to /cart
3. Try to go to payment step
4. See error message on shipping address

## Animated Gif/Screenshot

See videos here: 

https://openfoodnetwork.slack.com/archives/C01V3KW8RSM/p1677249745577039

## Workaround

None

## Severity
bug-s2: a non-critical feature is broken, no workaround

## Your Environment

* Version used: v4.1.25
* Browser name and version: Firefox and chrome
* Operating System and version (desktop or mobile): Windows and ubuntu

### PR DESCRIPTION
**Pull request by rioug**
When using a "pick up" shipping method, with a user who doesn't have a shipping address it was impossible to proceed to the payment step because shipping address was invalid.

To fix this, we ensure that "ship_address_same_as_billing" parameter is set to true when using a "pick up" shipping method.

#### What? Why?
- Closes #10479 

In a very specific scenario, a user can be blocked from proceeding to the payment step on checkout :
- User had no shipping address
- Shop only has a "pick up" shipping method
It this case the user will get a shipping address error when clicking on "Next - Payment Method" button as the shipping address is invalid

I am not sure how a user can end up in this scenario, I didn't get to check the affected user. As far as I can see, there is no way to delete a user/customer shipping address. I managed to reproduce the error by manually delete the customer shipping address ( see the test section below ) 
I fixed the issue by setting `ship_address_same_as_billing` to true when the selected shipping method is a "pick up" one. It's a bit hacky but it seems like the easiest solution.
Ideally we would skip validating the order's shipping address in this case, but that would mean getting rid of `accepts_nested_attributes_for :ship_address` in  `Spree::Order` which would probably cause other issue. I don't think there is a way to skip/conditionally skip validation with `accepts_nested_attributes_for`.  

Filipe did mention in this [comment](https://github.com/openfoodfoundation/openfoodnetwork/issues/9056#issuecomment-1087845901) that

>   Since we're dealing with a pick-up delivery method the hub's address should become the ship address for that order. Don't know   why this is happening

I don't if this correct or where in the code it's supposed to happen.

#### What should we test?

- Create or set up a shop with only a "pick up" shipping method
- Make sure there is an order cycle open for said shop

Shop_pick_up_shipping

- Create a new user
- Place an order with the new user
- Remove user shipping address via rails console x :
  - Load placed order:  `o = Spree::Order.find_by number: 'R313071156'`
  - Load customer `c = o.customer`, it should have a `ship_address_id`
  - Remove ship_address, 
    ```
    c.ship_address = nil
    c.save!
    ```
  - Check in back office that address has been remove properly 
  - Go to customer tab, choose shop you placed an order with , you should see "Edit" under "Shipping Address" for your use:
 
    customer_no_shipping_address

- Start an order with the new user and go to checkout
- Click on Next - Payment method -> you should be redirected to the payment step

Alternatively,  you might be able to do the following, similar to what the system spec does, I ran out of time to test that :
- Set up a shop with two shipping methods, one requiring a shipping address, and one pick up only 
- Start an order and go to checkout
- First choose the shipping method requiring an address, untick "Shipping address same as billing address?"
- Make sure the shipping address is empty
- Then choose the pick up shipping method 
- Click on Next - Payment method -> you should be redirected to the payment step

#### Release notes

Changelog Category: User facing changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by dacook — APPROVED** [review]
Hmm sounds like a tricky one. I agree, this seems like a hacky fix but it's not clear how else it could be fixed.

I was wondering if theres' any other way so jumped in to try.
I tried to clear the shipping address from the params (which I think the frontend JS should be doing), but the validation continues to execute and fail regardless
I discovered the temporary var `Order#save_ship_address`, so I tried disabling this. I think this disabled some validation, but not all.

So I can't find a better way either, I give up, and approve this fix :)

**Comment by dacook** [comment]
@jibees as you're intimately familiar with split checkout, it would be great to get your feedback.

**Review by jibees — APPROVED** [review]
As @dacook already said, this may seem a bit hacky, but it does the job. 
💪

**Comment by filipefurtad0** [comment]
Hey @rioug,
Thanks so much for all the details on how to reproduce and test :raised_hands: 

Some preliminary comments:

```

Filipe did mention in this https://github.com/openfoodfoundation/openfoodnetwork/issues/9056#issuecomment-1087845901 that

    Since we're dealing with a pick-up delivery method the hub's address should become the ship address for that order. Don't know why this is happening

I don't if this correct or where in the code it's supposed to happen.
```

I remember observing this behavior at some point, but the app has indeed changed quite a bit over time. This could be [related with this code/PR](https://github.com/openfoodfoundation/openfoodnetwork/pull/4252), although I'm not sure this is still active - I'll need to double check.

I'll proceed to test the workaround proposed in this PR.

I'm not sure though, it is strictly correct to set the shipping to the billing address of the customer, for pick up methods.

For example, for tax calculation, as we usually do this based on shipping address, with this tax setting:

`Spree::Config.set(tax_using_ship_address: true)`

I don't know how instances are set, but I assume this is the case for most -> something else for me to double check.

Looking at the userguide:
https://ofn-user-guide.gitbook.io/ofn-super-admin-guide/ofn-platform-configuration/taxes-and-tax-zones#how-zones-interact-with-tax

> Note: If the shipping method is a ‘collection’ method, the tax is based on the location of the shop. If the shipping method is a ‘delivery’ method, the tax will show according to the location of the customer (their shipping address).

So, this can lead to incorrect tax charges, in cases which the hub is located in another state (relevant for CA) or country with differing (business?) address.

**Comment by filipefurtad0** [comment]
Ok I think I've found it now:

https://github.com/openfoodfoundation/openfoodnetwork/blob/890ab6796ed87fc59eec3c99b9a773f19b330379/engines/order_management/app/services/order_management/order/updater.rb#L147-L154

And a spec here:

https://github.com/openfoodfoundation/openfoodnetwork/blob/890ab6796ed87fc59eec3c99b9a773f19b330379/engines/order_management/spec/services/order_management/order/updater_spec.rb#L147-L154

I've deleted this code snippet and ran our system test on split checkout:
`spec/system/consumer/split_checkout_spec.rb`

Indeed some tests fail, because it uses `before_save_hook`. So I don't know why it is not fetching the `shipping_address_from_distributor` in this case, but I think this would be the expected behavior.

So this seems to be the case for the legacy checkout - I did not test manually. But I guess we would need to decide whether we keep this behavior for split checkout or change it the proposal in this PR of

> ensure that "ship_address_same_as_billing" parameter is set to true when using a "pick up" shipping method.

I'll pose the question on the #split-checkout channel.

**Comment by RachL** [comment]
I feel like we should keep the same rule as legacy checkout as it looks like it has fixed the previous bug and never introduced side effects.

But if there are strong opinions that we should move forward with the current proposal, I'm following.

**Comment by mkllnk** [comment]
I agree on keeping the old behaviour and copying the distributor's address as shipping address. It's wrong to ship the delivery to the customer's home or business address when pickup is selected. The shipping address is also used for tax calculations and, while I'm no tax expert, I would expect the law of the store to be applied when picking up an order there and potentially paying in cash. This logic has worked for us so far.

**Comment by rioug** [comment]
Thanks for the feedback, I'll rework my solution

**Comment by rioug** [comment]
`shipping_address_from_distributor` mentioned by Filipe above is called here but  `updater.before_save_hook` : https://github.com/openfoodfoundation/openfoodnetwork/blob/890ab6796ed87fc59eec3c99b9a773f19b330379/app/models/spree/order.rb#L341-L365

So I think my previous solution would have worked. Anyway I reworked the solution to use the distributor address for "pick up" shipping method. It introduces a little bit of duplication as I couldn't reuse existing code, but I believe the `Order::Updater` still has the last word.

**Comment by dacook** [comment]
> So I think my previous solution would have worked. Anyway I reworked the solution to use the distributor address for "pick up" shipping method. It introduces a little bit of duplication as I couldn't reuse existing code, but I believe the `Order::Updater` still has the last word.

So it sounds like the fix here (whether the old or new solution) is simply just to get past validation. Then regardless, when the order is saved, it will copy the distributor. I wonder why this wasn't an issue with the old checkout process.

The second fix seems ideal because it is in line with the `Order::Updater` behaviour, but as you say it duplicates it. I'm wondering why you can't re-use existing code? 
It looks to me like this could be solved in the `Order` model. Could there be a `before_validation` that calls `updater.shipping_address_from_distributor`?

**Comment by rioug** [comment]
> It looks to me like this could be solved in the `Order` model. Could there be a `before_validation` that calls `updater.shipping_address_from_distributor`?

I didn't think of that, I'll give it a try. My main issue was the  `updater.shipping_address_from_distributor` requires shipping method and address data to be set.

File: app/controllers/split_checkout_controller.rb [hunk 1]
```diff
@@ -150,6 +154,31 @@ def update_order
...
   end
 
+  def use_shipping_address_from_distributor
+    @order.ship_address = @order.address_from_distributor
+
+    # Add the missing data
+    bill_address = params[:order][:bill_address_attributes]
+    @order.ship_address.firstname = bill_address[:firstname]
+    @order.ship_address.lastname = bill_address[:lastname]
+    @order.ship_address.phone = bill_address[:phone]
```
Comment (dacook) [inline app/controllers/split_checkout_controller.rb:164]: I can see that `@order.address_from_distributor` will include the name and phone number from billing address already. So I think that will pass for the validation sake.

Of course, this captures any user input that was just changed. But if `Order.updater` is overwriting it later anyway, I'm wondering if it's necessary here? Maybe we can remove this?

File: app/controllers/split_checkout_controller.rb [hunk 2]
```diff
@@ -150,6 +154,31 @@ def update_order
...
+
+    selected_shipping_method = allowed_shipping_methods.select do |sm|
+      sm.id.to_s == params[:shipping_method_id]
+    end
+
+    return nil if selected_shipping_method.empty?
+
+    selected_shipping_method.first.require_ship_address
+  end
+
```
Comment (dacook) [inline app/controllers/split_checkout_controller.rb:181]: Above, we had to test the result of this with `== false`, which at first glance looks wrong. It's because we're returning one of three values: true, false or nil. ( Usual `nil` is treated the same as false).

I'd like to see if we can encapsulate the complexity a bit more and return a simple true/false value. 
Can we get away with this suggestion I wonder? It uses the `&` operator which lets you attempt a method only if the object is present (I forget what it's called..)

```suggestion
  def shipping_method_require_ship_address
    selected_shipping_method = allowed_shipping_methods&.select do |sm|
      sm.id.to_s == params[:shipping_method_id]
    end

    selected_shipping_method&.first&.require_ship_address == true
  end

```

**Review by dacook — CHANGES_REQUESTED** [review]
Thanks for looking into that. I have one more review sorry! I wonder if we can simplify a couple of bits.

File: app/controllers/split_checkout_controller.rb [hunk 3]
```diff
@@ -188,6 +217,10 @@ def order_params
     @order_params ||= Checkout::Params.new(@order, params, spree_current_user).call
   end
 
+  def address_params
+    params[:order][:bill_address_attributes].permit(::PermittedAttributes::Address.attributes)
+  end
+
```
[the remark this answers is not in the document]
Comment (rioug) [reply app/controllers/split_checkout_controller.rb:223]: To see if you are paying attention :smile:
It's some left over from some other solution I tried that I forgot to clean up, I'll remove it.

File: app/controllers/split_checkout_controller.rb (hunk 1 above)
Comment (rioug) [reply app/controllers/split_checkout_controller.rb:164]: > Of course, this captures any user input that was just changed. But if `Order.updater` is overwriting it later anyway, I'm wondering if it's necessary here? Maybe we can remove this?

It is necessary because at the time `@order.address_from_distributor` is called annoyingly `order.bill_address` isn't set, so it's needed for `@order.ship_address` validation to pass

File: app/controllers/split_checkout_controller.rb (hunk 2 above)
Comment (rioug) [reply app/controllers/split_checkout_controller.rb:181]: I see what you are trying to do, the proposed changes doesn't quite work. Would something like this be better ?

```ruby
  def shipping_method_ship_address_not_required?
    selected_shipping_method = allowed_shipping_methods&.select do |sm|
      sm.id.to_s == params[:shipping_method_id]
    end

    return false if selected_shipping_method.empty?

    selected_shipping_method.first.require_ship_address == false
  end

```
I kept a return as a feel like something like `selected_shipping_method&.first&.require_ship_address == false` is not easy to read, it's easy to miss the use of the Safe Navigation Operator `&.`

Comment (dacook) [reply app/controllers/split_checkout_controller.rb:181]: 👍 Looks good

**Review by dacook — APPROVED** [review]
Great, thank you!

It would be good to squash the final solution down into one commit for the next reviewer.

**Review by jibees — APPROVED** [review]
I've squashed into one commit (hope this is fine). 

Thanks for this one @rioug 🙏  This looks good to me!!

**Comment by RachL** [comment]
Managed to reproduce in master with the following scenario (thanks @rioug :pray: ) :

- Set up a shop with two shipping methods, one requiring a shipping address, and one pick up only
- Start an order and go to checkout
- First choose the shipping method requiring an address, untick "Shipping address same as billing address?"
- Make sure the shipping address is empty
- Then choose the pick up shipping method

image

With the PR this scenario is fixed: I can go to payment method screen with no error + if I go back I see shipping address has been correctly field up with distributor address.

image

Marvelous 💪

**Comment by drummer83** [comment]
@RachL Great! Thanks for testing this! This bug was a mystery in the beginning and we solved it in great team work! :muscle:

Just curious: When you jumped back to the 'step 1 - details', was there a pre-selected shipping method? I believe it should still have been Pick-up and no shipping address was shown, right? In your screenshot it's not active anymore, so you switched to 'home delivery'. And then the hub address was used as shipping address? Is this really what we want? You would want your own shipping address in that case, wouldn't we?

**Comment by RachL** [comment]
> I believe it should still have been Pick-up and no shipping address was shown, right?

Yes that's what happened, I've selected the delivery method after seeing pick-up was correctly saved because I was curious to see what the system saved as a shipping address.

> You would want your own shipping address in that case, wouldn't we?

Yes but in that particular case I've removed my shipping address from the form, I don't see how we can retrieve it. Let's see if this scenario happens in real life. For now cases that came up on production were cases where there was only a pick-up method and we have no idea how the user has end up with no shipping address...

**Comment by audez** [comment]
Hi! Some users don't have shipping address because normally if you don't select "Save shipping address", no shipping address should be saved. But there's a recent bug: even if you don't check the box, the shipping address is saved (and clears out the preceding one if there already was a saved one). 

The bug occurs each time a user with no shipping address selects a pickup method (even if the shop also has a shipping method).

Steps to reproduce the prod scenario are here: https://github.com/openfoodfoundation/openfoodnetwork/issues/10479#issuecomment-1461043172
