### PR TITLE
Parse JSON to test ids separately and avoid flakiness

### LINKED ISSUE #10308: [Flaky] spec/serializers/api/admin/order_cycle_serializer_spec.rb
### What we should change and why (this is tech debt)

```
Failures:

  1) Api::Admin::OrderCycleSerializer serializes the order cycle with editable_variants_for_incoming_exchanges
     Failure/Error: expect(serializer.editable_variants_for_incoming_exchanges.to_json).to_not include order_cycle.distributors.first.id.to_s
       expected "{\"228\":[229,230],\"229\":[231,232]}" not to include "230"
     # ./spec/serializers/api/admin/order_cycle_serializer_spec.rb:24:in `block (2 levels) in <module:Admin>'
```

### Context

* https://github.com/openfoodfoundation/openfoodnetwork/actions/runs/3991500173/jobs/6846647626

Came up before:

* https://github.com/openfoodfoundation/openfoodnetwork/issues/10097

### PR DESCRIPTION
**Pull request by mkllnk**
#### What? Why?

- Closes #10308 

#### What should we test?

- Specs only

#### Release notes

Changelog Category: Technical changes

The title of the pull request will be included in the release notes.

### CODE REVIEW

**Review by rioug — APPROVED** [review]
Looks good :+1:

File: spec/serializers/api/admin/order_cycle_serializer_spec.rb [hunk 1]
```diff
@@ -18,11 +18,15 @@
   end
 
   it "serializes the order cycle with editable_variants_for_incoming_exchanges" do
-    expect(serializer.editable_variants_for_incoming_exchanges.to_json).to include order_cycle.variants.first.id.to_s
-    expect(serializer.editable_variants_for_incoming_exchanges.to_json).to_not include order_cycle.distributors.first.id.to_s
+    expect(from_json(serializer.editable_variants_for_incoming_exchanges).values.sum).to include order_cycle.variants.first.id
```
Comment (dacook) [inline spec/serializers/api/admin/order_cycle_serializer_spec.rb:21]: It took me a minute to work out why you're using `sum` here. I guess this is a quick way to test both that the ID is in there, and that it is also the only one. 
Hmm but you're still using `include` rather than `eq`, so did I get that right?

**Review by dacook — COMMENTED** [review]
I don't understand one of the lines sorry, can you explain?

File: spec/serializers/api/admin/order_cycle_serializer_spec.rb (hunk 1 above)
Comment (mkllnk) [reply spec/serializers/api/admin/order_cycle_serializer_spec.rb:21]: Maybe we need to write that better then. The values are arrays of ids. Array plus array is a new array. And then I test if the id is in that one array of variant ids.

Comment (rioug) [reply spec/serializers/api/admin/order_cycle_serializer_spec.rb:21]: I missed that somehow. I believe he is using sum to flatten the array as `values` here would return something like `[[1,2], [3,4]]` 
 I think it would be clearer to use `flatten` like this :
```ruby
expect(from_json(serializer.editable_variants_for_incoming_exchanges).values.flatten).to include order_cycle.variants.first.id
```

Comment (dacook) [reply spec/serializers/api/admin/order_cycle_serializer_spec.rb]: Thanks, not being familiar with the data structure, I find `flatten` nice and clear. 
But giving the array a variable name also helps a lot. 👍

File: spec/serializers/api/admin/order_cycle_serializer_spec.rb [hunk 2]
```diff
@@ -2,31 +2,34 @@
...
-      it "serializes the order cycle with editable_variants_for_incoming_exchanges" do
-        expect(serializer.editable_variants_for_incoming_exchanges.to_json).to include order_cycle.variants.first.id.to_s
-        expect(serializer.editable_variants_for_incoming_exchanges.to_json).to_not include order_cycle.distributors.first.id.to_s
-      end
-
-      it "serializes the order cycle with editable_variants_for_outgoing_exchanges" do
-        expect(serializer.editable_variants_for_outgoing_exchanges.to_json).to include order_cycle.variants.first.id.to_s
-      end
-    end
+describe Api::Admin::OrderCycleSerializer do
```
Comment (dacook) [inline spec/serializers/api/admin/order_cycle_serializer_spec.rb:5]: Thanks for this, and explaining why.
I see at least a couple other files that could be updated, but thankfully most are already like this. I'll look out for this in the future.

**Review by dacook — APPROVED** [review]

File: spec/serializers/api/admin/order_cycle_serializer_spec.rb (hunk 1 above)
Comment (mkllnk) [reply spec/serializers/api/admin/order_cycle_serializer_spec.rb]: I agree that `flatten` would have been better. But I don't want to add another commit just for that. Or do I? Why not.
