### PR TITLE
Prevent customers from editing shipped orders

### LINKED ISSUE #9235: Customer gets the snail when editing an order marked as 'shipped'
## Description

If a customer wants to edit an order which has been marked as shipped, the customer gets the snail. 

## Expected Behavior

The customer should not see the snail.
it shouldn't be possible to edit the shipped order.
## Actual Behaviour

The customer gets the snail.

## Steps to Reproduce

1. As a customer place an order.
2. As a shop manager capture the payment and mark the order as shipped.
3. As a customer go to your account and choose to edit the order.
4. Change the amount of an item.
5. Click Save changes.
6. See the snail.

## Animated Gif/Screenshot

Peek 2022-05-27 21-31

## Workaround

No workaround for customers.

## Severity
??? bug-s3: a feature is broken but there is a workaround
??? bug-s4: it's annoying, but you can use it

## Your Environment

* Version used: v4.1.33
* Browser name and version: Firefox 100
* Operating System and version (desktop or mobile): Ubuntu 20.04 LTS

### PR DESCRIPTION
**Pull request by murjax**
#### What? Why?

- Closes #9235 

Shipped orders are editable by customers in conditions where an enterprise allows order changes. More specifically, the quantity is editable. If a customer makes changes to an order and submits, the application throws an error and the customer sees an error page. Customers shouldn't be allowed to make changes to shipped orders.

This change prevents customers from editing shipped orders in two ways:
1. On the order confirmation page, the quantity is read only.
2. On the order history page (account -> orders tab), the order shows as past instead of open. Past orders don't have an edit link.

### Before
**Order History**
Screenshot from 2023-09-30 13-11-19

**Order Confirmation**
Screenshot from 2023-09-30 13-11-39

### After
**Order History**
Screenshot from 2023-09-30 13-12-42

**Order Confirmation**
Screenshot from 2023-09-30 13-12-03

#### What should we test?

1. Sign in as an enterprise owner.
2. Visit your enterprise's shop preferences (Enterprise -> Settings -> Shop Preferences).
3. Set "Change Orders" to "Customers Can Change" and save.
    - Screenshot from 2023-09-30 13-24-30
4. Sign in as a customer.
5. Find the shop you just updated as an owner.
6. Start a new order and complete it.
7. Visit your account page and click the orders tab.
8. Ensure the order shows under past orders.
9. Click on the order (Completed link).
10. Ensure the quantity cannot be edited.

More technically speaking, this is solved by changing adding a not yet shipped condition to `Order#changes_allowed?`. Any known pages that are impacted by this should be tested. As far as I can tell, this method is mostly used around these account pages.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

### CODE REVIEW

File: app/models/spree/order.rb [hunk 1]
```diff
@@ -225,7 +225,10 @@ def checkout_allowed?
     end
 
     def changes_allowed?
-      complete? && distributor&.allow_order_changes? && order_cycle&.open?
+      complete? &&
+        !shipped? &&
+        distributor&.allow_order_changes?.present? &&
+        order_cycle&.open?.present?
```
Comment (mkllnk) [inline app/models/spree/order.rb:231]: This is an interesting use of `present?`. I didn't know that `false.present? == false`. I would have expected it to be true.

**Review by mkllnk — APPROVED** [review]
Excellent! :star2: Thank you.

File: app/models/spree/order.rb (hunk 1 above)
Comment (murjax) [reply app/models/spree/order.rb:231]: `present?` will return `false` for "falsey" values including `false`, `nil`, empty hashes/arrays/strings, etc. I added `present?` to protect against possible nulls on these fields. This probably won't occur in reality because of database restrictions, but a null on one of these fields could make this method return `nil` instead of `false`.

Comment (dacook) [reply app/models/spree/order.rb:231]: Just to clarify, I think the `present?` is added in order to enforce  `changes_allowed?` returns a boolean (not truthy/falsey) value.

If we just want to cast a possible `nil` into `false`, how about  we wrap the whole thing with a double-bang? It adds only the needed feature and is a bit cleaner. I wonder if that would work and still pass your tests?
```ruby
        !!( complete? && ...etc )
```

**Review by dacook — COMMENTED** [review]
Great fix, thanks for figuring this one out, and double-thanks for adding the thorough specs!

I have a suggestion for tidying up the code slightly, would you like to give it a try?

File: app/models/spree/order.rb (hunk 1 above)
Comment (murjax) [reply app/models/spree/order.rb]: That's correct, `present?` was added to enforce a boolean is returned from `changes_allowed?`. I tried your suggestion with the double-bang and it works. The code has been updated and tests are passing. Thanks for suggesting this change!

**Review by dacook — APPROVED** [review]
Great!

**Comment by drummer83** [comment]
Hi @murjax,
Thanks for this nice contribution!

## Before your PR
- Even shipped orders were listed under 'Open orders'.
- They could be edited but the snail was shown when trying to save the changes.

image

## After your PR
- Previously shipped orders within the order cycle are now shown as 'Past orders'. :heavy_check_mark: 
- They can be viewed, but can't be edited. :heavy_check_mark: 
- Open orders can still be edited. :heavy_check_mark: 
- Marking an open order as 'shipped' turns it into a 'past order'. :heavy_check_mark: 
- When the order cycle closes, all open orders turn into past orders.

image

## Conclusion
This is a great improvement. Well done! I couldn't find any issues when testing your PR. 
It's ready to get merged! :rocket: 

Thanks again! :tada:
