### PR TITLE
Ensure unit_value is a number

### LINKED ISSUE #6527: Complete product range doesn't load on shop front for UK enterprise
## Description

The complete product range for this shop front is not loading.  Other shop fronts are unaffected.

Shop front: https://openfoodnetwork.org.uk/slow-food-birmingham/shop#/shop
Products get 'stuck' at 'Spring Onions' from Top Barn Harvest Shop

sfbstuckonions

Removing Top Barn Harvest products from the OC resolves the problem- all products load.

Unable to load up Top Barn Harvest Shop products in admin:

image

Could be a repeat of issue #4537

## Expected Behavior

-All products which are in stock should load on shop front
-All products should load in Admin

## Actual Behaviour

- only the first products load on shop front. all those after Spring Onions won't load
-None of Top barn harvest shop products load in admin

## Steps to Reproduce

1.
2.
3.
4.

## Severity

S1
User has customers unable to order.
Sunday evening.
User has contacted OFN UK team via WhatsApp.
Order Cycle closes tomorrow
Less than 2 weeks til Christmas.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### LINKED ISSUE #6737: missing "unit_value" validation when changing from item -> weight on /products/<product_name>/edit
## Description

Product edits made through the path `/products/<product_name>/edit` are not being validated on the `unit_value` field. This can corrupt variants, with consequences on the shopfront, product and order cycle pages, as observed in #6527, #4216, #6368 and #5234. 

Until recently, it was possible to create new variants with `unit_value = 0`. If this variant was from a product which had `variant_unit = items` and was changed into `variant_unit = weight` then a corrupt variant could be created. However:

i) a corrupt variant **would not be created** if this change was done under through the `/products` page. This pages validates the mandatory fields, and did not allow to create a weight item with `unit_value = <empty>` .

ii) a corrupt variant **would only be created** if this change was done under at `/products/<product_name>/edit` 

As I understand this, PR #6369 prevents variants to be created with an empty `unit_value`. This introduced to prevent this from happening, and automatically introduces a value (1), in these cases.

However, if variants from products with `variant_unit = items` were created with `unit_value = <empty>` **previous** to the deployment of #6369 in production, then these can still be changed from `variant_unit = items` -> `variant_unit = weight`, via ii), i.e., through `/products/<product_name>/edit` where validation for this mandatory field does occur. 

I think this might explain the reoccurrence from #6527 - ping @Matt-Yorkley @andrewpbrett 

## Expected Behavior

`unit_value` field is not being validated - cannot be empty - when product edits occur via `/products/<product_name>/edit`. 

## Actual Behaviour

`unit_value` field should be validated - cannot be empty - when product edits occur via `/products/<product_name>/edit`. 

## Steps to Reproduce

 
If you can find a product in staging with `variant_unit = items` and variants with no `unit_value` just skip to step 6.

1. Create a product with `variant_unit = items`
2. Create a variant, for this product.
3. After #6369 you need to remove the `unit_value`: log in to the server and open the SQL shell
4. UPDATE spree_variants SET "unit_value" = NULL WHERE id = <id>;
5. Go to the /products page and try switching that product from Items -> Weight: you should see the validation error:

`Saving failed. Saving failed with the following error(s): Unit value can't be blank `

6. Try the same, but under `/products/<product_name>/edit`: See that no validation occurs - at this step, **the corrupt variant is created** - the green banner should display

`Product "<product name>" has been successfully updated!`

See [testing notes](https://github.com/openfoodfoundation/openfoodnetwork/pull/6369#issuecomment-759424166) for more details.

## Animated Gif/Screenshot

validation

## Workaround

Using the `/products` page to change this type of products from items -> weight (not sure this is a workaround).

## Severity

This would prevent further occurrences from #6527, at least it would prevent some?
taking the liberty to rate this one as an S2 - ping @openfoodfoundation/train-drivers-product-owners 

## Your Environment

* Version used: v3.5.4
* Browser name and version: Firefox 84
* Operating System and version (desktop or mobile): Desktop Ubuntu 20.04

### PR DESCRIPTION
**Pull request by andrewpbrett**
#### What? Why?

Closes #6527 
Closes #6737 

This is a lighter weight approach than https://github.com/openfoodfoundation/openfoodnetwork/pull/6872; it's less guaranteed to work 100%, but I'm fairly confident that the way these variants are getting corrupted is that we're setting `unit_value` to `Float::NAN` and then the weight is getting set in the other `before_validation` method. Unless I'm missing something, this should prevent that from happening. 

#### What should we test?

More of a prod-test to keep an eye out for that bug recurring. 

#### Release notes

Fixed a bug that would cause the shopfront to not completely load.

Changelog Category: User facing changes

### CODE REVIEW

**Review by Matt-Yorkley — APPROVED** [review]

File: app/models/spree/variant.rb [hunk 1]
```diff
@@ -300,7 +300,7 @@ def destruction
     end
 
     def ensure_unit_value
-      return unless product&.variant_unit == "items" && unit_value.nil?
+      return unless (product&.variant_unit == "items" && unit_value.nil?) || unit_value&.nan?
```
Comment (mkllnk) [inline app/models/spree/variant.rb:303]: Great. We should probably add a unit test for this.

I was wondering about another approach as well: If we just add a validation then we still prevent this from happening but we might also notice (as user or in Bugsnag) where this is happening and find out the reason. The finding might be insightful. It might also be boring and we still want this code to automatically set the value. :shrug: 

A validation could be helpful anyway: https://guides.rubyonrails.org/active_record_validations.html#numericality

**Review by mkllnk — CHANGES_REQUESTED** [review]
Much nicer solution. :+1: 

I requested changes for a unit test.

File: app/models/spree/variant.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/models/spree/variant.rb:303]: I just tried out adding a validation, like so:

`validates :unit_value, numericality: true`

and then doing:
```
> p = Spree::Product.last
> v = p.variants.build
> v.unit_value = Float::NAN
> v.save
```
...returns true 🤔 
```
> v.reload
> v.unit_value
```
... returns `NaN`
```
> v.save
```
returns `false`
```
> v.errors
@messages={:unit_value=>["is not a number"]}
```
🤯

Comment (andrewpbrett) [reply app/models/spree/variant.rb:304]: Mystery aside, I added a unit test dec6d2189fd1ec443c9a038947613b4a308c8348 and also a notification to Bugsnag 5dcda317d28285da209d8a80828d794b101e2e3b if we do try to set `unit_value` to `NaN`.

Comment (mkllnk) [reply app/models/spree/variant.rb:304]: I was wondering about that. `NaN` is still a Float and therefore seen as number, apparently. I guess that we would need to do this:

```rb
validates :unit_value, numericality: { other_than: Float::NAN }
```

Anyway, your addition of Bugsnag meets our need to find the source of the problem.

**Review by mkllnk — APPROVED** [review]
Excellent. Let's get this into the release. :tada:

File: app/models/spree/variant.rb (hunk 1 above)
Comment (andrewpbrett) [reply app/models/spree/variant.rb:304]: Ah yeah that's a good use of that option. The part that was most puzzling was that it was valid at first, but then reloading and saving again made it invalid somehow... but anyway, yes, let's get this out there.

**Comment by filipefurtad0** [comment]
Awesome :muscle:
so we are getting Bugsnag notifications from attempts to set `weight` to `NaN`:

https://app.bugsnag.com/open-food-network-belgium/open-food-network-belgium/errors/603a1d404d7d6900189c414b?event_id=603a1d400072dcaa98f30000&i=sk&m=nw

This happens when a user edits a variant, and can be reproduced in staging env - see below. Notice the console response, when inserting numerical vs. string values on the respective field (weight or volume):

Peek 2021-02-27 12-06

However, the string is not accepted, and `0.001` (for a kg variant) is inserted instead - which prevents the fail cascade.

How would you suggest to follow this issue? Maybe the user should be notified through the UI, that a numerical input is required, in this case?

**Comment by andrewpbrett** [comment]
Great sleuthing, thanks @filipefurtad0! I think that new PR should address this; it warns that a numerical input is required in the UI.
