### PR TITLE
[Spree Upgrade] Fix product properties and images deletion

### LINKED ISSUE #3122: [Spree Upgrade][BackOffice] Fix features/admin/products_spec (3 broken tests)
Apart from #3018, fix features/admin/products_spec

```ruby
  36) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 as an enterprise user editing a product
      Failure/Error: select 'Permitted Supplier', from: 'product_supplier_id'
      
      Capybara::ElementNotFound:
        Unable to find visible select box "product_supplier_id" that is not disabled
      # ./spec/features/admin/products_spec.rb:141:in `block (3 levels) in <top (required)>'

  37) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 as an enterprise user deleting product properties
      Failure/Error: page.all('a.remove_fields').first.click
      
      NoMethodError:
        undefined method `click' for nil:NilClass
      # ./spec/features/admin/products_spec.rb:211:in `block (3 levels) in <top (required)>'

  38) 
    As an admin
    I want to set a supplier and distributor(s) for a product
 as an enterprise user deleting product images
      Failure/Error: defined_response.call
      
      NoMethodError:
        undefined method `admin_images_url' for #<ActionDispatch::Routing::RoutesProxy:0x007fb8577566f8>
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `call'
      # ./lib/spree/core/controller_helpers/respond_with_decorator.rb:15:in `respond_with'
      # ./lib/open_food_network/rack_request_blocker.rb:37:in `call'
      # ------------------
      # --- Caused by: ---
      # Capybara::ExpectationNotMet:
      #   expected not to find visible css "table[data-hook='images_table'] td img", found 1 match: ""
      #   ./spec/features/admin/products_spec.rb:233:in `block (3 levels) in <top (required)>'
```

### PR DESCRIPTION
**Pull request by luisramos0**
#### What? Why?

Closes #3122 

This fixes two specs:
- spec/features/admin/products_spec.rb:202 scenario "deleting product properties"
- spec/features/admin/products_spec.rb:223 scenario "deleting product images"

#### What should we test?
These specs should be green.

### CODE REVIEW

File: app/controllers/spree/admin/images_controller_decorator.rb [hunk 1]
```diff
@@ -0,0 +1,6 @@
+Spree::Admin::ImagesController.class_eval do
+  # This will make resource controller redirect correctly after deleting product images.
+  # This can be removed after upgrading to Spree 2.1.
+  # See here https://github.com/spree/spree/commit/334a011d2b8e16355e4ae77ae07cd93f7cbc8fd1
+  belongs_to 'spree/product', :find_by => :permalink
```
Comment (sauloperez) [inline app/controllers/spree/admin/images_controller_decorator.rb]: sorry, I don't understand what this line has to do with that commit. I don't even know what a `belongs_to` does in a controller. What did you find out?

Comment (luisramos0) [reply app/controllers/spree/admin/images_controller_decorator.rb]: it's how resource controller works. this is how the collection_url is build:
https://github.com/openfoodfoundation/spree/blob/2-0-stable/backend/app/controllers/spree/admin/resource_controller.rb#L242

belongs_to is used to define the parent of the resource (in terms of routes) and then collection_url will use the parent to build the path, in this case, instead of resulting in admin_images_path (it doesnt exist) it builds the path correctly by using parent admin_product_images_path. this is how I fix it here.
The fix in spree is different, somewhere in the future they create a resource_controller. location_after_destroy that image_controller can override. I think myy fix is easier, and, anyway, can be deleted when upgrading to 2.1.
