### PR TITLE
[Vouchers] Fix tax included in price amount

### LINKED ISSUE #11363: [Vouchers] For tax included in price the tax amount is not updated after applying the voucher
## Description

If tax is included in price there are two adjustments needed (see first example [here](https://github.com/openfoodfoundation/openfoodnetwork/issues/10432#issuecomment-1439402476)):
    - Reduce the order total (amount). :heavy_check_mark: 
    - Reduce the included tax. This is not happening currently, the tax included value is still calculated on the order total without the discount. :x:
image
image

## Expected Behavior

Included taxes should be calculated based on the discounted produce cost.
There should be an order adjustment to reflect this or the tax included amount in the back office should be corrected.

## Actual Behaviour

Included taxes are still calculated based on the original produce cost (without discount).
There is no order adjustment for included taxes.

## Steps to Reproduce

1. As enterprise user set up a shop with a percentage voucher and a product with included tax.
2. As customer put that product in your cart.
3. Proceed to checkout step 2.
4. Select the percentage voucher and a payment method.
5. Proceed to step 3.
6. Calculate the numbers.

## Animated Gif/Screenshot

See above.

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by rioug**
#### What? Why?

- Closes #11363 

When tax are included in price, we store the tax part of the voucher in the voucher adjustment itself. The issue is, this value isn't displayed anywhere nor is it used to display the discount tax to the customer. This PR fix this.
In the case of tax excluded from price, we store the tax part of the voucher as its own adjustment, which are both displayed to the customer and in the backoffice, so we no fix is needed there.

#### What should we test?

1. As enterprise user set up a shop with a percentage voucher and a product with included tax.
2. As customer put that product in your cart.
3. Proceed to checkout step 2.
4. Select the percentage voucher and a payment method.
5. Proceed to step 3.
6. Calculate the numbers.

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [x] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [ ] Technical changes only
- [x] Feature toggled

The title of the pull request will be included in the release notes.

#### Dependencies
Based on #11543, it will need to be merged first

### CODE REVIEW

File: app/helpers/admin/orders_helper.rb [hunk 1]
```diff
@@ -7,7 +7,17 @@ module OrdersHelper
...
+
+      if VoucherAdjustmentsService.new(order).voucher_included_tax.negative?
+        adjustment = order.voucher_adjustments.first
+        adjustments_for_display << Spree::Adjustment.new(
+          label: I18n.t("admin.orders.edit.voucher_tax_included_in_price", label: adjustment.label),
+          amount: adjustment.included_tax
+        )
+      end
+
+      adjustments_for_display
```
Comment (mkllnk) [inline app/helpers/admin/orders_helper.rb:20]: The whole `if` block could have been somewhere else, e.g. the service and then this could be simpler:
```suggestion
      voucher_service = VoucherAdjustmentsService.new(order)

      order.adjustments +
        order.all_adjustments.payment_fee.eligible +
        voucher_service.included_tax_adjustment
```

**Review by mkllnk — APPROVED** [review]

File: spec/helpers/checkout_helper_spec.rb [hunk 2]
```diff
@@ -15,12 +15,27 @@
     helper.validated_input("test", "foo", type: :email)
   end
 
-  describe "displaying the tax total for an order" do
-    let(:order) { double(:order, total_tax: 123.45, currency: 'AUD') }
+  describe "#display_checkout_tax_total" do
+    subject(:display_checkout_tax_total) { helper.display_checkout_tax_total(order) }
+
+    let(:order) { instance_double(Spree::Order, total_tax: 123.45, currency: 'AUD') }
+    let(:service) { instance_double(VoucherAdjustmentsService, voucher_included_tax: ) }
```
Comment (dacook) [inline spec/helpers/checkout_helper_spec.rb:22]: I would have set up real data and used the real VoucherAdjustmentsService. What if  the method `VoucherAdjustmentsService#voucher_included_tax` go renamed one day, or returned a different value? This test would still pass.

But maybe that's just opinion :)

If it's because the test data is complicated to set up, then maybe we need to create a factory for it?

**Review by dacook — COMMENTED** [review]
Good fix. 

I think it would be worth refactoring the helper though, what do you think?

File: spec/helpers/checkout_helper_spec.rb (hunk 2 above)
Comment (mkllnk) [reply spec/helpers/checkout_helper_spec.rb:22]: `instance_double` verifies that the methods are present. https://www.simplybusiness.co.uk/about-us/tech/2020/05/rspec-instance-doubles/

But in general I agree that mocking is to be avoided if possible.

Comment (dacook) [reply spec/helpers/checkout_helper_spec.rb:22]: Thanks, I didn't know that!

File: app/helpers/admin/orders_helper.rb [hunk 3]
```diff
@@ -7,17 +7,23 @@ module OrdersHelper
     # We exclude shipping method adjustments because they are displayed in a
     # separate table together with the order line items.
     def order_adjustments_for_display(order)
-      adjustments_for_display = order.adjustments + order.all_adjustments.payment_fee.eligible
+      order.adjustments +
+        voucher_included_tax_representations(order) +
+        order.all_adjustments.payment_fee.eligible
```
Comment (dacook) [inline app/helpers/admin/orders_helper.rb:14]: Should `voucher_included_tax_representations(order)` be the last one in the list? It looks like it was before.

**Review by dacook — CHANGES_REQUESTED** [review]
Great, thanks for doing this.

I agree that it's still confusing using a Struct. But I like how it's a bit clearer that it's not an actual adjustment, so I suggest we proceed this way.

However it looks like the adjustments for display are in the wrong order now, can you please check?

File: config/locales/en.yml [hunk 4]
```diff
@@ -974,7 +974,7 @@ en:
     orders:
       edit:
         order_sure_want_to: Are you sure you want to %{event} this order?
-        voucher_tax_included_in_price: "%{label} (tax included in price)"
+        voucher_tax_included_in_price: "%{label} (tax included in voucher)"
```
Comment (dacook) [inline config/locales/en.yml:977]: Oh and we need to update `spec/helpers/admin/orders_helper_spec.rb:49`

File: app/helpers/admin/orders_helper.rb (hunk 3 above)
Comment (mkllnk) [reply app/helpers/admin/orders_helper.rb:14]: I thought that that was looking odd. It seems clearer to me to put the voucher tax under the voucher.

File: config/locales/en.yml (hunk 4 above)
Comment (mkllnk) [reply config/locales/en.yml:977]: Done.

**Review by dacook — APPROVED** [review]
👍

**Comment by drummer83** [comment]
Hi @rioug,
Thanks for fixing this! :+1: 

I compared before and after staging and did some test shopping.

| Before | After |
| - | - |
| image | image |

Before:
image

After: 
image

Before:
image

After:
image

I have also tested:
- Checking out with multiple line items. :heavy_check_mark: 
- Shopping products excl. tax. :heavy_check_mark: 
- Using a voucher with a fixed rate. :heavy_check_mark: 

All looking good! Excellent! :tada: 
Merging! :rocket: 

Thanks again!
