### PR TITLE
Fix: record ToS acceptance during producer registration

### LINKED ISSUE #11796: Accepting the Terms of Service when registering a producer does nothing
## Description
Currently the tick box to accept the Terms of Service when registering a producer does nothing but allow to move to the next step.
As part of #11720 we are recording when the ToS has been accepted after an update, Ideally we should also record the ToS has been accepted when registering a producer.

## Expected Behavior

ToS should be recorded as accepted, no banner should show when first login in admin after registering a Producer

## Actual Behaviour

ToS is not recorded as accepted and a ToS has been updated  banner shows when first login in admin after registering a Producer

## Steps to Reproduce

1. Register a new Producer via https://openfoodnetwork.org.au/register/ and click on "I agree to the above Terms of Service" checkbox
2. As the enterprise user just created, login in admin
3. See Tos has been updated banner

## Workaround

You can just accept the ToS changes after the first login in admin 

## Severity
bug-s4: it's annoying, but you can use it

## Your Environment

* Version used:
* Browser name and version:
* Operating System and version (desktop or mobile):

## Possible Fix
The click on  "I agree to the above Terms of Service" checkbox should trigger a request to  `admin/users/:id/accept_terms_of_services`

### PR DESCRIPTION
**Pull request by gbathree**
#### What? Why?

Closes #11796

When a user completes enterprise registration and accepts the Terms of Service, `terms_of_service_accepted_at` was never being recorded on the user.

The ToS checkbox disables the Next button until checked, so any user who proceeds to create an enterprise must have accepted. We record acceptance in the enterprise `create` controller action — the natural save point, requiring no extra AJAX call or Angular code.

#### Changes

- `app/controllers/api/v0/enterprises_controller.rb` — add `record_tos_acceptance` private method called after successful enterprise save
- `spec/controllers/api/v0/enterprises_controller_spec.rb` — controller specs for both the required and not-required cases

#### What should we test?

1. Configure ToS as required (`Spree::Config.enterprises_require_tos = true`)
2. Register a new enterprise through the registration flow, accepting the ToS checkbox
3. Verify the user record has `terms_of_service_accepted_at` set after enterprise creation

#### Release notes

- [x] User facing changes

### CODE REVIEW

**Review by mkllnk — CHANGES_REQUESTED** [review]
Thank you for the contribution.

I think that it's the wrong approach though. Most of our site doesn't persist state on form change. You have to click _save_ or _next_ first. This is also adding an API endpoint on the v0 API which is deprecated and we trying to phase that out. And it adds a good chunk of AngularJS code which we are trying to replace as well.

Instead, you can only continue with the enterprise setup if you accept the terms. So when an enterprise is created this way, you can assume consent and mark the terms as accepted in the controller action.

I haven't verified if this works because I haven't looked at the code. But in theory, this should be a much easier solution with less code change.

Also, keep in mind that system specs are expensive to run. So if you can add a condition to an existing test then prefer that over adding a new example which will need to render a new page in the browser etc.

**Comment by mkllnk** [comment]
Oh, and I almost forgot: your PR template has improved a lot but it's not our PR template. I'm missing the part that tells me if you are intending to change the API or the user interface. We tag the PR accordingly which flows into our release notes.

**Comment by gbathree** [comment]
Thank you for the clear direction @mkllnk. You're right on all counts.

Refactored in the latest push:

- Removed the v0 API endpoint, Angular UserService, and ng-change hook entirely
- ToS acceptance is now recorded in `EnterprisesController#create` — the natural save point. Since the Next button is gated on the checkbox, any user who reaches enterprise creation has accepted
- Replaced the system spec with controller specs (two examples in the existing `creating an enterprise` describe block)
- Updated PR description to use the proper OFN template

**Review by rioug — APPROVED** [review]
Looks good, thanks !

File: spec/controllers/api/v0/enterprises_controller_spec.rb [hunk 1]
```diff
@@ -93,6 +93,31 @@
           api_post :create, { enterprise: new_enterprise_params, use_geocoder: "0" }
         end
       end
+
+      context "when Terms of Service acceptance is required" do
+        before { Spree::Config.enterprises_require_tos = true }
+        after { Spree::Config.enterprises_require_tos = false }
```
Comment (mkllnk) [inline spec/controllers/api/v0/enterprises_controller_spec.rb:99]: This is assuming that the value is `false` by default. This may be correct now but could change. It's better to use RSpec's mocking with `expect(Spree::Config).to receive(:enterprises_require_tos).and_return(true)` as that will never leak out of this spec context.

File: spec/controllers/api/v0/enterprises_controller_spec.rb [hunk 2]
```diff
@@ -93,6 +93,31 @@
...
+      end
+
+      context "when Terms of Service acceptance is not required" do
+        before { Spree::Config.enterprises_require_tos = false }
+
+        it "does not update terms_of_service_accepted_at" do
+          expect {
+            api_post :create, { enterprise: new_enterprise_params }
+            enterprise_owner.reload
+          }.not_to change { enterprise_owner.terms_of_service_accepted_at }
```
Comment (mkllnk) [inline spec/controllers/api/v0/enterprises_controller_spec.rb:118]: Why didn't you verify the response like above?
```
expect(response).to have_http_status :created
```

If we don't check that then the unchanged attribute could just be due to a failed request.

**Review by mkllnk — CHANGES_REQUESTED** [review]
Thank you, much better!

But I commented on two issues with the specs:

- They could leak global state if the app's config changes.
- The last test could pass even when the code is not working as expected.

File: spec/controllers/api/v0/enterprises_controller_spec.rb (hunk 1 above)
Comment (gbathree) [reply spec/controllers/api/v0/enterprises_controller_spec.rb]: Good point — switched to a stub so the config never mutates. Used `allow` instead of `expect` to keep the test focused on behavior rather than call counts, and added the same stub on the not-required context. 92866aa

File: spec/controllers/api/v0/enterprises_controller_spec.rb (hunk 2 above)
Comment (gbathree) [reply spec/controllers/api/v0/enterprises_controller_spec.rb:117]: You're right — added `expect(response).to have_http_status :created` so a failed request can't masquerade as a passing assertion. 92866aa

**Review by mkllnk — APPROVED** [review]

**Review by rioug — APPROVED** [review]

**Comment by AMEA-LYON** [comment]
Tested successfully !! Congratulations ! 🥳 🎉
