### PR TITLE
Stripe version in sync with vcr tests

### LINKED ISSUE #11746: [VCR] Append Stripe gem version to cassettes
### What we should change and why (this is tech debt)

Appending Stripe gem version to cassettes should make the tests fail - updated after discussion below.

~~We should change VCR settings so that, from time to time, cassettes are automatically re-recorded and real HTTP calls are made.~~

### Context

This came up [here](https://github.com/openfoodfoundation/openfoodnetwork/pull/11742#pullrequestreview-1707619025).

### Impact and timeline

~~Keeping it "real": making real HTTP calls from time to time may detect breaking changes on 3rd party dependencies, early on.~~ We should get automatic build failures each time we have a Stripe bump; this should remind us to re-save the cassettes for which request have to be re-ran using the latest gem.

### PR DESCRIPTION
**Pull request by filipefurtad0**
#### What? Why?

- Closes #11746 

_Where to append the Stripe gem version?_

I could not manage to append the Stripe version to the yml file or cassette name. Maybe there is a good/easy way to do it, but I could not find it... So I opted for:
- creating a separate directory with a given Stripe gem version
- set the cassette record mode to `:none`, which throws an error if there is no matching cassette

I think this follows the previous suggestion and should trigger an error each time we have a Stripe version bump.

To re-record new cassettes, we'll need to set the flag from `:none` to `:once`, I'll add this as well to the PR.

_How to achieve this?_

Here I also stumbled into issues: I'd say the correct way would be to append this to the VCR config file. So I tried changing `./spec/support/vcr_setup.rb` and, within the `VCR.configure do`, added a block as below:

```
  config.before_http_request(lambda {|r| r.uri =~ /api.stripe.com/}) do |request|
    config.default_cassette_options = { :record => :none }
    stripe_version = "Stripe-v#{Stripe::VERSION}"
    config.cassette_library_dir = "spec/fixtures/vcr_cassettes/#{stripe_version}"
  end
```

This would be perhaps a nice to have, as it should detect an HTTP request to Stripe automatically... I could not get it to work though. So, any tips on how to make this work would be appreciated! Please note that if we use `config.around_http_request` we get an error around `fibers` :shrug: :exploding_head: 

```
     VCR::Errors::AroundHTTPRequestHookError:
       Your around_http_request hook declared at /home/ffurtado/openfoodnetwork/spec/support/vcr_setup.rb:13:in `block in <main>' must call #proceed on the yielded request but did not. (actual error: FiberError: attempt to resume a terminated fiber)

```
So... in the end, I've opted to create a flag within our base_spec_helper, which does the job nicely. However, we do **need to remember** to set this flag on the respective tests, to enable the correct configuration. The advantage here is that the Stripe check is done only to the tests we wish to flag.

#### What should we test?

- Stripe cassettes should be recorder within a folder with the name of the current stripe gem version
- if the `:stripe_version` flag is set no new cassettes should be recorded
- if Stripe gem version gets updated, tests should fail
- otherwise green build

#### Release notes

Changelog Category (reviewers may add a label for the release notes):

- [ ] User facing changes
- [ ] API changes (V0, V1, DFC or Webhook)
- [x] Technical changes only
- [ ] Feature toggled

The title of the pull request will be included in the release notes.

#### Additional info to Reviewers

I've build this PR on top of a closed branch: https://github.com/openfoodfoundation/openfoodnetwork/pull/11751... For some reason the commit from this PR does not appear here - as it as been closed I guess - but I still had to delete the previously created file. This is done in 6c32c3ace40a24b727a2961d140cbf65336e6b61.

### CODE REVIEW

File: spec/base_spec_helper.rb [hunk 1]
```diff
@@ -131,6 +131,17 @@
     end
   end
 
+  # Appends Stripe gem version to VCR cassette directory with ':stripe_version' flag
+  config.around(:each, :stripe_version) do |example|
+    stripe_version = "Stripe-v#{Stripe::VERSION}"
+    VCR.configure do |c|
+      c.cassette_library_dir = "spec/fixtures/vcr_cassettes/#{stripe_version}"
+      # record: needs to be set to :once to record a new reply (cassette)
+      c.default_cassette_options = { record: :none }
```
Comment (mkllnk) [inline spec/base_spec_helper.rb:140]: Variable name `c` is okay but `vcr_config` would be better, I think.
```suggestion
    VCR.configure do |vcr_config|
      vcr_config.cassette_library_dir = "spec/fixtures/vcr_cassettes/#{stripe_version}"
      # record: needs to be set to :once to record a new reply (cassette)
      vcr_config.default_cassette_options = { record: :none }
```

And I would only set it to `:none` when we are running this on CI.
```suggestion
    VCR.configure do |vcr_config|
      vcr_config.cassette_library_dir = "spec/fixtures/vcr_cassettes/#{stripe_version}"
      # record: needs to be set to :once to record a new reply (cassette)
      vcr_config.default_cassette_options = { record: :none } if ENV["CI"]
```

File: spec/base_spec_helper.rb [hunk 2]
```diff
@@ -131,6 +131,17 @@
     end
   end
 
+  # Appends Stripe gem version to VCR cassette directory with ':stripe_version' flag
```
Comment (mkllnk) [inline spec/base_spec_helper.rb:134]:
```suggestion
  # Appends Stripe gem version to VCR cassette directory with ':stripe_version' flag
  #
  # When the stripe gem is updated, we should re-record these cassettes:
  #
  #     rm spec/fixtures/vcr_cassettes/Stripe-v* -r
  #     ./bin/rspec --tag stripe_version
```

File: spec/validators/vcr_stripe_check_spec.rb [hunk 3]
```diff
@@ -0,0 +1,21 @@
+# frozen_string_literal: true
+
+require 'spec_helper'
+
+describe 'current Stripe gem version vs Stripe VCR cassete version', :vcr, :twitter do
```
Comment (mkllnk) [inline spec/validators/vcr_stripe_check_spec.rb]: Here is where you added the spec file which you delete in the next commit. Squashing the two commits removes it from the history completely.

**Review by mkllnk — COMMENTED** [review]
Nice work! I like the solution you came up with. We will want other VCR tests that don't include stripe. So it's good to have the separate directory only for certain specs with a flag. The flag will also allow us to run only the specs that need re-recording.

I have some ideas for little improvements. And I may as well clean up the git history at the same time while nobody else reviewed this.

**Comment by mkllnk** [comment]
@filipefurtad0 I cleaned up the commit history and I added another script to make the re-recording a bit simpler. I wasn't able to do it though. Stripe tells me that I have a bogus API key even though I copied your key. Do I need your Stripe client id as well?

**Comment by mkllnk** [comment]
I think that your first idea didn't work because the cassette name has to be set before the test is executed. But the callback you defined was executed in the middle of the test when the actual request was happening. So we can't use that approach.

I'm also worried that we are not resetting the config. It may leak to other VCR specs without the tag. I don't know.

And lastly, the specs are failing, hurray! That should happen because I merged a Stripe gem update.

File: script/test-stripe-live [hunk 4]
```diff
@@ -0,0 +1,6 @@
+#!/usr/bin/env sh
+#
+# Test Stripe API integration and record new cassettes.
+
+rm spec/fixtures/vcr_cassettes/Stripe-v* -r
```
Comment (filipefurtad0) [inline script/test-stripe-live:5]: Should we add the git command to it? 
```bash
git rm spec/fixtures/vcr_cassettes/Stripe-v* -r
```

**Comment by filipefurtad0** [comment]
Great! Thanks so much @mkllnk .

> I'm also worried that we are not resetting the config. It may leak to other VCR specs without the tag. I don't know.

Hum, not sure... good to keep an eye for this one.

> Stripe tells me that I have a bogus API key even though I copied your key.

I would not think anything else is needed. I'm able to run the tests when the key is within the `.env.test.local`, or by running the request [indicated here](https://stripe.com/docs/upgrades/manage-payment-methods) in the rails console - after replacing the sample secret test mode API key by the secret key on the vault...

File: script/test-stripe-live (hunk 4 above)
Comment (mkllnk) [reply script/test-stripe-live:5]: Good idea.

**Comment by mkllnk** [comment]
> I'm able to run the tests when the key is within the .env.test.local

I got it working now. Yesterday I tried to be clever and thought that I can share the key with the development environment by placing it in the `.env.local` file. But the `.env.test` file contains a Stripe key as well and overrides it. So I really needed to put it in `.env.test.local`.

**Review by mkllnk — APPROVED** [review]

**Review by rioug — APPROVED** [review]
Looks good :+1:

**Comment by rioug** [comment]
Just going through the comment again, it looks like @mkllnk tested it ? If so I think we are good to merge this.
